### ISSUE TITLE
[FEATURE]: Longfin topspeed [Staffoverleg]

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1000]
### Contact Details

Arjen

### Beschrijf zo duidelijk mogelijk de feature

N.a.v. staffoverleg besproken dat de topsnelheid van de Longfin te snel is en dat die iets naar beneden gezet moet worden naar 280km/u maximaal wanneer full tuned.

### Wat lost deze feature op?

Te hoge onrealistische snelheid en onlogische snelheid in proportie met andere voertuigen (Longfin momenteel heeft de snelheid van een helikopter).

**Comment by niekschoemaker** [comment]
Is gefixed, verder heb ik het leunen in boten ook uitgeschakeld.
