### ISSUE TITLE
[Bug]: Inklokcirkel in Paleto Bay HB werkt niet voor de KMar

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1001]
### Contact Details

Arjen

### Wat gebeurde er?

In- en uitklokcirkel is er niet voor de KMar maar wel voor de politie rangen.

### Wat hoorde er te gebueren?

Er hoort wel een in- en uitklokcirkel te staan.

### Wat veroorzaakt de bug?

KMar job nemen in-game en naar Paleto Bay HB gaan.

### Wat de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
is aangepast. mocht dit niet het geval zijn, laat me het even weten
