### ISSUE TITLE
Telefoon nummers bellen onbekend[Bug]: 

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1002]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Als je iemand belt dan staat er geen naam meer maar ''Onbekend''

Mensen die je hebt opgeslagen en dan belt staat er onbekend, mocht je een clip willen zien dan stuur ik het je op.

### Wat hoorde er te gebueren?

Als het zou kunnen graag weer de namen terug i.p.v. onbekend.

### Wat veroorzaakt de bug?

Ik heb dit nu 3 dagen, en heb een video voor je.

### Wat de impact van deze bug?

laag

### Relevante log bestanden:
(https://www.youtube.com/watch?v=aykmZs1W8R0)

**Comment by Ljosfari** [comment]
kun je mij even een dm sturen naar Ljosfari#3575 ?

**Comment by Ljosfari** [comment]
is aangepast
