### ISSUE TITLE
[Bug]: Geen of extreem lage betaling bij hersenloze taxiritjes

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1003]
### Contact Details

Geertje123#2163

### Wat gebeurde er?

We zien dat bij langere ritten soms de uitbetaling van de rit extreem laag of 0 is. Deze bug zit er al minimaal zo'n 8 maanden in en komt regelmatig voor (vandaag al twee keer aangegeven) maar er is nooit een ticket voor aangemaakt.

Hier screenshots van wat er gebeurt:
![image](https://user-images.githubusercontent.com/93401910/150771997-eddd10d1-b81e-4ac3-8b2c-f1b59f3ef525.png)
![image](https://user-images.githubusercontent.com/93401910/150772004-b31e255a-37e9-46d1-bf60-72ff9bc6d8ff.png)

### Wat hoorde er te gebueren?

Een normale uitbetaling.

### Wat veroorzaakt de bug?

We merken dat dit op lange ritten gebeurt. Vaak boven de 8km, maar we weten niet of het aan de route ligt, of aan iets anders. We hebben nog geen route ontdekt waarbij het altijd voorkomt. Het is gewoon soms wel en soms niet.

De meest recente rit waarbij het gebeurde:
Vanaf ongeveer hier in paleto:
![image](https://user-images.githubusercontent.com/93401910/150772635-a606657d-608f-4ef0-8e5e-f7d9d08c8af9.png)

Naar ongeveer hier naast de politie:
![image](https://user-images.githubusercontent.com/93401910/150772664-b369690f-4b4f-457e-8738-1c206598e37a.png)

### Wat de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Ik kan in de code niks vinden wat dit kan veroorzaken, heb wat random fixes toegepast die het misschien fixen

**Comment by TedeaTaxi** [comment]
het is terug nu met F8 menu open 
![unknown](https://user-images.githubusercontent.com/93401910/153029639-4d650355-6f7b-4291-a2f5-bd1f316fddfb.png)

**Comment by TedeaTaxi** [comment]
@niekschoemaker helaas komt het nog steeds voor. Vandaag weer twee keer gemeld bij ons:

![image](https://user-images.githubusercontent.com/93401910/153029658-ba1b50d7-6ccf-4fdd-8081-035f3603f4c8.png)
![image](https://user-images.githubusercontent.com/93401910/153029667-efccf374-256d-4797-a58f-b7fb8659f51d.png)

**Comment by niekschoemaker** [comment]
> @niekschoemaker helaas komt het nog steeds voor. Vandaag weer twee keer gemeld bij ons:
> 
> ![image](https://user-images.githubusercontent.com/93401910/153029658-ba1b50d7-6ccf-4fdd-8081-035f3603f4c8.png)
> ![image](https://user-images.githubusercontent.com/93401910/153029667-efccf374-256d-4797-a58f-b7fb8659f51d.png)
> 

Van waar naar waar precies? En wat veroorzaakt het exact?

**Comment by TedeaTaxi** [comment]
Dit is opgelost?

**Comment by TedeaTaxi** [comment]
Net helaas weer iemand met het probleem: 
![image](https://user-images.githubusercontent.com/93401910/155180182-3006e507-77d4-4672-8399-ddf39f327bce.png)
@Ljosfari
