### ISSUE TITLE
Verandering en/of toevoeging extra witwaspunten.

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1004]
### Contact Details

Dekk#3792

### Beschrijf zo duidelijk mogelijk de feature

Het toevoegen van extra of nieuwe witwaspunten voor het witwassen van zwart geld. Het toevoegen van punten die gebruikt worden bij legale jobs zoals postnl, borent, vuilnisman etc. Door het toevoegen van punten die ook in gebruik zijn door legale jobs verdwijn je als het ware in de menigte en voelt het meer alsof je "echt" geld aan het witwassen bent. De criminaliteit is aan vernieuwing toe en om eerlijk te zijn wordt het witwassen op steeds de zelfde plek steeds saaier. Simpelweg het toevoegen van nieuwe punten zal dit al een nieuw leven in blazen en voor iedereen vernieuwend zijn. 

### Wat lost deze feature op?

Door het toevoegen van punten op plekken van legale jobs zal er nog minder gepowergamed kunnen worden. Je kan dan namelijk niet echt meer de punten herkennen die alleen gebruikt worden voor het witwassen, aangezien deze ook in gebruik zijn door de legale jobs. Natuurlijk moeten we niet alle legale job locaties toevoegen, want witwassen met berging locaties lijkt me vrijwel onhandig. Deze feature zal ook wat meer vernieuwing en spanning brengen binnen de criminaliteit.

**Comment by Ljosfari** [comment]
is aangepast
