### ISSUE TITLE
[FEATURE]: MEOS log systeem

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1005]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Log systeem voor het bijhouden van wie wat opzoekt in MEOS.

Waar het vooral om draait is dat agenten nu random mensen kunnen opzoeken, bijvoorbeeld als ze willen weten of hun vriend een signalering heeft om dat zo door te geven etc. Als we dat soort meldingen krijgen, kunnen we dat niet echt nakijken. Ook voertuigen op gestolen zetten, van gestolen af halen etc.

Dit alleen inzichtbaar maken voor de rangen met een gebruikersaccount.

**Comment by Chang-nl** [comment]
@niekschoemaker Zou je hier naar willen kijken of kunnen reageren, alvast bedankt!

**Comment by Chang-nl** [comment]
Helaas weegt de enorme arbeid om dit goed werkend te krijgen niet op tegen de voordelen hiervan. Indien je vragen hebt omtrent logs kun je hiervoor Misstake contacteren.
