### ISSUE TITLE
[Bug]: /tpb

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1007]
Toevoegen van /tpw [ID] [Locatie] en /tpwaypoint [ID] [Locatie]. Vervangend voor F5 -> teleport to waypoint. 
Momenteel is het zo dat je als helper best lang aan het zoeken bent voor een specifiek ID. Op deze manier kun je als helper mensen veel sneller teleporteren naar bv berging.

**Comment by AdventurePandah** [comment]
Toevoeging hierop aangezien het op [Bug]: /tpb staat. Zodra je iemand via EasyAdmin teleport naar een waypoint, reset je eigen /tpb.
