### ISSUE TITLE
[FEATURE]: Command voor het uitlezen van iemand anders zijn portonummer [Staffoverleg]

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1008]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een command of andere manier om iemand zijn portonummer uit te kunnen lezen, bijvoorbeeld vergelijkbaar met /request_search.
_(Is van staffoverleg 12/27 maar was toen geen github issue voor aangemaakt)_

### Wat lost deze feature op?

Dat mensen niet meer kunnen liegen over welke portofrequentie ze gebruiken (powergamen).

**Comment by Chang-nl** [comment]
Dit is toegevoegd na de eerstvolgende restart!
