### ISSUE TITLE
Touran Kmar

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1010]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

De rode balk op de kmar auto (touran) waar je stopsein mee moet geven in de touran doet het niet

en hij gaat max 225 waarmee je al een busje en vrachtwagen kan volgen dus zou dat iets omhoog kunnen.

### Wat hoorde er te gebueren?

De touran heeft nu geheel geen stopteken dus dat is erg lastig met staande houdingen.

De snelheid is echt te traag om normaal in achtervolging te kunnen gaan 225 max is genoeg voor vrachtwagens en busjes

dirtmap moet aangepast worden - voor auto developers

**Comment by Ljosfari** [comment]
Gebeurt random, bug van de stopsign is niet altijd.

**Comment by Daanvl1** [comment]
Was je auto en het stopbord werkt

**Comment by Ljosfari** [comment]
dirtmap moet aangepast worden - voor auto developers

**Comment by TDA-SanderD** [comment]
Dit geldt trouwens ook voor de touran van de politie.

**Comment by Lorenzo3001** [comment]
@FreddyKrueger2021 Is dit nog steeds zo? Bij mij werkt het stopbord gewoon ook als het voertuig vies is.

![image](https://user-images.githubusercontent.com/93911282/159256679-54a07050-c0f9-4f1f-954c-2c3b7d91d78e.png)
