### ISSUE TITLE
[Bug]: Taxi factuur systeem

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1011]
### Contact Details

Endorsite#0001

### Wat gebeurde er?
![chrome_7VGKROQWFh](https://user-images.githubusercontent.com/93401910/151664548-ce64a588-07b0-405d-8caf-6bfccb9b62eb.png)
![chrome_WgOALOAgvX](https://user-images.githubusercontent.com/93401910/151664549-668940b0-6545-4d56-ba02-c5807645b98c.png)

mijn collega heeft een klant opgehaald en naar een tankstation gereden 
vervolgens een factuur gestuurd van 631 euro maar klant krijgt een factuur van 472 euro 

hier door lopen we geld mis en missen we omzet waardoor de taxi geld kluis minder snel stijgt 

factuur gestuurd op 29-1-2022 om 14:44 ~~ish

[https://www.youtube.com/watch?v=UI9D0tSfnhE](https://www.youtube.com/watch?v=UI9D0tSfnhE)

### Wat hoorde er te gebueren?

als je een factuur stuurt van 631 euro dan hoort dat volledige bedrag ook als factuur binnen te komen 

### Wat veroorzaakt de bug?

als je een factuur stuurt hoort die het juiste bedrag te krijgen dit is niet het geval

### Wat de impact van deze bug?

hoog

### Relevante log bestanden

Geen log- zie video

**Comment by Ljosfari** [comment]
Is dit meerdere malen voorgevallen of alleen deze ene keer ?

**Comment by niekschoemaker** [comment]
Is gefixed
