### ISSUE TITLE
[Bug]: offroad rijden

### ISSUE THREAD

**Issue by Taker1987** [Tedeapolis/development#1013]
### Contact Details

Mart

### Wat gebeurde er?

ik had gister avond de admincar en op het zand / offroad blijkt deze te haperen , alsof je brandstof leeg is .. (glitchend heen en weer gaan ) 

nu komt er net een report binnen van iemand die excact het zelfde heeft maar dan met een normaal offroad voertuig ..

er lijkt dus een bug te zitten in het offroad rijden 

### Wat hoorde er te gebueren?

normaal offroad kunnen rijden

**Comment by Ljosfari** [comment]
Zijn we van op de hoogte. Zie Issue #996.
Ik ga deze sluiten en de extra info daarbij toevoegen.
