### ISSUE TITLE
[FEATURE]: Zeilboot toevoegen aan boten winkel

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1014]
### Contact Details

Hellfire a.k.a. mister anticheat

### Beschrijf zo duidelijk mogelijk de feature

De zeilboot : marquis (gta model) toevoegen aan de botenwinkel

### Wat lost deze feature op?

Extra boot voor leuke rp's :)

**Comment by niekschoemaker** [comment]
Done
