### ISSUE TITLE
Mijnwerker Lockers en Brood Bakkerij andere locatie.

### ISSUE THREAD

**Issue by RonaldDaquila** [Tedeapolis/development#1015]
### Contact Details

Daniël#4568

### Beschrijf zo duidelijk mogelijk de feature

Op het moment liggen deze twee punten op dezelfde locatie. Dat betekend dat daar best wel veel chaos ontstaat, aangezien hier nu twee UWV jobs door elkaar kruizen. 

Hier de screenshots: 
Bakker: https://gyazo.com/848a1961ed00602e6bb112c09f5b29c4
Mijnwerker: https://gyazo.com/1eae7691355c4161afa9f88ac115ba3b

### Wat lost deze feature op?

Wanneer ze beide op een andere locatie zitten, wordt de drukte beperkt.

**Comment by Ljosfari** [comment]
Is al aangepast
