### ISSUE TITLE
Sleepwagen kunnen geen voertuigen op gezet worden als die vol zitten met drugs enz

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1017]
### Contact Details

[TDA] Freddy K#1026

### Kenteken van voertuig

Sleepwagen politie/kmar

### Voertuig model

Sleepwagen

### Omschrijf de bug

Vanuit de kmar/politie de vraag of voertuigen met inhoud gewoon vervoerd kunnen worden naar HB

### Normaal gedrag

Lijkt mij toch dat een voertuig incl inhoud gewoon op de sleepwagen moet kunnen?

**Comment by niekschoemaker** [comment]
Is gefixed
