### ISSUE TITLE
[Bug]: mijnen aantal plekken

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1018]
### Wat gebeurde er?

Als je gaat mijnen kan dit maar met max 5 mensen. 1 per locatie. Er staat : er is een speler te dicht bij jou.

Kunnen hier meer locaties bij ?

### Relevante log bestanden

![unknown](https://user-images.githubusercontent.com/97713942/151719942-33accb6b-8ded-4c8a-97fa-39dc2fcc06e9.png)

**Comment by Willem-Dekker** [comment]
Graag coordinaten hier voor

**Comment by Ljosfari** [comment]
2983.03, 2750.90, 43.02
