### ISSUE TITLE
Kan dit worden aangepast bij de ANWB?

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#102]
- [x] De spelling van de rank: “Stagair” moet in-game aangepast worden naar “Stagiair”.
- [ ] Graag een pinautomaat bij de garage naast de ANWB. 
- [ ] Het kopen/pakken van een volle Jerrycan bij de ANWB werkt niet (  je krijgt de jerrycan niet in je inventory).
- [x] De "uren registratie overheid banen" voor de ANWB in Discord klopt niet. De tijden lopen daar 2 uur achter.
- [x] De spelling van de rank: “Technische Specialist” / “Technische Specialist in Opleiding” moet in-game aangepast worden naar “Technisch Specialist” / “Technisch Specialist in Opleiding”
- [x]  /repareer kunnen doen als er minder dan 3 ANWB aanwezig zijn.

**Comment by Willem-Dekker** [comment]
> Graag een pinautomaat bij de garage naast de ANWB.

Niet nodig aangezien dit een hidden garage is en hier geen pinautomaat bij komt
