### ISSUE TITLE
[Bug]: permradio kapoet

### ISSUE THREAD

**Issue by kerrieeee** [Tedeapolis/development#1021]
### Contact Details

Kerrie#1003

### Wat gebeurde er?

wanneer je /permradio doet gaat de radio niet aan. er is geen console melding.

### Wat hoorde er te gebueren?

de radio hoort aan te gaan

### Wat veroorzaakt de bug?

t + /permradio

### Frequentie van bug

Altijd

### Wat de impact van deze bug?

laag

### Relevante log bestanden

zijn er niet want er komt niets in de console

**Comment by niekschoemaker** [comment]
Zou weer moeten werken

**Comment by niekschoemaker** [comment]
Bedankt voor t melden, want paar dagen later en k zou alle config hiervan kwijt zijn, want had dit over gezet naar andere server
