### ISSUE TITLE
[BUG]: Helikopter kun je soms niet vol tanken

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1022]
### Contact Details

Arjen#0001

### Kenteken van voertuig

N.v.t.

### Voertuig model

annihilator3

### Omschrijf de bug

Wanneer de tank van deze helikopter boven de 50% is kun je deze niet voltanken. Pas wanneer je onder de 50% zit krijg je weer de optie om te tanken. Dan kun je wanneer deze 49% is dus wel weer voltanken tot boven de 50%.
![image](https://user-images.githubusercontent.com/92899337/151817272-763ccffd-9fee-4279-a241-252291572588.png)
![image](https://user-images.githubusercontent.com/92899337/151817288-daf6ad4a-667e-4ce5-9e8a-707912b87a2f.png)

### Repro

Pak de helikopter, vlieg een klein stukje zodat de tank een beetje verbruikt wordt (houd 'm boven de 50%) en probeer dan te tanken.

### Normaal gedrag

Normaal hoor je de tank van een voertuig altijd volledig vol te kunnen tanken.

**Comment by Ljosfari** [comment]
Heb je voor mij het kenteken van het voertuig ?

**Comment by ARJ3N** [comment]
Het kenteken voor dit specifieke voertuig van de foto is BIL 175. Maar dit heb ik bij elk voertuig van dat model, niet alleen bij dat specifieke kenteken. @Ljosfari

**Comment by niekschoemaker** [comment]
Is gefixed
