### ISSUE TITLE
[Bug]: Role bot in overheid discord 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1024]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

![image](https://user-images.githubusercontent.com/93401910/151875635-a8b78b75-5a50-48d2-a142-185391df0efe.png)

Bot role helemaal even terug fixen het is nu raar kapot gemaakt 

een Teigenaar moet alle rollen kunnen geven en afnemen inc zijn eigen eigenaar role 
een 

@TAXI EIGENAAR       moet alle rollen kunnen geven en afnemen (+ EIGENAAR)
@TAXI BAAS               moet alle rollen kunnen geven en afnemen (-EIGENAAR)
@TAXI TEAMLEIDER   moet alle rollen kunnen geven en afnemen (-EIGENAAR & -BAAS)
@TAXI RECRUITERS    moet alle rollen kunnen geven en afnemen (-EIGENAAR & -BAAS & -TEAMLEIDER )
@TAXI MARKETING    moet alleen de rolle MARKETING kunnen geven en afnemen
@TAXI                         moet GEEN kunnen geven en afnemen

### Wat hoorde er te gebueren?

ik hoopte als eigenaar dit wel te kunnen doen

### Wat veroorzaakt de bug?

geen rechten 

### Frequentie van bug

Altijd

### Relevante log bestanden

NVT

**Comment by niekschoemaker** [comment]
> ### Contact Details
> 
> Endorsite#0001
> ### Wat gebeurde er?
> 
> ![image](https://user-images.githubusercontent.com/93401910/151875635-a8b78b75-5a50-48d2-a142-185391df0efe.png)
> 
> Bot role helemaal even terug fixen het is nu raar kapot gemaakt
> 
> een Teigenaar moet alle rollen kunnen geven en afnemen inc zijn eigen eigenaar role een
> 
> @Taxi EIGENAAR moet alle rollen kunnen geven en afnemen (+ EIGENAAR) @Taxi BAAS moet alle rollen kunnen geven en afnemen (-EIGENAAR) @Taxi TEAMLEIDER moet alle rollen kunnen geven en afnemen (-EIGENAAR & -BAAS) @Taxi RECRUITERS moet alle rollen kunnen geven en afnemen (-EIGENAAR & -BAAS & -TEAMLEIDER ) @Taxi MARKETING moet alleen de rolle MARKETING kunnen geven en afnemen @Taxi moet GEEN kunnen geven en afnemen
> ### Wat hoorde er te gebueren?
> 
> ik hoopte als eigenaar dit wel te kunnen doen
> ### Wat veroorzaakt de bug?
> 
> geen rechten
> ### Frequentie van bug
> 
> Altijd
> ### Wat de impact van deze bug?
> 
> _No response_
> ### Relevante log bestanden
> 
> NVT

Ik zie vorige keer ook al, je kunt niet je eigen rang geven of weghalen, dit om problemen te voorkomen, deze rollen moet je alsnog aanvragen.

**Comment by niekschoemaker** [comment]
Zijn er naast die rollen nog problemen met de rollen? Want een eigen rol weghalen wil ik simpelweg niet toevoegen zoals ik dus al eerder aangegeven had.

**Comment by TedeaTaxi** [comment]
![image](https://user-images.githubusercontent.com/93401910/151889571-654f35eb-99e5-48b5-b561-628d59b422cf.png)
we hebben mensen die hebben meerdere rangen maar zijn ook manager hun moeten wel iemand van marketing en recruiter kunnen managen 

bij ons is het niet zo strak als bij de politie onze hiërarchie loopt nog best door elkaar heen waardoor het dus kan voor komen dat een manager ontslag neemt en een andere manager zijn ontslag verwerkt

**Comment by niekschoemaker** [comment]
Is gefixed zou nu goed moeten zijn, heb alleen niet de rechten gegeven om je eigen rollen te behren.
