### ISSUE TITLE
[Burgerraad][Bug]: GUI terug wisselen met porto

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1026]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

![image](https://user-images.githubusercontent.com/93401910/152043407-00d41255-a0cf-4fe9-a4cd-604c7cce8ad7.png)
De text van portofoon staat nu Voor je inventaris
vroeger stond het achter je inventaris zie foto 

### Wat hoorde er te gebueren?

inventaris voorrang geven op portofoon 

### Wat veroorzaakt de bug?

sinds een tijdje is het omgedraaid

### Frequentie van bug

Altijd

### Wat de impact van deze bug?

hoog

### Relevante log bestanden

geen log is een update geweest ?

**Comment by niekschoemaker** [comment]
Dit is waarschijnlijk 1 dag lang geweest omdat ik de plugin heb gerestart.
