### ISSUE TITLE
[Bug]: Mumble problemen

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1033]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Regelmatig het wegvallen van de voice. Dan mumble reconnect dan werkt het weer even.
Krijg regelmatig meldingen dat mensen niet verstaanbaar zijn en last hebben van problemen met voice.

### Wat hoorde er te gebueren?

Je praat wel in animatie maar ze horen je niet.
Dit is sinds 1/2 dagen

### Wat veroorzaakt de bug?

NVT.

### Frequentie van bug

Meerdere keren per dag

### Wat de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Als het goed is zijn deze problemen ondertussen opgelost? Graag even terugkoppelen of het nog steeds een probleem is.

**Comment by TDALionskull** [comment]
Ik heb geen last meer gehad van mumble problemen. 
Heb vandaag nog geen mumble_reconnect hoeven doen.

**Comment by niekschoemaker** [comment]
> Ik heb geen last meer gehad van mumble problemen. Heb vandaag nog geen mumble_reconnect hoeven doen.

Dan sluit ik hem bij deze, de issue, als het weer voorkomt hoor k het graag
