### ISSUE TITLE
[Bug]: FPS drops/desync issues

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1034]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Er zijn veel problemen met FPS drops in de stad. Op sommige plaatsen blijven veel mensen hangen langer als 2 seconde.

Desync probleem dat auto's terug teleporteren.

https://gyazo.com/d15b43d639defeff73126cf9c11aa5c0 

Voorbeeld van het probleem

### Wat hoorde er te gebueren?

Hopen dat het weer hersteld kan worden.

### Wat veroorzaakt de bug?

NVT

### Frequentie van bug

Meerdere keren per dag

### Wat de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
ja ehh, hoe hij daar dood gaat daar kunnen wij niks aan veranderen helaas.
