### ISSUE TITLE
[FEATURE]: MK2 Wapens voor criminelen

### ISSUE THREAD

**Issue by niekschoemaker** [Tedeapolis/development#1036]
### Beschrijf zo duidelijk mogelijk de feature

- [x] Wapens balancen
- [x] Wapen toevoegen
- [x] Ammo types dubbel checken en hiervoor refills toevoegen
- [x] Alle attachements checken en toevoegen

### Wat lost deze feature op?

Meer variatie in wapens.

**Comment by timfloors** [comment]
Voorstel, wapen Toevoegingen

- weapon_assaultrifle_mk2
- weapon_smg_mk2
- weapon_dbshotgun
- weapon_gusenberg
- weapon_revolver_mk2
- weapon_heavypistol

**Comment by Attomn** [comment]
weapon_assaultrifle_mk2 = Zit er al in
weapon_smg_mk2 = lijkt me een goede, mogelijk een ander model dan de SMG_MK2, namelijk deze gebruiken als replace? https://www.markomods.com/product/miniuzi/
weapon_dbshotgun = we hebben al een goede shotgun, neh.
weapon_gusenberg = Lijkt me een goede mits het een hoge recoil krijgt.
weapon_revolver_mk2 = krijg ik niet eens ingespawned dus wordt 'm niet.
weapon_heavypistol = Mehh, twijfelachtig, leuk dat er een red-dot sight op zit.

**Comment by Chang-nl** [comment]
Hey @niekschoemaker, hoe staat het met deze issue?
