### ISSUE TITLE
[FEATURE]: addFromTrunk optie toevoegen aan politie opslag op -1 garage

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1037]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Optie voor politie om de kofferbakinhoud in één keer te kunnen legen in de politieopslag, vergelijkbaar met hoe je de kofferbak kan uitladen in een loods. Dit zou dus enkel bij de opslag op de -1 garage zijn, dus onderaan bij de parkeerplaats bij HB, naast de rode cirkel om een auto in beslag te nemen.

### Wat lost deze feature op?

Is stukken handiger voor het uitladen van een voertuig wat bijvoorbeeld in beslag genomen moet worden, met name bij hele grote aantallen van in beslag genomen goederen.

**Comment by Chang-nl** [comment]
Deze feature is toegevoegd na de herstart!
