### ISSUE TITLE
Safezone bij pier verkleinen tot aan waar geen auto's mogen rijden

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1040]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment is de gehele pier tot aan de weg en delen strand een safezone, dit graag verkleinen tot alleen het gebied waar geen auto's mogen rijden/komen

### Wat lost deze feature op?

Roleplay kan buiten dat gebied dus wel gewoon gedaan worden

**Comment by Ljosfari** [comment]
safezone staat nog niet goed, zie mijn prachtige tekening voor info > rood is geen safezone, blauw wel safezone
![Schermafbeelding 2022-02-14 021651](https://user-images.githubusercontent.com/97713942/153784734-5a0d138b-be08-4f64-a2c8-1ab12a1b17ee.png)
