### ISSUE TITLE
Toevoegen van nieuwe wapens voor criminelen met rotatiesysteem voor afwisseling oude/nieuwe wapens

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1041]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

1. - Nieuwe soorten wapens voor Criminelen
Thread samenvatting:
Micro SMG, Pistol .50, Assault Rifle MK2 oftewel AK-15, Variant SMG MK2
Besproken:
Wapens er ook uit halen: M19-11 , normale SMG en deze vervangen door anderen, om er variatie in te houden. Roulatie ervan maken eventueel afwisseling.

### Wat lost deze feature op?

Meer afwisseling in wapens voor criminelen

**Comment by TDA-SanderD** [comment]
@FreddyKrueger2021 dit staat al vermeld in #1036. Deze kun je dus eigenlijk sluiten. ;)

**Comment by Ljosfari** [comment]
duplicate
