### ISSUE TITLE
Thermiet aanpassen zodat het vaker kan falen, deuren gevangenis en celdeuren moeilijker maken om open te breken

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1042]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

2. Gevangenis uitbraken:
- Gevangenis uitbraken.
Het gaat mij erom dat er meer risico aangebonden wordt. Zoals het op zak moeten hebben van een vuurwapen of kans dat je thermiet faalt. Dit omdat de laatste tijd iedereen wordt uitgebroken en er geen risico aan zit. Wat iedereen doet is een heli in de binnenplaats landen 3 deurtjes open branden en je bent weg.
Thread samenvatting:
Er ligt al een plan bij hoge raad voor goedkeuring (Chrushers C.): meer interactie, minder uitbraken, meer bewaking.
Toch hogere moeilijkheid, zodat dit meer tijd in beslag neemt en ook K-mar/politie aanrijdend kunnen komen?

Er worden aanpassingen gedaan aan thermiet en het falen ervan, de moeilijkheidsgraad voor het openbreken van deuren gaat omhoog en dit geeft eenheden meer tijd om aan te koppelen. Ook moet de Kmar actiever bij de gevangenis gaan posten en hier de boel in de gaten houden aangezien dit ook bij hun basistaken hoort

### Wat lost deze feature op?

Moeilijker om mensen uit te breken met hopelijk meer en betere rp

**Comment by TDA-SanderD** [comment]
@FreddyKrueger2021 het gedeelte van thermiet is al toegevoegd en daar gaat de issue over voor zover ik lees. 

![image](https://user-images.githubusercontent.com/71287080/152865066-8b80aaf2-4ba4-4d79-81a3-1c2b93094507.png)

Volgens mij kan hij dus dicht?
