### ISSUE TITLE
[FEATURE]: Kvk inschrijf formulier in /docu

### ISSUE THREAD

**Issue by LM-666** [Tedeapolis/development#1043]
### Contact Details

Luci#3010

### Beschrijf zo duidelijk mogelijk de feature

**kvk inschrijf formulier in /docu**

-In dit formulier moet een kopje 'bedrijfsnaam' komen te staan voor het naam van het bedrijf.
-ook een kopje voor het kvk nummer.
-een kopje voor soort onderneming (garage, detail handel etc).
-korte omschrijving omtrent werkzaamheden.
-kopje voor functionarissen (3 regels voor naam en geboortedata).
-vrij text veld voor voorwaarden.
-eventueel vestigingsadres.

**Volgorde**

regel 1. Bedrijfsnaam en kvk-nummer
regel 2. Soort onderneming en functionarissen
regel 3. omschrijving werkzaamheden en eventueel vestigings adres
overig. Vrij textveld 

Dit is in samenhang met de nieuwe kvk wetten en de rol binnen Justitie.

**Comment by Willem-Dekker** [comment]
zit er in na restart
