### ISSUE TITLE
Auto's die uit gele of groene cirkel komen nog als dupes eruit

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1044]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

Als je een auto uit de groene of gele cirkel wil halen duurt het soms best lang voordat ie eruit komt, ook komt het voor dat je dan helemaal niet in je voertuig word gezet en dat er dan een geduped voortuig uitkomt waar ook al je bezittingen inzitten

### Wat hoorde er te gebueren?

Normaal hoor je gewoon je voertuig te kunnen pakken en niet dat er dan een dupe en je eigen voertuig uitkomt waardoor er veel meer voertuigen in de stad staan

### Wat veroorzaakt de bug?

Ik heb werkelijk geen idee, kon niets uit logs halen als errors

### Frequentie van bug

Meerdere keren per dag

### Wat de impact van deze bug?

hoog

**Comment by Ljosfari** [comment]
Fix heeft niet gewerkt

**Comment by Chang-nl** [comment]
Is hier al meer duidelijkheid over of een video waarin deze issue zich voordoet met de f8 console open.
