### ISSUE TITLE
[FEATURE]: Nieuwe ambu facturen

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1045]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Nieuwe lijst met ambu facturen

Stuur me even een dm voor het bestand met de lijst

**Comment by Ljosfari** [comment]
[Facturen_AMBU.ods](https://github.com/Tedeapolis/development/files/8022976/Facturen_AMBU.ods)

**Comment by niekschoemaker** [comment]
Zit erin
