### ISSUE TITLE
Deepweb streamermode

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1046]
### Contact Details

Devv#4532

### Wat gebeurde er?

Er was een nieuwe update betreft “bijnamen” van deepweb kanalen voor streamers als je de deepweb opent.

echter als er een bericht binnen komt staat er links onderin : “ nieuw bericht in deepweb”
hierdoor weten ze niet over welke het gaat.

mogelijk dat de bijnaam ook gezien kan worden linksonder als melding?

### Wat hoorde er te gebeuren?

Zorgen dat je ipv “nieuw bericht in deepweb”

dat er bijvoorbeeld als de bijnaam pannekoek is
“Nieuw bericht in pannekoek”

### Wat veroorzaakt de bug?

Zo loop je onnodig te zoeken in deepwebs waar je een melding van kreeg

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

**Comment by niekschoemaker** [comment]
Zit erin na restart
