### ISSUE TITLE
[FEATURE]: Recherche jobs toegang geven tot porto 118

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1047]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kunnen de DSI en Korpsleiding rangen als enige in de in-game porto 118, zodat ze daar een afgesloten porto hebben indien nodig. Graag zouden wij recherche jobs hier ook aan toe willen voegen.

### Wat lost deze feature op?

Betere samenwerking mogelijkheden tussen de neventaken.

**Comment by niekschoemaker** [comment]
Zit erin
