### ISSUE TITLE
[BUG]: HRB G-Klasse rode gloed

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#1048]
### Contact Details

HRB G-Wagon

### Voertuig model

HRB G-Wagon

### Omschrijf de bug

Sinds vandaag is de kleur van de HRB G-Wagon in eens met een rode gloed. Zou hier misschien naar gekeken kunnen worden. Deze hoort zwart te zijn.

- naam voertuig: HRB G-Wagon
- Spawn Code: gclas9

Zie ook bijgevoegde printscreens.

### Normaal gedrag

![Gwagon](https://user-images.githubusercontent.com/90619128/153047068-bc52f993-a4bc-4085-b643-72daa63f9e44.jpg)
![Gwagon 2](https://user-images.githubusercontent.com/90619128/153047076-00d639a5-7b79-4711-8dbf-be8749f38de5.png)

**Comment by niekschoemaker** [comment]
Dit is geen feature, en gelieve volgende keer ook een titel invullen

**Comment by Lorenzo3001** [comment]
Zou samen met nog een paar andere problemen die ik gevonden heb na de restart opgelost moeten zijn.
