### ISSUE TITLE
[Bug]: /reportslisted

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#1049]
### Contact Details

AntonMoskvin#3144

### Wat gebeurde er?

Als je /reportslisted doet en dan op een report klikt en deze wilt verwijderen dan brengt die je terug naar alle main reports en kan je niet meer je muis gebruiken. Ook word de report niet verwijderd

**Geen Bug Wel een Request**

Wellicht het zo maken dat als iemand zijn report meer dan een half uur geleden is deze automatisch word verwijderd anders staat het heeeel erg vol

### Wat hoorde er te gebeuren?

De report hoort verwijderd te worden en je hoort je muis te kunnen gebruiken

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Na restart opgelost, bedankt voor het melden!
