### ISSUE TITLE
Mensen kunnen doorschieten in de animatie van boeien / taser 

### ISSUE THREAD

**Issue by SvenKeppel** [Tedeapolis/development#105]
Heyhey . Kreeg een report dat er doorgeschoten werd terwijl mensen in de animatie  zaten van boeien .  Ik heb een screenshot in t staff overleg geplaatst.  het lijkt erop als je inzoomt dat je dan gewoon kan schieten.

**Comment by Willem-Dekker** [comment]
Wie kan er schieten?
agent of boefje?

**Comment by SvenKeppel** [comment]
Op zo 23 aug. 2020 om 20:43 schreef Willem Dekker <notifications@github.com>

>
>
> Wie kan er schieten?
>
>
> agent of boefje?
>

Boefje willem en het is met de animatie van boeien van de politie

**Comment by SvenKeppel** [comment]
Op za 22 aug. 2020 om 13:43 schreef Strix <notifications@github.com>

**Comment by Willem-Dekker** [comment]
kan nu niet meer
