### ISSUE TITLE
[Bug]: Dames kleding is gebugged.

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1050]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

Er zijn verschillende dames torso's gebugged.

Ik kom straks even concreet met welke kledingstukken qua nummers dit zijn.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Het lijkt hier te gaan om nummers welke niet meer bestaan 🤔

**Comment by niekschoemaker** [comment]
Het gaat om schoenen **118** bij vrouwen.
