### ISSUE TITLE
Outlaws interiour

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1051]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

S.v.p even kijken naar de interiour. Schilderijen 'vliegen' momenteel voor de muur.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by brothasx** [comment]
Bekeken, om dit te fixen moet meerdere models aangepakt worden. 
Dit zal redelijk wat werk kosten ( + - 2 uur aan modelling werk)  

Conclusie : Niet nodig om te fixen, dit valt amper op.
