### ISSUE TITLE
[FEATURE]: Voertuigen pakken bij ANWB werkt niet goed.

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1052]
### Contact Details

DeStefanoKiller#4442

### Voertuig model

Alle voertuigen bij de ANWB weet niet elke spawn naam : Flatbed, ANWBvolvo, Tundra, asterope

### Omschrijf de bug

Het probleem wat je op het YouTube video ziet is het probleem wat gaande is. Dus na het pakken van een ANWB voertuig doet het voertuig niks meer je kan je banden niet bewegen /engine doet niks en na het uitstappen kun je niet meer terug instappen. Pas nadat je /trv hebt gedaan doet het voertuig na behoren. 

Video dat het voertuig niet werkt:
https://www.youtube.com/watch?v=GHUuYs4ZxvI

### Repro

- In-dienst gaan bij ANWB.
- Voertuig pakken bij ANWB via het ANWB Menu (boven bij kantoor).
- Als je de bovenste twee stappen hebt gedaan dan komt het probleem tevoorschijn. 

### Normaal gedrag

- Wat er hoorde te gebeuren is wanneer jij het voertuig inspawned dan hoef je alleen je motor aan te doen en zo kun jij je voertuig gebruiken voor je ANWB dienst. 

Video dat het voertuig wel werkt:
https://www.youtube.com/watch?v=x9xNEZvZ53g&ab_channel=DeStefanoKiller

**Comment by niekschoemaker** [comment]
Ik heb het spawnen nu iets aangepast, als je even kunt terugkoppelen (na restart) of het zo gefixed is.

het is wel een beetje sketchy, m'n volgende oplossing gaat denk ik zijn om de cirkel gewoon buiten neer te zetten.

**Comment by DeStefanoKiller** [comment]
@niekschoemaker helaas heeft de fix niet geholpen.

**Comment by niekschoemaker** [comment]
Oke poging nummer 2, na volgende restart. Hierna zet ik buiten gewoon een cirkel neer

**Comment by lexdeboer** [comment]
@niekschoemaker nu hebben we het probleem dat soms de voertuig niet ingeleverd willen worden in de gele cirkel, zie onderstaande video voor meer info.
https://www.youtube.com/watch?v=cvrbsVwAYkM&ab_channel=%5BTDA%5DLex

**Comment by Chang-nl** [comment]
ik heb een poging tot gedaan hopen dat het heeft gewerkt!

**Comment by Chang-nl** [comment]
zou na de restart van 2 uur toegepast moeten zijn.
