### ISSUE TITLE
[FEATURE]: Een kerk, pastoor job + items

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1054]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

GoedeDag Ik ben Mr Morello Beter bekend als Pastoor & binnen de wijk als ali express kenneth (Vraag me niet waarom)
Ik Speel nu al zon 3200 Uur TeDeApolis, en wil graag iets aanvragen zoals ik eerder verteld had ben ik pastoor in de stad, 
Dat houd in dat ik met mensen praat mensen kunnen biegten en mensen naar me toe kunnen voor vragen.
Nu wil ik een jobje aanvragen genaamd pastoor. 

- [ ]  Een kerk -  er was hier al een MLO van gestuurd
- [ ] Pastoor Rank ingame

- [ ] Hostie (Broodje Met de naam hostie of craker.

Wat is mijn plan?
een veilige plek om mensen elkaar te laten ontmoeten met elkaar kletsen en er voor elkaar zijn.
Een keer in de zoveel tijd kunnen we grote meetings houden niet meer dan 30 Man inverband met server load

Voor Boellag#3883.

Op aanvraag van Kenneth.

**Comment by Chang-nl** [comment]
Waar is die kerk te vinden zit dat al in de main?

**Comment by Ljosfari** [comment]
> Waar is die kerk te vinden zit dat al in de main?

Kenneth weet hier mee over !
