### ISSUE TITLE
[FEATURE]: Sloten op deuren van Cardealer op postcode 7044

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1055]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Sloten platsen (voor de Ondernemer role) op de voordeuren, zijdeur en de garagedeuren van de cardealer op postcode 7044.

Eventueel een kledings cirkel in het kantoortje achter de balie.

### Wat lost deze feature op?

Dit zorgt er voor dat mensen niet ongevraagt de cardealer binnen rijden, waardoor alle autos kapot gereden worden en heel de showroom vernaggeld is.

Het zorgt er ook voor dat mensen niet ongevraagt in de cardealer gaan staan terwijl de cardealer gesloten is.

De kleding cirkel zou handig zijn zodat de werkenemers makkelijk hun kleding kunnen aanpassen als ze gaan cardealen.

**Comment by brothasx** [comment]
Deze is uitgevoerd op de testserver, en staat klaar om gepushed te worden richting de Main Server.
