### ISSUE TITLE
[FEATURE]: Aanpassen snelheidsboetes

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1057]
### Contact Details

Lamine#4904

### Beschrijf zo duidelijk mogelijk de feature

Naar aanleiding van https://github.com/Tedeapolis/wet-en-regelgeving/pull/269 het verzoek om de snelheidsboetes ook daadwerkelijk in het boetemenu van de Politie & KMAR in-game aan te passen. 

Aangezien het nu best wat boetes zijn, eventueel ook het verzoek om een extra kopje/categorie toe te voegen genaamd "snelheidsboetes" en in de categorie "snelheidsboetes" twee categorieën "Binnen bebouwde kom" en "buiten bebouwde kom" voor het boetemenu. 

- [x] Aanpassen boetes voor binnen de bebouwde kom
- [x] Aanpassen boetes voor buiten de bebouwde kom
- [x] Toevoegen categorie "Snelheidsboetes"
- [x] Toevoegen categorie "Binnen bebouwde kom"
- [x] Toevoegen categorie "buiten bebouwde kom"

### Wat lost deze feature op?

Extreem roekeloos rijgedrag

**Comment by Willem-Dekker** [comment]
zit er na restart in
