### ISSUE TITLE
[Bug]: Taxi: Meerdere bugs met hersenloze ritjes sinds laatste update

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1058]
### Contact Details

Geertje123#2163

### Wat gebeurde er?

Sinds een aantal dagen zijn er een aantal bugs wua hersenloze ritjes bij de taxi. 

- Hersenloze worden niet meer automatisch klaargezet na een bestaande rit. En hersenloze zijn niet meer op alle normale locaties (zoals de bank) te vinden.
Druk op start/stop taxi rit, hij vind hij een hersenloze, je brengt de hersenloze naar bestemming. Hersenloze stapt uit, maar er gebeurt verder niets. Dus na de bestemming moet je weer op start/stop taxi rit drukken zo dat het stopt met zoeken en naar een punt rijden waar je sneller kan pakken, maar verder gebeurt het niet meer automatisch.

https://medal.tv/games/gta-v/clips/aCCGttcsHEwi0/d1337pEfis1i?invite=cr-MSxRM3QsNDQxNzU2NjQs
https://www.youtube.com/watch?v=MziJ3eMSPz8
https://www.youtube.com/watch?v=M0cSLI1JxGs 

Ook melden collega's dat hersenloze random bewusteloos raken tijdens de rit, waardoor die niet afgemaakt kan worden.

### Wat hoorde er te gebeuren?

Normaal als je een herseloze afzet dan komt er een nieuwe tevoorschijn die je kan wegbrengen.
Normaal kan je hersenloze op bekende locaties ophalen, maar bij de bank bijvoorbeeld werkt dit niet meer.
Normaal raken hersenlozen niet random bewusteloos tijdens de rit.

### Wat veroorzaakt de bug?

We vermoeden dat dit sinds de laatste gta update van een dag of twee geleden is.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Ljosfari** [comment]
ook is er een probleem met de porto, je wordt niet op het juiste kanaal gezet en/of kunt de porto niet gebruiken

**Comment by Ljosfari** [comment]
ik heb hier een github van aangemaakt met alle taxi issues die er momenteel zijn, zie #1062
