### ISSUE TITLE
[FEATURE]: Random timer op liften [Staffoverleg]

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1059]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een random timer tussen de 5 en 10 seconden voor het gebruik van een lift. Momenteel is dit een instant teleport.

### Wat lost deze feature op?

Voorkomt misbruik en maakt het ook wat realistischer aangezien in het echt je ook even moet wachten op de lift. :)

**Comment by Chang-nl** [comment]
yes toegevoegd!

**Comment by Ljosfari** [comment]
Timer staat nu alleen op overheidsgebouwen, dit graag op alle gebouwen. En de volgorde van de lift in het poltie hb klopt niet meer.

**Comment by Chang-nl** [comment]
yes dit is gefixt na de volgende restart!
