### ISSUE TITLE
[FEATURE]: Slot op deur onderzijde politie HB

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1060]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij een slot willen op de deur onderaan bij de parkeerplaats aan de achterzijde van het politiebureau, net zoals bij de rest van de deuren in het HB. 
![image](https://user-images.githubusercontent.com/93579695/153778215-bbf4efe5-a3d4-463e-b499-18d48c24dd2c.png)

### Wat lost deze feature op?

Dat onbevoegden zomaar naar binnen kunnen rennen.

**Comment by niekschoemaker** [comment]
Zit erin
