### ISSUE TITLE
[Bug]: Taxi -  meerdere bugs

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1062]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

- [x] - Hersenloze worden niet meer automatisch klaargezet na een bestaande rit. En hersenloze zijn niet meer op alle normale locaties (zoals de bank) te vinden.
Druk op start/stop taxi rit, hij vind hij een hersenloze, je brengt de hersenloze naar bestemming. Hersenloze stapt uit, maar er gebeurt verder niets. Dus na de bestemming moet je weer op start/stop taxi rit drukken zo dat het stopt met zoeken en naar een punt rijden waar je sneller kan pakken, maar verder gebeurt het niet meer automatisch.

https://medal.tv/games/gta-v/clips/aCCGttcsHEwi0/d1337pEfis1i?invite=cr-MSxRM3QsNDQxNzU2NjQs
https://www.youtube.com/watch?v=MziJ3eMSPz8
https://www.youtube.com/watch?v=M0cSLI1JxGs 

Ook melden collega's dat hersenloze random bewusteloos raken tijdens de rit, waardoor die niet afgemaakt kan worden.

### Wat hoorde er te gebeuren?

Normaal als je een herseloze afzet dan komt er een nieuwe tevoorschijn die je kan wegbrengen.
Normaal kan je hersenloze op bekende locaties ophalen, maar bij de bank bijvoorbeeld werkt dit niet meer.
Normaal raken hersenlozen niet random bewusteloos tijdens de rit.

- [x] Porto: je wordt niet op het juiste porto kanaal gezet en/of de hele porto werkt niet

- [x] Problemen met het inleveren van de voertuigen. Sommige taxi voertuigen willen na een paar keer pas de cirkel in, of helemaal niet. https://medal.tv/games/gta-v/clips/b0g6fLpIl6-Vn/d13377lSwRQi?invite=cr-MSxTZnMsMTk4MjA3NDks

**Comment by Ljosfari** [comment]
Nee. Kan het straks wel even aan je laten zien Chang

**Comment by TedeaTaxi** [comment]
1. Hersenloze die niet respawnt (sandy): https://medal.tv/games/gta-v/clips/bAa2O8b69sfY4/d1337qNgXp8P?invite=cr-MSx0bFMsNDQxNzU2NjQs

2. En dit is een plek waar hersenloze achter de barriere spawnen: https://medal.tv/games/gta-v/clips/bA8JjwsChDYox/d1337m868ijW?invite=cr-MSxEWW4sNDQxNzU2NjQs

![image](https://user-images.githubusercontent.com/93401910/154838064-8900c974-cbf2-4734-a59c-c47e1875d52d.png)

**Comment by TedeaTaxi** [comment]
3. Dit is een plek waar hersenloze op de loopbrug spawnen, en er niet vanaf kunnen komen. Het effect ervan is dat je opnieuw moet zoeken, maar dat de hersenloze daar blijft staan. Hier dealen mensen dan vaak ook drugs omdat er wat geglitchte hersenlozen staan: 
![image](https://user-images.githubusercontent.com/93401910/154838131-4d3be6a7-1abd-4bb6-b7ee-ef68ad8ec325.png)

**Comment by TedeaTaxi** [comment]
4: Bij het vliegveld het zelde verhaal. Als je bij de bovenste pijl iemand af zet, dan spawnt de volgende vaak op de brug bij de onderste pijl, waardoor die onmogelijk op te halen is: 
![image](https://user-images.githubusercontent.com/93401910/154838162-fae884b8-5c3b-4832-8ee9-0ffc3851f54c.png)

**Comment by TedeaTaxi** [comment]
@Ljosfari Ik was je vergeten te taggen. Maar dat je het weet ^

**Comment by niekschoemaker** [comment]
Ik heb nu een timeout toegevoegd dat peds automatisch geteleport worden, dit zoud de issues op moeten lopen
