### ISSUE TITLE
Noodknop overheden blijven in emote hangen als je wilt annuleren

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1063]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

Overheden die de noodknop indrukken en hem dan willen annuleren blijven in de emote hangen (Niek weet hiervan)

### Wat hoorde er te gebeuren?

Als je wilt annuleren moet de hand ook van de knop afgaan zodat mensen kunnen zien dat je hem dus los laat

### Wat veroorzaakt de bug?

geen idee

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
is gefixed
