### ISSUE TITLE
Shotgun damage op afstand aanpassen/verminderen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1064]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

De shotgun wat een close range/damage weapon is, schiet op grote afstanden met dezelfde damage als een sniper, zoals besproken in stafoverleg moet deze dus even nagekeken worden

### Wat hoorde er te gebeuren?

Close range de damage die hij hoort te doen, verre afstand moet de damage aanzienlijk minder zijn of helemaal niet

### Wat veroorzaakt de bug?

Denk dat die wat beter afgesteld moet worden

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Als dit gemerged is is dit gefixt!
