### ISSUE TITLE
[FEATURE]: Optie om dienstvoertuigen uit je persoonlijke politieopslag te kunnen verwijderen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1065]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een optie om politievoertuigen uit je eigen opslag te verwijderen, zoals op het screenshot hieronder:
![image](https://user-images.githubusercontent.com/93579695/153937662-d3a8345a-a0d4-4eae-a5e6-c4c74f0806d2.png)

### Wat lost deze feature op?

Dat je duplicates kunt verwijderen uit je garage, zodat het geordend en overzichtelijk blijft. Lage prioriteit.

**Comment by niekschoemaker** [comment]
Zit erin
