### ISSUE TITLE
[FEATURE]: TDA media

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1067]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Universele Media Rol

Deze rol is toepasselijk voor elke media instantie zodat er geen onderscheid is tussen de nieuwszenders (TDA NWS - DCR Nieuws)

Hierarchie:
TDA Media - Eindredacteur (1200€/10 minuten)
TDA Media - Editor  (1000€/10 minuten
TDA Media - Redacteur (950€/10 minuten)
TDA Media - Onderzoeker (850€/10 minuten)
TDA Media - Journalist (650€/10 minuten)
TDA Media - Stagiaire (450€/10 minuten)

- [ ] Rank lijst in de server supporter zetten
0 - Stagiaire
100 - Journalist
200 - Onderzoeker
300 - Redacteur 
400 - Editor
500 - Eindredacteur
- [x] Eventueel icoontje voor de media job in discord
- [x] Loon staat nog niet aan
- [x] Pasje voor de pers (id kaart)
- [x] Lift naar het dak voor de helicopter
- [x] Boss menu (cirkel staat er wel maar doet niks)

(Heb voor de lonen een beetje gekeken naar de verschillende andere banen en hoe moeilijk hun baan is. Redacteurs etc krijgen meer omdat zij eigenlijk meer uren maken buiten game dan IG)
(En voor de namen gekeken naar een aantal namen in de Cinema/Nieuws wereld)

- Iedereen moet toegang kunnen hebben tot de cirkels van de Telegraaf gebouw (naast postcode 5158), Busjes en Helikopters.
- Alle sloten van Telegraaf en TDA Nieuws moet iedereen kunnen openen
Ik raad aan om de baan van TDA Radio te kopiëren want daar werken alle sloten en alle cirkels al voor dus dit zal het werk makkelijker maken

Wellicht dat de helikopter cirkel alleen beschikbaar is vanaf Journalist.

![unknown](https://user-images.githubusercontent.com/97713942/153961811-2de26842-058f-4d06-b4ae-4a231c7ee3aa.png)

**Comment by Willem-Dekker** [comment]
zie bikerjob voor de vorige banen. hier kan je dit in zetten ga ik van uit dus gewoon samen voegen van de 2

**Comment by Chang-nl** [comment]
zodra dit gemerged is zit dit erin!

**Comment by niekschoemaker** [comment]
Boss menu zou vanaf volgende restart moeten werken.

Misten wat dingetjes in de database.

**Comment by ESP-Edgar** [comment]
Boss menu kan wel geopend worden maar er is geen beheer van lonen en er kunnen geen mensen aangenomen/ontslagen worden alleen geld storten, zie foto: 
![image](https://user-images.githubusercontent.com/71555741/155845753-5196023d-e5ed-41eb-b9dc-4699bc8f32db.png)
