### ISSUE TITLE
[Bug]: Laat inspawnen van voertuigen

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1069]
### Contact Details

Bas#6430

### Wat gebeurde er?

Sinds deze week zie ik steeds meer tickets of video's voorbij komen waarbij rijdende voertuigen enorm laat inspawnen. 

Zie hieronder 2 voorbeelden:
https://medal.tv/games/gta-v/clips/b7LeR0Qh6PuG-/d1337p9J8S8z?invite=cr-MSxYTjksNDg0NzAwNTgs
https://medal.tv/games/gta-v/clips/b7smGgV3R5wIT/d1337FBagXcn?invite=cr-MSw1b3EsMjcyODE3NjEs

### Wat hoorde er te gebeuren?

Voertuigen horen op afstand zichtbaar te zijn. Echter spawnen ze nu net voor je neus in waardoor je geen kans hebt om erop te reageren.

### Wat veroorzaakt de bug?

Onbekend.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by AdventurePandah** [comment]
Yes, deze instellingen staan op maximaal. Issue mag gesloten worden. Ik zal deze issue heropenen zodra dit opnieuw voorkomt.

**Comment by Ljosfari** [comment]
is gefixt
