### ISSUE TITLE
[FEATURE]: Toevoegen van contanten/zwartgeld in death logs

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1070]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Momenteel worden enkel fysieke items gelogged wanneer iemand dood gaat. Contant en zwartgeld wordt daar niet bij gezet.

### Wat lost deze feature op?

We kunnen zo makkelijker natrekken hoeveel cash of zwartgeld iemand had voor eventuele refunds.

**Comment by AdventurePandah** [comment]
Het gaat hier trouwens om de logs in Discord ^

**Comment by niekschoemaker** [comment]
Zit erin
