### ISSUE TITLE
[FEATURE]: autos op 2dehands

### ISSUE THREAD

**Issue by Grizzy77** [Tedeapolis/development#1071]
### Contact Details

Griezmann#6478

### Beschrijf zo duidelijk mogelijk de feature

Artikel .. omtrent het op 2dehands zetten van voertuigen.

1.    Hij/zij die een voertuig voor een te hoge waarde op 2dehands zet wordt gestraft volgens de 1e categorie.

2.    De overtreding vermeld in het eerste lid staat bekend als “onrealistische plaatsen van voertuigen 2dehands of failRP”

3.    Onder een te hoge waarde wordt verstaan boven de stockwaarde in de cardealer exclusief tunes.

4.    Is het voertuig getuned dient er rekening mee te houden dat deze voor normale prijzen aangeboden worden. (maximaal x aantal %van de stockprijs )

5.    Indien de overtreder na de straf genoemd in lid 1 nog niet ophoudt met het onrealistisch plaatsen van voertuigen kan er gekozen worden de overtreder te bestraffen volgens categorie 2.

### Wat lost deze feature op?

Waarom deze regel?

Vaak staan er voertuigen voor een veel te hoge waarde op 2dehands.

Na mijn weten is er al meerdere keren een warning door gegeven. ( ik maak wel is reports en freddy heeft er al wel is wat voor mij vanaf gehaald. )

Nergens in de apv staat na mijn weten dat je hier een warning voor kan krijgen en dan nu dus wel. Het voorkomt veel te dure voertuigen die een plekje innemen op de 2de hands waar het momenteel ook al erg druk is, ook in het echt zet je een fiat van 5000 euro niet tekoop voor 400.000 euro.

**Comment by Willem-Dekker** [comment]
verkeerde repo zie: https://github.com/Tedeapolis/wet-en-regelgeving
