### ISSUE TITLE
Shotgun zichtbaar maken op rug

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1073]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

Aangezien de shotgun te groot is om in je zakken te doen, dit een zichtbaar item op de rug maken zoals mini ak en de ak 47

### Wat lost deze feature op?

dat shotguns uit de broek worden getrokken als pistolen :)

**Comment by Ljosfari** [comment]
is na de restart gefixt
