### ISSUE TITLE
[FEATURE]: Vereiste rang om Amarok te kopen verlagen naar Surveillant

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1074]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

De benodigde in-game rang die je nodig hebt om de politie Amarok (/car pamarok) te kunnen kopen verlagen naar Surveillant ("police" "1" "Surveillant").

### Wat lost deze feature op?

De Amarok training is te volgen vanaf Surveillant maar momenteel pas te koop vanaf de rang Agent.

**Comment by Chang-nl** [comment]
Zit erin!
