### ISSUE TITLE
[Bug]: Taxi CLA ("Luxe Taxi") heeft random kleuren

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1075]
### Contact Details

Geertje123#2163

### Wat gebeurde er?

Taxiauto's worden ingeladen met random kleuren en wraps.

![image](https://user-images.githubusercontent.com/93401910/154228707-20e66cc3-e7ab-4854-8449-a784533f1e4a.png)
![image](https://user-images.githubusercontent.com/93401910/154228722-bd62e15a-86d3-4c82-8d1d-19c38fca2fff.png)
![image](https://user-images.githubusercontent.com/93401910/154228768-225f04ca-0cb8-4ca9-8525-917270095107.png)

### Wat hoorde er te gebeuren?

Zou gewoon zwart met de logo's moeten zijn.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by TedeaTaxi** [comment]
Mogelijk komt dit ook voor bij de andere taxiwagens

**Comment by Ljosfari** [comment]
Ik heb dit getest en heb er geen last van. Is er 1 persoon die hier last van heeft om meerdere mensen ?

**Comment by Chang-nl** [comment]
Hoe hoog heb je je texture kwaliteit staan in je instellingen en gebruik je een modpack?

**Comment by TedeaTaxi** [comment]
Dit was blijkbaar een fout in de stad, ANWB had er ook last van, en is nu opgelost.
