### ISSUE TITLE
[Bug]: Mercedes bus

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1076]
### Wat gebeurde er?

Als je achterin zit stap je instant in en uit, ook als de auto rijd. Je doet geen ragdoll. Dit kan helaas misbruikt gaan worden.

https://user-images.githubusercontent.com/97713942/154232930-4e2cc104-0003-47cd-9895-1b92ecd187cf.mp4

### Wat hoorde er te gebeuren?

Er hoort een ''uitsapt'' emote gebruikt te worden, deur open en dicht etc. of hier een delay op. En als de auto rijdt en je stapt uit moeten spelers wel ragdollen.

### Frequentie van de bug

Altijd

spawnnaam: v250

**Comment by Lorenzo3001** [comment]
Valt momenteel niet te fixen. De taxi bus heeft dit ook. Heeft ermee te maken dat het voertuig nu 6 persoons is. Op verzoek van Kenneth heb ik het voertuig van 4 persoons met animatie aangepast naar 6 persoons zonder animatie.
