### ISSUE TITLE
[FEATURE]: KMAR Vito Bus

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#1079]
### Contact Details

Chrushers#8656

### Kenteken van voertuig

NVT

### Voertuig model

Vito Politie

### Omschrijf de bug

Momenteel hebben wij een Vito bus tot onze beschikking van de KMAR. Alleen is de skin van de Politie. Het zou fijn zijn als de Vito de KMAR skin kan krijgen. Is dit niet mogelijk dan weet ik dat er in de test stad een Volkswagen T5 zit die nog een handeling aanpassing moet hebben. Misschien dat dit dan wel een goede vervanger is.

### Repro

Je kunt deze auto als KMAR job uit de garage halen onder bij HB.

KMAR skin op de vito Bus.

+ 
De bijrijder van de vitobus heeft altijd problemen met instappen, als er een persoon achter het stuur zit is het onmogelijk voor de bijrijder om in te stappen, de bestuurder moet dan eerst uitstappen voordat de bijrijder kan instappen en dit moet dan tegelijk anders werkt het ook niet

Wat hoorde er te gebeuren?
Normaal hoort de bijrijder normaal in te kunnen stappen

**Comment by Eseclick** [comment]
Waarschijnlijk heeft deze Vito maar 1 template file. Dit is zo geregeld bij het maken van het model van de bus.

**Comment by Lorenzo3001** [comment]
Vito is na de restart gereskined naar een Kmar Vito
