### ISSUE TITLE
[FEATURE]: Nieuwe KMAR auto Opel Astra

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#1080]
### Contact Details

Chrushers#8656

### Beschrijf zo duidelijk mogelijk de feature

We zouden graag een nieuwe dienstwagen zien voor de KMAR.  Dit zou om een Opel Astra gaan. Deze zou dan gebruikt mogen worden vanaf 1e Klasse KMAR.

Hier onder heb ik een link geplaatst waar hij te vinden is.
https://shop.alpha-store.nl/package/4872914

### Wat lost deze feature op?

Hierdoor hebben we iets meer variatie in voertuigen en kunnen we nog een specialisatie plaatsen bij de nieuwe rangen.

**Comment by Chrushers** [comment]
Als dit te lastig blijkt te zijn dan kunnen we ook wel een reskin van de B klasse van de politie doen. Deze rijd de KMAR namelijk ook.

**Comment by Attomn** [comment]
@walvisgedaan was hiermee bezig dacht ik: #1456

**Comment by walvisgedaan** [comment]
Model wordt niet meer aangeboden op de website
