### ISSUE TITLE
[Bug]: Lopen terwijl je geboeid bent kan niet met tie wrap handboeien

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1084]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Mensen kunnen niet lopen met tie wrap handboeien om.

### Wat hoorde er te gebeuren?

Het is laatst aangepast dat personen die geboeid zijn nog wel rond kunnen lopen. Dit is momenteel alleen nog zo bij handboeien van de politie/kmar, maar dat hoort als het goed is ook zo te zijn voor de criminele handboeien, dus de tie wraps.

### Wat veroorzaakt de bug?

Boei iemand met tie wrap handboeien en diegene kan niet lopen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
is aangepast
