### ISSUE TITLE
[FEATURE]: /Transfer toevoegen + /close uitzetten voor niet staffleden

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1085]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

In het vorige ticket systeem zaten twee features die ik nog niet heb teruggezien in het huidige ticket systeem.

- [x]  Voorheen bestond er een optie om ?transfer te gebruiken om het ownership over te dragen aan een andere persoon. Dit is momenteel geen optie waardoor staffleden die een ticket aanmaken voor iemand anders het transcript hiervan in hun eigen PM krijgen.

- [x]  ?close was voorheen uitgezet voor niet staffleden om te voorkomen dat mensen zelf hun tickets konden sluiten. Sinds het nieuwe ticket systeem is /close wel te gebruiken door burgers, waarbij het me handig lijkt dat het ook nu weer wordt uitgezet.

### Wat lost deze feature op?

Transcript naar de juiste personen en tickets die niet zomaar weg zijn.

**Comment by MisterM02** [comment]
Zou hier nog naar gekeken kunnen worden (/transfer)? Als je nu handmatig mensen toevoegt aan een ticket en deze hierna sleept gaat de persoon er weer uit.

**Comment by Chang-nl** [comment]
Hey @niekschoemaker, hoe staat het hiermee?

**Comment by niekschoemaker** [comment]
Zit erin!
