### ISSUE TITLE
[Bug]:  Probleem CBR na het behalen van rijbewijs.

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1086]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Als spelers klaar zijn met het behalen van hun rijbewijs, komt er een auto, bus of motor voor terug.
Hierdoor kunnen sommige mensen niet hun rijbewijs halen.

Ik heb een gyazo gemaakt van het probleem : https://gyazo.com/168ce046907037ab491bb90fb8451466 
 
Heb een video van wat er kan gebeuren, is opvraagbaar. 

### Wat hoorde er te gebeuren?

Normaal gaan auto's gewoon weg na het behalen van hun rijbewijs.

### Wat veroorzaakt de bug?

Denk door update van FIVE M.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Heeft niek in een recente commit gefixt!
