### ISSUE TITLE
[Bug]: Hersenlozen spawnen soms tijdens het rijden uit de auto en breken de auto en proberen je daarna aan te vallen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1087]
### Contact Details

Geertje123#2163

### Wat gebeurde er?

Dit zijn eigenlijk twee problemen in één. Hersenlozen spawnen tijdens het rijden soms uit de auto, en ze vallen je erna vaak aan.
Gebeurt tijdens het rijden soms. Meerdere keren gemeldt door andere collega's. Ik heb er nu een video van.

Het moment dat de hersenloze eruit spawnt:
https://medal.tv/games/gta-v/clips/bz7d6F9F3W99N/d1337jD5JsDg?invite=cr-MSxrV0osMTg4NjE4NDYs

Probeert erna aan te vallen:
https://medal.tv/games/gta-v/clips/bz7GB-6CxO9mQ/d1337Vd3T0ds?invite=cr-MSxtNE4sMTg4NjE4NDYs

### Wat veroorzaakt de bug?

Nog geen idee.

### Frequentie van de bug

1x per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Volgens mij is dit de log van het moment waarop het gebeurd:
![image](https://user-images.githubusercontent.com/93401910/154803089-58e1277d-7745-4509-a77b-7b73ed2c1e2d.png)

**Comment by niekschoemaker** [comment]
Is na volgende herstart gefixed
