### ISSUE TITLE
[FEATURE]: Geen drugs quicksell cirkels voor overheidsbanen.

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1088]
### Contact Details

Dekk#3792

### Beschrijf zo duidelijk mogelijk de feature

Het verwijderen van drugs quicksell cirkels voor overheidsbanen. Dus deze cirkels zijn dan niet meer zichtbaar voor mensen in de stad met een overheidsbaan, alleen mensen met een gang-job of legale job kunnen deze cirkels zien.

Wellicht alleen cirkels voor de recherche job.

### Wat lost deze feature op?

Powergaming van politie en/of kmar op de quicksells is al erg lang een probleem, dit zal zorgen voor minder powergaming en voor leukere roleplay; aangezien overheids diensten dan niet van te voren weten of dit een drugs locatie is of niet.

**Comment by Tijz** [comment]
Gisteren ook besproken in een groot overleg tussen politie, kmar en criminelen. Iedereen leek er wel over eens te zijn.

**Comment by Willem-Dekker** [comment]
Heb dit item op de agenda gezet

**Comment by Willem-Dekker** [comment]
kan geimplementeerd worden is accoord.

**Comment by Willem-Dekker** [comment]
fixed al een tijdje
