### ISSUE TITLE
[FEATURE]: /gijzel toestaan bij meerdere wapens.

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1089]
### Contact Details

Dekk#3792

### Beschrijf zo duidelijk mogelijk de feature

Github gemaakt vanwege vele animo in #suggesties.

Het mogelijk maken van /gijzel bij meedere wapens en niet alleen bij een pistool. Het lijkt me handig om dit te doen bij alle kleine wapens;

weapon_sawnoffshotgun (ik zag dat er een github open stond over het op de rug doen van dit wapen, dus wellicht deze niet.)
weapon_minismg

Het is momenteel mogelijk bij de volgende wapens;

weapon_pistol_mk2
weapon_pistol

De reden om dit niet toe te staan bij slag & steek is, omdat dit anders te overpowered zou zijn, dan zou je achter iemand kunnen gaan staan met een mes en instant /gijzel kunnen doen. En de reden om dit niet bij grote wapens te doen is, omdat ik denk dat het er heel raar uit gaat zien als je iemand gijzelt met een AK in je handen. Als het mogelijk wordt om dit er normaal uit te laten zien, dit wellicht ook overwegen. 

### Wat lost deze feature op?

Deze feature zal er voor zorgen dat je niet als je 1x je wapen niet op iemand richt die persoon als "niet bedreigt" wordt gezien, het is ook gewoon logischer om dit te kunnen met bijvoorbeeld een scorpion.

**Comment by Ljosfari** [comment]
Alleen voor de mini smg

**Comment by Chang-nl** [comment]
Gefixed!
