### ISSUE TITLE
[Bug]: Signaleringen in het MEOS blijven te lang staan

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1091]
### Contact Details

Lamine#4904

### Wat gebeurde er?

Op het moment dat een persoon een arrestatiebevel heeft in het MEOS en deze wordt weggehaald, dan blijft de naam rood op het moment dat je hem opzoekt. 

### Wat hoorde er te gebeuren?

Nadat een signalering opgeheven wordt, dient er na 10 minuten (caching geloof ik) geen rode naam meer te verschijnen op het moment dat je de persoon opzoekt. 

### Wat veroorzaakt de bug?

1. Een persoon opzoeken via het MEOS
2. Een notitie met arrestatiebevel op zijn naam zetten
3. Even wachten
4. Het arrestatiebevel opheffen
5. Dezelfde persoon nogmaals opzoeken

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/71287080/154850508-780cfc1b-49db-4c7b-b66e-9b737c725da4.png)
![image](https://user-images.githubusercontent.com/71287080/154850509-57524f4d-1d58-4c8a-9c31-695e11ffb8f8.png)
![image](https://user-images.githubusercontent.com/71287080/154850514-efecefc5-5122-410a-a4d5-c165397c96c8.png)

**Comment by niekschoemaker** [comment]
Zou je het even kunnen testen, zou nu gefixed moeten zijn

**Comment by TDA-SanderD** [comment]
Is nog niet gefixt helaas. Er kwam gisterenavond weer een ticket over @niekschoemaker.
