### ISSUE TITLE
Shotgun hoger op de rug plaatsen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1093]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

https://media.discordapp.net/attachments/564164473544245258/945034348674056263/unknown.png

### Wat hoorde er te gebeuren?

Hij moet op je rug, niet in je bilnaad :D

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
is na de restart gefixt
