### ISSUE TITLE
[FEATURE]: Body Armor aan/uit kunnen doen in f11 menu

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#1094]
### Contact Details

MassiveR3T4RD#1741

### Beschrijf zo duidelijk mogelijk de feature

Optie in het f11 kleding menu naast schoenen broek en shirt om ook je bodyarmor aan en uit te kunnen doen. 

(suggestie speler) -> 
![afbeelding](https://user-images.githubusercontent.com/56398140/154929385-d2ba1759-16d1-45ca-bb38-657a25a4d934.png)

### Wat lost deze feature op?

Zorgt voor meer mogelijkheid voor roleplay, zo kan een crimineel uit zijn auto een bodyarmor pakken en aandoen als hij in een schietpartij komt en dan met de ambulance een verdere roleplay aangaan dat hij/zij bodyarmor aan het etc..

**Comment by Ljosfari** [comment]
is deze al goedgekeurd door staff tim ?

**Comment by niekschoemaker** [comment]
Zit erin
