### ISSUE TITLE
[FEATURE]: /Gijzel /TakeHostage Update wapens (suggestie)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#1096]
### Contact Details

MassiveR3T4RD#1741

### Beschrijf zo duidelijk mogelijk de feature

Bij de /gijzel functionaliteit toevoegen dat dit mogelijk is met de weapon_minismg(skorpion) dit wapen is bijna net zo groot als de m1911 of beretta

![afbeelding](https://user-images.githubusercontent.com/56398140/154932641-a831fec9-7588-4a5f-8fdd-2c587410b750.png)

### Wat lost deze feature op?

Scenario's zoals in deze video (https://youtu.be/pHBcZp4d2ag) omdat je geen andere mogelijkheid hebt dan /me op het moment

**Comment by Ljosfari** [comment]
zie #1089
