### ISSUE TITLE
[Bug]: Juwelier kan niet meer overvallen worden

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1097]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer je de juwelier wilt overvallen, krijg je de melding dat de overval al gepleegd is. Echter is er sinds 11 december geen juwelier overval meer geweest.
Verder geen bug/foutmeldingen te zien.

### Wat hoorde er te gebeuren?

De mogelijkheid hoort er te zijn dat er minimaal 1x per dag een juwelier overval gepleegd kan worden.

### Wat veroorzaakt de bug?

Pak een wapen en ga vervolgens naar de juwelier toe. Schiet daar vervolgens met je wapen en je zult de melding zien.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
is gefixt
