### ISSUE TITLE
Mission Marker

### ISSUE THREAD

**Issue by Jesse-Poolman** [Tedeapolis/development#11]
Komt er een melding van een Noodknop van een ANWB/AMBULANCE/POLITIE. Dan willen we graag een route er naar toe hebben (Denk hier aan de melding van een bankoverval). Of dat er naar gekeken kan worden voor een ring rond om de noodknop zodat je niet door de war komt met meerdere noodknoppen.

**Comment by Willem-Dekker** [comment]
Er kan nu in keybinds een key worden ingesteld om een marker op de nieuwste gps locatie te zetten
