### ISSUE TITLE
[Bug]: CBR auto's

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1101]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

Na dat iemand rijles gehad heeft blijven de CBR auto's staan. Bijna op elk moment van de dag staan hier minimaal 2 autos.
Hierdoor is de spawn locatie geblokkeerd, of ze kunnen er niet langs voor de rijles route.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
