### ISSUE TITLE
[Bug]: Verwijderde documenten komen terug

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1102]
### Contact Details

MisterM#0001

### Wat gebeurde er?

Middels /docu kan je documenten verwijderen door op de selectie 'verwijderen" te drukken.
Op dat specifieke moment verdwijnen de documenten ook uit /docu.

Nu is het echter zo dat deze documenten na verloop van tijd weer terugkomen te staan in /docu.
Ze worden dus enkel verwijderd op dat specifieke moment, maar komen later weer terug.

### Wat hoorde er te gebeuren?

De documenten horen niet meer terug te komen.

### Wat veroorzaakt de bug?

1. Maak een document en sla deze op
2. Verwijder het document
3. Kijk of hij echt verwijderd is
4. Kijk enkele dagen later of hij er weer is

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Niks geks kunnen zien in de logs.

**Comment by niekschoemaker** [comment]
Zou na volgende herstart gefixed moeten zijn
