### ISSUE TITLE
Kamacho heeft geen speedlimiter

### ISSUE THREAD

**Issue by zeletix** [Tedeapolis/development#1103]
### Contact Details

Letix#3462

### Voertuig model

Canis Kamacho

### Omschrijf de bug

voertuig heeft geen speedlimiter

### Repro

w ingedrukt houden

### Normaal gedrag

een topspeeds van 220 ofzo

**Comment by Ljosfari** [comment]
is getest

**Comment by zeletix** [comment]
> 

hoe bedoel je?
