### ISSUE TITLE
[Bug]: Lightbars werken niet voor HRB rangen

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#1104]
### Contact Details

Chrushers#8656

### Beschrijf zo duidelijk mogelijk de feature

De HRB kan geen /lightbar meer doen. Dit is nodig omdat men een voertuig gebruikt voor transporten maar geen ELS er meer op zit. Daarom het weer mogelijk maken voor de HRB rangen om /lightbar en /loadlightbar te gebruiken. Het gaat om de volgende rangen.

- HRB Commandant
- HRB Sectiecommandant
- HRB Groepscommandant
- HRB Operator
- HRB Aspirant

### Wat lost deze feature op?

Dat men voor de transport autos weer lightbars kunnen aanbrengen.

**Comment by niekschoemaker** [comment]
Is gefixed
