### ISSUE TITLE
[Bug]: Animatie handboeien F6-menu politie

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1105]
### Contact Details

Lamine#4904

### Wat gebeurde er?

Op het moment dat je een persoon handboeit, werkt de animatie correct, echter stopt de animatie op het moment dat de daadwerkelijke boeianimatie afgelopen is, waardoor het lijkt alsof de persoon ontboeit is. 

https://youtu.be/q-MyHuCp_K0

### Wat hoorde er te gebeuren?

De persoon hoort nadat de animatie afgelopen is met zijn handen op zijn rug te staan, met handboeien om.

### Wat veroorzaakt de bug?

1. Jezelf een politierang geven
2. F6-menu van de politie openen
3. Juiste ID selecteren
4. Drukken op "boeien"
5. Wachten tot de animatie klaar is
6. Kijken hoe de persoon nu rondloopt.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
Is nog hetzelfde probleem

**Comment by Ljosfari** [comment]
is na de restart gefixed
