### ISSUE TITLE
[Bug]: Boete menu Aangepast bedrag

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#1107]
### Contact Details

NickBoos#7184

### Wat gebeurde er?

https://gyazo.com/b575cfcbf484bfee81a25b77dc12db1f 

Bij het uitschrijven van een boete krijg je de bovenstaande foutmelding.

De bug komt pas voor als je vaker dan +- 3x een aangepaste boete uitschrijft op kenteken.

### Wat hoorde er te gebeuren?

Er hoort een boete te worden uitgeschreven op de te naam gestelde van het voertuig. 

### Wat veroorzaakt de bug?

De volgende stappen kun je doorlopen om de bug te ondervinden.

Stap 1: Zet jezelf op de police job
F6 > Voertuig interactie > Schrijf boete uit > Vul een random kenteken in > Vervolgens opent er geen menu meer.

Om te ondervinden hoe het daadwerkelijk wel hoort te zijn kun je het zelfde doen maar dan bij burgerinteracties.
F6 > Burger interactie > ID > Boete > Aangepast bedrag > Vul een random bedrag in > Reden boete

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://gyazo.com/b575cfcbf484bfee81a25b77dc12db1f

**Comment by niekschoemaker** [comment]
Is als het goed is gefixed na restart

**Comment by SecretSupplier** [comment]
Yes het werkt! Je bent een TOPPERRRR!!
