### ISSUE TITLE
[Bug]: er staan geen brevetten op je vliegbrevet 

### ISSUE THREAD

**Issue by rubenTomassen** [Tedeapolis/development#1108]
### Contact Details

Ru🅱eN#8888

### Wat gebeurde er?

Als je je vliegbrevet bekijkt in de stad staat er niet meer op welke brevetten jij bezit. 
Als het goed is kan politie dit nog wel via MEOS zien maar dit kost natuurlijk extra tijd. 

### Wat hoorde er te gebeuren?

Normaal gesproken zou er op je vliegbrevet moeten staan welke brevetten jij bezit zoals: Heli, Prop, Jet

### Wat veroorzaakt de bug?

nvt
Was van de een op de andere dag zo 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

https://cdn.discordapp.com/attachments/784068803008004167/946866615646040084/unknown.png
https://cdn.discordapp.com/attachments/784068803008004167/946873296434102352/unknown.png

**Comment by niekschoemaker** [comment]
Is gefixed
