### ISSUE TITLE
Kamacho heeft geen speed limiter, omdat dit een GTA auto is

### ISSUE THREAD

**Issue by zeletix** [Tedeapolis/development#1109]
### Contact Details

Letix#3462

### Voertuig model

Canis Kamacho

### Omschrijf de bug

voertuig heeft geen speedlimiter

### Repro

w ingedrukt houden

### Normaal gedrag

een topspeed van 220 ofzo, met speedlimiter bedoel ik dit, dus voor Ljosfari; ik bedoel niet Y inklikken 😄 

![image](https://user-images.githubusercontent.com/84244559/155885802-86c5a8df-7e3a-42d8-b1d0-09485793e724.png)

**Comment by niekschoemaker** [comment]
Is toegevoegd
