### ISSUE TITLE
[EUP]: Ketting 123

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1110]
### Contact Details

Ljosfari#3575

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Ketting 123 zijn oor en gezicht piercings. Alleen zit hier een armband bij aan vast, deze komt door de kleding heen.
 Zou deze armband hiervan verwijderd worden ?

![image](https://user-images.githubusercontent.com/97713942/155903527-8e0c9040-91a2-42ef-b1d1-f22da3bc6a85.png)
![image](https://user-images.githubusercontent.com/97713942/155903536-cfcbdb6f-a024-400d-a45e-5a672f335bbc.png)
![image](https://user-images.githubusercontent.com/97713942/155903539-b93e40a3-5277-47bc-b88c-73436af3a928.png)

**Comment by brothasx** [comment]
Dit zou eventueel kunnen, alleen is het probleem als ik de model aanpas dat ik de hele dlc moet aanpassen. 
En zie ik dit niet zo zitten om voor een ketting'kje dat te doen =S
