### ISSUE TITLE
[Bug]: Pokeren Two Pair en Straight

### ISSUE THREAD

**Issue by RonaldDaquila** [Tedeapolis/development#1113]
### Contact Details

Daniël#4568

### Wat gebeurde er?

Wanneer er 1 hand is met two pair en eentje met een straight, wint de two pair. Volgens de officiële poker regels, is straight hoger.

### Wat hoorde er te gebeuren?

De persoon die een straight heeft, hoort te winnen.

### Wat veroorzaakt de bug?

Dat degene die een two pair heeft wint van een straight en al het geld naar degene gaat met de two pair.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Relevante log bestanden

Een voorbeeldlinkje alleen:
https://cdn.discordapp.com/attachments/931909951616598067/947877313025048606/30K_REFUND.mp4

**Comment by niekschoemaker** [comment]
Bekijk de video nog even een keer en kijk op welke knop hij klikt, hij fold letterlijk gewoon in die video, dus is niet heel gek dat de andere wint
