### ISSUE TITLE
[FEATURE]: Item maken van karretjes

### ISSUE THREAD

**Issue by OliviaVD** [Tedeapolis/development#1114]
### Contact Details

vikinggirlgamer696#1552

### Beschrijf zo duidelijk mogelijk de feature

Van het karretje een item maken, zodat je deze eerst moet aankopen of van een winkel stelen ofzo, voordat je dit kan gebruiken en dat je dit ook bij je moet hebben en mee moet rondlopen om het te kunnen gebruiken. Hierbij kan er dan ook goor gezorgd worden dat je met het karretje in handen niet kan instappen in een wagen. Dan moet je eerst het karretje in de wagen zetten, voordat je weg kan rijden. Je kan er dan ook voor zorgen dat je het karretje niet kan weg zetten als je te veel items bij hebt om zonder karretje te dragen. Zo zorg je ervoor dat er geen verder misbruik gemaakt wordt van veel meer dragen dan dat je eigenlijk kan.

Indien dit allemaal kan, kan er eventueel ook gekeken worden naar alle andere items waar je iets in kan steken, zoals koffertjes, winkeltassen, dozen... en deze dan ook in het zelfde systeem opnemen.

Misschien ook een leuke toevoeging: twee manieren om een karretje te bekomen:

1. Betalen: een degelijke prijs, zodat mensen hun karretjes niet zomaar random ergens laten staan en de map niet vol karretje staat.
2. Stelen: dat je bij een winkeloverval een kans hebt om ook een karretje te scoren.

### Wat lost deze feature op?

Deze feature zorgt ervoor dat er geen misbruik meer gemaakt wordt van de karretjes, zoals dit nu wel heel vaak gebeurd.

- Mensen dragen meer bij zich dan ze eigenlijk kunnen;
- Mensen gaan, met hun karretje nog vast, achter het stuur zitten;
- Mensen gaan op een scooter zitten, met een karretje in de hand;
- Mensen toveren een karretje uit hun achterwerk, om meer te kunnen dragen;
- Iedereen kan het zomaar meteen gebruiken, zonder er speciaal eerst één te bekomen/aan te kopen;
- ...

**Comment by Chang-nl** [comment]
Dit is gefixt na de volgende restart!
