### ISSUE TITLE
[Bug]: Shotgun damage

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1116]
### Contact Details

Dekk#3971

### Wat gebeurde er?

https://www.youtube.com/watch?v=q0lMuiqVtj8

Schotgun doet nauwelijks tot geen damage, zie video voor uitleg.

### Wat hoorde er te gebeuren?

De shotgun is echt enorm generfed. Laten we beginnen met dat je nu de shotgun op je rug kan zien, dat is inderdaad best logisch, aangezien je niet een shotgun uit je broekzak kan toveren. Maar daarna is er ook nog daar boven op een nerf geweest voor de shotgun die echt helemaal uit de hand is gelopen qua damage. De meeste schoten van de shoten doen ongeveer 9 tot 30 damage per hit en het is echt enorm slecht geworden. De wapens worden niet eens meer ingekocht door gangs, omdat dit wapen geen nut meer heeft. Nander heeft ook al gezecht dat dit niet de bedoeling was, dus vandaar de bug report.

[TDA] Nander — 28-02-2022
Ik zal hem zo even testen want dit is niet geheel de bedoeling nee

Ik denk persoonlijk dat de nerf dat hij op je rug komt al genoeg was, aangezien je dan niet meer als een of andere broektovenaar kan rond rennen met die shotgun, maar moet nadenken voordat je schiet. Ik stel voor dat de shotgun terug gaat naar de eerdere damage, maar wel op je rug blijft. Je moet momenteel namelijk 6x iemand raken met een shotgun voordat hij misschien dood is. Er is zelfs al in de stad voorgekomen dat iemand 7x is geraakt door de shotgun en alsnog 126 HP heeft. Een shotgun hoort een sterk wapen te zijn, met meerdere pallets, dus de kans dat je een paar van die pallets raakt en daardoor veel damage doet is aanzienlijk groot. 

### Wat veroorzaakt de bug?

Pak een shotgun, en begin te schieten. Je zult zien dat zodra je bovenop iemand staat hij nog wel 1 shot (en dat zelfs af en toe niet) , maar zodra je ook maar een klein beetje afstand neemt doe je helemaal geen damage meer. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![unknown (1)](https://user-images.githubusercontent.com/50420682/156336981-3b8254d4-d4e7-49fa-a464-25f74cc8fe82.png)
![4a8dea183a3c140b16db826f34ed3dfd](https://user-images.githubusercontent.com/50420682/156337001-64de9b23-50db-44d1-94e4-20bf4a58774b.png)

**Comment by niekschoemaker** [comment]
Ik heb de damage falloff aangepast van 5-20 meter naar 15-60 meter,

Voor een sawed off shotgun is dit alsnog belachelijk ver, maar denk dat dat zo wel iets beter werkt.
