### ISSUE TITLE
[FEATURE]: Supporter Suggestie: Boten kunnen duwen als je deze op het land vaart.

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1117]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Zoals de beschrijving al zegt, boten kunnen duwen vanaf het land. Als je deze op het strand oid heb gevaren, zou je hem zelf terug het water in kunnen duwen.

### Wat lost deze feature op?

Scheelt heel veel reports, en voegt een beetje extra roleplay toe.

**Comment by nickdb04** [comment]
@Ljosfari Deze zit er in dus kan gesloten worden
