### ISSUE TITLE
[FEATURE]: Server Supporter suggestie: Leaderbord bij de dragstrip resetten.

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1118]
### Beschrijf zo duidelijk mogelijk de feature

Leaderbord bij de dragstrip resetten. Er zijn veel records behaald met auto's die nog niet helemaal gebalanceerd waren. Eerlijke kans voor nieuwe auto's

### Wat lost deze feature op?

Na een lange tijd weer eens een vers begin. Kans voor nieuwe mensen om even op het scorebord te komen.

**Comment by niekschoemaker** [comment]
Done
