### ISSUE TITLE
[FEATURE]: Supporter Suggestie: Tiewrap on doors

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1120]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Dubbele deuren **Tijdelijk** vast kunnen maken door middel van Tiewraps. Bijvoorbeeld voordeur grote bank. 

Hierbij wel in acht genomen, dat politie deze eventueel open kan slopen door middel van deze kapot te schieten / 'Battering Ram'.

[Voorbeeld](https://media.discordapp.net/attachments/608089499049787412/948860678029078548/unknown.png)

### Wat lost deze feature op?

Voegt een extra beetje RP toe aan gijzelingen / overvallen etc .

**Comment by Solidhawk** [comment]
@Ljosfari hierbij een bestaand [Script](https://forum.cfx.re/t/release-esx-tiesdoor/1401950)

**Comment by Chang-nl** [comment]
Hey @Ljosfari, ik neem aan dat dit besproken en geaccepteerd is in staffoverleg?

**Comment by Ljosfari** [comment]
Yes klopt !

**Comment by Chang-nl** [comment]
Hey @Solidhawk,

Bedankt voor het aanmaken van de feature request!

Wij hebben besloten dat dit alleen voor criminelen toegankelijk zal worden, echter vragen we van jou om even te informeren bij de ca voor welk ganglevel dit beschikbaar moet worden. 

Alvast bedankt!

**Comment by Chang-nl** [comment]
Hey @Solidhawk,

Zou je een reactie kunnen geven op het bovenstaande bericht? Alvast bedankt!

**Comment by Solidhawk** [comment]
> 

Heb het in de groep gegooid. Je hoort van me.

**Comment by Chang-nl** [comment]
Hey @Solidhawk,

Feature is volledig geïmplementeerd! Graag hoor ik voor welk gang level dit beschikbaar moet worden.

**Comment by Chang-nl** [comment]
Hey @Solidhawk,

De tiewraps zijn nu beschikbaar voor level 1 gangs. Wil je dit anders zien? Laat het dan even weten!

**Comment by Chang-nl** [comment]
Gesloten i.v.m geen reactie

**Comment by iHax0rMC** [comment]
@Chang-nl we hadden aangegeven vanaf level 2, denk alleen dat die vergeten het is door te geven 😨

**Comment by Solidhawk** [comment]
> @Chang-nl we hadden aangegeven vanaf level 2, denk alleen dat die vergeten het is door te geven 😨 

Was nog niet zeker toen het doorgegeven werd aan mij, daarom wachtte ik nog even af.

**Comment by Chang-nl** [comment]
Hey @Solidhawk,

Hij zal worden aangepast naar lvl 2!
