### ISSUE TITLE
Sleepwagen kmar

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1121]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

er zijn in totaal 2 issues:

1. als je aan het rijden bent dan maakt hij random gewoon halve pitstops en gaat vol in de remmen, dit lijkt me niet geheel de bedoeling en is ook gevaarlijk voor verkeer achter je en bij belangrijke transporten.

2. Wagens die erop gezet worden verdwijnen 8 van de 10 keer en zijn helemaal nergens meer te bekennen dit maakt vrij weinig uit wat voor voertuigen 

### Wat hoorde er te gebeuren?

in ieder geval niet wat ik hier boven omschreef :D

### Wat veroorzaakt de bug?

Geen idee ik denk dat er bugs zijn in de sleepwagen

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by Attomn** [comment]
Heb het zojuist zover ik weet opgelost? Ben al een tijdje ermee aan het rondrijden en heb geen problemen meer ondervonden. Dit betekend wel dat de speedlimit van 75 -> 120 is gegaan.

**Comment by Ljosfari** [comment]
dit lijkt me gefixed zo

**Comment by PolitieTDA** [comment]
Even getest maar het probleem bestaat helaas nog steeds maar is nu verschoven. Sleepwagen rijdt nu 150-160 maar valt af en toe terug naar de limiter op 120. @Ljosfari @Attomn

**Comment by Attomn** [comment]
Heeft dit niet mogelijk te maken met de "verwarmingstoel" bug? Zie hier net een suggestie over langs komen en dat zou kunnen verklaren waarom hij door de speedlimiter heen trekt.
![afbeelding](https://user-images.githubusercontent.com/69365961/184616781-3afb8e60-fc97-40ee-af35-86ba73356497.png)

**Comment by Ljosfari** [comment]
kan hier nogmaals nar gekeken worden ?

**Comment by Ljosfari** [comment]
politie sleepwagen is niets mis mee, alleen de van de kmar, remt random af tot 75 km/h

**Comment by Chang-nl** [comment]
Het is opgelost na de herstart!
