### ISSUE TITLE
[FEATURE]: Garage achter Cardealer 7044

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1122]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Een garage platsing achter de Cardealer op postcode 7044. Dit met een groene, gele en rode circel zodat volledig gedespawnde auto's (wat soms gebeurt in het pand) er altijd uitgehaald kunnen worden.

idee van de plaatsing
https://prnt.sc/5qoWJ-6RoYBT
https://prnt.sc/Pxs-U351Ndi7

### Wat lost deze feature op?

Dit zorgt er voor dat alle werknemers kun auto weg kunnen zetten en geen prive auto's paraat hoeven te hebben staan om naar een andere garage te rijden.

Dit zorgt er voor dat er minder auto op de locatie zijn waardoor er minder lagg is.

**Comment by Ljosfari** [comment]
I.p.v hiervan gaan we een gele cirkel toevoegen bij de gemeente huis garage

**Comment by Rowdeeee** [comment]
Alleen het hele idee is dat je dat stuk dus niet hoeft te lopen of rennen waardoor er dus zo min mogelijk autos bij de dealer staan. 

Als dit dan alsnog bij het gemeente huis gezet word, dan blijven er alsnog autos daar staan die er niet hoeven te staan, aangezien het stiekem best ver is om naar het gemeente huis te lopen.

Vandaar dat ik die locatie had aangevraagt.

**Comment by Chang-nl** [comment]
Er zit een straat verder een garage in principe? daar kun je zelfs heen strompelen en je bent er zo...

**Comment by Rowdeeee** [comment]
Maar je lost op die manier nogsteeds niet op dat de autos despawnen omdat je uit de radius van ze gaat, omdat je andere autos moet pakken. Al word er een garage erachter geplaats waar ik het voorgesteld heb, blijf je in de raduis en worden de autos niet gedespawnd.

Dit is heel irritand en we kunnen niet 10 trv achter alkaar doen. Dus daarom is een garage achter dat pand een goede oplossing.
