### ISSUE TITLE
[BUG]: Als je de /rdoors openzet bij helikopters, dan gaat die veel harder.

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1123]
### Contact Details

Arjen#0001

### Kenteken van voertuig

N.v.t.

### Voertuig model

Voorbeeld: supervolito, polmav (kan zijn dat er nog meer models dit hebben).

### Omschrijf de bug

Als je in een helikopter zit waarbij de achterste deuren open kunnen, en je die ook open zet, dan ga je ineens heel veel harder.

### Repro

Pak een helikopter waarbij de achterste deuren open kunnen, ga vliegen en vergelijk de speed met /rdoors open en closed.

### Normaal gedrag

Hoort de snelheid niet de beïnvloeden, of realistisch gezien te vertragen.

**Comment by Chang-nl** [comment]
Is het al duidelijk of dit bij elke helicopter is?

**Comment by ARJ3N** [comment]
Voor zover ik weet wel. Werkt ook met de voorste deuren open trouwens. @Chang-nl

**Comment by CoffeeSipper** [comment]
Werkt bij elke helikopter.
