### ISSUE TITLE
[FEATURE]: zoekfunctie in telefoon toevoegen

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1125]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

Door vele contacten is het  vervelend om soms helemaal in het menu te scrollen. Scheelt een hoop als je een zoekfunctie hebt.

### Wat lost deze feature op?

Makkelijker bij contacten kunnen

**Comment by Chang-nl** [comment]
Hey @Goonsie, 

Bedankt voor het aanmaken van deze feature request.

Momenteel zijn we bezig met een nieuwe telefoon waar we dit wel in mee kunnen nemen. In de huidige telefoon gaan we dit niet toevoegen, vanwege het feit dat er een compleet vernieuwde versie van de telefoon aan komt. Bedankt voor je begrip.
