### ISSUE TITLE
[FEATURE]: persoon in kofferbak kunnen stoppen

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1126]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

Voegt een stukje roleplay toe. Tijdens een ontvoering kan je een zogezegd kofferbak ritje uitvoeren en deze persoon zonder dat hij gezien wordt kunnen vervoeren in je kofferbak

### Wat lost deze feature op?

Meer roleplay. En je hebt geen mensen meer die constant kunne roepen dat de ramen open staan waardoor de politie erop reageert. Misschien een idee om standaard naar whisper te gaan als je de kofferbak ingaat.

**Comment by CorruptSausage** [comment]
We hebben dit even overlegd, voor nu laten we dit er even uit aangezien we laatst ook al het hideintrash script hebben toegevoegd.
