### ISSUE TITLE
[FEATURE]: opslag voor non officials(warenhuis)

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1127]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid geven aan non officials om een warenhuis te kunnen kopen voor een bepaald bedrag. Net als de loodsen zal je deze moeten zoeken en een maximum van bijvoorbeeld 1000 dingen op te kunnen slaan. Nadat je loods is ge upgraded met 1000 verhogen bijvoorbeeld. Enz enz

### Wat lost deze feature op?

Meer rp. Meer opslag. Ook non official hebben een plek om spullen op te slaan.

**Comment by niekschoemaker** [comment]
Duplicate of #1092
