### ISSUE TITLE
[FEATURE]: flitsmeister app/item

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1128]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid om bij bepaalde winkels ( niet alle) een flitsmeister /flitspaal verklikker te kunnen kopen. 

### Wat lost deze feature op?

Stukje technologie. We leven tenslotte in 2022.

**Comment by Hellie94** [comment]
Gewoon leren waar de flitspalen zijn :P

**Comment by niekschoemaker** [comment]
Heb ik al 5x afgewezen, dus nee.
