### ISSUE TITLE
[FEATURE]: deepweb af kunnen lezen

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1129]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

Net zoals dat je het laatste radio frequentie kan afluisteren, een optie toevoegen om het laatste deepwebkanaal waarin berichten zijn verstuurd af te kunnen lezen.

### Wat lost deze feature op?

Meer rp.

**Comment by niekschoemaker** [comment]
Ik denk dat dit de communicatie voor gangs zo goed als onmogelijk gaat maken als we dit zouden toevoegen
