### ISSUE TITLE
[FEATURE]: visite kaartjes toevoegen met tel nummer

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1130]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

- Telefoon gegevens makkelijker uitwisselen onderling. 
Dit zal hetzelfde uit kunnen zien als een broodje geven aan iemand.

Voorheen kon je alleen bij je F2 menu je broekzakken zien. Nu is dat verdeeld tot ‘broekzakken’ en ‘portemonnee’.

Vanuit je portemonnee kun je nu een ‘visitekaartje’ geven. Dit zal hetzelfde concept zijn als een rijbewijs of id-kaart. Alleen zie de naam en telefoonnummer van persoon. 

### Wat lost deze feature op?

-Onnodig /me gebruik
- Makkelijker en sneller
- verbeterd en vergroot de rp mogelijkheden.

**Comment by Willem-Dekker** [comment]
geef je het dan ook of is het meer een item wat je laat zien?

**Comment by Goonsie** [comment]
Goeie opmerking. Misschien gewoon laten zien net als een rijbewijs.
