### ISSUE TITLE
[FEATURE]: kleren kunnen kopen en tanken met bankgeld

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1131]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

Kunnen tanken en kleren kopen met geld op je rekening.       

### Wat lost deze feature op?

Het is realistischer dat je spullen kan halen met je bankpas en het wordt makkelijker want dan hoef je niet heletijd heen en weer te lopen om geld te pinnen.

**Comment by niekschoemaker** [comment]
Is gefixed
