### ISSUE TITLE
[FEATURE]: portofoon volume aan kunnen passen.

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1132]
### Contact Details

Anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

- Porto zachter kunnen zetten, door bijvoorbeeld in portomenu 1 t/m 5 als volumekeuze 

### Wat lost deze feature op?

- Je hoeft niet uit de porto te gaan als het te druk is, maar je kan hem ook wat zachter zetten om rp verstoring

**Comment by Chang-nl** [comment]
Yes na de volgende restart zit dit erin!
