### ISSUE TITLE
[FEATURE]: Driftmodus Keybind aanpassen

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1133]
### Contact Details

anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

Nu staat driften op SHIFT keybind. deze graag switchen naar een andere keybind.
Bijvoorbeeld een dubbele keybind zoals het switchen van whisper naar normal.

### Wat lost deze feature op?

Dat je tijdens het rijden niet onverwachts in de driftmodus komt.

**Comment by Chang-nl** [comment]
Yes na de volgende restart is het (Left-shift + N)
