### ISSUE TITLE
[Bug]: Berichten zonder telefoon

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1134]
### Contact Details

SolidHawk#0929

### Wat gebeurde er?

Je krijgt SMSjes en Deepweb berichten zonder telefoon.

### Wat hoorde er te gebeuren?

Geen berichten. Is niet echt logisch als je geen telefoon hebt.

### Wat veroorzaakt de bug?

Onbekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Weet niet hoe.

**Comment by niekschoemaker** [comment]
Is gefixed
