### ISSUE TITLE
Feature: TRV cooldown verkorten 

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1135]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

De cooldown voor trv verkorten. Dit tijdelijk tot de bug met de loodsen en appartementen opgelost is.

### Wat lost deze feature op?

Mensen moeten vaak trv gebruiken als ze hun loods of appartement uitkomen. Dit werkt soms de eerste keer niet, en anders staan ze wel heel lang te wachten.

**Comment by niekschoemaker** [comment]
Is aangepast naar 10 seconden
