### ISSUE TITLE
[FEATURE]: Golfclub zichtbaar maken op de rug

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1137]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Golfclub is nu niet zichtbaar op de rug. Je kan deze gewoon wegstoppen in je broekzak. Om het wat realistischer te maken, deze toch ook laten zien, net als de knuppel.

### Wat lost deze feature op?

Meer realisme voor het slagwapen. Niet logisch dat je deze zo weg kan stoppen.

**Comment by Chang-nl** [comment]
Yes dit is na de komende restart geregeld!
