### ISSUE TITLE
[FEATURE]: MAX. 2 voertuigen op 2e hands kunnen zetten. 

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1138]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

MAX. 2 voertuigen op 2e hands kunnen zetten per persoon. Als er al 2 voertuigen van de desbetreffende persoon op de 2e hands of in de wachtrij krijgt de persoon een melding dat er al teveel voertuigen van hem erop staan.

### Wat lost deze feature op?

Dit zorgt er voor dat mensen niet 20 de zelfde voertuigen (Denk hierbij aan Campers, busjes enz) erop zetten, zodat niet heel de 2e hands vol staat van 1 persoon. 

Zo krijgen andere mensen ook de kans om hun auto sneller te verkopen.

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart
