### ISSUE TITLE
/cardealer toevoegen aan twitter voor auto verkoop

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1139]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

om de auto handel uit twitter weg te halen en overzichtelijk te krijgen een extra command toevoegen voor de verkoop van auto's

### Wat lost deze feature op?

dan word twitter weer normaal voor evenementen

**Comment by niekschoemaker** [comment]
Zit erin.

Je kunt advertenties in en uitschakelen met: /ads_subscribe

En voor het plaatsen van zo'n tweet kun je: /cardealer gebruiken
