### ISSUE TITLE
Toevoegen DJI bus voor tranporten naar gevangenis ipv standaard politie vito

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1140]
### Contact Details

Freddy Krueger

### Beschrijf zo duidelijk mogelijk de feature

Ik hoopte dat voor de Kmar/politie de volgende toevoeging geplaatst kon worden:

https://nl.gta5-mods.com/vehicles/mercedes-sprinter-dji-vervoer-els

het is voor roleplay beter om te zien wanneer er gevangen worden getransporteerd, hij is mooier als de standaard vito bus voor personen transport van politie, en dit zou dan alleen een toevoeging zijn voor de kmar gevangenetransport... ook als je een gevangene er dan uit wil halen dat je thermiet moet gebruiken om die persoon eruit te halen

### Wat lost deze feature op?

Hij voegt roleplay toe op duidelijk onderscheid dan vervoer met de vito, en het is realistischer kwa uiterlijk

**Comment by ARJ3N** [comment]
Is al eens getest door @walvisgedaan als ik me niet vergis, maar waren proberen met het model.

**Comment by Lorenzo3001** [comment]
Het model heeft inderdaad wat problemen en vind hem persoonlijk niet tda waardig.

**Comment by Jaydpn** [comment]
> Het model heeft inderdaad wat problemen en vind hem persoonlijk niet tda waardig.

Maar de KMar heeft wel de pakjes er voor, dan zou zo'n bus toepasselijk zijn eerder?

**Comment by Lorenzo3001** [comment]
> 

Klopt maar het model is te slecht gemaakt voor tda dus deze zal hem niet worden.
