### ISSUE TITLE
[FEATURE]: Volledige naam voertuig weergeven op Tweede hands

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1141]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Hele naam en model van voertuig weergeven op tweede hands. Zodat je niet per ongeluk verkeerde versie koopt, ook al lijken ze op elkaar.

### Wat lost deze feature op?

Voorkomt het kopen voor verkeerde variant auto. Als deze heel erg op elkaar lijkt.

**Comment by niekschoemaker** [comment]
Zit erin
