### ISSUE TITLE
[FEATURE]: Werkende kabelbaan Mount Chilliad

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1142]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Werkende kabelbaan van Paleto naar Mount chilliad. Mooie toevoeging als dit niet te veel problemen geeft voor de stad. Enkel laten bewegen als iemand daadwerkelijk naar boven wilt. ( Press E ).

[Script](https://forum.cfx.re/t/release-functional-pala-springs-aerial-tramway/188171)

### Wat lost deze feature op?

Eigenlijk enkel leuke interactieve toevoeging. Mensen die parachute willen springen hoeven niet met de motor naar boven te rijden, brengt wat meer leven in die hoek voor rustige RP's.

**Comment by Nander0320** [comment]
Auto's syncen helaas niet.
