### ISSUE TITLE
[Bug]: Artikel 16 - Karakter breken (ooc)

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1143]
Ik zag een foutje in het wetboek en mij werd er verteld om een github hiervoor te maken dus bij deze, ik wou even melden dat in artikel 16 karakter breken bij lid 5 een spelfoutje staat. Er staat "bestratft" zou dit aangepast kunnen worden naar "bestraft".

**Comment by niekschoemaker** [comment]
Hiervoor moet je een pull request bij de APV maken.

https://github.com/Tedeapolis/wet-en-regelgeving/

Als je daar het betreffende bestand opent kun je gewoon op de edit knop klikken om het bestand aan te passen en dan een pull request hiervan maken.
