### ISSUE TITLE
[FEATURE]: Permissies voor vlieginstructeurs voor ATC

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1144]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Destijds is deze feature aangevraagd ([#593](https://github.com/Tedeapolis/development/issues/593)). Echter werkt het al enige tijd niet meer, dus bij deze een nieuwe feature request. 

De mogelijkheid toevoegen om als Vlieginstructeur ten alle tijden de ATC te joinen zowel binnen als buiten een vliegtoestel.

### Wat lost deze feature op?

Als vlieginstructeur is het toegestaan om te reageren in de ATC en de controle over het luchtruim te bewaren. Op dit moment wordt er niet gereageerd in de ATC tenzij een vlieginstructeur toevallig aan het vliegen is. Door dit te implementeren kunnen instructeurs de ATC joinen zonder in een vliegtoestel te zitten om zo het luchtruim in de gaten te houden.

**Comment by niekschoemaker** [comment]
Je kunt toch gewoon /atc doen en dan handmatig even 326 joinen?

**Comment by AdventurePandah** [comment]
Ah, het was voor ons onbekend dat er eerst /atc uitgevoerd moest worden. Het werkt inderdaad :D
