### ISSUE TITLE
[FEATURE]: 2de hands zin veranderen bij auto

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1145]
### Contact Details

Devv#4532

### Beschrijf zo duidelijk mogelijk de feature

Nu dat alles een leuk kleurtje heeft, is het mogelijk dat het bovenste bedrag dat ervoor vraagprijs of een kleur aan word gegeven? voor meer overzicht. 

https://prnt.sc/FZYqD1Pxub26

### Wat lost deze feature op?

overzicht.

**Comment by Chang-nl** [comment]
Vraagprijs heeft een groen kleurtje na de komende restart!
