### ISSUE TITLE
[Bug]: Vliegtuig motor valt uit wanneer S ingedrukt

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1147]
### Contact Details

Bas#6430

### Wat gebeurde er?

Ik wilde landen met een Shamal. Echter zodra ik de wielen op de grond had en wilde afremmen met S, viel de motor uit. Hierdoor reed ik te ver door en crashte ik.

### Wat hoorde er te gebeuren?

De motor hoort niet uit te gaan en je hoort af te remmen tot stilstand.

### Wat veroorzaakt de bug?

Pak een Shamal, stijg op en probeer vervolgens te landen en af te remmen met S.
Mogelijk is dit sinds deze github commit.
![image](https://user-images.githubusercontent.com/47216413/157334297-f349983f-1405-4cba-841f-dc9d30f96300.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Geen logbestanden, wel een video: https://youtu.be/IR3a4xQJvPY

**Comment by Chang-nl** [comment]
Is gefixt!
