### ISSUE TITLE
[Bug]: Staff on duty klopt niet

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1148]
### Contact Details

Hellfire

### Wat gebeurde er?

Er zijn er bijvoorbeeld maar 2 on duty en dan zie je er hier 6.

### Wat hoorde er te gebeuren?

Dynamisch aangeven hoeveel er on duty staan. 

### Wat veroorzaakt de bug?

Inloggen, onduty gaan en dan vergelijken met de getonduty. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Relevante log bestanden

![Staff ding](https://user-images.githubusercontent.com/77858957/157474754-b9dbacbf-b9ef-4e97-b545-289a376d5f6e.PNG)

**Comment by niekschoemaker** [comment]
is gefixed
