### ISSUE TITLE
[FEATURE]: Havenjob met vorkheftruck eruit halen

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1149]
### Contact Details

Hellfire

### Beschrijf zo duidelijk mogelijk de feature

Deze oude job eruit halen omdat het npc's veroorzaakt en fouten in bepaalde scripts. 

### Wat lost deze feature op?

Wat minder ellende in de haven als iemand die job activeert.

**Comment by niekschoemaker** [comment]
Yes done
