### ISSUE TITLE
[FEATURE]: Aanpassing  schietmelding

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1150]
### Contact Details

Misterm#0001

### Beschrijf zo duidelijk mogelijk de feature

In verband met een feature request zijn laatst de meldingen veranderd omtrent vuurwapens. 
In elke situatie komt naar voren dat er is geschoten met "een vuurwapen" waarbij het type niet meer wordt vermeldt.
Nu is het echter zo dat, gezien het kaliber, onduidelijk is wat de grote van het wapen is, en hoeveel man hierop aangestuurd moet worden. Denk aan het aantal agenten, dsi, e.d.

In deze feature request stond naar mijn weten dat er onderscheid gemaakt zou moeten worden tussen automatisch vuur, en enkel vuur. Bij deze dus de aanvraag tot de volgende meldingen:

Voor handvuurwapens een zin als "Er is geschoten met een vuurwapen"
- M1911
- Beretta
- Sawed-off shotgun

Voor automatische vuurwapens een zin als "Er is geschoten met een automatisch vuurwapen"
- AK-47
- AK-12
- AK-74u
- Skorpion

### Wat lost deze feature op?

Voorkomen dat de hele bende op elke schietmelding afgaat

**Comment by niekschoemaker** [comment]
Zit erin
