### ISSUE TITLE
Naam van nieuwe loodsen aanpassen

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1152]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Kreeg een report binnen dat jongens een loods hadden gekocht.
Er stond een pilletje bij, alleen ze hebben geen idee wat ze gekocht hebben. Er staat Loods kopen bij, maar niet specifiek wat dit inhoud.

Je moet dus een flink bedrag betalen om te weten wat je koopt, kan dit aangepast worden?

### Wat hoorde er te gebeuren?

![image](https://user-images.githubusercontent.com/95652643/157623271-e5c0e23b-7244-4dc9-b059-3bdba6f0ad04.png)

### Wat veroorzaakt de bug?

Gewoon een andere naam geven.

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

geen

**Comment by TDALionskull** [comment]
Loods zit hier.

![image](https://user-images.githubusercontent.com/95652643/157625410-6a045e15-656e-4ced-aa23-8b056f98b681.png)

**Comment by TDALionskull** [comment]
Wil ook even melden als je er 1 koopt, dat de cirkels in de lucht hangen. 
Net boven je hoofd.

**Comment by niekschoemaker** [comment]
Yes done
