### ISSUE TITLE
[Bug]: report die dubbel binnenkomt

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1153]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je ingame /report doet krijg je twee keer jouw bericht te zien links boven.

### Wat hoorde er te gebeuren?

Er hoort oorspronkelijk komt er 1 report van je zelf binnen, als je /report gebruikt

### Wat veroorzaakt de bug?

Als je /report gebruikt en dan iets typt zie je dubbel jouw report voorbij komen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Is gefixed
