### ISSUE TITLE
[Bug]: AK-12 slechte prestaties

### ISSUE THREAD

**Issue by ChrisCircka** [Tedeapolis/development#1154]
### Contact Details

Circka#9764

### Wat gebeurde er?

We merken dat de nieuwe AK-12 die is toegevoegd niet voldoet aan de prijs/kwaliteit. Wapen kost meer dan de normale AK maar heeft slechtere recoil, slechtere range en lagere damage.

### Wat hoorde er te gebeuren?

Wij hadden verwacht dat deze AK-12 beter zou zijn dan de normale AK maar dit blijkt tegen te vallen. De inkoopprijs is 50k meer dan de normale AK maar is eigenlijk alleen maar slechter. 

### Wat veroorzaakt de bug?

Waarschijnlijk zijn het gewoon settings die aangepast moeten worden. Met Frequentie hoog bedoel ik dat iedereen die een AK-12 heeft er last van heeft. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://cdn.discordapp.com/attachments/932605234210017290/951244202564546591/unknown.png

**Comment by niekschoemaker** [comment]
Volgende keer graag zelf even een passende titel invoeren, maakt de issues nogal onoverzichtelijk

**Comment by niekschoemaker** [comment]
En hoezo lagere damage? Want voor zover ik weet staat de damage precies hetzelfde

**Comment by ChrisCircka** [comment]
Dit is een voorbeeld van iemand die met de AK12 schoot. Wellicht was dit dan ongelukkig maar aangezien het wapen iets duurder is, is het mogelijk om de damage ook iets hoger te zetten dan de normale AK?

https://media.discordapp.net/attachments/932605234210017290/951244202564546591/unknown.png?width=1440&height=166

**Comment by niekschoemaker** [comment]
![image](https://user-images.githubusercontent.com/32094562/158484863-39221af1-ac68-476a-bbbf-bb8b1404d1b8.png)

Zoals hier te zien is de performance standaard gewoon exact hetzelfde, in die combatlog daar zijn het allemaal hits in ledematen, daar is de damage een heel stuk lager

**Comment by Lorenzo3001** [comment]
@niekschoemaker Het is een MK2 wapen en ook duurder dus zou hij niet juist iets meer damage moeten doen? De Pistol mk2 doet namelijk ook een stuk meer damage dan de normale m19. 
Ook is volgens mij de range minder dan de normale ak en vinden veel mensen de recoil wat te groot.

**Comment by niekschoemaker** [comment]
> @niekschoemaker Het is een MK2 wapen en ook duurder dus zou hij niet juist iets meer damage moeten doen? De Pistol mk2 doet namelijk ook een stuk meer damage dan de normale m19. Ook is volgens mij de range minder dan de normale ak en vinden veel mensen de recoil wat te groot.

De range is hoger dan die van de normale AK, de recoil is exact hetzelfde.
Verder heeft de standaard pistol dezelfde damage als de pistol mk2.
Verder ga ik voor de recoil binnenkort nog even attachement support toevoegen.
