### ISSUE TITLE
[Bug]: ATC - Spelers hoorbaar na praten in ATC

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1155]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer een speler praat in de ATC en vervolgens in het toestel normaal praat, is deze speler nog steeds hoorbaar in de ATC.

### Wat hoorde er te gebeuren?

Persoon hoort enkel in de ATC hoorbaar te zijn als deze persoon ook daadwerkelijk in de radio praat.

### Wat veroorzaakt de bug?

Ga in een heli, open de ATC en zeg daar iets in. Praat vervolgens normaal en er is een kans dat andere spelers kunnen je horen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Ehh, ik kon deze issue zelf niet replicaten, echter wel dat de hele atc uberhaupt niet werkt zolang je niet in de radio zit, heb dit ondertussen even aangepast
