### ISSUE TITLE
[Bug]: Spelers gaan dood in helikopter shop

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1156]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer iemand in een helikopter shop zit dan bugged zijn speler op de plek waar helikopters spawnen. Wanneer iemand dus een helikopter spawned, gaat deze persoon dood door de draaiende wieken.

### Wat hoorde er te gebeuren?

Het beste is als de persoon invisible wordt gemaakt netzoals bij de cardealer. Dat lost dit hele probleem op.

### Wat veroorzaakt de bug?

Ga in de heli shop en laat iemand anders vervolgens een heli pakken.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
