### ISSUE TITLE
[FEATURE]: Mumble_reconnect command vervangen

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1157]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

/Mumble_reconnect vervangen naar /mr . Word vaak gebruikt.

### Wat lost deze feature op?

Sneller reconnecting van de voice.

**Comment by niekschoemaker** [comment]
In welke situaties wordt dit command gebruikt? Omdat eerder de achterliggende issues even gefixed moeten worden 🤔

**Comment by Solidhawk** [comment]
> In welke situaties wordt dit command gebruikt? Omdat eerder de achterliggende issues even gefixed moeten worden 🤔 

Komt nog wel eens voor in scenario's dat ik is moet vragen of mensen eerst mumble_reconnect willen doen, en ze daarna wel hoor. In suggesties zag ik dat meerdere mensen last van hadden. Daarom deze suggestie, en of dat dan aan bijvoorbeeld de internet van de persoon ligt, of niet. Is lastig te achterhalen natuurlijk
