### ISSUE TITLE
[Bug]: Haaien vissen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1158]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik was aan het vissen voor haaien, vervolgens krijg je een nummer wat normaal is. Maar als je meerdere malen vist na het vangen van haaien gebeurd er iets raars dan krijg je een nummer vang je iets en krijg je na een seconden gelijk een nieuwe nummer die niet werkt of dergelijke (het komt dubbel binnen, zie screenshot)
![haai](https://user-images.githubusercontent.com/101106299/157883850-eba4e683-4766-4e66-a4e7-1bc0917a1afe.PNG)
)

### Wat hoorde er te gebeuren?

Er hoort normaal gezien 1 nummer te komen, en de tweede nummer die komt werkt niet. Ik weet niet als de tweede nummer de bedoeling is of als de tweede nummer moet werken of niet.

### Wat veroorzaakt de bug?

Ik ga in stappen uitleggen wat ik deed: 

1. Ik ging met mijn longfin op zee.
2. Vervolgens pak ik mijn vishengel met schildpad aas.
3. Ik probeer een schildpad te vangen om vervolgens een haai te vangen.
4. Maar dan krijg je gelijk die 2 nummers (glitch / bug ?)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn

**Comment by CalRayy** [comment]
Volgens mij is het gefixt, thanks <3
