### ISSUE TITLE
[Snuffelen huisinbraak]: 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1160]
### Contact Details

Vayen#6904

### Wat gebeurde er?

Ik was Reports aan het doen en ik kreeg van verschillende mensen te horen dat huisinbraak niet werkt. 
Er word dan volgens de speler een cooldown aangegeven van 1865756 minuten. 
En je kunt dan niet verder. 

### Wat hoorde er te gebeuren?

Het huis te kunnen doorsnuffelen. 

### Wat veroorzaakt de bug?

Door een huisbraak in te doen, dan krijg je de melding. ( zelf niet uitgetest dit is n.a.v. reports in game)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Yes, is gefixed na volgende restart
