### ISSUE TITLE
[Bug]: Bugatti EB110 Supersport

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#1161]
### Contact Details

AntonMoskvin#3144

### Wat gebeurde er?

Voor heen waren de velgen mooi grijs metaal kleur achtig
https://prnt.sc/MYDE_zhgDK4O

Nu zien ze er zo uit

https://prnt.sc/er04TXs4_ihU

Daarnaast is de dirt mapping ook heel erg apart, als ik een stuk rijd ziet die er inplaats van vel geel zo uit

https://prnt.sc/rVNEvkG0K44G

### Wat hoorde er te gebeuren?

De velgen horen de originele look te hebben

De dirt mapping hoort minimaal te zijn en niet de hele auto te bedekken

### Wat veroorzaakt de bug?

Door rond te rijden word die heel erg vies

### Frequentie van de bug

Altijd

**Comment by niekschoemaker** [comment]
De velgen hebben een kleur gekregen, dus kan zijn dat he tdaardoor komt? Kun je nu niet gewoon de kleur aanpassen in de mod shop?

**Comment by Lorenzo3001** [comment]
De dirtmap ziet er bij mij niet raar uit dus kan wellicht met je settings of visual pack indien je de hebt te maken hebben. De velgen zijn inderdaad een feature dus die kun je zelf aanpassen.
