### ISSUE TITLE
[FEATURE]: Max aantal wapens dat een agent op een dag kan pakken.

### ISSUE THREAD

**Issue by ChrisCircka** [Tedeapolis/development#1162]
### Contact Details

Circka#9764

### Beschrijf zo duidelijk mogelijk de feature

Agenten kunnen per dag nog maar maximaal 3 wapens pakken. Als een agent dus doodgaat met zijn wapen kan hij er vervolgens nog maar 2 pakken enzovoort. 

### Wat lost deze feature op?

Dit zorgt ervoor dat agenten wellicht wat meer waarde hechten aan hun wapen. Op dit moment kost een wapen voor de politie 3k maar kunnen die oneindig kopen op een dag. Met de nieuwe feature moeten agenten dus wat meer nadenken over wanneer ze hun wapen wel of niet gebruiken. Als ze op een dag 3 wapens zijn verloren kunnen ze nog wel gewoon reguliere diensten draaien alleen dan zonder vuurwapen en alleen een taser.

**Comment by Ljosfari** [comment]
Is besproken in het laatste staffoverleg en mag ook doorgevoerd worden

**Comment by Tom974** [comment]
Zal na de restart ingame zitten.
