### ISSUE TITLE
[FEATURE]: Nieuwe Modshop

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1163]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Heel veel mensen (server supporter suggestie) zouden graag Benny's garage als modshop willen binnen in de stad, ik moet eerlijk toegeven het lijkt wel binnen op een modshop. Dit lijkt me ook super leuke toevoeging. Alleen is mijn vraag is dit mogelijk? (Zie screenshots)

![image](https://user-images.githubusercontent.com/101106299/158079897-f7e0c1d1-8e12-4233-8f37-e067031e8fbc.png)
![image](https://user-images.githubusercontent.com/101106299/158079900-c5267793-d254-4ea0-a580-c3565efc4014.png)

### Wat lost deze feature op?

Dit kan drukte verminderen bij de andere modshops, plus frustraties dat sommige mensen moeten wachten dat ze aan de kant moeten gaan etc.

**Comment by Chang-nl** [comment]
toegevoegd!
