### ISSUE TITLE
[Bug]: Telefoon

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1164]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Goedenavond, ik zat contacten te wijzigen waar ik eerst een " ! " had naar zonder " ! ". Maar toen ik dat deed bleef mijn telefoon hangen op mijn beeld en kon ik het niet weghalen of dergelijke en dit heb elke keer voor een bepaalde reden. (zie video: https://youtu.be/UuXA8NaCsL0).
Ik heb dit ook geprobeerd zonder dat ik in voertuig zat, maar helaas blijft het herhalen. Daarnaast gebeurd dit constant ik dacht eerst dat het aan mij lag, maar andere mensen hebben dit ook.

### Wat hoorde er te gebeuren?

Telefoon moest uit mijn beeld gaan, maar dat gebeurd niet

### Wat veroorzaakt de bug?

Contact wijzigen waar een " ! " voor staat naar geen " ! " (zie clip: https://youtu.be/UuXA8NaCsL0)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t. (heb gekeken in f8 maar zag totaal niets)

**Comment by Chang-nl** [comment]
Dit probleem is dus echt alleen met een uitroepteken, of uberhaupt als je een contact wilt wijzigen?

**Comment by CalRayy** [comment]
Dit probleem is alleen als ik een contact die een uitroepteken heeft naar geen uitroepteken verander.

**Comment by niekschoemaker** [comment]
Kun je hier het log bestand even van sturen?

kan de bug zelf namelijk niet replicaten als ik exact hetzelfde contact maak en exact hetzelfde doe.

**Comment by CalRayy** [comment]
Waar kan ik de log bestand vinden ?

**Comment by Tom974** [comment]
Heb hier zelf ook last van, ik krijg wel logs in m'n f8 terug; 
![image](https://user-images.githubusercontent.com/55812394/161396760-f70c63cc-bb0a-4391-9700-6d543672e7c7.png)

**Comment by Willem-Dekker** [comment]
in overleg gesloten omdat issue niet meer aanwezig is.
