### ISSUE TITLE
[FEATURE]: Voertuig schoon maken

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1166]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Goedenavond, ik zou graag iets willen voorstellen en dat gaat als volgt:

Als het regent dat je voertuig iets schoner word, aangezien in het echt voertuigen vol met stof zit bijvoorbeeld en als het dan regent zou het stof in het echt in principe ook langzaam aan weggaan door het regen (water). Dit leek mij een toffe idee, alleen weet ik niet als dit mogelijk is 😄.

### Wat lost deze feature op?

Meer realisme in de stad en zo kan je voertuig langzaam aan ook schoner worden. Het voertuig hoeft niet gelijk schoon te worden, het mag de effect hebben net zoals het vies worden van een voertuig 😄.

**Comment by niekschoemaker** [comment]
Is al eerder voorgesteld.

Als je in het echt in de regen rijdt wordt je auto juist viezer, omdat dan al het zand van de weg los komt wat dan (vooral op de achterkant) van je auto terecht komt.
In de winter is dit helemaal erg door zout ed.
