### ISSUE TITLE
[Wapen cooldown]: leg damage

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1167]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staffoverleg op 13-3-2022 is er besproken over het schieten in je been, vervolgens val je neer. En om No value of Life tegen te gaan. 
Is er overlegd voor een optie om dan een tijdelijke cooldown van ongeveer 10 a 15 seconden te doen. En anders of de lig emote iets langer duurt. 

### Wat lost deze feature op?

Door een cooldown erop te zetten met een timer om je wapen te gebruiken. 
En of een andere optie om het liggen nadat je in je been bent beschoten iets langer te laten duren.

**Comment by niekschoemaker** [comment]
Hier was naderhand een andere oplossing voor voorgesteld, deze is nu toegepast.

Je hebt nu 30 seconden lang nadat je dus neervalt enorme weapon sway waardoor richten met je wapen heel moeilijk wordt.
