### ISSUE TITLE
[Bug]: Confisqueren werkt niet op helikopters/vliegtuigen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1168]
### Contact Details

Arjen#0001

### Kenteken van voertuig

N.v.t.

### Voertuig model

N.v.t.

### Omschrijf de bug

Confisqueren is niet mogelijk bij helikopters en vliegtuigen. Je krijgt dan een foutmelding dat het voertuigen verplaatst is en daarom het niet werkt, ook al staat die stil (zie foto).
![image](https://user-images.githubusercontent.com/93579695/158258458-c5457ecf-797a-4a1c-8445-13562e982c47.png)

### Repro

Spawn een helikopter / vliegtuig en probeer die te confisqueren via politie F6 menu.

### Normaal gedrag

Je zou die voertuigen moeten kunnen confisqueren.

**Comment by Chang-nl** [comment]
yes, na volgende restart is het opgelost
