### ISSUE TITLE
[FEATURE]: Medische spullen in object spawner politie

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1170]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij naast de politie objecten ook graag wat medische spullen kunnen spawnen, zoals de ambulance heeft. Zie onderstaande foto. 
![image](https://user-images.githubusercontent.com/93579695/158259487-cc72c7f9-7239-4b72-bb4c-eb9d7868edfd.png)

### Wat lost deze feature op?

De politie voert vaak eerste hulp uit bij personen. Dit zou dit type roleplay bevorderen.

**Comment by Willem-Dekker** [comment]
Aanpassingen staan een pr voor open dus zullen er snel in komen
