### ISSUE TITLE
[Bug]: Spelling op politiepas (Very low priority)

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1171]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Legitimatiebewijs staat fout gespeld. 
![image](https://user-images.githubusercontent.com/93579695/158261392-590777d8-e92f-4340-b947-a14c01af8b85.png)

### Wat hoorde er te gebeuren?

Er hoort legitimatiebewijs te staan.

### Wat veroorzaakt de bug?

N.v.t.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

**Comment by brothasx** [comment]
Politiepas en presspas zijn gefixed bij de volgende github commit
