### ISSUE TITLE
[FEATURE]: Extra opslagcirkel in HB bij arrestanten ingang

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1172]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij een opslagcirkel voor de politie zien op de volgende locatie:

X: -1072 Y: -829 Z: 5.48 H: 131

![image](https://user-images.githubusercontent.com/93579695/158262305-63bd6476-315d-4bee-93ce-a113ffca002d.png)

### Wat lost deze feature op?

De arrestanten komen via deze kant naar binnen en worden veelal hier gefouilleerd. Dan is het handig dat je gelijk hier de spullen van de verdachte kan wegleggen. Hier staan ook kluisjes, te zien op de foto.

**Comment by Chang-nl** [comment]
Na restart zit dit erin!
