### ISSUE TITLE
[FEATURE]: Animatie toevoegen aan het uithalen en wegstoppen van een skorpion

### ISSUE THREAD

**Issue by musician1011** [Tedeapolis/development#1173]
### Contact Details

Musician1011#1260

### Beschrijf zo duidelijk mogelijk de feature

Wanneer je de skorpion trekt/wegstopt, komt die schijnbaar uit het niets tevoorschijn/verdwijnt die in het niets als je 'm weer weg stopt.

### Wat lost deze feature op?

iets meer realisme aan het hanteren van de skorpion, nu haal je die boven in een fractie van een seconde (geeft onrechtstreeks ook voordeel tijdens scenario's)

**Comment by Chang-nl** [comment]
Zit erin!

**Comment by Chang-nl** [comment]
Zit erin!

**Comment by Chang-nl** [comment]
Ho oeps verkeerde knop
