### ISSUE TITLE
[Bug]: Appartement

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1174]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je stopt met je voertuig voor je appartement en je gaat in je appartement. Vervolgens er weer uit moet je altijd /trv doen als je alleen bent waarom weet ik niet. Ik dacht ik meld het even.

### Wat hoorde er te gebeuren?

Je hoort eigenlijk gelijk in je voertuig te kunnen i.p.v. /trv doen elke keer als je uit je appartement gaat.

### Wat veroorzaakt de bug?

1. Je parkeert je auto voor je appartement
2. Je gaat in je appartement
3. Je gaat naar je opslag om iets eruit te halen bijvoorbeeld
4. Vervolgens ga je uit je appartement
5. Nu moet /trv doen, aangezien je voertuig nu bugged is of dergelijke

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Duplicate of #1053
