### ISSUE TITLE
[FEATURE]: Nieuwe Modshop

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1175]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Er sindskort een nieuwe Modshop, maar daar kan je helaas geen /repareer gebruiken. Is dit mogelijk om dit te kunnen ? 

### Wat lost deze feature op?

Een optie om te repareren, als er geen anwb is. Aangezien er een nieuwe modshop is leek me dit ook handig om dat daar toe te voegen. (zie screenshot over welke modshop je geen /repareer kan gebruiken.)
![image](https://user-images.githubusercontent.com/101106299/158465395-ac232ab0-187d-4e3b-9fc8-c5cd8cd9ee82.png)

**Comment by Ljosfari** [comment]
zit er in

**Comment by CalRayy** [comment]
De /repareer zit er nog niet in, ik krijg de melding "ga naar de dichtsbijzijnde modshop"
