### ISSUE TITLE
[FEATURE]: Bo-Rent

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1176]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Er kan in de Bo-rent van de cardealer, maar 5 KG in. Is het mogelijk om dit aan te passen, ik had misschien in gedachten om dit te veranderen naar 80 KG lijkt mij het meest realistische aanpassing.   Als dit niet mogelijk is, zo het niet uitmaken (leek me wel tof 😃 ).

### Wat lost deze feature op?

Dat de Bo-Rents kunnen gebruikt worden voor andere dingen zoals een bedrijfje. Ik heb sindskort samen met een groepje een bedrijfje voor te slepen / repareren van voertuigen en dit leek me handig als we daar een reparatie kit en zaklampen in de kofferbak konden doen. Dit is helaas niet mogelijk aangezien er 5 KG in en dat is eigenlijk 1 reparatie kit. Vandaar deze Github om te vragen, als dit mogelijk is 😄.

**Comment by MisterM02** [comment]
5kg is expres gedaan naar mijn weten

**Comment by niekschoemaker** [comment]
Done, heb nu illegale voowerpen geblokkeerd in werkvoertuigen en het gewicht verhoogd
