### ISSUE TITLE
[FEATURE]: cooldown /repareer

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1177]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Deze functie vanaf 0 ANWB'ers te kunnen gebruiken zonder cooldown.

### Wat lost deze feature op?

Als er geen ANWB'ers in dienst zijn, bijvoorbeeld in de nacht. Hoef je niet te wachten als je voertuig weer een lampje / schade heeft.

**Comment by Chang-nl** [comment]
Deze ga ik aanpassen naar 5 mins wanneer er 0 anwbers online zijn!
