### ISSUE TITLE
[FEATURE]: Togglehud

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1178]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Dat alles verdwijnt wanneer u /togglehud off doet. Wat bedoel ik precies? Nou als je /togglehud off doet zie je nog altijd je ID rechtsonder en postcode / locatie op je beeld. Mij lijkt het tof, als alles weg kan voor foto's te maken. Als dat zou kunnen natuurlijk, zo niet dan is het ook goed 😃.

### Wat lost deze feature op?

Meeste mensen maken vaak met /togglehud off een foto, maar als je dit doet zie je nog altijd je id en postcode op je beeld en als je dit zou weghalen wanneer je de commando uitvoert kan je betere foto's maken en geen random postcode op beeld of dergelijke. Dit zou meer opties kunnen geven voor betere foto's in de stad. 😄

**Comment by Chang-nl** [comment]
Na restart gefixt!
