### ISSUE TITLE
[FEATURE]: Toegang tot taxi kluis

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1179]
### Beschrijf zo duidelijk mogelijk de feature

Toegang tot de taxi kluis.

De reden waarom we toegang willen tot de kluis van Uberpolis.

-Geld van trouw en feesten dat wij als taxi regelen krijgen we geld voor
Dat wij het geld er in kunnen stoppen van gehuurde taxi chauffeurs.
Bij grootschalige 'events' vb bij trouw dat er meerdere gehuurde voertuigen etc. Dat wij dat geld gewoon in de kluis kunnen stoppen.

-Promotie geld.
Dat wij de top 3 werknemers van de week kunnen belonen met wat extra motivatie geld. 

-Geld uit halen voor marketing.
Binnen taxi word er af en toe events georganiseerd voor taxi, alleen wordt dat nu gefinancierd uit eigen zak. Terwijl het de bedoeling is dat taxi dat financiert. 

- Rang 
Chef rang 

Iedere inkomst en uitgave word bij gehouden door een persoon met de nieuwe functie Boekhouder. Die maandelijks ook een raport door geeft aan de taxi eigenaar. 
We houden ook dagelijks bij hoeveel er binnen komt in de taxi kluis. Sinds dat we het bij houden op 12/02 hebben we een winst geboekt van €16.034.552.

Dus wij denken dat het mogelijk is dat wij ook aan de kluis kunnen komen en alles te beheren.

### Wat lost deze feature op?

beter beheer van het geld wat rond gaat bij de taxi en om misbruik te voor komen een kanaal

**Comment by Willem-Dekker** [comment]
welke rank nu chef kan zwz alles al

**Comment by Willem-Dekker** [comment]
heb nu recruiter en Manager toegang geven tot geld opnemen aangezien zij ook konden inleggen

**Comment by Willem-Dekker** [comment]
zit er in na restart
