### ISSUE TITLE
[FEATURE]EUP: kleding taxi 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1181]
### Beschrijf zo duidelijk mogelijk de feature

https://youtu.be/X-COsswZwOY

### Wat lost deze feature op?

[Kleding_Taxi_2022_2.0.xlsx](https://github.com/Tedeapolis/development/files/8268319/Kleding_Taxi_2022_2.0.xlsx)

**Comment by brothasx** [comment]
Taxi outfits zijn toegevoegd en zullen bij de volgende commit toegevoegd worden aan de main :)
