### ISSUE TITLE
[FEATURE]: RS7 2020 ABT

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1183]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Ik had misschien wel ideetje voor de RS7 2020 ABT en dat gaat als volgt: 

RS7 2020 ABT Heeft een optie om zo'n kofferbak op het dak te zetten (zie screenshot). Mij leek het wel een toffe idee, als je 5 KG extra in je kofferbak kan doen. Mijn voorstel is als je de koffer op het dak hebt, dat je dan pas meer space krijgt voor je voertuig.

![image](https://user-images.githubusercontent.com/101106299/158698135-ccb13263-938e-43ec-ab5c-64e2862a138d.png)

### Wat lost deze feature op?

Het geeft meer realisme toe aan de stad / voertuig, aangezien in het echt zo'n kofferbak op het dak ook wel ruimte geeft om er wat in te doen en het leek me ook super tof als dit ook kan in de stad. Ik hoop dat dit mogelijk is 😄.

**Comment by Lorenzo3001** [comment]
Model gaat vervangen worden voor eentje zonder dakkoffer dus is niet meer van toepassing.
