### ISSUE TITLE
[FEATURE]: Enkele slagbomen verwijderen

### ISSUE THREAD

**Issue by ESP-Edgar** [Tedeapolis/development#1184]
### Contact Details

PoliceManED#8650

### Beschrijf zo duidelijk mogelijk de feature

Heel veel spelers hebben last van een paar slagbomen waardoor hun auto’s heel snel stuk gaan.

Dit probleem treedt niet op omdat ze er hardop tegen tijdje of iets dergelijks maar zelfs bij het kleinste tikje gaat je auto stuk. En er zijn een aantal slagbomen die niet eens opengaan.

Op aanvraag van Kyrinja AKA @Ljosfari  deze GitHub aangemaakt

De volgende slagbomen die verwijderd moeten worden zijn:

- [ ] **Garage Postcode 6062**

- [ ] **Helipads Postcode 5010**

- [ ] **Ook iets met de KMAR posten doen, weghalen of paaltjes zetten (Voorkeur van de KMAR is naar de paaltjes, ze gaven ook aan dat ze de paaltjes niet hoeven dicht te kunnen doen, het gaat er alleen om dat mensen niet met 400 door de oostpost vliegen)**

- [ ] **Slagbomen bij eiland**

### Wat lost deze feature op?

Geen gezeik met er niet door kunnen rijden of de metalen slagbomen moeten kapot rijden waardoor je auto soms tot wel 150 damage krijgt. (Bij 750 van de 1000 health heb je al gele motor)

**Comment by Ljosfari** [comment]
Bij de KMAR post eventueel paaltjes zoals bij de ANWB

**Comment by brothasx** [comment]
Blijkbaar zijn er al aantal slagbomen weggehaald maar niet aangevuld op de github.  Dus kan ik niets mee.

**Comment by Chang-nl** [comment]
Er zijn een aantal aanpassingen geweest aan de slagbomen, is daarmee deze issue ook opgelost?
