### ISSUE TITLE
[Bug]: Melding illegale goederen in leeg voertuig

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1185]
### Contact Details

Devv#4532

### Wat gebeurde er?

Een persoon heeft een mule gekocht en heeft deze in Sandy shores in de garage gezet. Nu kan hij het voertuig niet in de stad uit de garage halen dan komt er de foutmelding "het transportbedrijf weigert een voertuig met illegale goederen te vervoeren!"
Er zit niets in de vrachtwagen. Ik heb gevraagd of de persoon een ticket voor aan kon maken. #ticket-86694
kenteken mule: JYX 071
https://gyazo.com/27a7c93b5e3933fd22ff780006cfe56e
https://gyazo.com/1811f0c9de1dbbdca69a9e1210cc2ce8

### Wat hoorde er te gebeuren?

Aangezien er niets in zijn vrachtwagen zit hoort hij deze gewoon van locatie te kunnen transporteren naar de stad.

### Wat veroorzaakt de bug?

Er zit misschien iets onzichtbaars in?

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Yes is gefixt na volgende restart!
