### ISSUE TITLE
[Bug]: Haaien vangen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1186]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Op sommige plekken bij het water word je automatisch gestopt met vissen, waardoor je met je longfin moet gaan bewegen en dan op andere plek moet vissen.

### Wat hoorde er te gebeuren?

Je hoort normaal door te kunnen vissen.

### Wat veroorzaakt de bug?

Geen flauw idee, heb dit meerdere malen in een dag.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by Ljosfari** [comment]
heb je hier iets van een clip van ?
