### ISSUE TITLE
[Bug]: damage van vuisten klopt niet bij bepaalde animaties

### ISSUE THREAD

**Issue by BobDeHuisbaas20** [Tedeapolis/development#1188]
### Contact Details

BobDeHuisbaas20#3535

### Wat gebeurde er?

1 hit kill met de vuisten terwijl diegene vol levend was.

### Wat hoorde er te gebeuren?

gewoon een beetje damage zoals normaal. Dit is altijd zo tenzij je een npc slaat.

### Wat veroorzaakt de bug?

Waarschijnlijk vanwege de emote van de chains in basic Fat.

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/89611811/159176028-521389c7-d187-4521-a68c-11c0ce355ded.png)

Voor meer info, kom maar naar dm, dan kan ik de ticket laten zien.

**Comment by BobDeHuisbaas20** [comment]
https://youtu.be/y1yOymqisVA

**Comment by niekschoemaker** [comment]
Dit is een stealth kill, dit hoort niet te kunnen in alle situaties.
Verder weet ik dus ook niet in hoeverre dit een daadwerkelijk probleem is, want stealth mode is in principe al disabled, dus tenzij er een hele specifieke manier is om dit 100% te kunnen replicaten ga ik hier niks aan doen, gezien de lage impact hiervan.
