### ISSUE TITLE
[FEATURE]: Quicksell Eilandvoertuigen eiland.

### ISSUE THREAD

**Issue by BobDeHuisbaas20** [Tedeapolis/development#1189]
### Contact Details

BobDeHuisbaas20#3535

### Beschrijf zo duidelijk mogelijk de feature

Een cirkeltje om eilandvoertuigen te kunnen snelverkopen. Dit is een aantal keer gesuggesteerd door spelers. Besproken in staffoverleg dat ik hiervoor een github issue moest aanmaken.

### Wat lost deze feature op?

dan hebben de spelers de keuze om hem aan andere spelers te verkopen of te snelverkopen voor 50% dealersprijs.

**Comment by Chang-nl** [comment]
yes is gefixt!
