### ISSUE TITLE
Uren regestratie systeem

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#119]
Hij registeerd niet bij elk persoon de uren Bijvoorbeeld bij: t.mampaey is 25-08-2020 nog in dienst geweest.

**Comment by SecretSupplier** [comment]
https://gyazo.com/1b705019d85386ce73e9126d2dc8df92
De uren van de test server komen er ook bij daardoor staan er nu ook criminelen tussen.

**Comment by Willem-Dekker** [comment]
fixed en staat morgen op mijn let op dev en test server staan er ook in
