### ISSUE TITLE
[FEATURE]: Wapenstint voor shotgun

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1191]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kun je op alle wapens een wapentint zetten. Dit is echter niet het geval bij de shotgun. Vanuit criminelen is daarom de aanvraag gedaan tot het volgende:

- [x] Wapentint op shotgun kunnen zetten

### Wat lost deze feature op?

Op elk wapen kan een tint, behalve op de shotgun. Is een kleine feature waardoor crimineeltjes hun wapens een beetje kunnen tunen.

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart.
