### ISSUE TITLE
[Bug]: Eiland

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1192]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je bij het eiland langs wiet pluk rijdt of vliegt, zie je voor de rest van de dag geen coke tonnetjes of meth. Waarom dit gebeurd weet ik niet. Dit heb ik altijd, als ik langs wiet rij en er is iets actief ik zie het dan niet en hun wel. Ik vroeg hoe komt dat en iedereen zegt dat komt omdat je daar langs wiet hebt gereden, iedereen op eiland zegt dat tegen mij. 

### Wat hoorde er te gebeuren?

Je hoort dingen te zien ook al rij je langs wiet bij eiland.

### Wat veroorzaakt de bug?

Geen flauw idee, je rijdt langs wiet pluk bij eiland en je ziet niets meer tot je relogt. Dit komt bij iedereen o.a. ik.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Extra info, dit lijkt iets te maken hebben met het niet aan kunnen maken van objecten vanuit scripts.
Zo werkt CreateObject voor tankstationnen etc ook niet meer.
