### ISSUE TITLE
[BUG]: /neon werkt niet

### ISSUE THREAD

**Issue by joost00719** [Tedeapolis/development#1193]
### Contact Details

Via github

### Kenteken van voertuig

VMC 424

### Voertuig model

Nissan Skyline

### Omschrijf de bug

Ik heb er neon lampen onder gezet, maar deze kan ik niet uitzetten met het /neon commando.
Dit moet wel kunnen voor bij de grenscontrole

### Repro

1. Koop een auto
2. Zet er neon onder
3. Probeer het uit te zetten met /neon

### Normaal gedrag

De neon had uit moeten gaan

**Comment by niekschoemaker** [comment]
Als je na volgende restart even opnieuw bright pink neon op je auto zet zou het gefixed moeten zijn
