### ISSUE TITLE
[FEATURE]: garage bij de visplek

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1195]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Een garage bij de visplek : postcode 818 

### Wat lost deze feature op?

Er staan hier anders veel auto's, er zijn hier geen garages in de buurt. als mensen hun vis gaan verkopen nemen ze vanuit hier een busje mee, deze kunnen ze in de stad inleveren. Dus ze hoeven niet terug naar deze locatie.

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/159953248-918112ab-0364-4470-abb9-1fed511a8771.png)
Ze bedoeld deze locatie, als ik het niet verkeerd zeg 😄 .
