### ISSUE TITLE
Probleem bij het ziekenhuis.

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1196]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Ik kreeg een melding van een ambu dat regelmatig mensen zich verstoppen hier.

https://www.youtube.com/watch?v=KDztDa1arPE

### Wat hoorde er te gebeuren?

Probeer dit eruit te halen, want nu is het door meerdere mensen opgevallen.

### Wat veroorzaakt de bug?

Texture van het ziekenhuis aanpassen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Is dit de enige plek of zijn er meer plekken?

**Comment by Chang-nl** [comment]
Ik zag hier een dag of 2 terug een commit voorbijkomen wat betreft het ziekenhuis, is het opgelost?

**Comment by Chang-nl** [comment]
Gefixt, dankzij Oesewoes!
