### ISSUE TITLE
[FEATURE]: ANWB Pas / Abonnement 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1197]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Goedemorgen, de Ambulance heeft bijvoorbeeld een zorgverzekering is het mogelijk dat er voor de ANWB hetzelfde komt, maar dan voor voertuigen. Dit was trouwens een server supporter suggestie en ik kan wel begrijpen waarom mensen dit zouden willen aangezien de facturen soms wel duur kan zijn met de aanrijd kosten (aangezien er dagelijks verkeersongelukken gebeuren of mensen die slecht rijden) etc.

### Wat lost deze feature op?

Mensen die blij worden, aangezien ze minder moeten betalen omdat ze niet kunnen rijden en dagelijks gebeurd. In het echt heb je ook autoverzekering etc dus dit is ook wel realistisch. (Soortvan Ambulance zorgverzekering)

**Comment by Ljosfari** [comment]
niet akkoord
