### ISSUE TITLE
[Bug]: Gebruik van raketten wanneer in camera

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1199]
### Contact Details

MisterM#0001

### Wat gebeurde er?

Wanneer je een Apache of Armed Buzzard pakt, deze via /arm gevechtsklaar maakt, en op rechtermuisknop drukt, vuurt hij een raket af. Dit gebeurd echter ook wanneer gebruik wordt gemaakt van de camera waarbij er via de rechtermuisknop geswitch wordt van beeld (hitte, nacht, dag). Momenteel kan het dus gebeuren dat er onbewust een raket wordt afgeschoten wanneer je in de camera zit en het voertuig gearmed is.

Indien mogelijk is het wellicht handig om het afvuren van een raket via rechtermuisknop te disablen wanneer je in de camera (E) zit.
Dit voor de voertuigen met spawnnaam (/car buzzard en /car hunter)

### Wat hoorde er te gebeuren?

Er hoort geen raket afgevuurd te worden wanneer je in de camera zit.

### Wat veroorzaakt de bug?

Pak één van de voertuigen. Maak hem gevechtsklaar via /arm. Ga in de camera en druk op rechtermuisknop. Er wordt een raket afgevuurd.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t., indien toch nodig graag contacteren

**Comment by Chang-nl** [comment]
Gefixed na restart!
