### ISSUE TITLE
Respawnen verplaatsen en telefoon laten behouden

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#12]
Bij het respawnen van mensen nadat zij doodgaan, ze op het kerkhof laten spawnen. En hun telefoon laten behouden bij het respwawnen. Is besproken in het staff overleg van 28 juni 2020

https://docs.google.com/document/d/1ndBGIoTQnKtotnivCHKBLtcrXG1ykjPFnrFcO3ayWnM/edit?usp=sharing

**Comment by Willem-Dekker** [comment]
is imiddels gedaan
