### ISSUE TITLE
Kogels raken verloren 

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#120]
ik krijg van een aantal mensen te horen dat als je een wapen weg legt  waar kogels in zitten en je pakt daarna het wapen weer , dan zijn de kogels eruit . hier staat momenteel een ticket voor open (ticket nummer 8621) 

dit zelfde zie je ook gebeuren in ticket 8612 , daar hoor je in de video ook dat er ineens geen kogels meer in zitten en dat er een ticket word aangemaakt . dit gaat dus om zowel pistol clips als ak 47 clips

**Comment by takermart** [comment]
https://www.youtube.com/watch?v=A_PalnQvreE

**Comment by Willem-Dekker** [comment]
is geen bug is normaal gedrag
