### ISSUE TITLE
[FEATURE]: luchtmacht toestellen ook bij de marechaussee-korporaals rang onder persoonlijke toestellen laten vallen.

### ISSUE THREAD

**Issue by 123024** [Tedeapolis/development#1200]
### Contact Details

just_emre#6041 (besproken met Korpsleiding)

### Kenteken van voertuig

-

### Voertuig model

AH-64 Apache, Buzzard, Buzzard (Civiel), UH-60M.

### Omschrijf de bug

Op dit moment kan de marechaussee-korporaals rang geen koninklijke luchtmacht toestellen pakken bij helipads(postcode 5010), LSIA vliegveld (postcode 2011), sandy shores airfield, etc, eigenlijk overal waar burgers een heli kunnen pakken. Met een politie rol kan dit daarentegen wel, alle helikopters, dus ook hun persoonlijke helikopters, kunnen ze pakken in de groene cirkels, dus hun luchtmacht toestellen vallen onder hun persoonlijke toestellen. De marechaussee moet naar het hoofdbureau of de legerbasis om er een te pakken (bij de blauwe heli logo). 

Daarnaast kan er niet in en uitgestapt worden in de Buzzard (bij de marechaussee), maar dit zal wellicht wel kunnen nadat het probleem hierboven is verholpen.

https://youtu.be/XToQWy14TY0 

### Repro

Geef jezelf de marechaussee korporaals rang, ga naar de legerbasis helipads bij het begin van de landingsbaan (zie video). Koop het toestel Buzzard uit de voertuigdealer bij het blauwe helikopter icoontje naast de groene cirkel. Probeer de Buzzard te pakken vanuit de groene cirkel, dit zal niet lukken. 

https://youtu.be/XToQWy14TY0

### Normaal gedrag

Bij elke luchthaven of helipad, een luchtmacht toestel kunnen pakken, met de marechaussee-korporaals rang, dus bij alle groene cirkels, net zoals dat kan bij politie rollen.

**Comment by Willem-Dekker** [comment]
laat ff weten of het werkt na restart

**Comment by 123024** [comment]
> laat ff weten of het werkt na restart

Bij mij werkt het op dit moment niet (met de korporaals rang), er staat dat ik geen voertuigen heb, als ik in de groene cirkel loop.

**Comment by Willem-Dekker** [comment]
ze komen ook nooit in de groene circle dacht ik

**Comment by 123024** [comment]
> ze komen ook nooit in de groene circle dacht ik

https://www.youtube.com/watch?v=TOaChRAbloE , bij de politie is het mogelijk om bij groene cirkels een helikopter te pakken(bij helipads bijv zoals in de video), met een kmar rang is dit niet mogelijk.

**Comment by Willem-Dekker** [comment]
ik zie dat er iets mis gaat maar niet wat er mis gaat

**Comment by Willem-Dekker** [comment]
is fixed na restart
