### ISSUE TITLE
[Bug]: Berichten

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1202]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

![image](https://user-images.githubusercontent.com/101106299/160152793-b225e9c1-2091-4e71-bb48-2a1fe4b7afd3.png)
De berichten opslag melding weg doen, je kan er overheen gaan. Beetje onnodig lijkt me.

### Wat lost deze feature op?

Geen irritante melding dat je berichtenopslag vol zit (frustratie kwijt).

**Comment by Ljosfari** [comment]
Denk dat de :volle opslag melding' er met een reden in zit. Misschien voor de server load etc

**Comment by CalRayy** [comment]
Ja, dat kan ik eventueel begrijpen. Is er een mogelijkheid om de melding dan weg te halen?

**Comment by Willem-Dekker** [comment]
melding blijft staan berichten worden verwijderd na een tijd en het is meer een indicatie voor je zelf dat het kan laggen en doen
