### ISSUE TITLE
[Bug]: Off-Road

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1203]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik reed op een dood normale weg, uiteindelijk bleek die off-road te zijn, wat mij super raar lijkt. (ik reed richting de 120 uiteindelijk crashde ik omdat mijn voertuig rond vloog door een off-road stuk wat mij geen off-road weg is)

### Wat hoorde er te gebeuren?

Ik hoorde normaal in een rechte lijn te rijden, maar omdat het off-road was vloog de achter kant van mijn voertuig. (zie clip https://youtu.be/Bew1YmUuOP4)

### Wat veroorzaakt de bug?

Geen flauw idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by Ljosfari** [comment]
Ik snap niet helemaal wat je bedoelt. Dat je auto glijd op het stuk stoep ?

**Comment by CalRayy** [comment]
Ja, als je off-road rijd met een bugatti dan merk je dat super fel en dat gebeurd dus nu op een stuk stoep.

**Comment by Chang-nl** [comment]
Is dit alleen op die specifieke plek?

**Comment by CalRayy** [comment]
Yes

**Comment by Attomn** [comment]
Is een foutje van de GTA map zelf, hier kunnen we weinig aan veranderen tenzij Kenneth een ymap wil maken waarin dit verbeterd is en de ymap overschrijven.
