### ISSUE TITLE
[FEATURE]: Tedeapolis Nieuws Gebouw

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1204]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

De tedeapolis nieuws gebouw had eerst een slot op de deur, en die is nu weg. (zie screenshot)
![image](https://user-images.githubusercontent.com/101106299/160261250-1bc1fe59-7837-41aa-8028-eb58e4f9487f.png)
Zou hier een slotje terug kunnen komen?

### Wat lost deze feature op?

Random mensen die in het gebouw komen en rond kloten.

**Comment by brothasx** [comment]
sloten op de voordeur zijn toegevoegd voor de reporter job.
