### ISSUE TITLE
[FEATURE]: Schietmeldingen boven vliegradar tonen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1205]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Het rondje op de map van de automatische schietmelding boven de groene cirkel van de vliegradar tonen.
![image](https://user-images.githubusercontent.com/93579695/160292053-132614ed-2f7f-4726-9c6d-ef85a515f759.png)

### Wat lost deze feature op?

Dit zorgt ervoor dat die schietmeldingen niet verdwijnen onder de grotere groene cirkel van de helikopters en vliegtuigen die getoond worden op de vliegradar.

**Comment by Chang-nl** [comment]
Gefixed na herstart!

**Comment by PolitieTDA** [comment]
> Gefixed na herstart!

Van wat ik nu heb getest staat die initieel wel er boven, maar zodra de groene cirkel beweegt dan staat die weer boven de schietmelding.
