### ISSUE TITLE
[FEATURE]: Garage en toegewezen auto's voor justitie

### ISSUE THREAD

**Issue by Sjenkie-Sjembek** [Tedeapolis/development#1206]
### Contact Details

Sjenkie Sjembek #1118

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag willen weten of het mogelijk is om een (gezamenlijke) garage te creëren bij het gemeentehuis.  Daar kunnen advocaten en diegene die een job starten voor documenten(wat er binnenkort aankomt) een auto pakken.  

Zelf dacht ik een XC90 (wit met ministerie logo en text MINISTERIE) Ik heb eventueel een livery idee dus mocht het nodig zijn laat even weten. 

Ook hebben we een PULLMAN die we willen gebruiken voor VIP vervoer van Minister en Staatsecretaris. Luci heeft hem al gekocht wellicht dat we die kunnen gebruiken. 

Kort om iedereen die in dienst is van justitie kan een XC90 pakken om naar zaken te rijden en straks de documenten ronde.

### Wat lost deze feature op?

Het lost op dat iedereen maar in random auto's rijdt. Justitie is een stuk zichtbaarder. Daarnaast is het een mooie voorbereiding op de documenten ronde waar Chang al mee bezig is. 

Ook biedt het een mogelijkheid tot betere roleplay omdat de pullman als VIP vervoer gebruikt kan worden. We hebben er al een die we kunnen gebruiken. Zou leuk zijn als dit gezamenlijk kan.

**Comment by Willem-Dekker** [comment]
zit er in voor morgen
