### ISSUE TITLE
[Nieuwe Flitspalen]: 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1207]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staffoverleg is besproken voor nieuwe flitspalen bij de volgende 2 locaties : 

- La Fuente weg 
- Paleto Bay

### Wat lost deze feature op?

Op de volgende coords een nieuwe flitspaal zetten zie toegevoegde files. 

X: 1023.21 Y: 2084.92 Z: 50.26 H: 326.09
( La Fuente)  
![la fuene](https://user-images.githubusercontent.com/90053273/160295304-bfb2d6d1-5707-4e73-924e-f918dc1f674f.png)

X: 404.28 Y: 6589.93 Z: 27.66 H: 169.08
( Paleto ) 
![Screenshot_12](https://user-images.githubusercontent.com/90053273/160295285-bf0851bc-9801-4172-b861-49ec424ae666.png)

**Comment by brothasx** [comment]
Bij de volgende commit is dit in orde ! :)
