### ISSUE TITLE
[FEATURE]: Kleur van schiet- en drugsmeldingen op de kaart van een agent een verschillend kleurtje geven (Low priority)

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1209]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Voor een schietmelding een ander kleurtje dan een drugsmelding op de kaart laten weergeven.

### Wat lost deze feature op?

Zorgt ervoor dat er minder verwarring is aangezien ze op dit moment precies dezelfde kleur zijn en enkel de cirkelgrootte verschillend is.

**Comment by niekschoemaker** [comment]
Heb hem nu geel gemaakt
