### ISSUE TITLE
[FEATURE]: Optie voor politie om criminele handboeien los te kunnen maken

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1210]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een optie toevoegen om op een bepaalde manier mensen los te kunnen maken die door criminelen zijn geboeid.

### Wat lost deze feature op?

Vaak komt de politie personen tegen die nog geboeid zijn door criminelen en dan is momenteel de enige oplossing voor hen om te reloggen. Als er een optie is om de tie wrap handboeien los te kunnen maken dan zou dat de roleplay bevorderen.

**Comment by Chang-nl** [comment]
na restart zit er een optie in het f6 menu 'tie wrap losmaken' waarmee je criminele handboeien kan losmaken
