### ISSUE TITLE
[Bug]: Speedzone ANWB

### ISSUE THREAD

**Issue by rubenTomassen** [Tedeapolis/development#1211]
### Contact Details

Ru🅱eN#8888

### Wat gebeurde er?

Mensen die het ANWB terrein oprijden kunnen soms niet meer remmen. Dit komt volgens mij doordat je met een meer dan 50 km/u het terrein op rijd een daardoor sneller gaat dan de speedzone die daar is.

### Wat hoorde er te gebeuren?

Normaal gesproken zou je gewoon moeten kunnen remmen. 

### Wat veroorzaakt de bug?

Door het ANWB terrein op te rijden met meer dan 50 km/u

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by brothasx** [comment]
Is als het goed is gefixed, zou je even moeten checken.
