### ISSUE TITLE
[FEATURE]: Tedeapolis Nieuws gebouw deuren

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1212]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Je hoort de deur te kunnen openen, maar er zit geen sleutel of slotje bij de deur. (zie screenshot)
![image](https://user-images.githubusercontent.com/101106299/160460228-dc413df8-581a-44db-b677-3b07a63027ac.png)
(Je hoort namelijk binnen te kunnen gaan, maar nu is de deur een steen harde muur.)

### Wat lost deze feature op?

Je kan in het gebouw gaan, zodat je RP kan creëren en dingen kunt opnemen voor het nieuws .

**Comment by Willem-Dekker** [comment]
media baan heeft nu toegang tot deze deur
