### ISSUE TITLE
[FEATURE]: spectate 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1213]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Als je aan het spectate bent en iemand die je spectate is dood kan je niet om je heen kijken of dergelijke. Er is sindskort gekomen stel je gaat dood dat je om je heen kan kijken, maar is het mogelijk om dit bij het spectate modus in te voegen aub?

### Wat lost deze feature op?

Reports beter kunnen behandelen / mensen bekijken gaat makkelijker

**Comment by JohnnyFlodder** [comment]
@Willem-Dekker deze is al gedaan, kan gesloten worden. :)

**Comment by CalRayy** [comment]
> @Willem-Dekker deze is al gedaan, kan gesloten worden. :) 
> 
> 

Werkt niet naar mijn weten, vandaag nog gehad 😅

**Comment by Attomn** [comment]
Gezien dit al gedaan zou moeten zijn maar niet werkt zie ik dit als een bug.

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart
