### ISSUE TITLE
[FEATURE]: Geluid van enzo Ferrari veranderen

### ISSUE THREAD

**Issue by GodenPants** [Tedeapolis/development#1214]
### Beschrijf zo duidelijk mogelijk de feature

Kenteken van voertuig
No response

Voertuig model
Enzo ferrari 
-MIG

Omschrijf de bug
Sinds het begin dat hij in de stad zit heeft hij het geluid van een stofzuiger. kan daar misschien iets aan veranderd/ gedaan worden.

naam voertuig: Enzo ferrari
Spawn Code: -MIG

Repro
No response

### Wat lost deze feature op?

het geluid van de enzo ferarri

**Comment by Lorenzo3001** [comment]
Heb hem aangepast naar het geluid van de visione
