### ISSUE TITLE
[FEATURE]: voertuigen nemen om te testritten voor cardealer

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#1215]
### Contact Details

ExpensionX

### Beschrijf zo duidelijk mogelijk de feature

Ik en de leden van de officiele cardealer zijn al enkele keren aan het brainstormen hoe we  de mensen testritten kunnen geven in elke auto. 
Hoe we het momenteel in gedachte hebben:
- **een cirkel bij de officiele cardealer waar we auto's uit kunnen nemen. De auto's kunnen er alleen uit genomen vanaf een rank. De cardealer heeft al een rank van de luxury cardealer. Daar zou eventueel een rank aan toegevoegd kunnen worden met luxury handelaar en luxury adviseur.
- De handelaars + kunnen een auto nemen uit de cirkel voor testritten aan te bieden aan de mensen.**

### Wat lost deze feature op?

Dit idee is bedacht omdat er vaak testritten worden aangevraagd. Helaas is er niet altijd staff beschikbaar of is de tijd er niet voor. Via deze manier kan het personeel testritten geven zonder staff. Dit zal resulteren met sancties als ze zich niet aan de afspraken houden en het personeel moet ook een aanvraag ervoor goedgekeurd worden om de auto te nemen.

**Comment by Attomn** [comment]
We hebben even gekeken (@niekschoemaker @Ljosfari) en hebben besloten dat dit te veel gezeik is om te realiseren. Naast al het codewerk levert het gekloot vanuit spelers op (elkaar dood rijden, schade etc).
