### ISSUE TITLE
[Bug]: Reprorts listed verschijnt random in beeld bij spelers

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#1216]
### Contact Details

Willemde20#0001

### Wat gebeurde er?

Bij reloggen krijgt een speler (tot nu toe 1) de UI van reports listed in beeld. Deze is leeg en dus niet gevuld met tickets

![image](https://user-images.githubusercontent.com/16556575/161003643-c55fa992-bcbf-4271-b038-fd07cba75980.png)

### Wat hoorde er te gebeuren?

spelers horen dit scherm niet te zien

### Wat veroorzaakt de bug?

reloggen / random geen exacte repro

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Zijn geen log bestanden vanuit speler gegeven

**Comment by Chang-nl** [comment]
Is dit bij een random speler geweest of een admin of in ieder geval iemand die permissies heeft om dit menu te openen?

**Comment by Chang-nl** [comment]
heb je hier toevallig ook f8 logbestanden bij?

**Comment by Chang-nl** [comment]
ik heb nu in ieder geval wat exra checks doorgevoerd alleen om deze issue echt op te kunnen lossen heb ik echt f8 logs nodig, want het kan door nogal wat dingen komen.

**Comment by Chang-nl** [comment]
Zou hier even teruggekoppeld kunnen worden of dit opgelost is voor andere spelers te ja of te nee?

**Comment by Willem-Dekker** [comment]
ik heb er niks meer over gehoord denk dat het gefixed is @Chang-nl

**Comment by Chang-nl** [comment]
prima, als er weer een probleem is kan er of een nieuwe issue gemaakt worden of deze issue heropenen.
