### ISSUE TITLE
[Bug]: Spelers zien ticket niet na verplaatsen van categorie

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1217]
### Contact Details

Bas#6430

### Wat gebeurde er?

Het gebeurd regelmatig dat tickets worden aangemaakt waarin meerdere spelers worden toegevoegd. Echter wanneer dit ticket verplaatst wordt van category, worden alle spelers die toegevoegd waren eruit gezet en zien ze het kanaal niet meer.

### Wat hoorde er te gebeuren?

Alle toegevoegde mensen horen het kanaal gewoon te zien ook nadat het verplaatst is.

### Wat veroorzaakt de bug?

Onbekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
@AdventurePandah is dit nog steeds een probleem?

**Comment by AdventurePandah** [comment]
> @AdventurePandah is dit nog steeds een probleem?

Yes

**Comment by Chang-nl** [comment]
Nee dit is helaas niet mogelijk. Je zult ze naderhand weer moeten toevoegen.
