### ISSUE TITLE
Ban meldingen in de stad weer aanzetten met verandering geen steamnamen meer maar ID's

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1219]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

Ban meldingen in de stad zoals besproken worden weer aangezet, met de wijziging dat je niet meer de steamnaam ziet maar alleen het ID van de verbannen speler

### Wat lost deze feature op?

Besproken in stafoverleg moest alleen nog worden aangezet/aangepast

**Comment by Chang-nl** [comment]
geregeld!
