### ISSUE TITLE
[Bug]: Korporaals van de Kmar (KLU) kunnen geen heli's pakken

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1220]
### Contact Details

MickeyMorris#7393

### Wat gebeurde er?

Wanneer je naar een andere helipad gaat dan de legerbasis als korporaal van de Kmar(KLU), kun je niet zoals de KLU van de politie een helikopter pakken,

### Wat hoorde er te gebeuren?

Dat je net als de KLU van de politie de optie krijgt om daar de KLU heli's te pakken

### Wat veroorzaakt de bug?

Waarschijnlijk niet geimplementeerd voor de kmar

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by ARJ3N** [comment]
Volgens mij hetzelfde als #1200.

**Comment by Willem-Dekker** [comment]
laat ff weten of het werkt na restart

**Comment by Willem-Dekker** [comment]
gezien reactie ga ik er van uit dat het fixed is
