### ISSUE TITLE
[FEATURE]: Flitspaal op de pier weghalen/verplaatsen

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1222]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel staat er een flitspaal op de pier. Deze heeft echter geen nut meer gezien je niet meer met een voertuig op de pier kan komen. Deze flitspaal graag weghalen / verplaatsen naar het begin van de pier.

![image](https://user-images.githubusercontent.com/72617118/161435459-de6fd4c8-bf4f-43ed-9a18-f16930f08b09.png)

### Wat lost deze feature op?

Een flitspaal die zijn werk niet kan doen

**Comment by Chang-nl** [comment]
gefixt!
