### ISSUE TITLE
[FEATURE]: Voertuig automatisch op slot uit garage (Supporter suggestie)

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1223]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Wanneer je een voertuig uit je garage haalt staat deze automatisch open.
Hierdoor kunnen op drukke plekken mensen direct in je kofferbak om er spullen uit te pakken.
Indien mogelijk graag aanpassen dat een voertuig op slot uit de garage komt.

### Wat lost deze feature op?

Kinderen die random shit pakken uit mensen hun voertuigen.

**Comment by Chang-nl** [comment]
Na de volgende restart zit dit erin!
