### ISSUE TITLE
[Item vanuit kleine bank voor grote bank]: 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1224]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Aangezien de grote bank makkelijk gedaan kan worden en niet speciaal meer is. Is er besproken om een (Security) Pasje toe te voegen in de kleine banken. 
Doordat er een bepaalde drop change is kom je er ook niet makkelijk aan vanuit elke kleine bank. 

Door dat (Security) Pasje kan je dan de grote bank doen. Je kan dus niet meer met enkel thermiet en een hackers toestel de grote bank doen. 
Je hebt dan een Security pasje nodig om de grote bank te kunnen doen die je dus kunt verkrijgen uit een kleine bank. 

Dit is besproken in het staff overleg 

### Wat lost deze feature op?

Dit geeft wat meer handelingen om de grote bank te kunnen doen. 
Hopelijk levert dit wat meer op binnen de criminaliteit een nieuwe zwarte markt ervoor en weer een extra handeling voor de criminelen.

**Comment by niekschoemaker** [comment]
Vervalt ivm toekomstige updates
