### ISSUE TITLE
[FEATURE]: Uittesten recoil patronen wapens

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1225]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Tijdens het staffoverleg is besloten een issue aan te maken zodat alle wapen gecheckt kunnen worden op de huidige recoil.
De bedoeling is dus dat er voor elk wapen gekeken wordt of de recoil te erg, te weinig of perfect is.
Indien er dan aanpassingen nodig zijn kan dat gedaan worden.

### Wat lost deze feature op?

Sommige wapens hebben een hele heftige recoil terwijl dat niet als realistisch gezien wordt.

**Comment by MisterM02** [comment]
Dit graag ook uittesten met recoil in voertuigen. Zie clip

**Comment by Chang-nl** [comment]
Dit was een bug en is gisternacht opgelost, gisteren zijn ook een aantal dingen aangepast binnen de recoil.
