### ISSUE TITLE
[EUP]: Nieuwe HRB outfit niet toegankelijk voor hogere rangen

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1226]
### Contact Details

MickeyMorris#7393

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De nieuwe HRB outfit is niet toegankelijk voor kmar rollen 45, 50, 60, 72, 73, 74, 80, 81, 82, 83, 90, 95

**Comment by brothasx** [comment]
Zou normaal al in orde moeten zijn ?

**Comment by dilyano** [comment]
> Zou normaal al in orde moeten zijn ?

Mits deze niet is aangepast vannacht in de codebase werkt dit helaas nog steeds niet.

**Comment by Willem-Dekker** [comment]
zit er in na restart
