### ISSUE TITLE
[FEATURE]: KMAR Vito & KMAR Takelwagen

### ISSUE THREAD

**Issue by ESP-Edgar** [Tedeapolis/development#1227]
### Contact Details

PoliceManED41#8650

### Beschrijf zo duidelijk mogelijk de feature

Er werd vanuit de KMAR aangevraagd voor een reskin van de Politie Vito en Takelwagen en deze is nu af. Moest vanuit Ljosfari volgende github aanmaken hiervoor.

De files van de voertuigen heb ik bij mij, DM mij eventjes zodat ik het kan opsturen. Als bijlage enkele foto's.

![unknown3](https://user-images.githubusercontent.com/71555741/161559408-7b882fcd-ca24-456d-af7d-2f98435e194a.png)
![unknown2](https://user-images.githubusercontent.com/71555741/161559430-a82a270c-1f5f-464b-9f09-ee0c97e7fbcd.png)
![unknown](https://user-images.githubusercontent.com/71555741/161559438-db73d921-e175-48ee-ad0b-51a7f61d6848.png)

### Wat lost deze feature op?

KMAR wordt herkent op de weg en dit is realistischer dat de KMAR in hun eigen voertuigen rijdt.

**Comment by Ljosfari** [comment]
heeft permissie vanuit de kmar

**Comment by Lorenzo3001** [comment]
Zit er na de restart in
