### ISSUE TITLE
[FEATURE]: Nep Porto PTT ook werkend zonder in-game in een radiofrequentie te zitten

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1228]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel hebben we een ''neppe'' porto animatie die we gebruiken in samenhang met de push to talk die we gebruiken in onze Discord porto's. Zo lijkt het op die manier in de stad ook alsof we in een porto praten, zonder dat we dat in een in-game porto doen. Deze werkt enkel als je in-game ook in een portofrequentie zit. 

Nu is ons verzoek of dit veranderd kan worden naar dat die animatie altijd werkend is, ondanks of je in-game in een porto zit of niet.

### Wat lost deze feature op?

Dit zorgt ervoor dat bij druk portoverkeer in de in-game porto je die eventjes uit kunt zetten terwijl je bezig bent met je eigen situatie, maar dan nog wel de porto animatie behoud voor wanneer je via de Discord porto praat.

**Comment by niekschoemaker** [comment]
Zou na volgende restart gefixed moeten zijn
