### ISSUE TITLE
[FEATURE]: Vlieg instructeur Shamal vehicle properties

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#1229]
### Beschrijf zo duidelijk mogelijk de feature

De Shamal die je als vlieg instructeur kan pakken standaard laten spawnen met de vehicle properties van het voorbeeld voertuig. 

Voorbeeld voertuig: GDI 350

### Wat lost deze feature op?

Het krijgen van een random livery bij het pakken van de vlieg instructeur Shamal.

**Comment by Willem-Dekker** [comment]
zit er na restart in
