### ISSUE TITLE
[FEATURE]: Garage Vissers strarters punt.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1230]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Een grarage plaatsing bij de begin locatie van visser. 

Bij visser is het vaak druk met voertuigen bij de begin locatie, waardoor het soms voorkomt dat mensen hun werkvoertuig niet kunnen pakken. (Deze begin locatie is op Postcode 6012)

Ideeën van locaties voor de grage;
https://prnt.sc/R0IqMn6PM_UF
https://prnt.sc/lx0Xf0Bau50g

### Wat lost deze feature op?

Bij het inspauwnen van de vissers truck staat er niet meer een auto in de weg aangezien ze deze dan makkelijk in de garage kunnen zetten.

Mensen die daar langs rijden hebben niet FPS drops op die locatie omdat ze opeens 20 autos in moeten laden.

**Comment by Willem-Dekker** [comment]
zit er in na restart
