### ISSUE TITLE
[EUP]: fysieke porto ANWB

### ISSUE THREAD

**Issue by rubenTomassen** [Tedeapolis/development#1231]
### Contact Details

Ru🅱eN#8888

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Hallo,

Aangezien wij bij de ANWB steeds meer de Discord porto gebruiken zouden wij het fijn vinden als er een fysieke porto kan worden toegevoegd in ons EUP menu. 

Het gaat hier om Sticker 1: <7> 
hier zit namelijk ook een fysieke radio bij en die heb je helaas niet bij de porto die de politie gebruikt.

mvg,
Ruben T.

![image](https://user-images.githubusercontent.com/87775808/161619034-b311c402-fd67-4eb8-91f5-c1ff426c8d8f.png)
![image](https://user-images.githubusercontent.com/87775808/161619122-426dff20-6967-49c9-8b36-298e823aabe2.png)

**Comment by DeStefanoKiller** [comment]
Bij deze heeft die permission vanuit mij dat dit in het ANWB eup menu mag komen.

**Comment by Willem-Dekker** [comment]
zit er in na restart
