### ISSUE TITLE
[Bug]: Narcopolis wietvelden zorgt voor client-side issue. 

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1232]
### Contact Details

Dekk#3971

### Wat gebeurde er?

Als je over de wietpluks rijdt op narcopolis zorgt dit ervoor dat je de andere pluks op narcopolis, maar ook op het mainland niet meer kan zien en/of gebruiken. Dit is al ontzettend lang een issue.

### Wat hoorde er te gebeuren?

Je hoort gewoon over de wiet pluk te kunnen rijden en daarna nog steeds de pluks te kunnen zien, mensen vermijden nu de wietpluk, omdat je anders niks meer kan op het eiland totdat je relogged.

### Wat veroorzaakt de bug?

Pak een auto, rij over de wietpluk en ga daarna naar een andere (actieve) pluk, je zult zien dat je niks kan. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Deze issue heb je recent (in de laatste 2 weken) nog steeds zelf meegemaakt?

**Comment by Tijz** [comment]
> 

Laatste 2 weken wel, afgelopen paar dagen niet.
