### ISSUE TITLE
[FEATURE]: F3 emote menu steamnaam naar ID

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1235]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kun je bij F3 via shared emotes een steamnaam achterhalen. Dit kan gebruikt worden voor powergaming oid. Wellicht een idee om dit aan te passen naar een speler ID ipv steamnaam.

### Wat lost deze feature op?

Dit voorkomt powergaming / emote menu abuse om zo spelers via een OOC weg toch te herkennen.

**Comment by Willem-Dekker** [comment]
zit er in na restart
