### ISSUE TITLE
[FEATURE]: Spawn plek op LSIA aanpassen 

### ISSUE THREAD

**Issue by rubenTomassen** [Tedeapolis/development#1236]
### Contact Details

Ru🅱eN#8888

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment spawned jouw vliegtuig maar op 1 plek in de hangar en dit is precies in de rode cirkel. Het idee is om deze te verplaatsten naar 1 of indien mogelijk meer rode vlakken in de hangar. (zie foto hieronder) 

![image](https://user-images.githubusercontent.com/87775808/162582191-6094997b-92b2-4ad6-963f-6f682a39e8cd.png)

### Wat lost deze feature op?

- mensen kunnen de porto aanzetten en ATC joinen zonder dat je het vliegtuig weer in de garage zet.
- mensen hoeven niet meer te wachten op elkaar aangezien het enige tijd duurt voordat je weg kan rijden met je vliegtuig.
- mocht je het vliegtuig kapot uit de garage halen staat hij niemand in de weg want in sommige gevallen laten mensen het vliegtuig staan en blokkeert het dus de spawn en de plek waar je je vliegtuig weg zet.
- er gebeuren geen ongelukken meer op het moment dat mensen hun vliegtuig perongelijk op hetzelfde moment uit de garage halen of wanneer iemand zijn vliegtuig uit de garage haalt als iemand hem net wil gaan wegzetten.

**Comment by Willem-Dekker** [comment]
![image](https://user-images.githubusercontent.com/16556575/163573739-6fc53034-b809-430d-94ba-694a80369cd2.png)
heb ik er nu van gemaakt
