### ISSUE TITLE
[FEATURE]: Range voor slotjes groter maken.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1237]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

De range van de garage sloten verder zetten waardoor je deze vanuit de auto open kan doen, aangezien je nu zowat er tegen aan moet staan met je poppetje om deze open te kunnen doen.

Vanaf waar je dezen eigenlijk open zou moeten doen:
https://prnt.sc/UtlqCMTv-KE3

Vanaf waar het nu maar kan:
https://prnt.sc/TsGxRUv1OahI

### Wat lost deze feature op?

Dat mensen die hier tot bevoegd zijn deze makkelijker open kunnen doen.

**Comment by Willem-Dekker** [comment]
coords?

**Comment by Rowdeeee** [comment]
Deur 1 Linkse garagedeur (vanaf buiten gezien);
https://prnt.sc/kRKGLz6KUc8X       x: -770,32 y: -240,20 z: 37,06 h: 203,69
Vanaf waar wij deze open zouden willen doen (buitenkant);
https://prnt.sc/HZoQSy2aPpzD      x: -769,20 y: -243,45 z: 36,61 h: 23,03
Vanaf waar wij deze open zouden willen doen (binnenkant);
https://prnt.sc/8J5iwXzakqiv          x: -771,88 y: -237,16 z: 36,48 h: 203,56

Deur 2 Rechtse garagedeur (vanaf buiten gezien);
https://prnt.sc/oXpJy_lahym4        x: -765,27 y: -238,12 z: 37,06 h: 200,26
Vanaf waar wij deze open zouden willen doen (buitenkant);
https://prnt.sc/5gWlopUaf2SB       x: -764,21 y: -241,17 z: 36,60 h: 20,70
Vanaf waar wij deze open zouden willen doen (binnenkant);
https://prnt.sc/8pr9_KLNLj5b         x: -767,27 y: -235,00 z: 36,48 h: 204,23

**Comment by Chang-nl** [comment]
yes, de range is aangepast!
