### ISSUE TITLE
[Bug]: Reanimatie systeem bug 

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#1238]
### Contact Details

AntonMoskvin#3144

### Wat gebeurde er?

Als je reanimeert als politie zijnde dan reset de timer telkens naar 5 min, als je hierna weer stopt met reanimeren laat je de timer aflopen. En dan ga je vervolgens weer opnieuw reanimeren waar door weer de timer naar 5 min reset. Zo kan je makkelijk iemand meer dan een half uur laten liggen zonder dat de gene kan respawnen. 

### Wat hoorde er te gebeuren?

Langer moeten reanimeren voordat die timer reset. Nu kunnen ze met 1x op E drukken de timer resetten en dit flink abusen.

### Wat veroorzaakt de bug?

Mensen kunnen nu die timer zonder iets te doen omhoog houden terwijl dit niet de bedoeling is.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by ARJ3N** [comment]
Dit is geen bug maar er juist opzettelijk ingezet zodat mensen niet gaan respawnen terwijl ambulance roleplay nog bezig is of gedaan moet worden.

**Comment by Chang-nl** [comment]
waarom is het precies een issue?

**Comment by CalRayy** [comment]
Mensen misbruiken deze timer reset, hoe? Ze gaan om de 5 min weer reanimeren waardoor de timer reset en zo kan degene voor  30 minuten lang niet respawnen bijvoorbeeld. Ik heb deze issue in server supporter suggestie zien voorbij komen als het goed is.

**Comment by Chang-nl** [comment]
Arjen heeft hierboven een juiste uitleg gegeven van wat het doel is van die feature dit gaan we niet aanpassen.
