### ISSUE TITLE
Naam Maria's Winkel veranderen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#1239]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

In overleg met Kenneth wil ik graag een naam verandering aanvragen van Maria's Winkel naar Freddy's Kraslotenshop

### Wat lost deze feature op?

Niets, behalve dat het dan echt mijn winkeltje is :D

**Comment by CoffeeSipper** [comment]
**-1**

**Comment by Willem-Dekker** [comment]
zit er in na restart
