### ISSUE TITLE
[FEATURE]: pluk locatie eiland

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1240]
### Contact Details

iHax0r#3736

### Beschrijf zo duidelijk mogelijk de feature

De pluks op het eiland zijn momenteel al een jaar hetzelfde, hierbij de vraag of het mogelijk is om alle pluks op het eiland aan te passen (2x coke en 2x meth).

### Wat lost deze feature op?

Brengt weer is vernieuwing op eiland, aangezien de locaties al zolang hetzelfde zijn.

**Comment by Willem-Dekker** [comment]
dus op narco?

**Comment by Tijz** [comment]
> dus op narco?

Ja.

**Comment by Willem-Dekker** [comment]
dit zal worden opgepakt
