### ISSUE TITLE
[FEATURE]: Rework drugs percentages (Burgerraad)

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1241]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Tijdens de burgerraad is het puntje "drugspercentages" naar boven gekomen.
In overleg met Ljosfari is besloten een github issue aan te maken om te kijken of dit eventueel herbekeken kan worden.
Want momenteel lijkt het dat dit percentage, in tegenstelling tot vroeger (waar je met een hoger percentage meer kon verwerken) geen nut heeft.

- Percentage gaat nu enkel omhoog met plukken. -> Eventueel ook bij het gebruik van loodsen of het verkopen van drugs
- Waar heeft het percentage precies effect op? -> Eventueel met een hoger percentage meer/sneller kunnen verkopen/plukken

Het verzoek is dus om te kijken in hoeverre dit percentage nut heeft en dit nut wellicht te verhogen 

### Wat lost deze feature op?

Drugspercentages daadwerkelijk nut laten hebben

**Comment by Willem-Dekker** [comment]
welk percentage?

**Comment by zeletix** [comment]
> welk percentage?

de skill percentage, die je met Z kan zien

**Comment by Chang-nl** [comment]
De skill heeft wel nut, aangezien je meer van de planten krijgt.

**Comment by Willem-Dekker** [comment]
volgens mij is er nu genoeg nut aan

**Comment by Ljosfari** [comment]
is dit al aangepast wiilem ?

**Comment by Chang-nl** [comment]
> De skill heeft wel nut, aangezien je meer van de planten krijgt.

Dit is toch antwoord op de issue?

**Comment by Lorenzo3001** [comment]
> > De skill heeft wel nut, aangezien je meer van de planten krijgt.
> 
> Dit is toch antwoord op de issue?

De vraag was eigenlijk om ervoor te zorgen dat wanneer je drugs verkoopt het percentage ook omhoog gaat (nu is dat alleen bij plukken). En dat je met een hoger percentage eventueel ook wat sneller verkoopt of meer zakjes tegelijk dan normaal. Het verkopen gaat dan voornamelijk over de quicksell cirkels, geen idee of het ook toegevoegd kan worden voor het nieuwe systeem.

**Comment by niekschoemaker** [comment]
Bij verkopen is dit niet logisch, ik zal echter wel even de hoeveelheid XP die je krijgt wat aanpassen gezien de max die nu iemand heeft 24% is, dus zal dit ietsje aanpassen zodat het wat meer nut heeft.
