### ISSUE TITLE
[FEATURE]: Spawnplek voor voertuigen ( politie ) speciale eenheden narcopolis. [Burgerraad]

### ISSUE THREAD

**Issue by Daxn872** [Tedeapolis/development#1242]
### Contact Details

Daan#6435

### Beschrijf zo duidelijk mogelijk de feature

**[ Goedgekeurd tijdens burgerraad ]** 
Het toevoegen van een voertuigen spawn voor bepaalde politie rangen met voertuigen voor op het eiland.

**rangen**
- Police 12
- police 13
- police 14
- police 15
- police boss

**Voertuigen**
/car armed
/car unarmed
( Dus niet de overige politie voertuigen indien mogelijk 😄 )

**coördinaten om voertuig te pakken**
X: 4427.89 Y: -4480.47 Z:4.32 H: 129.56

**coördinaten waar voertuigen moeten spawnen**
X: 4423.61 Y: -4497.02 Z: 4.21 H: 203.79

Side note: Deze voertuigen moeten in roleplay vervoerd worden dmv een "chinook". Daarna mogen ze gepakt worden dmv de voertuig spawn. 

### Wat lost deze feature op?

Dat de voertuigen die hiervoor zijn toegevoegd ook gebruikt kunnen worden & niet door staff in-gespawned hoeven te worden.

**Comment by Streamcentralrulez** [comment]
Gelieve ook voor de volgende rangen van de Marechaussee:

kmar 100 - Label: Marechaussee Luitenant-Generaal
kmar 95 - Label: Marechaussee Generaal-Majoor
kmar 90 - Label: Marechaussee Brigadegeneraal 
kmar 83 – Label: Majoor 
kmar 82 – Label: Officieren 
kmar 81 – Label: Onderofficieren
kmar 80 – Label: Korporaals

**Comment by Chang-nl** [comment]
gefixt na volgende restart!
