### ISSUE TITLE
[FEATURE]: Mogelijk maken van wapens in hand te houden tijdens emote. [Burgerraad]

### ISSUE THREAD

**Issue by Daxn872** [Tedeapolis/development#1243]
### Contact Details

Daan#6435

### Beschrijf zo duidelijk mogelijk de feature

**Wapens in hand houden tijdens /e (emote)**

**Wat word er verwacht?**
Graag word er gezien dat op het moment dat jij een emote doet je jouw vuurwapen in de hand houdt op het moment dat jij de emote doet.

**Wat gebeurt er momenteel?** 
Op het moment dat je jouw vuurwapen vast hebt en een emote doet, doe je eerst je vuurwapen weg en daarna doe je pas de emote.

Tijdens burgerraad is er besproken dat hier een github voor aangemaakt moet worden om te kijken wat de mogelijkheden hierin zijn. 

### Wat lost deze feature op?

Meer mogelijkheden in roleplay en diversiteit door het gebruik van emotes.

**Comment by Ljosfari** [comment]
Ik heb dit besproken, en dit is helaas niet mogelijk. dit is express geblokkeerd, anders kun je in elke emote tegelijkertijd schieten als je een wapen vast hebt
