### ISSUE TITLE
[FEATURE]: Wasbeurt prijs aanpassing ANWB f6 facturen menu

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1244]
### Contact Details

DeStefanoKiller#4442

### Beschrijf zo duidelijk mogelijk de feature

Wij hebben besloten bij de ANWB om het Wasbeurt factuur omhoog te gooien van €50 naar €169.

### Wat lost deze feature op?

-

**Comment by Willem-Dekker** [comment]
done
