### ISSUE TITLE
[FEATURE]: KMar salarissen

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1246]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

aanpassen onduty salarissen Koninklijke Marechaussee:

kmar 40 - 1200
kmar 35 - 1100
kmar 30 - 1000
kmar 25 - 900
kmar 20 -  800
kmar 15 - 750
kmar 10 - 700
kmar 5 - 650
kmar 3 - 600
kmar 0 - 550

PS: Offduty salarissen mogen hetzelfde blijven

### Wat lost deze feature op?

-

**Comment by Willem-Dekker** [comment]
zit er in na restarf
