### ISSUE TITLE
[Bug]: Amarok Kmar

### ISSUE THREAD

**Issue by Mxcro1** [Tedeapolis/development#1247]
### Contact Details

Mxcro#9999

### Wat gebeurde er?

Ik kwam sinds gister achter dat de achter raam van de Kmar Amarok bullterproof is wat gewoon een raam is en waar je normaal gezien gewoon doorheen kan schieten

Voorbeeld clip in de testserver:

https://streamable.com/50xmpp

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Lorenzo3001** [comment]
Is na de restart gefixed
