### ISSUE TITLE
[Bug]: Bo rents (Graag spoedig mogelijk hier naar kijken)

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1248]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je kan nu illegale voorwerpen in Bo rents stoppen, dit lijkt me niet de bedoeling aangezien Misstake hier een voorwaarde aan gaf (zie screenshot)
![Uploading image.png…]()

### Wat hoorde er te gebeuren?

Je hoort er geen illegale voorwerpen in te kunnen doen.

### Wat veroorzaakt de bug?

n.v.t.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by CalRayy** [comment]
![dsfsd](https://user-images.githubusercontent.com/101106299/163469513-1d93e90d-2fee-46bb-a1b2-eb51878f9ff3.png)

**Comment by Chang-nl** [comment]
bij mij werkt het zoals het moet werken, zou je hier een repro aan toe kunnen voegen.

**Comment by CalRayy** [comment]
https://youtu.be/M1VVRrjjU-Y
