### ISSUE TITLE
[Bug]: TDA Media

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1249]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Er staat een dot op de map en de dot op de map heet TDA Media (zie screenshot)
![image](https://user-images.githubusercontent.com/101106299/163474931-6815a9d4-5be2-4cf7-8af1-3eed03dc5d38.png)
![Uploading image.png…]()

### Wat hoorde er te gebeuren?

De dot hoort bij het gebouw van TDA Media te zijn en niet midden op een weg.

### Wat veroorzaakt de bug?

Geen flauw idee.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/163475185-1fbd89a0-cf68-44e4-99a5-6674e266dc72.png)

**Comment by Chang-nl** [comment]
Kun je coördinaten hier doorgeven van waar de blip wel moet?

**Comment by Willem-Dekker** [comment]
fixed na restart
