### ISSUE TITLE
Bloed percentage daalt niet meer

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#125]
Ik krijg over de hele dag klachten van mensen dat hun bloed percentage niet daalt, ik weet niet de oorzaak of de oplossing maar ik denk dat ik dit het beste via een github issue kan melden, momenteel los ik het op door mensen te reviven en te slappen zodat zij wel kunnen respawnen.

**Comment by Willem-Dekker** [comment]
zou gemaakt moeten zijn na restart van net
