### ISSUE TITLE
[FEATURE]:  Alwaysname command aanpassen voor staffstreams ( alleen id's zichbaar ) 

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1251]
### Contact Details

[TDA] Johnny Flodder#3559

### Beschrijf zo duidelijk mogelijk de feature

Alwaysname command aanpassen voor staffstreams ( alleen id's zichbaar ) 

### Wat lost deze feature op?

Zodat de spelers/overheidmedewerkers undercover blijven in staff streams. 

Dit is ook besproken in staffoverleg dat dit een juiste oplossing is.

**Comment by niekschoemaker** [comment]
Zit erin.

Command is togglename.

**Comment by AdventurePandah** [comment]
Is het een idee als dit meegenomen wordt in een streamermodus? Dus dat het automatisch enkel ID's laat zien op het moment een stafflid streamermodus aan heeft?
