### ISSUE TITLE
[KLEDING]:

### ISSUE THREAD

**Issue by RakeFPS** [Tedeapolis/development#1252]
### Contact Details

Rake#1111

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Bij Bril 1: No.3 glitchen de glazen. Het lijkt alsof een custom model geglitched in het gta model zit. Dit gebeurd bij verschillende kleuren. Ik zal de nummers even opnoemen van bril 2: 0, 1, 2, 3, 4, 5 en 6. Indien mogelijk zou het fijn zijn als deze gefixed worden.

Foto: 
![image](https://user-images.githubusercontent.com/89594892/163599561-bd5c4640-c782-4774-a6e9-184e7cfdb0a6.png)

**Comment by MisterM02** [comment]
Fixed. Zit z.s.m. in de main
