### ISSUE TITLE
[Bug]: Porto nummers boven 9999

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1253]
### Contact Details

Tom974#9209

### Wat gebeurde er?

Je kunt nu in een hogere porto zitten als 9999, (meer als 4 getallen dus), echter kan je een porto met meer als 4 getallen (ex. 56316) niet joinen via het Shift + f2 menu. Je moet hiervoor /frequency 56316 gebruiken en kunt dit niet via het shift + f2 menu invullen, deze accepteert maar tot 4 getallen. 

### Wat hoorde er te gebeuren?

Meer als 4 getallen in kunnen vullen, in dit geval 5 dus. (aangezien porto's nu tot 99999 gaan als ik het goed heb).

### Wat veroorzaakt de bug?

1) Zorg dat je een porto op zak hebt
2) Open het menu met shift + f2
3) Probeer een 5-cijferige porto in te vullen, je zult zien dat het maar tot 4 cijfers werkt.

NOTE: Het werkt dus wel via /frequency, maar niet via het menu.

### Frequentie van de bug

Meerdere keren per dag

**Comment by Tom974** [comment]
Wanneer je ook via /frequency een porto met meer dan 4 cijfers bent gejoined, en vervolgens deze via het shift + f2 menu wilt aanpassen, bugged het menutje waar je de getallen invult ook en krijg je 5x het getal "2" achter elkaar :'p
![image](https://user-images.githubusercontent.com/55812394/163673468-b692ab55-c4f2-47bf-a4c5-34d41f5d8646.png)

**Comment by Chang-nl** [comment]
yes, na restart gefixt!
