### ISSUE TITLE
[FEATURE]: Benzineverbruik bij motorstoring

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1258]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Als je een lampje krijgt in je voertuig, dat de motor een bepaald percentage (30% of iets dergelijks) meer aan brandstof verbruikt. De motor werkt niet zoals deze moet werken. Hij zal dus meer moeten werken om vermogen te moeten leveren.

### Wat lost deze feature op?

Voegt realisme toe qua motoren/voertuigen.

**Comment by Chang-nl** [comment]
na restart gefixt
