### ISSUE TITLE
[Bug]: Shotgun ammo naam

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1259]
### Contact Details

Dekk#3971

### Wat gebeurde er?

De shotgun ammo heeft als enige niet de naam van de wapen in de ammo naam;

### Wat hoorde er te gebeuren?

Wel de naam van het wapen in de ammo naam. 

### Wat veroorzaakt de bug?

Gewoon niet toegevoegd. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/50420682/163865983-41827f18-1b73-4d34-a77d-50dbfebfcb49.png)
![image](https://user-images.githubusercontent.com/50420682/163865998-dbf44e0f-6df5-4fba-9694-83c8ca0315f2.png)

**Comment by Tijz** [comment]
![image](https://user-images.githubusercontent.com/50420682/163866042-d86613e5-5aea-4dc4-afb3-b47c4e20ecdb.png)

**Comment by Chang-nl** [comment]
is aangepast na volgende restart!
