### ISSUE TITLE
[Bug]: Overheids meldingen zit geen scroll lock op

### ISSUE THREAD

**Issue by NavyEU** [Tedeapolis/development#1260]
### Contact Details

Navy#7049

### Wat gebeurde er?

Als een burger een melding maakt bij de overheid dan komt dat binnen op veel telefoons van werknemers. Elke keer als er een melding binnen komt dan word je terug naar onder gezet naar de meest recente melding wat aardig vervelend is om de meldingen goed bij te houden / terug te vinden.

### Wat hoorde er te gebeuren?

Een scroll lock toevoegen zodat je blijft waar je bent ipv terug naar onder gezet worden.

### Wat veroorzaakt de bug?

Scroll omhoog in de meldkamer, wacht tot er een nieuwe melding komt en je word automatisch teruggezet naar onder

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is na volgende restart gefixed
