### ISSUE TITLE
[BUG]: Sloten op unmarked BMW politie werken niet

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1261]
### Contact Details

Arjen#0001

### Kenteken van voertuig

N.v.t.

### Voertuig model

Unmarked BMW (/car FBI)

### Omschrijf de bug

Met het voertuig op slot kun je nog steeds instappen.

### Repro

Pak een unmarked BMW, zet het voertuig op slot en stap in.

### Normaal gedrag

Zou niet in een auto moeten kunnen stappen die op slot staat.

**Comment by Chang-nl** [comment]
Is dit alleen bij dit specifieke model? Of ook bij andere (unmarked) voertuigen? En hoe/via waar heb je de voertuigen gepakt?

**Comment by ARJ3N** [comment]
> Is dit alleen bij dit specifieke model? Of ook bij andere (unmarked) voertuigen? En hoe/via waar heb je de voertuigen gepakt?

Voor zover bij mij bekend is het enkel dit voertuig. Je kunt die pakken bij alle locaties waar je de andere politievoertuigen ook pakt, zoals onder bij de parkeerplaats bij het HB in de stad, of voor het bureau in Sandy etc.

**Comment by niekschoemaker** [comment]
Is gefixed na volgende restart
