### ISSUE TITLE
[BUG]: Standaard GTA meldkamer is te horen in politievoertuigen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1262]
### Contact Details

Arjen#0001

### Kenteken van voertuig

N.v.t.

### Voertuig model

Alle politievoertuigen.

### Omschrijf de bug

Zoals je in GTA story mode of online hebt, hoor je de Engelse meldkamer van de LSPD terwijl je in een politievoertuig zit.

### Repro

Pak een politievoertuig en wacht even tot je een NPC hoort praten in de meldkamer.

### Normaal gedrag

Voorheen was dit niet zo en hoorde je deze meldkamer niet.

**Comment by Willem-Dekker** [comment]
maakt het net echt toch

**Comment by Joost010** [comment]
Dan is het dubbel op omdat we ook al communiceren via de porto.

**Comment by Willem-Dekker** [comment]
is een fix voor gemaakt echter weet ik niet of het werkt

**Comment by Ljosfari** [comment]
is dit opgelost ?

**Comment by Joost010** [comment]
> 

Helaas hoor ik nog steeds de Engelse meldkamer in de voertuigen

**Comment by Chang-nl** [comment]
Is gefixt na volgende server restart!

**Comment by ARJ3N** [comment]
@Chang-nl net even getest maar is helaas nog niet gefixt.

**Comment by Chang-nl** [comment]
Dus dan word het volgende restart of de restart erna ik heb geen idee

**Comment by Chang-nl** [comment]
Oke ik had een foutje gemaakt in het committen het is na de restart van morgen opgelost
