### ISSUE TITLE
[FEATURE]: Voertuig rangen KMAR veranderen

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1263]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Graag de volgende aanpassen zodat er andere rangen ook bij de voertuigen kunnen:
kmar 20 - Label: Marechaussee Opperwachtmeester - Voertuigen: + Motor on-/off-road
kmar 15 - Label: Marechaussee Wachtmeester 1e klasse - Voertuigen: +SIV (Audi A6)

### Wat lost deze feature op?

Dat opperwachtmeesters bij beide motoren kunnen en dat wachtmeester 1e klasse bij de SIV kunnen

**Comment by Willem-Dekker** [comment]
fixed na restard
