### ISSUE TITLE
[FEATURE]: Garage plaatsing

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1264]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag een garage willen op deze locatie.

Locaties van de plaatsingen;
https://prnt.sc/ZAitoKBdPnK3

Coords rode cirkel: x: -773,51 y: -199,43 z: 37,16 h: 300,23
Coords oranje cirkel: x: -775,68 y: -194,80 z: 37,28 h: 124,49
Coords grone cirkel: x: -777,52 y: -191,25 z: 37,28 h: 120,78

Auto Spawnlocatie 1: x: -790,04 y: -200,72 z: 37,28 h: 300,00
Auto Spawnlocatie 2: x: -791,81 y: -197,71 z: 37,28 h: 300,00
Auto Spawnlocatie 3: x: -794,35 y: -193,47 z: 37,28 h: 300,00
Auto Spawnlocatie 4: x: -796,04 y: -190,40 z: 37,28 h: 300,00

### Wat lost deze feature op?

Dit zal een hele hoop schelen met het gezijk dat de auto's despawnen, omdat de garage bij het gemeente huis net te ver is waardoor deze auto's dus despawnen in de cardealer op 7044.

Als deze garage zou zitten kunnen auto's dichtbij gepakt worden waardoor autos dus niet despawnen.

Ook scheeld het lagg door dat mensen waarvan de auto's niet persee er moeten staan simpel en snel weg te zetten.

Soms despawnen auto's in het pand door dat deze soms dicht bij elkaar komen waardoor ze in de oranje cirkel komen, hiermee kunnen die makkelijker eruit worden gehaald.

**Comment by Willem-Dekker** [comment]
duplicate van #1122
