### ISSUE TITLE
[FEATURE]: Command om reports uit te kunnen zetten.

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1265]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een command die je kunt gebruiken zodat de reports niet meer links bovenin verschijnen.

### Wat lost deze feature op?

Handig voor wanneer je aan het roleplayen bent en eventjes geen reports wilt zien. Tevens ook handig voor staff die aan roleplay livestreams doen, die hoeven dan tijdens het roleplayen niet hun tekstvlak linksbovenin te blurren.

**Comment by Attomn** [comment]
Bestaat nu, iets in de trent van /report_settings kan je hiervoor gebruiken.

**Comment by brothasx** [comment]
Bestaat nu, iets in de trent van /report_settings kan je hiervoor gebruiken.
