### ISSUE TITLE
[FEATURE]: FIB gebouw heist toevoegen

### ISSUE THREAD

**Issue by Goonsie** [Tedeapolis/development#1266]
### Contact Details

anthony0183#7651

### Beschrijf zo duidelijk mogelijk de feature

Een eventuele toevoeging voor de criminelen aan de stad toevoegen.
Klik op link voor een demonstratie video. https://buy-fivem.com/product/fib-heist/?v=796834e7a283

### Wat lost deze feature op?

Toevoeging van criminalteit

**Comment by zeletix** [comment]
Het zou mij wel beter lijken als je iets anders dan geld pakt, geclassificeerde documenten ofzo. Die je dan weer ergens moet verkopen.
