### ISSUE TITLE
[Bug]: je kan een witwaspunt pakken zonder geld

### ISSUE THREAD

**Issue by NavyEU** [Tedeapolis/development#1267]
### Contact Details

Navy#7049

### Wat gebeurde er?

Wij controleren iemand die in een witwasbus reed waarvan een melding afging, vervolgens heeft de persoon geen geld bij zich. 1minuut later pakt hij een nieuwe punt zonder nieuw geld gepakt te kunnen hebben en gaat de melding weer af.

### Wat hoorde er te gebeuren?

Dat het persoon niet verder kan met wassen

### Wat veroorzaakt de bug?

Wassen zonder geld

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
dit is getest en komt bij ons niet voor
