### ISSUE TITLE
[Bug]: Radio

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1269]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik merk dat niet elke radio station in je voertuig niet werkt, is het mogelijk om ze allemaal hoorbaar te maken?

### Wat hoorde er te gebeuren?

Je hoort alle radio's station gebruiken, maar ze werken niet allemaal.

### Wat veroorzaakt de bug?

Geen flauw idee, eerlijk gezegd.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Willem-Dekker** [comment]
welke stations?

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/164765546-50ceee50-3ef0-432a-a54c-4c2832470bc3.png)
Alle omcirkelde radio stations werken helaas niet.

**Comment by Willem-Dekker** [comment]
alle streams die broken waren zijn weer aan
