### ISSUE TITLE
[FEATURE]: Cap op clips in inventory

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1274]
### Contact Details

[TDA] Johnny Flodder#3559

### Beschrijf zo duidelijk mogelijk de feature

Besproken in staffoverleg: 

Een cap zetten op munitie voor zowel Criminelen als Politie. ( In de hoop dat er daardoor meer rp aangegaan wordt, dan wordt geschoten )

### Wat lost deze feature op?

Dat er meer rp aangegaan wordt en dat er zuiniger omgegaan wordt met wapens.

**Comment by CoffeeSipper** [comment]
Of ze het nou bij zich hebben of in de kofferbak leggen, verschil maak je er niet mee.

**Comment by Chang-nl** [comment]
De cap staat nu op 2!
