### ISSUE TITLE
[FEATURE]: Zichtbaar maken fouilleren en confisqueren

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1275]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kan je zonder dat het zichtbaar is voor andere iemand fouilleren of een wapen confisqueren.
Daarom is besproken dat dit zichtbaar moet worden op de volgende manieren:

- [x] Aan fouilleren een animatie toevoegen (bv. /e mechanic)
- [x] Wanneer een wapen geconfisqueerd wordt deze automatisch in de handen van de persoon laten komen (Als dat niet mogelijk is eventueel ook een animatie toevoegen)

### Wat lost deze feature op?

Handelingen worden zichtbaar waardoor powergamen op dat gebied niet meer mogelijk is

**Comment by Attomn** [comment]
- Animatie om toe te voegen: "/e parkingmeter"

**Comment by Chang-nl** [comment]
Gefixt morgen na herstart!
