### ISSUE TITLE
[Safezones weghalen]: 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1276]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staffoverleg is er besproken en tevens goedgekeurd 
om alle safezones weg te halen op die bij het ziekenhuis, casino en gemeentehuis na ( Voornamelijk de Job safezones ) 

Aangezien deze safezones best een lange afstand met zich meenemen en geen chaos/drukte meer is deze weghalen.

### Wat lost deze feature op?

De safezones in zijn geheel weghalen dit is besproken tijdens staffoverleg

**Comment by Willem-Dekker** [comment]
Ga er vanuit dat het nu werkt gezien geen reactie
