### ISSUE TITLE
[FEATURE]: Verhoog brandstoftank Actros

### ISSUE THREAD

**Issue by jaim1114** [Tedeapolis/development#1278]
### Contact Details

jaim#1114

### Beschrijf zo duidelijk mogelijk de feature

De brankstoftank van de Mercedes-Benz Actros (vrachtwagen) verhogen. Hier gaat nu slechts 65 liter in, terwijl er bijvoorbeeld in een RS6 2020 al 80 liter brandstof gaat. De brandstoftank van de Actros zou wat bij betreft meer op z'n plek horen bij 100 liter. 

### Wat lost deze feature op?

Meer realisme in de stad met betrekking tot de inhoud van brandstoftanks.

**Comment by Lorenzo3001** [comment]
Is na de restart aangepast naar 95L
