### ISSUE TITLE
Taxi factuur verdwijnt bij versturen zonder passagier

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#128]
Wanneer een klant uitstapt en de taxibestuurder nèt te laat de factuur verstuurt wordt melding gegeven dat er geen passagier in het voertuig aanwezig is. Vervolgens wordt de meter gereset. Wanneer iemand (te) snel uitstapt en de chauffeur (te) laat de factuur stuurt, ontstaat er een probleem.

Graag een oplossing hiervoor: is het bijvoorbeeld nodig de meter niet te resetten en in plaats daarvan een ja/nee melding te geven ("wil je de meter resetten? Y/N")

**Comment by Willem-Dekker** [comment]
Fixed: de meter wordt pas gereset na een succesvolle zending van een factuur
