### ISSUE TITLE
[Bug]: Electronica winkel in het noorden

### ISSUE THREAD

**Issue by TDAMitchell** [Tedeapolis/development#1280]
### Contact Details

Mitchelll#1258

### Wat gebeurde er?

Er kwam een report binnen van de electronica winkel dat deze niet zou werken. Ik ben er heen getp't en kwam tot mijn ontdekking dat de cirkel er wel is, maar niks in de cirkel https://gyazo.com/fdcadcd9a178689bb71cfda028d4e8d2

### Wat hoorde er te gebeuren?

Normaal zou hier dezelfde lijst in moeten staan als dat er in de electronica winkel in de stad staat. Echter is dit dus niet het geval.

### Wat veroorzaakt de bug?

Waarschijnlijk is het er niet ingezet en is alleen de cirkel toegevoegd.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://gyazo.com/e4e941ede8d7ab5a677ea568595754e3

Hier een clip

**Comment by Chang-nl** [comment]
stom stom stom verkeerde database naam, fucking stupid dat ik ben. In ieder geval na volgende restart gefixed.

**Comment by TDAMitchell** [comment]
> stom stom stom verkeerde database naam, fucking stupid dat ik ben. In ieder geval na volgende restart gefixed.

Je bent een topper
