### ISSUE TITLE
[FEATURE]: Generieke bezorgdienst overheidsjob

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1281]
### Contact Details

Hellfire

### Beschrijf zo duidelijk mogelijk de feature

Ik moest deze van Willem schrijven omdat hijzelf te lui is.
Dus hij weet zelf wat erin moet. 

### Wat lost deze feature op?

Dat Willem weer 1 taak kan afstrepen van zijn lijst.

**Comment by Willem-Dekker** [comment]
zie #667

**Comment by niekschoemaker** [comment]
Duplicate of #667

**Comment by niekschoemaker** [comment]
Duplicate of #667
