### ISSUE TITLE
[Bug]: Ambulance voertuigen sloten

### ISSUE THREAD

**Issue by SgtPointless** [Tedeapolis/development#1282]
### Contact Details

SgtPointless#7305

### Wat gebeurde er?

Het gebeurd regelmatig dat we uitstappen bij een melding en we doen de bus op slot dat er dan alsnog een nieuwe speler in kan stappen en weg rijden met het voertuig.

### Wat hoorde er te gebeuren?

Dat als er links bovenin "Dicht" staat het voertuig daadwerkelijk op slot gaat.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
is gefixed na volgende restart
