### ISSUE TITLE
[FEATURE]: HP verlies na het lang zwemmen in het water 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1283]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Bij staffoverleg op 03-04-2022 is er besproken om een Github aan te maken over het te lang door zwemmen in het water zonder uitgeput te raken en daarbij ook geen HP verliest.

Nu is er besproken of het mogelijk is als je te lang zwemt langzaam HP begint te verliezen, doordat je onderkoeld raakt en uitgeput raakt in de zee. 

### Wat lost deze feature op?

Door toe te voegen dat als je zwemt in de zee dat er op een begeven moment je uitgeput raakt en langzamerhand HP begint te verliezen.

**Comment by niekschoemaker** [comment]
Zit erin.

**Comment by CalRayy** [comment]
> Zit erin.

Krijg je ook damage als je met een duikfles aan het zwemmen / onderwater bent na een lange tijd?
