### ISSUE TITLE
[FEATURE]: Drank

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1284]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Er zijn enkele dranken in de stad, maar ze maken je niet echt dronken. De enige drank die ik heb opgemerkt die je dronken maakt is tequilla, is het mogelijk om meerdere dranken je dronken te laten maken zoals:
- Jagermeister
- Bier
- Whisky
- Rum
- White Martini
- Vodka

### Wat lost deze feature op?

Dit zou het meer realistischer maken en meer toffe avonden in Tedeapolis clubs.

**Comment by Willem-Dekker** [comment]
zit er na restart in
