### ISSUE TITLE
[FEATURE]: Pasje gokvergunning 

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1286]
### Contact Details

Hellfire

### Beschrijf zo duidelijk mogelijk de feature

Een fysieke pas die uitgegeven kan worden justitie als extra check op gokvergunningen voor bedrijven.
Dit idee kwam bij Willem vandaan en die weet als het goed is hoe dit verder uitgewerkt kan worden.

### Wat lost deze feature op?

Het lost een extra stukje oplichten op, doordat er strenge checks worden uitgevoerd voordat mensen een gokvergunning voor een bedrijf krijgen in de stad in combinatie met deze pas die getoond kan worden.

**Comment by Willem-Dekker** [comment]
@brothasx Zou jij hier een afbeelding voor kunnen maken? Voornaam, Achternaam, en een pasnummer veld?

**Comment by brothasx** [comment]
@Willem-Dekker  Deze is gemaakt en staat in de idplugin. Met de naam gokvergunningid.

**Comment by Willem-Dekker** [comment]
@brothasx topper ga ik er mee aan de slag

**Comment by Willem-Dekker** [comment]
@brothasx hier staan helaas de velden op een andere plek dan bij alle andere passen

**Comment by Willem-Dekker** [comment]
wacht op Document en de rangen die deze vergunningen mogen verstrekken

**Comment by Hellie94** [comment]
Pas uitgifte: Minister, staatssecretaris, kvk beheer

**Comment by Willem-Dekker** [comment]
perms zitten er in na restart
