### ISSUE TITLE
[FEATURE]: Nieuwe document Justitie voor leningen

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1288]
### Contact Details

Hellfire

### Beschrijf zo duidelijk mogelijk de feature

Voor het leningen systeem zouden wij graag een nieuw document in de stad krijgen.
Hieronder een grove schets van hou ik het voor ogen had.
![Leningovereenkomst](https://user-images.githubusercontent.com/77858957/166143347-ef57373f-86bd-4c9f-aef9-751bc25d1257.png)

### Wat lost deze feature op?

Dat wij volledig aan de slag kunnen met het leningen systeem voor burgers in de stad.

**Comment by Willem-Dekker** [comment]
![image](https://user-images.githubusercontent.com/16556575/166143774-615ece29-f608-4534-ba13-022ccdfec9bc.png)
dit is er nu

**Comment by Willem-Dekker** [comment]
Meerdere handtekeningen worden op dit moment niet ondersteund.

**Comment by Hellie94** [comment]
Ik zal even met de rest de standaard voorwaarden opstellen.
Die handtekening is jammer, maar maakt voor de rest niet zoveel uit. 

Verder:

Leningverstrekker, staat nu met een a

**Comment by Hellie94** [comment]
1. Leningdocumenten kunnen enkel worden uitgeschreven door personen van Justitie welke aangesteld zijn als notaris en daarvoor bevoegd zijn deze uit te schrijven. Voor elke andere lening is de documentopsteller zelf hoofdelijk aansprakelijk.  

2. Indien lener te laat is met afbetalen na afgesproken datum, dan krijgt deze 1 week om te betalen of een betalingsregeling te treffen. Indien de persoon dit niet doet, dan zal deze een boete ontvangen van het geleende bedrag + afgesproken rente.

3. Indien er sprake is van hetgeen genoemd in punt 2, dan zal de gemeente Tedeapolis huidige of toekomstige schulden in geen geval meer kwijtschelden.

**Comment by Willem-Dekker** [comment]
![image](https://user-images.githubusercontent.com/16556575/166501508-78a02953-5fc3-41bd-ac7d-85da037da88b.png)

**Comment by Willem-Dekker** [comment]
zit er in na restart
