### ISSUE TITLE
[Bug]: Complex bazen perms (second job)

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1289]
### Contact Details

MisterM#0001

### Wat gebeurde er?

Als je "unicorn boss" als second job hebt kan je de bazencirkel niet openen.
Dit zou betekenen dat je hiervoor persé je first job moet weghalen, wat erg vervelend is om constant te doen.

### Wat hoorde er te gebeuren?

Als je "unicorn boss" als second job hebt zou je de bazencirkel gewoon moeten kunnen openen.

### Wat veroorzaakt de bug?

Vermoedelijk omdat de job als second wordt gezien.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Klopt, dit is een issue waarvan ik weet maar is moeilijk te fixen en is qua impact heel erg laag, dus word niet gefixed.

Je kunt in plaats hiervan gewoon setjob gebruiken in principe.
