### ISSUE TITLE
[FEATURE]: Spawnplek voor /armed & /unarmed KCT Humvees verplaatsen naar vliegdekschip

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1290]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Sinds kort heeft het KCT een spawnplek op eiland voor de humvees (zie #1242).

Dit was gedaan omdat persoon die de feature request had aangevraagd nog dacht dat je de Humvees niet via Chinook kon verplaatsen omdat ze dan ontploften (was voorheen een bug).
Ik heb dit getest en dit blijkt wel mogelijk te zijn. Graag daarom de spawnplek verplaatsen naar het vliegdekschip en op de legerbasis. Op deze beide locaties staat al een cirkel om andere voertuigen te kunnen pakken. Eventueel kunnen ze hier aan toegevoegd worden?

### Wat lost deze feature op?

Zorgt voor betere roleplay mogelijkheden voor zowel de KLu als het KCT.

**Comment by Willem-Dekker** [comment]
zit er in na restart

**Comment by PolitieTDA** [comment]
> zit er in na restart

Ik zie deze nog niet staan op vliegdekschip, wel de reguliere voertuigen winkel, maar daar staan die Humvees niet tussen.

**Comment by Willem-Dekker** [comment]
dat is de zelfde dealer

**Comment by ARJ3N** [comment]
> dat is de zelfde dealer

Ze staan niet tussen de politie dealer.
