### ISSUE TITLE
Les Révoltés perms veranderingen.

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1291]
### Contact Details

Dekk#3971

### Beschrijf zo duidelijk mogelijk de feature

Les Révoltés job changes, staat al 4 maanden een ticket open, echter werd recent door Willem verteld dat dit via een github moet. 

De volgende veranderingen moeten doorgevoerd worden;

- [x] - Fondateur moet alle permissions hebben behalve het aannemen van mensen. Fondateur kan momenteel niet het potgeld beheren.
- [x] - Narreteur naam veranderen naar "Capitaine".
- [x] - De 4 hoogste rangen toegang geven tot de bazenheli (commandant, capitaine, fondateur & patron).
- [ ] - Nettoyeur (hangaround) alleen toegang verlenen tot sloten, verder niks, dus ook geen opslag en voertuig opslag etc. 

### Wat lost deze feature op?

Een aantal onhandige dingen binnen de gang.

**Comment by Willem-Dekker** [comment]
Garage is niet instelbaar momenteel andere aanpassingen zitter er na de herstart in.

**Comment by Willem-Dekker** [comment]
garages zit er ook in
