### ISSUE TITLE
[Bug]: Noodknop taxi komt niet goed binnen in meldkamer

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1292]
### Contact Details

Arjen#0001

### Wat gebeurde er?

De politie krijgt niet het juiste bericht binnen in de meldkamer wanneer een taxi chauffeur een noodknop verstuurt. Ook staat er dat die van de ambulance komt, terwijl dat niet zo is, zoals te zien is op onderstaande afbeelding:
![image](https://user-images.githubusercontent.com/93579695/166309831-5de125a9-ed71-4300-8c2b-bc8c70bb1a0f.png)

### Wat hoorde er te gebeuren?

Hoort een normaal bericht weergegeven te worden en de juiste overheidsberoep hoort erbij te staan.

### Wat veroorzaakt de bug?

Taxi drukt noodknop in.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Willem-Dekker** [comment]
na restart gefixed
