### ISSUE TITLE
[Bug]: Bankovervallen werken niet

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1293]
### Contact Details

MisterM#0001

### Wat gebeurde er?

De afgelopen 2 dagen kunnen er geen bankovervallen gepleegd worden. Elke keer komt de melding "De kluis van deze bank is nog leeg", terwijl dat helemaal niet zo hoort te zijn. De 24 uur daarvoor is deze namelijk niet overvallen.

### Wat hoorde er te gebeuren?

De bank hoort na 24 uur gereset te worden waardoor hij weer gevuld is. Dit gebeurd momenteel echter niet, waardoor banken niet overvallen kunnen worden. De kluis is namelijk constant leeg.

### Wat veroorzaakt de bug?

Voor wat ik in de logs terug zie restart de timer van elke bank, hierna spawnen de trolleys met geld en kort hierna despawnen ze allemaal.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Zie logs van 2 mei 2022.

**Comment by MisterM02** [comment]
Het lijkt erop dat dit probleem zichzelf heeft opgelost.

**Comment by zeletix** [comment]
> Het lijkt erop dat dit probleem zichzelf heeft opgelost.

Dit blijkt nog steeds een issue te zijn, ik heb hier laatste twee dagen veel last van gehad.

**Comment by ARJ3N** [comment]
> Zou gefixed moeten zijn na restart

Krijg te horen van een speler dat het nog niet werkt. Heeft twee banken geprobeerd na de restart maar beide geven nog aan dat de kluis leeg is.

**Comment by niekschoemaker** [comment]
Ik zie in de logs dat het weer werkt
