### ISSUE TITLE
[FEATURE]: Aanpassing 14k rangen

### ISSUE THREAD

**Issue by Enrico14k** [Tedeapolis/development#1294]
### Contact Details

Enrico#4089

### Beschrijf zo duidelijk mogelijk de feature

- Een extra rang toevoegen voor nieuwe mensen die alleen sleutels van het huis krijgen, verder niks (geen opslag cirkel, geen garage cirkel etc.). 

Wij kregen te horen dat je geen meelopers mag hebben zonder rang, dus zouden wij graag een "Non Member" rang willen aanvragen die er als volgt uit ziet:

14k Triade - 非會員

### Wat lost deze feature op?

- Geen onnodige moeilijkheden m.b.t. meelopers die nu worden gezien als samenwerking.

**Comment by Willem-Dekker** [comment]
kan ik hier niet de hangaroud rank voor gebruiken?

**Comment by Willem-Dekker** [comment]
rank 0 kan gebruikt worden dus de hangaround rank

**Comment by Enrico14k** [comment]
> kan ik hier niet de hangaroud rank voor gebruiken?

Uhm, dat zou dan betekenen dat als iemand wordt aangenomen hij eigenlijk niks kan, maar dan bij de eerste promotie gelijk alles kan, op natuurlijk de bazen cirkels etc na. Dus dan na de eerste promotie heeft iemand gelijk F6 menu en toegang tot de opslag.
