### ISSUE TITLE
[Bug]: Probleem met het Doodverklaren via F6

### ISSUE THREAD

**Issue by SgtPointless** [Tedeapolis/development#1295]
### Contact Details

SgtPointless#7305

### Wat gebeurde er?

Het komt steeds vaker voor dat als mensen doodverklaard worden dat ze dan onder het wegdek komen of onzichtbaar op de grond terecht komen en nog collided zijn. Ook reset hun timer dan niet en moeten ze alsnog 15 min wachten.

### Wat hoorde er te gebeuren?

Dat als we via het F6 menu van de ambulance op de knop doodverklaren drukken dat het slachtoffer direct kan respawnen en dat ze non collision zijn.

### Frequentie van de bug

Meerdere keren per dag

**Comment by niekschoemaker** [comment]
Als het goed is is dit nu gefixed.

Op de 1 of andere manier was de body bag spontaan geen geldig model meer, dus zou nu gefixed moeten zijn.

Je kunt ook even /carry doen, en als hij dan niet verschijnt weet je dat de zak dus niet bestaat, als hij dan wel verschijnt zat hij idd onder de map.
Want het probleem was dus dat de body bag uberhaupt niet aangemaakt werd

**Comment by niekschoemaker** [comment]
Was dit ondertussen gefixed?
