### ISSUE TITLE
[FEATURE]: Zaklampen toevoegen aan Opslag

### ISSUE THREAD

**Issue by SgtPointless** [Tedeapolis/development#1296]
### Contact Details

SgtPointless#7305

### Beschrijf zo duidelijk mogelijk de feature

Bij de laatste vergadering is een puntje naar boven gekomen waarbij een suggestie kregen over het toevoegen van de zaklamp in de opslag. Dat puntje is ook nog tijdens de burgerraad besproken en we kwamen tot de conclusie dat het een goed idee was en dat er een Github voor gemaakt kon worden.

In sommige scenario's kan de ambulance door gebruik te maken van een zaklamp een behandeling of diagnose voortzetten. We testen bijvoorbeeld bij een vermoeden van een hersenschudding of er klachten zijn van een bepaalde lichtgevoeligheid. Dat kunnen wij natuurlijk testen door gebruik te maken van een zaklamp.

### Wat lost deze feature op?

Aangezien we niet welkom zijn op het eiland kunnen we zonder de regels te overtreden toch een leuke roleplay neerzetten en de kwaliteit verbeteren.

**Comment by Ljosfari** [comment]
niet mogelijk
