### ISSUE TITLE
[FEATURE]: TFFT Rang aanpassen / toevoegingen

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1297]
### Contact Details

Tom974#9209 | maxjuh97#7233

### Beschrijf zo duidelijk mogelijk de feature

- [x] Extra job toevoegen voor DTMC (biker) genaamd "Support", rechtsonderin zou het dan dus staan als: "**DTMC - Support**" Dit wordt dan de rang die nu prospect heet. 

- [x] Daarnaast ook een extra rang aanmaken die "Prospect" gaat heten, hierbij dezelfde permissies als supporter / oude prospect + toegang geven tot de garage (voertuigenopslag).

Uiteindelijk zijn dit dan alle rangen:

DTMC - Support
DTMC - Prospect
DTMC - Full Patch
DTMC - Road Captain
DTMC - Enforcer
DTMC - Treasurer
DTMC - Secretary
DTMC - Sergeant
DTMC - V.President
DTMC - President

### Wat lost deze feature op?

Rangen die niet correct staan / kloppen waardoor er jobs gegeven moeten worden aan leden die niet kloppen bij hun daadwerkelijke rang.

**Comment by Willem-Dekker** [comment]
Zit er in na restart
