### ISSUE TITLE
[FEATURE]: Icona (cartel) rang aanpassingen.

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#1298]
### Beschrijf zo duidelijk mogelijk de feature

- [x] Associate - F6 menu toegang toevoegen (staat nu uit maar is niet de hangaround rang dus graag aanzetten).
- [x] Capo - Optie om bazen heli te pakken toevoegen.
- [x] Consigliere - Toegang tot de volledige wapen inkoop, dus ook ak's, toevoegen.
- Don 
  - [x]  - Toegang tot volledige wapen inkoop (kan nu geen ak's inkopen en de rest wel, graag dus ook ak's toevoegen).
  - [x]   - Personeelsbeheer toevoegen

**Comment by Willem-Dekker** [comment]
zit er in na restart van server
