### ISSUE TITLE
[FEATURE]: Aanpassingen / nieuwe rangen 14k

### ISSUE THREAD

**Issue by Enrico14k** [Tedeapolis/development#1299]
### Contact Details

Enrico#4089

### Beschrijf zo duidelijk mogelijk de feature

- [x] Nieuwe hangaround rang "14k Triade - 非會員" toevoegen die alleen sleutels tot het huis heeft en niks anders. 

- [x] "14k Triade - 选米机" Aanpassen naar hoe het was, dus sleutels tot het huis, dingen in de opslag kunnen leggen, item winkel en de voertuigen opslag.

### Wat lost deze feature op?

Door dat de rangen niet meer kloppen, moeten we nu mensen een rang hoger geven dan die ze daadwerkelijk horen te hebben.

**Comment by Willem-Dekker** [comment]
zit er in na restart
