### ISSUE TITLE
[Bug]: Spijkermatten werken niet naar behoren

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1300]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Als je over een spijkermat heenrijdt, gaat je band niet lek. Wel glipt je auto weg alsof de band lek is, maar hij blijft heel.

### Wat hoorde er te gebeuren?

Banden horen lek te gaan door de spijkermat.

### Wat veroorzaakt de bug?

Leg een spijkermat neer en rij er overheen.

### Frequentie van de bug

Altijd

**Comment by Chang-nl** [comment]
Niek heeft het gefixt!
