### ISSUE TITLE
[FEATURE]: Extra ANWB hesjes

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1301]
### Contact Details

DeStefanoKiller#4442

### Beschrijf zo duidelijk mogelijk de feature

Ik zal graag nog 2 extra hesjes willen bij de ANWB zoals bij het OPCO hesje wat er nu is. (kijk foto's voor het hesje wat er nu al inzit)
https://prnt.sc/1U7z7TJ7w5lI
https://prnt.sc/baJvGgs5AYAQ

- [ ] ANWB OPCO hesje "**OPCO** als tekst op de achterkant" 

- [ ] ANWB "normaal hesje zonder tekst wel ANWB logo"

### Wat lost deze feature op?

Het lost niets op maar het is een leuke toevoeging voor ANWB'ers.

**Comment by MisterM02** [comment]
Ik heb de files gemaakt, enkel nog even goed laten keuren door Whaledone en daarna moeten ze doorgevoerd worden
