### ISSUE TITLE
[Bug]: Benzinepomp

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1302]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De benzinepomp bij heli pads (zie screenshot) verdwijnt, als je van eiland naar land komt.
![image](https://user-images.githubusercontent.com/101106299/167055912-398ed5d3-204c-491c-a746-e8bde17f21b4.png)

### Wat hoorde er te gebeuren?

Je hoort de benzinepomp te zien, als je van eiland komt. Dit is volgens mij dezelfde bug toen met de pluks, maar dan met benzinepomp. Dit is trouwens ook de enigste benzinepomp die je niet kan zien. 

### Wat veroorzaakt de bug?

Ik denk hetzelfde als de eiland wiet pluk bug. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Lijkt gefixed te zijn sinds laatste updates
