### ISSUE TITLE
[Bug]: Bulletproof ramen (ferrari f430)

### ISSUE THREAD

**Issue by Mxcro1** [Tedeapolis/development#1303]
### Contact Details

Faiss#9999

### Wat gebeurde er?

Ik kwam pas achter dat de achter raam van de ferrari f430 bullterproof is wat gewoon een raam is en waar je normaal gezien gewoon doorheen kan schieten

Voorbeeld clip in de testserver:

https://streamable.com/yiji1f

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Lorenzo3001** [comment]
Fixed
