### ISSUE TITLE
[FEATURE]: Ticket logs per persoon bekijken

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1304]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Een optie om ticket history van een discord user te bekijken. Via een command/webpanel kun je een user opzoeken en daarmee krijg je alle tickets te zien waar de persoon aan toegevoegd was.

### Wat lost deze feature op?

Momenteel gebeurd het regelmatig dat spelers een nieuw ticket aanmaken voor bijvoorbeeld een refund op het moment een ander ticket gesloten wordt. Dit doen ze in de hoop dat een ander stafflid wel de refund geeft. 

Daarnaast kan het ook weleens zijn, bij unban appeals bijvoorbeeld, dat er iets opgezocht moet worden in een oud ticket wat gesloten is. Echter kost het ons enorm veel tijd om het oude ticket dan op te zoeken. Daarom deze feature request.

**Comment by niekschoemaker** [comment]
Ik ga binnenkort even kijken of dit haalbaar is, ik heb voor nu in elk geval even authorisatie toegevoegd zodat dit in elkgeval te doen is zonder dat we alle tickets per persoon vrijgeven.

**Comment by niekschoemaker** [comment]
Zit erin, je kunt nu naar: https;//tickets.tedeapolis.nl/{discord_id} (dus bijvoorbeeld: https://tickets.tedeapolis.nl/155977196278775808) om iemand zijn ticket overzicht te bekijken.
