### ISSUE TITLE
[FEATURE]: F6 menu boeien laat steamnaam zien ipv ID

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1306]
### Contact Details

Tom974#9209

### Beschrijf zo duidelijk mogelijk de feature

Zorgen dat er bij het F6 menu bij de politie en kmar tijdens het boeien zijn/haar id staat ipv de steamnaam, op het moment zie je de steamnaam en niet het id nadat je iemand geboeid hebt zoals je dat wel ziet bij het fouilleren, confisqueren etc.

### Wat lost deze feature op?

Powergaming vanuit politie/kmar.

**Comment by Chang-nl** [comment]
Na restart gefixed!
