### ISSUE TITLE
[FEATURE]: Aanpassen 14k rangen

### ISSUE THREAD

**Issue by Enrico14k** [Tedeapolis/development#1309]
### Contact Details

Enrico#4089

### Beschrijf zo duidelijk mogelijk de feature

Met de laatste update van onze rangen zijn er nog een aantal dingen fout ingesteld, we zouden graag nog enkele veranderingen willen vragen, zie hieronder:

- [ ] 14k Triade - 选米机 
    - Toegang tot de auto opslag (Zowel auto's pakken als auto's wegzetten)
    - Wapens opslaan
    - Objecten opslaan
    - Item winkel

Deze rang moet geen optie hebben om dingen uit de opslag te kunnen halen of wapens uit de opslag te kunnen pakken. Geen wapen mods kopen en geen wapen inkoop.

- [ ] 14k Triade - 非會員
    - Sleutels hebben van het huis

Deze rang moet geen enkele andere optie hebben naast de sleutels te hebben van het huis. Dus geen toegang tot de opslag, geen toegang tot de garage, geen optie om objecten op te slaan en geen optie om wapens op te slaan oid. Uiteraard ook geen objecten pakken, geen wapens pakken, geen wapeninkoop en geen wapen mods kopen.

**Comment by niekschoemaker** [comment]
Ik snap niet precies hoe je dit nu geformat hebt, want de dingen die daar op een rijtje staan is exact wat die rangen hebben?
Wat wil je exact aangepast hebben?

**Comment by Enrico14k** [comment]
> Ik snap niet precies hoe je dit nu geformat hebt, want de dingen die daar op een rijtje staan is exact wat die rangen hebben? Wat wil je exact aangepast hebben?

Nee er zijn dingen aangepast, 14k Triade - 选米机 kan nu namelijk ook objecten pakken en wapens pakken wat niet hoort, en 14k Triade - 非會員 kan nu ook objecten opslaan wapens opslaan en in de item winkel, terwijl die alleen sleutels horen te hebben.

**Comment by niekschoemaker** [comment]
> > Ik snap niet precies hoe je dit nu geformat hebt, want de dingen die daar op een rijtje staan is exact wat die rangen hebben? Wat wil je exact aangepast hebben?
> 
> Nee er zijn dingen aangepast, 14k Triade - 选米机 kan nu namelijk ook objecten pakken en wapens pakken wat niet hoort, en 14k Triade - 非會員 kan nu ook objecten opslaan, wapens opslaan, in de item winkel en in de garage, terwijl die alleen sleutels horen te hebben.

Waarom maakt het uit dat iemand wapens kan opslaan? Want ze kunnen deze er toch niet uithalen.

**Comment by Enrico14k** [comment]
> > > Ik snap niet precies hoe je dit nu geformat hebt, want de dingen die daar op een rijtje staan is exact wat die rangen hebben? Wat wil je exact aangepast hebben?
> > 
> > 
> > Nee er zijn dingen aangepast, 14k Triade - 选米机 kan nu namelijk ook objecten pakken en wapens pakken wat niet hoort, en 14k Triade - 非會員 kan nu ook objecten opslaan, wapens opslaan, in de item winkel en in de garage, terwijl die alleen sleutels horen te hebben.
> 
> Waarom maakt het uit dat iemand wapens kan opslaan? Want ze kunnen deze er toch niet uithalen.

Nouja, het maakt inderdaad niet veel uit, alleen had 14k Triade - 选米机 altijd al geen mogelijkheid om objecten/wapens te pakken. Dus dat zou mooi zijn als dat terug aangepast kan worden naar hoe het was. Verder maakt het voor 14k Triade - 非會員 inderdaad niet echt uit, daarvoor is het meer voor het oog.

**Comment by Willem-Dekker** [comment]
- [ ] Toevoegen permissie voor the toevoegen van items in de gang opslag
