### ISSUE TITLE
[FEATURE]: Kans op motorstoring luchtvaart

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1310]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Om het vliegen wat realistischer te maken, een kleine kans toevoegen op errors tijdens het vliegen. Denk hieraan bij een zeer laag percentage voor een motorstoring, of dat je een fuel-leak hebt. 

Bij het krijgen van een storing moet je uiteraard wel de kans krijgen om te kunnen landen, wellicht zorgen dat je nog voor zo'n 30 seconden goed kan blijven vliegen en dat daarna de motor uitvalt.

### Wat lost deze feature op?

Momenteel is de luchtvaart redelijk eentonig. Deze feature brengt wat spice in the kitchen! En voegt natuurlijk realisme toe.

**Comment by CalRayy** [comment]
Persoonlijk lijkt me dit niet handig, want je gaat al crashen bij een gele lamp bij je helikopter en door dit soort dingen zal dit niet leuk zijn voor heel veel spelers. Tevens had je suggestie ook op discord veel minnetjes, denk dat dit niet tof is voor de stad.

**Comment by CoffeeSipper** [comment]
> e

Mensen denken niet aan de RP. Dit is een leuke toevoeging die ook nog een realisme biedt voor de server.
Suggestie omtrent meer gebruik van brandstof had ook veel downvotes, is er ook ingekomen.

 Overigens meldt ik ook dat je niet instant moet crashen, maar zo'n 30 seconden de tijd hebt om nog te landen.

**Comment by CalRayy** [comment]
Ik begrijp je wel, alleen dit vraagt veel development werk waarschijnlijk. Terwijl er eigenlijk belangrijkere dingen op de planning staan.

**Comment by CoffeeSipper** [comment]
> 

Lage prioriteit tag...?

**Comment by Tijz** [comment]
Leuk als je net boven de zee vliegt en 30 seconde hebt om te landen, dan moet je daarna eerst nog 20 minuten terug zwemmen naar het strand.

**Comment by CoffeeSipper** [comment]
> Leuk als je net boven de zee vliegt en 30 seconde hebt om te landen, dan moet je daarna eerst nog 20 minuten terug zwemmen naar het strand.

30 seconden is meer dan genoeg. Probeer maar eens in de testserver.

**Comment by Tijz** [comment]
Net getest maar met 30 seconde ga je alsnog met een rotgang naar beneden.

**Comment by CoffeeSipper** [comment]
> 

Wat bedoel je met '' met 30 seconde ga je alsnog naar beneden''? Ik heb het erover dat je nog 30 seconden kan doorvliegen. Lukt mij wel gewoon...

**Comment by CoffeeSipper** [comment]
> 

Volg je de luchtvaart of niet? Kleine vliegtuigjes hebben dit regelmatig ;). Komt allemaal niet in het nieuws. Eerst onderzoeken of iets klopt wat je zegt.

**Comment by niekschoemaker** [comment]
Deze wordt gezien de prioriteiten niet opgenomen.
