### ISSUE TITLE
[FEATURE]: Extra dj paneel

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1311]
### Contact Details

iHax0r#3736

### Beschrijf zo duidelijk mogelijk de feature

Wij hebben een zeer mooi nieuw huis kregen (met veel dank aan Kobe 💯 ), hierbij hebben we ook een dj tafel staan bij het zwembad. Daarbij mijn vraag of het mogelijk is om de dj tafel (xDiskJockey) werkend te maken zoals bij postcode 7062.

### Wat lost deze feature op?

Aangezien wij de DJ tafel zeer veel gebruiken op postcode 7062, nu hebben we zelf een hele mooie afgesloten locatie waar dit mogelijk is.

**Comment by Chang-nl** [comment]
Het is gefixt!

**Comment by iHax0rMC** [comment]
> 

Hey Chang,

Waar kan ik deze terugvinden of duurt het even totdat hij in de server zit?

**Comment by Chang-nl** [comment]
Ooh wacht ik ben echt een gigantische idioot, ik heb je bericht volledig verkeerd gelezen haha🥴, ik dacht dat je een dj tafel bij postcode 7062 wilde. Maar nee dan zit dit er nog niet in nee🤭

**Comment by Chang-nl** [comment]
Waar moet hij precies komen? Heb je een postcode of coördinaten voor mij?

**Comment by iHax0rMC** [comment]
> Ooh wacht ik ben echt een gigantische idioot, ik heb je bericht volledig verkeerd gelezen haha🥴, ik dacht dat je een dj tafel bij postcode 7062 wilde. Maar nee dan zit dit er nog niet in nee🤭

Hahaha, kan gebeuren heb je een DM gestuurd, zal hierin de coords neerzetten :)
