### ISSUE TITLE
[FEATURE]: Vergroten van de kleding cirkel

### ISSUE THREAD

**Issue by Joost010** [Tedeapolis/development#1315]
### Contact Details

Joost#8797

### Beschrijf zo duidelijk mogelijk de feature

Momenteel is de kleding cirkel heel klein en passen er maar een paar personen in daarom zou het wenselijk zijn als deze cirkel wat groter gemaakt kan worden.

Hieronder een foto van de kleding cirkel, je merkt dat je er niet met heel veel mensen in zoon kleding cirkel kunnen staan. 
https://cdn.discordapp.com/attachments/608089499049787412/973245276112433152/unknown.png

### Wat lost deze feature op?

Het elkaar niet uit de cirkel drukken en makkelijker met meerdere mensen kleding kunnen aanpassen

**Comment by Chang-nl** [comment]
Na volgende restart gefixed!
