### ISSUE TITLE
Defecte Eiland voertuigen worden gemaakt na plaatsen in garage.

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1316]
### Contact Details

Lionskull#3747

### Wat gebeurde er?

Ik heb zelf 2 testen gedaan, en ik rijd me auto kapot en zet hem in de garage. Haal hem er weer uit, en vervolgens is die gemaakt.

### Wat hoorde er te gebeuren?

Dat het gemaakt wordt ;) 

### Wat veroorzaakt de bug?

Ik zou het niet weten.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Kan zijn dat dit nu gefixed is, weet het niet zeker, zou je even moeten checken

**Comment by Willem-Dekker** [comment]
is gefixed door @Chang-nl na restart
