### ISSUE TITLE
[FEATURE]: Eten/drinken kopen optie toevoegen aan opslagcirkel op -1 in HB 

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1317]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij bij de opslagcirkel op verdieping -1 (zie foto) een optie toegevoegd willen zien waar je eten/drinken kan halen voor de arrestanten.
![image](https://user-images.githubusercontent.com/93579695/167489958-7c944489-8e25-4e43-b5cf-32b03d2c2bae.png)

### Wat lost deze feature op?

QOL update zodat je makkelijker de arrestanten kan voorzien van eten/drinken.

**Comment by Chang-nl** [comment]
Hiervoor kun je eten en drinken halen bij de winkel en dat in de opslag doen!
