### ISSUE TITLE
[FEATURE]: ''Stunt'' op je ingame vliegbrevet kunnen geven

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1318]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

' /giveflylicense stunt ' kunnen doen. Mogelijk dat misschien de stuntvliegtuigen alleen door mensen met dit brevet gekocht kunnen worden. 

Kosten moeten 0 bedragen, zoals het ''beroeps'' brevet. 

### Wat lost deze feature op?

Voorkomt dat mensen als een gekkie gaan vliegen zonder stuntbrevet opleiding. Overigens is dit gewoon een brevet zoals prop en jet, maar kan je deze niet op je brevet ingame krijgen.

**Comment by Willem-Dekker** [comment]
welke vliegtuigen heb je het over die dan niet kunnen?

**Comment by CoffeeSipper** [comment]
![image](https://user-images.githubusercontent.com/96985840/168852348-e2873e67-8a11-4f95-9cfc-82381de858c1.png)
Is het mogelijk dat je flystunt hiertussen kan zetten? Als het niet te veel moeite is

**Comment by Willem-Dekker** [comment]
zit er in na restart
