### ISSUE TITLE
[FEATURE]: Gang heli narcos

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1319]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

Wij als Narcos zouden graag de hoogste 4 rangen en dat zijn:
Jefe
Capitan
Empresario
Consejero
zouden wij graag dat die rangen toegang krijgen tot het pakken van de gang heli.

### Wat lost deze feature op?

Dat meerdere rangen van Narcos een heli kunnen pakken. Op het moment kan alleen Jefe hem eruit halen.

**Comment by niekschoemaker** [comment]
De heli staat expres alleen op de hoogste rang, puur omdat het een best duur iets is wat een gang gratis krijgt, dus hierom staat hij alleen op de hoogste rang.

**Comment by EpicTomm** [comment]
Had gezien dat Les Revoltes ook een github had aangemaakt met precies dezelfde vraag en willem heeft het wel geaccepteerd!
