### ISSUE TITLE
[Bug]: Ticket Transcriptie

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1320]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je de ticket transcriptie bekijkt zie je geen enkele screenshots die je erin hebt geplaats ( bijvoorbeeld deze ticket werden er enkele screenshots erin geplaatst, alleen zag je die niet https://tickets.tedeapolis.nl/458649642259709973/973665462607036426)

### Wat hoorde er te gebeuren?

Je hoort de screenshot te kunnen zien. 

### Wat veroorzaakt de bug?

Geen flauw idee.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Was een issue aan Discord zijn kant
