### ISSUE TITLE
[FEATURE]: Updates aan Drugsdelivery

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#1321]
### Contact Details

Willemde20#0001

### Beschrijf zo duidelijk mogelijk de feature

Aanpassingen

- [ ] Roterende startpunten toevoegen
- [x] Animatie toevoegen bij afleveren
- [x] Meldingen Toevoegen bij afleveren slechte drugs voor deepweb

### Wat lost deze feature op?

Problemen die er nu zijn

**Comment by Chang-nl** [comment]
Hey @Willem-Dekker, hoe staat het met het laatste puntje in deze issue?

**Comment by Nander0320** [comment]
@Willem-Dekker

**Comment by Chang-nl** [comment]
Hey @Nander0320,

Aangezien Willem niet meer bereikbaar is zal ik deze issue oppakken mocht het nog iets zijn wat we willen hebben.

Zoals aangegeven moeten alleen de roterende startpunten nog. Moet dit nog toegevoegd worden?

**Comment by Chang-nl** [comment]
Er zit al een functie in dat je bij andere legale banen kan beginnen met witwassen!
