### ISSUE TITLE
[FEATURE]: Vergroten van trailer opslag 

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#1322]
### Contact Details

AntonMoskvin#3144

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag willen dat de trailer opslag van de trailers die je kan kopen naar meer kilo,s word gezet. Waarom dit ? Omdat je nu met een super  grote trailer net zoveel als 1 kleine bakwagen kan transporteren terwijl deze de dubbele grote heeft van een bakwagen (Mule).

### Wat lost deze feature op?

Dat je niet een onrealistische kilo aantal in die vrachtwagen hebt zitten en dat deze ook meer worden gebruikt i.p.v alleen maar die mules

![image](https://user-images.githubusercontent.com/84158163/167810052-d964a052-8360-445f-9c33-eafcc7092e51.png)

**Comment by Chang-nl** [comment]
na de restart gefixed!
