### ISSUE TITLE
[FEATURE]: Gang leden stats in csv

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1323]
### Contact Details

Dekk#3971

### Beschrijf zo duidelijk mogelijk de feature

Deze github feature op aanvraag van Willem zodat hij het niet vergeet;

- [x] Een extra kanaal in de categorieeen van gangs waarin de stats van de leden in een csv gepost worden.

### Wat lost deze feature op?

Op deze manier krijgt de gang meer inzicht over hun leden net zoals overheidsjobs hebben. 25 man is nog een aardig aantal om overzicht over te houden.

**Comment by Willem-Dekker** [comment]
zit er in en elke maandag wordt deze gevuld met data
