### ISSUE TITLE
[FEATURE]: Togglehud 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1324]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Ik had laatst een github gemaakt voor togglehud off dat je alles weg gaat op beeld, dit was opgelost. Alleen wat ik merk is dat je wel het safezone schild ziet tijdens togglehud off ( zie screenshot) 
![image](https://user-images.githubusercontent.com/101106299/167925008-22238be1-f04a-49ac-a0d8-17376ced5b78.png)
 is het mogelijk om dit ook weg te halen bij togglehud off?

### Wat lost deze feature op?

Betere camerabeelden voor journaals bij de nieuws / mooie foto's

**Comment by Chang-nl** [comment]
na restart opgelost!
