### ISSUE TITLE
[FEATURE]: reports

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1325]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Een commando waar je de reports uitschakeld, dit is super handig als je in roleplay bent wat je aan het opnemen bent. Als je /togglehud off doet komt de reports toch nog er doorheen. Mij leek het tof om een commando te maken om de reports uit te schakelen.

### Wat lost deze feature op?

Voor veel staff leden is dit super handig en is leuker voor de TDA nieuws etc.

**Comment by niekschoemaker** [comment]
/reports_settings

Hierbij krijg je een lijst om report settings aan te passen, command welke je zoekt is dus: `/report_settings toggle`
Zit er al in dus.

**Comment by ARJ3N** [comment]
> /reports_settings
> 
> Hierbij krijg je een lijst om report settings aan te passen, command welke je zoekt is dus: `/report_settings toggle` Zit er al in dus.

Wanneer ik de command gebruik komt dit er elke keer te staan:
![image](https://user-images.githubusercontent.com/92899337/168295066-bec4fac6-eb77-4df1-8e20-5f7798521849.png)
Verder komen de reports gewoon nog binnen zoals normaal. Ik krijg dit dus niet werkend.
