### ISSUE TITLE
[Bug]: Verkeerde politie rang onder docu ondertekening op boss job

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1326]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Wanneer je een document ondertekend terwijl je op Eerste Hoofdcommissaris job staat komt de verkeerde rang er te staan. Dit kan wel vervelend zijn als je documenten uitschrijft die enkel Korpsleiding mag uitschrijven en er vervolgens Hoofdagent bij staat. Zie foto:
![image](https://user-images.githubusercontent.com/93579695/167927580-af6fe93c-ccea-4b45-9468-d11b7ac7cc7a.png)

### Wat hoorde er te gebeuren?

Er hoort de juiste rang te staan.

### Wat veroorzaakt de bug?

Schrijf een document uit op Eerste Hoofdcommissaris rang en onderteken het document.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
Na herstart opgelost!

**Comment by Willem-Dekker** [comment]
> Na herstart opgelost!

dit zit er in op aanvraag van DSI btw

**Comment by PolitieTDA** [comment]
> Na herstart opgelost!

Net even getest maar zie nog Hoofdagent staan na het ondertekenen.

**Comment by Chang-nl** [comment]
Ja klopt, pr was nog niet gemerged zodra het dus daadwerkelijk in de server zit zie je dit in het github commits kanaal in discord
