### ISSUE TITLE
Bug omtrent schietmeldingen

### ISSUE THREAD

**Issue by TDAMitchell** [Tedeapolis/development#1328]
### Contact Details

Mitchelll#1258

### Wat gebeurde er?

Moment dat je de stad in komt, in dienst. Ontvang jij geen schietmeldingen. Dit betekend dus dat je elke keer naar hb moet om uit dienst en in dienst te klokken. Ook tijdens server restart en tijdens server crashes.

### Wat hoorde er te gebeuren?

Je hoort gewoon altijd te schietmeldingen te ontvangen, ook als je in dienst de stad in komt

### Wat veroorzaakt de bug?

Onbekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by AdventurePandah** [comment]
Is inderdaad een issue waar KMAR en Politie last van heeft. Ik krijg te horen dat het om elke melding gaat inclusief de bank/winkel/drugs meldingen.

**Comment by niekschoemaker** [comment]
> 

Zou je me even een keer kunnen aanspreken wanneer je last hebt van deze bug en dan even de issue negeren tot ik reageer, dan kan ik even wat data uit de plugin zelf halen om te kijken in welke van de 2 componenten het probleem ligt

**Comment by CoffeeSipper** [comment]
Overigens geef je zelf ook schietmeldingen als deze bug actief is. Stel je schiet in dienst met jouw dienstwapen, geef je zelf een vuurwapen melding.

**Comment by niekschoemaker** [comment]
> Overigens geef je zelf ook schietmeldingen als deze bug actief is. Stel je schiet in dienst met jouw dienstwapen, geef je zelf een vuurwapen melding.

Ah kijk dit is nuttige info want dan weet ik waarschijnlijk exact waar het probleem ligt

**Comment by niekschoemaker** [comment]
Zou na volgende herstart gefixed moeten zijn.
Als iemand dit even kan controleren en dit dan kan laten weten, dan kan ik dan de issue sluiten.

**Comment by TDAMitchell** [comment]
> Zou na volgende herstart gefixed moeten zijn. Als iemand dit even kan controleren en dit dan kan laten weten, dan kan ik dan de issue sluiten.

Ik zal het vanavond testen!

**Comment by TDAMitchell** [comment]
Het is opgelost. Dankjewel!
