### ISSUE TITLE
[FEATURE]: Opslag kilo,s gelijk trekken van vrachtwagens

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#1329]
### Contact Details

AntonMoskvin#3144

### Beschrijf zo duidelijk mogelijk de feature

Beste Developers,

Sinds een paar maanden is er nu een vrachtwagen winkel in het noorden waar je verschillende vrachtwagens kan kopen.
Echter is de ene vrachtwagen best duur **500K** en de andere wat goedkopere (Bakwagen) **300K**. Als je nou een normale vrachtwagen koopt zonder enige trailer kan je _50 kilo_  kwijt, helemaal prima want in zo een vrachtwagen zit niet veel ruimte. Maar nu kan je ook een trailer er bij kopen en een dichte trailer voor **100K** en kan maar 350 kilo in, terwijl als je een mule koopt voor maar **300K** hoef je geen moeite te doen om een trailer op te halen en/of er extra bij te kopen en je kan direct er _250 kilo_ in gooien. Dus kort gezegd een vrachtwagen+trailer= _350 kilo_ en een mule= _250 kilo_. Mij lijkt het wel eerlijk als een vrachtwagen meer kan dragen gezien deze 2x zo groot is als een mule en veel meer trekkracht heeft.

### Wat lost deze feature op?

Deze feature lost op dat er meer in een vrachtwagen kan en dat die ook echt gebruikt kan worden waar voor die bedoeld is.
Een vrachtwagen is voor groot zwaar transport en niet voor maar _350kilo_ 
Daarnaast krijg je dan meer waarde voor je geld want nu kan je net zo goed 2 mules halen en dan heb je nog meer ruimte dan alleen vrachtwagen met trailer 

Hier de fotos van een Vrachtwagen+Trailer en een Mule

![image](https://user-images.githubusercontent.com/84158163/168080340-d548e903-262d-4430-afed-d1beae73dea4.png)
![image](https://user-images.githubusercontent.com/84158163/168080396-c10a4095-7f5d-4bda-b6c3-9074d309120f.png)

**Comment by AnatolyMoskvin** [comment]
Inderdaad meestal zijn die jobs niet veel verdienende van wat ik weet 
En anders eventueel daar een andere trailer aan koppelen die niet word verkocht ? Of die trailer dan juist uit de shop halen

**Comment by Chang-nl** [comment]
heb het zojuist even Aangepast, in principe zijn de trailers nu 450 kg each en dus met een truck ervoor 500 kg, oftewel het dubbele van de mule
