### ISSUE TITLE
[FEATURE]: Justitie aanpassingen

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1330]
### Contact Details

Hellfire

### Beschrijf zo duidelijk mogelijk de feature

- [ ] Bevoegdheid/ optie tot het ten alle tijde boetes kunnen uitschrijven ten behoeve van het leningensysteem. 

_Wellicht dat dit het makkelijkste via meos een optie is net zoals vroeger? Graag zouden Sjenkie en ik hierover kunnen beschikken zodat het hele systeem betreft leningen rond is_

- [x] Salarissen aanpassen van bepaalde functies

-Graag zouden wij de salarissen aanpassen zodat dit meer gelijk getrokken wordt met de andere overheidsdiensten. Daarnaast zouden wij ook voor bepaalde functies zien dat de salarissen zowel in- als uitdienst hetzelfde worden. Nu gebeurt het nogal eens dat elke justitie medewerker in F10 aangezien wordt als een advocaat die een zaak kan lopen. Echter is dit niet altijd het geval en zouden we dus hierin wat aanpassingen willen maken, om meer duidelijkheid daarin te kunnen scheppen_

|Aangepast|naam|salaris in & uitdienst|
|---|---|---|
| **JA**  |Minister|1750|
| **JA** |Staatssecretaris|1500| > De offjob staat nog verkeerd en moet ook veranderd worden naar Staatssecretaris
| **JA** |Deken van de orde|1250|
| **JA** |KVK Beheer|1000|

|Aangepast|naam|Salaris indienst| Salaris uitdienst|
|---|----|---|---|
|  |Juridisch medewerker|1000| 500|
|  |Afgevaardigde|1000|500|

- [x] Extra rang toevoegen ingame:
    - [x] KVK medewerker Salaris in & uitdienst dienst 600_

- [x] Bevoegdheden ingame van de Staatssecretaris hetzelfde maken als die van de boss functie

_Zodoende kan degene met deze functie ook wat taken wegnemen en de kluis in etc. in het geval dat wij niet aanwezig zijn_

### Wat lost deze feature op?

-

**Comment by Willem-Dekker** [comment]
Boetes moet nog geïmplementeerd worden rest van de aanpassingen zitten er in na server restard

**Comment by Hellie94** [comment]
Boetes: Minister, Staatssecretaris

**Comment by brothasx** [comment]
Deze kan gesloten worden lijkt wegens leningen stop gezet word.
