### ISSUE TITLE
[FEATURE]: Dirtbike Model verkleinen

### ISSUE THREAD

**Issue by Dark5000** [Tedeapolis/development#1331]
### Contact Details

Dark#5000

### Voertuig model

bf400 | Dirtbike van de politie

### Omschrijf de bug

Het Model van de dirtbike, van de politie (en Kmar) zijn wat breeder dan die van de sanchez en africat. Nu misbruiken criminelen dit heel erg om plekjes en kiertjes te zoeken waar een sanchez wel door heen kan en een dirtbike niet. Al zet je beide voertuig naast elkaar neer is het breedte verschil (realistisch gezien) minimaal, de africat is nog zelfs breeder. Nou kan je zeggen dat de politie zelf slimmer moet nadenken en dat kon ook eerst maar de criminelen komen elke dag met een nieuw plekje waardoor het niet meer leuk wordt om offroad motoren te achtervolgen.

### Repro

Een voorbeeld van zo'n plek is deze in Mirrorpark in de volgende video te zien. Ook een Africat kan door deze steeg heen.
https://www.youtube.com/watch?v=uGVTDMJHszY

### Normaal gedrag

Dat de Dirtbike, Africat en Sanchez (realistisch gezien) even breedt zijn en dus ook overal op dezelfde plek tussen kan rijden.

**Comment by Lorenzo3001** [comment]
Sanchez en Manchez zijn al breder gemaakt zodat deze daar niet in passen, africat heb ik nu ook aangepast.
