### ISSUE TITLE
[Bug]: locaties drugs

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1333]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je kan bij bepaalde locaties niet leveren, zie hieronder de coords.
- X: 1930.04 Y:4634.95 Z: 40.47
- X: -565.19 Y: 684.10 Z: 146.41
-  X: 5.75 Y: 109.69 Z: 79.02
- X: -579.51 Y: 732.96 Z: 184.21
-  X: -753.56 Y: -1512.54 Z: 5.02
- X: 1291.64 Y: 4367.14 Z: 41.35
- X: -477.29 Y: 297.91 Z: 83.79
- X: 1099.73 Y: -2255.48 Z: 34.79
- X: -1974.57 Y: 198.91 Z: 86.60
- X: 1737.63 Y: -1474.62 Z: 113.94
- X: 1941.95 Y: 3845.11 Z: 35.39
-  X: 1108.65 Y: -2257.00 Z: 30.94 
- X: -586.66 Y: 36.97 Z: 43.61
- X: -567.69 Y: 5253.19 Z: 70.49
- X: 3310.72 Y: 5176.23 Z: 19.61

### Wat hoorde er te gebeuren?

je hoort hier op deze locaties te leveren

### Wat veroorzaakt de bug?

hij zit in de grond volgens mij (de aflever cirkels)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Willem-Dekker** [comment]
ga vandaag alle locaties in systeem na lopen en checken welke er wel en niet goed zijn

**Comment by Willem-Dekker** [comment]
zouden morgen gefixed moeten zijn
