### ISSUE TITLE
[Bug]: /rs

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1334]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je ziet de melding van druk op y op de fouillering te accepteren of niet, alleen kan je dit soms niet accepteren en moet je reloggen of je keybinds accepteren. Vaak komen hier tickets over en dan is het lastig als hij de waarheid zegt of niet, kan hier naar gekeken worden?

### Wat hoorde er te gebeuren?

Je hoort het te kunnen accepteren, maar dat gaat niet volgens veel spelers af en toe.

### Wat veroorzaakt de bug?

Geen flauw idee, eerlijk gezegd.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Oh wauw, dacht dat dit een complexe issue zou zijn, maar nvm, zou gefixed moeten zijn.

Blijkbaar nadat je de eerste keer fouilleren hebt afgewezen werkt de keer daarna niet, dat veroorzaakte deze issue waarschijnlijk.
