### ISSUE TITLE
[FEATURE]: Aanpassingen AK-12 ( Burgerraad )

### ISSUE THREAD

**Issue by Daxn872** [Tedeapolis/development#1335]
### Contact Details

Daan#6435

### Beschrijf zo duidelijk mogelijk de feature

Tijdens burgerraad is eruit gekomen dat de AK-12 momenteel haast niet gebruikt wordt, dit komt doordat het wapen van zichzelf stock niet te gebruiken is. ( Feedback official gangs ) er moeten dus automatisch al tunes op het wapen om hem te gebruiken. Hiervoor is tijdens burgerraad besproken dat de tune prijzen gelijk worden getrokken met de AK-74, daarnaast is het een MK2 wapen en zou daarbij het wapen ook beter moeten zijn gezien de inkoop prijs. Momenteel is de recoil erg stuiterend en is een normale AK-74 nogsteeds beter.

- [ ] Tune prijzen van de AK-12 gelijk trekken met de tune prijzen van AK-74
- [ ] Recoil verminderen van de AK-12.

### Wat lost deze feature op?

Dat de AK-12 gebruikt kan worden.

**Comment by niekschoemaker** [comment]
Beschrijf "Niet te gebruiken is" want de stats staan identitiek (zelfs beter) dan die van de AK, dus wat veroorzaakt exact dat hij niet te gebruiken is?

**Comment by Tijz** [comment]
> Beschrijf "Niet te gebruiken is" want de stats staan identitiek (zelfs beter) dan die van de AK, dus wat veroorzaakt exact dat hij niet te gebruiken is?

De standaard scope + recoil zorgt ervoor dat het wapen stock niet te gebruiken is, je ziet helemaal niks door de scope en dat in combinatie met de enorme recoil (veel meer dan AK-74) is het wapen niet te gebruiken.

**Comment by niekschoemaker** [comment]
> > Beschrijf "Niet te gebruiken is" want de stats staan identitiek (zelfs beter) dan die van de AK, dus wat veroorzaakt exact dat hij niet te gebruiken is?
> 
> De standaard scope + recoil zorgt ervoor dat het wapen stock niet te gebruiken is, je ziet helemaal niks door de scope en dat in combinatie met de enorme recoil (veel meer dan AK-74) is het wapen niet te gebruiken.

Ja oké, maar in welke manier is de recoil dan erger want de recoil staat identiek aan de AK-74 🤔 volgens mij zelfs iets lager

**Comment by Tijz** [comment]
> > > Beschrijf "Niet te gebruiken is" want de stats staan identitiek (zelfs beter) dan die van de AK, dus wat veroorzaakt exact dat hij niet te gebruiken is?
> > 
> > 
> > De standaard scope + recoil zorgt ervoor dat het wapen stock niet te gebruiken is, je ziet helemaal niks door de scope en dat in combinatie met de enorme recoil (veel meer dan AK-74) is het wapen niet te gebruiken.
> 
> Ja oké, maar in welke manier is de recoil dan erger want de recoil staat identiek aan de AK-74 🤔 volgens mij zelfs iets lager

Het is niet te gebruiken omdat de scope de hele tijd in de weg zit als je schiet met die recoil. De recoil kan misschien wel mee vallen, alleen de scope zit in de weg als je schiet met die scope. Dus de normale scope (ironsight) die er stock op zit zit in de weg als je schiet, probeer dit maar uit op de test server.

**Comment by niekschoemaker** [comment]
Ik heb de holo sight van de AK-12 nu gratis gemaakt, denk dat dat de beste fix is.

Heb een hele poos lopen klooien met scope offsets, maar die iron sight kan ik niet echt fatsoenlijk krijgen.

**Comment by Willem-Dekker** [comment]
#1154 <- Ter info

**Comment by Daxn872** [comment]
> Ik heb de holo sight van de AK-12 nu gratis gemaakt, denk dat dat de beste fix is.
> 
> 
> 
> Heb een hele poos lopen klooien met scope offsets, maar die iron sight kan ik niet echt fatsoenlijk krijgen.

Thanks voor de oplossing :)

**Comment by niekschoemaker** [comment]
> > Ik heb de holo sight van de AK-12 nu gratis gemaakt, denk dat dat de beste fix is.
> > Heb een hele poos lopen klooien met scope offsets, maar die iron sight kan ik niet echt fatsoenlijk krijgen.
> 
> Thanks voor de oplossing :)

Ik heb ook een preview toegevoegd aan het modden en zal de changes zo even doorzetten naar test server.

Check even of zo alles klopt, want nu zouden alle mods ook moeten werken, muzzle brakes verlagen recoil met 20%, een suppressor met 10% en een grip met 10%.

**Comment by niekschoemaker** [comment]
Oh zie nu ook dat de shaking modifier nog geen attachement waardes mee neemt, dus alleen de omhoog en links/rechts recoil wordt geimpact door de attachements, zal ik even snel fixen.

**Comment by Daxn872** [comment]
> > > Ik heb de holo sight van de AK-12 nu gratis gemaakt, denk dat dat de beste fix is.
> 
> > > Heb een hele poos lopen klooien met scope offsets, maar die iron sight kan ik niet echt fatsoenlijk krijgen.
> 
> > 
> 
> > Thanks voor de oplossing :)
> 
> 
> 
> Ik heb ook een preview toegevoegd aan het modden en zal de changes zo even doorzetten naar test server.
> 
> 
> 
> Check even of zo alles klopt, want nu zouden alle mods ook moeten werken, muzzle brakes verlagen recoil met 20%, een suppressor met 10% en een grip met 10%.

Zover getest werkt alles voor nu naar behoren. Thanks :)
