### ISSUE TITLE
[Bug]: Drugs cirkels 2.0

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1336]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je kan bij bepaalde locaties niet leveren, zie hieronder de coords.
- X: 2677.12 Y: 3517.96 Z: 51.98
- X: -1090.89 Y: -925.74 Z: 3.15
- X: 1734.35 Y: 3898.03 Z: 35.56
- X: 2529.91 Y: 2586.98 Z:" 37.34

### Wat hoorde er te gebeuren?

je hoort hier op deze locaties te leveren

### Wat veroorzaakt de bug?

hij zit in de grond volgens mij (de aflever cirkels)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Willem-Dekker** [comment]
graag log bestanden ik heb alle locaties gecheckt en ze zijn allemaal toegankelijk

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/168428111-0c1b7139-554c-46f3-b780-d26cd7c01b7d.png)
X: -1182.22 Y: -1773.68 Z: 3.91
De F8 staat hierboven, ik hoop dat u dit bedoeld met de log bestanden.

**Comment by Willem-Dekker** [comment]
zou nu gewoon moeten werken
