### ISSUE TITLE
[FEATURE]: Vaarbewijs 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1337]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Je kan momenteel bij het gemeentehuis een vaarbewijs halen, alleen zie je deze niet in je portemonnee. De enige manier hoe je weet dat je er eentje hebt is via Meos. Is het mogelijk om dit ook in je portemonnee te hebben, zodat mensen zonder Meos dit ook kunnen weten of eventueel zelf halen?

### Wat lost deze feature op?

Minder werk voor burgers en Politie eigenlijk en het is leuk om nog een pas te hebben.

**Comment by brothasx** [comment]
@Chang-nl  Deze pas is toegevoegd aan de images met naam "vaarbewijs" , deze kan dan gebruikt worden eventueel voor de pas.

**Comment by Willem-Dekker** [comment]
fixed
