### ISSUE TITLE
[FEATURE]: Porto als je op 'Whisper' staat hetzelfde laten klinken als Normal.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1338]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

Als je op Whisper staat, gaat je volume als je praat via je porto zo aanzienlijk omlaag, dat je iemand bijna niet hoort.
Gelieve het geluid via de porto terwijl je op Whisper staat gewoon op normaal volume te zetten. Bij het praten in een porto, heb je de porto altijd dicht bij je mond namelijk.

### Wat lost deze feature op?

Het bijna niet kunnen horen van iemand op Whisper via je porto.

**Comment by Willem-Dekker** [comment]
Dat is letterlijk de bedoeling van deze feature. je praat zacht in de porto

**Comment by Attomn** [comment]
Ja blijkbaar vinden mensen dat vervelend omdat je zowat onverstaanbaar bent. Is het mogelijk om het volume iets harder te zetten?

**Comment by niekschoemaker** [comment]
> Ja blijkbaar vinden mensen dat vervelend omdat je zowat onverstaanbaar bent. Is het mogelijk om het volume iets harder te zetten?

Ja, niet fluisteren in je porto, dit is om te voorkomen dat mensen express op whisper gaan om te voorkomen dat mensen in directe omgeving je niet in de porto horen praten.

Mensen kunnen wel zelf hun porto volume (dus hoe zij anderen horen) omhoog zetten met `/setportovolume 2.0`
