### ISSUE TITLE
[FEATURE]: ID kaart

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1339]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Als de Politie je ID kaart bekijkt / afpakt om te kijken wie je bent via het F6 menu dat je een melding krijgt (net zoals de fouilleringen melding) en dat gaat als volgt: 

"1548 heeft jouw ID kaart gepakt"

### Wat lost deze feature op?

Om het abuse omtrent F6 te verminderen / minder tickets omtrent F6 abuse.

**Comment by CalRayy** [comment]
Ik zou toch de ID van degene willen zien wie het bekijkt omtrent tickets (om het makkelijker te maken voor staff leden)

**Comment by CoffeeSipper** [comment]
Ik bedoel alleen het stukje tekst, dus ''heeft jouw ID kaart gepakt" vervangen.

**Comment by Willem-Dekker** [comment]
@CalRayy overleg dit even in staffoverleg zondag

**Comment by CalRayy** [comment]
Criminelen met F6 menu de mogelijkheid geven om een ID kaart te pakken van mensen. Als ze dit gebruiken komt er uiteraard een bericht bij met "ID xxx heeft je IDKaart gepakt".

Daarnaast dit bericht ook toevoegen als politie of kmar je id kaart pakt.

Dit besproken in staff overleg, hier ging iedereen akkoord op.

**Comment by CalRayy** [comment]
@Willem-Dekker

**Comment by Attomn** [comment]
**EEN onderdeel dat hierbij hoort, maar vergeten is, is dat criminelen de functie om een ID kaart te pakken ook moeten krijgen in het F6 menu, uiteraard ook met die melding.**

**Comment by Chang-nl** [comment]
Na herstart zit het erin!
