### ISSUE TITLE
[FEATURE]: Aanpassingen Flightschool rangen / 2e job

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1341]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Momenteel hebben de Flightschool rangen geen enkele functie. Het is bijvoorbeeld niet zo dat als je een hogere rang haalt, je meer verdient of extra dingen kunt. Het is dus niet per se motiverend om extra hard je best te doen voor een promotie. Daarom had ik het volgende idee. 

Huidige tarieven: 
- 1e brevet: 150k
- 2e brevet: 75k
- Stunt: 25k

Gemiddelde tijden per les:
- Prop: 60 minuten
- Heli: 30 minuten
- Jet: 60 minuten
- Stunt: 30 minuten

Rangen:
**Vlieginstructeur in opleiding**
```
Omschrijving:
Welkom bij TDA Flightschool. Je hebt alle uitleg gekregen en bent daarom Vlieginstructeur in opleiding. Je bent bevoegd om de eerste lessen te geven voor Heli of Prop. Je hebt slechts 1 specialisatie en dat is Prop of Heli.

Je verdient per brevet het volgende:
- Prop: 10k 
- Heli: 5k

Rechten:
Je kunt enkel Prop of Heli brevetten uitschrijven.
```

**Junior vlieginstructeur**
```
Omschrijving:
Je bent goed bezig! Je zit inmiddels 2 weken bij de vliegschool en hebt al enkele lessen gegeven voor Prop of Heli. Omdat je inmiddels al enige ervaring hebt opgedaan krijg je de bevoegdheid om meerdere brevetten te geven. Zo krijg je de mogelijkheid om Heli en Prop te geven. Daarnaast heb je vanaf nu ook de bevoegdheid om strikes en brevet innames te geven.

Je verdient per brevet het volgende:
- Prop: 15k
- Heli: 10k

Rechten:
Je kunt enkel Prop of Heli brevetten uitschrijven.
```

**Vlieginstructeur**
```
Omschrijving:
Je bent inmiddels al 2 maanden actief voor de vliegschool! Daarnaast heb je ook al meer dan 25 lessen gegeven. Goed bezig! Je bent hard aan het doorgroeien. Je geeft daarnaast zowel Prop en Heli. Omdat je nu vlieginstructeur bent krijg je ook de bevoegdheid om Jet te geven.

Je verdient per brevet het volgende:
- Prop: 20k
- Heli: 15k
- Jet: 25k

Rechten:
Je kunt enkel Prop, Heli of Jet brevetten uitschrijven.
```

**Ervaren vlieginstructeur**
```
Omschrijving:
Je bent erg actief en mensen kijken naar je op. Je bent het eerste aanspreekpunt voor vragen en je hebt veel ervaring met vliegen. Je bent al 4 maanden actief voor de vliegschool. Daarnaast heb je ook al meer dan 50 lessen gegeven. Naast dat je Prop, Heli en Jet geeft, krijg je ook de mogelijkheid om Stuntaantekeningen te geven.

Je verdient per brevet het volgende:
- Prop: 25k
- Heli: 20k
- Jet: 30k
- Stunt: 20k

Je kunt alle brevetten uitschrijven (behalve voor jobs).
```

**Senior Vlieginstructeur**
```
Omschrijving:
Jij bent een van de meest ervaren piloten en instructeurs. Je bent enorm actief en kan mensen goede uitleg geven. Je bent de helpende hand voor de Leiding en geeft af en toe nieuwe instructeurs instructies voor brevetten.
Je hebt elk brevet onder de knie en geeft dus onder andere Prop, Heli, Jet en Stunt. Daarnaast ben je al 6 maanden in dienst bij de vliegschool en heb je minimaal 100 lessen gegeven.

Je verdient per brevet het volgende:
- Prop: 30k
- Heli: 25k
- Jet: 35k
- Stunt: 25k

Je kunt alle brevetten uitschrijven.
```

**Flightschool leiding**
```
Omschrijving:
Samen met de meest ervaren piloten en instructeurs vorm jij 1 team met 1 taak, de vliegschool draaiende houden. Jij bent samen met je team verantwoordelijk voor alles wat binnen de vliegschool gebeurd. Je denkt goed mee en kijkt naar nieuwe initiatieven om de vliegschool nog beter te maken.
Leiding kun je alleen worden door uitgekozen te worden.

Je verdient per brevet het volgende:
- Prop: 30k
- Heli: 25k
- Jet: 35k
- Stunt: 25k

Je kunt alle brevetten uitschrijven.
```

De tarieven blijven hetzelfde, enkel de verdiensten veranderen. 

**Eerste optie**
Om dit makkelijk te beheren worden er enkele commands toegevoegd aan de discord / aan de server.

**/getflightinstructors**
`Met deze command verkrijg je een lijst met huidige instructeurs met daarbij de rangen per instructeur.`

**/addflightinstructor (steamid) (rang 0/1/2/3/4/5)**
`Met deze command voeg je een nieuwe instructeur toe of pas je de rang van een instructeur aan. 0 is junior vlieginstructeur, 5 is vliegschool leiding. De rangen van de instructeurs is ook zichtbaar op het pasje.`

**/removeflightinstructor (steamid)**
`Met deze command haal je de permissies van een vlieginstructeur weg.`

De bovenstaande commands kunnen enkel door staffleden uitgevoerd worden.

**Tweede optie**
Ik begreep dat de Flightinstructors momenteel worden opgegeven via de server config. Mocht het voor jullie makkelijker zijn, is het ook mogelijk om van de Flightschool een tweede job te maken.

De job verdient zelf niets en kan enkel gegeven worden door staffleden via /setjob2. Je verdient als instructeur met het geven van lessen en brevetten. Zie bovenstaand de toelichting van de rangen met daarbij de verdiensten.

### Wat lost deze feature op?

Door een structuur te brengen in salarissen en rangen, motiveert het instructeurs om actiever te zijn binnen het geven van vlieglessen. Daarnaast hebben de huidige rangen geen enkele functie wat hiermee opgelost wordt.

**Comment by niekschoemaker** [comment]
Is het niet logischer om dit gewoon als een 2e job toe te voegen, of als primaire job zelfs?
Weet niet precies hoe druk vlieginstructeurs het atm hebben, maar misschien dat het uit kan om het als primaire job te doen?

**Comment by AdventurePandah** [comment]
Update, inmiddels zijn de rechten gefixt per discord rang. Alleen de incassos vanaf de rekening moeten nog aangepast worden.

**Comment by Chang-nl** [comment]
Yes ik heb de profits per rang nu toegevoegd en de permissies zitten er ook na de volgende herstart in!
