### ISSUE TITLE
[Bug]: Kleding kopen Masker

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1342]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

Als je een andere masker koopt dan die je hebt als je hem afzet en weer op zet heb je je oude masker dit hoort niet te gebeuren

### Wat hoorde er te gebeuren?

het masker wat je koop hoord correct te worden opgeslagen in de kleding winkel

### Wat veroorzaakt de bug?

kleding winkel kapot

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

kan niks zien in F8 menu hier over evt iemand anders die dit kan testen bij mij gebeurd het 100% van de tijd ook als ik alle kleding koop uit de winkel

**Comment by Chang-nl** [comment]
Is gefixt na de restartt!
