### ISSUE TITLE
[FEATURE]: Eiland Helipads

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1343]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijkheid om een garage cirkel te creëren voor Helikopter op de coords: 

X: 4894.13 Y: -5291.40 Z: 8.64

De cirkel waar je de helikopters weg kan doen op:

X: 4882.29 Y: -5283.73 Z: 8.44

### Wat lost deze feature op?

Onnodige helikopters die daar staan (te veel soms), bij elke helipads op eiland heeft het dus leek mij tof om hier ook te hebben.

**Comment by Willem-Dekker** [comment]
overleg het ff in staff overleg

**Comment by CalRayy** [comment]
Besproken in staff overleg, dit gaat niet door :)
