### ISSUE TITLE
[FEATURE]: In-game job niet kunnen zien in politie MEOS

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1344]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij willen zien dat de in-game politie jobs niet weergegeven worden in het MEOS systeem.

### Wat lost deze feature op?

Voorkomt dat DSI/recherche herkent worden wanneer je door het systeem gehaald worden en ze dan dus kunnen zien dat ze in dienst zijn met welke rang.

**Comment by niekschoemaker** [comment]
Is gefixed
