### ISSUE TITLE
[Bug]: benzine pomp 2.0

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1345]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De bug met de benzine pomp is helaas weer terug gekeerd, de issues die ik bedoelde met de benzine pomp is deze github : https://github.com/Tedeapolis/development/issues/1302

### Wat hoorde er te gebeuren?

je hoort de pomp te zien

### Wat veroorzaakt de bug?

als je van eiland naar land gaat.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Voor zover wij te horen gekregen hebben is dit gefixt. Calray gaf zelf al aan dat hij er geen last meer van heeft gehad!
