### ISSUE TITLE
[Bug]: linten

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1346]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je in spectate modus zit zie je geen linten, is het mogelijk om dat wel te zien?

### Wat hoorde er te gebeuren?

je hoort de linten te zien in spectate 

### Wat veroorzaakt de bug?

geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Is dit alleen met linten of ook met andere props?

**Comment by CalRayy** [comment]
Dit is met alle objecten, hoe dit eigenlijk onstaat is als jij zelf niet in het gebied zit waar de props staan dan zie je het niet. Als de prop in het gebied is waar jouw poppetje staat dan zie je het wel. Ik weet niet als dit fixable is ?

**Comment by Chang-nl** [comment]
Dank voor de concrete uitleg! Het is denk ik best op te lossen, maar volgens mij is het niet echt nodig om props te kunnen zien terwijl je in spectate zit, of mis ik nu iets?

**Comment by CalRayy** [comment]
Regelmatig krijgen we reports dat mensen door linten heen rijden, maar ik kan bijvoorbeeld niet no clippen omdat ik de recht daarvoor niet heb dus ik moet spectaten en dan zie ik de props niet. Terwijl die er staan en ik weet dan niet 100% wie ik moet warnen of niet omdat ik de linten niet zie (je mag niet door politie linten heen rijden is een warn waardig namelijk).
