### ISSUE TITLE
[EUP]: Taser holster voor alle KMAR rollen

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1347]
### Contact Details

MickeyMorris#7393

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag de taser holster toevoegen voor alle KMAR rollen, zodat deze via de EUP aangetrokken kan worden.

**Comment by Willem-Dekker** [comment]
welke hebben het nu?

**Comment by dilyano** [comment]
@Willem-Dekker de politie heeft deze gordel. Wij willen deze gordel graag ook voor de niet vuurwapen dragende mensen

**Comment by Willem-Dekker** [comment]
heb je naam van hoe deze heet binnen de politie?
