### ISSUE TITLE
[EUP]: Blauwe handschoenen KMAR

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1348]
### Contact Details

MickeyMorris#7393

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag zouden wij als kmar via de eup toegang willen hebben tot blauwe handschoenen, zodat wij onszelf in RP kunnen beschermen bij fouilleringen en drugs onderzoeken

**Comment by Willem-Dekker** [comment]
Zit er in na restart
