### ISSUE TITLE
[FEATURE]: Combatlog beschikbaar maken voor KMAR

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1349]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Wanneer er geen ambulance in dienst is, komen de ambu meldingen bij de Politie en Kmar terecht. Om hier de juiste roleplay aan te kunnen hangen, willen we graag toegang krijgen tot de combatlog functionaliteit ( is ook al afgestemd met Wilma van de Ambu) zodat er goed gezien kan worden wat er een persoon is overkomen

### Wat lost deze feature op?

De juiste rp aan een reanimatie RP

**Comment by Chang-nl** [comment]
Na herstart gefixed!
