### ISSUE TITLE
[Bug]: KMAR in dienst betaald tol

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1350]
### Contact Details

MickeyMorris#7393

### Wat gebeurde er?

Wanneer de KMAR door de post heen rijdt, betalen zij in dienst tol. Dit is niet de bedoeling aangezien zij werkzaam zijn aan de post en niet bij iedere passage geld hoeven te betalen. DIt zorgt ervoor dat de salarissen van de mensen aan de post aanzienlijk teruglopen omdat zij veel kwijt zijn aan tol.

### Wat hoorde er te gebeuren?

Dat een medewerker van de KMAR die in dienst is, geen tol hoeft te betalen

### Wat veroorzaakt de bug?

Een foutje in de tolport code ;)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Na herstart gefixed
