### ISSUE TITLE
[FEATURE]: KMAR/HRB gwagon

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1351]
### Contact Details

MickeyMorris#7393

### Kenteken van voertuig

nee allen

### Voertuig model

(staat niet in spawnlist)

### Omschrijf de bug

Momenteel ondervinden wij 2 aspecten welke de Gwagon niet relaistisch maken:
- Bij een slagboom bij de oostpost, legerbasis of iets anders heb je instant een geel of rood lampje (pantser werkt niet)
- De offroad snelheid van de gwagon is dramatisch. Deze heeft een hele tijd normaal gefunctioneerd maar offrad trekt deze auto heel langzzam op naar 100 km/h en komt hij hier niet voorbij terwijl andere gwagons bij je wegrijden.

### Repro

Pak een HRB gwagon en ga er mee rijden

### Normaal gedrag

Offraod hoort dit ding echt geod te functioneren en qua pantser hoort deze door een slagboom geen lampje te krijgen

**Comment by Tijz** [comment]
Volgens mij ondervinden alle g-wagons het off-road probleem en niet alleen de kmar g-wagon.

**Comment by Lorenzo3001** [comment]
Zowel pantser als offroad staat nu gelijk aan de normale G65
