### ISSUE TITLE
[FEATURE]: Hoogte Jet

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1352]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Graag zou de Flightschool de hoogte van de Jet aangepast zien worden van ''2100-2500 Feet'' naar ''2100-Infinite''. Er zit niet een echt limiet aan hoe hoog hij mag. Of hij moet op 40.000 feet zoals in het echt.

### Wat lost deze feature op?

Realisme + geen melding dat je boven cruise zit.

**Comment by Chang-nl** [comment]
Staan changes voor open, is aangepast
