### ISSUE TITLE
[Bug]: Wapenattachment reset na vasthouden van ander vuurwapen

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1353]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer je een vuurwapen met attachments hebt en je pakt een ander vuurwapen op kan het gebeuren dat de attachments resetten. Dit los je op door je vuurwapen in en weer uit je kofferbak te halen.

### Wat hoorde er te gebeuren?

Het vuurwapen hoort ten alle tijden de attachments te behouden.

### Wat veroorzaakt de bug?

Wanneer je een ander vuurwapen confisceert en deze vastpakt/richt en daarna weer je oude vuurwapen erbij pakt. Dit is getest met een skorpion en een HK416.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by AdventurePandah** [comment]
@niekschoemaker durf ik niet precies te zeggen. Dit is wat ik had gedaan:
1. HK416 gekocht met attachments zoals scope en barrel erop.
2. Skorpion geconfisceerd uit iemands inventory
3. Skorpion in kofferbak van voertuig gelegd
4. Skorpion uit kofferbak van voertuig gehaald
5. Skorpion vernietigd op Politie HB.

Heb zelf het idee dat het gebeurd is bij stap 3/4

**Comment by Attomn** [comment]
@Ljosfari en ik hebben dit vandaag meerdere malen getest maar hebben niet het probleem niet weten te reproduceren. Is dit nog een probleem? @AdventurePandah

**Comment by AdventurePandah** [comment]
@Attomn Ik ga het even navragen.

**Comment by AdventurePandah** [comment]
@Attomn @Ljosfari ik heb het nagevraagd. IK krijg te horen dat je wapen attachments resetten wanneer je gerevived wordt.

Dus wanneer je neergeschoten wordt of dood gaat en je wordt overeind geholpen, resetten je attachments tot je het wapen in een voertuig stopt en er weer uit haalt.

**Comment by Chang-nl** [comment]
Hey @AdventurePandah, is dit nog steeds een probleem?

**Comment by AdventurePandah** [comment]
Geen idee @Chang-nl. Heb het kortgeleden wel nog gehad dat mijn attachments gereset waren.

**Comment by Chang-nl** [comment]
Hey @AdventurePandah, heb je hier een videoclip van hoe dit gebeurd is? Alvast bedankt!

**Comment by AdventurePandah** [comment]
Ik ga er even achteraan. Ik zal hier later op reageren.

**Comment by AdventurePandah** [comment]
Aangezien het niet vaak meer voorkomt, sluit ik deze issue.
