### ISSUE TITLE
[FEATURE]: holster 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1357]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk om bij K menu ook apart holster bij te toevoegen, soms wil je een ketting gebruiken en een holster. Dus mij leek het wel leuk als je een ketting en holster tegelijkertijd kan gebruiken. Simpel gezegd een categorie erbij alleen voor holsters.

### Wat lost deze feature op?

Soms willen mensen bij hun outfit een ketting en holsters dragen, maar dat gaat niet helaas en vroeg me af als dit mogelijk was.

**Comment by MisterM02** [comment]
Heel veel holsters vallen in de "ketting" categorie bij de kledingshop. Daardoor kan je geen holster en ketting tegelijk gebruiken, omdat je anders 2 kettingen draagt

**Comment by Willem-Dekker** [comment]
denk niet dat dit mogelijk is, om bovengenoemde reden

**Comment by brothasx** [comment]
Deze is inderdaad niet mogelijk, vermits zij de zelfde kledingslot gebruiken.
