### ISSUE TITLE
[FEATURE]: Aanpassingen Jets

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1358]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

**Aanpassingen prijzen van de jets:**
Buckingham Vestra 
Nieuwe prijs: 4.000.000
Oude prijs: 6.000.000

**Aanpassingen kofferbak ruimte van de jets:**
_Bij de onderstaande jets mogen alle kofferbak ruimtes naar 1500kg_
Buckingham Shamal
Buckingham Luxor
Buckingham Miljet
Buckingham Nimbus

**Dit is al besproken in het afgelopen staffoverleg en is goedgekeurd. De Server Supporters krijgen hier over ongeveer een half uur alvast bericht over IVM een suggestie en sneakpeak.**

### Wat lost deze feature op?

Jets aantrekkelijker maken. Alles is al besproken!

**Comment by Chang-nl** [comment]
Gewicht is aangepast na de restart!

**Comment by Chang-nl** [comment]
Prijs is ook aangepast naar de gewenste hoeveelheid!
