### ISSUE TITLE
[FEATURE]: Wapentinten als compontenten refunds toevoegen

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1361]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

Op het moment kunnen we bij refunds niet de wapen tinten (roze, groen, paars en dergelijke) van bijvoorbeeld de M1911 toevoegen als componenten en moeten we personen refunden met 28k bank geld. Dit zou handiger zijn als we deze tinten kunnen selecteren of toevoegen bij componenten bij een refund.

### Wat lost deze feature op?

Hoeven geen bank geld te geven, maar kunnen direct wapen tinten selecteren of toevoegen.
Zodat personen hun wapen terug krijgen zoals hij was.

**Comment by niekschoemaker** [comment]
Zit erin voor na volgende restart
