### ISSUE TITLE
[Bug]:Meldingen afvinken in de meldkamer(s)

### ISSUE THREAD

**Issue by TDAMitchell** [Tedeapolis/development#1362]
### Contact Details

Mitchelll#1258

### Wat gebeurde er?

Moment dat je enter op een melding doet, en vervolgens afvinken word hij niet afgevinkt. Dit is erg hinderlijk gezien je hierdoor niet kan zien of de melding al gereden word of niet.

### Wat hoorde er te gebeuren?

Dat de melding groen word en dus afgevinkt

### Wat veroorzaakt de bug?

Script errors veroorzaakt deze bug. Staan hier onder in de gyazo.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://gyazo.com/8a394bc9f4839bc001038441c931c847

**Comment by Chang-nl** [comment]
Zou je het volledige logbestand willen sturen?

**Comment by TedeaTaxi** [comment]
Taxiwerk gaat erg moeizaam door deze bug. Veel mensen die dubbele meldingen pakken, etc. Communicatie is dus key nu maar blijft heel lastig. Als hulpmiddel vinken we nu de meldingen op discord af.

Is de oorzaak al bekend en de fix onderweg?

**Comment by niekschoemaker** [comment]
Is gefixed
