### ISSUE TITLE
[FEATURE]: Request Radio

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1363]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Je kan de commando /request_search of /rs doen om iemand te fouilleren, is het mogelijk om dit ook te maken voor porto's af te lezen. Bijvoorbeeld /request_radio of /rr om iemand zijn porto nummer af te lezen zodat je de porto kan afluisteren.

### Wat lost deze feature op?

Brengt / geeft meer roleplay en de spelers zouden dit graag willen hebben.

**Comment by Lorenzo3001** [comment]
Dit zit er al in :p
