### ISSUE TITLE
Request radio

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1364]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Als je dood bent dat je nog wel /request_radio kan accepteren en /request_search . 

### Wat lost deze feature op?

Een porto aflezen van iemand waar je een shootout mee hebt gehad is wel vrij handig om eventueel andere shooters een stapje voor te zijn.

**Comment by Chang-nl** [comment]
Denk dat het gefixt is? even laten weten of het opgelost is na de restart

**Comment by Chang-nl** [comment]
Heb het zojuist getest het zou gewoon moeten werken, heb mogelijk ook een issue opgelost dat je soms de request niet kon accepteren.

**Comment by CalRayy** [comment]
Tof om te horen Chang ❤️!
