### ISSUE TITLE
[FEATURE]: ANWB aanpassing / toevoegingen

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1365]
### Contact Details

DeStefanoKiller#4442

### Beschrijf zo duidelijk mogelijk de feature

- [x] Op postcode 812 een ANWB icoon neerzetten op de map die alleen zichtbaar is voor ANWB'ers in-dienst.
_Hier heeft de ANWB namelijk een paar cirkels die alleen bruikbaar zijn in-dienst._ 

- [x] Slot van poortjes afhalen bij de ANWB voor coords zie screenshot.
![coordspoort](https://user-images.githubusercontent.com/68514420/170590163-8fc90472-195c-4bf3-8d53-4e66c7ebc7f2.png)

- [x] Slot van deur afhalen voor bij de ANWB voor coords zie screenshot.
![coordsdeur](https://user-images.githubusercontent.com/68514420/170590182-ac67b509-d173-484e-b49b-3cad57d94c11.png)

- [x] Zaklamp toevoegen bij “koop items” van de ANWB.

### Wat lost deze feature op?

-

**Comment by niekschoemaker** [comment]
Alles zit erin.
