### ISSUE TITLE
[FEATURE]: Verandering rangen Les Revoltes

### ISSUE THREAD

**Issue by Tijz** [Tedeapolis/development#1367]
### Contact Details

Dekk#3792

### Beschrijf zo duidelijk mogelijk de feature

De commandant rang moet toegang hebben tot het inkopen en tunen van AK's.

### Wat lost deze feature op?

Minder gezeik rondom het wachten op desbetreffende rangen in de stad zijn voor de wapeninkoop en/of tunen.

**Comment by Willem-Dekker** [comment]
beide AK toegevoegd aan rang
