### ISSUE TITLE
[FEATURE]: Niet storen modus en custom ringtones op de telefoon

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1368]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

**Niet storen functie:**
_Je krijgt geen meldingen binnen van telefoontjes die naar je gepleegd worden. Je hoort dus geen ringtone of krijgt het te zien op je telefoon. Daarnaast staat het geluid voor berichten ook uit, wel zie je dit links onder zoals dat normaal ook is._

**Custom ringtones:**
_Het zelf kunnen toevoegen van ringtones aan je telefoon door middel van een YouTube link of iets. Dit zou je dan bij je Telefoon instellingen kunnen aanpassen._

### Wat lost deze feature op?

Niet storen functie: Geen irritante telefoontjes of iets wanneer je het niet wilt.
Custom ringtone: Leuke unieke feature die de ringtone wat leuker maakt.

**Comment by Attomn** [comment]
Oke! De niet storen functie is volgensmij nu werkend dus dan kan deze Github gesloten worden denk ik.

**Comment by Attomn** [comment]
Nee toch niet, de niet storen functie is er nog niet in. Excuus

**Comment by niekschoemaker** [comment]
> Nee toch niet, de niet storen functie is er nog niet in. Excuus

Als ik het goed begrijp gaat dit dus puur om het geluid uitzetten en meer niet? Dus alle notificaties wel zoals normaal maar geen geluid?

**Comment by Attomn** [comment]
Yes, geen geluid en ook niet dat je je telefoon pakt als je gebeld wordt. Telefoon berichten mogen wel binnen komen.

**Comment by niekschoemaker** [comment]
Zit erin
