### ISSUE TITLE
/givecarkeys of /carkeys

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#137]
Command toevoegen bij superadmin zodat je geforceerd een voertuig kan overschrijven op iemands naam. 

/givecarkeys (kenteken) (steamID)

Eventueel een geheel andere command:
/carkeys (kenteken) (steamID)

**Comment by SecretSupplier** [comment]
Ja is prima zou wel steamID doen zodat het kan wanneer persoon offline is.

**Comment by Willem-Dekker** [comment]
/givecar  {steamid} {kenteken}
dit is het nieuwe command
