### ISSUE TITLE
[Bug]: Het overschrijven en quick sellen van de zeilboot (marquis) is niet mogelijk.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1370]
### Contact Details

Attom#3152

### Wat gebeurde er?

Quicksell verkopen:
![afbeelding](https://user-images.githubusercontent.com/69365961/170836941-fd00e292-e685-42e6-b66c-28797e537729.png)

Overschrijven naar andere:
![Uploading afbeelding.png…]()

### Wat hoorde er te gebeuren?

Quicksell: Boot hoorde verkocht te worden, gebeurde niet.
Overschrijven naar andere: Boot hoorde naar het andere persoon, gebeurde niet.

### Wat veroorzaakt de bug?

Geen idee. Dit gebeurd altijd bij de zeilboot dus dit is makkelijk na te maken.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Is gefixed
