### ISSUE TITLE
[Bug]: Auto's uit garage halen spawnen op andere auto's bij spawnplekken.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1371]
### Contact Details

Attom#3152

### Wat gebeurde er?

Iemand haalde zijn auto uit de garage, deze spawnde vervolgens op andere auto's die daar al geparkeerd stonden. 

Voorbeeld:
https://cdn.discordapp.com/attachments/608089499049787412/980519646195249223/Desktop_2022.05.29_-_19.12.32.03.DVR_Trim.mp4

Wat dus het probleem is, hij checkt niet of de spawnplek vrij is.
Dit is de garage bij postcode 7069.

### Wat hoorde er te gebeuren?

De garage hoort te checken of de spawnplek vrij is, als deze niet vrij is een melding geven dat de spawnplek niet vrij is.

### Wat veroorzaakt de bug?

Auto uit de garage pakken terwijl de spawn plekken bezet zijn.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

Hoog

**Comment by niekschoemaker** [comment]
Is dit iets wat vaker voorgekomen is? Want hij checked namelijk wel of de spawnplek vrij is.

Dus lijkt me dan eerder dat dit dan toevallig om een voertuig gaat welke voor de persoon die dus die camper inspawnde nog niet gedownload was, of voor een andere reden niet ingeladen was gaat.

**Comment by Attomn** [comment]
Ah, zover ik hoor gebeurt dit vaker daar. Wellicht dat de check bij die specifieke garage niet helemaal lekker werkt of iets?
