### ISSUE TITLE
[FEATURE]: Juwelier kunnen starten tot 24.00 n.a.v. staffoverleg

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1372]
### Contact Details

Hellfire

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid van het starten van de juwelier 2 uur extra tijd voor maken.

### Wat lost deze feature op?

Dat deze niet meer gestart kan worden terwijl er genoeg politie/kmar en criminelen in de stad zijn.

**Comment by niekschoemaker** [comment]
Is gefixed
