### ISSUE TITLE
[FEATURE]: In de auto, een handschoenenkastje inbouwen voor opslag.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1373]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

Na aanvang van afgelopen staff overleg (29-05-2022):

**Handschoenen kastje opslag in een voertuig**
Een opslag in je auto, van een maximaal aantal kilo waar je iets van een mesje, pistool, ammo of voedsel in op kan slaan.

Spieren die je kan gebruiken: 'O' of 'P' om dit kastje te openen in je voertuig.

Een voorbeeld: https://forum.cfx.re/t/esx-inventoryhud-glovebox/687328

**Zodra dit toegevoegd word, kan iemand mij even een berichtje doen? Dan kan ik de Server Supporters een sneak peak geven :)**

### Wat lost deze feature op?

Extra unieke toevoeging, hoor je niet veel van en voegt leuke dingen toe. Voertuig doorzoekingen van politie bijvoorbeeld.

**Comment by Nander0320** [comment]
Ik ga deze helaas toch afkeuren dit omdat een kofferbak en handschoenenkastje geen verschil gaan maken. Wanneer een agent je kofferbak gaat doorzoeken mag deze wettelijk ook simpelweg je handschoenenkastje doorzoeken. Dat maakt dit alles dus een beetje overbodig
