### ISSUE TITLE
[FEATURE]: Reports van Hoge Raad en Head Staff rood maken / announcement in scherm kunnen geven.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1375]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

Reports van Hoge Raad en Head Staff rood maken

Whisper announce richting een stafflid: met iets van /announcewhisper zodat je bericht zeker weten aankomt. Dit enkel beschikbaar maken voor Hoge Raad en Head Staff

### Wat lost deze feature op?

Replies die over het hoofd gezien worden vanuit ons. Vaak wanneer we staffleden checken op wat ze doen, een reply sturen, worden deze over het hoofd gezien omdat het niet opvalt.

**Comment by AnatolyMoskvin** [comment]
Kan ik deze ook hier bij zetten ? Gezien dit ook over reports gaat :)

![image](https://user-images.githubusercontent.com/84158163/170997024-ecf203a7-6a0e-45de-bdca-f8797f3dddc5.png)

![image](https://user-images.githubusercontent.com/84158163/170997040-b4ada119-f49e-43d5-9041-cedab31a01d5.png)

**Comment by Attomn** [comment]
@Chang-nl De kleur van reports hebben nu een rode omlijning, eigenlijk is het de bedoeling om de hele report rood te maken, zou je dit kunnen aanpassen? Alvast bedankt <3

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/171917772-3c84f03d-3318-47b6-ac53-d8735d3db776.png)
Ah, en replies zijn nog lichtblauw richting andere mensen.

**Comment by Chang-nl** [comment]
Gefixt is na de herstart van kracht.

**Comment by nickdb04** [comment]
@Chang-nl is alles dan gefixed ? :D

**Comment by Chang-nl** [comment]
Ah stom ik had niet gezien dat er ook nog een command bij moest. Wat moet dat command precies doen want ik kan uit de tekst niet helemaal opmaken wat jullie voor ogen hebben.

**Comment by nickdb04** [comment]
> Ah stom ik had niet gezien dat er ook nog een command bij moest. Wat moet dat command precies doen want ik kan uit de tekst niet helemaal opmaken wat jullie voor ogen hebben.

Wat er moest gebeuren is dat de huidige reports moeten veranderd worden naar

Je report is verstuurd naar de online admins
Je report is: (Dan wat diegene heeft verstuurd)

**Comment by Attomn** [comment]
Je bedoeld met mijn command? Met /announcement krijgt de hele server kei groot een bericht in hun scherm, we wouden deze ook per persoon kunnen sturen, dus met een command zoals /whisperannouncement id bericht, dat mensen een bericht in hun scherm krijgen.

**Comment by Chang-nl** [comment]
Volledige issue is gefixed na herstart!
