### ISSUE TITLE
[FEATURE]: Handboeien

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1376]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Politie kunnen momenteel eindeloos mensen handboeien en bij staffoverleg hebben hierover gepraat. We zijn op conclusie gekomen dat Politie een item moeten krijgen die ze kunnen gebruiken om mensen te boeien en ze mogen maximaal 2 in een inventory hebben.

Dit telt ook voor de criminelen, criminelen kunnen maximaal 5 tiewraps in hun inventory hebben, 

Dit is tevens ook overlegt in de vergadering.

### Wat lost deze feature op?

Het vermijden van eindeloze mensen boeien.

**Comment by Chang-nl** [comment]
Gefixed na restart!
