### ISSUE TITLE
[FEATURE]: Tijden reset dragstrip / kartbaan

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1377]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Momenteel zijn er verschillende tijden gezet bij zowel de kartbaan en bij de dragstrip die lastig zijn om te verbeteren. Veel mensen wagen dan ook geen poging om het een keer te proberen of om er actief mee bezig te zijn. Daarom het volgende idee: Eens in de zoveel tijd, bijvoorbeeld om de 2 maanden, de tijden resetten bij zowel de dragstrip als bij de kartbaan.

### Wat lost deze feature op?

Zo wordt de dragstrip en de kartbaan actiever gebruikt omdat je dan meer kans maakt om op het scoreboard te komen.

**Comment by Chang-nl** [comment]
Aangepast!
