### ISSUE TITLE
[FEATURE]: Meer huizen in het noorden.

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1379]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Een woning in het noorden is een leuke plek beetje afgelegen lekker in de natuur dit zal een leuke toevoeging zijn aangezien nu veel mensen het zelfde appartement/huis hebben waardoor het er altijd druk is deze lijk me leuk aangezien je hier ook leuke rp senario kan zetten met de velde erom heen en de crossbaan. 

Enkele huizen wat leuk kan zijn die je kan kopen:
https://cdn.discordapp.com/attachments/608089499049787412/977167410899603486/unknown.png
https://cdn.discordapp.com/attachments/608089499049787412/977167411902046238/unknown.png

https://cdn.discordapp.com/attachments/977167413147758602/977323980941852682/unknown.png
https://cdn.discordapp.com/attachments/977167413147758602/977324035778174986/unknown.png

### Wat lost deze feature op?

Meer variatie qua huizen in het noorden als het mogelijk is natuurlijk 😄

**Comment by Nander0320** [comment]
Niet nodig geacht. wel een leuk idee!
