### ISSUE TITLE
[Bug]: Kofferbak bug

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1380]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je zet iets in je kofferbak en je gaat eruit dat hij de emote weer opnieuw doet, is soms enorm hinderlijk als je snel iets moet pakken en moet uitvoeren. Is het mogelijk om dit aan te passen?

### Wat hoorde er te gebeuren?

Als je uit je kofferbak gaat dat je er ook echt uit bent en niet weer in die emote zit.

### Wat veroorzaakt de bug?

Geen flauw idee. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Ik weet niet wat dit veroorzaaakt en weet niet waar je het uberhaupt over hebt, dus als je er even een video of iets dergelijks van kunt maken, want dit is niet iets wat altijd gebeurt.

**Comment by nickdb04** [comment]
@Chang-nl klopt het dat het nog niet gefixed is ?

**Comment by nickdb04** [comment]
Het is namelijk nog steeds zo dat je naar je "kofferbak" loopt en dan pas er in kan. Wellicht een idee om het oude systeem er weer terug in te doen zonder dat die er naar toe loopt

**Comment by Chang-nl** [comment]
Is niet relevant aan deze issue.
