### ISSUE TITLE
[Bug]: Personeelsleden ontslaan uit het boss menu werkt niet meer. (KMar)

### ISSUE THREAD

**Issue by warturtlez** [Tedeapolis/development#1381]
### Contact Details

Johnny#8125

### Wat gebeurde er?

Als KMar boss job kan je in het Boss menu -> Personeelsbeheer -> Werknemerslijst mensen niet ontslaan. Als je op ontslaan drukt dan verdwijnt persoon uit het menu. Maar als je uit het menu gaat en opent het opnieuw komt dezelfde persoon weer terug in de lijst.

### Wat hoorde er te gebeuren?

Persoon hoort ontslagen te worden en niet terug te keren in het menu. En je hoort als boss zijnde een melding te krijgen dat specifieke persoon ontslagen is.

### Wat veroorzaakt de bug?

Jezelf op kmar 100 zetten, naar het boss menu gaan. Werknemerslijst en iemand ontslaan. (Onbekend of het bij andere jobs ook afspeelt)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by CalRayy** [comment]
Dit telt ook voor de ambulance, denk persoonlijk bij elke overheid / gang.

**Comment by Chang-nl** [comment]
Dit is opgelost!
