### ISSUE TITLE
[FEATURE]: Shotgun damage

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1382]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In staff overleg was er besproken om de damage van de shotgun te verhogen, is het mogelijk om de damage te verhogen van de shotgun?

### Wat lost deze feature op?

Meer damage geven / buffs van een wapen. Spelers worden blij.

**Comment by Chang-nl** [comment]
Gefixed!
