### ISSUE TITLE
[FEATURE]: Met een mesje /takehostage kunnen doen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1383]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In staffoverleg van enkele weken geleden was er besproken om met een mesje /takehostage te kunnen alleen is deze github nooit gemaakt volgens mij, ik vroeg me af als dit nog mogelijk is  / was?

### Wat lost deze feature op?

Betere RP's

**Comment by Lorenzo3001** [comment]
Dit is juist afgekeurd als ik het me goed herinner.

**Comment by CalRayy** [comment]
oh Willem zei dat het niet was doorgevoerd deze github feature dus dacht goedgekeurd was.
