### ISSUE TITLE
[Bug]: /chardel geeft geen output

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1384]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als /chardel bij iemand doet krijg je geen melding van " naam van speler" is verwijderd, dit komt volgens mij door de nieuwe chat bubbles.

### Wat hoorde er te gebeuren?

je hoort normaal te zien dat je iemand zijn karakter hebt verwijderd, de melding althans

### Wat veroorzaakt de bug?

Waarschijnlijk door de nieuwe chat bubbles. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Is gefixed!
