### ISSUE TITLE
[FEATURE]: TDA Nieuws helikopter cirkel

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1385]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

TDA Nieuws heeft een eigen helikopter alleen is er geen cirkel om de helikopter weg te zetten.
Is het mogelijk om een helikopter wegzet garage te zetten op de volgende coords:

x: -583.50 y: -930.51 h: 265.92

### Wat lost deze feature op?

Je kan je helikopter wegzetten en is wel handig lijkt me voor het Nieuws.

**Comment by Chang-nl** [comment]
Gefixed!
