### ISSUE TITLE
[Bug]: Politie / KMar tackelen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1386]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Als politie kun je mensen met KMar rang tackelen en vice versa.

### Wat hoorde er te gebeuren?

Politieagenten kunnen onderling elkaar niet tackelen (met opzet zo gedaan i.v.m. dat de tackel nogal willekeurig iemand kiest wanneer je dichtbij twee personen staat), maar de KMar en politie behoren niet tot dezelfde groep waardoor het ineens wel kan.

### Wat veroorzaakt de bug?

Tackel met politie job iemand met KMar job.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
Gefixed!
