### ISSUE TITLE
[NEW] Narcos MLO

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#1387]
### Beschrijf zo duidelijk mogelijk de feature

Narcos nieuwe MLO

Aanpassingen die zijn gemaakt en doorgevoerd moeten worden.

- [ ] esx_doorlock
- [ ] esx_bikerjob
- [ ] Narcos
- [ ] esx_property

**Comment by niekschoemaker** [comment]
Hiervoor kun je beter github-commits-aanvragen gebruiken in Discord

**Comment by Savagesix5654345353** [comment]
wwwwwwwwwwwwww
