### ISSUE TITLE
[FEATURE]: Muziek cirkel 

### ISSUE THREAD

**Issue by nickdb04** [Tedeapolis/development#1388]
### Contact Details

AntonMoskvin#3144

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag een muziek cirkel willen net zoals karmellos heeft 

Coords: X: 1385.01 Y"-2089.44 Z: 52.61

### Wat lost deze feature op?

Dat we muziek kunnen afspelen en dit niet hoeven te doen via onze mic

**Comment by Ljosfari** [comment]
denk dat dit beter op een andere manier aangevraagd kan worden, de devs kunnen het er wel in zitten, maar meer, is hier goedkeuring voor.

**Comment by Chang-nl** [comment]
Hij gaat doorgevoerd worden!
