### ISSUE TITLE
[FEATURE]: TDA Nieuws Busje

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1389]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Beste lezer,

Dit bericht is een aanvraag voor het vervangen van de huidige skin die op het dienstvoertuig zit van TDA Media. Dit is een verouderde versie van de vorige eigenaren van plus minus 1 jaar geleden. Sindsdien is er veel veranderd, eerst heeft Edgar Avagyan het nieuws over genomen en nu is het onder nieuw management van Micheal Terpstra. 

Waarom is deze aanpassing nodig, wat levert het op?
Deze aanpassing zou nodig en wenselijk zijn omdat wij nu rijden in reclame van een nieuwsinstantie die niet meer actief is. Daarnaast zenden wij een journaal uit en maken wij een Weekblad. Nu wordt er vaak door burgers geroepen; “Kijk de Telegraaf!” en dan moeten wij verklaren dat wij niet van de Telegraaf zijn maar van TDA Nieuws – Weekblad. Dit maakt de roleplay iets lastiger.  Ook zal deze aanpassing een soort erkenning zijn van de motivatie die wij hebben sinds augustus 2021. 

De aanpassing zal ook zorgen voor meer reclame en naamsbekendheid in de stad, hierdoor zullen de eventuele lezers en views toe kunnen nemen. 

Betreft de skins
Wij leveren een bestand aan waar de skins al in zijn gemaakt, de skin van het oude voertuig; Bus 2p van TDA Media mee vervangen kan worden. Eventueel hebben wij ook een nieuwe skin voor de helikopter van TDA Media. 

Als het niet mogelijk zou zijn de skins aan te passen zouden wij in staat kunnen zijn om een Volvo voertuig te reskinnen zoals de ministerie en ANWB heeft. 

In afwachting op antwoord,
TDA Media

(Het bestand van het voertuig staat in github commits aanvragen )

### Wat lost deze feature op?

De aanpassing zal zorgen voor meer reclame en naamsbekendheid in de stad, hierdoor zullen de eventuele lezers en views toe kunnen nemen.

**Comment by brothasx** [comment]
Is al reeds uitgevoerd
