### ISSUE TITLE
[Bug]: Remmen werken niet bij motorlampje jet

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1393]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer je te hard land met een Jet kan je een motorlampje krijgen. Zodra je een lampje hebt is het niet mogelijk om te remmen waardoor je dus van de baan af schiet.

### Wat hoorde er te gebeuren?

Je hoort af te remmen. 

### Wat veroorzaakt de bug?

Een motor lampje

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
Is dit nog steeds een probleem?

**Comment by AdventurePandah** [comment]
> Is dit nog steeds een probleem?

@Chang-nl ja

**Comment by Chang-nl** [comment]
Het is na herstart gefixt, bedankt voor het melden!
