### ISSUE TITLE
[Bug]: Vliegen op muis opent soms plotseling pause menu

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1394]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer je een vliegtuig of helikopter vliegt met je muis kan het soms gebeuren dat je opeens je pauze menu opent. Hiermee bedoel ik het menu wat je krijgt als je op escape drukt.

### Wat hoorde er te gebeuren?

Het pauze menu hoort alleen open te gaan wanneer je op ESC drukt.

### Wat veroorzaakt de bug?

Stap in een helikopter en bestuur deze met de muis. Tap daarbij meerdere keren ipv continu muisknop indrukken en vliegen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Het menu wordt alleen geöpened door GTA zelf, heb je niet toevallig een keybind op je muis zitten die op P staat of zo?

**Comment by Tijz** [comment]
> 

Ik ken niemand die het heeft dus ik denk idd dat het aan hem ligt.

**Comment by AdventurePandah** [comment]
Ik sluit deze voor nu aangezien er niet duidelijk is hoe het gebeurd. Mocht ik meer weten maak ik een nieuwe issue aan.

**Comment by CalRayy** [comment]
> Ik sluit deze voor nu aangezien er niet duidelijk is hoe het gebeurd. Mocht ik meer weten maak ik een nieuwe issue aan.

Ik heb dit ook af en toe, dit komt als ik ga landen meestal en meerdere knoppen druk en mijn muis gebruik.
