### ISSUE TITLE
[FEATURE]: ''Ontboei knop'' ook laten boeien.

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1395]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Zo nu en dan moet je iemand aanhouden voor een lichte overtreding, zoals lokaal vredebreuk. Je moet nu op de ''boeien'' knop drukken om iemand aan te houden. Deze animatie is redelijk gewelddadig voor een overtreding van deze klasse.

Dus de feature: ontboeien en boeien dezelfde functie geven, zoals voor de update dat je geen fysieke boeien nodig had. Zo kan je iemand aanhouden zonder gewelddadig over te komen.

### Wat lost deze feature op?

Je komt niet ontzettend gewelddadig over voor een kleine aanhouding, maakt het een stuk realistischer.

**Comment by Chang-nl** [comment]
Is aangepast volgende restart!
