### ISSUE TITLE
[Bug]: Blokkeer functie 2.0

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1396]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Mensen kunnen je nog altijd een sms sturen terwijl ze geblokkeerd zijn. Kreeg namelijk aantal klachten hierover, zie clip -> https://www.youtube.com/watch?v=Iaacn9n9bBY

### Wat hoorde er te gebeuren?

Je hoort normaal geen sms te kunnen ontvangen van een geblokkeerde persoon

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn na volgende restart, anders even hier commenten, dan reopen ik hem weer
