### ISSUE TITLE
[Voertuig BUG]: Bronco

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1397]
### Contact Details

CalRay#1513

### Kenteken van voertuig

EDC 147

### Voertuig model

Bronco Wildtrak

### Omschrijf de bug

Als jij op een gegeven moment rijd met de Bronco, komt er twee zwarte vlekjes waar je heel goed moet kijken om dit te zien. Ik zelf merkte het soms maar nu dat ik het heb gemerkt zie ik het altijd als ik een beetje rij met de Bronco hier heb ik ook een clip van.

Ik wil even duidelijk maken dat je de mini zwarte vlekken niet gelijk voor je auto ziet, maar laten we zeggen 20 meter voor je is.
Zie video: https://www.youtube.com/watch?v=rxKLlPOrqnc

### Repro

1. Rijden met de Bronco voor paar minuten.
2. vervolgens krijg je zwarte mini vlekjes op de weg

### Normaal gedrag

Je hoort de zwarte mini vlekjes niet te zien wanneer je rijd / stopt met je bronco en dit komt volgens mij van de voertuig zelf.

**Comment by niekschoemaker** [comment]
Als je je auto schoonmaakt gaan ze dan weg? En verder zie ik op die video dus echt helemaal niks

**Comment by CalRayy** [comment]
> Als je je auto schoonmaakt gaan ze dan weg? En verder zie ik op die video dus echt helemaal niks

Ik zal dit vanavond even testen, ja in de video zie je het echt lichtelijk misschien even in call proberen of ingame.

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/171700866-9bf9ce96-ab4e-4b73-b8e0-54dea8f9b7d7.png)
Deze puntjes zijn er constant als je rijdt, als hij schoon is dit niet aan de hand zover ik zag.

**Comment by niekschoemaker** [comment]
@Lorenzo3001 Kun jij hier toevallig iets mee?

Ik had hem al even geopend in OpenIV, en ik zie in de model zelf inderdaad 2 zwarte stippen voor het voertuig staan 🤔

**Comment by Lorenzo3001** [comment]
Fixed
