### ISSUE TITLE
[FEATURE]: Uitbetalingen van legale jobs direct naar bank ipv cash

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1398]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Momenteel worden facturen cash uitbetaald. Het zou mooi zijn als dit direct op je bank gestort kan worden.

### Wat lost deze feature op?

Zo hoef je na het uitbetalen van je facturen niet naar een pinautomaat te lopen en loop je ook geen risico om het net verdiende geld te verliezen door dood te gaan oid.

**Comment by AdventurePandah** [comment]
Weet overigens niet of dit bij elke job zo is, iig bij ramenwassen ^

**Comment by niekschoemaker** [comment]
Ik heb dit voor ramen wasser gefixed
