### ISSUE TITLE
[Bug]: Kofferbak Bug

### ISSUE THREAD

**Issue by nickdb04** [Tedeapolis/development#1399]
### Contact Details

AntonMoskvin#3144

### Wat gebeurde er?

Als je op **L** drukt om de kofferbak te openen loopt die naar het "kofferbak" van het voertuig. Echter klopt deze van geen kant en loop je vaak veelste ver van voertuig vandaan. Zie video

Uploading Desktop 2022.06.02 - 12.20.14.05.DVR_Trim.mp4…

 

### Wat hoorde er te gebeuren?

Je hoort gewoon normaal je kofferbak te kunnen openen zonder dat je helemaal naar de sarah loopt. Daarnaast is deze bug bij meerdere mensen een probleem.

### Wat veroorzaakt de bug?

Je pakt een voertuig bijvoorbeeld "/car nmule" je drukt op **L** en je poppetje loopt naar de "kofferbak" echter loopt die vaak helemaal naar de andere kant.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/36623846/171613050-37cc4373-701f-41a3-9249-337714a05d9b.png)

**Comment by niekschoemaker** [comment]
Is "gefixed"
