### ISSUE TITLE
Ambulanciers kunnen hartslag niet meten

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#14]
Als iemand dood op de grond ligt met genoeg hartslag en bloed kunnen ambulanciers het niet controleren.
Er komt niks in beeld te staan. Je volgt de juiste stappen die zoals anders doet. Naar persoon toe gaan, F6 controleer hartslag en dan komt er normaal hartslag en %bloed te staan. Nu niks.

**Comment by Willem-Dekker** [comment]
zou je iets meer debugging kunnen geven/ logs van de persoon met de issue (patient en ambuancier)
