### ISSUE TITLE
easy admin crash 

### ISSUE THREAD

**Issue by krizz696** [Tedeapolis/development#140]
om 1 of andere reden kan ik niet meer in mn easy admin menu nadat ik een persoon een warn geef en deze van de server gekickt word . gebeurd enkel als ik die zelfde persoon aan het spectaten ben ...

**Comment by Willem-Dekker** [comment]
graag logs en een reproductie als dit mogelijk is

**Comment by Willem-Dekker** [comment]
dit is denk ik opgelost aangezien er geen logs zijn of verdere opmerkingen
