### ISSUE TITLE
[Bug]: AMBU Ziekenhuis kleding voor vrouwen

### ISSUE THREAD

**Issue by SgtPointless** [Tedeapolis/development#1400]
### Contact Details

SgtPointless#7305

### Wat gebeurde er?

Wij hebben redelijk recent de nieuwe ziekenhuis kleding gekregen voor vrouwen. Enkel zit er wel een probleem in dat het nummertje van de Armen en T-Shirt niet kloppen waardoor je gaten hebt in bij de nek en een panter print shirtje. Ook kunnen ze geen accessoires dragen, denk dan bijvoorbeeld aan een hoedje / pet of zonnebril.
![unknown (3)](https://user-images.githubusercontent.com/104445984/171746608-124379a7-1035-4a91-b84b-bb6638c58bf8.png)
![unknown](https://user-images.githubusercontent.com/104445984/171746612-165085fa-8a02-43c0-b477-f4e3b6c9151f.png)
![unknown (1)](https://user-images.githubusercontent.com/104445984/171746618-de9773bd-2870-4327-a1a4-b10c1c84506a.png)
![unknown (2)](https://user-images.githubusercontent.com/104445984/171746624-49b35838-3a0f-4492-bfcc-51439059589c.png)
 

### Frequentie van de bug

Altijd

**Comment by brothasx** [comment]
Tot het maximale gefixed, enigste wat je nog hebt is een klein randje. Tshirt bug is gefixed.
