### ISSUE TITLE
[Bug]: Ontboeien werkt (vaak) niet

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1401]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Video: https://www.youtube.com/watch?v=cu1yO_FYFe8

Zoals op de video te zien is krijgt de agent in kwestie de melding "persoon is niet geboeid" als hij op Ontboeien klikt. Hij moet vervolgens de persoon opnieuw boeien om deze te ontboeien, wat een extra set handboeien kost (en hij krijgt de originele ook niet terug).

Video is trouwens niet van mij, heb ik viavia gezien en blijkbaar is deze issue nog niet aangekaart, vandaar deze Github.

### Wat hoorde er te gebeuren?

Persoon hoort ontboeid te worden en hoort de agent een set handboeien terug te krijgen.

### Wat veroorzaakt de bug?

Onbekend, ik heb verder ook geen logs of F8 screenshots. Eventueel kan dit door middel van testen of via politie opgevraagd worden.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by PolitieTDA** [comment]
Dit githubje mist wat informatie, zie #1404 voor meer uitleg.

**Comment by niekschoemaker** [comment]
Informatie van #1404 :

    Nadat je iemand in een voertuig hebt gezet en diegene er weer uithaalt, kun je deze niet meer ontboeien. Je krijgt dat het bericht te zien dat deze persoon al ontboeid is. Je moet de persoon dus weer boeien en dan gaat diegene los, maar verlies je dus weer opnieuw een setje handboeien daardoor.

    Voorheen kon je door op 'ontboeien' te klikken ook op een rustige manier iemand vastmaken, dit werkt nu niet meer sinds de nieuwe update.

**Comment by niekschoemaker** [comment]
Is dit ondertussen met de laatste fix die ik gedaan heb gefixed? Zat er vandaag (gisteren, dus 04-06) al in.

**Comment by Mikajac** [comment]
> Is dit ondertussen met de laatste fix die ik gedaan heb gefixed? Zat er vandaag (gisteren, dus 04-06) al in.

Ik ben net met eenheden van de politie mee geweest tijdens een huiszoeking en de bug mbt voertuigen zit er nogsteeds in. Hij moest de persoon weer via "Boeien" ontboeien aangezien hij de foutmelding kreeg.

**Comment by niekschoemaker** [comment]
Is dit nog steeds en issue op het moment @Mikajac @PolitieTDA

**Comment by Chang-nl** [comment]
Is dit nog een probleem of is het al opgelost?

**Comment by Attomn** [comment]
@Mikajac

**Comment by Mikajac** [comment]
> @Mikajac

Ik kan hier moeilijk op reageren, aangezien ik zelf geen F6 heb om te (ont)boeien. Ik had eigenlijk gehoopt dat @PolitieTDA terugkoppeling zou geven maar ik denk dat alles werkt, aangezien we niks horen dat het niet werkt.

**Comment by Ljosfari** [comment]
is dit al opgelost ?

**Comment by Mikajac** [comment]
Gesloten ivm gebrek aan terugkoppeling gebruiker. Waarschijnlijk werkt het dus weer.
