### ISSUE TITLE
[FEATURE]: Nieuwe rol narcos

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1402]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden als Narcos een nieuwe rang willen hebben genaamd "Teniente"
Deze zal tussen Sicario en Consejero in moeten.

### Wat lost deze feature op?

Meer variatie in rangen, om zo leden te kunnen belonen met promoties!

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart.
