### ISSUE TITLE
[FEATURE]: Aanpassing schietmeldingen Politie/KMar locatie

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1403]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Wanneer iemand schiet en er een schietmelding verstuurd wordt, wordt de locatie van de schutter van waar hij zich op dat moment bevindt verstuurd. Stel iemand schiet bij grote bank en vlucht vervolgens richting Eclipse, dan komt de schietmelding binnen tussen grote bank en eclipse ipv bij grote bank zelf waar de persoon daadwerkelijk geschoten heeft.

Dit zorgt voor een oneerlijk voordeel voor de Politie aangezien zij zo kunnen herleiden waar de schutter is heen gevlucht.

Het zou dus beter en eerlijker zijn als de locatie van het schietincident wordt verstuurd ipv de locatie van de schutter.

### Wat lost deze feature op?

Zo blijft het voor de Politie een raadsel waar de persoon heen is gevlucht en moeten ze het dus echt aan getuigen vragen.

**Comment by niekschoemaker** [comment]
Is gefixed
