### ISSUE TITLE
[Bug]: Politie handboeien

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1404]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Een aantal bugs met de nieuwe handboeien:

- Nadat je iemand in een voertuig hebt gezet en diegene er weer uithaalt, kun je deze niet meer ontboeien. Je krijgt dat het bericht te zien dat deze persoon al ontboeid is. Je moet de persoon dus weer boeien en dan gaat diegene los, maar verlies je dus weer opnieuw een setje handboeien daardoor.

- Voorheen kon je door op 'ontboeien' te klikken ook op een rustige manier iemand vastmaken, dit werkt nu niet meer sinds de nieuwe update.

### Wat hoorde er te gebeuren?

De handboeien hoor je los te kunnen maken en de handboeien terug te krijgen.

### Wat veroorzaakt de bug?

- Maak iemand vast met politie handboeien, plaats ze in een voertuig en haal ze er weer uit. Nu kun je deze niet meer losmaken en moet je diegene opnieuw boeien waardoor je de handboeien verliest.

- Ga bij iemand staan en probeer deze op de ''rustige'' manier te boeien met het 'ontboeien' knopje.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Duplicate of #1401
