### ISSUE TITLE
[Bug]: Draw performance uitzetten werkt niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1405]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je draw performance uit wilt zetten gaat de menu zo snel mogelijk weg zonder dat je iets kan aanvinken. Ik weet niet als dit komt door fivem of door TDA, zie video: https://medal.tv/games/gta-v/clips/n8NomBVBhl7ZD/d1337En29wYA?invite=cr-MSxiemosMjc3NTc1NTQs

### Wat hoorde er te gebeuren?

Je hoort normaal dingen te kunnen vinken voor je performance te lezen.

### Wat veroorzaakt de bug?

Je klikt erop en het gaat weg.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by AdventurePandah** [comment]
Heb hier ook last van, heb meerdere mensen hierover klagen ^

**Comment by niekschoemaker** [comment]
Meneer, dit is een FiveM feature 😳 
https://github.com/citizenfx/fivem/commit/ca3341bb4e61f1122a5b9e49282c3e7d05c93027

Maar ik gok dat deze commit dit al fixed, gezien er dus iets met console host focus gerevert is
