### ISSUE TITLE
[FEATURE]: Deepweb 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1407]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is er mogelijkheid om te zien hoeveel berichten je hebt gemist op deepweb, zie screenshot als voorbeeld:
![image](https://user-images.githubusercontent.com/101106299/172059970-074d50e9-2097-4158-b4ea-651d791614a9.png)

### Wat lost deze feature op?

Dan weet je hoeveel berichten je hebt gemist wanneer je offline was of iets anders 😄

**Comment by niekschoemaker** [comment]
Dit is niet mogelijk, gezien de berichten pas geladen worden op het moment dat de kanalen geöpend worden.
NOu ja zou technisch wel mogelijk zijn, maar is best wat werk voor een vrij kleine feature.
