### ISSUE TITLE
[Bug]: Snelheidsmeter komt boven telefoon te staan

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1408]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Sinds kort komt de snelheidsmeter boven de telefoon te staan in je beeldscherm (zie foto).
![image](https://user-images.githubusercontent.com/93579695/172074885-f6decb6a-46b2-46ac-8644-93de8730cda9.png)

### Wat hoorde er te gebeuren?

Hoort achter de telefoon te staan omdat je anders geen meldingen e.d. kunt lezen.

### Wat veroorzaakt de bug?

Zet de snelheidsmeter aan en pak je telefoon.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Is na volgende restart gefixed
