### ISSUE TITLE
[FEATURE]: Het kunnen verstoppen in afvalcontainers.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1409]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

https://forum.cfx.re/t/release-standalone-hideintrash/4825523

Besproken in het afgelopen staffoverleg van 05-06-2022. 

Het kunnen verstoppen in afval containers, wel is besproken dat dit niet iedere afvalcontainer gaat worden. Ook is het de bedoeling dat er maar 1 iemand in de container kan en dat de AFK kick gewoon meeloopt, zodat je niet AFK kan gaan in een container. Ook moet je een melding boven de prullenbak kunnen zien dat er al iemand in zit zodat je met "/me kijkt in prullenbak" kan roleplayen dat je iemand vind.

### Wat lost deze feature op?

Nieuwe unieke feature.

**Comment by CorruptSausage** [comment]
Zit erin na restart, voor enige bugs mij even contacteren.
