### ISSUE TITLE
Pistol Magazines

### ISSUE THREAD

**Issue by SvenKeppel** [Tedeapolis/development#141]
Heyhey! pistol magazines lijken niet te werken. 

Wat er mis gaat is als je de pistol bij je houd gevuld met 1 magazine en je logt uit dan ben je vervolgens alle kogels kwijt in het magazijn . 
Ook heb je dit als je m in de auto legt of in een huis/appartement . 
Zo raken mensen dus iedere keer 10 k kwijt. 

zie nu dat ik ook alle attachments kwijt ben.

**Comment by Willem-Dekker** [comment]
zou je het nog eens kunnen testen
dit zou namelijk al moeten werken.

**Comment by SvenKeppel** [comment]
Op ma 31 aug. 2020 om 19:35 schreef Willem Dekker <notifications@github.com>

**Comment by niekschoemaker** [comment]
Is deze issue ondertussen al gefixed? Dacht namelijk van wel
