### ISSUE TITLE
[FEATURE]: Effecten bij auto ongelukken

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1410]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

https://forum.cfx.re/t/release-effect-on-car-accident/1170833

Besproken bij het afgelopen staff overleg op 05-06-2022.

Effecten bij een auto ongeluk. Wel moeten we het even zo tweaken dat het geen epileptische aanvallen of iets kunnen veroorzaken en wanneer het in de server geplaatst wordt, wellicht een mededeling ervoor uit te gooien!

### Wat lost deze feature op?

Mensen die niet meteen meer doorrijden na een crash.

**Comment by Attomn** [comment]
Script heb ik zojuist in de test server gezet en uitgetest, ziet er goed uit! Enige wat mooi zou zijn is, als je deze effecten hebt, de walking style injured geven als je uit stapt en loopt.

**Comment by Chang-nl** [comment]
Na de herstart is hij compleet goed ingesteld voor de mainserver. Bedankt voor het aanmaken van deze feature request.
