### ISSUE TITLE
[Bug]: Niet alle duffelbags werken bij een juwelier overval.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1411]
### Contact Details

Attom#3152

### Wat gebeurde er?

https://medal.tv/games/gta-v/clips/npAaEMGKOzAYc/d1337YWt9Rky?invite=cr-MSw5bTAsNDczNDM4MTEs

**Duffelbags** 
81
82
85
86

Werken allemaal niet bij het starten van een overval.

### Wat hoorde er te gebeuren?

Een juwelier overval hoorde te starten.

### Wat veroorzaakt de bug?

Een rugzak van het onderstaande lijstje pakken en een juwelier starten:
**Duffelbags** 
81
82
85
86

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

-

**Comment by Willem-Dekker** [comment]
staat klaar voor main zal er morgen in zitten
