### ISSUE TITLE
[FEATURE]: Kleding kast hernoemen 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1414]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In call werd er gezegd dat het mogelijk zou zijn, dus vandaar deze github:

Optie noemen/hernoemen van je kleding vanuit je kledingkast in je appartement.

Soms willen mensen hun outfit, evenals hun voertuig renamen in hun kledingkast of garage. Misschien een idee om een optie te maken waardoor je kleding kan hernoemen in je kledingkast.

### Wat lost deze feature op?

Kleding kunnen hernoemen een extra optie om iets aan te passen van je kleding.

**Comment by Attomn** [comment]
Overbodig extra werk voor een kleine feature wat bij de kledingwinkel ook kan.
