### ISSUE TITLE
[Bug]: Korporaals van de Kmar (KLU) kunnen geen heli's pakken

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1415]
### Contact Details

MickeyMorris#7393

### Wat gebeurde er?

(duplicaat aan #1220 maar werkt nog niet) Wanneer je naar een andere helipad gaat dan de legerbasis als korporaal van de Kmar(KLU), kun je niet zoals de KLU van de politie een helikopter pakken,

### Wat hoorde er te gebeuren?

Dat je net als de KLU van de politie de optie krijgt om daar de KLU heli's te pakken

graag toepassen voor rang kmar 80 en hoger

### Wat veroorzaakt de bug?

Waarschijnlijk niet geimplementeerd voor de kmar

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Streamcentralrulez** [comment]
Als het goed is de rangen KMAR 81,82,83,84

**Comment by Willem-Dekker** [comment]
sou gefixed moeten zijn

**Comment by Chang-nl** [comment]
Is dit al gefixed of nog niet niet?
