### ISSUE TITLE
[FEATURE]: Aanpassing snelverkoop drugs

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1416]
### Contact Details

Misterm#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel roteren de snelverkoop locaties op basis van het verkopen van zakjes. 
Doordat hij verplaatst na het verkopen van een x aantal zakjes is het verkopen in grote groepen, wat veel gangs graag doen, niet echt meer mogelijk. Tijdens de burgerraad is besproken om de snelverkoop locaties niet te laten veranderen na de verkoop van x zakjes. Maar om deze per dag te veranderen.

Wat moet er gebeuren:

- [ ] Locaties niet laten veranderen nadat er een x aantal zakjes is verkocht
- [ ] Locaties veranderen om de 4 uur
- [ ] Nieuwe locaties toevoegen en de oude weghalen (Ik ga zelf locaties zoeken, dus indien deze nodig zijn mij pm'en svp)

### Wat lost deze feature op?

Meer mogelijkheden tot massa verkoop van gangs

**Comment by Chang-nl** [comment]
Hey @niekschoemaker, zou jij hier naar kunnen kijken?
