### ISSUE TITLE
[Bug]: Bij togglehud knippert chat af en toe tevoorschijn

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1419]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Soms ga je uit toggle hud zie clip: https://medal.tv/games/gta-v/clips/nJWDqQmxVxeWB/d1337ZbtFlIe?invite=cr-MSwyb2UsMzg0MzA5OTUs

### Wat hoorde er te gebeuren?

je hoort twitter niet te zien, maar soms bugged het.

### Wat veroorzaakt de bug?

https://medal.tv/games/gta-v/clips/nJWDqQmxVxeWB/d1337ZbtFlIe?invite=cr-MSwyb2UsMzg0MzA5OTUs

### Frequentie van de bug

1x per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Is gefixed
