### ISSUE TITLE
[Bug]: Met niet storen modus worden anonieme telefoonnummers toch weergegeven

### ISSUE THREAD

**Issue by mamalois** [Tedeapolis/development#1420]
### Contact Details

MamaLois#9805

### Wat gebeurde er?

Als je jou telefoon op de niet storen modus zet en je word gebeld door een anoniem nummer, zie je linksonder WEL het telefoonnummer.

![unknown](https://user-images.githubusercontent.com/107127512/172638195-07ac0781-321d-4b7e-b271-b3c43941594a.png)

### Wat hoorde er te gebeuren?

Eerder stond hier niet het telefoon nummer linksonder. Nu kan je dus wel zien door wie je word gebeld.

### Wat veroorzaakt de bug?

- Zet niet storen modus aan
- Zorg dat je word gebeld door een anoniem nummer

### Frequentie van de bug

Altijd

**Comment by niekschoemaker** [comment]
Is gefixed
