### ISSUE TITLE
[FEATURE]: Geen schietmeldingen verkooplocaties

### ISSUE THREAD

**Issue by Joost010** [Tedeapolis/development#1421]
### Contact Details

Joost#8797

### Beschrijf zo duidelijk mogelijk de feature

Op pluklocaties krijgt de politie geen schietmeldingen dit zouden we ook graag zien bij verkooplocaties. Dit is tevens besproken in de burgerraad.

### Wat lost deze feature op?

Stimuleert crimineel VS crimineel op de verkooplocaties

**Comment by niekschoemaker** [comment]
> ### Contact Details
> 
> Joost#8797
> ### Beschrijf zo duidelijk mogelijk de feature
> 
> Op pluklocaties krijgt de politie geen schietmeldingen dit zouden we ook graag zien bij verkooplocaties. Dit is tevens besproken in de burgerraad.
> ### Wat lost deze feature op?
> 
> Stimuleert crimineel VS crimineel op de verkooplocaties

Om welke verkoop locaties gaat dit uberhaupt?

**Comment by Tijz** [comment]
Drugs quicksell locaties

> > ### Contact Details
> > Joost#8797
> > ### Beschrijf zo duidelijk mogelijk de feature
> > Op pluklocaties krijgt de politie geen schietmeldingen dit zouden we ook graag zien bij verkooplocaties. Dit is tevens besproken in de burgerraad.
> > ### Wat lost deze feature op?
> > Stimuleert crimineel VS crimineel op de verkooplocaties
> 
> Om welke verkoop locaties gaat dit uberhaupt?

**Comment by niekschoemaker** [comment]
Die staan sws al als low risk areas, dus daar is een hele kleine kans dat er uberhaupt een melding gemaakt wordt.

**Comment by Joost010** [comment]
> Drugs quicksell locaties
> 
> > > ### Contact Details
> > > Joost#8797
> > > ### Beschrijf zo duidelijk mogelijk de feature
> > > Op pluklocaties krijgt de politie geen schietmeldingen dit zouden we ook graag zien bij verkooplocaties. Dit is tevens besproken in de burgerraad.
> > > ### Wat lost deze feature op?
> > > Stimuleert crimineel VS crimineel op de verkooplocaties
> > 
> > 
> > Om welke verkoop locaties gaat dit uberhaupt?

Quicksells

**Comment by Attomn** [comment]
Schietmeldingen staan al op een super laag risico, kans is klein dat er een melding wordt gemaakt. Daarnaast is in het staff overleg toen besproken dat we ze niet volledig uit gaan zetten.
