### ISSUE TITLE
[FEATURE]: Knife toevoegen aan de eiland shop 

### ISSUE THREAD

**Issue by Joost010** [Tedeapolis/development#1422]
### Contact Details

Joost#8797

### Beschrijf zo duidelijk mogelijk de feature

knife toevoegen aan de wapen winkel op eiland, momenteel is er alleen een switchblade te koop. Dit is besproken tijdens de burgerraad van 8-6-2022

### Wat lost deze feature op?

Variatie tussen mesjes kunnen kopen op het eiland

**Comment by CalRayy** [comment]
Is goedgekeurd, prijs moet wel even goed afgestemd worden.

**Comment by niekschoemaker** [comment]
Zit erin.
