### ISSUE TITLE
[Bug]: KMAR Kustwachtboten

### ISSUE THREAD

**Issue by warturtlez** [Tedeapolis/development#1423]
### Contact Details

Johnny#8125

### Wat gebeurde er?

Als je als KMar een kustwacht boot pakt en op ''E'' drukt werken alleen de zwaailichten, de sirenes werken hierbij niet waardoor mensen niet door hebben dat ze achtervolgt worden.

### Wat hoorde er te gebeuren?

Als je als KMar een kustwacht boot pakt en op ''E'' drukt gaan de sirenes niet aan, de sirenes horen te werken net zoals de dienstvoertuigen op het land.

### Wat veroorzaakt de bug?

N.v.t.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
Is gefixed !
