### ISSUE TITLE
[Bug]: Telefoon en porto bug

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1424]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik zat rustig te bellen met een vriend en mijn naam werd in de porto geroepen, dus ik praat in de porto en vervolgens hoort de persoon bij de telefoon mij niet meer. Is het mogelijk om deze bug eruit te halen ?

### Wat hoorde er te gebeuren?

De persoon op de telefoon hoort je te horen nadat je in de porto hebt gepraat.

### Wat veroorzaakt de bug?

Als je in de porto praat wanneer je met iemand aan het bellen bent hoort de persoon waar je mee belt je niet meer.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Zou morgen gefixed moeten zijn
