### ISSUE TITLE
[Bug]: Voertuigen verdwijnen opeens

### ISSUE THREAD

**Issue by WinsEU** [Tedeapolis/development#1425]
### Contact Details

Wins#7732

### Wat gebeurde er?

Wanneer je bij PostNL over de weg rijd richting eclipse garage despawned je voertuig opeens op een bepaalde plek. Dit heb ik al 2x eerder meegemaakt en weet niet waar het aan kan liggen. (zie clip) https://www.youtube.com/watch?v=zTwRV09u2bs

### Wat hoorde er te gebeuren?

Dat je voertuig niet verdwijnt uit het niets.

### Wat veroorzaakt de bug?

Heb geen idee eerlijk gezegd.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by CalRayy** [comment]
> ### Contact Details
> Wins#7732
> 
> ### Wat gebeurde er?
> Wanneer je bij PostNL over de weg rijd richting eclipse garage despawned je voertuig opeens op een bepaalde plek. Dit heb ik al 2x eerder meegemaakt en weet niet waar het aan kan liggen. (zie clip) https://www.youtube.com/watch?v=zTwRV09u2bs
> 
> ### Wat hoorde er te gebeuren?
> Dat je voertuig niet verdwijnt uit het niets.
> 
> ### Wat veroorzaakt de bug?
> Heb geen idee eerlijk gezegd.
> 
> ### Frequentie van de bug
> Meerdere keren per dag
> 
> ### Wat is de impact van deze bug?
> laag
> 
> ### Relevante log bestanden
> _No response_

Dit is als het goed is al gefixt @WinsEU 😄

**Comment by WinsEU** [comment]
Raar maar echter is het niet altijd 1x op een dag random rijd er soms 4-5x per dag

**Comment by niekschoemaker** [comment]
> Raar maar echter is het niet altijd 1x op een dag random rijd er soms 4-5x per dag

Dit is 1 dag lang een issue geweest op 5 juni, datum van de video dus, ik weet niet of het daarna nog gebeurd is?
Ik had ff een dag lang expres alle voertuigen die "invalid" waren verwijderd laten worden zodat ik duidelijk had welke voertuigen en waarom voertuigen precies despawnden, dus was puur om even te veroorzaken dat er meldingen van gemaakt werden.

maar als dit nog steeds gebeurt dan graag even vermelden.

**Comment by WinsEU** [comment]
Voor zover is het opgelost man, erg bedankt!
