### ISSUE TITLE
[Bug]: Seasparrow bug 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1426]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik probeerde in te stappen bij een seasparrow alleen doet hij een rare animatie waardoor je bijna dood gaat. (zie clip: https://medal.tv/games/gta-v/clips/nRC4lpAH7xAMz/d1337jd9mqP4?invite=cr-MSw0cE4sMTgwOTQwMjQs )

### Wat hoorde er te gebeuren?

Je hoort niet die opstap te doen en dood te gaan of dergelijke.

### Wat veroorzaakt de bug?

Ik denk persoonlijk als je crouched en instapt dan gebeurd dit maar ben niet zeker. (zie clip: https://medal.tv/games/gta-v/clips/nRC4lpAH7xAMz/d1337jd9mqP4?invite=cr-MSw0cE4sMTgwOTQwMjQs)

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by niekschoemaker** [comment]
Crouchen lijkt het niet te veroorzaken, dus als je iets specifieker kunt zijn met testen enzo dan kan ik er wellicht iets mee

**Comment by CalRayy** [comment]
Ik weet niet hoe dit gebeurd, maar heb nog een video over deze bug gevonden misschien dat dit het helder maakt ? https://youtu.be/y29SntfkRU4

**Comment by niekschoemaker** [comment]
Gebeurt dit misschien doordat een voertuig op slot wordt gezet tijdens het instappen?

**Comment by CalRayy** [comment]
> Gebeurt dit misschien doordat een voertuig op slot wordt gezet tijdens het instappen?

Ik denk het wel, zie namelijk twee video's waar de voertuig op slot zit: 
https://www.youtube.com/watch?v=jn3GWi--fcA
https://www.youtube.com/watch?v=l5eT6xSKV-A
