### ISSUE TITLE
[FEATURE]: Kleding cirkel voor TOS

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1427]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Een kleding cirkel net zoals bij basic fat, maar dan in de TOS gebouw. Dit zou super handig voor de medewerkers binnen TOS aangezien je dan niet helemaal naar basic fat of je appartement gaan voor te gaan omkleden. 

Graag zou ik de cirkel op deze coords hebben:

X: -584.44 Y: -938.84 Z: 23.87

### Wat lost deze feature op?

Stel je ziet iets wat een krantenartikel waardig is dat je niet heel snel naar basic fat moet gaan en dan naar de TOS gebouw voor de busje te gaan halen.

**Comment by brothasx** [comment]
Bij de volgende Github push zit deze in de main.
