### ISSUE TITLE
[FEATURE]: Helipads spawnlocatie

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1428]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Momenteel is er maar 1 spawn locatie voor helikopter bij helipads en die zit bijna wel altijd bezet met kapotte helikopters waardoor staff leden worden geroepen. Mij leek het handig om meer spawnlocaties te crëeren zodat we dit kunnen vermijden.

Zie coords: 

X: -721.90 Y: -1472.68 Z: 5.00
X: -762.04 Y: -1454.05 Z: 5.00
X: -745.86 Y: -1433.71 Z: 5.00

### Wat lost deze feature op?

Minder reports omtrent helikopters die kapot zijn op de enige spawnlocatie bij helipads. Meer spawnlocatie's lijkt me altijd handig 😄

**Comment by brothasx** [comment]
deze functie van meerdere spawnlocations moet nog eerst toegevoegd worden aan de plugin, dan kan er extra spawnlocaties toegevoegd worden.

**Comment by niekschoemaker** [comment]
Zit erin.
