### ISSUE TITLE
[Bug]: Schietmeldingen komen niet meer binnen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1430]
### Contact Details

Arjen#0001

### Wat gebeurde er?

De politie krijgt geen schietmeldingen meer binnen.

### Wat hoorde er te gebeuren?

Politie hoort wel schietmeldingen binnen te krijgen.

### Wat veroorzaakt de bug?

Onbekend, als je in dienst bent krijg je simpelweg nooit een schietmelding binnen. Kan helaas niet meer informatie hiervoor krijgen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed na restart
