### ISSUE TITLE
[FEATURE]: Gevangenis Roleplay 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1431]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

**Werken in de gevangenis:**
Bij elke job wat geld ontvangen, ongeveer de helft van een normale UWV job. Dit krijg je in contant uitbetaald. 

- Wasruimte kijken of daar een mogelijkheid is om te werken ( Emote strijken, was in de wasmachine etc ) 

- Kantinedienst draaien het zelf bevoorraden van eten/drinken in de gevangenis, tafels schoonmaken, keuken schoonmaken. 

- Cellen schoonmaken.

- Buiten de elektriciteit kunnen doen. 

**Elk succesvolle uitvoering van je shift is 0.30 seconden per gewerkte minuut vermindering.** 

**Items in de gevangenis:**
Bepaalde items kunnen krijgen in de gevangenis zodat het ook motiverend is om te werken in de gevangenis omdat je een ‘’uitweg’’ kunt krijgen. 

- 3% kans om een Lockpick te krijgen uit de job die je uitvoert.(Onder de tafel zat een lockpick geplakt, of je hebt een lockpick gevonden tussen de was, of in de cel wat je hebt schoongemaakt) De lockpick zorgt ervoor dat je EEN DEUR kan openen. De deur gaat weer dicht na 15 minuten.

- Een NPC ( Cirkel ) waar je met contant illegaal voor 20/25k een telefoon kan kopen. Kan alleen contant. 
Dit zorgt ervoor dat mensen gaan samenwerken met het geld wat ze hebben zodat ze gezamenlijk contact kunnen leggen met de buitenwereld. 

- 0,5% kans om een mesje te vinden, extreem rare. Dit zorgt voor ook gevangenis RP en ook voor de KMar regelmatig controleren. ( Zogenaamde smokkel ) 

### Wat lost deze feature op?

Bovenstaande is al voldoening qua antwoord.
Dit is besproken tijdens staffoverleg en doorgezet als Github.

**Comment by Chang-nl** [comment]
300 milliseconden tijd vermindering na een shift? Klopt dit?

**Comment by Chang-nl** [comment]
En hadden jullie een idee voor wat voor animaties jullie willen?

**Comment by Chang-nl** [comment]
> En hadden jullie een idee voor wat voor animaties jullie willen?

@Vayenn

**Comment by iHax0rMC** [comment]
> 300 milliseconden tijd vermindering na een shift? Klopt dit?

Dit is correct.

> En hadden jullie een idee voor wat voor animaties jullie willen?

Strijken: /e strijken
Tafels schoonmaken: /e spons
Cellen schoonmaken: /e janitor
Elektriciteitskast maken: /e mechanic3

Neem deze issue wel op me.

**Comment by Chang-nl** [comment]
Dank, yes ik zal zodra ik weer terug ben gaan kijken naar die animaties en mogelijke implementatie. Bedankt voor het uitzoeken van de animaties😅

**Comment by Chang-nl** [comment]
300 milliseconden tijdsvermindering lijkt mij een beetje weinig als je een shift voltooid. Dat zou bijna hetzelfde zijn als geen tijdsvermindering toch?

**Comment by iHax0rMC** [comment]
> 

Mmh moeten we even denken wat reëel is, hoe lang zal de job duren? Daarbij hoe vaak we hem kunnen uitvoeren? Dan kunnen we daarop misschien een mooie reële tijd bedenken.

**Comment by Ljosfari** [comment]
word een nieuwe issue
