### ISSUE TITLE
[Bug]: Garage deur sloten van Narcos kapot

### ISSUE THREAD

**Issue by AntonMTDA** [Tedeapolis/development#1434]
### Contact Details

AntonMoskvin#3144

### Wat gebeurde er?

Als je de garage deur open doet bij narcos verdwijnt vaak het slot en/of gaat die niet open. Soms zie je helemaal geen slot

https://prnt.sc/vufWkoBO1U-m

https://user-images.githubusercontent.com/36623846/173418218-b3b73776-7964-4b77-95b2-cdfb16923ee6.mp4

### Wat hoorde er te gebeuren?

Je hoort de garage deur normaal open te kunnen doen zonder dat het slot continu verdwijnt

### Wat veroorzaakt de bug?

Rij naar de garage deuren. Doe hem open en het slot zal verdwijnen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
> ### Contact Details
> 
> AntonMoskvin#3144
> ### Wat gebeurde er?
> 
> Als je de garage deur open doet bij narcos verdwijnt vaak het slot en/of gaat die niet open. Soms zie je helemaal geen slot
> 
> https://prnt.sc/vufWkoBO1U-m
> Desktop_2022.06.01_-_02.45.23.06.DVR_Trim.mp4
> ### Wat hoorde er te gebeuren?
> 
> Je hoort de garage deur normaal open te kunnen doen zonder dat het slot continu verdwijnt
> ### Wat veroorzaakt de bug?
> 
> Rij naar de garage deuren. Doe hem open en het slot zal verdwijnen
> ### Frequentie van de bug
> 
> Altijd
> ### Wat is de impact van deze bug?
> 
> hoog
> ### Relevante log bestanden
> 
> _No response_

Ik zie op die video niks verkeerd gaan?

**Comment by nickdb04** [comment]
Hoi Niek, ik zal het probleem even uitleggen, als wij de deuren open doen verdwijnt het slot vaak en kunnen wij vervolgens de deuren niet meer dicht doen. Als we dan stuk weg rijden wil het slot soms wel soms niet terugkomen.

**Comment by nickdb04** [comment]
https://prnt.sc/1HuYK7TIkH9J
https://youtu.be/GC5oVaAS588

Hier een filmpje van het probleem

**Comment by niekschoemaker** [comment]
Ik heb wat dingen aangepast, weet niet zeker of dit het fixed maar lijkt wel iets beter te werken nu.

**Comment by nickdb04** [comment]
Probleem is nog steeds niet gefixed. Je kan hem opslot zetten maar sloten verdwijnen weer en de deur gaat verder open ook al staat die op slot

**Comment by nickdb04** [comment]
Wat er vaak ook gebeurt is dat de deur open gaat maar dat er een soort van fake door blijft zitten
