### ISSUE TITLE
[Bug]: Safezone Icon niet meer te zien in-game

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1435]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Het ''schildje'' wat aangeeft dat je in een safezone bent, is niet meer zichtbaar in je scherm in-game wanneer je in een safezone staat.

### Wat hoorde er te gebeuren?

Die hoort links onderin te staan, zodat je weet dat je in een safezone zit.

### Wat veroorzaakt de bug?

N.v.t.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
