### ISSUE TITLE
[Bug]: TOS Cirkel iets te hoog

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1436]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De cirkel die sindskort is geplaatst in de TOS gebouw is iets te hoog geplaatst, zie screenshot .
![image](https://user-images.githubusercontent.com/101106299/173583900-d38d4ce4-e1a8-490e-b9d9-7e73661b85ef.png)
Is het mogelijk om dit iets lager te zetten?

### Wat hoorde er te gebeuren?

De cirkel moet iets naar onder zijn.

### Wat veroorzaakt de bug?

n.v.t.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Willem-Dekker** [comment]
wat zijn de coords hier van? en welke actie moet deze circle doen?

**Comment by CalRayy** [comment]
> wat zijn de coords hier van? en welke actie moet deze circle doen?

Het is een kleding cirkel op deze coords: X: -584.44 Y: -938.84 Z: 23.87
volgens Kenneth moet de Z eentje lager i.v.m. dat hij de coords pakt van je lichaam.

**Comment by niekschoemaker** [comment]
Is gefixed
