### ISSUE TITLE
[Bug]: Recoil in helicopter gaat alle kanten op behalve de goede kant

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1437]
### Contact Details

KeesdB#1477

### Wat gebeurde er?

Als je vanuit een heli schiet met een pistol dan beweegt je karakter ingezoomd volledig naar de andere kant, dus wat er achter je gebeurd. Dit zorgt er voor dat je niet kan schieten vanuit de heli, of dit ook is met automatische vuurwapens is niet bekend, maar met een pistol gebeurd dit. Zie video

https://user-images.githubusercontent.com/106243778/173616940-bc2069be-ce73-421c-ab8b-cff0bbfd6687.mp4

### Wat hoorde er te gebeuren?

Dat je je wel recoil hebt, maar niet zo extreem, je hoort wel gewoon in hetzelfde gebied te blijven kijken

### Wat veroorzaakt de bug?

Recoil wat bugged / verkeerd is afgesteld.
Je kan dit zelf testen door in een heli te gaan zitten en te schieten met een pistol

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

Hoog (schieten uit een heli is op deze manier niet mogeijk)

**Comment by niekschoemaker** [comment]
Is gefixed
