### ISSUE TITLE
[Bug]: Aanhanger garage paleto 

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1438]
### Contact Details

Misterm#0001

### Wat gebeurde er?

Graag het spawnpunt van aanhangers in Paleto (Noorden) iets verplaatsen. Vrachtwagen aanhangers spawnen nu op een voorwerp wat op de grond ligt.

![image](https://user-images.githubusercontent.com/72617118/173688806-03dfe417-9cd3-400d-b6c3-8b499d627e5e.png)

### Wat hoorde er te gebeuren?

Ze zouden gewoon normaal moeten spawnen 

### Wat veroorzaakt de bug?

Misplaatste spawnpoint

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Is gefixed
