### ISSUE TITLE
[FEATURE]: Mogelijkheid om te trainen met de apparaten bij het strand

### ISSUE THREAD

**Issue by jaim1114** [Tedeapolis/development#1440]
### Beschrijf zo duidelijk mogelijk de feature

Bij het strand is een locatie met verschillende gym-apparaten. Het is helaas niet mogelijk om hier te trainen, wat best zonde is aangezien dit op een best mooie locatie is en het super relaxed is op een zonnige dag. Het zou een mooie aanvulling zijn op de basic-fat, aangezien deze locatie aan de andere kant van de stad ligt.

Foto's van de locatie:
https://i.imgur.com/P7lrAql.jpeg
https://i.imgur.com/XYC1OB2.png

**Comment by Willem-Dekker** [comment]
dit is er uitgehaald ivm de basic-fat hierom zullen ze ook niet terug keren naar het strand
