### ISSUE TITLE
[FEATURE]: Humvees toevoegen aan kmar dealer

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1441]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Graag willen wij de volgende auto's (humvees) laten toeveogen voor kmar : 

/car unarmed
/car armed

Dit graag voor de volgende rangen:
Kmar 80
Kmar 81
Kmar 82
Kmar 83
Kmar 90
Kmar 95
Kmar 100

### Wat lost deze feature op?

Voegt de humvees toe voor bepaalde rangen aan de voertuig dealer van de kmar

**Comment by niekschoemaker** [comment]
Zit erin.
