### ISSUE TITLE
[Bug]: Wapen blijft op rug na wegleggen

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1443]
### Contact Details

Bas#6430

### Wat gebeurde er?

Het gebeurd enorm vaak dat een wapen op de rug blijft zitten nadat het wapen weggelegd is. De redenen zijn onbekend.
https://www.youtube.com/watch?v=aQ4VLzMvYwY

### Wat hoorde er te gebeuren?

Het wapen hoort van je rug te gaan als je het wapen niet meer in je inventory hebt.

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn
