### ISSUE TITLE
[Bug]: Testserver niet joinbaar

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1444]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Wanneer men de testserver probeert te joinen blijft de introvideo oneindig doorgaan en laadt men uiteindelijk alsnog niet in.
Zo ver ik heb vernomen hebben meerdere mensen hier last van, maar niet iedereen aangezien er ook mensen in de server zitten. Bij de mainserver vormt zich geen probleem.

### Wat hoorde er te gebeuren?

Na het laden dient men normaal gesproken de server te betreden, meestal voordat de video afgelopen is. 

### Wat veroorzaakt de bug?

Onbekend, mogelijk esx_juwelier (zie screenshot)

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Ditzelfde bericht komt elke keer in F8 te staan (althans bij mij, onbekend wat bij anderen in F8 staat): https://i.imgur.com/zW5X6S9.png

Edit: andere mensen krijgen precies dezelfde foutcode: https://media.discordapp.net/attachments/987349726758334505/987349884254445568/tda_test_stad.PNG?width=1439&height=631

**Comment by Willem-Dekker** [comment]
fixed door @brothasx
