### ISSUE TITLE
[Bug]: Voertuig respawned hersenloos.

### ISSUE THREAD

**Issue by WinsEU** [Tedeapolis/development#1445]
### Contact Details

Wins#7732

### Wat gebeurde er?

Op het moment dat je met een mule aankomt of uberhaut een voertuig en je gaat een appartement in of een loods en je gaat naar buiten bug je mule truck en na 5 seconden despawned hij en spawn hij hersenloos terug. 

Zie Video.
https://youtu.be/W4N3VqNvUM0

### Wat hoorde er te gebeuren?

Dat de mule na het verlaten van een appartement/loods niet despawned.

### Wat veroorzaakt de bug?

Heb eerlijk gezegd geen idee.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Hier de fout error.
![2022-06-17_19h19_14](https://user-images.githubusercontent.com/104858065/174354836-88a0c25b-c029-4239-906d-685a7736abfa.png)

**Comment by Attomn** [comment]
Hoi Wins,

Zou jij met deze error een paar log bestanden kunnen sturen? In je bovenstaande F8 error staan geen errors die gerelateerd zijn aan het boven beschreven probleem.

**Comment by Attomn** [comment]
Geen reactie.
