### ISSUE TITLE
[Bug]: Test stad tijdstip klopt niet (rechtsboven)

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1446]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De tijdstip en datum die rechtsboven kan zien klopt niet (alleen de datum).

### Wat hoorde er te gebeuren?

de tijd hoort correct te zijn.

### Wat veroorzaakt de bug?

de tijdstip is een uur terug in de tijd, dus er moet een uur naar voren gezet worden

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by jaim1114** [comment]
Is het echt noodzakelijk om dit aan te passen? Het is wel fijn om tijdens de restart van 2 uur even op de testserver te kunnen spelen aangezien deze nu om 3 uur snachts restart.
