### ISSUE TITLE
[Bug]: Noodknop Politie en KMar functioneren niet meer + F6 menu 

### ISSUE THREAD

**Issue by mrcrypticrage** [Tedeapolis/development#1447]
### Contact Details

mrcrypticrage#2994

### Wat gebeurde er?

Wanneer politie/KMar de noodknop indrukt verschijnt er een melding dat de noodknop is verzonden, echter de daadwerkelijke noodmelding wordt niet gemaakt en verschijnt bij niemand in het scherm. Als reactie hierop is ons F6 menu ook ?uitgeschakeld? en dient men te gaan knipperen om deze functie weer terug te krijgen. De noodknop blijft gebugd.
![image](https://user-images.githubusercontent.com/107763992/174447083-4a18f4aa-35bf-43d2-b49a-0de78df865ee.png)

### Wat hoorde er te gebeuren?

De noodknop hoorde geactiveerd te worden en op de map zichtbaar te worden en het F6 menu behoorde te blijven functioneren.

### Wat veroorzaakt de bug?

1. Activering van noodknop ( shift en F9)

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is dit iets wat al langer gaande is of alleen  vandaag? En nu sinds de laatste restart nog steeds?

**Comment by mrcrypticrage** [comment]
Hey Niek!

Dit probleem ontstond eergisterennacht, als ik mij niet vergis nadat de
schiet% werden gecorrigeerd. Ik ben vannacht niet online geweest, dus zou
niet weten of het nog steeds plaatsvindt. Ik zal vanavond even kijken of
alles weer functioneert naar behoren :)

Gr. John


Op za 18 jun. 2022 om 20:55 schreef Niek ***@***.***>:

**Comment by ARJ3N** [comment]
@niekschoemaker net getest maar ze werken momenteel nog niet.
