### ISSUE TITLE
[Bug]: CBR verdwenen/ rijbewijzen hebben geen type / Vliegbrevetten hebben geen type

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#1448]
### Contact Details

Hellfire

### Wat gebeurde er?

Het hele cbr is weg en nu kunnen mensen geen rijbewijs meer halen.
Daarnaast zijn alle types weg om de rijbewijzen/brevetten

### Wat hoorde er te gebeuren?

Dat het er wel is :P 

### Wat veroorzaakt de bug?

Dat er geen rijbewijzen kunnen worden gehaald + dat er boetes worden gegeven voor het rijden zonder

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

-

**Comment by Hellie94** [comment]
![image](https://user-images.githubusercontent.com/77858957/174471757-5490e55a-780e-4726-a2ac-272b6ac31922.png)
![image](https://user-images.githubusercontent.com/77858957/174471777-730ba53b-e870-48a0-abeb-b0090b18f530.png)

**Comment by Hellie94** [comment]
![image](https://user-images.githubusercontent.com/77858957/174471793-ad06eb36-35c5-4da9-9109-9ff34ca2ec8f.png)

**Comment by niekschoemaker** [comment]
Is gefixed na volgende restart
