### ISSUE TITLE
[FEATURE]: Jailmenu aan het F6 menu toevoegen (staff) 

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1450]
### Contact Details

Yohandessu#3314

### Beschrijf zo duidelijk mogelijk de feature

Jailmenu aan F6 menu toevoegen voor staff, zo kunnen wij als staffleden zien wie er in de jail zitten en wie niet meer. Aangezien ik vaak reports voorbij zie komen dat personen nog in de gevangenis zitten maar de tijd wel om is leek het mij een handige feature! 

### Wat lost deze feature op?

Er komen vaak reports binnen van personen die nog in de gevangenis zitten terwijl de tijd om is. Als wij het jaimenu hebben kunnen wij zien of dit echt zo is. Als dit echt zo is kunnen wij personen vrijlaten.

**Comment by Chang-nl** [comment]
Na herstart gefixt!
