### ISSUE TITLE
[FEATURE]: Rijbewijs/ID kaart vanuit auto kunnen geven

### ISSUE THREAD

**Issue by Enrico14k** [Tedeapolis/development#1451]
### Contact Details

Enrico#4089

### Beschrijf zo duidelijk mogelijk de feature

Ik had hier een burgerraad puntje voor aangemaakt, er is daar besproken om er een github van aan te maken.
Voorheen kon je al een keer pasjes geven vanuit de auto alleen is dat nu helaas niet meer mogelijk.

- [ ] Mogelijk maken dat pasjes (Rijbewijs / ID kaart) vanuit de auto naar buiten kunnen worden gegeven.

### Wat lost deze feature op?

Dit voorkomt hopelijk dat criminelen voor simpele staandehoudingen (wat zij vaak niet kunnen weten), niet voor de optie gaan om gelijk politie onder schot te houden, en/of om te leggen. 
Vaak kan je ook niet uitstappen als je een wapen op je rug hebt zonder het bovenstaande te doen, hopelijk wordt dat hierdoor vermindert.

**Comment by niekschoemaker** [comment]
Is gefixed
