### ISSUE TITLE
[FEATURE]: Witwasdeep veranderen tussen de 7 en 14 dagen (burgerraad)

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1452]
### Contact Details

maxjuh97#7233 | MyNqme#9209

### Beschrijf zo duidelijk mogelijk de feature

Kleine aanpassing doen aan het veranderen van de deepweb elke 2 weken. Zorgen dat de deepweb tussen de 7 en 14 dagen veranderd, in plaats van de standaard (2 weken als ik het goed zeg). Nu kun je weten wanneer de deepweb veranderd is en dus van te voren hier al op kunnen anticiperen.

Dus in plaats van een standaard aantal dagen, zorgen dat de deepweb veranderd ergens random tussenin de 7 en 14 dagen. Uiteindelijk zal bijvoorbeeld de 1e keer de deepweb veranderen na 8 dagen en daarna na 11 dagen enzovoorts.

### Wat lost deze feature op?

Powergaming omtrent het weten wanneer de deepweb voor witwassers veranderd is

**Comment by Chang-nl** [comment]
De logica is aangepast!

**Comment by Tom974** [comment]
> De logica is aangepast!

Volgensmij werkt het nog niet helemaal goed, de deepweb is namelijk nogsteeds hetzelfde (na 17-18 dagen)
