### ISSUE TITLE
[Bug]: Politie/KMAR/Staff problemen in F6 menu (Meer informatie in Bug report)

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1453]
### Contact Details

KeesdB#1477

### Wat gebeurde er?

Politie, KMAR en Staff kan niet meer personen via het f6 menu in het voertuig plaatsen, de optie ervoor is er wel, maar deze werkt niet. Gevolg dat niemand geboeid in een voertuig kan worden geplaatst maar dat een persoon zelf via /e geboeid in een voertuig moet gaan zitten wat de RP natuurlijk niet bevorderd en wat kan zorgen voor vreemde fratsen.

F6 menu bij voertuig interactie is ook leger dan normaal, hier ontbreekt de knop confisqueren, boete op kenteken uitschrijven en voertuig informatie werkt niet (er komt geen naam/kenteken te staan). Als een voertuig dus geen kenteken heeft dan kunnen we dit ook niet meer 
![f6 menu voertuig](https://user-images.githubusercontent.com/106243778/174974494-2a9df9ab-e3a1-4f4a-bed9-1670f5c88153.PNG)

Clip van wat er allemaal niet werkt: https://medal.tv/games/gta-v/clips/ppaxEPHpXedmF/d1337oDmzVMp?invite=cr-MSxuZjcsNjkxMTkwMDUs

### Wat hoorde er te gebeuren?

Politie, KMAR en Staff horen gewoon personen die geboeid zijn te kunnen plaatsen in het voertuig. Dit werkt nu niet.

Politie, KMAR en Staff kunnen door het chassisnummer te achterhalen in RP alsnog een kenteken achterhalen via de knop voertuig informatie, dit werkt niet. Tevens kunnen er nu geen voertuigen worden geconfisqueerd als dat echt niet anders kan of boetes op kenteken worden uitgeschreven (behalve via MEOS).

### Wat veroorzaakt de bug?

Het menu is leger dus er zijn dingen weggevallen, niet werkend of niet zichtbaar.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

![Log in voertuig plaatsen mislukt](https://user-images.githubusercontent.com/106243778/174976029-97c08a4a-7c03-4ce6-8ac1-e5d047b70543.PNG)

**Comment by niekschoemaker** [comment]
Is gefixed na restart
