### ISSUE TITLE
[FEATURE]: Kmar skin voor B klasse

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1456]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Bij de kmar heeft iemand een mooie skin gemaakt voor de huidige B klasse. Deze zouden wij graag willen implementeren. 

De files zijn hier te vinden (kreeg ze niet attached aan deze feature)
https://www.mediafire.com/folder/bd54lnxpczr1w/b_klasse

### Wat lost deze feature op?

Een nieuwe skin voor de B klasse

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/178001832-8ed4104d-9e46-4418-b474-9c4c9f4a496f.png)
Niet zo'n mooie skin? 🤔

**Comment by Attomn** [comment]
KMAR heeft geen B klasse zo ver ik kan zien trouwens...

**Comment by walvisgedaan** [comment]
De marechaussee heeft inderdaad geen B-Klasse. Er komt een kmar Opel Astra aan ipv een b klasse

**Comment by dilyano** [comment]
> De marechaussee heeft inderdaad geen B-Klasse. Er komt een kmar Opel Astra aan ipv een b klasse

Nice!
