### ISSUE TITLE
[FEATURE]: Een anker en sirene op de KMAR SMALLBOAT

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1457]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Momenteel zit er geen anker en geen sirene op de RHIB. Dit houdt in dat als je met de kustwacht overstapt naar een andere boot of in het water moet springen voor een situatie, dat je boot wegdrijft.

### Wat lost deze feature op?

Dat de kustwacht neit meer eindeloos achter zijn/haar boot aan moet zwemmen

**Comment by Chang-nl** [comment]
Anker zit op het voertuig els nog niet

**Comment by Attomn** [comment]
Beiden zitten nu op het voertuig!
