### ISSUE TITLE
[FEATURE]: KMAR sleepwagen kofferbak verhogen

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1458]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

De politie sleepwagen bevat een kofferbak ruimte van 1000kg. De kmar sleepwagen echter maar 130. Graag zouden wij deze verhoogt zien omdat deze ook beschikt over veel laadruimte

### Wat lost deze feature op?

Het niet eindeloos hoeven legen van de sleepwagen in een situatie.

**Comment by Chang-nl** [comment]
Na herstart Gefiixt!
