### ISSUE TITLE
[FEATURE]: Een rugzak voor de kmar

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1459]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Momenteel zit er geen rugzak in de eup.
Wanneer we nu iemand treffen waarvan we goederen meoten afnemen en je trekt een rugzak aan, verdwijnt je kmar kleding en heb je je prive kleding aan. een idee is om een karretje of rugzak aan de eup toe te voegen om deze te kunnen pakken wanneer spullen afgepkat of overgepakt moeten worden

### Wat lost deze feature op?

Dat je neit heel je uitrusting hoeft te droppen en je prie kleding aan hoeft te doen om een paar goederen in beslag te nemen

**Comment by MisterM02** [comment]
Tassen zijn gemaakt en in de eup gezet. Even wachten totdat deze in de main worden geplaatst.
