### ISSUE TITLE
Limiet op hoeveel wapens bende's maandelijks kunnen inkopen

### ISSUE THREAD

**Issue by Nander0320** [Tedeapolis/development#146]
Een maandelijks limiet of wekelijks limiet per bende over hoeveel wapens ze kunnen kopen.

Loopt momenteel beetje uit de hand. 

Ongv 54 ak's 
194 pistolen ezv in de server momenteel

Kortom elke idioot kan momenteel zeer gemakkelijk aan wapens komen maak ze iets zeldzamer dan hoeven de prijzen ook niet enorm hoog :)

**Comment by niekschoemaker** [comment]
Is effectief in dev server, meer overleg nodig om exacte limieten etc concreet te krijgen.
