### ISSUE TITLE
[FEATURE]: Mogelijkheid tot uitschakelen ANPR meldingen Kmar

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1460]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

Aangezien de kmar geen taken uitvoerd als de wegenverkeerswet, is het handig om de ANPR uit te kunnen zetten. Het verstoft namelijk het zien van andere meldingen in de gewone apps omdat je na een paar minuten je telefoon gaat negeren door de anpr meldingen. Deze komen soms wel tot 40 keer per minuut voorbij.

### Wat lost deze feature op?

Onnodig spammen van kmar leden verdwijnt

**Comment by Chang-nl** [comment]
Zit erin na herstart!

**Comment by MisterM02** [comment]
Er zit nog een kleine fout in de message die je krijgt als je /toggle_anpr_sound gebruikt.

**Comment by MisterM02** [comment]
![image](https://user-images.githubusercontent.com/72617118/176926092-80509fac-8449-4022-9b04-65d8178141d7.png)
![image](https://user-images.githubusercontent.com/72617118/176926097-3b920909-dc93-44a1-bbb8-01b2b13a40e3.png)

**Comment by Chang-nl** [comment]
Fix staat klaar, lekker slim colour codes in html gooien
