### ISSUE TITLE
[Bug]: Tanken zonder contant geld

### ISSUE THREAD

**Issue by jeffdv** [Tedeapolis/development#1461]
### Contact Details

Jeffrey#0734

### Wat gebeurde er?

Ik wilde tanken terwijl ik geen contant geld bij mij had. Ik heb contant geld gepint en vervolgens getankt. Het bedrag werd van mijn rekening afgeschreven, dus had ik eigenlijk helemaal geen contant geld nodig.

### Wat hoorde er te gebeuren?

Je hoort te kunnen tanken, ook al heb je geen contant geld bij je. Dit aangezien het bedrag van je rekening wordt afgeschreven

### Wat veroorzaakt de bug?

n.v.t

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t

**Comment by niekschoemaker** [comment]
Is gefixed na volgende herstart
