### ISSUE TITLE
[Bug]: Put in vehicle werkt niet als iemand geboeid is

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1462]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als een persoon geboeid is kan je degene niet in een voertuig zetten.

### Wat hoorde er te gebeuren?

je hoort hem in het voertuig te zetten. 

### Wat veroorzaakt de bug?

persoon moet geontboeid worden om hem in het voertuig te zetten, normaal hoor je ze geboeid in het voertuig te kunnen doen via f6 menu.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by ARJ3N** [comment]
Duplicate van #1453
