### ISSUE TITLE
[Bug]: Maze Bank garage

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#1463]
### Wat gebeurde er?

Wanneer je het kenteken aanpast van een voertuig die in de mazebank garage staat dan is het voertuig niet meer zichtbaar in de garage en ook niet in het menu maar het voertuig blijft wel nog met het oude kenteken in de database staan waardoor deze alsnog 1 spot inneemt.

### Frequentie van de bug

Altijd

### Relevante log bestanden

![unknown](https://user-images.githubusercontent.com/93911282/175374030-435a49dc-880a-4dcd-a921-b0230cb969fa.png)
![unknown2](https://user-images.githubusercontent.com/93911282/175374054-c853cd99-67f1-4454-8fac-6f14b30ad81c.png)
![unknown1](https://user-images.githubusercontent.com/93911282/175374077-cc445650-365a-4988-b0e6-4188aad0388a.png)

**Comment by niekschoemaker** [comment]
is gefixed
