### ISSUE TITLE
[Bug]: Nieuwe handboeien voor onofficials, ontboeien werkt niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1465]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je iemand boeit en degene wilt terug ge ontboeid worden werkt het niet. Als degene de hele tijd stil staat of beweegt tijdens het geboeid zijn heeft geen effect hierop. 

### Wat hoorde er te gebeuren?

Je hoort normaal degene die jij geboeid hebt terug te kunnen ontboeien.

### Wat veroorzaakt de bug?

1. Je boeit iemand af.
2. Je houd E ingedrukt 
3. geeft geen output

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

f8 geeft niets aan, n.v.t.

**Comment by niekschoemaker** [comment]
Is gefixed als het goed is
