### ISSUE TITLE
[Bug]: Narcos 2 garage deuren buggen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1466]
### Contact Details

EpicTom#5874

### Wat gebeurde er?

Bij ons terrein zijn de 2 garage deuren gebugged wat je kan zien in het filmpje hieronder.

https://youtu.be/oDdRF8eFexQ

### Wat hoorde er te gebeuren?

Dat ze altijd gewoon opengaan en dat de sloten niet steeds weggaan

### Wat veroorzaakt de bug?

Dat de deuren soms niet open gaan en dat mensen er gewoon doorheen kunnen lopen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Duplicate of #1467

**Comment by EpicTomm** [comment]
Nee 1tje zijn de garage deuren en die andere is de poort begin van het terrein

**Comment by Attomn** [comment]
Heb het bekeken, ligt zover ik kan zien niet aan het slot maar aan het gebouw zelf. Lijkt alsof er dubbele props gespawned worden. Kenneth zet het even door naar Kobe.

**Comment by EpicTomm** [comment]
Word hier nog naar gekeken?
