### ISSUE TITLE
[Bug]: Narcos poort doet het niet goed

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1467]
### Contact Details

EpicTom#5874

### Wat gebeurde er?

Zoals je kan zien op het filmpje hier beneden gaat de poort 2 a 3x terug spawnen wat denk ik niet hoort. Dit is in de test stad gefixt alleen moet het dan wel overgezet worden naar de main stad.

https://youtu.be/HnJXz_zmOIk

### Wat hoorde er te gebeuren?

Dat de poort normaal open gaat en niet de hele tijd terug spawned en dat die langzaam dichtgaat. Dit is dus al in de test stad gefixt alleen moet het over gezet worden.

### Wat veroorzaakt de bug?

Dat mensen vast blijven hangen in de poorten en daardoor hun voertuig kapot gaat

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Attomn** [comment]
Heb het zojuist even bekeken, het zou nu gefixt moeten zijn en staat klaar in de test server.

**Comment by EpicTomm** [comment]
U bedoelt dat het klaar staat in de main stad?

**Comment by Attomn** [comment]
> 

Ik heb hem klaar staan in de test server en hij is gecommit naar de main server. Ik wacht enkel nog op Niek die hem merged. Vermoedelijk na de restart is de port gefixt in de main server.

**Comment by brothasx** [comment]
Bij volgende push word dit uitgevoerd
