### ISSUE TITLE
[BUG]: EHBO pasjes werken niet

### ISSUE THREAD

**Issue by TDABob** [Tedeapolis/development#1468]
Goeiedag,

Ik heb vernomen als de EHBO pasjes worden gegeven aan de burgers en ze drukken op gebruiken dat het daarna niet in hun portemonnee zit. Vervolgens gaan ze knipperen en hebben ze het alsnog niet in de portemonnee.

Voorheen was dit wel het geval hoe het werkte alleen nu is dat niet zou hierna gekeken kunnen worden dat het wel weer op die manier kan werken. Want dit is erg vervelend als er EHBO cursussen worden gegeven en daarna niks met die pas kunnen doen. 

Alvast bedankt,
Gr. Bob Bros van de ambulance

**Comment by niekschoemaker** [comment]
Is gefixed, mensen krijgen de ehbo pas wel, maar pas na de restart, deze issue is gefixed, maar mensen hebben de EHBO pas wel, dus is niks nodig qua refunden of extra acties.

**Comment by TDABob** [comment]
Top bedankt
