### ISSUE TITLE
Porto werkt niet voor iedereen

### ISSUE THREAD

**Issue by BartBoos** [Tedeapolis/development#147]
[CitizenFX_log_2020-09-02T123957.log](https://github.com/Tedeapolis/development/files/5167390/CitizenFX_log_2020-09-02T123957.log)
niet voor iedereen werkt die in game porto, dus ATC ook niet. als  je bijvoorbeeld in porto nummer 420 en je wilt praten hoor je de andere personen wel echter als je zelf wilt praten hoor je het geluid wat je normaal hoort als je de porto  aan  klikt niet. en je bent niet hoorbaar in de porto.

**Comment by niekschoemaker** [comment]
Dit is waarschijnlijk de rate limiter, je kunt binnen 2 seconden niet opnieuw de porto indrukken, zal ff kijken of ik hier een notificatie aan toe kan voegen.

**Comment by BartBoos** [comment]
het mooie  er van is dat ik  de andere wel kan horen en zij mij niet, heb echt al van alles geprobeerd  (meerdere mensen  hebben hier last  van). je  moet bij het praten in de  porto eerste 1 a 2 seconden  wachten voordat je gaat  schreeuwen, doen we  dat helpt ook niet.

**Comment by BartBoos** [comment]
Heb een fix gevonden wat voor mij heeft  gewerkt het even op een  andere toets zetten  en dan weer  terug en dan doet die het weer.

**Comment by Willem-Dekker** [comment]
fix is opgenomen in bekende problemen
