### ISSUE TITLE
[FEATURE]: Repareer optie timer en misschien hier een verplichte uitstap emote aan hangen (15-30 seconde timer)

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1470]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

- Besproken in STAFF overleg 26-06 

Op het moment kan je /repareer doen als je auto kapot is en je kan direct weer door, je gaat voor de ingang van de modshop staan, je typt /repareer en je gaat door. Dat is totaal niet realistisch en zorgt voor oneerlijke achtervolgingen en dergelijke. Als de ANWB ter plaatsen komt ben je ook al snel 15-30 seconde aan het wachten, dus ik zou dezelfde timer hier aan koppelen. Bijvoorbeeld door 15-30 in een cirkel te moeten blijven staan of dat je auto pas na 15-30 seconde wordt gemaakt (zelfde als bij de parkeerplaatsen, dat je een nieuwe auto kan pakken). Dit zorgt er vooral voor dat in achtervolging de communicatie goed moet zijn omdat je echt pas na 15-30 seconde opnieuw kan koppelen aan de achtervolging. Dit kan groot verschil zijn voor de persoon die achtervolgd wordt of hij weg komt of niet. Je zou zelfs nog er aan kunnen toevoegen dat er ook uitgestapt moet worden en bijvoorbeeld een emote er aan gehangen wordt zoals /mechanic, dat je ook echt iets aan je voertuig aan het doen ben (alsof het bijvoorbeeld een kleine storing is of zoals als je een reparatie kit gebruikt). Dat laatste is dan ook weer een risico voor een crimineel omdat hij dan ook daadwerkelijk moet uitstappen en mogelijk ook met een wapen op de rug of met een holster / armor om. Zodat er dus goed moet worden gekozen of je dit wapen bijvoorbeeld niet vooraf in de kofferbak legt, of dat je iemand anders laat uitstappen zonder wapen en dergelijke (vergelijkbare situatie als bij tanken). 

Welke tijd je hier aan wilt hangen en of er uitgestapt moet worden is aan Development.

### Wat lost deze feature op?

Onrealistisch gebruik van /repareer doordat je voertuig na 0 seconde al gemaakt is, je hoeft het letterlijk alleen te typen. Maakt achtervolgingen leuker en uitdagender.

**Comment by Chang-nl** [comment]
Gefixt, zit er binnenkort in!
