### ISSUE TITLE
[FEATURE]: Tickethelpers whitelisten voor plaatsen van links

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1471]
### Contact Details

Lamine#4904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens het HR-/HS-overleg is besproken dat tickethelpers toestemming krijgen om links te plaatsen in de support discord en de main discord. Dit zal aangepast moeten worden in de discord bot.

### Wat lost deze feature op?

Frustraties en problemen waardoor staffleden links moeten plaatsen voor tickethelpers.

**Comment by niekschoemaker** [comment]
Is geffixed
