### ISSUE TITLE
[FEATURE]: TAXI: Mogelijkheid om te zien van wie een taxivoertuig is

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1474]
### Contact Details

Geertje123#2163

### Beschrijf zo duidelijk mogelijk de feature

Dat wij bij een taxiauto kunnen zien wie deze auto uit de garage heeft gehaald. Bijvoorbeeld via het F6 menu, of een commando, of iets anders. De oplossing hoeft niet fancy te zijn, we hoeven alleen de naam en bijvoorbeeld het telefoonnummer te zien.

Voor de rollen: `recruitmentleider`, `marketingleider` en `chef`.

### Wat lost deze feature op?

In de stad zien we best vaak achtergelaten taxi's. Wij kunnen niet zien wie deze wagen gepakt heeft. We hebben meerdere mededelingen geplaatst om medewerkers erop te attenderen dit niet te doen, maar na een jaar blijft het nog altijd voorkomen. De oplossing die vaak gegeven wordt is "Bel de politie, die kan dat zien". In vrijwel alle gevallen komt de politie echter nooit opdagen.

In het echt kunnen taxicentrales ook zien wie bij welke auto hoort, dus dit lijkt me een logische en nuttige oplossing.

**Comment by Chang-nl** [comment]
Zit erin na de herstart!

**Comment by TedeaTaxi** [comment]
@Chang-nl 

We krijgen deze meldingen binnen nu:

> Functie zit er in, alleen heeft iedereen die funtie in zijn f6 menu, het werkt wel alleen bij Chefs. En we kunnen nogsteeds geen Taxi's opeten
> Alleen geen flauw idee HOE het werkt hahaha

> Het werkt op alle voertuigen behalve taxi's😂 heb een politie om hulp gevraagd maar hun zien nu ook niet meer van wie een taxi is 
> Dus denk dat het een beetje kapot is

> Met uitzondering op de Tesla aangezien daar het stadskenteken zichtbaar op is

**Comment by TedeaTaxi** [comment]
![image](https://user-images.githubusercontent.com/93401910/176358205-db93eb53-1b0e-47bc-ab51-69913df9fbb7.png)

![image](https://user-images.githubusercontent.com/93401910/176358224-62f7f1c8-3706-4105-bc39-56d3e1879e90.png)

**Comment by TedeaTaxi** [comment]
En dus dat iedereen de optie te zien krijgt nu: 

![image](https://user-images.githubusercontent.com/93401910/176359849-b3fcca6e-aa54-49da-b2c8-b0c4e10e794e.png)

**Comment by Chang-nl** [comment]
Ik zie het bedankt nog voor het melden, ik had een paar dingen over het hoofd gezien zie ik net. Aan de logica voor het opzoeken van een voertuig heb ik niks aangepast dus het zou voor politie niet anders moeten zijn.

**Comment by Chang-nl** [comment]
Is nu daadwerkelijk gefixt, en je hoeft geen kenteken meer in te voeren die je bij sommige niet ziet.
