### ISSUE TITLE
[FEATURE]: "QA" swimlane toevoegen aan issues/project

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1477]
### Contact Details

Geertje123#2163

### Beschrijf zo duidelijk mogelijk de feature

Ik heb redelijk vaak tickets die ik aanmaak waarbij de fix of implementatie incorrect is, en dus nog aangepast moeten worden. De ticket wordt echter gelijk op closed gezet na implementatie zonder dat controle vanuit de aanmaker gedaan wordt. Het effect daarvan is dat alle comments die je op die tickets plaatst over dat het nog niet (goed) werkt, niet meer gelezen worden, waardoor je een nieuwe ticket moet aanmaken over het zelfde onderwerp. Gebruikelijk zie je bij softwareontwikkeling om die reden dus altijd de QA lane, waarin een ticket terecht komt na implementatie. Zodra de aanmaker dan de OK geeft kan de ticket op done.

**Comment by niekschoemaker** [comment]
We hebben geen QA afdeling en daar gebruiken we dus issues voor, issues is de main waar we mee werken, tickets controleer ik zo nu en dan.
issues kun je heropenen, dus vandaar.

**Comment by TedeaTaxi** [comment]
@niekschoemaker sorry, met 'ticket' bedoelde ik inderdaad GitHub issues. Het nadeel is dat de persoon die de issue heeft aangemaakt, niet zelf die kan heropenen. In ieder geval, wij hebben daar geen rechten toe, dus moeten we elke keer een nieuwe ticket aanmaken als iets nog niet is opgelost.

**Comment by Chang-nl** [comment]
Als je comment bij een issue dan word er een mailtje gestuurd naar degene die hem gesloten heeft. De issue word alleen gesloten als het getest is anders krijgt deze de label fixed-untested, echter zou het kunnen dat het niet helemaal goed getest is.
