### ISSUE TITLE
[Bug]: Ammo verdwijnt

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1483]
### Contact Details

dead123x5#1144

### Wat gebeurde er?

2 Wapens met de zelfde ammo worden in een appartement gelegt (dat zijn dus 2 verschillende ammo-clips) en dan verdwijnt de ammo van het ene wapen en de andere blijft hem houden.

Een clip van wat er gebeurde;
https://medal.tv/games/gta-v/clips/qh421bOERiks6/d133710K3zsP?invite=cr-MSxZS3UsNTA4NDQ1Mzgs 

### Wat hoorde er te gebeuren?

Alle bij de wapens moeten hun eigen ammo behouden en niet samen gevoed word waardoor er ammo verdwijnt.

### Wat veroorzaakt de bug?

Hey gebeurd wanneer je 2 wapens na elkaar in een appartement legt.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

N.V.T.

**Comment by niekschoemaker** [comment]
Dit klopt, de M1911 en Berreta 92 gebruiken dezelfde ammo, dus als je ze allebei tegelijk bij je hebt krijg je inderdaad deze issue.

Is iets van GTA waar we helaas niet echt iets aan kunnen doen, ik kan wel even kijken of ik de ammo types wellicht aan kan passen.

**Comment by niekschoemaker** [comment]
Nope heb het ff getest, ammo type kan ik niet aanpassen
