### ISSUE TITLE
[FEATURE]: Kleding cirkel plaatsen.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1484]
### Contact Details

dead123x5#1144

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graat in ons bedrijfspand een kleding cirkel willen krijgen.

Dit op de volgende coords; x-787.98  y-215.82  z37.08  h59.66
https://prnt.sc/aY-LoVBNFITt

### Wat lost deze feature op?

Medewerkers kunnen dan gemakkelijk hun kleding veranderen naar hun werk kleding.

**Comment by Attomn** [comment]
Kleding cirkel is toegevoegd. Zal er na de restart in staan.

![afbeelding](https://user-images.githubusercontent.com/69365961/177041475-3aa1e989-bc5d-458e-9f38-eafdde7ba65c.png)

**Comment by brothasx** [comment]
Cirkel toegevoegd
