### ISSUE TITLE
[Bug]: Ticket bot stuurt dubbele berichten

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1485]
### Contact Details

Bas#6430

### Wat gebeurde er?

Wanneer je een ticket moved naar een kanaal en daar wordt een automatische reply verstuurd, stuurt de bot dit twee keer.
<img width="625" alt="Schermafbeelding 2022-06-30 om 15 37 00" src="https://user-images.githubusercontent.com/47216413/176691268-10723477-3404-4a71-b855-12055376132b.png">

### Wat hoorde er te gebeuren?

Er hoort 1 bericht gestuurd te worden.

### Wat veroorzaakt de bug?

-

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

**Comment by niekschoemaker** [comment]
Is gefixed
