### ISSUE TITLE
Kleding Circels kleedkamers Ambulance personeel

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#1486]
### Contact Details

SolidHawk#0929

### Beschrijf zo duidelijk mogelijk de feature

Cirkels toevoegen in de vrouwen en mannenkleedkamers om jezelf om te kunnen kleden in de kleedkamers. Zowel naar werk kleding, als burger kleding.

### Wat lost deze feature op?

Zo voorkom je dat mensen onrealistisch in de gang met /Eup gaan omkleden. Voegt een klein beetje realisme toe.

**Comment by Attomn** [comment]
Afgekeurd, elke overheidsbaan die /eup heeft, heeft geen omkleed cirkel zover ons bekend is, daarnaast kan je /eup ook gewoon in de mannen- en vrouwen kleedkamer gebruiken ipv midden in de gang.

**Comment by brothasx** [comment]
Afgekeurd, elke overheidsbaan die /eup heeft, heeft geen omkleed cirkel zover ons bekend is, daarnaast kan je /eup ook gewoon in de mannen- en vrouwen kleedkamer gebruiken ipv midden in de gang.
