### ISSUE TITLE
[Bug]:  Buiten hek/ voordeur Ccf ( Colombo) 

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1487]
### Contact Details

[TDA] Johnny Flodder#3559

### Wat gebeurde er?

Leden met rang : Ondernemer kunnen de hek en voordeur niet opnen, ik zelf met superadmin rechten kan wel alles zien en openen. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Geen f8 informatie over deze bug.
![hek ccf johnny](https://user-images.githubusercontent.com/89384945/176992278-b97f7a43-5c64-4dfb-abb6-fd80faeaea13.png)
![hek ccf met ondernemer rol](https://user-images.githubusercontent.com/89384945/176992279-55498574-d2c2-4dbb-9000-a1ba21754d63.png)

**Comment by Attomn** [comment]
Ik ben gister bezig geweest met sloten boven en ben niet aan deze sloten geweest, deze zouden ook gewoon moeten werken zonder problemen.

![afbeelding](https://user-images.githubusercontent.com/69365961/176994427-0e99bc11-f4da-45ad-81e4-84f31ca3e902.png)
![afbeelding](https://user-images.githubusercontent.com/69365961/176994445-c5da3f6c-c527-4af8-8eaa-d2e0358afd1e.png)
![afbeelding](https://user-images.githubusercontent.com/69365961/176994458-01939d8d-f075-4bb0-8d4c-2671d1746417.png)

Alles klopt gewoon kwa code dus geen idee waar dit vandaan komt...

**Comment by Attomn** [comment]
Heb het even gekeken, exact dezelfde code werkt wel gewoon in de test server met de ondernemer rol. Nadat mijn commit gemerged is richting de main server zijn de sloten gefixt na de restart.

**Comment by brothasx** [comment]
Fixed
