### ISSUE TITLE
[FEATURE]: Texture fout

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1488]
### Contact Details

dead123x5#1144

### Kenteken van voertuig

Elke Marechaussee Amarok.

### Voertuig model

Marechaussee Amarok: /car kmaramarok

### Omschrijf de bug

De spiegels van de Marechaussee Amarok kloppen de texure niet.

Hier een screenshot van de fout;
https://prnt.sc/W8v17gppG-ML

### Repro

Als je de auto inspawnd met /car kmaramarok zie je het gelijk.

### Normaal gedrag

De spiegels horen netals de rechter spiegel nirmaal blauw te zijn en niet allemaal kleine texures bij elkaar geplat, zoals je op de linker spiegel ziet op de foto.

**Comment by walvisgedaan** [comment]
Ik heb geen ZModeler account meer, dus dit moet @Lorenzo3001 even aanpassen (UV map zit een foutje in)
