### ISSUE TITLE
[Bug]: Report settings kan je zien wie ieamand heeft gebanned

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1490]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik heb gemerkt dat als je als staff de commando /report_settings toggle gebruikt dat je kan zie iemand heeft gebanned.
Is het mogelijk om niet te kunnen zie wie is gebanned met deze setting, zo voorkom je dat staff streamers niet dat soort dingen kunnen leaken. 
zie voorbeeld van een staff stream: 
![image](https://user-images.githubusercontent.com/101106299/177014663-e0458023-887c-412f-86cd-9d99e52b8b79.png)

### Wat hoorde er te gebeuren?

Je hoort de ban niet te kunnen zien lijkt me?

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Dit lijkt me geen bug, aangezien het command gaat over reports die je aan/uit kan zetten?

**Comment by CalRayy** [comment]
> Dit lijkt me geen bug, aangezien het command gaat over reports die je aan/uit kan zetten?

Oh, is het mogelijk om dit aan te passen?

**Comment by niekschoemaker** [comment]
Nee dit kunnen we niet aanpassen.
