### ISSUE TITLE
[EUP]: Mondkapjes + handschoenen+ boddycam

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1491]
### Contact Details

Wilma Wonka#4312

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag zouden wij als de mogelijkheid er is een knop/functie willen hebben dat we als de mondkapjes of handschoenen of boddycam af willen doen dat ook alleen dat af gaat. Want nu moeten we de K spier indrukken om het allemaal af te doen. Is hier een mogelijkheid voor?

**Comment by MisterM02** [comment]
Heb voor alle accessoires een mogelijkheid toegevoegd om deze ook weer te verwijderen. Verder heb ik Ambulance Accessoires onderverdeeld in een "man" en "vrouw" categorie. 
Zit z.s.m. in de main
