### ISSUE TITLE
[FEATURE]: Gepantserd busje

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1492]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In staffoverleg hebben we besproken over het gepantserde busje.

We hebben besproken om de ramen van de gepantserde busje sneller kapot te laten maken met hollowpoint bullets.
Misstake gaf aan dit wel mogelijk is en dat hij er naar gaat kijken, maar moest even een github ervoor maken 😄 .

### Wat lost deze feature op?

Verschillende soorten gevechten op eiland.

**Comment by ARJ3N** [comment]
Probleem wat ik hier wel mee zie is dat met FMJ bullets auto's mogelijk ook extreem snel stuk geschoten zullen worden, misschien dat daar nog naar gekeken kan worden? Of eventueel nog even in Burgerraad bespreken of FMJ bullets de beste oplossing zouden zijn.

**Comment by zeletix** [comment]
> Probleem wat ik hier wel mee zie is dat met FMJ bullets auto's mogelijk ook extreem snel stuk geschoten zullen worden, misschien dat daar nog naar gekeken kan worden? Of eventueel nog even in Burgerraad bespreken of FMJ bullets de beste oplossing zouden zijn.

Hoe bedoel je precies, FMJ? Deze zijn niet in de server zover ik weet

**Comment by CalRayy** [comment]
> > ### Contact Details
> > CalRay#1513
> > ### Beschrijf zo duidelijk mogelijk de feature
> > In staffoverleg hebben we besproken over het gepantserde busje.
> > We hebben besproken om de ramen van de gepantserde busje sneller kapot te laten maken met hollowpoint bullets. Misstake gaf aan dit wel mogelijk is en dat hij er naar gaat kijken, maar moest even een github ervoor maken 😄 .
> > ### Wat lost deze feature op?
> > Verschillende soorten gevechten op eiland.
> 
> Niet met hollowpoint, hollowpoint is letterlijk het omgekeerde van armor piercing, het ging hier om FMJ en AP bullets.

Whoopsie 😄

**Comment by Chang-nl** [comment]
Is ondertussen gefixed!
