### ISSUE TITLE
[Bug]: De emote "Kloppen" tijdens het verkopen aan deuren kan je annuleren

### ISSUE THREAD

**Issue by MatteDB** [Tedeapolis/development#1493]
### Contact Details

MatteDB#4517

### Wat gebeurde er?

Als je nu verkoopt via het nieuwe drugsverkoopsysteem klop je aan aan een deur. Mensen duwen dan op de X-knop zodat ze de animatie kunnen annuleren. 

Eventueel als ze op X duwen dat ze opnieuw naar het startpunt moeten en opnieuw moeten beginnen.

### Wat hoorde er te gebeuren?

Je hoort de emote niet te kunnen cancelen.

### Wat veroorzaakt de bug?

Op de X-knop duwen 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Willem-Dekker** [comment]
dit zou 2 dagen geleden gefixed moeten zijn

**Comment by Chang-nl** [comment]
Dit is gefixed zojuist getest!
