### ISSUE TITLE
[FEATURE]: Mogelijkheid hebben om de snijbrander te cancellen.

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1494]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid geven aan spelers om de snijbrander animatie te cancellen, zodat de snijbrander ook faalt maar dat je snijbrander niet verliest.

### Wat lost deze feature op?

Ongemakkelijke situaties voorkomen met de politie dat je vast zit, een keuze hebben om het te annuleren.

**Comment by Chang-nl** [comment]
Je kan deze nu cancelen maar je krijgt de blowpipe niet terug.
