### ISSUE TITLE
[FEATURE]: weghalen verkoopplaats op colombo terrein

### ISSUE THREAD

**Issue by kerrieeee** [Tedeapolis/development#1495]
### Contact Details

Kerrie#1003

### Beschrijf zo duidelijk mogelijk de feature

Er zit een verkooplocatie van de dealer op het terrein van het colombo cafe ondanks dat er een hek staat om het terrein af te bakenen. Dus het weghalen van deze locatie als het kan. 
![image](https://user-images.githubusercontent.com/95652537/177189262-fbd8f827-ca2c-4e8b-aa05-913252dc8d17.png)

### Wat lost deze feature op?

De overlast bij het cafe van de verkopers en het zorgt ervoor dat colombo niet meteen een slechte naam opbouwt door de vele interacties met drugs op eigen terrein.

**Comment by Attomn** [comment]
Verkooppunt is verplaatst, na de restart zullen hier geen kiddo's meer over de hekken heen klimmen.
