### ISSUE TITLE
[Bug]: Gebanned spelers

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1498]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Spelers die gebanned zijn op discord, maar niet op de adminpanel kunnen nog altijd in de stad spelen dit lijkt me niet de bedoeling. 
Is het mogelijk om dit te fixen?

### Wat hoorde er te gebeuren?

Als je gebanned bent op discord hoor je niet op de server te kunnen spelen lijkt me. 

### Wat veroorzaakt de bug?

/

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

/

**Comment by Mikajac** [comment]
Dit lijkt mij geen development-issue maar eerder een foutje van diegene die de mensen uit de Discord bant zonder hier ook een in-game ban aan te koppelen. Zie namelijk niet hoe development hier iets op kan coderen oid.
