### ISSUE TITLE
ID kaart geven werkt niet

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#15]
Als je een ID kaart geeft komt er te staan bij de andere persoon : You dont have any licenses... 
De andere persoon ziet je ID kaart ook niet
![Screenshot_14](https://user-images.githubusercontent.com/68497102/87871175-8d47b200-c9ae-11ea-91dd-0715bbcca088.png)

**Comment by Willem-Dekker** [comment]
werkt weer naar behoren.
