### ISSUE TITLE
Nieuw politie rol

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#150]
Recherche rol toevoegen bij de politie en dan ook toegang geven tot /lightbar. De rest van de person moeten het zelfde zijn als inspecteur binnen de politie.

**Comment by Willem-Dekker** [comment]
Graag ff invullen:
 - naam
 - salaris
 en de rest van de job dingen

**Comment by SecretSupplier** [comment]
Het moet gewoon letterlijk een copy zijn van de rang inspecteur.

**Comment by SecretSupplier** [comment]
Recherche
900
Toegang tot alle voertuigen
Toegang tot /lightbar
Heel het F6 menu

**Comment by Willem-Dekker** [comment]
alles behalve lightbar
