### ISSUE TITLE
[Bug]: Bankoverval: door de grond zakken bij trolley leegmaken

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1500]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Wanneer men de rechter trolley wilt leegpakken wordt men door de muur gezet. Na het leegpakken zakt men door de grond en spawnt men op het dak waardoor er misbruikt van gemaakt kan worden.
Dit gebeurt 100% zeker bij de bank achter de modshop bij ziekenhuis/gemeentehuis. Ik heb net nog niet kunnen testen bij andere banken.
https://medal.tv/games/gta-v/clips/rnPOjTyo7NCQA/d13371io2AYL?invite=cr-MSxOdU0sMjE2NzQyMjcs 

### Wat hoorde er te gebeuren?

Men behoort in de kluis van de bank te blijven staan.

### Wat veroorzaakt de bug?

Waarschijnlijk zit de emote-locatie bij de trolley aan de verkeerde kant.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Geen errors oid in F8.
https://medal.tv/games/gta-v/clips/rnPOjTyo7NCQA/d13371io2AYL?invite=cr-MSxOdU0sMjE2NzQyMjcs

**Comment by Attomn** [comment]
Heb 't zojuist opgelost, na de restart werkt het weer naar behoren!
