### ISSUE TITLE
[Kleding]: Vernieuwde outfit gevangenis

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1501]
### Contact Details

Nubudi#1907 / Pim Z.#8743

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

**Toelichting**
De huidige outfit van gedetineerden is al een aantal jaar hetzelfde en bij mannen bugt onder ander de trui met de broek. Een nieuwe outfit zou voor afwisseling leuk zijn, vooral voor de "vaste klanten". 

**Kledingstukken**
skin_male = {
        tshirt_1 = 15,
        tshirt_2 = 0,
        torso_1 = 363,
        torso_2 = 2,
        sticker = 106,
        sticker_2 = 0,
        arms = 6,
        arms_2 = 0,
        pants_1 = 134,
        pants_2 = 2,
        shoes_1 = 24,
        shoes_2 = 0,
        ears_1 = -1,
        sex = 0,
        chain_1 = 0,
        chain_2 = 0,
        glasses_1 = 0,
        glasses_2 = 0,
    },
    skin_female = {
        tshirt_1 = 14,
        tshirt_2 = 0,
        torso_1 = 382,
        torso_2 = 2,
        sticker = 115,
        sticker_2 = 0,
        arms = 3,
        arms_2 = 0,
        pants_1 = 141,
        pants_2 = 2,
        shoes_1 = 24,
        shoes_2 = 0,
        ears_1 = -1,
        sex = 1,
        chain_1 = 0,
        chain_2 = 0,
        glasses_1 = 0,
        glasses_2 = 0,
}

**Foto's**
Man: ![image](https://user-images.githubusercontent.com/20951687/177809419-183f9cf8-5a29-4e66-a056-0e98ee9c7b91.png)
Vrouw: ![image](https://user-images.githubusercontent.com/20951687/177809451-324f83a3-e90f-4cf3-b86c-1e5290c4802e.png)
Rug (eventueel nog aanpassen naar iets TDA-gerelateerd?): ![image](https://user-images.githubusercontent.com/20951687/177809474-2b26096f-3f85-4bdf-815f-42e6193dbb7a.png)

**Comment by MisterM02** [comment]
Fixed. Zit zsm in de main
