### ISSUE TITLE
[Bug]: Dealerverkoop drugs kapot

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1502]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Niks.

### Wat hoorde er te gebeuren?

Normaal zou men bij de dealer voor drugs aan moeten kloppen en per SMS locaties toegestuurd krijgen. Momenteel is de cirkel te zien, krijgen de spelers ook de pop-up in beeld maar gebeurt er niets zodra zij de gewenste drug selecteren. Zover ik heb vernomen werken alle drie de drugs niet, maar coke weet ik in ieder geval zeker uit meerdere bronnen.

### Wat veroorzaakt de bug?

Onbekend, er komt geen foutcode oid in F8. Als ik ze plugin start in de testserver werkt alles wel naar behoren en krijg ik ook de SMS binnen. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

NVT, komen geen logs.

**Comment by CalRayy** [comment]
Video ervan: https://cdn.discordapp.com/attachments/994191952033632286/994566485097848832/bugggg.mp4
