### ISSUE TITLE
[Bug]: Kleding cirkels / K-menu werken niet

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1503]
### Contact Details

MisterM#0001

### Wat gebeurde er?

Er zijn meerdere dingen m.b.t. kleding die niet werken. 
O.a. het kledingmenu (paarse cirkels) en het K-menu (masker, rugtas, ketting e.d.)

Onbekend is hoe dit komt.

### Wat hoorde er te gebeuren?

De menu's horen gewoon te werken

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

[CitizenFX_log_2022-07-08T001322.log](https://github.com/Tedeapolis/development/files/9067980/CitizenFX_log_2022-07-08T001322.log)

**Comment by niekschoemaker** [comment]
Gefixed
