### ISSUE TITLE
[Bug]: Gele cirkel garages

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1504]
### Contact Details

Nubudi#1907 / ! 𝙨𝙖𝙢𝙞#6556

### Wat gebeurde er?

Wanneer Sami bij de garage de gele cirkel wilt gebruiken, krijgt hij onderstaande error in F8 en kan hij ook de garage niet gebruiken. 
Dit gebeurt bij elke garage bij hem en reloggen en zelfs andere PC helpt niet.

Er zou eventueel meer info staan in ticket #126164 en via daar kunnen jullie ook met hem in contact komen. 

### Wat hoorde er te gebeuren?

De gedespawnde voertuigen horen zichtbaar te worden waarbij hij deze kan terug kopen.

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/20951687/177901371-906786da-42cd-47df-8a56-ec242166f9bd.png)
https://www.youtube.com/watch?v=OLuBM6hEw40

**Comment by Attomn** [comment]
Zou je log bestanden kunnen regelen zodat we meer informatie hebben?

https://tedeapolis.nl/tutorials/

**Comment by Mikajac** [comment]
[CitizenFX_log_2022-07-08T050520.log](https://github.com/Tedeapolis/development/files/9073589/CitizenFX_log_2022-07-08T050520.log)
[CitizenFX_log_2022-07-08T050620.log](https://github.com/Tedeapolis/development/files/9073590/CitizenFX_log_2022-07-08T050620.log)
[CitizenFX_log_2022-07-08T154627.log](https://github.com/Tedeapolis/development/files/9073591/CitizenFX_log_2022-07-08T154627.log)
[CitizenFX_log_2022-07-07T235957.log](https://github.com/Tedeapolis/development/files/9073592/CitizenFX_log_2022-07-07T235957.log)
[CitizenFX_log_2022-07-08T004438.log](https://github.com/Tedeapolis/development/files/9073593/CitizenFX_log_2022-07-08T004438.log)

**Comment by Mikajac** [comment]
Dat zijn de 5 meest recente logs van hem. Boven aan het bestand heb ik nog wat belangrijke info geschreven.

**Comment by Mikajac** [comment]
Inmiddels heb ik van meerdere personen vernomen dat zij ook exact deze foutcode ontvangen wanneer zij voertuigen uit de gele cirkel willen halen.

**Comment by Mikajac** [comment]
Misschien ook relevant: het is niet voor iedereen gebugged. Ikzelf heb bijvoorbeeld nergens last van en kan gewoon auto's eruit halen.

**Comment by Attomn** [comment]
Klopt, we hebben een duidelijke error gehad. Het is opgelost na de restart!
