### ISSUE TITLE
[Bug]: AK-74 kan je niet meer tunen

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1505]
### Contact Details

iHax0r#3736

### Wat gebeurde er?

Wanneer ik in het gangmenu "Koop wapen mods" met een AK-74 probeer deze te tunen, lukt dit niet en krijg ik een error zoals te zien in onderstaande foto:
![image](https://user-images.githubusercontent.com/29235700/178100154-b440b9e3-d685-4725-b709-2954baa39292.png)

### Wat hoorde er te gebeuren?

Het menu om te tunen van een AK-74 hoorde open te gaan.

### Wat veroorzaakt de bug?

Dat je een AK-74 niet meer kan tunen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/178150222-13182b9a-2a13-4caa-9611-55c8b599972d.png)
Is opgelost nadat mijn commit gepushed is! :)
