### ISSUE TITLE
[Bug]: Lucky wheel werkt niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1506]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je draait aan het rad en je geld gaat weg, maar je krijgt niets. 
zie clip: 
https://cdn.discordapp.com/attachments/995277378127396944/995299527080820776/Desktop_2022.07.09_-_14.02.08.02.DVR_Trim.mp4

### Wat hoorde er te gebeuren?

je hoort geld te krijgen als hij ergens op land.

### Wat veroorzaakt de bug?

![image](https://user-images.githubusercontent.com/101106299/178104941-34f20c11-7914-4c60-8091-2cef8060a8c4.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/101106299/178104949-ef0cc5de-9d24-45fe-aaef-350ce633f5b4.png)

**Comment by Attomn** [comment]
Werkt als het goed is na de restart weer!

**Comment by Attomn** [comment]
Of misschien zelfs nu al, gezien de server crash.
