### ISSUE TITLE
[FEATURE]: Dealer systeem (drugs delivery )

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1507]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staff overleg hadden we besproken over deepweb meldingen (bij de nieuwe drugs delivery) en het toevoegen van dingen als hogere rewards op basis van hoeveel je gaat verkopen om grotere hoeveelheden bij je te hebben te stimuleren.

### Wat lost deze feature op?

Meer actie voor criminele en leukere scenario's voor gangs

**Comment by JohnnyFlodder** [comment]
Opties bij het nieuwe drugs verkoop systeem toevoegen:

Categorie 1,2,3 + Deepweb melding af laten gaan zoals bij witwas met kenteken. 

Categorie 1:
Lage kans op melding in de deepweb maar verkoopt daarbij minder zakken 
Kans deepweb 5%
Verkoop zakjes 1 t/m 5 

Categorie 2:
Middel kans op melding in de deepweb maar verkoopt daarbij gemiddeld hoeveelheid zakjes
Kans deepweb 25%
Verkoop zakjes 10 t/m 15

Categorie 3:
Grote kans op melding in de deepweb maar verkoopt daarbij grote hoeveelheden zakjes
Kans deepweb 50%
Verkoop zakjes 30 t/m 50

Wat nou als de speler geen kenteken heeft ? 
Kunnen spelers eigen voertuigen gebruiken ? 
Type voertuig + kleur ?

**Comment by Willem-Dekker** [comment]
> Opties bij het nieuwe drugs verkoop systeem toevoegen:
> 
> Categorie 1,2,3 + Deepweb melding af laten gaan zoals bij witwas met kenteken.
> 
> Categorie 1: Lage kans op melding in de deepweb maar verkoopt daarbij minder zakken Kans deepweb 5% Verkoop zakjes 1 t/m 5
> 
> Categorie 2: Middel kans op melding in de deepweb maar verkoopt daarbij gemiddeld hoeveelheid zakjes Kans deepweb 15% Verkoop zakjes 10 t/m 15
> 
> Categorie 3: Grote kans op melding in de deepweb maar verkoopt daarbij grote hoeveelheden zakjes Kans deepweb 35% Verkoop zakjes 30 t/m 50
> 
> Wat nou als de speler geen kenteken heeft ? Kunnen spelers eigen voertuigen gebruiken ? Type voertuig + kleur ?

Versie 1 is geïmplementeerd klaar voor testen op devserver

**Comment by Willem-Dekker** [comment]
zit er in na restart
