### ISSUE TITLE
[Bug]: /emotes

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1508]
### Contact Details

CalRay#1513

### Wat gebeurde er?

de commando /emotes geeft geen lijst meer van alle emotes.

### Wat hoorde er te gebeuren?

je hoort in de chat de hele emote lijst te zien

### Wat veroorzaakt de bug?

ik denk door de nieuwe hud / chat weergave werkt het niet.
F8 geeft dit aan: 
![image](https://user-images.githubusercontent.com/101106299/178141408-29e7a70a-916c-40c0-8dad-5e0e82658bbf.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Attomn** [comment]
Hoi, zou je wat log bestanden kunnen verschaffen? Met deze F8 kunnen we niks gezien er geen fouten in staan betreft emotes.

**Comment by Chang-nl** [comment]
Waarom maar waarom heeft dit een hoge prioriteit? En dit is geen bug want deze command is weggehaald.
