### ISSUE TITLE
[Bug]: Witwassen

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1509]
### Contact Details

iHax0r#3736

### Wat gebeurde er?

Wanneer je start met wassen gaat op het depot alles prima, alleen bij het eerste punt klik je op "e" en gebeurd er niks. Vervolgens zal je naar het depot moeten en de witwas opnieuw starten. Wanneer je dan naar een punt rijd doet hij het wel.

### Wat hoorde er te gebeuren?

Je hoort het eerste punt wel gewoon te kunnen doen, alleen hier krijg je een error.

### Wat veroorzaakt de bug?

De bug zorgt ervoor dat je behoorlijk staat te strugglen op dit punt en wanneer je pech hebt kan dit zelfs op een overval uitlopen, aangezien je niet naar behoren je job uitvoert.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Staan in #dev-overleg
https://discord.com/channels/563825802865541122/698956968764637205/994630141798011040

**Comment by niekschoemaker** [comment]
Is als het goed is al gefixed, bijbehorende issue in Sentry is in elkgeval weg
