### ISSUE TITLE
[Bug]: Alle Overheidsberoepen: Wekelijkse uren komen niet binnen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1510]
### Contact Details

Geertje123#2163

### Wat gebeurde er?

Geen mail voor wekelijkse uren ontvangen, maar wel voor facturen. Door de missende mail van uren kunnen wij promoties en dergelijke niet verwerken.

Nu:

![image](https://user-images.githubusercontent.com/93401910/178199023-20b921a4-b0bc-40e3-bafb-2dafa73ace18.png)

### Wat hoorde er te gebeuren?

Elke maandag om 7 uur 's ochtends krijgen we de gewerkte uren van de week ervoor in de mail.

Normaal:

![image](https://user-images.githubusercontent.com/93401910/178198970-0da99fcd-4968-4490-8ff2-21d0d521fea5.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Let op: Wekelijkse facturen hebben we wel ontvangen, maar de wekelijkse uren niet.

**Comment by Willem-Dekker** [comment]
fixed worden nu verzonden
