### ISSUE TITLE
[Bug]: Taxi NPC job (pet) vermenigvuldigen van dode lichamen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1512]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

![image](https://user-images.githubusercontent.com/93401910/178555181-85b13848-b110-4019-be63-d0418b54ccf2.png)

zie ook youtube 
[https://youtu.be/jxkaSf-0PMA](url)

als iemand die de stad uit gaat neer geslagen word of aan gereden 
En je bent op zoek naar een NPC via de taxi job 

dan pakt die ook de bewusteloze PET en probeert deze terug te spawnen want het is geen levende NPC 

### Wat hoorde er te gebeuren?

Als je een NPC zoekt dan moet die geen bewusteloze PET pakken maar alleen een levende PET

### Wat veroorzaakt de bug?

NPC missie starten als je zelf de persoon bewusteloos ziet

ps. als het dus gebeurd kunnen de taxi mensen het alleen voorkomen door de taxi job uit te zetten en weg te gaan uit dat gebied wij gaan hier een mededeling over plaatsen 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

word niet gezien als een bug door het systeem dus geen log bestanden

**Comment by Ljosfari** [comment]
is uitgebreid getest maar komt bij ons niet voor

**Comment by TedeaTaxi** [comment]
Update door niek check if body is dead
