### ISSUE TITLE
[Bug]: spectate steamnaam of soms id

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1513]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Soms als je iemand spectate zie je links onder de ID en soms zie je de steamnaam. Is het mogelijk om dit te veranderen naar ID en niet steamnaam ?
![spectate](https://user-images.githubusercontent.com/101106299/178815769-bd3b08a8-d0eb-420d-92c1-246d4bcce863.png)

### Wat hoorde er te gebeuren?

Je hoort volgens mij de ID te zien 

### Wat veroorzaakt de bug?

1. /spectate id 
2. je ziet linksonder ID of steamnaam is random

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

N.V.T.

**Comment by Chang-nl** [comment]
Dit is niet random maar gebaseerd op de /togglename command, dus mocht jij deze hebben uitgevoerd dan krijg je steamnamen te zien. Als je hem nog een keer uitvoert worden het weer id's

**Comment by CalRayy** [comment]
> Dit is niet random maar gebaseerd op de /togglename command, dus mocht jij deze hebben uitgevoerd dan krijg je steamnamen te zien. Als je hem nog een keer uitvoert worden het weer id's

Aha, is het mogelijk om altijd id's te zien of kan dat niet ?

**Comment by Chang-nl** [comment]
Dat is in principe al zo, ALLEEN als je het command uitvoert hierboven dan komen er steamnamen te staan
