### ISSUE TITLE
[Bug]: Callsinge bugt

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1515]
### Contact Details

Wilma Wonka#4312

### Wat gebeurde er?

Als wij in dienst zijn passen wij onze callsinge aan, naar het moment van wat we voor dienst hebben in de stad van de ambu. Maar als we klaar zijn et de dienst en we gaan de stad uit en we komen er weer in stad het weer terug op examinator of inleer terwijl er eigelijk wat anders hoort te staan!

### Wat hoorde er te gebeuren?

Als we de callsinge hebben aangepast dat het daar ook op hoort te blijven staan.

### Wat veroorzaakt de bug?

Dat is onbekent

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Zou je een video kunnen toevoegen zodat het duidelijker is voor ons hoe we de issue kunnen reproduceren, alv bedankt!

**Comment by WilmaWonka1985** [comment]
Jah ga ik morgen even  doen voor je

Op zo 17 jul. 2022 00:23 schreef Chang ***@***.***>:

**Comment by WilmaWonka1985** [comment]
[https://youtu.be/1yW0iMZN1Fs](url)

Ik hoop je hier mee geholpen te hebben?

**Comment by Willem-Dekker** [comment]
@TedeaTaxi heeft hier ook last van, kan een caching issue zijn naar hoe he klint

**Comment by Ljosfari** [comment]
is dit al opgelost ?

**Comment by WilmaWonka1985** [comment]
Nee  helaas nog niet. Nog steeds het probleem

**Comment by TedeaTaxi** [comment]
Wij hebben zojuist ivm dit probleem een mededeling aan alle medewerkers geplaatst.

> Sommigen van jullie waren al bekend met dit probleem, voor sommigen zal dit nieuw zijn. Elke keer als je in dienst komt en de porto in komt, zal je callsign gereset zijn en dus niet kloppen. Je moet dus handmatig jouw callsign weer goed zetten als je weer in dienst komt. Een handige tip is om jouw callsign op te slaan zodat je hem makkelijk kan copy pasten als je weer in de stad komt. Wij hopen dat het probleem zo snel mogelijk wordt opgelost, maar tot die tijd moet je hem handmatig veranderen!

Een van onze nieuwe managers rapporteerde dit erover:

> ik denk dat als je hem nu verandert dat ie niet opgeslagen wordt. Althans ik had gehoord dat vanaf een bepaald moment de callsigns niet worden opgeslagen. Zelf heb ik ook dat mijn callsign niet is opgeslagen sinds mijn promotie naar Manager haha

Geen idee of deze info helpt maar iets is beter dan niets lijkt me.

**Comment by Chang-nl** [comment]
Het is opgelost na de herstart!
