### ISSUE TITLE
[FEATURE]: 14k cirkels

### ISSUE THREAD

**Issue by Enrico14k** [Tedeapolis/development#1516]
### Contact Details

Enrico#4089

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag 2 aanpassingen aanvragen voor zowel onze opslagcirkel als onze voertuigspawn.

- Huidige opslagcirkel:   X: 952.46   Y: -1467.04   Z: 31.02   H: 96.13
- Nieuwe opslagcirkel:   X: 938.85   Y: -1462.55   Z: 30.40   H: 4.11

.

- Huidige voertuigspawn:   X: 940.81   Y: -1500.56   Z: 29.49   H: 280.57
- Nieuwe voertuigspawn:   X 944.34   Y: -1500.48   Z: 29.55   H: 269.04

### Wat lost deze feature op?

Onze bazenkamer heeft nu niet echt nut aangezien iedereen er constant doorheen loopt om wat uit de opslag te pakken, daarnaast was het toen we dit huis net kregen al de bedoeling om het ergens anders te plaatsen alleen was het er toen niet meer van gekomen.

Wat betreft de voertuigspawn, hebben we nu het probleem dat onze helikopter onder een hijskraan spawned waardoor vaak 1 van de wieken erin terecht komt tijdens het opstijgen en de heli dus stuk op onze spawnplek staat.

**Comment by Attomn** [comment]
Hoi, je helikopter en voertuig spawn zijn 2 verschillende cirkels, deze ga ik niet op dezelfde plek zetten. Mits je de helikopter spawnplaats wil verplaatsen moet je deze coördinaten even doorgeven.

Opslag cirkel gaat naar: X: 938.85 Y: -1462.55 Z: 30.40 H: 4.11
Voertuig cirkel gaat naar: ? even coördinaten doorgeven
Helikopter cirkel naar naar: ? even coördinaten doorgeven

**Comment by Enrico14k** [comment]
> Hoi, je helikopter en voertuig spawn zijn 2 verschillende cirkels, deze ga ik niet op dezelfde plek zetten. Mits je de helikopter spawnplaats wil verplaatsen moet je deze coördinaten even doorgeven.
> 
> Opslag cirkel gaat naar: X: 938.85 Y: -1462.55 Z: 30.40 H: 4.11 Voertuig cirkel gaat naar: ? even coördinaten doorgeven Helikopter cirkel naar naar: ? even coördinaten doorgeven

Hoi, onze helikopter spawned gewoon op dezelfde plek als onze auto's, tenzij je de bazenheli pakt. Maar ik had het nu over de helikopters waar iedereen toegang heeft die gewoon in de opslag worden gezet. Die komen op de zelfde plek als auto's. Ik zou je eventueel een foto in je pm kunnen sturen voor meer duidelijkheid?

**Comment by Attomn** [comment]
Oke, dan weet ik genoeg. Ik ga hier vanavond even naar kijken!

**Comment by Enrico14k** [comment]
> Oke, dan weet ik genoeg. Ik ga hier vanavond even naar kijken!

Top, dankjewel. Laat maar weten als je verder nog informatie nodig hebt :D

**Comment by Attomn** [comment]
Is gelukt! Als mijn commit naar de main server is gemerged, zijn de cirkels zoals aangevraagd!

**Comment by Enrico14k** [comment]
> Is gelukt! Als mijn commit naar de main server is gemerged, zijn de cirkels zoals aangevraagd!

Top, bedankt voor de snelle hulp!
