### ISSUE TITLE
[FEATURE]: Kofferbak groottes politievoertuigen aanpassen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1517]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij een iets andere verdeling willen zien in de kofferbak groottes van de politievoertuigen. Deze staan momenteel zo goed als allemaal op 40kg.

Ons voorstel is dan ook om de volgende voertuigen allemaal op 60 kilo te zetten:
- police
- police3
- fbi
- mercedesb
- Unmarked Volvo (kon de spawnnaam niet vinden)

### Wat lost deze feature op?

Extra opslag aangezien de kofferbakken nu nogal klein zijn, ook in vergelijking met andere soortgelijke auto's.

**Comment by Attomn** [comment]
Kofferbak groottes van onderstaande modellen heb ik zojuist aangepast naar 60KG:
- police
- police3
- fbi
- mercedesb
- politiev90
