### ISSUE TITLE
[FEATURE]: Voertuigen verwijderen uit jobgarage ambu en anwb

### ISSUE THREAD

**Issue by NouNou0** [Tedeapolis/development#1518]
### Contact Details

NouNou#2004

### Beschrijf zo duidelijk mogelijk de feature

Ambulance en ANWB de mogelijkheid geven om voertuigen uit hun jobgarage te verwijderen, politie en kmar hebben deze optie al. (Aangemaakt in overleg met Martijn)

### Wat lost deze feature op?

Dit lost niet per se iets op maar dit zorgt ervoor dat ambu en anwb orde krijgt in de jobgarage's en niet hetzelfde voertuig er 4x in hebben staan

**Comment by Chang-nl** [comment]
zodra de issue gesloten is, heeft de ambu nu de mogelijkheid om een voertuig te verwijderen en anwb heeft een ander soort garage waar de voertuigen niet persoonlijk zijn.
