### ISSUE TITLE
twitter bug

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#152]
Mensen krijgen allemaal de melding dat zij onjuiste inloggegevens gebruiken voor Twitter, ookal zijn zij al ingelogd.
Wanneer zij uitloggen en opnieuw inloggen, blijft de melding hetzelfde.

**Comment by PapaXilion** [comment]
https://github.com/Tedeapolis/development/issues/148
Was eerder gereport en werd toen (leek het) door een fix in de caching verholpen.

**Comment by Willem-Dekker** [comment]
@niekschoemaker heb jij hier recent aanpassingen aan gedaan?

**Comment by niekschoemaker** [comment]
> @niekschoemaker heb jij hier recent aanpassingen aan gedaan?

Is ondertussen idd gefixed
