### ISSUE TITLE
[Bug]: Getowner werkt niet bij spijkermatten

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1520]
### Contact Details

MisterM#0001

### Wat gebeurde er?

Via /getowner krijg je bij spijkermatten te zien dat het object niet genetworked is.

![image](https://user-images.githubusercontent.com/72617118/179426324-65bfbc88-fbd6-440f-b130-ea955eeb8c41.png)

### Wat hoorde er te gebeuren?

Je zou degene die hem neergelegd heeft moeten zien

### Wat veroorzaakt de bug?

Het object is niet genetworked

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
Dit command werkt bij geen één object dat geplaatst is vanuit het menu van de politie/kmar. Je moet hiervoor dan ook /getobjects gebruiken. De output van deze command komt in je f8 scherm te staan.
