### ISSUE TITLE
[FEATURE]: TDA bot automatische antwoorden uitschakelen voor bepaalde rollen

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1521]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

Momenteel wordt de TDA bot automatisch getriggered door verschillende rollen/kanalen terwijl dit niet nodig is. Het zou daarom handig zijn als er een blacklist komt voor rollen/kanalen die de bot niet kunnen triggeren.

Zo is het handig als alle ticket kanalen en alle staffrollen geblacklist worden. Daarnaast kunnen ook kanalen zoals #overheidsinstanties geblacklist worden.

Wellicht is het mogelijk om een command hiervoor te maken zodat je bij nieuwe rollen deze dmv command kan blacklisten?

### Wat lost deze feature op?

Onnodige berichten van de TDA bot.

**Comment by niekschoemaker** [comment]
Blijkbaar is die blacklist kort geleden kapot gegaan, ik zal even kijken

**Comment by niekschoemaker** [comment]
Ah yes, if statement stond verkeerd om, is gefixed
