### ISSUE TITLE
[FEATURE]: Mensen die geboeid zijn kan je niet in voertuigen zetten

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1522]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In staffoverleg hadden we besproken over mensen die geboeid zijn via de nieuwe commando /request_cuff kan je ze niet in voertuigen zetten, Misstake gaf aan dat het een missing feature was waar ik een github voor moest maken dus bij deze 😄 .

### Wat lost deze feature op?

Dat je mensen die geboeid zijn via de nieuwe commando in een voertuig kan doen en rare situaties + tickets over mensen die dan wegrennen etc.

**Comment by Chang-nl** [comment]
Heb er nu aan toegevoegd dat je iemand kan slepen en iemand het voertuig in kan zetten. Er zitten hulp notificaties bij wat het allemaal uitlegt.

**Comment by CalRayy** [comment]
Ah top!
