### ISSUE TITLE
[Bug]: witwas deepweb nogsteeds hetzelfde

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1524]
### Contact Details

MyNqme#9209

### Wat gebeurde er?

Na 20+ dagen is de witwas deepweb nogsteeds hetzelfde, terwijl deze na max 14 dagen veranderd hoort te zijn. (zie #1452) Denk dat het niet hoort dat deze nu nog hetzelfde is.

### Wat hoorde er te gebeuren?

De deepweb hoort al veranderd te zijn.

### Wat veroorzaakt de bug?

nvt

### Frequentie van de bug

Altijd

### Relevante log bestanden

nvt

**Comment by Chang-nl** [comment]
Is hij nog steeds hetzelfde, want dat is praktisch gezien niet mogelijk?

**Comment by Tom974** [comment]
> Is hij nog steeds hetzelfde, want dat is praktisch gezien niet mogelijk?

Ja de deepweb is nogsteeds hetzelfde haha

**Comment by Attomn** [comment]
Zou nu opgelost moeten zijn, kan je dit laten weten de komende paar dagen?

**Comment by Tom974** [comment]
> Zou nu opgelost moeten zijn, kan je dit laten weten de komende paar dagen?

yes is gelukt! bedankt!

**Comment by Chang-nl** [comment]
Yes ik zit net logs door te kijken en zie dat het gefixt is ondertussen en weer automatisch geregeld word!
