### ISSUE TITLE
Staff vestje voor vrouwen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1525]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Ik vroeg me af als het mogelijk was om een staff vestje te krijgen voor vrouwen, Martijn reageerde hierop maak even een github en voeg me eraan toe. Hij zal dit bekijken gaf hij aan, zou iemand hem willen toevoegen 😛?

### Wat lost deze feature op?

Herkenning dat er een staff lid aanwezig is etc

**Comment by MisterM02** [comment]
![image](https://user-images.githubusercontent.com/72617118/180090808-1b23fca8-64d3-46e9-96f1-0a278f4bcb25.png)
![image](https://user-images.githubusercontent.com/72617118/180090820-1254e25a-40a0-4958-aaf9-581cd1ebc6e8.png)

Zoiets @CalRayy ?

**Comment by CalRayy** [comment]
Yes, alleen is de achterkant "tedeapolis" en de rechthoek klein vind je niet? Bij de mannen is de achterkant groter dacht ik 😛

**Comment by MisterM02** [comment]
![image](https://user-images.githubusercontent.com/72617118/180314997-174fb0bc-4ba0-447a-9111-5d3cd8d2b713.png)

Fixed!

**Comment by MisterM02** [comment]
Zit z.s.m. in de main
