### ISSUE TITLE
[FEATURE]: Karmellos logo bij rang

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1526]
### Contact Details

iHax0r#3736

### Beschrijf zo duidelijk mogelijk de feature

Wij willen al een langere tijd ons logo veranderen, dit omdat ons huidige logo niet bij ons past. (icoontje naast de rang)
![coat_of_arms_of_galicia_spain_16th_century-svg](https://user-images.githubusercontent.com/29235700/179861308-da02566a-76ed-4254-9794-408a278b3fe8.png)

Dit is het wapen van Galicië en omdat onze familie daar vandaan komt, willen we vragen of het mogelijk is om deze bij onze rang neer te zetten.
![image](https://user-images.githubusercontent.com/29235700/179861579-c01d6f98-6e9f-496d-8808-fb748708c778.png)

### Wat lost deze feature op?

Dat wij een logo hebben wat wel bij onze groep past.

**Comment by iHax0rMC** [comment]
Ga het even navragen!

**Comment by Attomn** [comment]
Gecommit als 64x64, niet hele hoge kwaliteit maar met een beetje fantasie kom je ver 🤪
