### ISSUE TITLE
[FEATURE]: Aanpassing gangopslag cirkels Sandy Airfield.

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#1527]
### Contact Details

MisterM#0001

### Beschrijf zo duidelijk mogelijk de feature

Op het vliegveld van Sandy heeft iedere gang de optie om voertuigen weg te zetten in een "opslagcirkel". 
Naast deze opslagcirkel zit een cirkel waaruit je vervolgens weer voertuigen zou moeten kunnen pakken.
Deze cirkel is momenteel echter gelinkt aan het pakken van de bazenhelikopter en dus niet aan het pakken van voertuigen uit de voertuigopslag.

De kleine cirkel (zie foto)
![image](https://user-images.githubusercontent.com/72617118/180097226-c304f758-384c-422c-be19-15c6a2ebe85f.png)

zal dus omgezet moeten worden van bazenheli naar voertuigopslag. En daarbij eventueel een check toevoegen dat er via die cirkel enkel helikopters en vliegtuigen gepakt kunnen worden gezien dit oorspronkelijk ook de bedoeling was.

- [x] Cirkel omzetten 
- [x] Indien mogelijk een check op vliegtuigen en helikopter zetten

Verder zou het handig zijn om net als met normale garages zones (zuid en noord) te gebruiken. Denk aan "Huis" en "Vliegveld".  Dit zorgt ervoor dat mensen niets kunnen abusen door bv een vliegtuig te storen en deze vervolgens bij hun huis eruit te pakken. Het zou dan niet mogelijk moeten zijn om het voertuig te pakken op de andere locatie als er illegale goederen inzitten.

- [x] Zones toevoegen indien mogelijk

### Wat lost deze feature op?

Mensen kunnen er nu wel vliegtuigen wegzetten, maar geen pakken. Ze moeten deze nu alsnog pakken uit de opslag bij hun huis waar ze vervolgens niet kunnen opstijgen.

**Comment by MisterM02** [comment]
Ah. Ik zie nu dat Willem dit express had gedaan (https://github.com/Tedeapolis/development/issues/648). Maar zal dit bovenstaande voorstel even meenemen naar staffoverleg.

**Comment by niekschoemaker** [comment]
Zit erin
