### ISSUE TITLE
[FEATURE]: Overval gestaakt melding eruit halen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1528]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel krijgt de politie een melding als een overval gestaakt is. Dit zorgt ervoor dat agenten afkoppelen en er geen eenheid meer die kant opgaat. Graag zouden wij willen dat die melding eruit gehaald wordt.

### Wat lost deze feature op?

Wij willen dit aangezien het voor de roleplay leuker is als agenten nog wel die kant op gaan om de boel te checken. Dan kunnen ze daar kijken of het een valse melding was, of de overvallers nog binnen zijn, of dat er eventuele getuigen daar nog te spreken zijn of ze bijvoorbeeld iets gezien hebben.

**Comment by Chang-nl** [comment]
Zodra de issue gesloten is is het toegevoegd!
