### ISSUE TITLE
[Bug]: Rammenwasser ( Factuur per gereden km ) 

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1529]
### Contact Details

[TDA] Johnny Flodder#3559

### Wat gebeurde er?

De UWV job rammenwasser krijg je 3x facturen per gereden job boven de 3km. 

Dus simpel weg de distance moet aangepast worden.

### Wat hoorde er te gebeuren?

Je hoort 1 factuur per gereden km te krijgen.

### Wat veroorzaakt de bug?

Dat zorgt er voor dat je job minder wordt gebruikt en de mensen die hem gebruiken krijgen te weinig betaald. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Is gefixed
