### ISSUE TITLE
[FEATURE]: Taxi kantoor veiliger maken 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1530]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

We worden elke dag aan gereden op ons parkeer terrein. Mensen rijden veel te hard en verwonden vaak een van onze medewerkers.
Ook willen we het kantoor beter beveiligen aangezien we meerdere keren per maand gegijzeld worden door mensen met een nep "bom vest", dus we willen de deuren ook allemaal dicht kunnen doen. Tevens gebruiken mensen de pin automaat in het gebouw als of het een openbare bank is. Daarnaast is het ook vervelend als criminelen gebruik maken van onze taxi parkeer plaats/garage. Ook vaak om illegale dingen over te zetten naar garage en de politie kan er niks tegen doen maar wij worden er vaak wel op aan gekeken. Tevens willen we een aantal props ( camera's ) hebben hangen voor de roleplay met politie. Zo kan de politie camera bewaking opvragen als mensen lastig doen in en rond het kantoor, dan kunnen wij simpelweg vertellen dat alles wordt gefilmd.

![FiveM_b2372_GTAProcess_mYkwra0evj](https://user-images.githubusercontent.com/93401910/180650397-03dc0adc-a8bb-4829-b3f5-a5af8f5583c9.png)
![FiveM_b2372_GTAProcess_07Ml2F9ank](https://user-images.githubusercontent.com/93401910/180650398-4b2891e3-087f-490b-932b-df744f15ad72.jpg)
![FiveM_b2372_GTAProcess_n3t11PDKgF](https://user-images.githubusercontent.com/93401910/180650400-4c816b77-cfa9-47ee-b5c6-98bde2e2faa9.jpg)
![FiveM_b2372_GTAProcess_PDqL3K9BHs](https://user-images.githubusercontent.com/93401910/180650401-c1d6377f-f0bd-485e-9547-a7160d0c8cf2.jpg)
![FiveM_b2372_GTAProcess_2WvcMHfqCj](https://user-images.githubusercontent.com/93401910/180650403-1dfa5beb-2ea3-4266-bcf6-a18518bf0f4b.jpg)
![FiveM_b2372_GTAProcess_qOXq8wH3Ni](https://user-images.githubusercontent.com/93401910/180650404-0e429545-1c7b-4e01-90ea-63fefd7db810.jpg)

### Wat lost deze feature op?

Hekken rond om : We worden dan minder aangereden. Tevens gaan criminelen ergens anders hun zaken doen.
Sloten op de deur : Zodat mensen het gebouw niet gebruiken als persoonlijke bank en onbevoegde kunnen we dan ook gewoon weren van het taxi kantoor omdat we dan meer veiligheid garanderen voor onze personeel leden.
Camera's : Dan kunnen we met camera beelden werken om samen met de politie iets leuks neer te zetten!

### Checklist:

- [x] Sloten toevoegen aan de deuren
- [ ] Hekken plaatsen
- [ ] Camera's plaatsen

**Comment by Attomn** [comment]
Ik zit zo te kijken naar jullie sloten maar het is een publiek gebouw, jullie hebben een lobby voor klanten en al.. waarom zou op deze onderstaande deur: een slot moeten? @TedeaTaxi 
![afbeelding](https://user-images.githubusercontent.com/69365961/181579535-95e3311d-de6c-49ab-ac9b-f128018a4cb9.png)

Op deze onderstaande deur wil ik wel een slot plaatsen: 
![afbeelding](https://user-images.githubusercontent.com/69365961/181579700-f8ab5dd7-cf91-42b3-a648-f632d01f0c56.png)

Op deze onderstaande deur is een slot overbodig gezien hij omringt is met sloten?
![afbeelding](https://user-images.githubusercontent.com/69365961/181579953-b70f2b34-24cf-4462-8a59-bfbcb8fbc05a.png)

**Comment by TedeaTaxi** [comment]
als mensen lopen kloten in ons kantoor kunnen we ze niet buitensluiten door de tent op slot te doen tevens hebben we niet iemand aan de balie staan en komen mensen altijd ongevraagd binnen om onze pin apparatuur te gebruiken wat heel irritant is als je in gesprek bent op kantoor schreeuwen ze de boel bij elkaar 

de laatste deur willen we dicht hebben omdat we wel eens gesprekken hebben in het kantoor en dan die mensen dan soms denken dat ze lekker los kunnen lopen in de garage waarna ze dus soms ook aangereden worden als ze blind naar binnen rennen dus voor de veiligheid van onze bezoekers en personeel in de werk ruimte er achter 

tevens wil ik gewoon alles op slot kunnen doen als we straks ook het hekwerk hebben 

leuk dat we mensen kunnen vragen weg te gaan maar we kunnen niks doen als ze nee zeggen elke keer weer maar we zijn daar klaar mee en politie bellen heeft geen zin

We willen alle deuren dicht als er iemand aan de balie wil komen dan kan die zich melden bij personeel die zal dan zorgen dat de mensen naar binnen kunnen we hebben geen lobby voor bezoekers het is puur een lobby voor klanten die we willen ontvangen en worden dus altijd begeleid door personeel

@Attomn

**Comment by Attomn** [comment]
Ik zal vannacht of morgen even kijken naar de sloten. Gezien Kenneth even afwezig is denk ik niet dat er hekken gaan komen de aankomende tijd. Heb überhaupt geen idee of Kenneth speciaal een ymap hiervoor wilt gaan maken. Had je dit met hem besproken? @TedeaTaxi

**Comment by TedeaTaxi** [comment]
nee nog niet besproken
maar de hekken of afzetting is wel nodig vandaag was het weer raak mensen reden 3 personeel leden aan die meteen niet meer te redden waren 

de andere optie is de rode en groene garage toevoegen aan de taxi job zelf dat alleen taxi personeel het kan zien en gebruiken (in en uit dienst) dat zorgt er ook voor dat er geen mensen meer komen kloten met voertuigen op het terrein zelf

evt hoeven er geen hekken maar paaltjes en die on door dringbare onzichtbare muur kan ook maar dan moeten we even met Kenneth in gesprek

**Comment by Attomn** [comment]
Bespreek de hekken eerst even met Kenneth, dan regel ik die sloten en zien we dan wel later of de hekken daadwerkelijk van belang zijn.

**Comment by Attomn** [comment]
Sloten zijn toegevoegd, github issue is gesloten tot bevestiging vanuit Kenneth voor alle hekken. Ik neem aan dat jullie dit zelf regelen?
