### ISSUE TITLE
[FEATURE]: Aanpassingen / toevoegingen voor ANWB.

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1531]
### Contact Details

DeStefanoKiller#4442

### Beschrijf zo duidelijk mogelijk de feature

- [x] Er staan momenteel 2 menu's in waar je items kunt kopen (stock opnemen en koop items) graag stock opnemen weghalen zodat het overzichtelijker is.

- [x] Koop items een prijs geven:
Brood €4
Water €3
Zaklamp €50
Andere items blijven gratis.

- [x] 5 minuten delay voordat een melding naar ANWB weer mogelijk is nadat jij een melding hebt gemaakt.
- [x] Zelfde omkleed cirkel die bij basic-fat is (Waar jij je opgeslagen kleding kan aantrekken) ook in het ANWB omkleedhok neerzetten zie screenshot naar coords>
![Screenshot_2](https://user-images.githubusercontent.com/68514420/180659233-74c7cc25-d203-477e-95a0-faf72e4bf69a.png)

- [x] Pinautomaat toevoegen op ANWB HB bij de balie onder de televisie. (Als het mogelijk is zie screenshot voor coords) 
![Screenshot_1](https://user-images.githubusercontent.com/68514420/180659035-5bc6834d-8c73-4287-bd27-772bb967bb0d.png)

- [x] Tundra snelheid verhogen naar 220.

### Wat lost deze feature op?

-

**Comment by niekschoemaker** [comment]
@DeStefanoKiller Waarvoor is de anwb op het moment geld nodig? Of is het vooral voor geld storten?

**Comment by Attomn** [comment]
Kijkend naar de Tundra: Deze gaat op de weg nog niet eens 200. Waarom zou deze überhaupt 200 offroad moeten gaan gezien dit compleet onrealistische snelheden zijn offroad voor een ANWB..

**Comment by DeStefanoKiller** [comment]
> @DeStefanoKiller Waarvoor is de ATM op het moment nodig? Is het vooral voor geld storten?

@niekschoemaker deze is inderdaad bedoeld voor geld storten.

**Comment by Attomn** [comment]
Oke, dan ga ik dat even aanpassen betreft de Tundra.

Als er een pin automaat komt bij de ANWB, komt deze buiten op de hoek van het gebouw te staan ipv binnen zodat er geen dikke groepen binnen komen enkel om te pinnen.

**Comment by Chang-nl** [comment]
Ik heb voor nu een atm neergezet buiten om de hoek voor de ingang
