### ISSUE TITLE
[FEATURE]: Vereiste agenten voor juwelier overvallen naar 5 zetten

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1533]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel staat dit aantal op 4 werd mij verteld door een developer (mocht dit hoger zijn dan vervalt deze aanvraag). Graag zouden we dit naar 5 verplaatst zien.

### Wat lost deze feature op?

Met vier agenten heb je simpelweg nooit genoeg voor een juwelieroverval. Je hebt een OVD of OPCO die in porto 1 blijft, dus nog maximaal drie agenten over waarvan eentje achterblijft voor de gegijzelden. Dan heb je twee agenten in totaal nog beschikbaar voor een achtervolging of eventuele andere taken. Met vijf agenten blijft dit nog steeds erg krap maar is het iets beter te doen en is het alsnog laag genoeg zodat het de criminelen niet hindert.

**Comment by niekschoemaker** [comment]
Is aangepast
