### ISSUE TITLE
[FEATURE]: Narcos rang veranderen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1534]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

De rang Jefe is de enige rang die bevoegd is tot alles binnen Narcos. Dan heb ik het over de werknemers lijst bekijken, mensen aannemen en het geld pakken uit de bazenpot. Ik wil graag dat Capitan precies hetzelfde kan als de Jefe rol. Zodat er verschillende mensen hetzelfde kunnen als ik (Jefe).

### Wat lost deze feature op?

Dat er meer variatie komt binnen Narcos.

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart.
