### ISSUE TITLE
[EUP]: Ambulance kleding fixes

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1535]
### Contact Details

Attom#3152 / Ambulance Leiding

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

**OVD-G Kleding Dames**
Momenteel hebben de dames geen OVD kledij, deze is wel van belang.

**MMT Broek graag terug Rood ipv Oranje**
De MMT broek is momenteel Oranje IPV rood, matchen niet met elkaar. 
![afbeelding](https://user-images.githubusercontent.com/69365961/180989604-ce0b48e9-ca9a-4965-beb4-3d2690a4b361.png)

**MMT Arts en Ceremoniemeester man kaal?**
Bij het pakket van MMT ARTS en Ceremoniemeester als man zijnde, wordt je kaal.
![afbeelding](https://user-images.githubusercontent.com/69365961/180993963-d7d6e8aa-aabc-4f8a-a701-f96f72a06f1e.png)

**Rangen achterop de standaard outfit**
Zoals voorheen, een klein strookje met de rank achterop de kledij. Dit liep tot Geneeskundige.
![afbeelding](https://user-images.githubusercontent.com/69365961/180990109-cf0e0bb0-6973-4514-bdb8-7cda5163f397.png)

**Man en vrouwen kleding categoriseren in /eup zoals voorheen**
Momenteel staat alle kledij door elkaar waardoor je perongeluk op vrouwen kleding kan klikken terwijl je een man bent.
![afbeelding](https://user-images.githubusercontent.com/69365961/180989900-36c15df7-65c4-46db-8fd5-2f64377f2c65.png)

**Comment by walvisgedaan** [comment]
- [ ]  OVDG outfit vrouwen

- [ ]  MMT outfit maken/kleur aanpassen (man/vrouw)

- [ ]  Mannen en vrouwen kleding weer afzonderlijk van elkaar in de UI zetten

Er gaan geen rangen op shirt's komen aangezien dit in het echt ook niet zo is.

**Comment by Chang-nl** [comment]
@walvisgedaan 

> * [ ]   OVDG outfit vrouwen
> * [ ]   MMT outfit maken/kleur aanpassen (man/vrouw)
> * [ ]   Mannen en vrouwen kleding weer afzonderlijk van elkaar in de UI zetten
> 
> Er gaan geen rangen op shirt's komen aangezien dit in het echt ook niet zo is.

**Comment by walvisgedaan** [comment]
> @walvisgedaan
> 
> > * [ ]    OVDG outfit vrouwen
> > * [ ]    MMT outfit maken/kleur aanpassen (man/vrouw)
> > * [ ]    Mannen en vrouwen kleding weer afzonderlijk van elkaar in de UI zetten
> > 
> > Er gaan geen rangen op shirt's komen aangezien dit in het echt ook niet zo is.

?

**Comment by walvisgedaan** [comment]
Mannen en vrouwen staan nu weer in verschillende categoriën.

**Comment by DevvTDA** [comment]
Commit aangemaakt moet enkel doorgepushed worden naar mainserver ( kleur broek veranderen )

**Comment by DevvTDA** [comment]
- [ ]  OVDG outfit vrouwen

- [x]  MMT outfit maken/kleur aanpassen (man/vrouw)

- [x]  Mannen en vrouwen kleding weer afzonderlijk van elkaar in de UI zetten

- [ ] MMT Arts en Ceremoniemeester man kaal aanpassen naar normaal

Er gaan geen rangen op shirt's komen aangezien dit in het echt ook niet zo is.

**Comment by DevvTDA** [comment]
Alles is gefixt
