### ISSUE TITLE
[Bug]: Longfin anker

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1536]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je met je longfin op eiland stilstaat op het water en je gaat ervan af, vaart je boot automatisch weg, en de anker is ook los gelaten automatisch, persoonlijk denk ik dat de anker van de longfin stuk is op eiland.

### Wat hoorde er te gebeuren?

je boot hoort stil te zitten.

### Wat veroorzaakt de bug?

anker die gebugd is denk ik persoonlijk?

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Dit is ondertussen opgelost door niek.
