### ISSUE TITLE
[Bug]: Ambulance brancard

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1537]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Er zit iemand op je brancard en stopt de brancard met een persoon erop in de offroad ambulance val je eruit.

### Wat hoorde er te gebeuren?

je hoort niet uit de ambulance gelijk te vallen.

### Wat veroorzaakt de bug?

1. Je pakt een brancard
2. je zet je patient op de brancard
3. je gaat  rustig naar je ambulance en doet /rdoors
4. je zet de brancard in de ambulance met de patient erin
5. patient valt automatisch van de brancard af en glitched uit de ambulance

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Attomn** [comment]
Opgelost, vanaf nu is de keybind om iemand op en van de brancard te halen verplaatst naar toets [C]
