### ISSUE TITLE
[Bug]: Voertuigen in het water in beslag nemen werkt niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1538]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Een persoon rijdt zijn voertuig in het water, de takelwagen van de politie vist het voertuig uit het water en rijdt vervolgens naar Politie HB met het voertuig. Haalt het voertuig van de takelwagen af en het voertuig zelf kan niet bewogen worden en er moet een staff lid komen om hem in beslag te nemen via de database etc.

### Wat hoorde er te gebeuren?

Mij lijkt me dat je het voertuig kan laten bewegen door te rijden, maar je kan niet instappen.

### Wat veroorzaakt de bug?

1. Je rijdt een random voertuig in het water
2. Sleepwagen van de politie vist het voertuig uit het water
3. Je rijdt naar de HB in beslagname cirkel 
4. Je haalt het voertuig van de sleepwagen af
5. Voertuig die getakelt was kan niet bewogen worden.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t.

**Comment by Chang-nl** [comment]
Je kan voortaan voertuigen die in het water zijn geweest duwen
