### ISSUE TITLE
[FEATURE]: Boten die op land zijn 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1539]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Boten die op land zijn kan je sindskort duwen, maar je kan niet naar links of rechts gaan tijdens het duwen.
Is het mogelijk om naar links of naar rechts te kunnen sturen zoals bij auto's wanneer ze kapot zijn?

### Wat lost deze feature op?

Geen reports over boten die op land zijn, mensen kunnen verder gaan zonder een staff lid.

**Comment by Chang-nl** [comment]
Nee dit is niet mogelijk
