### ISSUE TITLE
[FEATURE]: Zoekfunctie toevoegen bij contacten in Telefoon

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1540]
### Contact Details

Bas#6430

### Beschrijf zo duidelijk mogelijk de feature

**Omschrijving**
Als speler wil ik in mijn telefoon tussen mijn contacten kunnen zoeken om zo een bepaald contact snel te kunnen bellen of smsen.

**Acceptatiecriteria**
- Een knop toevoegen 'Contact zoeken' onder de knop 'Contact toevoegen'.
- Wanneer je op 'Contact zoeken' drukt moet er een textfield in je UI komen.
- Wanneer je de zoekterm hebt ingevuld, worden alle overeenkomende contacten getoond. Voorbeeld:
   - Zoekterm: bas
   - Contacten: 
      - Bas Croissant
      - Piet Bas
      - Piet Basis
      - Bastiaan Vlees
      - Vleesbas Kaas
- Wanneer je op een resultaat klikt, krijg je de opties:
   - Bellen
   - Stuur een bericht
   - Contact aanpassen
   - Contact verwijderen

### Wat lost deze feature op?

Wanneer ik als speler veel contacten heb, en ik wil snel iemand opzoeken om te bellen, wil ik kunnen zoeken tussen al deze contacten. Zo kan ik door middel van korte zoektermen snel een persoon vinden tussen mijn contacten.

**Comment by Attomn** [comment]
#1125 , Wellicht voortaan eerst even dubbel checken of er geen eerdere github issues betreft hetzelfde gemaakt zijn 😛
