### ISSUE TITLE
[FEATURE]: Een optie om de maze bank garage te verkopen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1542]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk om een optie te krijgen om je maze bank garage te kunnen verkopen? 
Je zal net zoals bij appartementen 80% terug krijgen lijkt me de beste optie ook. 

### Wat lost deze feature op?

Zelfde als appartement, als je hem niet meer wilt kan je hem verkopen en krijg je 80% terug van je geld.

**Comment by Chang-nl** [comment]
Na herstart zit het erin!
