### ISSUE TITLE
[Bug]: Verklaar dood f6

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1545]
### Contact Details

Wilma Wonka#4312

### Wat gebeurde er?

Graag zouden we de verklaardood knop in het f6 menu van de Ambu weg willen hebben in het menu.

Want elke keer als we die knop gebruiken verdwijnen mensen onder de map en komen dan niet op de begraafplaats uit.

We weten niet hoe dat komt helaas.

### Wat hoorde er te gebeuren?

Er was ons uitgelegd als je de verklaardood knop gebruikt in het f6 menu dat de mensen gelijk bij de begraafplaats komen. Maar dat blijkt niet te werken helaas.

### Wat veroorzaakt de bug?

Je gaat in dienst bij de ambu en gaat het f6 menu in en je mag random ff iemand testen om de verklaardood knop uit te testen dan kan je het zelf ook even zien wat er gebeurd. En dan kunnen jullie zelf kijken hoe en wat veder. Maar het liefst willen we hem weg hebben tenzij het gefixt kan worden.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Welk command gebruiken jullie normaal om iemand bij de begraafplaats te krijgen dan? Want achter de schermen voert die knop gewoon /verklaardood uit als ik me niet vergis

**Comment by niekschoemaker** [comment]
De knop zelf is gefixed, dus de lijk zak werkt weer.
