### ISSUE TITLE
Bug : Eup dames Kmar

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1546]
Kleding bugs:

Steekvest werkt niet, is nu een porto.

3e klasse: ANWB broek
Vanaf 2e klasse: groene broek

**Comment by walvisgedaan** [comment]
Ik ga er naar kijken

**Comment by Ljosfari** [comment]
was dit nog gelukt ?

**Comment by Ljosfari** [comment]
is gefixed
