### ISSUE TITLE
[Bug]: BUG /GIJZEL, /TH, /Takehostage

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1547]
### Contact Details

[TDA] Johnny Flodder#3559

### Wat gebeurde er?

Als je iemand /gijzel of /th of /takehostage pakt dan kan je hem niet meer met C weg duwen dus alleen dood schieten 

### Wat hoorde er te gebeuren?

Dat je twee opties hebt, ( doodschieten of loslaten ) alleen werken de beide opties niet.

### Wat veroorzaakt de bug?

Dat een bepaalde animatie niet werkt in een scenario. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

https://medal.tv/games/gta-v/clips/uW9mR4dZOVgqR/d1337YNxHfnE?invite=cr-MSxlTEEsMjExNDkyMzIs
Geen f8 errors bekend.

**Comment by JohnnyFlodder** [comment]
Zelf even getest in de main maar het doodschieten met ( G ) werkt inderdaad niet.
Persoon blijf in leven, persoon loslaten ( C ) werkte wel bij mij.

**Comment by niekschoemaker** [comment]
Is mogelijk gefixed na volgende herstart.

fivem_server@25c5cdafd93536cc3df3dbe9ebd63d548826d1a4

**Comment by Chang-nl** [comment]
Zojuist in de main getest, Alles werkt weer naar behoren!
