### ISSUE TITLE
[FEATURE]: kleine wapens (pistols) van 2 naar 3 clips opzak

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1548]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Is besproken in burgerraad overleg op 02/08/22

Is dit mogelijk ?

**Comment by niekschoemaker** [comment]
2 clips geeft je 36 * 3 kogels om te schieten, dus 108 kogels.
Als je na 108 kogels nog niet de mogelijkheid hebt om bij een voertuig te komen om daaruit clips te kunnen pakken dan weet ik het niet 🤔
