### ISSUE TITLE
[FEATURE]: moeglijkheid om voertuigen in de gangopslag een andere naam kunnen geven

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1549]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Is dit mogelijk ?

**Comment by niekschoemaker** [comment]
Gaat dit om de merk namen of om de voertuigen zelf?
En met hoe de data op het moment wordt opgeslagen is dit niet mogelijk, dus dan zou hier eerst een migratie overheen moeten gaan zodat ik naast het voertuig ook data van het voertuig op kan slaan.

**Comment by Nander0320** [comment]
Geen response
