### ISSUE TITLE
Glitch in vissen

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#155]
Vissen werkt qua de actie starten etc. alleen kunnen spelers de vissen niet binnenhalen nadat zij de melding krijgen dat ze op 1 moeten drukken.  Er gebeurt niks en ze krijgen niks in hun inventory. https://www.youtube.com/watch?v=G5PgNKWwPyk eventueel onderbouwend videomateriaal.

**Comment by Willem-Dekker** [comment]
zou je log bestanden kunnen bij voegen?

**Comment by Willem-Dekker** [comment]
Gesloten wegens gebrek aan logs
