### ISSUE TITLE
Bug: foullieren is niet meer mogelijk in een auto

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1550]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

Na de update met de emote bij het foullieren kan er niet meer in voertuigen gefouilleerd worden.

Je blijft dan in de emote zitten en 'valt' uit het voertuig.

Ik heb ook begrepen als je dit wel doet daarna langzaamaan stikt ?

### Wat hoorde er te gebeuren?

Eventueel een check of de persoon in een voertuig zit. Zo wel, geen emote.

Is dat mogelijk.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Fixed as of 88935ec1e9ce0428d4e81f66803703895c948096

stond poosje open, dus na volgende restart zou dit al gefixed moeten zijn
