### ISSUE TITLE
[FEATURE]: Staartnummer voor vlieginstructeurs

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1552]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Mensen met de rechten van vlieginstructeur, de toegang geven om van vliegtuigen en helikopters het serienummer af te lezen.

Dit kan met een command zoals /checkplate of /checkregistration.

### Wat lost deze feature op?

Zo kunnen de instructeurs goed handhaven op voertuigen die achtergelaten worden, crashen of die gecheckt moeten worden. Zo hoeft niet de politie met een F6 menu continue opgeroepen te worden.

**Comment by Chang-nl** [comment]
Zou je hier dan alleen de kentekenplaat willen krijgen of ook de naam van de eigenaar en de kentekenplaat?

**Comment by Chang-nl** [comment]
Je kan nu van het dichtsbijzijnde vliegvoertuig de kentekenplaat opvragen!
