### ISSUE TITLE
[Feature]: med system politie Kmar

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1553]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

De ambulancedienst kan (als het goed is) namelijk geen burgers helpen die of een headshot hebben, met meer dan 150 aangereden zijn/een ongeluk hebben of nul bloed hebben. Dat zou voor de politie en kmar hetzelfde moeten zijn lijkt me. 

Nu gebeurt het (onbedoeld) dat er burgers overeind geholpen worden die eigenlijk helemaal niet meer te redden zijn.

**Comment by Ljosfari** [comment]
![image](https://user-images.githubusercontent.com/97713942/183304391-92fd4851-7525-40c5-9057-28d5fbbf5de7.png)
dit zien alleen de ambulance, net als het bloed, en waar persoon geraakt is

**Comment by Chang-nl** [comment]
Gefixt na herstart!
