### ISSUE TITLE
[Bug]: Rare tp bug?

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1554]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Wij krijgen laatste tijd enorm veel reports dat mensen net in de stad komen en bij het gemeentehuis spawnen, terwijl ze totaal ergens anders zijn uitgelogd (voorbeelden: eiland, legerbasis). 
Kan er gekeken worden naar deze rare gebeurtenis ?

### Wat hoorde er te gebeuren?

je hoort terug te spawnen waar je laatst ben uitgelogd

### Wat veroorzaakt de bug?

bepaalde locaties volgens mij uitloggen, waar hij dat niet opslaat? 

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Is mogelijk gefixed, ik wacht nu tot iemand volledig ingeladen is voordat ik de coordinaten opsla, maar weet niet zeker of dit de fix is, dus graag even laten weten of het probleem na volgende herstart nog voorkomt.

**Comment by Attomn** [comment]
@CalRayy is dit opgelost?

**Comment by CalRayy** [comment]
Geen report erover gezien, dus ik denk het wel.
