### ISSUE TITLE
[Bug]: Wall glitch

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1555]
### Contact Details

dead123x5#1144

### Wat gebeurde er?

Er werd een report aangemaakt waarbij iemand bij plasmakart door een muur gelopen zou zijn en zo binnen was gekomen.
Hier ben ik naartoe gegaan en gelijk gevraagd waar de wall glitch zat. 

Hier een filmpje hoe het gebeurd;
https://streamable.com/kohc1a

### Wat hoorde er te gebeuren?

Je hoord niet door de muur heen te kunnen lopen.

### Wat veroorzaakt de bug?

Waarschijnlijk een texure die niet goed afgewerkt is.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Attomn** [comment]
is bekend, kan weinig aan gedaan worden nu tot Kenneth weer aanwezig is en gaat kijken naar plasmakart, hier was hij al mee bezig dus voor nu sluit ik 'm en hopen we binnenkort een betere versie van plasmakart naar de stad te sturen.
