### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jensgr7** [Tedeapolis/development#1556]
### Contact Details

jens#6660

### Wat gebeurde er?

De nieuwe drugdelivery deepweb is gebugged het aantal letters is te lang waardoor je die niet kan invullen op je telefoon.

### Wat hoorde er te gebeuren?

Dat je niet een max heb kwa het aantal letters dat je kan invoeren of dat de deepweb van de drugdelivery een kortere naam krijgt

### Wat veroorzaakt de bug?

je krijgt de deepwebmelding als je slecht verkoopt maar je kan hem niet gebruiken omdat hij te lang is

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by CalRayy** [comment]
Is gefixt na de restart als het goed is door @Willem-Dekker
