### ISSUE TITLE
[FEATURE]: Upgraden van voertuigen verbeteren.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1557]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

Momenteel rijd u naar de modshop en kan je hier motor 1, 2, 3 en 4 op zetten. Daarbij beter je een bedrag hoe hoger hoe duurder. Maar ik zie graag dat je hier stage's in hebt. Dus als je motor 1 koopt word 2, 3 en 4 goedkoper want het bedrag wat je betaald voor motor 1 word er dan afgehaald voor motor 2, 3 en 4. Denk hierbij dus ook aan tweedehands auto's die dan ook in prijs stijgen als ze motor 1,2 of 3 hebben want niemand telt dat aantal meer als tune alleen maar als ze maxed out zijn op niveau 4 dus.

### Wat lost deze feature op?

Waardestijging van tweedehands auto's, meer handel mogelijkheden en betere gebruikerservaring.

**Comment by Chang-nl** [comment]
Na herstart zit dit erin!
