### ISSUE TITLE
[FEATURE]: DTMC rang aanpassingen

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1558]
### Contact Details

TFFT Mulli#2199

### Beschrijf zo duidelijk mogelijk de feature

Indien het mogelijk is, een aantal aanpassingen in de rangen binnen DTMC

**Name changes**
- [x] Name change | Support -> "Hangaround" (Hierbij heb je dus alleen sleutels van het pand)

**Nieuwe rangen**

- [x] Nieuwe rang | "Prospect 2" (zelfde permissies als full patch)
- [x] Nieuwe rang | "Head Enforcer" (zelfde permissies als full patch)

**Permissies aanpassing**
- [x] Permissies aanpassing | "Secretary" -> toegang tot alle wapens van wapeninkoop + wapens tunen toevoegen

De rangen krijg je dus uiteindelijk als: 

DTMC - Hangaround
DTMC - Prospect
DTMC - Prospect 2
DTMC - Full Patch
DTMC - Road Captain
DTMC - Enforcer
DTMC - Head Enforcer
DTMC - Treasurer
DTMC - Secretary
DTMC - Sergeant
DTMC - V.President
DTMC - President
DTMC - National President

### Wat lost deze feature op?

Aanpassing van de structuur, zodat de leden rechtsonderin de juiste rang hebben en de correcte permissies hebben

**Comment by Chang-nl** [comment]
Na de herstart zit het erin!
