### ISSUE TITLE
[EUP]: Volgorde heren EUP

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1559]
### Contact Details

Ljosfari#3575

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag de eup op deze volgorde rangschikken:

LICHTBLAUW
Marechaussee 3e klasse [xx-xx ❯]
Marechaussee 2e klasse [xx-xx ❯❯]
Marechaussee 1e klasse [xx-xx ❯❯❯]
Wachtmeester [xx-xx ❙❯]
Wachtmeester der 1e klasse [xx-xx ❙❯❯]
Opperwachtmeester [xx-xx ❙❯❯❯]
Adjudant [xx-xx ❙● ]

DONKERBLAUW
Tweede Luitenant [xx-xx ❃ ]
Eerste Luitenant [xx-xx ❃❃ ]
Kapitein [xx-xx ❃❃❃]
Majoor [xx-xx ❙❃ ]
Luitenant-Kolonel [xx-xx ❙❃❃ ]
Kolonel [xx-xx ❙❃❃❃]
Brigadegeneraal [xx-xx ❙✯ ]
Generaal-Majoor [xx-xx ❙✯✯ ]
Luitenant-Generaal [xx-xx ❙✯✯✯]

**Comment by niekschoemaker** [comment]
Wat betekent de LICHTBLAUW en DONKERBLAUW precies in deze issue?
Willen ze dat er 2 extra categorieen gemaakt worden?

En staat de volgorde op het moment goed of moet de volgorde zelf ook aangepast worden?

**Comment by walvisgedaan** [comment]
> Wat betekent de LICHTBLAUW en DONKERBLAUW precies in deze issue? Willen ze dat er 2 extra categorieen gemaakt worden?
> 
> En staat de volgorde op het moment goed of moet de volgorde zelf ook aangepast worden?

Licht- / en donkerblauw gaat over de rang die op het shirt zit en hoeven NIET in aparte categoriën. Ik was in de veronderstellign dat het ook niet mogelijk is om volgorde aan te passen in de UI?

**Comment by niekschoemaker** [comment]
> > Wat betekent de LICHTBLAUW en DONKERBLAUW precies in deze issue? Willen ze dat er 2 extra categorieen gemaakt worden?
> > En staat de volgorde op het moment goed of moet de volgorde zelf ook aangepast worden?
> 
> Licht- / en donkerblauw gaat over de rang die op het shirt zit en hoeven NIET in aparte categoriën. Ik was in de veronderstellign dat het ook niet mogelijk is om volgorde aan te passen in de UI?

Feature heb ik recentelijk toegevoegd, je kunt nu een "index" field toevoegen wat de volgorde overschrijft.

Dus als je bij een outfit: index = 1, neerzet komt die helemaal bovenaan te staan, en wordt dan op volgorde gezet van laag naar hoog met de index nummers.

**Comment by walvisgedaan** [comment]
Wat een luxe zeg, dan ga ik dat vanmiddag aanpassen.
