### ISSUE TITLE
Ferrari Pista Spider en Lamborghini Aventador veranderen steeds van kleur en stickers.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#156]
Sinds de optimalisatie van de Ferrari Pista Spider en Lamborghini Aventador in de main zitten ondervinden mensen problemen met stickers en kleuren die steeds veranderen, zo heeft de Ferrari Pista Spider geen mogelijkheid meer om de kleur aan te passen maar krijg je steeds een random sticker.

Dit is een filmpje van Thomas L. betreft de Lamborghini Aventador: https://youtu.be/gA1v6a6xCh4

Daarnaast zijn er meerdere tickets geweest over de Ferrari pista spider met zijn stickers.

Ik weet persoonlijk niet wat het probleem is maar ik denk dat het ergens met de optimalisatie (resizen van de voertuigen) zit.

**Comment by Willem-Dekker** [comment]
is dit nogsteeds een probleem of niet?
