### ISSUE TITLE
[Bug]: EUP werkt niet als je in dienst de stad in komt

### ISSUE THREAD

**Issue by jeffdv** [Tedeapolis/development#1560]
### Contact Details

Jeffrey#0734

### Wat gebeurde er?

Ik probeer als agent een outfit te kiezen maar mijn EUP geeft mij geen mogelijkheid tot het kiezen van kleding

### Wat hoorde er te gebeuren?

Ik hoor kleding te kunnen kiezen.
Als je in en uit dienst gaat kan je het probleem omzijlen.

### Wat veroorzaakt de bug?

In dienst in de stad komen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog aangezien iedere agent het gebeurd, maar tegelijkertijd laag omdat er een work-around bekend is.

### Relevante log bestanden

https://imgur.com/a/DruI4qD

**Comment by Chang-nl** [comment]
Is opgelost!
