### ISSUE TITLE
[Bug]: Bazen kunnen geen rangen meer geven in de overheidsdiensten discord

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1561]
### Contact Details

Lamine#4904

### Wat gebeurde er?

Op het moment dat een overheidsbaas in de overheidsdiensten discord probeert om een rol te geven middels het slashcommand /role add, dan voert deze de actie niet uit en verschijnt er de error "De applicatie heeft niet gereageerd". 
![image](https://user-images.githubusercontent.com/71287080/184111440-ac4051ed-912d-4e5f-8376-9498e32656e5.png)

### Wat hoorde er te gebeuren?

In plaats van de error zou de bot de geselecteerde rol moeten toewijzen aan de gekozen speler.

### Wat veroorzaakt de bug?

1. Het command /role add intypen en een willekeurige rol geven aan een willekeurig persoon, die de rol nog niet heeft.
2. Het command uitvoeren.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by TDA-SanderD** [comment]
Is er wellicht iets van een fix toegepast? Het lijkt nu wel deels te werken, de applicatie reageert, maar een taxi baas krijgt dit bericht
![image](https://user-images.githubusercontent.com/71119665/187080578-ef5d74bb-821e-483e-9947-800b25273a5a.png)

**Comment by TedeaTaxi** [comment]
voor de taxi ligt deze prio best hoog  omdat we veel mensen inwerken en ontslaan 
vaak omdat we ook dus staff moeten vragen om voor ons te doen is vaak belastend voor hun
