### ISSUE TITLE
[Bug]: Slagbomen legerbasis geven instant een lampje

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1562]
### Contact Details

MickeyMorris#7393

### Wat gebeurde er?

Wanneer je bij de legerbasis aankomt, heb je aan beide kanten slagbomen.
Deze slagbomen gaan niet open totdat je lichtelijk met je voertuig deze slagbppm rijdt. Echter heeft deze slagboom een dermate grote impact dat je voertuig een lampje krijgt.

Ik geef hem de klassificatie hoog omdat de legerbasis controleren binnen het takenpakket valt van de kmar en er dagelijks heel veel eenheden last ondervinden van het feit dat hun voertuig niet meer inzetbaar is.

### Wat hoorde er te gebeuren?

Of de schade van de slagbomen naar 0 zetten, of de slagbomen verwijderen/ andere toepassng neerzetten

### Wat veroorzaakt de bug?

De slagbomen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Oke en met wat voor snelheid knallen jullie de legerbasis in? En uberhaupt als je een lampje krijgt wanneer je tegen een slagboom aan rijd dan was je voertuig daarvoor al beschadigd. Er is al flink getest voor dit en het doet echt zo goed als geen/geen schade wanneer je er tegen aan rijd.

**Comment by dilyano** [comment]
@Chang-nl momenteel pak ik de slagboom met 3 km/h en dan gebeurd het vandaar dit issue. Dit gebeurde voorheen ook bij de helipads, vandaar dat ze daar ook weg zijn. Hier moet wel echt iets aan gebeuren.

**Comment by Chang-nl** [comment]
Is gefixed na de herstart. De slagbomen zouden nu om en nabij geen schade meer doen.
