### ISSUE TITLE
[FEATURE]: Flitspaal op great ocean Hightway Route 1

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#1563]
### Contact Details

MickeyMorris#7393

### Beschrijf zo duidelijk mogelijk de feature

ook Een flitser toevoegen aan de andere kant van de weg, (MILE 06 paal) 

### Wat lost deze feature op?

Dat mensen niet met 300 in tegengestelde richting gaan rijden om de flitpaal te ontwijken. Dit veroorzaakt veel dode/gewonden en auto wrakken.

**Comment by Chang-nl** [comment]
Na herstart zit dit erin!
