### ISSUE TITLE
[Bug]: ANPR werkt niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1564]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De ANPR werkt niet, en politie en KMAR denken dat express was, zou dit bekeken kunnen worden (moest een github maken van misstake).

### Wat hoorde er te gebeuren?

ANPR hoort te werken.

### Wat veroorzaakt de bug?

geen idee.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

/

**Comment by niekschoemaker** [comment]
Dit zou ondertussen gefixed moeten zijn, in elkgeval op de dev server

**Comment by Attomn** [comment]
@CalRayy is dit zo?

**Comment by CalRayy** [comment]
> @CalRayy is dit zo?

Ik heb nog niet nagevraagd bij de politie, maar er was een agent die zei van ja twee maanden geleden hadden we de anpr jammer dat het weg is. Dus ik zei hoezo is die weg, hij zei idk die is plots weg en ik zei denk dat het een bug is, nagevraagd bleek inderdaad een bug te zijn.
