### ISSUE TITLE
[Bug]: Slagbomen bij eiland geeft bijna instant een lampje

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1565]
### Contact Details

CalRay#1513

### Wat gebeurde er?

![image](https://user-images.githubusercontent.com/101106299/184215813-6ad8430d-cc83-4d67-ba43-2ea340836bc8.png)
![image](https://user-images.githubusercontent.com/101106299/184215854-cc886af7-2c61-4f0d-933e-46ce97654c55.png)
Deze slagbomen gaan niet open totdat je lichtelijk met je voertuig deze slagboom rijdt. Echter heeft deze slagboom een dermate grote impact dat je voertuig een lampje krijgt.

Er gaan dagelijks heel veel mensen erdoor heen en vinden dit zeer vervelend omdat je constant een repair kit nodig hebt en die kan breken, waardoor je terug naar land moet gaan.

### Wat hoorde er te gebeuren?

Of de schade van de slagbomen naar 0 zetten, of de slagbomen verwijderen/ andere toepassng neerzetten

### Wat veroorzaakt de bug?

De slagbomen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is als t goed is gefixed, zo niet dan pech gehad, want heb deze issue al 10x eerder voorbij zien komen.
