### ISSUE TITLE
[Bug]: Witwas inlever cirkel niet zichtbaar

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1566]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

https://youtu.be/Q9Z6j4C2OQ8

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

**Comment by niekschoemaker** [comment]
Zou na volgende restart gefixed moeten zijn.

**Comment by niekschoemaker** [comment]
In elkgeval, op dev server was het gefixed maar weet niet zeker of dit om dezelfde issue ging, dus zou even aangekeken moeten worden.

**Comment by Tom974** [comment]
was vandaag bij mij in ieder geval weer zichtbaar 
![image](https://user-images.githubusercontent.com/55812394/184974341-123652c0-28e9-4a57-9dd8-56642497cd42.png)

**Comment by Chang-nl** [comment]
Super dankjewel voor het melden tom!
