### ISSUE TITLE
[BUG] deepweb drugs

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1567]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De deepweb is te lang van de drugs deepweb en geeft nu geen meldingen in de main server.

### Wat hoorde er te gebeuren?

Je hoort de deepweb te kunnen zien en in te kunnen typen aangezien de deepweb naam die je ontvangt te lang is.

### Wat veroorzaakt de bug?

Deepweb naam van de drugsmeldingen is te lang.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
