### ISSUE TITLE
[FEATURE]: Statistieken Ticket helper

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1568]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

Zelfde feature als voor andere staff-leden om ticket statistieken te kunnen krijgen.

### Wat lost deze feature op?

Dan krijgen ticket helpers ook hun stats te zien.

**Comment by Streamcentralrulez** [comment]
Graag toekennen aan Willemde20 (is overlegt met willem)

**Comment by Willem-Dekker** [comment]
done
