### ISSUE TITLE
[Bug]: enorme Dsync in bullets 

### ISSUE THREAD

**Issue by Jensgr7** [Tedeapolis/development#1569]
### Contact Details

jens#6660

### Wat gebeurde er?

{voorbeeld 1
https://streamable.com/278vmu

https://streamable.com/xm5k7l

(voorbeeld 2)
https://streamable.com/3kw5as 

(voorbeeld 3)
https://www.youtube.com/watch?v=gWNVt1Qhabo

https://streamable.com/nawzkz

In deze 2 clips zie je dat het schieten voor geen meter klopt op het moment, Er zit super veel dsync in.

### Wat hoorde er te gebeuren?

Dat er geen Dsync plaatsvind in het schieten met wapens

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by CalRayy** [comment]
Is gefixt na de restart

**Comment by Chang-nl** [comment]
Is ondertussen opgelost!
