### ISSUE TITLE
[FEATURE]: Eigen voertuig gebruik witwas (Burgerraad)

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1570]
### Contact Details

maxjuh97#7233

### Beschrijf zo duidelijk mogelijk de feature

Vanuit burgerraad meegekregen om hiervoor een github issue aan te maken.

Functie toevoegen aan het huidige witwas systeem om je eigen bus te selecteren wanneer je wilt starten met witwassen, op dit moment krijg je altijd een busje van het depot en kun je dus niet je eigen witwasbusje gebruiken. Dit kon je echter in het verleden wel, maar nu dus niet meer.

### Wat lost deze feature op?

Momenteel kun je je eigen busje gebruiken, maar je moet eerst een busje van het depot pakken, deze wegzetten en dan weer in je eigen busje gaan rijden. het zit er dus in principe half half in, maar het zou veel gemakkelijker gaan op deze manier (en sneller).

**Comment by niekschoemaker** [comment]
Heb het getest op dev server, en ik kan daar gewoon op "Persoonlijk voertuig gebruiken" klikken.
Echter met het starten via banen is dit geen optie, en dit is by design.
