### ISSUE TITLE
[FEATURE]: Aanpassing boetes 

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1571]
### Contact Details

Lamine#4904

### Beschrijf zo duidelijk mogelijk de feature

Aanpassing van de volgende verkeersboetes in het F6-boetemenu van de politie/KMar in-game:
- Rijden zonder kentekenplaten van €840,- naar €10.000,-
- Geblindeerde ramen van  €690,- naar €7.500,-
- Verlichting(NEON) onder het voertuig van €690,- naar €2.500,-

https://github.com/Tedeapolis/wet-en-regelgeving/pull/341

**Comment by Willem-Dekker** [comment]
fixed na restart
