### ISSUE TITLE
[FEATURE]: Voertuigen zonder kenteken niet laten zien via snelheidmeter/kloksysteem

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1572]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk dat je voertuigen zonder een kenteken niet kunt traceren via het snelheidsmeter/kloksysteem?
Waarom zou je dit willen? Heel veel mensen maken misbruik van deze systeem en zoeken dan ook gelijk op van wie die is etc.
Terwijl er eigenlijk geen kenteken op zit, weet degene toch toevallig je naam en kenteken etc. 

### Wat lost deze feature op?

Minder misbruik van het systeem, zoals ik hierboven heb uitgelegd.

**Comment by Willem-Dekker** [comment]
is technisch niet mogelijk, tenzij er een lijst is met auto's en kentekens (Mods)
