### ISSUE TITLE
[FEATURE]: Optie om je huurwoning om te zetten naar een een koopwoning

### ISSUE THREAD

**Issue by Chang-nl** [Tedeapolis/development#1573]
### Contact Details

Chang#0001

### Beschrijf zo duidelijk mogelijk de feature

Mogelijkheid om je huurwoning direct vanuit het entrance menu over te schakelen naar een koopwoning.

### Wat lost deze feature op?

Onnodig wachten voordat je nieuwe huis woonklaar is gemaakt.

**Comment by Nander0320** [comment]
Not planned
