### ISSUE TITLE
[FEATURE]: extra melee wapens, bottle en dagger toevoegen.

### ISSUE THREAD

**Issue by Chang-nl** [Tedeapolis/development#1575]
### Contact Details

Chang#0001

### Beschrijf zo duidelijk mogelijk de feature

De bottle en dagger toevoegen als beschikbare melee wapens.

**Comment by Attomn** [comment]
Bottle is al eens besproken en zou er in komen. #881

**Comment by Chang-nl** [comment]
Na herstart is het toegevoegd!
