### ISSUE TITLE
[FEATURE]: Alleen eigenaren kunnen voertuigen hun tunes eraf halen

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#1576]
### Contact Details

Joris#0875

### Beschrijf zo duidelijk mogelijk de feature

Met deze feature zorg je ervoor dat niet mensen hun auto's worden gesloten en dan alle tunes worden vanaf gehaald. Zo verlies je ineens heel veel geld.

### Wat lost deze feature op?

Dat mensen niet auto's gaan stelen en alle tunes eraf gaan halen om te kut

**Comment by Chang-nl** [comment]
Prijs van downgraden tunes is nu weer de volle mep dus zoals het was.
