### ISSUE TITLE
[FEATURE]: Uitbraakmelding

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1578]
### Contact Details

Lamine#4904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens het staffoverleg is goedgekeurd dat er 5 minuten na een uitbraak een melding naar de KMar gestuurd wordt met iets in de richting "Na de uitbraak zojuist hebben we alle hoofden geteld. We zien dat "naam uitgebroken persoon" mist. Kunnen jullie een signalering regelen?".

### Wat lost deze feature op?

Dat de KMar geen inzicht heeft in wie er uitgebroken wordt. Realistisch gezien wordt er namelijk een lijst bijgehouden met alle gevangenen en kan er bepaald worden wie er uitgebroken is.

**Comment by Ljosfari** [comment]
fixed
