### ISSUE TITLE
[FEATURE]: Narcos ingame naam veranderen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1579]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

De foto hieronder zie je de ingame naam van Narcos. Wat wij veranderd willen hebben is dus plaats van Narcos - Jefe willen we Narcos Cartel - Jefe. 
![unknown](https://user-images.githubusercontent.com/104857888/185811850-98177177-e4fe-47be-9301-9a15bfc14c04.png)

### Wat lost deze feature op?

Zo laten we ons Cartel thema beter zien in alles wat we doen.

**Comment by Willem-Dekker** [comment]
fixed na restart
