### ISSUE TITLE
[FEATURE]:  /maxupgrades in de test stad 2.0

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1580]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In staff overleg hadden we besproken om de commando /maxupgrades toegankelijk te maken voor iedereen in de test stad.
Is het mogelijk om deze commando voor iedereen toe te staan in de test stad?

Deze commando kan je niet momenteel.

### Wat lost deze feature op?

mensen zouden dit graag willen en je verspilt geen tijd aan tunes

**Comment by Chang-nl** [comment]
Mogelijk na volgende herstart gefixed

**Comment by CalRayy** [comment]
> Mogelijk na volgende herstart gefixed

Ik kreeg te horen, dat helaas nog niet werkt.

**Comment by Chang-nl** [comment]
Bedankt voor het aanmaken van deze feature request. Na herstart is de feature doorgevoerd!
