### ISSUE TITLE
[Bug]: /charselect is bugged

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1581]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Er is een bug met /charselect als je je mannelijke character select, terwijl je een vrouw bent kan je geen man weer worden of dergelijke. Zie screenshot:
![image](https://user-images.githubusercontent.com/101106299/186131059-92736375-7c8c-49e3-846e-461cd3b221b1.png)
Zoals je ziet heeft deze persoon twee characters, 1 is een man en 1 is een vrouw. Als hij de man selecteert en relogt blijft hij een vrouw. Zijn mannelijke character is weg en dit geval heb ik ook bij iemand anders gezien, dus dacht ik meld het.

### Wat hoorde er te gebeuren?

Als je een mannelijke character selecteerd hoor je een man te zijn na het reloggen.

### Wat veroorzaakt de bug?

Geen idee, eigenlijk.
1. selecteer de mannelijke character
2. reloggen
3. logt in en blijft een vrouw

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

geen

**Comment by Chang-nl** [comment]
Na herstart gefixt!
