### ISSUE TITLE
[FEATURE]: request_cuff shortcut commando toevoegen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1583]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Je kan met de shortcut /rs iemand snel fouilleren, alleen met de nieuwe request_cuff commando is er geen shortcut en moet je dit volledig uittypen. Mij leek het handig en chill om van request_cuff ook een shortcut commando te maken bijvoorbeeld: /rc

### Wat lost deze feature op?

Minder typen, handig en lijkt me chill

**Comment by Willem-Dekker** [comment]
bespreken in staffoverleg graag
