### ISSUE TITLE
[Bug]: /togglehud off zie je je gps nog

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1584]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als /togglehud off doet hoor je je gps ook niet meer te zien, alleen die zie je wel. 
zie screenshot: 
![image](https://user-images.githubusercontent.com/101106299/186485673-7ef09b8c-8937-440b-acda-d2c92732f836.png)

### Wat hoorde er te gebeuren?

je hoort je gps niet te zien.

### Wat veroorzaakt de bug?

geen idee

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

**Comment by ARJ3N** [comment]
Komt omdat jij je playerradar aan hebt staan.

**Comment by CalRayy** [comment]
> ### **[ARJ3N](/ARJ3N) ** commented [44 seconden geleden](#issuecomment-1226353834)

oh serieus ?

**Comment by Willem-Dekker** [comment]
Het is je player radar
