### ISSUE TITLE
[FEATURE]: Aanpassing Rangen 14K

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#1586]
### Contact Details

MassiveR3T4RD#1741

### Beschrijf zo duidelijk mogelijk de feature

Zouden er wat dingen aangepast kunnen worden binnen onze organisatie kwa rangen, als dit mogelijk is,

**Nieuwe rangen**
- [x] Nieuwe rang | Purple Claw  ( 紫爪 ''ingame rang'' ) -  '' Zelfde als red pole(mafia 500)''  ( Toegang tot F6 & Opslag ( auto & huis )

**Permissies aanpassing**
- [ ] Permissies aanpassing | non-member(mafia 0) - Toegang tot "Armory" -> wapens opslaan, objecten opslaan en Item Winkel
- [ ] Permissies aanpassing | White paper Fan(mafia 700)  -  '' zelfde als Mountain master(mafia 900)''  ( Ook toegang tot de wapeninkoop + het Tunen & Gang Heli )
- [ ] Permissies aanpassing | Straw Sandal(mafia 600)  -   '' zelfde als Mountain master(mafia 900)''  ( Ook toegang tot de wapeninkoop + het Tunen )

**De rangen op een volgorde.**
1. 14k - Non-Member 
2. 14k - Rice Picker
3. 14k - Blue Lantern 
4. 14k - Red Pole 
5. 14k - Purple Claw - nieuwe rang
6. 14k - Straw Sandal
7. 14k - White Paper Fan
8. 14k - Mountain Master
9. 14k - Dragonhead

### Wat lost deze feature op?

Breder keuze kwa rangen en permissies, en beter structuur. (Besproken met Clay, github namens hem)

**Comment by RyanBoersma** [comment]
Purple claw is toegevoegd (grade 550) aan rangen en gelijkgetrokken met Red pole. Verzoek tot aanpassen van non-members is afgewezen want het zijn hangarounds en de afspraak is dat zij geen enkele toegang gaan krijgen tot verdere gangrechten. 
Permissies van White Paper fan en Straw Sandal zijn gelijkgetrokken met Mountain master. Het verzoek tot helikopter toegang is afgewezen aangezien die alleen voor boss en op een na hoogste beschikbaar blijven.

**Comment by timfloors** [comment]
We zitten met proefmensen die zich al redelijk bewezen hebben dus deze willen we meer rechten geven daarom deze aanvraag.

- [ ] Naam verandering rang non-member(mafia 0) -> "閒逛"
- [ ] Rang tussen non-member(mafia 0 en rice picker(mafia 100) genaamd(grass picker) -> "撿草機" | toegang tot armory hierin wapens opslaan, objecten opslaan, item winkel en voertuigen cirkel

**Comment by niekschoemaker** [comment]
Moet de nieuwe rang grass picker ook bij de garage kunnen of niet?

**Comment by Nander0320** [comment]
Geen reactie meer mogen ontvangen, Mocht het nog nodig zijn open dit even opnieuw
