### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by Kenjikuhh** [Tedeapolis/development#1587]
### Contact Details

Kenji D.#0001

### Kenteken van voertuig

N.V.T

### Voertuig model

Bestel Bus

### Omschrijf de bug

Bij het witwassen druk je eerst "Laad truck in", daarna ga je naar een andere cirkel om een locatie te krijgen. Maar als je daar over rijd, staat er "Je hebt al een bus geleverd gekregen". Wat niet klopt...Maar als ik mijn shift eindig en opnieuw start dan werkt het wel. Ik heb dit altijd wanneer ik wil witwassen. 

Foto= https://imgur.com/a/14O4Xzh

### Repro

Zie hierboven^^

### Normaal gedrag

Dat je over de 2de cirkel rijd en gelijk je locatie kan krijgen en niet je shift moet eindigen en opnieuw moet proberen.

**Comment by Ljosfari** [comment]
je moet dan gewoon even naar de andere cirkel en op voertuig inleveren drukken
