### ISSUE TITLE
[FEATURE]: Opbrengst inbreken huizen

### ISSUE THREAD

**Issue by mamalois** [Tedeapolis/development#1589]
### Contact Details

MamaLois#9805

### Beschrijf zo duidelijk mogelijk de feature

Na het staffoverleg is naar voren gekomen dat het inbreken in huizen te weinig verdiend. Je maakt hier vaker zelfs verlies op dan dat je er echt winst uit pakt. Hierom de github issue om de waardes/ kans ( op waardevolle items ) groter te maken als je inbreekt in een huis. 

### Wat lost deze feature op?

Meer mogelijkheden voor criminelen en meer roleplay mogelijkheden voor politie

**Comment by Attomn** [comment]
["speaker"] = 220,
	["laptop"] = 600,
	["toothpaste"] = 6,
	["ifruit"] = 400,
	["oldcoin"] = 130,
	["creditcard"] = 400,
	["rolex"] = 300,
	["omega"] = 250,
	["diamondring"] = 500,
	["ring"] = 150,
	["sojobeans"] = 20,
	["gpspill"] = 200,
	["wallet"] = 240,
	["console"] = 220,
	["tablet"] = 420,
	["treasuremap"] = 120,
	["dildo"] = 70,
	["pickledanimal"] = 80,
	["santashat"] = 260,
	["goldchain"] = 150,
	["goldbracelet"] = 150,
	["chocolate"] = 20,
	["tabacco"] = 30,
	["alcohol"] = 30,
	["gamingperipherals"] = 90,
	["passport"] = 300,
	["rarecoin"] = 240,
	["book"] = 50,
	["diamond"] = 600,
	["blurayplayer"] = 200,
	["rareornament"] = 200,
	["magazine"] = 40,
	["junk"] = 16,
	["phone"] = 500,
	["jewelry"] = random,
        ["drill"] = 7000,
        ["firebox"] = 2000
        
**Zou je hiermee zelf een leuk lijstje samen kunnen stellen? Dan kijk ik er later na.**

**Comment by Nander0320** [comment]
Opgelost
