### ISSUE TITLE
Puntjes Politie (Kijken wat haalbaar is)

### ISSUE THREAD

**Issue by Jesse-Poolman** [Tedeapolis/development#159]
- Mogelijkheid om een hek voor het HB te krijgen iedereen kan er nu in het bureau rijden, pakt jan en alleman maar hun auto bij ons achter weg, dit lijkt me niet helemaal de bedoeling dat spelers hun auto op Politie terrein kunnen pakken.

- Zou er gekeken kunnen worden naar een Politie boot? (Dit heeft verre van prioriteit nodig)

- Puntje voor Jasper (Meos) Er is huidig een tabje in Meos waar je je voor trainingen kunt aanmelden, Erg handig. Alleen het is misschien wat handiger en overzichtelijker als je jezelf hebt aangemeld of de training hebt afgerond dat er Aangemeld of Behaald hebt staan. Zodat je duidelijk kunt zien welke trainingen je al gedaan hebt en welke je nog niet gedaan hebt. Ook is het misschien handig dat er in Meos een tabje komt met Trainingen Agenda waarin je naast de discord melding ook een agenda hebt waar alle trainingen die ingepland staan ook kunt zien. Ook kun je er dan bijzetten door wie de training is ingepland en wie hem zal gaan geven (evt. voor eigen administratie). 

- Toevoegen dat je in MEOS kan zien welk voertuig bij het kenteken hoort. Kan je nu niet zien

- Akkoord van hogeraad Extra discord voice channel genaamd Koppel prio. zodat als er twee overvallen zijn je deze apart kunt koppelen en porto 1 clean kan houden om te surveilleren, en zo portprotocol maximaal te kunnen behouden. Ook is het handig om mensen die een achtervolging hebben in een aparte porto te kunnen zetten als de prio bezet is voor snelle communicatie zonder het verstoren van portprotocol in porto 1 door statusupdates naar gekoppelde eenheden te geven in deze extra porto, ook kun je dit apart in delen naast de extra Koppel Prio door een achtervolging porto te maken, zodat het overzicht ook duidelijk blijft voor de OVD als het druk is.

- Filtsmeldingen er uit halen. Ze hebben zeer weinig functie op dit moment. Dus kunnen ze er beter tussen uit.

- ANPR hit. flitsers vervangen voor ANPR camera's zodat als er een auto langs rijd van iemand die gezocht wordt dat we een ANPR hit krijgen. Deze hits zijn ook zelf toe te voegen

- Optie om de warmte beelden weer terug te brengen in de zulu. We hebben nu zeer weinig tot geen zicht in het donker, kunnen dus geen personen vinden.

- Mogelijkheid om motoren zwaarder te laten sturen? Nu kun je met 250 door een bocht jagen, in het echt knal je gewoon tegen een muur aan en ben je dood.

- De criminaliteit wordt steeds zwaarder in de stad en dan merkt het korps duidelijk ook. Deze dagen zijn veel collega's beschoten en of overleden door personen met veel zwaardere wapens dan dat wij hebben. Het DSI doet goed werk door uiteindelijk als nog een aantal op te pakken. Echter is het een groot verbeterpunt als we binnen het korps nog een tact zouden kunnen toevoegen wat bekend staat als het HRB - Hoog Risco beveiliging - Een eenheid die altijd in dienst is en altijd kan ( omkleden) Naar een zwaarder outfit. In het echte leven ziet het er zo uit > Dat neemt natuurlijk niet weg dat we gaan krijgen ja maar we hebben DSI zus en zo. KLOPT. Die zal altijd worden opgeroepen bij zulke incidenten! maar het is enorm fijn als mensen binnen het korps weer toegang krijgen ( na opleiding uiteraard ) tot een zwaarder wapen net zo als in het verleden. )

- De toevoeging van dreigingsniveau's. Dit geeft duidelijk aan op welk dreigingsniveau we zitten, afhankelijk van het aantal schietpartijen en geweldsmisdrijven. Een discordkanaal, die ook inzichtelijk is voor burgers, waar het huidige dreigingsniveau aangegeven staat en wat de gevolgen hiervan zijn. Gevolgen kunnen zijn:
Extra bevoegdheden voor de reguliere noodhulp, denk dan aan preventief fouilleren en dergelijke
 Inzet van HRB (Naar de suggestie van Cedric)
 Inzet van RRT (Rapid response teams) van de DSI
 DSI enkel nog met carbine rifles of zwaardere wapens (snipers en dergelijke)
 Brigadiers en hoger de bevoegdheid geven om een MP5 bij zich te dragen. 
 Kogelwerende en steekwerende vesten die ook daadwerkelijk meer armor geven.
Dit wordt elke week geüpdate aan de hand van hoe het vorige week is verlopen. Dit wordt gedaan door iemand van de korpsleiding.

- (Voor Jasper) Notities kunnen verwijderen in het MEOS-systeem. Als er daar een aantal notities staan die niet meer van toepassing zijn is dat wat onoverzichtelijk en kan er verwarring ontstaan. 

- Automatisch op Whisper als je op hulpdiensten terrein bent (Politiebureau en Ziekenhuis)

- (Voor Kenneth) Vrouwelijke bodycams/OVDvesten/holsters (Vrouwen hebben enkel een been holster) en marked lang/betere motoruniform(haar glitcht er doorheen)

- een soort van NL alert systeem voor de politie zodat wij meer info kunnen delen met de burger bijvoordbeeld tijdens een overval om een gebied aan te kaarten als afgesloten en ontruimen ect ect dit kan een hele boel voorkomen kwa de toestroom van mensen ik heb dit in een andere stad ook wel eens gezien is erg handig.

- OPCO Hesje 

Kijk wat er mogelijk is, benadruk nog een keer kijk hier na als je er echt tijd voor hebt <3 
(er is ook een foto meegeleverd dat is van het puntje van HRB)
![d171213bn1069](https://user-images.githubusercontent.com/37123395/92312649-0634b480-efc3-11ea-8d41-b42cd1ef5215.png)

**Comment by PapaXilion** [comment]
Houden we hier wel rekening met de wet? HRB is een KMar dependance, dacht ik. De politie zou beter samen kunnen werken met de KMar hiervoor.

**Comment by PapaXilion** [comment]
Aanvullend vwb het hek bij HB voor (ik neem aan dat hier die weg naar beneden wordt bedoeld?) - Aangezien er nooit politie bij de balie is, boven komt iedereen naar beneden bij de parkeer garage. Een hek gaat een hoop mensen niet blij maken... soms moeten mensen al tijden wachten voor een agent tijd heeft voor ze. Door ze nu te forceren bij de balie te wachten zal dat niet verbeteren (tenzij er toezegging komt dat er ten alle tijden een baliemedewerker present is )

**Comment by Jesse-Poolman** [comment]
> Aanvullend vwb het hek bij HB voor (ik neem aan dat hier die weg naar beneden wordt bedoeld?) - Aangezien er nooit politie bij de balie is, boven komt iedereen naar beneden bij de parkeer garage. Een hek gaat een hoop mensen niet blij maken... soms moeten mensen al tijden wachten voor een agent tijd heeft voor ze. Door ze nu te forceren bij de balie te wachten zal dat niet verbeteren (tenzij er toezegging komt dat er ten alle tijden een baliemedewerker present is )

Nee, er wordt bedoelt een hek boven het HB. Mensen rijden met hun auto's zo naar binnen om agenten te zoeken. Wij kunnen natuurlijk ook niet altijd bij een bali staan :).

**Comment by Jesse-Poolman** [comment]
> Houden we hier wel rekening met de wet? HRB is een KMar dependance, dacht ik. De politie zou beter samen kunnen werken met de KMar hiervoor.

het zijn enkel voorstellen. Wat ik al aangaf, als het niet haalbaar is of omdat het te veel werk is dan hoeft het niet! 👍

**Comment by PapaXilion** [comment]
> > Aanvullend vwb het hek bij HB voor (ik neem aan dat hier die weg naar beneden wordt bedoeld?) - Aangezien er nooit politie bij de balie is, boven komt iedereen naar beneden bij de parkeer garage. Een hek gaat een hoop mensen niet blij maken... soms moeten mensen al tijden wachten voor een agent tijd heeft voor ze. Door ze nu te forceren bij de balie te wachten zal dat niet verbeteren (tenzij er toezegging komt dat er ten alle tijden een baliemedewerker present is )
> 
> Nee, er wordt bedoelt een hek boven het HB. Mensen rijden met hun auto's zo naar binnen om agenten te zoeken. Wij kunnen natuurlijk ook niet altijd bij een bali staan :).

Je bedoelt de weg die naar beneden loopt naar de parkeerplaats toch? Als je die weg afsluit kan er effectief niemand meer op de parkeerplaats komen.. vervelend voor de burgers want die moeten dan wachten bij de balie (waar nooit iemand is), en de advocatuur moet dan eveneens wachten bij de balie (met hetzelfde effect). Ik snap je punt vwb de drukte daar beneden.. maar je beperkt wel de roleplay enorm door het gebied af te zetten.

**Comment by Jesse-Poolman** [comment]
> > > Aanvullend vwb het hek bij HB voor (ik neem aan dat hier die weg naar beneden wordt bedoeld?) - Aangezien er nooit politie bij de balie is, boven komt iedereen naar beneden bij de parkeer garage. Een hek gaat een hoop mensen niet blij maken... soms moeten mensen al tijden wachten voor een agent tijd heeft voor ze. Door ze nu te forceren bij de balie te wachten zal dat niet verbeteren (tenzij er toezegging komt dat er ten alle tijden een baliemedewerker present is )
> > 
> > 
> > Nee, er wordt bedoelt een hek boven het HB. Mensen rijden met hun auto's zo naar binnen om agenten te zoeken. Wij kunnen natuurlijk ook niet altijd bij een bali staan :).
> 
> Je bedoelt de weg die naar beneden loopt naar de parkeerplaats toch? Als je die weg afsluit kan er effectief niemand meer op de parkeerplaats komen.. vervelend voor de burgers want die moeten dan wachten bij de balie (waar nooit iemand is), en de advocatuur moet dan eveneens wachten bij de balie (met hetzelfde effect). Ik snap je punt vwb de drukte daar beneden.. maar je beperkt wel de roleplay enorm door het gebied af te zetten.

Dat klopt zeker, maar als jij 1 dagje mee gaat kijken wat daar allemaal staat en gaat. Dan durf je daar echt niet je auto weg te zetten want dan wordt hij toch weg gestolen van het terein. Puntje advocaten, die kunnen gewoon bellen of een melding maken voor agenten.

**Comment by PapaXilion** [comment]
> > > > Aanvullend vwb het hek bij HB voor (ik neem aan dat hier die weg naar beneden wordt bedoeld?) - Aangezien er nooit politie bij de balie is, boven komt iedereen naar beneden bij de parkeer garage. Een hek gaat een hoop mensen niet blij maken... soms moeten mensen al tijden wachten voor een agent tijd heeft voor ze. Door ze nu te forceren bij de balie te wachten zal dat niet verbeteren (tenzij er toezegging komt dat er ten alle tijden een baliemedewerker present is )
> > > 
> > > 
> > > Nee, er wordt bedoelt een hek boven het HB. Mensen rijden met hun auto's zo naar binnen om agenten te zoeken. Wij kunnen natuurlijk ook niet altijd bij een bali staan :).
> > 
> > 
> > Je bedoelt de weg die naar beneden loopt naar de parkeerplaats toch? Als je die weg afsluit kan er effectief niemand meer op de parkeerplaats komen.. vervelend voor de burgers want die moeten dan wachten bij de balie (waar nooit iemand is), en de advocatuur moet dan eveneens wachten bij de balie (met hetzelfde effect). Ik snap je punt vwb de drukte daar beneden.. maar je beperkt wel de roleplay enorm door het gebied af te zetten.
> 
> Dat klopt zeker, maar als jij 1 dagje mee gaat kijken wat daar allemaal staat en gaat. Dan durf je daar echt niet je auto weg te zetten want dan wordt hij toch weg gestolen van het terein. Puntje advocaten, die kunnen gewoon bellen of een melding maken voor agenten.

Ik sta daar dagelijks en er is zero handhaving door de politie op het terrein, die zelf ook elkaar staan te taseren en te lachen met mensen.. en dan moet er maar een hek komen.. Zit de oplossing hier niet in de RP van de Politie?

Als er niet meer RP bij de balie komt gaat deze feature zorgen voor enorme oponthoud in de te behandelen zaken door de advocaten, en dat loopt momenteel al als dikke stroop. 

Ook werkt de lift in de balie niet voor advocaten. Ik moest een keer via de balie komen en moest met /carry de lift in worden genomen.

Dus nee, ik ben faliekant tegen een hek om daarmee de RP rond het HB te vernietigen.

**Comment by SanderDekkers26** [comment]
> Houden we hier wel rekening met de wet? HRB is een KMar dependance, dacht ik. De politie zou beter samen kunnen werken met de KMar hiervoor.

Dan noemen we het gewoon BE, dat is exact hetzelfde maar dan voor de politie. Niet zeer moeilijk. :)

**Comment by SanderDekkers26** [comment]
> > > > > Aanvullend vwb het hek bij HB voor (ik neem aan dat hier die weg naar beneden wordt bedoeld?) - Aangezien er nooit politie bij de balie is, boven komt iedereen naar beneden bij de parkeer garage. Een hek gaat een hoop mensen niet blij maken... soms moeten mensen al tijden wachten voor een agent tijd heeft voor ze. Door ze nu te forceren bij de balie te wachten zal dat niet verbeteren (tenzij er toezegging komt dat er ten alle tijden een baliemedewerker present is )
> > > > 
> > > > 
> > > > Nee, er wordt bedoelt een hek boven het HB. Mensen rijden met hun auto's zo naar binnen om agenten te zoeken. Wij kunnen natuurlijk ook niet altijd bij een bali staan :).
> > > 
> > > 
> > > Je bedoelt de weg die naar beneden loopt naar de parkeerplaats toch? Als je die weg afsluit kan er effectief niemand meer op de parkeerplaats komen.. vervelend voor de burgers want die moeten dan wachten bij de balie (waar nooit iemand is), en de advocatuur moet dan eveneens wachten bij de balie (met hetzelfde effect). Ik snap je punt vwb de drukte daar beneden.. maar je beperkt wel de roleplay enorm door het gebied af te zetten.
> > 
> > 
> > Dat klopt zeker, maar als jij 1 dagje mee gaat kijken wat daar allemaal staat en gaat. Dan durf je daar echt niet je auto weg te zetten want dan wordt hij toch weg gestolen van het terein. Puntje advocaten, die kunnen gewoon bellen of een melding maken voor agenten.
> 
> Ik sta daar dagelijks en er is zero handhaving door de politie op het terrein, die zelf ook elkaar staan te taseren en te lachen met mensen.. en dan moet er maar een hek komen.. Zit de oplossing hier niet in de RP van de Politie?
> 
> Als er niet meer RP bij de balie komt gaat deze feature zorgen voor enorme oponthoud in de te behandelen zaken door de advocaten, en dat loopt momenteel al als dikke stroop.
> 
> Ook werkt de lift in de balie niet voor advocaten. Ik moest een keer via de balie komen en moest met /carry de lift in worden genomen.
> 
> Dus nee, ik ben faliekant tegen een hek om daarmee de RP rond het HB te vernietigen.

We hebben het enorm druk en er is nauwelijks mogelijkheid tot handhaven op dat terrein. Als advocaat word je altijd opgehaald als een verdachte erom vraagt. Mensen kunnen een afspraak maken als ze hun voertuig willen komen halen of een melding maken. Nu is het zo dat ze simpelweg in de weg lopen en aan de kop zeuren waardoor ze soms zelfs aangereden worden.

**Comment by SecretSupplier** [comment]
Jesse maak het bericht even korter zodat ze het daadwerkelijk gaan doen!
