### ISSUE TITLE
[FEATURE]: ATC logging

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1590]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Mogelijk maken om te kunnen zien wie er in de ATC aan het praten is voor de komende rangen/functies:

- DSI Grades (KMar en politie)
- Politie/KMar Boss
- Vlieginstructeurs 
- Admin on Duty

### Wat lost deze feature op?

Veel spelers kloten in de ATC, zitten te schreeuwen, verstoren anderen hun RP of gebruiken de ATC niet waarvoor die bedoelt is. Hiermee kunnen zowel staff als politie/kmar/vlieginstructeurs ze dan aanspreken of eventuele sancties (kan IC of OOC) uitdelen waar nodig.

**Comment by Nander0320** [comment]
Admin onduty kan dit inmiddels
Vliegintructeurs kunnen dit met nog wat toegingen 

Tevens dient klootgedrag aangepakt te worden door staf en niet door spelers :)
