### ISSUE TITLE
[FEATURE]: Server Supporter misbruik tegen gaan door Discord ID te controleren 

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#1591]
### Contact Details

Attom#3152

### Beschrijf zo duidelijk mogelijk de feature

Na hoge raad overleg dit puntje, bij het joinen checken of er al met dat discord id op dat moment iemand geconnect is.

### Wat lost deze feature op?

misbruik van discord accounts en server supporter.

**Comment by Ljosfari** [comment]
Dit zit er nu al in toch ?

**Comment by Chang-nl** [comment]
Is gefixt!
