### ISSUE TITLE
[FEATURE]: Perms testserver voor bepaalde commands

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1592]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

De commands in testserver m.b.t. set weather / time etc verlagen van vereiste staffrang (volgens mij op dit moment Superadmin). 

### Wat lost deze feature op?

Geeft meer staffleden toegang tot deze commands wat van pas kan komen bij het testen van bepaalde dingen (bijvoorbeeld voertuigen).

**Comment by Chang-nl** [comment]
het weer command en time command is vanaf de herstart beschikbaar voor moderator en hoger.
