### ISSUE TITLE
[FEATURE]: Verwijderen van pizza en ambulance locatie op postcode 5035

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#1593]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

Er is op Colombo Cafe terrein een Pizza bezorg locatie. Om hier te komen moet je als pizzabezorger klimmen over het hek van colombo: (afbeelding 1). Het verzoek om deze locatie weg te halen hier zodat de pizzabezorgers niet meer op colombo prive terrein hoeven te komen. Belangrijk: Ambulance heeft hier ook NPC missies, als die mogelijk ook aangepast kan worden zou top zijn!
![image](https://user-images.githubusercontent.com/32983383/187256772-92533431-5f07-4f77-b5b0-b16fbe9aa394.png)

Locatie: Afbeelding2
![image](https://user-images.githubusercontent.com/32983383/187257089-b0f9841c-d3da-4705-9d1c-0b8b102c1c1d.png)

### Wat lost deze feature op?

Hierdoor gaan de pizzabezorgers niet meer aan colombo hoeven vragen of ze door het hek mogen en hoeft colombo hier niet meer te helpen. Hierdoor komt er ook niet continu iemand die over het hek klimt wat eignelijk niet de bedoeling is natuurlijk en hoeft colombo dus niet iemand "aan te pakken" omdat hij pizza moet bezorgen.

**Comment by Ljosfari** [comment]
zou je de coordinaten hiervan erbij willen zetten ? ongeveer

**Comment by DaanDeW** [comment]
![image](https://user-images.githubusercontent.com/32983383/187559120-a2a42c59-56da-494b-9746-0cbd7ff7c9b4.png)

**Comment by CorruptSausage** [comment]
Is gefixt na restart.
