### ISSUE TITLE
[FEATURE]: Verwijderen van prullenbakken zodat hek open kan (postcode 5035)

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#1594]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

Bij Cafe Colombo komt het vaak voor dat het hek (met sleutels) niet open kan.  
Dit komt omdat de prullenbakken verschuiven soms waardoor het hek tegen de prullenbak aankomt en hierdoor het hek dus niet verder open kan door het object / obstakel.

![image](https://user-images.githubusercontent.com/32983383/187259581-47aa01cd-0104-4c8c-8622-2a19c07c5796.png)

### Wat lost deze feature op?

Zodat het hek niet vastloopt en de poort / het hek open kan. De vuilnisbakken staan enorm in de weg en als deze weg zijn zal het hek dus ook niet meer vast hangen

**Comment by Ljosfari** [comment]
Dit zat er al in nu toch @DaanDeW ?

**Comment by DaanDeW** [comment]
Als hij wordt gepusht in de main samen met t hek  zijn ze vast gezet ipv verwijderd, voor nu ook goed.

**Comment by Oesewoes** [comment]
Niek mondeling bedreigd en heeeel bang gemaakt, het komt er heel snel in als het goed is. 
Dit is een foto van een kikker: 
![32bb54051ccedcb6f6f76f45afe658a8](https://user-images.githubusercontent.com/69470855/188291649-8ebc9224-ea86-4115-8060-157c6def3ab8.jpg)
