### ISSUE TITLE
[FEATURE]: Toevoegen extra interior / garage Colombo Cafe (5035)

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#1595]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

Het verzoek vanuit CCF / Colombo om een locatie te hebben waar ze eventueel een deal kunnen doen, iets cirmineels of dergelijke. Het is natuurlijk niet de bedoeling dat het Cafe/restaurant gelinkt wordt aan criminele acitivteiten. Omdat Colombo geen kelder heeft of plek waar ze dit kunnen doen (wat de meeste wel hebben) verzochten ze een garage. 
![image](https://user-images.githubusercontent.com/32983383/187263433-1d7a18fa-d756-49bb-add2-995d91c16a43.png)

Met deze deur:
![image](https://user-images.githubusercontent.com/32983383/187263679-d36f8ad9-c406-4883-9f72-9255070cb1bd.png)

op deze locatie staat een garage deur die open kan die we hier zouden willen:
![image](https://user-images.githubusercontent.com/32983383/187264604-45dd2715-b260-4cff-8ec8-8417788191de.png)
 
 Hij ziet er zo uit:
 
![image](https://user-images.githubusercontent.com/32983383/187264651-18c8e781-b8e0-48d5-97de-86ddab6395de.png)

Het interior zou fijn zijn als hier  binnen in een soort garage zou zijn zoals bij MC.
Zie afbeelding:

![image](https://user-images.githubusercontent.com/32983383/187266048-cdae92c3-1533-442c-a7ee-9164b50df1b0.png)

### Wat lost deze feature op?

Hierdoor kan er iets crimineels gedaan worden bij het Cafe (plek van Colombo) zonder dat het Cafe/restaurant benadeeld wordt. Je wilt als server lijkt mij niet dat je criminele activiteiten wilt gelinkt hebbben aan een restaurant. Vandaar dat hier colombo nu dus een plek krijgt om criminele dingen uit te voeren. Dit zou een toevoeging zijn binnen de RP zowel voor de hele oude auto's waarmee Colombo altijd rijd, zodat ze een plek hebben om hun voertuigen te onderhouden. Maar ook voor een extra toevoeging waardoor ze dus crimineel en hun job als restaurant gescheiden houden. Geen idee of het mogelijk is, maar het zou voor hun een enorme toevoeging zijn en een enorm voordeel zijn.

**Comment by Oesewoes** [comment]
Mee bezig, maar duurt nog wel een tijdje voordat het af is.

**Comment by DevvTDA** [comment]
Staat in de server
