### ISSUE TITLE
[Bug]: Damage na behandeling ziekenhuis

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1597]
### Contact Details

Devv#4532

### Wat gebeurde er?

Als je bij het ziekenhuis een behandeling neemt, vervolgens het ziekenhuis uitloopt krijg je weer damage. 

### Wat hoorde er te gebeuren?

Je hoort geen damage te krijgen erna

### Wat veroorzaakt de bug?

behandeling in het ziekenhuis nemen en na de behandeling het ziekenhuis uitlopen

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://youtu.be/aW3hiIMWwGU

**Comment by zeletix** [comment]
Nog een clip https://streamable.com/4lvrii

**Comment by niekschoemaker** [comment]
Is gefixed
