### ISSUE TITLE
[FEATURE]: Witgeld ook zien via F6 fouilleren

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1598]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel zie je alleen zwartgeld via F6 als je iemand fouilleert. Graag zouden wij zien dat al het cash geld aan wordt gegeven en eventueel samenvoegen in het menu tot één bedrag.

### Wat lost deze feature op?

Brengt extra RP met zich mee wanneer je ook het witgeld kan onderzoeken. Ook wat nu gebeurt is dat wanneer een persoon bijvoorbeeld losgeld krijgt (witgeld cash) en daarna gepakt wordt dat agenten die niet via het fouilleren zien.

**Comment by Ljosfari** [comment]
Ik snap je punt, maar dit gaat om de hele bankrekening, die zou je normaal gesproken ook niet kunnen zien

**Comment by PolitieTDA** [comment]
> Ik snap je punt, maar dit gaat om de hele bankrekening, die zou je normaal gesproken ook niet kunnen zien

Ik bedoel hier enkel het witgeld wat persoon cash op zak heeft @Ljosfari.

**Comment by PolitieTDA** [comment]
Zie nu dat het in de main zit, dankjulliewel! :) Wel is me opgevallen dat wanneer je het wilt confisqueren je het witte cashgeld niet af kunt pakken, enkel het zwartgeld. @Ljosfari

**Comment by Chang-nl** [comment]
Is dit nog steeds het probleem ik zag enkele dagen geleden (ik denk voor dit) een fix voorbijkomen?

**Comment by Ljosfari** [comment]
dit zit er nu in toch ?

**Comment by PolitieTDA** [comment]
Het confisqueren van witgeld werkt helaas nog niet. @Ljosfari

**Comment by Nander0320** [comment]
Dit moet even overwogen worden binnen staf overleg of wij de politie de machtiging tot witgeld in beslag nemen mag. Dit vanwege corruptiemogelijkheden

**Comment by Chang-nl** [comment]
Hey @Nander0320,

Zou je hier dan ook agendapuntje voor kunnen maken zodat het besproken kan worden?

**Comment by ARJ3N** [comment]
> Hey Nander0320,
> 
> Zou je hier dan ook agendapuntje voor kunnen maken zodat het besproken kan worden?

Zal ik doen voor komend overleg. @Chang-nl

**Comment by Chang-nl** [comment]
Yes, dankjewel!
