### ISSUE TITLE
[Bug]: [Bug]: /charselect is bugged #1581 2.0

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1599]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Chang had mijn vorige github opgelost, alleen ben je nu wel een man je veranderd alleen niet hoe eerst je karakter was. 
zie screenshot: 
![image](https://user-images.githubusercontent.com/101106299/187750277-dd142ded-53f4-41a8-9cd9-a0c4b2f0ad24.png)

### Wat hoorde er te gebeuren?

je hoort je oude karakter te krijgen lijkt me.

### Wat veroorzaakt de bug?

als je van vrouw naar man gaat is je mannelijke character bugged, zoals je op de screenshot hebt gezien. 

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

**Comment by niekschoemaker** [comment]
Welke andere issue gaat dit over?

**Comment by CalRayy** [comment]
> Welke andere issue gaat dit over?

issue 1581, Chang gaf aan dat hij dit had gefixt (wat ook het geval is, je kon weer een man worden voor de mensen die een vrouw was). Alleen nu als je een man word krijg je een random poppetje zoals je op de screenshot kan zien 😅.

**Comment by niekschoemaker** [comment]
Hiervoor ben ik een repo nodig.

Ik heb zelf nu een vrouwelijke character gemaakt, deze werkt, hierna switch ik weer naar m'n mannelijke character, deze werkt.

**Comment by CalRayy** [comment]
Niek vertelde mij dat ik moest vermelden dat het ligt aan je karakter die je in het begin ooit hebt gemaakt. Hij slaat je karakter niet op van je oude character alleen de huidige die je toen had.

**Comment by CalRayy** [comment]
> Hiervoor ben ik een repo nodig.
> 
> Ik heb zelf nu een vrouwelijke character gemaakt, deze werkt, hierna switch ik weer naar m'n mannelijke character, deze werkt.

Wat ik deed met mijn character was het volgende:
1. Ik verander naar mijn mannelijke character 
2. Heb een gesaved outfit aangedaan voor de mannelijke outfit
3. Vervolgens ben ik paar uurtjes gaan spelen met die character
4. Ik wil terug naar mijn vrouwelijke character gaan
5. Character is bugged door volgens mij een gesaved outfit aan te doen voor een man

**Comment by CalRayy** [comment]
> > Hiervoor ben ik een repo nodig.
> > Ik heb zelf nu een vrouwelijke character gemaakt, deze werkt, hierna switch ik weer naar m'n mannelijke character, deze werkt.
> 
> Wat ik deed met mijn character was het volgende:
> 
> 1. Ik verander naar mijn mannelijke character
> 2. Heb een gesaved outfit aangedaan voor de mannelijke outfit
> 3. Vervolgens ben ik paar uurtjes gaan spelen met die character
> 4. Ik wil terug naar mijn vrouwelijke character gaan
> 5. Character is bugged door volgens mij een gesaved outfit aan te doen voor een man

-------
Als je switched naar een andere geslacht (in /charselect) en je gaat bijvoorbeeld een outfit maken of een outfit die al opgeslagen is aan doen. Vervolgens speel je met die karakter voor enkele uren en je veranderd je karakter terug naar de originele karakter waarmee je eerst begon (dus voordat je switched naar een andere geslacht) gebruikt is die specifieke karakter veranderd (en bugged, je originele karakter is volledig weg).

**Comment by CorruptSausage** [comment]
Issue is op verzoek van @CalRayy opnieuw geopend, aangezien dit nog niet opgelost is.

**Comment by Nander0320** [comment]
Dit is inmiddels opgelost :)
