### ISSUE TITLE
[FEATURE]: Sterker maken militaire voertuigen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1600]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Was een oude github, maar is toen gesloten door de maker, dus nu even een nieuwe:

Graag zouden wij zien dat een aantal voertuigen van defensie wat sterker gemaakt worden, aangezien het totaal niet realistisch is dat deze na een paar kogels van een pistool al uit de lucht vallen.

- hunter
- annihilator3
- chinook
- lazer
- hydra

### Wat lost deze feature op?

Maakt het realistischer voor de defensievoertuigen aangezien deze normaal gesproken ook gebouwd zijn met de insteek dat ze wat tegenstand kunnen weerstaan. Zo heeft een Apache in het echt bijvoorbeeld kevlar platen aan de onderkant. Nu hoeft dit niet zo gemaakt geworden dat ze onverwoestbaar zijn, maar iets sterker zou fijn zijn.

**Comment by zeletix** [comment]
Je moet het wel een beetje balanced houden he, die Apache's hebben al basically zulu cameras waarmee je opblaast op wat je klikt. Al willen we het realistisch maken zou er ook absurd veel bij de politie generfed moeten worden.

**Comment by Chang-nl** [comment]
Hey @PolitieTDA,

Zou je een agendapunt kunnen maken voor deze github issue zodat het besproken kan worden in staffoverleg?

**Comment by Chang-nl** [comment]
Gesloten i.v.m. geen reactie

**Comment by ARJ3N** [comment]
Ik krijg op die mail geen notificaties dus had daarom je reactie gemist. Excuses daarvoor! Dit was voorheen al goedgekeurd als het goed is en was toen een oude issue (van Whaledone) maar was toen gesloten i.v.m. dat die al heel lang openstond en niet opgepakt werd. Zie: https://github.com/Tedeapolis/development/issues/754 @Chang-nl

**Comment by Tom974** [comment]
Gefixt met Lorenzo samen, zit erin na de herstart.
