### ISSUE TITLE
[Bug]: Random Damage ontvangen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1601]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je krijgt laatste tijd random damage door bijvoorbeeld te wandelen of rijden in een auto. 
(Er staat een video van Kees waar hij random damage krijgt in dev overleg)

### Wat hoorde er te gebeuren?

je hoort geen random damage te krijgen.

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by zeletix** [comment]
voorbeeld clip https://streamable.com/4lvrii

**Comment by zeletix** [comment]
Als je full HP bent neem je ongeveer 20 damage, terwijl als je niet full HP bent je ongeveer 1-5 damage neemt.

**Comment by Ljosfari** [comment]
Dit gebeurt ook bij alle spelers tegelijk km de zoveel minuten. Half uurtje ongeveer ?

**Comment by niekschoemaker** [comment]
Is gefixed
