### ISSUE TITLE
[Bug]: Gevangenis bug

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1603]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je in de gevangenis zit en je game crashed wanneer je nog paar minuten nog moet zitten, blijf je daar voor altijd tot je word geholpen word door staff.

### Wat hoorde er te gebeuren?

Je hoort na de bepaalde tijd eruit te komen.

### Wat veroorzaakt de bug?

als je game crashed wanneer je nog paar minuten nog moet doen.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

**Comment by Nander0320** [comment]
Dit is opgelost! :)
