### ISSUE TITLE
[Bug]: Dragstrip tijden werken niet

### ISSUE THREAD

**Issue by Dark5000** [Tedeapolis/development#1604]
### Contact Details

Dark#5000

### Wat gebeurde er?

Als je een tijd wil neer zetten op de dragstrip op sandy shores airfield registeerd hij de tijd niet, je komt niet op de leaderboard, dit gebeurt pas als je een tijd hebt die even hoog/hoger is dan de top 3.

### Wat hoorde er te gebeuren?

Je tijd hoort geregisterd te worden en op de juiste positie met jou tijd worden geplaatst.

### Wat veroorzaakt de bug?

Onbekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

[   2120250] [b2372_GTAProce]             MainThrd/ CruiseControl Voertuig gelimiteerd naar: 100.0 m/s - 499.9 km/h - 1.24 x
[   2129187] [b2372_GTAProce]             MainThrd/ CruiseControl Voertuig gelimiteerd naar: 100.0 m/s - 499.9 km/h - 1.24 x
[   2138453] [b2372_GTAProce]             MainThrd/ CruiseControl Voertuig gelimiteerd naar: 100.0 m/s - 499.9 km/h - 1.24 x
[   2139500] [b2372_GTAProce]             MainThrd/ 9680642's coords was set to nil vector3(1713.3, 3261.4, 41.964425201416) by Testraces
[   2165218] [b2372_GTAProce]             MainThrd/ ELS-Plus: 1775 was removed. Reason: doesn't exist.

**Comment by niekschoemaker** [comment]
De tijden zijn per voertuig type, dus van elk voertuig komt er 1 tijd op de leaderbord, dit is om het leaderbord vrij te houden qua tijden.

Hoeveel tjiden staan er nu gemiddeld op de leaderbord? Gezien het systeem per voertuig van voor het automatisch resetten is.

**Comment by Dark5000** [comment]
> v
Er staan totaal 9 tijden op, als ik een tijd probeer neer te zetten met mijn voertuig (Jesko) lukt dat niet, dit type voertuig staat er nog niet op.

**Comment by niekschoemaker** [comment]
Ahhhhh, I see, heb even de logs gechecked en het gaat idd om een error 😳 

Ik zal even kijken wat dit veroorzaakt heeft en dit fixen waar nodig.

**Comment by niekschoemaker** [comment]
Is gefixed
