### ISSUE TITLE
[FEATURE]: ANPR meldingen

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1605]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Het voertuig model in de ANPR meldingen erin vermelden.

**Comment by Willem-Dekker** [comment]
![image](https://user-images.githubusercontent.com/16556575/192311170-5c8d4810-2279-4d97-891f-6d0ba0dbed28.png)
zit er in na de restart
