### ISSUE TITLE
[FEATURE]: Drugsmeldingen KMar

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1607]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

Dezelfde drugsmeldingen die de politie nu heeft, maar dan voor de KMar. Dit geldt voor alle rangen.

### Wat lost deze feature op?

Dat de KMar drugsmeldingen krijgt.

**Comment by zeletix** [comment]
Is idd wel logisch haha, snap niet waarom dit er niet vanaf het begin in zit
