### ISSUE TITLE
[Bug]: FMJ Magazine op de (Ak-74 - Ak-12)

### ISSUE THREAD

**Issue by Mxcro1** [Tedeapolis/development#1608]
### Contact Details

Faiss#9999

### Wat gebeurde er?

Hier een klein iets wat gefixt moet worden:

FMJ Magazine's zijn toegevoegd je kan ze op zowel de m1911 en baretta zetten

Sinds deze Feature erin zit kan je deze magazine niet op de (Ak-74 - Ak-12) zetten
Echter kan je de ammo/clip wel inkopen alleen heeft het nu geen nut gezien je de magazine niet kan kopen

(Zie foto) hieronder
![hgsdfhsDASH](https://user-images.githubusercontent.com/102612000/188509145-ca266202-6302-4d94-a4e8-3708e6d4408e.png)
![hfsahfha](https://user-images.githubusercontent.com/102612000/188509147-0b420d23-1e2f-4d9a-b6ca-cc0909b473af.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Oh oepsie, vergeten toendertijd, zit erin na volgende restart.

**Comment by Mxcro1** [comment]
Even een reminder het is nog steeds niet gefixt. @niekschoemaker
