### ISSUE TITLE
[Bug]: /fixvehicle die af en toe niet werkt

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1609]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je helpt een persoon met zijn voertuig door hem te repareren met /fixvehicle alleen repareert die soms totaal niet en moet je af toe meerdere malen /fixvehicle (degene was ook uitgestapt en zat niet in het voertuig).

Ik zelf heb het op een keybind en moet dan meerdere malen erop drukken tot het gefixt is, ik zag dit ook af en toe met andere staff leden.

### Wat hoorde er te gebeuren?

Het voertuig moet instant gerepareerd zijn voor beide personen alleen is het op jouw beeld fixed maar bij een ander niet.

Waardoor je soms terug moet gaan en het voertuig "repareren" terwijl je dat al had gedaan zeg maar.

### Wat veroorzaakt de bug?

1. Je pakt de report op 
2. Je geeft aan bij de persoon van stap uit het voertuig 
3. Eenmaal afgestapt 
4. doe je /fixvehicle (ik heb het gekeybind)
5. bij jou is het gefixt en bij degene niet
6. hoe ik dit issue fix is door zelf in te stappen en zo fixvehicle te doen (zodat degene hem ook gerepareerd ziet)

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

**Comment by Ljosfari** [comment]
heb ik zelf nog nooit ervaren...

**Comment by CalRayy** [comment]
> heb ik zelf nog nooit ervaren...

Kan het komen omdat ik het op een keybind heb?

**Comment by Chang-nl** [comment]
Gefixt na herstart, bedankt voor het melden. Overigens hoeft de persoon ook niet meer uit te stappen.
