### ISSUE TITLE
[Bug]: Grote bank bug 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1610]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je start de grote bank en je krijgt de melding dat over 300 seconden de kluis open gaat. Alleen gaat de kluis nooit open.

Clip: https://www.youtube.com/watch?v=rz-NAhdMHQ0&ab_channel=TFFTNoah 
Geluid matched niet met de video, maar als je kijkt naar de tijdstip rechtsboven is de kluis nog altijd niet open en dat komt volgens mij omdat iemand op dat moment een andere overval aan het doen is.

(Ik heb deze bug 2 keer voorbij zien komen, het gebeurd zeer zelde )

### Wat hoorde er te gebeuren?

De kluis hoorde open te gaan

### Wat veroorzaakt de bug?

1. Je doet de grote bank
2. je gaat de kluis hacken
3. je wacht tot de kluis open gaat
4. kluis gaat nooit open (waarschijnlijk omdat er een andere overval gaande is net toevallig wanneer je de bank doet? )

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
is opgelost
