### ISSUE TITLE
[Bug]: ANWB Stock opbergen werkt niet 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1611]
### Contact Details

DeStefanoKiller#4442

### Wat gebeurde er?

Als ik op de knop "stock opbergen" klik bij de ANWB gebeurd er niks ook komen er geen fout meldingen binnen in mijn console.

### Wat hoorde er te gebeuren?

Normaal als je de knop "Stock opbergen" selecteert dan krijg jij je inventory te zien met welke spullen jij wilt opbergen in de opslag. 

### Wat veroorzaakt de bug?

1: Zet jezelf als ANWB'er in-dienst.
2: Loop naar boven bij het kantoor en ga in de gele cirkel staan en druk op E.
3: Klik op de knop "Stock opbergen". 

Heb je alle 3 de stappen gedaan? Dan zie je dat er niks gebeurd.
(Waarschijnlijk is er niks verbonden aan de knop "Stock opbergen")

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

-

**Comment by CorruptSausage** [comment]
Moet als het goed is gefixt zijn na de restart.
