### ISSUE TITLE
[Bug]: Justitie als job2

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1612]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Wanneer men Justitie als job2 heeft, werkt bijna niks meer, namelijk:
- [x] Geen advocatenpas in F2
- [ ] Geen toegang tot dienstvoertuig
- [x] Geen toegang tot EUP
- [x] Wordt niet meegeteld in F10 

Met de job als secondary heeft men echter wel nog toegang tot de sloten en de meldingen die binnen komen.

### Wat hoorde er te gebeuren?

Graag alle bovenstaande opmerkingen inschakelen waardoor mensen zoals ik ook een andere primary job (in mijn geval Radio Baas) kunnen hebben.
Het vervelendste is dat ik nu niet meegeteld word in F10 en agenten dus niet kunnen zien dat er een advocaat in dienst is.

### Wat veroorzaakt de bug?

De job als secondary ipv primary hebben

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by CalRayy** [comment]
Dit is met elke overheidsbaan zover ik weet.

**Comment by Mikajac** [comment]
> Dit is met elke overheidsbaan zover ik weet.

Dat durf ik niet te bevestigen, ik merk het nu toevallig zelf. 

Maar dan dus het verzoek de secondary job evenveel "waarde" en toegang te geven als primary.

**Comment by Chang-nl** [comment]
Hey @Mikajac, je kan gewoon de radiobaas job op job 2 houden toch?

**Comment by Mikajac** [comment]
> Hey @Mikajac, je kan gewoon de radiobaas job op job 2 houden toch?

Hey, dat zou inderdaad kunnen maar dan krijg je het probleem omgedraaid, dus dan heb ik geen toegang meer tot het baas-menu van de radio. 
Bij Job2 heb je eigenlijk alleen de sleutels van panden, verder vervalt elke mogelijkheid qua cirkels, documenten, pasjes etc.

**Comment by Chang-nl** [comment]
Hey @Mikajac,

Klopt het dat alle puntjes los van toegang tot dienstvoertuig zijn opgelost?

**Comment by Mikajac** [comment]
> Hey @Mikajac,
> 
> Klopt het dat alle puntjes los van toegang tot dienstvoertuig zijn opgelost?

Ik zou je graag antwoord willen geven maar helaas kan ik dat niet. Ik werk inmiddels niet meer als advocaat waardoor ik geen job2 meer heb, sorry!

**Comment by Chang-nl** [comment]
Hey @Mikajac,

Momenteel wegen de voordelen niet op tegen de nadelen om het puntje toegang tot dienstvoertuig te gaan fixen, want dit is compleet niet ondersteund en zal veel tijd en arbeid vereisen, dus zullen we dit niet gaan doen in de nabije toekomst.
