### ISSUE TITLE
[FEATURE]: Flitsboetes in dienst politie/KMar

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1613]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel krijgen de politie/kmar nogsteeds flitboetes op een aantal van de flitspalen in de stad. Om een paar voorbeelden van deze flitspalen te noemen die nog werken op mensen die in dienst zijn: Blokkenpark (die is met opzet gedaan als het goed is), oude taxi, oude ANWB & Mazebank. 

### Wat lost deze feature op?

Wij krijgen nog steeds erg veel klachten van agenten die flitsboetes krijgen in dienst. Dit is erg vervelend in achtervolgingen waarbij je meerdere keren langs deze flitspalen kan rijden waardoor het uiteindelijk best veel geld kan kosten per achtervolging, terwijl ze gewoon hun werk aan het uitvoeren zijn. Daarom zouden wij graag willen dat wij ook op deze locaties geen flitsboetes meer ontvangen. Uiteraard snappen wij dat op sommige hotspots deze flitspalen handig zijn, zodat je daar niet hard langsrijdt (ook al gebeurd dat alsnog door zowel politie/criminelen), maar deze flitspalen werken ook nog steeds op in dienst agenten op hele oude hotspots, zoals dus de oude taxi e.d. Deze zijn allang niet meer relevant en dus dienen die flitspalen ook niet hun oude nut meer daar.

**Comment by niekschoemaker** [comment]
Yes klopt, deze flitspalen zijn met opzet zo gezet idd.

**Comment by PolitieTDA** [comment]
> Yes klopt, deze flitspalen zijn met opzet zo gezet idd. @niekschoemaker 

Maar deze hebben toch geen enkel nut meer op deze plekken? Het zijn al heel lang geen hotspots neer. Is het niet mogelijk die dan te verplaatsen naar plekken waar het wél hotspots zijn? Nu heeft niemand wat aan deze flitspalen namelijk.
