### ISSUE TITLE
[Bug]: Helikopter kapot slaan (met vuisten / trappen)

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1615]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Tegenwoordig gaan mensen je helikopter kapot slaan / trappen zodat je niet kan ontsnappen van het eiland, maar dit is super onrealitisch en vind ik persoonlijk powergamen. Is het mogelijk om de damage van slaan / trappen op een helikopter te verminderen (eventueel op 0 damage zetten?). 

### Wat hoorde er te gebeuren?

Een helikopter hoort niet na paar meppen / trappen gelijk stuk te zijn.

### Wat veroorzaakt de bug?

je trapt een helikopter en je helikopter is stuk.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by CalRayy** [comment]
Ik moest van Niek even een github issue maken 😄

**Comment by Chang-nl** [comment]
Gefixt na herstart, bedankt voor het melden!
