### ISSUE TITLE
[FEATURE]: Het kunnen verstoppen in kofferbak.

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1616]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

https://forum.cfx.re/t/standalone-hide-in-trunk-system/4818531

Besproken in het afgelopen staffoverleg van 11-09-2022.

Het kunnen verstoppen in een kofferbak. Ook is het de bedoeling dat er maar 1 iemand in de kofferbak kan en dat de AFK kick gewoon meeloopt, zodat je niet AFK kan gaan in een kofferbak. 

### Wat lost deze feature op?

Nieuwe mogelijkheden qua RP's.

**Comment by Chang-nl** [comment]
Duplicate of #1126
