### ISSUE TITLE
[FEATURE]: request_cuff ook met politie handboeien kunnen gebruiken

### ISSUE THREAD

**Issue by NouNou0** [Tedeapolis/development#1618]
### Contact Details

NouNou#2004

### Beschrijf zo duidelijk mogelijk de feature

Uit dienst agenten die bevoegd zijn met dienstwapen te lopen kunnen momenteel niet boeien terwijl de gehele stad dit kan dmv tiewraps. Aangezien de politie deze niet mag gebruiken is dit de beste oplossing.

### Wat lost deze feature op?

Onnodige noodhulp oproepen aangezien die soms moeten komen puur voor het boeien en het ontboeien. Geeft ook gemak aan de agent die iemand uit dienst aanhoud waardoor het gehele proces voor iedereen vlot verloopt

**Comment by Chang-nl** [comment]
Staat nu op de boss, dsi en recherche rangen. Mochten er nog meer toegevoegd willen worden kun je een bericht achterlaten in de issue.

**Comment by PolitieTDA** [comment]
Ik krijg deze nog niet werkend wanneer ik uit dienst ben. In dienst lukt /request_cuff wel, maar dan heb je natuurlijk het F6 menu. Wanneer ik dan iemand boei en ontboei via /request_cuff krijg ik ook de handboeien niet terug. @Chang-nl

**Comment by Chang-nl** [comment]
Is gefixt al een tijdje terug, mocht dit net het geval zijn kun je een berichtje achterlaten!
