### ISSUE TITLE
[FEATURE]: Open lassen van voertuigen met lightbars

### ISSUE THREAD

**Issue by Haceyy** [Tedeapolis/development#1620]
### Contact Details

hace#6126

### Voertuig model

Alle voertuigen met lightbars

### Omschrijf de bug

Als er lightbars van de DSI/recherche op een voertuig staan, is het niet mogelijk om met een snijbrander het voertuig open te branden. Dit is eerder ook al een probleem geweest en dit zou toen gefixt zijn, maar dit is bij een hoop voertuigen nog altijd niet het geval.

### Repro

- Pak een G65
- Maak er lightbars op en laad deze
- Probeer deze open te branden met een snijbrander

### Normaal gedrag

De snijbrander opent het voertuig, of het open branden van het voertuig faalt en je moet het opnieuw proberen.

**Comment by niekschoemaker** [comment]
Bedankt voor het melden.

Deze issue is na de volgende restart gefixed.

Als dit niet het geval is graag even mij taggen in deze issue, dan heropend iemand de issue.
