### ISSUE TITLE
[FEATURE]: Gezamenlijke bootopslag voor officiële groepen

### ISSUE THREAD

**Issue by Haceyy** [Tedeapolis/development#1621]
### Contact Details

hace#6126

### Beschrijf zo duidelijk mogelijk de feature

Dat officiële gangs een gedeelde bootopslag krijgen, soortgelijk aan de voertuigopslag die we hebben. Momenteel hebben officiële groepen ook al zo'n gedeelde vliegtuigen opslag in Sandy en het zou leuk zijn als we ook een bootopslag kunnen delen.

De locatie die wij voorstellen is ergens in de haven, maakt niet zo zeer uit waar.

### Wat lost deze feature op?

Dat wij net als voertuigen en vliegtuigen dan ook vaartuigen van elkaar kunnen lenen zodra deze in de gezamenlijke opslag gezet worden door de leden.

**Comment by Nander0320** [comment]
Hey @Haceyy dit is helaas niet uitvoerbaar aangezien de andere 2 zijn toe te voegen rondom het huis van de gang, dit is hier helaas niet mogelijk
