### ISSUE TITLE
[FEATURE]: Optie om repair animatie cancellen.

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1622]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Als je op eiland bent en je voertuig aan het repareren bent dat je met een bepaalde knop de repair animatie kan annuleren.

### Wat lost deze feature op?

Mogelijkheden om sneller te handhaven stel er is iemand met een slagwapen dichtbij jou.

**Comment by Chang-nl** [comment]
Bedankt voor het aanmaken van deze feature request. Na de herstart is het opgelost!
