### ISSUE TITLE
[FEATURE]: 1 loods per locatie

### ISSUE THREAD

**Issue by Haceyy** [Tedeapolis/development#1623]
### Contact Details

hace#6126

### Beschrijf zo duidelijk mogelijk de feature

Na een suggestie vanuit de community en ook uit eigen ervaring kwamen we erachter dat het bij sommige loods locaties zo is dat er meerdere sleutelhouders zijn voor 1 loods.

Nu komt het voor dat meerdere loodsen dus op een gedeelde locatie zitten, wat niet heel realistisch is. Dit gaat om prof loodsen.

### Wat lost deze feature op?

Mensen betalen bakken met geld voor een loods en werken daar hard voor, op het moment dat er meerdere mensen toegang hebben tot 1 en dezelfde loods locatie, kan het zo zijn dat de één een onderzoek laat starten tegen zich, waardoor indirect de andere eigenaar van de loods op dezelfde locatie ook de klos kan zijn. Hierdoor zou al het harde werken verloren kunnen gaan.

Bovendien is het in het echt ook niet zo dat er 2 drugsloodsen in 1 warenhuis zitten. Je betaalt al genoeg voor een loods, dus wat ons betreft ook reden genoeg om de locaties beperkt te houden tot 1 eigenaar per locatie.

Wellicht dan ook extra locaties toevoegen, mocht het lastig uitkomen met de huidige.

**Comment by Haceyy** [comment]
Aanvulling van burger Dennise Cakir:
"Bij mij stond er een keer toen ik op cirkel van de loods stond kies loods 410 of 410 ik weet niet of dat er iets mee te maken heeft dat er meerdere loodsen daar zijn."

Wellicht ook handig om mee te nemen in het bovenstaande.

**Comment by Chang-nl** [comment]
Bedankt voor het melden. De issue is sinds ongeveer een week opgelost!
