### ISSUE TITLE
[Bug]: FMJ Magazine (AK-74 / AK-12)

### ISSUE THREAD

**Issue by Mxcro1** [Tedeapolis/development#1625]
### Contact Details

Faiss#9999

### Wat gebeurde er?

(Dit zou na de restart gefixt zijn 9 dagen geleden)
Maar het zit er nog niet in dus hier even een reminder!

**_[niekschoemaker] commented] 9 Days ago
Oh oepsie, vergeten toendertijd, zit erin na volgende restart._**

Hier een klein iets wat gefixt moet worden:

FMJ Magazine's zijn toegevoegd je kan ze op zowel de m1911 en baretta zetten

Sinds deze Feature erin zit kan je deze magazine niet op de (Ak-74 - Ak-12) zetten
Echter kan je de ammo/clip wel inkopen alleen heeft het nu geen nut gezien je de magazine niet kan kopen
![hgsdfhsDASH](https://user-images.githubusercontent.com/102612000/190291478-6620b32e-2e5b-46b5-a2d2-9919f657d085.png)
![hfsahfha](https://user-images.githubusercontent.com/102612000/190291482-fb1ad911-aa4f-4930-b9ed-d08363c93d37.png)

### Frequentie van de bug

Altijd

**Comment by niekschoemaker** [comment]
Hold up, heb ik nou serieus alles gefixed aan fmj en ben ik uiteindelijk vergeten simpelweg dit aan te zetten in de   config? 😢 
Ik zal ff checken

**Comment by niekschoemaker** [comment]
Oh wauw, ik ben de config van de criminele jobs vergeten te comitten 🤦

**Comment by niekschoemaker** [comment]
Zou er volgende restart in moeten zitten, zo niet tag me even in deze issue

**Comment by Attomn** [comment]
na 2 dagen geen update meer gehad dus wordt gezien als opgelost :)
