### ISSUE TITLE
[Bug]: Eiland weer bugged

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1626]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je op eiland bent en je kijkt naar het weer word het soms plots donker. Daarnaast word het soms licht en dag op eiland.

### Wat hoorde er te gebeuren?

Hoort gewoon rustig donker te worden niet plots donker en ook random licht.

### Wat veroorzaakt de bug?

geen idee, staat  niets in f8.
1. In de main op eiland wandelen / rijden
2. Bekijk het weer en je ziet het soms random donker worden 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by CalRayy** [comment]
https://www.youtube.com/watch?v=WkNoLJ5y6KA

**Comment by niekschoemaker** [comment]
He wat flauw dat het eiland alweer gebugged is, ik heb het gefixed.
