### ISSUE TITLE
[Bug]: adminonduty en noclip tijdens het inloggen doet raar

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1629]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je net inlogged bent en je was onduty krijg je de melding "ga aub in dienst met /adminonduty " alleen dat ben je al dan ga je off duty.

Soms heb ik de melding niet als ik inlog maar dat noclip gebugged / raar doet dan doe ik /noclip dan zegt hij: 
![image](https://user-images.githubusercontent.com/101106299/190895958-b10d4b22-b0fb-4a09-beeb-0ad653a0edf1.png)
dan geeft hij net zoals deze screenshot gelijk noclip disabled en enabled maar je zit niet in noclip en valt naar je dood.
Hoe je dit fixed is door off duty te gaan en terug on duty vervolgens weer /noclip.

### Wat hoorde er te gebeuren?

Je hoort de melding soms niet te krijgen van "ga aub in dienst met /adminonduty" en dat noclip af en toe raar doet als je pas inlogt.

### Wat veroorzaakt de bug?

ik denk persoonlijk dat het komt omdat in je vorige sessie in noclip zat?
Stappen die ik deed:
1. start fivem op
2. logt in op TDA
3. Krijgt de melding links van ga "ga aub in dienst met /adminonduty" (maar je zit nog in de luchtscherm / laadscherm)
4. vervolgens doe /adminonduty omdat je denkt dat je offduty bent (wat niet zo is)
5. je doet weer adminonduty voor snel onduty te gaan want je zit midden in de lucht (en je gaat dood als je niet noclipt)
6. dan als je probeert te noclip krijg je de melding "noclip has been disabled" en "noclip has been enabled" alleen werkt noclip niet
7. je kan dit fixen door off duty en weer onduty te gaan
8. nu werkt noclip weer

### Frequentie van de bug

1x per dag

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
Is gefixed na volgende herstart
