### ISSUE TITLE
Rolls-Royce Phantom visual bug

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#163]
In de supporter-only Rolls-Royce Phantom zit een visueel bugje; het dak en de motorkap (ik vermoed dat dat respray secondary is) zit een vreemd patroon wat lijkt op een verkeerd geplaatste / repeat pattern image. Heel storend om te zien, dus ik vroeg me af of dat te fixen was! :)

**Comment by Attomn** [comment]
Dit "probleem" wordt veroortzaakt door de dirtmap, auto is gewoon altijd vies als je hem ergens uit trekt.

**Comment by PapaXilion** [comment]
Hm... wel irritant. De dirtmap heeft lijkt het wel een soort repeat-texture waardoor er een soort schaakbord te zien wordt. Dat zal dan niet te fixen zijn gok ik?
