### ISSUE TITLE
[EUP]: Steekvest AMBU

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1631]
### Contact Details

Wilma Wonka#4312

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Suggestie: Scherf/steek/kogelvrij vesten / helmen 

Aangezien we merken dat we als ambulanciers in steeds minder veilige situaties komen in TDA-stad denk ik dat het handig is om de ambulanciers uit te rusten met een scherf/steek/kogelvrij vest dit omdat ambulanciers steeds vaker moeten werken bij bvb schiet/steekmeldingen van de politie/kmar waarbij ik altijd denk is het niet handig dat we de mogelijkheid hebben om een vest aan te trekken opdat onze vitale organen beter beschermt zijn. In het echt hebben veel regionale ambulance diensten ook een vest ter bescherming van de medewerks in ieder geval in Almelo wel. Ik zou het fijn vinden of er hier mogelijk naar gekeken kan worden.

Ik weet niet of deze hier hoort. Sorry als ie verkeerd staat. Maar volgens mij is deze ooit aangemaakt maar  kan het nergens meer terug vinden wat hier op was gezegt!

**Comment by CorruptSausage** [comment]
@walvisgedaan zou dit misschien mogelijk zijn voor jou?

**Comment by DevvTDA** [comment]
Ik kan kijken voor een soort steekvest om toe te voegen voor zowel mannen en vrouwen.

**Comment by WilmaWonka1985** [comment]
Dank je wel dr voor. We wachten het veder gewoon rustig af.

**Comment by DevvTDA** [comment]
Overigens is een steekvest alleen voor sier en doet niet daadwerkelijk minder damage of iets. is dat wel de intentie of is het voor enkel show?

**Comment by WilmaWonka1985** [comment]
ze willen heel graag dat ze er wel door beschermd kunnen worden. dat ze bijvoorbeeld niet meteen dood zijn door een kogel als ie eerst tegen dat vest aankomt.

Maar als dat niet mogelijk is dan maar voor de sier/fun

**Comment by DevvTDA** [comment]
Nee dat is inderdaad niet mogelijk

**Comment by WilmaWonka1985** [comment]
Dan mogen ze het lekker voor de fun/sier dragen en het idee hebben dat ze zich een stuk veiliger voelen :)

**Comment by DevvTDA** [comment]
Zit er in voor mannen en vrouwen
