### ISSUE TITLE
[EUP]: Kmar dames

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1632]
### Contact Details

Ljosfari#3575

### Waar bevind de issue zich?

EUP/Kleding

### Toevoegen:

- [x] Zwaar steekvest
- [x] OVD hesje
- [ ] OPCO hesje
- [x] Reflecterend hesje
- [x] HRB outfit

**Comment by walvisgedaan** [comment]
Zou je iets meer context kunnen geven over wat er precies niet klopt?

**Comment by Ljosfari** [comment]
het zit er niet in, dat klopt er niet :D

**Comment by walvisgedaan** [comment]
Hmm oke, dan snap ik de issue haha. Ik ga er mee aan de slag :D

**Comment by Ljosfari** [comment]
@DevvTDA jij bent echt heel lekker bezig!

**Comment by DevvTDA** [comment]
Zit in de server!
