### ISSUE TITLE
[Bug]: Nieuwe shock komt random in beeld. 

### ISSUE THREAD

**Issue by Jaydpn** [Tedeapolis/development#1635]
### Contact Details

Jaydpn#5445

### Wat gebeurde er?

Hoi, 

Ik haalde als agent een voertuig uit de opslag, daarbij kreeg ik de random beeld shock (als je crasht). 
(Zie video) 

Van burgerraad hace#6126 moest ik een bug github maken, want dit hoort niet te gebeuren. 

https://www.youtube.com/watch?v=D1TdX1hmh-I

### Wat hoorde er te gebeuren?

Geen beeld shock. 

### Wat veroorzaakt de bug?

Geen idee. 

### Frequentie van de bug

Sporadisch/Heel soms

**Comment by niekschoemaker** [comment]
Is gefixed
