### ISSUE TITLE
[Bug]: /dvfine werkt niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1636]
### Contact Details

CalRay#1513

### Wat gebeurde er?

/dvfine werkt helaas niet, dit staat er f8: 
![image](https://user-images.githubusercontent.com/101106299/192003953-e03c3f28-ce74-48b9-b837-bf9c3ed2a061.png)

### Wat hoorde er te gebeuren?

je hoort normaal een voertuig te kunnen verwijderen en een boete geven aan de eigenaar van het voertuig.

### Wat veroorzaakt de bug?

![image](https://user-images.githubusercontent.com/101106299/192003999-d1fae01c-23e7-4aed-878f-42603b30296e.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
