### ISSUE TITLE
[FEATURE]: Politiegarage op voertuignaam laten gaan, niet op alfabetische volgorde van de kentekens.  

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1637]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Politiegarage op voertuignaam laten gaan, niet op alfabetische volgorde van de kentekens.

Maakt alles een heeeel stuk duidelijker. Is overigens niet veel werk. 

Momenteel gaat alles op de eerste letter van het kenteken. Dus je volgorde is helemaal door elkaar.
Het zou fijn zijn als alles op voertuignaam staat.

Zo staan alle unmarkeds ook bij elkaar.

Of de mogelijkheid maken om een nieuwe optie toe te voegen: Naam aanpassen.
Dit kan tussen het lijstje van:
Voertuig pakken
Voertuig opslaan
Voertuig verwijderen
**Nieuw**: Voertuigen hernoemen
### Wat lost deze feature op?

Onnodig zoekwerk. Maakt alles veel duidelijker, ziet er professioneler uit.

**Comment by PolitieTDA** [comment]
Akkoord vanuit de politie.

**Comment by CorruptSausage** [comment]
Voertuigen zullen na de restart op naam gesorteerd worden, er moet nog even gekeken worden naar de label van de amarok omdat deze namelijk een kleine letter heeft. Hij staat dus achteraan.
