### ISSUE TITLE
[FEATURE]: Narcos rang aanpassen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1638]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

De rang Empresario toegang geven tot alle wapens te tunen, betekend dus ook dat ze alles kunnen inkopen.

### Wat lost deze feature op?

Zodat meer mensen wapens kunnen tunen en niet 2 man die bevoegd is daarvoor.

**Comment by Willem-Dekker** [comment]
fixed en klaar voor merge
