### ISSUE TITLE
[FEATURE]: HRB Meldkamer

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1639]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

Een meldkamer zoals de DSI en Recherche ook hebben voor "Intern" gebruik door de Politie en KMar om de HRB te kunnen oproepen en onderling elkaar oproepen. Daarnaast word het ook gebruikt om locaties naar elkaar te versturen.

Rangen:
kmar 100
kmar 95
kmar 90

kmar 80
kmar 81

kmar 70
kmar 71
kmar 72
kmar 73
kmar 74

- Uitdienst dienen de bovenstaande rangen ook meldingen te krijgen.

### Wat lost deze feature op?

Momenteel gebruikt de HRB de KMar meldkamer om locaties te ontvangen van o.a. de Politie en DSI dit is verwarrend voor de normale KMar dienst die berichten krijgen waarvan ze niet weten waarvoor die is. Voor onderling locaties sturen en elkaar oproepen gebruikt de HRB momenteel een deepweb dit blijkt vervelend te werken en wel eens te zijn gelekt de afgelopen jaren.

**Comment by niekschoemaker** [comment]
Ik zie hier dat kmar 80 en kmar 81 bsb rangen zijn, maar de rest van de bsb rangen staan er niet bij, klopt dit?
@Streamcentralrulez

**Comment by Streamcentralrulez** [comment]
> Ik zie hier dat kmar 80 en kmar 81 bsb rangen zijn, maar de rest van de bsb rangen staan er niet bij, klopt dit? @Streamcentralrulez

Ja Niek dat klopt. Het kan soms zijn dat er HRB leden bij de KLu zitten zij hebben dan de kmar 80 of 81 rang.

**Comment by KMarTDA** [comment]
Hi! Was hier al een status update voor? Staat al een aantal maanden open.
