### ISSUE TITLE
Kmar uren logger kopieren naar spreadsheet

### ISSUE THREAD

**Issue by Robertowhh** [Tedeapolis/development#164]
Is het mogelijk om de KMAR uren logger te kopieren naar een spreadsheet? Het gaat om dit document https://docs.google.com/spreadsheets/d/1-9p1xF6CV_Gb-dvqmwEBe83nmhGS2J4rQN1sYuXsO8Q/edit#gid=0

**Comment by Willem-Dekker** [comment]
Nee

Met vriendelijke groet

Willem Dekker

________________________________
