### ISSUE TITLE
[FEATURE]: Nieuwe telefoon script

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1640]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In staff overleg hebben we besproken om een nieuwe telefoon script aan te schaffen, omdat de huidige zeer moeilijk aan te passen. 

https://forum.cfx.re/t/paid-esx-qbcore-any-framework-high-phone-truly-the-best-looking-phone/4778619

Deze script kan je sms groepen maken, auto's verkopen op een betere manier en nog veel meer.

### Wat lost deze feature op?

Huidige is moeilijk aan te passen, nieuwe script zou dit oplossen

**Comment by CalRayy** [comment]
https://www.youtube.com/watch?v=XmLwlBqD1nE
https://store.lbphone.com/
Ik had deze ook gevonden, heeft ook veel leuke features.

**Comment by Nander0320** [comment]
Niek is op dit moment al bezig met de telefoon te moderniseren
