### ISSUE TITLE
[FEATURE]: taxi uitdienst  salaris

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1642]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

we hebben al heel lang geen update gedaan omtrent salaris uit dienst 
die staan nog op de oude gegevens 
hier bij een lijstje waar de nieuwe uit dienst salaris in staat 

Uitdienst Salaris:
Chef: 850
Chef-Recruitment: 750
Chef-Marketing: 750
Manager: 700
Recruiter: 550
Marketing: 520
Uber-1: 350
Uber-2: 350
Uber-3: 325
Uber-4: 300
Uber-5: 300
Taxichauffeur-1: 260
Taxichauffeur-2: 250
Taxichauffeur-3: 240
Taxichauffeur-4: 230
Taxichauffeur-5: 220
Regiotaxi-1: 200
Regiotaxi-2: 190
Regiotaxi-3: 180
Regiotaxi-4: 170
Uitzendkracht: 150

als er een format is waar we aan moeten houden dan zie ik die graag tegemoet alvast bedankt -ali 

### Wat lost deze feature op?

dat mensen stoppen met zeuren om uit dienst salaris 
omdat we het nooit aan gepast hebben moeten we met de tijd mee

**Comment by Willem-Dekker** [comment]
fixed na rastart
