### ISSUE TITLE
[Aanpassing Ambu]: Locatie in ganghuis

### ISSUE THREAD

**Issue by BertBrug** [Tedeapolis/development#1643]
### Contact Details

Eseclick#1865

### Wat gebeurde er?

Bij de ambulance job is er een mogelijkheid om medicijnen rond te rijden. Je komt dan op verschillende locaties en daar dien je medicijnen af te leveren. Echter zit een van deze punten in een recent geplaatst gang huis.

### Wat hoorde er te gebeuren?

Nou eigenlijk hoorden daar medicijnen geleverd te worden, maar dit kan dus niet meer :3

### Wat veroorzaakt de bug?

Even ambulancier worden en medicijnen gaan rijden.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Logbestanden heb ik niet, maar het is niet zo handig dat de locatie hier zit, want anders wordt er straks nog stiekem ambulancepersoneel ontvoerd of gerekruteerd.

**Comment by niekschoemaker** [comment]
Om welke postcode gaat dit of om welke locatie uberhaupt?

**Comment by Ljosfari** [comment]
staat al een issue over open: https://github.com/Tedeapolis/development/issues/1593
