### ISSUE TITLE
[FEATURE]: KMar facturen

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1644]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

Om net als bijv. de Taxi wekelijks een CSV met de facturen van KMar personeel op te sturen naar de Kmar mailbox.

-- Besproken met Willemde20 in voice

### Wat lost deze feature op?

Dat we de facturen kunnen inzien per persoon.

**Comment by Willem-Dekker** [comment]
vanaf maandag krijg je ze binnen
