### ISSUE TITLE
[FEATURE]: Burgerraad overleg dragg strip

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1645]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

• Aan het einde van de dragg strip een plek waar je auto bijna instant stopt/ remt zo dat je vol gas kan en niet gaat vliegen over de duinen er achter (Ali)

is overlegt in de burgerraad 

als idee een rem naar 50kmph als je de laatste cirkel raakt

### Wat lost deze feature op?

sommige mensen vliegen over de duinen omdat ze niet kunnen remmen met hun auto waar door die kapot vliegt en is dan meteen kapot

**Comment by niekschoemaker** [comment]
Zit erin
