### ISSUE TITLE
[FEATURE]: Gele cirkels toevoegen bij grote garage's

### ISSUE THREAD

**Issue by NouNou0** [Tedeapolis/development#1647]
### Contact Details

NouNou#2004

### Beschrijf zo duidelijk mogelijk de feature

Er zijn geen gele cirkels bij gemeentehuis (postcode 7041) en HB garage (postcode 5012). Ik zou deze graag toegevoegd zien worden 

### Wat lost deze feature op?

Lost niks op is meer voor t gemak

**Comment by CorruptSausage** [comment]
Heb je hiervoor al een suggestie ingediend in het suggesties kanaal in de main server?

**Comment by CorruptSausage** [comment]
Je hebt 5 dagen gekregen om de issue aan te passen, ik ga deze nu sluiten.
