### ISSUE TITLE
[FEATURE]: Benzine prijs omhoog

### ISSUE THREAD

**Issue by nickdb04** [Tedeapolis/development#1648]
### Contact Details

AntonMoskvin#3144

### Beschrijf zo duidelijk mogelijk de feature

De bedoeling is dat de benzine prijs verhoogd word, dit was een beste tijd geleden al afgesproken in staff overleg alleen is hier nooit een github issue voor gemaakt dus bij deze.

De bedoeling is dat mensen meer betalen voor benzine en er dus voor zorgt dat er meer geld uit de economie gehaald word.

### Wat lost deze feature op?

Een te snel groeiende economie met mensen die veel te veel geld hebben.

**Comment by Chang-nl** [comment]
Na herstart is deze hoger!
