### ISSUE TITLE
[FEATURE]: Transmissie tunen werkt niet op de Issi Sport

### ISSUE THREAD

**Issue by zeletix** [Tedeapolis/development#1649]
### Contact Details

Letix#1424

### Voertuig model

Issi Sport (spawncode: issi7)

### Omschrijf de bug

Wanneer je in een modshop naar tunes gaat in een Issi Sport, staat de transmissie tab er wel, maar kan je hem niet openen.

### Repro

Spawn een issi7 in, ga ermee naar de modshop en probeer er transmissie op te zetten

### Normaal gedrag

Je zou de transmissie tab moeten kunnen openen zodat je transmissie 1-4 erop kan zetten

**Comment by zeletix** [comment]
de transmissie tab* oops

**Comment by Chang-nl** [comment]
Even reloggen / opnieuw de modshop in gaan. Dit zal de issue oplossen.

**Comment by zeletix** [comment]
> Even reloggen / opnieuw de modshop in gaan. Dit zal de issue oplossen.

Beide hebben helaas niet voor mij gewerkt
