### ISSUE TITLE
[FEATURE]: Logging toevoegen aan Overheidsdiscord voor wannneer er Medicatie wordt gereden als Ambulancier

### ISSUE THREAD

**Issue by TDANYX** [Tedeapolis/development#1650]
### Contact Details

Nyxx#2490

### Beschrijf zo duidelijk mogelijk de feature

Voegt logging toe aan discord wanneer een Ambulancier medicatie heeft bezorgd.

### Wat lost deze feature op?

Inzage wanneer een Ambulancier meldingen rijdt of bezig is met medicatie rijden.

**Comment by CorruptSausage** [comment]
Fixed na restart.
