### ISSUE TITLE
[FEATURE]: De objects bordjes bij mazebank garage weg halen.

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#1651]
### Contact Details

ToniGain#0001

### Beschrijf zo duidelijk mogelijk de feature

De objects bordjes bij mazebank garage weg halen.

### Wat lost deze feature op?

Lampjes. Zorgt voor engine damage, iedere keer moet je ze omver rijden als je je garage in of uit wil. Uiteindelijk maakt het je auto dus stuk, ze blijven ook respawnen. 
![image](https://user-images.githubusercontent.com/73707925/193405770-9f6986f3-4d82-4508-a521-e7f586d288c1.png)

**Comment by AntonMTDA** [comment]
Fix ligt klaar alleen even wachten op akkoord van oesewoes :)

@ToniGain

**Comment by Oesewoes** [comment]
Is helemaal mooi, aangevraagd op discord.
Geef @AntonMTDA die credits

**Comment by AntonMTDA** [comment]
Is gecommit :D

**Comment by Oesewoes** [comment]
Sluiteeee
