### ISSUE TITLE
[Bug]: Deepweb berichten laden niet in soms

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1652]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je soms een deepweb opent dan laad die de berichten in de deepweb niet in en moet je het af en toe heropenen om de berichten te zien.
![Uploading image.png…]()

### Wat hoorde er te gebeuren?

je hoort de berichtne gelijk te kunnen zien.

### Wat veroorzaakt de bug?

1. je opent een deepweb
2. je krijgt rechtsonder een bericht dat ik opnieuw moet proberen
3. soms lukt het om het opnieuw te openen
![image](https://user-images.githubusercontent.com/101106299/193409546-58424617-a4cb-46bb-914d-e8c837852510.png)
in F8 staat ook geen errors, gewoon de normale dingen.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
zijn er meer mensen die hier last van hebbe ? heb dit nog nooit gezien

**Comment by CalRayy** [comment]
> zijn er meer mensen die hier last van hebbe ? heb dit nog nooit gezien

Heel veel mensen van mijn gang hebben hier dagelijks last van en ik ook wel. Kan het zijn om dat ik 6 deepwebs heb dat die moeilijk doet ?

**Comment by CorruptSausage** [comment]
> Heel veel mensen van mijn gang hebben hier dagelijks last van en ik ook wel. Kan het zijn om dat ik 6 deepwebs heb dat die moeilijk doet ?

Ik begon hier persoonlijk ook pas last van te krijgen toen ik inderdaad rond de 6+ deepweb kanalen had.

**Comment by CalRayy** [comment]
Ik heb hier helaas nog altijd last van, en heb persoonlijk 10+ deepwebs. Het duurt soms minuten voordat het werkt (je kan het fixen door erin en uit te gaan of reloggen). En hopen dat die dan wel werkt.

**Comment by Chang-nl** [comment]
Hey @CalRayy,

Bedankt voor het aanmaken van de github issue! Hoe valt de bug te reproduceren? En gebeurt het vaker met meer deepweb kanalen of maakt dit niet uit? Alvast bedankt!

**Comment by CalRayy** [comment]
> Hey @CalRayy,
> 
> 
> 
> Bedankt voor het aanmaken van de github issue! Hoe valt de bug te reproduceren? En gebeurt het vaker met meer deepweb kanalen of maakt dit niet uit? Alvast bedankt!

Je kan deze bug reproduceren doormiddel van meerdere deepwebs te zitten die actief zijn, ik zit bijvoorbeeld in 15 deepwebs ongeveer waar er actief in gepraat word (elke dag) en als ik dan elke deepweb check dan komt dit af toe voor. Ik wil het je best in call laten zien als je daar tijd voor hebt.

**Comment by Chang-nl** [comment]
Hey @CalRayy,

Bedankt voor het melden van de issue!

Als het goed is is de issue gefixt!

**Comment by CalRayy** [comment]
> 

ik heb de bug net weer gekregen of is dit pas gefixt bij de restart?

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/214620342-972391c1-8d8d-420b-b44a-9cfb327bbf91.png)

**Comment by Chang-nl** [comment]
Hey @CalRayy,

Mijn excuses. Ik ben het vergeten te melden. Het is gefixt bij de volgende herstart!
