### ISSUE TITLE
[FEATURE]: Quicksell deepweb (meldingen)

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1654]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

Besproken in Staff overleg van 02-10

Op dit moment wordt de quicksell vrij weinig/slecht gebruikt ondanks dat het genoeg opbrengt en heb je daar vrij spel op het moment dat je deze wilt gebruiken. Het idee is dat er een een deepweb wordt gemaakt met meldingen dat er ergens wordt gequickselled, zonder te zeggen waar het is.  

Bijvoorbeeld:
Er is iemand drugs aan het quicksellen in de stad, je kan hem overvallen. 

### Wat lost deze feature op?

Quicksell kan weer meer worden gebruikt, vooral vanuit de gangs wordt het dan interessant en zit er meer RP aan het quicksellen.  
Het kan vervolgens een zoektocht worden naar waar er gequickselled worden en dit kan dus leiden tot interessante RP scenario's

**Comment by Chang-nl** [comment]
Hey @KeesdeB,

Is dit nog steeds nodig? Mocht dit nog nodig zijn, graag dan een agendapuntje aanmaken voor het staffoverleg. Alvast bedankt!

**Comment by KeesdeB** [comment]
> Hey @KeesdeB,
> 
> Is dit nog steeds nodig? Mocht dit nog nodig zijn, graag dan een agendapuntje aanmaken voor het staffoverleg. Alvast bedankt!

Dit was al besproken in staf overleg en is goedgekeurd.
