### ISSUE TITLE
[FEATURE]: BSN toevoegen op ID-kaart en in MEOS

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1655]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een BSN toevoegen op iedereen hun ID-kaart en op hun MEOS profiel. 

### Wat lost deze feature op?

Besproken in staffoverleg. Zorgt ervoor dat mensen niet van character kunnen wisselen om zo te voorkomen dat ze nog herkend worden aan hun ''oude'' character. Dit bijvoorbeeld tijdens politie RP waarbij ze in het cellencomplex zitten of wanneer ze weten dat ze een signalering hebben gekregen.

**Comment by Chang-nl** [comment]
Hey @ARJ3N,

Bedankt voor je feature request!

Na de herstart zitten er BSN nummers op de id kaarten.

De feature voor BSN nummers is geïmplementeerd in de meos alleen moet dit nog doorgevoerd worden. Heb gelijk even een extra zoekfunctie toegevoegd, zodat je ook specifiek op BSN nummer kan zoeken.

**Comment by ARJ3N** [comment]
@Chang-nl fantastisch, dankjewel! :)
