### ISSUE TITLE
[FEATURE]: Extra voertuigen garage

### ISSUE THREAD

**Issue by MatteDB** [Tedeapolis/development#1657]
### Contact Details

MatteDB#4517

### Beschrijf zo duidelijk mogelijk de feature
_Dit werd besproken tijdens het overleg van 3/10 besproken en ik moest hiervoor een Github issue maken. Bij deze:_

Op dit moment hebben we in TDA de Mazebank garage waar je je voertuigen kan tentoonstellen. Voor deze garage betaal je 1 miljoen voor de eerste 5 plekken, 500 duizend voor de volgende 5 plekken en 750 duizend voor de laatste 5 plekken. Dit brengt het totale kostenplaatje op een mooie 2.25 miljoen wat dus een pak geld is voor de gewone burger.

Nu lijkt het me leuk dat de spelers die geen tonnen per week verdienen, maar wel een mooie verzameling van JDM-auto's hebben of Amerikaanse klassiekers, ook zo een plekje kunnen kopen. Het idee gaat als volgt:

Je koopt het pand en standaard krijg je 1 of 2 plekken, als je meer plekken wilt dan koop je deze gewoon. Je kan er max 6 à 7 kopen, zie de afbeelding hieronder voor een eventuele indeling.
![afbeelding](https://user-images.githubusercontent.com/37267349/193628023-7bf15d82-03b5-4f74-87ee-bd6cdfd04aed.png)

Waar kan je deze garage hebben?

Overal waar er zo een verdiepingsgarage zit heb je zo een modshop erboven, ik heb nu bijvoorbeeld het appartementsgebouw nabij Lombank genomen. Hier heb je ook een ondergrondse garage met een lift die naar boven kan.
![afbeelding](https://user-images.githubusercontent.com/37267349/193628471-69796a24-5b2b-49b4-a98c-f42d18ee0667.png)

### Wat lost deze feature op?

De huidige garage is wel leuk en mooi maar het is jammer voor echte auto-enthousiastelingen dat ze niet al hun auto’s tegelijkertijd kunnen zien. Daarnaast geeft deze garage een gevoel dat je in een tunershop zit, je hebt de apparaten, de kastjes de autoliften enzovoort. Daarnaast heb je ook een kleine zitruimte voor als je met je vrienden even gezellig wil babbelen.
Daarnaast is deze kleine ruimte wat leuker voor mensen met een kleinere collectie en heb je ook niet die lege verdiepingen daarboven. 
Als laatste hebben we ook mensen die het huidige pand al vol hebben en dit geeft hun ook weer de kans om mooie voertuigen neer te zetten.

En als laatste denk ik ook dat dit voor scenario’s kan zorgen, je kan zogezegd aan je wagens werken en er eventueel een verhaaltje aan vastknopen. Maar ook kan dit voor prachtige foto’s zorgen.

**Comment by Chang-nl** [comment]
Hey @Nander0320,

Wanneer word dit besproken? Want je hebt wel de staffoverleg label gegeven.

**Comment by MatteDB** [comment]
Hai @Chang-nl, dit was al in het staffoverleg besproken en ik moest hiervoor gewoon een github issue maken.
