### ISSUE TITLE
[Bug]: Spawnplekken van politie hb dak bugged soms

### ISSUE THREAD

**Issue by Misha0717** [Tedeapolis/development#1658]
### Contact Details

Misha#0460

### Wat gebeurde er?

Op het moment wanneer je een heli wilt pakken op het dak van politie hb(in de stad) krijg je heel vaak een message 'alle spawnplekken zijn op dit moment geblokkeerd' terwijl dit niet het geval is. Je moet dan echt een halve meter van de helipad af lopen en dan heb je soms de kans dat het dan wel weer werkt maar soms is het geval dat het alsnog niet werkt. Is er dus een mogelijkheid om de radius van de check omlaag te zetten waardoor jezelf niet in de weg staat om een heli te pakken?

### Wat hoorde er te gebeuren?

De heli gewoon laten spawnen op het moment wanneer er niks geblokkeerd word.

### Wat veroorzaakt de bug?

Waarschijnlijk sta je zelf op de spawnplek waardoor het geblokkeerd word.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

-

**Comment by CorruptSausage** [comment]
Zou je hier wellicht een clip van kunnen maken?

**Comment by Misha0717** [comment]
> Zou je hier wellicht een clip van kunnen maken?

lijkt me niet nodig lijkt me? Vertel stap voor stap wat het probleem is :P

**Comment by CorruptSausage** [comment]
> > Zou je hier wellicht een clip van kunnen maken?
> 
> lijkt me niet echt nodig? Vertel stap voor stap wat het probleem is :P

Alsnog is het fijn als hier een clip bij komt, alvast bedankt!

**Comment by PieterBert** [comment]
> 

https://user-images.githubusercontent.com/111922042/195921649-b2d87e40-7e1c-40f4-afae-3d533078fc95.mp4

**Comment by CorruptSausage** [comment]
> > 
> 
> Moments-clip-from-Oct-14-2022.mp4

Thanks.

**Comment by CorruptSausage** [comment]
Fixed na restart
