### ISSUE TITLE
[Bug]: Recoil Fix / Teststad opnieuw syncen 

### ISSUE THREAD

**Issue by Mxcro1** [Tedeapolis/development#1659]
### Contact Details

Faiss#8325

### Wat gebeurde er?

Recoil die het niet goed deed is gefixt deze restart 

Alleen is dit niet gefixt op de teststad wel op een paar wapens maar bijv de ak-12 is de recoil bugg er wel nog OP (Teststad)

Dit heeft natuurlijk geen prio, alleen is het wel fijn als het gemaakt zou kunnen worden.

(Mischien handig om weer de main server te syncen met de teststad na een lange tijd)

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

**Comment by CorruptSausage** [comment]
Ik ga deze issue sluiten aangezien hier weinig/geen informatie in staat over het daadwerkelijke onderwerp, daarnaast staan er 2 onderwerpen in 1 issue.
