### ISSUE TITLE
[FEATURE]: Verhoog opslag van (eigen) vuilniswagen

### ISSUE THREAD

**Issue by jaim1114** [Tedeapolis/development#1660]
### Beschrijf zo duidelijk mogelijk de feature

Momenteel is de opslag van de vuilniswagen 40kg. Voor de job-versie van dit voertuig is dit prima, je gebruikt de opslag immers niet tijdens het uitvoeren van je baan als vuilnisman. Voor de mensen die deze vuilniswagen als eigen voertuig hebben is dit echter nogal aan de lage kant.

De vissersbus (Vapid Benson) heeft momenteel een opslag van 300kg. Deze bus heeft dezelfde prijs als de vuilniswagen, namelijk 500k. Gezien het feit dat de vuilniswagen ongeveer even groot is als de vissersbus, lijkt het mij niet meer dan logisch om de vuilniswagen ook een opslagruimte van 300kg te geven.

### Wat lost deze feature op?

De prijs-opslag verhouding eerlijker maken.

Daarnaast is het ook leuker voor kmar, aangezien er met deze verandering de kans bestaat dat er verboden goederen tussen het vuilnis vervoerd worden. Hebben zij weer redenen om ook de vuilniswagens in douanegebieden te checken ipv dat dit een jobvoertuig is die 'toch niks bij zich heeft'.

**Comment by CorruptSausage** [comment]
Is hier al een suggestie over ingediend bij suggesties? Zo niet, doe dit eerst even. Dan maakt het community team een issue hiervoor aan.
