### ISSUE TITLE
[Bug]: "Stoelverwarming" kmar SIV

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1661]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

De "stoelverwarming" werkt nog bij de kmar audi (/car kmaraudi) waardoor deze een upgrade naar motor 2 krijgt zodra iemand anders even achter het stuur kruipt of nadat de ANWB er aan gewerkt heeft. Bij overige politievoertuigen is dit uitgeschakeld maar blijkbaar niet bij de kmar audi. Hierdoor pakt dit nadelig uit voor criminelen in een achtervolging.

### Wat hoorde er te gebeuren?

Auto hoort zelfde snelheid aan te houden ipv sneller kunnen door upgrade.

### Wat veroorzaakt de bug?

/

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Lorenzo3001** [comment]
Fixed
