### ISSUE TITLE
[Bug]: Weg voor Benny's 

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1662]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

De weg/steeg voor Benny's (postcode 4002) lijkt op een verharde weg maar is eigenlijk een onverhard zandpad. Hierdoor glijden auto's die niet gemaakt zijn voor off-road vaak door en hebben ze vervolgens geen grip.

### Wat hoorde er te gebeuren?

Auto's behoren grip te behouden.

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://medal.tv/games/gta-v/clips/Dsxn541Berodo/d1337ZVTSV2t?invite=cr-MSxyWEwsMjE2NzQyMjcs

**Comment by Ljosfari** [comment]
Denk niet dat we dit wegdek aan kunnen passen

**Comment by CorruptSausage** [comment]
Ik heb even met @Oesewoes hierover gepraat, het is is inprincipe mogelijk alleen moet de collision material dan aangepast worden. Ik verwijs de issue dus even door aan hem.

**Comment by Oesewoes** [comment]
fixed it mom @CorruptSausage

**Comment by Mikajac** [comment]
> fixed it mom @CorruptSausage

Brave jongen!
