### ISSUE TITLE
[FEATURE]: Voertuig automatisch van gestolen halen in MEOS bij overschrijving

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1664]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Wanneer een voertuig overgeschreven wordt van de ene naar de andere persoon dat automatisch de gestolen status eraf gehaald wordt. Als dit niet mogelijk is dan eventueel dat alle gestolen voertuigen om een x periode gewiped worden (bijvoorbeeld elke twee weken).

### Wat lost deze feature op?

Heel veel mensen vergeten een voertuig van gestolen te halen of verkopen het voertuig aan iemand die niet weet dat die nog op gestolen staat. Dit veroorzaakt veel onnodig werk en veel gedoe voor de kopende partijen.

**Comment by niekschoemaker** [comment]
Ik kan het ook blokkeren, of is in dit geval het er automatisch afhalen een betere optie?

**Comment by CorruptSausage** [comment]
Ik zou hier wel nog iets van beveiliging op gooien, aangezien je anders het probleem krijgt dat mensen dit gaat abusen. Door bijvoorbeeld even snel het voertuig naar elkaar over te schrijven, zodat de "gestolen" status weg gaat.

**Comment by zeletix** [comment]
> Ik zou hier wel nog iets van beveiliging op gooien, aangezien je anders het probleem krijgt dat mensen dit gaat abusen. Door bijvoorbeeld even snel het voertuig naar elkaar over te schrijven, zodat de "gestolen" status weg gaat.

Ik snap eerlijk gezegd niet hoe dit abusen is, gezien een "gestolen" status op je voertuig hebben als crimineel je juist heel veel voordelen geeft.

**Comment by CorruptSausage** [comment]
> 

Er zullen vast wel manieren zijn om dit abusen.

**Comment by CorruptSausage** [comment]
> Ik snap eerlijk gezegd niet hoe dit abusen is, gezien een "gestolen" status op je voertuig hebben als crimineel je juist heel veel voordelen geeft.

Er zullen vast wel manieren zijn waardoor dit geabused kan worden, beter het er wel in hebben en het niet nodig hebben dan nodig hebben maar het er niet in hebben. :)

**Comment by jaim1114** [comment]
> Ik zou hier wel nog iets van beveiliging op gooien, aangezien je anders het probleem krijgt dat mensen dit gaat abusen. Door bijvoorbeeld even snel het voertuig naar elkaar over te schrijven, zodat de "gestolen" status weg gaat.

@CorruptSausage Zoals je weet kan alleen de eigenaar een voertuig overschrijven. Als de eigenaar een voertuig overschrijft, mag er vanuit worden gegaan dat de auto niet meer gestolen is. Het automatisch van gestolen afhalen bij overschrijving zou de politie/kmar juist helpen om onnodige ANPR meldingen tegen te gaan.

**Comment by jaim1114** [comment]
> Ik kan het ook blokkeren, of is in dit geval het er automatisch afhalen een betere optie?

@niekschoemaker Ik denk dat er automatisch afhalen de beste optie is, blokkeren gaat alleen maar extra werk voor de politie opleveren terwijl de rechtmatige eigenaar 'm als enige kan overschrijven.

**Comment by CorruptSausage** [comment]
> @CorruptSausage Zoals je weet kan alleen de eigenaar een voertuig overschrijven. Als de eigenaar een voertuig overschrijft, mag er vanuit worden gegaan dat de auto niet meer gestolen is. Het automatisch van gestolen afhalen bij overschrijving zou de politie/kmar juist helpen om onnodige ANPR meldingen tegen te gaan.

Hoezo zouden wij er vanuit kunnen gaan dat de auto dan van gestolen is? Mensen zouden die alsnog gewoon kunnen abusen, er zal zoiezo iets van beveiliging opkomen om dit goed werkend te maken zonder abusing.

**Comment by jaim1114** [comment]
> > @CorruptSausage Zoals je weet kan alleen de eigenaar een voertuig overschrijven. Als de eigenaar een voertuig overschrijft, mag er vanuit worden gegaan dat de auto niet meer gestolen is. Het automatisch van gestolen afhalen bij overschrijving zou de politie/kmar juist helpen om onnodige ANPR meldingen tegen te gaan.
> 
> Hoezo zouden wij er vanuit kunnen gaan dat de auto dan van gestolen is? Mensen zouden dit alsnog gewoon kunnen abusen, er zal zoiezo iets van beveiliging opkomen om dit goed werkend te maken zonder abusing.

Een voertuig wordt op gestolen gezet omdat de eigenaar niet meer het voertuig tot zijn beschikking heeft. De eigenaar is de enige die het voertuig kan overschrijven. Een voertuig kan alleen worden overgeschreven als de eigenaar in de buurt staat. In vrijwel 100% van de gevallen zal de eigenaar dus kunnen beschikken over zijn voertuig wanneer hij deze overschrijft.

Maar goed, jullie zijn de devs en maken de inschatting hoe het moet gebeuren qua codering. Ik weet in ieder geval dat deze aanpassing vanuit de politie nog erg gewild is.

**Comment by ARJ3N** [comment]
> gaat waarschijnlijk erg misbruikt worden

Op wat voor manier? We krijgen nu namelijk enorm veel klachten dat bij 99% van alle ANPR meldingen over gestolen voertuigen dat het voertuig alweer bij de eigenaar terecht is. Dit systeem zorgt er juist voor dat er veel minder foutieve meldingen zijn. @Ljosfari
