### ISSUE TITLE
[FEATURE]: In MEOS kunnen zien vanaf welk moment persoon een voertuig op zijn/haar naam kreeg

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1665]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Dat in MEOS te zien is op welk moment persoon eigenaar is geworden van een voertuig.

### Wat lost deze feature op?

Politie en de KMar krijgen vaak de horen dat persoon de auto net aangekocht heeft wanneer ze persoon bijvoorbeeld aantreffen met te donkere ramen of andere gebreken aan het voertuig. Op dit moment is er op geen enkele mogelijkheid te checken of persoon een voertuig pas net heeft of al heel lang. Voorkomt dus een stukje kleine powergaming.

**Comment by CorruptSausage** [comment]
@niekschoemaker zou dit mogelijk kunnen zijn in de huidige meos?

**Comment by CorruptSausage** [comment]
Zit er al een tijdje in.
