### ISSUE TITLE
[FEATURE]: Illegale voertuigen automatisch vernietigen.

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#1666]
### Beschrijf zo duidelijk mogelijk de feature

De illegale voertuigen die langer dan 14 dagen in de politie opslag staan automatisch verwijderen. Het gaat dan om de volgende voertuigen:
Cliffhanger (cliffhanger)
Dune Buggy (dune)
Manchez (manchez)
Sanchez (sanchez)
Sanchez Sport ((sanchez2)

### Wat lost deze feature op?

Dat mensen onnodig lang moeten wachten voor hun voertuig handmatig is vernietigd.

**Comment by Willem-Dekker** [comment]
heb je de model hash voor mij?

**Comment by Lorenzo3001** [comment]
> heb je de model hash voor mij?
Cliffhanger (cliffhanger) 390201602
Dune Buggy (dune) -1661854193
Manchez (manchez) -1523428744
Sanchez (sanchez) 788045382
Sanchez Sport ((sanchez2) -1453280962

**Comment by Willem-Dekker** [comment]
fixed
