### ISSUE TITLE
[FEATURE]: Brandweer

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1667]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Er is veel vraag naar een extra overheidsjob, en brandweer is al meerdere keren naar boven gekomen.

Als we de fire spread aan zetten kunnen er brandjes geblussed worden, maar ook personen uit voertuigen gehaald worden na een zware crash. De ploitie/kmar kan dan ook gaan straffen op brandstichting.

Wat hebben we hiervoor nodig:

- [ ] Een gebouw
- [ ] In game rangen (5 om mee te beginnen lijkt me)
- [ ] Een brandweerwagen en een kleinere ''touran''. Voor ongelukken etc
- [ ] Heren en dames kleding
- [ ] Een overheidsdiscord ?

**Comment by walvisgedaan** [comment]
- Gebouw
- Kleding
- Voertuigen

Is voor mij vrij gemakkelijk te realiseren

**Comment by walvisgedaan** [comment]
https://www.youtube.com/watch?v=qVUb0uvKNWI

**Comment by walvisgedaan** [comment]
Wellicht is het een idee om -indien dit development-wise mogelijk is- verschillende branden te laten labelen. Dan krijg je automatische meldingen. Alle hulpdiensten krijgen deze dan binnen. Dus politie, ambulance en de brandweer. Dat zorgt voor meer roleplay's en een betere samenwerking

**Comment by walvisgedaan** [comment]
- [] Feature waarin mensen na een heftige crash vast zitten in hun voertuig

**Comment by walvisgedaan** [comment]
Rangen:
- Brandwacht
- Hoofdbrandwacht
- Brandmeester
- Hoofd brandmeester
- Commandeur
- Adjunct hoofdcommandeur
- Hoofdcommandeur
