### ISSUE TITLE
[Bug]: Deepweb die soms niet inlaad

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1668]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je soms een deepweb opent krijg je rechtsboven de melding dat je opnieuw moet proberen, zie screenshot:
![image](https://user-images.githubusercontent.com/101106299/194423611-5d287b8c-ae85-4a15-8292-7d794a36e28c.png)
![Uploading image.png…]()

### Wat hoorde er te gebeuren?

Je hoort gewoon de deepweb te kunnen zien.

### Wat veroorzaakt de bug?

Geen idee, er staat niets speciaals in F8.
1. Je doet deepwebs open
2. je scrollt er door paar heen
3. en je ziet de deepweb niet 
4. Je krijgt de melding dat je opnieuw moet proberen.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by CorruptSausage** [comment]
Duplicate van https://github.com/Tedeapolis/development/issues/1652
