### ISSUE TITLE
[Bug]: Melding krijgen van deepweb zonder telefoon

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1669]
### Contact Details

Wilma Wonka#4312

### Wat gebeurde er?

Het schijnt als je geen telefoon meer hebt dat je toch deepweb berichten krijgt.

https://discord.com/channels/563825802865541122/1027939256884277370

### Wat hoorde er te gebeuren?

Je hoor berichten te krijgen als je een telefoon hebt

### Wat veroorzaakt de bug?

onbekend

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by CorruptSausage** [comment]
Is als het goed is gefixt door @niekschoemaker
