### ISSUE TITLE
[FEATURE]: Een extra pomp op eiland voor Heli's

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1670]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

https://discord.com/channels/563825802865541122/1025799461500358656

**Comment by CorruptSausage** [comment]
Waar zouden die pompen dan moeten komen staan?

**Comment by WilmaWonka1985** [comment]
Helipad zijkant. Grote helipad bij de grote villa

**Comment by CorruptSausage** [comment]
Zit erin na de restart.
