### ISSUE TITLE
[Bug]: (Spoed) Lightbars werken niet als deze op één voertuig zijn geladen en je switcht naar een ander voertuig

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1671]
### Contact Details

KeesdB#1477

### Wat gebeurde er?

Wanneer je een voertuig hebt gebruikt waar al 4 lightbars op zijn geladen, dit voertuig wegzet en je een ander voertuig wilt pakken  (Bijvoorbeeld bij omswitchen in achtervolging) dan werken op het nieuwe voertuig de lightbars niet, je krijgt dan ipv dat de lightbars zouden moeten werken de radio en je kan op geen enkele manier de lightbars werkend krijgen. De lightbars worden dus wel geladen, maar je krijgt ze niet werkend. Dit heeft vermoedelijk te maken met de maximum van 4 lightbars op een voertuig per sessie. Als je dan gaat reloggen en je laad de lightbars op het nieuwe voertuig dan werkt dit wel.
Dit is getest in de test stad maar is slecht bewijs / clip van te maken aangezien je hiervoor moet reloggen.
Je kan het zelf testen door een voertuig te voorzien van 4 lightbars, vervolgens deze lightbars te saven en het voertuig in de garage te zetten, daarna een nieuw voertuig pakken en daar ook 4 lightbars op te zetten, de lightbars gaan dan niet meer aan en je krijgt de Radio.

### Wat hoorde er te gebeuren?

De lightbars moeten gewoon laden en gebruikt kunnen worden, hierdoor kan je dus als speciale eenheid niet altijd je zichtbaar maken. Wat wel zou moeten gebeuren. Dit is op het moment een zeer groot irritatie punt bij criminelen aangezien ze niet zeker weten of het andere criminelen zijn of speciale eenheden. Het is dus belangrijk dat dit zo snel mogelijk wordt opgelost, om misverstanden te voorkomen.

### Wat veroorzaakt de bug?

Maximum van 4 lightbars in één sessie (vermoedelijk)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Er staat hier niets over in de log

**Comment by niekschoemaker** [comment]
Het laden wordt in dit geval met /loadlightbar gedaan neem ik aan?

**Comment by niekschoemaker** [comment]
En wat wordt er exact gedaan? Gaat dit om 2 verschillende voertuig modellen?
Want als ik op 1 voertuig lightbars zet, deze verwijder en een nieuwe pak dan werken de lightbars nog wel bij mij

**Comment by niekschoemaker** [comment]
En een video van de issue zelf, het reloggen zou wel, want het is logisch dat dat de issue fixed, maar een video is misschien wel handig.

Als je eventueel ook op het nieuwe voertuig even: `/lightbars_canuse` uit kunt voeren, daaruit krijg ik heel wat informatie met waarom de lightbars niet werken

**Comment by niekschoemaker** [comment]
Is gefixed
