### ISSUE TITLE
[Bug]: je ziet geen /me's boven mensen hun hoofd tijdens het spectaten

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1673]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je spectated en mensen doen dingen in /me zie je het niet boven hun hoofd.

### Wat hoorde er te gebeuren?

je hoort het boven hun hoofd te zien, nu zie je het alleen links boven.

### Wat veroorzaakt de bug?

Geen idee, staat niets in F8.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
Je ziet het in principe toch gewoon in de chat, waarom de hoge prio? Graag alleen de hoge prio bij issues die daadwerkelijk urgent gefixed moeten worden.
