### ISSUE TITLE
[FEATURE]: Kunnen zien hoe ver weg een bewusteloze speler getild is

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1674]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Feature toevoegen dat je in het med systeem kan zien hoe ver weg een bewusteloze speler getild is is vanaf de locatie dat hij/zij overleden is.

### Wat lost deze feature op?

Lost op dat spelers bewusteloze personen kilometers meetillen om ze ergens anders te kunnen laten helpen. Besproken in staffoverleg.

**Comment by Nander0320** [comment]
@Willem-Dekker Was hier nog een update op ?

**Comment by Willem-Dekker** [comment]
@Chang-nl ik was hier wel aan begonnen weet niet meer de status verder

**Comment by Ljosfari** [comment]
dus ?

**Comment by Chang-nl** [comment]
Hey @ARJ3N, 

Na de herstart zal de update erdoorheen zijn!
