### ISSUE TITLE
Item kaart tarrot1 Bekijken in game

### ISSUE THREAD

**Issue by TDABob** [Tedeapolis/development#1675]
Item kaart met de naam Tarrot1 is gemaakt, nu is de vraag of dit item in het F2 keuze menu ook bekeken kan worden als zijnde afbeelding. 

Deze item's worden ''enkel'' af gegeven door de onderwereld dokters aan de groepen waar de samen werkingen mee zijn.
Hierbij de afbeelding:
![unknown (1)](https://user-images.githubusercontent.com/108182252/194774273-c5dbc108-948c-4df8-8e05-d1869103d9eb.png)

Hopelijk gaat dit lukken voor het effect eraan.

**Comment by Chang-nl** [comment]
Hey @Willem-Dekker,

Wat is de status hiervan?

**Comment by Willem-Dekker** [comment]
dit is een low prio ding wat een nice to have is meer een idee voor ooit niet iets waar nu iets mee gedaan moet worden.

> Hey @Willem-Dekker,
> 
> Wat is de status hiervan?

**Comment by Chang-nl** [comment]
Hey @TDABob,

Is dit nog steeds nodig?

**Comment by TDABob** [comment]
@Chang-nl, 

Ja graag als dat gaat lukken :)

**Comment by Tom974** [comment]
Ga ik voor nu niet toevoegen gezien de odw dokter momenteel ook niet echt iets is. Mocht het weer wat worden, kan de issue opnieuw geopend worden :)
