### ISSUE TITLE
[EUP]: Yeezy's voor vrouwen

### ISSUE THREAD

**Issue by Hank-maker** [Tedeapolis/development#1677]
### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Misschien yeezy's maken voor vrouwen. gewoon net zoals voor de mannen.

**Comment by CorruptSausage** [comment]
Heb je hier al een suggestie voor ingediend bij het suggesties kanaal in de main server?

**Comment by CorruptSausage** [comment]
Ik ga deze issue sluiten, graag volgende keer even eerst bij server suggesties hierover een suggestie indienen. Zodra deze goedgekeurd is door het community team zullen zij hier een issue voor aanmaken, alvast bedankt!
