### ISSUE TITLE
[Bug]: De range van Shift + E om een voertuig te duwen is onrealistisch

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#1678]
### Contact Details

Mr. Martin#3886

### Wat gebeurde er?

Shift + E om een total loss voertuig te duwen heeft een te grote range,  je kan namelijk door muren of hekken teleporteren.

### Wat hoorde er te gebeuren?

Dat je niet door hekken of muren teleporteerd als je een voertuig gaat duwen.

### Wat veroorzaakt de bug?

De range van Shift + E is te groot of moet rekening houden met obstakels.

### Frequentie van de bug

1x per week

### Wat is de impact van deze bug?

laag

**Comment by CorruptSausage** [comment]
![afbeelding](https://user-images.githubusercontent.com/56514707/195592433-58da1ab9-7c0d-4b73-ac1f-23ef813ca3ea.png)

^^ Foto

**Comment by CorruptSausage** [comment]
Hiervoor is oorspronkelijk een ticket aangemaakt, persoon heeft een issue ervoor aangemaakt. Het blijkt dat soms de Shift + E van een voertuig verder is dan normaal. Het kan dan gebeuren dat als je op Shift + E klikt je door een muur/hek wordt geteleporteerd aan je voertuig.

**Comment by CorruptSausage** [comment]
Fixed na restart.
