### ISSUE TITLE
[FEATURE]: KTM body grootte

### ISSUE THREAD

**Issue by hakan1911** [Tedeapolis/development#1679]
### Contact Details

Hakan#7218

### Kenteken van voertuig

NVT

### Voertuig model

KTM exc 350

### Omschrijf de bug

De KTM offroad motor is zoals we weten wanneer hij fully tuned is een erg goede motor vergeleken met de politie dirtbike. Dat hij heel erg snel optrekt op offroad gebieden dat is natuurlijk al bekend, maar hier gaat het om zijn body. Daarmee bedoel ik eigenlijk soort van zijn hitbox. 

De KTM motor kan bij een aantal plekken in de stad steegjes nemen met smalle doorgangen waarvan je zou denken dat de politie/kmar dirtbike ook daar door heen zouden kunnen rijden. Helaas is dit niet het geval en botst de motor dan soortvan tegen een onzichtbaar iets omdat de body wat groter is (dus een grotere hitbox voor het botsen). Mij lijkt het dus beter om de body van de ktm of net zo breed te maken als de kmar/politie dirtbike. Of om de kmar/politie dirtbike zijn body smaller te maken qua hitbox. 

Dit vind ik een probleem aangezien (meestal dezelfde) criminelen steeds dezelfde routes nemen om te ontsnappen en wij als politie hier in 99% van de gevallen niets meer tegen kunnen doen.

### Repro

Een achtervolging van een criminele ktm en een politie dirtbike. Je rijdt bij papierfabrik via de achterkant naar binnen en pakt daar de smalle steegjes. De KTM rijdt er doorheen , de politiemotor blijft vast haken want zijn body is de breed/groot.

### Normaal gedrag

De politie motor zou daar ook gewoon door heen moeten kunnen of beide motoren zouden het niet moeten kunnen.

**Comment by CorruptSausage** [comment]
Als problemen zoals dit vaak voorkomen kun je toch juist zeggen om dit probleem vooruit te werken? Als je weet dat iemand dit gaat doen, moet je gewoon met de communicatie en de andere mensen het probleem oplossen. Daarnaast vraag ik me ook af als hier al een suggestie voor is ingediend en als deze goed is gekeurd?

**Comment by CorruptSausage** [comment]
Graag heb ik dat hiervoor eerst een suggestie indiend, zodra deze goedgekeurd word pakt het community team dit verder op.

**Comment by ARJ3N** [comment]
@hakan1911 dit is al eens aangepast door Lorenzo. Zijn er nog steeds plekken waar dit gebeurd en zo ja, welke?

**Comment by CorruptSausage** [comment]
Ik open hem even omdat hier blijkbaar aan gewerkt word.

**Comment by Lorenzo3001** [comment]
Zowel de KTM als de Politie motor hebben nu een collision die overeen komt met de daadwerkelijke grote van de motor. Daar zit wel iets verschil in aangezien de KTM wel wat smaller is. Maar ze passen nu dus beide alleen door steegjes waar ze realistisch gezien ook doorheen zouden kunnen.
