### ISSUE TITLE
[FEATURE]: Cooldown wapens bij schieten in benen, voeten, armen en handen

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1681]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

Besproken in Staff overleg van 16-10. 

Op dit moment wordt er ontzettend veel No Value of Life gepleegd wanneer personen worden geschoten in de benen, je valt dan om maar je kan nog wel gewoon je vuurwapen pakken en als rambo gaan schieten. We hebben besproken om een cooldown er aan toe te voegen dat wanneer je in de benen wordt geschoten en je valt om dat je dan daadwerkelijk niet meer kan schieten voor een tijd van 5-10 seconden.  Gezien je meestal binnen een afstand van 50 meter kan schieten en je ongeveer binnen 5 á 7 seconde vanaf 50 meter bij de persoon welke je beschoten hebt kan komen lijkt mij een cooldown van 7 seconde meer dan genoeg. Je kan dan dus op het moment dat je ben gevallen voor 7 seconde niet terugschieten, het wapen verdwijnt uit je handen en deze moet je opnieuw pakken. 

Tevens ook bekijken of dit bij handen / armen ook gedaan kan worden, dat er gericht op je armen wordt geschoten dat het wapen 8 seconde niet gebruikt kan worden nadat je in je armen/hand ben geschoten. Het wapen automatisch laten vallen is niet mogelijk dus dan gewoon om het wapen ook te laten verdwijnen uit je handen en dat je dan 8 seconde lang niet het wapen kan pakken, dus je zal dan dekking moeten zoeken, wegrennen of het wapen pas 8 seconde later weer kunnen pakken.

### Wat lost deze feature op?

Dit zorgt er hopelijk voor dat er meer RP wordt gedaan in de Server, minder headhunten maar gericht schieten op het onderlichaam of armen/handen. Mensen minder snel met wapens rond gaan rijden omdat je dus daadwerkelijk een risico loopt dat je hierdoor eerder wordt ingesloten door de politie doordat ze je op de knien kunnen dwingen op het moment dat je geen wapen vast hebt. 
Andersom kunnen criminelen makkelijker weg komen door gericht te schieten op de benen/handen/armen van agenten. Er hoeft dus niet gelijk in het hoofd worden geschoten. 
Onderling tussen criminelen kan je hiermee dus ook sneller "rippen" wat er voor zorgt dat het kwartje de ene kant de ene kant en de andere keer de andere kant kan vallen. Op dit moment zou het al zo moeten zijn dat als je in de benen ben geraakt en je valt om en je wordt "overmeesterd" dat je dan geript moet worden omdat het onder no value of life valt als je dit niet doet.
De NVOL regel wordt hiermee dus veel duidelijker.

**Comment by Chang-nl** [comment]
Hey @KeesdeB,

Dit zit er ondertussen in!
