### ISSUE TITLE
[FEATURE]: Bij spectaten meeluisteren in porto waar persoon in zit

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1682]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

Zoals besproken in Staff overleg 16-10

Meeluister functie in de porto waar persoon waarbij je meekijkt op dit moment zit, zodat je communicatie kan horen en de RP dus beter kan volgen. Dit kan je dan ook uit / aan zetten via een command.

### Wat lost deze feature op?

Beter volgen wat er in RP wordt gezegd in porto's. Wel met nadrukkelijke vraag dat het uit en aan gezet kan worden, vooral voor de staff leden welke streamen.
Tevens kan je hiermee META beter onderzoeken. (Je ziet niet altijd de emote dat iemand in een porto praat, dus dan kan je achterhalen of iemand in een porto praat of niet)

Besproken: Wordt gekeken/github aangemaakt waarbij je automatisch de porto joined van de persoon die je spectate. Evt. ook dat je dit zelf in/uit kan schakelen naar behoefte.

**Comment by Nander0320** [comment]
Dit command bestaat al maar is beschikbaar tot een bepaalde groep stafleden :)
