### ISSUE TITLE
[FEATURE]: Bloods logo

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1683]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Er sinds kort een nieuwe officiële groep erbij gekomen, alleen bij deze rang is er ook een logo toegevoegd.
De logo zit er nu ook in sinds een paar dagen geleden, de vraag is als de logo ietsjes groter gemaakt kon worden.
zie logo: 
![image](https://user-images.githubusercontent.com/101106299/196116929-65188a50-3ab3-430f-bd00-48913bf4a185.png)

### Wat lost deze feature op?

Ziet er beter uit, momenteel ziet het er klein uit.

**Comment by Chang-nl** [comment]
Dan moet je er een met een minder grote border doorsturen.

**Comment by Toro-Carri** [comment]
Beste Chang,

Bedankt dat jullie ons willen helpen met het logo. Natuurlijk snappen we dat jullie het druk hebben en dat dit soort randzaken niet de hoogste prioriteit hebben. Daarom toch onze dank dat jullie hiervoor tijd vrij maken.

Ik heb geprobeerd de borders kleiner te maken, en heb er een webp bestand van gemaakt. Omdat ik begreep dat dit voor jullie gemakkelijker was. De webp file van ons logo heb ik hier in de transferlink gezet, omdat ik hem niet los hier in kon slepen.

https://we.tl/t-PTjnAfshhw

Alvast bedankt!

**Comment by CorruptSausage** [comment]
Ik heb het logo iets groter gemaakt, je moet zelf even kijken hoe dit er ingame uitziet. Als het lelijk is kun je mij even prive een berichtje sturen.
