### ISSUE TITLE
[FEATURE]: Bloods vechtclub sleutels syncen 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1684]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

The Bloods rang heeft op het moment geen toegang tot de vechtclub, wat wel van de The Bloods is.
Onze vraag was als het mogelijk is om de sleutels van de vechtclub op de Bloods rang te zetten en de sleutels weg te halen bij de ondernemer rang waar het nu op zit.

### Wat lost deze feature op?

Bloods kan dan hun vechtclub terug binnen zonder de ondernemer rang, maar wel met hun official groep rang.

**Comment by Attomn** [comment]
Sloten zijn als het goed is aangepast naar de juiste groep. Is helaas niet te testen in de dev server.
