### ISSUE TITLE
[Bug]: Lift TDA Nieuws-gebouw

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1686]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Personen die de DJ rol (/setjob reporter) als job2 hebben kunnen niet de lift zien in het TDA Nieuws-gebouw. Zij hebben wel toegang tot de sloten en ook tot de voertuigen, maar niet tot de lift die ze naar het dak brengt voor bijvoorbeeld de helikopter.

### Wat hoorde er te gebeuren?

Personen horen deze lift te kunnen zien en te kunnen gebruiken.
https://i.imgur.com/D355gzV.jpeg
https://i.imgur.com/UoufE7Y.jpeg

### Wat veroorzaakt de bug?

Onbekend, hoogstwaarschijnlijk geen permissies voor personen met job2.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Attomn** [comment]
is gefixt
