### ISSUE TITLE
[Bug]: Logo's job2

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1687]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Alle job2's hebben geen logo meer. Bij mijzelf is dit al 2-3 dagen en blijkbaar sinds de restart van net bij iedereen. 
![image](https://user-images.githubusercontent.com/20951687/196305611-d7ae3400-74e6-4b22-8278-94a5276f94a7.png)

### Wat hoorde er te gebeuren?

Logo hoort fatsoenlijk in te laden.

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

**Comment by CorruptSausage** [comment]
Moet als het goed is gefixt zijn na restart.

**Comment by CorruptSausage** [comment]
Issue blijkt nog niet gefixt te zijn, ik zet hem nog even open.

**Comment by CorruptSausage** [comment]
Niks gezegd, toch gefixt :P
