### ISSUE TITLE
[FEATURE]: issues/1530(vervolg)

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1688]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

Ik kan hem niet opnieuw openen maar ik heb oes gesproken en in toestemming van jullie zou hij wel kunnen helpen
Of hij gaf aan dat kobe het ook kan ?

Vervolg op ::https://github.com/Tedeapolis/development/issues/1530

### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

We worden elke dag aan gereden op ons parkeer terrein. Mensen rijden veel te hard en verwonden vaak een van onze medewerkers.
Ook willen we het kantoor beter beveiligen aangezien we meerdere keren per maand gegijzeld worden door mensen met een nep "bom vest", dus we willen de deuren ook allemaal dicht kunnen doen. Tevens gebruiken mensen de pin automaat in het gebouw als of het een openbare bank is. Daarnaast is het ook vervelend als criminelen gebruik maken van onze taxi parkeer plaats/garage. Ook vaak om illegale dingen over te zetten naar garage en de politie kan er niks tegen doen maar wij worden er vaak wel op aan gekeken. Tevens willen we een aantal props ( camera's ) hebben hangen voor de roleplay met politie. Zo kan de politie camera bewaking opvragen als mensen lastig doen in en rond het kantoor, dan kunnen wij simpelweg vertellen dat alles wordt gefilmd.

![FiveM_b2372_GTAProcess_mYkwra0evj](https://user-images.githubusercontent.com/93401910/180650397-03dc0adc-a8bb-4829-b3f5-a5af8f5583c9.png)
![FiveM_b2372_GTAProcess_07Ml2F9ank](https://user-images.githubusercontent.com/93401910/180650398-4b2891e3-087f-490b-932b-df744f15ad72.jpg)
![FiveM_b2372_GTAProcess_n3t11PDKgF](https://user-images.githubusercontent.com/93401910/180650400-4c816b77-cfa9-47ee-b5c6-98bde2e2faa9.jpg)
![FiveM_b2372_GTAProcess_PDqL3K9BHs](https://user-images.githubusercontent.com/93401910/180650401-c1d6377f-f0bd-485e-9547-a7160d0c8cf2.jpg)
![FiveM_b2372_GTAProcess_2WvcMHfqCj](https://user-images.githubusercontent.com/93401910/180650403-1dfa5beb-2ea3-4266-bcf6-a18518bf0f4b.jpg)
![FiveM_b2372_GTAProcess_qOXq8wH3Ni](https://user-images.githubusercontent.com/93401910/180650404-0e429545-1c7b-4e01-90ea-63fefd7db810.jpg)

### Checklist:

- [x] Sloten toevoegen aan de deuren
- [x] Hekken plaatsen
- [ ] Camera's plaatsen

### Wat lost deze feature op?

Hekken rond om : We worden dan minder aangereden. Tevens gaan criminelen ergens anders hun zaken doen.
Sloten op de deur : Zodat mensen het gebouw niet gebruiken als persoonlijke bank en onbevoegde kunnen we dan ook gewoon weren van het taxi kantoor omdat we dan meer veiligheid garanderen voor onze personeel leden.
Camera's : Dan kunnen we met camera beelden werken om samen met de politie iets leuks neer te zetten!

**Comment by Ljosfari** [comment]
hekkies @Oesewoes

**Comment by Oesewoes** [comment]
![1549916870_3133](https://user-images.githubusercontent.com/69470855/196825928-159ae428-816d-46eb-afb8-5b827ded1084.gif)

**Comment by Oesewoes** [comment]
Komt ook een wc bij. 🐸

**Comment by DevvTDA** [comment]
Hek is geplaatst.
