### ISSUE TITLE
[FEATURE]: Onderscheid in schiet- en drugsmeldingen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1689]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Voorheen met de ''oude'' meldingen had je soms een ander kleurtje voor bijvoorbeeld drugs of schietmeldingen. Nu lijken alle meldingen op het eerste gezicht hetzelfde waardoor die niet meer echt opvallen. Graag zouden wij dus zien dat er duidelijk onderscheid gemaakt kan worden tussen deze verschillende soorten meldingen doormiddel van bijvoorbeeld een andere kleur o.i.d. Ook de lengte van dat de meldingen op je scherm staan is vrij kort, waardoor deze snel weer verdwijnen. Mogelijk ook de lengtes langer maken van de belangrijke meldingen.

### Wat lost deze feature op?

Dat er onderscheid gemaakt kan worden tussen de meldingen, nu lijkt alles op elkaar.

**Comment by CorruptSausage** [comment]
Fixed na restart.
