### ISSUE TITLE
[Bug]: Hartmonitor

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1690]
### Contact Details

Wilma Wonka#4312

### Wat gebeurde er?

Beste, 

Als het zou kunnen de nieuwe hartmonitor het volume voor omstanders wat zachter te zetten. Als wij in dienst zijn van de AMMBU staat het geluid perfect. Maar voor de omstanders is het echt veel te hard. Gister ben ik als omstander gewoon weg gelopen omdat het geluid veel en veel te hard was. Zou hier misschien een oplossing voor kunnen komen?

### Wat hoorde er te gebeuren?

Het volume wat zachter

### Wat veroorzaakt de bug?

Ik weet niet waar dit onder valt dus vandaar dat ik het hier zet

### Frequentie van de bug

Altijd

**Comment by Chang-nl** [comment]
Is opgelost na hestart!
