### ISSUE TITLE
[FEATURE]: Drugsmelding KMAR

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1691]
### Contact Details

Wesleyy#6647

### Beschrijf zo duidelijk mogelijk de feature

Wij als KMAR willen graag dezelfde drugsmeldingen als de politie. Dit is besproken met de politie en wij zien zeker meerwaarde hierin sinds wij grotendeels bezig zijn met controles en surveillance. De politie kan niet op 10 plekken tegelijk zijn en sinds wij eigenlijk meer bezig zijn met opium dan de politie. Doormiddel van deze meldingen kunnen wij ook reageren hierop en zullen er afspraken gemaakt worden met de politie hoe wij dit gaan verdelen.

### Wat lost deze feature op?

Het lost eigenlijk niks op maar zorgt wel voor meer roleplay voor de KMAR. Wij kunnen sneller reageren op drugsmeldingen in bijvoorbeeld in het noorden sinds wij daar eigenlijk altijd aanwezig zijn. Wij hebben vaak 10+ mensen in dienst waardoor wij eigenlijk altijd wel een surveillance eenheid hebben.

**Comment by Ljosfari** [comment]
voor welke rangen zouden er meldingen moeten komen ? en ook op alle locaties ?

**Comment by niekschoemaker** [comment]
https://github.com/Tedeapolis/development/issues/1607

Graag in het vervolg zoeken of de issue al ooit aangemaakt is.
