### ISSUE TITLE
[FEATURE]: Tankpas voor alle overheidsdiensten

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1692]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een tankpas waarmee de overheidsmedewerkers gratis hun **dienstvoertuigen** mee kunnen tanken. Enkel dus wanneer ze in dienst staan en enkel op dienstvoertuigen (indien dit mogelijk is).

### Wat lost deze feature op?

Met de verhoogde benzineprijzen kost dit een aanzienlijk percentage van hun loon, terwijl ze gewoon hun werk aan het uitvoeren zijn. Dit is tevens overlegd met alle overheidsinstanties.

**Comment by CorruptSausage** [comment]
Tanken indienst is gratis voor nu, tankpas gaan we binnenkort even naar kijken als dit echt een fysieke pas gaat worden.
