### ISSUE TITLE
[FEATURE]: Ticket bot onderwerpen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1693]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Goedemiddag, 

Als jij een ticket aanmaakt moet je een onderwerp aanduiden in welke categorie de ticket moet komen.
Is het mogelijk om bepaalde onderwerpen eruit te halen, zoals: "ticket-helper", persoonlijke categorieën van ticket helpers zelf.

### Wat lost deze feature op?

Dat mensen geen tickets maken in iemand zijn persoonlijke categorie, lijkt me niet handig. 
Dit lost frustraties op lijkt mij.

**Comment by niekschoemaker** [comment]
Is config van bot, maar is gefixed
