### ISSUE TITLE
[Bug]: HUD die verlengd is met leegte

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1694]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je hebt twee jobs of 1 rechts onder en bij sommige mensen is de HUD iets verlengd, ik zelf heb dit ook maar echt een kleine verlenging (gedeeltelijk leeg). 
Screenshot wat ik toevallig zag van een speler waar het extreem is: 
![image](https://user-images.githubusercontent.com/101106299/197384455-ae5fbd12-2bec-4faf-a830-6dc6f183318e.png)

### Wat hoorde er te gebeuren?

Je hud hoort normaal te zijn en niet zo verlengd.

### Wat veroorzaakt de bug?

Geen idee, het is volgens mij al een paar dagen zo. 
(Niet iedereen heeft deze bug / last van, maar sommige wel)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by CorruptSausage** [comment]
Fixed na restart.
