### ISSUE TITLE
[FEATURE]: Telegraaf gebouw koppelen aan een nieuwe job/slotjes aanpassen/busje retexturen

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#1695]
### Contact Details

StoffigKontje#8688

### Beschrijf zo duidelijk mogelijk de feature

Voor het nieuwe Telegraaf gebouw zouden de mannen van de Telegraaf graag wat slotjes aangepast willen hebben.
![image](https://user-images.githubusercontent.com/53233719/197393690-b5088943-f91e-48bf-ad59-5a4e6e37bdfb.png)
Het slot op de bovenste coords mag volledig weggehaald worden, hier mag iedereen dus in kunnen. 

![image](https://user-images.githubusercontent.com/53233719/197393725-6b6b718f-ddfa-44d3-be22-182d3b6df2dc.png)
Op de coordinaten van de bovenste deur (schuifdeur) mag er graag een slotje op, gekoppeld aan de reporter job (of nieuwe job). 

-----

Daarbij is er een verzoek (geen idee of dit mogelijk is, maar het zou fijn zijn) dat er een aparte job zou komen voor dit gebouw. Voor nu zit dit gebouw gekoppeld aan de "reporter" job, waardoor mensen van het concurrerende TDA Weekblad ook het gebouw in kunnen. 

Mocht het dus mogelijk zijn, zou er dan een job kunnen komen genaamd "TV1" met als rollen Stagiarie - redacteur - hoofdredacteur

Het idee is dan dat de TV1 job niet bij het gebouw van het TDA weekblad kunnen. En de reporter job dus niet bij het TV1 jobzaken
------
![image](https://user-images.githubusercontent.com/53233719/197394148-747f1983-72f0-4dd6-8489-021e23d51682.png)

Daarbij ook het verzoek om de rumpo die ingespawnd wordt bij het gebouw aan te passen. Dit is nu een TDA Nieuws busje (zie bovenstaande afbeelding) , is het mogelijk dat dit ook een aparte bus wordt? Er kan een texture aangeleverd worden die klaar staat, indien dit mogelijk is. 

Voorbeeld van het nieuwe busje staat hieronder: 
![image](https://user-images.githubusercontent.com/53233719/197394241-8c1452af-4f3c-4393-bfe0-5ed295253ccf.png)
![image](https://user-images.githubusercontent.com/53233719/197394245-edaa7775-401e-404b-84ec-450701e919a3.png)

Texture hier van kan aangeleverd worden, mits dit alles mogelijk is natuurlijk :) 

-------

TLDR: 

- [x] Slotjes aanpassen telegraaf gebouw
- [ ] Nieuwe job aanmaken/koppelen aan telegraaf gebouw en permissies van reporter job hierop aanpassen
- [ ] texture van rumpo aanpassen voor TV1 job

Mocht iets niet mogelijk zijn, begrijpelijk. Dan hoor ik het graag zodat ik dit kan terugkoppelen! 

### Wat lost deze feature op?

Geclash tussen de 2 nieuwsbedrijven "TDA Weekblad [reporter]" en "TV1". Het zijn concurrerende bedrijven maar kunnen nu in elkaars gebouw en moeten dezelfde job hebben.

**Comment by CorruptSausage** [comment]
Sloten zijn gefixt.

**Comment by StoffigKontje** [comment]
[busjeeeee.zip](https://github.com/Tedeapolis/development/files/9846753/busjeeeee.zip)
Dit is de texture van het busje, mocht dit mogelijk zijn.

**Comment by StoffigKontje** [comment]
![image](https://user-images.githubusercontent.com/53233719/197838234-ced607ab-4f59-4976-b73c-046c71b28a2e.png)
Kleine toevoeging aan de sloten, de vraag of hier ook een slotje op kan komen.

**Comment by StoffigKontje** [comment]
Nog een slotje toevoegen aub: 

![image](https://user-images.githubusercontent.com/53233719/201544136-e1c4f957-04ec-4f50-85f2-9fba966d2687.png)

**Comment by Nander0320** [comment]
@CorruptSausage Is dit mogelijk :)

**Comment by StoffigKontje** [comment]
@CorruptSausage ?

**Comment by CorruptSausage** [comment]
> @CorruptSausage ?

Sloten zijn aangepast, het busje zal even iemand van voertuigen development naar moeten kijken. Voor de job is het beter dat @niekschoemaker of @Chang-nl hier even naar kijkt, aangezien ik geen jobs kan toevoegen aan de database.

**Comment by Chang-nl** [comment]
Hey Jordy, op welke job staan de sloten nu?

**Comment by CorruptSausage** [comment]
> Hey Jordy, op welke job staan de sloten nu?

reporter2
