### ISSUE TITLE
[FEATURE]: Spawn locatie voertuig opslag veranderen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1697]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

![image](https://user-images.githubusercontent.com/104857888/197402251-8836091d-99d3-4743-804a-9a3dac502eda.png)
deze foto hierboven is de huidige spawn plek van onze voertuigen opslag. 

Wij willen dit graag veranderen naar deze locatie:
![image](https://user-images.githubusercontent.com/104857888/197402296-2e4c2beb-5f44-42a3-9dc8-a57a16dc1bf1.png)

### Wat lost deze feature op?

Minder snel kapotte voertuigen omdat we hele tijd tegen aan beuken.

**Comment by CorruptSausage** [comment]
Fixed na restart.
