### ISSUE TITLE
[FEATURE]: Whisper range aanpassen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1698]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staffoverleg is er besproken om de whisper range aan te passen. 
Zie screenshot: 
![image](https://user-images.githubusercontent.com/101106299/197410053-1a49a1ed-442e-4c64-a862-22cc192f61a2.png)

### Wat lost deze feature op?

Meer privacy etc

**Comment by CorruptSausage** [comment]
Fixed na restart.

**Comment by CorruptSausage** [comment]
Heb hem een klein beetje verlaagd, als het alsnog te groot is stuur me even een dm.
