### ISSUE TITLE
[FEATURE]: Bloods Muziek cirkel

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1699]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Onze muziek cirkel zat op de rang ondernemer, kan die ook naar onze job gezet worden (Bloods)? 
Als het mogelijk is. 

### Wat lost deze feature op?

Dan kan Bloods epische muziek afspelen tijdens toernooien.

**Comment by Chang-nl** [comment]
Graag iets meer info geven dan "onze" muziek cirkel ik heb geen idee welke cirkel ik nu moet aanpassen, even een locatie of foto met locatie sturen graag.

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/199462615-d1ab6bb3-7129-4354-8c66-69fff8af7d8f.png)
Op deze locatie met deze coords. Excuses voor het ongemak!

**Comment by Attomn** [comment]
Aangepast, echter wacht ik nog op Niek voor een bug fix waardoor geluid afspelen momenteel niet werkt.
