### ISSUE TITLE
Op de website linkt de "server regels" niet naar de APV maar naar een 404 not found pagina!

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#170]
Dit is de link die je krijgt als je op "Server regels" klikt vanuit https://tedeapolis.nl

**http://tedeapolis.nl/Algemene%20Plaateslijke%20Verordening%20Tedeapolis/**
Deze linkt echter naar een 404 not found pagina.

![afbeelding](https://user-images.githubusercontent.com/69365961/92967698-024cda80-f47a-11ea-9f59-90bb0500a1ba.png)

**Comment by Willem-Dekker** [comment]
fixed
