### ISSUE TITLE
[FEATURE]:  Warnings & Bans ook weergeven van offline spelers (maar zonder steamnaam)

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1700]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

**BESPROKEN IN STAFF OVERLEG**

Alle bans, warnings die wij nu uitdelen van spelers die offline zijn worden niet weergegeven ingame, dit betekend dus dat iedereen alleen de melding krijgt van ban's en warnings van online spelers.
Je kan veel leren van wat er in het ban/warn bericht staat, vooral als er uitgebreid beschreven staat wat de reden is.
Daarom is het handig om dit weer aan te zetten.

**Weergave**: 
Een speler is 3 dagen gebanned voor reden
Een speler is 1 dag gebanned voor reden
Een speler is gewarnd voor de volgende reden
**Bijvoorbeeld**:
Een speler is 3 dagen gebanned voor RDM | Zonder enige vorm van RP iemand neerschieten die meewerkt, het is je zoveelste keer dus dan maar even wat extra dagen afkoelen.
Een speler is 1 dag gebanned voor VDM | Je voertuig gebruiken als wapen om zo de achtervolging te stoppen
Een speler is gewarnd voor Earrapen | Bewust luid praten of je mic in je mond doen om zo harder over te komen

Absoluut niet de bedoeling om Steam namen / ingame namen te laten zien.
Voor online spelers kunnen nog wel ID's weergegeven worden.
Staffleden kunnen nog wel altijd steam namen zien.

### Wat lost deze feature op?

Hopelijk verbetering van RP, je kan namelijk zien waarvoor andere gestraft worden zodat je daar uit kan leren of wel 3x nadenkt voordat je het zelfde doet. Hierdoor leert men spelende wijs, maar nagel je niemand aan de schandpaal omdat niemand kan weten om wie het gaat (tenzij je zelf betrokken ben geweest bij het scenario).

**Comment by KeesdeB** [comment]
@CorruptSausage wat is de status van deze github? :)

**Comment by Chang-nl** [comment]
Hey @KeesdeB,

Bedankt voor het aanmaken van de github issues.

Momenteel worden bans en warns alleen weergegeven aan mensen dichtbij en staff. Zo willen we dat houden aangezien het ook aangevraagd is op deze manier.

**Comment by KeesdeB** [comment]
> Hey @KeesdeB,
> 
> Bedankt voor het aanmaken van de github issues.
> 
> Momenteel worden bans en warns alleen weergegeven aan mensen dichtbij en staff. Zo willen we dat houden aangezien het ook aangevraagd is op deze manier.

Dit is besproken in stafoverleg en is door de meerderheid goedgekeurd als zijnde: Leer proces.
Dus niet anageven WIE er is gestraft, maar dat er iemand is gestraft hier voor.
Je kan namelijk leren van warnings/bans.

**Comment by Chang-nl** [comment]
Hey @niekschoemaker, zou je hier op kunnen reagere?

**Comment by KeesdeB** [comment]
@Chang-nl deze was goedgekeurd in staffoverleg door veel stafleden.

**Comment by Tom974** [comment]
Opnieuw geopend op aanvraag. 

Zal gelijk even vanavond navragen bij Niek wat precies de bedoeling hiervan was :P

**Comment by KeesdeB** [comment]
Dit was met een grote meerderheid in een lang geleden staff overleg besloten dat dit rp bevorderend is zodat mensen weten waarvoor je gebanned/gewarnd kunnen worden. Daarom ik deze heb laten heropenen. Als het echt nodig is kan ik ook opzoeken in welke het was.

**Comment by KeesdeB** [comment]
Nvm, heb hem al 
![image](https://user-images.githubusercontent.com/106243778/230355964-8be20571-c892-4776-8cae-544c8d321e4d.png)

**Comment by Tom974** [comment]
Aanpassing zit als het goed is in @KeesdeB, kun je het me laten weten als dit klopt? 

Thanks!

**Comment by Wiebren-3** [comment]
Dit werkt!

**Comment by Tom974** [comment]
Gesloten ivm geen reactie
