### ISSUE TITLE
[Bug]: Punten verdwijnen bij witwassen

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1702]
### Contact Details

Tom974#9783

### Wat gebeurde er?

Tijdens het witwassen krijg je soms na het pakken geen punten meer en verdwijnen alle waypoints. (Ik gok dat dit komt door return to depot?) Indien dit gebeurd moet je reloggen om weer punten te krijgen. Dit gebeurd heel soms.

Voor videobewijs kun je mij dmmen op Tom974#9783, de eigenaar van de video heeft liever dat deze video prive blijft, dus deel ik deze hier niet op github

### Wat hoorde er te gebeuren?

Je hoort gewoon nieuwe punten te krijgen

### Wat veroorzaakt de bug?

1. Begin met witwassen
2. Wacht totdat (ik gok return to depot) getriggerd word

### Frequentie van de bug

Altijd

**Comment by Ljosfari** [comment]
is gefixed
