### ISSUE TITLE
[Bug]: Zoeklicht Zulu

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1704]
### Contact Details

CoffeeSipper#8888

### Wat gebeurde er?

Zoeklamp van de zulu gaat niet meer aan met ''G''

### Wat hoorde er te gebeuren?

Hoort aan te gaan

### Wat veroorzaakt de bug?

Zijn wat github-commits geweest omtrent de spotlight, wellicht hierdoor.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

Hoog

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/96985840/197598355-9b665722-c205-4a58-8c89-00ed0d275357.png)

**Comment by CoffeeSipper** [comment]
Update: lamp gaat aan, maar zit een delay in. Als je hem aanzet en je gaat bewegen met je muis, volgt de lamp relatief traag. Is dit door de nieuwe update?

**Comment by Chang-nl** [comment]
Is het toevallig dat de lamp nu aan ging of gaat hij weer structureel aan? De delay is toegevoegd inderdaad omdat een lamp niet zo snel draait

**Comment by CoffeeSipper** [comment]
> Is het toevallig dat de lamp nu aan ging of gaat hij weer structureel aan? De delay is toegevoegd inderdaad omdat een lamp niet zo snel draait

Volgens mij structureel. Die delay ziet er wel erg uit als lagg. Mijn ervaring maakt het niet beter tbh. Lijkt alsof je game erg langzaam loopt.

**Comment by Chang-nl** [comment]
Gaat erom dat er een delay op zit wanneer je draait. Die lamp kan niet instant bewegen bij mij werkt alles. Mochten er nog problemen optreden kun je dat laten weten.
