### ISSUE TITLE
[Bug]: Verbinding met radio ligt plat

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1705]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Wij als DJ's kunnen momenteel niet meer verbinden met de server om muziek af te spelen.

### Wat hoorde er te gebeuren?

Wij horen een verbinding op te kunnen zetten waarmee wij handmatig muziek kunnen afspelen en hierbij de autoDJ kunnen overrulen. Hierdoor kunnen wij live uitzendingen maken ipv alleen maar autoDJ te hebben.

### Wat veroorzaakt de bug?

Hoogstwaarschijnlijk het gekloot van Niek op 17-10 (zijn woorden).

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/20951687/197890760-c4b0bffb-933f-434a-9375-36cd6c61f788.png)

**Comment by AaranTDA** [comment]
Dit is inmiddels door Niek opgelost! @CorruptSausage
