### ISSUE TITLE
[Bug]: Voertuig bug

### ISSUE THREAD

**Issue by Mxcro1** [Tedeapolis/development#1706]
### Contact Details

Faiss#8325

### Wat gebeurde er?

-Sinds na deze restart (29-10-2022 02:00) moet je elke keer na het instappen de motor weer aanzetten 
dat betekent dat je dan elke keer van het voertuig af/uit gaat en weer in/op het voertuig gaat je handmatig de motor weer aan moet zetten dit zorg voor een enorme lange tijd voordat jij weer kan rijden 3 seconden+

- Buiten dat werkt de kilometer teller niet meer die staat nu op 0KM en gaat ook niet omhoog.

- De tankmeter die werkt ook niet meer die blijft op dezelfde aantal staan en veranderd niet.

Zie clip hieronder:
https://streamable.com/mxdibz

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by CorruptSausage** [comment]
Volgendsmij is dit gefixt, aangezien wij er geen last meer van hebben.
