### ISSUE TITLE
[Bug]: Ambu Spullen

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1707]
### Contact Details

Wilma Wonka#4312

### Wat gebeurde er?

Wij onder vinden momenteel erg veel problemen met de ambu spullen. zoals tassen hartmonitor. Wij ruimen de spullen op maar de mensen zien ze nog steeds staan. Vaak als wij het ook opruimen/of willen opruimen krijgen we het ook niet weg!

### Wat hoorde er te gebeuren?

Als wij iets verwijderen van de ambulance spullen moet het ook gelijk weg zijn, Want nu lijkt het of wij alles laten liggen terwijl het bij sommige wel weg is en bij sommige niet!

### Wat veroorzaakt de bug?

Ik zou het niet weten.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by Chang-nl** [comment]
Hey @WilmaWonka1985,

Is dit nog steeds een probleem?

**Comment by WilmaWonka1985** [comment]
Nou dit is op gelost maar we hebben alleen het probleem dat als we de E spier gebruiken terwijl er spullen staan voor ons dat die ineens verdwijnen. dus ik zet hartmonitor neer en ga dan EHBO toe dienen dan verdwijnt dus mijn hartmonitor. of me EHBO tas. Bambi weet hier van volgens mij

**Comment by Chang-nl** [comment]
Hwy @WilmaWonka1985,

Ja we zijn hiernaar aan het kijken en dat zal aangepast worden. Dat is een andere issue dus ik zal deze sluiten.
