### ISSUE TITLE
Kippen met helmpjes 

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1708]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Voor betere roleplay 

### Wat lost deze feature op?

Alles

**Comment by Attomn** [comment]
is dit een grap? haha

**Comment by AntonMTDA** [comment]
> is dit een grap? haha

Nee dit is wel een serieus iets xD
