### ISSUE TITLE
[Bug]: /repareer

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1709]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

Als je /repareer gebruikt en in de animatie met 'x' de animatie cancelled betaal je niks maar is wel je auto gerepareerd.

### Frequentie van de bug

Altijd

**Comment by Mikajac** [comment]
Ik heb dit net even geprobeerd en je cancelt inderdaad de emote, maar de auto wordt bij mij niet gerepareerd. Heb het op verschillende momenten getest gedurende de emote.

**Comment by CorruptSausage** [comment]
Ik heb dit even getest op de dev server, maar bij mij word de reparatie ook gecanceled. Heb je hier misschien een clip van?

**Comment by CorruptSausage** [comment]
Zover dat ik weet is dit gefixt, graag mij even een berichtje sturen als dit niet het geval is.
