### ISSUE TITLE
[FEATURE]: Gemeentehuis slotjes koppelen aan de Gemeente job [Militar]

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#1710]
### Contact Details

StoffigKontje#8688

### Beschrijf zo duidelijk mogelijk de feature

Op het moment kan je alleen de sloten voor het gemeentehuis gebruiken als je adminonduty bent. 

Kortom: RP'en als gemeenteraad kan alleen als je adminonduty bent.

### Wat lost deze feature op?

Roleplayen uit adminonduty

**Comment by CorruptSausage** [comment]
Zit erin na restart.
