### ISSUE TITLE
[FEATURE]: Narcos rangen aanpassen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1711]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

Het mogelijk maken om de rang Consejero, toegang te geven tot het alles tunen. En de rang Teniente toegang geven tot de kleine wapens te tunen.

### Wat lost deze feature op?

Dat meerdere mensen kunnen tunen en dat je ergens kan toestreden binnen narcos.

**Comment by niekschoemaker** [comment]
Done
