### ISSUE TITLE
[EUP]: Narcos Hoed

### ISSUE THREAD

**Issue by Paveltda** [Tedeapolis/development#1714]
### Contact Details

Zeta#7750

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Wij als Narcos zouden graag een custom Cartel kledingstuk in de server willen hebben waarbij wij onze roleplay kunnen bevorderen en ons meer kunnen laten zien als Cartel zijnde. https://nl.gta5-mods.com/player/cowboy-hat-eup 

(Gemaakt op aanvraag van @walvisgedaan)

**Comment by AntonMTDA** [comment]
@Paveltda Was dit nog nodig ? :D

**Comment by Paveltda** [comment]
Nee niet meer we zijn nu bezig met een ander hoedje wegens andere thema.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by DevvTDA** [comment]
Niet meer nodig.
