### ISSUE TITLE
[FEATURE]: Rang aanvraag.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1715]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Tijd geleden had ik de toestemming gekregen om een gitup aan te maken voor een eigen rang te krijgen voor mijn bedrijven. Dus bij deze;

Rangs:
R3D - CEO
R3D - Manager
R3D - Senior Medewerker
R3D - Medior Medewerker
R3D - Junior Medewerker
R3D - Stagiaire

F6 Menu:
Bij de factures is het de bedoeling dat het geld niet naar een pot gaat, maar naar de persoon die de factuur stuurd.
Het zou hier makkelijk zijn voor de devv's dat we zelf in kunnen voeren wat de reden is en daarbij zelf kunnen invoeren wat ze moeten betalen.

Rechten/ inkomsten.
De uitbetalingen van de rangs zouden dan gaan via een (onzichtbare) pot. Netals bij de Ondernemer job. Enkel we met een in en uitdienst mogelijkheid.

R3D - Stagiaire:
Inkomen: in en uit dienst €200
Rechten: -

R3D - Junior Medewerker:
Inkomen: in en uit dienst €300
Rechten: F6 menu

R3D - Medior Medewerker:
Inkomen: in en uit dienst €400
Rechten: F6 menu

R3D - Senior Medewerker:
Inkomen: in en uit dienst €500
Rechten: F6 menu

R3D - Leiding:
Inkomen: in en uit dienst €600
Rechten: F6 menu, Kras - loten cirkel & Rang/personeel beheer cirkel

R3D - CEO:
Inkomen: in en uit dienst €700
Rechten: F6 menu Kras - loten cirkel & Rang/personeel beheer cirkel

Locatie van de Rang/personeel beheer cirkel mag op:
vector3(-810.04, -208.39, 37.13)
heading: 207.63
https://prnt.sc/-6opaUnUXw0d

Locatie van Kras - loten cirkel
vector3(-781.44, -209.30, 37.15)
heading: 171.73
https://prnt.sc/muf7L4dfYFcb

### Wat lost deze feature op?

-

**Comment by niekschoemaker** [comment]
Waarom mot er in en uit dienst en alles in? En die facturen is ook echt compleet gezeik, kun je mensen niet gewoon laten betalen in plaats van volledig met facturen werken?

Als het gewoon een baan is kan ik het makkelijk toevoegen, maar in en uit dienst en hele facturen systeem is nogal meh.

**Comment by niekschoemaker** [comment]
Zorgt er ook voor dat het veel sneller doorgevoerd worden, want het enige wat ik hier zie is een enorme zoot zooi om in te voeren en hersendood over te typen.

En die facturen is sws makkelijker om intern af te handelen want dan kun je zelf gewoon bedragen aanpassen in plaats van dat dat constant via via moet en er weer een week overheen gaat,
dus lijkt me logischer als je dat gewoon met overschrijvingen of zo laat afhandelen.

**Comment by Rowdeeee** [comment]
Het idee met in en uitdienst was het idee zodat als mensen een overheids baan hebben het f6 menu (met de facures) uit kunnen zetten. Het punt met de factures is omdat mensen soms niet de RP aan gaan om het te betalen en het onmogelijk is om voor elk persoon die niet betaald de politie te bellen. Met factures dwing je ze er tot toe zodat het wel betaald moet worden.

**Comment by Rowdeeee** [comment]
Deze
