### ISSUE TITLE
[FEATURE]: Unarmed damage uitschakelen en overschakelen naar KO systeem.

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#1716]
### Contact Details

Ryan/Eliryth#3607

### Beschrijf zo duidelijk mogelijk de feature

WEAPON_UNARMED omzetten naar dat je iemand alleen tijdelijk KO kan slaan i.p.v. daadwerkelijk damage doen
zoals met een wapen of voertuig. 

Kortgezegd moet het erop neer komen dat spelers X aantal unarmed hits kunnen krijgen (binnen een bepaalde tijd) waarna ze KO gaan en op een later moment weer bij komen. Dit in tegenstelling tot het huidige systeem waarin je elkaar volledig dood kan slaan en alleen bv. een overheidsdienst je overeind kan helpen. 
Uit een voorbeeld blijkt dat een KO periode van ongeveer 1 minuut (kan later evt. nog aangepast worden mocht dat nodig zijn) in principe genoeg is. 

### Wat lost deze feature op?

Lost een vrij groot deel van de RDM issues op, vooral m.b.t. RDM situaties waar mensen spullen kwijtraken doordat ze random neergeslagen worden door bijvoorbeeld een nieuwe speler die alleen maar komt kloten.  Heeft onder zowel criminelen als overheidsbanen enorm veel stemmen voor gekregen waar alleen al uit blijkt dat random vuistgevecht gedrag een veelvoorkomend probleem is. Verder is RDM/FailRP hierdoor makkelijker te handhaven omdat het direct opvalt wanneer iemand een ander meerdere keren achter elkaar KO slaat en er dus meer tijd is om op een Report te reageren i.p.v. eerst videobewijs moeten bekijken.

**Comment by Chang-nl** [comment]
Feature zit erin!
