### ISSUE TITLE
[Bug]: Maze Bank Garage Aanbellen kapot

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#1717]
### Wat gebeurde er?

De optie om aan te bellen bij iemand zijn garage om naar binnen te kunnen werkt vaker niet dan wel. Vaak in de ochtend uren werkt het maar later op de dag werkt het niet meer en kun je het kopje "Aanbellen bij garage" niet meer openen.

### Frequentie van de bug

Meerdere keren per dag

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/93911282/199546779-3445b46b-d7a0-4c3f-bf46-4cfd0d1eee01.png)

**Comment by ToniGain** [comment]
Als het eventueel uit komt ook hier nog naar kijken: https://github.com/Tedeapolis/development/issues/1651

**Comment by CorruptSausage** [comment]
Is dit nog steeds een probleem? Want zover ik zag was deze error slechts een timed out.

**Comment by Chang-nl** [comment]
Hey @Lorenzo3001, kun je hier een update over geven? Alv bedankt!

**Comment by Lorenzo3001** [comment]
> Hey @Lorenzo3001, kun je hier een update over geven? Alv bedankt!

Dit is nog steeds een probleem ja. Het leek eerst verholpen te zijn maar heb het zojuist getest en werkt nog niet.

**Comment by TedeaTaxi** [comment]
als je iemand wil binnen laten staat er ook een steam naam ipv in game naam 

als je iemand wil binnen laten vaker dan 1 keer blijft zijn naam staan dus als iemand 4 keer aan belt dan blijft de lijst staan met 4x zijn naam

**Comment by Attomn** [comment]
@Chang-nl

**Comment by Ljosfari** [comment]
is dit al gefixed ? @Lorenzo3001
