### ISSUE TITLE
[FEATURE]: Permissie update CCF

### ISSUE THREAD

**Issue by musician1011** [Tedeapolis/development#1718]
### Contact Details

Musician1011#1260

### Beschrijf zo duidelijk mogelijk de feature

(indien mogelijk)
-de aankoop van attachments toelaten vanaf de "made men" rang

**Comment by zeletix** [comment]
Zover ik weet is de aankoop van attachments los niet mogelijk, zodra je bijvoorbeeld de permissies krijgt om pistols te tunen kan je die ook gelijk inkopen, en het zelfde geldt voor de grotere wapens.

**Comment by musician1011** [comment]
Dan kan deze gewoon dicht denk ik? Lijkt me ook dat andere zaken misschien net iets belangrijker zijn dan dit.

**Comment by musician1011** [comment]
Gesloten, issue is teveel werk voor wat het toevoegt (vind ik persoonlijk)
