### ISSUE TITLE
[FEATURE]: Nieuw takelwagen script?

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1719]
### Contact Details

DeStefanoKiller#4442

### Beschrijf zo duidelijk mogelijk de feature

Ik denk dat de video wel genoeg informatie geeft over het systeem. Het takelen ziet er vele malen realistischer eruit, dit is dan ook veel leuker voor de takel ploeg om dit te doen. 

https://www.youtube.com/watch?v=derm4LaiuGo&list=LL&index=4&ab_channel=KadDarem

### Wat lost deze feature op?

Het takelen gaat er realistischer eruit zien Ipv dat uit het niets een voertuig achterop de takelwagen wordt getped.

**Comment by CorruptSausage** [comment]
We gaan even overleggen als dit voor onze server mogelijk is.

**Comment by Chang-nl** [comment]
@CorruptSausage is hier een update over?

**Comment by CorruptSausage** [comment]
> 

Nope

**Comment by CorruptSausage** [comment]
> @CorruptSausage is hier een update over?

Nope

**Comment by niekschoemaker** [comment]
Script zou dan even zelf geschreven moeten worden, gezien de prijs voor het script simpelweg te duur is (niet encrypted versie is rond de 130 euro, budget is beter te besteden)

**Comment by Chang-nl** [comment]
Hey @DeStefanoKiller,

Bedankt voor je feature request!

Helaas hebben we besloten dat deze issue niet gedaan gaat worden, omdat het script zelf 130 euro is en voor het script zelf maken is helaas geen tijd.
