### ISSUE TITLE
ANWB fix dingetjes?

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#172]
- [x]  A) Jerrycans kunnen nog niet vol door een anwb’er gepakt worden. 
- [ ] B) Een pinautomaat buiten de ANWB, OF in de winkel boven de ANWB.
- [x] C) Bij /repareer het geld van de bank af laten gaan.
- [x] D) Lonen van rang 9 en 10, teamleiding/teambaas omhoog naar 1200.
- [ ] E) Het locken van /whisper zodat mensen dat niet kunnen aanpassen in de garage van de ANWB.
- [x] F) Een aantal rangen qua naam moeten veranderd worden:
- Technische specialist in opleiding = Technisch Specialist
- Technische specialist = Assistent Teamleiding
- [ ] G) Welke voertuigen elke rang kan pakken, moet veranderd worden:
- Stagiair = ANWB offroad / ANWB dienstwagen
- Uitzendkracht = ANWB Offroad / ANWB Dienstwagen / Schepwagen
- Monteur in Opleiding = ANWB offroad / ANWB Dienstwagen / Schepwagen / ANWB touring
- Monteur = ANWB offroad / ANWB dienstwagen / Schepwagen / ANWB touring / Takelwagen
- Autotechnicus in opleiding = ANWB offroad / ANWB dienstwagen / Schepwagen / ANWB touring / Takelwagen
- Autotechnicus = ANWB offroad / ANWB dienstwagen / Schepwagen / ANWB touring / Takelwagen
- Eerste Autotechnicus = ANWB offroad / ANWB dienstwagen / Schepwagen / ANWB touring / Takelwagen
- Technisch Specialist = ANWB offroad / ANWB dienstwagen / Schepwagen / ANWB touring / Takelwagen
- Assistent Teamleiding = Alle auto’s.
- Teamleider = Alle auto’s.
- Baas = Alle auto’s.

- [x] H) Facturen systeem zie bijlagen.
[Facturensysteem_ingame_ANWB (1).docx](https://github.com/Tedeapolis/development/files/5212542/Facturensysteem_ingame_ANWB.1.docx)

**Comment by Willem-Dekker** [comment]
G is niet haalbaar met de huidige setup van de plug in

**Comment by Willem-Dekker** [comment]
@niekschoemaker kan jij kijken naar punt E? jij had dit toen ook aangezet in de server ik weet zo namelijk niet waar dit moet zitten
