### ISSUE TITLE
[FEATURE]: de map emote wanneer je de map opend

### ISSUE THREAD

**Issue by kerrieeee** [Tedeapolis/development#1722]
### Contact Details

Kerrie#0469

### Beschrijf zo duidelijk mogelijk de feature

Het is heel simpel. Zodra je esc doet wordt tergelijk de map emote gedaan.

Emote: /e map

### Wat lost deze feature op?

Niks, maar het is realistisch

**Comment by Chang-nl** [comment]
Hey @kerrieeee,

Bedankt voor je feature request!

Zou je een emote kunnen aanleveren, zodat wij deze daaraan kunnen koppelen. Alvast bedankt!
