### ISSUE TITLE
[FEATURE]: Auto's pakken

### ISSUE THREAD

**Issue by kerrieeee** [Tedeapolis/development#1723]
### Contact Details

Kerrie#0469

### Beschrijf zo duidelijk mogelijk de feature

De feature zou zijn dat wanneer je een auto uit de garage pakt dat je dan niet in de auto spawned maar dat je auto op een parkeer plek wordt gezet en dat je dan nog naar je voertuig moet lopen.

### Wat lost deze feature op?

Het snel een voertuig pakken in bijvoorbeeld een achtervolging. En het houd roleplay ontwijkend gedrag tegen gezien ze alsnog naar de auto moeten lopen.

**Comment by zeletix** [comment]
Ik snap niet waarom dit toegevoegd zou moeten worden, dat je in je auto spawned heeft er sinds altijd al ingezeten en dit toevoegen is dus gewoon een anti-QoL feature waar iedereen zich alleen maar aan gaat irriteren ipv dat het problemen oplost.

**Comment by Chang-nl** [comment]
Deze issue zal voor vele problemen gaan zorgen of kost heel veel tijd om te implementeren, mocht het zelfs te implementeren zijn. Uiteraard gaan we verder kijken naar een andere oplossing voor het voorgestelde probleem.
