### ISSUE TITLE
[FEATURE]: Het gebruiksgemak van de F6 gelijktrekken tussen Politie en Criminelen.

### ISSUE THREAD

**Issue by Toro-Carri** [Tedeapolis/development#1724]
### Contact Details

Toro#5710

### Beschrijf zo duidelijk mogelijk de feature

Gütentag allemaal,

Bij de criminelen is er een vertraging in de F6 waardoor wij 3x zo lang bezig zijn als een agent, bij het confisqueren van items. Ik zou niet weten waarom hier een verschil in zou moeten zijn.

Het is momenteel oneerlijk aangezien er geen speciale handelingen worden verricht wat zou verklaren dat criminelen een delay zouden moeten hebben op het confisqueren. Tijdens burgerraad is er besproken om er een github van te maken.

Overheids confisqueren: https://youtube.com/clip/UgkxsOUOt2b4TOuTq3HW_Lvhb5pAM2e2Rmh_
Criminelen confisqueren: https://medal.tv/games/gta-v/clips/HIty9M3xWxprK/d1337NSJv3yx?invite=cr-MSxuRUksNTA4NDQ1Mzgs

Hopelijk kan dit gelijk worden getrokken aangezien criminelen bij elke keer confisqueren een vertraging hebben van een aantal seconde. Ook krijgen wij elke keer de emote opnieuw als we iets hebben gepakt. Bij overheidsdiensten is het makkelijk en is het klik, klik en klaar.

Zou door vele in de stad worden gewaardeerd, mochten jullie er misschien eens naar kunnen kijken! 😀 

### Wat lost deze feature op?

Het fouilleren en confisqueren van politie en criminelen gelijk trekken. Momenteel zijn criminelen 3x zo lang bezig, ten opzichte van politie/kmar.

**Comment by Toro-Carri** [comment]
Ik zie dat de 'overheids confisqueren' video link niet werkt als je er op klikt. Maar als je de URL kopieert en plakt in de zoekbalk, doet hij het wel :)

**Comment by zeletix** [comment]
En je kan misschien zeggen "dit duurt maar een seconde of twee langer invergelijking met politie" maar als je dan 3-4 dingen moet afpakken in the heat of the moment kan dit een heel groot verschil maken.
