### ISSUE TITLE
[FEATURE]: Gangopslag sleutel delen met iedereen in de job

### ISSUE THREAD

**Issue by musician1011** [Tedeapolis/development#1725]
### Contact Details

Musician1011#1260

### Beschrijf zo duidelijk mogelijk de feature

Is het doenbaar om de sleutel van een voertuig dat uit een gangopslag komt, te koppelen aan de desbetreffende gang/job? 

### Wat lost deze feature op?

Zo zijn de voertuigen toegankelijker voor iedereen die bijvoorbeeld meedoet aan een RP waar opslagvoertuigen aan te pas komen. (nu heeft enkel de speler die het voertuig uit haalt daadwerkelijk de sleutels.)

**Comment by CorruptSausage** [comment]
Lijkt me persoonlijk zelf een beetje overbodig en ook enorm overpowered, het lijkt mij logischer om gewoon alleen de persoon die het voertuig eruit pakt de sleutels te geven. Daarnaast als deze sleutel gedeeld moet worden kunnen ze dit gewoon met grantkeys doen.

**Comment by Chang-nl** [comment]
Hey @Ljosfari, was hier al een puntje voorbhet staffoverleg bij aangemaakt?
