### ISSUE TITLE
[FEATURE]: Reports van Streamer role in andere kleur weergeven

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1727]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

Besproken in Staff Praatstraat vandaag, o.a Akkoord van Stoffigkontje.

Kleur: #E1C5FC
Discord rollen: Streamer

Reports van streamers in andere kleur zodat het meer opvalt tussen de andere reports.

### Wat lost deze feature op?

Buiten dat het #youtube kanaal hiervoor gebruikt kan worden is het ook duidelijker voor ingame reports vooral met de veel wisselende steam namen dat het om een streamer gaat, aangezien deze de streamer rol heeft in discord.

**Comment by Chang-nl** [comment]
Hey @Ljosfari, is dit al besproken en kan deze doorgevoerd worden?

**Comment by KeesdeB** [comment]
HR en meerdere HS waren het er mee eens, zodat die reports beter opvallen.

**Comment by StoffigKontje** [comment]
Wanneer kan dit uitgevoerd worden?

**Comment by Chang-nl** [comment]
Hey @StoffigKontje, Heeft het prioriteit? Dan kan de label "high priority" gegeven worden aan de github issue en zal er zo spoedig mogelijk naar gekeken worden!

**Comment by StoffigKontje** [comment]
Eigenlijk wel, dus als je dat zou willen? <3

**Comment by Chang-nl** [comment]
Hey @KeesdeB, 

Bedankt voor het aanmaken van de github issue.

Na de herstart zit de feature in de server!
