### ISSUE TITLE
[FEATURE]: Overval- en drugsmeldingen ook via de meldkamer binnen laten komen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1728]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Meldingen van overvallen en drugsmeldingen niet alleen op de map en notificatie link onderin je scherm aangeven maar ook via de meldkamer een melding binnen krijgen. 

### Wat lost deze feature op?

Wij gebruiken het portosysteem om eenheden aan te sturen. Hierin krijgen we de meldingen uit de meldkamer in-game binnen die we dan ook gelijk kunnen toewijzen aan bepaalde eenheden. Overval en drugsmeldingen krijgen we niet via deze meldkamer binnen en hiervoor kunnen we dan dus ook niet ons handige portosysteem voor gebruiken. Dit zou dus handig (en logisch zijn) dat we deze ook via de meldkamer binnen krijgen.

**Comment by Chang-nl** [comment]
Hey @CorruptSausage, is hier al een update voor te geven?

**Comment by CorruptSausage** [comment]
> Hey @CorruptSausage, is hier al een update voor te geven?

Was er mee bezig, ligt momenteel nog op een laag pitje aangezien het niet enorm grote prioriteit heeft.

**Comment by Chang-nl** [comment]
Hey @PolitieTDA,

Bedankt voor je github issue!

Zou je kunnen specificeren wat je van ons precies nodig hebt?

**Comment by Tom974** [comment]
Hey @PolitieTDA, 

Dit zal aangepast zijn na de herstart van 02:00!
