### ISSUE TITLE
[FEATURE]: Uitzetten van volbrachte taakstraffen en overige berichten in de chat

### ISSUE THREAD

**Issue by Haceyy** [Tedeapolis/development#1729]
### Contact Details

hace#6126

### Beschrijf zo duidelijk mogelijk de feature

Nu is het zo dat er openbaar gemaakt word in de chat dat mensen hun taakstraf volbracht hebben. Een groot groen vlak verschijnt in je chat met daarin bijv. "RECHTER: RvdBogaart heeft zijn taakstraf volbracht!"

Ik zou graag een soortgelijk command als "/toggletwitter", "/chatagree" en "/automessage" zien, waardoor je deze meldingen dus niet meer binnen krijgt.

Ik stel zelf voor "/rechter" of iets in die trant.
Welk command maakt in principe niet uit.

### Wat lost deze feature op?

Het lelijke groene vlak in je beeld, dat bovendien een boel ruimte in beslag neemt voor mensen met een 1080p scherm en voor mij persoonlijk ook niets toevoegt aan mijn beleving in TDA zal niet meer te zien zijn.

Hierdoor heb ik meer overzicht van mensen die berichten sturen in /me of /looc, zie ik duidelijker op welk volume ik mijn porto gezet heb en zie ik gemakkelijk of ik mijn auto open of dicht heb staan.

**Comment by Haceyy** [comment]
Hierboven niet benoemd, maar bovendien ook de straffen die staff uitdeelt aan anderen. In mijn optiek zijn alleen de straffen die ik zelf zou krijgen relevant.

**Comment by niekschoemaker** [comment]
> Hierboven niet benoemd, maar bovendien ook de straffen die staff uitdeelt aan anderen. In mijn optiek zijn alleen de straffen die ik zelf zou krijgen relevant.

Je kunt ook gewoon /togglechat doen voor zover ik weet, sommige berichten markeer ik als belangrijk, deze negeren togglechat, dus als je togglechat doet zie je alleen nog hele belangrijke berichten.

**Comment by Chang-nl** [comment]
Hey @Haceyy, Het staat nu voor de time-being op admin only. Bedankt voor het melden!
