### ISSUE TITLE
re-issue: /docu documenten kunnen niet verwijderd worden

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#173]
Ik zag dat deze als solved aangemerkt stond ( https://github.com/Tedeapolis/development/issues/143 ), maar ik heb dit probleem nog steeds.
![2020-09-07 22_14_42-Window](https://user-images.githubusercontent.com/70340143/92994370-e38e2880-f4f9-11ea-9f01-68912b86248c.png)

**Comment by niekschoemaker** [comment]
Zou morgen gefixed moeten zijn.

Blijkt dat documenten die niet bestonden op de server niet verwijderd konden worden als je ze nog lokaal had opgeslagen. Dus die zitten dan vast, dus heb die check gewoon weggehaald dat zou het moeten fixen.

**Comment by niekschoemaker** [comment]
@PapaXilion Zou je nog even kunnen terugkoppelen hierop of het gefixed is voor jou?
Voor mij is het nu namelijk gefixed.

**Comment by PapaXilion** [comment]
Deze werkt nu! 👍 Kan dicht.
