### ISSUE TITLE
[Bug]: Taxi Hek

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1730]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

Als mensen naar het noorden gaan komt het voor dat ze het sleuteltje van het hek niet meer zien 
tevens is de range van het hek zo groot dat je het hek open en dicht doet als je voertuigen pakt uit de garage en ze er weer in zet hier door komen er als nog vaak weer mensen op het terrein 

### Wat hoorde er te gebeuren?

slotje hoort blijven zitten en dan kunnen ze de poort weer open en dicht doen

oplossing voor de garage is verplaatsen van de cirkels 
Foto hier onder 
![FiveM_b2372_GTAProcess_5FxpwWcuha](https://user-images.githubusercontent.com/93401910/201216665-742b0220-6f40-4b20-95d4-fdaee61a7c72.jpg)

Rood : OUD
X 316.13
Y -1154.87 
Z 29.29
H 310.13

Rood : Nieuw
X 316.02
Y -1164.96 
Z 29.29
H 356.95

Groen : OUD
X 325.32
Y -1156.90 
Z 29.29
H 240.39

Groen : Nieuw
X 309.64
Y -1164.96 
Z 29.29
H 180.86

### Wat veroorzaakt de bug?

uit de range gaan van het laden van het hek gebeurd niet bij iedereen en dus random

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by CorruptSausage** [comment]
Fixed na restart.
