### ISSUE TITLE
[FEATURE]: Caribbean cirkels

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#1731]
### Contact Details

ToniGain#0001

### Beschrijf zo duidelijk mogelijk de feature

Hoi!
Ik heb toestemming gekregen om een issue hiervoor te maken vanuit de ticket.

Ik ben in bezit van het huis in de bergen op postcode 653, hier zaten wij vroeger met Peaky.
Nu wonen we hier met Caribbean en zetten we er onze roleplays graag neer. In ticket 167671 is er een akkoord gegeven om de cirkels te fixen. Hier was een tijdje aan gewerkt, maar we hebben er niet veel meer van gehoord. 

Het gaat om het volgende:
- [ ] Expension 20 rank werkend maken op secondary job (job2)
- [ ] Expension 10 cirkel niet toonbaar maken
- [ ] Recruiten en ontslaan fixen (bugged nu)
- [ ] Geld storten/pot werkend maken (als dat mogelijk en goed is vanuit jullie)

De cirkels zitten in het kantoor boven. 

Als deze nog gemaakt kunnen worden zal dat echt top zijn! We zijn al bij het huis zelf begonnen met allerlei roleplay's, maar als dit nog gedaan kan worden dan kunnen de leden zelf ook sleutels krijgen. Voor extra context refereer ik naar de ticket.
Alvast bedankt!

### Wat lost deze feature op?

Onze cirkels in het huis worden werkend. We kunnen dan echt beginnen als 'gang' bij het roleplay huis.

**Comment by Ljosfari** [comment]
van wie heb je toestemming ?
