### ISSUE TITLE
[Bug]: Mazebank lift naar helipads stuk

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#1732]
### Contact Details

ToniGain#0001

### Wat gebeurde er?

De lift naar het dak werkt niet altijd meer bij de mazebank. Soms wel, soms niet. Als die niet werkt moet je reloggen, dan werkt die wel. Een error heb ik niet gevonden in de console. Ik ben niet de enige die dit heeft. 

Mocht deze bug niet zo makkelijk op te lossen zijn, is dit ook nog een optie.
https://github.com/Tedeapolis/development/issues/1628#issue-1376437644

### Wat hoorde er te gebeuren?

Dat je naar boven gaat

### Wat veroorzaakt de bug?

1) Gebruik de lift
2) Gebruik hem weer omhoog, dan zul je zien dat het niet altijd werkt
dat is het.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by ToniGain** [comment]
Vandaag in de console gevonden wat het was.
![image](https://user-images.githubusercontent.com/73707925/201470759-41a671c8-2d1f-4543-bd73-06c981797122.png)

https://user-images.githubusercontent.com/73707925/201470773-7e52a5df-f470-49e0-b74b-c8fdff44700f.mp4

**Comment by Chang-nl** [comment]
Hey @ToniGain, bedankt voor het aanmaken van deze github issue. Mogelijk dat de issue na de herstart verholpen is. Zou je dit kunnen terugkoppelen of dit dan opgelost is dan ja of te nee. Alv bedankt!

**Comment by ToniGain** [comment]
Heel fijn dankjewel, ik zal het gaan testen komende dagen en je hoort van me.

**Comment by niekschoemaker** [comment]
Geen verdere reactie
