### ISSUE TITLE
[Bug]: Zoeklicht zulu niet gesynced

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1733]
### Contact Details

CoffeeSipper#8888

### Wat gebeurde er?

Zulu lamp/zoeklicht is niet gesynced. Personen op de grond zien m niet

### Wat hoorde er te gebeuren?

Iedereen hoort het licht te zien.

### Wat veroorzaakt de bug?

Er staat in de F8 logs ''Prepare and update data for: 4264''

### Frequentie van de bug

Af en toe

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/96985840/201445950-da2c5435-7f1c-4cef-93e0-2146fa4542fe.png)

**Comment by Chang-nl** [comment]
Is als het goed is opgelost in de laatste update, klopt dit? @CoffeeSipper

**Comment by Chang-nl** [comment]
Hey @CoffeeSipper, Ik neem aan dat dit opgelost is, zo niet laat het hieronder weten. Bedankt voor het aanmaken van deze issue!
