### ISSUE TITLE
[FEATURE]: Nieuwe MLO Vespucci

### ISSUE THREAD

**Issue by Kalasjj** [Tedeapolis/development#1734]
### Contact Details

Kalasjj #4845

### Beschrijf zo duidelijk mogelijk de feature

MLO Vespucci(Side location):

- Sloten moeten nog ingebracht worden.
- De 2 motors binnen moeten veranderd worden naar eigen motor.
- Voertuigopslag/kledingkast toevoegen.
- Muziekbox plug-in toevoegen.
- Boxring plug-in toevoegen.
- Pooltafel plug-in toevoegen.

Nieuwe Kleding TFFT:
- Alle huidige kleding van nu moeten vervangen worden door de nieuwe met een aantal extra kledingstukken.

MLO Cypress Flats(Main location):
- Sloten moeten nog ingebracht worden.
- Uiterlijk minimaal aangepast worden.
- Gangopslag
- Voertuigopslag
- Kledingkast 
Nog een aantal dingen..

### Wat lost deze feature op?

N.V.T.

**Comment by Oesewoes** [comment]
Assign me pls ;_;

**Comment by DevvTDA** [comment]
Kleding is gefixt staat vannacht om 02:00 uur in de server

**Comment by Ljosfari** [comment]
dit zit er allemaal in toch ?
