### ISSUE TITLE
[FEATURE]: Groene cirkel groter maken

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1735]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Ik merk dat de cirkels van het pakken van je voertuig kleiner zijn geworden. Alleen is dit enorm hinderlijk want iedereen duwt elkaar uit de cirkel. Tevens heb ik het probleem dat ik er amper meer inpas door mijn lichaam. Ik zie de cirkel dus graag weer terug naar normale grootte.

Zie screenshots: 
![image](https://user-images.githubusercontent.com/101106299/201494148-f32f15d8-984d-4891-a0ec-48085f33a79f.png)
![image](https://user-images.githubusercontent.com/101106299/201494159-7839fe0d-673d-4cd6-af61-bc2f972796c7.png)

### Wat lost deze feature op?

Dat iedereen weer normaal in de cirkel past en zijn voertuig kan pakken.

**Comment by Chang-nl** [comment]
Om welke cirkel gaat dit specifiek? Lijkt alleen bij die cirkel een probleem te zijn namelijk.

**Comment by CalRayy** [comment]
> Om welke cirkel gaat dit specifiek? Lijkt alleen bij die cirkel een probleem te zijn namelijk.

Excuses, de groene cirkel om voertuigen te pakken is nog al verkleind en vandaar de vraag om het terug groter te maken.

**Comment by CalRayy** [comment]
Ik zie dat de cirkels weer groot zijn, thanks!

**Comment by Chang-nl** [comment]
Hey @CalRayy, goed om te horen dat het probleem opgelost is. Bedankt voor het aanmaken van een github issue!
