### ISSUE TITLE
[Bug]: Zoeklicht zulu

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1736]
### Contact Details

CoffeeSipper#8888

### Wat gebeurde er?

Zoeklicht gaat regelmatig niet aan met G

### Wat hoorde er te gebeuren?

Hoort aan te gaan

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by Chang-nl** [comment]
Mogelijk gefixt na herstart!

**Comment by niekschoemaker** [comment]
@CoffeeSipper Zou je even terug kunnen koppelen als het gefixed is nu?

**Comment by CoffeeSipper** [comment]
> 

Lijkt erop van wel! Dank!

**Comment by Chang-nl** [comment]
Goed om te horen, bedankt voor het aanmaken van de bug report!
