### ISSUE TITLE
[FEATURE]: Maanden celstraf van een minuut per stuk naar 30 seconden veranderen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1737]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Momenteel telt elke maand voor één minuut in-game tijd, graag dit veranderen naar 30 seconden.

### Wat lost deze feature op?

Tijdelijke oplossing totdat er nieuwe roleplay mogelijkheden worden toegevoegd aan de gevangenis.

**Comment by niekschoemaker** [comment]
Zit erin
