### ISSUE TITLE
[Bug]: Sloten Karmellos

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1738]
### Contact Details

iHax0r#3736

### Wat gebeurde er?

![image](https://user-images.githubusercontent.com/29235700/201543625-99bea806-a3bd-4401-ae35-7c517634c3e2.png)
De deur op deze coördinaten is heel vaak geen slot zichtbaar, waardoor je hem niet open of dicht kan doen. Nu is hij dicht waardoor ik niet naar binnen kan en indien hij open staat kan juist iedereen naar binnen.

### Wat hoorde er te gebeuren?

Deur hoort een slot te hebben, die momenteel niet altijd zichtbaar is.
![image](https://user-images.githubusercontent.com/29235700/201543688-9775138b-1857-47d3-91f5-72d76737f446.png)
Zoals bij deze deur.

### Wat veroorzaakt de bug?

Hierdoor kunnen we via een deur die best veel gebruikt wordt niet naar binnen, tevens kunnen mensen naar binnen die niet naar binnen horen te kunnen.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

**Comment by TedeaTaxi** [comment]
ons hek heeft het zelfde probleem miss is er een storing met nieuwe sloten ?
dat die anders werken dan de rest van de sloten ?

als dit per situatie bekeken moet worden maak ik hier een nieuwe github voor 

--ali osram

**Comment by Chang-nl** [comment]
kleine kans dat het gefixt is, heb een aantal aanpassingen gedaan.

**Comment by Chang-nl** [comment]
Zou er terug gekoppeld kunnen worden of het enig verschil heeft gemaakt? @iHax0rMC

**Comment by iHax0rMC** [comment]
> 

Zijn momenteel geen klachten meer over, wat mij betreft mag hij geclosed worden dank voor de hulp!

**Comment by Chang-nl** [comment]
Hey @iHax0rMC, goed om te horen dat het opgelost is en bedankt voor het aanmaken van de github issue.
