### ISSUE TITLE
[Bug]: Casino (rad) is geen greenzone meer

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1739]
### Contact Details

Yohandessu#3314

### Wat gebeurde er?

Bij heel casino is er zolang ik mij kan herrineren een greenzone, alleen sinds kort is er bij het rad geen greenzone meer. Hier kunnen mensen dus gewoon slaan en mensen dood maken. 

### Wat hoorde er te gebeuren?

Dat er een greenzone is bij geheel casino inclusief het rad

### Wat veroorzaakt de bug?

Dat mensen kunnen slaan en doodmaken waar dit niet hoort 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Geen

**Comment by Chang-nl** [comment]
Hey @JohanDewus, hartelijk bedankt voor het aanmaken van een github issue. De issue is opgelost na de herstart!
