### ISSUE TITLE
[FEATURE]: Dat zodra je een rolstoel inspawnt iemand deze meteen vast heeft in zijn hand.

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1740]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Zodra patiënten naar binnen moeten en niet met de brancard naar binnen kunnen zullen we toch de rolstoel moeten gebruiken maar ik hoor erg vaak irritatie dat de rolstoelen vaak omvallen bij het inspawnen en er dan mee zitten te kloten dat de rolstoel eindelijk rechtop staat om em beet te nemen. Dat kost tijd en stress. Ik heb er al sinds dag 1 last van. Dus mijn idee was als je de rolstoel inspawnd dat je die gelijk vast hebt in je handen en niet dat de rolstoel in je karakter spawnd.

### Wat lost deze feature op?

als je de rolstoel inspawnd dat je die gelijk vast hebt in je handen en niet dat de rolstoel in je karakter spawnd.

**Comment by Chang-nl** [comment]
Hey @WilmaWonka1985, Ik heb het aangepast en dit zal na de herstart van kracht zijn. Bedankt voor het aanmaken van een github issue.
