### ISSUE TITLE
[Bug]: Daily rewards 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1741]
### Contact Details

Ali Osram
### Wat gebeurde er?

als je /daily doet blijf je vast hangen in het menu je kan hem niet sluiten door esc te drukken 

### Wat hoorde er te gebeuren?

drukken van esc zorgt dat hij sluit 

### Wat veroorzaakt de bug?

![image](https://user-images.githubusercontent.com/93401910/201705373-97a19c84-7311-4195-8e13-a4ebc7a944ff.png)
je kan niet meer uit je daily rewards scherm 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

zie foto

**Comment by CorruptSausage** [comment]
Heb je hier nog steeds last van? Want als het goed is was dit gefixt.

**Comment by TedeaTaxi** [comment]
fixed :) 

gister hadden er meer mensen last van vandaag werkt het ! dankje
