### ISSUE TITLE
[FEATURE]: Verandering in /daily

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1742]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In het staffoverleg hadden wij besproken dat /daily in een rad mag veranderen, zodat er inzicht in zit van als je bijna wat leuks had gewonnen of niet. Tevens hebben wij ook besproken om extra items in /daily te zetten wat elke persoon iets aan heeft.

### Wat lost deze feature op?

Meer overzicht en het kan leuk zijn

**Comment by Ljosfari** [comment]
wat voor een items ?

**Comment by Ljosfari** [comment]
we hebben er naar gekeken, is helemaal kut
