### ISSUE TITLE
[FEATURE]: Dealer systeem cancelen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1743]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

In het staffoverleg hadden we besproken om een verandering aan te brengen aan mensen die dealer cancelen tijdens het kloppen. 
Niek gaf aan dat hij hier een oplossing voor had: 

Er word gekeken hoe lang de persoon in kwestie aan het kloppen is en die hoeveelheid die hij krijgt een penalty geven voor het cancelen, zodat mensen die cancelen benadeelt zijn en minder snel cancelen.

### Wat lost deze feature op?

Meer risico tijdens het verkopen.

**Comment by Chang-nl** [comment]
Hey Calray, Ik Snap het idee van de penalty niet volledig. Een penalty in de zin van zakjes afpakken of wat word hier bedoeld?

**Comment by Toro-Carri** [comment]
> Hey Calray, Ik Snap het idee van de penalty niet volledig. Een penalty in de zin van zakjes afpakken of wat word hier bedoeld?

Ik denk dat Calay bedoeld; Wanneer je klopt bij je dealer punt kan er een melding afgaan. Op dat moment kan je gelijk de verkoop cancellen en naar je nieuwe locatie (in de hoop dat er hier geen melding is) en op deze manier zonder risico verkopen.

De penalty waar Ray het over heeft zou dan zijn; Je kan bijvoorbeeld de eerste 3 seconde niet cancellen, maar daarna wel. Als je gelijk cancelt loop je weinig risico maar verkoop je ook maar 5 zakjes (bijvoorbeeld). Dus op basis van hoe lang je klopt de zakjes verkopen. Per seconde dat je klopt bijvoorbeeld 2 zakjes drugs verkopen. 

Op deze manier is het realistisch gezien je natuurlijk ook kan stoppen met het verkopen van drugs, als je het gevoel hebt bedreigd te worden. Maar je moet dus wel daadwerkelijk risico lopen om überhaupt drugs te verkopen.

**Comment by CalRayy** [comment]
> > Hey Calray, Ik Snap het idee van de penalty niet volledig. Een penalty in de zin van zakjes afpakken of wat word hier bedoeld?
> 
> Ik denk dat Calay bedoeld; Wanneer je klopt bij je dealer punt kan er een melding afgaan. Op dat moment kan je gelijk de verkoop cancellen en naar je nieuwe locatie (in de hoop dat er hier geen melding is) en op deze manier zonder risico verkopen.
> 
> De penalty waar Ray het over heeft zou dan zijn; Je kan bijvoorbeeld de eerste 3 seconde niet cancellen, maar daarna wel. Als je gelijk cancelt loop je weinig risico maar verkoop je ook maar 5 zakjes (bijvoorbeeld). Dus op basis van hoe lang je klopt de zakjes verkopen. Per seconde dat je klopt bijvoorbeeld 2 zakjes drugs verkopen.
> 
> Op deze manier is het realistisch gezien je natuurlijk ook kan stoppen met het verkopen van drugs, als je het gevoel hebt bedreigd te worden. Maar je moet dus wel daadwerkelijk risico lopen om überhaupt drugs te verkopen.

@Chang-nl Klopt inderdaad, alleen toevoeging hierop als je cancelt verlies je ook een gedeelte van het geld bij het verkopen en de hoeveelheid zakjes. Voorbeeld hiervan: je moet 10 seconden lang kloppen en je hebt 30 zakken. Je cancelt na 2 seconden dan zal je 6 zakjes verkopen, en krijg je 2K i.p.v. 6k of hoger (dit is een voorbeeld).

**Comment by niekschoemaker** [comment]
Zit erin.
