### ISSUE TITLE
Sloten voor Tcharmil

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#1744]
### Contact Details

Lionskull

### Beschrijf zo duidelijk mogelijk de feature

Al een geruime tijd zijn we aanwezig in de stad als groep. We willen graag onze Roleplay voorzetten doormiddel van een bestaand huis wat al meer als een jaar niet actief gebruikt wordt.

Het zal gaan om het oude Evans/Alba huis waarbij de MLO al gereed is. We zijn alleen op zoek na een rang waarbij we deuren op en dicht kunnen maken.
We hadden een ticket open staan bij Nander, maar dat MLO wat we nu hebben is niet goed. 
We zouden dus graag een bestaande MLO invullen.

Ticket:166670

Oude Evans huis 
Rang met sloten erop als dit mogelijk is?
![image](https://user-images.githubusercontent.com/95652643/201869334-efb01088-0cc9-45f0-9846-ff89ed735cd6.png)

### Wat lost deze feature op?

We zijn al een geruime tijd hiermee bezig .
Als groep doen we veel bij ons huis en zouden dit graag willen uitbreiden.

**Comment by TDALionskull** [comment]
Moest hem aanmaken van Stoffigkontje.
Nander gaf aan in ticket dat het mogelijk was.

**Comment by Chang-nl** [comment]
Hey @TDALionskull, ik zou graag het volgende willen weten:

Mocht er nog **geen** rang bestaan voor jullie gang, dan graag het volgende invullen:
\* = vereist
mocht er een punt niet ingevuld worden die niet vereist is word hier een eigen invulling aan gegeven

Baan:
- Naam van de baan*
- Rangen die jullie willen met hierbij het salaris*
- Wapen permissies per rang*
- Voertuigen die gemoeid zijn met jullie gang
- Locatie van de armory*
- Locatie van het voertuig spawn punt
- Locatie van het heli spawn punt
- Locatie van het baas menu*

Sloten:
- naam van de baan*
- locatie van het huis(postcode of coördinaten)*
- deuren die niet op slot moeten


Ps: Coördinaten kun je bovenin het scherm krijgen door het commando `/coords` uit te voeren

**Comment by TDALionskull** [comment]
Baan:
**1.	Naam van de baan*** 

Tcharmil Depannage service


**Rangen die jullie willen met hierbij het salaris***

مدير - mudir - directeur = Rang 1 
قناص - qanaas - scherpschutter = Rang 2
جزار - lkazaar - slager = Rang 3 
سلوجي - sloughi - sloughi = Rang 4
شفار - chafar - dief = Rang 5
التلميذ - altilmidh - leerling = Rang 6
خروف - lhouwli - schaap = Rang 7 (geen officieel Tcharmil lid, mag kleding nog niet dragen)

 
**Wapen permissies per rang***

Zijn de enige 2 die toegang hebben tot wapens.
Directeur –  Kan/mag alles
 
**12.	Voertuigen die gemoeid zijn met jullie gang**
 Mercedes 220s
Dit is onze main auto wat Tcharmil !

**13.	Locatie van de armory***
X1826.12
Y441.10
Z118.37
H178.02

 
**15.	Locatie van het voertuig spawn punt**
X-1792.12
Y416.16
Z113.45
H174

 
**16.	Locatie van het heli spawn punt**
X-1750.58
Y443.86
Z128.45
H179.91
 
**17.	Locatie van het baas menu***
X-1796.05
Y413.85
Z116.84
H221.46
 
Sloten:
**1.	naam van de baan***
Tcharmil Depannage service
 
 
**2.	locatie van het huis(postcode of coördinaten)***
X-1805.75
Y400.43
Z152.21
H221.96
 
Postcode : 605
**4.	deuren die niet op slot moeten**
 X-1787.15 
 Y459.45 
Z128.95 
H 221.46
 
 
Groetjes Lionskull

**Comment by Ljosfari** [comment]
er is geen goedkeuring voor jobs/rangen, alleen voor de sloten @Chang-nl @TDALionskull
