### ISSUE TITLE
[FEATURE]: 3 drugs cirkels 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1745]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staffoverleg is er besproken en goedkeuring voor gegeven om 3 cirkels toe te voegen die de hele dag actief blijven tot aan de restart. 
Dit om meer gang wrijving te creëren, tevens ook verzoek van veel criminelen. 

1 Coke cirkel
1 Meth cirkel
1 Wiet cirkel

Na de restart zal de cirkel zich verplaatsen. 

### Wat lost deze feature op?

niet van toepassing, als er hulp nodig is qua locaties. Kan ik altijd mee denken.

**Comment by Vayenn** [comment]
p.s misschien de cirkel een andere kleur dan ook geven bijvoorbeeld Paars.

**Comment by Chang-nl** [comment]
Hey Vayen, had je enkele ideeën voor locaties?

**Comment by Vayenn** [comment]
> 

Zal ik dit dan even in je DM sturen? of wil je dit via deze github

**Comment by niekschoemaker** [comment]
> ### Contact Details
> 
> Vayen#6904
> ### Beschrijf zo duidelijk mogelijk de feature
> 
> Tijdens staffoverleg is er besproken en goedkeuring voor gegeven om 3 cirkels toe te voegen die de hele dag actief blijven tot aan de restart. Dit om meer gang wrijving te creëren, tevens ook verzoek van veel criminelen.
> 
> 1 Coke cirkel 1 Meth cirkel 1 Wiet cirkel
> 
> Na de restart zal de cirkel zich verplaatsen.
> ### Wat lost deze feature op?
> 
> niet van toepassing, als er hulp nodig is qua locaties. Kan ik altijd mee denken.

Dit gaat om de verkoop cirkels of om de pluk cirkels?

**Comment by Chang-nl** [comment]
Hey @Vayenn,

Heb je bovenstaande vraag gelezen?

Voor de locaties kun je ze het beste even persoonlijk naar een van ons sturen, dan zullen wij een prive github issue aanmaken. Alvast bedankt!

**Comment by Chang-nl** [comment]
Gesloten i.v.m. geen reactie

**Comment by Tom974** [comment]
locaties kun je in mijn dm sturen :)

**Comment by Tom974** [comment]
Zit erin na de herstart
