### ISSUE TITLE
[FEATURE]: Huisinbraken in het noorden/KMar

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1746]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staffoverleg is het besproken en tevens goedgekeurd:

Dat er nieuwe huisinbraken komen in het noorden, tevens ook de KMar deze huisinbraak meldingen laten krijgen. Nu kan enkel Politie huisinbraak alarmen zien. Dit zorgt er voor dat er sneller iemand op de huisinbraak meldingen nu dan ook af gaat, tegenwoordig komt er niemand op af.

### Wat lost deze feature op?

Dit zorgt er voor dat er sneller iemand op de huisinbraak meldingen nu dan ook af gaat, tegenwoordig komt er niemand op af. En heeft de KMar nog een nieuwe bezigheid.

**Comment by Chang-nl** [comment]
Hey Vayen, wat had je in gedachte qua locaties? Was hier al iets voor bedacht? zo niet, zou dit gedaan kunnen worden. Alv bedankt.

**Comment by Ljosfari** [comment]
@Vayenn ?

**Comment by Chang-nl** [comment]
Geen verdere reactie meer.
