### ISSUE TITLE
[Burgerraad]: opslag loods updaten 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1747]
### Contact Details

Ali / Ches / Lorenzo

### Bug
Wapens kunnen niet uit de opslag gepakt worden op dit moment 
(ticket staat nu open voor dit probleem Ticket nr: Dev - 189248  )

### Features
- Optie om zwartgeld op te slaan kunnen kopen (ongelimiteerd bedrag) optie kopen kost 2.000.000 b.v.

- Opslag wapens verhogen naar de volgende waardes niveau 0 = 5 wapens niveau 1 = 10 wapens +5 per niveau etc...  tot max van 30 wapens 
kosten per niveau 
niveau 0 Stock kost de loods 2.000.000 
niveau 1 upgrade wapens kost 500.000
niveau 2 kost 1.000.000
niveau 3 kost 1.500.000
niveau 4 kost 2.000.000
niveau 5 kost 2.500.000
 totaal upgrade wapens kost : 7.500.000

upgrade kosten 
niveau 1 kost 1.000.000
niveau 2 kost 1.500.000
niveau 3 kost 2.000.000

kosten voor opslaan van een auto kost dan 100.000 per auto 

auto's kunnen uitladen in een keer net als andere loods

### Checklist:
- [x] Fix opslag bug (wapens paken)
- [x] Zwartgeld toevoegen 
- [ ] Uitladen via cirkel laten gaan
- [ ] Wapens opslag veranderen
- [ ] Alle puntjes ( feest tijd )

### Wat lost deze feature op?

1. meer gebruik maken van opslag loods 
2. momenteel word het niet gebruikt door de bugs 
3. de prijs voor het opslaan van wapens is te hoog en aantal is niet genoeg op dit moment 

Besproken in de burgerraad 

Lorenzo gaat deze doorzetten naar staf overleg

**Comment by Toro-Carri** [comment]
Mooi puntje, ik denk dat de opslagloodsen inderdaad iets moois kunnen worden voor criminelen op deze manier!

**Comment by niekschoemaker** [comment]
Aangemaakt door het taxi account, wat zijn we van plan 🤔

**Comment by Toro-Carri** [comment]
Mocht er naar gekeken worden, is het misschien nog wel handig om de zelfde optie toe te voegen als in de gang opslag? Met betrekking tot de wapens, zodat je de namen erop ziet en je weet van wie welke is (ivm meerdere dezelfde wapens en attachements)

**Comment by niekschoemaker** [comment]
> Mocht er naar gekeken worden, is het misschien nog wel handig om de zelfde optie toe te voegen als in de gang opslag? Met betrekking tot de wapens, zodat je de namen erop ziet en je weet van wie welke is (ivm meerdere dezelfde wapens en attachements)

Als het goed is geeft hij labels al weer, alleen aanpassen zit er niet in.

**Comment by Toro-Carri** [comment]
Ah super, ik zie dat de items er nu inmiddels ook uit gehaald kunnen worden! Mochten sommige features er niet door komen, wellicht dat we dan eens kijken naar wat wel haalbaar is. Op deze manier worden de opslagloodsen hopelijk wel gebruikt en is het echt iets moois voor de (onofficiële) criminelen.

**Comment by TedeaTaxi** [comment]
> Aangemaakt door het taxi account, wat zijn we van plan 🤔

Ches had hulp nodig vanuit burgerraad en een loods is niet illigaal als je er niks illigaals mee doet 

--ali

**Comment by Lorenzo3001** [comment]
Is goedgekeurd bij staffoverleg

**Comment by Toro-Carri** [comment]
> 

Zoals het hierboven staat beschreven of nog wel anders?

**Comment by Toro-Carri** [comment]
Misschien is het handig om rekening te houden met het volgende puntje:

Op het moment dat je een voertuigen opslag toevoegt kunnen mensen hun wapens in hun auto doen, en opslaan. Het hele effect van de wapenopslag (tunen) en hier geld voor uitgeven, vervalt dan.
Misschien is het handig om hier iets op te bedenken. Bijvoorbeeld dat de inhoud van de kofferbak leeg moet zijn, om je auto op te slaan? 

Het zwart geld opslaan:
- In plaats van één keer de tune kopen om ongelimiteerd op te slaan. Hierin ook tunes kopen. Stock kan er 5.000.000 contant (zwart) geld in. Elke tune vergroot het de geld opslag + 5.000.000 en kost dan een bepaald bedrag;
Tune 1 kost dan 1.000.000 en er past dan 10.000.000 (zwart) contant geld in.
Tune 2 kost dan 1.500.000 en er past dan 15.000.000 (zwart) contant geld in.
Tune 3 kost dan 2.000.000 en er past dan 20.000.000 (zwart) contant geld in.
Tune 4 kost dan 2.500.000 en er past dan 25.000.000 (zwart) contant geld in.
Tune 5 kost dan 3.000.000 en er past dan 30.000.000 (zwart) contant geld in.

**Comment by LouisTDA** [comment]
Komt dit nogsteeds in de stad?

**Comment by WilmaWonka1985** [comment]
Ik krijg vragen of dit nog door gezet gaat worden aangezien dit op 20-11-2022 goed is gekeurd bij staffoverleg. en ik krijg nu mensen in mijn DM hierover.

**Comment by Tom974** [comment]
Hallo iedereen & @TedeaTaxi,

Ik heb even overlegd met Misstake wat precies de status is van deze issue. Helaas ga ik moeten mededelen dat de features die er nu inzitten zo zullen blijven. Er zal dus geen aanpassing worden gedaan aan het aantal wapens of een optie om je kofferbak uit te laden.
