### ISSUE TITLE
[Bug]: Daily niet sluitbaar

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1748]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Zodra men /daily doet is dit "menu" niet meer te sluiten. Niet via escape maar ook niet door er bijvoorbeeld naast te klikken. Overige toetsen (T, M etc) werken ook niet.

### Wat hoorde er te gebeuren?

Menu van /daily hoort te sluiten

### Wat veroorzaakt de bug?

/

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

![image](https://user-images.githubusercontent.com/20951687/202065211-a60df744-ce6a-4094-8912-225ff9ab2178.png)

**Comment by CorruptSausage** [comment]
Dit is een duplicate van https://github.com/Tedeapolis/development/issues/1741. Is het probleem weer teruggekomen of niet op de hoogte dat hier al een issue voor was?

**Comment by niekschoemaker** [comment]
Is een nieuwe issue

IK HAD HET GETEST REEEEEEEEEEEEEEEEE

**Comment by niekschoemaker** [comment]
Oh wacht, dit is de oude key handler nog, ja je kunt nu het menu gewoon sluiten door er buiten te klikken

Maar ik zal escape ook even fixen, maar je kunt er dus ook gewoon ergens buiten klikken om het te sluiten, dat werkt wel.

**Comment by niekschoemaker** [comment]
Is gefixed
