### ISSUE TITLE
Bug: wijzigen profielfoto Twitter geeft melding Onjuist Wachtwoord

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#175]
Zoals beschreven in titel.
![image](https://user-images.githubusercontent.com/70340143/92995744-5a312300-f506-11ea-891c-965c1b5a4183.png)

**Comment by niekschoemaker** [comment]
Issue zou vanaf morgen gefixed moeten zijn

**Comment by PapaXilion** [comment]
Deze werkt weer! Dankje! 👍
