### ISSUE TITLE
[Bug]: Benzine / tank station 3.0

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1750]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De issues is weer terug die ik een tijdje terug beschreef: #1345 en #1302 , maar deze keer gebeurd dit ook wanneer je naar het noorden vliegt en terug.

### Wat hoorde er te gebeuren?

je hoort de tank pomp te zien, nadat je een stukje hebt gevlogen.

### Wat veroorzaakt de bug?

geen idee, Niek wist een tijdje geleden wel het probleem. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Zou je het morgen even kunnen checken? Heb de issue denk ik gevonden

**Comment by CalRayy** [comment]
> Zou je het morgen even kunnen checken? Heb de issue denk ik gevonden

Yes, ik zal dit vandaag even testen.

**Comment by CalRayy** [comment]
![image](https://user-images.githubusercontent.com/101106299/202820798-0b971523-b1f5-4b02-802f-b18e7846456a.png)
Helaas is het niet gefixt.

**Comment by Mikajac** [comment]
Zojuist (~03.40, 21-11) zat de bug er nogsteeds in.

**Comment by niekschoemaker** [comment]
Is mogelijk gefixed nu

**Comment by CalRayy** [comment]
Helaas nog niet gefixt (laatst getest 09-12-2022)
