### ISSUE TITLE
[Bug]: Tanken niet mogelijk bij tankstations

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#1752]
### Contact Details

Nubudi#1907

### Wat gebeurde er?

Soms kun je bij een tankstation niet tanken met je auto. Als je uitstapt krijg je niet de mogelijkheid om te tanken of om een jerrycan te kopen. Vaak is dit ook niet op te lossen en moet je naar ander tankstation, wat op sommige momenten best vervelend kan zijn.

### Wat hoorde er te gebeuren?

Na uitstappen hoor je te kunnen tanken of een jerrycan te kunnen kopen als de auto te ver weg staat.

### Wat veroorzaakt de bug?

Onbekend, geen F8 logs en ik heb momenteel ook geen clips. Ik zal updaten met clips zodra ik iets heb.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden
![image](https://user-images.githubusercontent.com/20951687/202878991-cc94d573-8d51-48d4-be3f-ba7b0cc58e74.png)

TBA

**Comment by Ljosfari** [comment]
error message ?

**Comment by Mikajac** [comment]
> error message ?

Helaas niks. Niks in beeld en niks in F8.

https://medal.tv/games/gta-v/clips/JfNn0JxjQy15c/d1337eYZc2kv?invite=cr-MSxDWW4sMjE2NzQyMjcs
Ik heb het voornamelijk bij dit tankstation maar andere mensen hebben het ook bij andere tankstations, voornamelijk die aan Bo-Rentlaan (naast Karmellos).

**Comment by niekschoemaker** [comment]
Als het goed is is dit gefixed
