### ISSUE TITLE
[FEATURE]: Respawnen cellencomplex ( Politie HB ) 

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1753]
### Contact Details

[TDA] Johnny Flodder#3559

### Beschrijf zo duidelijk mogelijk de feature

Mensen laten zichen ( bewust ) verhongeren in de cel om zo onder hun straf uit te komen. 

### Wat lost deze feature op?

Dat mensen niet onder hun straf uit kunnen komen als ze zich bewust laten verhongeren.

Graag personen die dit doen laten respawnen in hun cel waar ze in dood gingen. 

Dit is besproken tijdens stafoverleg. 20-11-2022

**Comment by niekschoemaker** [comment]
Zit erin
