### ISSUE TITLE
[Bug]: Ontbrekende collision

### ISSUE THREAD

**Issue by MatteDB** [Tedeapolis/development#1755]
### Contact Details

MatteDB#4517

### Wat gebeurde er?

Bij de kartbaan kan je gewoon door de muur heen lopen terwijl de kartbaan gesloten is.

https://streamable.com/oqkr2f

### Wat hoorde er te gebeuren?

Je hoort niet door deze muur te gaan

### Wat veroorzaakt de bug?

Een missende collision

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

nvt

**Comment by AntonMTDA** [comment]
Assign me plss

**Comment by AntonMTDA** [comment]
Commit is aangevraagd alleen nu even wachten tot dat het doorgevoerd word

**Comment by AntonMTDA** [comment]
close plsss
