### ISSUE TITLE
[Bug]: Deur glitch la fuenta

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1757]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je de deur opent gaat die niet fatsoenlijk dicht zoals de andere deur. 
Zie clip: https://youtu.be/gHl9l6_LYDk

### Wat hoorde er te gebeuren?

De andere deur gaat gelijk dicht en de andere niet, is het mogelijk om de deur gelijk te dicht te laten gaan met E zoals de clip op het einde: https://youtu.be/gHl9l6_LYDk

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
