### ISSUE TITLE
[FEATURE]: blaadjes met notities kunnen achterlaten op de huidige positie

### ISSUE THREAD

**Issue by Chang-nl** [Tedeapolis/development#1758]
### Beschrijf zo duidelijk mogelijk de feature

Notities blaadjes op de grond kunnen leggen en lezen.

voorgestelde script: https://forum.cfx.re/t/releases-esx-notepad/655595

### Wat lost deze feature op?

Mensen kunnen best veel roleplay opzetten op deze methode, gangs en groepen in de onderwereld kunnen bepaalde rp opzetten wat nu niet mogelijk is met tussenpersonen.

Anoniem kan je met deze briefjes best veel roleplay opzetten.

Politie en ambulance kan ook verschillende bedreigingen krijgen door deze briefjes, waardoor er weer roleplay ontstaat.

**Comment by niekschoemaker** [comment]
Wel interessante toevoeging opzich, was deze nog besproken bij staff overleg of niet?

**Comment by Chang-nl** [comment]
Nope, deze was nog niet besproken.

**Comment by Zjefvm** [comment]
Doorgevoerd!
