### ISSUE TITLE
voertuigen achter de ANWBer repareren 

### ISSUE THREAD

**Issue by BartBoos** [Tedeapolis/development#176]
Mocht een ANWBer een auto aan het  repareren zijn, komt er iemand met de auto achter de ANWBer staan wordt zijn auto gemaakt en niet de auto die de ANWBer wil maken. Dit wordt zeer regelmatig gedaan om max €1.500 te besparen.

**Comment by Willem-Dekker** [comment]
fixed raycasting is nu van toepassing
