### ISSUE TITLE
[FEATURE]: Animatie toevoegen aan quicksell

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1761]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een animatie toevoegen aan de quicksell locaties. Op andere servers heb ik ook wel eens gezien dat ze een zakje wiet o.i.d. in hun handen hadden tijdens het dealen, misschien dat zoiets ook leuk is om toe te voegen.

### Wat lost deze feature op?

In plaats van helemaal stil staan in een cirkel doe je dan nog tenminste iets met je character.

**Comment by zeletix** [comment]
Wel dat je dan nog kan lopen, anders wordt alles heel lomp

**Comment by Ljosfari** [comment]
welke animatie @ARJ3N ?

**Comment by Chang-nl** [comment]
Hey @ARJ3N,

Zou je bovenstaand bericht kunnen beantwoorden?

**Comment by ARJ3N** [comment]
Goede vraag. Misschien /e windowshop of /e parkingmeter? Hadden jullie misschien nog suggesties? :) @Chang-nl @Ljosfari

**Comment by Wiebren-3** [comment]
Zelfde emote als '/nearby give', ofc aan de ped.

**Comment by Tom974** [comment]
Deze is al een tijdje toegevoegd, issue stond echter nog open. 

Dus bij deze, het is toegevoegd!
