### ISSUE TITLE
[Bug]: postcode 5024 toevoegen aan /postal (ticket 197824)

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1762]
### Contact Details

Yohandessu#3314

### Wat gebeurde er?

Wanneer je /postal 5024 doet staat er dat deze postcode niet bestaat. Echter is deze wel te vinden op je map die je kan openen met ESC. Dit is erg vervelend voor bijvoorbeeld een eigen bedrijf die daar klanten moet ontvangen! 

### Wat hoorde er te gebeuren?

Dat als je /postal 5024 doet dat er dan een waypoint komt naar de juiste postcode 

### Wat veroorzaakt de bug?

Dat mensen er niet makkelijk kunnen komen aangezien zij dan eerst de postcode handmatig moeten zoeken. 

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

**Comment by niekschoemaker** [comment]
![image](https://user-images.githubusercontent.com/32094562/204685559-f9cb62af-c87d-4b0c-87e1-f4db712a4077.png)

**Comment by niekschoemaker** [comment]
Heb de postcode toegevoegd.
