### ISSUE TITLE
Sloten gaan open om 2u snachts[Bug]: 

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#1763]
### Contact Details

ExpensionX#1134

### Wat gebeurde er?

Er komt vanuit de eigenaar op locatie **6042** met de rank **Ondernemer werknemer/werkgever** rol.
Het probleem is dat de sloten om 2u open gaan staan, dit zonder dat iemand het open zet.

### Wat hoorde er te gebeuren?

De sloten behoren dicht te blijven.

### Frequentie van de bug

1x per dag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Sloten kunnen na een restart alleen standaard op slot of standaard open.

Gaat dit om een gekocht pand of gewoon een pand wat gebruikt wordt? Want die staan in principe standaard open zodat ze gebruikt kunnen worden door anderen wanneer het pand niet meer gebruikt wordt voor langere tijd.

**Comment by niekschoemaker** [comment]
Verder is dit opslaan niet te doen qua resource usage, nou ja is wel te doen, maar is iets wat een hele kleine benefit heeft terwijl dit best wat server resources kost omdat dan constant alle slot statussen opgeslagen moeten worden.

**Comment by ExpensionX** [comment]
Het is een gebouw op bruikleen. Het pand van land and sea. Iedereen met een ondernemers rol kan het openen en sluiten

**Comment by niekschoemaker** [comment]
> Het is een gebouw op bruikleen. Het pand van land and sea. Iedereen met een ondernemers rol kan het openen en sluiten

Yes klopt, maar in principe kan ik hem standaard op slot zetten of standaard open, hij is nu dus standaard open (standaard als in nadat de server restart)

**Comment by ExpensionX** [comment]
Indien het mogelijk is mag die op slot gezet worden. Als het teveel tijd of resource kost is het niet nodig.

**Comment by niekschoemaker** [comment]
> Indien het mogelijk is mag die op slot gezet worden. Als het teveel tijd of resource kost is het niet nodig.

Ja nee, ik geef gewoon de opties aan welke atm mogelijk zijn, dus zonder extra iets. Het opslaan van slot state zou dus teveel moeite zijn. Hij pakt bij het opstarten gewoon de waarde die ik aan het slot  gegeven hebben, dus ene slot staat standaard open, andere standaard dicht.

Maar dan zet ik ze standaard op slot.

**Comment by niekschoemaker** [comment]
Is aangepast
