### ISSUE TITLE
[Bug]: V-65 Molotok kan gestart worden met prop brevet

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#1764]
### Contact Details

Bas#6897

### Wat gebeurde er?

De V-65 Molotok heeft een straalmotor waar je een Jet en Stunt brevet voor nodig hebt. Echter kan dit toestel ook gestart worden met een prop brevet.

### Wat hoorde er te gebeuren?

De V-65 Molotok hoort alleen gestart te kunnen worden met een jet en stunt brevet.

### Wat veroorzaakt de bug?

-

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ehh, is het gewenst dit aan te passen, want atm is het gewoon als je een brevet hebt kun je alle vliegtuigen starten en zitten niet echt specifieke checks oid op.

**Comment by niekschoemaker** [comment]
En als het wel gewenst is, kan je dan even een lijstje sturen met alle spawn namen van de vliegtuigen en welke brevet hierbij hoort (en prop hoeft dan niet, want dat hou ik als default, en helikopter is een losse class dus die kan ik al makkelijk filteren)

Dus alle vliegtuigen waarvoor je een jet of stunt license voor nodig bent.

**Comment by AdventurePandah** [comment]
> En als het wel gewenst is, kan je dan even een lijstje sturen met alle spawn namen van de vliegtuigen en welke brevet hierbij hoort (en prop hoeft dan niet, want dat hou ik als default, en helikopter is een losse class dus die kan ik al makkelijk filteren)
> 
> 
> 
> Dus alle vliegtuigen waarvoor je een jet of stunt license voor nodig bent.

Ik zal hier morgen een lijst plaatsen.

**Comment by Tom974** [comment]
Hey @AdventurePandah,

De aanpassingen zullen aanwezig zijn in de server na de herstart van 02:00!
