### ISSUE TITLE
[FEATURE]:  KMar Drugsmeldingen

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1765]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

Wij als KMAR willen graag dezelfde drugsmeldingen als de politie. Dit is besproken met de politie en wij zien zeker meerwaarde hierin sinds wij grotendeels bezig zijn met controles en surveillance. De politie kan niet op 10 plekken tegelijk zijn en sinds wij eigenlijk meer bezig zijn met opium dan de politie. Doormiddel van deze meldingen kunnen wij ook reageren hierop en zullen er afspraken gemaakt worden met de politie hoe wij dit gaan verdelen.

De hele map drugsmeldingen voor rangen:

kmar 80 
kmar 81 
kmar 82 
kmar 83
kmar 90
kmar 95 
kmar 100

Indien mogelijk zie bijlage voor afbeelding. Het gebied voor de volgende rangen:
![meldingen gta map](https://user-images.githubusercontent.com/77009746/205332450-63eef293-b464-4849-97ab-d5f6f23b8e1d.png)

kmar 74
kmar 73
kmar 72
kmar 71
kmar 70
kmar 60
kmar 50
kmar 45
kmar 40
kmar 35 
kmar 30 
kmar 25 
kmar 20 
kmar 15 
kmar 10
kmar 5
kmar 3
kmar 0

PS: Issue weer geopend na mondeling het besproken te hebben met Misstake & Rabbit

### Wat lost deze feature op?

Het lost eigenlijk niks op maar zorgt wel voor meer roleplay voor de KMAR. Wij kunnen sneller reageren op drugsmeldingen in bijvoorbeeld in het noorden sinds wij daar eigenlijk altijd aanwezig zijn. Wij hebben vaak 10+ mensen in dienst waardoor wij eigenlijk altijd wel een surveillance eenheid hebben.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart
