### ISSUE TITLE
[FEATURE]:  Wapenopslag op de legerbasis

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1767]
### Contact Details

Johnny#8125

### Beschrijf zo duidelijk mogelijk de feature

Dit kwam als suggestie vanuit de KMar. Een wapenopslag op de legerbasis zou voor vele trainingen heel handig zijn, om bijvoorbeeld je wapens, brood en water te kunnen pakken. De meeste trainingen worden hier namelijk ook gegeven. Ik heb ook coördinaten van de locatie waar we het graag zouden willen zien:  X: -2348.62 Y: 3267.29 Z: 32.81 H: 82.14

### Wat lost deze feature op?

Het zou handig zijn voor bij trainingen om hier een cirkel te plaatsen. Sinds kort hebben we ook al een voertuig garage waar we dienstvoertuigen uit kunnen halen, een algemene wapenopslag zou het afmaken. Hierdoor kunnen wij in plaats van op een (hoofd)bureau afspreken gelijk afspreken op de legerbasis, dit zal dan ook het aantal personen/voertuigen op het drukke HB verminderen als er verzameld moet worden voor trainingen die tot 10+ man kunnen zijn.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed na restart.
