### ISSUE TITLE
[FEATURE]: F6, ID/Rijbewijs positie verplaatsen.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1769]
### Contact Details

Johnny#8125

### Beschrijf zo duidelijk mogelijk de feature

Momenteel als je een ID kaart of rijbewijs bekijkt via het F6 menu krijg je die op een positie onder het F6 menu zelf. Maar wij als KMar/Politie moeten altijd bewijslast uploaden van de inventory en een ID-kaart. Op het moment dat je de inventory open hebt staan en een identiteitskaart dan overlappen deze waardoor je niet de complete inventory ziet. Het verzoek is dan ook om het identiteitsbewijs/rijbewijs te verplaatsen, misschien linksboven naast het F6 menu?
Zie voorbeeldfoto's:

https://prnt.sc/mtXcQsfwBXYU
https://prnt.sc/m8WHHnsIaFmL

### Wat lost deze feature op?

Het uploaden van bewijslast completer maken, het overlappen van het identiteitsbewijs en de inventory weghalen. Waardoor je een duidelijk beeld hebt van wat degene op zak heeft en hoe degene heet.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin.
