### ISSUE TITLE
[FEATURE]: Locatie taakstraf verplaatsen naar buiten of binnen in de gevangenis.

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#1771]
### Contact Details

[TDA] Johnny Flodder#3559

### Beschrijf zo duidelijk mogelijk de feature

- Locatie taakstraf verplaatsen naar buiten of binnen in de gevangenis

Zorgt voor meer rp mogelijkheden binnen/buiten de gevangenis.
Dit is besproken tijdens staff overleg ( indien dit mogelijk is )

### Wat lost deze feature op?

Dit zorgt voor meer activiteiten in en buiten de gevangenis, dit zorgt naar mijn idee ook meer rp in de cel plaats van alleen maar AFK staan met Netflix aan. 
Daarbij zorgt dit ook voor een leuke en extra taak voor kmar of politie ( mensen laten luchten etc ) 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
@niekschoemaker heb je hier al een update over?

**Comment by Ljosfari** [comment]
verzoek is dat het op het terrein rond de gevangeis komt

**Comment by Ljosfari** [comment]
kan iemand hier een locatie met coords voor uitzoeken ?

**Comment by CorruptSausage** [comment]
Fixed
