### ISSUE TITLE
[Bug]: /postal doet het niet meer

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1773]
### Contact Details

CalRay#1513

### Wat gebeurde er?

/postal doet het niet, zie screenshot. 
![image](https://user-images.githubusercontent.com/101106299/205511309-194a646c-32d9-43b1-89a6-aea57ee6e879.png)

### Wat hoorde er te gebeuren?

het hoort je een GPS te geven van de postcode 5000 bijvoorbeeld

### Wat veroorzaakt de bug?

![image](https://user-images.githubusercontent.com/101106299/205511318-8f56ac46-75f0-4d54-8d16-777d9565fce3.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Is gefixed
