### ISSUE TITLE
[Bug]: DJ tafels

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1774]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

Na Halloween event zijn alle DJ tafels weg

### Wat hoorde er te gebeuren?

dat de dj tafels op alle locaties er weer zijn 

### Wat veroorzaakt de bug?

Geen idee het gebeurde na dat Halloween afgelopen is 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @TedeaTaxi, na de herstart is de beschreven issue opgelost, bedankt voor het aanmaken van de issue!

**Comment by TedeaTaxi** [comment]
dankje jij voor het maken !! <3
