### ISSUE TITLE
[Bug]: Stopbord politie

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1775]
### Contact Details

CoffeeSipper#8888

### Wat gebeurde er?

Als je op K drukt voor het stopbord, komt er ''politie'' te staan. Dit gaat dan uit en dan staat er opnieuw ''politie''

### Wat hoorde er te gebeuren?

''STOP'' >> ''POLITIE'' zou er moeten staan. Lijkt erop dat alle KMAR voertuigen dit wel hebben. In ieder geval de SIV van de kmar

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Je had minimaal even kunnen vermelden om welke auto dit gaat wellicht, alsin welk model ik zou moeten spawnen, want ik heb geen flauw idee om welk voertuig dit zou moeten gaan.

**Comment by CoffeeSipper** [comment]
> 

Excuus, heb gisteren met Lorenzo het er even over gehad, blijkt dat geen voertuig dit meer heeft. Dus elk politie voertuig laat enkel politie op het stopbord zien.

**Comment by niekschoemaker** [comment]
En t liefst even screenshot van het scherm, dus dat ik het voertuig ook zie, voorkomt verwarring met voertuig modellen, dus per model ff een screenshot met dat paneeltje, en om welke pattern het gaat (8 is om secondary te veranderen, maar andere nummers is nog weer voor andere types lichten)

**Comment by CoffeeSipper** [comment]
![image](https://user-images.githubusercontent.com/96985840/206442255-8aabcdf8-71a3-47a4-9868-3df6e696c143.png)
Vito correct ^ Police3

![image](https://user-images.githubusercontent.com/96985840/206443405-3a010d00-635b-41eb-b1fd-317ee4260112.png)
Touran incorrect ^ police  -- Valt op dat als je je blauwe lampen aanzet, dat het stopbord en de orange lichten ( SEC en WRN ) allebei veranderen naar M004 en L002 uit zichzelf

![image](https://user-images.githubusercontent.com/96985840/206443673-3c79c52a-6f14-41c2-8f8a-c6f33a4227ca.png)
![image](https://user-images.githubusercontent.com/96985840/206443889-6a1ac39f-2d6e-4e23-a70f-f12d8cfee3cc.png)
SIV incorrect ^ police3 -- Stopbord voor is met K, stopbord achter met scrollen, laat alleen ''VOLGEN'' zien. Na 1x blauwe lichten aan te doen, M004 & L002

![image](https://user-images.githubusercontent.com/96985840/206444034-3a484eff-ae68-4cf3-9bd3-25babaef34ba.png)
Alle unmarked voertuigen ^ unmarkedaudirs6 unmarkedrs6 unmarkedrs3 unmarkedrange unmarkedx5m unmarkedgolf unmarkeda6 - Na 1x blauwe lichten aan te doen, M004

![image](https://user-images.githubusercontent.com/96985840/206444594-0d5fe1a5-228d-41ea-a143-e0de356e115f.png)
B-klasse incorrect ^ mercedesb - komt uit de garage met M000 & L000, na 1x blauwe lichten aan te doen, M003 & L002


![image](https://user-images.githubusercontent.com/96985840/206445043-a9a0aa81-9352-49ef-a5dd-10b04f53f270.png)
Amarok incorrect ^ pamarok -- komt uit de garage met M000 & L000, na 1x blauwe lichten aan te doen, M004 & L002

![image](https://user-images.githubusercontent.com/96985840/206445532-b06fc59f-99ba-47be-8d3b-c8a36ba22056.png)
Politie motor incorrect ^ policeb -- komt uit de garage met M000 & L000, na 1x blauwe lichten aan te doen, M004 & L002


Ik heb er niet veel verstand van, maar misschien M000 en M003/4 voor alles gelijk zetten? Dat zijn de standjes die er standaard staan. En misschien L000 laten staan ipv een automatische switch naar L002.

Mocht je meer nodig hebben voor ik het

**Comment by niekschoemaker** [comment]
Blijbkaar zat er een foutje in elsplus, waardoor de hele extra 9 uberhaupt niet werkte.
Het kan dus zijn dat het nu voor aardig wat voertuigen gefixed is, dus als je het even opnieuw kunt checken?

**Comment by CoffeeSipper** [comment]
> Blijbkaar zat er een foutje in elsplus, waardoor de hele extra 9 uberhaupt niet werkte. Het kan dus zijn dat het nu voor aardig wat voertuigen gefixed is, dus als je het even opnieuw kunt checken?

Yes, veel werkt. Alleen de unmarked hebben nog hetzelfde probleem.
![image](https://user-images.githubusercontent.com/96985840/206653131-9bb039d2-f13f-4a83-9870-8fb050ceded2.png)

**Comment by CoffeeSipper** [comment]
> > > Blijbkaar zat er een foutje in elsplus, waardoor de hele extra 9 uberhaupt niet werkte. Het kan dus zijn dat het nu voor aardig wat voertuigen gefixed is, dus als je het even opnieuw kunt checken?
> > 
> > 
> > Yes, veel werkt. Alleen de unmarked hebben nog hetzelfde probleem. unmarkedaudirs6 unmarkeda6 unmarkedrs3 unmarkedrange unmarkedgolf unmarkedx5m ![image](https://user-images.githubusercontent.com/96985840/206653131-9bb039d2-f13f-4a83-9870-8fb050ceded2.png)
> > Edit: Als je je M004 naar M003 veranderd werkt het wel. Alleen als je 1x je blauwe lampen aanzet, dan veranderd M automatisch naar M004. En die heeft alleen ''POLITIE''. Misschien dat de voertuigen naar M003 gezet kunnen worden. WERKT ALLEEN BIJ UNMARKEDX5M
> 
> Edit 2: Achterkant van de unmarkeds werken niet met M003 aan.

**Comment by niekschoemaker** [comment]
Yes oke, die unmarkeds zijn qua stop borden echt een zootje, dus die kan ik helaas niet fixen.
