### ISSUE TITLE
[FEATURE]: /getlocation id

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1777]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Een nieuwe commando genaamd /getlocation id, dit is super handig voor handhaving. Waarom? Je weet niet waar de report is (qua locatie) en dan moet je naar degene tpen of noclippen en als je deze commando gebruikt krijg je dus een GPS naar de report om als handhaving naar toe gaan.

### Wat lost deze feature op?

Leukere RP, en onnodige reply's naar de report toe van "Waar ben je" ?

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Je kan met het commando /waypoint [id] een waypoint op een speler zetten.
