### ISSUE TITLE
[FEATURE]: JOB plaatje toevoegen exotica

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1778]
### Contact Details

Yohandessu#3314

### Beschrijf zo duidelijk mogelijk de feature

een job plaatje toevoegen voor de alle exotica jobs, dit omdat daar nu een soort img. plaatje staat. Het plaatje wat ik hieronder heb bijgevoegd moet er dan komen te staan, bij zowel in en uitdienst exotica jobs. 
![image](https://user-images.githubusercontent.com/103584419/206869619-d472d383-73e5-4e4b-a168-736a915dadec.png)

### Wat lost deze feature op?

Dat de exotica job er net uit komt te zien. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed na restart, voor problemen even mij dmen.
