### ISSUE TITLE
[Bug]: Dood gaan door een explosie geeft je oneindig zwart scherm na een revive

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1779]
### Contact Details

CalRay#1513

### Wat gebeurde er?

We waren een communicatie training aan het doen met de KMAR, toen vloog de auto tegen een explosieve raket. Nadat ik de mensen van de explosie had gerevived o.a. mezelf had ik zwart wit scherm en kon ik niet uitloggen. 

### Wat hoorde er te gebeuren?

Je hoort geen permanente zwarte scherm te hebben na dood te gaan door explosie.

### Wat veroorzaakt de bug?

dood gaan door explosie 

### Frequentie van de bug

1x per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

[CitizenFX_log_2022-12-10T142304.log](https://github.com/Tedeapolis/development/files/10200757/CitizenFX_log_2022-12-10T142304.log)
[CitizenFX_log_2022-12-10T181226.log](https://github.com/Tedeapolis/development/files/10200758/CitizenFX_log_2022-12-10T181226.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Heb je hier toevallig een clip van? Want snap met de omschrijving niet precies wat je bedoelt.

**Comment by CalRayy** [comment]
> Heb je hier toevallig een clip van? Want snap met de omschrijving niet precies wat je bedoelt.

Als het goed is wel, ik ga zometeen even kijken.

**Comment by CalRayy** [comment]
ik heb geen clip ervan helaas.

**Comment by Ljosfari** [comment]
was dit nog gelukt @CalRayy ?
