### ISSUE TITLE
[FEATURE]: Kleur van drugsmelding bij de KMAR aanpassen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1780]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

De leden van de KMAR zijn super tevreden dat ze drugsmeldingen krijgen, alleen de nadeel is dat de cirkel geel is en is het te moeilijk te zien is. (Zie volgende screenshots)
![image](https://user-images.githubusercontent.com/101106299/206991685-5c2202bb-92c4-4043-a223-41504d6e9450.png)
![image](https://user-images.githubusercontent.com/101106299/206991703-25eba545-04bf-4008-83c0-710731443eff.png)
Je moet goed kijken en veel inzoomen, de vraag is als het een andere kleur kan krijgen (Paars) en eventueel een postcode voor het makkelijk terug te vinden op de kaart.

### Wat lost deze feature op?

Makkelijker te zien op de map, en handig.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by KeesdeB** [comment]
@CalRayy Als dit ook wordt gewijzigd voor de politie of kader/bsb rangen dan is rood misschien niet handig omdat dit dezelfde kleur is als een schietmelding (welke de kmar, behalve sommige rangen niet krijgen)

**Comment by CalRayy** [comment]
> @CalRayy Als dit ook wordt gewijzigd voor de politie of kader/bsb rangen dan is rood misschien niet handig omdat dit dezelfde kleur is als een schietmelding (welke de kmar, behalve sommige rangen niet krijgen)

Ik heb het veranderd naar paars, denk dat wel prima is.

**Comment by CorruptSausage** [comment]
Meldingen zijn vanaf nu paars voor kmar, fixed na restart!
