### ISSUE TITLE
[FEATURE]: HEIST starten vanaf 15 politie

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#1781]
### Contact Details

Keesdb#1477

### Beschrijf zo duidelijk mogelijk de feature

Besproken in Staff overleg van gisteren.

De heist moet een enorm risico zijn met een slagingskans van 1/3, op dit moment wordt de Heist gestart op het moment dat er weinig Politie aanwezig (net genoeg) is of op onmogelijke tijdstippen, vooral rond etenstijd. Dit zorgt voor dat de heist vaak wordt afgeraffeld omdat je minimaal zo'n één uur tijd hiervoor moet inrekenen en mensen moeten gaan eten. Laten we even kijken hoe dit bevalt of dat er nog steeds problemen rond etenstijd optreden, voor nu dus vanaf 15+ politie starten.

### Wat lost deze feature op?

Uitgebreide scenario's, geen afgeraffelde scenario's.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin.
