### ISSUE TITLE
Brancard

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1782]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Graag als de mogelijkheid er is om de brancard ook in de handen te laten inspannen.
Net zoals bij de rolstoel.

Want nu schiet de brancard nog wel eens weg als we hebben willen pakken.

### Wat lost deze feature op?

Volgens mij niets verloren.

Zou het iets makkelijker maken

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin na volgende herstart
