### ISSUE TITLE
[FEATURE]: In de ambu meldkamer een aparte kleur geven aan de melding zodra persoon overleden is.

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1783]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Als je bij een melding aan komt is het heel erg irritant als er niemand is dit heb ik heel vaak mee gemaakt en erger me ook een beetje aan. Nu heb ik hier denk ik een oplossing op bedacht, in de meld kamer hebben we nu 2 soorten kleuren staan groen voor behandeld en geel voor open wat nou als we een derde kleur toevoegen zoals rood (lijkt me het beste hiervoor) dat aangeeft wanneer de persoon die de melding heeft gemaakt overleden is zo ga je niet iedere keer naar een zo gehete Ghost melding. 

Misschien is het dan ook mogelijk om overheidsmeldingen een andere kleur te geven dit om het dan nog overzichtelijker te maken

### Wat lost deze feature op?

Dit zou het misschien overzichtelijker maken.
En wij rijden dan niet voor jan doedel naar een plek toe

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Ik ga dit heel even bespreken, aangezien ik denk dat hier wellicht nog wat misbruik van kan komen.

**Comment by Ljosfari** [comment]
is niet mogelijk

**Comment by WilmaWonka1985** [comment]
Oke helaas is niet anders. toch bedankt
