### ISSUE TITLE
[FEATURE]: winterbanden voor overheid

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1784]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

Het is weer koud in de stad en een mooie witte glans maakt het saaie grijze weer mooi
verwarming aan en lampjes in het donker !

maar dit geeft ook lekker veel gladde wegen met zich mee
van hier het verzoek
Winterbanden onder de auto's

- [x] Politie
- [x] ambu
- [x] taxi
- [x] anwb
- [x] kmar
- [x] justitie 
- [x] Hendhaving 

### Wat lost deze feature op?

minder werk voor anwb 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Kan niet voor handhaving, rest van de banen zit het er allemaal in voor volgende restart!
