### ISSUE TITLE
[FEATURE]: Politievoertuigopslag toevoegen bij oud HB

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1785]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een zelfde punt toevoegen als bij het huidige HB waar je politievoertuigen kunt pakken en wegzetten.

### Wat lost deze feature op?

Extra punt waar je bijvoorbeeld een sleepwagen kunt pakken en ook handig voor wanneer er nog arrestanten in het oude HB worden neergezet.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed na restart.
