### ISSUE TITLE
[FEATURE]: /repareer gratis maken op dienstvoertuigen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1786]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Wanneer er te weinig ANWB aanwezig is de /repareer command gratis maken voor enkel dienstvoertuigen van de politie/kmar (en eventueel ook de andere overheidsdiensten). 

### Wat lost deze feature op?

Zorgt ervoor dat wanneer er geen ANWB niet de agenten hoeven te betalen voor de reparatie van hun dienstvoertuig, die normaal gesproken ook gratis gerepareerd wordt door de ANWB. Er zit ook al een cooldown op dus kan dit niet al te vaak gebeuren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Ik ga dit heel even bespreken met de andere developers.

**Comment by niekschoemaker** [comment]
Zit erin
