### ISSUE TITLE
[FEATURE]: Strafbladen in MEOS laten sorteren op datum i.p.v. feitnummer

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#1787]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Strafbladen in MEOS laten sorteren op datum i.p.v. feitnummer.

### Wat lost deze feature op?

Momenteel staan ze gesorteerd op feitnummer en op één of andere manier gaat dit niet altijd goed en krijg je soms onoverzichtelijke MEOS profielen zoals hieronder op de foto te zien is.
![image](https://user-images.githubusercontent.com/93579695/207147971-ede8e5fe-6eb4-4822-a839-bcb135c4026b.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
@niekschoemaker kan jij hier heel even naar kijken?
