### ISSUE TITLE
[FEATURE]: Unmarked voertuigen voor de hoofdofficier rangen.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1788]
### Beschrijf zo duidelijk mogelijk de feature

De hoofdofficier/HRB rangen van de koninklijke marechaussee hebben toegang tot de unmarked voertuigen. 
Het gaat om de volgende rangen:

kmar 45
kmar 50
kmar 60
kmar 70
kmar 71
kmar 72
kmar 73
kmar 74

Voertuig spawncodes:

unmarkeda6
unmarkedaudirs6
unmarkedgolf
unmarkedrange
unmarkedrs3
unmarkedx5m

### Wat lost deze feature op?

De hoofdofficieren mogen sinds kort unmarked rijden deze  moeten alleen nog worden toegevoegd aan de juiste rangen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed na restart.
