### ISSUE TITLE
[FEATURE]: Logo op de kaart 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1789]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

![image](https://user-images.githubusercontent.com/93401910/207417057-b091350b-eac4-4789-91e5-3d779a81eadd.png)
![image](https://user-images.githubusercontent.com/93401910/207417112-b201a62c-1414-4b1c-8023-3af910d64084.png)

Wij willen bij de taxi job graag het Uberpolis logo hebben. Ook willen wij graag het Uberpolis logo op de kaart zien.

![image](https://user-images.githubusercontent.com/93401910/207417076-003ca08f-562f-4478-a2e9-59c36e9bb91d.png)

### Wat lost deze feature op?

ziet er duidelijker uit op de kaart 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Job logo's zijn aangepast, map logo moet ik nog even kijken.

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/212345993-ed6ebf0e-45ab-42b0-8f7c-8641cdffb4a8.png)
Map logo is ook aangepast maar zie je beetje slecht op de map, dit is het beste wat ik hem kan krijgen :(
