### ISSUE TITLE
brancards en bodybags nakijken

### ISSUE THREAD

**Issue by krizz696** [Tedeapolis/development#179]
mogelijkheid om een overleden personen en bodybags op een brancard te gooien en mee te nemen . zodat deze met rp kan doodverklaard worden aan het ziekenhuis
alsook de mogelijkheid om de brancard in de lijkwagen te plaatsen .

**Comment by Willem-Dekker** [comment]
@StrixCoding wat is de prop van de lijkzak

**Comment by Willem-Dekker** [comment]
hebben nu de zelfde handeling as brancards - het zetten er op
