### ISSUE TITLE
[FEATURE]: taxi auto's

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1790]
### Contact Details

Endorsite#0001

### Beschrijf zo duidelijk mogelijk de feature

Wij willen graag een aantal nieuwe auto's toevoegen aan onze Taxi garage. en een aantal veranderingen door voeren 
de tesla is en blijft altijd lastig met off-road en vaak worden collega's er op aan gesproken 

ons idee was dus om de Tesla auto te vervangen met :
Aston Martin DBX
![image](https://user-images.githubusercontent.com/93401910/207418111-f8b4cc01-e962-4d45-8bfe-7ab49de75867.png)

We hebben nu een tijdje nieuwe rangen maar geen nieuwe auto's dus zouden we graag daar voor de volgende veranderingen door voeren 

Rang : vanaf Marketing
op deze manier krijgen marketing en recruiter's ook een auto van de zaak Auto: Mercedes S500
![image](https://user-images.githubusercontent.com/93401910/207418801-c80ef313-d3ad-48e8-b356-463ff001bd20.png)

Rang: Manager 
We hebben nu de Auto: Zentorno als chef auto  deze zouden we graag willen doorschuiven naar manager 
![image](https://user-images.githubusercontent.com/93401910/207423038-603b4a24-3287-4bab-944c-6996f9212c53.png)

Rang: vanaf marketing-chef
we hebben 4 mensen die deze auto kunnen gebruiken  ( marketing-chef en recruiter-chef)
Nieuwe auto: Ferrari Roma
![image](https://user-images.githubusercontent.com/93401910/207423223-0140d815-55b6-427c-a847-4d7cf58e22f3.png)

Rang: Chef (eigenaar)
we hebben maar 3 mensen die chef zijn en dus de auto zullen gebruiken 
Nieuwe auto : Lamborghini Sian 
![image](https://user-images.githubusercontent.com/93401910/207423336-f67a5c06-7b2a-4ef9-a700-b0e448011c1e.png)

hebben jullie andere ideeën hoor ik het graag ik weet namelijk wel dat ik veel vraag

### Wat lost deze feature op?

veel overheid beroepen hebben 10 of meer auto's 
wij hebben er maar 3 met een skin evt kijken of dat mogelijk is met deze modellen ?
zo hebben wij ook meer om uit te kiezen en als mensen promotie hebben hebben ze ook weer wat om op uit te kijken 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed na restart.
