### ISSUE TITLE
[FEATURE]: De Weijck

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1791]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

- [x] Met shift E op de barkrukken kunnnnnnen zitten
- [x] Dj cirkel
- [x] Kleding cirkel : 
![image](https://user-images.githubusercontent.com/97713942/207655597-16340f6b-31f1-43e7-8653-8bf61fc0ade6.png)
- [x] Biljart tafel : 
![image](https://user-images.githubusercontent.com/97713942/207655514-7ef36b83-b8ef-4d64-881d-5bc7a731af94.png)

- [x] Nog wat kleine interieur dingen, staan in de 3d model discord :) 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AntonMTDA** [comment]
interieur dingen zijn gefixed enkel nog de plugins van de biljard tafel de dj cirkel en de barkrukken die gefixed moeten worden

**Comment by AntonMTDA** [comment]
biljart tafel plugin word hem helaas niet!

**Comment by AntonMTDA** [comment]
stoelen kunnen helaas niet met shift+e van alles geprobeerd maar werkt helaas niet!

De rest is allemaal gefixed
