### ISSUE TITLE
Constant /mr doen in CCF MLO[Bug]: 

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1792]
### Contact Details

Schmutz#8587

### Wat gebeurde er?

wij hebben best vaak dat je moet /mr als je binnekomt, kamer veranderd of verdieping etc. is dat altijd zo in een MLO, bij ons lijkt het extreem dus je loopt cafe binnen met je dat doen, loopt door de deur moet je dat doen ander hoort niemand je. ook als je naar boven loopt etc..

### Wat hoorde er te gebeuren?

niks, dat je dus al pratend de deur open kan doen en door kan lopen etc....

### Wat veroorzaakt de bug?

I dont know 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

gesprek met oesewoes

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Hiervoor ben ik een betrouwbare repro nodig die 100% werkt.
Dit is namelijk al een issue die er een eeuwigheid in zit.
