### ISSUE TITLE
[FEATURE]: Dienstvoertuigen namen aanpassen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1795]
### Contact Details

James Bond#1033

### Beschrijf zo duidelijk mogelijk de feature

Zoals je bij de normale garage een voertuig kan hernoemen, willen we dat ook graag bij de kmar garage. 

### Wat lost deze feature op?

Door deze feature kan je voertuig goed uit elkaar halen die nodig hebt voor bepaalde diensten. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Dit lijkt me in mijn ogen totaal overbodig, we gaan hier dus ook niet aan werken.
