### ISSUE TITLE
[FEATURE]: Exotica blip veranderen 

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1796]
### Beschrijf zo duidelijk mogelijk de feature

De blip van exotica is momenteel een schoen, ik heb  met de eigenaren gepraat over exoitca en hun zouden graag de blip zien veranderen naar een custom logo. Dit logo is custom gemaakt. Jet heeft geen haast maar zou wel leuk zijn voordat ze open gaan! 

Logo:
![ExoticaLogoTDA](https://user-images.githubusercontent.com/103584419/208179691-9956076d-fb34-458a-9765-e282c18790ed.png)

### Wat lost deze feature op?

Dat mensen makkelijker exotica kunnen vinden, dit is erg handig voor bijvoorbeeld de feesten die zij gaan geven daar! 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/212343514-deab7595-da25-4cc6-b7d3-a6e5ddbe59cd.png)
Logo is nogal klein op de map maar beter dan de zwarte laars I guess

**Comment by JohanDewus** [comment]
Top dankjewel!

**Comment by JohanDewus** [comment]
Hey Morgan! ik krijg net te horen dat hij mooier word als je hem op zwart of wit zet. Voor ons maakt dit ook niet uit, als het logo maar zichtbaar is. Ook is het altijd beter dan een zwarte schoen @Attomn 👍 THX Alvast
