### ISSUE TITLE
[FEATURE]: eup handhavings vest texture aanpassen

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1797]
### Contact Details

Devv#4532

### Beschrijf zo duidelijk mogelijk de feature

Zou de admin /eup handhaving texture van het dames kogelwerend vest aangepast kunnen worden? 

### Wat lost deze feature op?

zo kan je volledig handhaving doen
![task_diff_008_f_uni TEST](https://user-images.githubusercontent.com/79802852/208250296-4878faf1-da35-463b-8816-4d5cabc3185d.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Zou je wellicht even kunnen kijken hoever deze issue overeenkomt met #1776 en #1760, aangezien hier beide iets in voorkomt over kleding.
