### ISSUE TITLE
[Bug]: Als je een auto leent met grantkeys en appartement in gaat en eruit dan despawned die

### ISSUE THREAD

**Issue by NsGames070** [Tedeapolis/development#1799]
### Contact Details

NsGames07#2712

### Wat gebeurde er?

Je komt je appartement/loods/lift uit dan wil je je auto open doen van je vriend waar van je de grantkey hebt gekregen vervolgens moet de auto respawnen maar het is niet je eigen auto en het is echt wanneer de persoon van wie de auto is niet in de buurt is dat hij despawned voor helemaal geen reden.

### Wat hoorde er te gebeuren?

Dat de auto normaal ging en niet hoefde te respawnen

### Wat veroorzaakt de bug?

Dat je als je een auto leent met grantkey dat je als je appartement of loods of een lift naar beneden komt niet je auto open kan doen en dan je auto moet respawnen en dat hij dan niet meer terug spawned. En soms heb ik het zelfs ook bij me eigen auto's

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

https://medal.tv/games/gta-v/clips/Mv6vXHACbAaiH/d1337515ZEV8?invite=cr-MSxIRVYsMzI2NjU1OTIs

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Is niet te fixen.
