### ISSUE TITLE
handeling lijkwagen van de ambu 

### ISSUE THREAD

**Issue by krizz696** [Tedeapolis/development#180]
voertuig rolt om tegen 30 per uur een bocht nemen

**Comment by krizz696** [comment]
alsook bekijken wat er hier mee scheelt , als het voertuig rolt zou de deur er normaal uit getrapt worden als je uitstapt . maar in het geval lijkwagen duplicate hij de hele caroserie 

 https://gyazo.com/c09e9e44cb0b96dc3bcbb1f930c81e7a

**Comment by Willem-Dekker** [comment]
ik denk dat deze uit de server gaat model trekt op niks en hij is glitchy af
