### ISSUE TITLE
[Bug]: FMJ Ammo in M1911 met FMJ laden

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#1800]
### Contact Details

Tom974#9783

### Wat gebeurde er?

Wanneer je een m1911 met FMJ tuned, en vervolgens een FMJ clip in dit wapen probeert te stoppen, krijg je de melding dat dit niet kan en komen er ook geen kogels bij. Zie ook onderstaande screenshot
![image](https://user-images.githubusercontent.com/55812394/208271101-edb6b069-833f-4a9f-a16a-fffa1bff6e01.png)

### Wat hoorde er te gebeuren?

Dat je een FMJ clip in je FMJ pistol kunt "laden"

### Wat veroorzaakt de bug?

Hierboven al uitgelegd

### Frequentie van de bug

1x per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Tom974, bedankt voor het aanmaken van de github issue. Ik krijg dit op geen enkele manier gereplicate. Zou je logbestanden kunnen sturen zodat er iets beter aan gewerkt kan worden?

**Comment by Tom974** [comment]
Krijg net te horen dat hij eerst nog hollowpoint had getuned 😅 

Dus hollowpoint tunen -> FMJ tunen -> FMJ clip inladen (en dan heb je de bug)

**Comment by Tom974** [comment]
Fixed na herstart.
