### ISSUE TITLE
[FEATURE]: Extra opties facturen systeem

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1801]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Op het moment hebben wij een facturen systeem waar wij facturen kunnen sturen voor hapjes & drankjes. Alleen is het zo dat wij vaak Entree gaan vragen bij feesten. Wij zouden daarom graag de optie er bij willen om mensen een factuur te kunnen sturen voor entree, dit zijn de opties die wij er graag bij zouden willen hebben

Exotica Entree: 500
Exotica Entree: 1000
Exotica Entree: 2500
Exotica Entree: 5000
Exotica Entree: 10000

Ook zouden wij graag de feature hebben om zelf te bepalen wat het bedrag word van een factuur die wij sturen naar een persoon. Dit voor als wij bijvoorbeeld het pand een keer verhuren. Het idee is dan dat als wij ons F6 menu open wij ook een optie krijgen om zelf een bedrag/reden in te vullen van een factuur. Op deze manier komt het geld direct in de pot. Wij kunnen zelf namelijk geen geld in de pot stoppen omdat onze rang op Second-Job staat. 

### Wat lost deze feature op?

- Lange wachtrijen voor de deur bij Exotica.
- Dat het geld meteen in de pot komt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin.
