### ISSUE TITLE
[FEATURE]: Rangen Aanpassing Exotica

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1802]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Bij Exotica hebben we verschillende rangen alleen kunnen ze niet allemaal wat ze horen te kunnen. Hier zijn de features die we graag zouden zien per rang.

Mogelijkheden per rang: 

- [x] 0 Exotica - Trainee:
Toegang tot alle deuren, toegang tot de koelkast

- [x] 500 (**NAME CHANGE**) Exotica - Barkeeper
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes & het sturen van facturen

- [x] 550 (**NIEUWE RANG**) Exotica - DJ
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes & het sturen van facturen

- [x] 600 Exotica - Performer
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes & het sturen van facturen

- [x] 700 Exotica - Portier
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes, het sturen van facturen & de mogelijkheid mensen te tackelen

- [x] 800 Exotica - Chauffeur
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes, het sturen van facturen & de mogelijkheid een limousine te pakken (zelfde die Complex heeft)

- [x] 850 (**NIEUWE RANG**) Exotica - Leiding
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes, het sturen van facturen, een limousine pakken, kunnen tackelen & toegang tot de werknemers lijst

- [x] 900 (**NAME CHANGE**) Exotica - Onderbaas
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes, het sturen van facturen, een limousine pakken, kunnen tackelen, toegang tot de werknemers lijst & toegang tot de bedrijfs pot.

- [x] 1000 (**NAME CHANGE**) Exotica - Eigenaar 
Toegang tot alle deuren, toegang tot de koelkast, het mixen van drankjes, het sturen van facturen, een limousine pakken, kunnen tackelen, toegang tot de werknemers lijst, toegang tot de bedrijfs pot & het kunnen aanpassen van het loon.

### Wat lost deze feature op?

Dat alle rangen weer werken naar behoren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
er moet ook support voor de 2e job komen, baas menu, kluis etc

**Comment by ExoticaTDA** [comment]
> er moet ook support voor de 2e job komen, baas menu, kluis etc

2e job support zit er nu in, nu moeten alleen de rangen nog gefixt worden

**Comment by Tom974** [comment]
Zit erin na de herstart.
