### ISSUE TITLE
[FEATURE]: Gevangenis + DJI

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1803]
### Beschrijf zo duidelijk mogelijk de feature

Dingen die voor de DJI toegevoegt worden worden: 

- [x] - Rangen DJI.

- [x] - Indienst cirkel.

- [x] - Save zone verwijderen.

- [ ] - Spawnplek van de gevangenen veranderen.

- [x] - Bossmenu toevoegen.

- [x] -  Extra camera's in de gevangenis.

- [x] - Dames kleding voor de DJI

- [ ] - Activiteiten voor in de gevangenis:

- [ ] - Tennisbaan. _(Edit: Wordt voor nu overgeslagen - Tom)_

- [x] - Boks zak toevoegen.

- [ ] - Basketbal (Als het kan). _(Edit: Wordt voor nu overgeslagen - Tom)_

- [ ] - Extra Jobs in de gevangenis (criminelen en de DJI):

- Wasruimte kijken of daar een mogelijkheid is om te werken ( Emote strijken, was in de wasmachine etc )
- Kantinedienst draaien het zelf bevoorraden van eten/drinken in de gevangenis, tafels schoonmaken, keuken schoonmaken.
- Cellen schoonmaken.
- Buiten de elektriciteit kunnen doen.
- Was ophalen / wegbrengen / wassen / wegbrengen naar de opslag.
Elk succesvolle uitvoering van je shift is 0.30 seconden per gewerkte minuut vermindering.

- [ ] Items in de gevangenis:

Bepaalde items kunnen krijgen in de gevangenis zodat het ook motiverend is om te werken in de gevangenis omdat je een ‘’uitweg’’ kunt krijgen.
- 3% kans om een Lockpick te krijgen uit de job die je uitvoert.( Je hebt een lockpick gevonden tussen de was, of in de cel wat je hebt schoongemaakt) De lockpick zorgt ervoor dat je EEN DEUR kan openen. De deur gaat weer dicht na 15 minuten. 
- 0,5% kans om een mesje te vinden, extreem rare. Dit zorgt voor ook gevangenis RP en ook voor de DJI regelmatig controleren. ( Zogenaamde smokkel )

- [x] Dienstnummers DJI rang

- [x] Salaris rangsysteem

- [x] Geld systeem, geld pot

- [x] Wanneer ontvangt de DJI vergoeding ingavangplaatsen

- [x] Sollicitaties

- [x] Sleutels voor de rechtzaal 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
mezelf even toegewezen voor de kleding

**Comment by DevvTDA** [comment]
Als ik het goed begrijp is er nog geen job voor DJI ?
Ook staat er dubbel kleding dames in betreft dit beide DJI kleding of ook gevangenis kleding?

**Comment by Ljosfari** [comment]
Ola @DevvTDA , als je mij tagged krijg ik ook een mailtje btw :)

Dames kleding staat er inderdaad dubbel in. Excuus.

Er bestaat ook momenteel nog geen job voor. Misschien kan dit tijdelijk bij de KMar erbij gezet worden ? De heren dji kleding zit er al wel in. Onder gemeente raad of KMar dacht ik.

**Comment by CalRayy** [comment]
Extra camera's zijn toegevoegd (werkende)

**Comment by Streamcentralrulez** [comment]
Rangen DJI aparte issue gemaakt #1982
