### ISSUE TITLE
[FEATURE]: Nieuwe flitspalen

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1804]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag 2 nieuwe flitspalen willen hebben in de stad.

Hier zijn de locaties (Het zijn er 2 bij alkaar aangezien het een groot kruispunt is en ik niet de range weet)
Het is de bedoeling dat deze flitspalen dan op 80km/u komen te staan.

Locatie1: x: -13,17 y: -1617.84 z: 29.26 h: 47.77
https://prnt.sc/YTlfbdRL8xcU

Locatie2: x: -38.19 y: -1597.04 z: 29.27 h: 227.71
https://prnt.sc/XlKV_-eT3Lih

### Wat lost deze feature op?

Er worden bij dat pand suppranos tacos elke dag veel mesen overreden, omdat mensen daar overdreven hard langs rijden en daar nogal vaak ongelukken gebeurd waardoor mensen die daar staan dood gaan.

Door die flitspalen denk ik dat mensen in ieder geval er al zachter langs komen rijden, zodat er in iedergeval daar minder gezijk is.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed
