### ISSUE TITLE
[BUG]: Glitch in CCF MLO

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1806]
### Contact Details

Schmutz#8587

### Wat gebeurde er?

als je voornamelijk in de keuken loopt of soms zelfs restaurant verdwijnen mensen in beeld en komen ze terug , zie video

https://user-images.githubusercontent.com/120605155/208860233-9d0da98d-280f-4f85-b834-3d14bafa9ddb.mp4

### Wat hoorde er te gebeuren?

geen glitch

### Wat veroorzaakt de bug?

zie video

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Donnycolombo** [comment]
@Ljosfari @CorruptSausage  is hier misschien nog iets aan te doen ? same as het MR achter elke deur weer opnieuw te doen ?

**Comment by Tom974** [comment]
Is dit nogsteeds een ding @Donnycolombo ? Kreeg het zelf niet voor elkaar namelijk

**Comment by Tom974** [comment]
Gesloten ivm geen reactie.
