### ISSUE TITLE
[FEATURE]: ''Handen in vest'' emote

### ISSUE THREAD

**Issue by CoffeeSipper** [Tedeapolis/development#1807]
### Contact Details

CoffeeSipper#8888

### Beschrijf zo duidelijk mogelijk de feature

Emote voor politie/kmar dat je je handen in je vest stopt, zie foto:

![image](https://user-images.githubusercontent.com/96985840/208909025-4e537c0e-e897-4fdb-ac04-c05d9749927a.png)

Niet de beste kwaliteit, maar je snapt het idee wel, toch? :)

### Wat lost deze feature op?

Niks, brengt wellicht wat meer realisme naar voren als je het zo ziet.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Als je de emote weet zou dit kunnen, maar ik zou zelf niet weten welke emote dit is.

**Comment by CoffeeSipper** [comment]
> Als je de emote weet zou dit kunnen, maar ik zou zelf niet weten welke emote dit is.

Dacht dat ie misschien gemaakt kan worden. Zo niet, dan niet..

**Comment by CorruptSausage** [comment]
We gaan deze helaas niet zelf maken, als je deze emote hebt kun je de issue even opnieuw openen.
