### ISSUE TITLE
[FEATURE]: JUSTITIE

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#1808]
### Contact Details

undisclosed#0001

### Beschrijf zo duidelijk mogelijk de feature

Bij justitie missen wij nog een aantal dingen omdat wij (zonder weet) nog geen toegang hadden tot deze github.
We hopen dat de informatie hieronder voldoende is en indien niet kan er contact op worden genomen :)

- [x] ### - Kledingcirkel 

 Er is op gemeentehuis nog geen kledingcirkel en met het rechtzakenproject die in de maak is samen met de DJI (https://github.com/Tedeapolis/development/issues/1803)
is het van belang dat de advocaten, rechters en/of OVJ zich kunnen omkleden voor/na een zaak.
Deze zouden we graag willen op deze coords. 
X: -515.41 Y: -182.04 Z: 38.22 H: 269.08

- [x] ### - Rechter rol
Voor het rechtszakenproject zal er ook een rechter rol toegevoegd moeten worden, omdat de rechter een 3e partij is en dus los staat van de advocatuur, verdediging en de aanklagers.
De rechters mogen dan ook geen zaken meer lopen ivm hun objecitiviteit. 
dit houdt dus ook in hun dat hun salaris voor de pro-deo zaken en prive cliënten volledig wegvalt. 

Salaris in dienst: 1100 in dienst
Salaris uit dienst: 1000 uit dienst

- [x] ### - Safezone rondom gemeentehuis
Omdat criminelen ook de kans moeten krijgen iemand te kunnen uitbreken tijdens/voor/na de rechtzaak moet de safezone bij het gemeentehuis verkleind worden omdat er anders geen wapens gebruikt kunnen worden.
Dan is het natuurlijk zo dat de safezone er staat voor nieuwe spelers maar willen we graag dat de safezone verkleind wordt naar enkel het pleintje en zal derest dus geen safezone meer zijn.

### Wat lost deze feature op?

Een kledingcirkel op gemeentehuis
Een rechter binnen Tedeapolis
Preciezere safezeone rondom gemeentehuis

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/212362038-b8cb132b-4e6f-4f1c-afc3-cd203c97fa1a.png)
Kledingcirkel is toegevoegd!

**Comment by Attomn** [comment]
Safezone ook, enkel nog de rechter rol.

**Comment by Attomn** [comment]
extra rol is ook toegevoegd joejoe doe de groetjes aan Loena de poena
