### ISSUE TITLE
[FEATURE]: dj crikel op 6034 

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1809]
### Beschrijf zo duidelijk mogelijk de feature

De DJ cirkel van de Outlaws staat momenteel op de gemeente raad rang. 
Deze graag op de ondernemers rang zettten

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Is gefixt, Anton had een kleine oepsie met de cirkels gehad. Rank staat op ondernemer. Enkel even wachten op een bug fix van Niek voor xSound!
