### ISSUE TITLE
[FEATURE]: Loodsen -Burgerraad

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1810]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Loods locaties nakijken, de 'kut' loacties eruit halen en nieuwe toevoegen.

Minder loods locaties in douane en risico gebieden. 

Dus even alle loods locaties bekijken en veel weghalen en toevoegen.

aka groepsporjectje voor onze criminele staffleden. 

Laat mij even weten als je wilt helpen :)

### Wat lost deze feature op?

Powergamen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by LouisTDA** [comment]
Dit is een zeer goed idee, want er zijn veels te veel locaties in douanegebied niet eens een beetje verstopt.

**Comment by Toro-Carri** [comment]
Ben geen staff maar wil best helpen laat maar weten :)
