### ISSUE TITLE
[Bug]: Niet in een voertuig kunnen stappen wanneer het voertuig uit het water is gesleept.

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1811]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als een verdachte in het water rijdt met zijn voertuig, en hij wordt met een sleepwagen uit het water getrokken kan je niet in het voertuig. Waardoor je een voertuig soms niet in beslag kan nemen alleen met een bepaalde glitch met de sleepwagen, vandaar dat ik deze github maak. 

### Wat hoorde er te gebeuren?

je hoort gewoon erin te kunnen stappen als je hem uit het water haalt met een sleepwagen. 

### Wat veroorzaakt de bug?

Het water veroorzaakt de bug, dus ik zal even uitleggen hoe je deze bug creëert.
1. Je rijdt met een random voertuig in het water.
2. Je pakt een sleepwagen van de politie of KMAR
3. Je takelt het voertuig die in het water was
4. Je brengt het voertuig op de sleepwagen naar politie HB om hem in beslag te nemen
5. Je laat het voertuig vallen bij de rode cirkel voor in beslag te nemen
6. Nu kan je niet meer in het voertuig die in het water belandt is, waardoor je het voertuig niet in beslag kunt nemen (alleen met een glitch met de sleepwagen)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by jaim1114** [comment]
Ook als de anwb het voertuig repareert en als je relogged blijft deze bug bestaan.

**Comment by TheKevNL** [comment]
> Ook als de anwb het voertuig repareert en als je relogged blijft deze bug bestaan.

Bij de ANWB inderdaad ook altijd dit probleem, als wij het voertuig 2x repareren kan je vaak wel weer instappen.

**Comment by niekschoemaker** [comment]
Is mogelijk na volgende restart geefixed, not sure.

**Comment by niekschoemaker** [comment]
Heb het nog ff verder getest, en GTA heeft gewoon complete scheit aan SetVehicleUndriveable, dus kan dat niet aanpassen for some reason, alleen volledig repareren werkt daarvoor, dus gewoon anwb bellen.
