### ISSUE TITLE
[FEATURE]: Loskoppelen van de pot

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1812]
### Contact Details

dead123x5#0001

## ESX_unicorn
- [x] Winkeltjes loskoppelen van de pot.
- [x] Facures uit zetten.

Dit is voor niek.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin
