### ISSUE TITLE
[Bug]: setjob

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1813]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

/setjob (id) offtaxi 1000

werkt niet meer sinds ??

![image](https://user-images.githubusercontent.com/93401910/209866422-e8d6c01e-c9b7-4745-a892-531adf95285c.png)

krijg te zien dat het niet meer mag dit gebruiken we na promoties om mensen uit dienst te zetten en om mensen die bvb opgepakt zijn of niet reageren uit dienst te zetten 

### Wat hoorde er te gebeuren?

dat je mensen uitdienst kan zetten maar dat werkt niet meer 

### Wat veroorzaakt de bug?

geen rechten ? of foutje ? 

### Frequentie van de bug

1x per week

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

geen log maar foto 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Niet getest maar zou gefixed moeten zijn na restart, anders mij ff taggen in reactie aub.

**Comment by TedeaTaxi** [comment]
![image](https://user-images.githubusercontent.com/93401910/210281217-30e6f4bd-8ab0-4637-8f62-830618ec4412.png)
nog niet

**Comment by CorruptSausage** [comment]
Geen reactie, zal vast gefixt zijn.
