### ISSUE TITLE
[FEATURE]: Wapen stok politie/Kmar

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1814]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Suggestie: De wapenstok nerven.
de wapenstok van de politie is momenteel 1 hit en dan ben je bewusteloos (KO). Ik vind dit persoonlijk iets te overpowered. dit kan je dus vrijwel alleen nog kantelen met slag of steekwapens. hierdoor zijn agenten geen juggernauts meer met de wapenstok en is er evt ruimte voor meer rp.
Voordelen suggestie:
Meer roleplay en ruimte voor de wapenstok, kijken hoe het gedrag zich vormt hierdoor. + irl ben je ook niet met 1 stomp vd wapenstok buiten bewustzijn.
Eventuele nadelen
mensen gaan evt vaker de wapenstok negeren of kloten agenten neerslaan.

Hoe zie jij dit voor je in de stad? Wat zal deze aanpassing verbeteren?
meer mogelijkheden in rp en minder op.

### Wat lost deze feature op?

Ik ben niet van de politie dus dat weet ik eigelijk niet. Ik heb hem er gewoon even ingezet zoals er is uitgelegt

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ik heb nu dezelfde health check als de normale knockout met unarmed erop gezet, dus onder de 150 HP wordt je knockout geslagen.

Dus als je full HP bent zou het 2 hits moeten zijn, en anders 1 hit.

**Comment by WilmaWonka1985** [comment]
Dan ga ik dat door geven thnxs
