### ISSUE TITLE
[FEATURE]: Koraal vissen

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1815]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

https://fivem-mods.net/shop/diving-job-for-esx/

Maar er staan er echt nog meerdere op
Is nu ook nog promotie op zie ik
8 € indeplaats 28
Als je wilt kan hem ook betalen, maakt me niet uit

ESB | Don Sander
Tijd voor een nieuw iets in tda lijkt me 

Suggestie: 
Koraal duiken ( is een script voor die ik heb ) is een illegale activiteit, in deze script veranderd de locatie als hij leeg gehaald is. Paleto bay sandy overal rondom de stad zeg maar in het water. Het is een illegale job dus kmar of politie of andere instanties kunnen hier op handelen, ik zou het niet te veel laten verdienen, ( well wat meer dan bv ramenwassen ) het is en blijft een illegaal iets, en natuurlijk een groot risico. Denk dat het in deze stad well leuk is met zoveel mensen. Veel transport ook dus veel roleplay.. zou de verkoop locatie ergens goed verstoppen. Zo dat er veel risico blijft en in gehandeld wordt

Voordeel:
Eens iets nieuw in de onderwereld, momenteel kan je op het land enkel maar drugs, en heisten doen al je in de criminele wereld zit. Denk dat hier heel veel roleplay kan uitkomen als mensen ver goed aanpakken.

Nadeel:
Well goed kijken qua prijzen, want je kan deze job ook doen zonder politie ( wat hier niet zoveel uitmaakt ) want je hebt altijd well criminelen die je kunnen rippen.

Bestandje of link: 
Ik heb deze script all liggen.. of kan ook een linkje sturen 

Groetjes don,  en fijne feestdagen!   (bewerkt)

### Wat lost deze feature op?

Ik weet niet of deze hier moet. Zo niet laat het me even weten waar ik hem dan moet zetten a.u.b

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Vind het persoonlijk een beetje teveel op het huidige duiker / vissen lijken.
