### ISSUE TITLE
[FEATURE]: Rang logo

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1816]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag een logo krijgen bij de neiuwe rang van R3D (Rang heet: red)

Ik zou graag dit logo daar willen hebben;
https://i.imgur.com/3PVxmSL.png

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin
