### ISSUE TITLE
[FEATURE]: ANWB aanpassingen? 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#1817]
### Contact Details

DeStefanoKiller#4442

### Beschrijf zo duidelijk mogelijk de feature

- [x] Rang: Directeur toegang geven tot /setjob (off)mechanic 0 t/m 110

- [x] 5 minuten timer op het pakken van een radio uit de ANWB shop.

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Timer is toegevoegd

**Comment by Tom974** [comment]
Hey @DeStefanoKiller, 

De aanpassing omtrent het /setjob is ondertussen doorgevoerd, deze zit dus ook al in de main server. 

Mocht het toch nog niet naar behoren werken, gelieve deze issue opnieuw te openen :)
