### ISSUE TITLE
[FEATURE]: Garage plaatsing

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1818]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag een (Privé) garage krijgen, waar je een auto kan inzetten en dat andere mensen deze er dan ook uit kunnen pakken. (Voorbeeld is hiervan de Landandsea garage.) Enkel bij deze is het de bedoeling om het te koppelen aan de R3D rang (red), zodat enkel de mensen met deze rang de voertuigen eruit kunnen pakken.

- [ ] Groene cirkel: x: -770.65 y: -225.86 z: 37.75 h: 122.14 [Foto van cords/ locatie: https://prnt.sc/B4enL7gOHL12]
- [ ] Rode cirkel: x: -736.93 y: -271.05 z: 36.95 h: 25.85 [Foto van cords/ locatie: https://prnt.sc/zvyj3iykon3J]
- [ ] Spawn locatie: x: -736.93 y: -271.05 z: 36.95 h: 25.85 (Zefde als de rode cirkel) [Foto van cords/ locatie: https://prnt.sc/zvyj3iykon3J]

### Wat lost deze feature op?

Dit zodat mensen bij bepaalde bedrijven voertuigen kunnen vrijstellen voor andere medewerkers, waarmee de RP verbeterd kan worden en ze meer kunnen doen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
https://github.com/Tedeapolis/development/issues/1497

Is al eerder afgewezen en hier hebben we in DM toen nog over gesproken op 07-06-2022

**Comment by AntonMTDA** [comment]
Hoi @Rowdeeee, wat is er precies verkeerd aan de huidige cirkel die achter het pand staat
