### ISSUE TITLE
[FEATURE]: Cirkel plaatsing (Rangen/peroneel)

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1819]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Hey, ik zou graag nog een rang/personeels cirkel willen hebben als dit mogelijk is. Dit gaat over de rang R3D (red) De bedoeling is dat de rang CEO en Manager deze mogen gebruiken.

Dit graag op de volgende locatie:
(Locatie van de Rang/personeel beheer cirkel mag op:)
**(Deze had niek al zo naar mij toe gestuurd, dus ik weet niet of hij de meter er al heeft afgehaald of niet)**
vector3(-810.04, -208.39, 37.13)
heading: 207.63
https://prnt.sc/-6opaUnUXw0d

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Rowdeeee,

Bedankt voor het aanmaken van de GitHub issue.

> (Deze had niek al zo naar mij toe gestuurd, dus ik weet niet of hij de meter er al heeft afgehaald of niet)

Ik neem aan van bovenstaande bericht dat hier al toestemming voor is?

De meter eraf is niet perse nodig wij testen altijd na dus dan zien we vanzelf of de meter er al af is of niet😄

**Comment by Rowdeeee** [comment]
Hey @Chang-nl,

In prenciepe is de rang en al is er al. Enkel is de boss cirkel er nog niet. Ik had inderdaad al met niek besproken dat deze op die locatie zou moeten komen alleen dat was er nog niet van gekomen. (Dus vandaar deze github)

**Comment by Rowdeeee** [comment]
Hey, 

Ik zie dat er nu een baas menu in zit, maar hij zit op de verkeerde plek. 
Hij staat namelijk op een locatie waar in de toekomst een loten cirkel moet komen.

https://prnt.sc/KnvD4FYxsmSk
Daar staat hij nu op;
Locatie van Kras - loten cirkel
vector3(-781.44, -209.30, 37.15)
heading: 171.73
https://prnt.sc/muf7L4dfYFcb

Maar hij moet op;
Locatie van de Rang/personeel beheer cirkel mag op:
vector3(-810.04, -208.39, 37.13)
heading: 207.63
https://prnt.sc/-6opaUnUXw0d

Ik hoop dat je hier iets mee kan!

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/212048026-2b829dc7-debc-421d-86a0-a8293895ff54.png)

Gefixt
