### ISSUE TITLE
/giveflightlicense

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#182]
Goedemorgen!

Ik krijg zojuist in een ticket voor een vliegbrevet te horen dat /giveflightlicense kapot is! Ik heb bijna geen info en kan momenteel niet meer info geven omdat ik in de les zit :3

**Comment by Attomn** [comment]
Ik zal dit zo als ik tijd heb eventjes ingame testen met f8 menu open :)

**Comment by Willem-Dekker** [comment]
heb je hier logs

**Comment by niekschoemaker** [comment]
Het is /giveflylicense, mag hopen dat dat niet het probleem is @Attomn

**Comment by Attomn** [comment]
Nee, dat is niet het probleem, ik heb ook niet echt logs hiervan, ik dacht dat @Willem-Dekker hier meer van wist, ik heb Henk het nu even overnieuw laten proberen!

**Comment by Willem-Dekker** [comment]
ik weet van niks hier over

**Comment by Willem-Dekker** [comment]
het gaat mis op regel 209 in de server van de plugin

**Comment by Willem-Dekker** [comment]
fixed zijn morgen werkend weer
