### ISSUE TITLE
[FEATURE]: In en uitdienst

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1820]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Als het mogelijk is zou ik graag een in en uitdienst mogelijkheid willen krijgen bij R3D (red).
Dit omdat er een klein f6 menutje in zit voor een duscotheek om dranken te mixen, maar dit kan in de knoei komen met iemand die een overheids baan heeft waar ook een f6 menu in zit. 
Er gebeurd dan nemelijk dat ze dan soms het verkeerde f6 menu voor zich krijgen en de andere dan niet kunnen gebruiken.

Locatie van in/uitdienst cirkel:
Coords: x: -800.45 y: -199.17 z: 37.15 h: 220.13
Foto van locatie: https://prnt.sc/6svEeKzY9-2k

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Rowdeeee, 

Bedankt voor het aanmaken van de github issue. 

Als ik het goed begrijp is het momenteel mocht je een overheidsbaan hebben dat de een f6 menu's overlappen?

Staat de job red op de 2e baan slot of 1ste slot of kan dit op beide momenteel?

Alvast bedankt!

**Comment by Rowdeeee** [comment]
Hey @Chang-nl,

Ze overlappen elkaar niet echt, hij pakt eigenlijk gewoon het f6 menu van de 2e job.

Hier is een voorbeeld dat je kan zien wat er gebeurd. In dit geval is het met AMBU job en complex (unicorn) job.
https://streamable.com/xj0tj3

**Comment by Rowdeeee** [comment]
Deze was al gefixed dus ik sluit deze zelf wel :)
