### ISSUE TITLE
[FEATURE]: De R3D Complex opdruk van de Exotica voorraadbus afhalen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1822]
### Contact Details

Dyon#9999

### Voertuig model

mule2

### Omschrijf de bug

Als wij bij Exotica onze voorraad bus willen pakken krijgen wij een bus met de opdruk van R3D Complex. Zover ik weet is er ook een livery van Exotica zelf en wij waren benieuwd of we die weer op onze bus kunnen krijgen.

Als deze niet meer te vinden is zouden we hem ook zelf kunnen maken.

### Normaal gedrag

Dat als wij onze bus pakken hij spawned met een Exotica livery en niet met die van R3D Complex.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by musician1011** [comment]
Kan jij eventueel een eigen versie ervan maken? Dan kijk ik vanaf daar weer verder. Lijkt me sowieso handig dat er eentje is die 100% jullie ding is.

**Comment by ExoticaTDA** [comment]
Gaan we mee aan de gang!

**Comment by ExoticaTDA** [comment]
> Kan jij eventueel een eigen versie ervan maken? Dan kijk ik vanaf daar weer verder. Lijkt me sowieso handig dat er eentje is die 100% jullie ding is.

Heb jij een basis texture/model voor me?

**Comment by Attomn** [comment]
> Kan jij eventueel een eigen versie ervan maken? Dan kijk ik vanaf daar weer verder. Lijkt me sowieso handig dat er eentje is die 100% jullie ding is.

Er is al een kant en klare livery van exotica, als ik zo in de YTD van het model kijk, kan ik ook geen R3D livery vinden.

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/212326184-738b55b7-98dd-4c41-aac4-d5c35d333d38.png)
Heb het gefixt!
