### ISSUE TITLE
[FEATURE]: Sloten veranderen.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1823]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

R3D bedrijven hebben sinds kort een eigen rang. Enkel staan de sloten van de cardealer nog op de entrepreneur job.

- [ ] Sloten in de Cardealer op postcode 7044 veranderen naar de R3D Rang (red) (Deze staan nu dus nog op de entrepreneur job)

Dit zijn de deuren;
- [ ] Voordeur: https://prnt.sc/h6tbRCWBOXZB
- [ ] Kantoor deur: https://prnt.sc/gzAayRENJY01
- [ ] Kantine deur: https://prnt.sc/vX1Dhm2aQ-pv
- [ ] Garagedeur Links: https://prnt.sc/GM1mLg3njSgO
- [ ] Garagedeur Rechts: https://prnt.sc/ZI8_WULg_m3Y

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Sloten zijn aangepast!
