### ISSUE TITLE
[Bug]: Overheids voertuig tanken bug?

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1824]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik zat rustig te tanken en mijn tank reset zichzelf bij 50L naar de hoeveelheid waar ik startte. Ik herstart het tanken, maar zelf dat hielp niet.  https://www.youtube.com/watch?v=J3BowJZR3gE

### Wat hoorde er te gebeuren?

Mijn tank liter hoort niet te resetten. 

### Wat veroorzaakt de bug?

geen idee, er staat niets in F8, zie video https://www.youtube.com/watch?v=J3BowJZR3gE

### Frequentie van de bug

1x per week

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Mikajac** [comment]
Zelf heb ik dit ook wel eens meegemaakt, meestal is de oorzaak hiervan een verandering in het voertuig. Oftewel: iemand die instapt, uitstapt, /shuff doet etc. Hierna blijft het tanken oneindig doorgaan en resetten, maar blijf je wel doorbetalen.

**Comment by Ljosfari** [comment]
er zit nog een een passasier in het voertuig en je hebt je zwaailicht aan, dat verorzaakt de issue
