### ISSUE TITLE
[Bug]: zwaailichten bug touran

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1825]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je niet het eigenaar bent van een touran en je doet met Q de zwaailichten aan, gaan ze niet aan alleen de eigenaar van het voertuig zelf. Dit heb ik paar keer meegemaakt toen ik in dienst was en mocht rijden met de touran toen mijn collega in zijn hoofd was. Gisteren gebeurde het ook toevallig met een ANWB'er, dus ik dacht ik meld het even. https://www.youtube.com/watch?v=uDcO8LRsKfA

### Wat hoorde er te gebeuren?

Als de bijbestuurder Q drukt (zwaailichten dus) dan hoort de lichten ook te werken, alleen gebeurd dat niet. 

### Wat veroorzaakt de bug?

geen idee, https://www.youtube.com/watch?v=uDcO8LRsKfA

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Fyi, de video staat op privé. Je moet hem op verborgen zetten, niet privé :)

**Comment by CalRayy** [comment]
> Fyi, de video staat op privé. Je moet hem op verborgen zetten, niet privé :)

Ah, thanks voor het melden als het goed is is dat nu gefixt 😃

**Comment by AntonMTDA** [comment]
zie dat het gefixed is dus deze word gesloten

**Comment by Lorenzo3001** [comment]
Geen idee wat dit probleem veroorzaakt. Er is geen duidelijke manier waarop dit te reproduceren valt. Als het goed is kun je het probleem in ieder geval ook oplossen doormiddel van /resync.
