### ISSUE TITLE
[FEATURE]: CCF cirkels lift die in de test stad staan deploy naar de stad

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1828]
### Contact Details

Schmutz#8587

### Beschrijf zo duidelijk mogelijk de feature

van het heleipad op het gebouw bij CCF op postcode 5035 zouden er tp crikels komen naar in het gebouw, benden, 1e, 2e verdieping, deze zijn al wel gedeployed naar de teststad maar nog niet doorgekomen naar de stad zelf
![cirkels](https://user-images.githubusercontent.com/120605155/210969032-29dabc06-dbc1-4f8f-a678-c5808e124874.jpg)

### Wat lost deze feature op?

via de trap langs het huis omhoog en omlaag en soms zelf doodvallen / gebruik lift

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Zojuist alles in de dev server bijgewerkt en gecommit naar de main server.
