### ISSUE TITLE
[FEATURE]: CCF aanpassen permissions kluis

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1829]
### Contact Details

Schmutz#8587

### Beschrijf zo duidelijk mogelijk de feature

vanaf made men dus volwaardig lid (made men) mag ook de kluis toegankelijk zijn, we merken dat dit anders problemen oplevert met de loods opens stellen voor de familie. dus made men, wise guy, caporegime, consigliere en don mogen overal bij. de bazenpot is uiteraard voor de don zelf. zouden jullie dit kunnen aanpassen ? alvast bedankt

![permissions](https://user-images.githubusercontent.com/120605155/210969544-dbd49e3a-9883-45d7-aa01-b0d79d11fafb.png)

### Wat lost deze feature op?

gezeur met loodsen en zakken uit kluis

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Donnycolombo** [comment]
Hallo devs, zouden jullie dit willen oppakken dat zou ons leven toch gemakkelijker maken

**Comment by niekschoemaker** [comment]
Oh adviesje voor volgende keer, we zijn in principe alleen de wijzigingen nodig, want we kunnen wel zien hoe het nu staat, maar dat moeten we dan uitzoeken, dus we moeten hiermee alles controleren in plaats van simpel een paar kleine dingetjes aanpassen:

Dus bijv:
- made man (200) -> toegang tot kluis
- wise guy (300) -> toegang tot kluis

Dat maakt het wat makkelijker

**Comment by Donnycolombo** [comment]
@niekschoemaker  helemaal goed, dan weet ik wat ik de volgende keer moet doen. nog een andere vraag zou je voor associate --> afboeien willen toestaan? als volledig F6 menu makkelijker is ook prima. 

Ik merk dat leden dit erg vervelend vinden dit niet te kunnen. Hoor het graag en alvast bedankt

**Comment by Donnycolombo** [comment]
@niekschoemaker  may I tag you friendly sir :) zie bovenstaand

**Comment by Tom974** [comment]
Hey @Donnycolombo,

De aanpassing voor associate is zojuist doorgevoerd. Dit zit ook al in de server
