### ISSUE TITLE
[FEATURE]: CCF fotos in huis

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1830]
### Contact Details

Schmutz#8587

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag om de MLO wat persoonlijker te maken wat fotos die in het huis hangen laten vervangen door fotos van de familie. is dat mogelijk ? wij hebben een channel aangemaakt in onze discord waar de fotos staan en waar ze geplaatst mogen worden in het huis.

https://discord.com/channels/917721498360373258/1036391954814079026

bij vragen ben ik bereikbaar en alvast bedankt

### Wat lost deze feature op?

leuk en gaaf huis, persoonlijk voor CCF

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AntonMTDA** [comment]
Wellicht handig om de fotos even te uploaden zodat we hier bij kunnen :D

**Comment by Avii97** [comment]
![IMG_8253](https://user-images.githubusercontent.com/122118644/211076184-15f6ceca-4c25-42f7-94c4-7dedd8130879.jpg)
![unknown (1)](https://user-images.githubusercontent.com/122118644/211076190-5a48880a-5a82-49ed-a865-26a356c1784a.png)
![unknown](https://user-images.githubusercontent.com/122118644/211076195-d3a0dd69-a1d9-4423-935d-05b1df796c3d.png)
![IMG_8256](https://user-images.githubusercontent.com/122118644/211076196-e41588e7-75b3-4a85-9483-110d9c5452bc.jpg)
![IMG_8255](https://user-images.githubusercontent.com/122118644/211076199-d6490f66-83da-41eb-a778-79ced714a63a.jpg)
![IMG_8254](https://user-images.githubusercontent.com/122118644/211076202-7d7a6578-cc63-4758-b097-2fdbedc0655f.jpg)
![unknown (2)](https://user-images.githubusercontent.com/122118644/211076211-5a9860ac-6813-46c2-bd0b-23d3e13ceb3f.png)
![2](https://user-images.githubusercontent.com/122118644/211076217-1b366394-c6c2-4e17-af9c-45de3aec1d14.png)
![daan_c](https://user-images.githubusercontent.com/122118644/211076220-2a9b0c8f-6375-4ba6-9c7e-3816a48bb05b.jpg)
![22_1](https://user-images.githubusercontent.com/122118644/211076222-342e726a-eec8-476e-9d8b-95e95acdd6e4.png)
![Desktop_Screenshot_2022 11 20_-_22 18 56 41](https://user-images.githubusercontent.com/122118644/211076226-b25f8120-fd78-4220-894b-5b296ca20f24.png)
![unknown_3](https://user-images.githubusercontent.com/122118644/211076229-9abbe763-3b74-4b80-914b-8e0ba9be27ac.png)
![Screenshot_20221130-073133_Discord](https://user-images.githubusercontent.com/122118644/211076231-e9df8fd1-ddae-4151-808f-7e7887e05396.jpg)

**Comment by CorruptSausage** [comment]
@AntonMTDA kan jij hiermee verder gaan?

**Comment by Donnycolombo** [comment]
In onze discord staat naast de fotos zelf ook de posities waar wij ze in gedachten hadden, onder de links huis fotos

**Comment by Donnycolombo** [comment]
@AntonMTDA heb je misschien al wat tijd gemaakt ?

**Comment by AntonMTDA** [comment]
Hoi daar! Ik was afgelopen tijd aardig druk ik zal hier eens naar gaan kijken :)

**Comment by AntonMTDA** [comment]
Als de plekken hier in gezet kunnen worden dan kan ik net wat meer!

**Comment by Tom974** [comment]
@Donnycolombo, zie comment van Anton hierboven ^

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/
![1](https://user-images.githubusercontent.com/120605155/236560394-5ddc78e9-2d25-48de-ae82-60aa62ce3109.png)
236560350-0435c14d-98f5-454a-bf7f-53804e37c5d0.png)


![211076196-e41588e7-75b3-4a85-9483-110d9c5452bc](https://user-images.githubusercontent.com/1
![rat2](https://user-images.githubusercontent.com/120605155/236560513-821fe1a1-6b0a-4d88-b243-1b96848bb33c.png)
20605155/236560437-370a1bf6-f2e3-4c89-8a2b-f3b63f5d12e0.jpg)

![image](https://user-images.githubusercontent.com/120605155/236560465-beb4ce20-5434-4528-bba3-f29b0f6736f7.png)
![image](https://user-images.githubusercontent.com/120605155/236560554-4f99609e-f790-4c91-ae65-a42c287bcd04.png)

**Comment by Donnycolombo** [comment]
![PACKARD](https://user-images.githubusercontent.com/120605155/236560664-61569370-aabe-4fe6-b1f9-5784e7ccf728.png)
![image](https://user-images.githubusercontent.com/120605155/236560684-9b74fb74-cb9d-4b22-9e14-1af438e772d6.png)

**Comment by Donnycolombo** [comment]
![IMG_8256](https://user-images.githubusercontent.com/120605155/236560725-5cc5fa1c-3006-4c93-a2eb-897e0288da95.jpg)
![image](https://user-images.githubusercontent.com/120605155/236560747-77488a19-94b3-4258-96fa-d04199fe9edc.png)

**Comment by Donnycolombo** [comment]
![434](https://user-images.githubusercontent.com/120605155/236560838-a6ed4478-46d4-4e67-b585-f477293e8114.png)
![image](https://user-images.githubusercontent.com/120605155/236560858-6ed8fe25-2b3c-49d5-95f5-8d674b62869b.png)

**Comment by Donnycolombo** [comment]
![rat2](https://user-images.githubusercontent.com/120605155/236561025-5d7f9fe1-5070-420b-a375-4e0caaf8fe5b.png)
![image](https://user-images.githubusercontent.com/120605155/236561041-3eebbe9f-d1cc-4010-b5e0-1e20b7b9836f.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236561285-ca40555f-4962-4e43-ab58-008004ae25af.png)
![Screenshot 2023-05-05 222211](https://user-images.githubusercontent.com/120605155/236561512-c89373bd-f8cd-4faf-8ccc-e1fa06cb04b7.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236561819-d131e25d-3875-4b37-8a5b-cb8664788985.png)
![image](https://user-images.githubusercontent.com/120605155/236561872-5eca52c2-0b6b-4e59-ba1b-8b130b9e67d4.png)

**Comment by Donnycolombo** [comment]
De bovenstaande fotos zijn beneden in het restaurant

**Comment by Donnycolombo** [comment]
De onderstaande fotos zijn op de 1e verdieping

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236562436-93053e3f-b27d-4c01-afcb-ff62468a00ab.png)

![Moreno_4](https://user-images.githubusercontent.com/120605155/236562497-bba26868-5ae2-4fbb-9459-3a473f38cb5c.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236562758-0c47f985-4400-49aa-a0b3-eea59370a5b5.png)
![image](https://user-images.githubusercontent.com/120605155/236562882-5c2cef14-ae73-49e3-adf8-e444cad01007.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236562944-6a8e055b-4e94-4899-815d-0c25353fb9c5.png)
![1](https://user-images.githubusercontent.com/120605155/236562962-18dda999-d4d2-4245-8119-437e54a4abf1.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236563047-e902a108-ef67-4052-aeb0-4aa899ec933e.png)
![IMG_9280](https://user-images.githubusercontent.com/120605155/236563064-ee36d470-06c1-4016-b813-5048a14afeef.jpg)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236563160-e007b25e-948e-49e2-
![1 (1)](https://user-images.githubusercontent.com/120605155/236563208-cdf4954d-f806-45f8-925d-bb7e9a346c9a.png)
beaa-34e1c0ff3407.png)

**Comment by Donnycolombo** [comment]
![1 (1)](https://user-images.githubusercontent.com/120605155/236563246-c3cdbfac-8e67-49cf-a093-a712f355cf75.png)
![image](https://user-images.githubusercontent.com/120605155/236563256-00de4f84-3eb2-449a-b03d-c353d800935f.png)

**Comment by Donnycolombo** [comment]
![unknown (3)](https://user-images.githubusercontent.com/120605155/236563428-cb867588-e020-4934-b8ca-b84d2c1615d2.png)

![image](https://user-images.githubusercontent.com/120605155/236563475-aab7b606-ef1e-40eb-82ab-4a5649e9ca0c.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236563665-9fad07ea-d546-4605-ab4d-68cb6588951d.png)
![Desktop_Screenshot_2022 11 20_-_22 18 56 41](https://user-images.githubusercontent.com/120605155/236563705-202c21f1-3784-414d-912d-a8ebafdc9eb6.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236563809-632e88d2-0494-4dab-acf4-5cf74c42aa62.png)
![unknown (3)](https://user-images.githubusercontent.com/120605155/236563941-1c0c2cad-9c5f-44b1-8382-d8206d061c4c.png)

**Comment by Donnycolombo** [comment]
de onderstaande fotos zijn voor de 2e verdieping

**Comment by Donnycolombo** [comment]
![22 (1)](https://user-images.githubusercontent.com/120605155/236564292-31de2fd4-4449-464e-b385-6659ffc6b690.png)
![image](https://user-images.githubusercontent.com/120605155/236564316-67ad0608-2e22-4382-a4c5-c090e05c1f3e.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/2365643
![2 (1)](https://user-images.githubusercontent.com/120605155/236564876-90dfdd75-ddd3-45bd-8598-fd529254eb81.png)
38-a263a06b-2969-40ae-ab73-75041113300b.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236564929-cbd39273-55fc-40df-b237-9ac429397828.png)
![image](https://user-images.githubusercontent.com/120605155/236564952-9889b3fb-8e9c-481b-8bae-753cbc8ba1da.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236564977-969e1436-870b-45d5-ac1e-3b685dd44ff0.png)

![2 (1)](https://user-images.githubusercontent.com/120605155/236564999-37a5f20b-c8e7-478c-b966-ee14beaabc96.png)

**Comment by Donnycolombo** [comment]
![2](https://user-images.githubusercontent.com/120605155/236565637-9311040d-ec50-474d-9cb8-fb404ea84045.png)
![image](https://user-images.githubusercontent.com/120605155/236565651-99f09ce5-bc01-49d2-a7f6-06bf16ccfa7a.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236565844-ed880907-82a7-4235-9c42-21ae80e87ea0.png)
![123123](https://user-images.githubusercontent.com/120605155/236565894-616e92a3-e936-49de-9380-ceea10acdd17.png)

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236565937-06ba2bf9-ebe8-465d-8123-bfc22ce2fb33.png)

![FiveM_b2372_GTAProcess_2023-03-28_13-22-00](https://user-images.githubusercontent.com/120605155/236566332-00af210f-cfe9-4d79-a9a1-031ec1df8166.png)

**Comment by Donnycolombo** [comment]
@AntonMTDA @Tom974  hallo heren, iets te laat gezien maar zouden jullie het bovenstaand willen doorvoeren ?" super tof

**Comment by Tom974** [comment]
Ik ben zelf geen 3modellor, dus ik kan je hier sowieso niet bij helpen haha. 

Aangezien Anton (naar mijn weten) nu ook afwezig is zal ik het even navragen bij @CalRayy

**Comment by Donnycolombo** [comment]
@CalRayy is er iemand anders die wij kunnen vragen ?
