### ISSUE TITLE
[FEATURE]: CCF 1 kluis locatie veranderen naar garage

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1831]
### Contact Details

Schmutz#8587

### Beschrijf zo duidelijk mogelijk de feature

graag de kluis die bij de lockers in de keuken ligt verplaatsten naar de garage die is ontwikkeld door oesewoes zodat we de garage ook kunnen gebruiken waarvoor die bedoeld is. alvast dank

De kluis cirkel op
![cooords old kluis](https://user-images.githubusercontent.com/120605155/210973391-bf2116d4-9a0b-4c0d-8758-1661c502ee8f.JPG)

mag verplaatst worden naar

![Coords kluis cirkel](https://user-images.githubusercontent.com/120605155/210972803-025476e3-d018-44d4-b370-62b2ad3bca08.JPG)

### Wat lost deze feature op?

zie bovenstaand

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
![afbeelding](https://user-images.githubusercontent.com/69365961/212328177-67bda3b3-d1b2-489b-807a-1f9cbf81df3d.png)
Kan het niet in de dev server volledig nakijken omdat we jullie nieuwe garage interior daar niet hebben maar ik ga er van uit dat hij op de juiste plek staat. Ik ga het committen naar de main server.
