### ISSUE TITLE
[FEATURE] hoeveelheid tickets zien op adminpanel

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#1835]
### Contact Details

StoffigKontje#8688

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid om op het adminpanel profiel van iemand in te kunnen zien hoeveel en wat voor tickets iemand heeft aangemaakt. 

Dus waarschijnlijk het tickets.tedeapolis.nl/DISCORDID weergeven op adminpanel

### Wat lost deze feature op?

Overzicht of iemand onnodig veel tickets aanmaakt. O.A. Besproken in staff overleg van 08-01-2023

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
is helaas niet mogelijk
