### ISSUE TITLE
[EUP]: Unmarked outfit toevoegen KMAR

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1836]
### Contact Details

Johnny#8125

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Wij zouden graag de unmarked outfit willen toevoegen voor alle KMar rangen:

De outfit is als volgt:
T-Shirt 1 = 48
T-Shirt 2 = 1
Torso 1 = 156
Torso 2 = 4
Stickers 1 = 0
Stickers 2 = 0
Armen = 12
Broek 1 = 108
Broek 2 = 0
Schoenen 1 = 25
Schoenen 2 = 0
Kogelvrij Vest 1 = 0
Kogelvrij Vest 2 = 0
Ketting 1 = 3
Ketting 2 = 0

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Hey @KMarTDA Als ik het goed begrijp zijn deze kleren er al en hoeven dus enkel voor elke rang toegevoegd te worden?

**Comment by KMarTDA** [comment]
@DevvTDA Hoi! Dat klopt, alles zit er al in.

**Comment by DevvTDA** [comment]
Zit erin ! :)
