### ISSUE TITLE
[FEATURE]: Tedeapolis bot inventory check, toevoegen dat je geld opzak ook ziet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1837]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Goedemorgen, 

Op het moment kunnen wij als staff zijnde een mooie commando gebruiken om iemand zijn inventory te checken (wat super goed is). Enige nadeel is dat je het geld (en zwart geld) op zak niet ziet, is het mogelijk om dit ook te kunnen zien? 

### Wat lost deze feature op?

Stel een witwasser combatlogged, zie je hoeveel geld die bij zich had en dan kunnen we het bedrag gelijk refunden en via database aanvragen om het weg te laten halen. (Kost minder werk voor de database mensen 😄 )

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
@niekschoemaker kan jij hier even naar kijken?
