### ISSUE TITLE
[Interior] Bloods MLO

### ISSUE THREAD

**Issue by Toro-Carri** [Tedeapolis/development#1839]
Hey!

In overleg met Oesewoes en Nander heb ik deze GitHub aangemaakt. Het zal gaan om de MLO voor groep 'The Bloods' waarvan de files inmiddels door zijn gestuurd. Deze is te vinden Grove Street 😄 

- [Verbreding en doortrekken van de garage. Wanneer je de garage inkomt vanaf de garagedeur, deze verbreden en dus de lege ruimte van het pand opvullen. De muur die tussen de basketbal court en garage in staat weg, zodat dit één grote garage kan worden. Muren van deze totale garage kan de zelfde textures en opgevuld met zoals op de foto is te zien rode paintings (graffiti, gangsigns etc.). De muren van de garage indien mogelijk donker grijze stenen en hierover dan de graffiti, foto's en tekst die ik in de discord heb neergezet. Voorbeeld van hoe we de garage in gedachten hadden is ook te vinden in de discord (maar dan alle kleuren graag rood).]
- [Het dak plat maken zodat hier een heli op kan landen (helipad op dak). Wellicht aan de andere kant van het dak een kleine chill plek/terras. Vanaf het dak een lift naar binnen het gebouw, of een trap die uitkomt op het dak vanaf de bovenste verdieping.]

Hopelijk is het zo iets duidelijker en hoor ik graag als ik nog ergens mee kan helpen 👍 😄

**Comment by Tom974** [comment]
Deze is afgerond toch @Toro-Carri?

Anders graag opnieuw openen!
