### ISSUE TITLE
[Bug]: Muziekcirkel Exotica weer kapot

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1840]
### Contact Details

Dyon#9999

### Wat gebeurde er?

Het moment dat wij muziek aan willen zetten in Exotica doet de muziek cirkel het niet naar behoren. Je kan het menu wel openen, maar het moment dat je iets wilt afspelen gebeurd er niks. 

### Wat hoorde er te gebeuren?

Zodra je op play drukt, het nummer ook echt afspeelt. Door deze bug kunnen wij ook geen feesten meer geven op het moment.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

[CitizenFX_log_2023-01-11T050615.log](https://github.com/Tedeapolis/development/files/10389059/CitizenFX_log_2023-01-11T050615.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Als het kan zouden we ook graag de muziek lijst gecleared hebben aangezien er ook een aantal gebuggde nummers in staan die we niet weg kunnen halen

**Comment by Attomn** [comment]
Bug is bekend, gaat hopelijk zo snel mogelijk naar gekeken worden. Nummers verwijderen heb je zelf ook vingertjes voor. Zit een mooie verwijder knop ingebouwd. 
![afbeelding](https://user-images.githubusercontent.com/69365961/212042592-19357e88-653e-4dff-947a-f7c269d51222.png)

**Comment by ExoticaTDA** [comment]
> Bug is bekend, gaat hopelijk zo snel mogelijk naar gekeken worden. Nummers verwijderen heb je zelf ook vingertjes voor. Zit een mooie verwijder knop ingebouwd. ![afbeelding](https://user-images.githubusercontent.com/69365961/212042592-19357e88-653e-4dff-947a-f7c269d51222.png)

Dat is het ding dus, we hebben een stuk of 10 nummers die wij niet verwijderd krijgen. Dus vandaar de vraag of jullie die weg kunnen krijgen

**Comment by Attomn** [comment]
afspeel bug zou nu gefixt moeten zijn!!! Verwijderen moet nu ook lukken als ik het zo test.
