### ISSUE TITLE
[FEATURE]: KMar & Politie pas/document aanpassen naar fake grade rang.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1841]
### Contact Details

Johnny#8125

### Beschrijf zo duidelijk mogelijk de feature

 Toevoegen dat je gekozen /fake_grade ook op je KMar/Politie pas komt te staan. Tevens ook dat de gekozen rang op documenten komt te staan. 

### Wat lost deze feature op?

Momenteel is het zo dat de DSI leden van de Politie en KMar /fake_grade gebruiken om zijn of haar rang te verbergen. Echter staat er op het pasje van de Politie agenten ''Hoofdagent'' en bij de KMar ''Luitenant'' (Luitenant op zich is een rang die momenteel NIET gebruikt word). Dit geldt ook voor de documenten die ondertekent worden. Het verzoek is dan ook om dit te veranderen zodat als een agent zijn of haar pasje/document geeft er een ''normale'' rang staat die zij hanteren. 

Mochten er vragen zijn, dan hoor ik het graag!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
- [ ] fake_grade op documenten
- [ ] fake_grade op passen

**Comment by CorruptSausage** [comment]
Zit erin na restart
