### ISSUE TITLE
[FEATURE]: Trustscore systeem tickets

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1843]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Githubje voor Niek. Trustscore systeem voor tickets bijhouden om inzicht te krijgen wie veel tickets aanmaakt die afgekeurd worden.

### Wat lost deze feature op?

Spelers gaan eerder nadenken voordat ze een ticket maken en is informatief voor staffleden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dit zit er al in toch @ARJ3N ?

**Comment by ARJ3N** [comment]
Een versie zit hiervan in maar je zou aan Niek moeten vragen of hij er nog meer mee wilt. @Tom974
