### ISSUE TITLE
[Bug]: In meldkamer porto 110 in-game hoor je regelmatig ineens een ander persoon die niet in de porto praat

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1846]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Met enige regelmaat hoor je indien je in-game in porto 110 zit als KMar/Politie ineens een random iemand praten die ook in de porto zit maar die niet in de porto aan het praten is. Daardoor heb je als je in dienst bent de hele dag door dat mensen via de porto moeten vragen of diegene die het bijvoorbeeld op dat moment over een arrestant heeft even het mumble reconnect command kan uitvoeren omdat hij diegene anders de hele tijd blijft horen.

### Wat hoorde er te gebeuren?

Je hoort enkel mensen te horen als ze ook de porto indrukken.

### Wat veroorzaakt de bug?

Ik heb geen idee, het lijkt enorm random en het gaat dan ook maar om één persoon per keer die een ander random persoon ineens blijft horen door de porto.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Is in het algemeen bij elke porto, toen ik crimineel was had ik dit ook in de normale frequenties.

**Comment by Tom974** [comment]
Ik ben er in ieder geval achter gekomen dat als je NIET praat terwijl je de porto joined, je hier vrijwel tot geen last van hebt. 

Dus als tip; zorg dat je niet praat als je de porto joined

**Comment by Tom974** [comment]
Aankomende weken even aankijken hoe vaak dit nog voorkomt.

**Comment by Tom974** [comment]
fixed.
