### ISSUE TITLE
[FEATURE]: Garage voor Soprano's Taco's

### ISSUE THREAD

**Issue by JaylinFerluci** [Tedeapolis/development#1847]
### Contact Details

Jaylin Ferluci#5959

### Beschrijf zo duidelijk mogelijk de feature

Jack Evans heeft een gesprek gehad met Niek voor een garage voor de Soprano's Taco's, waar ik alle foodtrucks in zou kunnen zetten en het personeel de foodtrucks eruit zouden kunnen halen.

### Wat lost deze feature op?

Voor mij wat rust om speciaal de stad in te moeten komen voor het personeel om een bus aan hun uit te lenen.
Dit zou voor ons veel hoofdpijn oplossen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Heb even gekeken en hebben een hele parkeerplaats achter en naast het pand waar de cirkels kunnen komen.

Coords rode cirkel: x: 57.79, Y: -1570.02 Z: 29.46 H: 228.11
Coords groene cirkel: X: 38.63 Y: -1570.15 Z: 29.29 H: 235.63

![image](https://user-images.githubusercontent.com/79802852/218492864-0520f9da-fe78-4345-ae72-63ea2d9472e4.png)

**Comment by JaylinFerluci** [comment]
Nu is mijn vraag is dit een openbare garage, Zo ja er zou ook een deel garage komen voor het personeel om de foodtrucks te kunnen delen met elkaar. Als ik de foodtrucks erin zou zetten zodat personeel ze eruit konden halen met grantkeys.

Maar ik heb sowieso wel geduld hoor maar wilde ook weten hoe dat ervoor stond.

**Comment by DevvTDA** [comment]
Dat laten we nu denk ik nog beter achterwegen, publieke garages kunnen we wel plaatsen voor je. dit is wat ik gehoord heb vanuit Misstake.

**Comment by CalRayy** [comment]
Garage is toegevoegd, nu wachten op Misstake voor het doorvoeren 😄 !
