### ISSUE TITLE
[FEATURE]: Outlaw kleding cirkel

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1848]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Outlaws zou graag een kleding cirkel willen hebben in hun MLO, als het mogelijk graag op deze coords: 
![image](https://user-images.githubusercontent.com/101106299/212200778-d3fad34a-00a3-4aa9-a342-943d9f32dccf.png)
( X: 1223.22 Y: -404.13 Z: 68.86 )

### Wat lost deze feature op?

Dan kunnen de Outlaws in hun eigen MLO van kleding veranderen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
is niet nodig.
