### ISSUE TITLE
[Bug]: Porto taxi (140) 

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1849]
### Contact Details

Yohandessu#3314

### Wat gebeurde er?

Heel erg vaak als je van porto 141 naar porto 140 schakeld hoor je mensen praten in de porto die wel in de porto zitten maar die niet actief aan het praten zijn in de porto. Eerder dacht ik dat dit gewoon een porto BUG was maar ik zag eerder vandaag dat de politie er ook last van heeft. 

### Wat hoorde er te gebeuren?

Dat je de mensen niet hoort praten wanneer zij niet actief in de porto praten 

### Wat veroorzaakt de bug?

Dat je meermaals per dag moet vragen of mensen in de porto/mr moeten doen. Dit veroorzaakt vaak veen onnodig gepraat in de porto.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Geen 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Als dit dezelfde issue is als bij de politie graag geen dubbele issues maken
