### ISSUE TITLE
[Bug]: Soprano's Taco's verkoopcirkels 

### ISSUE THREAD

**Issue by JaylinFerluci** [Tedeapolis/development#1851]
### Contact Details

Jaylin Ferluci#5959

### Wat gebeurde er?

Mensen met de taco rang als 2de job kunnen de cirkels niet zien. Zou hier naar gekeken kunnen worden. De meeste mensen die daar werken, die werken ook bij een overheids job. Bvd

### Wat hoorde er te gebeuren?

Dat je met de rang ongeacht job 1 of 2 dat de cirkels zichtbaar zijn.

### Wat veroorzaakt de bug?

Toen de Cirkels op rang zijn gezet hebben de mensen die hun job op de 2 rang hebben staan zien sindsdien de cirkels niet meer

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

Dat de helft van de mensen geen taco's kan verkopen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Is opgelost na de restart!
