### ISSUE TITLE
[FEATURE]: Flywheels mlo toestemming van nander

### ISSUE THREAD

**Issue by Fluffyfox120** [Tedeapolis/development#1852]
### Contact Details

FluffyFox#8075

### Beschrijf zo duidelijk mogelijk de feature

Flywheels MLO (Toestemming van nander is er)
Momenteel is de mlo zelf helemaal goed qua textures voor de files moet u me maar even op discord een bericht sturen
textures zitten al juist en correct maar enkel zouden der modshop cirkels moeten komen op deze 4 platformen (zie foto)
Liefst niet zichtbaar op de map
![image](https://user-images.githubusercontent.com/114611475/212479690-4e2dd2f1-5ae7-4c49-b5df-5cf0c0ffa5d8.png)

En als het zou kunnen de mogelijkheid voor de deuren kunnen open en toe doen natuurlijk :3 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Hoi,

Ik ga de MLO in de test server zetten zodat je zelf aan kan geven waar de mod cirkels precies moeten komen en welke deuren een slot nodig hebben!

**Comment by Fluffyfox120** [comment]
Zie foto's voor mod cirkels en deuren
Deuren

![image](https://user-images.githubusercontent.com/114611475/212483271-0f770cf1-2a72-4b61-9727-38c5f521d2ec.png)
![image](https://user-images.githubusercontent.com/114611475/212483304-e9c029d9-a0b9-40eb-8e88-1388578c0e13.png)
![image](https://user-images.githubusercontent.com/114611475/212483432-e2413e63-e2fe-4d2f-abd2-f64cfd24d082.png)
![image](https://user-images.githubusercontent.com/114611475/212483444-150889b1-606a-4000-ad36-1a1d282961e9.png)


Mod cirkels
1
![image](https://user-images.githubusercontent.com/114611475/212483332-20dd89da-0146-4952-a5bb-53e78b3b1be7.png)
2
![image](https://user-images.githubusercontent.com/114611475/212483357-67349fe8-d0e9-46eb-a253-8931394e86ac.png)
3
![image](https://user-images.githubusercontent.com/114611475/212483371-271894fb-a445-4372-8074-c603d533e97b.png)
4
![image](https://user-images.githubusercontent.com/114611475/212483395-df5bb7cb-cacc-41a0-a485-d39c659021c8.png)

**Comment by Fluffyfox120** [comment]
Is het trouwens mogelijk voor deze 2 obstakels weg te fixen want deze horen hier normaal niet maar te staan 
![image](https://user-images.githubusercontent.com/114611475/212713546-e6aeb830-15b7-4932-b460-797d0e45759a.png)

**Comment by Fluffyfox120** [comment]
is hier al wat info over :3

**Comment by Fluffyfox120** [comment]
Moest het kunnen
hier een kleedkamer cirkel coords staat bovenaan

- [ ] Kleedkamer cirkel plaatsen

![image](https://user-images.githubusercontent.com/114611475/220942841-dde8505b-409d-4cdd-b70d-4f452f48919e.png)

**Comment by Fluffyfox120** [comment]
- [ ] Textures aangepast/verkleint

- [ ] sloten

- [ ] kledingcirkel

- [ ] tunecirkel

Deze zijn allemaal toegevoegd
enkel nog naar main pushen :3

**Comment by AntonMTDA** [comment]
Is fixedddd
