### ISSUE TITLE
[FEATURE]: Kleding cirkel voor de caribbean

### ISSUE THREAD

**Issue by Jeanpaulmorris** [Tedeapolis/development#1853]
### Contact Details

Jean-Paul M#1942

### Beschrijf zo duidelijk mogelijk de feature

Wellicht is het mogelijk voor de caribbean om een kleding cirkel te krijgen in ons huis om zo makkelijker van kleding te wissen voor een scenario (Het is geen must maar het is wel handig om te hebben).  Locatie voor de cirkel staat in de bijlage.
![image](https://user-images.githubusercontent.com/122266973/212487816-48d690d2-f0ce-4b46-aef4-e67e20fbbf91.png)

### Wat lost deze feature op?

Als wij als caribbean een aantal scenario's willen doen, dan kunnen wij alvast een aantal outfits maken en in onze kledingkast te zetten. Het is fijn om zo'n cirkel te hebben maar het is gee must :).

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Hoi, dit gaan we niet doen. Jullie zijn gang level 1 en hebben nog niet eens een MLO zover mij bekend.
