### ISSUE TITLE
[FEATURE]: Mazebank Garage kunnen delen.

### ISSUE THREAD

**Issue by ExpensiveK09** [Tedeapolis/development#1854]
### Contact Details

ExpensiveK#0001

### Beschrijf zo duidelijk mogelijk de feature

Dat je mazebank garage kunt delen met vrienden, net zoals loodsen principe. Je kunt beide dan auto's in de garage steken en eruit halen van beide personen die er ook in zitten. Deze hebben dan “full acces” over het voertuig (dus sleutels, /trv), zoals de voertuigopslag van gangs 

Voordelen: Zal leuk zijn om bijvoorbeeld samen een auto te kopen en deze te gebruiken wanneer je maar wilt en niet hoeft te wachten op een ander of dergelijke.

### Wat lost deze feature op?

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExpensiveK09** [comment]
@Ljosfari, is dit wel mogelijk kwa scripten?

**Comment by Tom974** [comment]
Zie hier momenteel niet echt heel veel voordelen in dus ik plak er ff een low prio aan

**Comment by Tom974** [comment]
Als ik zo kijk naar hoe vaak de garages momenteel gebruikt worden vind ik dit niet een feature welke veel toevoeging heeft. 

Om deze reden wijs ik hem af.
