### ISSUE TITLE
[FEATURE]: Omwisselen van de tank van een havok en seasparrow - Community team

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1855]
### Contact Details

Yohandessu#3314

### Beschrijf zo duidelijk mogelijk de feature

De tank van een Havok is een heel stuk kleiner dan die van de seasparrow, dit terwijl de seasparrow een stuk kleiner is dan de Havok. De tank van een havok is atm 45L en die van de seasparrow 90L. Dit zouden wij namens het Community team graag omgewisseld willen. Dus dat de Havok 90L word en de seasparrow 45L 

### Wat lost deze feature op?

Dat mensen langer kunnen vliegen met een grotere heli. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Lorenzo3001** [comment]
Ik gok dat je de namen hebt omgedraaid :p

De Seasparrow stond op 50L en de Havok op 100L, die zijn nu aangepast naar 80L voor de Seasparrow en 45L voor de Havok.

**Comment by JohanDewus** [comment]
Oeps.... haha, bedankt!
