### ISSUE TITLE
[FEATURE]: Secondjob zichtbaar maken in de werknemers lijst

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1857]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Op het moment zijn bij alle jobs alleen de mensen met de rang op hun eerste job zichtbaar in de werknemers lijst. Dit kan best vervelend zijn op het moment dat je iemand wilt ontslaan die de rang op hun Secondjob heeft. Dit zijn dingen die vaak voor komen bij Exotica, R3D, TDA Nieuws, Luxery Cardealer en andere jobs die mensen vaak op hun secondjob hebben staan. Zo hebben wij bij Exotica van de +/- 20 mensen die een rang hebben er maar 3 in de werknemerslijst staan.

Is het mogelijk dat mensen die een job op hun secondjob hebben staan ook zichtbaar worden in de werknemers lijst?
![image (32)](https://user-images.githubusercontent.com/120292087/212812568-3a2a81c8-7f0c-4e88-9d83-a6fb2e22091a.png)

### Wat lost deze feature op?

Het probleem dat we iemand z'n rang niet weg kunnen halen het moment dat deze persoon niet meer in dienst is bij de desbetrefende job.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Mikajac** [comment]
Hierbij dan ook graag het verzoek om bazen toegang te geven tot /setjob2. Bij de radio kunnen wij namelijk niemand aannemen op de 2e job zonder hulp te vragen via een report. Ik denk dat elke secondaire job daar last van heeft.

**Comment by ExoticaTDA** [comment]
> Hierbij dan ook graag het verzoek om bazen toegang te geven tot /setjob2. Bij de radio kunnen wij namelijk niemand aannemen op de 2e job zonder hulp te vragen via een report. Ik denk dat elke secondaire job daar last van heeft.

Bij Exotica en Taxi kunnen wij wel 2e job geven. Dus ik zou als ik jou was daar een losse github over maken

**Comment by Tom974** [comment]
Hey @ExoticaTDA, 

Dit zal gefixt zijn na de herstart!

Laat je het mij eventjes weten indien dit toch niet zo is?

Bedankt!
