### ISSUE TITLE
[Bug]: R3D uitdienst (Sloten)

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1858]
### Contact Details

dead123x5#0001

### Wat gebeurde er?

Als je uit dienst gaat bij de rang R3D (red) kan je de deuren niet meer open maken.

### Wat hoorde er te gebeuren?

Dat als je uitdienst gaat de sloten nog steeds kan gebruiken,

Het gaat over de volgende sloten.

- [ ]  Voordeur: https://prnt.sc/h6tbRCWBOXZB
- [ ]  Kantoor deur: https://prnt.sc/gzAayRENJY01
- [ ]  Kantine deur: https://prnt.sc/vX1Dhm2aQ-pv
- [ ]  Garagedeur Links: https://prnt.sc/GM1mLg3njSgO
- [ ]  Garagedeur Rechts: https://prnt.sc/ZI8_WULg_m3Y

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Is gefixt na de restart.
