### ISSUE TITLE
[FEATURE]: Logo toevoegen bij Uitdienst rang

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1859]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Als wij uit dienst gaan hebben wij daarbij nog geen logotje. En het de text staat heel raar.

- [ ] Bij het uitdienst R3D (offred) logo toevoegen met het volgende fototje: https://i.imgur.com/3PVxmSL.png

- [ ] De test van de uitdienst R3D (offred) neer zetten met een spatie dus "Uitdienst R3D"

Die tekst staat nu namelijk aan elkaar.
https://prnt.sc/7V8zK2yk7B7L

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed
