### ISSUE TITLE
[FEATURE]: Rang toevoegen Bloods

### ISSUE THREAD

**Issue by Toro-Carri** [Tedeapolis/development#1860]
### Contact Details

Toro#5710

### Beschrijf zo duidelijk mogelijk de feature

Mocht er een mogelijkheid zijn om dit een keer aan te passen, zouden we dat geweldig vinden! Indien mogelijk zou ik graag drie nieuwe rangen willen toevoegen aan de gang. Bij 'niets veranderen' is de rang zoals hij nu staat ingesteld prima.

The Bloods - **War Elder** (Niets aan veranderen)
The Bloods - **Triple O.G.** (Niets aan veranderen)

- [**Nieuwe Rang:** The Bloods - **Shotcaller** (Normale F6 Rang + Inkoop/mod alle wapens)]

The Bloods - **Regent** (Normale F6 Rang) - Inkoop handwapen weghalen
The Bloods - **Street Enforcer** (Normale F6 Rang - Niets veranderen) - Inkoop handwapen weghalen
The Bloods - **Gangster** (Normale F6 Rang- Niets veranderen)
- [**Nieuwe Rang:** The Bloods - **Captain** (Normale F6 Rang)]
- [**Nieuwe Rang:** The Bloods - **Bookkeeper** (Normale F6 Rang + Koop alle wapen mods (Alles kunnen tunen)]
- [**Nieuwe Rang:** The Bloods - **Chairman** (Normale F6 Rang)]

The Bloods - **Young Blood** (Normale F6 Rang - Niets veranderen)
The Bloods - **Thug** (Normale F6 Rang - Niets veranderen)

**Meeloop:**
The Bloods - **Runner**  (Niets aan veranderen)
The Bloods - **Recruit** (Niets aan veranderen)

### Wat lost deze feature op?

Progressie binnen onze gang

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zit erin na volgende herstart!
