### ISSUE TITLE
[Bug]: Sanchez Sport mist speedlimiter

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1861]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Sanchez Sport (sanchez2) heeft geen speedlimiter.

### Wat hoorde er te gebeuren?

Het voertuig hoort wel een speedlimiter te hebben.

### Wat veroorzaakt de bug?

Pak een Sanchez Sport en trek een wheelie. Nu kun je extreme snelheden behalen. 
![image](https://user-images.githubusercontent.com/92899337/213017098-f43faa94-c7b3-4587-8e53-90ad4227cf71.png)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Is opgelost na de restart!
