### ISSUE TITLE
[FEATURE]: garage bij kleermaker en ramenwassen

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1862]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

Een rode en groene cirkel bij de ramenwasser job en de kleermaker job plaatsen.

Voorkomt hopelijk een grote opstapeling van voertuigen.

Ramenwasser:

- [ ] rood: -175.05, -1377.29, 31,27
- [ ] groen: -179.88, -1380.22, 31.26

Kleermaker:

- [ ] rood: 685,61, -988.59, 23.26
- [ ] groen: 684.90, -983.47, 23.23

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Ramenwasser heeft al een garage bij het tankstation, zo'n 30 seconde lopen. Kleermaker ga ik even voor kijken
