### ISSUE TITLE
CCF parkeer plaats uitbreiding [FEATURE]: 

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#1863]
### Contact Details

Schmutz#8587

### Beschrijf zo duidelijk mogelijk de feature

We komen met een grote familie wat parkeerplekken te kort en de stad is al jaren bezig met de weg voor ons cafe. Wij zouden het super gaaf vinden als de weg gedicht kan worden en de parkeer plekken kunnen worden uitgebreid. Stel je voor allemaal prachtige packards op een rij
![STREET 2](https://user-images.githubusercontent.com/120605155/213283795-40a406be-38ba-4bb4-bf96-1e628d9832de.png)
![STREET 1](https://user-images.githubusercontent.com/120605155/213283997-c5fff491-e2d2-4ddd-a64f-2c0309fc52fc.png)

### Wat lost deze feature op?

ruzie over parkeer plekken, straatbeeld, klanten parkeer plaats beleid

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Na overleg hebben we besloten dat dit niet nodig is. Er zijn genoeg parkeer mogelijkheden.

**Comment by Donnycolombo** [comment]
> Na overleg hebben we besloten dat dit niet nodig is. Er zijn genoeg parkeer mogelijkheden.

> ik begreep dat oesewoes dit ook als een leuk project zou zien en helpt het straatbeeld verbeteren ipv een open stuk. Geen prio begrijp ik maar totaal niet uitvoeren zou toch jammer zijn
