### ISSUE TITLE
[Bug]: Mumble bug in de soprano MLO

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1866]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als jij in het MLO staat en je probeert met iemand buiten te praten (terwijl je binnen bent) hoor je degene niet, waardoor je vanaf binnen geen klanten via het raampje kan helpen. Dus je moet je klanten altijd via buiten helpen, is het mogelijk dat je ook iemand van buiten hoort als je binnen in het MLO staat? 

### Wat hoorde er te gebeuren?

Je hoort iemand te kunnen horen als je binnen staat en de andere persoon buiten het MLO (via het raampje).

### Wat veroorzaakt de bug?

Geen idee 😓 .

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Dit is al ongeveer 2 jaar een known issue, en een won't fix
