### ISSUE TITLE
[FEATURE]: Taxi salaris + rangen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1867]
### Contact Details

Timez#0003

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag een aanpassing willen toebrengen aan het salaris en de rangen binnen Uberpolis. Hierbij de veranderingen:

Wij willen in plaats van "Taxi Chauffeur - Chef" voor de rangen "Uberpolis - Chef". En dit graag bij alle rangen die wij hebben.
![image](https://user-images.githubusercontent.com/93401910/213600226-2882ca1e-7631-4cc4-a9a4-ce6c460428e0.png)

Ook zouden wij graag een aanpassing willen toebrengen aan 3 rangen:

- "Chef" aanpassen naar "Baas" (Rang nummer = 1000)
- "Recruitmentleider" aanpassen naar "Chef" (Rang nummer = 970)
- "Marketingleider" schrappen (Rang nummer = 960)

Ook zouden wij een aanpassing willen toebrengen aan het salaris binnen Uberpolis. Wij hebben binnen de leiding bij Taxi minder tijd om hersenlozen te vervoeren, dit is ter compensatie voor het werk dat wordt geleverd. 

Indienst Salaris:
[/setjob ID taxi 1000] Uberpolis - Baas: 1700
[/setjob ID taxi 970] Uberpolis - Chef: 1500
[/setjob ID taxi 950] Uberpolis - Manager: 1250
[/setjob ID taxi 900] Uberpolis - Recruiter: 950
[/setjob ID taxi 850] Uberpolis - Marketing: 950
[/setjob ID taxi 800] Uberpolis - Uber-1: 850
[/setjob ID taxi 750] Uberpolis - Uber-2: 800
[/setjob ID taxi 700] Uberpolis - Uber-3: 790
[/setjob ID taxi 650] Uberpolis - Uber-4: 780
[/setjob ID taxi 600] Uberpolis - Uber-5: 770
[/setjob ID taxi 550] Uberpolis - Taxichauffeur-1: 680
[/setjob ID taxi 500] Uberpolis - Taxichauffeur-2: 650
[/setjob ID taxi 450] Uberpolis - Taxichauffeur-3: 630
[/setjob ID taxi 400] Uberpolis - Taxichauffeur-4: 620
[/setjob ID taxi 350] Uberpolis - Taxichauffeur-5: 600
[/setjob ID taxi 300] Uberpolis - Regiotaxi-1: 580
[/setjob ID taxi 250] Uberpolis - Regiotaxi-2: 550
[/setjob ID taxi 200] Uberpolis - Regiotaxi-3: 530
[/setjob ID taxi 100] Uberpolis - Regiotaxi-4: 520
[/setjob ID taxi 0] Uberpolis - Uitzendkracht: 500

Uitdienst Salaris:
[/setjob ID offtaxi 1000] Uberpolis - Baas: 1600
[/setjob ID offtaxi 970] Uberpolis - Chef: 1400
[/setjob ID offtaxi 950] Uberpolis - Manager: 1150
[/setjob ID offtaxi 900] Uberpolis - Recruiter: 650
[/setjob ID offtaxi 850] Uberpolis - Marketing: 650
[/setjob ID offtaxi 800] Uberpolis - Uber-1: 500
[/setjob ID offtaxi 750] Uberpolis - Uber-2: 480
[/setjob ID offtaxi 700] Uberpolis - Uber-3: 450
[/setjob ID offtaxi 650] Uberpolis - Uber-4: 430
[/setjob ID offtaxi 600] Uberpolis - Uber-5: 400
[/setjob ID offtaxi 550] Uberpolis - Taxichauffeur-1: 360
[/setjob ID offtaxi 500] Uberpolis - Taxichauffeur-2: 350
[/setjob ID offtaxi 450] Uberpolis - Taxichauffeur-3: 340
[/setjob ID offtaxi 400] Uberpolis - Taxichauffeur-4: 330
[/setjob ID offtaxi 350] Uberpolis - Taxichauffeur-5: 320
[/setjob ID offtaxi 300] Uberpolis - Regiotaxi-1: 280
[/setjob ID offtaxi 250] Uberpolis - Regiotaxi-2: 260
[/setjob ID offtaxi 200] Uberpolis - Regiotaxi-3: 240
[/setjob ID offtaxi 100] Uberpolis - Regiotaxi-4: 220
[/setjob ID offtaxi 0] Uberpolis - Uitzendkracht: 200

### Wat lost deze feature op?

Meer duidelijkheid in de rangen van Uberpolis. Ook namen wij hier direct het nieuwe salaris in mee.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Lonen en namen zijn aangepast, enkel het uberpolis gedeelte voor de rank en het verwijderen van marketingleider moet nog even wachten.

**Comment by Chang-nl** [comment]
> enkel het uberpolis gedeelte voor de rank

Hey @Attomn, wat moet er nog precies gebeuren? Althans wat bedoel je met bovenstaand bericht?

**Comment by Chang-nl** [comment]
Hey @TedeaTaxi,

De Marketingleider rang is nu weg!

**Comment by ExoticaTDA** [comment]
> > enkel het uberpolis gedeelte voor de rank
> 
> Hey @Attomn, wat moet er nog precies gebeuren? Althans, wat bedoel je met bovenstaand bericht?

Het enige wat nu nog aangepast moet worden is dat "Taxichuaffeur - Regiotaxi-4" veranderd word in "Uberpolis - Regiotaxi-4" 

En dit dan voor alle rangen :)

**Comment by TedeaTaxi** [comment]
Zoals meneer Exotica (Kay) het zegt moet inderdaad enkel Uberpolis voor de taxi rangen komen te staan. Verder zijn wij erg tevreden!

**Comment by niekschoemaker** [comment]
> > > enkel het uberpolis gedeelte voor de rank
> > 
> > 
> > Hey @Attomn, wat moet er nog precies gebeuren? Althans, wat bedoel je met bovenstaand bericht?
> 
> Het enige wat nu nog aangepast moet worden is dat "Taxichuaffeur - Regiotaxi-4" veranderd word in "Uberpolis - Regiotaxi-4"
> 
> En dit dan voor alle rangen :)

Dit heb ik aangepast
