### ISSUE TITLE
[FEATURE]: Commissaris rang toegang geven tot volledige politie /eup

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1868]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

De rang Commissaris (grade 7) toegang geven tot de volledige politie /eup.

### Wat lost deze feature op?

Zorgt ervoor dat personen met de Commissaris rang op die rang gezet kunnen worden i.p.v. de rang van hun neventaak en ze dus de juiste salarissen e.d. kunnen ontvangen. Uiteraard low priority.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @ARJ3N,

Bedankt voor het aanmaken van de github issue!

Na de herstart is het aangepast!
