### ISSUE TITLE
[FEATURE]: Rangen aanpassing

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1870]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden nog graag de salarisen aangepast willen hebben, aangezien dit voor ons logisch lijkt.
Dit gaat over de rangen "red" en "offred"
De bedoeling is dat ze in en uit dienst geewoon het zelde verdienen, aangezien in en uitdienst puur is om bepaalde dingen uit te schakelen.

- [ ] Salarisen aanpassen van R3D in en uitdienst ("red" & "offred") naar;
Stagiaire - €300,-
Junior Medewerker - €400,-
Medior Medewerker - €500,-
Senior Medewerker - €600,-
Manager - €700,-
CEO - €800,-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
Is er een eigen pot waar dit vanuit betaald wordt ?

**Comment by Rowdeeee** [comment]
Nee, er is geen iegen pot waaruit dit betaald word. Dit word het zelfde betaald netals een ondernemer job.

**Comment by Ljosfari** [comment]
Dan is het ook een beetje vreemd om in en uit dienst hetzelfde loon te geven. Aangezien het dus niet uit de pot van de cardealer gaat, maar volledig door de society (gemeente geld) betaald wordt.

**Comment by Rowdeeee** [comment]
De rede waarom er een "Uit dienst" is, omdat er een f6 menu aan gekoppeld zit. Dit gaat fout samen met een andere eventuele rangen waar een eventuele f6 aan vast zit. Ook is het "Uit dienst" ervoor om eventuele meldingen van onze meldkamer uit te zetten, aangezien we op deze rang meerdere bedrijven hebben lopen dan enkel de cardealer, ook de loterij, rental, casino, complex. terwijl soms deze meldingen van de meldkamer niet binnen hoeven te krijgen, aangezien deze bedoeld zijn voor het sleephuis.

Snap je een beetje wat ik bedoel? Anders misschien handig dat ik dit je in call uit leg 😅

**Comment by Ljosfari** [comment]
De salarissen kunnen gelijk gezet worden aan het salaris van de ondernemer rangen.

Of de aangevraagde salarissen. Maar dan wel uit een eigen pot. Net als bij de taxi etc.

**Comment by Rowdeeee** [comment]
En dat bij het Nieuws en Radio? Daar is dat dan toch ook niet?

**Comment by Ljosfari** [comment]
Nee maar die kunnen ook geen geld verdienen. Jullie hebben het sleephuis, autoverkoop, en straks de krasloten

**Comment by Ljosfari** [comment]
Nieuws en radio kunnen zelf geen verdiensten maken om het loon van te betalen

**Comment by Rowdeeee** [comment]
Oke en dat hebben we om rp te maken in de server? Waar de server voor bedoeld is naar mijn mening? We verdienen hier niet bepaald de jackpot mee en lijkt mij dat dit best beloond mag worden na 2,5 jaar werk. 

Vind het ook een beetje jammer dat de taxi hier bij word gehaald dat hun een "Eigen" inkomen creeeren terwijl naar mijn mening dat niet echt klopt. Als je het zo bij kijkt, de taxi pot verdient minimaal €1600,- aan een ritje wat gereden word van 2,5 km en waar ze dan 1 minuut mee bezig zijn. Dit betekent dat als er 1 persoon is de 1 uur herselozen rijd dat de taxipot out of nowhere €96.000,- binnen haalt. Stel er doen dit 5 mensen op een dag (wat zoizowel elke dag gebeurd) Komt er dus per dag minimaal €480.000,- binnen in de taxi pot. Dit zonder RP en met zeer onrealistise bedragen als je het mij vraagt, aangezien het normalte tarief bij hun 100,- per km is dus eigenlijk maar in totaal 250 euro binnen zou moeten komen aan een ritje van 2,5km, dus jah dan kunnen hun de salarisen wel opeens een stuk hoger zetten jah..

Dus daarom lijkt mijn vraag met deze salarisen geen raar voorstel... Aangezien wij best veel RP neer zetten voor meerdere mensen en ik niet om een optie vraag om geld te gaan grinden door hersenlozen te rijden.

**Comment by Ljosfari** [comment]
Ik snap het. Maar voor rp heb je toch niet perse een hoger salaris nodig dan de ondernemers rangen?
Het staat erg krom als we jullie in en uit dienst hetzelfde salaris gaan geven ook.
Het is dan volledig gefinancierd door de gemeente. En het is wel een onderneming die winst kan maken.

**Comment by Rowdeeee** [comment]
Perse nodig? Nee klopt, maar naar mijn mening is dit geen grote/ rare vraag na 2,5 jaar werk met de bedrijven om veel RP de stad in te brengen.

Als je dus weet waarom het in/uit dienst is lijkt het mij niet raar om de salarisen gelijk te hebben aan het in dienst. Mij part veranderen we de naam "UitdienstR3D" naar "Offline R3D". Dan klinkt het al anders.

Wij maken inderdaad winst, maar dit is totaal niet veel, aangezien wij niet gericht zijn op volle bakken met geld te maken maar om veel RP neer te zetten.
