### ISSUE TITLE
[FEATURE]: Winkel Cirkeltje

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1872]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Er moet nog een cirkel geplaatst worden voor krasloten. Deze mag gekoppeld worden aan de rang " red 1000 " (red boss)

- [x] Locatie van Kras - loten cirkel
vector3(-781.44, -209.30, 37.15)
heading: 171.73
https://prnt.sc/muf7L4dfYFcb

- [x] De cirkel koppelen aan de rang " red 1000 " (red boss)
### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Rowdeeee,

Bedankt voor het aanmaken van de github issue!

Na de herstart zit de feature erin op de aangegeven locatie!
