### ISSUE TITLE
[FEATURE]: Winkel Cirkeltje

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1873]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag nog een personlijk winkeltje voor de rang " red " willen krijgen waar wij op de volgende locatie het volgende kunnen kopen.

- [ ] Item shop:
x: -780.34 y: -231.27 z: 37.15 h: 74.27
Met de volgende items
Zaklamp - €50,-
Band - €50,-
Brandblusser - €500,-
Jerrycan - €350,-
Portofoon - €400,-

- [ ] Deze koppelen aan de volledige rang van " red "

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Rowdeeee,

Is hier toestemming voor?
