### ISSUE TITLE
[FEATURE]: Nieuwe Emotes 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1874]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Ik mocht deze github maken van StoffigKontje met de vraag als er extra emotes toegevoegd kan worden. 
https://www.youtube.com/watch?v=HveuLJrfcLs zijn er leuke emotes zoals BBQ als vrouw (wat niet kan atm alleen voor mannen) en extra equipment voor TOS : TTV1).

https://youtu.be/HveuLJrfcLs?t=101 vanaf 1:41 leuke prop emotes zoals carry food bags kan leuk zijn voor RP, verschillende dozen voor biertjes kan ook leuk zijn voor feesten bij exotica bijvoorbeeld of ergens anders  😛 ? Andere soorten dienbladen, zelfs dienbladen die je per twee kan dragen 👀. Zijn ook veel nieuwe Ped emotes wat super leuk is en dat zouden we graag ook zien in de stad 😄 .

Hopelijk is dit mogelijk, zo niet dan is het maar zo helaas 😞 .

### Wat lost deze feature op?

Leuke toevoeging aan de emotes en dat zal ook meer RP toevoegen aan onze stad! 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
> Hey @CalRayy,
> 
> Waar kunnen we de resources die in de video geshowcased worden vinden?

https://whitecustom.tebex.io/package/5473142

**Comment by Tom974** [comment]
Nieuwe emotes wordt aan gewerkt.
