### ISSUE TITLE
[FEATURE]: derde job

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1875]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

We hebben besproken in staff overleg dat er een derde job mag toegevoegd worden aan de stad, indien dit haalbaar is voor de development.  Aangezien dit super handig is voor vele mensen die langs hun tweede job ook andere dingen willen doen zoals uitzendkantoor jobs of nog een extra limited job.

### Wat lost deze feature op?

Nog een slot voor een job, extra RP.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
Dit moet door ons even bekeken worden of het mogelijk is.

**Comment by niekschoemaker** [comment]
Nee en nee.
Leer keuzes maken in het leven, hoort erbij.
