### ISSUE TITLE
[FEATURE]: Staff meos second job zien

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1876]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

We hebben besproken in staff overleg dat er in de staff meos gezien mag worden wat iemand zijn second job is (en de derde als die komt). Dit zodat staff weet wat de rangen zijn om ze eventueel weg te halen etc. Hopelijk is dit haalbaar, zo niet dan niet helaas.

### Wat lost deze feature op?

 Zodat staff weet wat de rangen zijn om ze eventueel weg te halen etc.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @CalRayy,

Bedankt voor het aanmaken van je suggestie. 

De feature is geïmplementeerd alleen moet de webserver even geüpdate worden met de nieuwe build. Dit zal binnenkort zijn en dan zit de feature erin!
