### ISSUE TITLE
[Bug]: 2 dezelfde postcode's op de map 

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#1878]
### Contact Details

Yohandessu#3314

### Wat gebeurde er?

Er staan 2 dezelfde postcode's op de map. Als je nu dus postcode 818 invult krijg je dus 1 van de 2. Een is in sandy en 1 is in humane labs.  
![image](https://user-images.githubusercontent.com/103584419/214019778-c6842945-4ec2-4534-b97b-a349848433ad.png)

### Wat hoorde er te gebeuren?

Dat 818 weer 1 postcode word en niet 2.

### Wat veroorzaakt de bug?

Dat er gekozen word tussen 2 dezelfde postcodes wat best vervelend kan zijn. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dit geldt overigens ook voor postcode 852, als je dan toch bezig bent :P

(Ook in sandy en ongeveer in het midden van de map)

![image](https://user-images.githubusercontent.com/55812394/214674590-93c270a2-0b21-451f-be37-d042cc18939b.png)
![image](https://user-images.githubusercontent.com/55812394/214674720-f75bb311-4a20-4fd2-a3f9-a21b61bc2f86.png)
