### ISSUE TITLE
[FEATURE]: Extra command staffreports zichtbaar maken.

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#1879]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kan je reports uitschakelen via /reports_settings toggle. Het verzoek is gebleken uit staffoverleg van 15-01-2023 dat het handig is om de reports die staff maken wel nog zichtbaar te hebben.
Echter hebben wij in het staffteam een heleboel streamers en is het dus niet handig om dit toe te voegen in de normale toggle.

Het verzoek is dus om een extra command te maken om alle reports te toggelen, behalve de reports die binnen komen vanuit een stafflid.

Dus de /reports_settings toggle blijft zoals het is

extra command:
/reports_settings staff of /reports_staff dan alleen reports die staffleden maken zichtbaar hebben.

### Wat lost deze feature op?

Dat als staffleden offduty staan nog wel eventueel bij kunnen springen bij staffleden die hulp nodig hebben of staflfeden die vragen hebben. Ook voor de hogere staffleden kunnen dan een heal, revive of permban geven terwijl zij offduty zijn en krijgen zij nog wel de staffreports binnen om te helpen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @DaanDeWit,

Bedankt voor het aanmaken van de github issue!

De feature zit er naar alle waarschijnlijkheid na de herstart in. Let wel op: Ik heb deze feature nauwelijks kunnen testen dus het zou kunnen dat het nog niet helemaal werkt zoals zou moeten. Mocht dit het geval zijn zou je dit kunnen laten weten? Alvast bedankt!

**Comment by DaanDeWit** [comment]
helemaal goed, ik laat het weten!

**Comment by Chang-nl** [comment]
Hey @DaanDeWit,

Na de volgende herstart is het volledig gefixt en doorgetest. ZIjn er alsnog bugs dan hoor ik het graag.
