### ISSUE TITLE
[FEATURE]: CCF Cirkel wapenopslag

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#1880]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

![image](https://user-images.githubusercontent.com/68959019/214109202-d02a6db5-d9d6-4363-aa62-e4b9468084c7.png)

Op deze locatie en coords een cirkel voor de volgende cirkel capiciteiten:
- Wapenopslag
- Sla Wapen op
- Item Winkel
- Koop wapen Mods
- Wapen Winkel
- Hernoem Wapens
(dus het armory menu)

### Wat lost deze feature op?

Hierdoor is er een plek (waar de MLO ook op gebouwd is) voor wapen inkoop en verkoop. Dat maakt het verkopen van wapens realistischer op die plek en binden ze er ook meer RP aan. + de MLO heeft hier een plek voor deze cirkel op gebouwd.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @DaanDeWit,

Bedankt voor het aanmaken van de github issue!

Moet er een extra armory toegevoegd worden of moet er een bestaande cirkel van plaats veranderd worden?

**Comment by DaanDeWit** [comment]
@Chang-nl extra armory! :)

**Comment by Chang-nl** [comment]
Hey @DaanDeWit,

Dankjewel voor de snelle reactie!

Na de herstart zit er een extra cirkel op de aangegeven locatie!
