### ISSUE TITLE
[Bug]: Eiland spectaten en tp'en

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1881]
### Contact Details

Ljosfari#3575

### Wat gebeurde er?

Als de helpers tp eiland gebruiken of naar een speler tp'en naar het eiland vallen ze door de map omdat het eiland niet inlaad.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Ljosfari,

Bedankt voor het aanmaken van de issue!

Ondertussen is de issue opgelost. Volgende keer graag de issue sluiten wanneer deze via andere kanalen opgelost is. Alvast bedankt!
