### ISSUE TITLE
[FEATURE]: Bewusteloos logging

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1882]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk om een bewusteloos log (of toegevoegd worden aan kill loggs ) te maken en door wie je bewusteloos bent geslagen? Is handig voor dingen te onderzoeken voor reports en tickets 😄.

### Wat lost deze feature op?

Is handig voor staff om dingen te onderzoeken voor reports en tickets 😄.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @CalRayy,

Wanneer iemand de 150 hp bereikt dan is degene bewusteloos en dit kan gewoon gecheckt worden in de combatlog.
