### ISSUE TITLE
[FEATURE]: Logo toevoegen aan criminal job

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1884]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Logo toevoegen aan criminal job. Al met Chang over gehad, hij heeft het logo in DM. :)

### Wat lost deze feature op?

Job heeft momenteel geen logo.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @ARJ3N,

Bedankt voor het aanmaken van de github issue!

Na de volgende herstart zit het logo erin!
