### ISSUE TITLE
[Bug]: Werkvoertuigen kunnen niet met lampje teruggezet worden

### ISSUE THREAD

**Issue by DylanPeys** [Tedeapolis/development#1885]
### Contact Details

dyl6n#5310

### Wat gebeurde er?

Zodra een werkvoertuig een lampje heeft, kan dit voertuig niet terug ingeleverd worden. Dan krijg je de melding dat het voertuig schade heeft en je eerst langs de ANWB moet. Dit was voorheen niet zo en hierdoor komen er altijd onnodig veel lege bussen te staan bij de ramenwasser job. Zover ik weet is het probleem bij de ramenwasser job maar mogelijk dat het bij elke job zo is.

### Wat hoorde er te gebeuren?

Dat je je werkvoertuig kunt inleveren, en indien er schade opzit, dit van je borg afgaat. 

### Wat veroorzaakt de bug?

Als je voertuig schade heeft kan je bus niet meer ingeleverd worden.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @DylanPeys,

Is dit alleen een probleem bij de ramenwasser baan?

**Comment by Chang-nl** [comment]
Hey @DylanPeys,

Het is voor de ramenwasser nu aangepast! Je zal nu moeten betalen mocht je schade aan het voertuig hebben toegebracht.
