### ISSUE TITLE
[EUP]: Steekvest

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1889]
### Contact Details

Wilma Wonka#4312

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

voor de Groen OVD steek vest en of je dan ook gelijk de MMT Steekvest erbij wilt zetten.

Ik weet niet of dit mogelijk is. 
Dit is een vraag geweest die is gekomen uit de algemene vergadering van de Ambulance

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Hey @WilmaWonka1985  
Ambulance heeft 1 steekvest en heeft verder geen toegevoegde waarde, hierbij lijkt het me ook onnodig dat de ovdg nog een apart vest zou  moeten krijgen. degene die zij nu kunnen nemen is het blauwe steekvest. Heb daar helaas ook geen slots meer voor over.

**Comment by WilmaWonka1985** [comment]
Dank je wel voor het toch te willen bekijken. Ik ga dit door geven!
