### ISSUE TITLE
[FEATURE]: Exotica Logo's

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1891]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Atm hebben wij bij Exotica 3 verschillende logo's wat best verwarrend is, zo hebben we 1 op het gebouw, een andere bij onze rang en weer een andere op de kaart. Graag zou ik alle 3 de logo's hetzelfde hebben. Het logo die ik wil is deze: 
![Exotica](https://user-images.githubusercontent.com/120292087/215151042-f3ff8520-0125-4740-ac29-11c6106a9bb2.png)

De logo's die aangepast moeten worden zijn de volgende: 

- Logo bij je job in en uit dienst
- Logo op de kaart

### Wat lost deze feature op?

Dit maakt het een stuk overzichtelijker

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed

**Comment by CorruptSausage** [comment]
Map logo moet nog even aangepast worden.

**Comment by Attomn** [comment]
Is gefixt!
