### ISSUE TITLE
[FEATURE]: Taxi - Taxichauffeurs volgen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1893]
### Contact Details

Timez#0003

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid krijgen om te zien waar onze chauffeurs zich bevinden op de kaart. De afgelopen tijd hebben wij vaak het idee dat er af en toe chauffeurs aan het money farmen zijn. Op deze manier kunnen wij er achter komen of een chauffeur zich daadwerkelijk bezig houdt met Taxi werkzaamheden. Wij hadden vernomen dat andere overheids jobs hier gebruik van (kunnen) maken. Graag zouden wij dit ook willen. 

### Wat lost deze feature op?

Deze feature zal er voor zorgen dat wij kunnen handhaven op chauffeurs die mogelijk money farmen en zich dus niet bezig houden met de werkzaamheden die zij horen te verrichten als Taxi chauffeur. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Na stemming binnen HR zijn we tot de conclusie gekomen dat dit niet toegevoegd gaat worden. Er zijn genoeg andere oplossing, ander dan blips zoals /onduty taxi en een report aanmaken met vragen wat iemand aan het doen is.
