### ISSUE TITLE
[FEATURE]: Outlaw MLO en kleding uit de server verwijderen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1894]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Custom gemaakte kleding en de MLO van de Outlaws graag verwijderen uit de server.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
MLO, Cirkel voor muziek en sloten zijn al verwijderd. @DevvTDA is aan het kijken naar de kledij.

**Comment by DevvTDA** [comment]
Github commits zijn aangemaakt zodat de kleding eruit gehaald wordt :)
