### ISSUE TITLE
[FEATURE]: Timer grote bank

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#1895]
### Contact Details

Cazorla#7638

### Beschrijf zo duidelijk mogelijk de feature

Momenteel wordt de grote bank vaak gecamped. Er staat hier een timer op van 48 uur. Dus na 48 uur staan de mensen vaak weer bij de grote bank. Kan dit veranderd worden dat er een variabelle tijd aan wordt gekoppeld zoals 38 tot 58 uur.

### Wat lost deze feature op?

Het campen van de grote bank (verdienmodel)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @TDALarry,

Dit is al een bestaande feature!
