### ISSUE TITLE
[Bug]: Exotica Bus niet meer bruikbaar

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1896]
### Contact Details

Dyon#9999

### Voertuig model

mule2

### Omschrijf de bug

Als je iets in de kofferbak van de transport bus wilt leggen geeft hij een error.

Clip:
https://medal.tv/games/gta-v/clips/SXTLSQ4dVSTBI/d1337BeRjHGm?invite=cr-MSx0OEksNDg1Nzc3ODMs

### Repro

Je opent de kofferbak en probeert er iets in te leggen.
Ik weet niet of het verschil maakt of je de Exotica rang wel of niet hebt. Het werkt in ieder geval **niet** als je de Exotica rang wel hebt.

### Normaal gedrag

Je hoort iets in je voertuig te kunnen leggen. Op deze manier kunnen wij namelijk geen inkopen meer doen.

Logs: 
[CitizenFX_log_2023-01-30T010031.log](https://github.com/Tedeapolis/development/files/10532311/CitizenFX_log_2023-01-30T010031.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
is gefixed
