### ISSUE TITLE
[FEATURE]: plasmakart blip weghalen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1897]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

![image](https://user-images.githubusercontent.com/101106299/215546237-2a8e4db1-d4d9-4c24-8205-bfb23c77774f.png)
De blip staat er nog, maar de MLO zelf is al weg. Is het mogelijk om de blip te verwijderen?

### Wat lost deze feature op?

onnodige blip.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @CalRayy,

Na de herstart is de blip weg!
