### ISSUE TITLE
[FEATURE]: Commissaris rang politie aanpassingen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1898]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Volgende dingen toevoegen aan de Commissaris rang:

- [x] Toegang tot porto 118.
- [x] Toegang tot DSI en recherche meldkamer op de telefoon.
- [x] Toegang tot alle wapens in de wapenwinkel van de politie.
- [x] Toegang tot alle voertuigen in de voertuigwinkel van de politie.
- [x] Toegang tot /lightbar.

### Wat lost deze feature op?

Maakt de rang bruikbaar voor personen die ook een neventaak hebben.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zou na volgende herstart goed moeten staan.
