### ISSUE TITLE
[BurgerRaad]: Loop stijlen/Moods opslaan

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1899]
### Contact Details

Endorsite#0001 & Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

 - [x] Loop Stijlen opslaan

Op dit moment heb je heel veel leuke loop stijlen alleen het jammere hier van is als je 1 keer crouched ben je die alweer kwijt. 

Loop stijlen opslaan zodat je altijd dezelfde loopstijl kan hebben ook als je opnieuw de stad in komt of crouched. Nu loopt iedereen het zelfde en er zijn niet veel mensen met een aparte loop stijl. Eventueel gaat dit dus zorgen dat er meer mensen anders gaan lopen en dat maakt het weer een stukje anders.

- [x] Moods opslaan

Hetzelfde geld voor moods, je hebt verschillende moods in de stad maar ook die verdwijnen als je opnieuw de stad in komt. 
Kijken of er een oplossing is dat je ook die permanent kan houden

### Wat lost deze feature op?

Meer unieke karakters in de stad. Mensen kunnen echt een karakter vormen aan een loopstijl/mood

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Dit zou moeten werken.

Voor alsnog is het niet volledig ondersteund, dus het kan zijn dat hier en daar je movement weer reset, maar dan zou een simpele handjes omhoog en weer naar beneden je walking style weer terug moeten zetten, dus als makkelijkheidje om het snel weer terug te krijgen.

In principe zet elke emote die je doet jeweer terug in de walking style.

Verder is een belangrijke dat je dus je walking style weer kunt resetten met "/walk reset"

**Comment by niekschoemaker** [comment]
Zit erin, inclusief mood nu.
