### ISSUE TITLE
Anwb aanneem menu

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#19]
Het aanneem menu van de anwb is kapot wij zien daar geen spelers tussen staan.

![unknown](https://user-images.githubusercontent.com/68514420/87931781-9dcd5a80-ca8a-11ea-9e22-03c44b68b74b.png)

**Comment by Willem-Dekker** [comment]
is dit nog steeds zo?

**Comment by DeStefanoKiller** [comment]
> is dit nog steeds zo?

Het menu werkt weer danku <3

**Comment by Willem-Dekker** [comment]
top, sluit ik de issue
