### ISSUE TITLE
[BurgerRaad]: Standaard volgorde itemshop voor officiële gangs

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1900]
### Contact Details

RalphVidus#0836 & Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

In de item shop van de officiële gangs heb je op dit moment elke keer wanneer je relogged een nieuwe volgorde van items.
Dit is erg vervelend doordat je soms het verkeerde item koopt, doordat je of niet goed oplet of dat je eerst een normale pistol clip op die plek had staan.

Wij hopen dat dit aangepast kan worden naar een standaard volgorde zodat er minder verwarring is tijdens het kopen van items.

### Wat lost deze feature op?

Het perongeluk kopen van verkeerde items.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
fixed
