### ISSUE TITLE
[BurgerRaad]: Meerdere Jerrycans/Parachutes opzak kunnen dragen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1901]
### Contact Details

RalphVidus#0836 & Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag de mogelijkheid zien om meerdere Jerrycans/Parachutes te kunnen dragen. 

### Waarom zouden we dit willen?
De reden dat we dit graag willen zien is omdat je soms meer dan een uur bezig bent met heen en weer lopen als je de voorraad bij wilt vullen van je gang opslag. 

### Hoe wil je dit mogelijk maken?
Hoe we dit in gedachten hadden is dat je van jerrycans en parachutes een item maakt die je kan gebruiken. Zodra je het item gebruikt krijg je hem als wapen. Om abuse te voorkomen kan je hier misschien een emote aan linken die een aantal seconden duurt wanneer je hem gebruikt, zodat je in achtervolgingen niet 5 parachutes of jerrycans kan gaan gebruiken.

### Wat lost deze feature op?

Dat je soms uren bezig bent met heen en weer lopen om je opslag bij te vullen omdat je elke keer maar 1 jerrycan & 1 parachute kan pakken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
niet mogelijk
