### ISSUE TITLE
[BurgerRaad]: Drugs percentage ook omhoog laten gaan bij quicksellen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1902]
### Contact Details

ALX#9953 & Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Vele groepen komen op het punt dat je minder gaat plukken en alleen gaat aannemen van klanten. Omdat je op deze manier niet zelf plukt, gaat je drugs percentage ook niet omhoog. Het lijkt mij interessant om daar verandering in te brengen. 

### Wanneer **wel** omhoog:
- plukken (eiland/land)
- quicksellen van drugs

### Wanneer **niet** omhoog:
- Het verwerken van drugs in de loods als je in 1 of meerdere zit 
- Huis aan huis verkoop/kloplocaties (omdat het anders misschien te snel gaat?)

### Wat lost deze feature op?

Dat mensen die drugs vooral aannemen ook progressie krijgen in hun drugs percentage

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done door @niekschoemaker
