### ISSUE TITLE
[BurgerRaad]: Outfits verwijderen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1903]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Mij leek het een goed idee om een optie toe te voegen aan bijvoorbeeld kledingwinkels en/of basic-fat waar je opgeslagen outfits kan verwijderen. Als brave burger heb je namelijk niet echt wat aan appartementen want wij hoeven vaak niks op te bergen ergens.

Op dit moment word je eigenlijk verplicht een appartement aan te schaffen om je outfits te kunnen verwijderen.
Als je op openbare plekken je outfits aan kan trekken lijkt het me meer dan logisch als je ze daar ook weg kan gooien.

### Wat lost deze feature op?

Dat je niet meer verplicht word een appartement aan te schaffen om je outfits te verwijderen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @ExoticaTDA,

Na de herstart zit de feature erin!
