### ISSUE TITLE
[Bug]: Helm zorgt voor minder damage bij headshots

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1905]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Een helm op hebben zorgt voor aanzienlijk minder damage bij headshots door weapon_sniperrifle.

### Wat hoorde er te gebeuren?

Hoort een one-shot te zijn.

### Wat veroorzaakt de bug?

Doe een helm op en laat iemand je op je hoofd schieten met een weapon_sniperrifle.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
fixed
