### ISSUE TITLE
[BurgerRaad]: Nieuwe unmarked garage

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1906]
### Contact Details

Zevenhuis#7777 & Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Bij de burger raad hebben we het gehad over de zware lagspikes bij Sopranos Taco's
In dat gebied heb je een aantal dingen zitten. Zo heb je Sopranos Taco's waar gemiddeld 5+ auto's staan. Een straat hier tegenover heb je Baretto Kurabu waar soms 5+ auto's staan. Naast Sopranos heb je Valhalla MC waar gemiddeld 5+ motoren staan.

Wij hebben het toen gehad over een unmarked garage zodat de mensen van Baretto en Soprano's makkelijk hun auto weg kunnen zetten en zo een hoop lag voorkomen kan worden.

### Groene Cirkel
![image](https://user-images.githubusercontent.com/120292087/215628894-fd5868c5-2b6e-48c6-a342-025d7dfd9a59.png)

### Rode Cirkel
![image](https://user-images.githubusercontent.com/120292087/215628955-9d97752b-b3f7-4d60-b89a-9831b1ba6c69.png)

### Wat lost deze feature op?

Dit zorgt er voor dat de lag op de weg richting 2e hands een stuk minder word.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
staat al een issue voor open

**Comment by JaylinFerluci** [comment]
@Ljosfari dat is een andere soort garage die open staat. Die garage is alleen voor Soprano's Taco's Personeel om deel auto's te hebben. Zodat het personeel de foodtrucks kunnen pakken met grantkeys

**Comment by ExoticaTDA** [comment]
![image](https://user-images.githubusercontent.com/120292087/219986181-fe716fdc-dbff-4f48-a9c3-695a4c7f3846.png)


Is wel hard nodig denk ik :)
