### ISSUE TITLE
[BurgerRaad]: Startpunt voor nieuwe spelers veranderen naar het vliegveld

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1907]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Ongeveer een jaar geleden waren er foto's van een nieuw vliegveld in Tedeapolis en ik denk dat als dit ooit door gezet word het heel goed zou zijn voor de stad. Zo kregen we van Ambu leiding ook te horen dat hun dagelijks last hebben van nieuwe spelers/kale batsen. die hun ambulances stelen het moment dat ze iemand uit hun ambu aan het halen zijn. En zou dit voor Taxi ook perfect zijn aangezien nieuwe mensen dan meer geneigd zijn een taxi melding te maken om naar de stad te komen (hierdoor worden ze dus geforceerd de RP aan te gaan). Ook is het een stuk logischer dat als je de stad voor het eerst binnen komt vliegen je aankomt bij het vliegveld.

Ik hoop dus dat het idee van een nieuw vliegveld doorgezet kan worden omdat dit naar mijn mening een aantal problemen zou oplossen.

![image](https://user-images.githubusercontent.com/120292087/215630466-10e6758d-8c49-45f6-8b29-b8b848da5453.png)

### Wat lost deze feature op?

De overlast die de ambulance heeft van nieuwe spelers/kale batsen. En dat nieuwe mensen geforceerd worden RP aan te gaan doormiddel van een taxi bellen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
is dit vanuit burgerraad ? graag er even bij vermelden ?

**Comment by Ljosfari** [comment]
mlo is er nog niet
