### ISSUE TITLE
[FEATURE]: Drinken bij Soprano's taco's

### ISSUE THREAD

**Issue by JaylinFerluci** [Tedeapolis/development#1908]
### Contact Details

Jaylin Ferluci#5959

### Beschrijf zo duidelijk mogelijk de feature

Ik heb in een ticket wat drinken gevraagd en dat mag worden toegekend

Om wat voor drinken gaat het dan:

Chocomel
Cola
Bier

Het zou in de cirkel erbij gevoed moeten worden voor drinken 
![image](https://user-images.githubusercontent.com/121064556/215840456-edc7067c-40cb-432d-bbdb-9a7904e7e4ac.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @JaylinFerluci, 

Zit erin na de aankomende herstart!

**Comment by JaylinFerluci** [comment]
Ik heb het nog niet gezien komt het na een update moet het ook in de Github staan ?

**Comment by Tom974** [comment]
> Ik heb het nog niet gezien komt het na een update moet het ook in de Github staan ?

Nee, maar het zit er nu wel in :"P

**Comment by JaylinFerluci** [comment]
> > Ik heb het nog niet gezien komt het na een update moet het ook in de Github staan ?
> 
> Nee, maar het zit er nu wel in :"P

![image](https://user-images.githubusercontent.com/121064556/230490543-f72ee4fc-5eba-4c99-86f7-74a4e85be4e9.png)

Ik mis nog de bier zou dat nog mogelijk kunnen zijn ?

Ik heb wel de chocomel en cola gekregen

**Comment by Tom974** [comment]
> > > Ik heb het nog niet gezien komt het na een update moet het ook in de Github staan ?
> 
> > 
> 
> > Nee, maar het zit er nu wel in :"P
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/121064556/230490543-f72ee4fc-5eba-4c99-86f7-74a4e85be4e9.png)
> 
> 
> 
> Ik mis nog de bier zou dat nog mogelijk kunnen zijn ?
> 
> 
> 
> Ik heb wel de chocomel en cola gekregen

Oei, zal die zo ook even toevoegen

**Comment by Tom974** [comment]
Zitten er als het goed is nu ook in @JaylinFerluci
