### ISSUE TITLE
[FEATURE]: Aanpassingen pluksysteem

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1909]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Aanpassingen aan het pluksysteem:

- [x] Wietpluk verwijderen van Narcopolis.
- [x] Meth en cocaïnepluk naar één per stuk op Narcopolis.
- [x] De gebieden van de pluklocaties wordt over een groter gebied verspreid.
- [x] De methpluk op mainland wordt weer toegevoegd.
- [ ] ~~De totale hoeveelheid drugs die je kunt plukken blijft hetzelfde.~~
- [ ] ~~Er zal nadat een pluk op Narcopolis inactief is geworden een lange periode van inactiviteit achteraan komen. Deze~~ ~~periode tussen de tijd dat de pluklocaties actief zijn zal random zijn tussen de 10 en de 14 uur.~~
- [ ] ~~Zowel de meth als cocaïnepluks op Narcopolis zullen tegelijk actief worden, met dus de random timer er tussen van 10-14 uur.~~

### Wat lost deze feature op?

Dit zorgt ervoor dat spelers weten dat nadat een pluk actief is geweest op Narcopolis deze een lange tijd niet meer actief zal worden. Hierdoor zullen spelers meer gaan roleplayen i.p.v. enkel op het eiland wachten totdat er weer wat te plukken valt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hoe de pluks werken, ga ik op het moment even hetzelfde houden, echter zal ik de andere aanpassingen wel doorvoeren.

**Comment by Tom974** [comment]
Heb een paar aanpassingen gedaan. Dit proberen we eerst even uit.
