### ISSUE TITLE
Visserboot toeter blijft vast hangen

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#191]
https://youtu.be/5W_F_2nJiso

"Dat van die toeter.. Ben nu weer aan het vissen. Zet hem op slot. Hij hangt. Haal het slot eraf. Toeter ging ff uit maar daarna gelijk weer aan. Daarna weer op slot en de toeter is nu nog uit"

**Comment by Willem-Dekker** [comment]
kan  niet reproduceren
