### ISSUE TITLE
[FEATURE]: Passagier zit niet goed op stoel

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1910]
### Contact Details

Wilma Wonka#4312

### Kenteken van voertuig

KFB 326

### Voertuig model

Koenigsegg CCX

### Omschrijf de bug

Passagier zit niet goed op zijn stoel.

https://medal.tv/games/gta-v/clips/Tk27dGcJRxKWj/d1337Q1m2xo2?invite=cr-MSxqQjEsMTU1MDM2NTYs

Ik weet niet of alleen ik het heb maar zal voor de zekerheid mijn eigen kenteken er bijzetten

### Repro

Bekijk de clip. Zelf heb ik er geen verstand van

### Normaal gedrag

Passagier moet goed in de stoel zitten. Want het is niet tof zo.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ARJ3N** [comment]
De ruitenwisser hoort recht omhoog te staan op een CCX. @WilmaWonka1985

**Comment by WilmaWonka1985** [comment]
@ARJ3N meen je dat echt? ik sta er echt versteld van. Hahah. Maar dat van dat stukje met passagier dat kan dus wel misschien gefixt worden?

**Comment by WilmaWonka1985** [comment]
Geen probleem
