### ISSUE TITLE
[EUP]: Vrouwelijke KMAR steekvest te donker

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1911]
### Contact Details

CalRay#1513

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De steekvest van de vrouwelijke KMAR is te donker en hier komen veel klachten over. Ik heb met Mila besproken en ze zei dat ik hiervoor een github moest maken, zodat ze dit verder kan bekijken. Kan de kleurcode hetzelfde zijn als de mannelijke KMAR steekvest? 😄 

Vrouwelijke KMAR steekvest: 
![image](https://user-images.githubusercontent.com/101106299/216394866-54053e7a-c636-4ecb-8878-3a2b0415d5d8.png)

Mannelijke KMAR steekvest:
![image](https://user-images.githubusercontent.com/101106299/216395338-55ce2d8a-4d4a-4beb-af41-8d9b7f6c4ea0.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Ik krijg dit vest niet gevonden tussen de lijst waardoor ik dekleur niet aan kan passen.

**Comment by DevvTDA** [comment]
Helaas niet mogelijk.
