### ISSUE TITLE
[Bug]: Speedlimiter werkt niet op lazer & hydra

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1912]
### Contact Details

Arjen#0001

### Wat gebeurde er?

De speedlimiter doet niks op de /car lazer & hydra.

### Wat hoorde er te gebeuren?

Hoort het toestel te limiteren op een bepaalde snelheid. Handig als je bijvoorbeeld op een vaste snelheid naast een ander toestel wilt vliegen. Het toestel vliegt anders te snel en ook al ga je constant vol op de rem kun je amper zij aan zij met een ander vliegtuig vliegen.

### Wat veroorzaakt de bug?

Pak een lazer of hydra, ga ermee vliegen en zet de speedlimiter aan. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @ARJ3N,

Is dit alleen met deze 2 vliegtuigen of ook met andere vliegtuigen?

**Comment by ARJ3N** [comment]
@Chang-nl zal dat binnenkort even testen maar ik kreeg er berichten over vanuit de KLu dat er voorheen wel een speedlimiter op kon.

**Comment by Chang-nl** [comment]
Hey @ARJ3N,

Ik heb het probleem gevonden en het zal gefixt zijn na de herstart!
