### ISSUE TITLE
[Bug]: Taxi - Medewerker lijst werkt niet meer

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1913]
### Contact Details

Timez#0003

### Wat gebeurde er?

De werknemer lijst werkt niet meer. Op het moment dat je deze aanklikt krijg je niks te zien.  
Hier een voorbeeld video: https://medal.tv/games/gta-v/clips/Ty5SUn6VfYfDb/d1337BCzemVy?invite=cr-MSxCdUMsNDg1Nzc3ODMs

### Wat hoorde er te gebeuren?

Normaal gesproken hoor je een werknemer lijst te zien waar in alle medewerkers die bij de Taxi werken te zien zijn.

### Wat veroorzaakt de bug?

Dat is een goeie vraag. Ik zou het persoonlijk niet weten! 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

[CitizenFX_log_2023-02-03T145824.log](https://github.com/Tedeapolis/development/files/10581611/CitizenFX_log_2023-02-03T145824.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
is na volgende restart gefixed.
