### ISSUE TITLE
[FEATURE]: HRB meldkamer voor BSB rangen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1914]
### Contact Details

Johnny#8125

### Beschrijf zo duidelijk mogelijk de feature

De volgende KMar rangen moeten toegang krijgen tot de ''hrb'' meldkamer.
kmar 80
kmar 81
kmar 82
kmar 83

### Wat lost deze feature op?

Er zijn een aantal HRB leden die op de BSB rang staan i.v.m. de neventaak KLu. Hierbij is het dus handig dat ze toegang hebben tot zowel de DSI als HRB meldkamer.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @KMarTDA,

Na de herstart is het gefixt!
