### ISSUE TITLE
[FEATURE]: Criminelen op borg vrijlaten

### ISSUE THREAD

**Issue by TommyHuisbaas** [Tedeapolis/development#1915]
### Contact Details

Cap_Rogers1941#0093

### Beschrijf zo duidelijk mogelijk de feature

Lock op appartementen en op voertuigen met de flag illegale items. Dit zodat criminelen eventueel op borg vrijgelaten kunnen worden zonder hun spullen te kunnen overzetten. 

**Verdere regels worden nadat dit is geregeld besproken.**

### Wat lost deze feature op?

Dit voorkomt onnodige lange wachtijden in cellencomplex en bied hun ook weer de interactie aan met hun vrienden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @TommyHuisbaas,

Dit is een change die moet worden besproken in het staffoverleg. Zou je hier een agendapuntje voor aan kunnen maken?

**Comment by CalRayy** [comment]
> Hey @TommyHuisbaas,
> 
> 
> 
> Dit is een change die moet worden besproken in het staffoverleg. Zou je hier een agendapuntje voor aan kunnen maken?

Is besproken en goedgekeurd bij het staff overleg 😛.

**Comment by Chang-nl** [comment]
Hey @TommyHuisbaas,

De volgende keer graag vermelden dat de issue is goedgekeurd in staffoverleg.
