### ISSUE TITLE
[FEATURE]: Unmarked Garage Trailer Park

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1916]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Er was een reddit suggestie voor een unmarked garage bij het trailer park en aangezien ik deel ben van het community team maak ik hier een githubje over :)
https://www.reddit.com/r/tedeapolis/comments/10te2mk/garage_trailer_park/

Ook heb ik meteen wat logische locaties opgezocht voor die cirkels en kwam op de volgende plekken uit:

Groene Cirkel:
![image](https://user-images.githubusercontent.com/120292087/216804304-7ca0213d-20a9-43ea-bbd1-224a75b2fb1d.png)

Rode Cirkel:
![image](https://user-images.githubusercontent.com/120292087/216804332-390a6fb2-3431-49c2-b23e-6804e25e0f8e.png)

### Wat lost deze feature op?

Maakt het opbergen/pakken van je vrachtwagen wat makkelijker.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @ExoticaTDA,

Na de herstart zal de nieuwe garage beschikbaar zijn!
