### ISSUE TITLE
[FEATURE]: Vliegen zonder vliegbrevet

### ISSUE THREAD

**Issue by TFFTDAPerry** [Tedeapolis/development#1917]
### Contact Details

maxjuh97#7233

### Beschrijf zo duidelijk mogelijk de feature

(Is besproken bij stafoverleg)
Je zou dan weer kunnen vliegen zonder vliegbrevet. Als je nu je brevet kwijtraakt, weet je ineens niet meer hoe je moet vliegen. 
Mogelijkheid is om bijvoorbeeld bij 5% flying te kunnen vliegen zonder brevet of volledig weg te halen. 

### Wat lost deze feature op?

Je kunt dus weer vliegen zonder dat je per se een vliegbrevet nodig hebt. 
Meer roleplay voor KLU

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by TFFTDAPerry** [comment]
Is besproken tijdens stafoverleg

**Comment by Chang-nl** [comment]
Hey @TFFTDAPerry,

Even zodat ik het goed begrijp moet je zonder vliegbrevet weer gewoon in alle vliegtuigen kunnen vliegen. Klopt dit?

**Comment by TFFTDAPerry** [comment]
Dat klopt inderdaad. Ik had al een paar ideetjes met Misstake besproken in DM.

**Comment by niekschoemaker** [comment]
Zit erin na volgende restart
