### ISSUE TITLE
Emote Justitie papieren bezorgen aanpassen

### ISSUE THREAD

**Issue by DannyTerpstra** [Tedeapolis/development#1918]
Momenteel als je als justitie papieren bezorgt heb je de emote /e knock2 hierdoor worden veel justitie medewerkers overvallen omdat de criminele denken dat ze illegale activiteiten aan het doen zijn. Misschien een idee om het aan te passen naar /e atm?

**Comment by Chang-nl** [comment]
Hey @DannyTerpstra,

De emote /e atm past hier niet zo goed bij. Heb je nog een andere suggestie voor een emote?

**Comment by jaim1114** [comment]
Misschien een van de volgende emotes?

/e wait --> je staat te wachten tot er wordt opengedaan

/e windowshop --> je kijkt wat om je heen en doet af en toe je armen over elkaar (alsof je staat te wachten)

/e parkingmeter --> lijkt alsof je iets in de brievenbus gooit, wel dezelfde emote als lockpicken

/e clipboard2 --> lijkt alsof je met documenten voor de deur staat

> Hey @DannyTerpstra,
> 
> De emote /e atm past hier niet zo goed bij. Heb je nog een andere suggestie voor een emote?

Misschien een van de volgende emotes?

/e wait --> je staat te wachten tot er wordt opengedaan

/e windowshop --> je kijkt wat om je heen en doet af en toe je armen over elkaar (alsof je staat te wachten)

/e parkingmeter --> lijkt alsof je iets in de brievenbus gooit, wel dezelfde emote als lockpicken

/e clipboard2 --> lijkt alsof je met documenten voor de deur staat

**Comment by Chang-nl** [comment]
Hey @DannyTerpstra,

De animatie zal aangepast worden naar clipboard2.

Bedankt voor je input @jaim1114!
