### ISSUE TITLE
[FEATURE]: Taxi - Extra in-game porto kanalen 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1923]
### Contact Details

Timez#0003

### Beschrijf zo duidelijk mogelijk de feature

Zoals de titel al zegt willen wij extra porto kanalen aanvragen. Gezien wij een van de weinigen (of de enige) zijn die in-game porto's gebruiken zouden wij graag 2 extra porto's willen hebben naast onze huidige. Momenteel hebben wij namelijk 140, 141 en 142.

Hoe wij het plan voor ons zien:
140 = Algemene porto voor in-dienst meldingen omroepen
141 = Porto voor vragen aan leiding
142 = Marketing - hierin zullen onze Marketing medewerkers hun overleg kunnen houden mits zij bezig zijn met Marketing taken
143 = Recruitment - Hier in kunnen Recruiters zich bevinden tijdens een inwerking met een nieuwe medewerker
144 = Leiding - hier in kan leiding overleg houden en of elkaar apart spreken

### Wat lost deze feature op?

Dat wij wat meer ruimte hebben voor bepaalde taken en/of gespreken die gerelateerd zijn met taken zoals Marketing, Recruitment of Leiding.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @TedeaTaxi,

Na de herstart zijn deze toegevoegd!
