### ISSUE TITLE
[Bug]: Charselect niet werkende (het switchen naar een ander character dan character 1 werkt niet)

### ISSUE THREAD

**Issue by Smokjertje12** [Tedeapolis/development#1924]
### Contact Details

smokertje12#2488

### Wat gebeurde er?

Wanneer ik probeer te switchen naar mijn tweede character werkt dit niet en gebeurt er niks. Er werdt ook niks weergegeven in de console waaruit ik wat zou kunnen opmaken er gebeurde gewoon niks.

### Wat hoorde er te gebeuren?

Dat ik switch naar mijn tweede character.

### Wat veroorzaakt de bug?

Dat is voor mij ongekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Even een report aanmaken of iemand je 2e character wil verwijderen, waarschijnlijk klopt er iets niet in die character.

**Comment by Smokjertje12** [comment]
Check dankjewel
