### ISSUE TITLE
[FEATURE]: Vliegtuigen/Helikopters kofferbakken legen op LSIA.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1925]
### Contact Details

driemaalsmedes#8258

### Beschrijf zo duidelijk mogelijk de feature

De Koninklijke Marechaussee heeft vaak het probleem dat wanneer er een vliegtuig of helikopter wordt gepakt vol met drugs dat het een enorme operatie is om deze leeg te halen. De meeste vliegtuigen hebben namelijk zeer veel opslag ruimte. Daarom dan ook de vraag of er een icoontje toegevoegd kan worden waarmee de hele kofferbak van een voertuig (vliegtuig/helikopter in dit geval) geleegd kan worden, net zoals bij stad/sandy HB.

Graag op onderstaande locatie:
![20230207230224_1](https://user-images.githubusercontent.com/112424697/217377427-8c49ba96-6ba0-4758-bc75-d6e2e4dc6121.jpg)

### Wat lost deze feature op?

Dit neemt een hele hoop moeite weg voor de KMar. Vliegtuigen/helikopters kunnen dan leeggehaald worden en daarna meteen in de opslag gezet worden. Dit is namelijk in de zelfde hangar.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Je kunt in principe gewoon overladen naar een flatbed, dat is de hele reden dat de flatbed uberhaupt een enorme kofferbak heeft.

**Comment by KMarTDA** [comment]
Dat klopt maar het maak het gewoon wat makkelijker. Deze functie hebben wij momenteel ook al op stad HB zitten dus waarom niet hier.
