### ISSUE TITLE
[Bug]: Pijl om van character te wisselen werkt niet

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1926]
### Contact Details

Arjen#0001

### Wat gebeurde er?

De pijl wisselt niet van character. Zie hieronder voor meer uitleg.

### Wat hoorde er te gebeuren?

Normaliter kun je nadat je /charselect 2 doet met deze pijl (zie foto) op 'E' klikken en dan wisselde je gelijk van character, zonder dat je hoefde te reloggen.
![image](https://user-images.githubusercontent.com/92899337/217675935-609f653e-18dc-42a1-99ef-f4a3909df842.png)

### Wat veroorzaakt de bug?

Doe /charselect 2 en gebruik de pijl. Er gebeurt niks.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Dit klopt, dit was nooit de bedoeling, dus heb eruit gehaald dat het synced wordt, dus je moet reloggen, zoals er in de chat gezegd wordt.
