### ISSUE TITLE
[Bug]: Van character wisselen werkt niet

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1927]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Ik krijg van meerdere spelers te horen dat het wisselen van hun character niet meer werkt. Als ze reloggen veranderd enkel de naam op hun ID kaart maar niet hun uiterlijk. Dit is zowel met net nieuw aangemaakte characters als oude characters het geval.

### Wat hoorde er te gebeuren?

Je hoort van character te wisselen.

### Wat veroorzaakt de bug?

Gebruik /charselect en relog.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Hebben de mensen ook daadwerkelijk gerelogged?

**Comment by ARJ3N** [comment]
Ja compleet FiveM afgesloten en opnieuw opgestart. @niekschoemaker

**Comment by niekschoemaker** [comment]
Ehhh, ik kan dit zelf niet reproduceren, want bij mij werkt het wel gewoon.
