### ISSUE TITLE
[FEATURE]: Katana toevoegen

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#1928]
### Contact Details

Cazorla#7638

### Beschrijf zo duidelijk mogelijk de feature

Gelieve een katana toevoegen en duplicaten voor een knuppel 2. Dus niet de knuppel eruit halen, maar een 2e wapen erin doen (katana). Dit is besproken met Chang.
Hier de link: https://www.gta5-mods.com/weapons/katana
Model is goedgekeurd door Lorenzo.

### Wat lost deze feature op?

Dit is voor een RP voor 14K. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Voor zover ik weet kun je niet "even" een nieuwe wapen toevoegen aan gta, of ik moet dat mis hebben.
Maar zoveel moeite voor even 1 roleplay vind ik nogal meh

**Comment by TDALarry** [comment]
Hi Niek,

Dit is niet voor 1 roleplay, maar voor meerdere roleplays. Dit "wapen" hoort bij hun thema, hetzelfde bijvoorbeeld bij TFFT/DTMC die een bijl gebruikt bij hun promoties. Deze katana kan voor meerdere scenario's gebruikt worden.
Als het geen grootte moeite is, zal ik het waarderen. Ik hoor graag van je.

**Comment by Ljosfari** [comment]
dit is alleen mogelijk als we de knuppel eruit halen

**Comment by ARJ3N** [comment]
Kan eventueel vervangen worden met de poolstick of golfclub i.pv. de bat. @Ljosfari
