### ISSUE TITLE
[FEATURE]: Nieuwe rang toevoegen Reznikov

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1929]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

Wij als leiding willen graag een nieuwe rang binnen de groep. 

Deze zal ingame er zo moeten uit zien: Reznikov - командир
Deze rang zal geplaatst moeten worden tussen Reznikov - лейтенант & Reznikov - советник

De nieuwe rang zal dezelfde functie kunnen hebben als Reznikov - советник
Dit is dus alles kunnen tunen qua wapens, maar niks kunnen inkopen.

### Wat lost deze feature op?

Meer variatie in rangen en leuker voor eventuele promoties binnen de groep

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Rank is toegevoegd.

**Comment by EpicTomm** [comment]
Top, dankjewel

**Comment by EpicTomm** [comment]
Ik zie dat de nieuwe rang niks kan tunen. Kan de nieuwe rang dezelfde functie hebben als de rang erboven?
