### ISSUE TITLE
[FEATURE]: Charselection verhogen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1930]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk om de charselection te verhogen naar maximum 5 karakters? 

### Wat lost deze feature op?

Mogelijke karakters voor bepaalde items, wat ik niet openbaar kan aankaarten. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
@CalRayy Overleg dit eerst even in staff overleg. Zelf zie ik het nut er niet van in naast misbruik.
