### ISSUE TITLE
[Bug]: vliegdekschip interior laadt niet in

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1933]
### Contact Details

CalRay#1513

### Wat gebeurde er?

De interior van de vliegdekschip laadt niet goed in, zie screenshots. 
![image](https://user-images.githubusercontent.com/101106299/218287460-2413e260-bd83-41d6-8afc-577e68787271.png)
![image](https://user-images.githubusercontent.com/101106299/218287461-4649b0b4-46a0-47f3-99bc-62d882dbc158.png)

### Wat hoorde er te gebeuren?

je hoort gewoon de interior van de vliegdekschip te zien. 

### Wat veroorzaakt de bug?

de nieuwe eiland feature dat je het land niet ziet. (gok ik) 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

heb ik niet helaas

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
ik heb zelf geen problemen

**Comment by CalRayy** [comment]
Het gaat om de binnenkant van de vliegdekschip, erop staan is er niets aan de hand. Eenmaal als je binnen in de vliegdekschip wandelt heb je problemen. Heb het paar dagen geleden nog getest nog altijd aan de hand.

**Comment by Ljosfari** [comment]
zorg dat je gta up tp dat is

**Comment by ARJ3N** [comment]
Ook met de laatste versie werkt het niet bij mij. @Ljosfari

**Comment by KMarTDA** [comment]
Dit werkt nog steeds niet. Hoe staat dit ervoor?

**Comment by CalRayy** [comment]
@Ljosfari @Tom974

**Comment by Tom974** [comment]
Zou na de restart gefixt moeten zijn door de almachtige Misstake en een hoop gekloot daarvoor door mij en Thijs 😂

**Comment by CalRayy** [comment]
> Zou na de restart gefixt moeten zijn door de almachtige Misstake en een hoop gekloot daarvoor door mij en Thijs 😂 

😍❤️
