### ISSUE TITLE
[Bug]: Tedeapolis bot in overheidsdiscord functioneert niet meer

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#1934]
### Contact Details

Lamine#4904

### Wat gebeurde er?

Op het moment dat er interacties worden uitgevoerd met de Tedeapolis bot in de overheidsdiscord, dan komt de error "De applicatie heeft niet gereageerd" in beeld.
![image](https://user-images.githubusercontent.com/71287080/218307397-3ee2ab81-40f7-4095-a1f4-778d66691806.png)

### Wat hoorde er te gebeuren?

Normaliter zou de bot het uitgevoerde command moeten uitvoeren en dan een succesbericht moeten weergeven.

### Wat veroorzaakt de bug?

1. Naar de overheidsdiscord gaan
2. In een willekeurig kanaal een slashcommand intypen
3. Het slashcommand versturen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Hij werkt weer!
