### ISSUE TITLE
[FEATURE]: Tunes Taxivoertuigen

### ISSUE THREAD

**Issue by MatteDB** [Tedeapolis/development#1935]
### Contact Details

MatteDB#4517

### Beschrijf zo duidelijk mogelijk de feature

De Taxi heeft onlangs nieuwe wagens gekregen die ze kunnen gebruiken om indienst mee te gaan rijden.
Nu hadden hun graag dat deze voertuigen gefulltuned werden als ze deze uit de Taxigarage halen.

**Voertuigen:**
- amdbx (Graag de tune offroad banden geven) Nu hebben ze namelijk geen offroad voertuig
- S63w222
- panamturs21
- mqgts
- 2018s650

==> Graag alle voertuigen Fully Tunen ex Pantser

_Jordy ging dit doorvoeren maar Ljosfari vertelde me dat ik hiervoor het beste een Github zou voor aanmaken_ 
_Voertuigen zitten er al in en werden goedgekeurd door HR_

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Na overleg binnen HR hebben we besloten dit af te keuren. We zien geen reden waarom een taxi fully tuned zou moeten zijn. Het is een taxi en geen sport auto. Auto's hebben voldoende snelheid.
