### ISSUE TITLE
[Bug]: CCF MLO

### ISSUE THREAD

**Issue by Avii97** [Tedeapolis/development#1937]
### Contact Details

𝐀𝐯𝐢.#5497

### Wat gebeurde er?

Sinds de nieuwe MLO van TFFT in Vespucci zijn er een paar objecten terug gekomen of veranderd, zo zitten een paar props in elkaar, ook is er bij sommige stukken de blauwe hekken weer te zien die dan buggen in de zwarte hekken. De container in de steeg is weer teruggekomen waardoor iedereen via de container weer kan binnendringen. De 2 grote containers die vast stonden zijn weer los waardoor de hek niet helemaal meer open gaat. 

![foto1](https://user-images.githubusercontent.com/122118644/218324724-ef953a17-9c42-44e0-9e73-9bc4c067c0cb.png)
![image](https://user-images.githubusercontent.com/122118644/218324737-49b163b8-1780-4c6d-9600-ee1b3c29dbf9.png)
![image](https://user-images.githubusercontent.com/122118644/218324747-f46feaae-4744-4e34-997d-e1ccfc47ca10.png)
![image](https://user-images.githubusercontent.com/122118644/218324753-f6e0900b-8f01-4115-a799-0befbbe62e30.png)
![image](https://user-images.githubusercontent.com/122118644/218324761-7c57f0b9-04e9-43ba-b5f3-7c6159e62d9c.png)
![image](https://user-images.githubusercontent.com/122118644/218324767-3e5e03f5-5ff1-4b23-a81d-485a6b366be2.png)

### Wat hoorde er te gebeuren?

Terug naar hoe het was, zo ziet het er netter uit en werkt alles naar behoren.

### Wat veroorzaakt de bug?

Nieuwe MLO van TFFT

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Oesewoes** [comment]
Ja is weer eens een ymap die zowel in ccf zit als in die tfft plugin.

Het gaat om: hei_vb_rd_strm_3.ymap
Moet ff kijken wat daar in is aangepast maar beetje kuttig omdat het escrowed is enzo ;_;

**Comment by Avii97** [comment]
je praat code taal voor me, maar klinkt ingewikkeld xD

**Comment by DaanDeW** [comment]
Verjaard
