### ISSUE TITLE
[FEATURE]: Toevoegen van nieuwe heist

### ISSUE THREAD

**Issue by Wiebren-3** [Tedeapolis/development#1938]
### Contact Details

Wiebren#6393

### Beschrijf zo duidelijk mogelijk de feature

Op het moment is er niet perse veel variatie in activiteiten/scenario's in de criminaliteit, daarom is mijn suggestie om hier een nieuwe **Heist** aan toe te voegen. 

Deze heist is het overvallen van een kantoor-gebouw, met een voorgaande missie. Namelijk het verkrijgen van data waardoor je naar binnen kunt bij het gebouw.

Voor meer info is het duidelijker om even de video te kijken.

**Tasklist:**
- [ ] ↳ Overleggen HR.
- [ ] ↳ Kopen MLO.
- [ ] ↳ Kopen script.
- [ ] ↳ Meldingen in Recherche Meldkamer.
- [ ] ↳ Aanpassingen MLO met servernaam (Eerst kijken of deze escrowded is)
- [ ] ↳ Vertalen van Notification die binnenkomen.
- [ ] ↳ Aanpasingen script: Alleen bij bepaalde NPC's denk hierbij op een plek zoals LSIA?

Links: 
[] (https://modit.store/products/office-heist-custom-mlo-required?pr_prod_strat=collection_fallback&pr_rec_id=472b9fcab&pr_rec_pid=7916992594137&pr_ref_pid=7505740071129&pr_seq=uniform)
[](https://modit.store/collections/fivem-maps-mlo-shells/products/apache-office-mlo-info?variant=40396168265911)
(Indien deze links verwijderd moeten worden ivm plagiaat andere servers, graag even dm'en)

### Wat lost deze feature op?

- Meer variatie in scenario's.
- Meer motivatie voor criminelen.
- Meer roulatie in plekken waar een overval gepleegd kan worden.
- Meer roleplay achter een overval.
- Meer interactie met politie bij voorbereiding (Misschien ook met recherche i.v.m. het hacken)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AntonMTDA** [comment]
@Ljosfari denk dat deze gesloten kan worden
