### ISSUE TITLE
[FEATURE]: Boete voor gekleurde koplampen in F6 menu toevoegen.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1939]
### Contact Details

driemaalsmedes#8258

### Beschrijf zo duidelijk mogelijk de feature

Afgelopen maand is het strafbaar gemaakt om je koplampen een andere kleur te hebben dan wit. Hier wordt dus ook op gehandhaafd door de marechaussee/politie. Deze boete bedraagt €5000. Graag zien wij deze boete terug in ons F6 menu onder het kopje 'verkeersmidrijven'. Zie hieronder hoe het in het wetboek staat.

![image](https://user-images.githubusercontent.com/112424697/218484581-dd174e52-62bd-4acd-b9ff-b427ca38f604.png)

### Wat lost deze feature op?

Dit bespaart wat tijd. Opsporingsambtenaren hoeven nu niet helemaal de boete op te zoeken in het wetboek om deze vervolgens handmatig uit te schrijven.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ik heb de boete toegevoegd als:
Rijden met voertuig met niet toegestane verlichting

Gebaseerd op feitcode [N640](https://boetebase.om.nl/?SrtCatVer=a2&boete_tree=22206%2c22118%2c22071%2c21957%2c21912&Linked=N+640#N%20640)
