### ISSUE TITLE
ID/Steamnaam bij een twitter bericht

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#194]
Momenteel is het erg lastig voor staffleden om te handhaven op twitterberichten. Tijdens het staffoverleg is besproken dat elke vorm van criminele activiteit op twitter (dus ook bijvoorbeeld: "Wie wil mijn vuile sokken wassen?") bestraft zal worden. 

Helpers & andere staffleden (behalve mensen die in de database kunnen) hebben momenteel niet de mogelijkheid om hierop te handhaven. Daarom is het verzoek om achter elk twitterbericht een ID te laten zien voor alle staffleden die in dienst zijn. 

Bijvoorbeeld
xxKoekjesxx1217 [2630] 
Heeft iemand tijd om mijn vuile sokken te wassen? 

2630 geeft dan het ID van de spelers aan en op deze manier kunnen wij dan acties uitvoeren.

To do:
- [x] Toevoegen van een functie voor staffleden om ID's te zien achter namen op twitter.

**Comment by PapaXilion** [comment]
Vraagje: wordt dit dan bestraft vanuit staff of via de politie? Want afhankelijk van wat er gezegd wordt zou je kunnen redeneren dat dit wel meer een RP-situatie creëert dan een probleem op server-niveau.

Verder uiteraard eens dat dit aangepakt moet worden, maar misschien is enige nuance hier wel passend :)

**Comment by TDA-SanderD** [comment]
Dit wordt bestraft vanuit staff. In het staffoverleg is besproken dat dit soort dingen via Twitter niet meer kunnen. Er volgt een in principe een warning bij elke (poging tot) verkopen/kopen van illegale spullen of het gebruiken van Twitter voor criminele doeleinden. 

De gedachte hierachter is dat Twitter zorgt voor een te makkelijk platform voor nieuwe spelers om drugs en dergelijke te verkrijgen. De spelers dienen door middel van roleplay met criminele organisaties achter drugslocaties te komen en niet door middel van Jan met de korte achternaam via Twitter. Dit wordt momenteel al gedaan door criminele organisaties te laten werken met lijsten en dergelijke, echter blijkt dit niet voldoende.

**Comment by TDA-SanderD** [comment]
Dit is als het goed is geïmplementeerd. Nog één kleine bug: Je ziet "nil" voor de twitternaam en na het ID.
https://i.imgur.com/1HGrv6c.png

**Comment by Willem-Dekker** [comment]
dit zou gefixed moeten zijn nu
