### ISSUE TITLE
[BurgerRaad]: Mogelijkheid heist alarm uit te schakelen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1940]
### Contact Details

RalphVidus#0836 & Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

- [ ] Een functie voor de Politie/KMar om het alarm bij de heist uit te schakelen

### Wat lost deze feature op?

Op dit moment is het zo dat als je de heist start er een luid alarm af gaat, dit is logisch maar al heb je soms een scenario van meer dan een uur kan je soms heel gek worden van dit alarm. Daarnaast is het onderhandelen met de Politie/KMar ook heel lastig omdat je elkaar slecht kunt verstaan. 

Vandaar graag de functie voor de Politie/KMar dat hun dit alarm uit kunnen zetten zodra hun bij de heist aankomen.

**Dit is besproken in de burgerraad**

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
zit er blijkbaar al in, 

/disablealarm voor agenten. (POLITIE agenten).
