### ISSUE TITLE
[BurgerRaad]: Wapen Tint Goedkoper Maken

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1941]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

- [ ] De aanschaf van een wapen tint op een wapen goedkoper maken

Op dit moment heb je de optie om een mooie tint op je wapen te zetten alleen is dit in verhouding met andere wapentunes (die wel een effect hebben op het wapen) extreem duur. 

### Wat lost deze feature op?

Dit is niet persee een hele belangrijke aanpassing maar is zeker leuk voor de mensen in de onderwereld. Zo kan je je wapen toch wat meer personaliseren. Als dit wat goedkoper gemaakt word word dit misschien ook waker gekocht.

**Dit is besproken in de burgerraad**

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
@ExoticaTDA Graag ook een lijstje met prijzen, als het mogelijk is 😃 !

**Comment by ExoticaTDA** [comment]
> @ExoticaTDA Graag ook een lijstje met prijzen, als het mogelijk is 😃 !

Ik ga ff een crimineel aan z'n oren trekken XD

**Comment by ExoticaTDA** [comment]
> > @ExoticaTDA Graag ook een lijstje met prijzen, als het mogelijk is 😃 !
> 
> Ik ga ff een crimineel aan z'n oren trekken XD

Ik heb een lijst die ik kan sturen, maar eigenlijk waar het op neer komt is alle wapen tinten 50% goedkoper maken.

Wij denken dat hierdoor mensen het eerder kopen en hierdoor ook meer geld uit de economie verdwijnt

**Comment by DevvTDA** [comment]
Beste Burgerraad,

Zondag om 20.00 uur hadden wij een staff overleg en daar is het volgende besproken:

Helaas zal er geen aanpassing worden gemaakt aan de wapentinten. Dit is geen noodzakelijke verandering en heeft geen extra waarde, dus dit zal helaas zo blijven.
We gaan de straffen voor APV overtredingen niet aanpassen. Als staffleden zullen we vaker kijken naar het verleden van de betreffende persoon. Als we zien dat dit vaker is voorgekomen, dan zullen we daar rekening mee houden. Kortom, we zullen strenger optreden tegen personen die deze overtredingen vaker begaan en we kunnen de straf op basis van de context zelf verhogen.
