### ISSUE TITLE
[BurgerRaad]: Beretta FMJ Ammo

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1942]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment als je op een beretta FMJ zet kunnen er nog maar 8 patronen in het wapen, terwijl als je op een M1911 FMJ zet je gewoon nogsteeds hetzelfde aantal patronen in je wapen kan doen als eerst (max)

Kan dit gelijk getrokken worden aangezien het beide pistols zijn en FMJ een bepaald type patroon is en het zou geen verschil moeten maken in het formaat van het patroon.

Kortom, graag zien we dat de baretta FMJ patronen van 8 patronen omhoog gezet worden naar het max. (evenveel als dat in een beretta past voordat je er FMJ opzet) 

**Dit is besproken in de burgerraad en er werd vanuit gegaan dat dit onbewust was en dus een foutje was**

### Wat lost deze feature op?

Dat de baretta en de m1911 net zoals normaal gelijk zijn kwa ammunitie, ook wanneer er FMJ patronen in zitten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Het zijn 2 compleet verschillende kallibers wapen, de M1911 is een .45 ACP (11mm) en de Beretta en 9mm, dus de M1911 heeft een stuk grotere kogels.
