### ISSUE TITLE
[EUP]: Kleding uit de winkel?

### ISSUE THREAD

**Issue by Nick21458** [Tedeapolis/development#1943]
### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Zover dat ik weet was van de broek ook een upper body kleding het zelfde als de broek. alleen die kan ik zelf niet meer vinden
het gaat om broek: 151

https://cdn.discordapp.com/attachments/853002344271052820/1074958834507989092/image.png

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Chang-nl** [comment]
Hey @Nick21458,

Het zou kunnen dat deze vervangen is of verplaatst is naar een ander kleding slot. Heb je ook op andere kleding slots gekeken naar dit kledingstuk?

**Comment by Nick21458** [comment]
@Chang-nl Ja alleen ik kon hem zelf niet vinden dus vandaar dat ik dit had gemaakt :) Maar ik kon hem zelf niet vinden
