### ISSUE TITLE
Productiviteit van loodsen drastisch naar beneden zonder reden

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#1946]
### Contact Details

Cazorla#7638

### Wat gebeurde er?

Er komen meerdere tickets/reports/berichten binnen dat de productiviteit van loodsen drastisch naar beneden zijn gezet. Dit komt waarschijnlijk door een bug. Eerst produceerde een PRO loods ongeveer 100 zakjes per uur. Dit is nu gemiddeld 33-40 zakjes per uur. 
Kan hier aub naar gekeken worden?

### Wat hoorde er te gebeuren?

Productiviteit omhoog zetten van pro loodsen.

### Wat veroorzaakt de bug?

Geen idee, Chang gaf aan dat het een bug was omdat er zelf niks veranderd is.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
De productiviteit is van 1.3 per upgrade aangepast naar 1.25 het verschil in zakjes per uur kun je dus ook terug zien in de hoeveelheid ingrediënten, omdat de snelheid ook verlaagd is.

Dit om de drukte op de pluk weer te verminderen.
