### ISSUE TITLE
[FEATURE]: garage bij Bark! Polis

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#1948]
### Beschrijf zo duidelijk mogelijk de feature

- [ ] Een garage voor op het terrein bij de parkeerplaats. Een groene en rode cirkel.
- Groen: 584.26, 2720.67, 42.96
- Rood: 586.66, 2736.46, 42.06

i.v.m. veel lag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Attomn** [comment]
Een garage hier toevoegen lijkt me geen goede toevoeging gezien het rond de oostpost is en daardoor smokkelen heel makkelijk wordt.

**Comment by ExoticaTDA** [comment]
> Een garage hier toevoegen lijkt me geen goede toevoeging gezien het rond de oostpost is en daardoor smokkelen heel makkelijk wordt.

Ik snap je punt maar denk wel echt dat hier een garage nodig is. Wij van Bark! Polis kunnen zelf onze auto niet kwijt (en vaak gaan we open met 10+ man personeel aanwezig), en als klanten dan langs komen kunnen hun ook hun auto niet kwijt.
Al laten we de auto's weghalen hebben we zelf aan 't einde van de dag geen vervoer meer terug.

Ook als we events doen willen we Bark! Polis als start punt gebruiken en komen er dan tientallen mensen die kant op.

Misschien een idee om deze unmarked garage een "West" garage te maken. Hier heb je er atm geen van en zou je dus ook niet kunnen gebruiken voor smokkelen. Je kan auto's met illegale goederen namelijk niet heen en weer transporteren naar garages in andere gebieden.
