### ISSUE TITLE
[FEATURE]: Nieuwe tpw's locaties toevoegen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1951]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden de nieuwe junior-mods bij de volgende locatie een nieuwe TPW hebben: 
- [x] x: -297.68 y: 6276.17 z: 31.49 = Paleto 
- [x] x: 1838.13 y: 3691.82 z: 34.27 = Sandy HB
- [x] x: -1647.70 y: -1126.90 z: 13.03 = Casino 
- [x] x: -2344.62 y: 3267.78 z: 32.81 = militaire base
- [x] x: -192.04 y: -1360.20 z: 31.26 = Ramenwasser start locatie
- [x] x: -253.72 y: -1996.97 z: 30.15 = tweedehands arena
- [x] x: -764.91 y: -1531.78 z: 5.50 = Helipads
- [x] x: -895.80 y: -2983.33 z: 19.85 = vliegveld LSIA
- [x] x: 230.63 y: -1360.16 z: 28.65 = CBR
- [x] x: 276.09 y: -309.79 z: 49.87 = Basicfit/basicfat

Tevens staat er BP en blokkenpark, kan blokkenpark weggehaald worden (dubbel namelijk).

### Wat lost deze feature op?

Makkelijker voor de nieuwe Junior-mods om reports op te pakken. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @CalRayy 

De nieuwe locaties zitten erin na volgende herstart!
