### ISSUE TITLE
[FEATURE]: Thermiet op deuren verbeteren.

### ISSUE THREAD

**Issue by DaneyLB** [Tedeapolis/development#1952]
### Contact Details

DarkerNL#6490

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kun je in de stad alleen enkele deuren open branden. 
Bijvoorbeeld de kluis deuren in de banken, de deuren van Exotica, en inprenciepe iedere enkele deur, Maar dubbele deuren zoals die bij Bahama Mamas, TDA Nieuws, en ieder andere dubbele deur kan NIET open gebrand worden. 
Dit is een beetje unfair tegenover de gebouwen die wel open gebrand kunnen worden.
En zo zijn er meer inbraak mogelijkheden in de stad

### Wat lost deze feature op?

Dat er meer mogelijkheden zijn om deuren open te branden en zo nieuwe scenarios neer te kunnen zetten die voorheen minder makkelijk mogelijk waren ivm het niet kunnen open maken van deze deuren als crimineel.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @DaneyLB,

Bedankt voor het aanmaken van een github issue. De aanpassingen die dit probleem oplossen zullen actief zijn na de herstart van 02:00!
