### ISSUE TITLE
[Bug]: Misbruik van /med

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#1954]
### Contact Details

iHax0r#3736

### Wat gebeurde er?

In de titel van /med zie je de voor- en achternaam van de persoon die op de grond ligt, nu zie ik best veel manieren hoe dit misbruikt kan worden. Aangezien je dan zonder iemands id kaart te pakken kan zien wie het is wat ook een beetje RP ontwijkend is.

### Wat hoorde er te gebeuren?

Het lijkt me beter om daar het ID van persoon weer te geven.

### Wat veroorzaakt de bug?

Powergaming & RP ontwijkend gedrag.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Relevante log bestanden

nvt

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
dit moeten even getest worden als je uit dienst ben als staff

**Comment by iHax0rMC** [comment]
> dit moeten even getest worden als je uit dienst ben als staff

Het gaat alleen vooral om overheidsdiensten die dit gebruiken.

**Comment by Tom974** [comment]
Hey @iHax0rMC, 

Dit zal gefixed zijn na de restart!
