### ISSUE TITLE
[Bug]: Helikopter kapot slaan met knuppel 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#1956]
### Contact Details

Endorsite#0001

### Wat gebeurde er?

https://www.youtube.com/watch?v=M76Gaw-qd3A&ab_channel=GertOmerta

ze kunnen met een knuppel 1 hit een helikoper meteen kapot slaan 

### Wat hoorde er te gebeuren?

evt alleen het raam kapot maar niet het voertuig

### Wat veroorzaakt de bug?

zie video is 1 hit met de knuppel meteen motor kapot

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
fixed
