### ISSUE TITLE
[FEATURE]: Togglehud off

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1957]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Op het moment heb je de functie "/togglehud off" wat heel handig is voor mensen die mooie foto's/video's willen maken. 
Alleen heb je in voertuigen nogsteeds je voertuig hud in beeld.

Voorbeeld:

Mijn HUD staat hier uit, alleen zie je mijn voertuig HUD nogsteeds
![image](https://user-images.githubusercontent.com/120292087/219988601-c3c2ed2b-f562-48e2-b3c7-e34aaa033e7c.png)

Is er een mogelijkheid dat deze ook verdwijnt het moment dat je "/togglehud off" gebruikt?

### Wat lost deze feature op?

Dit geeft creators meer ruimte voor mooie voertuig foto's

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
is doorgevoerd
