### ISSUE TITLE
[FEATURE]: Inbeslagname cirkel voor boten bij vissers.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1958]
### Contact Details

driemaalsmedes#8258

### Beschrijf zo duidelijk mogelijk de feature

Momenteel is het zo dat als de marechaussee een boot in beslag neemt dat deze helemaal naar helipads gevaren moet worden. Dit is iets wat al gauw veel tijd kost omdat je helemaal om het mainland heen moet. Daarom zouden wij graag een inbeslagname cirkel voor boten willen bij vissers. Zie hieronder:
![image](https://user-images.githubusercontent.com/112424697/220190040-1b7482af-c636-47b2-9e23-1c3152953f18.png)

### Wat lost deze feature op?

Dit bespaart veel tijd omdat je niet helemaal vanuit het noorden naar helipads toe moet om een auto in beslag te nemen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed
