### ISSUE TITLE
Auto's Tunes Verdwijnen

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#196]
"terwijl ik mijn auto in Los Santos Customs zet voor een andere paintjob zijn ineens al de visuele en performance updates verdwenen en is de auto stock. Ik heb het eventueel op clip staan."

https://www.youtube.com/watch?v=-3OTLM_6-OA&ab_channel=PeterG

**Comment by Willem-Dekker** [comment]
@niekschoemaker dit lijkt een issue te zijn met het tunen van de aanhanger en dat de de auto wordt overschreven

**Comment by niekschoemaker** [comment]
Is een client issue, server side wordt er niks veranderd voor zover ik weet

**Comment by niekschoemaker** [comment]
Eventueel ben ik ook even logs nodig, daar kan ik meer info uit halen met wat precies wat veranderd heeft. @DaanDeWit
