### ISSUE TITLE
[FEATURE]: Zorg pas in de hand

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#1960]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Een collega kwam met een idee om je zorgpas , als je die aangeeft aan de ambulance dat die dan in je hand terecht kan komen. Zo zien wij ook dat we idd dat we een zorgpas vast hebben van de persoon die facuurs moet krijgen. Is dit misschien een mogelijkheid?

Groetjes Wilma Wonka

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Ik zou dit dan doen met alle pasjes en niet alleen de zorgpas

**Comment by WilmaWonka1985** [comment]
Dit was echter een idee van iemand uit het ziekenhuis. Maar goed dan zou het misschien voor alle passen kunnen gelden.

**Comment by Ljosfari** [comment]
is te veel werk voor een kleine toevoeging
