### ISSUE TITLE
[Bug]: HRB rangen krijgen DSI meldkamer meldingen.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1962]
### Contact Details

Johnny#8125

### Wat gebeurde er?

HRB rangen (kmar 70, 71, 72, 73, 74) krijgen momenteel DSI (meldkamer) meldingen binnen sinds 14-02-2022.

### Wat hoorde er te gebeuren?

HRB rangen horen niet de DSI meldingen binnen te krijgen.

### Wat veroorzaakt de bug?

Jezelf op één van de HRB rangen zetten en melding maken naar ''dsi'' meldkamer.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ik heb mezelf op rang 70 gezet, ben in dienst gegaan, en krijg geen melding, heb je dit zelf getest voordat je een issue aangemaakt hebt? Want sinds 14-02 zijn er al weer heel veel wijzigingngen geweest.

**Comment by KMarTDA** [comment]
@niekschoemaker Ik heb het zojuist getest op alle HRB rangen, de DSI meldingen die ik heb gemaakt tussen 19:55 en 20:01 zijn allemaal binnen gekomen op alle HRB rangen.

**Comment by Ljosfari** [comment]
dit was gefixed toch @KMarTDA @Chang-nl ?

**Comment by KMarTDA** [comment]
Excuses voor mijn late reactie. De HRB rangen krijgen nog steeds DSI meldingen...

**Comment by Tom974** [comment]
Hey @KMarTDA,

Bedankt voor het meden van de bug! Dit zal gefixt zijn na de herstart van 02:00!

**Comment by KMarTDA** [comment]
Hi @Tom974

Ik krijg zojuist berichten dat alle HRB rangen ze sinds vandaag weer ontvangen. Zal ik een nieuwe github aanmaken of moet deze heropend worden?

**Comment by Tom974** [comment]
Hey @KMarTDA

Is hier toevallig een clip bij? Ik krijg het zelf namelijk niet gereplicate

**Comment by Tom974** [comment]
Hey @KMarTDA,

Zal gefixt zijn na de herstart!
