### ISSUE TITLE
[FEATURE]: Schietmeldingen boven icoontjes zetten.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1963]
### Contact Details

Johnny#8125

### Beschrijf zo duidelijk mogelijk de feature

Momenteel verdwijnen schietmeldingen onder icoontjes op de map zoals bijvoorbeeld het ANWB logo of de cardealer logo. Is het mogelijk om te zorgen dat een schietmelding altijd gezien word bovenop de icoontjes, dus een soort van overlap. 

Mocht dit niet lukken dan is de vraag om de schietmelding iets te vergroten om het zichtbaarder te maken.

### Wat lost deze feature op?

Het probleem ligt momenteel dat de schietmeldingen niet gezien/gevonden worden op de map gezien het overlapt word door andere icoontjes. De suggestie is om te zorgen dat schietmeldingen overlappen over de icoontjes of te vergroten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Helaas niet mogelijk.
