### ISSUE TITLE
[FEATURE]: Rang aanpassing reznikov

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1964]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

In me vorige github: https://github.com/Tedeapolis/development/issues/1929

Ik had gevraagd of de nieuwe rang toegang kreeg tot het alles tunen van de wapens.
Nu is dit niet gedaan/gelukt. Mijn vraag is of deze rang Reznikov - Командир tot alles toegang krijgt tot tunen van wapens.
Dus dezelfde functie als de rang erboven!

### Wat lost deze feature op?

Meer variatie in de rangen tot tunen van wapens!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ik snap je zins opbouw niet, ze moeten toegang tot alles tot wapen tuning, moeten ze dus alles, of alleen wapen tuning?
Alsin, wat moet ik aanpassen, ik wil ze best toegang geven tot de bazen pot, als ik het goed begrijp?

**Comment by EpicTomm** [comment]
Oh nee sorry, die rang moet alleen toegang krijgen tot wapen tuning. Wat dus de rang daarboven ook heeft!

**Comment by EpicTomm** [comment]
Kan dit nog aangepast worden?

**Comment by Tom974** [comment]
Hey @EpicTomm 

Dit zou gefixt moeten zijn na de volgende herstart, mocht dit toch niet zo zijn, gelieve deze issue dan opnieuw te openen 😄

**Comment by EpicTomm** [comment]
Ik zal je op de hoogte houden!
