### ISSUE TITLE
[Bug]: /repareer werkt soms niet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#1966]
### Contact Details

CalRay#1513

### Wat gebeurde er?

iemand doet /repareer, maar dat werkte niet. Zie clip: https://www.youtube.com/watch?v=17Pibm00gUA

### Wat hoorde er te gebeuren?

/repareer hoorde te werken. 

### Wat veroorzaakt de bug?

https://www.youtube.com/watch?v=17Pibm00gUA 
[CitizenFXgaragebug_log_2023-02-23T140642.log](https://github.com/Tedeapolis/development/files/10816516/CitizenFXgaragebug_log_2023-02-23T140642.log)

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

[CitizenFXgaragebug_log_2023-02-23T140642.log](https://github.com/Tedeapolis/development/files/10816525/CitizenFXgaragebug_log_2023-02-23T140642.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Lorenzo3001** [comment]
Dat komt omdat hij nog in het modshop menu zit bij het gebruiken van /repareer.
