### ISSUE TITLE
[FEATURE]: Toegang tot het zien van Callsign's en ID's in ATC porto voor Koninklijke luchtmacht rol in Flightschool Discord

### ISSUE THREAD

**Issue by Smokjertje12** [Tedeapolis/development#1967]
### Contact Details

smokertje12#2488

### Beschrijf zo duidelijk mogelijk de feature

Momenteel hebben de vlieginstructeurs met de vlieginstructeur discord rollen hier toegang tot. Maar vanuit Klu leiding word gevraagd om dit ook toe te voegen voor de KLU rol.

### Wat lost deze feature op?

Dat de KLU dan ook ATC werk kan doen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @Smokjertje12,

De politie heeft toch sowieso al toegang tot het inzien van callsign's en ids in de atc porto? Of begrijp ik je nu verkeerd?

Is het mogelijk om je issue iets nader te omschrijven?

**Comment by Smokjertje12** [comment]
Ook niet Politie medewerkers mogen bij de flightschool werken. Zij zouden dan wanneer zij bezig zijn met criminele zaken dit kunnen abusen hier uit dan ook de mogelijkheid om deze uit te zetten zodat dit niet gebeurt.

**Comment by Smokjertje12** [comment]
Momenteel zien de mensen die bij de KLu werken met de (korporaals, onderofficieren, officieren) rangen deze niet alleen de vlieginstructeur's. Naar mijn weten kan een gewone politie rang deze momenteel ook niet zien.

**Comment by Tom974** [comment]
Heb dit in een groep gezet, KLU leiding weet er van.
