### ISSUE TITLE
[FEATURE]: Mogelijk maken voor Kader en BSB rangen om uitdienst gevangenis poort/deuren op te maken.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#1968]
### Contact Details

James Bond#1033

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kunnen de BSB/kader rangen uitdienst niet de gevangenis deuren/poorten opdoen hierdoor worden operators erg belemmerd in hun werkzaamheden wanneer zij uitdienst worden opgeroepen en snel ter plaatsen moeten komen. Omdat zij hier niet de permissie voor hebben kunnen zij niet ondersteunen bij uitbraken van gevangenissen.

**Kader rangen**:
kmar 90
kmar 95
kmar 100

**BSB rangen**:
kmar 80
kmar 81
kmar 82
kmar 83

### Wat lost deze feature op?

Als deze feature wordt goedgekeurd kunnen de operators van de BSB en kaderleden handhaven op hun plicht en dienst die zij hebben ook als zij uitdienst zijn op dat moment. Waardoor hun de reguliere eenheden van de Koninklijke Marechaussee en de Politie kunnen ondersteunen tijdens een gevangenisuitbraak of beveiliging. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
lijkt ons onnodig, ze kunne hievoor in dienst gaan

**Comment by KMarTDA** [comment]
De BSB is in sommige gevallen ook uit dienst oproepbaar en zij zijn hier ook voor uitgerust met bepaalde bewapening uit dienst..Juist bij een gevangenisalarm telt elke seconde. Als je dan eerst naar sandy shores HB moet rijden om in te klokken ben je al te laat en dan is de vogel al gevlogen. Dit is een terugkerend probleem bij verschillende BSB operators en daarom zouden wij dit toch graag willen.
