### ISSUE TITLE
Voicebug Appartementen 

### ISSUE THREAD

**Issue by BartBoos** [Tedeapolis/development#197]
Nadat je uit je appartement  komt hoor je  niemand meer, ook kunnen ze jouw ook  niet horen. om dit op te  lossen kun je even relogen. Ook kun je even iemand bellen (de persoon moet  wel  opnemen) na het telefoon  gesprek horen de personen om je  heen je weer en hoor jij hun.

**Comment by niekschoemaker** [comment]
Kun je dit morgen even opnieuw testen, denk dat het zo gefixed is.
