### ISSUE TITLE
F6 van politie en criminelen (delay) gelijk trekken.

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#1970]
### Contact Details

Cazorla#7638

### Beschrijf zo duidelijk mogelijk de feature

Er is hier al eerder een request voor gemaakt, maar blijkbaar is er weinig veranderd.

Er zit heel veel delay in als een crimineel iets wil afpakken. Hij moet op het item klikken wat al best veel delay heeft en daarna nog aantallen invullen. 
Bij politie zit er een mini delay in het fouilleren, maar kan je in 3 seconden een hele inventory leeg trekken. Zou hier aub meer delay op gezet kunnen worden? 
Zie clip: https://clips.twitch.tv/ZanyHealthyPastaAMPEnergy-0H9IePAW3Xj9HwIV

### Wat lost deze feature op?

Dit bied meer tijd voor criminelen om handelingen te ondernemen. Tevens zocht dit voor een vertraging van "combat stashing", waarbij snel spullen worden afgepakt en snel met persoon (of spullen) naar HB gereden wordt. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Er zit een delay van 2 seconden tussen elk item afpakken, dit is gedaan vanwege dat hier toen ook al gezeik over was.

Verder zie ik niet echt in wat hiermee het probleem is en zit ik niet te wachten op m'n tijd verspillen aan dingen extra moeilijk maken voor iedereen omdat het "oneerlijk is" omdat ik hier dan weer een paar uur aan kwijt ben terwijl ik zelf de impact van deze hele issue totaal niet in zie.
