### ISSUE TITLE
[FEATURE]: Boss cirkel aanpassen.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1973]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Wij hebben een tijd geleden een boss cirkel gekregen in R3D (op de rang red, deze staat op de volgende locatie 
vector3(-810.04, -208.39, 37.13)
heading: 207.63), 
enkel kunnen wij hier nog niks in.

Wij zouden graag in deze cirkel mensen kunnen aan nemen en kunnen ontslaan als dit mogelijk is.
Dan zouden er 2 rangen hier toestemming voor moeten hebben. Dit moet "red 900" & "red 1000" zijn.

- [x] Aannemen/ontslaan & promoten/demote toevoegen aan de Boss cirkel.
- [x] Enkel "red 900" & "red 1000" toegang geven tot deze cirkel.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
2e job is niet mogelijk in het werknemers register

**Comment by Rowdeeee** [comment]
> 2e job is niet mogelijk in het werknemers register

Ahh okey, dan enkel de 1e job :)

**Comment by Tom974** [comment]
Hey @Rowdeeee,

De boss cirkel zal werkend zijn na de herstart van 02:00!

**Comment by Rowdeeee** [comment]
> Hey @Rowdeeee,
> 
> De boss cirkel zal werkend zijn voor R3D - CEO & R3D - Manager na de herstart van 02:00!

Hey @Tom974, De cirkel doet het op de CEO rang. Enkel werkt deze nog niet op de manager rang. Kan hier nog even naar gekeken worden?
