### ISSUE TITLE
[FEATURE]: Zoek functie in te zetten bij de politie opslag.

### ISSUE THREAD

**Issue by Jeanpaulmorris** [Tedeapolis/development#1974]
### Contact Details

Jean-Paul M#1942

### Beschrijf zo duidelijk mogelijk de feature

Mij lijkt het handig om een zoekfunctie in de politie opslag te zetten. Aangezien er veel spullen in de opslag staat.

### Wat lost deze feature op?

Als je als agent iets uit de opslag moet zetten duurt het vrij lang. Om een zoekfunctie erin te zetten ben je sneller klaar en heb je de spullen wat je moet vinden, dan kan je direct weg.[ 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
welke opslag ?

**Comment by Jeanpaulmorris** [comment]
Item opslag waar wij spullen inleggen zoals wiet, telefoons, radio';s. Bij de politie HB.

**Comment by Tom974** [comment]
Hey @Jeanpaulmorris,

De feature zal toegevoegd zijn na de herstart van 02:00!
