### ISSUE TITLE
[FEATURE]: Rang toevoegen DTMC

### ISSUE THREAD

**Issue by TFFTDAPerry** [Tedeapolis/development#1975]
### Contact Details

maxjuh97#7233

### Beschrijf zo duidelijk mogelijk de feature

Onlangs is Kalasjj binnen TFFT gepromoveerd naar National Sergeant at Arms. Momenteel gebruikt Kalasjj de rang President in game maar het zou mooier zijn als hij zijn eigen rang zou kunnen gebruiken. 

Deze rang heet dus: National Sergeant at Arms. 
Ingame zou dat uitzien als Nat. Sergeant

Deze rang zou dezelfde permissies hebben als President en National President
In de rangorde staat deze rang tussen National President en President

Mochten er vragen zijn, kun je me altijd berichten

### Wat lost deze feature op?

Hiermee hoeft Kalasjj niet met de rang President rond te lopen maar National Sergeant at Arms waar hij hard voor gewerkt heeft. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zit erin na volgende herstart!
