### ISSUE TITLE
[FEATURE]: Veranderen Timer bankovervallen 

### ISSUE THREAD

**Issue by JoelTDA** [Tedeapolis/development#1976]
### Contact Details

Joel#6061

### Beschrijf zo duidelijk mogelijk de feature

Besproken in staffoverleg 26-02-2023 ; 
Het veranderen van de timer die staat op de grote bank. Er staat nu een reset timer van 38 tot 50 uur voordat de grote bank opnieuw gedaan kan worden. Hieruit is gebleken dat mensen daadwerkelijk een timer zetten voor hun zelf / een groep om te weten wanneer je de grote bank weer kan doen. Door deze te veranderen naar bijvoorbeeld tussen 34 en 48 of 40 en 52 maak je hier al meer afwisseling in zodat men niet altijd meer kan timen. De precieze rate laat ik even aan jullie over 

### Wat lost deze feature op?

Wat deze feature oplost is het ''campen'' en timen wanneer de bank opnieuw gedaan kan worden, en daarbij ook eventuele counters vanuit andere groepen. Want ook dat is een ding dat andere groepen timeren en wachten tot een groep een poging onderneemt om de bank te doen, om vervolgens te counteren. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
timer is al een groter tijdsbestek dan aangevraagd is, in principe kan dit al niet getimed worden
