### ISSUE TITLE
[FEATURE]: F6 menu veranderingen.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1977]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Op de R3D rang (red) staat een f6 menu. Hier moet alleen nog wat in veranderd worden.

- [x] De naam van het F6 menu veranderen naar " R3D " (https://prnt.sc/SV6an2jni0VS)
- [x] De optie Drank Mixen op elke rang van R3D zetten. (Deze staat enkel nog actief op de Boss job van R3D)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @Rowdeeee,

Momenteel werkt het zo dat de optie "Drank Mixen" wel beschikbaar komt wanneer je de outfit "Bar outfit" aantrekt. 

Maar dit moet dus aangepast worden naar dat dit ten alle tijden voor elke rang van R3D beschikbaar is?

**Comment by Rowdeeee** [comment]
> Hey @Rowdeeee,
> 
> Momenteel werkt het zo dat de optie "Drank Mixen" wel beschikbaar komt wanneer je de outfit "Bar outfit" aantrekt.
> 
> Maar dit moet dus aangepast worden naar dat dit ten alle tijden voor elke rang van R3D beschikbaar is?

Sorry zie het bericht nu pas.. Wij wisten niet dat dit aan het outfit gekoppeld was.
Maar als het mogelijk is het inderdaad op elke rang ten alle tijden laten werken! Dat zou top zijn!

**Comment by Tom974** [comment]
> > Hey @Rowdeeee,
> > Momenteel werkt het zo dat de optie "Drank Mixen" wel beschikbaar komt wanneer je de outfit "Bar outfit" aantrekt.
> > Maar dit moet dus aangepast worden naar dat dit ten alle tijden voor elke rang van R3D beschikbaar is?
> 
> Sorry zie het bericht nu pas.. Wij wisten niet dat dit aan het outfit gekoppeld was. Maar als het mogelijk is het inderdaad op elke rang ten alle tijden laten werken! Dat zou top zijn!

Hey @Rowdeeee 

Bedankt voor de reactie! Ik heb het drank mixen beschikbaar gemaakt voor elke rang ten alle tijden. Dit zal actief zijn na de restart!
