### ISSUE TITLE
[FEATURE] JUSTITIE 

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#1978]
### Contact Details

undisclosed#0001

### Beschrijf zo duidelijk mogelijk de feature

We hopen dat de informatie hieronder voldoende is en indien niet kan er contact op worden genomen :)

- [x] - Porto Kanalen in-game voor justitie medewerkers
Momenteel heeft justitie geen in-game porto's waar de medewerkers met elkaar kunnen communiceren.
Justitie doet dit momenteel via Discord, maar graag wilt justitie net zoals de andere overheidsdiensten een paar in-game kanalen om porto contact te behouden met elkaar.

- [x]  - Documentenronde bug
Als je je voertuig uit de paarse circle pakt die jouw de meldingen op de map geeft, is het niet mogelijk om spullen op te slaan in de kofferbak. Dit houdt dus in dat je je opgehaalde documenten niet kunt stoppen in je kofferbak.

- [x]  - Document ondertekening laten fixen
Als iemand van justitie een document ondertekend met uitzondering de kvk rollen en staatssecretaris staat er plots OPCO onder. 
Hier zou dus de juiste rang moeten staan.

- [x]  - Kvk inschrijving document naam kunnen veranderen
Momenteel kunnen de naam van het kvk-inschijvings document niet worden veranderd.
Dit zorgt voor veel verwarring aangezien de kvk soms meerdere documenten met die template moet uitschrijven.
Graag hebben we dan ook dat de naam van dit document veranderd kan worden.

- [x]  - Uitdienst justitie pasje toevoegen in F2
Als justitie medewerkers uitdienst gaan hebben ze geen uitdienst pasje. Graag dus dat deze toevoegd wordt.

- [ ]  - Geluidsbarrière fixen in de verhoorkamers
Momenteel kun je door het nieuwe mumble systeem de advocaat en cliënt afluisteren tijdens hun 1 op 1 gesprek om verweer op te bouwen. 
Je hoort elkaar heel zacht door het glas heen wat niet de bedoeling is omdat dit onder powergaming valt en dus direct de argumenten van de advocaat ontkracht kunnen worden.

### Wat lost deze feature op?

Porto kanalen voor justitiem edewerkers
De documenten ronde voor eens en aantal goed fixen
Document ondertekening laten fixen
Kvk inschrijving document naam kunnen veranderen
Uitdienst justitie pasje toevoegen in F2
Geluidsbarrière fixen in de verhoorkamers

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Voor porto's heb ik kanalen 150 t/m 159 aan jullie toegewezen.

**Comment by Tom974** [comment]
Het stukje "Geluidsbarrière fixen in de verhoorkamers" is helaas niet op te lossen. Als tip; ga gewoon aan de andere kant van de kamer staan en op whisper :)
