### ISSUE TITLE
[BurgerRaad]: Toevoegen van witwas punten

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1979]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

**Deze GitHub is gemaakt naar aanleiding van de BurgerRaad vergadering van 13/02/23** 

Hierin is besproken om een aantal witwas locaties toe te voegen in Grapeseed, Palleto en onder in het haven gebied.
Dit omdat momenteel alle punten kort op elkaar liggen. 

Momenteel zijn de witwas locaties:
3 in Palleto
1 in Grapeseed
1 in de haven

Hier mogen wel 1 á 2 per locatie bij komen

### Wat lost deze feature op?

Meer variatie in de witwas punten zorgt er voor dat gangs hier minder tijd aan kwijt zijn en deze tijd kunnen gebruiken voor roleplay doeleinden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
fixed
