### ISSUE TITLE
De gele circels

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#198]
De gele cirkels hebben er vandaag geen zin in.

Als je je voertuig voor 600 euro terug wilt kopen komt hij met de foutmelding dat je niet genoeg geld opzak hebt en kan je hem dus niet nemen.

In F8 zegt die niet direct iets dus zou niet weten waar het aan licht heb het laten testen door meerdere mensen.

**Comment by Willem-Dekker** [comment]
Ik ga er van uit dat dit geen issue meer is aangezien er na 9 dagen geen comment is geplaatst
