### ISSUE TITLE
[FEATURE]: 14k rang logo rechtsondering

### ISSUE THREAD

**Issue by PisaMartinez** [Tedeapolis/development#1981]
### Contact Details

zaka#4407

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag een andere logo willen voor onze rang rechtsonderin. Deze rang is nog van heel lang terug, ver voordat 14k uberhaupt bestond. Vandaar dat wij deze verandering aanvragen, deze Draak past ook bij ons thema en is onze eigen merk!
![image](https://user-images.githubusercontent.com/126700355/222200347-f7dde577-d369-4a73-af46-5bbd52424188.png)

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by PisaMartinez** [comment]
Volgensmij is de foto ook niet goed, zou de draak ook kunnen worden gecentreerd. Dus dat hij in het midden staat!

**Comment by CorruptSausage** [comment]
Fixed
