### ISSUE TITLE
[FEATURE]: Dienst Justitiële Inrichtingen Rangen + Meldkamer

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#1982]
### Contact Details

King Kai#4248

### Beschrijf zo duidelijk mogelijk de feature

Meldkamer dji (Ook voor burgers wegens bezoekuren etc.) voor rangen KMAR 51 t/m 59 & KMAR 90,95,100 & 

Naast de lonen staan beschreven welke andere features elke rang moet hebben, de rangen gaan beneden naar boven en elke rang heeft toegang tot wat de onderstaande rangen hebben met wat additionele rechten indien die zijn vermeld.

Eerste loon e.g. 1500 = indienst en de tweede is het uitdienst salaris 750.
FORMAT: Overheidsdienst - rangnummer - label - perms/autos

kmar 59 - DJI - Algemeen Directeur / Loon 1500-750  - 
kmar 58 - DJI - Operationeel Directeur / Loon 1300-650
kmar 57 - DJI - Commandant / Loon 1100-550 +Voertuigen S63 AMG
kmar 56 - DJI - Adjudant / Loon 1000-500
kmar 54 - DJI - Senior Beveiliger / Loon 700-350
kmar 53 - DJI - Medior Beveiliger / Loon 600-300 
kmar 52 - DJI - Junior Beveiliger / Loon 500-250 Wapenkluis: +HKP2000 +Alle munitie van elke wapen 
kmar 51 - DJI - Aspirant / Loon 400-200 Wapenkluis: Wapenstok, Taser, Zaklamp, fire extinguisher, snijbrander, handboeien + Indienst geen flitsboetes Voertuigen: KMar Vito Rechten: Gevangenis alarm + Gevangenis alarm kunnen aan en uit zetten. + Vliegtuig radar + Sloten HB en Gevangenis in en uitdienst. Meldkamer DJI

Voor de EUP's komt er een andere issue.

### Wat lost deze feature op?

Dit is voor de opzetting van de Dienst Justiele Inrichtingen binnen de KMar overheidsdienst. 

Overige gevangenis aanpassingen zijn momenteel hier te vinden  #1803

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @Streamcentralrulez, 

Ik neem aan dat het de bedoeling is dat algemeen directeur toegang heeft tot het bazenmenu?

Ook wilde ik even bij jou aangeven dat iedereen van de kmar standaard toegang heeft tot de touran en de sleepwagen, dus ik kan het wel aanpassen voor de dji specifiek (dat deze alleen toegang heeft tot de vito) maar dat is erg veel werk. Dus is dit per se nodig?

**Comment by CalRayy** [comment]
Toevoeging hierop is, dat je ook reguliere diensten met deze rangen. Dus als het mogelijk is bij de eup om alle rangen voor de reguliere dienst kunt zien (zie screenshot). 
![image](https://user-images.githubusercontent.com/101106299/233187964-5a0421b8-a7ba-4caf-a03f-a2878bbdeded.png)

**Comment by CalRayy** [comment]
Lonen aanpassen naar -> 
Aspirant 1000
Junior beveiliger 1050
Medior 1100
Senior 1150
Adjudant 1200
Commandant 1300
Operationeel directeur 1400
Algemeen directeur 1500

**Comment by Tom974** [comment]
Ik sluit deze ivm nieuwe issue
