### ISSUE TITLE
[Bug]: Reportslisted bug

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1984]
### Contact Details

Devv#4532

### Wat gebeurde er?

Als de reports binnen komen op het reports systeempje dan schakelt deze automatisch al naar  "In behandeling".

![image](https://user-images.githubusercontent.com/79802852/222288091-8ec47a49-2ed8-4b28-9469-31ac1a6fc921.png)

### Wat hoorde er te gebeuren?

Deze hoort naar "status nieuw" te gaan

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @DevvTDA,

Als het goed is is dit opgelost. Mocht dit toch niet zo zijn gelieve de issue weer te openen :)

Thanks!
