### ISSUE TITLE
[FEATURE]: Reportslisted streamermodus

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#1985]
### Contact Details

Devv#4532

### Beschrijf zo duidelijk mogelijk de feature

Mogelijk maken dat als je streamermodus van fivem aan heb staan dat je enkel ID ziet in het reports systeem ipv ook de steamnaam erachter, zodat de staff streamers dit ook kunnen tonen. Van chang kreeg ik namelijk te horen dat als we het systeem kleiner maken dat hij dan ging buggen dus vandaar de feature.

### Wat lost deze feature op?

Staff streamers kunnnen makkelijk reports oppakken met het systeem zonder gedoe te krijgen met privacy van steamnamen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
En het hoofdmenu een optie om te teleporteren naar de speler
