### ISSUE TITLE
[FEATURE]: Drugs Prijzen in het algemeen & (dealer)

### ISSUE THREAD

**Issue by Nick21458** [Tedeapolis/development#1986]
### Contact Details

NsGames07#2712

### Beschrijf zo duidelijk mogelijk de feature

Hey een Goedemiddag,

ik heb net geselled met wiet 40 zakken zijn momenteel 13,5k dit was bij de normale quicksell en ik deed het met dealer en ik kreeg 10,5k zwart alleen ter vergelijking doe je met dealer meer moeite om bijvoorbeeld langs het douane gebied te gaan en kloppen en wegens de meldingen die af kunnen gaan.
En ook omdat de loodsen ook zijn aangepast met de snelheid en het dus ook langer duurt etc. is het misschien ook iets om de drugs prijzen weer aan te passen in het algemeen omdat ja het duurt langer en dan krijg voor dat weer iets meer terug.

### Wat lost deze feature op?

Dat de prijzen van de drugs weer iets omhoog gaan en dat via dealer ook meer wordt geselled omdat nu doet iedereen als op de quicksell en staan de sells soms ook echt overvol. En ook buiten de dealer de algemene prijs omhoog omdat mensen die in een loods zitten nu ook langer moeten wachten op hun zakken.

Ik zei graag een bericht terug

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Quick sells zijn expres op deze prijs gezet.

En prijzen zijn afhankelijk van veel factoren, als hoeveel politie/spelers zijn er, welke dealer type gebruik je etc.
