### ISSUE TITLE
[FEATURE]: Animatie of het liefst een prop in handen toevoegen voor uitladen van specifiek drugs

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#1987]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een bepaalde animatie of het liefst een prop toevoegen die je in je handen vasthoudt wanneer je drugs aan het uitladen bent. Eventueel die kort in je handen laten houden. Bij het inladen hoeft dit niet.

### Wat lost deze feature op?

Momenteel laden spelers 10-20 voertuig op één plek uit, in het openbaar, op klaarlichte dag. Zo'n feature zou een goede oplossing zijn en zorgt voor meer roleplay voor zowel de criminelen als de politie. Besproken in staffoverleg.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
maak maar even een lijstje van welke props en emotes @ARJ3N

**Comment by ARJ3N** [comment]
Heb eventjes gekeken maar eventueel iets van dit voor zakjes?
p_weed_bottle_s

En eventueel iets als dit voor planten?
prop_weed_02

Ik verzin ook maar iets, misschien dat er nog betere alternatieven zijn.
@Ljosfari
