### ISSUE TITLE
[EUP]: Vrouwenkleding voor zulu Politie 

### ISSUE THREAD

**Issue by FoxieF** [Tedeapolis/development#1988]
### Contact Details

Foxie#6344

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Er is momenteel geen vrouwen kleding als je als vrouw zijnde in de zulu wil dus een piloten uniform, dit missen wij in ons EUP menu het zou wel een leuke toevoeging zijn als wij deze ook kregen net als de mannen binnen te politie wel hebben 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
@FoxieF  Is gemaakt, staat klaar om de server ingepushed te worden :) 

![Image](https://user-images.githubusercontent.com/79802852/222969345-996677ea-bc32-4b38-b41b-a10ba0d4f924.png)
