### ISSUE TITLE
[FEATURE]: Onderwereld dokter van gemeenteraad afhalen (Eigen rang) 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#1990]
### Contact Details

Vayen#6904

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staff overleg is er besproken om een Onderwereld dokter rang te maken. Dit omdat ons f6 zo groot is en eventueel misschien in toekomst ook 1/2 spelers te kunnen werven. 

**Naam rang:** Onderwereld Dokter

**Rangen:**
Onderwereld Dokter - Baas
Onderwereld Dokter - Dokter
Onderwereld Dokter - Stagiair

**Wat in de f6:**  
- [x] Reanimeren 
- [x]  hartslag meten 
- [x]  Wapens confisqueren wanneer ze dood zijn. 
- [x]  Fouilleren
- [x]  Ambulance props 

**Afbeelding voor de rang**

![Screenshot_6](https://user-images.githubusercontent.com/90053273/222981091-d2a8f5da-03c3-43e2-b8d8-519727dae10d.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Voor de rangen had ik dit in gedachten: 
Onderwereld Dokter - Baas
Onderwereld Dokter - Dokter
Onderwereld Dokter - Stagiair

**Comment by Tom974** [comment]
Hey @Vayenn & @CalRayy,

De job is toegevoegd en zal actief zijn na de volgende herstart!

Je kunt de baas job aan jezelf geven via (/setjob id odwdokter boss). De bazencirkel voor het personeelsbeheer en pot beheer is te vinden waar jullie kledingcirkel ook staat ;)
