### ISSUE TITLE
[FEATURE]: Meer Quicksells in het zuiden.

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#1992]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

**Tijdens staff overleg is overlegd dat er meer quicksells moeten komen in het zuiden van TDA.**

Op dit moment zijn er maar 2 in het zuiden en hier zouden er nog 2 bij kunnen.

Om Niek wat moeite te besparen heb ik al wat locaties gezocht waar de nieuwe quicksells geplaatst kunnen worden.

### Locatie 1: 
![image](https://user-images.githubusercontent.com/120292087/222983723-98b40769-5439-4961-bd4a-be058a13f50b.png)

### Locatie 2: 
![image](https://user-images.githubusercontent.com/120292087/222983752-c60f55d9-5b94-4fa2-9c7d-0db8e39515a9.png)

Ik heb nog meer locaties gevonden die goed zijn voor quicksell locaties, dus al willen jullie die kunnen jullie in mijn DM sliden

### Wat lost deze feature op?

Meer diversiteit in de quicksells

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Toro-Carri** [comment]
Scheelt mij weer zoeken, thanks @ExoticaTDA xxx

**Comment by Ljosfari** [comment]
fixed
