### ISSUE TITLE
[FEATURE]: Barman shirt

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1993]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag voor bij onze bar mannen/vrouwen een simpel tshitje willen met het logo van R3D op de mouwen!

Het gaat dan over deze 2 modellen;
Mannan:
mp_m_freemode_01_mp_m_vinewood_jbib_023
https://prnt.sc/bZXWCkPzKCfv
Vrouwen:
mp_f_freemode_01_mp_f_vinewood_jbib_021
https://prnt.sc/8ruqPqtrGsTJ

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
@Rowdeeee   Zoiets aan beide kanten? 
![image](https://user-images.githubusercontent.com/79802852/223586353-8d8e8579-ae61-49c7-896b-390b2a227721.png)

**Comment by DevvTDA** [comment]
![image](https://user-images.githubusercontent.com/79802852/223587484-459143d7-ec87-41f7-83f0-5121a2b6e2ef.png)

**Comment by Rowdeeee** [comment]
@DevvTDA jah perfect!

**Comment by DevvTDA** [comment]
@Rowdeeee Heb ze door gecommit, moet enkel nog gepushed worden :) Gelieve dus github commits in de gaten te houden. 
Mannen 
Torso 1: 313
Torso 2: 3
Vrouwen:
Torso 1: 324
Torso 2: 3
