### ISSUE TITLE
[EUP]: EUP politie aanpassing vrouwen DSI helm / Hondenbegeleiders kleding / aanpassing aan de Vesten 

### ISSUE THREAD

**Issue by FoxieF** [Tedeapolis/development#1994]
### Contact Details

Foxie#6344

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

We missen bij mannen bij politie soms nog bepaalde dingen en het zou leuk zijn als wij ook deze opties kregen hieronder vallen de 
- Hondenbegeleider [ Voorbeeld bij de mannen ] 
![image](https://user-images.githubusercontent.com/126918219/223205111-1345e219-8ff2-46dc-848b-40278d4c5e5a.png)

- Hondenbegeleider event [ Voorbeeld bij de mannen ] 
![image](https://user-images.githubusercontent.com/126918219/223205031-b818bce3-f2fb-46aa-96c7-298a3c988a35.png) 
![image](https://user-images.githubusercontent.com/126918219/223205065-3f199c8a-02d8-4b78-b15d-1f86fd6bf63d.png)

- DSI helmen voor vrouwen [ Voorbeeld bij de mannen ] 
we hebben als vrouw nu wel DSI kleding enkel mist de mogelijkheid om een helm op te doen nog 
![image](https://user-images.githubusercontent.com/126918219/223204950-8a5c8af3-9255-4e6e-a1e2-ffd36521720e.png) 
![image](https://user-images.githubusercontent.com/126918219/223204964-2a24a2f5-ff76-49ea-9ea3-ef192ca1a52c.png)

-  De Zwaren [ Kogelwerende] vesten voor vrouwen [ Onze vesten momenteel in vergelijking met die van de mannen] 
![image](https://user-images.githubusercontent.com/126918219/223204874-bad6a9dc-b403-488c-ad58-845023215264.png) 
![image](https://user-images.githubusercontent.com/126918219/223204893-06e1e98c-33b8-48a2-9fdf-8aff52a19cb4.png)

- De Ongemarkeerde vesten voor vrouwen  [ Dit is momenteel de genen van de mannen ] 
![image](https://user-images.githubusercontent.com/126918219/223204775-0783b74f-bd28-489e-bd39-d4d85984b186.png) 
![image](https://user-images.githubusercontent.com/126918219/223204786-d896bbc9-5ee5-4396-98a9-27a5c8b3d6b0.png)

Momenteel hebben wij enkel van dit rijtje de zwaaren vesten maar zien deze er niet goed of realistisch uit vergeleken met de mannen aangezien het een steekvest is met het woord Politie erop 

Ook zou het prettig zijn al zouden we via de EUP ook kleding uit te kunnen doen zodat we niet elke keer helemaal opnieuw onze outfit aan hoeven te doen 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
- [ ] Unmarked vest vrouwen
- [ ] Hondenbegleider vest 
- [ ] DSI Helm
- [ ] Toevoegen om dingen uit te doen zoals vesten (mocht dit meer zijn reageer even in de github

@FoxieF Heb verder even gekeken naar het kogelwerend vest irl van de politie en daar zie ik wel dat zij een vest aan hebben die er zoals dit uitziet 
![image](https://user-images.githubusercontent.com/79802852/223689375-4a566410-3d28-4f58-84d7-5932d8101e82.png)

**Comment by DevvTDA** [comment]
@FoxieF  Helmen kan ik niet toevoegen... in ieder geval de standaard wel die er al inzitten maar kan ze niet customizen ik kan deze bestanden namelijk niet vinden :(

**Comment by DevvTDA** [comment]
De volgende dingen heb ik klaar staan om doorgepushed te worden
Politie vesten:
- Unmarked
- Steekvest
- Verkeerspolitie
- Hondengeleider
- Event hondengeleider
- Kogelwerend vest

DSI Helmen 3 stuks

Mogelijkheid om Vesten, Helmen en Maskers af te doen via EUP.

Houd de github commits op discord dus in de gaten :) @FoxieF
