### ISSUE TITLE
[FEATURE]: cirkel bazenheli reznikov

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#1995]
### Contact Details

EpicTom#5874

### Beschrijf zo duidelijk mogelijk de feature

Wij Reznikov zijn laatst level 4 geworden en hebben dus toegang gekregen tot een bazenheli. Nu is deze nog niet geplaatst en zouden wij dit graag willen.
Hier die coords waar de cirkel moet staan:
![image](https://user-images.githubusercontent.com/104857888/223264916-5f4e9cfc-0e36-495c-bd9c-5513630cd23a.png)

De spawnplek zal hetzelfde moeten zijn als de normale heli spawner.

### Wat lost deze feature op?

Dat we als groep een bazenheli hebben.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Gefixt na de restart.
