### ISSUE TITLE
[FEATURE]: Kleding Cirkel

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#1996]
### Contact Details

dead123x5#0001

### Beschrijf zo duidelijk mogelijk de feature

Hey, ik zou graag een kleding cirkel willen krijgen op de volgende locatie als dit mogelijk is!
Dit is in een nieuw gebouw van R3D - Het Sleephuis

x: 550.65 y: -181.88 z: 54.49 h: 358.17
https://prnt.sc/6qQgdgLtU65l

- [ ] Kleding cirkel toevoegen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AntonMTDA** [comment]
Hey @Rowdeeee, is hier toesteming voor ? :D

**Comment by Rowdeeee** [comment]
> Hey @Rowdeeee, is hier toesteming voor ? :D

Neeh ik heb hier nog geen toestemming voor gevraagd.

**Comment by CalRayy** [comment]
> > Hey @Rowdeeee, is hier toesteming voor ? :D
> 
> Neeh ik heb hier nog geen toestemming voor gevraagd.

Zou je dit wel kunnen doen, dan kunnen we dit doorvoeren :) !

**Comment by Rowdeeee** [comment]
> > > Hey @Rowdeeee, is hier toesteming voor ? :D
> > 
> > 
> > Neeh ik heb hier nog geen toestemming voor gevraagd.
> 
> Zou je dit wel kunnen doen, dan kunnen we dit doorvoeren :) !

Jah @CalRayy of @AntonMTDA we hebben hier nu toestemming voor vanuit dusty!

**Comment by CalRayy** [comment]
> > > > Hey @Rowdeeee, is hier toesteming voor ? :D
> 
> > > 
> 
> > > 
> 
> > > Neeh ik heb hier nog geen toestemming voor gevraagd.
> 
> > 
> 
> > Zou je dit wel kunnen doen, dan kunnen we dit doorvoeren :) !
> 
> 
> 
> Jah @CalRayy of @AntonMTDA we hebben hier nu toestemming voor vanuit dusty!

Ik zal hier morgen in de middag naar kijken voor je :)

**Comment by CalRayy** [comment]
Zit erin bij de volgende github commit wanneer Niek tijd heeft.

**Comment by CalRayy** [comment]
@Ljosfari Zou je deze github willen sluiten als "complete" ? (ik heb helaas geen rechten om dat te doen).
