### ISSUE TITLE
[EUP]: Vrouwelijke stropdas 14k

### ISSUE THREAD

**Issue by LucasAbruzzi** [Tedeapolis/development#1999]
### Contact Details

Lucas.#2282

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

We hebben onlangs de vrouwelijke versie van het jasje aangepast en bij deze dan ook de stropdas:

[Female Stropdas.zip](https://github.com/Tedeapolis/development/files/10914160/Female.Stropdas.zip)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
![image](https://user-images.githubusercontent.com/79802852/223583463-3caa4dc9-525d-4a5d-baf2-822f2e85f34f.png)

Ik heb het gecommit moet enkel nog gepushed worden door Niek :) dit zal dan staan op ketting: 10 

Houd dus Github-commits toe in de main discord ! :D
