### ISSUE TITLE
Een soort van ruitdienst ambulancier 

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#20]
Als alle ambulanciers uit dienst zijn dat je bij een pad of een cirkel verband of gewoon healing kan kopen een soort van EHBO kit. Zou ook mogen werken voor als er wel ambulance is maar dat het bevoordeelt wel redelijk lang duurt dat je geheald wordt.

to-do:
- [ ] zoeken naar systeem hier voor
- [ ]  testen van systeem

**Comment by Willem-Dekker** [comment]
wordt naar gekeken is een plugin voor gevonden die moet worden getest

**Comment by Willem-Dekker** [comment]
to-do:

- [ ] zoeken naar systeem hier voor
- [ ] testen van systeem
