### ISSUE TITLE
Cardealer auto's kopen werkt niet

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#200]
![afbeelding](https://user-images.githubusercontent.com/69365961/94270536-79857280-ff40-11ea-911f-7628ae357f99.png)

Dit is de error die je krijgt zodra je een voertuig wilt kopen (heb het getest bij supporter auto's omdat ik daar de report over kreeg).

**Comment by niekschoemaker** [comment]
Is na volgende herstart gefixed.

Als issue nog steeds blijkt voor te komen gelieve issue te reopenen.
