### ISSUE TITLE
[FEATURE]: Echte radiostations er uit en de GTA radio's weer terug

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2001]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

De echte radiostations er uit halen via de radiowheel en de GTA radio's weer terug. Uiteraard een uitzondering voor TDA radio.

### Wat lost deze feature op?

Is leukere GTA muziek!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Ahh jammer, vond het wel leuk soms het foute uur of SLAM op te zetten

**Comment by CorruptSausage** [comment]
Wellicht dit even overleggen met de andere staffleden, geloof best dat hier meningen over verschilt zijn.

**Comment by ARJ3N** [comment]
Dit is gedaan. :) @CorruptSausage

**Comment by CorruptSausage** [comment]
Top

**Comment by AntonMTDA** [comment]
Deze was al door gevoerd toch ? :D

**Comment by Tom974** [comment]
> Deze was al door gevoerd toch ? :D

Nope, moet nog gedaan worden.

**Comment by Tom974** [comment]
echte radios for the win!!!!

**Comment by ARJ3N** [comment]
> echte radios for the win!!!!

Waarom is die closed as not planned @Tom974

**Comment by niekschoemaker** [comment]
> > echte radios for the win!!!!
> 
> Waarom is die closed as not planned @Tom974

Omdat ik dit niet zie als iets wat toegevoegde waarde  heeft, juist het omgekeerde.
