### ISSUE TITLE
[FEATURE]: Forensische opsporing toevoegen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2003]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Een script toevoegen waardoor het mogelijk is om forensische opsporing te doen.
https://www.youtube.com/watch?v=MH2ApneZ-Xs&ab_channel=CoreResources
https://www.c8re.store/package/4265655

### Wat lost deze feature op?

Zorgt voor veel meer roleplay voor zover de criminelen als de politie.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Dit script is voor Qbcore, heb je wellicht ook een script hiervan voor esx?

**Comment by CorruptSausage** [comment]
Checklist:

- [x] Niet alles bewijzen zijn geldig (randomizen)
- [x] Alleen police boss kan bewijzen verwijderen
- [ ] UI aanpassingen
- [ ] Emote uitvoeren tijdens het analyseren (Dat het niet automatisch gaat)
- [ ] Alleen dna vinden van mensen waarvan het dna bekend is
- [x] Beschikbaar vanaf recherche junior
- [ ] Zodra je dna afneemt van iemand dat je ook gelijk vingerafdrukken afneemt, zodat je altijd de link hebt.
- [ ] Alleen aangeven wat wie het is als het dna bekend is

**Comment by ARJ3N** [comment]
Is het niet een dik idee om de hulzen te kunnen linken aan een vuurwapen? Op die manier kun je daadwerkelijk RP eraan verbinden. Als je gelijk een volledige naam kan krijgen van een huls is dat nogal onrealistisch.

**Comment by Tom974** [comment]
Als update; basically done, zit alleen nog even het een en ander te testen.

**Comment by Tom974** [comment]
Zit erin na de herstart.
