### ISSUE TITLE
[FEATURE]: ESB Official Gang

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#2005]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

ESB is vanaf heden een officiele gang geworden namens Crimineel Aanspreekpunt. Daar moeten nog een aantal dingen geregeld worden voor de ingame rang.

De ingame rang kan het beste "ESB" genoemd worden voor /setjob.

Rangen:

Van Hoog naar Laag >

Shotcaller (boss) - Volledig F6 + Bazenmenu

Young Shotcaller (underboss) - Volledig F6 

Street General - Volledig F6

Big Gangster - Volledig F6

Soldier - Volledig F6

Gangster - Volledig F6

Young Gangster - F6 via menu, maar het daadwerkelijke fouilleren moet geaccepteerd worden. Wel permissies om af te pakken indien fouilleren geaccepteerd wordt.

Runner - F6 via menu, maar het daadwerkelijke fouilleren moet geaccepteerd worden. Wel permissies om af te pakken indien fouilleren geaccepteerd wordt.

Recruit - F6 via menu, maar het daadwerkelijke fouilleren moet geaccepteerd worden. Wel permissies om af te pakken indien fouilleren geaccepteerd wordt.

![ba2f04026-ballas-logo (1)](https://user-images.githubusercontent.com/32983383/224312674-63e0320c-5e9f-49da-881c-0db2f11a8e10.png)

^het logo hierboven mag toegevoegd worden als ingame job logo.

### Wat lost deze feature op?

Offi gang geworden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @DaanDeW, 

Op welke locaties moeten de cirkels van deze gang precies komen? 
(Hier heb ik het over de helikoptercirkels, de voertuigencirkels, de bazencirkel, de kledingcirkel en de opslagcirkel)

Indien mogelijk graag de coordinaten doorsturen (deze kun je zien door /coords ingame te gebruiken)! 

Bedankt!

**Comment by Tom974** [comment]
Ik ben op de hoogte gesteld dat de cirkels etc op de oude plek van revoltes konden. 

De rangen zijn toegevoegd onder de naam "esb" (dus /setjob <id> esb boss = baas rang). 

Dit zal actief zijn na de volgende herstart!

**Comment by DaanDeW** [comment]
Wapen inkoop vanaf Street General en hoger
