### ISSUE TITLE
[Bug]: 2e job RED

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#2006]
### Contact Details

Devv#4532

### Wat gebeurde er?

Met RED als 2e job kan je niet alles zoals behoren, F6 inhoud is niet te zien en ook kan ik hier als baaszijnde ook geen loontjes uit de lootjeswinkel halen. Mogelijk dat 2e job ook net zo toegangbaar word als de eerste? dit voorkomt de hele tijd dat ik van job moet wisselen. 

### Wat hoorde er te gebeuren?

Alles moet hetzelfde werken als de rang op job 1 

### Wat veroorzaakt de bug?

doordat het op de 2e job staat

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
is niet mogelijk helaas
