### ISSUE TITLE
[EUP]: Vrouwen Kleding TDA Media

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2007]
### Contact Details

Dyon#9999

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

**Ik maak deze Github na aanleiding van een reddit suggestie:** https://www.reddit.com/r/tedeapolis/comments/11ixesz/kleding_tda_media/ 

Op het moment is er alleen TDA Media kleding voor mannen, dit gaat om de volgende items:

**Polo:**
Voorkant:
![image](https://user-images.githubusercontent.com/120292087/224509136-2568a198-0953-45c5-8280-1004d9eb0fdb.png)

Achterkant:
![image](https://user-images.githubusercontent.com/120292087/224509154-8b9c7d55-2161-43b9-af7f-c2bff5af12a1.png)

**Steekvest Zwart:**
Voorkant: 
![image](https://user-images.githubusercontent.com/120292087/224509176-bec30b04-0c48-414d-bc88-9423c56a879f.png)

Achterkant:
![image](https://user-images.githubusercontent.com/120292087/224509191-52d20dad-0e62-4140-ab91-b8ec15133e9d.png)

**Steekvest Blauw**
Voorkant: 
![image](https://user-images.githubusercontent.com/120292087/224509204-1ee5261c-2f7f-4980-9bf9-828097ffb08a.png)

Achterkant:
![image](https://user-images.githubusercontent.com/120292087/224509210-b0a559ae-ff85-4981-af8e-d6218bac6266.png)

### Vrouwen Variant
Nou is de vraag of hier ook een vrouwen variant van kan komen. Er werken ook vrouwen bij TDA Nieuws en deze hebben op het moment geen werkkleding om te dragen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Hey @ExoticaTDA de files van nieuws heb ik niet gemaakt die waren al gemaakt, dus misschiend at je bij de eigenaar kan vragen of hij de vrouwen variant kan maken? weet niet wie het is tho

**Comment by ExoticaTDA** [comment]
> Hey @ExoticaTDA de files van nieuws heb ik niet gemaakt die waren al gemaakt, dus misschiend at je bij de eigenaar kan vragen of hij de vrouwen variant kan maken? weet niet wie het is tho

Pff, dat durf ik je ook niet te zeggen. Ik zal het wel antwoorden op de Reddit Suggestie en dan kan die contact opzoeken met de eigenaar van TDA Nieuws

**Comment by ExoticaTDA** [comment]
> Hey @ExoticaTDA de files van nieuws heb ik niet gemaakt die waren al gemaakt, dus misschiend at je bij de eigenaar kan vragen of hij de vrouwen variant kan maken? weet niet wie het is tho

Zal ik deze dan weer sluiten? Ik DM je dan wel gewoon als ik kleding files van ze krijg.

**Comment by DevvTDA** [comment]
Maak dan gelieve een nieuwe github aan :) zo haall ik alles gewoon goed bij elkaar kwa opdrachten.
