### ISSUE TITLE
toevoegen van porto

### ISSUE THREAD

**Issue by krizz696** [Tedeapolis/development#201]
kan de het porto kledingstuk en een riem toegevoegd worden aan de uniformen voor ambulance , ovd , verpleger

de rest van de uniformen hebben jasjes en daar gaat de porto door glitchen , maar mag naar gekeken worden dat het toch mogelijk is 

kledingstuk 
Tshirt 55 = riem met zakjes
kogelvrije vest 1 = ptt mic op schouder

eventueel ook de stetoscoop verwijderen aangezien deze door de kledij glitched

**Comment by Willem-Dekker** [comment]
Ik heb de proto's toegevoegd aan de autfits maar custom dingen gaan er denk ik niet komen
