### ISSUE TITLE
[Bug]: Karmellos DJ cirkel stuk

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#2010]
### Contact Details

Devv#4532

### Wat gebeurde er?

De dj cirkel bij het huis van karmellos is helaas stuk dit nadat er volgens mij een update was van cirkels ( cirkelplaatsing ergens anders) of iets in die richting. 

### Wat hoorde er te gebeuren?

als je bij de DJ tafel staat moet er een cirkeltje komen waar je dus uiteindelijk muziek kan afspelen/ 

### Wat veroorzaakt de bug?

ik denk update van iets anders waardoor hij kapot gegaan is.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
@niekschoemaker Ik heb het bekeken in de dev server, maar daar werkt hij gewoon. Ik denk dat dit komt door de nieuwe second job support die er laatst in is getoevoegd.

**Comment by niekschoemaker** [comment]
> @niekschoemaker Ik heb het bekeken in de dev server, maar daar werkt hij gewoon. Ik denk dat dit komt door de nieuwe second job support die er laatst in is getoevoegd.

Dev server en main staan gelijk daarin

Ik zie wel dat bloods_djbooth dubbel erin staat weet niet of dat er iets mee te maken heeft, in elkgeval dat is een duplicate index.

Verder staat karmellos z'n cirkel op de job bratva, weet niet of dat klopt, en weet ook niet om welke cirkel het exact gaat.

De karmellos cirkel staat in config op de coordinaten `vector3(-1593.64, 762.58, 189.30)`

**Comment by DevvTDA** [comment]
@niekschoemaker 
Dit zijn inderdaad de juiste coords, en hij moet op de job bratva komen inderdaad :)

**Comment by TDASammie** [comment]
Ik weet niet of er iets is aangepast, maar hij doet het inmiddels weer.

**Comment by CalRayy** [comment]
> Ik weet niet of er iets is aangepast, maar hij doet het inmiddels weer.

Klopt, had Niek gefixt. @Tom974 can you close this one please? 🥺
