### ISSUE TITLE
[FEATURE]: Een aantal shops voor level 1 gangs (job criminal 0) verwijderen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2011]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Graag de level 1 gangshops die op onderstaande coördinaten staan weghalen:

- X: 811 Y: -2156.75 Z: 29.62
- X: 251.59 Y: -49 Z: 69.94
- X: 1693.62 Y: 3758.67 Z: 34.71
- X: -117.87 Y: 2697.32 Z: 18.55
- X: -3171.67 Y: 1086.59 Z: 20.84

### Wat lost deze feature op?

Besproken in staffoverleg.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Done.
