### ISSUE TITLE
[FEATURE]: Aanpassingen wapens

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2012]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

- [x] weapon_bullpuprifle_mk2 zichtbaar op rug.
- [x] weapon_combatshotgun zichtbaar op rug.
- [x] weapon_combatshotgun een andere item naam geven.
- [x] weapon_revolver trekanimatie toevoegen.
- [x] weapon_musket toevoegen op rug.
- [x] Voor bovenstaande wapens de juiste ammo bruikbaar maken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Ljosfari** [comment]
wat bedoel je met de combatshotgun een andere item naam geven ? @ARJ3N

**Comment by ARJ3N** [comment]
Momenteel heet deze nog WEAPON_COMBATSHOTGUN in bijvoorbeeld je inventory via F2 of in de kofferbak van je voertuig. De bullpuprifle is bijvoorbeeld hernoemd naar de QBZ-95 (als ik het goed heb). @Ljosfari

**Comment by Tom974** [comment]
Hey @ARJ3N,

Aan welke ammo types zat je te denken voor onderstaande wapens? 

WEAPON_REVOLVER
WEAPON_MUSKET

**Comment by ARJ3N** [comment]
@Tom974 

Revolver kan pistol ammo in.
Musket is een beetje een geval apart, je zou kunnen kiezen voor rifle of shotgun.

**Comment by Tom974** [comment]
Toppie!

De aanpassingen zitten er na volgende restart in
