### ISSUE TITLE
[Bug]: Level 2 gangsysteem heet geen wapen mods/tune optie

### ISSUE THREAD

**Issue by DylanPeys** [Tedeapolis/development#2013]
### Contact Details

dyl6n#0001

### Wat gebeurde er?

Je kunt geen M1911's tunen. Er kunnen geen modificaties op omdat de optie er niet bij staat.

### Wat hoorde er te gebeuren?

In het menu van de opslag hoort deze optie te verschijnen zodat je de wapens kunt tunen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Is gefixed na volgende herstart
