### ISSUE TITLE
[Bug]: Je kan direct je wapen trekken nadat je in je benen wordt geschoten

### ISSUE THREAD

**Issue by TFFTDAPerry** [Tedeapolis/development#2015]
### Contact Details

maxjuh97#7233

### Wat gebeurde er?

https://www.youtube.com/watch?v=lQHMI2RCu_Y
Zoals je ziet in de video kan je direct je wapen trekken als je in je benen bent geschoten. 

### Wat hoorde er te gebeuren?

Je hoort namelijk een x aantal seconden niet je wapen te kunnen trekken

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Dit zou gefixed moeten zijn
