### ISSUE TITLE
[Bug]: Op en aftakelen werkt soms niet sleepwagen (ANWB)

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2016]
### Contact Details

DeStefanoKiller#4442

### Wat gebeurde er?

Als wij via het F6 menu op takelen klikken, dan werkt het niet dit probleem is voor zowel aftakelen als optakelen. Kijk video voor wat er gebeurd. 

**Aftakelen**  
https://medal.tv/games/gta-v/clips/ZCSlVK9xllF4A/HpmvfzSXMc2c?invite=cr-MSxPbUIsNDMwMjA0MDUs

**Optakelen**
https://medal.tv/games/gta-v/clips/ZDg5hpCjjL4Or/H8tQsfGR5ZL9?invite=cr-MSxIRmssNDMwMjA0MDUs

### Wat hoorde er te gebeuren?

Als het voertuig nog niet op de sleepwagen staat en je klikt op "ANWB Takelwagen" dan hoort het voertuig op de sleepwagen te komen, en als het voertuig erop staat en je klikt weer op "ANWB Takelwagen" dan hoort het voertuig weer van de sleepwagen af te komen. Maar beide van deze handelingen werkt best wel vaak niet. 

### Wat veroorzaakt de bug?

-

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Is gefixed na volgende herstart

**Comment by niekschoemaker** [comment]
Oh mijn god, I know what happened.

Maar je kunt hem er ook gewoon handmatig ff oprijden toch.

Maar ik had de code aangepast zodat hij niet sketchy een voertuig bijhoudt in het script maar via gta zelf checkt of er iets aan het voertuig vast zit, maar ik denk dat die ramp dus voor wat issues zorgt, ik zal de code ff dubbel checken.

Want hij zegt dus ook dat het voertugi is afgekoppeld dus denk dat daar een deel van de issue zit.

**Comment by niekschoemaker** [comment]
Of wacht, het kan ook zijn dat het komt omdat het aankoppelen gedaan wordt door iemand die de takelwagen niet in scope heeft, in dat geval is het niet echt te fixen behalve door ff in beide voertuigen te stappen.

Dus eerst in de auto welke je op wilt takelen, en dan op de flatbed.

Een makkelijkere fix is om gewoon de andere plugin te gebruiken en dus het voertuig er gewoon zelf ff op te rijden en dan op e te klikken.

Als het goed is zou het aftakelen ook moeten werken wanneer je hem via daar aankoppeld dacht ik.

**Comment by niekschoemaker** [comment]
Ik zou zeggen test het ook even een beetje uit, ik gok als je eerst in stapt in de auto, en dan in de flatbed, en daarna takelt dat het dan ook wel kan werken, maar dat is even uitzoeken.

**Comment by Tom974** [comment]
Hey @DeStefanoKiller, is dit nogsteeds een probleem (ook na het uitvoeren van de stappen in de berichten hierboven) ?

**Comment by DeStefanoKiller** [comment]
> Hey @DeStefanoKiller, is dit nogsteeds een probleem (ook na het uitvoeren van de stappen in de berichten hierboven) ?

Wij hebben in de tussen tijd wel hier en daar een paar dagen gehad dat het even niet werkte zonder dat er iets veranderd was. Maar voor nu werkt alles gewoon weer.

**Comment by Tom974** [comment]
Toppie, dan sluit ik deze issue voor nu!
