### ISSUE TITLE
[FEATURE]: Rang aanpassingen 14K

### ISSUE THREAD

**Issue by PisaMartinez** [Tedeapolis/development#2017]
### Contact Details

zaka#4407

### Beschrijf zo duidelijk mogelijk de feature

**_Totaal nieuwe rangschikking voor de 14K Triade._**

![image](https://user-images.githubusercontent.com/126700355/225438437-e50d0ff4-fdf2-4f64-8470-1b7978de40d6.png)

- [x] Dragonhead (龙头) - Blijft hetzelfde
- [x] Mountain Master (山地大师) - Blijft hetzelfde, behalve de naam aanpassen
- [x] Nieuwe rang: Vanguard (先锋): Leiding. F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Toegang tot wapens tunen + inkopen. Toegang tot gangheli!
- [x] Nieuwe rang: Incense Master (香師): Leiding Proefperiode. F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Toegang tot wapens tunen + inkopen. Toegang tot gangheli! 

- [x] White Paper Fan (白皮书风扇)- Blijft hetzelfde 
- [x] Straw Sandal (草编凉鞋) - Aanpassen, F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Toegang tot wapens tunen, maar niet inkopen.
- [x] Purple Claw (紫爪) - Aanpassen, F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Geen toegang meer tot tunen/inkopen.
- [x] Red Pole (红极): Blijft hetzelfde 
- [x] Blue Lantern (蓝灯笼): Blijft hetzelfde
- [x] Rice Picker (捡稻子的人): Aanpassen (2de meelooprang), F6 menu en toegang tot dingen in de opslag te leggen, maar niet eruit te halen.
- [x] Grass Picker (撿草機): Aanpassen (meelooprang). Toegang tot /rs confisqueer en voertuigen in en uit de opslag te doen. Kan ook dingen in de opslag leggen, maar niet eruit halen.

_IRL Rangen:_
![image](https://user-images.githubusercontent.com/126700355/225444044-80e99f38-3234-401c-b1e7-37978d2b8de0.png)

### Wat lost deze feature op?

Wij vragen deze rangen aan omdat wij momenteel best veel problemen hebben met de rangen. De meelopers krijgen momenteel de Rice Picker rang ingame, omdat hij niet klopt. Dit zou het ook realistischer maken, sinds dit de rangen zijn die IRL ook worden toegepast binnenin de Triade. 

Wij hopen dat er snel word geantwoord op deze GitHub, en alvast bedankt! (Voor meer vragen zou je MOON#1337 of Clay. D#5513 op Discord kunnen berichten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by PisaMartinez** [comment]
> Hey @PisaMartinez,
> 
> Als ik het goed begrijp blijven er dus ook rangen bestaan? Moeten er dus alleen dingen toegevoegd worden of ook rangen gewijzigd worden of misschien zelfs verwijderd?
> 
> Is het misschien mogelijk voor jou om een lijstje te maken welke rangen toegevoegd moeten worden, welke rangen hun permissies gewijzigd moeten worden en/of welke rangen verwijderd moeten worden?
> 
> Zie #1860 als voorbeeld van wat ik bedoel
> 
> Bedankt!

Dragonhead (龙头) - Blijft hetzelfde
Mountain Master (山地大师) - Blijft hetzelfde, behalve de naam aanpassen
- Nieuwe rang: Vanguard (先锋): Leiding. F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Toegang tot wapens tunen + inkopen. Toegang tot gangheli!
- Nieuwe rang: Incense Master (香師): Leiding Proefperiode. F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Toegang tot wapens tunen + inkopen.
White Paper Fan (白皮书风扇)- Blijft hetzelfde 
Straw Sandal (草编凉鞋) - Aanpassen, F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Toegang tot wapens tunen, maar niet inkopen.
Purple Claw (紫爪) - Aanpassen, F6 menu en toegang tot dingen in de opslag leggen, en eruit te halen. Geen toegang meer tot tunen/inkopen.
Red Pole (红极): Blijft hetzelfde 
Blue Lantern (蓝灯笼): Blijft hetzelfde
Rice Picker (捡稻子的人): Aanpassen (2de meelooprang), F6 menu en toegang tot dingen in de opslag te leggen, maar niet eruit te halen.
Grass Picker (撿草機): Aanpassen (meelooprang). Toegang tot /rs confisqueer en voertuigen in en uit de opslag te doen. Kan ook dingen in de opslag leggen, maar niet eruit halen.

**Comment by Tom974** [comment]
Zit erin na de herstart!
