### ISSUE TITLE
[FEATURE]: Logo rechtsonderin 14K

### ISSUE THREAD

**Issue by PisaMartinez** [Tedeapolis/development#2018]
### Contact Details

zaka#4407

### Beschrijf zo duidelijk mogelijk de feature

Wij hadden laatst een logo aanpassing, alhoewel die te klein voor ons overkwam! Vandaar de nieuwe aanvraag. Wij zouden graag een witte rondje willen hebben, in plaats van de huidige blauwe die elke groep heeft! Hierbij de bijlagen.

![Schermafbeelding_2023-03-10_om_12 00 29-removebg-preview (1)](https://user-images.githubusercontent.com/126700355/225456117-7e47a8d7-6958-42d8-9981-727da271222d.png)
![image](https://user-images.githubusercontent.com/126700355/225456135-df5b320c-e707-4e19-bc53-1a73311c6cc5.png)

### Wat lost deze feature op?

Te kleine logo atm

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
De kleur van het rondje is niet aan te passen.
