### ISSUE TITLE
[FEATURE]: Tatoeages niet syncen tussen characters

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2019]
### Contact Details

Arjen#0001

### Beschrijf zo duidelijk mogelijk de feature

Dat je tussen verschillende characters verschillende tatoeages kunt hebben.

### Wat lost deze feature op?

Zorgt ervoor dat je niet op elk character dezelfde tatoeages hebt waardoor je ook als meerdere characters kunt roleplayen waar bijvoorbeeld eentje onder de tatoeages zit waaronder in zijn gezicht terwijl je niet gelijk dan ook op je andere character onder de tatoeages zit. Bevordert weer de roleplay mogelijkheden!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Dit zou gefixed moeten zijn na volgende restart.
