### ISSUE TITLE
MMT rang toevoegen aan de ambulance dienst .

### ISSUE THREAD

**Issue by krizz696** [Tedeapolis/development#202]
MMT rang toevoegen aan de ambulance dienst .

wil zeggen : 
offroad snelle eenheid en snelle eenheid uit de verpleger , dokter en piloot rang halen en voor die rangen een optie als MMT . 
Momenteel profiteren werknemers te veel van de snelle eenheden en zo kan er toegang gegeven worden mits examens en verantwoord gedrag tot de MMT . creeerd meer rp en doorgroei binnen het ambuteam . mensen kunnen dan ook bij misbruik de rol MMT afgenomen worden .

**Comment by niekschoemaker** [comment]
Bedoel je dat er 3 rangen komen: MMT arts, MMT piloot of gewoon 1 extra rang namelijk MMT?

**Comment by niekschoemaker** [comment]
Ik heb nu 1 rang toegevoegd namelijk MMT die boven piloot en onder baas staat. En heb de voertuigen ook weggehaald

**Comment by krizz696** [comment]
ja ik bedoelde een duplicate van de drie rangen . die gelijke lonen hebben . zodat je voor elke rang een optie met en zonder hebt .
