### ISSUE TITLE
[EUP]: de kleding voor de KNRM 

### ISSUE THREAD

**Issue by JeroenKla** [Tedeapolis/development#2020]
### Contact Details

AvocBe#0125

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Dit zijn de kleding bestanden van het project van de KNRM. Deze zijn allemaal aangepast en klaargezet. dit zijn  juist de bestanden die gebruikt worden + normaal staat het eup al uitgesorteerd. 
https://we.tl/t-8WjaIrurT3

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Hey @JeroenKla 
De kleding is getest en gechecked, kunnen de server in. 
Ik wacht nog even tot alle andere afdelingen klaar zijn zodat alles in 1 geheel bij elkaar geplaaatst kan worden en in een keer er in zit.

**Comment by JeroenKla** [comment]
Nog een puntje vergeten een duikoufit voor het redden van personen te water

- [ ] Duik outfit KNRM

**Comment by DevvTDA** [comment]
@JeroenKla  even gekeken maar we kunnen het beste de duik outfit pakken van beging in een andere kleur, daarvan weten we zeker dat die werkt :)

**Comment by DevvTDA** [comment]
Notitie voor mezelf:
**_scuba outfit mannen_**
Torso 1: 243
Torso 2: 6
Broek 1: 94
Broek 2: 6
Schoenen 1: 67
Schoenen 2: 6
Bril 1: 26
Bril 2: 6

**_Scuba outfit vrouwen_**
Torso 1: 251
Torso 2: 6
Broek 1: 97
Broek 2: 6
Schoenen 1 : 70
Schoenen 2: 6
Bril 1 : 28
Bril 2 : 6

**Comment by DevvTDA** [comment]
gecommit
