### ISSUE TITLE
[FEATURE]: Logo rechtsonderin 14K

### ISSUE THREAD

**Issue by PisaMartinez** [Tedeapolis/development#2021]
### Contact Details

zaka#4407

### Beschrijf zo duidelijk mogelijk de feature

Ik had vernomen dat je het rondje niet kon aanpassen, dus dan graag gewoon deze logo met het blauwe rondje erom heen! 

![d96vma8-e0c71229-f454-43c3-881a-c149707294b7](https://user-images.githubusercontent.com/126700355/226106863-cfbfce0e-3e8a-4e4a-8b72-5c4b71400dd5.png)

### Wat lost deze feature op?

Logo is momenteel te klein, en niet heel zichtbaar.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Logo is aangepast naar het correcte logo.

Zit erin na de volgende herstart
