### ISSUE TITLE
[Bug]: Op en aftakelen werkt nog steeds niet 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2022]
### Contact Details

DeStefanoKiller#4442

### Wat gebeurde er?

Informatie staat in vorige GitHub : https://github.com/Tedeapolis/development/issues/2016

### Wat hoorde er te gebeuren?

-

### Wat veroorzaakt de bug?

-

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Relevante log bestanden

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Duplicate of #2016 heb die gereopened
