### ISSUE TITLE
[Bug]: vissen cancel bug 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2023]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Vissen stopt soms met random verzamelen, zie clip: https://medal.tv/games/gta-v/clips/109AJwgv3ysUT5/d1337oVfMdIZ?invite=cr-MSxaY0EsNDcwMjgyNDYs
https://medal.tv/games/gta-v/clips/109D8hW_VAWqtR/d1337P4nroH1?invite=cr-MSx2S1MsNDcwMjgyNDYs

### Wat hoorde er te gebeuren?

je hoort gewoon door te vissen

### Wat veroorzaakt de bug?

Geen idee 

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

[CitizenFX_log_2023-03-18T122736.log](https://github.com/Tedeapolis/development/files/11011113/CitizenFX_log_2023-03-18T122736.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Persoon is simpelweg uit de marker, is na volgende restart gefixed dat hij dan die melding niet meer weergeeft
