### ISSUE TITLE
[FEATURE]: DJ Cirkel Club Laporta

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2024]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

**Ik maak deze Github naar aanleiding van een Reddit suggestie**
https://www.reddit.com/r/tedeapolis/comments/11upl6b/dj_boot/

Club Laporta is recent overgenomen en gaat een aantal keer per week open, echter lopen hun wel vast op het probleem dat iedereen bij de DJ cirkel kan. Het gebeurd heel vaak dat random mensen allerlei soorten muziek aan gaan zetten via de cirkel.

Op hun verzoek vraag ik daarom of de DJ cirkel bij Club Laporta daarom ook gelinkt kan worden aan de volgende rangen:

entrepreneur 0
entrepreneur 10
entrepreneur 20
entrepreneur 30

Het idee is dat dan alleen mensen met de bovenstaande rangen gebruik kunnen maken van de DJ cirkel

### Wat lost deze feature op?

Dat mensen niet zomaar aan de DJ cirkel kunnen komen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Fixed
