### ISSUE TITLE
[Bug]: DJ Cirkel Exotica

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2025]
### Contact Details

Dyon#9999

### Wat gebeurde er?

Bij Club Exotica hebben wij een DJ Cirkel waar wij muziek aan toe kunnen voegen. Echter lopen wij de laatste tijd steeds vaker op het probleem dat wij sommige nummers niet meer kunnen afspelen/verwijderen

Nou is sowieso mijn vraag om onze lijst te laten resetten zodat de niet verwijderbare nummers verdwenen zijn.

Ook was ik benieuwd of er is gekeken kan worden naar wat de oorzaak is van de bug.

### Wat hoorde er te gebeuren?

Als je een nummer verwijderd hij ook echt verdwijnt, en niet terug komt.

### Wat veroorzaakt de bug?

Probeer 1 van deze nummers te verwijderen. Ze verdwijnen zodra je op verwijder klik. Maar als je dan opnieuw de lijst opent staan ze er weer in.
![image](https://user-images.githubusercontent.com/120292087/226500259-4ba0520c-3d14-4b6a-8f6d-60028969dbc1.png)

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Geen idee of je iets aan deze log bestanden hebt?

[CitizenFX_log_2023-03-21T013011.log](https://github.com/Tedeapolis/development/files/11024280/CitizenFX_log_2023-03-21T013011.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
is al opgelost.

**Comment by ExoticaTDA** [comment]
> is al opgelost.

Wat is die Niek toch ook snel
