### ISSUE TITLE
[FEATURE]: Brandweer

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#2026]
### Beschrijf zo duidelijk mogelijk de feature

- [ ] Porto nummer die aan de rang vastzit:
Main porto (Zuid, stad/haven); 150
Main porto (Noord, Paleto/Sandy); 151
Incident porto 1; 152
Indicent porto 2; 153
Incident porto 3; 154
KNRM Porto Main; 155
KRNM Incident porto 1; 156
KRNM Incident porto 2; 157 

- [ ] Meldkamer:
Meldkamer; 'brandweer'
Meldkamer KNRM; 'KNRM'

- [ ] Boss cirkel
1207.81, -1490.11, 42.47

- [ ] Garage spawn point
1215.52, -1483.16, 34.69

1e spawnplek:
1185.31, -1474.05, 43.69

2e spawnplek:
1193.43, -1474.02, 34.69

3e spawnplek:
1201.43, -1474.27, 34.69

4e spawnplek:
1209.36, -1474.28, 34.69

- [ ] In/uit dienst cirkel
1226.58, -1494.10, 34.69

- [ ] (persoonlijke) kleding cirkel
1231.44, -1493.95, 34.69

- [ ] Opslag
1208.59, -1486.44, 34.69

- [ ] Wapen/item store
1231.43, -1488.59, 34.69

- [ ] Item store voedsel
1219.84, -1474.22, 42.47

- [ ] Gym apparaten werkend maken

- [ ] Het volgende (Toestemming van geheel ambulance leiding):

- Toevoegen dat als er tot en met 4 ambulanciers in de stad zijn de Brandweer ook de ambulance meldkamer ontvangt. 
- Toevoegen dat brandweer kan reanimeren via F6 menu
- Toevoegen dat brandweer in de ambulance in-game porto's kan.
- KNRM zal neventaak worden vanuit zowel Brandweer als Ambulance (Dit zal zowel binnen brandweer als de ambulance dus extra rollen vereizen, pas voor later stadium)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by JeroenKla** [comment]
KNRM hoort toch niet tot brandweer ?

**Comment by jaim1114** [comment]
> KNRM hoort toch niet tot brandweer ?

Dienst Justitiële Inrichtingen behoort ook niet tot de Koninklijke Marechaussee, maar in TDA is het soms wat anders dan in de echte wereld. Niks mis mee lijkt mij :)

**Comment by JeroenKla** [comment]
Nee weet ik maar ik ben er. Mee bezig om dit onder de ambu te krijgen. zoals in een vorige post heb ik al kledij en voertuigen aangebracht hiervoor. Ook is er reeds een apv voor uitgeschreven dat dit deel uitmaakt van de ambu. Dit was ook met hoger af al besproken :)
