### ISSUE TITLE
[FEATURE]: Verplaatsen Garage Exotica

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2027]
### Contact Details

Dyon#9999

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag de groene & rode cirkel van Exotica verplaatst hebben. Dit omdat tijdens evenementen wij het terrein afzetten en deze cirkels altijd binnen de afzetting vallen. Dit zorgt er dus voor dat niemand zijn auto kan opbergen en er veel lag ontstaat in dit gebied.

Ik zou de cirkels graag verplaatst hebben naar de volgende locaties:

**GROENE CIRKEL:**
![image](https://user-images.githubusercontent.com/120292087/227807341-6b2c2586-bd00-414e-b0a0-a2a3f0e0cc1c.png)

**RODE CIRKEL:**
![image](https://user-images.githubusercontent.com/120292087/227807358-732f69e3-839f-427f-af59-3492208bb0db.png)

**SPAWN LOCATIES AUTO**
![image](https://user-images.githubusercontent.com/120292087/227821454-76c3e269-5272-4d95-86ca-d84602ef5208.png)

### Wat lost deze feature op?

De lag in dit gebied tijdens evenementen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by TedeaTaxi** [comment]
we moeten even praten ik heb beter idee
gr ali

**Comment by ExoticaTDA** [comment]
> we moeten even praten ik heb beter idee gr ali

Oh haha, dan sluit ik hem nog ff
