### ISSUE TITLE
[FEATURE]: Mogelijkheid Heli-Radars uitzetten voor (non overheidsdienst) Vlieginstructeur's | /Flightinstructor

### ISSUE THREAD

**Issue by Smokjertje12** [Tedeapolis/development#2030]
### Contact Details

smokertje12#2488

### Beschrijf zo duidelijk mogelijk de feature

Deze feature zou een /command toevoegen = /Flightinstructor

Hoe:
Na het invoeren van /Flightinstructor worden de heli radars onzichtbaar.
Dit zou de persoon zelf invoeren en hierna verdwijnen de heli radars voor hem of haar.

Waarom? 
Dit voorkomt dat een criminele vlieginstructeur de radar's zou gebruiken als oneerlijk voordeel in een crimineel scenario.

Waarom nu?
Dit idee kwam aan het licht vanwege nieuw aangenomen flight school leden waar er een aantal nog geen overheidsdienst van zijn en dit dus een mogelijks risico opent, wat wij graag willen vermijden aangezien deze feature belangrijk is voor vlieginstructeurs maar ook verkeerd gebruikt zou kunnen worden door een crimineel. Dit command zou er dus voor zorgen dat zij dit uit kunnen zetten en dit voorkomen.

### Wat lost deze feature op?

Dit voorkomt abuse vanuit een non overheidsdienst speler die dit voordeel zou kunnen gebruiken in een crimineel scenario.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @Smokjertje12,

Ik heb als command voor alle vlieginstructeurs toegewezen: `/disable_airspace_pings`

De feature zal in de server zitten na de herstart!
