### ISSUE TITLE
[EUP]: Karmellos Garage ( Al goedgekeurd door HR) 

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#2031]
### Contact Details

Devv#4532

### Waar bevind de issue zich?

Interiors

### Wat klopt er niet

In februari heeft Karmellos de aanvraag gedaan om een garage te krijgen bij het huis, dit is ook al goedgekeurd vanuit oesewoes en vanuit hoge raad. Nu hebben we tot heden helaas nog niets vernomen dat dit in werking was dus vandaar de github. 
Dit gaat om een ondergrondse garage die vanuit het gras te betreden is volgens oes is het een gta garage pakken en die kopieëren, ingang + tunnel maken en koppelen aan het huis. (anton zou hier aan beginnen maar heeft er geen tijd voor)

- Ook hebben wij op dit grasveld een helikopter cirkel deze zou wat meer naar achter geplaatst moeten worden. 

coords ongeveer: 
https://prnt.sc/X2oM4FhzhOeZ

Zo hebben wij minder risico bij het gang terrein om gezien te worden door pottenkijkers die weer op de berg aan het bespioneren zijn. en is het makkelijker voor meelopers om wapens uit hun garage te pakken die groter zijn en op de rug komen.

![image (1)](https://user-images.githubusercontent.com/79802852/227944328-6b58e405-0af9-4cd3-8650-bc3b1abb6f27.png)
![image (2)](https://user-images.githubusercontent.com/79802852/227944332-c79fcce1-8517-4787-bafc-a82a601ad430.png)
![image](https://user-images.githubusercontent.com/79802852/227944334-f5890468-e942-45aa-95ae-ae356b8249ac.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
https://media.discordapp.net/attachments/1083407021933609042/1100458067214225458/image.png?width=1250&height=676  e garage van de wijk past bijvoorbeeld ook een mule in, misschien kan je dat model ook gebruiken?

**Comment by Tom974** [comment]
Zit er in door Thijs, ik close deze issue.
