### ISSUE TITLE
[EUP]: Ambu RugTas

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2032]
### Contact Details

Wilma Wonka#4312

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

ambulance rugzak

Wat precies?
Een rugzak voor ambulanciers die ongeveer lijkt op onderstaande afbeelding. Deze zou je dan kunnen aandoen via de k spier.

Waarom?
We hebben nu wel een ambulance zak, maar die heeft niet meteen echt een nuttige functie. Ik wil een rugzak via het k menu omdat we zo echt meer kunnen dragen. Want ik merk dat ik soms niet genoeg spullen tegelijk kan dragen. Ook al heb ik max stamina en strength. En een rugzak via het k menu zorgt dat je echt meer kilo kan dragen. Ik denk dat dit er voor zal zorgen dat niemand meer te weinig EHBO-spullen, infusen, drank, eten of andere spullen te kort zal komen. Ook is deze rugzak gewoon een cool en mooi detail voor de ambulance outfit. 

Deze rugtas heeft de MMTO idd. Maar nu willen de mensen graag dat die rugtas ook beschikbaar komt voor alle rangen. Maar wel op de manier dat je meer kilo's kan krijgen erbij

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Ik zie het momenteel niet als een prioriteit dus ik gooi er low prio op, zal wanneer mogelijk dus naar gekeken worden.

**Comment by WilmaWonka1985** [comment]
Helemaal goed! Wel bedankt voor het bekijken er voor

**Comment by DevvTDA** [comment]
Toegevoegd, helaas geen extra kilo's. houd github commits in de gaten!
