### ISSUE TITLE
[FEATURE]: Spawn Locatie postcode 7069 garage 

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2033]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Mijn suggestie is om 6 parkeer plekken weg te halen waar voertuigen kunnen spawnen. Dit omdat als er iemand op de cardealer locatie staat, het regelmatig gebeurd dat er voertuigen op de geparkeerde voertuigen spawnen. Waardoor er telkens ANWB moet komen om die voertuigen weer te repareren..

Het voordeel is dat de cardealer die op dat moment de over de locatie beschikt (deze kunnen best prijzig zijn) niet telkens random voertuigen op de geparkeerde autos heeft staan.. Moet er telkens ANWB komen om deze voertuigen te repareren..

Wat zou een eventueel nadeel kunnen zijn? Omdat er (6) minder spawnlocaties kan het zijn dat de voertuigen boven op andere gaat spawnen..

Ik weet niet in hoeverre dit soort dingen mogelijk zijn, maar wat ik zou doen is de 6 parkeerplekken vrij houden. Dat hier geen voertuigen kunnen spawnen die uit de garages worden getrokken

### Wat lost deze feature op?

ik zet hier de clip neer.

[https://discord.com/channels/563825802865541122/1083136052258156544/1083136052258156544](url)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @WilmaWonka1985, 

De link die er nu staat is een link naar een discord channel welke ik niet kan zien, heb je toevallgi een ander linkje met de clip? :P

Bedankt!

**Comment by Tom974** [comment]
Hey @WilmaWonka1985, 

Ik heb met behulp van een ander stafflid toevallig kunnen achterhalen om welke spawnplekken het gaat

Deze aanpassing zit erin na de herstart van 02:00!

**Comment by WilmaWonka1985** [comment]
![image](https://user-images.githubusercontent.com/108530402/228317277-cab91854-a73f-4389-96ca-fcbf7d64446a.png)
om deze @Tom974
