### ISSUE TITLE
[FEATURE]: Tiewraps op deuren

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2036]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Een tijdje geleden is er tiewraps toegevoegd om op de deuren te zetten, alleen is er 1 nadeel eraan. Politie of KMAR kunnen hier niets tegen doen, wat bedoel ik hiermee? Nou ze kunnen de tiewraps niet los maken met iets, want ze moeten die open maken met een mes en de politie of KMAR heeft niet bepaald een mes. Dus mijn idee was om met een wapenstok of met je vuurwapen te slaan of dergelijke om de tiewrap los te maken. 

Toevoeging hierop net besproken in staff overleg:
- Graag een stanleymes of kniptang als item toevoegen voor de Politie / KMAR. Die toegangbaar is alleen voor hogere rangen bij de politie of kmar. Deze kunnen dan de tiewraps afknippen na ongeveer 15 a 20 minuten.

### Wat lost deze feature op?

Politie of KMAR kan de tiewrap  los maken wanneer dit van toepassing is. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by HarkoB** [comment]
Misschien een idee om dit bij de brandweer toe te voegen?

**Comment by Tom974** [comment]
Heb een kniptang toegevoegd voor KL/Kader
