### ISSUE TITLE
[FEATURE]: ID van spelers kunnen pakken

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2037]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Wij van de ambu kunnen nu geen namen meer zien als wij mensen moeten dood verklaren of iets. Wij gebruiken de namen om hun dood te verklaren.
Dat zetten wij dan netjes in looc en zetten we naam datum en tijd bij. Nu is het verzoek of wij de ID's van de spelers kunnen pakken als we ze dood verklaren. Want dat maakt het voor ons een stuk realistisch 

### Wat lost deze feature op?

Wij zien geen namen meer van spelers tijdens het dood verklaren of bij de harmonitor

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
@Tom974 ^^

**Comment by Tom974** [comment]
Hey @CalRayy & @WilmaWonka1985,

Is hier goedkeuring vanuit staff voor of wie heeft hier goedkeuring voor gegeven?

**Comment by WilmaWonka1985** [comment]
@Tom974 ik ben van het ziekenhuis. Ik ben een Teamleider. En @CalRayy gaf mij de tip om hier een github voor te maken

**Comment by CalRayy** [comment]
Ik zal het meenemen naar staff overleg

**Comment by CalRayy** [comment]
@Tom974 goedgekeurd

**Comment by WilmaWonka1985** [comment]
@Tom974 super bedankt!
