### ISSUE TITLE
[FEATURE]: Taakstraf eten toevoegen

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2040]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Net zoals bij de gevangenis kan je bij een cirkel eten kopen. Misschien is het ook handig om een cirkel te plaatsen bij de Taakstraf in de Gevangenis. Want het is handig want als je niet eet ga je dood. 
Voordelen suggestie: Stel voor je hebt geen eten op zak en je kan het niet kopen is dat veel gezeik ook want dan word je ook naar de Begraafplaats gestuurd met taken wat helemaal niet kan.. Dus dit zal zeker een handige toevoeging zijn naar mijn mening!
Eventuele nadelen: Nee denk het niet?
Hoe zie jij dit voor je in de stad? Wat zal deze aanpassing verbeteren? Ik zie dit in de stad als een handige Toevoeging. Mensen moet eten anders gaan ze dood, is niet handig als ze dood gaan tijdens een Taakstraf.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @WilmaWonka1985,

Zal toegevoegd zijn na de herstart!
