### ISSUE TITLE
[FEATURE]: Banden kopen bij de bouwmarkt

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2041]
### Contact Details

Wilma Wonka#4312

### Beschrijf zo duidelijk mogelijk de feature

Dat je banden kan kopen in de bouwmarkt (zelfde plek waar je Reparatiekit kan kopen.). Tot op heden kan je ze enkel krijgen van een ANWBer terwijl het eigenlijk wel handig is. 

**EDIT: Maximaal 1 per voertuig in de kofferbak. (bij anwb voertuigen mag dit wel nog unlimited zijn)**

Voordelen suggestie:
Meer Rp
Gewoon handig

Eventuele nadelen
/ 

Hoe zie jij dit voor je in de stad? Wat zal deze aanpassing verbeteren?
Meer RP mogelijkheden + leuke toevoeging.

Chang had gezegt dat dit mogelijk was namelijk :)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DeStefanoKiller** [comment]
Ik ben het niet echt mee eens dat banden een item wordt die door iedereen gekocht kan worden. Er staat wel bij voor meer RP maar ik denk eerder dat de RP achteruit gaat in plaats van verbetering.  

En hoe zien jullie de voorraad voor je? Iedereen die standaard 10 banden in de auto heeft? En het gewicht dat erbij komt kijken? Auto's met een reserve band erin of eronder gaan nou eenmaal minder snel door het gewicht, om nog niet te beginnen over het gewicht van de krik. Dus ik zie deze toevoeging niet echt als verbetering voor roleplay.

**Comment by WilmaWonka1985** [comment]
@DeStefanoKiller ik zal dit antwoord morgen even in de suggestie zetten en kijken wat zei dr van zeggen oke, Dan kom ik hier op terug bij je. Bedankt voor je antwoord

**Comment by ARJ3N** [comment]
Goedkeuring vanuit staff indien er een limiet op gezet kan worden van één band maximaal tegelijkertijd in een kofferbak. De ANWB voertuigen hebben daar dan een vrijstelling van. @Tom974

**Comment by Tom974** [comment]
> Goedkeuring vanuit staff indien er een limiet op gezet kan worden van één band maximaal tegelijkertijd in een kofferbak. De ANWB voertuigen hebben daar dan een vrijstelling van. @Tom974

Check.

**Comment by DeStefanoKiller** [comment]
Is het ook al bekend wat de prijs gaat worden voor banden? Want dan kan ik namelijk de prijzenlijst van de ANWB erop aanpassen zodat wij ze ook kunnen gaan verkopen. @Tom974

**Comment by Tom974** [comment]
> Is het ook al bekend wat de prijs gaat worden voor banden? Want dan kan ik namelijk de prijzenlijst van de ANWB erop aanpassen zodat wij ze ook kunnen gaan verkopen. @Tom974

Geen idee, stuur maar wat jou een handige prijs lijkt, gebruiken we dat.

Dacht zelf aan de prijs die iets goedkoper is als een repareer setje.

**Comment by DeStefanoKiller** [comment]
Ik denk dat €2300 wel redelijk oké is voor een band in de huidige economie staat van TDA? 

@Tom974
