### ISSUE TITLE
[FEATURE]: Drugsmeldingen via de meldkamer binnen laten komen (KMAR)

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2042]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Drugsmeldingen niet alleen op de map en notificatie link onderin je scherm aangeven, maar ook via de meldkamer een melding binnen krijgen.
Zodat de OVD-K makkelijker mensen kan aansturen naar drugsmeldingen, soms kijk je niet naar de map of links onderin waar de notificatie komt. 
Waardoor je niet alle meldingen meekrijgt, sinds kort zag ik dat de Politie dit had gekregen en het leek mij ook super handig (en logisch) om dit te hebben voor de KMAR.

### Wat lost deze feature op?

- Je kan mensen aansturen via de portosysteem als OVD-K.
- Snellere aansturing i.p.v. status 6 aanvragen.
- Logischer en handiger.
- Overzichtelijker voor de KMAR.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @CalRayy,

Dit zal aangepast zijn na de herstart van 02:00!
