### ISSUE TITLE
[FEATURE]: /register als exta bij takenpakket van justitie toevoegen

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#2043]
### Contact Details

Ravvy#1934

### Beschrijf zo duidelijk mogelijk de feature

- [ ]  - /register als exta bij takenpakket van justitie toevoegen
Bij dit leek het ons een goed idee om /register bij spelers aan te maken wanneer er een x aantal leden van justitie online zijn. Daarbij kan justitie dan de naam, achternaam en geboortedatum voor de speler doorvoeren en aanpassen. 

### Wat lost deze feature op?

Wij vragen om dit toe te voegen om het takenpakket van justitie meer gevarieerd te maken, gezien wij momenteel afhankelijk zijn van Politie & KMAR meldingen.

De vraag van "hoe kan ik mijn naam veranderen" krijgen wij vaak te horen in het gemeentehuis.
Dit lijkt ons een leuk RP moment om dan aan te geven dat wij dat in orde kunnen maken voor de burger.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Solidhawk** [comment]
Doorgezet naar staff overleg

**Comment by Tom974** [comment]
> Doorgezet naar staff overleg

Hey @Solidhawk,

Is hier nog een terugkoppeling over?

**Comment by Solidhawk** [comment]
> > Doorgezet naar staff overleg
> 
> 
> 
> Hey @Solidhawk,
> 
> 
> 
> Is hier nog een terugkoppeling over?
> 
> 
> 
> 

Nog niet, kom ik op terug :)

**Comment by Tom974** [comment]
Is hier al een terugkoppeling over ondertussen? 

> > > Doorgezet naar staff overleg
> > 
> > 
> > Hey @Solidhawk,
> > Is hier nog een terugkoppeling over?
> 
> Nog niet, kom ik op terug :)

**Comment by Tom974** [comment]
Gesloten ivm geen reactie.
