### ISSUE TITLE
[FEATURE]: REDEMPTION - Official Gang

### ISSUE THREAD

**Issue by tdaroyo** [Tedeapolis/development#2044]
### Contact Details

Mathijs.#9818

### Beschrijf zo duidelijk mogelijk de feature

[](url)Redemption is vanaf heden een officiele gang geworden namens Crimineel Aanspreekpunt. Daar moeten nog een aantal dingen geregeld worden voor de ingame rang.

Redemption - مدير      - (Bazenmenu)
Redemption - مشرف   -  (F6, Tunen en inkopen)
Redemption - مراقب    -  (F6, Tunen)
Redemption - منسق    -  (F6, tunen en Inkopen)
Redemption - إدارة      -  ( F6 en tunen)          
Redemption - المستشارين - (F6)
Redemption - المجدول -  (F6)
Redemption - محللين     - (F6)
Redemption - منفذه    -  (F6)
Redemption - موظف    - (F6 - Dingen in en uit de opslag halen)
Redemption - متدرب    -  (F6  maar moet geaccepteerd worden om te fouilleren en voertuigopslag. Dingen in opslag maar er niet uit halen)
![Redemption_2 (1)](https://user-images.githubusercontent.com/128492778/229865197-cc00bcd3-d2cb-40b9-99ab-fe7f042a550f.png)

Logo hierboven moet als ingame logo ^
MLO: **OUD REVOLTES (KOEPEL)**

### Wat lost deze feature op?

Officiele gang geworden vanuit Crimineel Aanspreekpunt

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DaanDeW** [comment]
logo transparant
![redemptrans](https://user-images.githubusercontent.com/32983383/230445707-1f08342c-4934-466b-a07e-c39de3610c40.png)

**Comment by Tom974** [comment]
Hey @tdaroyo,

De rangen zitten in de main server.
