### ISSUE TITLE
[EUP]: HRB

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2045]
### Contact Details

Chrushers#8656

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Hallo,

Graag zouden wij een extra helm willen laten toevoegen aan de outfit van de HRB. Als model zouden we hetzelfde willen als onderstaande beschrijving. Als enige verandering zou de tekst: ''Dienst Speciale Interventies'' verwijderd moeten worden.

Helm1 = 2
Helm 2 = 1

In het eup menu graag toevoegen onder het kopje KMar - Hoog Risico Beveiliging.

Mochten er vragen zijn dan verneem ik dit graag.

In bijgevoegde printscreen
![HRB Helm 1](https://user-images.githubusercontent.com/112424697/230122164-f51500b2-24f5-42a4-836f-0a44f0250cef.png)
![HRB Helm 2](https://user-images.githubusercontent.com/112424697/230122167-25118986-1204-4939-9af6-6ffd67a00fad.png)
![HRB Helm 3](https://user-images.githubusercontent.com/112424697/230122169-96bf64b3-e2a3-4a55-802e-180618b9523e.png)
s zie je ook waar hij voor vervangen moet worden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Ik zal je helaas moeten teleurstellen dat degene die deze helmen gemaakt heeft de textures op een plaats gezet heeft die ik niet kan vinden, hierbij kan ik dus ook niets aanpassen of toevoegen omtrent de helm.
