### ISSUE TITLE
Multiple revives

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2046]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk om meerdere mensen tegelijkertijd te kunnen reviven, aangezien er soms massa vdm’s zijn of bij trainingen heel handig kan zijn om meerdere id’s te kunnen typen bij /revive id id id… 
Hopelijk is dit mogelijk en als dit mogelijk is kan dit ook voor de Tedeapolis bot stel je zit op je telefoon 😅.

### Wat lost deze feature op?

Je kan sneller te werk gaan als Staff bij massa VDM’s of bij trainingen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Je kunt gewoon pijltje omhoog doen, en dan het oude nummer ff weghalen en een nieuw nummer neerzetten.

Voor die paar keer dat het gebeurt ga ik dit niet toevoegen, omdat het hooguit een minuut aan tijd bespaart per week.
