### ISSUE TITLE
[FEATURE]: Shiftlogging nieuwe level 2 gangs in de discord.

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#2047]
### Contact Details

Daan de Wit#8441

### Beschrijf zo duidelijk mogelijk de feature

Redemption rol (is aangevraagd in een github)

mag de shiftlogging geadd worden in kanaal: 1093574755023589396

En van EAST SIDE BALLAS ( Rol = ESB )
Mag de shiftlogging geadd worden in kanaal: 1083714360167378954

Thanks!

### Wat lost deze feature op?

Shiftlogging gefixt

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @DaanDeW,

Deze zijn gefixt, ze komen a.s. maandag voor het eerst binnen, mocht dit niet zo zijn gelieve deze issue opnieuw te openen! 

Thanks!
