### ISSUE TITLE
[FEATURE]: Voertuig uitladen functie opslagloods

### ISSUE THREAD

**Issue by tdaroyo** [Tedeapolis/development#2048]
### Contact Details

Mathijs.#9818

### Beschrijf zo duidelijk mogelijk de feature

Ik hoor dat hierover een tijd geleden iets over is aangemaakt, maar verder valt het niet terug te zien waar en hoe.

Zoals je bij drugs loodsen hebt heb je een functie met kofferbak uitladen. Hierbij de vraag als dit ook kan gebeuren bij opslagloodsen om in 1x je kofferbak uit te laden via de cirkel.

### Wat lost deze feature op?

Sneller en makkelijker met het vervoeren met een opslagloods met voertuigen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Ik wil geen spelbreker zijn maar volgend mij is dit al een aantal keer afgewezen?

**Comment by CorruptSausage** [comment]
Hier is in #1747 al op gereageerd, deze feature gaat niet toegevoegd worden.
