### ISSUE TITLE
[FEATURE]: In/uitdienst optie voor TDA Nieuws + nieuwe rangen

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#2049]
### Beschrijf zo duidelijk mogelijk de feature

Een tijdje terug is er besproken dat TDA Nieuws (media) een in en uitdienst functie zal krijgen om moneyfarmen tegen te gaan. Hiervoor dus graag een cirkel op de volgende coordinaten en de bijbehorende uitdienst rangen die nog wel toegang hebben tot de sloten. 
![image](https://user-images.githubusercontent.com/93911282/230716729-4dbdccff-fa6d-4e30-a0e9-6c9f6ae7ab94.png)

Daarnaast ook de vraag om de rangen structuur en perms aan te passen zodat deze overeen komt met de onderstaande lijst. Salaris voor zowel de nieuwe rangen als uitdienst mag voor nu op 200 gezet worden.

1. Staigiair
2. Junior Journalist
3. Journalist
4. Senior Journalist
5. Onderzoeker
6. Junior Editor
7. Editor
8. Organisator
9. Ass. Redacteur
10. Redacteur | Bazen cirkel toegang
11. Hoofd Redacteur | Bazen cirkel toegang
12. Ass. Eindredacteur | Bazen cirkel toegang
13. Eindredacteur | Bazen cirkel toegang

- [ ] In/uitdienst cirkel
- [ ] Uitdienst rangen
- [ ] Aanpassen rangen structuur

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zit erin na de herstart.
