### ISSUE TITLE
[FEATURE]: /register toevoegen aan vliegveld

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#2051]
### Contact Details

Devv#4532

### Beschrijf zo duidelijk mogelijk de feature

Momenteel als nieuwe in de stad komen spawnen ze bij het vliegveld neer, als zij een character te snel doorklikken kunnen zij hier niet nogmaals /register doen hiervoor staat er dat ze dan naar het gemeentehuis moeten. 
Misschien toevoegen dat ze /register zowel bij het vliegveld als bij het gemeentehuis kunnen doen of enkel het vliegveld?

### Wat lost deze feature op?

nieuwe mensen hoeven hiervoor dan niet eerst naar het gemeentehuis als het fout gaat maar kunnen gelijkt het foutieve verbeteren voorkomt ook weer onnodige reports

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed
