### ISSUE TITLE
[FEATURE]: Aanpassingen Redemption 

### ISSUE THREAD

**Issue by tdaroyo** [Tedeapolis/development#2052]
### Contact Details

Mathijs.#9818

### Beschrijf zo duidelijk mogelijk de feature

De volgende dingen moeten nog veranderd worden / toegevoegd worden bij de MLO / rangen

- [x] Redemption - متدرب  (Laagste rang) moet vehicleopslag toegang krijgen
- [x] In het MLO moet de kledingcirkel nog toegevoegd worden
- [x] De aparte vehicleopslag cirkel moet verwijderd worden waar de gangheli wordt gepakt

### Wat lost deze feature op?

Vergeten erin te doen en zorgt voor verbetering van MLO / rangen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @tdaroyo,

De laatste aanpassing mbt de rang zit erin na de herstart!
