### ISSUE TITLE
[FEATURE]: Garage bij de gevangenis

### ISSUE THREAD

**Issue by Nick21458** [Tedeapolis/development#2053]
### Contact Details

NsGames07#2712

### Beschrijf zo duidelijk mogelijk de feature

Zou het misschien niet handig zijn als er bij de gevangenis? Omdat wanneer je uit de gevangenis komt dan moet je eerst een heel end lopen naar de garage omdat de eerste garage is bij sandy.

### Wat lost deze feature op?

Dat mensen die uit de gevangenis komen meteen een auto kunnen pakken en naar de stad kunnen gaan.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Zover ik zie is dit nog niet goedgekeurd, zodra dit wel het geval is even opnieuw reageren.
