### ISSUE TITLE
[FEATURE]: Nieuwe rangen Dierenkliniek

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#2054]
### Contact Details

Yohandessu#3314

### Beschrijf zo duidelijk mogelijk de feature

Hey Hoi! Wij vanuit Bark! Polis zouden graag wat aanpassingen/nieuwe rangen willen aangezien wij de rangen nu echt voor elke medewerker willen gaan gebruiken. In de huidige rangen zitten nog wat dingen waar we niet elke medewerker toe kunnen vertrouwen. Met dit nieuwe systeem willen we dus iedereen die bij ons komt werken ook daadwerkelijk een role geven.

Dierenkliniek - Stagiair
Dierenkliniek - Medewerker
Dierenkliniek - Manager
Dierenkliniek - Baas

Veranderen naar: 

Dierenkliniek - Puppy (geen f6)
Dierenkliniek - Daggoe (geen f6, wel toegang tot opslag)
Dierenkliniek - DierenArts (f6 + toegang tot opslag)
Dierenkliniek - Roedelleider (f6 + toegang om geld te storten in de pot & toegang tot opslag)
Dierenkliniek - Manager (f6 + toegang om geld te storten in de pot & toegang tot opslag)
Dierenkliniek - Eigenaar (alle rechten)

En dan graag ook de offduty variant ervan ;p 

### Wat lost deze feature op?

Zodat iedereen rangen kan krijgen bij ons! 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @JohanDewus,

Zit erin na de herstart!
