### ISSUE TITLE
[FEATURE]: command om wokstatus te checken

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2055]
### Beschrijf zo duidelijk mogelijk de feature

![image](https://user-images.githubusercontent.com/108530402/230790109-58ee8618-07f4-49a1-92ab-0fa6d053035a.png)

Zou dit nog wel mee genomen kunnen worden in staf overleg?

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ARJ3N** [comment]
Geen goedkeuring. Kan gewoon via RP bij de politie gecheckt worden. @Tom974

**Comment by Tom974** [comment]
Thanks @ARJ3N !
