### ISSUE TITLE
[FEATURE]: Thermiet die een cooldown op deuren zet

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2056]
### Contact Details

CalRay#1513

### Beschrijf zo duidelijk mogelijk de feature

Als je thermiet op een deur plaats en bij een gebouw inbreekt kan de eigenaar met de rang van het gebouw E drukken en is hij weer op slot. Als je in het echt een thermiet zal gebruiken kan je niet 1 2 3 terug op slot zetten, want dan is hij kapot. Wat mij handig leek is een cooldown zetten op sloten wanneer er recent een thermiet op geplaatst is. Zelf stel ik voor een timer van 5 minuten voor de deur niet direct te sluiten. 

### Wat lost deze feature op?

Realisme en RP

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
Hier staat al een timer op?

**Comment by CalRayy** [comment]
> Hier staat al een timer op?

Nope, gisteren een RP gedaan en ze konden het gelijk weer dicht doen dus gok dat de timer dan bugged is.

**Comment by ExoticaTDA** [comment]
> > Hier staat al een timer op?
> 
> Nope, gisteren een RP gedaan en ze konden het gelijk weer dicht doen dus gok dat de timer dan bugged is.

Nou bij Exotica word dagelijks de deur open gebrand en wij moeten elke keer een kwartier wachten voor we hem dicht kunnen doen.

**Comment by Tom974** [comment]
@CalRayy Weet je toevallig welke deur?

**Comment by Tom974** [comment]
Overal getest, ook in de gevangenis etc, bij mij komt er overal een cooldown op. 

Mocht je een clipje hiervan hebben, gelieve deze in de issue te zetten en deze te heropenen! 

Thanks!
