### ISSUE TITLE
[Bug]: Kustwacht helikopter

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2057]
### Contact Details

CalRay#1513

### Wat gebeurde er?

2 mensen besturen de helikopter en veranderen de grootte van de licht en je zit vast in de camera. zie screenshots: 
![image](https://user-images.githubusercontent.com/101106299/230802253-81371c8d-5d8f-41a6-b34d-a13a5e070e32.png)
![image](https://user-images.githubusercontent.com/101106299/230802257-81210155-b77a-4b8f-a3a3-0c2861f637d5.png)
![image](https://user-images.githubusercontent.com/101106299/230802262-53dd58d8-b614-441c-981e-cba74425fc1b.png)

### Wat hoorde er te gebeuren?

Je hoort gewoon de camera te gebruiken en eruit te gaan. 

### Wat veroorzaakt de bug?

Twee mensen die de spotlight / flashlight veranderd. 
[kustwachtbug.txt](https://github.com/Tedeapolis/development/files/11186604/kustwachtbug.txt)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

[kustwachtbug.txt](https://github.com/Tedeapolis/development/files/11186605/kustwachtbug.txt)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @CalRayy 

Deze bug is onderhand gefixt door Misstake, je kunt nu niet meer tegelijkertijd de spotlight gebruiken. 

Bedankt voor het melden!
