### ISSUE TITLE
[FEATURE]: Aanpassingen wapens wapendealer

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#2058]
### Contact Details

Cazorla#8107

### Beschrijf zo duidelijk mogelijk de feature

Voor de wapendealer moeten een aantal wapens nog aangepast worden, dit gaat om het volgende:

- [x] WEAPON_REVOLVER -> damage mag iets minder, deze is one shot op benen van grote afstand. 
- [x] WEAPON_SNSPISTOL -> deze mag een /th animatie krijgen.
- [x] WEAPON_MACHINEPISTOL -> recoil mag gelijkgetrokken worden aan Skorpion V2 (WEAPON_MINISMG), maar dan een tikkeltje beter. Deze mag ook een /th animatie krijgen. 

### Wat lost deze feature op?

Voor de wapendealer, roleplays en toekomstige level 5's.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey Larry,

Zal doorgevoerd zijn na de herstart van 02:00!
