### ISSUE TITLE
[FEATURE]: Wapendealer rangensysteem

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#2060]
### Contact Details

Cazorla#8107

### Beschrijf zo duidelijk mogelijk de feature

De wapendealer is sinds een aantal maanden een onderwerp in de stad. Sinds heden heeft de wapendealer een MLO waar de wapendealer veel RP aan wilt verbinden met officiële groepen. Daar moeten een aantal dingen geregeld voor worden om zo de RP te bevorderen. 

Rangen:

Wapendealer - Master Chief (Bazenmenu)
Wapendealer - Elites (F6 en tunen)
Wapendealer - Arbiter (F6 - Dingen in en uit de opslag halen)
Wapendealer - Rookie (F6-menu en voertuigopslag. Dingen in opslag maar er niet uit halen)

Er moet een voertuig opslag zijn (auto's pakken en wegzetten)
Er hoeft geen kledingcirkel te zijn, want er wordt geroleplayed met PEDS.
Er moet een opslagcirkel zijn en een item winkel (clips kopen etc). 
Er moet een bazenpot zijn waar witgeld in opgeslagen kan worden (m.b.t salaris, veilingen en inval politie)

Salarissen:
Master Chief: 1 per 10 minuten als men indienst aan het roleplayen is.
Elites: 1 per 10 minuten als men indienst aan het roleplayen is.
Soldier: 1 per 10 minuten als men indienst aan het roleplayen is.
Rookie: 1 per 10 minuten als men indienst aan het roleplayen is.

De volgende wapens moeten in de wapeninkoop (opslagcirkel) staan:
(DIT STAAT IN TOM ZIJN DM)

Dit is een second job, dus er moet een in/uit dienst feature zijn met een groene cirkel.

Geld van de lonen gaat uit hun eigen pot

### Wat lost deze feature op?

Roleplay bevorderend voor de groepen die in aanraking zijn gekomen met wapendealer en in de toekomst level 5 gangs.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ARJ3N** [comment]
Heeft toestemming! @Ljosfari @Tom974
