### ISSUE TITLE
[FEATURE]: Koninklijke Nederlandse Redding Maatschappij - Voertuigen

### ISSUE THREAD

**Issue by JeroenKla** [Tedeapolis/development#2061]
### Contact Details

AvocBe#0125

### Beschrijf zo duidelijk mogelijk de feature

Binnen  de KNRM zouden we ook gebruik maken van nieuwe voertuigen. 

Deze zijn voor een groot deel zelf al aangepast geweest maar zouden dus echter wel nog naar TDA standaarden gezet moeten worden.
 De rangen die toegang hebben tot welk voertuigen zijn in een vorige issue terug te vinden.
 Zie "Koninklijke Nederlandse Reddings Maatschapij Rangen + meldkamer".

We beginnen met de water voertuigen hier heb ik 3 boten die ik zou aanbrengen. 

- [ ] Grote Reddingsboot
- [x] Kleine Reddingsboot (hier heeft Lorenzo het model van) 
- [x] Jetski

Als volgt heb ik de landvoertuigen dit zijn zowel transport als logistieke voertuigen die kunnen gebruikt worden. 

- [ ] Unimog
- [x] Amarok
- [x] Ford Raptor

En als laatste de Helikopter 

- [ ] Helikopter

bestanden zijn terug te vinden 
https://we.tl/t-xEkgrmKNpL

![unimog](https://user-images.githubusercontent.com/85429857/231055858-c384b7af-cf94-4672-b548-90a62efc45d1.PNG)
![Materiaal_wagen__OVD_Wagen_2 1](https://user-images.githubusercontent.com/85429857/231055869-39a4a906-a6e9-43e8-8c95-842eecfd5ef5.png)
![Raptor](https://user-images.githubusercontent.com/85429857/231056343-8fcdbe3a-a009-4f28-bbd3-64701f21777
![Voertuigen 2](https://user-images.githubusercontent.com/85429857/231056364-797900f5-c436-484c-8200-7f9c6bcd4470.PNG)
6.png)
![Boten](https://user-images.githubusercontent.com/85429857/231056360-7a7b039a-7c08-48be-8e21-3c628c18037b.PNG)

![alle voertuigen](https://user-images.githubusercontent.com/85429857/231056793-d9bc7330-158b-492a-8f8f-401d49aa2282.PNG)
![heli](https://user-images.githubusercontent.com/85429857/231056798-ee377e93-525f-4649-a754-5566226f86ac.PNG)
![boot knrm](https://user-images.githubusercontent.com/85429857/231057076-e5ffe0f7-1c20-4358-9b48-6bcc7aa7cd88.PNG)

### Wat lost deze feature op?

Deze feature is vooral het toevoegen en bekendmaken van KNRM. Zo heeft ook deze tak zijn eigen voertuigen die zorgen voor publiciteit en vertoning. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
@Lorenzo3001 kan jij dit bekijken 👀?

**Comment by Ljosfari** [comment]
is hier al toestemming voor dan ?

**Comment by JeroenKla** [comment]
@Ljosfari ja zoals te zien is in ticket 221290 heb ik voor alles een toestemming voor gekregen. Dit was in het verleden al goedgekeurd en is nu nogmaals goed gekeurd. Ik heb de vorige 2 GitHubs ook terug opengezet.

**Comment by Tom974** [comment]
@Lorenzo3001 was dit al af of?

**Comment by Lorenzo3001** [comment]
> @Lorenzo3001 was dit al af of?

![IMG_0078](https://github.com/Tedeapolis/development/assets/93911282/369052af-f825-4021-8ca5-37bef667b562)

**Comment by Tom974** [comment]
> > @Lorenzo3001 was dit al af of?
> 
> ![IMG_0078](https://user-images.githubusercontent.com/93911282/268591826-369052af-f825-4021-8ca5-37bef667b562.jpeg)

https://tenor.com/view/gfy-go-fuck-yourself-gif-12366013

**Comment by JeroenKla** [comment]
@Lorenzo3001 toevallig zicht waneer hier verder aan kan gewerkt worden ? :)

**Comment by Lorenzo3001** [comment]
Voor nu blijft het bij de voertuigen die er momenteel in zitten.
