### ISSUE TITLE
[FEATURE]: Dierenwinkel 2.0

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#2062]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

- [ ]  Dierenvoer item
Een eetbaar item voor dieren en mensen de we kunnen verkopen

- [x] Telefoonnummer met een eigen meldkamer : 0900-0245

- [x] Spawn cirkel voor voertuigen, die aan de rank vastzit. Voor de toekomstige dieren ambulance

- [x]  Logo van Bark! Polis op de map

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ExoticaTDA** [comment]
![Bark!Polis Logo Final](https://user-images.githubusercontent.com/120292087/231860369-a2263ffb-eb12-416d-b5de-2a46ed2f505a.png)


Hierbij het logo voor op de kaart

**Comment by Tom974** [comment]
Vind het laatste puntje momenteel niet echt van belang.

**Comment by Dyon033** [comment]
> Vind het laatste puntje momenteel niet echt van belang.

Je hebt het icoontje wel weg gehaald 😢
