### ISSUE TITLE
[FEATURE]: extra peds

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#2063]
### Contact Details

Ljosfari#3575

### Beschrijf zo duidelijk mogelijk de feature

https://www.gta5-mods.com/player/greyhound-dog-replace

https://pl.gta5-mods.com/player/pit-bull-replace

https://www.gta5-mods.com/misc/add-on-quadrupeds-animals

### Wat lost deze feature op?

Op aanvraag van spelers voor rp scenario's en de dierenwinkel

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Peds zijn van nogal slechte kwaliteit / alleen replacements van gta helaas.

Ik ga deze dus sluiten
