### ISSUE TITLE
[Bug]: zwart wit scherm voor altijd, na een revive / reanimatie

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2064]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Ik had hier eerder last van een tijdje terug, maar ik kreeg het niet voor elkaar om deze bug te krijgen voor het te melden. Vorige keer dat ik dit had gemeld had ik helaas geen clip. Deze keer wel gelukkig. https://www.youtube.com/watch?v=d1gOlOeHbsw

### Wat hoorde er te gebeuren?

je hoort niet voor altijd zwart wit te zien, zie screenshots en clips:  https://www.youtube.com/watch?v=d1gOlOeHbsw
![image](https://user-images.githubusercontent.com/101106299/231614695-3bd7dae7-25c5-4074-b8d6-641dd57c4fa2.png)

### Wat veroorzaakt de bug?

na een revive of reanimatie

### Frequentie van de bug

Sporadisch/Heel soms

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

[zwartwitCitizenFX_log_2023-04-12T235951.log](https://github.com/Tedeapolis/development/files/11217067/zwartwitCitizenFX_log_2023-04-12T235951.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ik kan niet vinden wat dit veroorzaakt, heb wel een timeout toegevoegd aan het respawnen, maar weet niet of dit het perse fixed of niet.
