### ISSUE TITLE
[FEATURE]: Nieuwe benaming DSI (AOT en BSB) rollen ingame

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#2065]
### Contact Details

KeesdB#1477

### Beschrijf zo duidelijk mogelijk de feature

Onlangs hebben we een overleg gehad waarbij de rangenstructuur binnen de DSI is veranderd en op basis daarvan willen we ook graag dat ingame de rang namen veranderd worden, lonen en dergelijke hoeven niet veranderd. Het gaat alleen om de benaming.
Het gaat om de volgende rangen:

12, 13, 14 en 15 van de Politie
80, 81, 82 en 83 van de KMAR

12, 80 = DSI Soldaten (De benaming is nu Korporaals)
13, 81 = DSI Korporaals (De benaming is nu Onderofficieren)
14, 82 = DSI Onderofficieren (De benaming is nu Officieren)
15, 83 = DSI Officieren (De benaming is nu Majoor)

Als er vragen zijn hoor ik het graag.
DSI Leiding

### Wat lost deze feature op?

Andere namen binnen de rangenstructuur.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @KeesdeB,

Zit erin na de herstart!
