### ISSUE TITLE
[Bug]: Parachute die soms niet opent

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2067]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Animatie gebeurt wel maar er opent niks, zie video (let op earrape aan einde): 
https://youtu.be/PvLBfJOCAOw

### Wat hoorde er te gebeuren?

Parachute hoort open te klappen.

### Wat veroorzaakt de bug?

Sommigen vermoeden dat het met in de porto te praten te maken heeft, maar dat is niet zeker.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @ARJ3N,

Mogelijk is het gefixt na de herstart, gelieve terug te koppelen of het gefixt is!

Thanks!

**Comment by ARJ3N** [comment]
Helaas is het alleen maar erger geworden helaas:
https://streamable.com/21t2s6
@Tom974

**Comment by Tom974** [comment]
> Helaas is het alleen maar erger geworden helaas: https://streamable.com/21t2s6 @Tom974

Zou nu wel gefixt moeten zijn :)

**Comment by ARJ3N** [comment]
Nieuwe fix werkt inderdaad, tot nu toe geen problemen mee ondervonden. @Tom974
