### ISSUE TITLE
[FEATURE]: Command /frequency weghalen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2069]
### Contact Details

Arjen#0001

### Goedgekeurd door

Staff

### Beschrijf zo duidelijk mogelijk de feature

Command /frequency weghalen.

### Wat lost deze feature op?

Command is gevoelig voor misbruik aangezien je zonder een porto te pakken snel kunt wisselen van frequentie. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @ARJ3N,

Het command zal niet meer bruikbaar zijn na de herstart van 02:00
