### ISSUE TITLE
[FEATURE]: Brandweer rangen

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#2071]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Hoofdcommandeur (100 / boss)
Toegang tot boss menu
Toegang tot alle voertuigen
Toegang tot alle wapens
Toegang tot alle items

Adjunct-Hoofdcommandeur (70)
Toegang tot alle voertuigen
Toegang tot alle wapens
Toegang tot alle items

Commandeur (60)
Toegang tot alle voertuigen
Toegang tot alle wapens
Toegang tot alle items

Hoofdbrandmeester (50)
Toegang tot voertuigen xx & xx
Toegang tot alle wapens
Toegang tot alle items

Brandmeester (40)
Toegang tot voertuigen xx & xx
Toegang tot wapens xx & xx
Toegang tot items xx & xx

Hoofdbrandwacht (30)
Toegang tot voertuigen xx & xx
Toegang tot wapens xx & xx
Toegang tot items xx & xx
Toegang tot normale brandweer EUP

Brandwacht (20)
Toegang tot voertuig TS
Toegang tot wapens xx & xx
Toegang tot items xx & xx
Toegang tot normale brandweer EUP

Aspirant (10)
Toegang tot geen voertuigen
Toegang tot wapens xx & xx
Toegang tot items xx & xx
Toegang tot i.o. brandweer EUP

Stagiaire (0)
Toegang tot geen voertuigen
Toegang tot geen wapens
Toegang tot geen items
Toegang tot i.o. brandweer EUP

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AaranDejager** [comment]
Brandweer 86 - KNRM - Medisch Hoofd Officier / Toegang tot Vito
Brandweer 85 - KNRM - Medisch Officier / Toegang tot NH90 (heli)
Brandweer 84 - KNRM - Nautische Arts / Toegang tot Unimog
Brandweer 83 - KNRM - Nautische Verpleegkundige / Toegang tot Jetski, Dinghy, Grote reddingsboot
Brandweer 82 - KNRM - Lifeguard / Toegang tot Ford Raptor + Aanhangwagen
Brandweer 81 - KNRM - Lifeguard in Opleiding

**Comment by Tom974** [comment]
Is er ook een logotje hiervoor @AaranDejager @Ljosfari 😅 ?

**Comment by AaranDejager** [comment]
@Tom974 Ik zal hem in je DM sturen!

**Comment by Tom974** [comment]
Jobs zijn toegevoegd
