### ISSUE TITLE
[EUP]: Brandweer eup

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#2072]
### Contact Details

Ljosfari#3575

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

- Outfit voor basis (Zonder jas) - https://www.fivemstore.nl/product/eup-v3
- Outfit voor reguliere Brandweer
- Outfit voor Bevelhebber
- Outfit voor OVD
- Outfit AGS ( Adviseur Gevaarlijke Stoffen) (groene flap)
![image](https://user-images.githubusercontent.com/97713942/233188633-2a2b9673-a32a-4905-8720-83999d1c88b4.png)
![image](https://user-images.githubusercontent.com/97713942/233188673-a60e2323-ab45-470b-a97c-07f969da2838.png)
![image](https://user-images.githubusercontent.com/97713942/233188698-6e805950-96e5-4092-8bdc-ddf9e6db718d.png)

Masker op
![image](https://user-images.githubusercontent.com/97713942/233188753-0ef9d8e7-e86d-466a-a403-26bc8403141d.png)

Masker af
![image](https://user-images.githubusercontent.com/97713942/233188801-22307b47-07c6-4bae-ae92-d9916a0eced0.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AaranDejager** [comment]
Toevoeging: Brandweer outfit als sportkleding. (Simpelweg een donkerblauw / zwart t-shirt met brandweer + logo er op in het wit. + een kort sport broekje met gympen.

**Comment by DevvTDA** [comment]
Staat er in na de restart

**Comment by Gullianobrandweer** [comment]
de web is offline voeg me discord afrgulliano
