### ISSUE TITLE
- Verandering permissies ESB- 

### ISSUE THREAD

**Issue by musician1011** [Tedeapolis/development#2073]
### Contact Details

Musician1011#1260

### Goedgekeurd door

Tom974

### Beschrijf zo duidelijk mogelijk de feature

- Shotcaller (Balla Boss)
- Young Shotcaller (Righthand Balla Boss)

Deze bovenstaande Rollen zouden ook in het boss menu moeten kunnen, het zelfde als ik eig kan als leiding, dus geld ook uithalen.

Onderstaande rollen zouden in de garage moeten kunnen auto's inzetten en uithalen & toegang krijgen tot F6 

- Shotcaller (Balla Boss)
- Street General 
- Street BiG Gangster
- Street Soldier
- Street Gangster
- Young Street Gangster
- Runner
- Recruit

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @musician1011, 

Zal doorgevoerd zijn na de herstart!
