### ISSUE TITLE
[FEATURE]: DJI / BOT Rangen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2076]
### Contact Details

CalRay#1513

### Goedgekeurd door

Tom & HR / HS

### Beschrijf zo duidelijk mogelijk de feature

kmar 59 - DJI - Algemeen Directeur / Loon 1500-750 -
kmar 58 - DJI - Operationeel Directeur / Loon 1400-650
kmar 57 - DJI - Commandant / Loon 1300-625 
kmar 56 - DJI - Adjudant / Loon 1200-600
kmar 54 - DJI - Senior Beveiliger / Loon 1150-625
kmar 53 - DJI - Medior Beveiliger / Loon 1100-600 + Voertuigen S63 AMG, A6, Range rover en X5 (unmarked voertuigen, wat ze mogen inkopen vanaf deze rang)
kmar 52 - DJI - Junior Beveiliger / Loon 1050-525 
kmar 51 - DJI - Aspirant / Loon 1000-500 Wapenkluis: Wapenstok, Taser, Zaklamp, fire extinguisher, snijbrander, handboeien + Indienst geen flitsboetes Voertuigen: KMar Vito Rechten: Gevangenis alarm + Gevangenis alarm kunnen aan en uit zetten. + Vliegtuig radar + Sloten HB en Gevangenis in en uitdienst. Meldkamer DJI +HKP2000 +Alle munitie van elke wapen

Suggestie (als het niet mogelijk is dan helaas)
- Stel er zijn geen gevangenen, dat je een jobje als DJI kan starten dat je npc (gevangenen) kan transporteren richting cellen vanuit buitenplaats of medische kazerne en dat je hier kleine hoeveelheid geld kan verdienen net zoals het geld verdienen als gevangenen. Extra dat je cellen kan schoonmaken eventueel. 

----
EUP van alle rangen die hierboven staat beschreven acces geven net zoals HRB/BSB/DSI tot alle reguliere KMAR outfits.
Vanaf Medior Beveiliging mogen ze Acces hebben tot Bijzonder Ondersteuningsteam (kleding / eup).
Vanaf Medior beveiliging mogen ze de volgende wapens inkopen: SMG en HK416.
![image](https://user-images.githubusercontent.com/101106299/233799628-2b01b035-aa06-4f24-abec-d5b2ff92c53d.png)

### Wat lost deze feature op?

_Dit is voor de opzetting van de Dienst Justiele Inrichtingen binnen de KMar overheidsdienst._

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Alleen eup moet nog gedaan worden.

**Comment by Tom974** [comment]
Die extra suggestie moet even in een aparte issue @CalRayy, verder zit alles erin dus sluit ik deze issue.
