### ISSUE TITLE
[FEATURE]: Rang aanpassingen Karmellos

### ISSUE THREAD

**Issue by TDASammie** [Tedeapolis/development#2077]
### Contact Details

Sammie#8681

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag willen wij onze rangen binnen Karmellos aanpassen. Dit voor een betere structuur in de groep. Op dit moment wordt onze ‘Tío’ rang gebruikt voor de wapeninkopers. Wij willen hiervoor een aparte rang aanmaken genaamd ‘Comandante’, waardoor wij Tío weer kunnen gebruiken als een normale rang.

**• Aanpassing 1: Hernoemen van de huidige Tío rang naar Comandante:**
/setjob {id} bratva 800 | Karmellos - Tío  →  /setjob {id} bratva 800 | Karmellos - Comandante
Gaat dus slechts om een rename van de rang met behoud van dezelfde permissies.

**• Aanpassing 2: Opnieuw toevoegen van Tío, maar dan op job level 850:**
/setjob {id} bratva 850 | Karmellos - Tío
Graag Tío opnieuw toevoegen, maar dan op job level 850. Deze rang dient dezelfde permissies te krijgen als dat de rang Hermano nu heeft (job level 700). Enige toevoeging hierop is dat Tío ook toegang mag hebben tot de bazenheli, deze toegang heeft Hermano niet.

**• Aanvullend verzoek:**
Indien dit mogelijk tot de mogelijkheden behoort, willen wij graag de rangen Sobrino (job level 600), Hermano (job level 700) en Tío (job level 850) de permissie geven om alle soorten vuurwapens te kunnen tunen, maar niet inkopen.

Rangorde wordt dan als volgt:
/setjob {id} bratva 0 | Karmellos - Extraño
/setjob {id} bratva 100 | Karmellos - Conocido
/setjob {id} bratva 500 | Karmellos - Nieto
/setjob {id} bratva 600 | Karmellos - Sobrino
/setjob {id} bratva 700 | Karmellos - Hermano
/setjob {id} bratva 800 | Karmellos - Comandante
/setjob {id} bratva 850 | Karmellos - Tío
/setjob {id} bratva 900 | Karmellos - Padre
/setjob {id} bratva 1000 | Karmellos - Abuelo

### Wat lost deze feature op?

Betere structuur in de groep waaronder meer mogelijkheden voor het geven van promoties e.d.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @TDASammie,

Ik kan de job levels helaas niet aanpassen, omdat er nog mensen op deze rang staat en dit dan conflicten veroorzaakt.

Ik heb dus een andere grade toegewezen aan deze rang, deze is 750.

**Comment by TDASammie** [comment]
Hey @Tom974,

Bedankt voor het snelle oppakken :) 

Dus als ik hem samenvat:
-> Comandante is toegevoegd op job level 750 met de permissies die Tío eerst had (?)
-> Tío is blijven staan op job level 800 maar de permissies zijn gewijzigd naar die van Hermano + toegang tot de bazenheli (?)
-> Aanvullende verzoek is ook gelukt (?)

Klopt dit?

**Comment by Tom974** [comment]
> Hey @Tom974,
> 
> Bedankt voor het snelle oppakken :)
> 
> Dus als ik hem samenvat: -> Comandante is toegevoegd op job level 750 met de permissies die Tío eerst had (?) -> Tío is blijven staan op job level 800 maar de permissies zijn gewijzigd naar die van Hermano + toegang tot de bazenheli (?) -> Aanvullende verzoek is ook gelukt (?)
> 
> Klopt dit?

Yup, klopt
