### ISSUE TITLE
[EUP]: porto op de schouder van de ambu

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2078]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag zouden wij bij de ambu op zowel de mannen als de vrouwen op alle kleding een porto op de schouder willen. Nu praten we namelijk wel op de schouder maar we hebben er geen porto op zitten. 

![image](https://user-images.githubusercontent.com/108530402/234047144-ffe83c6f-0469-4134-9163-ba35d9005ac0.png)

is dit misschien mogelijk om het op de linker schouder te krijgen?

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Toegevoegd, github commits in de gaten houden wanneer het erin komt :)
