### ISSUE TITLE
[FEATURE]: Reznikov lift plaatsen

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#2079]
### Contact Details

EpicTom#5874

### Goedgekeurd door

Dit is destijds met het mlo goedgekeurd

### Beschrijf zo duidelijk mogelijk de feature

In het mlo van Reznikov hebben we een plaats voor een lift. Deze kan alleen naar 1 etage naar boven en terug naar de begane grond. Zie foto hieronder waar die geplaatst moet worden en eventuele coords. 
![image](https://user-images.githubusercontent.com/104857888/234048140-d38e3825-ec70-4abe-86af-b736d5275926.png)
![image](https://user-images.githubusercontent.com/104857888/234048222-aec886a8-5886-4af6-849e-02afcd5a19ad.png)
![image](https://user-images.githubusercontent.com/104857888/234048508-1dd63549-685e-4633-a97c-ab544f77a0fe.png)
![image](https://user-images.githubusercontent.com/104857888/234048550-02953011-763d-41cb-9c3f-9b421b3ff8c7.png)

### Wat lost deze feature op?

Dat wij de bovenverdieping meer kunnen gebruiken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Zit erin na de restart @EpicTomm

**Comment by EpicTomm** [comment]
Snelle service! Thanks
