### ISSUE TITLE
Politie krijg geen wapen meldingen

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#208]
Politie krijgt geen wapen meldingen.
Heb al 3 clips van ak's geschoten en geen 1 melding gegaan naar poltiie
Heb al 3x met shotgun geschoten en geen melding naar de politie
Heb regelmatig met tazer geschoten en geen melding voor politie komt binnen
Heb met pistol geschoten en geen melding komt binnen bij politie

Ik heb mij eigen ook op een andere job gezet.
Kwamen van geen enkel iets meldingen binnen van schoten.

**Comment by niekschoemaker** [comment]
Op welke server was dit?
En welke tijds periode zit hier tussen? Want de eerste melding heeft de hoogste kans, dan iets minder, etc, dus het eerste schot is het belangrijkste.
Als ik het goed was checked hij een periode van ongeveer 1 minuut. HIernaast hangt het ook af van welke locatie jeje bevindt en hoeveel mensen er dichtbij staan.

Bij blokkenpark en bp bank en politie bureau is de kans op meldingen extra hoog, etc etc @ExpensionX

**Comment by ExpensionX** [comment]
Dit was gewoon op onze server van TDA.
Dat was rond 11u smiddags. Er waren niet veel mensen in de buurd. Dat zou het misschien geweest kunnen zijn. Er waren maar 3 mensen in de buurd. Ik schoot met ak en denk 10 seconden erna met ander wapen. Maar ik merk dat we terug meldingen binnen krijgen. Dus ik weer in orden.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Niek Schoemaker <notifications@github.com>
Verzonden: Saturday, October 3, 2020 4:36:21 AM
Aan: Tedeapolis/development <development@noreply.github.com>
CC: ExpensionX <ruben1995moors@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Tedeapolis/development] Politie krijg geen wapen meldingen (#208)


Op welke server was dit?
En welke tijds periode zit hier tussen? Want de eerste melding heeft de hoogste kans, dan iets minder, etc, dus het eerste schot is het belangrijkste.
Als ik het goed was checked hij een periode van ongeveer 1 minuut. HIernaast hangt het ook af van welke locatie jeje bevindt en hoeveel mensen er dichtbij staan.

Bij blokkenpark en bp bank en politie bureau is de kans op meldingen extra hoog, etc etc @ExpensionX<https://github.com/ExpensionX>
