### ISSUE TITLE
[EUP]: BOT Kleren voor vrouwen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2081]
### Contact Details

CalRay#1513

### Goedgekeurd door

Mila / Devv

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Wij gaan binnenkort starten met DJI / BOT alleen is er geen vrouwelijke kleding voor de BOT. Mila gaf aan dat ik hiervoor een github moest maken dus bij deze :D !
Foto's van de mannelijke kleding versie van de BOT:
![image](https://user-images.githubusercontent.com/101106299/234351391-b0acabcb-2994-4ef1-8057-05d2c3841b41.png)
![image](https://user-images.githubusercontent.com/101106299/234351401-9fdb7ca6-e17c-4888-adcc-23c3a16e3a9c.png)
![image](https://user-images.githubusercontent.com/101106299/234351412-f1fea6eb-460d-46bc-953b-b4ef8a795662.png)
![image](https://user-images.githubusercontent.com/101106299/234351422-7eac468a-7723-4acf-8a3a-5f9b03fb0e7e.png)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Ik zag dat de HRB vrouwen kleding heeft, misschien nog een versie maar dan voor de BOT? Ik weet niet hoe makkelijk dat is? @DevvTDA

**Comment by DevvTDA** [comment]
![image](https://github.com/Tedeapolis/development/assets/79802852/c7c4437b-56b8-4209-963d-c32d777be8bd)
![image](https://github.com/Tedeapolis/development/assets/79802852/164b26a5-19c5-4332-8b53-6d043ae73aff)

**Comment by DevvTDA** [comment]
is gecommit :)
