### ISSUE TITLE
[BurgerRaad]: Toevoegen van /request_radio aan f6 menu Offi's en Politie/KMar

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2082]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

**Een optie in het F6 menu van officiële gangs & de politie/KMar.** 

Vaak word er super veel tijd gerekt door mensen met het goedkeuren de /request_radio. Daarom de vraag of dit toegevoegd kan worden aan het F6 menu zodat het niet meer goed gekeurd hoeft te worden en mensen ook super veel tijd kunnen gaan rekken.

**Dit is besproken in BurgerRaad**

### Wat lost deze feature op?

Dit zorgt er voor dat mensen niet meer overbodig veel tijd kunnen gaan rekken en mensen ook niet stiekem snel nog van porto kunnen veranderen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Goedgekeurd, alleen is er 5 seconden delay met een emote dat je porto ook in je hand houd zodat dit zichtbaar is.
