### ISSUE TITLE
[BurgerRaad]: Rechten dat Community Team & BurgerRaad GitHub linkjes kunnen plaatsten in chats.

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2084]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Nou maak ik binnen de Burgerraad veel Githubjes maar ben ik ook Community Team en behandel ik de suggesties in: ⁠suggesties
Elke keer als wij dan een github aanmaken voor iets is het fijn die mee te sturen zodat mensen het zelf ook in de gaten kunnen houden. Echter blokkeert de @Tedeapolis Bot dit op het moment.

Edit van Tom: Voeg hier ook even clipchamp.com aan toe

**Dit is besproken in BurgerRaad**

### Wat lost deze feature op?

Dat wij mensen makkelijk op de hoogte kunnen houden van de status op hun suggestie

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zou nu moeten werken
