### ISSUE TITLE
[BurgerRaad]: Geld in je auto kunnen stoppen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2085]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op het moment is het niet mogelijk om grote geld bedragen in je voertuig te stoppen. Op het moment kan je er misschien 100 euro in doen en dan houd het wel op

Graag hopen we dat die limiet er af kan, of een stuk hoger gezet kan worden (bijvoorbeeld €500.000,- of €1.000.000,-)
Dit is leuk om scenario's als geld smokkelen te kunnen doen. Maar ook tijdens criminelen deals kan het leuk zijn het geld in een kofferbak te hebben.

**Dit is besproken in de BurgerRaad**

### Wat lost deze feature op?

Extra mogelijkheden voor RP

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Goedgekeurd @Tom974
