### ISSUE TITLE
[BurgerRaad]: Toevoegen van Melee wapens aan de level 1 wapen inkoop

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2086]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Sinds dat de wapen inkoop op eiland weg is zijn er een aantal melee wapens niet meer beschikbaar. Dit zijn de volgende:

1. Hamer
2. Golfclub
3. Boksbeugel
4. Crowbar

Wij zagen graag dat deze toegevoegd worden aan de level 1 wapen inkoop. Op deze manier zijn deze wapens weer beschikbaar voor mensen.

### Wat lost deze feature op?

Dat deze wapens weer beschikbaar zijn om te kopen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
goedgekeurd
