### ISSUE TITLE
[FEATURE]: KNRM Mlo cirkels + opslag in overleg goedgekeurd met Nyx en HR en HS 

### ISSUE THREAD

**Issue by JeroenKla** [Tedeapolis/development#2088]
### Goedgekeurd door

HS en HR zie ticket 221290

### Beschrijf zo duidelijk mogelijk de feature

Graag hadden wij binnen de KNRM mlo nog bepaalde zaken van cirkels gezien.

- [x]  Opslag dienst voertuigen
- [x]  uitname dienst voertuigen
- [x] Opslag (zelfde ambulance)
- [x]  in & uit dienst kunnen gaan
- [x]  opslag en uitname boten
- [x]  opslag en uitname helikopter

wij vragen ook of er mogelijkheid is dat wij toegang krijgen tot volgende zaken:

- [x]  beton blok afzetting
- [x]  Hekje met pijl afzetting
- [ ]  Oranje lint met KNRM op
- [ ]  Oranje tent met KNRM op
- [x] Pionnen

Dit is in overleg met ambulance leiding aangevraagd. KNRM is in het verleden goedgekeurd door HR en HS zie ticket 221290

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Linten moet je maar even een aparte issue voor maken als deze gemaakt zijn.
