### ISSUE TITLE
[FEATURE]: Wetsvoorstel, vermoorden en beroven.

### ISSUE THREAD

**Issue by ProgyNL** [Tedeapolis/development#2089]
### Contact Details

ZQ Mert#9351

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

_Nieuwe regels omtrent mensen vermoorden en beroven zowel op land en eiland door individuelen, non en officiële groepen omdat er weinig duidelijkheid hierover is._

Aangezien er weinig regels zijn omtrent het ontvoeren, vermoorden en beroven van iemand op het wetboek.tedeapolis.nl website, vind ik wel (hoop ook meerdere) dat er eigenlijk gepaste regels moet komen zowel voor individuelen, non en officiële groepen.

**Nieuwe wetsvoorstellen zowel geldig voor land en eiland:**
Artikel 25 - RDM

1. 'Persoon van het leven beroven binnen x aantal uur/minuten. (Cooldown)' 
2. 'Persoon van het leven beroven via vrienden/groeperingen om cooldown te ontwijken.' - Zowel persoon en de gene die aangespoord is om iemand te vermoorden moeten beide bestraft worden.
3. 'Persoon vermoorden omdat hij een ongepaste gedrag vertoont volgens de moordenaar.' (Beoordeling stafflid)

_Persoon is vermoord, weet inprincipe niet wie hem/haar vermoord heeft (FailRP), maar omdat hij herkenbaar is aan zijn kleding/stem of in een bepaalde groepering zit word hij weer binnen de cooldown vermoord en om dat tegen te gaan de bovenste wetsvoorstel._

Artikel 27 - Overvallen & Oplichten
Met betrekking tot de volgende dingen/situaties is overvallen/oplichten niet toegestaan:

1. 'Persoon meerdere keren overvallen/bestelen/afnemen binnen een x aantal uur/minuten. (Cooldown)'
2. 'Persoon beroven via vrienden/groeperingen om cooldown te ontwijken.'

_Persoon is overvallen, weet niet wie het heeft gedaan (hoogstwaarschijnlijk droegen de overvallers maskers) even later word het weer overvallen door zelfde individu, non en officiële groep, wellicht kan dit wetsvoorstel alleen gelden voor individuelen ongeacht of die in een groep zit, maar dat de zelfde overvaller kan/mag niet de zelfde persoon weer overvallen binnen de cooldown_

**Voorbeeld:**
Jan verricht een illegale activiteit, word bestolen door individu, non en officiële groep => Cooldown van x aantal uur/minuten, individuelen, non en officiële groepen moeten het zelf bijhouden wie waar wat heeft gedaan wat betreft illegaliteit dit maakt het band/vertrouwen binnen de groep hoogstwaarschijnlijk beter om secuur te werk te gaan en NIET alles op het spel te zetten om iemand te beroven/vermoorden en daarna 'expres' refund-waardig ticket aanmaken om alsnog de buit en zijn eigen wapen terug te krijgen.

Zowel voor Jan en individuelen, non en officiële groepen moeten dan bestraft worden.

Jan mag niet opzettelijk uitlokken of zich voordoen dat hij een illegale activiteit verricht om de cooldown te ontvangen van de tegenpartij (Beoordeling stafflid + bewijs verplicht) => Straf Categorie 1

Individuelen, non en officiële groepen opzettelijk dan wel ontwetend (niet bijgehouden) zelfde persoon beroven/vermoorden, zo weten ze de non en officiële groepen ook wie vaak word vermoord en kunnen ze binnen de groep een oplossing voor vinden voor de combatspelers.  (Beoordeling stafflid + bewijs verplicht) => Straf Categorie 1

### Wat lost deze feature op?

1. Overzicht voor de staffleden, dat individuelen/non en officiële groepen of het niet alleen maar combat spelers zijn maar ook roleplay waardige spelers. 
2. Om buiten de stad om (in de discord kanalen of privé) ruzie te maken of op te zoeken ingame om die gene aan te spreken en daarna RDM/VDM gepleegd word onbewust dan wel bewust.
3. Nieuwelingen in de stad te beschermen omdat zij (hoogstwaarschijnlijk) niet weten dat ze meerdere keren niet vermoord mogen worden. (Mensen die opzoek zijn naar 'koters' om de 'koter' de fout in te laten gaan om vermoord te worden of de 'koter' opzettelijk iets laten verrichten zodat hij/zij vermoord word).
4. Voorkomen dat mensen niet meer willen spelen op TDA
5. Mensen in de stad verstandig laten omgaan met wapens en moeten zowel voor hun leven en criminele activiteiten(voorkomen dat ze opgerold worden) en wapens waarde aan hechten omdat de kosten en de levens veel meer waard zijn dan iemand vermoorden/beroven/bestelen/afnemen en iets kwijtraken.
 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @ProgyNL, 

Wetsvoorstellen kunnen gedaan worden via de wet-en-regelgeving github op https://github.com/Tedeapolis/wet-en-regelgeving

Gelieve dus daar je issue aan te maken mocht je hier de correcte toestemming voor hebben.

Bedankt!
