### ISSUE TITLE
[FEATURE]: DJI meldkamer voor kader rangen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2092]
### Contact Details

Johnny#8125

### Goedgekeurd door

KMar leiding

### Beschrijf zo duidelijk mogelijk de feature

Kader rangen (KMar leiding) moet toegang krijgen tot de meldkamer van de DJI, gezien het een neventaak is van de KMar.
De volgende rangen gaat het om:
kmar 90 
kmar 95 
kmar 100

### Wat lost deze feature op?

Toegang tot de meldkamer

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @KMarTDA,

Zal gefixed zijn wanneer dit te zien is in github-commits!
