### ISSUE TITLE
[EUP]: BOT outfit voor het kader.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2093]
### Contact Details

Johnny#8125

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Kader rangen (KMar leiding) moet toegang krijgen tot de complete outfit van het Bijzonder Ondersteuningsteam, gezien het een neventaak is van de KMar.

De volgende rangen gaat het om:
kmar 90
kmar 95
kmar 100

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @KMarTDA,

Zal gefixed zijn wanneer dit in github-commits te zien is!
