### ISSUE TITLE
[FEATURE]: Bank verplaatsen

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2094]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Ik stuur de clip er bij

Als je bij het bed dat we gebruiken voor psychologie wilt rechtstaan kom je altijd buiten de kamer terecht. Weet niet of het mogelijk is om die plek te verschuiven naar de andere kant van het bed of het bed 180 graden te draaien zodat we niet steeds gesprek moeten onderbreken om de patiënt binnen te laten.

https://medal.tv/games/gta-v/clips/16Xv50hcIlYEtm/d1337vEzmV5k?invite=cr-MSxOVXMsNzY4NjcwNzgs

### Wat lost deze feature op?

Heb het er boven bij gezet

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Niet fixbaar, dan ga je krijgen dat het bij andere locaties weer mis gaat. Gewoon even gebruik maken van emotes mocht het nodig zijn.
