### ISSUE TITLE
[FEATURE]: Aanpassing/Uitbreiding MLO CCF

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#2095]
### Contact Details

Schmutz#8587

### Goedgekeurd door

N.V.T. / al aangekaart bij Anton M. / Mila E.

### Beschrijf zo duidelijk mogelijk de feature

Aanpassingen huidige MLO:
- Garage deur verplaatsen naar links
- Pion uit hek achter
- Afvalbakken/containers op binnenplaats verwijderen
![image](https://user-images.githubusercontent.com/120605155/235375904-77611e8b-3f1b-4b44-8deb-02ee51de0638.png)

- Mogelijkheid over hek springen verwijderen, bv hek hoger of container weg
![image](https://user-images.githubusercontent.com/120605155/235375877-53273d9c-f6c3-433a-81fb-bd7e87e05c00.png)

- Garage uitbreiding martelkamer verplaatsen en dan de die ruimte bij de garage aantrekken vanwege ruimte gebrek en keren met mules etc....
![image](https://user-images.githubusercontent.com/120605155/235375942-b486fcba-d29d-4364-90cb-6425304893f1.png)

- rood cola bord midden op stoep naast ingang [weghalen](url)
![image](https://user-images.githubusercontent.com/120605155/235375863-acc51898-3287-4835-a327-c4cb6867338f.png)

- Martelkamer verplaatsen, opties Martelkamer, bespreken graag in een voicecall:
1) met de lift naar verdieping -1 uitkomen midden van de vaten in de martelkamer, eventueel de trap te verlengen naar beneden, dit is dus een kelder optie en we weten van jullie dat dit lastig is.
2) 2e verdieping WC en slaapkamer weg te halen en daar zonder ramen de martel kamer neer te zetten, misschien een makkelijkere optie
![image](https://user-images.githubusercontent.com/120605155/235375970-5fdfa399-45cd-42b2-8656-35217cea237b.png)

Uitbreiding Nieuwe MLO: Hotel Colombo

Wij als de familie Colombo halen veel plezier uit de RP van het Cafe en het bewaken van ons district. om het Mafia verhaal af te maken en ons ook wat ruimte te gunnen lijkt het ons echt super gaaf en compleet om hopelijk in 2023 Hotel Colombo te openen. Dit in het aangrensende pand zoals te zien op de foto. we voldoen hiermee aan de behoefte van onze klanten om ook een leuke overnachten en RP te koppelen, daarnaast biedt het veel zakelijke kansen en een uitbreiding van ons bestaande bedrijf
Wij zijn ook bereid als het makkelijker is om van de zelfde aanbieder als de huidige MLO de onderstaande versie aan te schaffen die dan misschien verplaatst kan worden naar het cafe terrein.

![image](https://user-images.githubusercontent.com/120605155/235375986-b76f2b06-240b-41ff-b4aa-293ae6db877c.png)
https://www.youtube.com/watch?v=pb67hW0oAQg

Ik hoor graag wat er mogelijk is en we kijken met  plezier en spanning af naar jullie reactie. We lichten graag alles toe in een Call of DM.

Mvg

Colombo familie 

### Wat lost deze feature op?

- Toegankelijker voor de groep en overzichtelijker zodat we meer plaats hebben voor voertuigen zodat wij de RP hierin kunnen verbeteren. 
- Behoorlijke teamspirit boost 
- Bugs die niet goed zitten, zoals de pionen in het hek of koters die over hekken springen
- en nog veel meer die we met plezier toelichten

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
De props die sinds kort bij jullie zijn gekomen, kunnen we helaas niet weghalen vanwege de escrow van een andere MLO. Als het goed is heb ik dit vermeld bij [TDA] Dylan

**Comment by Donnycolombo** [comment]
Jammer ! maar levenbedreigend zeg maar :) horen graag over de rest

**Comment by DevvTDA** [comment]
@Donnycolombo 
Vraag me persoonlijk wel af waar ik iets van dit goedgekeurd zou hebben, persoonlijk ben ik niet van mening dat dit goedgekeurd zou moeten worden. Ook is dit niet mogelijk met de TFFT mlo vanwege escrow en vindt een 2e gebouw ernaast enorm overbodig. vanuit mij zou je hier dus geen goedkeuring voor krijgen nee.

**Comment by Donnycolombo** [comment]
@DevvTDA ik heb ook nooit gezegd dat je dit goed hebt gekeurd... als je dit zo hebt gelezen was dat niet de bedoeling, als het goed is heeft wins het eea aan je gevraagd, daar had ik er bij gezet aangekaart. daarnaast begrijp ik dat we dus vast worden gezet omdat tfft een escrow gebouw heeft en niks er meer mag komen. erg jammer hetzelfde als wat calray aangeeft. 

 een 2e gebouw aangrensend is voor ons super tof en het past totaal bij het verhaal van CCF waarbij we niet vragen een andere MLO ergens anders ien de stad maar hebben gezocht naar een complimentair RP verhaal. 2 gebouwen als offi gang is blijkbaar niet gek. volgensmij heeft de voorgenoemde partij dat zelfs. waarom is het minecraft TFFT gebouw daar uberhaupt geplaats als het zo zwaar is ? 
 
 Zijn de andere vragen wel mogelijk ? kan bv de garage groter en de martel kamer naar boven ? ik ben helaas niet technisch genoeg maar dat zou wel heel gaaf zijn

**Comment by DevvTDA** [comment]
TFFT is vanaf 3 jaar geleden al op die plek begonnen, dus de plek dat ze daar staan met dat gebouw is vrij duidelijk gaat ook mooi in hun verhaallijn waar het allemaal begon. Daarbij is dit het gebouw wat zij destijds gekocht hadden en helaas was dat escrow zij wilde daarvoor niet switchen wat ik kan begrijpen en dat accepteren we. 

Ik blijft erbij dat we het onnodige vinden voor een extra gebouw.

**Comment by Donnycolombo** [comment]
@DevvTDA jammer zown reactie maar dat was al te verwachten gezien het eerste antwoord en dank voor de uitleg van het TFFT verhaal dat geeft iets meer body eraan.

Is uitbreiding garage en verplaatsten martelkamer wel mogelijk ?

**Comment by DevvTDA** [comment]
Wat is er mis met deze garage?  en waar is de martelkamer nu?

**Comment by Donnycolombo** [comment]
@CorruptSausage  geen toestemming maar wij werden gevraagd een github hiervoor aan te maken... nu weer een ticket ?

@DevvTDA de martelkamer zit achter de rode kast in de garage, initieel was de vraag of de garage wat groter kom gezien we lastig met 2 mules hier kunnen keren, parkeren en manouvreren..... het zou dus heel fijn zijn als de garage groter kon. ik begreep dat dit niet zomaar kon ivm ruimte in het gebouw. als we de martelkamer verplaatsten zouden we die ruimte kunnen gebruiken voor de garage zodat we makkelijk kunnen keren, parkeren en ons werk doen.. zodoende de vraag van de martelkamer te verplaasten en de garage wat groter te krijgen. anders eventueel in een call verder te bespreken?

**Comment by Donnycolombo** [comment]
![image](https://user-images.githubusercontent.com/120605155/236648186-3a63b40c-3cb9-4672-8db7-2abdfb66cf8a.png)
 hier een mooi voorbeeld waarom een wat grotere garage echt super zou zijn, de jongens pakken 4 aks en gaan weg want met een ak midden op terrein je auto weg zetten kan ook niet. 

hoor het graag

**Comment by CalRayy** [comment]
@DevvTDA Kunt u dit met Hoge Raad bespreken, en eventueel goedkeuren / afkeuren voor CCF.

**Comment by DevvTDA** [comment]
@CalRayy  besproken, zijn er over eens dat inderdaad de garage wat groter gemaakt kan worden. verder zullen wij niet akkoord gaan met een uitbreiding van panden.

**Comment by Donnycolombo** [comment]
@DevvTDA jullie zijn toppers ! fijn dankjulliewel :)

**Comment by Donnycolombo** [comment]
@CalRayy kan ik nog iets doen, voorbereiden?

**Comment by CalRayy** [comment]
> @CalRayy kan ik nog iets doen, voorbereiden?
> 
> 

Donny, ik heb de files bekeken en zie dat de garage tot zijn maximale is gekomen. De enige optie wat ik hier zie is dat dan de martelkamer weggaat.

**Comment by Donnycolombo** [comment]
@CalRayy dat begrijp ik, kan de martelkamer dan ergens anders op het terrein, bv de 2e verdieping ? indien dat niet mogelijk is bv een andere locatie ?

**Comment by Donnycolombo** [comment]
@CalRayy garage van de wijk past bijvoorbeeld ook een mule in, misschien kan je dat model gebruiken

https://media.discordapp.net/attachments/1083407021933609042/1100458067214225458/image.png?width=1250&height=676

**Comment by DevvTDA** [comment]
@Donnycolombo ik zi dat je mijn bericht van een andere issue heb gekopieerd en geplakt. Jammer om te zien. Hierbij vergelijk je ook 2 MLO’s die niet hetzelfde zijn daarbij is er geen garage van karmellos dus is de garage van de weijck niet relevant voor colombo, gezien dit waarschijnlijk niet mogelijk is ivm het MLO.

**Comment by Donnycolombo** [comment]
@DevvTDA  dacht te helpen hoor want zie geen response, waar kunnen we bv zoeken om het makkelijker te maken ? en is toch gewoon slim om dit te doen ipv jammer... dont get it ...

**Comment by Tom974** [comment]
Wat is de status van deze issue? Is dit goedgekeurd, afgekeurd, kan dit doorgevoerd worden of niet?

**Comment by CalRayy** [comment]
Deze issues is opgelost
