### ISSUE TITLE
[FEATURE]: DJI Meldkamer meldingen ook uit dienst ontvangen als DJI

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2098]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T. / Kader

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk dat de DJI meldingen ook verkrijgen wanneer je uit dienst bent, zodat je ook reageren uit dienst om in dienst te komen.

### Wat lost deze feature op?

Levert extra RP op.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Krijg je deze nu niet dan @CalRayy ?

**Comment by CalRayy** [comment]
> Krijg je deze nu niet dan @CalRayy ?

Mij werd verteld van niet, maar heb het zojuist zelf getest en dit is al van toepassing.
