### ISSUE TITLE
[FEATURE]: DJI Bossmenu weghalen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2099]
### Contact Details

Chrushers#8656

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Er is een DJI bossmenu aangemaakt voor DJI leiding deze mag verwijderd worden.

### Wat lost deze feature op?

Dat men niet meer in het bossmenu kan dit komt te vervallen en zal Kader op zich nemen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Deze aanpassing zal definitief worden, zodra dit is aangepast worden het dus niet meer teruggedraaid. Gesproken met @CalRayy

**Comment by KMarTDA** [comment]
Duidelijk @CorruptSausage
