### ISSUE TITLE
[EUP]: DJI EUP

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2100]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Je ziet in de eup geen BOT vest, waardoor je niet je volledige BOT outfit kan aandoen. Zie screenshots: 
https://cdn.discordapp.com/attachments/1017422277178032129/1101662745809670164/image.png (main)
https://cdn.discordapp.com/attachments/1017422277178032129/1101664246003159161/image.png (dev)

- [x] DJI - Aspirant heeft acces tot de BOT kleren (dit hoort niet)
- [x] DJI - Junior heeft acces tot de BOT kleren (dit hoort niet)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
is opgelost
