### ISSUE TITLE
[EUP]: BSB Persoonsbeveiliger EUP

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2102]
### Contact Details

Johnny#8125

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Gezien de taken van de BSB willen wij graag 2 outfits zien in het EUP, deze zijn al samen gesteld en de nummertjes zijn als volgt:

Graag volgende outfit toevoegen aan het volgende kopje in de categorie 'Brigade Speciale Beveiligingsopdrachten'
Als naam: ''Persoonsbeveiliger''
T-shirt 1: 31
T-shirt 2: 0
Torso 1: 295
Torso 2: 0
Stickers 1: 0
Stickers 2: 0
Armen: 33
Armen 2: 0
Broek 1: 28
Broek 2: 0
Schoenen 1: 10
Schoenen 2: 0
Kogelvrij vest 1: 0
Kogelvrij vest 2: 0
Ketting 1: 28
Ketting 2: 2
Masker 1: 11
Masker 2: 0

Graag volgende outfit toevoegen aan het volgende kopje in de categorie 'Brigade Speciale Beveiligingsopdrachten'
Als naam: ''Leiding PB''
T-shirt 1: 31
T-shirt 2: 0
Torso 1: 295
Torso 2: 0
Stickers 1: 0
Stickers 2: 0
Armen: 33
Armen 2: 0
Broek 1: 28
Broek 2: 0
Schoenen 1: 10
Schoenen 2: 0
Kogelvrij vest 1: 0
Kogelvrij vest 2: 0
Ketting 1: 28
Ketting 2: 4
Masker 1: 11
Masker 2: 0

De volgende KMar rangen moeten deze kunnen zien:
kmar 80, 81, 82, 83 + 90, 95 & 100

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Is aangemaakt en gecommit, houd github commits op discord in de gaten :)
