### ISSUE TITLE
[FEATURE]: Garage verplaatsing 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2105]
### Contact Details

CalRay#1513

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

De gevangenis garage die op het moment staat bij de gevangenis verplaatsen naar voren bij de garage parkeer plek, zodat burgers na hun straf bij de gevangenis hun auto kunnen pakken. 

### Wat lost deze feature op?

Ze moeten niet enorm ver gaan lopen naar een garage.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Fixed na restart
