### ISSUE TITLE
[FEATURE]: Jailmenu actieve lijstje

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2107]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk om in de jail menu te laten zien, wie er op het moment actief in de stad is? 
Zie screenshot hoe het er nu uitziet: 
![image](https://user-images.githubusercontent.com/101106299/235991592-f20fa6b1-cce5-49c4-825d-d21cd0491f38.png)
Eventueel langs unjail speler een status check met "Actief" of "Non-Actief"

### Wat lost deze feature op?

Dan kan DJI roleplayen met de actieve mensen en de lijstje goed in de gaten houden etc. Geeft meer RP

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Zit er in na de restart.
