### ISSUE TITLE
[FEATURE]: als gedetineerde kunnen bellen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2109]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Is het mogelijk dat je elkaar kan slaan (Safezone weghalen) of dergelijke als je gejailed bent en ook dat je een telefoon kan gebruiken. Ze mogen namelijk een telefoontje plegen alleen dat kan niet waardoor wij /unjail moeten doen vervolgens telefoontje laten plegen en dan weer jailen. 

### Wat lost deze feature op?

Voegt RP toe. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zit er al in bij de algemene DJI / Gevangenis issue. dus ik sluit deze.
