### ISSUE TITLE
[FEATURE]: Karmellos Huis - Tennis veld werkend maken

### ISSUE THREAD

**Issue by TDASammie** [Tedeapolis/development#2110]
### Contact Details

Sammie#8681

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op het terrein van Karmellos staat een prachtig tennisveld, echter kunnen wij deze niet daadwerkelijk gebruiken. Er zijn wel werkende tennisbanen in TDA.  Wij vroegen ons daarom af of het mogelijk is om ons tennisveld werkend te maken. Coördinaten zal ik onderstaand neerzetten.

![image](https://user-images.githubusercontent.com/128930588/236573638-1875c9e9-72fb-4bc9-8488-675039466e28.png)

![image](https://user-images.githubusercontent.com/128930588/236573596-62138d0c-f01d-4a38-a39d-f6bc32418a79.png)

### Wat lost deze feature op?

Leuke toevoeging aan het huis

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @TDASammie,

Is dit goedgekeurd door staff of?
