### ISSUE TITLE
[FEATURE]: Rollen toekennen in overheidsdiensten discord door KMar leiding

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2113]
### Contact Details

Johnny#8125

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In de overheidsdiensten discord zijn er een aantal rollen die nog niet gegeven kunnen worden door de rol ''Marechaussee Leiding''
Dit gaat voornamelijk om nieuwe rollen die wel door kaderleden gegeven moeten worden.

Het gaat om de volgende rollen:
DOC
Hoofdofficier
Intel
Accessrole
hOvJ
Dienst Justitiële Inrichtingen (DJI)

### Wat lost deze feature op?

Kaderleden kunnen dan alle neventaken rollen toewijzen aan personen die hiervoor bevoegd zijn.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Volgensmij kun je deze rollen gewoon aanvragen in het daarvoor bestemde kanaal, denk dat dit niet echt nodig is... ?

**Comment by KMarTDA** [comment]
@Tom974 Dat klopt in principe, echter is het handig als kader zijnde om alle rollen te kunnen geven naast de rollen die we momenteel al kunnen geven/afnemen via de bot. Er is al een ruime selectie die wij kunnen geven en afnemen en het is handig om alle rollen die KMar leden kunnen krijgen ook te kunnen nemen en afnemen.
