### ISSUE TITLE
[FEATURE]: Flitspalen bij ziekenhuis

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2114]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij het een fijn idee vinden om bij het ziekenhuis flitspalen te krijgen. Want mensen rijden hier erg hard. Als wij vanaf het gemeentehuis moeten oversteken naar het ziekenhuis is het echt een groot gevaar om niet dood gereden te worden. Is hier toevallig een mogelijkheid voor?

Groetjes Wilma Wonka

### Wat lost deze feature op?

Niets . We zouden het op prijs stellen als ze er zouden kunnen komen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Is hier goedkeuring voor vanuit staff @WilmaWonka1985 ?

**Comment by WilmaWonka1985** [comment]
@Tom974 Jah zeker van Nyx Laporta

**Comment by WilmaWonka1985** [comment]
> Is hier bevestiging voor vanuit personeel@WilmaWonka1985?

jah zeker er is een Suggestie gemaakt bij ons er voor

**Comment by WilmaWonka1985** [comment]
@CorruptSausage

**Comment by ARJ3N** [comment]
Er kan één flitspaal geplaatst worden aan de kant van het gemeentehuis zodat de ambulances daar veiliger de weg op kunnen rijden vanaf het ziekenhuis. @Tom974

**Comment by CorruptSausage** [comment]
Zit erin na de restart
