### ISSUE TITLE
[BurgerRaad]: Voertuigen kunnen hernoemen in Gang Opslag.

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2117]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment is het niet mogelijk om voertuigen te kunnen hernoemen in een gangopslag. Dit is vervelend omdat het hierdoor super onoverzichtelijk word.

Wij hebben daarom in BurgerRaad besproken een functie aan te vragen waardoor je de voertuigen in de gang opslag kan hernoemen. Denk hierbij aan het zelfde idee als hoe je op het moment wapens kan hernoemen in een wapen opslag

**Dit is besproken in BurgerRaad**

### Wat lost deze feature op?

Meer overzichtelijkheid in de gangopslag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hey @ExoticaTDA,

Zou er misschien een schets gemaakt kunnen worden van hoe dit eruit moet zien? 

Dus bij welk menu moet je hoe en wat kunnen doen, welk menu open ik eerst en welke daarna etc etc.

Thanks!

**Comment by ExoticaTDA** [comment]
> Hey @ExoticaTDA,
> 
> Zou er misschien een schets gemaakt kunnen worden van hoe dit eruit moet zien?
> 
> Dus bij welk menu moet je hoe en wat kunnen doen, welk menu open ik eerst en welke daarna etc etc.
> 
> Thanks!

Heb dit in je DM gestuurd!

**Comment by Tom974** [comment]
oke meneer
