### ISSUE TITLE
[BurgerRaad]: Toevoegen Melee wapens

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2118]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Er zijn op het moment veel melee wapens in de stad, echter missen er nog 2 waar je hele leuke originele RP mee neer kan zetten.
Dit zijn de volgende:

“WEAPON_POOLCUE” (slaat knock-out)
![image](https://github.com/Tedeapolis/development/assets/120292087/3cb26996-23ea-4090-8bef-e65cab6a4f46)

“WEAPON_PIPEWRENCH” (slaat dood)
![image](https://github.com/Tedeapolis/development/assets/120292087/fc632b38-83ec-4852-b0c1-60f058c5c5dd)

Dit zijn wapens waar je weer leuke nieuwe scenario's neer kan zetten als loodgieter, of bijvoorbeeld een uit de hand gelopen bar gevecht.

Ook leek het ons een leuk idee om dan de Poolcue het zelfde effect te geven als de nightstick. Met een poolcue sla je dus niemand dood, maar je slaat iemand wel knockout met 2 hits.

Het idee is dan om deze toe te voegen aan de Level 1 wapen inkoop

**Dit is besproken in BurgerRaad**

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by ARJ3N** [comment]
De melee wapens zijn goedgekeurd. Knuckledusters mogen knock-out slaan en dan kan de poolcue gewoon doodslaan. @Tom974

**Comment by ExoticaTDA** [comment]
> De pipewrench moet ik helaas afwijzen aangezien wij die momenteel ergens anders voor gebruiken.
> 
> De poolcue heb ik toegevoegd, zal beschikbaar zijn wanneer je dit in github-commits ziet staan.

Die pipewrench is atm zeker die sugarcane?

**Comment by Tom974** [comment]
> > De pipewrench moet ik helaas afwijzen aangezien wij die momenteel ergens anders voor gebruiken.
> > De poolcue heb ik toegevoegd, zal beschikbaar zijn wanneer je dit in github-commits ziet staan.
> 
> Die pipewrench is atm zeker die sugarcane?

yes klopt
