### ISSUE TITLE
[FEATURE]: CLS items toevoegen HRB EUP

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2119]
### Contact Details

Larrsss#3819

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

**DSI CLS Backpack + Backpack Afdoen toevoegen** aan HRB eup.
Gaat om de rangen :
- HRB Commandant
- HRB Sectiecommandant
- HRB Groepscommandant
- HRB Operator

### Wat lost deze feature op?

HRB krijgt de functie CLS erbij in het takenpakket waarbij deze items in de EUP nodig zijn. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Heb je een foto van wat het moet zijn? @KMarTDA

**Comment by KMarTDA** [comment]
https://prnt.sc/sHfXbwkqTn6k
https://prnt.sc/XKWFw3ckcZgC
@DevvTDA

**Comment by Jokos53** [comment]
Een goeden dag @DevvTDA ,
Wij namens de HRB hebben de vraag hoe het er voor staat met de CLS-EUP. Dit wegens de github al een tijdje open staat en wij benieuwd zijn hoe lang dit nog gaat duren zodat wij er rekening mee kunnen houden.

Een fijne dag verder,
Jokos

**Comment by DevvTDA** [comment]
@Jokos53 als ik eerlijk ben heb ik over deze hele github heengekeken, zal hier zsm naar kijken. Ben er wel bang voor dst dit pas zondag/maandag gaat zijn. 

Excuses voor het lang wachten !!

**Comment by Jokos53** [comment]
Dat is top het heeft voor nu ook nog geen haast. Bedankt voor je antwoord!

**Comment by DevvTDA** [comment]
![Image](https://github.com/Tedeapolis/development/assets/79802852/ba8741a0-3465-4a41-a589-7ba201ecf625)

**Comment by DevvTDA** [comment]
Toegevoegd naar de restart :) mocht er nog wat zijn hiervan stuur me even een DM

**Comment by Jokos53** [comment]
Topper bedankt voor de moeite!
