### ISSUE TITLE
[FEATURE]: Markeer als behandeld optie in de DJI meldkamer

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2122]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In de dji meldkamer is er momenteel geen optie om een melding te markeren als behandeld. Waardoor het soms onduidelijk is voor sommige die niet in de porto iets heeft gehoord dat de melding afgehandeld is of niet. Daarom lijkt het me handig als de dji dat krijgt in de meldkamer voor verwarring te voorkomen.

### Wat lost deze feature op?

Verwarring en snellere handelingen voor de DJI. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@CalRayy 

Mogelijk was dit gefixed, klopt dit?

**Comment by CalRayy** [comment]
> @CalRayy 
> 
> 
> 
> Mogelijk was dit gefixed, klopt dit?

Ik zal dit vanavond ergens bekijken!
