### ISSUE TITLE
[Bug]: Porto glitch tijdens het willen schieten

### ISSUE THREAD

**Issue by WinsEU** [Tedeapolis/development#2123]
### Contact Details

Wins#7732

### Wat gebeurde er?

Op het moment dat jij je wapen vast pakt en praat door de porto en aimt om te gaan schieten pakt hij de animatie niet meer goed door, hij blijft hangen in de porto waardoor je niet meer kan richten om te gaan schieten.

### Wat hoorde er te gebeuren?

Dat wanneer je de porto los laat en wilt gaan richten hij het wapen goed moet pakken om te kunnen schieten. Nu blijft hij vast hangen in de porto animatie.

### Wat veroorzaakt de bug?

Na het praten in de porto komt dit voor tijdens het richten en willen schieten.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

Die heb ik niet zo 123, heb enkel clips ervan
 Voorbeeld 1.
https://streamable.com/c3j30r
Voorbeeld 2.
https://streamable.com/ss2cus

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Of je praat niet in je porto tijdens het trekken van je wapen 🤔 ?

**Comment by WinsEU** [comment]
Dit wat vroeger nooit zo? en porto contact lijkt me wel handig voordat je gaat schieten om duidelijke communicatie te zoals "rijd iets zachter" of zoals een agent zegt dit ook met de noodknop te hebben.

Als dit opgelost kan worden zou dit fijn zijn is wel gewoon een bug en het hoort van oorsprong niet, of zeg ik iets nou heel raars? :)

**Comment by Wiebren-3** [comment]
Is ook niet alleen tijdens het trekken van je wapen zoals...

**Comment by Wiebren-3** [comment]
Bij noodknop is dit ook 10sec erna
