### ISSUE TITLE
[FEATURE]: Box beugel dodelijk maken ( 2 klappen ) 

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#2124]
### Contact Details

[TDA] Johnny Flodder#3559

### Goedgekeurd door

Wordt meegenomen tijdens staff overleg 

### Beschrijf zo duidelijk mogelijk de feature

Nu is het zo dat je met een bogbeugel K.O gaat en daardoor gaan mensen looten kwa wapens.
Graag de boxbeugel dodelijk maken ( 2 klappen ) 

### Wat lost deze feature op?

Dat mensen niet gaan looten voor wapens.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
https://github.com/Tedeapolis/development/issues/2118#issuecomment-1556253949

🤔

**Comment by JohnnyFlodder** [comment]
Besproken tijdens staff overleg:

Het afpakken blokkeren als iemand K.O is, om zo het looten tegen te gaan. :)

**Comment by Tom974** [comment]
done.
