### ISSUE TITLE
[FEATURE]: Haaien kunnen zien als prop bij het uithalen en inzetten in een voertuig

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2125]
### Contact Details

CalRay#1513

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

We hebben in staff overleg besproken om net zoals bij drugs uit een voertuig halen dat dit ook moet komen voor haaien dat je ziet dat het in een voertuig wordt gezet en ook eruit wordt gehaald. **Als dit eenmaal van toepassing is, mag de prijzen volgens staff overleg van de haaien 10% stijgen.** 

### Wat lost deze feature op?

Meer risico en KMAR / Politie kunnen hierop handteren

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Wiebren-3** [comment]
is nog geen gta5 prop van, wel een kleine vis die je kunt toepassen, want die A_C_SharkHammer is wel een beetje groot. Mijn idee is de "A_C_Fish, is het in elk geval herkenbaar.

**Comment by Tom974** [comment]
Is hier al een prop oid voor @CalRayy ?

**Comment by Tom974** [comment]
Als je een prop vind kun je de issue opnieuw openen.
