### ISSUE TITLE
[FEATURE]: Verhogen kans op schietmeldingen

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#2126]
### Contact Details

Lamine#4904

### Goedgekeurd door

Tijdens staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Tijdens het staff overleg is er besloten dat de pakkans als criminelen schieten omhoog moet, door de delay op een schietmelding te verlagen en de kans dat er een melding komt te verhogen. Er is geen specifieke richtlijn afgesproken, maar wel dat de pakkans significant groter wordt.

### Wat lost deze feature op?

Momenteel hebben gangs grote hoeveelheden aan wapens. Hierdoor komen er te veel wapens bij overige spelers. Door de pakkans bij schietmeldingen te vergroten, zullen er meer wapens verloren gaan.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Heb ze iets aangepast, kijk maar in je dm voor de exacte data.
