### ISSUE TITLE
[FEATURE]: ANWB boten spawn locatie

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2129]
### Contact Details

DeStefanoKiller#4442

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

- [x] Cirkel om ANWB boot te pakken (Vanaf rang autotechnisch ingenieur + hoger en moet zichtbaar zijn zowel in als uit dienst)
Coords naar cirkel: 
![image](https://github.com/Tedeapolis/development/assets/68514420/497a6f76-80c7-45c1-8cea-3c87460092aa)

- [x] Coords waar ANWB boot moet spawnen:
![image](https://github.com/Tedeapolis/development/assets/68514420/3180d955-e8dc-4c47-b9e7-cf661988e202)

**Spawn naam van boot = anwbdinghy**

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DeStefanoKiller** [comment]
Als het niet anders kan dan is het niet anders, was handig geweest voor ons zodat wij uitdienst cursussen konden geven.

@Tom974

**Comment by Tom974** [comment]
Check, ik zal het vanavond door laten pushen door Niek :P
