### ISSUE TITLE
[FEATURE]: Exotica Group

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2131]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag een group genaamd "exotica_boss" willen. Dit omdat de eigenaar en de onderbaas allebei meerdere rangen heeft en hierdoor de Exotica rang niet kunnen hebben. Deze group zou dan precies dezelfde perms moeten krijgen als dat de rang "Exotica Eigenaar" nu heeft.

Dit is op het moment heel vervelend aangezien ik zelf dus de heletijd moet switchen tussen Dierenkliniek Eigenaar en Exotica Eigenaar en de Onderbaas moet de heletijd switchen tussen Exotica Onderbaas en R3D Manager. Dit zijn allemaal jobs waar je de rang ook echt nodig hebt. En als exotica_boss dus op een group gezet kan worden zou dit heel veel gedoe voorkomen

### Wat lost deze feature op?

Dit voorkomt de dagelijkse reports moeten maken om te vragen of ze een rang kunnen aanpassen. En het hierdoor dus vaak niet openkunnen gooien van de club.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Door wie is dit goedgekeurd / met wie heb je dit besproken?

**Comment by Tom974** [comment]
Sleutels zou wel doorgevoerd mogen worden.

**Comment by ExoticaTDA** [comment]
> Sleutels zou wel doorgevoerd mogen worden.

Top, als je dan de manage group op mijn naam kan zetten (Dyon) zou dat perfect zijn!
