### ISSUE TITLE
[Bug]: In container klimmen werkt bij veel containers niet

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2133]
### Contact Details

Arjen#0001

### Wat gebeurde er?

In containers klimmen werkt enkel op de blauwe containers en niet op de groene (zie foto).
![image](https://github.com/Tedeapolis/development/assets/92899337/0633afcf-ee33-439f-b09a-b2ca5629565e)

### Wat hoorde er te gebeuren?

Je hoort in alle containers te kunnen klimmen.

### Wat veroorzaakt de bug?

Zoek een groene container en probeer er in te klimmen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Dit is een geen bug, dit heb ik met opzet toegevoegd.

**Comment by ARJ3N** [comment]
> Dit is een geen bug, dit heb ik met opzet toegevoegd.

Waarom? :)

**Comment by ARJ3N** [comment]
> Dit is een geen bug, dit heb ik met opzet toegevoegd.

Waarom? :P @CorruptSausage

**Comment by CorruptSausage** [comment]
We hadden eerst gekozen om het iedere keer te random in te delen welke containers er wel en niet beschikbaar waren, achteraf hebben we er toch gewoon voor gekozen om het zo in te stellen. Dan is het script namelijk veel beter geoptimaliseerd.

**Comment by ARJ3N** [comment]
Check, thanks voor de reactie! :)
