### ISSUE TITLE
[FEATURE]: Setjob links weergeven in de chat 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2136]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Ik had aan Tom gevraagd in call als het mogelijk is om links in de chat te laten zien als de persoon in kwestie de juiste rang of uberhaupt een rang heeft gekregen. Hij was namelijk bezig met een UI update met togglename en noclip etc in de chat. 

### Wat lost deze feature op?

Handig voor staff. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Done
