### ISSUE TITLE
[EUP]: hOvJ-steekvest

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#2137]
### Contact Details

Lamine#4904

### Goedgekeurd door

Devv #4532

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Het is nu zo dat hulpofficieren van justitie (hOvJ's) vaak persoonlijke kleding dragen met daarover een normaal politie steekvest, zodat ze herkenbaar zijn als hOvJ. 

In plaats daarvan willen we graag dat hOvJ's normale politiekleding dragen, maar wel herkenbaar zijn.

Hopelijk lukt het om een extra steekvest te maken, net als het wijkagent steekvest, maar dan met de letters 'hulpofficier van justitie' (of hOvJ) erop.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
gecommit, moet enkel nog gepushed worden en dan zit het er in.

**Comment by jaim1114** [comment]
@DevvTDA Het steekvest zit nog niet in de EUP van de politie (en ik denk ook niet bij de kmar), zou dit nog geregeld kunnen worden?

**Comment by DevvTDA** [comment]
oepsie, stond wel i de server maar inderdaad niet in de eup my bad! na de restart staat het er in
