### ISSUE TITLE
[BurgerRaad]: Boksbeugel Nerfen

### ISSUE THREAD

**Issue by ExoticaTDA** [Tedeapolis/development#2139]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In BurgerRaad is besproken de boks beugel te nerfen kwa damage. Op het moment kan je vaak iemand met 1 monkey punch knock-out slaan om dan vervolgens die persoon te rippen.

We zouden dus graag de damage van een boksbeugel lager zien zodat je meer stoten nodig hebt om iemand knock-out te slaan.

### Wat lost deze feature op?

Het feit dat je iemand met 1 slag knock-out kan slaan en dan die persoon meteen kan rippen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Heb er even naar gekeken met @niekschoemaker, maar krijg de damage niet echt aangepast.

Gta doet een beetje moeilijk kwa damages met melees. 

Hier zal dan dus even een andere oplossing voor gezocht moeten worden @ExoticaTDA.
