### ISSUE TITLE
[FEATURE]: Lightbars toevoeging

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#2140]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

De mogelijkheid om specifieke modellen (lampen) via K aan te kunnen zetten in plaats van Q

Modellen die doormiddel van K geactiveerd dienen te worden:
- stopvoor
- stopachter

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Moeite weegt niet op tegen de voordelen.
