### ISSUE TITLE
[FEATURE]: /checkplate kunnen doen als ambulance

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2142]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

Nyxx #2490

### Beschrijf zo duidelijk mogelijk de feature

Mogelijkheid om /checkplate te doen als teamleider zijnde om zo te achterhalen van wie de achtergelaten ambulance is.

Het is de bedoeling dat dit alleen voor Teamleider/Baas rang is.

Wij weten dat politie/Kmar/taxi dit kunnen. 
Maar wij willen het ook graag hebben als het mogelijk is.

### Wat lost deze feature op?

Dat wij de collega's zelf kunnen aanspreken op het opruimen van hun wagens als ze ineens de stad uit zijn. Dat we niet elke keer politie/ANWB melding hoeven te maken. Zo kunnen wij ze zelf opruimen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Even nagevraagd gezien dit nogal wat werk is om toe te voegen, en daaruit besloten om het voor nu even te laten.
