### ISSUE TITLE
[FEATURE]: Fully maken Taxi voertuig

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#2143]
### Contact Details

Timez#0003

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag onze Aston Martin DBX fully willen ontvangen in onze Taxi garage

### Wat lost deze feature op?

Dit zal oplossen dat deze op een off-road gedeelte geen moeite meer heeft. Wij hebben hier 2 video's van, 1 waarbij de DBX stock is en 1 waarbij deze fully is.

Video 1 (stock): https://medal.tv/games/gta-v/clips/1cZKwyXF9O_bNL/d1337gOo9A5X?invite=cr-MSxiSmIsNDg1Nzc3ODMs

Video 2 (fully): https://medal.tv/games/gta-v/clips/1cZKIit1Wip1X7/d1337EB8jcxX?invite=cr-MSxDeUQsNDg1Nzc3ODMs

Zoals te zien is in de video's is dit wel iets wat best belangrijk is gezien niet iedereen toegang heeft tot een off-road auto en wij wel graag zouden zien dat deze kwa performance in iedere situatie werkt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Hier is in issue #1935 ook al aangegeven dat we dit niet gaan doen.

**Comment by TedeaTaxi** [comment]
> Hier is in issue #1935 ook al aangegeven dat we dit niet gaan doen.

Dat snap Ik volledig. En wij zijn het er ook mee eens dat onze voertuigen niet fully gemaakt hoeven worden. Maar dit gaat om de functionaliteit van dit voertuig. Het is bedoelt als off-road voertuig maar deze bereikt niet de performance om hem volledig off-road te kunnen gebruiken. Dit is te zien in de video's die hierbij zijn vermeld. Eventueel fully maken maar snelheid op een bepaalde snelheid cappen anders?
