### ISSUE TITLE
[FEATURE]: Taxi Vito snelheid

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#2144]
### Contact Details

Timez#0003

### Kenteken van voertuig

NVT (overheid voertuig)

### Voertuig model

Mercedes-Benz V250 

### Omschrijf de bug

De Mercedes Vito die wij uit de Taxi garage halen haalt met heel veel moeite een top snelheid van ongeveer 170. Deze hoort normaal gesproken 195 te bereiken

Video: https://medal.tv/games/gta-v/clips/1d9P4QmOCRP8Xb/d1337ZrNaJMB?invite=cr-MSxXb24sNTY5OTE5MTMs

### Repro

1. Taxi job in test stad
2. Taxi garage betreden
3. Mercedes Vito pakken
4. Test ritten

### Normaal gedrag

Deze auto hoort zoals gewoonlijk een snelheid van 195 km/h te bereiken. Maar zoals te zie is in de video haalt hij deze helaas niet momenteel

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CorruptSausage** [comment]
Zover ik weet is hier niks aan aangepast, deze heeft altijd al deze snelheid gehad. Klopt dit?

**Comment by Wiebren-3** [comment]
@CorruptSausage Dit is aangepast met de nieuwe snelheidslogica update, Lorenzo heeft aangegeven in "Tedeapolis Cardealer" dat je het daar in een kanaal kan achterlaten. Hier linkje naar het kanaal: https://discord.com/channels/727258132312490034/1109206263407050772

**Comment by CorruptSausage** [comment]
@Wiebren-3 Waarom wordt er hier een issue gemaakt als er gezegd werd dat je het in dat kanaal kon achterlaten?

**Comment by TedeaTaxi** [comment]
> @Wiebren-3 Waarom wordt er hier een issue gemaakt als er gezegd werd dat je het in dat kanaal kon achterlaten?

Ik was er niet van op de hoogte dat Ik dit via de Cardealer Discord kon regelen. Vandaar dat Ik dit via de github heb aangevraagd. Ik zal het daar even vermelden
