### ISSUE TITLE
[FEATURE]: Automatische XMIT 2 aanzetten net zoals XMIT 1 bij de radar systeem

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2145]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op het moment moeten wij onze mooie radar systeempje openen en moeten we de onderste XMIT (2) drukken om ook achter ons te flitsen. Mij lijkt het handig dat hij net als de eerste XMIT gelijk aan gaat i.p.v. apart selecteren en het te activeren. Ik dacht hieraan en besloot een suggestie ervan te maken, aangezien dit veel makkelijker kan gaan lijkt me. (https://cdn.discordapp.com/attachments/918097867644755998/1117167956175097887/image.png)

Voordelen:
Sneller de radar aan kunnen doen.
Minder tijd verloren om het te selecteren.

Nadelen:
Luiheid & te luxe.

### Wat lost deze feature op?

Sneller te werk gaan. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@CalRayy luie zak

**Comment by CalRayy** [comment]
> @CalRayy luie zak

Nou ja zeg 😂

**Comment by Tom974** [comment]
Denk dat het mij meer moeite kost om dit toe te voegen dan dat je het zelf even handmatig aan zet.
