### ISSUE TITLE
[FEATURE]: KL toegang krijgen tot de setped menu.

### ISSUE THREAD

**Issue by Jeanpaulmorris** [Tedeapolis/development#2146]
### Contact Details

jeanpauls

### Goedgekeurd door

Misstake

### Beschrijf zo duidelijk mogelijk de feature

Graag korpsleiding toegang laten krijgen tot de setped menu (Als het kan alleen voor K9).

### Wat lost deze feature op?

Omdat korpsleiding bezig is om K9 op te zetten binnen het korps en dan hoeven ze staff niet te vragen om iemand te veranderen in een K9 ped.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
![image](https://github.com/Tedeapolis/development/assets/55812394/155d3c2e-324a-44bc-b28f-fce584ee2e36)
Vanuit wie in het staffteam is dit goedgekeurd if I may ask?

**Comment by Jeanpaulmorris** [comment]
Niek. Hij zei zo:" Ja maak maar een github van".

**Comment by Jeanpaulmorris** [comment]
PS: Goedkeuring van Niek
