### ISSUE TITLE
[BurgerRaad]: Snelweg Namen

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2147]
### Contact Details

Dyon#9999

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

De snelwegen op TDA een naam geven.
Dit zou er voor kunnen zorgen dat er wat meer realisme is in bijvoorbeeld achtervolgingen etc.

Wellicht zou het een idee zijn om op de kaart wanneer je op escape drukt, dat daar de namen van de snelwegen op worden weergegeven zoals hieronder: (dit is een voorbeeld, dit hoeft in principe niet zo uitgebreid)
![image](https://github.com/Tedeapolis/development/assets/120292087/a49118ce-5bfd-4ecd-b52b-06c82d7f8f24)

### Wat lost deze feature op?

Dit zou er voor kunnen zorgen dat er wat meer realisme is in bijvoorbeeld achtervolgingen etc.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
En hoe zit het met de custom straatnamen dan 🤔

**Comment by Tom974** [comment]
Gesloten op verzoek
