### ISSUE TITLE
[FEATURE]: Lucas

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2148]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag bij de ambu de luca's als prop willen. Mensen vragen erom om zo de RP te verbeten wegens dat we het kunnen gaan gebruiken voor de AED.

Nu moeten wij hem op de rug hebben, maar zouden hem ook graag neer willen zetten. 
Is dit misschien mogelijk?

Groetjes Wilma

### Wat lost deze feature op?

Dat de collega's de luca's makkelijker en vaker gaan gebruiken voor de AED als ze het moeten gebruiken om shoks toe te dienen als iemand een hartstilstand heeft.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
