### ISSUE TITLE
[Bug]: Missiles doen geen damage/impact op voertuigen/helikopters 

### ISSUE THREAD

**Issue by 123024** [Tedeapolis/development#2149]
### Contact Details

just_emre  

### Wat gebeurde er?

 raketten doen geen damage/ impact op voertuigen / helikopters. Homing of geen homing maakt geen verschil. Alleen degene die raketten afschiet ziet de raketten ook daadwerkelijk afgevuurd worden. Anderen kunnen dit niet eens zien dit hoort ook niet. Daarnaast ziet alleen degene die ze afschiet ze ook ontploffen, hierbij gebeurd er verder niks met de helikopter of auto waarop geschoten wordt. 

Dit is een bug met een grote impact op de server aangezien criminelen vrij spel hebben in het luchtruim waar veel geschoten wordt en dagelijks veel drugs wordt vervoerd. De Luchtmacht is niet meer inzetbaar. https://www.youtube.com/watch?v=-vtuEN6IFIc&ab_channel=E024

### Wat hoorde er te gebeuren?

raketten horen net zoals in GTA Online direct impact / damage te doen op een voertuig / helikopter. Daarnaast zou iedereen ontploffingen moeten kunnen zien + de raketten die worden afgevuurd. 

### Wat veroorzaakt de bug?

Pak een buzzard of een armed toestel en een helikopter of voertuig naar keuze. 
Laat 1 persoon in een buzzard stappen met /arm en de juiste rang. 
Schiet met homing missiles op een helikopter of voertuig. 
Hierbij zie je direct dat raketten niet werken en degene in het voertuig zal geen raket zien of ontploffing. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Fixed
