### ISSUE TITLE
[Bug]: Geen missiles kunnen afvuren wanneer je in je benen wordt geraakt/voet

### ISSUE THREAD

**Issue by 123024** [Tedeapolis/development#2150]
### Contact Details

just_emre 

### Wat gebeurde er?

Tijdens luchtmacht diensten is er gemerkt dat wanneer een piloot in zijn been/voet wordt geraakt terwijl hij in zijn helikopter zit, dat hij geen raketten kan afvuren, of kan schieten met een machine gun voor een X aantal seconden. Dit is onrealistisch aangezien je zit in je helikopter en dus niet zou moeten vallen zoals dat op de grond gebeurd als je in je benen wordt geraakt. 

### Wat hoorde er te gebeuren?

Als je wordt geraakt in je been/voet terwijl je in een helikopter zit dan zou je weaponwheel/ raketten / machinegun niet geblocked moeten worden voor een X aantal seconden omdat je in een helikopter zit.

### Wat veroorzaakt de bug?

Raak een piloot in zijn voet/been
Piloot kan voor X aantal seconden niet meer schieten/ raketten afvuren

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Is de impact van deze bug daadwerkelijk hoog?

Like hoe vaak wordt een piloot in zijn benen geraakt terwijl die vliegt?

**Comment by Tom974** [comment]
fixed
