### ISSUE TITLE
[Bug]:  Mogelijkheid Heli-Radars uitzetten voor Vlieginstructeur's | Werkt niet

### ISSUE THREAD

**Issue by Smokjertje12** [Tedeapolis/development#2152]
### Contact Details

smokertje12

### Wat gebeurde er?

Bij het gebruik van de laatst toegevoegde feature om heliradars uit te zetten voor vlieginstructeurs met (/disable_airspace_pings) 
gebeurt er niets.

### Wat hoorde er te gebeuren?

De Heliradars zouden voor de speler/vlieginstructeur uitgeschakelt of ingeschakelt moeten worden. 
![Screenshot 2023-06-16 145547](https://github.com/Tedeapolis/development/assets/86876080/2b363412-addc-4161-bd27-a3d5cb25cabe)

### Wat veroorzaakt de bug?

Ongekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Heb je hier wellicht een videoclipje bij @Smokjertje12 ?

Laatste keer dat ik het zelf testte werkte het prima namelijk

**Comment by Smokjertje12** [comment]
https://medal.tv/games/gta-v/clips/1dZN9doYPDYL8H/d13379nRLAAT?invite=cr-MSxLSGksNTIxMTYwODAs

**Comment by Tom974** [comment]
Oh, die hele command is weg inderdaad, zal eens kijken hoe dat komt.

**Comment by Smokjertje12** [comment]
Thx!

**Comment by Tom974** [comment]
gefixt na de restart
