### ISSUE TITLE
[FEATURE]: Onderscheid tussen wapens in voertuig

### ISSUE THREAD

**Issue by ghost** [Tedeapolis/development#2153]
### Contact Details

Mathijs.#9818

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment als iemand twee dezelfde vuurwapens in de auto heeft en je een wapen hiervan wil pakken pak je het wapen die het langst in het voertuig zit. Dit is nogal een issue aangezien je dan of de wapens apart moet leggen of opnieuw terug erin moet doen..

**Het voorstel is**

Ervoor zorgen dat je net zoals de gangopslag dan in een nieuw menu komt eventueel waarbij je kan kiezen welk wapen je wilt pakken met eventueel een naam zodat je in voertuigen het makkelijk kan scheiden.

### Wat lost deze feature op?

Dit is vooral makkelijk voor de level 2 of lager of voor de criminelen die hun vuurwapens in hun auto hebben liggen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hiervoor is de gangopslag
