### ISSUE TITLE
[FEATURE]: Custom ringtone

### ISSUE THREAD

**Issue by DevNsGames07** [Tedeapolis/development#2154]
### Contact Details

NsGames07#2712

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kan je met de telefoon alleen de achtergrond veranderen met een linkje van een afbeelding wat mij leuk lijkt dat ook een eigen ringtone kan kiezen inplaats van de normale 

### Wat lost deze feature op?

Dat je zelf een ringtone kan kiezen en dat je je telefoon iets meer kan customizen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Dyon033** [comment]
Volgensmij heb jij geen permissie om een github aan te maken?

**Comment by CorruptSausage** [comment]
Precies wat @ExoticaTDA zegt, heb je hiervoor toestemming?

**Comment by Tom974** [comment]
Gelieve hiervoor even een suggestie aan te maken in de tedeapolis discord en indien er daar toestemming is gegeven, hier pas een github issue te maken. 

Dankjewel!
