### ISSUE TITLE
[FEATURE]: Nieuwe rangen justitie

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#2156]
### Contact Details

yohandessu

### Goedgekeurd door

NVT

### Beschrijf zo duidelijk mogelijk de feature

**Binnen justitie willen wij 2 nieuwe rangen introduceren en 1 rang aanpassen.** 

**Justitie - Griffier (25)**
Loon:
Salaris indienst: 1100
Uitdienst salaris: 150

**Justitie -  Meester in rechten (35)**
Loon: 
Salaris indienst: 1250
Salaris uitdienst: 150

**Aanpassingen:**

Justitie  - Advocaat stagiair (0) 
_aanpassen naar_ 
Justitie - Stagiair jurist (0)

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Alleen als je wiebe terug aanneemt doe ik de rangen er voor je in :)

_p.s. ik doe dit om wiebe te irriteren_

**Comment by Tom974** [comment]
Done, zit erin na restart
