### ISSUE TITLE
[FEATURE]: In-game ontslag bij een permban

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#2157]
### Contact Details

Lamine

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Als iemand een permban ontvangt, dan zie ik graag dat de politierang of KMar-rang automatisch wordt weggehaald.

### Wat lost deze feature op?

Momenteel is het niet altijd duidelijk dat een speler bij de politie/KMar zit als hij een permanente ban krijgt. Als deze gepermbanned wordt, dan kan degene alsnog misbruik maken van het MEOS en andere systemen. Daarom zie ik graag dat dit aangepast wordt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dus de job moet worden weggehaald en het meos account @TDA-SanderD ?

**Comment by Dyon033** [comment]
Misschien dit gelijk doen met alle overheidjobs?

**Comment by TDA-SanderD** [comment]
> Dus de job moet worden weggehaald en het meos account @TDA-SanderD ?

Klopt en het MEOS-account mag dan inderdaad gedeactiveerd worden.

**Comment by Tom974** [comment]
Zit erin na de herstart

Meos werd al gedeactiveerd wanneer je job veranderd werd.
