### ISSUE TITLE
[FEATURE]: nieuw icoontje reznikov

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#2159]
### Contact Details

epictom

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zagen dat bloods hun huis icoontje, hun logo was en vonden dat wel vet eruit zien. Nu vragen wij eigenlijk precies hetzelfde. Of het Reznikov logo als icoontje krijgen inplaats van dus die rode kroon die we nu hebben. 

### Wat lost deze feature op?

NVT

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by EpicTomm** [comment]
![image](https://github.com/Tedeapolis/development/assets/104857888/39889a0e-4cd9-44f0-8097-7d5e01516632)

**Comment by Tom974** [comment]
Denk dat deze even komt te vervallen icm jullie level.
