### ISSUE TITLE
Weapon attachments 

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#216]
We krijgen meerdere meldingen van verschillende spelers dat weapon attachments verdwijnen als je het wapen uit je appartement haalt. 

De speler ziet dan rechts in beeld wel welke attachments hij erbij hoort te krijgen, maar ze worden niet daadwerkelijk toegevoegd op het wapen. 

Video: https://cdn.discordapp.com/attachments/761593456560308297/761593786467614800/FiveM_2020-10-02_16-18-22_Trim.mp4

**Comment by TDA-SanderD** [comment]
Log van het probleem: https://cdn.discordapp.com/attachments/763379525094080542/763379627074387978/CitizenFX_log_2020-10-07T121745.log

**Comment by prepix** [comment]
Kleine aanvulling:

**Werkt wel wanneer:**
Je koopt
Je relogged

**Werkt niet wanneer:**
Je wapen pakt uit voorraad
Je je wapen aan iemand geeft
