### ISSUE TITLE
[FEATURE]: Recoil op motoren verhogen

### ISSUE THREAD

**Issue by TDALarry** [Tedeapolis/development#2160]
### Contact Details

cazorla.

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Het is momenteel erg overpowered om vanaf de motor te schieten. Er worden snel bandjes lek geschoten en mensen vermoord vanaf de motor. Er valt hier niks tegen de doen. Met veel meer recoil is het lastiger om raak te schieten. 

### Wat lost deze feature op?

Minder combat vanaf motoren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
GTA being GTA, kan het helaas niet aanzienlijk verhogen.
