### ISSUE TITLE
[FEATURE]: ANWB sollicitatie vragen veranderen op website

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2161]
### Contact Details

destefanokiller

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Vragen voor de sollicitatie website:

Ingame naam
Ingame 06 nummer
e-mail + e-mail bevestigen
Discord naam
Steam naam
Je echte leeftijd
Waarom solliciteer je specifiek voor de ANWB?
Noem 3 goede eigenschappen van jezelf
Noem 3 slechte eigenschappen van jezelf
Op welke manier denk jij jezelf te onderscheiden van de andere?
Wat is jouw ervaring met RolePlay?
Heb je al eerdere ervaring met het ANWB beroep en/of auto mechanica?
Vertel in minimaal 25 woorden wat over jezelf
Hoeveel dagen per week ben je online? (MPC zoals hij nu is)
Hoeveel uur ben je dan online per dag? (MPC zoals hij nu is)
Heb je de afgelopen 3 dagen een andere overheidsbaan gehad? (MPC zoals hij nu is)
Heb je de afgelopen 3 dagen bij een criminele organisatie gezeten? (MPC zoals hij nu is)
GDPR overeenkomst (MPC zoals hij nu is)

Gelieve op deze volgorde, ook krijg ik klachten dat mensen soms alle vakjes moeten aanvinken bij "hoeveel uur ben je dan online per dag?" om de sollicitatie in te dienen, is sinds 5/6 weken vermoed ik.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zet deze even op Niek zijn naam gezien hij als enigste bij de code ervan kan.

**Comment by Tom974** [comment]
Aangepast. Laat me even weten als het niet goed gaat in de mail @DeStefanoKiller
