### ISSUE TITLE
[Bug]: noclip met een voertuig

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2163]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Als je noclipped met een auto en je vliegt voor ongeveer 15 seconden is je voertuig gelijk gedespawned of onzichtbaar en wordt je eruit gegooid. 

### Wat hoorde er te gebeuren?

Het lijkt me dat je in het voertuig blijft tot je er zelf uit gaat i.p.v. eruit gegooid te worden of het voertuig die onzichtbaar wordt.  

### Wat veroorzaakt de bug?

noclippen met een auto.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zie DM
