### ISSUE TITLE
[FEATURE]: eiland voertuigen ook kunnen zien in staff meos

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2165]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Als je in staff meos eiland kentekens opzoekt vind je ze niet. Graag zou ik dit willen zien, voor betere onderzoeken. 

### Wat lost deze feature op?

betere opzoek werk

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zet deze even op Niek zijn naam gezien hij als enigste bij de code ervan kan.

**Comment by niekschoemaker** [comment]
Zit erin
