### ISSUE TITLE
[Bug]: Gevecht met controller vs toetsenbord

### ISSUE THREAD

**Issue by MatteDB** [Tedeapolis/development#2167]
### Contact Details

mattedb

### Wat gebeurde er?

Momenteel kan je met een controller veel sneller slaan en teleporteren dan iemand met een toetsenbord. Dit zorgt voor een oneerlijk voordeel. 

Nu kunnen spelers met een controller door muren teleporteren.

Enkele video's _Rechts is met controller_
https://youtu.be/-tdk3j3_DOc
https://youtu.be/24_aPOCeEpM

### Wat hoorde er te gebeuren?

Je hoort niet te teleporteren of zo snel te slaan

### Wat veroorzaakt de bug?

Controller

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Volgensmij is dit niet te fixen, maar zal eens een kijkje nemen.

**Comment by Tom974** [comment]
Sowieso, als mensen er expres gebruik van maken dan weet je al genoeg :)

**Comment by Tom974** [comment]
Kan er helaas niet zoveel aan doen los van het controller gebruiken blokkeren, maar dat lijkt me ook niet echt de beste oplossing. 

Mocht iemand hier met opzet misbruik van maken dan kunnen we het beter bij straffen houden ipv hier een hele sketch workaround (wat veel tijd kost) voor gaan bedenken. Zoals je ziet in de video aimt hij voor 1 seconde heel erg kort. Als hij gewoon normaal aimde dan was er niks aan de hand.
