### ISSUE TITLE
[FEATURE]: LIJKENZAK

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2169]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Er is bij ons een vraag gekomen of het misschien mogelijk is om de lijkenzak ook als prop te gebruiken.

### Wat lost deze feature op?

De functie is niet verloren. Maar dit zou de RP bij de ambulance bevoderen!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Gaat helaas niet omdat het dan gaat glitchen met het bodybaggen zelf.
