### ISSUE TITLE
Aanpassen boetes in MEOS

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#217]
Samen met de korpsleiding even alle boetes in MEOS besproken. We hebben ze opnieuw gerangschikt, bedragen aangepast, en enkele tekstuele wijzigingen gemaakt. Een paar boetes zijn verwijderd omdat deze niet (langer) gelden, een aantal zijn juist toegevoegd omdat ze ontbraken.

Zo ik begreep van Nick zou hij het nog even met Willem bespreken aan de eettafel.

Onderstaand de nieuwe lijst, in juiste volgorde:

### Verkeers misdrijf

|Feit|Boete bedrag|
|:---|:----:|
| Rijden met rijontzegging 1e keer | €2000,- |
| Zonder rijbewijs rijden | €2000,- |
| Zonder rijbewijs rijden 2e keer | 4000,- |
| Binnen bebouwde kom < 10 KM/H te hard | €80,- |
| Binnen bebouwde kom 10-20 KM/H te hard | €200,- |
| Binnen bebouwde kom 20-30 KM/H te hard | €340,- |
| Binnen bebouwde kom 30-40 KM/H te hard | €500,- |
| Binnen bebouwde kom 40-50 KM/H te hard | €900,- |
| Binnen bebouwde kom 50-60 KM/H te hard | €1200,- |
| Buiten bebouwde kom < 10 KM/H te hard | €75,- |
| Buiten bebouwde kom 10-20 KM/H te hard | €190,- |
| Buiten bebouwde kom 20-30 KM/H te hard | €330,- |
| Buiten bebouwde kom 30-40 KM/H te hard | €450,- |
| Buiten bebouwde kom 40-50 KM/H te hard | €600,- |
| Buiten bebouwde kom 50-60 KM/H te hard | €900,- |
| Door rood licht rijden met een fiets | €95,- |
| Door rood licht rijden met een bromfiets | €160,- |
| Door rood licht rijden | €240,- |
| Verkeerde voertuig informatie doorgeven | €90,- |
| Onnodig claxoneren | €95,- |
| Joyriding | €850,- |
| Rijden onder invloed | €3000,- |
| Illegaal off road rijden | €140,- |
| Door rijden bij een stop bord | €140,- |
| Illegaal inhalen over een vluchtstrook | €380,- |
| U-turn | €140,- |
| Over een doorgetrokken streep rijden | €240,- |
| Onnodig linksrijden | €140,- |
| Spookrijden | €620,- |
| Stil staan met je auto waar dat niet mag | €140,- |
| Hinder zonder ongeval | €1000,- |
| Verkeersongeval met licht lichamelijk letsel | €2000,- |
| Verkeersongeval met zwaar lichamelijk letsel | €5000,- |
| Dodelijk verkeersongeval | €8000,- |
| Doorrijden na een ongeluk | €5000,- |
| Overtreding van WOK status | €400,- |
| Verboden voertuig openbare weg | €1100,- |
| Negeren van stopteken | €1200,- |
| Fout parkeren | €1500,- |
| Roekeloos Rijgedrag | €1500,- |
| Voertuig rijden met een wok status | €1500,- |
| Weg blokkeren | €240,- |
| Verkeersovertreding niet nader gespecificeerd | €430,- |

### Klein misdrijf

|Feit|Boete bedrag|
|:---|:---:|
| Openbare dronkenschap | €120,- |
| Rechtsdoorgang beletten | €130,- |
| Onbevoegd begeven op privé terrein | €180,- |
| Dragen van gezichtsbedekkende kledij | €200,- |
| Beledigen van een ambtenaar in functie | €600,- |
| Verstoring Openbare orde | €220,- |
| Valse informatie geven | €250,- |
| Valse melding | €450,- |
| In het bezit zijn van inbrekers gereedschap | €2500,- |
| Poging tot diefstal | €1400,- |
| Diefstal | €2000,- |
| Poging tot omkopen | €1500,- |
| Rijden met rijontzegging 2e keer | €4000,- |
| Rijden met rijontzegging 3e keer | €6000,- |

### Middelmatig misdrijf

|Feit|Boete bedrag|
|:---|:---:|
| Bedreiging | €3000,- |
| Bedreiging overheidsmedewerker | €4000,- |
| Afpersing / Chantage | €7500,- |
| Verduistering | €5000,- |
| Fraude / Heling | €2000,- |
| Buiten dienst wapen dragen | €10000,- |
| Een auto stelen | €5600,- |
| Identiteitsfraude | €2000,- |
| Ontvoering/gijzeling van een burger | €10000,- |
| Ontvoering van een overheidsmedewerker | €13000,- |
| In het bezit zijn van een illegaal vuurwapen Cat. 1 | €10000,- |
| In het bezit zijn van een illegaal vuurwapen Cat. 2 | €20000,- |
| In het bezit zijn van een nepwapen of holster | €5000,- |
| In het bezit zijn van taser | €5000,- |
| In het bezit zijn van een slag/steekwapen | €5000,- |
| Deelname aan een criminele organisatie | €3000,- |

### Grootmisdrijf

|Feit|Boete bedrag|
|:--|:---:|
| Eenvoudige mishandeling | €5000,- |
| Zware mishandeling | €10000,- |
| Eenvoudige mishandeling overheidsmedewerker | €6600,- |
| Zware mishandeling overheidsmedewerker | €13300,- |
| Poging tot doodslag | €10000,- |
| Poging tot doodslag overheidsmedewerker | €13300,- |
| Doodslag | €15000,- |
| Doodslag overheidsmedewerker | €20000,- |
| Poging tot moord | €14400,- |
| Poging tot moord op een overheidsmedewerker | €19150,- |
| Moord | €20000,- |
| Moord op een overheidsmedewerker | €26600,- |
| Overval | €20000,- |
| Witwassen | €15000,- |
| Zonder Vliegbrevet vliegen | €75000,- |

**Comment by Willem-Dekker** [comment]
Ik ben ze nu in het systeem aan het zetten binnen de stad daarna moet het nog naar meos, alleen weet ik niet waar die staan dus daar moet naar gekeken worden.

**Comment by Willem-Dekker** [comment]
aangepast en gemerged
