### ISSUE TITLE
[FEATURE]: ANPR Systeem in politie voertuigen

### ISSUE THREAD

**Issue by Lorenzo3001** [Tedeapolis/development#2170]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Het toevoegen van een ANPR systeem in bepaalde politie voertuigen. 
De bedoeling is dat dit dan enkel op de SIV gebruikt zal worden (pa62020 & pa62020s), de overige politie voertuigen moeten deze informatie dus niet te zien krijgen. Bij het flitsen van een persoon doormiddel van de radar zal er naast de snelheid en het kenteken van het voertuig ook worden weergegeven of dit voertuig op dat moment een WOK status heeft of op gestolen staat. Een voorbeeld van hoe dit zou kunnen: 
![image](https://github.com/Tedeapolis/development/assets/93911282/cd087b39-cbf8-4000-ac13-36550085aca7)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Staat nog even op de testserver om te testen

**Comment by Tom974** [comment]
Done, commit staat op testserver voor als je het op de main wilt.
