### ISSUE TITLE
[FEATURE]: Rang Aanpassing ESB

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2171]
### Contact Details

dyon. & bennieb.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In overleg met ESB wil ik wat veranderingen aan de rangen van ESB aanvragen.

Hier onder komt een lijst met rangen, en welke rechten ze moeten krijgen.

**Young Thug:** 
Bevoegdheden: /RS
Voertuigopslag: Nee
Wapenopslag: Nee
Baas Menu: Nee

**Thug:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel
Baas Menu: Geld Storten

**Hustler:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen
Baas Menu: Geld Storten

**Runner:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen
Baas Menu: Geld Storten

**Young Street Gangster:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen
Baas Menu: Geld Storten

**Street Gangster:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen, Wapens Modificeren
Baas Menu: Geld Storten

**Big Street Gangster:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen, Wapens Modificeren
Baas Menu: Geld Storten

**Street Soldier:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen, Wapens Modificeren
Baas Menu: Geld Storten

**Street General:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen, Wapens Modificeren, Wapen Winkel
Baas Menu: Geld Storten

**Young Shotcaller:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen, Wapens Modificeren, Wapen Winkel
Baas Menu: Geld Storten, Geld Opnemen, Personeelsbeheer, Salarisbeheer

**Shotcaller:**
Bevoegdheden: F6
Voertuigopslag: Ja
Wapenopslag: Inleggen, Item Winkel, Uitnemen, Wapen Hernoemen, Wapens Modificeren, Wapen Winkel
Baas Menu: Geld Storten, Geld Opnemen, Personeelsbeheer, Salarisbeheer

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Gelieve even op te schrijven wat er precies veranderd moet worden, dus wat er veranderd moet worden bij welke rang en niet wat de rang nu heeft. Anders is het nogal onduidelijk voor mij en ik ga niet alles nalopen.

**Comment by BennieBarkie** [comment]
Wat hierboven staat zijn de nieuwe rangen + permissies wat ze moeten worden.

Maar ik zal hieronder de veranderingen nog eens toelichten:

**VERWIJDEREN:**

**Rang:** Recruit

**NIEUWE HIERARCHY:**

Young Thug
Thug
Hustler
Runner
Young Street Gangster
Street Gangster
Big Street Gangster
Street Soldier
Street General
Young Shotcaller
Shotcaller


**RANG TOEVOEGEN:**

**Nieuwe Rang:** Young Thug 
**Permissies:** _/RS + Sleutels_

**Nieuwe Rang:** Thug
**Permissies:** _F6 + Sleutels + Item Winkel + Voertuigopslag + Wapenopslag (Alleen inleggen) + Baasmenu: Geld storten_

**Nieuwe Rang:** Hustler
**Permissies:** _F6 + Sleutels + Item Winkel +  Voertuigopslag + Wapenopslag (inleggen en Uitnemen) + Wapen hernoemen + Baasmenu: Geld storten_

**RANG AANPASSEN:**

**Street Gangster:** Wapen modificeren
**Big Street Gangster:** Wapen modificeren
**Street Soldier:** Wapen Modificeren

Ik hoop dat dit voldoende is! :)
