### ISSUE TITLE
[Bug]: BSB rangen heeft geen volledige toegang tot de BOT outfit

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2172]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Je hoort de volledige BOT outfit aan te kunnen doen. 
https://cdn.discordapp.com/attachments/1017422277178032129/1124369369032560650/image.png

### Wat hoorde er te gebeuren?

Je hoort de volledige BOT outfit aan te kunnen doen. 

### Wat veroorzaakt de bug?

geen idee.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
stomme eup ook

**Comment by CalRayy** [comment]
> stomme eup ook

Ja echt irritant hé 😳😂

**Comment by DevvTDA** [comment]
@CalRayy Als ik zo zie in de .lua waar eup in staat valt het onder categorie isBot, idk wie die gemaakt heeft maar die doet het niet hjet been holster wat je wel ziet staan staat onder isDsi dus ik kan ze eventueel daar onder zetten maar dan ziet de dsi hem ook. idk of dat een probleem is?

**Comment by DevvTDA** [comment]
ahh nvm ik zie het probleem denk ik al, er staat police_esx maar valt onder job kmar

**Comment by CalRayy** [comment]
Ja de DSI (BSB) rangen mogen de BOT Outfit ook zien, mensen die DJI hebben moeten het ook zien namelijk. Ik weet niet als dat kan, hopelijk wel 😅. De DJI werkt, maar de DSI (BSB) rang niet.

**Comment by DevvTDA** [comment]
Heb nu de names veranderd in de console, hopelijk fixed dit het. even in de gaten houden dus :) zo niet stuur me even eeen DM
