### ISSUE TITLE
[FEATURE]: ANWB inwerking hesje

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2173]
### Contact Details

destefanokiller

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

- [ ] Graag zal ik een "inwerking" hesje willen krijgen bij de ANWB, het liefst in de kleur oranje zodat die een beetje onderscheid heeft van onze andere hesjes. 

Foto van onze huidige hesje: 
![image](https://github.com/Tedeapolis/development/assets/68514420/137f350e-bcca-4d26-931e-678bd1f8554c)
![image](https://github.com/Tedeapolis/development/assets/68514420/40968948-d7bb-4790-a5a8-f3c488c01c51)

### Wat lost deze feature op?

Als het inwerking hesje erin komt dan kan iedereen zien of er een inwerking wordt gedaan door de personen die dat hesje dragen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Toegevoegd, moet enkel nog gepushed worden naar de main. jullie eup zal hierna ook in categorieën staan. :)
