### ISSUE TITLE
[Bug]: Agenten krijgen uitdienst bankoverval melding

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#2174]
### Contact Details

Tom974

### Wat gebeurde er?

Kreeg vandaag te horen dat agenten uitdienst alsnog bankoverval meldingen ontvangen, kleine note to self, moet hier even naar kijken.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
Als op de dag zelf de overval is gedaan en je komt net de stad in (terwijl de overval een uur geleden is gedaan) krijg je ook de melding.

**Comment by Tom974** [comment]
> Als op de dag zelf de overval is gedaan en je komt net de stad in (terwijl de overval een uur geleden is gedaan) krijg je ook de melding.

Dat gaat over de heist toch ? want dat staat hier los van

**Comment by CalRayy** [comment]
> > Als op de dag zelf de overval is gedaan en je komt net de stad in (terwijl de overval een uur geleden is gedaan) krijg je ook de melding.
> 
> 
> 
> Dat gaat over de heist toch ? want dat staat hier los van

Ja de heist inderdaad.
