### ISSUE TITLE
[FEATURE]: Kleding cirkel Karmellos huis Grapeseed

### ISSUE THREAD

**Issue by OwenFufu** [Tedeapolis/development#2175]
### Contact Details

miguelitoooo

### Goedgekeurd door

Navraag staff overleg.

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij een kledingcirkel bij onze boerderij in Grapeseed, dit omdat het huis momenteel niet veel toevoegd naast de RP die we in de kelder kunnen doen.

Als wij nu bijvoorbeeld iemand aannemen of ontvoeren moeten we al in de stad gepaste kleding aan doen en het zou wel handig zijn als dit in het huis zelf ook kan. 

### Wat lost deze feature op?

Voegt meer mogelijkheden toe!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Wat was er uit het staffoverleg gekomen @OwenFufu ?

Moet dit doorgepushed of?

**Comment by OwenFufu** [comment]
> 

Was nog niet besproken tijdens het staffoverleg.

**Comment by DevvTDA** [comment]
@Tom974 Goedgekeurd dus kan erin gezet worden. @OwenFufu stuur coords waar hij moet komen aub.,

**Comment by TDASammie** [comment]
@Tom974 

Hier mag de cirkel komen. 

![image](https://github.com/Tedeapolis/development/assets/128930588/fef15cbd-64f3-4835-8c8a-40019596fa5e)

**Comment by Tom974** [comment]
Top, zit er in na de herstart!

> @Tom974
> 
> Hier mag de cirkel komen.
> 
> ![image](https://user-images.githubusercontent.com/128930588/254583944-fef15cbd-64f3-4835-8c8a-40019596fa5e.png)
