### ISSUE TITLE
[EUP]: Nieuw kogelwerend vest voor justitie

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#2176]
### Contact Details

yohandessu

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag voor justitie willen wij een kogelwerend vest. Dit is handig voor huiszoekingen aangezien we daar momenteel rond lopen in onze dienstkleding. Er lopen mensen met grote wapens rond, er is gewoon een groot risico. 

Graag zien we de aanpassing voor:
Kogelvrij vest 1 <62> 
Dit is momenteel MEDIA, deze moet dus ook gewoon blijven. 

Graag willen we dan ook dit vest in ons EUP hebben. 
job justitie

![image](https://github.com/Tedeapolis/development/assets/121113817/0e2a8661-2e43-4c3e-8eca-1b66cd82e81d)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Wiebren-3** [comment]
Is misschien ook wel handig dat BOT deze net zoals bij de ambu d.m.v /patient (ID) zo een vest bij mensen kunnen aantrekken, iets voor het staffoverleg..

**Comment by JustitieTDA** [comment]
@Wiebren-3 Deze vesten zijn bedoeld voor advocaten/KvK medewerkers die bij een huiszoeking of gevaarlijke situatie komen. Niet perse voor normale burgers. Daarom ook alleen in de /eup  voor onze advocaten.

**Comment by DevvTDA** [comment]
@JustitieTDA  Ik heb het volgende gemaakt, staat klaar om in de server gezet te worden :) 

![Image](https://github.com/Tedeapolis/development/assets/79802852/e171635b-5f23-41cd-8851-e73e0df9095b)


![Image](https://github.com/Tedeapolis/development/assets/79802852/946e129c-a0d5-4342-89ba-dce59a207de8)

**Comment by JustitieTDA** [comment]
Top dankjewel!
