### ISSUE TITLE
[FEATURE]: TAXI - Salaris aanpassingen 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#2178]
### Contact Details

Timez#0003

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Na overleg binnen Uberpolis zouden wij graag een kleine aanpassing willen in de volgende lonen van Taxi, dit omdat wij van mening waren dat deze in vergelijking met andere overheden aan de lage kant waren. 

Het geld van taxi word door ons zelf verdiend, en onze pot word NIET bijgevuld door staff. Alle rangen hebben een aangepast salaris op Baas na, dit omdat deze naar onze mening voor nu goed is.

Hierbij al het aangepaste salaris:

[/setjob ID taxi 1000] Uberpolis - Baas: 1700
[/setjob ID taxi 970] Uberpolis - Chef: 1600
[/setjob ID taxi 950] Uberpolis - Manager: 1450
[/setjob ID taxi 900] Uberpolis - Recruiter: 1150
[/setjob ID taxi 850] Uberpolis - Marketing: 1150
[/setjob ID taxi 800] Uberpolis - Uber-1: 1000
[/setjob ID taxi 750] Uberpolis - Uber-2: 900
[/setjob ID taxi 700] Uberpolis - Uber-3: 990
[/setjob ID taxi 650] Uberpolis - Uber-4: 980
[/setjob ID taxi 600] Uberpolis - Uber-5: 970
[/setjob ID taxi 550] Uberpolis - Taxichauffeur-1: 780
[/setjob ID taxi 500] Uberpolis - Taxichauffeur-2:750
[/setjob ID taxi 450] Uberpolis - Taxichauffeur-3: 730
[/setjob ID taxi 400] Uberpolis - Taxichauffeur-4: 720
[/setjob ID taxi 350] Uberpolis - Taxichauffeur-5: 700
[/setjob ID taxi 300] Uberpolis - Regiotaxi-1: 680
[/setjob ID taxi 250] Uberpolis - Regiotaxi-2: 650
[/setjob ID taxi 200] Uberpolis - Regiotaxi-3: 630
[/setjob ID taxi 100] Uberpolis - Regiotaxi-4: 620
[/setjob ID taxi 0] Uberpolis - Uitzendkracht: 600

Uitdienst Salaris:
[/setjob ID offtaxi 1000] Uberpolis - Baas: 1600
[/setjob ID offtaxi 970] Uberpolis - Chef: 1400
[/setjob ID offtaxi 950] Uberpolis - Manager: 1150
[/setjob ID offtaxi 900] Uberpolis - Recruiter: 650
[/setjob ID offtaxi 850] Uberpolis - Marketing: 650
[/setjob ID offtaxi 800] Uberpolis - Uber-1: 500
[/setjob ID offtaxi 750] Uberpolis - Uber-2: 480
[/setjob ID offtaxi 700] Uberpolis - Uber-3: 450
[/setjob ID offtaxi 650] Uberpolis - Uber-4: 430
[/setjob ID offtaxi 600] Uberpolis - Uber-5: 400
[/setjob ID offtaxi 550] Uberpolis - Taxichauffeur-1: 360
[/setjob ID offtaxi 500] Uberpolis - Taxichauffeur-2: 350
[/setjob ID offtaxi 450] Uberpolis - Taxichauffeur-3: 340
[/setjob ID offtaxi 400] Uberpolis - Taxichauffeur-4: 330
[/setjob ID offtaxi 350] Uberpolis - Taxichauffeur-5: 320
[/setjob ID offtaxi 300] Uberpolis - Regiotaxi-1: 280
[/setjob ID offtaxi 250] Uberpolis - Regiotaxi-2: 260
[/setjob ID offtaxi 200] Uberpolis - Regiotaxi-3: 240
[/setjob ID offtaxi 100] Uberpolis - Regiotaxi-4: 220
[/setjob ID offtaxi 0] Uberpolis - Uitzendkracht: 200

### Wat lost deze feature op?

Dit zal het salaris een klein tikje omhoog duwen wat voor onze geweldige chauffeurs natuurlijk onwijs leuk nieuws is. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
yes, zit erin na a.s. herstart!
