### ISSUE TITLE
[FEATURE]: Pot log JUSTITIE

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#2179]
### Contact Details

yohandessu_

### Goedgekeurd door

Johan

### Beschrijf zo duidelijk mogelijk de feature

Wij van justitie leiding willen graag een justitie pot log. Ik heb dit nagevraagd aan HS, zij gaven aan dat ik even een github aan moest maken hiervoor. Deze log moet bijhouden wie geld uit de pot pakt en de reden er achter. En deze logger moet in onze ministerie discord komen. 

Het kanaal waar de log in moet komen is: 1126566394180415488 

Bedankt alvast! 

### Wat lost deze feature op?

Zo kunnen staatssecretarissen en ministers actief in de gaten houden waarom iets uit de pot gehaald word. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zit er in na de herstart
