### ISSUE TITLE
[BURGERRAAD]: Wijziging Opslagloodsen

### ISSUE THREAD

**Issue by Toro-Carri** [Tedeapolis/development#2181]
### Contact Details

Toro#5710

### Goedgekeurd door

Burgerraad

### Beschrijf zo duidelijk mogelijk de feature

Momenteel worden de opslagloodsen minimaal gebruikt. Vooral de functie '_wapenopslag_' zou de nodige veranderingen nodig hebben. Het opslaan van wapens is te duur en er kunnen (te) weinig wapens in worden weggestopt.

**Wapenopslag** (4.500.000 euro)
Level 1: 4 Wapens (Stock)
Level 2 (750.000 euro): 7 Wapens (+3)
Level 3 (1.000.000 euro): 10 Wapens (+3)
Level 4 (1.250.000 euro): 13 Wapens (+3)
Level 5 (1.500.000 euro): 16 Wapens (+3) 

Op deze manier zal de functie meer worden gebruikt. In totaal zal je voor (aanschafwaarde + tune kosten) een klein aantal wapens kunnen opslaan. Er zal geld voor worden uitgegeven en dit komt ten goede van de economie. Hierdoor zal de functionaliteit van de loodsen verbeteren.

_Besproken en goedgekeurd in burgerraad :D_

### Wat lost deze feature op?

Het gebruiken van opslagloodsen, geld uit de economie.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik zal het er eens met Niek over hebben

**Comment by Tom974** [comment]
Zit erin na de herstart. (prijzen blijven wel hetzelfde)
