### ISSUE TITLE
[Bug]: /setjob werkt niet op uitdienst job

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#2182]
### Contact Details

dead123x5

### Wat gebeurde er?

Sinds kort kunnen we op de " offred 900 " geen /setjob of setjob2 meer doen. Dat is de uitdienst manager rang (UitdienstR3D - Manager) Deze kon dat voorheen wel en moet dat dus ook kunnen.

### Wat hoorde er te gebeuren?

De rang offred 900 zou ook de rechten moeten hebben om /setjob of /setjob2 voor alle rangen van red en offred te kunnen doen.

### Wat veroorzaakt de bug?

Een tijdje geleden is kon het opeens niet meer geen idee hoe het komt.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Gek, de jobs bestaan nog wel. Krijg je te zien dat deze rang niet bestaat of ?

**Comment by Tom974** [comment]
![image](https://github.com/Tedeapolis/development/assets/55812394/ae3a5230-70ae-420f-9a67-2dfc4d1b723d)
Heb het net even getest, en bij mij werkt het prima 🤔 

@Rowdeeee

**Comment by Tom974** [comment]
Excuus, ik kan niet lezen 🤦Zal gefixt zijn na de restart!
