### ISSUE TITLE
[FEATURE]: /removelightbar toevoegen

### ISSUE THREAD

**Issue by Kenjikuhh** [Tedeapolis/development#2183]
### Contact Details

kenjikuhh

### Goedgekeurd door

DSI leiding / warturtle_

### Beschrijf zo duidelijk mogelijk de feature

Het command /removelightbar toevoegen. Met deze command zullen de lightbars van je auto verdwijnen. Wat je nu moet doen is /lightbar intypen en dan opent er een menutje en vervolgens op de knop "Verwijder lampen" drukken. 

Door de voorgesteld command zou dit veel makkelijker zijn en hoef je niet altijd in dat menu.

### Wat lost deze feature op?

Het lost wat ongemak op en het kost je minder moeite om ze weg te halen. Tevens kan je de command ook keybinden en hoef je enkel maar 1 knop te drukken en dan zijn de lightbars weg.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Heb het toegevoegd, test het zelf eventjes en laat mij weten als het niet werkt :^)
