### ISSUE TITLE
[FEATURE]: Nieuwe custom tattoos 

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2184]
### Contact Details

Arjen#0001

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Nieuwe custom tattoos toevoegen:
https://www.gta5-mods.com/player/franklin-s-rap-legend-body-tattoo-s
https://www.gta5-mods.com/player/sureno-gang-tattoos-mp-male
https://www.gta5-mods.com/player/compton-polynesian-gangster-tatoos-ped

### Wat lost deze feature op?

Extra roleplay mogelijkheden voor gangs.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
@ARJ3N Heb dit ook al besproken om een nieuwe script toe te voegen, momenteel heeft kenneth altijd de tattoo's gedan en het is nergens te vinden waar of hoe of via wat hij dit deed. daarom dat ik van mening ben om een nieuw concept erin te zetten. ik zal het nogmaals aankaarten.
