### ISSUE TITLE
[FEATURE]: Verplaatsen Garage Exotica

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2185]
### Contact Details

dyon.

### Goedgekeurd door

N.V.T.

## Garage verplaatsing Exotica
De garages bij Exotica zijn een beetje vervelend geplaatst waardoor er tijdens events veel ongelukken gebeuren. Ik zou daarom graag de garages verplaatst hebben naar de volgende plekken: 

## Groene Cirkel: 
![image](https://github.com/Tedeapolis/development/assets/120292087/5726808f-37cd-4adf-95aa-e964a944a97f)

## Rode Cirkel:
![image](https://github.com/Tedeapolis/development/assets/120292087/18de2d86-5d8b-4e43-8f9a-303d0a7264de)

## Voertuig Spawnplekken:
![spawnplekken](https://github.com/Tedeapolis/development/assets/120292087/90c5b324-a610-4d19-9365-173565b38035)

### Wat lost deze feature op?

De vele ongelukken + chaos die er is tijdens events

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Is dit ook goedgekeurd door Ali @ExoticaTDA ?

**Comment by Dyon033** [comment]
> Is dit ook goedgekeurd door Ali @ExoticaTDA ?

Is iets wat Ali en ik een tijd terug al besproken hadden

**Comment by ExoticaTDA** [comment]
> Is dit ook goedgekeurd door Ali @ExoticaTDA ?

Is iets wat Ali en ik een tijd terug al besproken hadden
