### ISSUE TITLE
[FEATURE]:  Mensen kunnen ontslaan Soprano's Taco's

### ISSUE THREAD

**Issue by JaylinFerluci** [Tedeapolis/development#2187]
### Contact Details

Jaylin Ferluci#5959

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Ik zou graag bij de Soprano's Taco's een ontslag menu willen hebben voor de 1ste en 2de job. Want er zijn mensen die zich niet meer laten horen en het zou dan fijn zijn om ze zelf te kunnen ontslaan.

Van Callray mocht ik deze github aanmaken

Dit zou dan alleen geldig moeten zijn met de rang Taco Baas  /setjob sopranotaco boss

Het Zou ,mogelijk kunnen op deze locatie zie foto
![image](https://github.com/Tedeapolis/development/assets/121064556/b610f2d9-b29b-4d0c-9a7b-a7b6f50c56ec)

### Wat lost deze feature op?

Mensen die een loop je met je nemen voor de rang omdat je meer krijgt dan die standaard 100 euro per 10 minuten

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Gezien ik enorm weinig vanuit sopranos tacos qua activiteiten zie ga iki dit helaas afkeuren. je zult het dus via report nog moeten doen
