### ISSUE TITLE
[EUP]: Hesjes Opco-g

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2188]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Nu we met politie en Kmar in porto 110 zitten is het handig als de Opco's een hesje krijgen met OPCO-G zo weet de politie en Kmar ook dat zei opco zijn als we bij dingen aanwezig moeten zijn. Zou dit mogelijk zijn? het mag ook voor de OVD-G. Maar denk dat het daar niet voor nodig is aangezien we als OVD-G in groene pakjes lopen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
wat voor hesje zat je te denken? want ik heb geen ruimte meer voor de reflecterende hesjes @WilmaWonka1985

**Comment by WilmaWonka1985** [comment]
@dev

> wat voor hesje zat je te denken? want ik heb geen ruimte meer voor de leidende hesjes@WilmaWonka1985

gewoon zo'n groen of geel hesje. die we over de kleding kunnen doen van de Opco. Want de opco heeft nu helemaal niets herkenbaars namelijk.

**Comment by DevvTDA** [comment]
Heb even gekeken en lijkt me geen noodzakelijk iets en zie dus eigenlijk ook geen reden om dit erin te zetten. zal hierbij dus ook de github sluiten
