### ISSUE TITLE
[FEATURE]: Ambu Amarok

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2189]
### Contact Details

Wilma Wonka#4312

### Voertuig model

Amarok

### Omschrijf de bug

Nou ik weet niet echt of dit een bug is. 
Maar ik hoor de laatste tijd heel vaak van de collega's dat de Amarok veel en veel te snel stuk gaan. Oranje lampje na een kleine stoot op een stoeprandje of bosjes of verkeersbord.

Is er een mogelijkheid dat er naar gekeken kan worden waarom dat voertuig zo snel oranje knipperd?

### Normaal gedrag

Je hoeft niet bij elke klein ding bijvoorbeeld: stoeprand of drempel een geel lampje te krijgen voor de Amarok

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Lorenzo3001** [comment]
Heb de damage gelijk gezet aan andere voertuigen. Hij ging inderdaad iets sneller kapot dan normaal. Zal ergens deze dagen worden doorgevoerd.

**Comment by WilmaWonka1985** [comment]
Dank je wel
