### ISSUE TITLE
[Bug]: 100$ bill in MLO CCF

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#2190]
### Contact Details

epicdonny

### Wat gebeurde er?

op een dag verscheen er een goude staand 100$ bill in de martelkamer van CCF

### Wat hoorde er te gebeuren?

Geen 100$ bill 

### Wat veroorzaakt de bug?

zie video

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

https://github.com/Tedeapolis/development/assets/120605155/86b00044-b8fd-459b-a395-482bb8cd031f

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@CalRayy Zou jij hiernaar kunnen kijken of dit door kunnen communiceren met iemand die hier naar kan kijken :D?

**Comment by CalRayy** [comment]
Fixed
