### ISSUE TITLE
[FEATURE]: "Stel GPS in" functie toevoegen aan drugsmeldingen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2191]
### Contact Details

driemaalsmedes

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Als de marechaussee een drugsmelding ontvangt dan komt deze op de map te staan met een paarse cirkel en er wordt automatisch een melding in de kmar meldkamer gemaakt. Op deze melding zit echter geen "Stel GPS in" functie. Aangezien de paarse cirkel op de map vrij snel weggaat kan het zijn dat er een drugsmelding gemist wordt aangezien je niet altijd in staat bent om meteen je map te openen. Om dit te verhelpen zouden wij graag een functie willen om de locatie van de drugsmelding in te stellen op onze GPS, zoals ook kan bij normale meldingen die wij via de meldkamer binnen krijgen. 

### Wat lost deze feature op?

De feature voorkomt dat wij een drugsmelding missen omdat wij niet altijd in staat zijn om meteen op onze map de locatie van de drugsmelding te achterhalen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dit is expres op deze manier gedaan zodat de meldingen niet te overpowered zouden worden. Voorheen is het ook altijd alleen een blip op de map geweest en toen is er gevraagd om hier een melding van te maken zodat dit voor de OVD makkelijk te verdelen was onder de eenheden.

Dus om deze reden ga ik geen functie toevoegen waarbij je de gps naar de melding kan zetten. De melding is puur zodat de OVD mensen kan aansturen.
