### ISSUE TITLE
[Bug]: Flitspalen flitsen niet meer

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2192]
### Contact Details

Arjen#0001

### Wat gebeurde er?

Flitpalen geven geen flits meer af.

### Wat hoorde er te gebeuren?

Ze horen een visuele flits te geven.

### Wat veroorzaakt de bug?

Rij langs een flitser.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Fixed, best wel dikke improvement overheen gegooid met Niek
