### ISSUE TITLE
[FEATURE]: Juwelier vereisten aanpassen

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#2194]
### Contact Details

Arjen#0001

### Goedgekeurd door

Staff

### Beschrijf zo duidelijk mogelijk de feature

Minimale vereisten om juwelier te kunnen overvallen veranderen naar boven de 5 agenten en het huidige tijdslot verwijderen.

### Wat lost deze feature op?

Ben je niet meer tijdsgebonden. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
