### ISSUE TITLE
[FEATURE]: KMar Huisinbraakmeldingen 

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#2196]
### Contact Details

Streamcentral

### Goedgekeurd door

KMar & Politie

### Beschrijf zo duidelijk mogelijk de feature

Momenteel heeft de Politie al huisinbraakmeldingen en deze willen we voor de Marechaussee ook.

### Wat lost deze feature op?

Momenteel zijn er ook in Paleto inbraken waardoor de criminele meestal vrijspel hebben gezien de Politie voornamelijk in de stad rijd. Door dit ook bij de KMar toe te voegen die voornamelijk in het noorden rijd creeer je meer risico voor de criminele en word Paleto weer een beetje veilig.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Had ik al toegevoegd

**Comment by ARJ3N** [comment]
Dit was eigenlijk voorheen opzettelijk niet toegevoegd @Tom974

**Comment by Streamcentralrulez** [comment]
> Dit was eigenlijk voorheen opzettelijk niet toegevoegd @Tom974

Door wie precies niet dan? Want vandaag hebben we dit verzoek vanuit KL gekregen.
