### ISSUE TITLE
[FEATURE]: OVA toegang tot kluis en werknemerslijst

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#2198]
### Contact Details

yohandessu

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Hey! Graag willen wij wat aanpassingen aan de rang OVA van justitie. Momenteel hebben zij nog geen toegang tot rollen geven en kluis toegang. Dit willen wij dus graag aangepast hebben

Perms die aangepast moeten worden:
- Toegang tot geld opnemen in de kluis
- Toegang tot /onduty command
- Toegang tot /setjob justitie 
- Toegang tot de werknemerlijst

Job: justitie 60

### Wat lost deze feature op?

Toegang tot extra dingen die nodig zijn als leiding 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zit erin na de herstart
