### ISSUE TITLE
[FEATURE]: Langzaam doodbloeden na dat je bent geraakt door een kogel

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#2199]
### Contact Details

[TDA] Johnny Flodder#3559

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

bandages toevoegen om extra minuten toe te voegen. Rond de 10-15 minuten tijd heb je standaard maar dit kan verlengd worden door de bandages. Bandages 5 min. Dit kan je kopen in de shop in het ziekenhuis en dit zou 1.000,- kosten per stuk. Je kan er maar 2 kort na elkaar gebruiken waardoor je dus een 10 minuten erbij zou kunnen krijgen. Dit ook toevoegen bij de Politie en Kmar shop.

### Wat lost deze feature op?

Spreekt voor zich 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Ehhhh, ik neem aan dat dit nog verder uitgewerkt moet worden?

Want zoals de issue nu omschreven staat is het "Je bent geraakt dus ben je gegarandeerd dood tenzij je naar het ziekenhuis gaat" alsin, moet hier niet meer aan zitten als kansen om te bloeden, kansen dat het bloeden stopt na een periode etc?

**Comment by iHax0rMC** [comment]
We gaan deze issue in de komende Burgerraad meenemen.

**Comment by Tom974** [comment]
resource bestaat niet meer, moest dit nog gedaan worden?

**Comment by iHax0rMC** [comment]
![image](https://github.com/user-attachments/assets/c6f98d13-e2be-4e37-a984-ad068767fa3a)
https://ptb.discord.com/channels/1232813900626395238/1232814170819395634/1267571231763202079

**Comment by Tom974** [comment]
wat de, hij heeft mn comment onder de verkeerde github issue gezet lmao

**Comment by iHax0rMC** [comment]
> wat de, hij heeft mn comment onder de verkeerde github issue gezet lmao

Dat doe je zelf

**Comment by Tom974** [comment]
Ik heb het bloeden nu zo aangepast zoals in de screenshot hierboven, behalve het stacken & het effect (soort van crasheffect zegmaar) van het bloeden, dat laten we nog maar even gezien is gebleken dat dit wel heel heftig wordt nu het er pas net in zit.

Verband (bandages) is nu ook te koop op eiland voor 1000 eur

**Comment by Tom974** [comment]
Oh en ik heb ook een onderwereld ziekenhuis toegevoegd op mainland waar je dus bandages kunt kopen en een behandeling kunt nemen, zodat je niet geforceerd naar ziekenhuis moet waar de politie je staat op te wachten
