### ISSUE TITLE
Geen zulu nemen

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#22]
Een agent indienst kan geen helikopter nemen.
De helikopters komen wel in de garage te staan maar vanaf je er 1 probeert te spawnen komt de heli niet.
Dit probleem is in de stad bij het politie kantoor

**Comment by Willem-Dekker** [comment]
zou gefixed moeten zijn na restart

**Comment by Willem-Dekker** [comment]
kan je morgen testen

**Comment by ExpensionX** [comment]
Is goed

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Willem Dekker <notifications@github.com>
Verzonden: Friday, July 24, 2020 10:01:04 PM
Aan: Tedeapolis/development <development@noreply.github.com>
CC: ExpensionX <ruben1995moors@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Tedeapolis/development] Geen zulu nemen (#22)


kan je morgen testen
