### ISSUE TITLE
[FEATURE]: Timer toevoegen (zie screenshot)

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2202]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Als je dood bent kan je je radio en telefoon niet gebruiken + vuurwapen. Is het mogelijk om een daadwerkelijke timer toe te voegen zoals je moet nog 2minuten en 50 seconden wachten. Want dan weet je ook gelijk hoe lang je moet wachten. 
![image](https://github.com/Tedeapolis/development/assets/101106299/e12fcf7f-c459-4911-9eed-db137a496fde)
De melding bij de screenshot dus veranderen naar een daadwerkelijke timer. Als dit niet mogelijk is dan helaas.

### Wat lost deze feature op?

Dan weet je hoe lang je moet wachten en kan handig zijn om te weten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Teveel werk in verhouding wat we ervoor terugkrijgen.
