### ISSUE TITLE
[EUP]: Vrouwen DSI kleding

### ISSUE THREAD

**Issue by AaranDejager** [Tedeapolis/development#2203]
### Contact Details

aarantv

### Goedgekeurd door

Devv

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

**Uitdienst Vrouw DSI EUP**
Momenteel missen er een 2 dingentjes in het EUP als uitdienst zijnde. Dit gaat om 2 kleding stukken ( Holster, Kogelvrij noodhulp vest )
![image](https://github.com/Tedeapolis/development/assets/80160287/2a9b9d2a-e538-46db-b4af-ed35840fdcce)
![image](https://github.com/Tedeapolis/development/assets/80160287/e768f6c7-3196-4d68-8c51-71b19a6f118b)

**Indienst Vrouw DSI EUP**
Momenteel mist er 1 belangrijk kleding stuk in het indienst/uitdienst vrouw EUP dit gaat om een motor helm.
![image](https://github.com/Tedeapolis/development/assets/80160287/7f2603c6-efb5-4108-af21-b3a5c4c80dbc)

**Kogel Vrij DSI Vest Vrouw**
Momenteel zit er 1 kogelvrij vest in voor vrouw DSI echter is er een ander vest wat er een stuk beter uit ziet. Het probleem bij deze is dat er momenteel KMAR op staat. Zou het mogelijk zijn dat ze een remodel kan krijgen zodat er DSI / Dienst Speciaal Interventie op staat? En indien mogelijk de taser van de voorkant af.
![image](https://github.com/Tedeapolis/development/assets/80160287/23f1d10a-e6be-4f10-8587-5b145a493bd7)

**Richtlijn**

- Uitdienst EUP Vrouw DSI een nieuw kopje toevoegen met DSI - Accessoires ( Holster, Noodhulp Kogelvrij Vest )
- Indienst EUP Vrouw DSI Onder DSI - Helmen Motor Helm toevoegen
- DSI Kogelvrij vest Vrouw - Indien mogelijk remodel naar DSI vest en toevoegen onder DSI - Vesten
 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Heb alles gecommit en gewijzigd, zal dus toegevoegd zijn als niek het pushed :)
