### ISSUE TITLE
[Bug]: Blauwe tekst van de porto gaat door je menu's heen

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2205]
### Contact Details

CalRay#1513

### Wat gebeurde er?

Normaal ging je menu's zoals F6 altijd links van de blauwe tekst, maar nu gaat door alles heen. Zie screenshot: 
![image](https://github.com/Tedeapolis/development/assets/101106299/b34a6df8-c2be-40d1-8ef0-779bd3aaab03)
Kan dit terug aangepast worden zoals vroeger ? 

### Wat hoorde er te gebeuren?

Normaal hoort de menu's en de blauwe tekst niet door elkaar heen te gaan. 

### Wat veroorzaakt de bug?

Geen idee, 
![image](https://github.com/Tedeapolis/development/assets/101106299/94ffce63-3e3b-459e-8a51-69cfa0107c6b)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Dyon033** [comment]
Dit is al vaker het geval geweest en as far as I know komt dit door een update. Tot zover ik weet is dit altijd een probleem tot de eerstvolgende herstart en daarna is dat automatisch verholpen :)

**Comment by Dyon033** [comment]
Heb ff voor je gekeken en zoals ik al zei is dit na de meest recente herstart automatisch verholpen :)
![image](https://github.com/Tedeapolis/development/assets/120292087/f19baf1c-520d-4ad6-921c-434afc8a8334)
