### ISSUE TITLE
[EUP]: motorpak vrouwen aanpassen

### ISSUE THREAD

**Issue by TommyHuisbaas** [Tedeapolis/development#2207]
### Contact Details

cap_rogers1941

### Goedgekeurd door

devv4532

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

**Nieuw motorpak voor vrouwen**

Als je het motorpak van de vrouwen gaat vergelijken met die van de mannen ziet het er wel slecht uit. Motorpak heeft een gat bij het borst waardoor het er niet realistich uitziet. Daarnaast als je een zwaar vest over het motorpak doet glitched het pak er heel erg doorheen. Misschien een idee om een dichte motorjas toe te voegen waar geen gat zichtbaar is en de jas niet door het zware vest glitched. https://discord.com/channels/876808615749644338/876809793938010172/1136617200053137549

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Het zware vest erdoor heen kan ik helaas niet fixen, heb enkel de armen kunnen fixen zodat het gat weg is.
