### ISSUE TITLE
[FEATURE]: `/wheelchair toevoegen voor de Ambu Teamleiding Ambu Teambaas

### ISSUE THREAD

**Issue by WilmaWonka1985** [Tedeapolis/development#2208]
### Contact Details

Wilma Wonka#4312

### Goedgekeurd door

N.V.T. Nyx Laporta

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden de Teamleiders en de baas de /wheelchair uit dienst willen gebruiken. Want wij kunnen nu geen rolstoelen of brancard opruimen als die zijn blijven staan. Graag zouden wij deze functie als Teamleider of afdelingshoof en Ambulance Baas willen gaan gebruiken.

### Wat lost deze feature op?

Dat de spullen netjes opgeruimd kunnen worden

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
En wat zijn de grades van de rangen waar dat op moet gebeuren?

**Comment by WilmaWonka1985** [comment]
Rang 12 13 en 14 dat zijn de rangen waar we het op zouden willen hebben

**Comment by Tom974** [comment]
Teveel werk om dit aan te passen in vergelijking met wat we ervoor terug krijgen, ik raad je aan om gewoon even in dienst te gaan bij het ziekenhuis.
