### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2209]
### Wat gebeurde er?

Wanneer je recherche en KLU tegelijk bent dan hoor je de recherche rol te krijgen zodat je in de recherche meldkamer kan. Echter werken momenteel nog niet alle KLU functies en die heb ik gesplitst onder de volgende 3 features die ontbreken:
**-1.** Voertuig dealer(politie), je kan geen KLU toestellen aanschaffen (zie foto).
![adfsa](https://github.com/Tedeapolis/development/assets/141491362/51b0ba3b-d12a-4d3a-8958-e7b85d7b9058)

**-2.** Je hebt geen toegang tot politie vliegtuigen (dat is een apart kopje onder voertuigen als je een groene cirkel in gaat voor vliegtuigen, zie foto's).
![adfsaaa](https://github.com/Tedeapolis/development/assets/141491362/683b1e5a-1b7d-4d73-af5b-91347daba6da)
Dat hoort dit te zijn:
![asdgfsa](https://github.com/Tedeapolis/development/assets/141491362/60057d78-25f0-4dd2-a817-503ce57f5fb0)

**-3.** /arm werkt niet
Dit is nodig voor de gewapende vliegtoestellen. Zonder /arm kan je dus ook niet schieten.
 
 -----------------------------------------------------------------------------------------------------------------------------------

**Dit moet gebeuren bij de volgende rollen:**
Recherche Junior (police 16)
Recherche (police 19)
Recherche Senior (police 17)
Recherche Leiding (police 18)

--------------------------------------------------------------------------------------------------------------------------------------

**Momenteel hebben we een tijdelijke workaround voor dit probleem maar dit willen we niet permanent zou houden.
Korpsleiding is op de hoogte van deze issue en heeft deze issue goedgekeurd.**

---------------------------------------------------------------------------------------------------------------------------------------

### Wat hoorde er te gebeuren?

Wanneer je bij de recherche zit hoor je ook acces te hebben tot KLU permissions.

### Wat veroorzaakt de bug?

Recherche en KLU tegelijk zijn bij de politie.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Fixed na de herstart. 

Ik ga er vanuit dat dit ook alleen door KLU leden gebruikt wordt en niet door recherche leden welke geen KLU zijn gezien je wel een aantal helikopters etc erbij krijgt.. Anders haal ik het weer weg.
