### ISSUE TITLE
[EUP]: Recherche outfit

### ISSUE THREAD

**Issue by Zjefvm** [Tedeapolis/development#2211]
### Contact Details

zjef

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De recherche outfit is een beetje kapot, het T-Shirt komt door de jas heen, voorheen was dit geen probleem. Wellicht een ander T-Shirt of dergelijke. Deze outfit valt onder de "Recherche jas" in het EUP menu van de recherche.

https://prnt.sc/HUSLqsctTYQf 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed met nieuwe kleding
