### ISSUE TITLE
[EUP]: Recherche nieuw EUP

### ISSUE THREAD

**Issue by TommyHuisbaas** [Tedeapolis/development#2212]
### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Foto's zijn vastgepinned in ons DM. Voor vragen kun je altijd even DM sturen. We hebben samen even overlegd wat mogelijk was. Ik kijk er erg naar uit!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed
