### ISSUE TITLE
[EUP]: Recherche rangen uitdienst toegang geven tot recherche EUP

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2213]
### Goedgekeurd door

@tomtommer (korpsleiding)

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De recherche wil graag toegang krijgen tot het recherche EUP wanneer ze uitdienst zijn. Dit is besproken met korpsleiding en die zijn het hier ook mee eens. De reden hiervan is dat de recherche altijd herkenbaar moet kunnen zijn indien dit nodig is. Bijvoorbeeld bij het overmeesteren van een verdachte.
Momenteel als je uitdienst staat als recherche zie je dit (mits je staff bent natuurlijk): 
![rechercheding](https://github.com/Tedeapolis/development/assets/141491362/5e4e0a33-7f96-4925-a87e-caf02f6bca72)
Wij zouden graag deze eup erbij willen hebben:
![rechercheding2](https://github.com/Tedeapolis/development/assets/141491362/3f4ac8ba-3192-4806-8e3a-20b181e74ce4)

**Dit moet gebeuren bij de volgende rollen:**
police 16 (recherche junior),
police 17 (recherche senior),
police 18 (recherche leiding),
police 19 (recherche) en
police 1000 (eerste hoofd commesaris)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
uhm, werkt dit niet al? zou het namelijk wel moeten doen

**Comment by Tom974** [comment]
Ah i see, fixed na herstart.

**Comment by NovaGazer3** [comment]
Good service, 5/5 stars
