### ISSUE TITLE
[EUP]: Inwerking Shirt Ambulance

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2214]
### Contact Details

jaak_steifkes

### Goedgekeurd door

Mila

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Indien mogelijk graag een Ambulance T-shirt van ''Inwerking'' toevoegen voor de Ambulance. Dit kan de persoon die de inwerking volgt aantrekken en de trainer die de inwerking geeft, zodat ze herkenbaar zijn en dat mensen wat meer geduld hebben bij meldingen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
welke kleur? @Jaak-Steifkes

**Comment by Jaak-Steifkes** [comment]
> welke kleur? @Jaak-Steifkes

We zaten zelf aan geel te denken, als je zelf een kleur ziet die er mooier op staat mag dat ook natuurlijk

**Comment by DevvTDA** [comment]
Heb het toegevoegd, zal na de restart in de eup moeten zitten :)
