### ISSUE TITLE
[AMBULANCE]: Extra Psychologie rang toevoegen

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2215]
Nieuwe rang genaamd Psychologie Leiding

/setjob {id} ambulance 830 -> Ambulance - Psychologie Leiding -> In dienst salaris 1750 | 
/setjob {id} offambulance 830 -> Ambulance uit dienst - Psychologie Leiding -> 1000 euro uit dienst salaris in verband met gesprekken die uit dienst gevoerd worden.

Is enkel een nieuwe rang toevoegen met dezelfde rechten als Senior Psycholoog -> grade 820. Ik had gezien dat grade 830 nog niet bezet was.

**Comment by Tom974** [comment]
done
