### ISSUE TITLE
[FEATURE]: Muziek cirkel op rang.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#2216]
### Contact Details

dead123x5

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag de muziek cirkel (de naam van de cirkel is Vanilla) in het gebouw complex willen laten zetten op onze rang, zodat mensen deze zonder rang niet meer kunnen gebruiken.

Deze zou dan moeten komen op de rangen van "red" en "offred"

### Wat lost deze feature op?

Zodat mensen die aan het feesten zijn niet meer zomaar de muziek van de DJ kunnen veranderen en daardoor de RP verstoord word.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
