### ISSUE TITLE
[FEATURE]: Extra In/uitdienst cirkel.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#2217]
### Contact Details

dead123x5

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag een EXTRA in/uitdienst cirkel willen krijgen in een ander pand van ons. Dit gaat om de rang(en) "red" en "offred"

De cirkel zou op de volgende coords geplaatst moeten worden:
X: 544.03 Y: -201.34 Z: 54.49 H: 5.69
https://prnt.sc/euzRbumfawke

### Wat lost deze feature op?

Zodat mensen niet onnodig helemaal naar de andere kant van de stad hoeven te gaan om zich in/uitdienst te zetten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
