### ISSUE TITLE
[FEATURE]: Verlagen van de damage van vuurwapens

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#2218]
### Contact Details

Lamine

### Goedgekeurd door

Tijdens staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Tijdens het staff overleg is er besloten dat de damage van alle vuurwapens verlaagd moet worden. 

### Wat lost deze feature op?

Dit voorkomt dat een shootout zeer snel voorbij is en de betrokken speler geen kans heeft om te reageren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@niekschoemaker Deze moet ff gemixt worden met https://github.com/Tedeapolis/development/issues/2199

**Comment by Tom974** [comment]
Zit erin na de herstart
