### ISSUE TITLE
Uitdienst staff en justitie

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#2220]
### Contact Details

yohandessu

### Beschrijf zo duidelijk mogelijk de feature

Hey! Het is mogelijk om tijdens /adminonduty indienst te gaan bij justitie. Graag zie ik dat als je indienst gaat als staff dat je dan uitdienst word gezet bij justitie.

### Wat lost deze feature op?

Ja.. gezeik

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
