### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by EpicTomm** [Tedeapolis/development#2221]
### Contact Details

epictom

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij zagen dat bloods hun huis icoontje, hun logo was en vonden dat wel vet eruit zien. Nu vragen wij eigenlijk precies hetzelfde. Of het Reznikov logo als icoontje krijgen inplaats van dus die rode kroon die we nu hebben.

![image](https://github.com/Tedeapolis/development/assets/104857888/49ac50c8-c983-489c-bc7f-0584d1bdd734)

### Wat lost deze feature op?

NVT

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Hey @EpicTomm 

gister heeft tom een github commit geplaatst dat ij geen custom icoontjes meer erop zet omdat het enorm veel werk is, hierdoor heeft hij ook die van bloods weggehaald. 

Gaat dus helaas niet door :)

![image](https://github.com/Tedeapolis/development/assets/79802852/2ed28a5d-5c2d-45d3-aa3f-17f4b96ba321)
