### ISSUE TITLE
[EUP]: DSI Vrouw broek 

### ISSUE THREAD

**Issue by Ssaannddyy1** [Tedeapolis/development#2222]
### Contact Details

sandyy

### Goedgekeurd door

devv4532

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

DSI Vrouw EUP Glitch door nieuwe kleding update

Schoenen zijn veranderd naar 
Schoen 1 : 124
Schoen 2 : 12

Broek veranderd naar

Grijs
Broek 1 : 181
Broek 2 : 6

Zwart 
Broek 1 : 181
Broek 2 : 5

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by CalRayy** [comment]
@DevvTDA 🫣

**Comment by DevvTDA** [comment]
Word gefixt na de restart :)
