### ISSUE TITLE
[FEATURE]: Deuren van de luchtmacht toestellen.

### ISSUE THREAD

**Issue by RobinKolb** [Tedeapolis/development#2224]
### Contact Details

___robin___

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Momenteel vallen deuren van vlieg toestellen af wanneer een toestel vliegt. Het probleem is dat binnen de luchtmacht de achterklep van de C-130 Hercules en de Chinook open moeten kunnen op hoge snelheden. Dit kan wel, maar momenteel vallen ze er dan af. Dit zorgt zelfs voor een rood motor lampje bij de C-130 Hercules.

Het zou erg tof zijn als op deze 2 toestellen,
- C-130 Hercules 
- Chinook 

De deuren er niet afvallen op hoge snelheden.

### Wat lost deze feature op?

Dat deze 2 toestellen voor goede doeleinden gebruikt kan worden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Bij vliegtuigen donderen ze er niet vanaf, dus dat komt te vervallen.

Helikoptoren heb ik de snelheid verhoogt naar 100 knopen, merkte zelf dat die chinook maar net 80 a 90 ging, dus dat is wel prima denk ik.
