### ISSUE TITLE
[FEATURE]: Onherkenbaar voertuig kvk justitie 

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#2229]
### Contact Details

begoo

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag willen wij als KVK een onherkenbaar dienstvoertuig. Dit omdat bij controles als wij de justitie auto pakken mensen vluchten of niet de waarheid spreken aangezien ze dan bang zijn voor sancties. Met een onherkenbaar voertuig kunnen we dus controles uitvoeren zonder dat mensen weten dat we van de KVK zijn.

Nu denk je misschien, kunnen wij dan niet eigen auto's gebruiken. Dit omdat we dit simpel weg niet van ons personeel kunnen vragen. Met een onherkenbaar voertuig rijdt ons personeel ook niet in allerlei auto's rond. Maar is er gewoon 1 voertuig die ze kunnen gebruiken voor de controles. 

/car x5m2016 
Dit is een BMW x5. 

En dan alleen toegang voor deze rangen:
Justitie 63
Justitie 65
Justitie 70
Justitie 80

Graag horen we of het mogelijk is. Zo niet, of eventueel aanvragen voor een andere auto: Begoo (Begoo
#5014)

### Wat lost deze feature op?

Mensen weten op voorhand niet dat wij van justitie zijn, zo kunnen we meer mensen op heterdaad betrappen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@Lorenzo3001

**Comment by Tom974** [comment]
Ik heb jullie toegang gegeven tot de volvoxc90, dat lijkt me voor nu prima ipv een heel voertuig toe te voegen voor kvk.

**Comment by JohanDewus** [comment]
Topper, thx tom!
