### ISSUE TITLE
La Icona

### ISSUE THREAD

**Issue by AimeKoenders234** [Tedeapolis/development#223]
Huis: La Fuente Blanca.

- [x] Sloten overzetten van 'Pavlov' naar 'La Icona' : Sloten zijn normaal gezien nog in het huis!

- [x] Cirkels: In het kantoor van het huis zou de opslag en het menu voor mensen aan te nemen moeten staan. De cirkel voor de helikopter / voertuig opslag moet ergens bij de garage staan. Indien dit kan genoeg plaats voor er een helikopter in en uit te halen/zetten.

Dit zijn overigens de rangen voor de job 'La Icona'
Zou het mogelijk zijn dat enkel de 2 hoogste rangen wapens kunnen inkopen? 
Hieronder even een lijstje met welke wel en welke niet. Indien mogelijk

- [x] -Godfather  : Deze rang kan alles inkopen 
- [x] -Don  : Deze rang kan alles inkopen behalve de "AK"
- [x] -Consigliere /
- [x] -Capo /
- [x] -Soldato /
- [x] -Associate /

**Comment by Willem-Dekker** [comment]
Is geimplementeert kan morgen getest worden op main dan kan deze worden overgezet
