### ISSUE TITLE
[Bug]: Job icon Karmellos off-center

### ISSUE THREAD

**Issue by OwenFufu** [Tedeapolis/development#2230]
### Contact Details

miguelitoooo

### Wat gebeurde er?

Sinds de job icons groter gemaakt zijn gemaakt voor alle jobs merk ik dat onze job icon niet meer in het midden staat maar meer naar links onder staat. 

### Wat hoorde er te gebeuren?

Dat het icoontje in het midden staat inplaats van de huidige locatie.

### Wat veroorzaakt de bug?

Het groter maken van de job icons

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by OwenFufu** [comment]
![image_2023-08-31_182655564](https://github.com/Tedeapolis/development/assets/138393362/b497bb19-2bed-44bb-aa59-c531a214774c)

**Comment by CalRayy** [comment]
@Tom974 zie je wel XD
