### ISSUE TITLE
[EUP]: Hondengeleider in KMAR EUP

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2231]
### Contact Details

Larrsss#3819

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag in de **KMAR EUP** onder het kopje **KMAR - Vest** de hondengeleiders vest toevoegen. 
Echter kan deze niet gekopieerd worden vanuit de politie. Er zal dus een reskin gemaakt moeten worden voor de KMAR.
Zie screenshots voor het vest van de politie, z'n soort vest willen we ook graag bij de KMAR. 

![Hondengeleider zwart achterkant](https://github.com/Tedeapolis/development/assets/112424697/964601d0-7eab-43b4-86ee-4d4cf14bdbb9)
![Hondengeleider Zwartl voorkant](https://github.com/Tedeapolis/development/assets/112424697/75c74408-567a-4260-a67b-813d673b9e8b)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by KMarTDA** [comment]
@DevvTDA al iets meer nieuws? :D

**Comment by DevvTDA** [comment]
@KMarTDA Gelieve gewoon geduld te hebben

**Comment by DevvTDA** [comment]
fixed houd github in de gaten :)
