### ISSUE TITLE
[FEATURE]: Rang aanpassingen Karmellos

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2233]
### Contact Details

ihax0r

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

We willen na langere tijd (meer dan 3 maanden) onze rangen wederom aanpassen binnen Karmellos, dit zodat we meer stappen hebben binnen onze groep en we hiermee meer structuur kunnen creëren.

Hieronder zijn alle rangen te vinden, met daarbij de permissies. Mochten er nog vragen zijn en permissies missen, laat dit even weten bij voorkeur in mijn DM (ihax0r) of die van Gino (giniii).

Indien er conflicten zijn met rangen omdat deze nog op de job zijn, kan je dit aangeven dan zal ik iedereen tijdelijk op een andere rang zetten.

/setjob {id} bratva 0 | Karmellos - Extraño | Permissies: Items kopen, Spullen in de pot leggen Niks er uit halen.
/setjob {id} bratva 100 | Karmellos - Conocido | Permissies: Voertuig opslag bekijken, Items kopen , Spullen in de pot leggen Niks er uit halen.
/setjob {id} bratva 200 | Karmellos - Nieto | Permissies: Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 300 | Karmellos - Cuñado | Permissies: Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 400 | Karmellos - Sobrino | Permissies: Melee inkoop, Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 500 | Karmellos - Hermano | Permissies: Melee inkoop, Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 600 | Karmellos - Suegro | Permissies: Melee inkoop, Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 700 | Karmellos - Commandante | Permissies: Alle Wapens inkopen, Wapens tunen. Voertuig opslag , Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 800 | Karmellos - Tío | Permissies: Alle Wapen inkoop, Bazen heli, Wapen tunen, Voertuig opslag, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 900 | Karmellos - Padre | Permissies: Alles
/setjob {id} bratva 1000 | Karmellos - Abuelo | Permissies: Alles

### Wat lost deze feature op?

Meer mogelijkheden binnen onze groep.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Wat moet er nu aangepast worden dan @iHax0rMC ?

**Comment by Tom974** [comment]
Ik zie namelijk wel een rangenstructuur maar het kost mij veel minder tijd als je puur even de toevoegingen / veranderingen opschrijft :)

**Comment by iHax0rMC** [comment]
> Ik zie namelijk wel een rangenstructuur maar het kost mij veel minder tijd als je puur even de toevoegingen / veranderingen opschrijft :)

In dat geval ik geloof dat alle nummers bij de jobs veranderen, aangezien we meer rollen hebben en ze dan in chronologische volgorde staan.

Nieuwe rangen:
- Karmellos - Cuñado | Heeft dezelfde permissies als Nieto.
- Karmellos - Suegro |  Heeft dezelfde permissies als Hermano.

Veranderingen in rangen:
- Karmellos - Tío | Krijgt de permissie erbij om de volledige wapeninkoop te kunnen kopen en tunen.
- Karmellos - Padre | Krijgt dezelfde permissies als Abuelo.

De volgorde hoe ik de rangen had gesorteerd staan in het bericht erboven.
