### ISSUE TITLE
[Bug]: Dierenkliniek meldkamer werkt niet meer. 

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2234]
### Contact Details

dyon.

### Wat gebeurde er?

Als mensen een bericht sturen naar de meldkamer "dierenkliniek" krijgen wij die niet meer binnen. Dit is best vervelend want hierdoor kunnen de dierenartsen eigenlijk niet makkelijk terecht komen bij de gewonde dieren.

### Wat hoorde er te gebeuren?

Wij horen een melding binnen te krijgen.

Is het ook mogelijk dat de meldkamer naam veranderd word van "dierenkliniek" naar: "bark". Dit omdat mensen blijkbaar heel veel moeite hebben met hoe ze dierenkliniek typen 😅 

Is het ook mogelijk dat het niet hoofdletter gevoelig word. Want hierdoor raken ook veel mensen in de war.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
_Is het ook mogelijk dat de meldkamer naam veranderd word van "dierenkliniek" naar: "bark". Dit omdat mensen blijkbaar heel veel moeite hebben met hoe ze dierenkliniek typen 😅_
Helaas niet, het nummer is letterlijk de jobnaam dus dat hou ik ook gewoon zo. Ik zal hem wel standaard bij mensen in de contacten zetten, denk dat dat het probleem al opgelost.

_Is het ook mogelijk dat het niet hoofdletter gevoelig word. Want hierdoor raken ook veel mensen in de war._
Helaas op dit moment niet. We zijn bezig met een update van de telefoon en daar zou dit evt wel in verwerkt kunnen worden. Ik zal het doorpasen naar Misstake :)

**Comment by Dyon033** [comment]
Je bent een held @Tom974

Nog 1 vraagje, klopt het dat ons logo verdwenen is van de kaart?
