### ISSUE TITLE
[AMBULANCE]: Porto 110 -> porto 120

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2235]
Een tijd geleden is er een proeftraject opgestart om de Ambulance in porto 110 te plaatsen. Echter heeft dit geen succes gehad en zouden we graag terug naar onze eigen porto (120) willen. KL & Kader zijn hier akkoord mee.

**Comment by Tom974** [comment]
Zal ik het anders zo doen dat de standaardporto 120 wordt maar je nog wel 110 kunt joinen? En evt dat de politie / kmar wel nog jullie porto (120) in kan mocht het nodig zijn?

**Comment by Jaak-Steifkes** [comment]
> Zal ik het anders zo doen dat de standaardporto 120 wordt maar je nog wel 110 kunt joinen? En evt dat de politie / kmar wel nog jullie porto (120) in kan mocht het nodig zijn?

Eventueel zouden hier koppelprio's voor kunnen gebruikt worden. Voor nu mogen ze er niet in gezien dat collega's nogal afgeblaft werden, de laatste tijd door Politie/Kmar. Als dat niet was voorgevallen hadden we het eventueel wel een kans gegeven.

**Comment by Tom974** [comment]
> > Zal ik het anders zo doen dat de standaardporto 120 wordt maar je nog wel 110 kunt joinen? En evt dat de politie / kmar wel nog jullie porto (120) in kan mocht het nodig zijn?
> 
> Eventueel zouden hier koppelprio's voor kunnen gebruikt worden. Voor nu mogen ze er niet in gezien dat collega's nogal afgeblaft werden, de laatste tijd door Politie/Kmar. Als dat niet was voorgevallen hadden we het eventueel wel een kans gegeven.

Is dat dan niet eerder een probleem om even te melden bij korpsleiding zodat deze personen interne sancties kunnen krijgen? Ik denk dat dat een betere oplossing is..

**Comment by Tom974** [comment]
Want nu wil je dus enkel het probleem verplaatsen ipv het probleem aan te pakken

**Comment by Jaak-Steifkes** [comment]
We hebben dit bij de Ambulance zo besproken onderling en zouden het eerst even via deze weg willen oppakken, wellicht dat er in de toekomst gekeken kan worden naar weer een eventuele samenwerking in de porto dat ze kunnen joinen, maar voor nu hebben we het besloten om het even niet te doen. Dit omdat we nog aan het reorganiseren zijn en nog zoekende zijn, tevens werd er van de 110 porto geen gebruik gemaakt om Ambulanciers op te roepen en werden er nog meldingen gemaakt steeds. Voor nu dus graag niet dit is intern besproken met TL/Afdelingsmanager/Baas en hiermee was ieder akkoord. Dit is niet het verplaatsen van een probleem, maar meer een voor iets wat later te bespreken valt wanneer er een meeting is.

**Comment by Tom974** [comment]
Ik ben nogsteeds van mening dat je het probleem gewoon op moet lossen ipv te vermijden maar goed, dat is jullie eigen keuze. 

Het zal aangepast zijn na de herstart

**Comment by Jaak-Steifkes** [comment]
Goedenavond, het werkt nog niet. 120 is nu weer joinbaar, net zoals porto 110. Maar we worden niet standaard in porto 120 gezet en nog steeds in 110. Dus is volgens mij ergens misgegaan :D

**Comment by Jaak-Steifkes** [comment]
Is opgelost zie ik, bedankt!
