### ISSUE TITLE
[FEATURE]: Ambulance Lifeliner - ANWB Logo's + dirt fix

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2236]
### Contact Details

jaak_steifkes

### Goedgekeurd door

Vayen

### Beschrijf zo duidelijk mogelijk de feature

ANWB logo's verwijderen van de Lifeliner + het toevoegen van een dirt fix.

### Wat lost deze feature op?

Momenteel wordt de Lifeliner redelijk snel vuil, eenmaal dat deze vuil is beginnen de ramen te flikkeren en worden ze donker alsof ze getuned worden naar pure black. Hierdoor veranderen de ramen de hele tijd van doorzichtig naar pure black. Het ANWB logo staat veel groter op de lifeliner in verhouding met het Ambulance logo waardoor we constant worden aangesproken als ANWB met een helikopter, dus zou fijn zijn als deze ANWB logo's eraf worden gehaald. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Dyon033** [comment]
![image](https://github.com/Tedeapolis/development/assets/120292087/41ecaf62-d456-461b-9b02-ad9c484febb8)

In het echt staat het ANWB logo er ook op hè

**Comment by Tom974** [comment]
Door wie is dit goedgekeurd?

**Comment by Jaak-Steifkes** [comment]
> Door wie is dit goedgekeurd?

Door Vayen.

**Comment by Tom974** [comment]
> > Door wie is dit goedgekeurd?
> 
> Door Vayen.

ah oke, wel handig als je dat ook even in de "Goedgekeurd door" box zet voortaan (er staat nu namelijk niet van toepassing) :P

Verder zal ik m ff doorpasen naar lorenzo :))

**Comment by Lorenzo3001** [comment]
Ramen zijn gefixed, verder zie ik geen reden om de livery aan te passen.
