### ISSUE TITLE
[EUP]: Kazernekleding en duikuitrusting

### ISSUE THREAD

**Issue by Tommetjeh** [Tedeapolis/development#2237]
### Contact Details

Tommetjeh#6007

### Goedgekeurd door

Mila

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Kazernekleding
- Riem van kazernekleding zwart maken, is op dit moment dezelfde kleur blauw als het shirt en de broek. Riem is wel zichtbaar maar dus dezelfde kleur.

Duikuitrusting
- Wetsuit met flippers (liefst volledig zwart of zwart met rode accenten), toevoegen aan EUP
- Duikset toevoegen aan EUP

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Riem kan niet aangepast worden gezien dit 3d is.

**Comment by DevvTDA** [comment]
duik uitrusting is wel gefixt
