### ISSUE TITLE
[FEATURE]: GHB

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2238]
### Contact Details

CalRay#1513

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Burgerraad:
Suggestie GHB

Momenteel is er geen goede oplossing om een gijzeling/ontvoering af te ronden zonder het risico te lopen dat er wraak word genomen of er een signalement word uitgeschreven. Vooral dit laatste zal deze suggestie zich op verdiepen. Momenteel kan je een overheidsmedewerker van de Koninklijke Marechaussee of de politie ontvoeren, zijn communicatiemiddelen en bodycam/dashcam afnemen en hem achteraf achterlaten. Echter kunnen de agenten juridisch gezien nog altijd een proces verbaal opstellen, en in het geval van meerdere agenten, meerdere PV's die elkaar versterken. Hierdoor kun je ondanks dat er geen beeldmateriaal op dashcam is, alsnog gesignaleerd worden, kan er een onderzoek gestart worden of de agenten kunnen de locatie waar ze zijn geweest onthouden. Dit laatste is bijvoorbeeld jammer aangezien veel gang terreinen een kamer hebben voor martelingen echter worden deze niet vaak gebruikt omdat de personen dan het kunnen linken aan een plaats. 

Ik stel daarom voor dat er een item word toegevoegd in TDA, namelijk: GHB. Dit is een narcosedrug die in het echte leven bijwerkingen heeft van vergeetachtigheid, misselijkheid, overgeven en stuiptrekkingen. Ook treed er bewusteloosheid toe. Dit is dus een perfect item om bovenstaande problemen op te lossen. Zo kan het worden toegediend bij personen om ze achter te laten op een locatie na bijvoorbeeld een ripdeal of gijzeling om zo het risico op vervolging te voorkomen.

De werking is als volgt; 

Het item moet gegeven worden aan de persoon, deze dient persoon dan via de inventory te 'gebruiken'. Hierna komende volgende meldingen in zijn beeld;

'Je begint je duizelig en misselijk te voelen'
'Je bent bewusteloos geraakt' -> Hierbij komt dan ingame het bewusteloze effect.
'Omdat je GHB hebt genuttigd moet je het afgelopen scenario vergeten'

We hebben ook in burgerraad overlegd dat het iets rare's moet worden. Dus dat het niet zo toegankelijk is. 

Zie bijlage
![image](https://github.com/Tedeapolis/development/assets/101106299/a4a29cbd-717e-4a23-985b-95c4223aaa97)

### Wat lost deze feature op?

RP

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by RobinKolb** [comment]
Krijg je hierbij niet het probleem dat criminelen dit gaan opsparen en gaan geven aan elke agent die zij handsuppen?

**Comment by CalRayy** [comment]
Je krijgt het ook niet zomaar, development is hiervan op de hoogte... @RobinKolb
