### ISSUE TITLE
CCF - consignliere en underboss aanpassing[FEATURE]: 

### ISSUE THREAD

**Issue by Donnycolombo** [Tedeapolis/development#2239]
### Contact Details

epicdonny

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Zouden jullie bij de rang consignliere en underboss van CCF de functie voor personeelsbeheer willen toevoegen? Ze hoeven geen access tot de bazenpot maar dat ze mensen kunnen aannemen en ontslaan indien nodig is wel fijn

### Wat lost deze feature op?

wachten op de don ;P

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
