### ISSUE TITLE
[Bug]: Recherche rollen kunnen geen /disarm

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2240]
### Wat gebeurde er?

De recherche rollen hebben geen toegang tot disarm. Deze feature zorgt er voor dat je niet perongelijk gaat schieten en met een homing missle kan dit een vrij grote impact hebben.

Het gaat om de volgende rollen:
police 16
police 17
police 18
police 19

### Wat hoorde er te gebeuren?

Dat wanneer je /disarm doet dat het onmogelijk is om te schieten.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik heb al wat anders op de planning staan wat dit vervangt. Dus ik sluit deze issue even.
