### ISSUE TITLE
[Bug]: Groot wapen (soms) niet zichtbaar op rug.

### ISSUE THREAD

**Issue by RobinKolb** [Tedeapolis/development#2243]
### Contact Details

____robin____

### Wat gebeurde er?

Mijn SMG van de Marechaussee is af en toe niet zichtbaar op de rug. 

### Wat hoorde er te gebeuren?

De SMG / groot wapen moet altijd zichtbaar zijn op de rug wanneer deze niet in de handen zit.

### Wat veroorzaakt de bug?

Dit veroorzaakt dat criminelen niet weten of zei deze moeten afnemen bij een eventuele gijzeling.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

![Schermafbeelding 2023-09-10 203843](https://github.com/Tedeapolis/development/assets/143357734/4cb55320-8e20-45d8-86d6-d696173560f7)
![Schermafbeelding 2023-09-10 203819](https://github.com/Tedeapolis/development/assets/143357734/9337ff45-37ba-4670-866f-dff9e2f8eb45)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Maar wat veroorzaakt de bug dan? Of heb je daar geen idee van? 

Alsin, stapte je in of uit een voertuig, pakte je het wapen ? schoot je ermee? of iets anders?

**Comment by RobinKolb** [comment]
Ja het gebeurd wanneer je het grote wapen van je handen (gepakt) weg doet op je rug. Dan is het niet meer zichtbaar. Dit is niet altijd zo. Dit probleem doet zich voor sinds attachments te zien zijn op rug.

**Comment by Tom974** [comment]
@RobinKolb 

Misstake heeft een mogelijke patch doorgepushed, laat het even weten of het nogsteeds voorkomt.

**Comment by RobinKolb** [comment]
Geen last meer van, probleem lijkt opgelost!

**Comment by Tom974** [comment]
Top, dan sluit ik de issue voor nu. Mocht het weer voorkomen kun je deze issue opnieuw openen :)
