### ISSUE TITLE
[EUP]: Ambulance kleding (vrouwen)

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2244]
### Contact Details

jaak_steifkes

### Goedgekeurd door

Mila E.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

**Ambulance Psychologie (vrouw)**

Fout bij nummers van kledij. Aanpassing van nummers naar:

T-Shirt 1: <7>
T-Shirt 2: <0>
Torso 1: <631>
Torso 2: <5>
Stickers 1: <0>
Stickers 2: <0>
Armen 1: <1>
Armen 2: <0>
Broek 1: <15>
Broek 2: <0>
Schoenen 1: <42>
Schoenen 2: <9>
Kogelvrij vest 1:<75>
Kogelvrij vest 2:<0>
Ketting 1: <157>
Ketting 2: <2>

**Ambulance Inwerking (vrouw)**

Momenteel staat hier nog 'Specialist' op in plaats van Inwerking. Zie onderstaande screenshot.

https://imgur.com/7HZbEXE

**Ambulance Examinator (vrouw)**

Momenteel staat hier nog 'Verpleegkundige' op in plaats van Examinator. Zie onderstaande screenshot.

https://imgur.com/43SUZoT

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed
