### ISSUE TITLE
[EUP]: BOT vest vrouwen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2245]
### Contact Details

Larrsss#3819

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Er mist justitie op het BOT vrouwen vest, waardoor het te erg op DSI lijkt.
Zie screenshot van het goede vest en hoe het er nu uit ziet.

![image](https://github.com/Tedeapolis/development/assets/112424697/d6b7a009-2082-4386-864c-2f214ff7b0cc)

![image](https://github.com/Tedeapolis/development/assets/112424697/61010491-c46b-44ee-82e8-c6a3c112ce34)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Hey @KMarTDA 
Laatste keer dat ik wat voor de kmar vrouwen gemaakt heb kreeg ik te horen is lelijk willen we veranderen, dus dit zal door Ruby gemaakt mogen worden.

**Comment by KMarTDA** [comment]
Ahh okay! Ga ik dat even doorkoppelen. Bedankt

**Comment by KMarTDA** [comment]
Heb jij toevallig het bestandje van het vrouwen steekvest van het BOT? Dan kan ik deze doorsturen naar hun, zodat ze hem kunnen aanpassen. @DevvTDA

**Comment by DevvTDA** [comment]
@KMarTDA gssproken met Lynn en het is enkel de retexture ik zal dit zelf doorzetten.

**Comment by DevvTDA** [comment]
fixed
