### ISSUE TITLE
[FEATURE]: Parachutes - Gang itemwinkel

### ISSUE THREAD

**Issue by ExpensiveK09** [Tedeapolis/development#2246]
### Contact Details

ExpensiveK

### Goedgekeurd door

Besproken in staffoverleg (https://discord.com/channels/563825802865541122/1152784247506092102/1153051591797121044)

### Beschrijf zo duidelijk mogelijk de feature

De parachutes in de item winkel van officiele gangs kosten op dit moment €500,- perstuk. Deze moesten €150 perstuk zijn. 

### Wat lost deze feature op?

Er wordt veel meer gebruik van gemaakt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik heb ze expres op 500 euro gezet, als je lui bent betaal je 500 euro en anders ga je naar lsia toe en koop je er eentje voor 75eu.
