### ISSUE TITLE
[Bug]: Voertuigen vallen in ziekenhuis

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#2247]
### Contact Details

Solidhawk

### Wat gebeurde er?

- Wanneer je in het Ziekenhuis bent, en iemand parkeert boven of rijd langs boven of staat stil. Dan is het voor diegene die in het Ziekenhuis staat dat er een auto de Ziekenhuis komt binnen storten. Dit is enkel zichtbaar voor diegene die op dat moment in het Ziekenhuis is en is per persoon verschillend. 

### Wat hoorde er te gebeuren?

-

### Wat veroorzaakt de bug?

Stilstaand voertuig, bij, of op het ziekenhuis.

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

None

### Relevante log bestanden

![image](https://github.com/Tedeapolis/development/assets/4984517/73bd7480-fcc5-47a4-8b05-b0ff8f2fe757)

enkel voorbeeld foto.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@Solidhawk is al bekend bij ons, dit is niet alleen bij het ziekenhuis. Kan helaas niet door ons gefixt worden en moet door FiveM gedaan worden.

Zie https://github.com/citizenfx/fivem/issues/2173
