### ISSUE TITLE
[FEATURE]: KNRM Rangen Permissies

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2248]
### Contact Details

jaak_steifkes

### Goedgekeurd door

Daniel P.

### Beschrijf zo duidelijk mogelijk de feature

Graag voor onderstaande ambulance rangen toegang tot de volledige KNRM job, deursloten, voertuigen etc. 

-  Ambulance grade 1000 - Medisch Directeur
-  Ambulance grade 925 - Afdelingshoofd Psychologie
-  Ambulance grade 900 - Afdelingshoofd Geneeskunde
-  Ambulance grade 850 - Teamleider afdeling Geneeskunde
-  Ambulance grade 875 - Teamleider afdeling Psychologie

### Wat lost deze feature op?

Dat Teamleiding die er meer is voor het coordineren van de KNRM hun huidige secondjob niet verliezen. Gezien dat we af en toe zullen bijspringen bij de KRNM.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Heb je dit uberhaupt al getest... ? Want volgensmij heb ik dit al gedaan.....

@Jaak-Steifkes

**Comment by Jaak-Steifkes** [comment]
Ik kan met Medisch Directeur geen andere voertuigen kopen bij de KRNM-voertuig opslagplaats. 

Zie onderstaande voorbeelden: 
https://imgur.com/i91ik1L
https://imgur.com/bTy7xzv

**Comment by Tom974** [comment]
Oh ik zie t indd, had het nog niet doorgepushed.

is gefixt na de herstart. Sleutels etc werkte wel gewoon al toch? (indien dit niet zo was, graag issue even opnieuw openen)
