### ISSUE TITLE
[Bug]: Brandweer job bugs

### ISSUE THREAD

**Issue by BrandweerTedeapolis** [Tedeapolis/development#2250]
### Contact Details

Jeffreynl

### Wat gebeurde er?

Nadat vannacht de nieuwe brandweer job erin gezet is, werkt de job niet meer.

- Het is niet mogelijk om voertuigen te pakken
- Het is niet mogelijk om objecten te pakken
- Het is niet mogelijk om het baas menu te openen
- Het is niet mogelijk om het F6 menu te openen
- Het is niet mogelijk om porto 110 & 160 in te gaan

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed
