### ISSUE TITLE
Shiftlogging voor de brandweer

### ISSUE THREAD

**Issue by BrandweerTedeapolis** [Tedeapolis/development#2251]
### Contact Details

JeffreyNL

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Shiftlogging toevoegen voor de brandweer. Mag naar brandweertedeapolis@gmail.com

### Wat lost deze feature op?

Stelt ons in staat om promoties te beoordelen binnen de brandweer. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hebben jullie een mailbox ofzo waar de shiftlogging moet komen dan?

**Comment by BrandweerTedeapolis** [comment]
> Hebben jullie een mailbox ofzo waar de shiftlogging moet komen dan?
> 
> 

Voor nu hebben we nog geen TDA e-mail, dus voor nu mag het naar brandweertedeapolis@gmail.com
