### ISSUE TITLE
[Bug]: Brandweer bugs

### ISSUE THREAD

**Issue by BrandweerTedeapolis** [Tedeapolis/development#2252]
### Contact Details

JefffeyNL

### Wat gebeurde er?

- Nadat afgelopen nacht er 2 nieuwe brandweervoertuigen zijn toegevoegd, is het voor niemand meer mogelijk om de normale brandweerauto te pakken. 

- Het is niet mogelijk om de blauwe lampen of sirenes op de Vw golf aan te zetten via de normale methode. 

- Brandweervoertuigen krijgen flitsboetes. 

- Stip op de kaart is weg

- Brandweer kan niet meer in porto 110

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
De normale brandweerauto is er inderdaad uitgehaald omdat deze te amerikaans was en naar onze weten puur als tijdelijke vervanging. Daarnaast kun je er ook mensen mee doodspuiten wat niet de bedoeling is maar wel zal gebeuren mocht her voertuig gestolen worden.

Verder over de sirenes, gebruik je dan Q en alt of? Want dat is hoe ze gewoon aan horen te gaan

**Comment by BrandweerTedeapolis** [comment]
> De normale brandweerauto is er inderdaad uitgehaald omdat deze te amerikaans was en naar onze weten puur als tijdelijke vervanging. Daarnaast kun je er ook mensen mee doodspuiten wat niet de bedoeling is maar wel zal gebeuren mocht her voertuig gestolen worden.
> 
> Verder over de sirenes, gebruik je dan Q en alt of? Want dat is hoe ze gewoon aan horen te gaan
> 
> 

De nieuwe brandweerauto kan ook niet gepakt worden. 
Sirenes werken iig op de polo niet met q en alt

**Comment by Lorenzo3001** [comment]
> Verder over de sirenes, gebruik je dan Q en alt of? Want dat is hoe ze gewoon aan horen te gaan

@Tom974 Als ik de Golf inspawn dan werkt het gewoon prima, dus wellicht dat het te maken heeft met de job spawner

**Comment by BrandweerTedeapolis** [comment]
> > Verder over de sirenes, gebruik je dan Q en alt of? Want dat is hoe ze gewoon aan horen te gaan
> 
> 
> 
> @Tom974 Als ik de Golf inspawn dan werkt het gewoon prima, dus wellicht dat het te maken heeft met de job spawner
> 
> 
> 
> 

Heb het geverifieerd, het werkt. Denk dat ik zelf op het verkeerde knopje heb gedrukt. De andere issues spelen wel.

**Comment by Tom974** [comment]
Welke ? want 110 werkt prima bij mij.

**Comment by BrandweerTedeapolis** [comment]
Flitsboetes - Is ook zo met de volvo:
https://medal.tv/games/gta-v/clips/1v1cKt3SwhKOBT/d1337Bv8zTNm?invite=cr-MSw1ckwsMTQ2MDQ4MTAs

Stip op de kaart:
![image](https://github.com/Tedeapolis/development/assets/145530665/4775f689-1639-4ba8-b5eb-75f7f920d44a)

Porto 110:
https://medal.tv/games/gta-v/clips/1v1dFPxCsdXGp9/d1337l34vkce?invite=cr-MSxYa3osMTQ2MDQ4MTAs

Volvo werkt niet:
https://medal.tv/games/gta-v/clips/1v1fiQX0Gtnt63/d1337dEMztgY?invite=cr-MSw5eVcsMTQ2MDQ4MTAs

ELS werkt niet:
https://medal.tv/games/gta-v/clips/1v1hIzjBfJDjOc/d1337IDTVAoS?invite=cr-MSxhUkssMTQ2MDQ4MTAs

Brandweer heeft ook geen toegang tot /neckbrace

**Comment by Lorenzo3001** [comment]
> ELS werkt niet: https://medal.tv/games/gta-v/clips/1v1hIzjBfJDjOc/d1337IDTVAoS?invite=cr-MSxhUkssMTQ2MDQ4MTAs

ELS werkt wel maar bugged soms als het voertuig niet van jou is. Als die niet zou werken dan zou je de sirene ook niet horen namelijk.

**Comment by BrandweerTedeapolis** [comment]
> > ELS werkt niet: https://medal.tv/games/gta-v/clips/1v1hIzjBfJDjOc/d1337IDTVAoS?invite=cr-MSxhUkssMTQ2MDQ4MTAs
> 
> 
> 
> ELS werkt wel maar bugged soms als het voertuig niet van jou is. Als die niet zou werken dan zou je de sirene ook niet horen namelijk.
> 
> 
> 
> 

Duidelijk, dan kan die ook afgevinkt worden. 
Dan is het dus alleen het spawnen van de Volvo, porto 110, de blip en de flitsboetes

**Comment by Tom974** [comment]
Is die stip per se nodig dan? Denk dat je liever een brandweer logotje wilt net zoals de politie/ambu e.d. Maak daar wel ff een aparte issue voor aan samen met het logotje dan.

De andere issues zijn voor mij iig niet relevant wanneer ik inlog(in de main server), dus ik snap even niet hoe je dat voor elkaar gekregen hebt. Ik zie nu ook weer brandweer in porto 110 zitten dus ik ga er vanuit dat dit opgelost is.
