### ISSUE TITLE
[Bug]: KNRM Issues

### ISSUE THREAD

**Issue by Solidhawk** [Tedeapolis/development#2253]
### Contact Details

Solidhawk

### Wat gebeurde er?

~~- [ ] Mensen met de KNRM Rang op de 2e job kunnen geen voertuigen aanschaffen van de KNRM~~
- [x] Iedereen met een ambulance rol kan in het KNRM gebouw. Gelieve dit enkel te maken voor 2e job van de KNRM. (Werkt op dit moment ook niet)
- [x] Mogelijkheid om de knrm voertuigen kunnen ook in het ziekenhuis genomen worde zoals een jetski en een boot 
- [x] Kleding kan ook door iedereen in de ambulance aan gedaan worden.
~~- [ ] Geen F6 op 2de job (geen idee of dit kan ja dan nee)~~

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik ga geen 2e job support toevoegen voor de ambulance. Dus zet die job gewoon op je eerste job. 

Mbt sleutels en eup zal ik straks even naar kijken

**Comment by JeroenKla** [comment]
ik ben niet mee met wat je bedoeld :) op dit --> _(Ik ga geen 2e job support toevoegen voor de ambulance. Dus zet die job gewoon op je eerste job.)_

**Comment by Tom974** [comment]
Er zit momenteel geen support in voor secondjob. Dit betekent dat de ambulance job alleen werkt op je erste job. Mocht je dus knrm als neventaak hebben, dan moet je gewoon die job aannemen. Of als je teamleider bent kun je natuurlijk wel de teamleider job, want die heeft wel de knrm ingebouwd

**Comment by JeroenKla** [comment]
dus als ik het goed lees kunnen enkel Teamleiders knrm voertuigen nemen
op hun second job maar als je dit als lagere rang wilt moet de knrm rol op je eerste job staan

**Comment by Tom974** [comment]
Nee, ambulance job werkt in zijn geheel niet op de 2e job

**Comment by JeroenKla** [comment]
knrm moet dus eigelijk volledig op de 1ste job staan om te doen werken

**Comment by Tom974** [comment]
Ja inderdaad

**Comment by Tom974** [comment]
rest van de issues gefixt na de herstart.
