### ISSUE TITLE
[FEATURE]: KNRM toevoegen aan brandweer & 2 kleine bugs

### ISSUE THREAD

**Issue by JeroenKla** [Tedeapolis/development#2254]
### Contact Details

AvocBe#0125

### Wat gebeurde er?

We ondervinden nog enkele probleempjes 

- [x] KNRM meldingen kunnen niet ingame afgevinkt worden
- [x] Mogelijkheid de in de stad zijnde boot trailer ook voor ons beschikbaar te maken aangezien wij soms op verplaatsing met de boot gaan

**Extra**: Brandweer  zou deze job ook moeten hebben we zitten nu dus met een probleem dat als zij deze rang hebben dan kunnen zij hun brandweer rang niet meer uitvoeren. We zitten ook wat vast hoe we dit nu moeten oplossen. 

**Brandweer**

- [ ] KNRM rangen ook toevoegen aan de brandweer job
- [ ] met sloten van het KNRM gebouw
- [ ] EUP van KNRM
- [ ] toevoeging barricade aan brandweer F6
- [ ] Niet kunnen geflitst worden met de knrm voertuigen

### Wat hoorde er te gebeuren?

- [x] de binnekomende meldingen in de gsm ook kunnen afvinken

Brandweer

 dit lost het probleem van de knrm en de brandweer op 

### Wat veroorzaakt de bug?

/

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zijn alle dingen op dit lijstje getest? want het niet geflitst kunnen worden bvb zit er al 4 maanden in.

**Comment by JeroenKla** [comment]
Ik ga het eens bekijken ik zie net met het testen dat er al zaken aangepast zijn ondertussen

**Comment by JeroenKla** [comment]
meldingingen afvinken is nog niet mogelijk in game

**Comment by JeroenKla** [comment]
@Tom974 de boot trailer is nog niet mogelijk om te nemen ik dacht dat ik het voorbij had zien komen dat dit er in zat :)

**Comment by JeroenKla** [comment]
@Tom974 in de offroad ambulance van de knrm kan er oij geen brancard in gelegd worden is dit mogelijk om dit aan te passen dat dit ook lukt.
