### ISSUE TITLE
[FEATURE]: Brandweer / ANWB toegang

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2255]
### Contact Details

destefanokiller

### Goedgekeurd door

destefanokiller

### Beschrijf zo duidelijk mogelijk de feature

- [x] In-dienst brandweer mogelijkheid geven om de hulpdiensten deur bij ANWB open en dicht te doen. 

- [ ] Als in-dienst brandweer ANWB melding maakt dat deze melding in #meldkamer-overheidsdiensten komt in plaats van de normale ANWB meldkamer.

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
niet meer van toepassing
