### ISSUE TITLE
[FEATURE]: Side Job Justitie

### ISSUE THREAD

**Issue by aimabel** [Tedeapolis/development#2258]
### Contact Details

aimabel

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Binnen de Justitie hebben we onze eigen ramenwasser waarbij je de documenten van je cliënten ophaalt, hiervoor krijg je aparte kleding en al. Alleen merk ik dat vrijwel niemand die kleding gebruikt. 

Dit side job start je door in een circle te staan en je kleding aan te doen voor je werk. (Bij de vrouwen is die atm bugged.) Zodra je de kleding aan hebt moet je naar buiten om de justitie voertuig te pakken en pas dan krijg je een marker voor je side job. 

Hierbij merk ik toch wel dat de meeste geliever met hun eigen voertuig rijden dan de justitie auto.

De vraag is dan natuurlijk of jullie dit kunnen aanpassen voor ons. Het zou fijner zijn als we de side job kunnen starten zoals bij ramenwassen. Je drukt dan op de DELETE en je krijgt een gps naar je locatie.

Voor de auto hebben we al een garage aan de rechterkant van het gebouw, als de Volvo samen bij de KVK auto zou kunnen wordt het makkelijker. Voor de mensen die toch ik de Justitie voertuig wilt rijden kunnen dan uit die garage het voertuig ophalen. 

### Wat lost deze feature op?

Hierbij heb je minder onnodige circles bij de Justitie, minder onnodige garages en makkelijker toegang voor de side job. Hierbij haal je ook de bugs voor kleding weg als de nummertjes binnen de TDA kleding kast weer kapot gaan.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by JustitieTDA** [comment]
Mag genegeerd worden, geen toestemming voor het aanmaken van deze github ;p

**Comment by Attomn** [comment]
> Mag genegeerd worden, geen toestemming voor het aanmaken van deze github ;p

nvm
