### ISSUE TITLE
[EUP]: Justitie Steekvest

### ISSUE THREAD

**Issue by aimabel** [Tedeapolis/development#2259]
### Contact Details

aimabel

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Gelieve ook een Justitie steekvest voor de vrouwen in de /eup. 

Ik merk als ik soms op de politie hoofdbureau kom dat er gijzelingen zijn, daarbij zou ik dan voor de roleplay mijn steekvest willen gebruiken zoals mijn collega’s het doen. 
Alleen dat lukt niet echt als de vrouwen geen een hebben Q_Q!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
zit erin na de restart
