### ISSUE TITLE
[FEATURE]: Taxi - Aanpassing Aston Martin DBX

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#2261]
### Contact Details

timez.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Momenteel hebben wij de Aston Martin DBX ter beschikking. Helaas biedt dit voertuig ons niet wat wij nodig hebben bij de Taxi. Het is namelijk zo dat dit voertuig dient als off-road voertuig alleen is de performance off-road niet al te best, dit omdat het voertuig stock is. 

**Wat hebben wij nodig?** 
Wij zouden graag zien dat dit voertuig fully wordt gemaakt. Dit zodat wij de performance die deze fully kan bieden kunnen gebruiken voor diensten die wij off-road moeten leveren. Niet alleen voor taxi ritten maar ook voor Marketing evenementen die te maken hebben met off-road terrein. Het voertuig hoeft overigens niet persé de fully snelheid te krijgen, dit kan wat dat betreft de stock snelheid behouden.

Hierbij ook 2 video's die de huidige performance van het voertuig kunnen tonen

Video 1 (stock): https://medal.tv/games/gta-v/clips/1cZKwyXF9O_bNL/d1337gOo9A5X?invite=cr-MSxiSmIsNDg1Nzc3ODMs

Video 2 (fully): https://medal.tv/games/gta-v/clips/1cZKIit1Wip1X7/d1337EB8jcxX?invite=cr-MSxDeUQsNDg1Nzc3ODMs

### Wat lost deze feature op?

Deze feature zal oplossen dat wij bij de Taxi zonder enige moeite altijd een off-road voertuig ter beschikking hebben. Het komt namelijk redelijk vaak voor dat wij off-road moeten gaan voor bepaalde doel einde. Dit zal dat stukje dan coveren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Is dit goedgekeurd door HR/HS? De vorige keer was dit namelijk afgekeurd en "Goedgekeurd door" is ook niet ingevuld.

**Comment by Tom974** [comment]
blijkbaar gedaan door niek dus deze kan gesloten worden
