### ISSUE TITLE
[FEATURE]: Tank inhoud Borent Bus

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2263]
### Contact Details

dyon.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Er kwam een suggestie langs op de reddit over de inhoud van een borent bus. Deze zit op het moment op 65 Liter. 

Ik denk dat dit wat aan de lage kant is aangezien dit het zelfde aantal liters is als wat er atm in een Hayabusa gaat. 
Ik denk persoonlijk dat 75/80 wat meer aan de logische kant is voor een borent bus, ook omdat mensen hier soms uren in rijden.

### Wat lost deze feature op?

Wat logischere tank inhoud voor een borent bus

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ga ik niet aanpassen. Tank is prima zo, helaas maar eventjes wat vaker tanken.

Dan kan ik beter de tank van de hayabusa verlagen.

**Comment by Dyon033** [comment]
> Ga ik niet aanpassen. Tank is prima zo, helaas maar eventjes wat vaker tanken.
> 
> Dan kan ik beter de tank van de hayabusa verlagen.

Prima 🫡
