### ISSUE TITLE
[EUP]: Vrouw EUP DSI Noodhulp Vest

### ISSUE THREAD

**Issue by Ssaannddyy1** [Tedeapolis/development#2264]
### Contact Details

sandyy

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Na de restart is het Noodhulp Vest in vrouw eup gebugged geraakt waardoor hij nu niet meer aankan. Waarschijnlijk is hij door de restart veranderd van nummer in de kleding winkel is het mogelijk dat dit weer aangepast kan worden? Momenteel als ik deze namelijk aan doe is hij onzichtbaar. 

Nieuw Nummer Kogelvrij vest : KogelVrijVest 11 

![Github Issue1](https://github.com/Tedeapolis/development/assets/143293216/2eab1906-0d8e-4176-824c-14dd12816def)
![Github Issue 2](https://github.com/Tedeapolis/development/assets/143293216/903bd17a-2bcf-45db-8943-fae853bc182e)
![github issue3](https://github.com/Tedeapolis/development/assets/143293216/3006ffc0-5f78-447b-a573-e4b8237787c8)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Woopsie had hem inderdaad verplaatst, is gefixt na de restart
