### ISSUE TITLE
[FEATURE]: Stuntvliegtuig in de "Vlieginstructeurs Garage"

### ISSUE THREAD

**Issue by Smokjertje12** [Tedeapolis/development#2268]
### Contact Details

smokertje12

### Goedgekeurd door

Flightschool Leiding

### Beschrijf zo duidelijk mogelijk de feature

Deze feature zou een stuntvliegtuig | de WESTERN MALLARD | toevoegen aan het voertuig arsenaal van de vlieginstructeur. 
Deze zou dan in te spawnen zijn zoals de andere vlieginstructeurs voertuigen.
![Screenshot 2023-09-27 213535](https://github.com/Tedeapolis/development/assets/86876080/bb8082e7-0a84-41b8-8e6b-f2212f7c566c)

### Wat lost deze feature op?

Momenteel is een stuntvliegtuig niet beschikbaar vanwege dat stuntbrevetten pas later zijn ingevoerd. Uiteindelijk zijn deze nooit toegevoegd geweest en zou deze issue daar een einde aan brengen. 

Hierdoor zou een instructeur niet meer zelf een stuntvliegtuig moeten aanschafen maar kan hij deze spawnen zoals hoort.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik heb geen flauw idee wat de spawnnaam van de mallard is @Smokjertje12, kun je die hier posten?

**Comment by Tom974** [comment]
Heb nu het vliegtuigje met model "stunt" toegevoegd, hoop dat het de goeie is.

**Comment by Smokjertje12** [comment]
> Ik heb geen flauw idee wat de spawnnaam van de mallard is @Smokjertje12, kun je die hier posten?

Stunt is de juiste denk ik, thx!
