### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by bdweerd** [Tedeapolis/development#2269]
### Contact Details

burbbie

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In het echt wanneer er iets gebeurd op een luchtmacht basis, denk aan landen, opstijgen of een flyby gaat er een bel af. (VB: https://streamable.com/5g5uwy) Voor in TDA leek mij dit ook een leuk idee. Dit omdat de baan dan vrij gemaakt kan worden zodat er een veilige landing ingezet kan worden. Vaak zijn er trainingen op de legerbasis van de Kmar of Politie en wordt daarbij de runway gebruikt wat voor gevaarlijke situaties kan zorgen. 

Zie dit een beetje hetzelfde als het /alarm_off - /alarm_on systeem bij de legerbasis maar dat er dan een bel afgaat in plaats van een alarm. Daarnaast geeft het ook weer een extra sfeerimpressie voor de mensen die zich dan bevinden op de legerbasis.

### Wat lost deze feature op?

- Onnodige ongelukken op de legerbasis tussen toestellen en andere eenheden.
- Een extra stukje ervaring

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Lijkt me niet echt handig kwa hoe TDA zelf werkt, overigens ook niet iets wat echt vaak voorkomt in een rolepaly scenario.
