### ISSUE TITLE
F6 menu Justitie

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#227]
Hai!

We hebben momenteel een F6 menu bij Justitie. Iedereen vanaf advocaat heeft de mogelijkheden om mensen te boeien, fouilleren e.d.

Ik vermoed dat dat niet gewenst is (eventueel voor de OvJ / Minister dan nog, maar voor de normale advocaten zéker niet)

Kunnen jullie daar wat mee?

**Comment by Willem-Dekker** [comment]
is uit gezet
