### ISSUE TITLE
[FEATURE]: Nieuwe Peds voor Bark! Polis

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2270]
### Contact Details

dyon.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij bij Bark! Polis gaan op het moment meerdere keren per week open, echter kunnen bij me de huidige peds niet de RP wensen van iedereen vervullen. In het verleden is ons ooit verteld dat we nieuwe peds konen aanvragen in de toekomst en bij deze zou ik dat ook willen doen (als dit nog kan). 

Ik heb een paar linkjes van gratis peds & betaalde peds. De peds die betaald zijn die betaal ik uiteraard zelf.
- https://www.gta5-mods.com/player/french-bulldog-addon-replace
- https://www.gta5-mods.com/player/goats-mod-for-gta-5-replace
- https://nl.gta5-mods.com/player/greyhound-dog-replace
- https://www.gta5-mods.com/misc/chop-to-german-shepherd
- https://www.gta5-mods.com/player/pit-bull-replace
- https://www.gta5-mods.com/player/new-textures-for-rabbit
- https://future.tebex.io/package/5643064

### Wat lost deze feature op?

Meer diversiteit in de peds.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Was dit goedgekeurd door staff @ExoticaTDA ?

**Comment by Tom974** [comment]
Gesloten ivm geen reactie
