### ISSUE TITLE
[FEATURE] /docu verwijder documenten

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2272]
### Contact Details

calray

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Als je /docu doet hebben heel veel hOvJ’s enorm veel documenten bij /docu en om ze allemaal weg te krijgen moet je ze één voor één verwijderen. Mijn vraag was is het mogelijk om meerdere documenten te selecteren en te kunnen verwijderen?

### Wat lost deze feature op?

Heel veel hOvJ’s zouden het appreciëren als dit mogelijk zou zijn.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
onnodig veel werk voor mij
