### ISSUE TITLE
[FEATURE]: Brandweer aanpassingen

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#2273]
### Contact Details

Daan de Wit#8441

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Hoi hoi, vanuit brandweer leiding het verzoek op de volgende features:

- 

- [x] Voor alle brandweer rollen acces tot /neckbrace (ID). Dit omdat de brandweer veel ingezet wordt in TDA voor THV (Technische hulp verlening)

- 

- [x]  Mercedes Vito, we hebben nu de Golf voor de leiding en niet voor iedereen. We willen graag een vito zodat ook de medische meldingen sneller opgepakt kunnen worden. Het voertuig voor de normale brandweerlieden is de TS en die rijd max 120.

Daarop gelijk:

- [x] de brandweer FE320 auto max 170 laten lopen indien mogelijk. Vooral voor de lange afstanden zoals Sandy etc.

- [x]  Kan er aan de EUP een bodycam toegevoegd worden, dit omdat brandweerlieden dit graag willen ivm veel samenwerking scenarios voor overheids instanties

- [ ] Brandweer pasje, voorbeeld zal ik later toevoegen hierin, maa Politie pas maar dan brandweer (zal dit zelf maken).

- [x] Uitdienst loon:

Stagaire: 1
Aspirant: 150
Brandwacht: 250 
Hoofdbrandwacht: 400
Brandmeester: 500
Hoofdbrandmeester: 600
Commandeur: 650
Adjunct Hoofd Commandeur: 700
Hoofd commandeur: 750

### Wat lost deze feature op?

Staat boven erbij beschreven

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Over de Vito, daar is de golf juist voor bedoeld lijkt me. Als je die wilt veranderen naar alleen leiding sure, maar ik denk niet dat er een nieuwe toegevoegd gaat worden (also looking at @Lorenzo3001 )

**Comment by DevvTDA** [comment]
Uitdienst lonen zijn gefixt :)

**Comment by DevvTDA** [comment]
bodycam ook

**Comment by DaanDeW** [comment]
> Over de Vito, daar is de golf juist voor bedoeld lijkt me. Als je die wilt veranderen naar alleen leiding sure, maar ik denk niet dat er een nieuwe toegevoegd gaat worden (also looking at @Lorenzo3001 )

nee is ook te begrijpen, thanks voor het terugkoppelen!

**Comment by Tom974** [comment]
Moest dat pasje nog gedaan worden @DaanDeW ?

**Comment by DaanDeW** [comment]
> Moest dat pasje nog gedaan worden @DaanDeW ?

Yess, deze staat in de github van @BrandweerTedeapolis

**Comment by DaanDeW** [comment]
> Moest dat pasje nog gedaan worden @DaanDeW ?
![image](https://github.com/Tedeapolis/development/assets/32983383/e3e5c54e-73fe-4d16-8a11-cefbc4ffe985)

**Comment by Tom974** [comment]
top, zit er in na de herstart!
