### ISSUE TITLE
[EUP]: cargo helm pak 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2274]
### Contact Details

CalRay#1513

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

![image](https://github.com/Tedeapolis/development/assets/101106299/2305efda-ccf4-4702-a67d-1aa81f684d16)
![image](https://github.com/Tedeapolis/development/assets/101106299/da894456-c4db-416f-b34f-8d62b909a6b9)
![image](https://github.com/Tedeapolis/development/assets/101106299/895c6048-6e9b-43d1-97c1-49fa3d121747)
![image](https://github.com/Tedeapolis/development/assets/101106299/26086554-b472-4051-a846-a0018b06672d)
We kunnen nu sinds kort met "K" een mooie menu openen, maar helaas als we onze helm omdraaien wordt die groen, is het mogelijk dat hij hetzelfde kleuren en stijl als huidige helm wordt. Zie screenshots. @DevvTDA 🥺 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
uhh wat is een K en weet je de nummers toevallig of hoe deze in het eupzich noemt ? @CalRayy

**Comment by Tom974** [comment]
> uhh wat is een K en weet je de nummers toevallig of hoe deze in het eupzich noemt ? @CalRayy

Je kunt sindskort via het K menu (kleding wheel) je helm togglen naar een andere variant. Wat calray dus eigenlijk vraagt is of dezelfde dsi helm toegevoegd kan worden maar dan met de vizieren voor je ogen :P

**Comment by CalRayy** [comment]
Yes, wat tom bedoeld idd 🫣

**Comment by DevvTDA** [comment]
ik krijg deze niet gevonden kan hjelaas dus niets voor betekenen
