### ISSUE TITLE
[EUP]: Bijzonder Ondersteunings Team

### ISSUE THREAD

**Issue by Tomtommer21** [Tedeapolis/development#2276]
### Contact Details

tomtommer

### Goedgekeurd door

devv4532

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Binnen Eerste Hoofdcommissaris het EUP onderdeel Bijzonder Ondersteunings Team (BOT) toevoegen. Devv heeft een schermafbeelding van het EUP onderdeel die toegevoegd moet worden. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart
