### ISSUE TITLE
[EUP]: Rechter Toga verkeerde broek. 

### ISSUE THREAD

**Issue by Tomtommer21** [Tedeapolis/development#2277]
### Contact Details

tomtommer

### Goedgekeurd door

devv4532

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

![image](https://github.com/Tedeapolis/development/assets/146876614/378fed03-fb9b-4df0-b3de-674a8c6aad5a)

Denk dat de afbeelding al wel voldoende zegt. Maar waar het op neer komt, de broek van de Rechter is eerder de brandweer broek.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart
