### ISSUE TITLE
Motors repareren werkt niet

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#228]
Ik krijg van ANWB'ers klachten binnen over dat als zij een motor willen repareren via het f6 menu dat het voertuig dan niet wordt gerepareerd.

Hoe gaan ze tewerk 

- F6 menu openen bij het voertuig
- Op repareren klikken
- En dan gebeurd er niks kijk video:

https://www.youtube.com/watch?v=bnGfTYiV6vs&ab_channel=DeStefanoKiller

Hopelijk kun je iets met deze info.

**Comment by Willem-Dekker** [comment]
can not repro en heb dit net getest en het werkt gewoon. heb een bmws in de prak gereden en kon hem nog gewoon repareeren.
