### ISSUE TITLE
[FEATURE]: Gangopslag kluisjes

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2280]
### Contact Details

iHax0r#3736

### Goedgekeurd door

Burgerraad 09/10/2023

### Beschrijf zo duidelijk mogelijk de feature

Het idee kluisjes is heel simpel, je hebt momenteel 1 opslag waar alle items in gedumpt worden. Dit is zeer onoverzichtelijk, dus dit proberen we met een sheet bij te houden. 
Alleen hierbij komen veel problemen kijken, zoals dat een klein foutje in onze administratie een totale onoverzichtelijkheid creëert.

Daarnaast gebruiken we nu voertuigen als een soort van privé kluis voor je eigen clips etc, in plaats hiervan willen we naast de opslag een extra menu kluisjes.

Hierin kan je een kluisje 1 t/m 25 aanklikken, zodat je spullen zelf kan ordenen. Zo is het aan de gang om hier zelf een onderverdeling in te maken. Daarnaast behouden we de grote gezamenlijke kluis voor de algemene POT.

Alle kluisjes zijn toegankelijk door de permissie van spullen uit de pot pakken, dit om ervoor te zorgen dat het niet een extra beveiliging word. Het is puur voor overzicht binnen de groep, zoals je in je huis ook aparte vakjes kan maken voor spullen.

Dit puntje is goedgekeurd in de laatste Burgerraad.

### Wat lost deze feature op?

Zo kan iedereen zijn eigen privé spullen makkelijk apart houden, zonder dat het op een grote berg gegooid word.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Status: Flinke rewrite gedaan van plugin, implementatie zo goed als af.
