### ISSUE TITLE
[EUP]: K9 diensthonden vest

### ISSUE THREAD

**Issue by justdogamingNL** [Tedeapolis/development#2282]
### Contact Details

justdogamingnl

### Goedgekeurd door

lamine 

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Wij hebben bij de hondengeleiders van de politie, geconstateerd dat de diensthond door veel te veel mensen geaaid wordt. Wij willen minder geweld inzetten en zijn tot de conclusie gekomen dat een waarschuwing op het vest van de diensthond met de tekst 'NIET AAIEN' hierin zou helpen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@DevvTDA is dit iets wat je wilt/kunt oppakken of ? Anders kun je de issue terug aan mij asignen

**Comment by DevvTDA** [comment]
@Tom974 heb echt geen idee :P

**Comment by Tom974** [comment]
@justdogamingNL als je er zelf een vest voor kunt maken in die ped vind ik het prima, anders zal het hem helaas niet worden.

**Comment by DaanDeW** [comment]
Nieuwe K9 zit er in na restart
