### ISSUE TITLE
[FEATURE]: Nieuwe text bij command

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#2283]
### Contact Details

dead123x5

### Goedgekeurd door

Niek

### Beschrijf zo duidelijk mogelijk de feature

Wanneer je "/givecarkeys" doet dat er komt te staan wat je er bij moet schrijven.

Voorbeeld:
https://prnt.sc/F3ePI_v_CaX3

### Wat lost deze feature op?

Dit lost het op dat mensen weten hoe ze de command volledig moeten uitvoeren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
heh, dacht dat ik dat allang  had toegevoegd

**Comment by DevvTDA** [comment]
@Tom974 niet dus 🫠

**Comment by Tom974** [comment]
Staat wel in de code zie ik nu (zoals ik al dacht), blijkbaar is het dus in het algemeen dus stukkie wukkie ofzo

**Comment by Tom974** [comment]
![image](https://github.com/Tedeapolis/development/assets/55812394/94c8685b-86d8-47d9-b9d3-f8e486d54693)
Fixed na herstart, blijkbaar moet je die suggesties pas inladen nadat de speler volledig ingeladen is.
