### ISSUE TITLE
[FEATURE]: Toevoeging van de "Buckingham Miljet" | aan de flightschool LEIDING garage

### ISSUE THREAD

**Issue by Smokjertje12** [Tedeapolis/development#2284]
### Contact Details

smokertje12#2488

### Goedgekeurd door

[TDA] Joris[⌛](https://emojipedia.org/hourglass-done)

### Beschrijf zo duidelijk mogelijk de feature

Deze feature zou de grootste jet | de Buckingham Miljet (spawnaam: miljet) | toevoegen aan het voertuig arsenaal van ALLEEN flightschool leiding. 
Deze zou dan in te spawnen zijn zoals de andere vlieginstructeurs voertuigen. 
![image](https://github.com/Tedeapolis/development/assets/86876080/086801b7-c48a-4916-b7dd-348ee6536768)

### Wat lost deze feature op?

Deze feature zou de mogelijkheid bieden voor de Flightschool om deze jet uit te lenen aan bedrijven op aanvraag in een flightschool ticket, deze bedrijven zouden deze jet dan voornamelijk gebruiken bij bedrijfsuitjes en dergelijke events. 

De voornamelijkste reden van de feature zou dan ook zijn dat een grote jet met veel personen capaciteit gebruikt zou kunnen worden voor events van bedrijven in de stad. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Smokjertje12** [comment]
Spawnaam: miljet
Discord Role Id FS leiding: 747466741277392956

**Comment by Tom974** [comment]
Waarom koop je er niet gewoon eentje dan? Komt bij mij een beetje over als een gratis jet inspawnen namelijk.

**Comment by Smokjertje12** [comment]
> Waarom koop je er niet gewoon eentje dan? Komt bij mij een beetje over als een gratis jet inspawnen namelijk.

Word gezien als een manier voor bedrijven om deze te kunnen gebruiken voor hun evenement aangezien deze momenteel niet tekoop is als ik het goed heb? Heb hem namelijk alleen nog maar ingespawned gezien.

**Comment by Tom974** [comment]
Ja, deze kun je gewoon kopen. 
![image](https://github.com/Tedeapolis/development/assets/55812394/5b7ce29d-eeb9-455c-a4cc-ac5a02a01605)

**Comment by Smokjertje12** [comment]
> Ja, deze kun je gewoon kopen. ![image](https://user-images.githubusercontent.com/55812394/275290858-5b7ce29d-eeb9-455c-a4cc-ac5a02a01605.png)

Top! Dan wacht ik even af op wat Joris er in dat geval dan van vind.

**Comment by Lorenzo3001** [comment]
> Top! Dan wacht ik even af op wat Joris er in dat geval dan van vind.

Is hier inmiddels al meer duidelijkheid over?
