### ISSUE TITLE
[FEATURE]: ID's toevoegen bij mensen die de stad verlaten

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2286]
### Contact Details

CalRay#1513

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Als iemand uitlogd dat je bij het drukken van "Z" nog altijd een ID ziet. 

### Wat lost deze feature op?

Combatloggers melden of makkelijker aan te kunnen pakken. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Coolcooli** [comment]
Zit erin na restart
