### ISSUE TITLE
[EUP]: Brandweer toevoegingen EUP

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#2288]
### Contact Details

_Daan de Wit_

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Toevoeging aan EUP 

Volledige outfit (Medische Outfit)
Deze outfit is voor medische melding, Brandweer is verplicht in hun uitruk uniform aan te hebben bij een melding, om het gemakkelijker te maken voor de medische hulp krijgen wij veel vragen uit de brandweerlieden om een tussen weg te vinden.
Outfit:
![image](https://github.com/Tedeapolis/development/assets/32983383/548269de-6cc1-4f13-bc68-8e3347be0a11)
T-Shirt 1 : 15
Torso 1: 131
Armen: 85
Broek 1: 120
Broek 2: 1
Schoenen: 51

Losse toevoegingen:
Medische tas: 
T-shirt1 : 8
T-Shirt2: 0

Daarbij was het verzoek of de brandweer broeders een armband konden krijgen zoals de politie, aangezien dit in real life ook bij de brandweer een ding is en we veel echte brandweer lieden hebben, als dit mogelijk is zou top zijn.
![image](https://github.com/Tedeapolis/development/assets/32983383/cbae8e3f-6dd5-434e-976d-6f90cb586c18)
Dit is de foto van de politie, ons verzoek is dezelfde maar dan met rood. In de keuze menu staan er 2 en allebei zijn ze atm blauw. 

Voor afwerking:
- [ ] Medische outfit

- [ ]  Medische tas

- [ ] Brandweer bandje?? 

Alleen als het mogelijk is allemaal :))

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
na de restart zit de outfit erin vind de  armband niet en lijkt me niet heel bijzonder tbh.
