### ISSUE TITLE
[FEATURE]: ANWB Aparte voorrijkosten factuur

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2289]
### Contact Details

mrmartin02

### Goedgekeurd door

destefanokiller

### Beschrijf zo duidelijk mogelijk de feature

De regels over schepwagens van de ANWB zijn recent aangepast waardoor er niet meer 'on the spot' gerepareerd kan worden, omdat schepwagens niet uitgerust zijn met gereedschap. Voertuigen kunnen alleen nog getakeld en afgesleept worden naar ANWB locaties, maar soms gaan klanten hier niet mee akkoord. Wij zijn dan al ter plaatse met een schepwagen, maar omdat ze geen zin hebben in het afslepen van hun voertuig, weigeren ze onze hulp. Dat mag, maar dan willen wij ze wel graag een voorrijkosten factuur kunnen sturen.

**De volgende facturen hebben wij hiervoor nodig:**
Voorijkosten binnen de stad - Auto €300
Voorijkosten buiten de stad - Auto €400
Voorijkosten binnen de stad - Motor €150
Voorijkosten buiten de stad - Motor €200

Deze facturen kunnen onder het kopje 'Extra' komen van ANWB Facturen in het F6 menu.

### Wat lost deze feature op?

Het onnodig laten rijden van een schepwagen en de verloren tijd dat de collega niet naar een andere melding kon, doorbereken naar de klant.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
zit er als het goed is na de restart in, indien dit niet zo is, mag je me DMen op discord.
