### ISSUE TITLE
Nieuwe vlieginstructeurs

### ISSUE THREAD

**Issue by LeoRageKiller** [Tedeapolis/development#229]
Voor de twee nieuwe vlieginstructeurs graag de mogelijkheid geven van /giveflylicense en helikopters toe te voegen aan in hun garages. Bij voorbaat dank. 
Betreft:
- [x] LeoRageKiller#7916 | 402084698014220290 | https://admin.tdafivem.nl/user/license:a070cd7a8bc164f618d4a584b81ec0fadd2dc00d

- [x] robin.v.game#1222 | 308316456137916417 | https://admin.tdafivem.nl/user/license:6a018c971bd24984c840a33ad4ee7cec262c5d52

**Comment by Willem-Dekker** [comment]
done na restart van server is het gedaan
