### ISSUE TITLE
[EUP]: Gasmasker toevoegen aan KMAR EUP.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2290]
### Contact Details

Larrsss#3819

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag willen we binnen de KMAR het gasmaker in het EUP menu. (Bijvoorbeeld onder het kopje ''Kmar accessoires'')

Dit moet voor de volgende rangen:
kmar 0 | Marechaussee - der 3e klasse
kmar 3 | Marechaussee - der 2e klasse
kmar 5 | Marechaussee - der 1e klasse
kmar 10 | Marechaussee - Wachtmeester
kmar 15 | Marechaussee - Wachtmeester der 1e klasse
kmar 20 | Marechaussee - Opperwachtmeester
kmar 25 | Marechaussee - Adjudant
kmar 30 | Marechaussee - Tweede-Luitenant
kmar 35 | Marechaussee - Eerste-Luitenant
kmar 40 | Marechaussee - Kapitein
kmar 45 | Marechaussee - Majoor
kmar 50 | Marechaussee - Luitenant-Kolonel 
kmar 51 | Marechaussee - DJI - Aspirant
kmar 52 | Marechaussee - DJI - Junior Beveiliger
kmar 53 | Marechaussee - DJI - Medior Beveiliger
kmar 54 | Marechaussee - DJI - Senior Beveiliger
kmar 56 | Marechaussee - DJI - Adjudant
kmar 57 | Marechaussee - DJI - Commandant
kmar 58 | Marechaussee - DJI - Operationeel Directeur
kmar 59 | Marechaussee - DJI - Algemeen Directeur
kmar 60 | Marechaussee - Kolonel
kmar 70 | Marechaussee - HRB - Aspirant
kmar 71 | Marechaussee - HRB - Operator
kmar 72 | Marechaussee - HRB - Groepscommandant
kmar 73 | Marechaussee - HRB - Sectiecommandant
kmar 74 | Marechaussee - HRB - Commandant
kmar 80 | Marechaussee - DSI Soldaten
kmar 81 | Marechaussee - DSI Korporaals
kmar 82 | Marechaussee - DSI Onderofficieren
kmar 83 | Marechaussee - DSI Officieren
kmar 85 | Marechaussee - B - Recherche Junior
kmar 86 | Marechaussee - B - Recherche
kmar 87 | Marechaussee - B - Recherche Senior
kmar 88 | Marechaussee - B - Recherche Leiding
kmar 90 | Marechaussee - Brigadegeneraal
kmar 95 | Marechaussee - Generaal Majoor
kmar 100 | Marechaussee - Luitenant Generaal

gaat om ''Masker 175'' in de kleding winkel.
![image](https://github.com/Tedeapolis/development/assets/112424697/b7aac393-a1d6-49fc-894f-d6cd49ecbb05)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Ik ga ze niet specifiek voor die rangen zetten ik zet het er wel gewoon in onder inderdaad kmar accesoires, heb je ook het nummertje van de vrouwen ? @KMarTDA

**Comment by DevvTDA** [comment]
zit er in na de restart
