### ISSUE TITLE
[FEATURE]: Cirkels nieuwe brandweer gebouw

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#2292]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Nieuwe cirkels voor brandweer gebouw:

In / uitdienst klokken brandweer job op coordinates:
X 193.58 / Y -1648.61 / Z 29.80 / H 319.01
![image](https://github.com/Tedeapolis/development/assets/32983383/d14b49cd-4769-49b3-8c2e-4a3a9afe3254)

Omkleed cirkel:
X 190.14 / Y -1644.43 / Z 33.36 / H 240.58
![image](https://github.com/Tedeapolis/development/assets/32983383/3f735c96-c7e4-4bba-b99b-5f699b850bfd)

Bossmenu brandweer:
X 200.76 / Y -1635.32 / Z 33.36 / H 140.66
![image](https://github.com/Tedeapolis/development/assets/32983383/eaaaec98-76a0-4d99-8454-12fc865f60e5)

Voertuig WEGzet cirkel:
X 174.39 / Y -1659.02 / Z 29.80 / H 252.98
![image](https://github.com/Tedeapolis/development/assets/32983383/67c6affe-970d-45d8-9bcf-c3876e60a776)

DEUR SLOT (alle brandweer rangen)
![image](https://github.com/Tedeapolis/development/assets/32983383/0ca9d6cd-7b7b-463a-8d11-fde6c60648aa)

DEUR SLOT ALLE RANGEN
![image](https://github.com/Tedeapolis/development/assets/32983383/d68e214f-4fc7-41ff-a1e4-e623c4a81b9b)

DEUR SLOT ALLE RANGEN
![image](https://github.com/Tedeapolis/development/assets/32983383/f5991416-a5b3-47d8-b411-d61327894999)

DEUR SLOT ALLE RANGEN
![image](https://github.com/Tedeapolis/development/assets/32983383/5e28f769-c7b3-426e-9a0e-394f7c0b82af)

DEUR SLOT COMMANDEUR RANG< ADJUCANT COMMANDEUR EN HOOFDCOMMANDEUR
![image](https://github.com/Tedeapolis/development/assets/32983383/66283ff6-ce64-48f3-8f7a-834db9310552)

### Wat lost deze feature op?

nieuwe brandweer gebouw

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
slot per rang ga ik neit doen ivm dat die plugin daar momenteel geen functionaliteit voor heeft, verder is done
