### ISSUE TITLE
[FEATURE]: Als je iemand fouilleert dat degene ook gefreezed wordt

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2293]
### Contact Details

calray

### Goedgekeurd door

Staffoverleg een tijdje terug

### Beschrijf zo duidelijk mogelijk de feature

Als je iemand fouilleert dat degene ook gefreezed wordt dan heb je geen situaties waarbij mensen NVOL plegen.

### Wat lost deze feature op?

Vermijden van mensen die NVOL plegen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
waar zijn labels men

**Comment by CalRayy** [comment]
> waar zijn labels men

Sorry hahaha

**Comment by TedeaTaxi** [comment]
Soms fouilleren mensen elkaar in de auto wat gebeurd er als je dan iemand freezed/fouilleert? 

En het misbruik maken dat je iemand kan fouilleren die in de auto zit en hem dus "kan vast zetten zonder boeien" dus gewoon naast de bestuurder staan en fouilleren en op die manier wachten op mensen met meer wapens

**Comment by DevvTDA** [comment]
Uhh dat is niet toegestaan :P @TedeaTaxi

**Comment by Tom974** [comment]
Denk dat we beter de mensen die niet meewerken kunnen afstraffen door middel van sancties, ipv dit te implementeren. Het is nogal kut om te maken en zal (te veel) werk in gaan zitten.
