### ISSUE TITLE
[FEATURE]: Brandweer toevoegingen / aanpassingen

### ISSUE THREAD

**Issue by BrandweerTedeapolis** [Tedeapolis/development#2294]
### Contact Details

JeffreyNL

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Wij hebben een korpsoverleg gehad en daar zijn de volgende punten uit gekomen:

- [x] Wij worden met de brandweerauto ingehaald door scooters, dit is nogal onrealistisch. Daarnaast duurt het een eeuwigheid om vanuit de kazerne naar het noorden te rijden. Graag zien we dat de brandweerauto sneller gaat.
- [x] Brandweerlieden moeten zelf betalen voor de benzine die ze in de tank gooien. Graag zien we een tankpas waarbij het geld van de pot af gaat.
- [x] Brandweerlieden moeten zelf betalen voor de tol. Graag zien we een tolpas waarbij het geld van de pot af gaat.
- [x] Om incidenten af te schermen willen we graag toegang tot de afschermhekken waar de politie ook toegang tot heeft.
- [x] Graag willen we toegang tot de pijlhekken die de politie en ANWB ook hebben om verkeer te regelen.
- [x] Onze brandweerpas is op dit moment nog een perspas. Graag zien we een daadwerkelijke brandweerpas. Als deze ontwikkeld moet worden wil ik hier ook mijn steentje wel aan bijdragen. 
- [x] Tot slot: De brandweer heeft geen toegang tot de medische meldingen als er geen ambulance in dienst is, zoals de politie dat heeft. Wij willen hier graag ook toegang toe. Daarnaast heeft de politie leiding dit ook bij ons geopperd.

Voor vragen of hulp weet je me te vinden!

Thnx! - Jeffrey

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Door wie is dit allemaal goedgekeurd? Er staat namelijk "N.V.T."

**Comment by DaanDeW** [comment]
@Tom974 Medische meldingen is met politie besproken inderdaad; voor de rest heb ik aaran gevraagd even akkoord door te geven aan jou

**Comment by DevvTDA** [comment]
Goedgekeurd in superadmin + @Tom974

**Comment by BrandweerTedeapolis** [comment]
@Tom974 ik heb het pasje gemaakt, ben alleen even benieuwd of het zo mogelijk is met witte tekst.
![Brandweer pas wit](https://github.com/Tedeapolis/development/assets/145530665/189c647f-11a7-40ac-ada9-1d9c4a76b2c9)

**Comment by Tom974** [comment]
Voor het laatste puntje, ik heb er voor nu ff voor gezorgd dat als er 3 of minder brandweer is, dat de meldingen OOK naar de politie gaan, zodat deze ondersteuning kunnen bieden indien nodig.
