### ISSUE TITLE
[Bug]: kledingwinkel kledingkast

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2295]
### Contact Details

CalRay

### Wat gebeurde er?

Als je in een kledingwinkel je kledingkast opent en een outfit switch wordt je uit het menu gegooid i.p.v. door te kunnen scrollen in het kledingkast menu. 

### Wat hoorde er te gebeuren?

Je hoort gewoon door te kunnen scrollen en door te kunnen switch als je naar onder wilt gaan alleen wordt je uit het menu gegooid. 

### Wat veroorzaakt de bug?

Niet echt bekend, je wordt uit het menu gegooid als je in een kledingwinkel je kledingkast opent en een outfit switcht. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

/

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zal helaas niet gefixt kunnen worden, de kledingkasten zitten er overigens ook alleen in zodat je je outfits kun fixen indien kledingstukken aangepast worden, deze zijn "in principe" niet bedoeld als echte kledingkasten.
