### ISSUE TITLE
[Bug]: Geen geld uit kluizen

### ISSUE THREAD

**Issue by tdalynn** [Tedeapolis/development#2298]
### Wat gebeurde er?

Bij een aantal winkel overvallen geeft de kluis geen geld af. Het geld ligt er wel, maar het kan niet gepakt worden. 
Daarnaast bugged de Casino heist ook met de kluis (zie clip Twitch link) De kluis gaat niet open.

https://www.youtube.com/watch?v=HqexM9Cq3jQ (geen geld uit kluis)
https://youtu.be/EbGHRRYfzP0 (geen geld uit kluis)
https://www.twitch.tv/videos/1963581678?filter=highlights&sort=time (Casino heist bugg)

### Wat hoorde er te gebeuren?

Je hoort het geld te kunnen pakken en de kluis te kunnen openen

### Frequentie van de bug

1x per week

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zou nu gefixt moeten zijn
