### ISSUE TITLE
[FEATURE]: Aanpassingen voor DJI binnen de politie

### ISSUE THREAD

**Issue by JuanMax076** [Tedeapolis/development#2299]
### Contact Details

maxjuan

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Bij de politie hebben we nu ook DJI rangen. Echter kunnen wij niet de voertuigen pakken van de DJI en ook niet de voertuigen en wapens van de BOT. Ook hebben we nog geen sleutels van de uitvalbasis en zitten we nog zonder EUP. 

We hebben nieuwe rangen nodig voor de DJI net als die bij de KMAR.

Politie - DJI - Aspirant   - 1000 indienst - 500 uitdienst - DJI EUP
 Audi A6 + DJI sprinter

Politie - DJI - Junior beveiliger   - 1050 indienst - 525 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels

Politie - DJI - Medior beveiliger    -  1100 indienst - 550 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels

Politie - DJI - Senior beveiliger     -  1150 indienst - 575 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels

Politie - DJI - Adjudant       -   1200 indienst - 600 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels
 
Politie - DJI - Commandant      -  1300 indienst - 650 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels

Politie - DJI - Operationeel Directeur    -  1400 indienst - 700 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels

Politie - DJI - Algemeen Directeur    -  1500 indienst - 750 uitdienst -  DJI sprinter - DJI + BOT EUP - /fake_grade
SMG - Audi A6 - Range Rover - HK 416a5- BMW X5- S63 AMG - Uitvalsbasissleutels

Deze rangen hebben we nodig. Met deze rangen moeten we ook de normale noodhulp kunnen draaien. We moeten dus ook gewoon de noodhulp voertuigen, motoren en unmarked voertuigen kunnen pakken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by JuanMax076** [comment]
Pluspuntje! We moeten ook alle sleutels van de gevangenis hebben. Dit geld voor alle rollen.

**Comment by Tom974** [comment]
done
