### ISSUE TITLE
[FEATURE]: Staffoverleg - Criminele Items - Wide Receiver

### ISSUE THREAD

**Issue by Toro-Carri** [Tedeapolis/development#2300]
### Contact Details

Toro#5710

### Goedgekeurd door

STAFFOVERLEG

### Beschrijf zo duidelijk mogelijk de feature

**Item:** __*Wide Receiver*__
- Een item vergelijkbaar met de 'noodknop' van politie. Bij gebruik van dit item zal er naar iedereen (in de zelfde porto **of** zelfde ingame rang) een noodlocatie worden gestuurd. Het voorwerp kan een bepaald aantal keren worden gebruikt, tot deze vernietigd zal worden. Criminelen hebben vaak veel geld en dragen/gebruiken over het algemeen modernere apparatuur dan politie. In de roleplay zou dit dus ook goed passen.

### Wat lost deze feature op?

Hiermee wil ik de focus dus minder leggen op het rippen/beroven/schieten, maar meer richting de roleplay. Het bemachtigen van deze voorwerpen zal namelijk ook gaan doormiddel van roleplay (contacten leggen).

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done.
