### ISSUE TITLE
[FEATURE]: Voertuigen die op gestolen staan niet kunnen overschrijven.

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2303]
### Contact Details

iHax0r

### Goedgekeurd door

N.V.T. (Lijkt me logisch)

### Beschrijf zo duidelijk mogelijk de feature

Wanneer je voertuig op gestolen staat, kan je je voertuig niet overschrijven of gaat de gestolen status van je voertuig af. Dit omdat het niet echt mogelijk is om de eigenaar te veranderen indien die op gestolen staat.

Lijkt me niet dat hier goedkeuring voor nodig is, want is zeer onrealistisch.

### Wat lost deze feature op?

Dat random voertuigen op gestolen staan, zonder dat de eigenaar het weet. Tevens lijkt het me niet mogelijk om een gestolen voertuig van eigenaar te verwisselen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Haal dit even door staffoverleg :P

**Comment by Tom974** [comment]
Geen reactie meer op issue gekregen

**Comment by iHax0rMC** [comment]
> Geen reactie meer op issue gekregen

Kreeg gek genoeg geen melding, maar staat erin.

**Comment by iHax0rMC** [comment]
Goedgekeurd in staffoverleg @Tom974

**Comment by Tom974** [comment]
fixed na herstart
