### ISSUE TITLE
[EUP]: EUP BOT 

### ISSUE THREAD

**Issue by tdalynn** [Tedeapolis/development#2304]
### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Toevoegen EUP voor het BOT. Aangezien BOT nog geen aparte rangen heeft, graag op de volgende rangen toevoegen:
DJI - Junior beveiliger
DJI - Medior beveiliger
DJI - Senior beveiliger
DJI - Operationeel Directeur
DJI - Algemeen Directeur

**Heren**
**Sleeve mask:**
Nummer masker: 169
**Peltor:**
Nummer Helm 1: 148
Nummer Helm 2: 1

**Dames**
**Sleeve mask:**
Nummer masker: 169

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
@tdalynn  Als het goed is staan ze toch al op enkel BOT en   grades = {'boss', 'genmajoor', 'brigadegeneraal', 'hrb3', 'hrb4', 'hrb5'}, ? 
<img width="496" alt="image" src="https://github.com/Tedeapolis/development/assets/79802852/9f9d1333-1a0b-431d-b76a-123893e8b891">

**Comment by Tom974** [comment]
> @tdalynn Als het goed is staan ze toch al op enkel BOT en grades = {'boss', 'genmajoor', 'brigadegeneraal', 'hrb3', 'hrb4', 'hrb5'}, ? <img alt="image" width="496" src="https://user-images.githubusercontent.com/79802852/282712637-9f9d1333-1a0b-431d-b76a-123893e8b891.png">

waarom leak je code, wat doe jijjjjj

**Comment by Tom974** [comment]
Dit zit er al in.

**Comment by tdalynn** [comment]
Er zit al een masker en helm in indd, maar BOT leiding vraagt om extra. Momenteel zitten er andere maskers in. de peltor zit er niet in
