### ISSUE TITLE
[FEATURE]: /setped perms voor Bark! Polis Management.

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2306]
### Contact Details

dyon.

### Goedgekeurd door

Johan Dewus

### Beschrijf zo duidelijk mogelijk de feature

Johan en ik hebben besproken /setped perms voor de rang "dierenkliniek 750" aan te vragen aangezien op deze manier Bark! Polis een stuk soepeler loopt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Dyon033** [comment]
@Tom974 Johan is super admin :)

**Comment by Tom974** [comment]
Afgewezen vanuit superadmin+.
