### ISSUE TITLE
[EUP]: ANWB Pet logo aan de binnenkant

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2309]
### Contact Details

mrmartin02

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Op de ANWB Pet zit het ANWB logo aan de binnenkant ipv voorop op de buitenkant.

_Foto van de ANWB Pet op de grond met het logo zichtbaar aan de binnenkant:_
![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/e38739c8-e648-4a87-a8db-cfb08ccb4282)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Gaat dit om mannelijke of vrouwelijke kleding?
![image](https://github.com/Tedeapolis/development/assets/32094562/c67d08bf-b32c-4b59-a9b8-2dfb64074b73)
Zie zelf hierbij geen issue?

**Comment by goudvis02** [comment]
![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/dc70077a-80df-4b45-a0cc-cdfbfc5e7f21)
Dit is de pet die ik op krijg (Mannelijke kleding)

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn na herstart.
