### ISSUE TITLE
Portofoons en telefoons doen het niet fatsoenlijk

### ISSUE THREAD

**Issue by prepix** [Tedeapolis/development#231]
Bij portofoons komt het regelmatig voor dat we mensen niet horen.
Ook moeten we soms iemand 3 of 4 keer bellen voordat we elkaar kunnen verstaan.
Dit is heel frustrerent omdat je geen discord mag gebruiken maar elkaar soms wel snel nodig bent.

**Comment by Willem-Dekker** [comment]
Dit kan te maken hebben met dat je snel tussen de zones aan het wisselen bent maar ik heb een repro nodig om dit te kunnen testen
