### ISSUE TITLE
[Bug]: Noodknop signaal komt binnen bij ANWB

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2311]
### Contact Details

mrmartin02

### Wat gebeurde er?

De noodknop melding van ANWB personeel komt nu ook bij de ANWB zelf binnen. 
Deze 'aanpassing' is niet aan ANWB management doorgegeven, laat staan aan het personeel. Die komen nu op noodknop meldingen af waar zij niks te zoeken hebben. Het geeft hinder en overlast voor onze bedrijfsvoering en de noodsituatie zelf.

### Wat hoorde er te gebeuren?

Dat het noodknop signaal NIET bij de ANWB binnen komt.

### Wat veroorzaakt de bug?

Onbekend

### Frequentie van de bug

1x per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Oke, leuk dat de "aanpassing" niet is doorgegeven, maar development heeft niks aangepast. Overigens zie ik niet in waarvoor wij alles zouden moeten doorgeven aan ANWB management. Voor nu denk ik handig als je gewoon dmv een mededeling je medewerkers op de hoogte stelt dat ze hier niet op af moeten gaan. Overigens ook wel logisch lijkt me als anwber, je maakt tenslotte voertuigen en die noodknop is niet om extra hulp op te roepen omdat er een boutje los zit.

**Comment by goudvis02** [comment]
We gaan er een mededeling voor sturen in het ANWB Team.

**Comment by Tom974** [comment]
Geen idee hoe je dit voor elkaar hebt gekregen, zijn er toevallig clips en logs beschikbaar @goudvis02 ? Anders kan ik er helaas niet zoveel mee.

**Comment by Dyon033** [comment]
> Geen idee hoe je dit voor elkaar hebt gekregen, zijn er toevallig clips en logs beschikbaar @goudvis02 ? Anders kan ik er helaas niet zoveel mee.

Ik heb dit ook eens gehad bij taxi, volgensmij was dat omdat ik indienst was bij Bark! Polis EN Taxi. Heel vaag was het.

**Comment by Tom974** [comment]
Geen reactie meer op issue.
