### ISSUE TITLE
[Bug]: Bark! Polis helikopter/dierenambulance niet meer spawnbaar

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2312]
### Contact Details

dyon.

### Wat gebeurde er?

Als wij bij Bark! Polis de dierenambulance of de helikopter willen spawnen krijgen wij te lezen dat dat niet mogelijk is.

![Schermafbeelding 2023-11-08 214321](https://github.com/Tedeapolis/development/assets/120292087/7e78bcd7-fa36-48e8-bab3-011f1b1c87bc)

### Wat hoorde er te gebeuren?

Er hoort een dierenambulance/helikopter te spawnen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

[CitizenFX_log_2023-11-08T203446.log](https://github.com/Tedeapolis/development/files/13301169/CitizenFX_log_2023-11-08T203446.log)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed na herstart
