### ISSUE TITLE
[FEATURE]: Uitdienst toegang tot 110 + politie meldkamer

### ISSUE THREAD

**Issue by Zjefvm** [Tedeapolis/development#2318]
### Contact Details

tomtommer

### Goedgekeurd door

Korpsleiding

### Beschrijf zo duidelijk mogelijk de feature

De volgende rangen toegang geven tot uitdienst porto 110 + uitdienst politie meldkamer.

police 17
police 18
police 19
police 20

### Wat lost deze feature op?

Hoeveelheid INDIENST recherche verminderen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
