### ISSUE TITLE
[FEATURE]: Het logo/icoontje op de map verplaatsen van het oude naar het nieuwe MLO van 14K. 

### ISSUE THREAD

**Issue by chayenn3** [Tedeapolis/development#2319]
### Contact Details

JannaChayenne

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Het logo/icoontje op de map van het ganghuis van 14K van het oude MLO naar het nieuwe MLO op La Fuenta verplaatsen. Momenteel heeft het nieuwe MLO geen custom icoontje meer op de map. 

### Wat lost deze feature op?

Het custom logo/icoontje van 14K zal weer zichtbaar zijn voor leden op de map bij het juiste MLO. 

### Richtlijnen

- [x] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Als je even /coords doet, en dan een screenshot van de coordinaten maakt op de correcte plek, dan kan dit voor je aangepast worden.

**Comment by chayenn3** [comment]
Is niet meer nodig helaas, zou je hem kunnen verwijderen?

**Comment by Tom974** [comment]
> Is niet meer nodig helaas, zou je hem kunnen verwijderen?

rip
