### ISSUE TITLE
[EUP]: Aanpassing Vrouw Politie EUP

### ISSUE THREAD

**Issue by Ssaannddyy1** [Tedeapolis/development#2320]
### Contact Details

sandyy / jasminevibes

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Aanpassing/toevoegingen vrouwen eup.

Ik ben van mening dat er wat meer gedaan mag worden aan het vrouwen eup van de politie. Ik heb wat dingetjes uitgezocht en zie graag meningen van de rest tegemoet.

Fietshelm (Foto 1)
Dit wordt niet vaak gebruikt, maar als het heel rustig is dan is het best wel leuk om een dienstje te draaien op de fiets. Alleen in het vrouwen eup zit de fietshelm niet. Het is niet echt veilig om te fietsen zonder helm en als politie ben je ook een voorbeeldfunctie, dus ben ik van mening dat de fietshelm moet worden toegevoegd in het eup van de vrouwen.

Nieuw motorpak (Foto 2 & 3)
Ik doe nogmaals de suggestie om het motorpak te vernieuwen. Ik krijg vaak de opmerking, ben jij wel een echte agent, omdat het een design is van een oud motorpak. Ik weet niet tot hoeverre dit mogelijk is, maaaaar het zou wel leuk zijn als er een nieuwe versie komt die ook lijkt op die van de mannen.

Aanpassing uniform met shirt (Foto 4 & 5)
Het uniform met de lange mouwen ziet er gewoon goed uit, want die heeft de koppelriem met alles erop en eraan, maar de uniform met het shirt die heeft nog de oude koppelriem. Hierdoor draag ik het uniform met shirt eigenlijk bijna nooit. Ook gaat mijn bril van mijn outfit af als ik die aantrek. Dus het zou fijn zijn als de juiste koppelriem op die outfit wordt gezet en als het mogelijk is dat het gefixt wordt dat je bril niet weggaat.

Zwarte handschoenen (Foto 6)
Mannen kunnen de optie kiezen om zwarte handschoenen te dragen, maar als vrouw heb je die keuze niet. Ik zou toch wel de keuze willen hebben om de zwarte handschoenen aan te doen, want ja als het koud is is het wel fijn als de handjes warm blijven.

Unmarked Kleren 
Bij de unmarked kleren is de zelfde issue als bij de T-Shirt. Dit is dan ver oudere riem en dat je je bril niet kan opzetten.

![image](https://github.com/Tedeapolis/development/assets/143293216/517af51b-1d96-4ff6-b361-8984987c5a2d)

![image 22](https://github.com/Tedeapolis/development/assets/143293216/7fa0b3ba-dcbe-4d33-ae85-86c50a99723f)

![image 33](https://github.com/Tedeapolis/development/assets/143293216/b20bdd5c-31ba-469b-9d72-42ad37a34e65)

![55](https://github.com/Tedeapolis/development/assets/143293216/451b7112-814d-4543-bd3f-5cee85765a7b)

![image 77](https://github.com/Tedeapolis/development/assets/143293216/00c7de18-72eb-4241-8570-78fee8d45239)

![99](https://github.com/Tedeapolis/development/assets/143293216/c978d1a1-4f5e-4ba3-aedc-87c12a39d211)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
@Ssaannddyy1 ik heb de eup issues al aangepast motorpak ben ik nog mee bezig, de rest is na de restart gefixt

**Comment by DevvTDA** [comment]
Motor agenten pak is ook toegevoegd
