### ISSUE TITLE
[FEATURE]: Rangen Justitie

### ISSUE THREAD

**Issue by WiebeZevenhuis** [Tedeapolis/development#2321]
### Contact Details

Zevenhuis aka TDA Wiebel

### Goedgekeurd door

Justitie leiding - Johan & Wiebe

### Beschrijf zo duidelijk mogelijk de feature

NIEUWE RANG: KVK Stagiair ( Geen F6 menu en geen toegang tot de justitie /docu)  Salaris indienst  800 - Uitdienst 150

IS ER AL: KVK Medewerker (Niks veranderen) 

NIEUWE RANG: KVK Senior Medewerker -  Zelfde rechten als KVK Medewerker - Salaris indienst 1100 - Uitdienst 950

Aanpassing aan rechten:
KVK Beheer toegang geven tot de kluis (geld er uit halen) en toegang tot werknemerslijst. 

### Wat lost deze feature op?

Nieuwe rangen bij justitie om de KVK aantrekkelijker te maken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by lisaeindhoven** [comment]
NEE KRIJG JE NIET DOEI

**Comment by LiSatesaus** [comment]
NEE KRIJG JE NIET DOEI

**Comment by niekschoemaker** [comment]
Zit erin na restart
