### ISSUE TITLE
[FEATURE]: Ambulance sollicitatie website

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2323]
### Contact Details

jaak_steifkes

### Goedgekeurd door

jaak_steifkes (Ambulance Baas)

### Beschrijf zo duidelijk mogelijk de feature

- Heb je de afgelopen 7 dagen een andere overheidsbaan gehad **aanpassen naar** Heb je de afgelopen 3 dagen een andere overheidsbaan gehad
- Ben je in de afgelopen 7 dagen lid geweest van een criminele organisatie **aanpassen naar** Ben je in de afgelopen 3 dagen lid geweest van een criminele organisatie

### Wat lost deze feature op?

Selectievakjes zijn gelijk met de APV-regels van Tedeapolis.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Is gefixed
