### ISSUE TITLE
[FEATURE]: Patiënten lig functie verzorgingskamer

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2324]
### Contact Details

jaak_steifkes

### Goedgekeurd door

jaak_steifkes (Ambulance Baas)

### Beschrijf zo duidelijk mogelijk de feature

Momenteel wordt de verzorgingskamer best veel gebruikt door ambulanciers en patiënten, in deze kamer staat een bed. Dit bed is het enigste bed in heel het ziekenhuis waar een patiënt niet de mogelijkheid heeft om hierop te gaan liggen.

 Zou dit op onderstaande coords toegevoegd kunnen worden?
https://imgur.com/a/RbEL1cA

Voorbeeld van wat ik bedoel, moest het niet duidelijk zijn:
https://imgur.com/a/rFPMdfI

### Wat lost deze feature op?

Patiënten kunnen in deze kamer op het bed gaan liggen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Oude ziekenhuis dus ik sluit deze
