### ISSUE TITLE
[FEATURE]: Grenspost toevoeging

### ISSUE THREAD

**Issue by WesleyS01** [Tedeapolis/development#2325]
### Contact Details

Wesley#6647 [ TDA Wesley ].

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Hoi, ik stond vandaag op de oostpost en merkte dat mensen nog steeds niet wisten dat de rechterbaan van de post een overheidsbaan is. Ik heb zitten nadenken over hoe we dit kunnen oplossen en kwam op het idee om eventueel pijlen en kruisjes op de post te zetten. Momenteel staan er op de bovenkant van de post een bord met 10 erop. Ik zou graag willen aanvragen dat dit vervangen word door de linkerbaan een groen pijltje te maken en de rechterbaan een kruisje. Denk aan eventuele matrixborden. Ik zal ook foto's toevoegen als voorbeeld. 
![Controlepost oostpost](https://github.com/Tedeapolis/development/assets/152522233/e1e1d0bb-9699-4a88-b11b-d01291180e5e)
![Controlepost voorbeeld](https://github.com/Tedeapolis/development/assets/152522233/a77ad4d5-af83-4b12-a5dd-df4338d9af32)

### Wat lost deze feature op?

Dat wij duidelijk kunnen aangeven dat de rechterbaan gesloten is en alleen beschikbaar is voor overheidsdiensten zo dat eventuele crashes of ophoud voorkomen word. Het is ook geen grote aanpassing dus FPS zou ook niet veel moeten schelen :)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DaanDeW** [comment]
ik ga hier even naar kijken!

**Comment by DaanDeW** [comment]
Doorgevoerd en zit al in de main!

**Comment by DaanDeW** [comment]
Is gecommit
