### ISSUE TITLE
[Bug]: Geen heli radar meer

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#2326]
### Contact Details

TheOnlyJoris

### Wat gebeurde er?

Ik was aan het vliegen en zie geen heli cirkels meer op de radar
De flightschool ziet deze ook niet meer. 
Hierdoor kunnen de KLu en flightschool hun werk niet meer doen

### Wat hoorde er te gebeuren?

Je hoort een heli cirkel te zien

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn na volgende herstart
