### ISSUE TITLE
[Bug]: Bij richten kom je niet terug in de juiste "view"

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2327]
### Contact Details

iHax0r#3736

### Wat gebeurde er?

Stel jij speelt in First Person view en drukt 1x op je rechtermuisknop, ga je eerst in first person en als je rechtermuisknop loslaat kom je in Third Person View (eerste mode).

Indien er vragen zijn stel ze in mijn DM, probeer het zo goed mogelijk uit te leggen.

Video 1 (zonder ped):

https://github.com/Tedeapolis/development/assets/29235700/d1659c47-8659-4e21-bbcd-74623c827377

Video 2 (met ped):

https://github.com/Tedeapolis/development/assets/29235700/836bac9f-d280-4cae-8764-71af2d9fc193

### Wat hoorde er te gebeuren?

Terugkomen in de view die je voorheen gebruikte, dus als jij First Person View zit. Blijf je in First Person View ook na het schieten, maar als jij in Third Person View zit, ga je naar First Person View tijdens het richten en daarna terug naar Third Person View

### Wat veroorzaakt de bug?

Wapensysteem, dit heb je namelijk niet als ped.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Is gefixed na restart
