### ISSUE TITLE
[FEATURE]: Op afstand vliegbrevetten in kunnen nemen.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2328]
### Contact Details

xuify

### Goedgekeurd door

KL & FS leiding

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment kan de FS enkel vliegbrevetten in beslag nemen doormiddel van een signalering uit te schrijven op de persoon waarvan hij in beslag genomen moet worden. 
Er is samen met KL en FS leiding een gesprek geweest om hier over te brainstormen, en hier kwamen we op het volgende idee.
Leden van de FS (vlieg instructeurs dus) en van de KLU kunnen op afstand een vliegbrevet in beslag nemen, op welke manier dit kan laat ik over aan de DEVS (mogelijk via meos of iets met f6 en een bsn in vullen). 
Wel moet er iets van een mededeling komen naar de persoon die zijn vliegbrevet kwijt is, in mijn ogen lijkt het beste en meest RP wise om een bericht op je telefoon van de FS te ontvangen met daarin iets omtrent:
"Helaas hebben we je <input welk brevet> brevet in beslag moeten nemen. Indien je vragen hebt omtrent je vliegbrevet inbeslagname kun je ten alle tijden contact op nemen met de flightschool.".
Als de devs een beter idee hebben omtrent een mededeling richting de spelers is dat ook geheel prima!

### Wat lost deze feature op?

Momenteel krijgt de politie veel "valse" signaleringen. Dit levert veel gedoe op omdat vaak de verdachte dan ook al aangehouden is en gefouilleerd is. Dit zorgt er helaas voor dat er illegale dingen gevonden worden die normaal niet gevonden zouden zijn en dat is jammer.
Ook zorgt dit er voor dat er achtervolgingen ontstaan omdat gesignaleerde mensen mogelijk een wapen op zak hebben en dit kan heel ver uit lopen voor enkel in vliegbrevet die ingetrokken moet worden.
Dit is dus een voordeel voor de politie (minder valse signaleringen), voor de criminelen (minder politie achter je aan voor een minder goede reden) en voor de FS.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Done, confiscate_flylicense [bsn] [licentie type]

**Comment by Smokjertje12** [comment]
> Done, confiscate_flylicense [bsn] [licentie type]

Zou het ook mogelijk zijn om hier logs aan toe te voegen? Zoals we de Flylicense logs momenteel hebben?
Zou namelijk moeilijk te traceren zijn anders.
