### ISSUE TITLE
[EUP]: Ambulance kledij, lange mouwen man en vrouw

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2330]
### Contact Details

jaak_steifkes

### Goedgekeurd door

Mila E.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Voor de mannen en vrouwen een nieuw pak met lange mouwen maken. We hebben nu namelijk wel een pak met lange mouwen, maar dit past niet meer bij het huidige kleurenthema. We hebben namelijk voor reguliere diensten geen geel met groene pakken meer (alleen voor inwerking of examen). Maar we zouden ook graag een blauw pak met lange mouwen willen hebben indien mogelijk.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
done, moet gecommit worden dan is het na de restart gefixt
