### ISSUE TITLE
[FEATURE]: Basketbal veld binnenplaats gevangenis

### ISSUE THREAD

**Issue by tdalynn** [Tedeapolis/development#2333]
### Contact Details

lin_x

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In de binnenplaats van de gevangenis staat een basketbal veld, deze is niet werkzaam. Omdat er momenteel veel DJI in dienst is, leek het ons leuk om dat basketbal veld werkzaam te maken :)
Mocht het niet lukken, leek het ons leuk om een tennisveld erin te zetten aangezien die al in TDA zitten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
basketbal veld gaat niet lukken, tennis klinkt als een piece of cake.

**Comment by Tom974** [comment]
Is dit ook goedgekeurd door Kader? Zie namelijk dat een github account welke niet in de lijst staat, deze issue heeft gemaakt.

**Comment by DevvTDA** [comment]
Lynn heeft dit aangevraagd bij mij @Tom974 of het kon ik zei lijk me geen grote issue

**Comment by tdalynn** [comment]
Goedgekeurd door Chrushers (kader) en Thomas (korps)

**Comment by DevvTDA** [comment]
staat er na de restart in :)
