### ISSUE TITLE
[EUP]: Extra DJI outfit M/V

### ISSUE THREAD

**Issue by tdalynn** [Tedeapolis/development#2334]
### Contact Details

lin_x

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Voor de DJI zouden we een extra outfitje willen, hierbij zijn wel een aantal aanpassingen bij nodig, zie hieronder:
**Torso**
_Man: 
Torso 1: 156
Torso 2: 5
Vrouw:
Torso 1: 58
Torso 2: 2_
Dit politie shirt moet een beetje aangepast worden, het politie logo op de schouders kan weg of vervangen worden door het logo van DVO (foto toegevoegd). Mocht dit niet mogelijk zijn, of te lastig, kan het politie logo gewoon weg en is dat ook prima!

**Steekvest**
Het mooiste zou zijn dat het oude kmar steekvest een reskin kan krijgen.
Man:
_Kogelvrij vest 1: 8
Kogelvrij vest man 2: 3_
Tekst vervangen met '' justitie ''
Vrouw:
hOvJ vest, nummers kan ik in de kledingwinkel helaas niet vinden. Hierbij ook hOvJ vervangen met '' justitie ''
_**Mocht de reskin niet lukken of te veel werk zijn, zouden we graag gebruik willen maken van het justitie steekvest**_
_Man:
Kogelvrij vest 1: 10
Kogelvrij vest 2: 0
Vrouw:
Kogelvrij vest 1: 11
Kogelvrij 2: 1_

Voorbeelden:
DVO logo eventueel op de schouders van torso:
![1678118856543](https://github.com/Tedeapolis/development/assets/147812850/a5438441-4f81-4a9c-9010-1d9fdf121161)
![4789ace4ca31c4b08be5264a249c789f](https://github.com/Tedeapolis/development/assets/147812850/d697696f-b4c0-44d8-9924-df7dc79d8642)
Shirt in Skin menu man:
![image2](https://github.com/Tedeapolis/development/assets/147812850/4610c94d-d0da-49b7-a778-9f358637ea3e)
Shirt in Skin menu vrouw:
![image](https://github.com/Tedeapolis/development/assets/147812850/58281063-380a-42a0-bf32-f3eb54390234)
Steekvest oud kmar voor reskin met justitie tekst man:
![3c1365e7a9f6b9bc9f77993e8a0d76f8](https://github.com/Tedeapolis/development/assets/147812850/7d8f7c92-e47d-49dc-9b9e-9e1a0a5c0440)
![5554f1817ddce71e1325893e52becb7e](https://github.com/Tedeapolis/development/assets/147812850/e1df9229-0f79-4a29-b35a-780ed5b82241)
Steekvest hOvJ voor reskin met justitie tekst vrouw:
![image3](https://github.com/Tedeapolis/development/assets/147812850/97ba7c7b-59a9-48d7-b05a-1cbb0cc4a6cb)
![image4](https://github.com/Tedeapolis/development/assets/147812850/41e66fdd-14d1-41c0-8c3b-4413aafb0e0a)
Steekvest voor als reskinnen niet mogelijk is man:
![cc823ca60acb1da75a08ff39acdb0bb0](https://github.com/Tedeapolis/development/assets/147812850/70e56f73-636b-425f-91e0-6675b61766b7)
![6cec208391f0278a1bef05d37db812c1](https://github.com/Tedeapolis/development/assets/147812850/aa337cda-4d1c-4e38-b228-9bd9fbfb28ff)
Steekvest voor als reskinnen niet mogelijk is vrouw:
![image5](https://github.com/Tedeapolis/development/assets/147812850/2eb9fff8-a212-46a1-b03a-df6eff2a3a1b)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart
