### ISSUE TITLE
[FEATURE]: /setjob perms dierenkliniek management

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2335]
### Contact Details

dyon.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

de rang "dierenkliniek 750" toegang geven tot /setjob dierenkliniek

Dit hoorde deze rang al te hebben maar had het blijkbaar niet

### Wat lost deze feature op?

Dat management stadsrangen kan geven aan personeel.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Hebben ze geen toegang tot het menu dan? Lijkt me ook prima werkend.

**Comment by Dyon033** [comment]
> Hebben ze geen toegang tot het menu dan? Lijkt me ook prima werkend.

Tot zover ik weet niet, en dan moeten ze sws op een gemiddelde avond door 500+ man zoeken naar de juiste steam naam.

**Comment by Dyon033** [comment]
> Hebben ze geen toegang tot het menu dan? Lijkt me ook prima werkend.

Oh en dit heeft sowieso niet echt een meerwaarde dat menu. 9/10 Bark! Polis jobs moet op de second job, en dat kan niet met dat menu.
