### ISSUE TITLE
[Bug]: Ziekenhuis behandeling

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2337]
### Contact Details

CalRay

### Wat gebeurde er?

Collega en ik nemen een behandeling komen we in hetzelfde bed en ook nog iemand erop. Dus uiteindelijk liggen er 3 mensen in 1 bed tijdens het nemen van een behandeling. 
![image](https://github.com/Tedeapolis/development/assets/101106299/7c7914e9-fe99-4167-8c8b-94670d561c07)

### Wat hoorde er te gebeuren?

Iedereen hoort een aparte bed te krijgen bij een behandeling. 

### Wat veroorzaakt de bug?

Een behandeling nemen en de kans zit erin dat je samen in 1 bed zit.  

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Niet zo zeer nodig om aan te passen gezien er geen roleplay aan verbonden is.
