### ISSUE TITLE
[Bug]: Medicijnen niet kunnen leveren met een ambulance voertuig

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2338]
### Contact Details

CalRay

### Wat gebeurde er?

Je kan niet met bepaalde ambulance voertuigen medicijnen rijden. Zie screenshot: 
![image](https://github.com/Tedeapolis/development/assets/101106299/214d9dfa-d3a7-476b-a6ef-eb21e227fed9)

### Wat hoorde er te gebeuren?

Je hoort gewoon medicijnen te kunnen leveren

### Wat veroorzaakt de bug?

Hij herkent het voertuig niet als ambulance voertuig

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Jaak-Steifkes** [comment]
Is net de bedoeling dat dit niet gaat op een MMT / Rapid responder.
