### ISSUE TITLE
[Bug]: Voertuig niet meer dichtbij

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2339]
### Contact Details

CalRay

### Wat gebeurde er?

Als je iets in een kofferbak wilt doen staat er meestal "Voertuig is niet meer dichtbij". waardoor je opnieuw uit "L" moet drukken. Dit  probleem is sinds kort gekomen, alleen was ik een beetje lui om een github te maken.  Zie clip: https://www.youtube.com/watch?v=pt4xxK7DmGY

### Wat hoorde er te gebeuren?

Je hoort gewoon in je kofferbak te kunnen gaan. 

### Wat veroorzaakt de bug?

Geen idee

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Komt omdat je bij de deur staat en niet bij de kofferbak, als je bij de kofferbak gaat staan heb je hier geen last van.
