### ISSUE TITLE
[EUP]: Brandweerhelm niet meer juist in EUP

### ISSUE THREAD

**Issue by TheKevNL** [Tedeapolis/development#2340]
### Contact Details

thekevnl

### Goedgekeurd door

iom. Daan de Wit

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Sinds de kleding update is de brandweerhelm een pet geworden in het brandweer EUP.
De brandweerhelm zit nu op nummer 195 in het skin menu.
![Brandweerhelm](https://github.com/Tedeapolis/development/assets/121273172/51604132-f666-419b-8e2d-90bcfffd1eb5)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart
