### ISSUE TITLE
[EUP]: Vrouwen officieren outfit KMAR

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2342]
### Contact Details

larrsss

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag willen we voor de KMAR een vrouwen officieren outfit, omdat we deze niet hebben. 
Deze is al gemaakt, zie screenshot hier onder voor de nummertjes. 

/eup -> Kmar - Uniform -> NAAM ''Officier Kort (v)''

![image](https://github.com/Tedeapolis/development/assets/112424697/f72559b3-fe5d-4765-8599-9b0db250a9e6)
![image](https://github.com/Tedeapolis/development/assets/112424697/c8ea6c7a-76ea-4429-8d08-a6583239d621)
![image](https://github.com/Tedeapolis/development/assets/112424697/6296047c-4683-42c5-b770-1329af32c274)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fiixed na de restart
