### ISSUE TITLE
[Bug]: Meos op verschillende devices 

### ISSUE THREAD

**Issue by CalRayy** [Tedeapolis/development#2345]
### Contact Details

CalRay

### Wat gebeurde er?

Ik ben niet helemaal zeker of dit een bug is, maar uit voorzorg heb ik een GitHub-issue aangemaakt. Wanneer je op je pc inlogt op Meos en vervolgens op je laptop of telefoon inlogt, wordt je pc meos account automatisch na enkele minuten uitgelogd.

### Wat hoorde er te gebeuren?

Lijkt me handiger dat dit niet constant gebeurd, want dan moet je je inloggegevens weer opnieuw invullen.

### Wat veroorzaakt de bug?

Verschillende devices gebruiken op meos, en dan na meerdere minuten / uren wordt je uitgelogd op een bepaalde device omdat je op een andere device hebt ingelogd met je meos account. Als hier meer duidelijkheid voor nodig is hoe dit gebeurd, mag je me hier altijd een bericht voor sturen. 

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dat is expres zo gedaan.
