### ISSUE TITLE
[Bug]: Brigade recherche heeft toegang tot voertuigen kopen welke ze niet moeten hebben

### ISSUE THREAD

**Issue by Zjefvm** [Tedeapolis/development#2347]
### Contact Details

zjef

### Wat gebeurde er?

De Brigade recherche, de volgende nummertjes dus:

B - Recherche Junior = 85
B - Recherche = 86
B - Recherche Senior = 87
B - Recherche leiding = 88

Hebben toegang om deze voertuigen te kopen, maar deze moeten ze niet kunnen kopen:
- Armed Humvee
- Armored BMW M550i
- Armored BMW X5M
- Armored Mercedes S63
- Armored Range Rover
- BSB Landcruiser
- EOD Crafter
- Landmacht Humvee
- Unarmed Humvee

### Wat hoorde er te gebeuren?

De brigade recherche hoort geen toegang te hebben om armored voertuigen te kopen in de politie voertuig dealer.

### Wat veroorzaakt de bug?

Geef jezelf 1 van deze jobs en je voertuigen kopen wat je niet hoort te kunnen kopen bij de brigade recherche.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
oftewel zeg tegen ze dat ze het niet mogen kopen..?

**Comment by Lorenzo3001** [comment]
Zou aangepast moeten zijn als het goed is.
