### ISSUE TITLE
[EUP]: Brandweerhelm niet meer juist in EUP (Vrouwen)

### ISSUE THREAD

**Issue by TheKevNL** [Tedeapolis/development#2348]
### Contact Details

thekevnl

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De helm voor **vrouwen** klopt helaas ook niet meer.

Sinds de kleding update is de brandweerhelm een pet geworden in het brandweer EUP.
De brandweerhelm zit nu op nummer 194 in het skin menu.
![Helm Vrouw](https://github.com/Tedeapolis/development/assets/121273172/93fd791f-4c44-4a6a-a926-f3df81fd1bb6)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DaanDeW** [comment]
na restart zit ie erin!
