### ISSUE TITLE
[Bug]: Porto's joinen 2de job

### ISSUE THREAD

**Issue by JustitieTDA** [Tedeapolis/development#2349]
### Contact Details

yohandessu

### Wat gebeurde er?

Momenteel kan je rechter zijn naast je 2de job. Helaas kan je op je 2de job geen portos van justitie binnen. Dit hoort wel te kunnen als een rechter een zaak heeft. 

### Wat hoorde er te gebeuren?

Dat je de portos van justitie ook kunt joinen op je 2de job

### Wat veroorzaakt de bug?

Dat rechters de porto niet in kunnen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Relevante log bestanden

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Dyon033** [comment]
Heeft Niek al gefixt xoxo
