### ISSUE TITLE
Justitie telefoon - afvinkmogelijkheid + listing in de telefoon

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#235]
Hi!

Is het mogelijk:

- Om een afvink-optie op te nemen voor berichten van Justitie (zoals bij de taxi e.a.);
- Om de contactpersoon Justitie standaard op te nemen op alle telefoons (zoals ook de ambu, politie, e.d. is opgenomen)

**Comment by Willem-Dekker** [comment]
Done
