### ISSUE TITLE
[FEATURE]: Saints aanpassingen

### ISSUE THREAD

**Issue by SaintsTDA** [Tedeapolis/development#2351]
### Contact Details

.thomasss. 

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Nieuwe rangen binnen Saints

Sentinal -> Alle perms
Counselor -> Alle perms
Master Sergeant -> Alle perms
Vanguard -> opslag, voertuig opslag, f6 en wapeninkoop
Captain affiliate-> opslag , voertuig opslag en F6
Lieutenant -> opslag , voertuig opslag en F6
Inquisitor -> opslag , voertuig opslag en F6
Crusador -> opslag , voertuig opslag en F6
Member -> opslag , voertuig opslag en F6
Affiliate -> alleen spullen in opslag stoppen , voertuig opslag en /rs
Associate ->Enkel deuren van het huis

Daarnaast zouden we de kledingcirkel en 1 opslag cirkel op een andere plek willen hebben, De opslag cirkel in de garage mag blijven.
De opslag cirkel van X399.04, Y-21.31, Z91.94 naar X411.92, Y6.85, Z84.92
De kleding cirkel van X395.43, Y -20.67, Z91.94 naar X429.91, Y99.65, Z99.65

### Wat lost deze feature op?

Aanpassingen Saints job

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DaanDeW** [comment]
Armory cirkel done
