### ISSUE TITLE
[EUP]: ANWB Baas nette schoenen zijn sportschoenen geworden

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2352]
### Contact Details

mrmartin02

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Bij de ANWB hebben wij een net pak voor management in /eup, maar sinds een kleding update zijn de nette schoenen die bij dit pak horen veranderd in sportschoenen. Gek genoeg hoor je bij het lopen nog wel het geluid van nette schoenen.

![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/fc94f318-9199-4f1a-a2bc-2f87c69a588a)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DaanDeW** [comment]
gefixt na restart
