### ISSUE TITLE
[FEATURE]: Twitter account algemeen voor rechtszaken

### ISSUE THREAD

**Issue by WiebeZevenhuis** [Tedeapolis/development#2353]
### Contact Details

Zevenhuis

### Goedgekeurd door

KMAR/politie/Justitie leiding

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden we net zoals politie het volgende willen voor het gebruik van de rechtszaken:

We willen wat meer publiek hebben bij de rechtszaken, vaak zijn ze last moment waardoor het nieuws laat in de stad verspreid word. Daarom zouden we graag een Twitter account willen waar de hele stad een tweet krijgt als we een oproep plaatsen dat mensen bij een rechtszaak aanwezig kunnen zijn.
Graag zouden we het woord: ''Rechtszaal'' willen verifiëren voor onze naam zodat de tweet openbaar komt.

Dat betekend dus dat als we rechtszaal voor onze naam hebben, we dan net zoals de politie een openbare tweet kunnen plaatsen en ook iedereen deze krijgt. Ook de mensen die hun Twitter niet aan hebben staan.

### Wat lost deze feature op?

Zodat wij meer publiek krijgen tijdens een rechtszaak en zo meer RP bevorderen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
