### ISSUE TITLE
[FEATURE]: Vuurwerk standaard toegevoegd hebben in TDA.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2354]
### Contact Details

Xuify

### Goedgekeurd door

Staff overleg.

### Beschrijf zo duidelijk mogelijk de feature

In Paleto ammunition store een shop toevoegen waar je vuurwerk kan kopen. 
![image](https://github.com/Tedeapolis/development/assets/141491362/6315c38c-2b2a-45cc-8371-5c7d8bf9ff6c)
Vuurwerk buiten oud en nieuw (hier worden datums aan gelinkt) is illegaal om af te steken zonder de juiste documentatie die je bedrijf kan krijgen bij justitie. 
Graag kijken of de prijzen verhoogt moet worden of dat de ratelimiters aangepast moeten worden, deze vrijheid is er voor de developers.

 

### Wat lost deze feature op?

Deze feature crëert nieuwe roleplay mogelijkheden voor zowel bedrijven, overheid en criminelen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by NovaGazer3** [comment]
Bij updates graag mij een PM sturen (xuify / [TDA] Nero).

**Comment by Nander0320** [comment]
Hey na overleg binnen hoge raad hebben wij besloten dat wij dit toch niet willen gaan doen omdat wij dit toch wel een seizoensgebonden dingetje vinden :)

**Comment by Nander0320** [comment]
Hey na overleg binnen hoge raad hebben wij besloten dat wij dit toch niet willen gaan doen omdat wij dit toch wel een seizoensgebonden dingetje vinden :)
