### ISSUE TITLE
[EUP]: VTB motorvest toevoegen

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2356]
### Contact Details

784411764267286559 - Lynn M. 

### Goedgekeurd door

Kader.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Er moet een VTB vest komen voor de Marechaussee. Dit hesje/vest moet blauw van kleur zijn met de letters VTB er op aan de achterkant, zie foto. 
Dit moet onder de categorie ''KMAR - Vest'' te komen staan. 

Dit vest is bedoeld om een hele delegatie aan voertuigen te escorteren / te spitsen op de wegen om een bijzonder transport soepel te laten verlopen. 

Mochten er vragen zijn over dit vest neem dan even contact op met Lynn M. (staff) en Chrushers (Kader). 
![VTB vest](https://github.com/Tedeapolis/development/assets/112424697/3ddabf31-9398-4436-be82-e9579d0dcf49)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DaanDeW** [comment]
toegevoegd
