### ISSUE TITLE
[FEATURE]: Dierenarts & Management toegang geven tot de pot.

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2358]
### Contact Details

dyon.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Bij Bark! Polis willen we graag het volgende aangepast in de rangen:

Manager (dierenkliniek 750)
Mogelijkheid geld uit de pot te halen 
Mogelijkheid geld in de pot te stoppen

Dieren Arts (dierenkliniek 200)
Mogelijkheid geld in de pot te stoppen

### Wat lost deze feature op?

Dat dierenartsen en hoger het geld van de verhuur in de pot kunnen storten & dat management geld er uit kan halen indien nodig.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed, als het sstuk is dan uhm stuur me even :)
