### ISSUE TITLE
[FEATURE]: Saints rangen

### ISSUE THREAD

**Issue by SaintsTDA** [Tedeapolis/development#2359]
### Contact Details

.thomasss. 

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

We hebben sinds de afgelopen restart (25-01) nieuwe rangen. Echter kloppen twee rangen nog niet: 

Member -> Geen f6, moet die wel hebben
Vanguard -> Wapen winkel erbij

Daarnaast is de kleding cirkel nog niet verplaatst. 

### Wat lost deze feature op?

Aanpassingen Saints job

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Als je de coords van de kledingcirkel er even inzet.

**Comment by SaintsTDA** [comment]
Kleding cirkel moet van X395.43, Y -20.67, Z91.94 naar x429.95 y-11.94 z99.65

**Comment by DevvTDA** [comment]
@SaintsTDA vanguard / seguace heeft wel de wapen inkoop ? 
![image](https://github.com/Tedeapolis/development/assets/79802852/c9e2edc6-9696-4f2e-b874-a4fb018b2534)

**Comment by DevvTDA** [comment]
already fixed
