### ISSUE TITLE
custom ringtone + sms

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#236]
géén idee of dit überhaupt kan, maar zou je de ringtone en/of sms tone kunnen veranderen naar iets customs? (local file afspelen of via een url ofzo?)

**Comment by Willem-Dekker** [comment]
kan wel maar is heel veel werk aangezien het een gegenereerde javascript is en het bouwen hier van broken is.

**Comment by PapaXilion** [comment]
Duidelijk, was hooguit een nice-to-have. Dan gooi ik 'm dicht :)
