### ISSUE TITLE
[FEATURE]: HRB s63

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2361]
### Contact Details

larrsss

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

We willen graag een S63 voor de HRB. Dit gaat gewoon om de bestaande S63 die al ingame is. (Unmarked politie) echter moet er nog het HRB logo op. Dit aan beide zijkanten.

HRB logo staat ook op de Toyota landcruiser op de zijkant. 

### Wat lost deze feature op?

De HRB heeft er dan een onroad voertuig bij, deze hebben ze nu niet. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Moet je @Lorenzo3001 lief aankijken voor de logo's.

**Comment by KMarTDA** [comment]
> Moet je @Lorenzo3001 lief aankijken voor de logo's.

Als hij dit kan doen graag.
