### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by WiebeZevenhuis** [Tedeapolis/development#2362]
### Contact Details

Zevenhuis

### Goedgekeurd door

Justitie leiding - Wiebe

### Beschrijf zo duidelijk mogelijk de feature

De rang Meester In Rechten salaris naar 1500 - Uitdienst salaris 500
De rang Juridisch Medeweker naam veranderen naar - Nestor advocaat
De rang Afgevaardigde weghalen

### Wat lost deze feature op?

Meer doorgroeimogelijkheden voor advocaten en rechters

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
![8ec33e](https://github.com/Tedeapolis/development/assets/32094562/b59c5450-999a-4154-b06d-89f517fa62ea)

**Comment by niekschoemaker** [comment]
Done
