### ISSUE TITLE
[Bug]: Ultralight heeft geen hoogtemeter.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2363]
### Contact Details

xuify

### Wat gebeurde er?

Wanneer je vliegt in een ultralight zie je je hoogte niet.
https://medal.tv/games/gta-v/clips/1Sx6wZREUgYdHB/d1337PfdyD7D?invite=cr-MSw0MTEsMTcyMTk0MzU0LA

### Wat hoorde er te gebeuren?

Dat je de hoogte wel kan zien.

### Wat veroorzaakt de bug?

Vliegen met een ultraligt.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed na restart
