### ISSUE TITLE
[FEATURE]: Laatste toevoegingen/aanpassingen KNRM

### ISSUE THREAD

**Issue by DaanDeW** [Tedeapolis/development#2364]
### Contact Details

daandwtwitch

### Goedgekeurd door

Daan de Wit (Ambulance)

### Beschrijf zo duidelijk mogelijk de feature

Er moeten nog een aantal aanpassingen komen voor de KNRM. Hierna is de KNRM zo goed als af. 

- [x] KNRM Lonen juist zetten
Ambulance 87 - KNRM - Medisch Hoofd Officier / Loon 1900-1900 
Ambulance 86 - KNRM - Medisch Officier / Loon 1700-1700 +NH90 
Ambulance 84 - KNRM - Nautische Arts / Loon 1650- 1650 
Ambulance 83 - KNRM - Nautische Verpleegkundige /Loon 1400 -1400
Ambulance 82 - KNRM - Lifeguard / Loon 1350- 1350 + Aanhangwagen
Ambulance 81 - KNRM - Lifeguard in Opleiding / Loon 1300-1300 
Allemaal vanuit ambu pot gewoon.

- [ ] Nieuwe KNRM voertuigen / toevoegingen ( Aanhanger voor boot aan garage toevoegen, NH90 reskin (zal hieronder toegevoegd worden). 

- [ ] Tank Jetski omhoog, momenteel kan je amper ver varen. 

- [ ] KNRM amarok brandcard toevoegen

- [ ] KNRM anker toevoegen aan kleine boot. 

### Wat lost deze feature op?

Dit zijn de aanpassingen die nog nodig zijn om alles op orde te hebben voor de KNRM.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Loon van rangen zijn aangepast
