### ISSUE TITLE
[EUP]: Ambulance OPCO hesje

### ISSUE THREAD

**Issue by Jaak-Steifkes** [Tedeapolis/development#2365]
### Contact Details

jaak_steifkes

### Goedgekeurd door

Mila E.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Toevoegen van een OPCO-hesje. Mag hetzelfde texture zijn als het VTB-hesje van de kmar indien dit past over de ambulance kledij. Het liefst in een gele kleur met ambulance logo onder of een kleur die passend is op de kledij. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
zit er na de restart in :)

**Comment by DevvTDA** [comment]
oepsie, verkeerde github

**Comment by DevvTDA** [comment]
ga dit toch afkeuren, is onnodig.
