### ISSUE TITLE
[EUP]: politie outfits -> police 24 (politie DJI Junior Beveiliger)

### ISSUE THREAD

**Issue by AshwinV9595** [Tedeapolis/development#2366]
### Contact Details

ashwin95

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### ** Bij de rang van "Politie DJI Junior Beveiliger" missen we heel wat politie kleding.**

Deze kleding was beschikbaar als Aspirant beveiliger en is ook beschikbaar als Medior beveiliger, maar bij Junior mist dit nog. Ik vermoed dat hier dus nog iets vergeten aan te klikken is kwa rechten tot de EUP kleding.

Hier onder zal ik een foto mee sturen van wat de EUP aangeeft met de rang **"police 24"**
![Screenshot 2024-02-07 105245](https://github.com/Tedeapolis/development/assets/24451975/6daa26ed-c526-4ae9-b01a-35be7a551676)

De screenshot hier onder is een foto van de eup als "police 23 (aspirant)". Aangezien deze een lagere functie is zouden deze outfits zeker ook beschikbaar moeten zijn in de Junior Beveiliger. 
![Screenshot 2024-02-07 105319](https://github.com/Tedeapolis/development/assets/24451975/7cfa07fb-c33d-4a6b-b246-587f8b61c60d)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
na restart waarschijnlijk gefixt :)
