### ISSUE TITLE
[FEATURE]: Bankoverval melding naar HRB meldkamer en fysiek op map

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2367]
### Contact Details

Hugo//KlotSjak (Barry S.)

### Goedgekeurd door

Kader en HRB leiding

### Beschrijf zo duidelijk mogelijk de feature

De Hoog Risico Beveiliging (HRB) krijgt op het moment in de HRB telefoon meldkamer meldingen als er een winkel wordt overvallen. Echter hebben de heren van de HRB hebben meer aan meldingen van een bank die wordt overvallen. Graag dit dus dan toevoegen dat ze meldingen krijgen in de HRB meldkamer dat er een bank wordt overvallen. Dit dan dus ook als melding toevoegen dat een bank wordt overvallen wat je tezien krijgt op je kaart.

### Wat lost deze feature op?

Dat de HRB kan opschalen vanwege een melding van een bankoverval en deze kant op kunnen gaan aangezien dit hun taak is. 
Kort gezegd: 
- Melding in meldkamer ''hrb'' ontvangen 
- Fysieke melding (Linksonder in je scherm) dat er een bank wordt overvallen en dat dit tezien is op de kaart.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
zit erin na de restart
