### ISSUE TITLE
[EUP]: DSI Vrouw

### ISSUE THREAD

**Issue by Ssaannddyy1** [Tedeapolis/development#2368]
### Contact Details

Sandyy

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Momenteel ziet de cargo broek er vrij raar uit met de combinatie van de rest van de outfit.

Is het mogelijk dat de cargobroek kan vervangen worden voor de volgende broeken:

Cargo Broek Zwart: Broek 1 ( 109 ) Broek 2 ( 0 ) 
Cargo Broek Zwart: Donker Grijs 1 ( 109 ) Broek 2 ( 1 )
Cargo Broek Zwart: Licht Grijs 1 ( 109 ) Broek 2 ( 2 )  

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
zit erin na de restart
