### ISSUE TITLE
Appartement

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#237]
Je kan geen appartement kopen bij de MiltonDrive.
Ik probeer dus het appartement 'Appartement mode 3 - 250.000 euro' te kopen. Het geld gaat van mijn bank, maar krijg het appartement niet. Heb ook al gerelogd. Dat appartement is in postcode 628. Kijk je op de map staat er wel dat het appartement van u is.
![Screenshot_9](https://user-images.githubusercontent.com/68497102/95485588-40aeba00-0992-11eb-8bc0-50519f09d6f3.png)

**Comment by Willem-Dekker** [comment]
zit volgens mij een cooldown op waar bij je moet wachten

**Comment by ExpensionX** [comment]
Aah oke, ik zal dan nog wachten. Ik zal morgen dan even opnieuw kijken.

________________________________
Van: Willem Dekker <notifications@github.com>
Verzonden: donderdag 8 oktober 2020 18:22
Aan: Tedeapolis/development <development@noreply.github.com>
CC: ExpensionX <ruben1995moors@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Tedeapolis/development] Appartement (#237)


zit volgens mij een cooldown op waar bij je moet wachten

**Comment by ExpensionX** [comment]
Ja nu werkt het wel. Alleen kan je elkaar niet horen in het appartement als je iemand uitnodigd.
Wel zien maar niet horen

________________________________
Van: Willem Dekker <notifications@github.com>
Verzonden: donderdag 8 oktober 2020 18:22
Aan: Tedeapolis/development <development@noreply.github.com>
CC: ExpensionX <ruben1995moors@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Tedeapolis/development] Appartement (#237)


zit volgens mij een cooldown op waar bij je moet wachten

**Comment by Willem-Dekker** [comment]
ik denk dat @niekschoemaker hier dan beter naar kan kijken aangezien hij meer weet van de code daar achter

**Comment by prepix** [comment]
Als je 1 keer in je porto praat kun je elkaar wel horen
