### ISSUE TITLE
[FEATURE]: Camera een fysiek item maken

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2370]
### Contact Details

ihax0r2.0_74473 / iHax0r

### Goedgekeurd door

Burgerraad (Afwachting op staffoverleg)

### Beschrijf zo duidelijk mogelijk de feature

Camera een fysiek item maken.

Zo moet je deze in je inventory hebben en indien je betrapt word, kan je er niet omheen dat je net met een giga ding in je handen stond.

Zal hem niet te duur maken, gewoon toevoegen in de elektronicawinkel voor ongeveer 500 euro. Daarbij zal ik een gewicht eraan vasthangen van 5 kg, zodat je bewust een keuze moet maken om hem mee te nemen.

Stel je ziet iemand met zo'n camera foto's of video's maken van wat jij aan het doen bent (waar dan ook). Dan kan je deze persoon fouilleren en bijvoorbeeld zijn camerabeelden bekijken en/of zijn camera afnemen.

Daarbij kan je de camera niet altijd gebruiken, aangezien sommige politie / criminelen deze camera ook gebruiken voor hun zoomfunctie. Kunnen ze op afstand even snel dat ding pakken, om in te zoomen en zo de situatie te bekijken.

Niet fysiek bij, is geen mogelijkheid tot het gebruik van deze camera.

### Wat lost deze feature op?

Je kan met een camera verder inzoomen, dus hiermee voorkom je dat je zomaar altijd die camera uit je broek trekt. Daarnaast kan je mensen daadwerkelijk controleren of ze deze camera bijhebben en heb je extra roleplay mogelijkheden, zoals de beelden bekijken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
afgekeurd bij staff overleg
