### ISSUE TITLE
[FEATURE]: Drugsmeldingen douanegebieden voor de Marechaussee 

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2371]
### Contact Details

hugoklotsjak

### Goedgekeurd door

Kader

### Beschrijf zo duidelijk mogelijk de feature

Momenteel krijgt de politie in het Los Santos International Airport ( LSIA ), Vaak de melding, er probeert hier "locatie" iemand drugs te verkopen. Wij als Koninklijke Marechaussee niet, Dit vind ik persoonlijk onlogisch want dit is een vliegveld oftewel ons douanegebied, Zoals iedereen weet In Nederland is de Koninklijke Marechaussee verantwoordelijk voor de veiligheid op-rondom de luchthavens, en een van onze hoofdtaken handhaven op Drugs-verkoop&smokkel. Dus waarom zou de politie hier wel deze melding krijgen en wij niet. In het echt als iemand drugs probeert te verkopen op-rondom het vliegveld maak je ook een melding bij de Koninklijke Marechaussee i.p.v de politie, Hierbij stel ik wel voor dat de politie nogsteeds deze melding krijgt maar wij ook want het kan zijn dat afhankelijk van de specifieke situatie, de politie ter plaatse sneller beschikbaar is om te reageren op een melding van drugsverkoop.

### Wat lost deze feature op?

Dat de KMAR ook drugsmeldingen krijgt in douanegebieden (stad) aangezien het de taak is van de Marechaussee te controleren in de doaunegebieden en de drugshandel/smokkel tegen te gaan.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dit zal teveel werk gaan worden omdat de drugs zones constant zullen wijzigen, wellicht kun je dan beter overleggen om het gewoon door heel de stad te ontvangen? Moet je maar even kijken met korpsleiding :)
