### ISSUE TITLE
[FEATURE]: Voertuig logo bij helipads

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2372]
### Contact Details

larrsss

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Er kwam een suggestie vanuit de KMAR om een voertuig punt weg te zetten bij helipads. (Dit op de plek bij de dozen, zie screenshot.) Dit is handig voor bij kustwacht controles, zodat niet heel helipads vol staat met KMAR/politie voertuigen wanneer we hier mee bezig zijn. 

Locatie voertuig punt (voertuig pakken & wegzetten)
![image](https://github.com/Tedeapolis/development/assets/112424697/e3c9ea20-4af1-478f-b69d-0e6536bec443)

### Wat lost deze feature op?

Geen 1000 voertuigen meer op helipads als de KMAR bezig met kustwacht controles/zo kunnen we in het geheim een kustwacht doen. Als mensen nu al die voertuigen zien weten ze direct dat er een kustwacht bezig is. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
