### ISSUE TITLE
[FEATURE]: ANWB item cirkel winkel

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2373]
### Contact Details

destefanokiller

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

- [ ] Ik zal graag een winkelcirkel willen krijgen bij de ANWB balie waar elk persoon in de stad banden, reparatie gereedschap kist, jerrycan, washandschoenen en een brandblusser kunnen kopen, is het mogelijk dat deze wordt geplaatst op de onderstaande coördinaten? 

**Kosten van de items:**
Banden: €1750,-
Brandblusser: €2500,-
Reparatie gereedschap: €5000,-
Jerrycan: €525,-
Washandschoenen: $30,-

**Coords:**
https://cdn.discordapp.com/attachments/827239942903955496/1208859907562934292/image.png?ex=65e4d185&is=65d25c85&hm=8ce660290599f46d267968d46458b3474fb49f2ee223f58d4c2131ccec18deba&

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik heb dan wel coordinaten nodig, en banden ga ik wel op 2500 houden, anders kan ik die van de rest in de stad ook net zo goed gelijk aanpassen :P

**Comment by DeStefanoKiller** [comment]
> Ik heb dan wel coordinaten nodig, en banden ga ik wel op 2500 houden, anders kan ik die van de rest in de stad ook net zo goed gelijk aanpassen :P

Dit zijn de coördinaten waar de cirkel moet komen https://prnt.sc/Tq6pYD-ySq0I

En als het goed is zijn banden 1750 in de stad? Ik heb de prijzen namelijk aangehouden die aangegeven staan in de cirkel bij Mega Mall (postcode 4015)

@Tom974

**Comment by Coolcooli** [comment]
Added na restart
