### ISSUE TITLE
[FEATURE]: Verhoog max aantal voertuigen op tweedehands - STAFFOVERLEG GOEDKEURING

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2374]
### Contact Details

xuify

### Goedgekeurd door

Staffoverleg van 18 februari 2024

### Beschrijf zo duidelijk mogelijk de feature

Het maximale hoeveelheid voertuigen dat een individu kan verkopen verhogen van 2 naar 4 voertuigen.

### Wat lost deze feature op?

2e hands meer vullen & actiever maken. Dit zorgt er voor dat er meer gecardealt kan worden ingame.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
zal na de restart gefixed zijn
