### ISSUE TITLE
[Bug]: Exotica Paaldans Emote

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2375]
### Contact Details

dyon.

### Wat gebeurde er?

Sinds kort is 1 van onze palen bugged omdat de paaldans emote een meter naar links verplaatst is, zichtbaar op de foto hier onder.

![image](https://github.com/Tedeapolis/development/assets/120292087/754f2c29-38ed-4cd6-a8bd-382c8a263cd2)

Hierdoor is ook de emote nu op de verkeerde plek, zichtbaar op de foto hier onder.

![image](https://github.com/Tedeapolis/development/assets/120292087/2dbbea43-360f-4b71-ad90-73706e39f955)

Het gaat om de paal op deze coords:
![image](https://github.com/Tedeapolis/development/assets/120292087/551d6e0f-5820-4335-afd0-697a0e165b4a)

### Wat hoorde er te gebeuren?

Dat je de paaldans emote op de paal doet :)

### Wat veroorzaakt de bug?

Dat de emote op de verkeerde plek is gezet

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na restart

**Comment by Dyon033** [comment]
https://medal.tv/games/gta-v/clips/23WI0qJI33knFy/d1337BbIZM5y?invite=cr-MSxTZlYsNDg1Nzc3ODMs

@DevvTDA Hij zit er nog steeds ruim naast😳Heb er even een clip bij gestuurd
