### ISSUE TITLE
[FEATURE]: TAXI Rang aanpassingen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#2376]
### Contact Details

timez.

### Goedgekeurd door

N.V.T.

### Als eerst willen we graag de jobcode van manager iets lager zetten omdat we er een aantal rangen bij willen boven.
- [ ] taxi 950 - Manager veranderen naar jobcode 910
-
- [ ] **Nieuw loon:** taxi 1000 - Baas: (Indienstloon: 2000)
- [ ] **Nieuw loon:** taxi 970 - Chef: (Indienstloon: 1800)
- [ ] **Nieuwe rang:** taxi 950 - Cursus-Leiding: (Indienstloon: 1600 Uitdienstloon: 1150)
- [ ] **Nieuwe rang:** taxi 940 - Air-Leiding: (Indienstloon: 1600 Uitdienstloon: 1150)
- [ ] **Nieuwe rang:** taxi 930 - Voorraad-Leiding: (Indienstloon: 1600 Uitdienstloon: 1150)
- [ ] **Nieuwe rang:** taxi 920 - EHBO-Leiding: (Indienstloon: 1600 Uitdienstloon: 1150)
- [ ] **Nieuw loon/Jobcode:** taxi 910 - Manager: (Indienstloon: 1500)
- [ ] **Nieuw loon:** taxi 900 - Recruiter (Indienstloon: 1250)
- [ ] **Nieuw loon:** taxi 850 - Marketing (Indienstloon: 1250)
- [ ] **Nieuwe rang:** taxi 820 - Voorraadbeheer: (Indienstloon: 1100 Uitdienstloon: 500)
- [ ] **Nieuwe rang:** taxi 810 - Air: (Indienstloon: 1100 Uitdienstloon: 500) 
-
- [ ] Voor de rangen: Cursus-Leiding, Air-Leiding, Voorraad-Leiding & EHBO-Leiding willen we dezelfde perms en kleding als die van Manager.
- [ ] Voor de rangen: Voorraadbeheer & Air willen we dezelfde perms en kleding als die van Uber-1.

*Al het geld uit de taxi pot word door ons zelf verdiend en deze word **niet** aangevuld door staff*

### Wat lost deze feature op?

Duidelijkheid in de rang verdeling van de Taxi. Wij hebben in de afgelopen maanden een aantal extra neventaken er bij gekregen, Hierbij willen wij daar dus ook rangen voor toevoegen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Vanuit SA+ overleg is dit afgekeurd, we zullen geen extra rangen toevoegen ook zullen de prijzen blijven staan zoals het nu is.
