### ISSUE TITLE
[EUP]: Saints kleding

### ISSUE THREAD

**Issue by SaintsTDA** [Tedeapolis/development#2377]
### Contact Details

.thomasss. 

### Goedgekeurd door

Mila

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Saints jasje toevoegen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
zit er na de restart in
