### ISSUE TITLE
[Bug]: Flightschool helikoptoren despawnen als je ze op slot wil doen.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2378]
### Contact Details

Xuify

### Wat gebeurde er?

Wanneer je een helikopter van de flightschool gebruikt en je doet deze op slot dan despawned hij.
Het zelfde effect heb bij ingespawnde voertuigen. Ik vermoed dat het te maken heeft omdat de helikoptoren niet echte toestellen zijn en ook niet echt hard kenteken hebben. Mijn kenteken van alle toestellen zijn bijvoorbeeld PH NOM.

### Wat hoorde er te gebeuren?

Dat je een toestel op slot kan doen zonder dat deze despawned.

### Wat veroorzaakt de bug?

Door op de "u" toets te drukken van je toetsenbord.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed na restart
