### ISSUE TITLE
[FEATURE]: Handeling aanpassen Amarok ambulance

### ISSUE THREAD

**Issue by Jordy-Kolb** [Tedeapolis/development#2381]
### Contact Details

jordy_kolb

### Voertuig model

Volkswagen Amarok

### Omschrijf de bug

Amarok heeft lage snelheid en trekt traag op, we willen graag dat dit ongeveer gelijk is met de Sprinter.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Het is een offroader met een reden, een gwagon houdt een brabus ook niet bij met optrekken. Deze is helaas afgewezen.
