### ISSUE TITLE
[Bug]: Taxi pot

### ISSUE THREAD

**Issue by cghsnl** [Tedeapolis/development#2382]
### Contact Details

Endorsite 

### Wat gebeurde er?

taxi pot werkt niet meer kunnen geen geld meer uit halen het menu is niet meer zichtbaar

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Is geen bug, je zult hiervoor bij nander moeten wezen.
