### ISSUE TITLE
[EUP]: ANWB Broek 4 schoenen komen door broek

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2385]
### Contact Details

mrmartin02

### Goedgekeurd door

destefanokiller

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De schoenen van ANWB Broek 4 komen door de broek heen. Het zijn schoenen 1: 25. Het lijkt ons beter om deze te wijzigen naar schoenen 1: 71.
![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/8c7404f0-ce49-441f-9e2c-92a35e680ac5)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed

**Comment by goudvis02** [comment]
@DevvTDA De schoenen staan nu op 70 en glitchen nog steeds door de broek. Is het mogelijk dat deze naar 71 aangepast kunnen worden?
![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/bbdb9233-3c19-461f-baae-d770e8b435ad)
![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/2300f049-2079-4660-bd5e-4a2ea6cc7c84)
