### ISSUE TITLE
[FEATURE]: Justitie rang aanpassen

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2386]
### Contact Details

.jarno.

### Goedgekeurd door

Justitie leiding

### Beschrijf zo duidelijk mogelijk de feature

graag zouden wij de rang: Meester in Rechten toegang willen geven tot het kopje "personeelsbeheer" in onze cirkel 
![image](https://github.com/Tedeapolis/development/assets/128511055/84ab74c7-03a0-4284-99d6-ba2682d1ee11)
 Graag de zelfde rechten als een OVA (Deken van de orde)

### Wat lost deze feature op?

Dat leiding van de rechters mensen kan aannemen/ontslaan/promoveren

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed na restart
