### ISSUE TITLE
[FEATURE]: F6 menu justitie

### ISSUE THREAD

**Issue by WiebeZevenhuis** [Tedeapolis/development#2388]
### Contact Details

Zevenhuis aka TDA Wiebel

### Goedgekeurd door

Superadmin +

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden graag voor justitie een F6 menu willen met facturen sturen. Dit omdat met de civivle rechtszaken we vaak boetes uitdelen zijn we altijd afhankelijk van andere mensen die niet tijd hebben. Daarom willen wij graag dat wij als justitie een boete kunnen sturen. Dit geld zou dan de justitie pot in komen. De boete is een eigen bedrag wat wij zelf kunnen invullen.

### Wat lost deze feature op?

Zodat wij zelf ook iets kunnen doen ipv wachten op anderen die niet kunnen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done, ik hoor wel of het werkt of niet
