### ISSUE TITLE
[Bug]: TAXI Hersenloze locaties 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#2390]
### Contact Details

timez.

### Wat gebeurde er?

Wij hebben een aantal locaties ontvangen van onze chauffeurs die niet helemaal kloppen en/of niet super handig zijn. Geen idee wat er fout is gegaan maar het zijn 3 locaties die niet helemaal naar behoren werken. Zouden deze toevallig weg gehaald kunnen worden? 

### Wat hoorde er te gebeuren?

Dat de hersenloze locatie werkt naar toebehoren. Wij waren er al bang voor dat er misschien een aantal locaties niet helemaal zouden werken met het aantal locaties die wij hebben ingestuurd. Echter komen wij dit pas te weten na dat de locaties toegevoegd waren.

### Wat veroorzaakt de bug?

Ik vermoed een fout met coords? Vermoed dat jullie hier wat meer in kijk op hebben dus zou top zijn als iemand hier naar zou kunnen kijken!

Coords van de locaties die niet werken:
{x = -2172.91, y = 422.89, z = 147.49},
{x = -1902.61, y = 2513.26, z = 3.01},
{x = 3640.68, y = 3775.05, z = 28.15},
![image](https://github.com/Tedeapolis/development/assets/93401910/278457d2-e971-420e-aefc-3af35fe65b3a)
![image](https://github.com/Tedeapolis/development/assets/93401910/00554474-f392-445c-be21-4cbb8d411717)
![image](https://github.com/Tedeapolis/development/assets/93401910/4aae37be-1dfd-4f37-b21e-fc3c6cf45568)

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Zou je de coordinaten zelf kunnen zoeken in de post waar ik de coordinaten overhandigd kreeg? Scheelt mij best wat werk xD 
https://github.com/Tedeapolis/development/issues/2379

**Comment by TedeaTaxi** [comment]
{x = 3639.94, y = 3775.96, z = 271.86},
{x = -1902.28, y = 2512.52, z = 20.74},
{x = -2172.80, y = 421.75, z = 12.88},

Deze 3 komen er het meest in overeen. Wat wel gek is is dat ze Z compleet anders is maar X & Y vrijwel perfect overeen komen

**Comment by TedeaTaxi** [comment]
> Zou je de coordinaten zelf kunnen zoeken in de post waar ik de coordinaten overhandigd kreeg? Scheelt mij best wat werk xD #2379

{x = 3639.94, y = 3775.96, z = 271.86},
{x = -1902.28, y = 2512.52, z = 20.74},
{x = -2172.80, y = 421.75, z = 12.88},

Deze 3 komen er het meest in overeen. Wat wel gek is is dat ze Z compleet anders is maar X & Y vrijwel perfect overeen komen

**Comment by DevvTDA** [comment]
gefixt na de restart
