### ISSUE TITLE
[FEATURE]: Banden autotrailers resetten

### ISSUE THREAD

**Issue by jaim1114** [Tedeapolis/development#2391]
### Goedgekeurd door

Tom

### Beschrijf zo duidelijk mogelijk de feature

De banden van alle autotrailers resetten, zodat sommige trailers niet meer te grote banden hebben.

### Wat lost deze feature op?

Bovenstaand probleem, mensen mogen zelf niet tunen dus moet via development.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Door de wipe was alles weggehaald dus dit is niet meer nodig
