### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2393]
### Contact Details

xuify

### Wat gebeurde er?

Ik had een github issue gemaakt over de flightschool helikoptoren. Deze was afgerond helaas is het probleem niet opgelost en zelfs erger geworden. Wij ervaren nu de volgende problemen:

- De FS heli heeft geen kenteken meer
- Eerst als we in e ATC zaten hadden we bovenaan een lijst met wie er allemaal inzat, deze is nu niet meer zichtbaar
-Moment dat je je heli wilt wegzetten krijg je de melding dat je niet de eigenaar bent van het voertuig, denk dat dit komt doordat er geen kenteken gekoppeld is
- De foutmelding voor opslot zetten krijg je nog steeds en na 2x klikken despawned je voertuig

![image](https://github.com/Tedeapolis/development/assets/141491362/65b5d47f-5453-471c-b0c2-9f5004f37445)
Hier zie je dat de toestellen geen kenteken meer hebben.

![image](https://github.com/Tedeapolis/development/assets/141491362/4a8ee5e2-d31e-45c1-9a48-6a64a0782cba)
Hier zie je dat je wel in de ATC zit maar de id's niet meer kan zien.

![image](https://github.com/Tedeapolis/development/assets/141491362/da6135e3-f28e-4f97-adb7-19b89d9f66a9)
Hier zie je de foutmelding als je het toestel weg probeert te zetten.

![image](https://github.com/Tedeapolis/development/assets/141491362/58db8001-25a4-4cc8-9ef0-8ecb142644f9)
Deze foutmeldingen krijg je als je het toestel op slot probeert te doen.

### Wat hoorde er te gebeuren?

Dat je het toestel weg kan zetten in de cirkel, dat je het toestel op slot kan doen en dat je de personen in de ATC kan zien.

### Wat veroorzaakt de bug?

Op "u" klikken, je voertuig proberen weg te zetten in de rode cirkel en in de ATC zitten.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed na restart
