### ISSUE TITLE
[FEATURE]: Verplaatsen Interactie Menu van Penthouse Appartementen

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2394]
### Contact Details

dyon.

### Goedgekeurd door

Mila

### Beschrijf zo duidelijk mogelijk de feature

Op het moment zit het interactie menu van penthouse appartementen bij de balie: 
![image](https://github.com/Tedeapolis/development/assets/120292087/e98ff0a8-3490-46fb-bb80-68282f0bd715)
Echter gebruiken mensen hierdoor amper het appartement. Er is een suggestie aangemaakt deze te verplaatsen naar het bureau zoals hier onder:
![image](https://github.com/Tedeapolis/development/assets/120292087/cea1fdd2-4674-4d1c-ab3e-e9be0cf9b636)

Mila heeft mij gevraagd hier een github voor te maken zodat hier naar gekeken kan worden of dit mogelijk is.

### Wat lost deze feature op?

Dit zorgt er voor dat er meer gebruik gemaakt word van het volledige appartement in plaats van alleen de entree.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik denk dat ik heel veel mensen boos ga maken als ik dit ga doen, Het is bij ieder appartement hetzelfde en ik denk dat het volledig aan jezelf ligt of je het appartement benut of niet.
