### ISSUE TITLE
[FEATURE]: Buggy uit de game halen.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2395]
### Contact Details

Xuify

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

De buggy uit de game halen. De bug zorgt voor problemen wat scenario's verpest en geen refunds geeft. Aan development de speling hoe ze het er uit willen halen, opties die bedacht zijn:
- Tot bepaalde datum mogen quicksellen (mogelijk ook naar tunes kijken).
- Iedereen die een buggy op zijn naam heeft een quicksell percentage geven.

### Wat lost deze feature op?

Veel ticket gezeik en het verpesten van refunds.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
De buggy's zijn verwijderd en refunds zijn uitgeschreven
