### ISSUE TITLE
Sloten

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#24]
De sloten in het ziekenhuis zijn weg. Je kan ook niet meer door de deur lopen omdat ze volledig dicht zijn. Ambulanciers kunnen geen materialen nemen of mensen onderzoeken omdat elke deur opslot is.
![Screenshot_21](https://user-images.githubusercontent.com/68497102/88163140-8620de00-cc12-11ea-9836-d867e8e1a9d0.png)

**Comment by Willem-Dekker** [comment]
dit zou al opgelost moeten zijn.

**Comment by Willem-Dekker** [comment]
graag ff testen en hier in zetten
