### ISSUE TITLE
/takehostage veranderen naar /th

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#240]
Momenteel moet je om een persoon als hostage te nemen een lang woord (/takehostage) typen voordat je iemand daadwerkelijk als hostage kan nemen. Zou dit aangepast kunnen worden naar /th (afkorting van). Dit gaat een stuk makkelijker en zorgt ervoor dat je takehostage in meedere situaties snel kan gebruiken.

**Comment by Willem-Dekker** [comment]
nee dit blijft zo om gespam van het command te voorkomen.
