### ISSUE TITLE
[FEATURE]: Extra ingame rang voor de DJI

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2400]
### Contact Details

Hugo//KlotSjak (Barry S.)

### Goedgekeurd door

Kader en KL

### Beschrijf zo duidelijk mogelijk de feature

De **Dienst Justitiële Inrichtingen** verder genoemd de **DJI** is een neventaak die transporten uitvoert van gevangenen/arrestanten in verschillende omstandigheden/scenario's. 

Binnen de DJI heb je een rangenstelsel waarbij je steeds hoger op kan komen. In overleg met Kader en Korpsleiding willen de mensen van de DJI een extra ingame rang hebben genaamd ''Medewerker Beveiliger''. 
Deze rang moet te komen staan tussen Junior Beveiliger en Medior Beveiliger, dit zodat er extra doorgroei mogelijkheden zijn binnen de DJI en mensen meer te zien krijgen bij de DJI en het werk zich meer eigen kunnen maken. 

Graag hierbij dus het verzoek een extra ingame rang aantemaken tussen Junior Beveiliger en Medior Beveiliger. Dit moet bij de Marechaussee als de Politie.
 
**Rangen stelsel nu** 
**KMAR:** 
/setjob {id} kmar 51 | Marechaussee - DJI - Aspirant
/setjob {id} kmar 52 | Marechaussee - DJI - Junior Beveiliger
/setjob {id} kmar 53 | Marechaussee - DJI - Medior Beveiliger
/setjob {id} kmar 54 | Marechaussee - DJI - Senior Beveiliger
/setjob {id} kmar 56 | Marechaussee - DJI - Adjudant
/setjob {id} kmar 57 | Marechaussee - DJI - Commandant
/setjob {id} kmar 58 | Marechaussee - DJI - Operationeel Directeur
/setjob {id} kmar 59 | Marechaussee - DJI - Algemeen Directeur

**Wat moet het worden:** 
/setjob {id} kmar 51 | Marechaussee - DJI - Aspirant
/setjob {id} kmar 52 | Marechaussee - DJI - Junior Beveiliger
**/setjob {id} kmar (rangnummer) | Marechaussee - DJI - Medewerker Beveiliger**
/setjob {id} kmar 53 | Marechaussee - DJI - Medior Beveiliger
/setjob {id} kmar 54 | Marechaussee - DJI - Senior Beveiliger
/setjob {id} kmar 56 | Marechaussee - DJI - Adjudant
/setjob {id} kmar 57 | Marechaussee - DJI - Commandant
/setjob {id} kmar 58 | Marechaussee - DJI - Operationeel Directeur
/setjob {id} kmar 59 | Marechaussee - DJI - Algemeen Directeur

**Politie rangen:** 
/setjob {id} police 23 | Politie- DJI -Aspirant
/setjob {id} police 24 l Politie- DJI - Junior Beveiliger
/setjob {id} police 25 l Politie- DJI - Medior Beveiliger
/setjob {id} police 26 l Politie- DJI - Senior Beveiliger
/setjob {id} police 27 l Politie-DJl- Adjudant
/setjob {id} police 28 l Politie-DJl- Commandant
/setjob {id} police 36 l Politie- DJI - Algemeen Directeur
/setjob {id} police 39 l Politie- DJI - OperationeelDirecteur

**Wat moet het worden:**
/setjob {id} police 23 | Politie- DJI -Aspirant
/setjob {id} police 24 l Politie- DJI - Junior Beveiliger
**/setjob {id} police (RANGNUMMER) | Politie - DJI - Medewerker Beveiliger**
/setjob {id} police 25 l Politie- DJI - Medior Beveiliger
/setjob {id} police 26 l Politie- DJI - Senior Beveiliger
/setjob {id} police 27 l Politie-DJl- Adjudant
/setjob {id} police 28 l Politie-DJl- Commandant
/setjob {id} police 36 l Politie- DJI - Algemeen Directeur
/setjob {id} police 39 l Politie- DJI - OperationeelDirecteur

### Wat lost deze feature op?

Dat de DJI een extra rang er bij heeft 

**Deze rang moet €1075,- ingame verdienen per 10 minuten salaris storting en de helft hiervan uitdienst.**

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Denk dat er wel genoeg rangen zijn op het moment. Daarnaast zit het zo goed als vol met de rangen.
