### ISSUE TITLE
[FEATURE]: Toevoeging job documenten Ambulance

### ISSUE THREAD

**Issue by Jordy-Kolb** [Tedeapolis/development#2402]
### Contact Details

jordy_kolb

### Goedgekeurd door

jordy_kolb

### Beschrijf zo duidelijk mogelijk de feature

Door wetswijziging hebben wij het volgende stuk tekst geregeld nodig in de ambu dienst, we zien dit graag terug in de standaard job documenten via /docu. 
![Ambu doc](https://github.com/Tedeapolis/development/assets/162512890/df0c8b12-099e-405c-80da-f9ae2fbf1b82)

**Naam document:**
Verklaring Letselschade Ambulance:

**De tekst:** 
[BSN van het slachtoffer]

[Naam van de Ambulancier]

Hierbij verklaar ik, [naam van de ambulancier], dat ik op [datum] gevraagd door [Naam van de agent] ben om de medische gezondheid van [Naam van het slachtoffer] vast te stellen, dit doe ik zodat ik kan vaststellen of er sprake is van zwaar letsel of niet.

Als gevolg van het ongeval heb ik de volgende lichamelijke en/of psychische letsels kunnen vaststellen als ambulancier bij het slachtoffer van het desbetreffende ongeval:

[Beschrijf het eerste letsel, zoals bijvoorbeeld een gebroken arm]
[Beschrijf het tweede letsel, indien van toepassing]
[Beschrijf eventuele andere letsels]

Hierbij verklaar ik dat er [wel/niet] sprake is van zwaar lichamelijk letsel

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Dit zit er na de komende restart in!
