### ISSUE TITLE
[EUP]: ANWB Broek 4 schoenen komen nog steeds door broek heen

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2404]
### Contact Details

mrmartin02

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

De schoenen van ANWB Broek 4 komen nog steeds door de broek heen. Het lijkt ons beter om deze te wijzigen naar schoenen 1: 71. - In de vorige Github zijn de schoenen aangepast naar nummer 70 en niet 71.
![319595675-bbdb9233-3c19-461f-baae-d770e8b435ad](https://github.com/Tedeapolis/development/assets/115710738/b6c3cdf6-6368-4ac1-a1de-3347c93d6834)
![319595727-2300f049-2079-4660-bd5e-4a2ea6cc7c84](https://github.com/Tedeapolis/development/assets/115710738/92816b1c-ad25-4268-a38d-f540329270f6)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart
