### ISSUE TITLE
[FEATURE]: Tape item toevoegen.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2405]
### Contact Details

xuify

### Goedgekeurd door

Burgerraad & overlegd met development.

### Beschrijf zo duidelijk mogelijk de feature

Wanneer een hostage wat minder goed is in RP'en en soms veel schreeuwt of praat doen overvallers soms Tape over de mond met /do. Echter komt het vaak voor dat ze nogsteeds gaan praten of bij de hand gaan doen. Het idee is dat je een item hebt waarmee je dus iemand tape over de mond kan plakken en dus zijn mond hiermee kan snoeren, dit mute dus dan ook de mumble voor die persoon.

Aan development de vrijheid hoe je aan tape kan komen (specifieke shop? gang lvl 1 shop? offi shop? iets anders?). 
Tape moet je van de mond af gehaald kunnen worden netzoals /bag. 
Tape moet na zoveel tijd er vanzelf af gehaald worden (10 min ongeveer) met een melding "Je hebt de tape succesvol van je mond af gehaald".
(earplugs toevoegen?!?! Het zelfde idee maar dan dat je niks kan horen).

### Wat lost deze feature op?

Koters

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Done, de criminelen moeten zelf nog even een goed idee bedenken voor het verkrijgen van het item, dus daar wacht ik even op met het toevoegen zelf. het script is iig klaar en ready voor gebruik
