### ISSUE TITLE
[EUP]: Psychologie vrouwen bij de ambulance klopt niet meer. 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2406]
### Contact Details

elizestolemyname

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

![image](https://github.com/Tedeapolis/development/assets/167293905/d9f0c4e3-1801-4fc6-9e37-ba1a10e9842d)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by RoxyFay** [comment]
Graag veranderen we hem naar: 
shirt1: 7
shirt2: 0

torso 1: 767 
torso 2: 1

broek 1: 215
broek 2: 6

schoenen 1: 173
schoenen 2: 0

![image](https://github.com/Tedeapolis/development/assets/167293905/94647e0d-75bd-48c4-80d6-0601b5807e4f)


![image](https://github.com/Tedeapolis/development/assets/167293905/c7ea4ab9-d2bc-4e6b-b431-ae8671478068)

**Comment by DevvTDA** [comment]
fixed
