### ISSUE TITLE
[Bug]: Emote anwb3 werkt niet voor vrouwen

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2407]
### Contact Details

mrmartin02

### Wat gebeurde er?

Als je /e anwb3 als vrouw doet, gebeurd er niks.

### Wat hoorde er te gebeuren?

De emote /e anwb3 zoals bij de mannen.

### Wat veroorzaakt de bug?

Onbekend.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

nvt

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Komt omdat GTA deze emote alleen voor mannen heeft gemaakt. Dit is dus niet te fixen tenzij iemand een custom emote maakt :)
