### ISSUE TITLE
[EUP]: ANWB Inwerkingsvestje kan niet gedragen worden door vrouwen

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2408]
### Contact Details

mrmartin02

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Het ANWB inwerkingsvestje kan niet gedragen worden door vrouwen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen
![afbeelding](https://github.com/Tedeapolis/development/assets/115710738/89abba0e-56fd-4e44-97f1-33c6aad56e7a)

**Comment by Tom974** [comment]
Is dit een bug of een feature request voor een vestje voor vrouwen? Ik gok namelijk het tweede. Kun je het beste even een nieuwe issue aanmaken waarin je het vestje aanvraagt ;p
