### ISSUE TITLE
[Bug]: Telefoon gebruik in de gevangenis

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2411]
### Contact Details

larrsss

### Wat gebeurde er?

Wanneer een gevangene die gejaild is zijn telefoon wilt gebruiken gaat dit niet.

### Wat hoorde er te gebeuren?

Dat een gevangene zijn/haar telefoon gewoon kan gebruiken in de gevangenis als hij/zij is gejaild.

### Wat veroorzaakt de bug?

Hierdoor kunnen de gevangenen niet bellen (waar ze wel recht op hebben volgens de TDA wetgeving) 1 belletje per dag.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dit is geen bug.
