### ISSUE TITLE
Aanpassingen rangen Sabini Cartel

### ISSUE THREAD

**Issue by broodjepirri** [Tedeapolis/development#2412]
### Contact Details

pirrib

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

_We hebben wat rang aanpassingen_

**Rang die weg kan:**
- Moglie Del Capo

**Nieuwe rol**
- Il Poccioto V

Deze kan toegevoegd worden boven de normale Il Poccioto.
Deze rol zal alles moeten kunnen hebben zoals La Banda rol

**Hoe zit het rangstel er dan uit?**
Il Capo (Zelfde)
Il Capobastone (zelfde)
Il Sottocapo (zelfde)
Il Consigliere (zelfde)
Il Caporegime (Zelfde)
Il Capitano (Zelfde)
il guardaspalle (nieuwe rang zelfde perms als La Coragna)
la Coragna (Zelfde)
La Banda (Zelfde)
**Il Poccioto V (NEW --> Zelfde perms zoals La Banda)**
Il Poccioto (Zelfde)
Il Borsailolo (Zelfde)

### Wat lost deze feature op?

Door deze veranderingen kunnen we ervoor zorgen dat vertrouwde mensen binnen de groep sneller dingen kunnen uitvoeren binnen de groep, denk aan in de opslag gaan. Wij proberen ervoor te zorgen dat mensen niet zomaar 1,2,3 promotie kunnen ontvangen maar willen er wel voorzorgen dat alles constant blijft draaien binnen de groep, dus ook het werk binnen de stad omtrent aannemen, uitbetalen, zakken verkopen willen we constant welvaart door laten gaan. We hopen dat ook met deze rol voor die personen die we vertrouwen op die manier een positieve verandering erin kunnen krijgen voor ze.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
oeh, fancy issue die makkelijk te lezen is.

Fixed na de restart

**Comment by broodjepirri** [comment]
Kan het kloppen dat het al in de github stond maar na de restart nog niet in game is gekomen? Waarschijnlijk zeker pas de volgende restart?
