### ISSUE TITLE
[EUP]: ANWB Inwerkingsvestje voor vrouwen

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2413]
### Contact Details

mrmartin02

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Het ANWB inwerkingsvestje dat al bestaat kan alleen gedragen worden door mannen. Wij zouden graag willen zien dat het vestje ook beschikbaar wordt gemaakt voor vrouwen.
![323263190-89abba0e-56fd-4e44-97f1-33c6aad56e7a](https://github.com/Tedeapolis/development/assets/115710738/60328d79-322d-422c-aee4-09e8bd4f1536)

### Wat lost deze feature op?

Dat vrouwelijke collega's ook het inwerkingsvestje kunnen dragen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dan moet er wel een hesje voor zijn xD

**Comment by DevvTDA** [comment]
fixed na de restart
