### ISSUE TITLE
[FEATURE]: Cirkel in het ziekenhuis om je uiterlijk aan te kunnen passen! 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2415]
### Contact Details

elizestolemyname

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

In het vorige ziekenhuis hadden wij achterin een paarse cirkel waarin je je uiterlijk kon aanpassen.
Dit is de zelfde cirkel als in het gemeentehuis, alleen betaalde je in het ziekenhuis €10.000,- hier voor. 
Er werd veel gebruik van gemaakt. 

We willen deze cirkel onder de trap in de lift. Toen we eerder in dit ziekenhuis zaten zat hij ook op deze plaats.
![image](https://github.com/Tedeapolis/development/assets/167293905/292fa39a-aee1-4862-9c1b-f754bafc63b1)

### Wat lost deze feature op?

Mensen kunnen gemakkelijk hun uiterlijk aanpassen. 
Nu krijgen we regelmatig de vraag waar de cirkel is gebleven, en het wordt soms ook gezien als plastische chirurgie cirkel. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Dit is toegevoegd!
