### ISSUE TITLE
[EUP]: staff eup uitbreiden

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2417]
### Contact Details

xuify

### Goedgekeurd door

Staff overleg

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Ik dacht dat ik hier een github voor gemaakt had maar ik kan  het niet terug vinden, indien hier al een github issue voor is kan deze uiteraard gesloten worden.

Staff eup uitbreiden, dit betekend ANWB outfit en ambulance outfit (het liefst 1 click outfits) toevoegen aan het staff eup. Dit is puur om de RP te bevorderen en minder staffleden op de straten te zien. Dit mag natuurlijk niet geabused worden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
Als jij voor mij van zowel vrouw als man en welke baan je wilt hebben moet ik of de nummers weten of gewoon hoe de outfit heet in hun eup @NovaGazer3

**Comment by NovaGazer3** [comment]
@DevvTDA 
**Ambulance**
  Man: eup -> Ambulance Uniform -> Ambulancier (man) _(zie foto 1)_
  Vrouw: eup -> Ambulance Uniform -> Ambulancier (vrouw) _(zie foto 2)_
  
**ANWB**
  Man: T-shirt1: 15 **|** Torso1: 15 **|** Broek1: 88 **|** Schoenen1: 24
  Man: T-shirt1: 15 **|** Torso1: 134 **|** Broek1: 50 **|** Schoenen1: 24


![image](https://github.com/Tedeapolis/development/assets/141491362/bbf8a3e0-fbfb-41ff-8b04-5f13882065e0)
![image](https://github.com/Tedeapolis/development/assets/141491362/0a52cf98-7493-446c-944d-21a756cbc6e8)
![image](https://github.com/Tedeapolis/development/assets/141491362/4a72c289-e248-4c22-8fde-630d707e5556)
![image](https://github.com/Tedeapolis/development/assets/141491362/ade0ee83-a0d4-4a39-9f81-ca84acf6cd54)

**Comment by DevvTDA** [comment]
zit erin na de restart!
