### ISSUE TITLE
[FEATURE]: Aanpassing voertuig overschrijf tekst.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2418]
### Contact Details

Xuify

### Goedgekeurd door

Staffoverleg 21-04-2024

### Beschrijf zo duidelijk mogelijk de feature

De overschrijf tekst van 1 euro aanpassen aangezien nieuwe spelers dachten dat je voertuigen mocht scammen wegens de niet helemaal duidelijke melding.

"LET OP: Je wilt je voertuig gaan verkopen voor € 1. Oplichting met voertuigen is tegen de serverregels. Voorkom oplichting en verkoop nooit je voertuig voor €1. Vul altijd het volledige koopbedrag in, zodat deze automatisch bij de koper kan worden afgeschreven. Als je toch door wilt gaan, typ dan het volgende: "<voertuignaam>""

### Wat lost deze feature op?

De verwarring voor nieuwe spelers dat het mogelijk onduidelijk is. Tuurlijk in de APV staat dat het niet mag echter maakt dit het makkelijker om speel gewijs de APV te leren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
denk dat die tekst veelste lang is maar we zullen zien
