### ISSUE TITLE
[FEATURE]: Extra opslagpunt politiebureau (ruimte achter de balie)

### ISSUE THREAD

**Issue by jaim1114** [Tedeapolis/development#2419]
### Contact Details

jaim. (Vente)

### Goedgekeurd door

KL

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden vanuit de politie graag een extra opslagpunt willen, op de volgende locatie: 
https://prnt.sc/qJsHVW1pTpb6 

X: -1091.40 Y: -834.89 Z: 19.00 H: 208.31

Dit is een kleine kamer in de gang achter de balie. Dit om het dagelijkse balieuurtje gemakkelijker te maken voor dienstdoende agenten.

Graag zouden we de volgende opties willen bij dit opslagpunt:

- Object nemen van opslag
- Object opbergen in opslag

Met opslagpunt bedoelen we net zoals dit: https://prnt.sc/vW1VFm6qwO7- (voorbeeld), alleen dan zonder de laatste 2 opties. Alvast bedankt!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik heb dit eerder al eens afgekeurd, dus nee gaat niet toegevoegd worden. Er zijn genoeg opslagplekken om spullen te pakken.
