### ISSUE TITLE
[Bug]: Eiland cartel cirkels werken niet

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2421]
### Contact Details

xuify

### Wat gebeurde er?

Wanneer je naar een cirkel van eiland cartel gaat gebeurt er precies niks. Ook krijg je geen foutmeldingen in f8 binnen of wat dan ook.
Dit geld voor alle cirkels, oftewel voor voertuig en wapenopslag cirkels. Dit zou wel het zelfde probleem zijn.
Ik heb het ook geclipt maar dat is verder niet zo spannend, via f8 komt er nooit wat relevants binnen wanneer ik er in loop en ook niet als ik op e druk.

https://youtu.be/CtE6KdP9Xf4

### Wat hoorde er te gebeuren?

Dat de cirkels werken.

### Wat veroorzaakt de bug?

Eerder de vraag wat veroorzaakt de bug niet :)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
related to https://github.com/Tedeapolis/development/issues/2424
