### ISSUE TITLE
[Bug]: Flightschool atc werkt niet meer.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2422]
### Contact Details

xuify

### Wat gebeurde er?

Wanneer je vanaf de grond de ATC wil joinen kan dit ineens niet meer bij de flightschool. Dit is al een paar weken echter was ik vergeten een github te maken. 

### Wat hoorde er te gebeuren?

Dat je vanaf de grond de ATC kan joinen zodat je mensen in de ATC kan beantwoorden en eventueel striken als ze de regels overtreden.

### Wat veroorzaakt de bug?

Niet in een helikopter zitten en de atc joinen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Fixed
