### ISSUE TITLE
[Bug]: Cirkels BarkPolis

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2424]
### Contact Details

yohandessu / .jarno.

### Wat gebeurde er?

De cirkel om de voertuigen te pakken werken niet 
![image](https://github.com/Tedeapolis/development/assets/128511055/ed59b62f-74fd-478c-853b-5b6c0bf4a99d)

### Wat hoorde er te gebeuren?

Dat je wel de voertuigen kan pakken

### Wat veroorzaakt de bug?

Is sinds de kluisjes update, met de barkpolis rang kan je ook alle kluisjes beheren 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

geen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
related to https://github.com/Tedeapolis/development/issues/2421
