### ISSUE TITLE
[Bug]: Brandstof is nogsteeds vol na reparatie 

### ISSUE THREAD

**Issue by AlfieSolomons1903** [Tedeapolis/development#2425]
### Contact Details

.furkan1903

### Wat gebeurde er?

Brandstof wordt automatisch bijgevuld na de reparatie van de wegenwacht

### Wat hoorde er te gebeuren?

Brandstof moet niet worden bijgevuld na de reparatie 

### Wat veroorzaakt de bug?

-

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed
