### ISSUE TITLE
[FEATURE]: Ducttape

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2426]
### Contact Details

iHax0r

### Goedgekeurd door

Burgerraad & Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Ducttape is momenteel een feature die toegevoegd is in de game, je kan het alleen nog niet verkrijgen. Nu is het voorstel om dit toe te voegen aan de mdealer voor een bedrag van €500,-. Wellicht ook een kleine kans dat je het krijgt bij de huisinbraken, zodat hier ook een extraatje uit te halen is.

### Wat lost deze feature op?

Mensen die schreeuwen wanneer ze ontvoerd zijn en hun mond moeten houden. De item moet alleen gebruikt worden indien mensen zich echt misdragen, dus niet bij alles en iedereen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Staat op 2500 totdat er een fatsoenlijk idee komt.
