### ISSUE TITLE
[FEATURE]: Force Feeden van hostages

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2428]
### Contact Details

dyon.

### Goedgekeurd door

Besproken in BurgerRaad

### Beschrijf zo duidelijk mogelijk de feature

Een functie om hostages te voeren.
Idee is als volgt:

- Er komt een command "request_feed" dit werkt alleen bij mensen die geboeid zijn. (voor officiële gangs komt dit in de F6).
- Je komt in een menu waar je alle voedsel items in je inventory te zien krijgt.
- Door er op te klikken kan je dit voedsel item voeden aan de hostage.
- De hostage krijgt eten/drinken er bij per item dat hem gevoed word.

### Wat lost deze feature op?

Dit zorgt er voor dat je hostages niet steeds meer hoeft te ontboeien omdat ze dood gaan van de honger/dorst. 

Dit ontboeien zorgde er namelijk wel vaker voor dat hostages hierna gingen kloten omdat ze niet meer geboeid waren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by iHax0rMC** [comment]
In stafoverleg is besproken om dit puntje aan te passen, force feeden zal niet worden toegevoegd.
Wanneer je iemand ontboeit krijg je de tiewraps terug, aangezien dit in het echt vaak ook mogelijk is met tiewraps handboeien. Hiermee voorkom je dat force feeden misbruikt kan worden en lost dezelfde issues op.
