### ISSUE TITLE
[FEATURE]: Extra tankstations voor Heli's/Vliegtuigen

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2429]
### Contact Details

dyon.

### Goedgekeurd door

Besproken in BurgerRaad

### Beschrijf zo duidelijk mogelijk de feature

Na aanleiding van afgelopen burgerraad hier een lijst met locaties voor extra tankstations voor helikopters/vliegtuigen:

1.
![image](https://github.com/Tedeapolis/development/assets/120292087/6075dc5b-f69d-428a-ba06-e487b0f083fe)
![image](https://github.com/Tedeapolis/development/assets/120292087/6bdc6b06-8d97-45f1-a954-e94107e5a5ea)

2.
![image](https://github.com/Tedeapolis/development/assets/120292087/ed60f26a-f480-4915-b2b5-c59744a1f03a)
![image](https://github.com/Tedeapolis/development/assets/120292087/29723b68-a523-4493-9e0b-a6fb8d307ebb)

3.
![image](https://github.com/Tedeapolis/development/assets/120292087/d36f78f3-2907-4549-8dd7-169de8b76f7a)
![image](https://github.com/Tedeapolis/development/assets/120292087/209fcac5-9e7b-4375-8946-a83f3999b714)

4.
![image](https://github.com/Tedeapolis/development/assets/120292087/2842b65a-92ae-496d-93bc-8cbd51253e17)
![image](https://github.com/Tedeapolis/development/assets/120292087/fd8b13b3-f58d-4d0e-8bf8-f992c2c43059)

### Wat lost deze feature op?

Dit zorgt er voor dat je op meer plekken kan landen met je helikopter/vliegtuig om hem bij te tanken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Ik zal deze oppakken!

**Comment by Zjefvm** [comment]
Done!
