### ISSUE TITLE
Uitbetaling Pro Deo advocatuur door politie

### ISSUE THREAD

**Issue by PapaXilion** [Tedeapolis/development#243]
Hai!

Ik merk en hoor bij mijn advocaten dat de betaling van pro deo zaken niet lekker loopt.
Na elke zaak wordt er via /docu een document opgesteld door de dienstdoende agent, waarna dit document aan de korpsleiding gegeven kan worden voor betaling uit de politiepot.

Probleem is dat er weinig korpsleiding aanwezig is, of wanneer ze aanwezig zijn, ze te druk zijn voor het handelen van de betaling.
Ik heb uiteraard alle begrip voor de drukte, maar merk wel dat de betaling naar de advocaten zo niet goed loopt.

Om die druk weg te halen aan beide kanten (administratie, 4 stappen voor de uitbetaling, meerdere mensen betrokken) heb ik een voorstel:

- Ofwel we krijgen een mogelijkheid vanuit Justitie om die documenten te vergoeden (dan kan ik het intern oplossen en, uiteindelijk, is het beiden 'overheidsgeld'.)

- Ofwel we krijgen iets van een Pro Deo token (een inventory item), die je kan 'verkopen' in een cirkel bij Justitie (desnoods alleen wanneer in-dienst). Het pro-deo tarief is vast (op 2500) dus zou dit via een item te doen zijn. Deze items kunnen wellicht makkelijker uitgegeven worden, en dan ligt de verantwoording niet meer bij de politie.

Mocht beiden niet gaan, maar je hebt nog een alternatief dan hoor ik dat graag! :-)

**Comment by Willem-Dekker** [comment]
ja ik ga optie 2 maken binnen kort dat je die alleen kan verkopen als je indienst bent en alleen kan krijgen van uit de politie met loggin er op

**Comment by PapaXilion** [comment]
Tof! Goed om te horen, en dank je!
