### ISSUE TITLE
[Bug]: Quicksell werkt niet

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2430]
### Wat gebeurde er?

Wanneer je een voertuig probeert te quicksellen werkt dit niet. Er staat dat het voertuig niet van mij is. En ja, het voertuig was wel van mij. In f8 staat niks behalve het bericht dat je in beeld krijgt.

https://youtu.be/dlSiEpzDZaU

### Wat hoorde er te gebeuren?

Dat de quicksell wel werkt.

### Wat veroorzaakt de bug?

Een voertuig proberen te verkopen.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Kenteken @NovaGazer3 ?

**Comment by NovaGazer3** [comment]
> Kenteken @NovaGazer3 ?
![image](https://github.com/Tedeapolis/development/assets/141491362/4e9a1594-26e0-4b19-8464-39d7c6840bc7)
@Tom974 

MEZ 427
