### ISSUE TITLE
[FEATURE]: Gym op het strand aanzetten.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2432]
### Contact Details

xuify

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Tijdens staff overleg is besproken dat de beach gym weer aangezet kan worden. Deze is in het verleden ook aan geweest alleen zou de basic fit dan amper gebruikt worden. Dat is nu niet meer het geval.

Als het makkelijk aangezet kan worden dmv oude code of iets anders makkelijks dan mag het door gevoerd worden. Als het veel moeite kost mag deze feature afgekeurd worden (dit is ook besproken bij het staff overleg).

### Wat lost deze feature op?

Leuke feature, lost niks op

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
`{["x"] = 256.71, ["y"] = -259.63, ["z"] = 59.93 - 0.98, ["h"] = 75.44, ["exercise"] = "Situps"},`

Als je zelf de coords erin zet vind ik het prima. 

Voor exercises heb je Situps, Chins, loopband, boksbal en weight

**Comment by Tom974** [comment]
@Xuifyy

**Comment by Xuifyy** [comment]
{["x"] = -1204.73, ["y"] = -1564.35, ["z"] = 4.61 - 0.98, ["h"] = 34.45, ["exercise"] = "Chins"},
{["x"] = -1199.99, ["y"] = -1571.14, ["z"] = 4.61 - 0.98, ["h"] = 209.22, ["exercise"] = "Chins"},

{["x"] = -1197.94, ["y"] = -1566.52, ["z"] = 4.61 - 0.98, ["h"] = 337.99, ["exercise"] = "weight"},
{["x"] = -1207.98, ["y"] = -1559.06, ["z"] = 4.61 - 0.98, ["h"] = 327.50, ["exercise"] = "weight"},
{["x"] = -1203.06, ["y"] = -1567.10, ["z"] = 4.61 - 0.98, ["h"] = 210.94, ["exercise"] = "weight"},

Dit lijkt heel weinig maar meer dan dit is er ook niet. Er is geen loopband, situps iets wat voor tda werkt of boksbal. 
Verder viel me op dat Chins en Situps wel met een hoofdletter begint en de rest niet, klopt dit?
@Tom974

**Comment by Zjefvm** [comment]
Na de restart zitten ze in de server!
