### ISSUE TITLE
[FEATURE]: Taken verwijderen als je meer dan een half jaar niet meer in de stad geweest bent.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2433]
### Contact Details

xuify

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Wanneer iemand meer dan een half jaar niet meer ingelogd is geweest mogen alle taken weg gehaald worden van de speler.

### Wat lost deze feature op?

Meer speelplezier bij nieuwe / terugkomende spelers.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
code is af, moet alleen ff nog gepushed worden
