### ISSUE TITLE
[FEATURE]: Toegang tot de sleutels van het ziekenhuis voor de Politie en Kmar intrekken

### ISSUE THREAD

**Issue by ArjanSteenboom** [Tedeapolis/development#2434]
### Contact Details

tbone5192

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij willen zien dat de Politie en Kmar geen toegang meer hebben tot de sloten van het ziekenhuis. Dit is niet een realistisch concept, en wij vinden dat de politie toestemming moet hebben van ziekenhuismedewerkers om toegang te hebben tot bepaalde kamers in het ziekenhuis. 

### Wat lost deze feature op?

Dat agenten niet zomaar, ongevraagd, de kamers binnen stormen tijdens een operatie. Of dat agenten het ziekenhuis voor prive doeleinden gebruiken zonder interactie met ambulance personeel 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Is dit besproken ergens?

**Comment by ArjanSteenboom** [comment]
Is zover ik weet alleen besproken binnen ambulance leiding overleg, niet met anderen. Echter lijkt het alsof de toegang al is weggehaald +- 4 dagen geleden.

**Comment by Tom974** [comment]
Development heeft niks aangepast, maar dan sluit ik de issue
