### ISSUE TITLE
[FEATURE]: Kniptang voor Hoofdofficieren

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2435]
### Contact Details

Hugo//KlotSjak (Barry S.)

### Goedgekeurd door

Kader KMAR

### Beschrijf zo duidelijk mogelijk de feature

Momenteel is het zo dat alleen het Kader toegang heeft tot het kopen van een ''Kniptang'' in de itemshop. 
Na overleg binnen het Kader besloten dit graag te willen toevoegen aan de Hoofdofficieren.

De kniptang mag alleen gebruikt worden volgens de regels die de politie ook heeft:
_Regels omtrent kniptang (Vanuit politie mededeling):_
**Kniptang vanaf inspecteur**:
Zoals jullie weten hebben we bij de politie een kniptang om tiewraps los te maken van deuren. Deze is nu ook voor inspecteur+ beschikbaar in de itemwinkel. Vanaf inspecteur+ mag je de kniptang op zak hebben.
Voor de inzet van de kniptang zijn wel een aantal punten belangrijk:

- _Tiewraps doorknippen mag alleen als laatste redmiddel dienen. Laat de criminelen eerst zelf de deur openmaken, en als dit niet lukt, kunnen wij dat doen.
- De brandweer beschikt ook over een kniptang. Roep altijd eerst de brandweer op om de deuren te openen, inspecteur+ is de laatste optie._

I.v.m. dat er ook Hoofdofficieren zijn met een neventaak binnen bijvoorbeeld de DSI moeten deze ook worden toevoegd aan de DSI rangen. Alleen hoofdofficieren mogen deze pakken, geen DSI leden die lager in rang zijn. Mocht dit wel gebeuren zullen daar zware sancties aan worden verbonden.

**Rangen waar dit aan moet worden toegevoegd:** 
/setjob {id} kmar 45 | Marechaussee - Majoor
/setjob {id} kmar 50 | Marechaussee - Luitenant-Kolonel 
/setjob {id} kmar 60 | Marechaussee - Kolonel
/setjob {id} kmar 72 | Marechaussee - HRB - Groepscommandant
/setjob {id} kmar 73 | Marechaussee - HRB - Sectiecommandant
/setjob {id} kmar 74 | Marechaussee - HRB - Commandant
/setjob {id} kmar 58 | Marechaussee - DJI - Operationeel Directeur
/setjob {id} kmar 59 | Marechaussee - DJI - Algemeen Directeur
/setjob {id} kmar 81 | Marechaussee - DSI Korporaals
/setjob {id} kmar 82 | Marechaussee - DSI Onderofficieren
/setjob {id} kmar 83 | Marechaussee - DSI Officieren
/setjob {id} kmar 86 | Marechaussee - B - Recherche
/setjob {id} kmar 87 | Marechaussee - B - Recherche Senior
/setjob {id} kmar 88 | Marechaussee - B - Recherche Leiding

### Wat lost deze feature op?

Het zorgt er voor dat Hoofdofficieren nu zelfstandig in een situatie kunnen handelen met de kniptang waar dit nodig is zodat er geen Kaderverzoek hoeft gemaakt te worden.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Ik zal deze oppakken.

**Comment by Zjefvm** [comment]
Toegevoegd!
