### ISSUE TITLE
[FEATURE]: DJI Sprinter Dirtlevel aanpassen / bus versterken.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2436]
### Contact Details

Hugo//KlotSjak (Barry S.)

### Kenteken van voertuig

DJI sprinter

### Voertuig model

DJI Sprinter

### Omschrijf de bug

**Het Kader kreeg het volgende signaal:**
- De DJI sprinter (gevangenistransport bus) wat verbeteren, op dit moment gaat hij erg snel kapot & wordt hij erg snel vies. Daarnaast is de tank ook erg snel leeg. Hierdoor kun je vaak wassen,tanken en naar de wegenwacht. Omdat dit een mercedes sprinter is, is dat wel gek.

### Repro

Voertuig pakken en rijden zodat je dit ervaart.

### Normaal gedrag

De sprinter hoort iets sterker te zijn en hoeft niet te snel vies worden, dit zorgt voor een representatievere blik en zie je goed dat het een bus is van de DJI.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by PolitieTDA** [comment]
@Lorenzo3001 Hey man, wanneer word dit gefixt?
