### ISSUE TITLE
[Bug]: kloksysteem politie SIV

### ISSUE THREAD

**Issue by Masteriuss** [Tedeapolis/development#2438]
### Contact Details

masterius#0

### Wat gebeurde er?

Wanneer je het kloksysteem opent in de SIV (Passat als A6) dan freezed deze na een paar seconde/minuten

### Wat hoorde er te gebeuren?

Op het moment dat je het kloksysteem opent en instelt zou deze je eigen snelheid moeten blijven bijhouden en ook kunnen flitsen en niet dat hij freezed

### Wat veroorzaakt de bug?

Je stapt in de Passat of A6, dan open je het kloksysteem met CTRL+M, deze stel je dan in op gewenste snelheid en als je dan gaat rijden freezed het kloksysteem compleet en kan je hem ook niet meer unfreezen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Iets van logbestanden of zegt ie niks in f8?

**Comment by Tom974** [comment]
ah i see, is opgelost bij aanstaande restart.
