### ISSUE TITLE
[FEATURE]: Wapens kunnen renamen in een kluisje

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2439]
### Contact Details

iHax0r

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Momenteel is het niet mogelijk om een wapen die in een kluisje ligt te renamen, wanneer hier tijd voor is dit toevoegen.

### Wat lost deze feature op?

Wapens in een kluisje kunnen renamen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by iHax0rMC** [comment]
Besproken in Burgerraad

**Comment by Zjefvm** [comment]
Dit is recentelijk doorgevoerd.
