### ISSUE TITLE
[Bug]: /refund check fixen

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2440]
### Contact Details

xuify

### Wat gebeurde er?

/refund check is al een tijdje kapot. Momenteel staan er 11 refunds open die ik niet 123 kan vinden. /refund check had het een stuk makkelijker gemaakt.

### Wat hoorde er te gebeuren?

Alle openstaande refunds op een rijtje zien.

### Wat veroorzaakt de bug?

/refund check typen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Relevante log bestanden

"Er is een onbekende fout opgetreden! Error: The fetched channel does not belong to this manager's guild."

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Geen github hiervoor maken, dev-overleg will do.
