### ISSUE TITLE
[FEATURE]: Lijstje met zooi waar nog ANWB in staat ipv Wegenwacht.

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#2441]
### Contact Details

destefanokiller

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

- [x] **Alle** uitdienst rangen hebben nog ANWB als naam staan.
![image](https://github.com/Tedeapolis/development/assets/68514420/18ca3318-672a-432a-9b57-8a46facffb24)

- [x] In-game porto's hebben rechtsonder nog de naam ANWB, gaat om porto frequency 130,131 en 132
![image](https://github.com/Tedeapolis/development/assets/68514420/60e83f50-8b9d-46c5-a5b0-f568353bd0be)

- [x] De volgende emotes hebben nog /e anwb. Misschien een optie om dit naar wegenwacht te veranderen of eventueel afkorting ww (wegenwacht)
- /e anwb2
- /e anwb3
- /e anwb5
- /e anwb6
- /e anwbvelg

- [x] F3 Menu -> TDA Emotes staat nog ANWB.
![image](https://github.com/Tedeapolis/development/assets/68514420/97b13722-7717-4357-a380-f468fc98ff66)

- [x] Wegenwacht pas heeft nog ANWB logo bij het bekijken van deze pas. Dit is bij uitdienst en indienst pas (geen idee of dit verschil uitmaakt)
![image](https://github.com/Tedeapolis/development/assets/68514420/8729d2b1-8de9-4cea-ba7c-73f51ac8489b)

- [x] F10 menu logo copyright?
**Ik heb geen idee of hier copyright opzit maar het hem toch voor de zekerheid hier neer.** 
![image](https://github.com/Tedeapolis/development/assets/68514420/2ad79d2e-8ce7-459a-a9a2-c247c67edbff)

- [x] Discord meldingen komen nog binnen onder de naam ANWB (+ eventuele copyright logo) in beide Wegenwacht meldkamers. Dit is niet echt een fix wat direct moet gebeuren maar zal fijn zijn als dit ooit gedaan wordt.
![image](https://github.com/Tedeapolis/development/assets/68514420/7992f197-9515-45a9-9fc7-4103ceb94187)

### Wat lost deze feature op?

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AshwinV9595** [comment]
Hey @DeStefanoKiller,

Net even gecheckt, alles is volgens mij ondertussen weg gehaald of verranderd.

Enkel de meldkamer is nog ANWB, maar dit is niet echt een probleem aangezien dit geen gevolg heeft voor de FiveM server.
Kijk het zeker zelf even na of ook voor jou alles aangepast is zoals je in het ticket hebt beschreven.

**Comment by Tom974** [comment]
alles is doorgevoerd
