### ISSUE TITLE
[Bug]: Tactische recherche senoir en brigade recherche senior toegang geven tot wapen opslag.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2444]
### Contact Details

xuify

### Wat gebeurde er?

Niet helemaal een bug maar het was altijd de bedoeling dat alle recherche seniororen toegang hadden tot de wapenopslag, momenteel kan enkel FO senior dit.

### Wat hoorde er te gebeuren?

Dat brigade & tactische recherche toegang hebben tot de wapen opslag.

### Wat veroorzaakt de bug?

NVT

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by PolitieTDA** [comment]
@Tom974 Hoi, wil je dit fixen aub?

**Comment by Tom974** [comment]
niet als je me gaat taggen om te vragen of ik het wil fixen
