### ISSUE TITLE
[Bug]: Niet helemaal een bug maar het was altijd de bedoeling dat alle recherche seniororen toegang hadden tot de wapenopslag, momenteel kan enkel FO senior dit.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2446]
### Contact Details

xuify

### Wat gebeurde er?

Dat brigade & tactische recherche toegang hebben tot de wapen opslag.

### Wat hoorde er te gebeuren?

NVT

### Wat veroorzaakt de bug?

NVT

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Xuifyy** [comment]
Graag development niet taggen, deze issue heeft ook geen haast.

**Comment by Xuifyy** [comment]
Graag development niet taggen, deze issue heeft ook geen haast.

**Comment by PolitieTDA** [comment]
Oke @Xuifyy

**Comment by Zjefvm** [comment]
Opgelost!

**Comment by Xuifyy** [comment]
a

**Comment by DylanPeys** [comment]
test
