### ISSUE TITLE
[FEATURE]: Meer MDealer locaties

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2448]
### Contact Details

iHax0r

### Goedgekeurd door

Burgerraad 01/07/2024

### Beschrijf zo duidelijk mogelijk de feature

Meer locaties van de MDealer in het Noorden maken. Aangezien de locaties nu vooral in het zuiden zijn, dat er ook kansen zijn dat ze in het Noorden komen.

### Wat lost deze feature op?

Niet constant naar het zuiden moeten om spullen in te kopen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Deze staan ook expres in het zuiden

**Comment by Tom974** [comment]
uitleg gegeven in burgerraad waarom dit niet doorgevoerd wordt.
