### ISSUE TITLE
[FEATURE]: Porsche Panamera Sport Turismo Mansory

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2449]
### Contact Details

iHax0r

### Voertuig model

pstmansory

### Omschrijf de bug

![image](https://github.com/user-attachments/assets/379e8b2a-5791-46a9-b10c-6d5f9a5dee38)
![image](https://github.com/user-attachments/assets/29c596c0-3bd2-4871-98a1-818e1990f7e9)
![image](https://github.com/user-attachments/assets/d5cece38-9787-4fb3-bd9a-9dc0c32fd0d1)

Eerste 2 zijn in de devserver, laatste in de main server.
Kofferbak kleur is niet gelijk aan de kleur van de auto.

### Repro

1. Spawn auto in met /car pstmansory.
2. Rijd naar een modshop.
3. Verander kleur naar gewenste kleur.
4. Staar naar de kofferbak.
5. Kom erachter dat de kleur niet overeenkomt.

### Normaal gedrag

Kofferbak hoort dezelfde kleur te hebben.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
cfx is een bitch sometimes
