### ISSUE TITLE
[FEATURE]: De camera's kunnen in- en uitzoomen

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#2450]
### Contact Details

jaim.

### Goedgekeurd door

Korpsleiding

### Beschrijf zo duidelijk mogelijk de feature

(suggestie vanuit het suggestiekanaal binnen de politie)

Een mogelijkheid om in te zoomen binnen de cameraweergave, zonder of met weinig kwaliteitsverlies, voor camera's op locaties zoals HB, tweedehands winkels, Lombank, Basic-Fit, enzovoort.

### Wat lost deze feature op?

"_Momenteel mis je namelijk soms net dat ene lettertje op een kenteken of kan je net het verschil niet zien tussen het soort wapen dat iemand vast zou hebben. Ook de kleine details op lichamen van verdachten is soms net niet goed zichtbaar. Het lijkt me prettig en realistischer als we kunnen in- en uitzoomen op de camera's, zodat we sommige zaken beter kunnen waarnemen._"

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done, zie github commits voor uitleg hoe t werkt
