### ISSUE TITLE
[Bug]: Lab resultaten (serienummers) werken niet meer (Tom weet precies hoe en wat).

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2451]
### Contact Details

xuify

### Wat gebeurde er?

Wegens aanpassingen in de discord werken de labresultaten niet meer. Deze github issue is voor Tom, hij weet precies waar dit over gaat.

### Wat veroorzaakt de bug?

Alles

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Al een tijd geleden opgelost
