### ISSUE TITLE
[FEATURE]: Kleding cirkel wapendealers

### ISSUE THREAD

**Issue by TDA-Dandi** [Tedeapolis/development#2452]
### Contact Details

Dandi.b

### Goedgekeurd door

keesdebeuker

### Beschrijf zo duidelijk mogelijk de feature

De wapendealers zouden graag een kleding cirkel willen in hun hide out. Dit omdat er meerdere wapendealers nu zijn die zonder Ped spelen maar gewoon met een char. Zo kunnen zij zich makkelijk omkleden. 

Coords: X: -254.48 Y: -2209.62 Z: 10.06 H: 266.51

![image](https://github.com/user-attachments/assets/690f4dc8-6a1d-4700-bc47-2052c5ccce8e)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Fixed
