### ISSUE TITLE
[FEATURE]: Zorgen dat je alleen je auto kunt tunen indien je grantkeys hebt of de eigenaar bent.

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#2453]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Titel says it all.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd!
