### ISSUE TITLE
[Bug]: Voertuig 720S zonder kenteken nog te scannen met ANPR / RADAR / ZULU

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2455]
### Contact Details

iHax0r

### Wat gebeurde er?

720S zonder kenteken is momenteel nog te scannen spawncode: /car 720S

### Wat hoorde er te gebeuren?

Kenteken eraf = niet scanbaar
Kenteken erop = scanbaar.

### Wat veroorzaakt de bug?

Dat er rare situaties ontstaan, waarbij de Politie op ANPR camera's afgaat die niet af konden gaan.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
ja heb nu niet zoveel nut meer xD, kut rockstar
