### ISSUE TITLE
[Bug]: Voertuig kofferbakken gangopslag

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2457]
### Contact Details

iHax0r

### Wat gebeurde er?

De kofferbak van een voertuig werkt niet, wanneer je er wat in probeert te leggen staat die altijd op slot. Zelfs als je /locktrunk doet. Dit komt omdat je hem uit de gangopslag haalt.

### Wat hoorde er te gebeuren?

Spullen in de kofferbak kunnen leggen.

### Wat veroorzaakt de bug?

1. Pak een Supervolito Carbon
2. Zet hem in de gangopslag
3. Haal hem eruit
4. Doe hem open
5. Leg spullen in de kofferbak
6. Zie dat het niet werkt
7. Kijk of dit probleem bij meerdere heli's is.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by iHax0rMC** [comment]
Kom er net achter dat dit is als je een voertuig uit de gangopslag haalt

**Comment by Tom974** [comment]
@niekschoemaker

**Comment by Tom974** [comment]
Should be fixed @iHax0rMC, heb het gehotreload dus het is ook direct actief in de server.

**Comment by Tom974** [comment]
net getest met sjef, works.
