### ISSUE TITLE
[Bug]: Niks kunnen kopen in de ANWB

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2458]
### Contact Details

iHax0r

### Wat gebeurde er?

Wanneer je naar de ANWB winkel gaat, zit er niks in de shop (zie screenshot)
![image](https://github.com/user-attachments/assets/7199f71a-c79d-4056-bd62-66d0ec1d0394)

### Wat hoorde er te gebeuren?

Je hoort hier een menu te krijgen met de juiste artikelen die te koop zijn.

### Wat veroorzaakt de bug?

Winkelmenu openen in de ANWB.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed na restart
