### ISSUE TITLE
[FEATURE]: Hogere drugs prijzen

### ISSUE THREAD

**Issue by Fase1020** [Tedeapolis/development#2461]
### Contact Details

Fase

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op dit moment zijn de prijzen van drugs zeer laag in vergelijking met vroeger. Dit komt natuurlijk door de daling van spelers. Daarom zou ik de prijzen graag willen zien stijgen. 

### Wat lost deze feature op?

Het geeft mensen terug een reden om aan drugs te doen en het zou mss mensen terug aantrekken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Thanks voor het melden, heb een aanpassing doorgevoerd.
