### ISSUE TITLE
[Bug]: Overheid meos ziet eiland voertuigen.

### ISSUE THREAD

**Issue by NovaGazer3** [Tedeapolis/development#2463]
### Contact Details

Xuify

### Wat gebeurde er?

Voorheen zag overheids meos de eiland voertuigen nooit, nu wel.

### Wat hoorde er te gebeuren?

Dat je enkel land voertuigen ziet.

### Wat veroorzaakt de bug?

De voertuig lijst openen op meos

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Yes is gefixt
