### ISSUE TITLE
[FEATURE]: Aantal kilo's laten zien bij pakken van voertuig & toevoegen aan alle voertuigen

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2464]
## Contact Details

dyon.

## Goedgekeurd door

Tom

### Het toevoegen van het aantal kilo's wat in het voertuig zit bij het pakken van een voertuig.
Op het moment zie je hoeveel liter benzine er in zit en of de motor schade heeft. Kan hierbij toegevoegd worden hoeveel kilo er in de kofferbak zit en hoeveel kilo dit voertuig maximaal kan dragen.

Het idee is alsvolgt:
**Inhoud: 0/130 KG**

### Alle voertuigen
Ook was de vraag of dit toegevoegd kon worden aan eiland voertuigen, Heli's, Vliegtuigen & Boten.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Coolcooli** [comment]
Gaat er voor nu niet in komen
