### ISSUE TITLE
[Bug]: Scrollwheel in Kleding Menu

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2465]
### Contact Details

dyon.

### Wat gebeurde er?

Sinds vandaag is er support toegevoegd voor het gebruik van de scrollwheel in menu's. Echter werkt dit niet super lekker in de kleding winkel omdat het scrollen ook ingesteld staat op het in en uit-zoomen van je character. 

https://medal.tv/games/gta-v/clips/iwhyYjtQpGNdFdkCd/d1337Q1Pgi5N?invite=cr-MSxhbGQsNDg1Nzc3ODMs

### Wat hoorde er te gebeuren?

Met scrollen hoort alleen je character in en uit te zoomen en hoor je niet door alle soorten kleding te scrollen.

### Wat veroorzaakt de bug?

De laatste commit over [feature(esx_menu_default): Support muis wiel voor scrollen, en blokkeer enkele toetsen tijdens menu](https://github.com/niekschoemaker/fivem_server/commit/87b9a30dbca9d578596f06b2c42740f11efb98d0)

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
is gefixt na de restart
