### ISSUE TITLE
[Bug]: Visite geven kaartjes werken niet.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2466]
### Contact Details

xuify

### Wat gebeurde er?

Visite kaartjes **geven** werkt niet. Er komt ook niks in je F8 te staan, je eigen visite kaartje bekijken werkt wel.

### Wat hoorde er te gebeuren?

Dat je een visite kaartje ontvangt als iemand die geeft.

### Wat veroorzaakt de bug?

F2 > Portemonnee > Visite Kaartje > Geef > [ID]

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

Er staat geen error in F8

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
is gefixt
