### ISSUE TITLE
[FEATURE]: Voertuig kunnen veranderen als die uit de gangopslag komt

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2467]
### Contact Details

iHax0r

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Alle voertuigen die in de gangopslag zijn, kan je niet veranderen van kleur etc. Sommige voertuigen worden gebruikt vanuit heel de groep en "deel" je dus een soort van. Uit de gangopslag halen is ook een soort van grantkeys, dus lijkt me ook logisch als je kleuren kan veranderen indien nodig.

### Wat lost deze feature op?

Voertuig kunnen aanpassen, wanneer deze uit de gangopslag komt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
fixed
