### ISSUE TITLE
[FEATURE]: Blacklist support discord wipen.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2469]
### Contact Details

xuify

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Iedereen van de blacklisted role afhalen (support discord)

### Wat lost deze feature op?

Mensen kunnen weer tickets maken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Dit is een tijdje geleden doorgevoerd.
