### ISSUE TITLE
Attachment van wapens + vuren met wapen werkt soms niet.

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#247]
Als je attachments op wapens zet en je legt je wapen in een kofferbak van een auto. Dan gaan ze er vanaf als je die eruit neemt.
Ook is er een probleem met zware vuurwapens zoals M4a1 en Ak's... Als je schiet. De 1ste 1-5 schoten vuurt die niet af. Dit merk ik vaak als ik wapens koop uit politie opslag. Attachments op zet en dan wil schieten. Moet ik 1-5 keer vuren tot er eindelijk een kogel gelost wordt.

**Comment by Willem-Dekker** [comment]
Er zit een vertraging op het schieten van 5 sec dat kan het zijn
