### ISSUE TITLE
[EUP]: Brandweer EUP toevoegen aan ambulancejob. 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2471]
### Contact Details

elizestolemyname

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Omdat de brandweer nu niet in dienst kan met voertuigen enzovoort zou het fijn zijn dat hun EUP bij de ambulancejob komt. 
Dan kunnen wij de brandweerleden de ambulancejob geven en kunnen zijn wel al in dienst gaan maar dan onder de ambulance. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Brandweer is opgeheven
