### ISSUE TITLE
[Bug]: Brandblussers + zaklampen doen het niet in de inventory. 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2472]
### Contact Details

elizestolemyname

### Wat gebeurde er?

Wanneer je de zaklamp of brandblusser uit de opslag van de ambulance pakt zit hij in je broekzak maar je kan er niets mee. 
Je kan ze ook niet verwijderen en niet gebruiken

### Wat hoorde er te gebeuren?

Zaklamp + brandblusser in je broekzakken hebben als je die uit de ambulance opslag pakt. 

### Wat veroorzaakt de bug?

Geen idee. Maar als we de zaklamp of brandblusser pakken gebeurt er niets. 
Hij is wel zichtbaar in je broekzakken maar je kan hem niet gebruiken en ook niet vastpakken. 
Doordat je ze niet kan vastpakken kan je ze ook niet weg doen 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Kan zijn dat het na de restart gefixt is, laat me even weten of dat ook zo is :^)

**Comment by Coolcooli** [comment]
Ik heb het nu definitief gefixt. Zou na restart goed moeten zijn.
