### ISSUE TITLE
[FEATURE]: Is het mogelijk de GTA brandweer wagen in de stad te zetten? 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2473]
### Contact Details

elizestolemyname

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Omdat de brandweer als neventaak onder de ambulance valt maak ik deze github aan... 
Brandweerleiding Sjaak gaf aan dat hun nu helemaal geen voertuigen hebben. 
Is het mogelijk dat de GTA brandweer wagen wordt toegevoegd zodat de brandweer weer iets kan gaan doen? 

### Wat lost deze feature op?

Brandweer kan weer in dienst 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Brandweer is opgeheven
