### ISSUE TITLE
[FEATURE]: Mount Chilliad TPW

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2474]
### Contact Details

iHax0r

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Aanvraag voor: /tpw mountchilliad

![image](https://github.com/user-attachments/assets/69ac4662-4e57-4dea-9bb3-18f88c069b29)
Coords: X: 498, Y 5587, Z: 794, H: 208

### Wat lost deze feature op?

Oude staff tradities terugbrengen

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
oude staff tradities?

**Comment by iHax0rMC** [comment]
> oude staff tradities?

https://ptb.discord.com/channels/563825802865541122/1278014947980349551/1279568736868761612

**Comment by Coolcooli** [comment]
Is toegevoegd na restart
