### ISSUE TITLE
[Bug]: Op een stoel zit plugin is kapot.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2476]
### Contact Details

xuify

### Wat gebeurde er?

Wanneer je op een stoel gaat zitten (shift + e) dan TP je in de lucht bij rockwood plaza. Wanneer je weer opstaat kom je weer naast de stoel terecht. Deze bug is niet alleen een bug voor je zelf maar ook 3e partijen zien je niet in deze stoel zitten.

Clip: https://youtu.be/mtWS-g6uQ48

### Wat hoorde er te gebeuren?

Dat als je in een stoel zit dat je daadwerkelijk in de stoel geplaatst word.

### Wat veroorzaakt de bug?

In een stoel gaan zitten.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
is al gefixt
