### ISSUE TITLE
[FEATURE]: Nieuwe wegenwacht voertuigen

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2479]
### Contact Details

mrmartin02

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Voor de wegenwacht hebben wij dringend nieuwe voertuigen nodig. Wij kunnen offroad meldingen niet bereiken, personeel is uitgekeken op ons ene wegenwacht busje en standaard GTA schepwagen en cursussen om nieuwe voertuigen te leren hebben geen nut meer. In het wegenwacht discord kanaal Leiding staan de voertuigen aangeleverd door Hafid S. 
https://discord.com/channels/876808615749644338/876836416670273546

### Wat lost deze feature op?

Offroad meldingen kunnen bereiken, cursussen hebben weer nut en personeel heeft meer variatie waardoor het werk weer leuker en interessanter wordt en ze niet ontslag nemen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Lorenzo3001** [comment]
Hey @goudvis02,

Er is een offroader zo goed als klaar, echter mist hier momenteel nog een livery voor. Wellicht dat er iemand binnen jullie team zin en tijd heeft om deze livery aan te leveren. Ik zal de template van de livery bijvoegen, het voertuig is de Caracara 4x4.
![template](https://github.com/user-attachments/assets/c2a15a44-b397-40ff-800f-52c0074e7fe0)

**Comment by goudvis02** [comment]
Ik zal het doorgeven @Lorenzo3001 
En de busjes in wegenwacht #leiding?

**Comment by Lorenzo3001** [comment]
> En de busjes in wegenwacht #leiding?

De grote bus lijkt me overbodig en de kleine hebben jullie toch al?

**Comment by Kian1540** [comment]
> > En de busjes in wegenwacht #leiding?
> 
> De grote bus lijkt me overbodig en de kleine hebben jullie toch al?

Goedenavond @Lorenzo3001,

De bedoeling van de **grote bus** is dat deze te gebruiken is voor personen die de **ongevallen cursus** behalen.

Voor het **kleine busje** is er een **aangepaste livery** (livrei is gelijkaardig) en **gereedschap** interieur + **zwaailichten** toegevoegd.

Hieronder een overzicht van onze huidige cursussen waarvoor leden in het verleden een voertuig konden vrijspelen:

- Inwerking (Stagair) = **Benefactor Imperial**
- Schepwagen (Uitzendkracht) = **MTL Towtruck**
- Ongevallen (Monteur In Opleiding) - **Benefactor Jogger**
- Off-road (Eerste Monteur) = **Vapid Sandstorm** (deze is tevens al door Tom getest, zie foto onderaan)
- Boten (Autotechnicus in opleiding) = Onze vorige boot is weg, wij werken hieraan.
- OPCO (Technisch Specialist) = Vapid Aleutian (Work In Progress = ON HOLD)

PS: Hafid Shemlali vraagt voor de bestanden van de Caracara 4x4 om ermee aan de slag te gaan(om het ook visueel in de editor te kunnen bekijken hoe het staat).

Met Vriendelijke Groet,
Francois Proveaux 
TDA-Wegenwacht Teamleider

![image](https://github.com/user-attachments/assets/8771edd2-f4bd-43fe-b989-e66490f84d47) 
![image (1)](https://github.com/user-attachments/assets/26ad0bfe-0b1d-4bc2-93f8-9d08488e3bac)
![image (2)](https://github.com/user-attachments/assets/0c32dc7a-4619-4145-867d-1df597b999d8)

**Comment by Lorenzo3001** [comment]
Er worden momenteel niet meer voertuigen toegevoegd dan nodig. De Caracara zal er inkomen als offroader en daarnaast vind ik het prima om de Aleutian als SUV erbij te doen, maar daar blijft het voorlopig bij. 

Ik heb de files van de standaard Caracara bijgevoegd, dit zal voldoende moeten zijn om de livery te testen. De custom files van de Wegenwacht versie worden niet gedeeld.
[caracara.zip](https://github.com/user-attachments/files/17002927/caracara.zip)

**Comment by RazorAIM** [comment]
@Lorenzo3001 
Even paar dingen op een rijtje, dit is een noodkreet vanuit de wegenwacht we verliezen elke dag meer en meer leden dit heeft te maken dat er binnen de wegenwacht niks te behalen valt en het niet leuker word aangezien we niks hebben. om die rede vragen wij de voertuigen aan die je kunt vrij spelen na dat je de cursussen hebt behaald.

**Benefactor Imperial Stagair busje** (op de afbeelding is een vervanger voor wat we nu hebben)
**Benefactor Jogger (Rang2)** beide voertuigen zijn uitgerust met gereedschap en zwaailichten zo als we voor heen hadden
**Vapid sandstorm** (bestanden gekregen van Tom en getest door tom die zou zogezegd goed zijn maar nog niet toegevoegd)
de caracara die je nu verzonden hebt zien wij niet passen in ons arsenaal maar heb zelf daarvoor een ander model gevonden misschien kun jij hier iets mee (skin is al gemaakt echter moet de sirene en zwaailichten naar oranje aangepast worden)
de Aleutian skin is ook al klaar weet alleen niet of die werkt op een standaard model(EMS Mod) 
![image](https://github.com/user-attachments/assets/be48fc66-82f1-4f31-9056-619a6ba0cc0b)
![image](https://github.com/user-attachments/assets/c4337962-d1c5-4b1a-981b-fc71206fae18)
![image](https://github.com/user-attachments/assets/deaf7dc6-e867-42d7-adce-9808fd397fba)
![image](https://github.com/user-attachments/assets/f19dbf36-5b2b-4497-abd5-dc4e9a26bbff)

**voertuigen die we hadden: Caddy / Touring / Sleepwagen / Vito / Volvo / cursusauto / dingyboot** 
Graag horen we van je
Hafid S.
Directeur
TDA Wegenwacht

**Comment by Lorenzo3001** [comment]
Dat is erg vervelend, maar zoals eerder benoemd gaan er niet meer zoveel voertuigen worden toegevoegd als voorheen. De Vapid Sandstorm komt er niet in, daarvoor in de plaats komt de Caracara. Graag hoor ik of jullie hier zelf nog een livery voor maken of dat wij dit moeten doen. Als je mij de skin voor de Aleutian door kan sturen zal ik daar ook vast naar gaan kijken.

**Comment by Kian1540** [comment]
> Dat is erg vervelend, maar zoals eerder benoemd gaan er niet meer zoveel voertuigen worden toegevoegd als voorheen. De Vapid Sandstorm komt er niet in, daarvoor in de plaats komt de Caracara. Graag hoor ik of jullie hier zelf nog een livery voor maken of dat wij dit moeten doen. Als je mij de skin voor de Aleutian door kan sturen zal ik daar ook vast naar gaan kijken.

Goedenavond @Lorenzo3001,

Wij van de wegenwacht betreuren dit uiteraard. Is dit tijdelijk wegens de hoge druk of ziet dit er in de nabije toekomst niet aan te komen? Hafid beantwoord zometeen uw 2de vraag.

Of wilt u dat wij meer naar voertuigen toewerken die andere overheidsdiensten gebruiken?

Met Vriendelijke Groet,
Francois Proveaux
TDA-Wegenwacht Teamleider

**Comment by RazorAIM** [comment]
@Lorenzo3001  ik heb de afgelopen weken gewerkt aan skins voor de wegenwachtvoertuigen met het idee dat wij dit konden doen, vind het best jammer dat al deze tijd verloren gaat. D
at terzijde, graag zien wij de huidige busje vervangen door het busje wat is te zien op de fotos zodat er 1 thema aan skins gebruikt kunnen worden 
De Caracara kan ik wel een livery voor maken, Alleen snap ik niet waarom de caracara niet oke is die ik nu al heb gemaakt 
hierbij stuur ik je de skin voor de aleutian die te zien is op de fotos:
![Aleutian](https://github.com/user-attachments/assets/d30b1ca8-f3c3-4a53-bdff-0ff3306c56d8)

**Comment by Lorenzo3001** [comment]
> Wij van de wegenwacht betreuren dit uiteraard. Is dit tijdelijk wegens de hoge druk of ziet dit er in de nabije toekomst niet aan te komen?

Er zal in de toekomst vast wel wat meer mogelijk zijn, maar er wordt over het algemeen wel strenger gekeken naar het toevoegen van extra voertuigen aangezien we er in het verleden te veel hadden.

**Comment by Lorenzo3001** [comment]
> @Lorenzo3001 ik heb de afgelopen weken gewerkt aan skins voor de wegenwachtvoertuigen met het idee dat wij dit konden doen, vind het best jammer dat al deze tijd verloren gaat. 

Dat begrijp ik, maar er is ook niks met mij gecommuniceerd over die voertuigen, anders had ik je het vooraf al kunnen vertellen. 

Ik zal morgen kijken naar de aanpassingen van het busje en de Aleutian. Verder wacht ik de skin voor de Caracara af.

**Comment by RazorAIM** [comment]
@Lorenzo3001 ik ga er nu mee beginnen maar kan dit gegarandeerd worden dat het word toegevoegd anders gooi ik weer mijn tijd weg.
PS: kan er ook zwaailichten op komen en iets van toolboxen achter in?

**Comment by Lorenzo3001** [comment]
> @Lorenzo3001 ik ga er nu mee beginnen maar kan dit gegarandeerd worden dat het word toegevoegd anders gooi ik weer mijn tijd weg. PS: kan er ook zwaailichten op komen en iets van toolboxen achter in?

Zoals in mijn bericht stond is de Caracara die hier is gestuurd de standaard versie, puur om de livery te testen. De livery zelf komt uiteindelijk op een aangepaste versie waar inderdaad lampen en dergelijke opzitten. Deze is op de livery na ook al af en zal er zeker inkomen.

**Comment by RazorAIM** [comment]
[caracara.zip](https://github.com/user-attachments/files/17003989/caracara.zip)
Hierbij de skin laat me weten als er dingen aangepast moeten worden

**Comment by Lorenzo3001** [comment]
> Hierbij de skin laat me weten als er dingen aangepast moeten worden

Ziet er goed uit, bedankt voor het maken!

**Comment by RazorAIM** [comment]
@Lorenzo3001 heb je toevallig ook de bestanden van de MTL Flatbed dan kan ik die skin ook testen is al klaar moet alleen getest worden

**Comment by Lorenzo3001** [comment]
> @Lorenzo3001 heb je toevallig ook de bestanden van de MTL Flatbed dan kan ik die skin ook testen is al klaar moet alleen getest worden

[flatbed.zip](https://github.com/user-attachments/files/17006171/flatbed.zip)
Ik heb ook al een versie met lightbar erop, die zal ik er dan teglijk met de skin inzetten.

**Comment by RazorAIM** [comment]
[flatbed.zip](https://github.com/user-attachments/files/17006575/flatbed.zip)
@Lorenzo3001 hierbij Sleepwagen skin
Werkte de Aleutian Skin als dat niet het geval is stuur maar daar ook de files van dan maak ik die ook even dan is alles een beetje in de zelfde thema

**Comment by Lorenzo3001** [comment]
Alles zit erin na de restart.

![image](https://github.com/user-attachments/assets/8198817b-e394-4770-b06a-9a5f7e59954f)
![image](https://github.com/user-attachments/assets/dd1caf55-43fa-43de-8170-386d29c9c489)
![image](https://github.com/user-attachments/assets/e9d9528a-0404-4cfe-95ca-ef0ccb0bd139)
![image](https://github.com/user-attachments/assets/e8b1af55-05cc-4a03-b84d-023aabb05990)
