### ISSUE TITLE
[Bug]: /onduty dierenkliniek werkt niet op 2de job

### ISSUE THREAD

**Issue by JohanDewus** [Tedeapolis/development#2480]
### Contact Details

yohandessu

### Wat gebeurde er?

Hey! Aangezien 90% van ons management team de dierenkliniek op 2de job heeft kan bijna niemand /onduty gebruiken

### Wat hoorde er te gebeuren?

Dat je /onduty ook op je 2de job kunt doen 

### Wat veroorzaakt de bug?

Dat 90% van het team niet kan checken wie indienst is. En dit is heel belangrijk om misbruik van de perms te voorkomen. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

None

### Relevante log bestanden

-

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
onduty werkt op basis van telefoonnummer, dus /onduty dierenkliniek en het werkt
