### ISSUE TITLE
[Bug]: Wegenwacht schepwagen ramp werkt niet

### ISSUE THREAD

**Issue by goudvis02** [Tedeapolis/development#2481]
### Contact Details

mrmartin02

### Wat gebeurde er?

Sinds gisteren is het niet meer mogelijk om bij de wegenwacht schepwagen de ramp uit te schuiven. De optie: Druk op E om de ramp uit te schuiven. Komt niet als je achter de schepwagen staat.

### Wat hoorde er te gebeuren?

Normaal hoort de optie: Druk op E om de ramp uit te schuiven. te verschijnen als je aan de achterkant van de schepwagen staat. Nu komt er geen melding en is het onmogelijk om de ramp uit te schuiven.

### Wat veroorzaakt de bug?

Onbekend. Sinds gisterochtend is het spontaan onmogelijk geworden om de ramp te gebruiken.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by RazorAIM** [comment]
Nu doet helemaal niks het van de schepwagen de [F6 - takelen optie] is volledig eruit

**Comment by Kian1540** [comment]
De F6 doet het weer. De ramp is wel niet werkende of zeer uitzonderlijk.

**Comment by Kian1540** [comment]
Ik verneem van collega's dat het inschuiven/uitschuiven van de ramp weer werkt!

**Comment by AshwinV9595** [comment]
@goudvis02 @Kian1540

Lees ik het juist dat het probleem ondertussen opgelost is?

**Comment by Tom974** [comment]
@niekschoemaker Het vastzetten van een voertuig dmv E moet alleen nog even gefixt worden, lijkt om VehicleTransport te gaan
