### ISSUE TITLE
[Bug]: Vuilniszak in jail te laat opruimen bugged.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2482]
### Contact Details

xuify

### Wat gebeurde er?

Als je in de jail de vuilniszak taak uitvoert en je word vrij gelaten voordat je klaar was dan sta je buiten vast met de vuilniszak emote die je niet kan cancelen.
![image](https://github.com/user-attachments/assets/fc0eb8ce-4c71-42be-a469-57eb828dcc14)

### Wat hoorde er te gebeuren?

Dat de emote eindigt wanneer je vrij gelaten word.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Heb het mogelijk gefixt, laat maar weten als dat niet het geval is

**Comment by Tom974** [comment]
Ik heb niks meer gehoord dus ik denk dat het werkt
