### ISSUE TITLE
[FEATURE]: Quicksellen niet baseren op agenten in dienst

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2488]
### Contact Details

xuify

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Een quicksell moet worden gebaseerd op spelers in de stad. Er moet een balans in zitten dat als je gaat quicksellen met heel weinig spelers in de stad dat het het niet waard is om het te verkopen. Verder moet de check er van af of er genoeg overheid in dienst is.

### Wat lost deze feature op?

Spelers kunnen eerder op de dag quicksellen en dat zorgt voor meer activiteit in de stad.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
