### ISSUE TITLE
[FEATURE]: Beveiligings Eenheid (BE) toegang tot uitvalsbasis

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2490]
### Contact Details

Hugo//KlotSjak

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Mensen die TBB zijn binnen de politie hebben GEEN Sleutels van de uitvalbasis, graag het verzoek dit wel toe tevoegen zodat de BE ook zijn werkzaamheden kan verrichten.

**Ingame rangen:**

- police 260 | Politie - TBB - Aspirant
- police 270 | Politie - TBB - Operator
- police 280 | Politie - TBB - Groepscommandant
- police 290 | Politie - TBB - Sectiecommandant
- police 300 | Politie - TBB - Commandant

### Wat lost deze feature op?

Dat de BE de uitvalsbasis binnen kan en zijn werkzaamheden kan uitvoeren.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AshwinV9595** [comment]
Deze is toegevoegd en heb deze vandaag even getest in de stad en lijkt ook te werken. Heb het dan vooral over de poort van uitvalsbasis (deze heb ik getest.
