### ISSUE TITLE
[FEATURE]: Mijnen verwijderen op en rondom eiland

### ISSUE THREAD

**Issue by KeesdeB** [Tedeapolis/development#2492]
### Contact Details

KeesdeB

### Goedgekeurd door

Staffoverleg, al lang geleden maar de Github is niet meer terug te vinden of nooit gemaakt.

### Beschrijf zo duidelijk mogelijk de feature

De mijnen rondom Narcopolis verwijderen.
Allemaal.

### Wat lost deze feature op?

Dit zorgt er voor dat met boten aanmeren/aannemen weer veiliger kan gebeuren, dit soort voor meer "actie" op het water en geeft de kustwacht ook weer nieuwe bezigheden. De mijnen zorgen er voor dat het gevaarljik is om met een een boot naar eiland te gaan. Dit is al goedgekeurd en besproken in staffoverleg.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by KeesdeB** [comment]
Staff overleg niet meer te vinden waar het in is besproken, maar dit kan beaamd worden door veel stafleden.

**Comment by Tom974** [comment]
Heb de explosie uitgezet, de bommen zelf zijn er wel nog maar hebben dus geen effect. Handig voor als ik het in de toekomst weer aan moet zetten, vandaar.
