### ISSUE TITLE
[FEATURE]: APV aanpassing

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2493]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Zoals besproken in staffoverleg van 21 juli graag APV aanpassing doorvoeren: 
Voor alle groepen is het mogelijk ambulanciers vanaf 5 ambulanciers te gijzelen. Er moeten dus altijd 4 ambulanciers over blijven. Dit was nu alleen voor offi groepen zo. 

### Wat lost deze feature op?

Er gaan geen discussies meer OOC plaats vinden over of iemand offi is of niet.
Geen discussies van: dit mag niet wat jullie doen, zijn jullie wel een offi groep. 
Hierdoor zal de RP rondom gijzelingen veel soepeler verlopen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by iHax0rMC** [comment]
https://github.com/Tedeapolis/wet-en-regelgeving/pull/540

**Comment by Tom974** [comment]
Hey, hier is de wet-en-regelgeving repo voor, daar kun je ook een issue/pull request aanmaken
