### ISSUE TITLE
[FEATURE]: De website van TDA updaten

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2497]
### Contact Details

xuify

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

**De volgende dingen zijn nog outdated**
- [x]  Oude TDA intro
- [x]  ATWB logo inplaats wegenwacht logo (https://tedeapolis.nl/)
- [x]  Brandweer sollicitaties staan er nog tussen (https://tedeapolis.nl/)
- [x]  De tekst en logo aanpassen van de wegenwacht (https://tedeapolis.nl/solliciteren/ **andere link!**)
- [x]  Politie & kmar logo is outdated (https://tedeapolis.nl/ & https://tedeapolis.nl/solliciteren/)
- [x]  Op de donatie website staat een outdated loods win actie melding (zie onderstaande foto)
![image](https://github.com/user-attachments/assets/a3901c39-aeae-41c8-b5bd-d1176c43a537)
- [x]  Op de donatie pagina staat dat we achtbanen hebben.
![image](https://github.com/user-attachments/assets/03f932ea-c301-4e04-b85e-f8dcfed01488)
- [x]  Mila staat niet tussen de hogeraadleden (https://tedeapolis.nl/hogeraad/)

### Wat lost deze feature op?

Een mooiere website

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
kijk er vd week wel even naar

**Comment by DevvTDA** [comment]
alles is fixed!

**Comment by Xuifyy** [comment]
Goed bezig dame & heer @DevvTDA & @Tom974 !!
