### ISSUE TITLE
[FEATURE]: Rang toevoegen en een rangnaam aanpassen

### ISSUE THREAD

**Issue by Sofie-C88** [Tedeapolis/development#2498]
Kunnen wij een rol aanpassing hier doorgeven?

- Er zou een rol moeten bijkomen met de naam: Matriarch

Deze mag alle rechten krijgen want die komt tussen chairman en underboss zoals bookkeeper.

- En een naamsaanpassing van shotcaller die nu de naam controller zou moeten krijgen maar gewoon met dezelfde rechten als shotcaller

**Comment by Tom974** [comment]
Voor in de toekomst; als je een issue aanmaakt kun je op feature drukken, dan krijg je een format die je kunt volgen.

**Comment by Sofie-C88** [comment]
Oke duidelijk ! Dankjewel

**Comment by Sofie-C88** [comment]
@Tom974 

Sorry dat ik je weer kom lastig vallen.
Maar we hebben nog eens alles bekeken en we willen graag het een beetje anders doen dan voorheen.

Om het even te schetsen ( Dit is ook de laatste aanpassingen van de rangen)

- We willen graag de rang RUNNER volledig weg
- Dan willen we er graag een rang bij: LIEUTENANT en deze mag dezelfde rechten hebben als Soldier
- Dan willen we de rang MATRIARCH erbij onder Chairman en die mag alle rechten hebben als Chairman

Ik hoop je hiermee voldoende info te hebben gegeven?

**Comment by DevvTDA** [comment]
fixed na de restart als er issues zijn dm me even
