### ISSUE TITLE
[Bug]: Gangjob Saints - Heli Cirkel (Sandy)

### ISSUE THREAD

**Issue by Dyssh** [Tedeapolis/development#2500]
### Contact Details

dyssh

### Wat gebeurde er?

Officiële groeperingen horen een extra gangheli cirkel te zien op Sandy airfield, echter met gangjob Saints zie je deze cirkel niet. Zie screenshots hieronder

![heli-sandy3](https://github.com/user-attachments/assets/864b1002-1a82-4b2d-83b1-6648582da2fe)
![heli-sandy2](https://github.com/user-attachments/assets/ff1bc791-6be2-4ad6-91fe-3865d0d7322d)
![heli-sandy](https://github.com/user-attachments/assets/ce7e5141-6306-41aa-8d5a-9f91e3eb657b)

### Wat hoorde er te gebeuren?

Dat je met gangjob Saints wel een cirkel ziet voor opgeslagen heli's van je gang.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Dat klopt, omdat je deze cirkel al op het dak hebt. Je krijgt er helaas geen 2.
