### ISSUE TITLE
[Bug]: Wanneer je taakstraffen krijgt wanneer je offline bent krijg je 8 taken extra.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2503]
### Contact Details

xuify

### Wat gebeurde er?

Je krijgt altijd 8 taken extra wanneer je je taakstraffen ontvangt wanneer je offline was. Dit komt omdat je dan niet op de gevangenis inlogt en je dan 8 extra taken krijgt omdat je probeerde te ontsnappen.

Mijn voorstel is om de 8 taken die je er bij krijgt er überhaupt uit te halen. Tegenwoordig is het taakstraf gebied toch in de gevangenis dus ga je in principe niet kunnen vluchten. Wel zie ik redelijk vaak een bug voorbij komen zoals deze die ik omschrijf of mensen die enorm veel taken hebben. Ik denk als je die 8 taken 

### Wat hoorde er te gebeuren?

Dat je niet 8 taken erbij krijgt.

### Wat veroorzaakt de bug?

Een taakstraf krijgen wanneer je uit de stad bent.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Coolcooli** [comment]
Is toegevoegd.

**Comment by Xuifyy** [comment]
@Coolcooli ik heb nu nogsteeds een aantal reports gezien dat mensen 8 taken erbij krijgen. Ik denk niet dat het momenteel opgelost is.
