### ISSUE TITLE
[FEATURE]: Weghalen van brandweerrangen / items

### ISSUE THREAD

**Issue by MathiasBlack** [Tedeapolis/development#2504]
### Contact Details

mathias_0403

### Goedgekeurd door

elizestolemyname

### Beschrijf zo duidelijk mogelijk de feature

In de ambulance opslag / personeelsbeheer hadden wij er veschillende items / rangen erbij gekregen voor de samenvoeging die de ambulance ging maken met de brandweer. Nu de brandweer uit de stad gehaald is, hebben deze voor ons geen toegevoegde waarde dus zouden uit de stad gehaald mogen worden.

Volgende 8 rangen zullen niet meer gebruikt worden en mogen uit de stad gehaald worden:

Brandweer - Aspirant
Brandweer - Brandwacht
Brandweer - Hoofdbrandwacht
Brandweer - Brandmeester
Brandweer - Hoofdbrandmeester
Brandweer - Commandeur
Brandweer - Adjunct Hoofdcommandeur
Brandweer - Hoofdcommandeur
![Schermafbeelding 2024-10-20 122741](https://github.com/user-attachments/assets/81ba4dc3-5572-4ac4-98da-8acd004b18a5)

Volgende 3 items waren ook voorzien voor de samenvoeging met de brandweer, deze zouden ook uit de ambulance opslag gehaald mogen worden

- Brandblusser
- GPS
- Zaklamp
![Schermafbeelding 2024-10-20 123232](https://github.com/user-attachments/assets/983da86b-71a7-4dc4-8c2a-697d94e63405)

### Wat lost deze feature op?

Geen rangen / items waarvan we geen gebruik gaan maken

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AshwinV9595** [comment]
@MathiasBlack Morgen kijk ik naar dit issue voor jullie.

**Comment by AshwinV9595** [comment]
De items heb ik er al uitgehaald, ben nu bezig met die rangen voor de promoties.

**Comment by AshwinV9595** [comment]
Beide zaken zijn opgelost
