### ISSUE TITLE
[FEATURE]: Telefoon geven aan nieuwe spelers.

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2506]
### Contact Details

iHax0r

### Goedgekeurd door

Burgerraad & Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Controleren of nieuwe spelers daadwerkelijk een telefoon geven, wellicht ook mededelen hoe ze een melding maken naar de Taxi.

### Wat lost deze feature op?

Taxi word dan door nieuwe spelers gevraagd om een lift te geven.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Al gedaan toch?

**Comment by iHax0rMC** [comment]
> Al gedaan toch?

Indien dit gedaan is, mag deze gesloten worden. Krijgen ze ook al medegedeeld hoe ze een melding kunnen maken bij Uberpolis?
