### ISSUE TITLE
[FEATURE]: Nieuwe offroad ambulance. 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2508]
### Contact Details

elizestolemyname

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

https://www.gta5-mods.com/vehicles/brute-ambulance-improved-add-on-replace-liveries

Wij zouden graag deze ambulance willen als vervanging voor de Amarok. Natuurlijk wel met de juiste skin er op :) 

### Wat lost deze feature op?

Na het verliezen van de Amarok hebben wij geen offroad personen transport meer. 
Wel hebben wij de MMT die offroad kan, maar wij zouden graag ook weer een personen transport willen die offroad kan. 
Dit is veel realistischer voor onze RP, en we missen nu gewoon voertuigen voor de specialisaties. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
@Lorenzo3001
