### ISSUE TITLE
[FEATURE]: /repareer aanpassen

### ISSUE THREAD

**Issue by mrtn2001** [Tedeapolis/development#2510]
### Contact Details

mrtn2001

### Goedgekeurd door

mrmartin02

### Beschrijf zo duidelijk mogelijk de feature

Wij zouden het graag zo willen krijgen dat vanaf 5 Wegenwacht in dienst de /repareer niet meer gebruikt kan worden. Het huidige nummer van 9 word niet meer zo vaak aangetikt als vroeger en daardoor gaan mensen massaal naar de modshop om /repareer te doen en wij (de Wegenwacht) nu erg grote verliezen draaien. Omdat er nu wel constant mensen in dienst zijn maar heel vaak niks te doen hebben omdat er geen meldingen zijn.

### Wat lost deze feature op?

Het mogelijk faillissement van de Wegenwacht en het feit dat veel van onze collega's niks te doen hebben.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

Edit: Ik heb zojuist vernomen dat bij minder dan 3 man in dienst een repareer kit een auto helemaal kan maken. Zou dit ook generfed kunnen worden?

**Comment by mrtn2001** [comment]
Is het ook mogelijk om er voor te zorgen dat vanaf er een uur of 23a00 tot 12a13 vanaf 1 persoon in dienst geen /repareer gedaan kan worden? Aangezien er dan echt niks te doen is. Meer meldingen = ook meer rp.

**Comment by AshwinV9595** [comment]
Aanpassing van aantal mensen is doorgevoerd, we gaan nog evalueren of de aantallen nu goed staan of toch aangepast moeten worden.
