### ISSUE TITLE
[EUP]: CLS backpack voor vrouwen (TBB en DSI)

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2512]
### Contact Details

Discord ID: 418373896656388106 (Jemairo) of Hugo//KlotSjak.

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Graag een CLS rugzak toevoegen voor een vrouwen karakter ingame. Dit kan gebruikt worden door de TBB (Team Bewaken en Beveiligen) en de door de DSI (Dienst Speciale Interventies).

De Backpack zorgt voor een extra stukje roleplay.

Rangen die deze CLS backpack moeten:
- Alle DSI rangen en alle TBB rangen.

Alvast bedankt!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart

**Comment by KMarTDA** [comment]
> fixed na de restart

Hartelijk dank!
