### ISSUE TITLE
[Bug]: Check voor zorgpas in ambulance F6 werk niet naar behoren

### ISSUE THREAD

**Issue by ArjanSteenboom** [Tedeapolis/development#2513]
### Contact Details

tbone5192

### Wat gebeurde er?

Wanneer je als ambulancier via je F6 checkt voor een zorgverzekering staat er dat iemand deze heeft, ookal heeft hij/zij geen actieve zorgverzekering. Dit gebeurt, na een beetje testen, volgensmij alleen wanneer iemand wel een zorgverzekering had en deze heeft opgezegd.

### Wat hoorde er te gebeuren?

Er hoort te staan dat de persoon geen zorgverzekering heeft. 

### Wat veroorzaakt de bug?

Dat durf ik niet te zeggen. 

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![zorgvverzkereng](https://github.com/user-attachments/assets/6339135c-120a-41f4-97a9-863f261f3629)
![Zorgverzekering](https://github.com/user-attachments/assets/77050e0d-9cb6-42a7-93a7-25637b5f975b)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Mogelijk gefixt, heb ff geen tijd om te testen

**Comment by ArjanSteenboom** [comment]
Ik heb het even getest, en het is inderdaad gefixt! Bedankt

**Comment by Zjefvm** [comment]
Fixed
