### ISSUE TITLE
[FEATURE]: Mogelijkheid om opslag van uitvalsbasis en politie opslag te splitsen in 2 opslagen.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2514]
### Contact Details

xuify

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Momenteel zijn de opslagen van de politie opslag en die in uitvalsbasis precies het zelfde (1 opslag). Wij hadden dit graag gezien als 2 opslagen.

### Wat lost deze feature op?

Logischere roleplay.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
