### ISSUE TITLE
[FEATURE]: Ongemarkeerde politie/kmar motor

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2515]
### Contact Details

Hugo//KlotSjak

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Vanuit een suggestie zouden we graag een ongemarkeerde motor willen hebben voor de KMar (en eventueel de politie natuurlijk). Atm zijn er weinig unmarked voertuigen waarbij je inprincipe alleen maar ongemarkeerde auto's hebt maar we het ook leuk zouden vinden als er een ongemarkeerde motor zou komen.

De motor is natuurlijk niet voor iedereen beschikbaar _(unmarked is vanaf hoofdofficier namelijk te rijden)_ en wilde dit graag in deze rang categorie _(Majoor, Luitenant-Kolonel of Kolonel)_ plaatsen.

**Enkele voor en nadelen:**
**Voordelen**:
1. Discretie bij Surveillance
- De ongemarkeerde motor valt nauwelijks op in stadsverkeer, waardoor agenten gemakkelijk criminelen kunnen observeren zonder direct op te vallen. Ze kunnen dicht bij verdachte locaties of voertuigen komen zonder meteen politie-aanwezigheid te verraden.

2. Snelle Achtervolging door Smalle Straten
- De motor is perfect voor snelle achtervolgingen door steegjes, drukke stadsdelen, of gebieden waar auto’s moeilijk kunnen manoeuvreren. Dit geeft de politie een voordeel bij het achtervolgen van verdachten in drukke, stedelijke gebieden waar auto’s vast zouden komen te zitten.

3. Verkenning en Informatie Verzamelen
- In situaties waarbij agenten informatie willen verzamelen of gewoon de situatie willen observeren, biedt de motor snelheid en mobiliteit. Ze kunnen zonder aandacht te trekken een locatie verkennen of snel op een melding reageren.

4. Snelle Versterking bij Incidenten
- Als een team back-up nodig heeft, kan de motor snel ter plaatse zijn om ondersteuning te bieden totdat andere eenheden aankomen. Dit verhoogt de reactietijd in noodgevallen.

**Nadelen:**
1. Snelle Opsporing en Infiltratie
- De ongemarkeerde motor kan criminelen dicht benaderen zonder direct te worden opgemerkt, wat hun plannen bemoeilijkt. Ze hebben minder tijd om hun actie te voltooien of te ontsnappen voordat de politie dichterbij komt.

2. Hogere Kans op Onverwachte Controles
- Doordat criminelen niet direct zien dat het om een politievoertuig gaat, kunnen ze zich minder makkelijk voorbereiden of vluchten. Dit verhoogt de kans dat ze verrast worden door een controle of achtervolging.

3. Uitdagender om de Politie Te Herkennen
- Omdat de motor ongemarkeerd is, weten criminelen soms niet meteen dat ze gevolgd worden door een politie-eenheid. Ze kunnen hierdoor minder goed inschatten hoeveel tijd ze hebben om te ontsnappen of zich voor te bereiden, wat hen sneller kan verrassen en beperken in hun acties.

### Wat lost deze feature op?

Lees hierboven.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
flinke chatgpt of niet dan

**Comment by Tom974** [comment]
Ik heb dit even besproken, helaas gaan we dit niet toevoegen. Het komt te dicht bij recherche in de buurt en we vinden dit niet haalbaar.
