### ISSUE TITLE
[Bug]: Reparatie kit bij Wegenwacht HB defect

### ISSUE THREAD

**Issue by Kian1540** [Tedeapolis/development#2516]
### Contact Details

Belgican

### Wat gebeurde er?

Ik kreeg vaker te horen van mensen dat de "reparatie kit" niet werkt. Er is simpelweg geen optie om het te gebruiken.

Wat opvallend is dat "reparatie kit" een andere benaming heeft t.o.v. die bij de bouwmarkt "reparatie gereedschap".
![image](https://github.com/user-attachments/assets/1a58078c-b5e7-4643-8a9d-7108c0e25acd)

### Wat hoorde er te gebeuren?

![image](https://github.com/user-attachments/assets/ccb02387-d66f-4582-8841-e72c78146104)

### Wat veroorzaakt de bug?

Simpelweg gewoon aankopen bij beide winkels en vergelijken, het ene item bij Wegenwacht HB kan gewoon niet gebruikt worden en is een useless item voor 5.000 euro.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Fixed

**Comment by Kian1540** [comment]
> Fixed

Wanneer komt dit in de stad zichtbaar? Momenteel werkt het nog niet.

**Comment by Kian1540** [comment]
In de stad zichtbaar maar geen refund uitgebracht. Kan je hiernaar kijken @Zjefvm?
