### ISSUE TITLE
[FEATURE]: Optie toevoegen voor het kopen van een telefoon in voorwerpen winkel voor de Koninklijke Marechaussee & Politie.

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2517]
### Contact Details

joko53

### Goedgekeurd door

Kader

### Beschrijf zo duidelijk mogelijk de feature

De optie om in de voorwerpen winkel van de Koninklijke Marechaussee & Politie een telefoon toe te voegen. Dit voor hetzelfde bedrag in de telefoon winkel. Dit voor alle rangen en neventaken.

### Wat lost deze feature op?

Wanneer collega's hun communicatie is afgenomen bij bijvoorbeeld een gijzeling kunnen ze gemakkelijk op het HB meteen al hun communicatie spullen pakken en hoeven ze niet nadat ze op het hb zijn geweest ook nog naar de telefoon winkel te gaan om nog een telefoon te halen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Telefoonwinkel werkt volgensmij prima. Er is destijds al een redelijke discussie geweest over de andere spullen in het HB, dus ik ga het laten voor wat het is. Als je dood gaat, behoud je je telefoon ook, je leeft na een gijzeling vaak nog, dus dan kun je ook wel even naar de telefoonwinkel rijden of er eentje pakken uit de opslag.
