### ISSUE TITLE
[FEATURE]: Meer ramenwas locaties in het havengebied

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2518]
### Contact Details

xuify

### Goedgekeurd door

Burgerraad

### Beschrijf zo duidelijk mogelijk de feature

Meer ramenwas locaties in het havengebied om powergamen te voorkomen met de containers

### Wat lost deze feature op?

Powergamen voorkomen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd
