### ISSUE TITLE
[Bug]: Staff EUP loessoe

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2519]
### Contact Details

xuify

### Wat gebeurde er?

Als ik /eup doe als admin in dienst staat het staff eup nergens. Deze bug is al een tijdje echter ben ik vergeten een github issue aan te maken.

### Wat hoorde er te gebeuren?

Dat je het staff eup kan zien met /eup. Dit is voornamelijk fijn als ik dingen wil oplossen als staff in RP met bijvoorbeeld een wegenwacht outfit of dergelijken wat Mila toegevoegd had aan het staffeup.

### Wat veroorzaakt de bug?

/eup typen

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by AshwinV9595** [comment]
Dit wekt ondertussen al weer!
