### ISSUE TITLE
[FEATURE]: Oogkleur veranderen in kapper zaak

### ISSUE THREAD

**Issue by OwenDeBeuker** [Tedeapolis/development#2520]
### Contact Details

Discord: miguelitoooo

### Goedgekeurd door

Burgerraad

### Beschrijf zo duidelijk mogelijk de feature

Je kan momenteel enkel de kleur van je ogen aanpassen door een nieuw karakter aan te passen, vaak is dit een grote moeite voor een klein iets. Je kan in het echt b.v. ook contact lenzen aan doen, lijkt me gewoon handig om dit in de kapper te kunnen doen i.p.v een volledig nieuw karakter te moeten maken.

Dus bij de kapper een extra stukje in het menu genaamd "oog kleur" of iets in die richting, waar je gewoon precies dat kan aanpassen.

### Wat lost deze feature op?

Niks, gewoon handige toevoeging!

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
staat er als goed is na de restart in, ga er geen misbruik van maken meneer

**Comment by OwenDeBeuker** [comment]
Topper dankjewel :), tuurlijk geen misbruik!

**Comment by OwenDeBeuker** [comment]
Is er misschien ook een mogelijkheid om blush eraan toe te voegen? Aangezien dit ook vaak gebruikt word door mensen!
