### ISSUE TITLE
[FEATURE]: /request_coms & /rc toevoegen om alleen communicatie af te nemen van persoon

### ISSUE THREAD

**Issue by PeysPlays** [Tedeapolis/development#2521]
### Contact Details

ferarris

### Goedgekeurd door

Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Tijdje terug besproken in staffoverleg. Met deze command kun je alle telefoons en radio's die iemand op zak heeft afnemen. Eigenlijk hetzelfde als fouilleren, maar heb je nu zicht op alleen de communitcatie. Ook toevoegen aan F6 menu voor de officiele groeperingen. 

Maken dat automatisch bij het accepteren alle coms afgegeven worden, of dat je alleen de communicatie ziet en zelf nog moet afnemen. Wat voor development makkelijker is.

(let op, /rc is momenteel een command maar het doet niks. Even dubbelchecken voordat het niet werkt omdat er twee commands inzitten met dezelfde naam)

### Wat lost deze feature op?

Dit lost op dat als je in iemand zijn zakken kijkt om communicatie te pakken, je niet perongeluk iemand zijn wapen ziet. Dit zorgt voor veel problemen en situaties waar spelers beroofd worden zonder geldige reden. Op deze manier zie je alleen waar je recht op hebt, en dat is communicatie van persoon en deze kunnen afnemen. 

Hierdoor zal het een groot deel van ongeldige rips verholpen kunnen worden. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Dit zit er na de restart als het goed is in!
