### ISSUE TITLE
[FEATURE]: Chatter account voor de ambulance

### ISSUE THREAD

**Issue by ArjanSteenboom** [Tedeapolis/development#2522]
### Contact Details

tbone5192

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij binnen de ambulance ook een twitteraccount kunnen gebruiken waardoor elke speler dit links boven in beeld krijgt. In principe net zoals hoe het bij de politie werk.

### Wat lost deze feature op?

Hiermee kunnen wij meer mensen bereiken voor onze EHBO cursussen, en zullen minder mensen zonder een EHBO pas zitten. Ook kan het helpen als wij bijv een open dag houden. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Als je zelf aan account aanmaakt met de gebruikersnaam "ambulance", is dit na de restart gefixt

**Comment by Zjefvm** [comment]
Doorgevoerd na de restart!
