### ISSUE TITLE
[FEATURE]: Ambulance voertuigen kunnen kopen vanaf een bepaalde rang. 

### ISSUE THREAD

**Issue by ArjanSteenboom** [Tedeapolis/development#2523]
### Contact Details

tbone5192

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij willen dat ambulanciers pas bepaalde voertuig kunnen kopen vanaf een bepaalde rang. Graag zien wij de volgende voertuigen beschikbaar vanaf deze rangen:

Benefactor Sprinter ---------> Ambulance - Stagair (0)
Ambulance Bus -------------> Ambulance - Helpende zorg (100)
Onroad ----------------------> Ambulance - Verpleegkundige in Opleiding (200)
Ambulance Offroad --------> Ambulance - Doktersassistent (400) 
Rebla GTS -------------------> Ambulance - Medisch Specialist (700)
Lijkenwagen ----------------> Ambulance - Teamleider Afdeling Geneeskunde (850) 

### Wat lost deze feature op?

DIt zorgt er voor dat ambulanciers geen voertuigen meer kunnen pakken waar ze nog geen recht op hebben. Er zal dus geen misbruik meer worden gemaakt van het feit dat ze de voertuigen kunnen kopen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Opgelost na de restart!
