### ISSUE TITLE
[FEATURE]: Rang aanpassing Karmellos

### ISSUE THREAD

**Issue by OwenDeBeuker** [Tedeapolis/development#2524]
### Contact Details

miguelitoooo

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

We willen na langere tijd (meer dan een jaar) onze rangen wederom aanpassen binnen Karmellos, dit zodat we meer stappen hebben binnen onze groep en we hiermee meer structuur kunnen creëren.

Dit zouden dan een aantal nieuwe, en een aanpassing van een huidige rang zijn.

Hieronder zijn alle rangen te vinden, met daarbij de permissies. Mochten er nog vragen zijn en permissies missen, laat dit even weten bij voorkeur in de DM van ihax0r, giniii of sjeffelicious

/setjob {id} bratva 0 | Karmellos - Extraño | Permissies: Items kopen, Spullen in de pot leggen Niks er uit halen.
/setjob {id} bratva 100 | Karmellos - Conocido | Permissies: Voertuig opslag bekijken, Items kopen , Spullen in de pot leggen Niks er uit halen.
/setjob {id} bratva 200 | Karmellos - Nieto | Permissies:  Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 300 | Karmellos - Cuñado | Permissies:  Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 350 | Karmellos - Niño | Permissies: Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 400 | Karmellos - Sobrino | Permissies: Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 450 | Karmellos - Primo | Permissies: Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 500 | Karmellos - Hermano | Permissies:  Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 550 | Karmellos - Suegro | Permissies:  Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 600 | Karmellos - Pareja | Permissies:  Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen
/setjob {id} bratva 650 | Karmellos - Marido | Permissies:  Wapen tunen, Voertuig opslag bekijken, Spullen uit de opslag halen, Items kopen, Alle kluisjes kunnen zien
/setjob {id} bratva 700 | Karmellos - Hijo | Permissies: Alle Wapens inkopen, Wapens tunen. Voertuig opslag , Spullen uit de opslag halen, Items kopen, alle kluisjes kunnen zien
/setjob {id} bratva 800 | Karmellos - Tío | Permissies: Alle Wapen inkoop, Bazen heli, Wapen tunen, Voertuig opslag, Spullen uit de opslag halen, Items kopen, alle kluisjes kunnen zien / aanpassen
/setjob {id} bratva 900 | Karmellos - Padre | Permissies: Alles
/setjob {id} bratva 1000 | Karmellos - Abuelo | Permissies: Alles

### Wat lost deze feature op?

Aanpassing van rang + toevoeging nieuwe rangen. Zorgt voor meer mogelijkheden en structuur.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
kon niet jou grading doen dan zou ik echt alles verneuken in de config maar heb het aangepast zit er na de restart in mocht er iets niet klppen stuur me dan even een bericht. 
![image](https://github.com/user-attachments/assets/70a752ef-4ea1-425a-9f61-acb244a6afdf)

**Comment by OwenDeBeuker** [comment]
DANKJEWEL MILA!
