### ISSUE TITLE
[FEATURE]: Rang aanpassingen Moreno

### ISSUE THREAD

**Issue by KlaasMoreno** [Tedeapolis/development#2526]
### Contact Details

KlaasMoreno

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Na aanleiding van het behalen van de officiële status bij deze onze rangen met daarbij alle permissies per rang. 

Mochten er vragen zijn na aanleiding van deze aanpassingen kan contact opgenomen worden via discord met KlaasMoreno

/setjob {id} biker 0    | Moreno - Seguidor     | Permissies: | /RS,Voertuig opslag bekijken, Spullen i opslag leggen, maar niks eruit halen, items inkopen.
/setjob {id} biker 100  | Moreno - Soldado      | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Geld storten bazen menu, niet eruit halen,
/setjob {id} biker 200  | Moreno - Coraza       | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Geld storten bazen menu, niet eruit halen, 
/setjob {id} biker 300  | Moreno - Sargento     | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu niet eruit halen,
/setjob {id} biker 400  | Moreno - Cerebro      | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu niet eruit halen, 
/setjob {id} biker 500  | Moreno - Asesino      | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu niet eruit halen,
/setjob {id} biker 600  | Moreno - Enlace       | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu niet eruit halen,
/setjob {id} biker 700 | Moreno - Consejero | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu, en mogelijkheid tot eruit halen, Bazenheli, Toegang tot alle kluisjes / aanpassen,
/setjob {id} biker 800  | Moreno - Comandante   | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu, en mogelijkheid tot eruit halen, Bazenheli, Toegang tot alle kluisjes / aanpassen,
/setjob {id} biker 900  | Moreno - El Coronel   | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu, en mogelijkheid tot eruit halen, Bazenheli, Toegang tot alle kluisjes / aanpassen, Promotie / Kicken
/setjob {id} biker 1000 | Moreno - El Jefe      | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu, en mogelijkheid tot eruit halen, Bazenheli, Toegang tot alle kluisjes / aanpassen, Promotie / Kicken ,Wapeninkoop.

### Wat lost deze feature op?

Aanpassing van de huidige rangen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by KlaasMoreno** [comment]
Kleine aanpassing aan de volgende rol aangezien dat niet helemaal goed gegaan is. 

Ik heb het hierboven ook alvast aangepast voor de zekerheid.

Mijn excuses! 

/setjob {id} biker 700 | Moreno - Consejero | Permissies: | F6, Voertuig opslag, Spullen uit opslag halen, items inkopen, Wapen's tune, Geld storten bazen menu, en mogelijkheid tot eruit halen, Bazenheli, Toegang tot alle kluisjes / aanpassen,

**Comment by DevvTDA** [comment]
aangepast na de restart mocht er nog wat fout zij stuur even dm
![image](https://github.com/user-attachments/assets/21b1ecd9-7646-4247-a233-b9ce92e8ec6e)
