### ISSUE TITLE
[FEATURE]: Towtruck

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2527]
### Contact Details

.jarno.

### Goedgekeurd door

Staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Kijken of het mogelijk is om towtrucks te kunnen kopen en gebruiken om voertuigen te slepen. 
![image](https://github.com/user-attachments/assets/55258c90-7bf9-4d84-aa00-3b4e682d3c15)

### Wat lost deze feature op?

Leuke toevoeging voor sleepbedrijven en eventueel de Wegenwacht

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Coolcooli** [comment]
Komt eraan!
