### ISSUE TITLE
[FEATURE]: Sneller drugs kunnen plukken.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2528]
### Contact Details

xuify

### Goedgekeurd door

Staffoverleg & burgerraad

### Beschrijf zo duidelijk mogelijk de feature

Tijdens het burgerraad en het staffoverleg is besproken dat de plukaantallen met 1 omhoog gaan. Dit betekent dat de minimale en maximale plukhoeveelheid per keer plukken met 1 omhoog gaat.

Dus als je minimaal 2 kan plukken en maximaal 3 kan plukken dan gaat dat naar -> min = 3 & max = 4.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
