### ISSUE TITLE
[FEATURE]: Boten opslag gangs in het noorden + eiland gang opslag.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2529]
### Contact Details

xuify

### Goedgekeurd door

Het burgerraad & het staffoverleg

### Boten garage in het noorden voor gangs.
Een nieuwe boten opslag voor in het noorden voor gangs. Deze boten opslag staat niet gelinkt aan de huidige boten garage en gaat dus echt een aparte garage zijn.
Op x: -1604 y5256 z2.08 h270 kun je de boot vanaf de stijger pakken.
![image](https://github.com/user-attachments/assets/96c1344f-d92c-420d-b982-7d566346b0e6)

Op x:-1597.46 y:5255.99 z:1.24 h270.44 kun je de boot in de garage stoppen, **deze moet op de zelfde hoogte als de huidige wegstop cirkel!**.
![image](https://github.com/user-attachments/assets/8b5826fd-2bf8-4c7a-903d-5a454ba4dd10)

### Voertuigen garage eiland
Er komt een eiland voertuigen garage (auto's & motoren) waar gangleden hun voertuigen in op kunnen slaan om deze te delen. Er moet hier een check voor komen dat het **niet** toegestaan is om je auto weg te zetten als er iets in de kofferbak zit.
Op x:5152.46 y:-5144.74 z:2.30 h:256.77 kan je een voertuig uit de garage pakken.
Op x:5154.90 y:-5126.63 z:2.29 h:144.41 kun je je voertuig opslaan in de gang opslag (met een controle of de kofferbak leeg is).

### Wat lost deze feature op?

Dat gangs meer voertuigen kunnen delen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Zit er na de restart in!
