### ISSUE TITLE
Kan dit worden aangepast bij de ANWB?

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#253]
- [ ] Dat je vanaf rank 8 kan zien op de map waar iedereen van de ANWB is die in-dienst zijn. (als dit mogelijk is)

- [ ] Dat Teamleiders ook mensen kunnen gaan aannemen in-game. 

- [ ] Een cooldown per melding naar de ANWB van 5 minuten. 

- [x] Offroad wielen op de Offroad auto zodat die minder snel omvalt als je door de bocht heen rijd.

**Comment by Willem-Dekker** [comment]
zijn deze aanpassingen nog steeds van toepassing?

**Comment by DeStefanoKiller** [comment]
> zijn deze aanpassingen nog steeds van toepassing?

Ja deze toepassing zijn nog wel nodig.

**Comment by Willem-Dekker** [comment]
1 en 2 zijn niet mogelijk
3 ga ik naar kijken maar er zit al een spam filter op

**Comment by DeStefanoKiller** [comment]
Is niet meer nodig
