### ISSUE TITLE
[FEATURE]: Quicksells aanpassing

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2530]
### Contact Details

xuify

### Goedgekeurd door

Het burgerraad & het staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Maximaal 1 quicksell actief per categorie. Dat betekent dus maximaal 1:
- Wiet
- Coke
- Meth
- Multisell
actief tegelijkertijd.

### Wat lost deze feature op?

Meer activiteit rondom de drugs locaties inplaats van verspreid.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done
