### ISSUE TITLE
[FEATURE]: Geen wapen kunnen trekken voor 90 seconden nadat je equipment gefouilleerd is.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2531]
### Contact Details

xuify

### Goedgekeurd door

Het staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Tegenwoordig kun je met /comsfouilleren & /rcs iemand zijn communicatie afnemen zonder hem te fouilleren. Hierbij moet toegevoegd worden dat de persoon waarvan de communicatie afgenomen is voor 90 seconden geen (vuur)wapens kan trekken om te voorkomen dat hij er misbruik van maakt. Er moet dus een melding komen dat zijn wapens voor 90 seconden niet werken/ geblokkeerd zijn of dergelijken en de feature zelf moet toegevoegd worden (eventueel met inspiratie van het zelfde systeem als dat je geen wapen kan trekken nadat je door bent gegaan).

### Wat lost deze feature op?

Veel problemen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Done
