### ISSUE TITLE
[EUP]: Vrouwen hondengeleider steekvest 

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2532]
### Contact Details

joko53

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Binnen de KMar is er de training K9 en is hier voor de mannen op het moment ook een steekvest waar op staat "Hondengeleider". Voor vrouwen bestaat dit op het moment niet, dus hierbij de vraag om dit te laten toevoegen. 

Het vest bij de mannen bestaat op het moment uit het standaard steekvest, maar achterop een extra woord met "Hondengeleider". Hierdoor hoeft alleen hetzelfde gebeurd te worden bij het huidige steekvest van de vrouwen, met dus een tekst "Hondengeleider" achterop. (Zie hieronder de foto's van de mannen Hondengeleider vest en hoe het bij de vrouwen er ongveer uit zou zien.)

Het vest zorgt voor een extra stukje roleplay, zodat er gezien kan worden dat de persoon in kwestie de geleider is van de K9.

Rangen die dit vest moet krijgen:
Alle vrouwen vanaf Wachtmeester der 1e klasse of hoger.

![imageh](https://github.com/user-attachments/assets/99d8fff8-56be-480f-a6c0-b8ddbecd5bd5)
![imageh2](https://github.com/user-attachments/assets/0ccb0d46-f7fb-4cd2-8465-3b18c0fa9873)

![imageh3](https://github.com/user-attachments/assets/b391ff88-2458-447d-bdc3-bac467e66189)
![imageh4](https://github.com/user-attachments/assets/da20a83a-5738-4dad-92ef-686b6078256d)

Voorbeeld:
![imageh5](https://github.com/user-attachments/assets/b5f1149e-4697-4ed6-8287-11d84e0e7b68)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
fixed na de restart

**Comment by KMarTDA** [comment]
Top heel erg bedankt!
