### ISSUE TITLE
[FEATURE]: Paleto bank toevoegen aan politie/KMar camera's

### ISSUE THREAD

**Issue by Rick-TDA** [Tedeapolis/development#2534]
### Contact Details

rick.4524

### Goedgekeurd door

Korpsleiding

### Beschrijf zo duidelijk mogelijk de feature

In het hoofdbureau van de politie kunnen wij camera's bekijken. In het verleden was Paleto bank ook zichtbaar in dit menu, alleen viel het een collega onlangs op dat Paleto bank er niet meer tussen staat. De camera's van Paleto bank kunnen wij dus niet meer bekijken. 
![image](https://github.com/user-attachments/assets/a80b5b36-4a96-499e-824c-4b41d48a95d6)

### Wat lost deze feature op?

Extra roleplay en andere mogelijkheden

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd
