### ISSUE TITLE
[EUP]: Vrouwen onderofficier baret

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2537]
### Contact Details

joko53

### Goedgekeurd door

N.V.T.

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Binnen de KMar hebben we de Baret. Echter is dit bij de vrouwen onderofficier gebugged waarbij het een pet is. (Zie bijlage)

Binnen de KMar is het dragen van de Baret verplicht en is het handig om de juiste baret op te kunnen doen.
Als hier naar gekeken zou kunnen worden zou dat top zijn.

Rangen die dit vest moet krijgen:
Alle vrouwen vanaf Wachtmeester of hoger en neventaken.

![baret](https://github.com/user-attachments/assets/1bbb01aa-e23b-47b7-af3b-fc4182873f2c)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd

**Comment by DevvTDA** [comment]
fixed na restart
