### ISSUE TITLE
[FEATURE]: Route 68 bank camera

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2538]
### Contact Details

joko53

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op het politie HB kunnen wij de camera beelden bekijken van de banken. Hier staan alle banken in van de stad. Laatst is die van Paleto bank nog toegevoegd. Echter mist er nog 1 Route 68 bank. 

De camera kan toegevoegd worden aan het lijstje van banken in de daar voor bedoelde cirkel  op de 4e verdieping van het HB. 

### Wat lost deze feature op?

Wanneer deze toegevoegd is kunnen we net als alle andere banken met de camera's naar binnen kijken om te kijken naar wat er gebeurd en voor de veiligheid van de collega's. En bovendien is dan het lijstje compleet.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd!
