### ISSUE TITLE
[Bug]: Gevangenis taak zit vast achter een gesloten deur.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2539]
### Contact Details

xuify

### Wat gebeurde er?

Als je taken hebt in de gevangenis dan heb je een taak die vast zit achter een gesloten deur waar de gevangen niet bij kunnen. Bij deze de vraag of er gekeken kan worden naar de deur of hij open kan of dat die taak locatie er uit gehaald word.

https://youtu.be/rxQQYV5Ok2A

### Wat hoorde er te gebeuren?

Dat je de taak kan uitvoeren

### Wat veroorzaakt de bug?

Gepakt worden door de politie

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Als het goed is opgelost na de restart!
