### ISSUE TITLE
[FEATURE]: Aanpassing opmaak reports

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2540]
### Contact Details

xuify

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Tegenwoordig hebben mensen steeds raardere namen met meerdere woorden. Dit is erg trippy als je reports aan het behandelen bent. Is er een mogelijkheid dat hier wat verduidelijking komt in de layout? Mogelijk dat de naam dikgedrukt (bold) is of dat de ":" een ander kleurtje heeft zodat het duidelijk opvalt.

Voorbeeld van het probleem:
![image](https://github.com/user-attachments/assets/ff2df8a7-7ff1-404c-939a-2a2ddc6f55ef)

### Wat lost deze feature op?

Wat verduidelijking in de reports voor de late avond.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Zit erin voor volgende restart
