### ISSUE TITLE
[FEATURE]: Wapens hernoemen in de kluis zelf.

### ISSUE THREAD

**Issue by sjefoost** [Tedeapolis/development#2541]
### Contact Details

sjeffelicious

### Goedgekeurd door

Besproken in een burgerraad paar weken geleden.

### Beschrijf zo duidelijk mogelijk de feature

Je kunt nu in een gangopslag alleen de wapens hernoemen die in de normale wapenopslag liggen.
Het zou super fijn zijn als deze optie ook werkt aangegeven bij elk kluisje.

Op de eerste foto zie je de optie in het algemene gangmenu
![image](https://github.com/user-attachments/assets/f8db7d67-6957-48c0-b9d6-730633d9c7b2)

Het zou fijn zijn als die optie op de 2de foto erbij komt van aparte kluisjes
![image](https://github.com/user-attachments/assets/40d366fc-357c-4fd8-8ed4-baf60dae0345)

### Wat lost deze feature op?

Scheelt een hoop werk als dit zou kunnen.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
done, veel plezier ermee
