### ISSUE TITLE
[FEATURE]: Kniptang voor TBB rangen

### ISSUE THREAD

**Issue by jaim1114** [Tedeapolis/development#2543]
### Contact Details

jaim. (Vente)

### Goedgekeurd door

Korpsleiding

### Beschrijf zo duidelijk mogelijk de feature

De volgende rangen toegang geven tot de kniptang in de item shop:

- police 260
- police 270
- police 280
- police 290
- police 300

### Wat lost deze feature op?

Dat inspecteur+ de kniptang kan gebruiken

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Ik heb de namen van de jobs nodig, niet de nummertjes ;p

**Comment by jaim1114** [comment]
@Tom974 Excuus, ik dacht dat jullie het met de nummertjes deden

- Politie - TBB - Aspirant
- Politie - TBB - Operator
- Politie - TBB - Groepscommandant
- Politie - TBB - Sectiecommandant
- Politie - TBB - Commandant

**Comment by Zjefvm** [comment]
Doorgevoerd!
