### ISSUE TITLE
[FEATURE]: Uitdienst stadsporto 110 voor de TBB

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2544]
### Contact Details

Hugo//KlotSjak

### Goedgekeurd door

KMar-Leiding

### Beschrijf zo duidelijk mogelijk de feature

Momenteel kun je ons op 2 manieren oproepen.
1. Via de stads porto;
2. Via de meldkamer die de TBB hebben. 

Echter merken ze dat de meldkamer eigenlijk nooit wordt gebruikt. Als ze bijvoorbeeld in regulier zit en er is TBB nodig, antwoorden ze meestal even met: "Maak even een melding, dan kom ik eraan." Of iets dergelijks. Echter merken ze vaak dat dit dan meestal niet gedaan wordt en dat ze dan maar bijvoorbeeld DSI oproepen. Als de TBB uitdienst in de stadsporto kan krijgen, ze dit soort dingen vaker mee en kan er sneller worden gehandeld en worden opgeschaald wanneer dit gewenst is.
Dit zorgt er ook voor dat de drempel wordt verlaagd bij de andere eenheden om de TBB te laten opschalen in plaats van bijvoorbeeld een koppeltje DSI dat aanwezig is.

_Graag zouden we vanuit het Kader zien dat dit wordt toegevoegd voor deze toppers._

**De ingame rangen waar dit voor moet worden toegevoegd zijn:**
/setjob {id} kmar 70 | Marechaussee - TBB - Aspirant
/setjob {id} kmar 71 | Marechaussee - TBB - Operator
/setjob {id} kmar 72 | Marechaussee - TBB - Groepscommandant
/setjob {id} kmar 73 | Marechaussee - TBB - Sectiecommandant
/setjob {id} kmar 74 | Marechaussee - TBB - Commandant

    police 260
    police 270
    police 280
    police 290
    police 300

### Wat lost deze feature op?

De TBB kan hierdoor sneller uitdienst gecontacteerd worden ingame om op teschalen wanneer dat nodig is.

### Richtlijnen

- [x] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Coolcooli** [comment]
fixed na restart

**Comment by KMarTDA** [comment]
> fixed na restart

Je bent een topper, bedankt!

**Comment by KMarTDA** [comment]
> fixed na restart

Hoi, er zijn signalen dat het nog niet werkte. Kan dat kloppen?

**Comment by Tom974** [comment]
> > fixed na restart
> 
> Hoi, er zijn signalen dat het nog niet werkte. Kan dat kloppen?

Klopt, dit is met opzet teruggedraaid. Voor meer info kun je het beste even overleggen met KL. @KMarTDA
