### ISSUE TITLE
[FEATURE]: Auto's vastzetten op trailer werkt niet

### ISSUE THREAD

**Issue by JasmineVibes** [Tedeapolis/development#2545]
### Contact Details

jasminevibes

### Voertuig model

Flatbed trailer

### Omschrijf de bug

Als je je voertuig vast wil zetten op de trailer met 'E' werkt het niet. 

Alles is al geprobeerd. Voertuig uit zetten en dan vastmaken, voertuig achteruit erop rijden, /trv, trailer in en uit de garage gehaald, voertuig in en uit de garage gehaald.

### Normaal gedrag

Normaal gesproken hoor je op 'E' te drukken en dan zit hij vast.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Heb je iets van beelden of dergelijke? Want bij mij werkt het gewoon nog.

**Comment by JasmineVibes** [comment]
Dit keer had ik geen vrachtwagen gekoppeld, maar met de vrachtwagen gekoppeld doet hij hetzelfde. Niks werkt.
https://www.youtube.com/watch?v=6NI4aI2sj1k

**Comment by niekschoemaker** [comment]
> Dit keer had ik geen vrachtwagen gekoppeld, maar met de vrachtwagen gekoppeld doet hij hetzelfde. Niks werkt. https://www.youtube.com/watch?v=6NI4aI2sj1k

Is het mogelijk dat je de log bestanden erbij stuurt? (Of alternatief even F8 openen nadat je op E drukt in video)

Lijkt er namelijk op dat het mis gaat bij het attachen zelf, en als het een error is zou het wel makkelijk oplosbaar moeten zijn.

**Comment by niekschoemaker** [comment]
Oh moment ik denk dat ik het al heb, blijkbaar staan er nog wat changes open op dev server, waardoor het daar dus wel compleet werkt, oopsie.

Zou gefixed moeten zijn na volgende restart.

**Comment by JasmineVibes** [comment]
Het werkt weer helemaal, dankjewel.
