### ISSUE TITLE
[FEATURE]: Wide Receivers aan telefoon winkel toevoegen

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2547]
### Contact Details

.jarno.

### Goedgekeurd door

Staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Wide Receivers toevoegen aan de telefoon winkels voor 2500 euro.

### Wat lost deze feature op?

Dat er meer gebruik gemaakt van wordt.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Zit er na de restart in!
