### ISSUE TITLE
[FEATURE]:  Flitspaal weghalen

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2548]
### Contact Details

.jarno.

### Goedgekeurd door

Staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Flitspaal bij oud casino pier weghalen

### Wat lost deze feature op?

Dat de paal weg is

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd!
