### ISSUE TITLE
[FEATURE]: Repairkit eiland

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2549]
### Contact Details

.jarno.

### Goedgekeurd door

Staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Repairkit toevoegen op het eiland voor 10K. Eventueel een nieuwe plek of in de cirkels waar je eten/drinken kan kopen.

### Wat lost deze feature op?

Dat mensen hun auto's ook kunnen maken als ze geen repairkit bijzich hebben.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Zit er na de restart in!
