### ISSUE TITLE
aanpassingen ambulance

### ISSUE THREAD

**Issue by krizz696** [Tedeapolis/development#255]
**aanpassing ambulance**
graag hadden wij bij het ambuteam volgende aanpassingen doorgevoerd gekregen

- [ ] toevoegen van volvo FLL MICU [link](https://gta5mod.net/gta-5-mods/vehicles/trucks/volvo-fll-micu-dutch-ambulance-replaceelstemplateenterable-v1-5-added-els-file-and-changed-headlights/)
- [x] automatisch op fluister als je het ziekenhuis binnenkomt
- [x] audio nakijken in de garage en audiozones nakijken in het algemeen
- [x] plastische chirurgie ring terug toevoegen 
- [ ] pinautomaat in de lobby
- [x] safezone in het ziekenhuis 

**naam van de rangen aanpassen en de bijpassende voertuigen toewijzen**

- [x]  **Ambulance-In Opleiding** rang 0  **550euro**
⦁	Mercedes Benz Otaris (_model= ambulance)_ 200km/h
- [x] **ambulance-chauffeur** rang 20 **650euro**
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h

- [x] **ambulance-Verpleegkundige** rang 40 **750euro**
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h
⦁	Volkswagen Amarok (_model=ambuam_) 200km/h

- [x] **Ambulance-Specialist** rang 60 **850euro**
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h
⦁	Volkswagen Amarok (_model=ambuam_) 200km/h
⦁	Mercedes Benz Bclasse Rapid Responder (_model=mercedesb_) 220km/h

- [x] **Ambulance-Geneeskundige** rang 70 **950euro**
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h
⦁	Volkswagen Amarok (_model=ambuam_) 200km/h
⦁	Mercedes Benz Bclasse Rapid Responder (_model=mercedesb_) 220km/h
⦁	Volvo XC90 MMT (_model=ambu90_) 280km/h

- [x] **Ambulance-Hoofd assistent Geneeskundige** rang 80 **1050euro**
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h
⦁	Volkswagen Amarok (_model=ambuam_) 200km/h
⦁	Mercedes Benz Bclasse Rapid Responder (_model=mercedesb_) 220km/h
⦁	Volvo XC90 MMT (_model=ambu90_) 280km/h
⦁	LifeLiner Helikopter (_model=frogger2_) 350km/h

- [x] **Ambulance-Hoofd geneeskundige** rang 90 **1150euro**
⦁	_**toegang tot mensen in dienst nemen en promoveren , niet tot de kluis of ontslagen van mensen**_
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h
⦁	Volkswagen Amarok (_model=ambuam_) 200km/h
⦁	Mercedes Benz Bclasse Rapid Responder (_model=mercedesb_) 220km/h
⦁	Volvo XC90 MMT (_model=ambu90_) 280km/h
⦁	LifeLiner Helikopter (_model=frogger2_) 350km/h

- [x]	**Ambulance-Directie** rang 100 **1250euro**
⦁	_**toegang tot het hele baas menu**_
⦁	Mercedes Benz Otaris (_model= ambulance_) 200km/h
⦁	Mercedes E-Klasse (_model=eclass_) 200km/h
⦁	Volvo FLL MICU 110km/h
⦁	Volkswagen Amarok (_model=ambuam_) 200km/h
⦁	Mercedes Benz Bclasse Rapid Responder (_model=mercedesb_) 220km/h
⦁	Volvo XC90 MMT (_model=ambu90_) 280km/h
⦁	LifeLiner Helikopter (_model=frogger2_) 350km/h

**Comment by Willem-Dekker** [comment]
| toegang tot mensen in dienst nemen en promoveren , niet tot de kluis of ontslagen van mensen

Ik weet niet of dit gaat lukken aangezien het menu volgens mij alles of niks is

**Comment by Willem-Dekker** [comment]
er is afgevinkt wat gedaan is

**Comment by krizz696** [comment]
kunnen de medicijnen ook uit de f6 menus gehaald worden , alsook heal kleine wonden en al de facturen van betreffende behandeling en medicijnen

**Comment by Willem-Dekker** [comment]
medicijnen zijn uit de menus
