### ISSUE TITLE
[Bug]: Chat (twitter) werkt niet.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2552]
### Contact Details

xuify

### Wat gebeurde er?

Sinds een aantal dagen werkt chat (twitter) niet. Zo ver ik zag stond er ook niks in mijn f8 wanneer ik het opende/ een bericht plaatste.

### Wat hoorde er te gebeuren?

Dat je berichten kan plaatsen & binnen ziet komen.

### Wat veroorzaakt de bug?

Spreekt voor zich.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Coolcooli** [comment]
Fixed na restart
