### ISSUE TITLE
[Bug]: Visite kaartjes kapot

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2553]
### Contact Details

dyon.

### Wat gebeurde er?

Als je je visite kaartje laat zien is niks meer leesbaar kwa naam/telefoonnummer.
![image](https://github.com/user-attachments/assets/170adbb7-9c70-4080-a233-2d18fd12edfa)

### Wat hoorde er te gebeuren?

Dat je je naam/telefoonnummer kan zien.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
![image](https://github.com/user-attachments/assets/9dd81391-5e35-4844-a5cf-5ee363a50885)
![huh-cat-huh-m4rtin](https://github.com/user-attachments/assets/a1fc883c-8af0-461d-8e05-6ff39134239e)

**Comment by Tom974** [comment]
![image](https://github.com/user-attachments/assets/18ea48a1-cd5b-4abe-b9a8-7c6522bdfae5)
fixed 🫡

**Comment by Dyon033** [comment]
> ![image](https://github.com/user-attachments/assets/9dd81391-5e35-4844-a5cf-5ee363a50885)
> 
> ![huh-cat-huh-m4rtin](https://github.com/user-attachments/assets/a1fc883c-8af0-461d-8e05-6ff39134239e)
> 
> 

Zo'n visite kaartje wil ik ook! 😂

**Comment by Dyon033** [comment]
> ![image](https://private-user-images.githubusercontent.com/55812394/397518996-18ea48a1-cd5b-4abe-b9a8-7c6522bdfae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1OTEzNzAsIm5iZiI6MTczNTU5MTA3MCwicGF0aCI6Ii81NTgxMjM5NC8zOTc1MTg5OTYtMThlYTQ4YTEtY2Q1Yi00YWJlLWI5YTgtN2M2NTIyYmRmYWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDIwMzc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDViNWZiMGZmZjg4MmE5MGRlZDY0MjVhYTM1YzRiMWYxNTJkNWI3MzEyNTUyMzFmODliODhmYjIxYWRmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kEAeBbC0Hy8qC6hmn7aCWvOFitM2fzRGvUvBV8-JVLw) fixed 🫡

![image](https://github.com/user-attachments/assets/c0570021-1f95-4353-89c0-5f3d45754f17)
Je liegt
