### ISSUE TITLE
[EUP]: Unmarked vrouwen outfit

### ISSUE THREAD

**Issue by KMarTDA** [Tedeapolis/development#2554]
### Contact Details

Hugo//KlotSjak

### Goedgekeurd door

Kader

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

Momenteel hebben we een heren Unmarked outfit beschikbaar in ons EUP systeem. Echter hebbben de vrouwen dit niet. Graag zouden we een unmarked vrouwen outfit willen zodat zij deze ook kunnen gebruiken.

Herenoutfit:
![Schermafbeelding 2024-12-06 215947](https://github.com/user-attachments/assets/bf07d589-45f5-462e-a199-e21df7590a79)
![Schermafbeelding 2024-12-06 215956](https://github.com/user-attachments/assets/081e8bcb-f2e1-4905-9800-9c43354802ad)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by DevvTDA** [comment]
@KMarTDA Vrouwen hebben nu niets of? is het ook enkel shirt verandering ? tis me niet duidelijk.

**Comment by KMarTDA** [comment]
> @KMarTDA Vrouwen hebben nu niets of? is het ook enkel shirt verandering ? tis me niet duidelijk.

Nee vrouwen hebben op het moment helemaal niks naast hun normale dienstkleding.

**Comment by DevvTDA** [comment]
@KMarTDA dus wat moeten ze nu krijgen? Het vest of de kleding eronder??

**Comment by DevvTDA** [comment]
![image](https://github.com/user-attachments/assets/b1340ed7-da9a-4976-98ec-1f641399dd44)


fixed nma de restart

**Comment by KMarTDA** [comment]
> ![image](https://private-user-images.githubusercontent.com/79802852/396537928-b1340ed7-da9a-4976-98ec-1f641399dd44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTQzNjAsIm5iZiI6MTczNDU1NDA2MCwicGF0aCI6Ii83OTgwMjg1Mi8zOTY1Mzc5MjgtYjEzNDBlZDctZGE5YS00OTc2LTk4ZWMtMWY2NDEzOTlkZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDIwMzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWZmZWUzMTkzOTU0OGNiYWJlMmNjZmE1NzdkZmRiZDVkNTg2NTgzOGMyYTNiNzI5N2ZhOTk4NjY0N2ZmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rHB7E1jJQijjYi65Np6i3c6h8NBODbWrFXZKMl6f35Y)
> 
> fixed nma de restart

Top hartelijk bedankt!
