### ISSUE TITLE
[FEATURE]: Aantal verband wat je bij kan dragen verhogen

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2555]
### Contact Details

iHax0r

### Goedgekeurd door

Burgerraad & Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

Je hebt momenteel een limiet op 2 verband om bij te dragen & 2 verband om te gebruiken. Dit is een beetje dubbel op, dus zorgen dat je meer dan 2 kan bijdragen. Alleen wel maximaal 2 kan gebruiken.

Voeg ook een gewicht toe aan verband, zodat je niet 100 verband meeneemt.  

### Wat lost deze feature op?

Zorgen dat je wel fatsoenlijk verband kan meenemen en eventueel in je huis/kluis/auto een stash maken.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Xuifyy** [comment]
@Tom974 ik denk dat er iets meer gewicht op moet zitten. Net liep er namelijk iemand met 80 verband xD.
Ik zou zelf zeggen dat je maar maximaal ongeveer 10 kan dragen.
