### ISSUE TITLE
[FEATURE]: Witwas aanpassingen

### ISSUE THREAD

**Issue by iHax0rMC** [Tedeapolis/development#2556]
### Contact Details

iHax0r

### Goedgekeurd door

Burgerraad & Staffoverleg

### Beschrijf zo duidelijk mogelijk de feature

- [x] Witwassen in het bazenmenu functionerend maken.
- [x] Witwaspercentage 10% (Bazenmenu)
Duurt: 72 uur.

Witwassen met de job
Percentage behouden
- [x] x1.5 per punt, zodat het sneller gaat.
Afhankelijk maken van spelersaantal (is als het goed is al)
- [x] Limiet eraf halen indien van toepassing (momenteel voel je geen verschil tussen 40 miljoen en 80 miljoen).

### Wat lost deze feature op?

Geeft je een extra optie in het bazenmenu, waarin je witwast voor 10% in het bazenmenu. (dit werkt momenteel niet)
Dit duurt 72 uur lang.

Witwassen in de bus aantrekkelijker maken, zodat het geen echte baan is. Zorgen dat er meer risico is door spelersaantal erin mee te nemen. Limiet eraf halen, high risk high reward.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Tom974** [comment]
Witwassen in het bazenmenu functionerend maken.

Dit is toch al werkend?

**Comment by Raff072** [comment]
Dit werkt niet. Bij ons werkte het niet en bij andere groepen ook niet. 
Zag ook deze github https://github.com/Tedeapolis/development/issues/2551 dus het zal denk ik nog steeds niet werken.

**Comment by iHax0rMC** [comment]
Werkte idd laatst nog niet

**Comment by Tom974** [comment]
Fixed
