### ISSUE TITLE
[FEATURE]: Respawn timer verlengen wanneer iemand down ligt. 

### ISSUE THREAD

**Issue by RoxyFay** [Tedeapolis/development#2560]
### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Het gebeurt nu wel eens dat iemand **automatisch** respawned midden in een scenario. 
looc benoemen dat er nog 1 minuut is bijvoorbeeld verstoord ook vaak het scenario. 

In burgerraad is besproken dat de automatische repawner verlengd moet worden naar 30 minuten. 
Mocht je eerder kunnen respawnen, dan kan er gewoon gebruik gemaakt worden van E. 
Maar dan gebeurt het automatisch respawnen niet meer mid scenario. 

### Wat lost deze feature op?

Niet meer automatisch respawnen midden in scenario terwijl ambulance nog bezig is, of wapen nog niet is afgenomen. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd!
