### ISSUE TITLE
[FEATURE]: In de kofferbak van een werkvoertuig kunnen met grankeys

### ISSUE THREAD

**Issue by Dyon033** [Tedeapolis/development#2563]
### Contact Details

dyon.

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Op het moment is het niet mogelijk spullen uit andermans werkbus te pakken. Echter zijn er bedrijven die bijvoorbeeld zeebaars opkopen bij vissers. Op dit moment is het alleen lastig om die bussen leeg te halen aangezien dit dan gedaan moet worden door de eigenaar van de bus zelf. 

Ook heb je mensen die samen ramenwasser doen bijvoorbeeld. Ook die kunnen dan niet beide in de kofferbak.

Hier is een suggestie voor gemaakt dat mensen met grantkeys dan ook dingen uit de kofferbak van het werkvoertuig kunnen pakken.

Link naar suggestie: https://discord.com/channels/563825802865541122/1315702756144582739

### Wat lost deze feature op?

Dat mensen die samen uitzendjobs doen of mensen die vis opkopen ook in de kofferbak kunnen van een werkvoertuig.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Doorgevoerd!
