### ISSUE TITLE
[FEATURE]: Unmarked garage toevoegen

### ISSUE THREAD

**Issue by HarkoB** [Tedeapolis/development#2568]
### Contact Details

.jarno.

### Goedgekeurd door

Staff overleg

### Beschrijf zo duidelijk mogelijk de feature

Een unmarked garage toevoegen in de haven. (groene en rode cirkel is voldoende)
Eventueel hier de auto's laten spawnen: https://prnt.sc/2kXGTBFisL94
Eventueel hier de cirkels: https://prnt.sc/EK04EugsNr6d

### Wat lost deze feature op?

Dat je je auto's kan pakken en wegzetten bij de boot cirkel.

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
fixed
