### ISSUE TITLE
[FEATURE]: Automatische /e pas wanneer wij een ID kaart pakken via F6

### ISSUE THREAD

**Issue by ArjanSteenboom** [Tedeapolis/development#2571]
### Contact Details

tbone5192

### Goedgekeurd door

N.V.T.

### Beschrijf zo duidelijk mogelijk de feature

Graag zouden wij willen zien dat wij ook automatisch /e pas doen wanneer wij een ID kaart pakken via onze f6. Nu is het vaak dat mensen niet deze emote bebruiken om iemand zijn ID kaart te pakken omdat wij het handmatig moeten doen. 

### Wat lost deze feature op?

Deze feature lost het probleem op dat wij mensen hun ID kaart kunnen pakken zonder wij die emote doen. Veel ambulanciers doen deze emote niet, dus zal deze feature een aangename aanpassing zijn. Nu kan je het doen zonder dat andere mensen het zien, door deze feature toe te voegen wordt dit probleem ook opgelost. 

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
fixed
