### ISSUE TITLE
[Bug]: Je hoort een telefoon te krijgen als je uit de gevangenis komt, dit gebeurt niet.

### ISSUE THREAD

**Issue by Xuifyy** [Tedeapolis/development#2574]
### Contact Details

xuify

### Wat gebeurde er?

Ik had me zelf voor 1 minuut gejailed omdat ik te horen kreeg dat het telefoon krijgen niet werkte. Toen ik vrij gelaten werd kreeg ik inderdaad geen telefoon.

https://youtu.be/urocXrmbXTQ

### Wat hoorde er te gebeuren?

Dat als je vrij gelaten word dat je 1 telefoon krijgt.

### Wat veroorzaakt de bug?

Zie bovenstaande informatie

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

### Relevante log bestanden

![image](https://github.com/user-attachments/assets/6b42b361-0b5f-42ad-8861-bd5b4c1fdb3e)

### Richtlijnen

- [X] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by Zjefvm** [comment]
Fixed
