### ISSUE TITLE
Het vissen als bijjob

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#262]
Als je een hengel koopt, aas en je wilt gaan vissen werkt dat niet.

Je gaat naar een plaats waar het diep genoeg is.
Dan gebruik je u hengel.
Dan werkt het volgende al niet. Al er staat druk op een cijfer en je doet het, krijg je geen vis.
Het volgende wat ook niet werkt is dat je geen aas of schildpadden aas aan een hengel kunt haken om te vissen.

**Comment by Willem-Dekker** [comment]
ik heb het net getest en het werkt gewoon
