### ISSUE TITLE
Werk in gevangenis geeft geen rewards/loon. 

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#263]
In de gevangenis is het volgens mij de bedoeling dat gevangenen d.m.v. werk hun voedsel en drinken kunnen aanvullen.
Daarnaast krijgen ze volgens de tooltip nog een beetje geld als beloning.

Dit de melding hiervan wordt wel gemaakt maar je krijgt vervolgens niks als gevangene.
Voor het werk:
![image](https://user-images.githubusercontent.com/56109953/97116290-737be080-16fc-11eb-9a79-4c123b33843c.png)
Na het werk:
![image](https://user-images.githubusercontent.com/56109953/97116294-78409480-16fc-11eb-8b62-03b86eec0f8d.png)

**Comment by Willem-Dekker** [comment]
heb het net getest en werkt gewoon
