### ISSUE TITLE
Crosshair toevoegen voor de Hunter / Camera toevoegen voor de Hunter en de Buzzard

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#264]
Tijdens staffoverleg is dit overlegd dus bij deze de github issue:

met camera wordt bedoelt, een camera die ook in de zulu zit.

Hunter: moet een crosshair en camera krijgen
- [x] crosshair voor alle inzittende
- [x] camera voor alle inzittende

Buzzard: moet enkel een camera krijgen
- [x] camera voor alle inzittende

**Comment by Willem-Dekker** [comment]
camera zit er op.
