### ISSUE TITLE
Niet kunnen remmen en sturen na inklikken rechtermuisknop op auto/motor

### ISSUE THREAD

**Issue by prepix** [Tedeapolis/development#268]
Dat je niet direct gas kan geven kan ik snappen, maar je kan gewoon 3 seconden niet remmen/sturen niks, soms klik je je telefoon weg met rechtermuisknop rij je jezelf dood of je motor kapot

**Comment by Willem-Dekker** [comment]
ja dit is normaal gedrag, maar zou denk ik een check op moeten of je daadwerkelijk een wapen hebt.

**Comment by Willem-Dekker** [comment]
is normaal gedrag
