### ISSUE TITLE
Klacht van speler Jornn

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#27]
Het probleem is dat : Als je een boot uit de opslag haalt iedere keer 500 euro moet betalen. Ook al zet je de trailer veilig in de opslag moet je volgende keer gewoon weer 500 euro betalen. Het zou fijn zijn als hetzelfde wordt als de auto's. Gewoon als die stuk is of weg is dat je dan 500 euro moet betalen en voor de rest gratis eruit kan halen en gewoon moet betalen voor de schades ect. Misschien ook een leuk idee om dat te doen voor de boten. Precies hetzelfde verhaal, laat je hem staan op het water moet je betalen zet je hem er netjes en veilig in gewoon gratis eruit halen.

**Comment by niekschoemaker** [comment]
Deze issue is voor zover ik kan zien gefixed dus ik sluit de issue
