### ISSUE TITLE
(Offline) warnings

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#275]
Het zou enorm handig zijn dat er alsnog een taakstraf wordt gegeven bij waarschuwingen die worden gegeven terwijl de speler op dat moment offline is. Zodra de speler dan weer de server in komt, krijgt hij 50 uur taakstraf. 

Daarnaast zou het handig zijn om waarschuwingen ook inzichtelijk te maken voor spelers. Mocht een speler namelijk een offline warning ontvangen, dan merkt hij/zij hier niets van. Dit zou bijvoorbeeld opgelost kunnen worden door een soort van "error message" te laten zien als de speler de eerst volgende keer joint na een waarschuwing die offline is gegeven. 

- [x] Toevoegen van een taakstraf bij offline warnings
- [ ] Warnings (die offline zijn gegeven) inzichtelijk maken voor spelers

**Comment by Willem-Dekker** [comment]
2e punt kan niet, zoder dat daar enorm veel werk in gaat zitten.

**Comment by TDA-SanderD** [comment]
Is reeds gefixt door Niek.
