### ISSUE TITLE
Aanvraag voor extra rol Pavlov in ticket 14450.

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#277]
Goeiemorgen 

Ik ben aanspreekpunt van pavlov en wij als pavlov zijnde zouden graag een nieuwe rol krijgen..

Stric
Deze rol zou net onder de hoogste staan,genaamd ocec.

Deze zal dan ook alle's kunnen wat een ocec kan,behalve aan het potgeld komen & Ledenlijst

Deze rol zou dan kunnen komen ipv de rol gopnik.

Alvast bedankt!

Nieuwe rol Stric

- [x] Op 1 na hoogste rang geplaatst worden in de pavlov rang list. 

- [x]  Deze rol mag alle's behalve aan de pot zitten en aan de leden aan nemen en ontslaan.

- [x]  Naam van de rol is Stric.

**Comment by Willem-Dekker** [comment]
okay en wat moet er gebeuren met de vorige aanvraag die nog niet verwerkt is zie #244

**Comment by Kobinsky18** [comment]
Ze willen een nieuwe rank onder de bazen rank die een aantal perms heeft zolas het hierboven vermeld staat.

**Comment by Willem-Dekker** [comment]
dit is geen antwoord op de vraag die ik stelde.....
