### ISSUE TITLE
Bug Bij de phone dealer .

### ISSUE THREAD

**Issue by SvenKeppel** [Tedeapolis/development#279]
Hey jongens er is een kleine wall bug bij de phone dealer. 
Zo kunnen mensen dus ontsnappen aan de politie via de wall. 
Zouden jullie hier even naar kunnen kijken. 

(Link voor bewijs) https://www.youtube.com/watch?v=f4yoEpZN6RQ

**Comment by Willem-Dekker** [comment]
fixed
