### ISSUE TITLE
Ferrari Pista Spider niet meer van kleur veranderen

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#281]
De ferrari pista spider kan alleen nog maar de WITTE kleur als je kiest voor de optie 1 kleur (zonder stickers). De binnenkant van de deuren kleuren wel mee en worden bijvoorbeeld rood, maar de auto zelf niet.

**Comment by Willem-Dekker** [comment]
@Nander0320 of @walvisgedaan kunnen jullie hier eens naar kijken?
