### ISSUE TITLE
de rode cirkel komt er niet meer als je dood gaat. 

### ISSUE THREAD

**Issue by BartBoos** [Tedeapolis/development#282]
de rode cirkel die normaal als je dood gaat waar je een uur niet in kunt komen komt er niet meer. met dit als gevolg dat mensen nadat ze dood zijn gegaan gewoon terug kunnen komen op de plek waar e dood zijn gegaan.

**Comment by Willem-Dekker** [comment]
Heb je hier log bestanden van?
