### ISSUE TITLE
Boottrailer script 

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#283]
Bonjour, het **script** van de **boottrailer** werkt niet meer optimaal. Mijn boot werd ineens een prop waar je doorheen kon lopen en als je wilde instappen, dan gebeuren er rare dingen. Er poppen in F8 ook geen gekke errors o.i.d. op. 

Kan hier geen MP4 file indroppen, dus voel me vrij een PM bericht te sturen op Discord. Zal de clip dan toesturen.
Issue meer bedoeld voor: @Willem-Dekker

**Comment by Willem-Dekker** [comment]
Hier is al 3 maanden niks aan veranderd  dus vind het ook raar dat er nu dan in eens problemen mee zijn.

**Comment by ToniGain** [comment]
Ik heb zelf ook werkelijk waar geen idee, maar ik weet wel dat de boot ineens een walking through prop werd en als ik wilde instappen van A naar B teleporteerde en uiteindelijk zo hoog vloog dat ik dood ging. Zodra ik uit ben zal ik game logs tonen + de clip.

**Comment by ToniGain** [comment]
Als je mij een discord bericht kan sturen, stuur ik wat er precies aan de hand is dmv clips.

**Comment by Willem-Dekker** [comment]
Ik heb hier niks aan kunnen vinden
