### ISSUE TITLE
Rangen Politie

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#286]
Graag zouden wij drie rangen toegevoegd willen hebben binnen de politie:

Recherche leiding: 1400
Titel spreek voor zich. Dit salaris word alleen verdiend voor personen met een leidinggevende functie binnen de recherche.

Recherche Senior: 1200
Dit salaris wordt verdient door personen die ervaren krachten zijn binnen de recherche. Deze personen weten de werkwijze, en zijn in staat dit over te brengen naar de junioren. Enkele van de senioren kunnen in aanmerking komen om door te stromen naar leiding. 

Recherche Junior: 1000
Dit zijn personen die in hun proefperiode zitten, en vanaf daar ervaring op gaan doen. Uiteindelijk zullen deze personen doorstromen naar senior, mits ze zichzelf bewezen hebben als volwaardig lid.

Alle premissions van de rangen moeten het zelfde zijn als de rang Recherche actueel. Nadat de rangen zijn aangemaakt mag de oude Recherche range verwijderd worden.

**Comment by Nander0320** [comment]
Ik kijk hier vanavond naar

**Comment by Willem-Dekker** [comment]
Zijn toegevoegd  zitten er morgen in
