### ISSUE TITLE
Flitspaal midden op de weg

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#288]
![image](https://user-images.githubusercontent.com/68959019/100358526-96006280-2ff6-11eb-8c69-44407a656cd3.png)

![image](https://user-images.githubusercontent.com/68959019/100358568-a4e71500-2ff6-11eb-99c5-65fb268133c2.png)

![image](https://user-images.githubusercontent.com/68959019/100358593-ae707d00-2ff6-11eb-935b-35ccdea720e2.png)

Flitspaal midden op de weg, kan deze weggehaald worden of verplaatst?

**Comment by Willem-Dekker** [comment]
fixed voor volgede restart
