### ISSUE TITLE
Gangs F6 menu put en drag out of vehicle werkt niet meer.

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#289]
[https://youtu.be/NQpsGQA_WKM]
Het werkt niet, als je iemand het voertuig in wil zetten moet eerst iedereen uit het voertuig.

**Comment by Willem-Dekker** [comment]
logs?

**Comment by TDAMarvinW** [comment]
[CitizenFX_log_2020-12-15T191532.log](https://github.com/Tedeapolis/development/files/5698212/CitizenFX_log_2020-12-15T191532.log)

Hoop dat je hier wat aan heb :D
