### ISSUE TITLE
Na dood gaan een gebied waar je naar dood gaan niet in mag komen

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#29]
De new live rule beter handhaven door middel van een systeem, om je uit dat gebied te houden / het markeren van dat systeem. 

- [x] Het weergeven van de regio waar je bent doodgegaan.
- [x] Persoon op de hoogte stellen als je in die regio komt
- [x] Persoon na x hoeveelheid tijd uit deze zone tpen.

**Comment by niekschoemaker** [comment]
Issue is gepushed naar master, zal binnenkort wel verschijnen op main server.

[] Mededeling eruit gooien over deze update
