### ISSUE TITLE
Snelheid Audi A6

### ISSUE THREAD

**Issue by Jesse-Poolman** [Tedeapolis/development#290]
De optrek snelheid van de A6 willen we graag omhoog hebben. Zodat wij ook bij kunnen trekken met achtervolgingen, kan er ook naar gekeken worden naar de top snelheid van de A6? zo ja dan willen wij hem verhogen naar 370km/h. Gezien de snelheid van de RS6 ook zo hard gaat. En wij steeds genoodzaakt zijn om de RS6 te pakken bij achtervolgingen. Aub geen handeling veranderen van de A6.

**Comment by Nander0320** [comment]
Voor de a6 zijn de geen realistische snelheden in het echt loopt zo'n bak niet harder dan 270 max denk ik, los dit dus op door meer inzet van de maserati of de politie rs6.

**Comment by Jesse-Poolman** [comment]
Is goed, dan zal ik dat door geven!
