### ISSUE TITLE
Kleine fixes

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#291]
- Flashlight verdwijnt na relog uit inv
- Parachute verdwijnt na relog uit inv

Voeg ATM's toe op
	{name="ATM", id=(), x=-1074.110, y=-827.350, z=19.040},
        {name="ATM", id=(), x=-549.750, y=-204.440 z=38.220},
        {name="ATM", id=(), x=-423.530, y=-342.860 z=24.230},
        {name="ATM", id=(), x=-421.030, y=-349.500 z=24.230},
        {name="ATM", id=(), x=-355.610, y=-130.610 z=39.440},
	{name="ATM", id=(), x=-37.740, y=-1115.360, z=26.440}, met ATM prop indien mogelijk

**Comment by ToniGain** [comment]
![image](https://user-images.githubusercontent.com/73707925/102009398-70ce5c80-3d37-11eb-957d-b7e869a4a772.png)
toevoeging op de eerste 2 puntjes

**Comment by Willem-Dekker** [comment]
de prop kan ik niet plaatsen anderen zijn geplaast
