### ISSUE TITLE
Audio not working when leaving or entering appartment. 

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#3]
**Describe the bug**
als je naar binnen loopt in een appartement hoor je niks meer (voice-chat)

**To Reproduce**
1. ga een appartament in
2. praat je niemand hoort je 
3. ga naar buiten
4. niemand hoort je

**Expected behavior**
je hoort mensen

**Additional context**
reloggen lijkt het te fixen

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn na restart, moeilijk te testen op test server.
Als issue na restart gefixed is kan issue gesloten worden, anders even comment plaatsen dat er verder naar gekeken moet worden
