### ISSUE TITLE
KMAR aanpassingen

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#30]
Even een paar kleine dingetjes die handeg zouden zijn als het niet te veel werk bij komt kijken. 

- [x] De snelheid kunnen meten van voertuigen. (Het kunnen flitsen met je voertuig)

- [x] Het kunnen onderuithalen (Tekelen)  van personen 

- [x] Het openbaar maken van de slootten voor KMAR bij de bezoekers ruimte is alleen nog maar toegankelijk voor  politie.

- [x] Eventueel weer een cirkel voor voedsel en drinken in de gevangenis. Eventueel gewoon waar wij als KMAR bij kunnen maar 
  burgers niet.  De eventueel locatie daar voor is de cafetaria.

**Comment by Willem-Dekker** [comment]
> Het openbaar maken van de slootten voor KMAR bij de bezoekers ruimte is alleen nog maar toegankelijk voor politie.
weet niet welke sloten je bedoeld maar dit  is volgens mij gewoon de bedoeling dat kmar dit allemaal in goede banen leid.

**Comment by Willem-Dekker** [comment]
alle punten zijn gedaan
