### ISSUE TITLE
Voertuigen verdwijnen door X spier bug

### ISSUE THREAD

**Issue by TDARemco** [Tedeapolis/development#300]
Soms als je in een voertuig zit
(stilstaand) of (rijdend)
Overheid en of normale voertuigen.
Deze verdwijnen soms als je op X drukt terwijl je in het voertuig staat als bestuurder.
En dit alleen als het jou eigen voertuig is. (privé en of overheid)
Dit is uitgebreid getest door mij en 2 andere spelers.
En dit is een 30+/- keer gebeurd.

Dit is bij mij bekend sinds 5 dagen geleden nu.

**Comment by Willem-Dekker** [comment]
zijn hier log bestanden van?

**Comment by TDARemco** [comment]
Ik ga dit even opzoeken zodra ik terug wakker ben.

Op di 8 dec. 2020 15:34 schreef Willem Dekker <notifications@github.com>:

**Comment by Willem-Dekker** [comment]
al meer info?

**Comment by TDARemco** [comment]
Ik heb hier in de loggs njks van kunnen vinden. Ook heb ik de laaste dagen
dit probleem niet meer ervaren

Op zo 13 dec. 2020 00:01 schreef Willem Dekker <notifications@github.com>:
