### ISSUE TITLE
Rangen en lonen kmar

### ISSUE THREAD

**Issue by Robertowhh** [Tedeapolis/development#303]
Als het mogelijk zou zijn hebben we nog een paar extra rangen om zo de doorstroom beter te laten verlopen en ook met de bsb rangen omdat zij nu samen met de dsi zijn is het handig als daar de rangen hetzelfde zijn. Hieronder duidelijk uitgeschreven hoe de structuur er dan uit komt te zien!
 
https://cdn.discordapp.com/attachments/749738041668534302/783750808193204304/KMAR_RANGEN.xlsx

**Comment by Willem-Dekker** [comment]
done
