### ISSUE TITLE
Geen damage in het cellenblok

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#305]
Tijdens het staffoverleg is besproken dat vanaf heden damage door eten moet worden uitgezet. Zodra een persoon dus in het cellencomplex komt, wordt de honger-/dorstfunctie uitgeschakeld, waardoor iemand niet meer dood kan gaan in een politiecel door een tekort aan water/voedsel.

**Comment by StoffigKontje** [comment]
Fixed, safezone toegevoegd aan het cellenblok in HB zodat je geen damage meer krijgt van te weinig eten/drinken. Ze moeten nog wel eten en drinken krijgen dus!
