### ISSUE TITLE
Nummer voor recherche

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#307]
Het zou zeer handig zijn om een optie toe te voegen waarmee iedereen die een rechercherang heeft (Junior rechercheur, senior rechercheur, recherche leiding en uiteraard korpsleiding/EHC) toegang krijgt tot een nummer dat specifiek voor de recherche is bedoeld, soortgelijk aan het DSI-nummer. Agenten kunnen het nummer invoeren en meldingen sturen naar de recherche.

**Comment by Willem-Dekker** [comment]
done
