### ISSUE TITLE
Opslag politie

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#308]
De politie zou graag een extra cirkel willen zien, soortgelijk/gelijk aan de cirkel op -3, waar ze inbeslaggenomen goederen als drugs en dergelijke in kunnen vernietigen. De coördinaten hiervan zijn:
X: -1087,03, Y: -843, 50, Z: 4.88, H: 6568,

Dit is goedgekeurd door Nick.

**Comment by Willem-Dekker** [comment]
Zit er morgen in er is alleen toegang tot het gedeelte voor de items en niet voor de wapenkamer bij deze blip
