### ISSUE TITLE
DSI lightbars 

### ISSUE THREAD

**Issue by SvenKeppel** [Tedeapolis/development#31]
DSI lightbars 

Het lijkt compleet mis te gaan met de lightbars voor de DSI .  Ze werken wel met inladen enzv maar als je ze dan aan wilt zetten krijg je de radio .  q en e werken beide niet en je kan t voertuig geen sirene laten afspelen

**Comment by Willem-Dekker** [comment]
graag log bestanden

**Comment by SvenKeppel** [comment]
Welke logs wil je hebben ? Dan zoek ik ze morgen ff op willem .

Op za 25 jul. 2020 om 22:43 schreef Willem Dekker <notifications@github.com>

**Comment by Willem-Dekker** [comment]
game logs, we kunnen het niet reproduceren en zien ook geen errors. met alle banen die hier toegang tot hebben
