### ISSUE TITLE
Je kan door de muur bij de kmar

### ISSUE THREAD

**Issue by AFriendlyRacoon** [Tedeapolis/development#310]
Bij de kmar kan je door de muur en dus binnen in het gebouw komen door een bug coords hiervan zijn 
X:1827.39 Y:2577.60 Z: 45.67 H: 350.73

**Comment by Willem-Dekker** [comment]
ik heb dit bij oes neer gegooid hij zal er naar kijken

**Comment by Willem-Dekker** [comment]
fix staat klaar moet nog worden gezet in de main server
