### ISSUE TITLE
Garage op taxiterrein weghalen

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#317]
De garage op het terrein van de taxi zorgt voor veel kutkoters/vervelende situaties. De vraag is dus of deze ALSJEBLIEFT weggehaald kan worden.

coords: 
x: 905.06
y: -175.67
z: 74.07
h: 300.65
 
![image](https://user-images.githubusercontent.com/53233719/102127575-f263de80-3e4c-11eb-98b8-ad447a2b6070.png)

**Comment by Willem-Dekker** [comment]
is weg
