### ISSUE TITLE
/testreticle kan worden gebruikt voor een crosshair ingame 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#32]
als je in first person zit en je hebt een wapen vast en je typed /testreticle dan krijg je een crosshair als je weer terug gaat naar third person dan staat het stipje er. /testreticle kan ook worden gebruikt voor third person slaan.

https://www.youtube.com/watch?v=TwoPX9n7kwM

**Comment by Willem-Dekker** [comment]
fixed
