### ISSUE TITLE
Aanvullingen KMAR

### ISSUE THREAD

**Issue by TomK-KMAR** [Tedeapolis/development#323]
- **Beschrijf zo duidelijk mogelijk de feature**

- [ ] Takelwagen KMAR (dit om de politie te ontlasten en zodanig zelfstandig ons werk kunnen doen);

- [x] Toegang tot de inbeslagname cirkel van voertuigen zodat wij zelfstandig de inbeslagnames kunnen afhandelen;

- [ ] KMAR reskin van de Mercedes-benz Vito (dit zodat wij onze standaard arrestantenvervoer hier in kunnen laten rijden);

- [ ] Stand van zaken KMAR Opel Astra;

- [ ]  Meerdere camerapunten (Dit om vanuit HB zicht te kunnen houden op de belangrijke punten voor de KMAR, Punten wat wij      graag zouden willen zien: Vliegveld/In en buiten de gevangenis/westpost

- [ ]  Schietmeldingen vanaf de rang Wachtmeester (Dit omdat wij snel interventie kunnen plegen in het noorden op deze meldingen    met onze vrije surveillance eenheden.

- [ ] (h)OvJ KMAR mogelijkheid tot het geven van taakstraffen (dit ook om de politie te ontlasten voor deze kleine taken)

- [ ]  3 mogelijke nieuwe KMAR posten (Info ligt bij Kenneth)

- [ ]  Toevoeging van de KMAR jas  aan het EUP menu (Deze is al in de stad mogelijk toevoegen genaamd 'KMAR JAS'

- [ ] Toevoeging HRB outfit aan de EUP. (Voor verdere info hierover stuur DM)

- [ ]  Toevoeging van het realistische vest van de KMAR (Het vest wat wij nu dragen zit standaard 5.56 patroonhouder in zouden      dit graag realistischer zien
- [ ] Verlichting op de posten (het is er te donker in de nacht)

**Wat lost deze feature op?**

Meeste van deze features lossen het afhankelijk zijn van de politie op. Waardoor de politie bezig kan met zijn eigen taak en wij met onze taak.

**Comment by Willem-Dekker** [comment]
in beslag name is in het verleden gebleken dat dit niet toevertrouwd kan worden en misbruik van gemaakt wordt
