### ISSUE TITLE
Problemen met kogels

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#326]
**Omschrijf de bug**
Je kan kogels overgeven van wapen tot wapen. Soms verwijden ze ook. Is ook te zien in de video wat ik erbij ga plaatsen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door elke keer een wapen in je appartement te leggen. Meerdere wapens eruit te nemen. Zo worden de kogels eigenlijk verdeeld over meerdere wapens. Soms ga ook ineens je kogels weg wat te zien is op de video.

**Normaal gedrag (Wat zou er normaal moeten gebreuren***
Normaal zou alle kogels in zijn eigen wapen moeten zitten.

**Screenshots en/of logbestanden**
https://www.youtube.com/watch?v=1gXBzbDrRdA&feature=youtu.be&ab_channel=Wesley

**Impact op de server**
Zo kunnen mensen goedkope kogels kopen en het vullen bij de duurdere wapens. Of je hebt ineens een wapen nodig maar zie je dat de kogels ineens op zijn. Dit kan voor frustratie zorgen

**Comment by niekschoemaker** [comment]
Deze issue wordt veroorzaakt omdat je meer dan 1 wapen met hetzelfde type ammo bij je hebt.
Dus je kunt maximaal 120 kogels bij je dragen voor AMMO_RIFLE
