### ISSUE TITLE
Tankstation user crash

### ISSUE THREAD

**Issue by prepix** [Tedeapolis/development#327]
**Omschrijf de bug**
Als een tankstation ontploft crashen spelers in de buurt

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Tankstation laten ontploffen

**Impact op de server**
Groot

**Comment by Willem-Dekker** [comment]
logs?

**Comment by niekschoemaker** [comment]
Deze issue is sinds de laatste commit hopelijk gefixed, ik heb nu de explosies van tank stations verwijderd.

**Comment by niekschoemaker** [comment]
Explosies van tankstations zijn weggehaald, crash is een week lang niet meer voorgekomen.
