### ISSUE TITLE
Arm/Disarm functionaliteit

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#328]
Als je in een helikopter zit die gedisarmed is en je dan op spatie drukt (schieten) dan schiet je op je eigen beeld niet, maar bij andere wel. /disarm werkt dus alleen bij jezelf want andere horen/zien je nog wel shcieten

repro: spawn een buzzard in, disarm hem en druk op schieten, andere mensen zullen je dan wel horen/zien schieten

**Comment by niekschoemaker** [comment]
Is vanaf morgen (dus over 24 uur) gefixed.
Werkt sws stukken beter zo, je kunt nu van te voren al wapen selecteren en crosshair etc verwijderd hij automatisch (is blijkbaar iets wat GTA standaard al doet, nooit geweten)
