### ISSUE TITLE
Agenten kunnen geen wapens pakken 

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#33]
**Describe the bug**
agenten kunnen geen wapens pakken uit de kluis . 
https://www.youtube.com/watch?v=gmyEcWw61Jc

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Willem-Dekker** [comment]
heb je hier ook een log bestand van?

**Comment by takermart** [comment]
[CitizenFX_log_2020-07-26T082418.log](https://github.com/Tedeapolis/development/files/4977346/CitizenFX_log_2020-07-26T082418.log)

**Comment by Willem-Dekker** [comment]
dit is opgelost
