### ISSUE TITLE
Vissersjob kleding Bug

### ISSUE THREAD

**Issue by TDARemco** [Tedeapolis/development#330]
**Omschrijf de bug**
Als je als 2de job visser bent, krijg je na het reloggen / joinen van de server automatich vissers kleding aan. Ook als je hier voor niet in dienst bent geweest als visser

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Aanpassen script waardoor je kleding automatich krijgt.

**Screenshots en/of logbestanden**
Niet aanwezig aangezien dit niet in loggs te vinden is.

**Impact op de server**
Automatich aanpassen van je kleding.

**Comment by Willem-Dekker** [comment]
fixed
