### ISSUE TITLE
Wapen upgrades kickt uit menu

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#332]
Momenteel is het in het politie arsenaal zo dat als jij een wapen attachment op je wapen zet, je terug gaat naar het wapenkies menu.

Dit is enorm vervelend als je (als DSI) meerdere dingen er op moet zetten. Is het mogelijk (en zo ja, fix pls) dat je in het attachments menu blijft?

Ty!

**Comment by Willem-Dekker** [comment]
Niet voldaan aan issue format
