### ISSUE TITLE
De Ammu-Nation shop verplaatsen naar het Noorden

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#333]
**Beschrijf zo duidelijk mogelijk de feature**
De huidige Ammu-Nation shop verplaatsen naar het noorden. XD

**Wat lost deze feature op?**
Op deze manier moeten criminelen vaker naar het noorden reizen voor hun steekwapens. 
Zo komt er wat meer variatie in de server en is niet alles in het zuiden.
Tevens is dit ook leuk voor de Kmar. Zo hebben zij weer wat meer te doen in het noorden.

**Comment by Willem-Dekker** [comment]
Done
