### ISSUE TITLE
Blip politie

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#334]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel kan de politie blips op de map zien waar de collega's zijn. Graag zouden wij de feature er uit willen hebben zodra de agent uit het voertuig is. Dus de agenten mogen de collega's niet meer zien op de map zodra ze uit hun voertuigen zijn. 
**Wat lost deze feature op?**
Stukje powergaming en het voegt RP toe bij de politie.

**Comment by niekschoemaker** [comment]
Dit zit er als het goed is al in.

**Comment by SecretSupplier** [comment]
Correct!
