### ISSUE TITLE
Wapenlocker is kapot

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#335]
**Omschrijf de bug**
Als je in de politie wapenlocker zit en een attachment op je wapen zet, dan ga je terug naar het eerste menu.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Koop een wapen in de politie locker en zet er een attachment op.

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Lijkt me dat je dan in hetzelfde menu blijft om zo sneller attachments er op te kunnen zetten.

**Screenshots en/of logbestanden**
Lijken me niet nodig

**Impact op de server**
Niet al te veel.

**Comment by walvisgedaan** [comment]
test

**Comment by niekschoemaker** [comment]
Click bait title REEEEEEEEEE

Maar zal t binnenkort ff fixen

**Comment by Willem-Dekker** [comment]
fixed
