### ISSUE TITLE
Nissan Skyline buffen

### ISSUE THREAD

**Issue by ToyStoner** [Tedeapolis/development#336]
Beschrijf zo duidelijk mogelijk de feature:
De Nissan Skyline is een Japanese auto. Deze auto staat bekend voor zijn extreme motor prestaties. De Skyline was eerst een uitmuntende auto, maar door verschillende nerfs op die auto is hij niet meer zo goed als hij was. Door die nerfs heeft de auto een beetje zijn waarde verloren.

Wat lost deze feature op?:
Dit kan gefixt worden door de topsnelheid naar 305km/h op te krikken. Ook zou ik de acceleratie opkrikken. Misschien even snel optrekken als de Brabus 800. De handeling is volgens mij wel mooi gebalanceerd.

**Comment by Willem-Dekker** [comment]
Zal niet gedaan worden op dit moment
