### ISSUE TITLE
NPC jobs gelijk trekken

### ISSUE THREAD

**Issue by ToyStoner** [Tedeapolis/development#338]
**Beschrijf zo duidelijk mogelijk de feature**
Is het geen idee om de NPC jobs gelijk te trekken? Ik heb mij even bezig te houden met alle NPC jobs uit te proberen, uit dit onderzoek heb ik besloten dat Slager en Kleermaker veel minder goed verdienen als olieverwerker of visser. 

De buschauffeur job doet het zelfs helemaal niet. 

**Wat lost deze feature op?**
Deze buff/nerf zorgt ervoor dat er minder druk komt op 1 bepaalde job. Hierdoor heb je niet dat er 50 vuilnismannen rond blokkenpark rijden. Ook kan dit er voor zorgen dat de server stabieler word omdat er minder mensen op dezelfde plaats op het zelfde moment zijn.

**Comment by niekschoemaker** [comment]
Ik buff en nerf banen vaak op basis van de hoeveelheid mensen die deze baan uitvoeren.

Mensen zoeken altijd de "beste" baan uit, ook al zit er zo goed als geen verschil tussen, dus je blijft dit probleem denk ik hebben.
