### ISSUE TITLE
Rijschool

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#339]
**Beschijf zo duidelijk mogelijk de feature**
Een extra pand bij de luchthaven. 
Het CBR pand blijft zoals het is. Je kunt hier alleen je auto rijbewijs halen. (motor en vrachtwagen worden hier weggehaald)
Wanneer je je motor of vrachtwagen rijbewijs wilt halen, dan moet je naar de rijschool in de haven.
Ook wanneer je je rijbewijs verliest, mag je 24 uur niet opnieuw halen en ben je verplicht naar de rijschool te gaan voor de EMG cursus. 
Rijschoolauto's met eigen logo (motor en vrachtwagen mogen eventueel hetzelfde blijven)
Gebouw moet voorzien worden van een voertuigspawn voor de rijlesauto's
EMG cursus kost ongeveer 10k, Het geld kan naar een pot waaruit de instructeurs worden betaald.

Eventueel via f10 menu kunnen zien hoeveel instructeurs er online zijn. Na 24 speeluren kun je terugvallen op het CBR mits er minder dan 2 instructeurs in dienst zijn. (Eventueel tussen een bepaald tijdsslot)

Kenneth heet het extra pand.
Developers moeten de CBR plugin aanpassen of een nieuwe maken.

Is allemaal verder besproken in het staff overleg, Mart gaat dit leiden

----

Ik stel voor te beginnen met een basis opzet van een nieuw pand, met daarbij de opzet voor voertuigen spawnen en lessen te kunnen geven. Uiteraard de job rijinstructeur toevoegen. Eventueel Yassir een L laten plaatsen op een voertuig

Hierna kunnen we verder uitbouwen.

**Wat lost deze feature op?**

**Comment by AnatolyMoskvin** [comment]
> 24 uur cooldown zit er al op, voor de rest lekker laten zoals het is aangezien niemand hier nog tijd voor heeft :)

Lijkt me idd het beste vraag me af waarom deze issue nog open staat :P

**Comment by brothasx** [comment]
Nou bij deze is die gesloten x)
