### ISSUE TITLE
Bugg duikers

### ISSUE THREAD

**Issue by Jesse-Poolman** [Tedeapolis/development#34]
Bugg bij de duikers:
Als je gaat duiken naar een wrak stuk op de bodem, je drukt E je begint met lassen wanneer je aan het lassen bent druk je 2x X en je zwemt naar boven kan je terug in je boot stappen en wanneer je op je boot zit krijg je al je facturen waardoor je volgens de server nog in die animatie zit van het voertuig open lassen.

**Comment by Willem-Dekker** [comment]
Graag log bestanden van als dit gebeurt

**Comment by niekschoemaker** [comment]
Is dit alleen dat iemand wat eerder weg kan? Want zoals je het hebt verwoord komt het over dat iemand oneindig facturen krijgt dan maar kan dat zelf niet herproduceren?

**Comment by Willem-Dekker** [comment]
ik heb het net ook getest en ik had nergens last van.
