### ISSUE TITLE
despawn van vuilniswagen auto's werkt niet

### ISSUE THREAD

**Issue by ZoiH** [Tedeapolis/development#340]
**Omschrijf de bug**

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**

**Screenshots en/of logbestanden**

**Impact op de server**

**Comment by niekschoemaker** [comment]
Repro nodig 🤔
