### ISSUE TITLE
Tunnel onder oud ziekenhuis bugged

### ISSUE THREAD

**Issue by AFriendlyRacoon** [Tedeapolis/development#344]
**Omschrijf de bug**
Als jij de tunnel in komt rijden zie je mensen niet tot op het laatste moment 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een speler in de tunnel hebben met een auto en dan vanaf de kan van de snelweg aankomen rijden

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Normaal gezien moet je iedereen gewoon kunnen zien en niet op het laatste moment

**Screenshots en/of logbestanden**

https://user-images.githubusercontent.com/75691729/104340161-b332b700-54f8-11eb-840b-49816e3c94a9.mp4

**Impact op de server**
veel crashes met voertuigen onnodig werk voor de anwb

**Comment by niekschoemaker** [comment]
Kunnen we niet fixen is een onesync dingetje, gewoon snelheid minderen bij de tunnel.
Is voor zover ik weet ook niet specifiek bij de tunnel.

**Comment by niekschoemaker** [comment]
Waar dit ook wel op lijkt is op dat je het voertuig nog niet gedownload hebt (of de mods) want de personen en de ANWB auto zie je wel.

**Comment by niekschoemaker** [comment]
Al poosje terug opgelost, had met culling te maken.
