### ISSUE TITLE
De rang capo terug veranderen naar gopnik

### ISSUE THREAD

**Issue by Maxva03** [Tedeapolis/development#345]
**Beschijf zo duidelijk mogelijk de feature**
De pavlov rang genaamd "Gopnik" is uit het niets veranderd naar Capo, de vraag hierbij of de naam terug gewijzigd kan worden naar oude vorm.

**Wat lost deze feature op?**
Het is realistischer in ons rangensysteem, een spaanse naam hoort niet in een bulgaarse gang :)

- [ ] Naam van Capo naar Gopnik veranderen

**Comment by niekschoemaker** [comment]
Wat wil je nou? IN het begin vraag je of we capo naar gopnik kunnen veranderen en daarna of we gopnik naar capo kunnen veranderen?

**Comment by Maxva03** [comment]
Bericht aangepast

**Comment by Willem-Dekker** [comment]
zit er vanaf morgen in
