### ISSUE TITLE
Tunnels buggen

### ISSUE THREAD

**Issue by ToyStoner** [Tedeapolis/development#346]
**Omschrijf de bug**
Indien je in een tunnel rijd in de stad zal de persoon die mee in de tunnel rijd gaan laggen en buggen. Hierdoor botst hij op uw scherm tegen de rand of in de vangreel. Dit kan misbruikt worden in een achtervolging of irritant zijn als je zit te rijden met vrienden.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Met een klein groepje door verschillende tunnels rijden en u ziet het probleem van zelf.

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Normaal gezien zou je de persoon mooi zien rijden voor u of achter u.

**Screenshots en/of logbestanden**
/

**Impact op de server**
Zeer groot, dit kan misbruikt worden en het is ook extreem irritant.

**Comment by Willem-Dekker** [comment]
Kunnen we niet fixen is fivem wat ik zo lees
