### ISSUE TITLE
Bug om uit de kartbaan te komen

### ISSUE THREAD

**Issue by AFriendlyRacoon** [Tedeapolis/development#347]
**Omschrijf de bug**
Als jij met 3 tegelijk een kart pakt ga je vliegen zo kom je uit de kartbaan en kan je dus ook je kart tunen wat niet helemaal de bedoeling is

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Met 3 tegelijk een kart pakken op het zelfde moment

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Dat je een kart pakt en niet gaat vliegen

**Screenshots en/of logbestanden**
https://youtu.be/yAA8d1L1xPc 

**Impact op de server**
Mensen kunnen karts tunen en zo een betere tijd halen mensen kunnen dan ook met een kart buiten de baan rijden

**Comment by Willem-Dekker** [comment]
Heel simpel als dit gebeurt valt het onder bugabuse

**Comment by niekschoemaker** [comment]
Bugabuse dus perm ban, can't fix.

**Comment by niekschoemaker** [comment]
Toevoeging hierop, ik heb ergens (test of dev) de upgrades van deze voertuigen uitgeschakeld, dus dit zou als Cayo perico erin zit of binnenkort ook gefixed moeten zijn als in je hebt er niks meer aan dan.
