### ISSUE TITLE
Voice doet het niet wanneer je iemand uitnodigt in je appartement

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#348]
**Omschrijf de bug**
Wanneer je iemand uitnodigt in je appartement, doet de voice chat het niet voor beide personen. Je hoort elkaar dus niet. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In je appartement gaan en iemand uitnodigen.

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Je zou elkaar moeten kunnen horen in het appartement.

**Screenshots en/of logbestanden**
nvt

**Impact op de server**
Geen roleplay mogelijk in appartementen.

**Comment by niekschoemaker** [comment]
Zou je deze bug eens kunnen controleren met /displayvoicechannel erbij geactiveerd.
Dit command voegt bij je ID rechts onderin een nummertje toe, deze nummers moet ik even weten van beide personen, dit is het kanaal waar je in zit binnen het voice systeem namelijk.

**Comment by StoffigKontje** [comment]
https://media.discordapp.net/attachments/575819121405460492/801170467926966342/unknown.png
https://media.discordapp.net/attachments/575819121405460492/801170819144220672/unknown.png?width=1440&height=188

Dit moest ik doen van Niek, aangezien /displayvoicechannel niet helemaal werkte. Ondertussen werkt voice in appartementen wel weer. Thanks <3

**Comment by niekschoemaker** [comment]
Blijkbaar is dit gefixed met m'n mooie refactor van laatst 👍
