### ISSUE TITLE
Opslag voor helikopters voor politie

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#349]
**Beschijf zo duidelijk mogelijk de feature**
Als er nu een helikopter in beslag wordt genomen door de politie kan je nergens de helikopter in opslaan. 
Misschien ergens een cirkel waar je met je helikopter kan komen om een helikopter in beslag te nemen.

**Wat lost deze feature op?**
Nu weten mensen dat je geen helikopter inbeslag kan nemen en vliegen mensen gewoon rond alsof het niks is.

**Comment by niekschoemaker** [comment]
Deze is toegevoegd bij LSIA
