### ISSUE TITLE
Helicopters gaan heel de opslag in en komen er kapot uit

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#35]
"Wanneer ik mijn heli uit de helikopter opslag haal is deze stuk. Dit is nou al de 5e keer vandaag dus ik neem aan dat dit een bugg is. Zou iemand hier naar kunnen kijken want elke keer dat ik mijn heli moet laten maken door de ANWB kost mij die 1250,-. Dat dit 1x gebeurd kan gebeuren maar alleen vandaag al 5x vind ik een beetje veel worden. Btw ik zet mijn heli steeds helemaal heel terug in de garage dus het kan niet zijn dat ik m kapot in de opslag zet." ticket 6153

Heb hier al meerdere klachten over gehad.

**Comment by Willem-Dekker** [comment]
ik zal dit even testen heb dit zelf namelijk nog niet ondervonden zouden er ook logs gestuurd kunnen worden van het voorval

**Comment by niekschoemaker** [comment]
Kan geen repro voor deze bug vinden, als ik met ANWB een heli repareer wordt deze correct in de database geupdate en gerepareerd.
Dit wordt echter pas gedaan wanneer je hem daadwerkelijk terug zet in de garage.

**Comment by niekschoemaker** [comment]
our gefixed moeten zijn
