### ISSUE TITLE
Autos die niet op de 2de hands komen

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#350]
**Omschrijf de bug**
Als je een voertuig op de 2de hands zet en het bedrag is hoger dan +- 300-400k+ komt die niet in de lijst te staan. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Ik zelf heb het juist gedaan. Ik heb een RS6 2020 voor 475k op de 2de hands geplaatst en hij staat er niet tussen. Dit hoor ik van meer mensen met dit probleem. Dan gaat het altijd over hogere bedragen dan 300-400k

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Normaal zou de auto op de 2de hands moeten komen. 

**Screenshots en/of logbestanden**

**Impact op de server**
Dit voorkomt veel tickets van dat mensen hun autos kwijt zijn na het op de 2de hands te plaatsen.

**Comment by niekschoemaker** [comment]
Was een foutje in het sorteren, is ondertussen al gefixed.
