### ISSUE TITLE
Permissies Test Server

### ISSUE THREAD

**Issue by Marius-002** [Tedeapolis/development#351]
**Omschrijf de bug**
Enkele commands die te maken hebben met /time en /weather werken niet helemaal op en top op de test server. Wanneer je deze invoert krijg je linksboven een bericht waarin staat: 'vSync: Error: You are not allowed to use this command.'

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Permissies goed zetten zodat dit weer mogelijk is.

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Bij /time zou de tijd moeten veranderen en bij /weather het weer.

**Screenshots en/of logbestanden**
https://prnt.sc/wzdz30

**Impact op de server**
Normaal niets aangezien dit gewoon aan permissies ligt.

Alvast bedankt! 👍

**Comment by niekschoemaker** [comment]
Deze command werd heel veel gedaan wat nogal irritant is tijdens testen met foto's etc, hierom is dit command volledig uitgeschakelt.
