### ISSUE TITLE
Politie HB Poort Request

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#352]
Hey hooi,
is het mogelijk dat hier:
![image](https://user-images.githubusercontent.com/68959019/104852543-e8c21080-58fb-11eb-804d-45c5c977e025.png)

een slagboom komt? Die wel automatisch open gaat, maar dat het wel "afgesloten" staan. Dan kunnen we aan HB lokaalvredebreuk koppelen. aangezien er heletijd gekloot wordt op HB parkeerplaats.

Verder kan hier deze poort gefixt worden?
![image](https://user-images.githubusercontent.com/68959019/104852616-566e3c80-58fc-11eb-9f46-32cdb5dd4eeb.png)
misschien verder richting de straat plaatsen dat hij helemaal afsluit. aangezien heel veel via hier wegrennen of met motoren naar binnen komen rijden.

**Comment by brothasx** [comment]
Paaltjes geplaatst op het pad richting de parking, vervolgens ook een camera geplaatst aan de poort zodat er daar niet doorgereden kan worden.
