### ISSUE TITLE
HB Prive garage naar nieuwe locatie

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#353]
Kan de parkeergarage's van HB (zie afbeelding 1) naar de parkeerplaats naast HB bij de winkel? (zie afbeelding 2)
We willen hem bij HB sowieso weg eigenlijk als dat kan.

afbeelding 1:
![image](https://user-images.githubusercontent.com/68959019/104852829-5884cb00-58fd-11eb-97e8-2ca8ade06205.png)

afbeelding2:
![image](https://user-images.githubusercontent.com/68959019/104852800-3c812980-58fd-11eb-99c4-0057d2fe7b06.png)

**Comment by brothasx** [comment]
Garage cirkels verplaatst naar de parking rechtover het politiekantoor. ( aangegeven met een garage blip)
