### ISSUE TITLE
Politie pot, reden bij vragen.

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#354]
Is het mogelijk dat als we geld opnemen van de samenleving (politie pot)
![image](https://user-images.githubusercontent.com/68959019/104853078-d695a180-58fe-11eb-9b02-534783588f23.png)

dat er hier bij wordt gevraagd als eerst:
![image](https://user-images.githubusercontent.com/68959019/104853086-eb723500-58fe-11eb-848f-6b9aa75e72b5.png)

en vervolgens de reden gevraagd wordt "waarom" er geld uit de pot gehaald wordt. Zo om alles te regristreren wat er uit de pot gaat en waarom.
dus ongeveer zo:
![image](https://user-images.githubusercontent.com/68959019/104853167-528fe980-58ff-11eb-9708-6d058c6374fa.png)

**Comment by niekschoemaker** [comment]
Oke en dan? Wat moet er dan gebeuren met die reden?

**Comment by DaanDeWit** [comment]
> Oke en dan? Wat moet er dan gebeuren met die reden?

Kan dan misschien dat opgeslagen worden in database? Of maybe een "uitgave overzicht" per mail?
in ieder geval dat het geregristreerd wordt, want heb het idee dat er nogal makkelijk over de pot wordt gedaan van pak ff dit geld

**Comment by niekschoemaker** [comment]
Het enige wat doebaar is is via een Discord bot, dat zou kunnen.

**Comment by Willem-Dekker** [comment]
Waarom moet dit opgelost worden met code en worden er niet gewoon afspraken gemaakt binnen de politie hier over?
