### ISSUE TITLE
Geen dingen in appartementen kunnen opslaan

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#357]
**Omschrijf de bug**
Geen dingen in appartementen kunnen opslaan.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Ik weet niet zeker of het bij andere is, ik kan iniedergeval geen spullen opslaan in mijn appartement. 
Je gaat je appartement in, drukt op "Sla objecten op" en vervolgens gebeurt er niks en krijg ik in mijn console een error.

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Je drukt op "Sla objecten op" en vervolgens zou er een menu moeten openen met opties welke spullen ik wil opslaan in mijn appartement.

**Screenshots en/of logbestanden**
![afbeelding](https://user-images.githubusercontent.com/69365961/105208649-38e1e280-5b49-11eb-9ace-e2379f1aee62.png)

**Impact op de server**
Gezien ik geen andere reports heb gezien, gemiddeld.

**Comment by Willem-Dekker** [comment]
deze is inmiddels op gelost door misstake als ik het goed heb
