### ISSUE TITLE
Alfa Romeo Stelvio Quadrifoglio offroad handling te OP

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#358]
**Omschrijf de bug**
 Alfa Romeo Stelvio Quadrifoglio gaat bijna 300 offroad

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
pak de Alfa Romeo Stelvio Quadrifoglio ga er mee offroad rijden

**Normaal gedrag (Wat zou er normaal moeten gebreuren)**
Geen 300 offroad

**Screenshots en/of logbestanden**
NVT

**Impact op de server**
niet realistish

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn
