### ISSUE TITLE
Kmar BSB Rang

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#359]
**Uitleg feature**
Dit is deels een nieuwe feature maar ook geef ik hier een Issue aan, 

namelijk een tijdje geleden is er bij de KMAR een bsb rang gekomen dat is netzoals bij de politie de DSI rang die werkt allemaal perfect alleen het enigste probleem is dat de schietmeldingen(is mij verteld dat dit zou werken) niet werken op deze Kmar rang dus mijn vraag of daar naar gekeken kan worden. Dan de nieuwe feature zou zijn of de politie meldingen ook richting de Kmar rang kunnen worden gestuurd daar worden namelijk de meeste meldingen over bedreigingen, vuurgevechten etc... in gemaakt

- [x] Schietmeldingen etc naar KMAR BSB
- [x] Voertuigen voor KMAR BSB rang

**Wat lost deze feature op?**
Wat deze feature oplost is dat de KMAR DSI mensen dan net zo goed kunnen handelen in hun eentje of met meerdere zonder dat er perse een politie persoon bij moet zijn, daarnaast dan kunnen ze ook allemaal van de politie rangen af want dan is dat totaal onnodig :D

**Comment by Willem-Dekker** [comment]
all fixed
