### ISSUE TITLE
Prop Emotes fixen

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#361]
**Omschrijf de bug**
op het moment dat je bijvoorbeeld /e brief3 doet is de prop er heel eventjes en daarna verdwijnt.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
doe /e brief3 en ga rondlopen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je zou bij de prop emote's een prop in je handen krijgen en daarmee een animatie zal doen

**Impact op de server**
je haalt een deel roleplay weg zonder die emotes bijvoorbeeld de advocaten zonder koffertje of een feestje zonder champagne glazen

**Comment by Willem-Dekker** [comment]
Hier zijn al een aantal fixes voor gedaan die er morgen in zitten

**Comment by timfloors** [comment]
ja had niek al gevonden als het goed is
