### ISSUE TITLE
(H)Ovj outfit & KMAR OVD-K vest

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#362]
Nog toe te voegen besproken met kenneth in burgerraadoverleg:
- Toevoeging (H)OVJ Outfit zodat deze niet allemaal met hun burgerskleding naar binnen kunnen en onderscheid maken van de politie/kmar

- Toevoeging OVD-K Vest om de burgers duidelijk te maken via de leiding heeft en waar ze voor klachten moeten komen

**Comment by walvisgedaan** [comment]
- OVD-K vest is zojuist gemaakt, daarnaast zijn er wat kleine updates gemaakt aan de EUP voor de Koninklijke Marechaussee.
Dit zal met de grote update van 31 januari gepushed worden.

* Wat bedoel je precies met een (H)OVJ outfit ((hoofd) officier van justitie duuhuu), heb je hier misschien een voorbeeld o.i.d van?

**Comment by walvisgedaan** [comment]
![Uploading unknown (8).png…]()

**Comment by timfloors** [comment]
ah top, dat plaatje kan ik niet zien man

**Comment by walvisgedaan** [comment]
https://prnt.sc/xpn7qg
