### ISSUE TITLE
KMAR Contact Burgerraad 24-1

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#363]
**Beschijf zo duidelijk mogelijk de feature**
Toevoeging KMAR aan de contacten van alle whitelisted-jobs zodat deze ook meldingen makkelijk heen en weer.

**Wat lost deze feature op?**
Mogelijke miscommunicaties voorkomen en de algehele communicatie wat makkelijker maken aangezien niet iedereen weet hoe je de kmar moet bereiken

**Comment by Willem-Dekker** [comment]
done enjoy the spamm
