### ISSUE TITLE
Ambulance & taxi pasjes + on/off-duty aangeven Burgerraad overleg 24-1

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#364]
**Beschijf zo duidelijk mogelijk de feature**
Dienst pasjes voor ambulance en taxi ook aangeven op alle whitelisted jobs of ze in of uit dienst zijn

**Wat lost deze feature op?**
dat als gebieden worden afgezet bijvoorbeeld bij het ziekenhuis dat mensen met een ambu pasje er wel door heen mogen om in dienst te gaan hetzelfde geld voor de taxi dan kunnen ze tonen bij de anwb als ze indienst zijn de de reparatie van hun uber voertuig gratis is

**Comment by Willem-Dekker** [comment]
de passen voor ambu en taxi zijn er alleen als je in dienst bent dus daar hoeft het ook niet op te staan lijkt me

**Comment by timfloors** [comment]
Het idee was om elke overheidsjob in en uit dienst een pasje te laten hebben waar dan ook op staat of ze in of uit dienst zijn want dan kunnen ze bijvoorbeeld bij de ambu in dienst als het ziekenhuis is afgezet, dan laten ze het pasje zien en kunnen ze verder naar binnen voor hun dienst

**Comment by Willem-Dekker** [comment]
done
