### ISSUE TITLE
Mogelijkheid ambulance om props te plaatsen burgersraad 24-1

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#366]
**Beschijf zo duidelijk mogelijk de feature**
Mogelijkheid om de weg voor een deel af te zetten. Door middel van een hek. kleine toevoeging hierop dat bordpijlen soms blijven staan voor mensen etc.. niek krijgt hier een repo van

**Wat lost deze feature op?**
Zodat ze hun voertuig hier niet voor hoeven te gebruiken hiervoor. Ze Hebben het helaas te vaak mee gemaakt dat ze zelf dood gingen hierdoor.

**Comment by Willem-Dekker** [comment]
waar in de uitrusting van een ambu zitten die dingen dan?

**Comment by Willem-Dekker** [comment]
zit er in zag ik
