### ISSUE TITLE
Een tankpas Burgersraad 24-1

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#367]
**Beschijf zo duidelijk mogelijk de feature**
tanken op de kosten van de baas in dienst voor whitelisted jobs, bepaalde models of jobs blacklisten voor tanken, zodat deze niet hoeven te tanken.

**Wat lost deze feature op?**
Dit lost op dat bepaald overheids voertuigen niet hoeven te tanken of te betalen voor te tanken dan kunnen ze sneller en makkelijker op meldingen aankomen

**Comment by Willem-Dekker** [comment]
graag ook de rest van de template in vullen

**Comment by timfloors** [comment]
done

**Comment by Willem-Dekker** [comment]
welke modellen en hoe en wat zou wel handig zijn voor de implementatie

**Comment by timfloors** [comment]
Ik zal dat even overleggen in het kanaal van agenda punten :D

**Comment by Willem-Dekker** [comment]
en?

**Comment by timfloors** [comment]
ik heb het overlegd in het channel, de vraag is eigenlijk om dit toe te voegen op de job dat de baas ervoor betaald.

**Comment by Willem-Dekker** [comment]
dan alleen voor de job auto's geen prive

**Comment by timfloors** [comment]
ja dat klopt, alle jobvoertuigen van de jobs, de dsi kan zelf wel betalen die verdienen genoeg

**Comment by timfloors** [comment]
Kreeg een voorbeeld vanuit de anw,

Ze willen het zo dat als jij in dienst in een anwb voertuig rijd dat als jij dan gaat tanken dat de kosten van de pot af gaan. Dat de baas betaald zegmaar
