### ISSUE TITLE
Wapen en attachments prijzen + meer attachments voor wapens burgersraad 24-1

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#368]
Niek gaat hiernaar kijken. Er zal gekeken worden naar een percentage van de nieuwprijs van een wapen, zodat dit de uiteindelijke prijs wordt van een attachment. 

daarnaast voor meer attachments mogelijke toevoeging van mk-II Ak

**Comment by Willem-Dekker** [comment]
Zit er al in wat ik zie
