### ISSUE TITLE
burgers-Advocaten pas zonder dat je advocaat bent, burgersraad 24-1

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#369]
**Beschijf zo duidelijk mogelijk de feature**
Mogelijkheid dat mensen zonder advocaten rang ook een burgersadvocaten pasje kunnen krijgen zo kun je goedkopere en meer advocaten beschikbaar hebben

**Wat lost deze feature op?**
Dan kan er weer toegevoegd worden dat mensen met een VOG en een opleidingscursus ook advocaat kunnen spelen zonder dat ze hun ingame rang advocaat moeten hebben

**Comment by Willem-Dekker** [comment]
hier ben ik op tegen je ondermijnd heel justitie hier mee

**Comment by timfloors** [comment]
dit word dan toegevoegd vanuit het justitie dat hun de mogelijkheid hebben om dit uit te delen/te geven met een toets/cursus eraan vast. ik heb het niet bedacht puur in een githubissue gezet :D

**Comment by Willem-Dekker** [comment]
wat we dan eigenlijk gaan doen is terug naar het oude systeem, terwijl er signalen zijn vanuit justitie zijn dat er niet genoeg werk is. Waarom zouden we dan nog minder werk voor ze maken?
