### ISSUE TITLE
Verandering winkelovervallen, Besproken staffoverleg 24-1-2021

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#371]
**Beschrijf zo duidelijk mogelijk de feature**
De manier van overvallen van winkels veranderen met niet 1 cirkel maar 2 cirkels, 1 voor in de winkel achter de kassa en 1 achter bij de kluis

Cirkel 1: 15sec tot 60sec mee bezig om de kassa te openen en dan hier 1 tot 5k zwart-geld uit krijgen, te openen met een lockpick
Cirkel 2: 1 tot 3min mee bezig om te openen hier 20 tot 50k zwart-geld uit halen te openen met een crowbar

mogelijk implementatie script: https://www.fivem-store.com/product/store-robbery-v1/

**Wat lost deze feature op?**
dit maakt een winkeloverval iets meer toegankelijk voor beginners en zorgt ervoor dat er mogelijk meer RP hierin plaats vind zo kunnen mensen er voor kiezen om mogelijk te moeten gaan onderhandelen of ervoor kiezen om een klein deel te pakken en dan snel ervandoor te gaan(wat of een lange RP creërt of een achtervolging als de agenten op tijd zijn), dit voegt dan ook een deel realisme toe aangezien je in het echt ook niet perse gaat wachten tot agenten er zijn.

daarnaast ga je hiermee aanpassen dat omdat het iets makkelijker toegankelijk dat het vaker gaat gedaan worden dit creërt dan weer iets meer voor de agenten om te doen

**Comment by nickvmeurs** [comment]
mn-storerobbery is hier een mooi script van! Met features zoals:
- 0.01MS
- Lockpick elke kassa
- alle kluizen overvalbaar doormiddel van kluiscode die ja kan krijgen bij een kassa (met een beetje geluk)
- Anti hacker systeem ingebouwd

Deze is gratis door hem gereleased en is te downloaden op https://cdn.discordapp.com/attachments/880731661556400128/883477533310472293/mn-storerobbery.rar

**Comment by Chang-nl** [comment]
Als hier een publieke release van is wil ik er best naar kijken.

**Comment by nickvmeurs** [comment]
> Als hier een publieke release van is wil ik er best naar kijken.

Ik heb je een PM erover gestuurd

**Comment by Chang-nl** [comment]
Na herstart zit zijn de winkelovervallen aangepast!
