### ISSUE TITLE
Claimen van refunds werkt niet

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#375]
**Omschrijf de bug**
Het is momenteel voor spelers niet mogelijk om refunds te claimen die door staffleden zijn uitgeschreven. Op het moment dat ze /claimrefund typen gebeurt er niets, terwijl de refunds wel al goedgekeurd zijn. Als ze /checkrefunds doen, dan krijgen ze wel te zien dat er een refund klaarstaat. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Geef een willekeurige refund aan een speler en/of stafflid en keur deze goed. Vraag de speler om /checkrefunds te typen. Vraag de speler vervolgens om /claimrefund te typen en kijk of er iets wordt toegevoegd. 

(Ik heb dit zelf getest met een speler door een refund van 1 euro te geven, maar dit werkte ook niet). 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou het item dat toegevoegd is aan de refund aan de desbetreffende speler gegeven moeten worden. 

**Screenshots en/of logbestanden**
https://cdn.discordapp.com/attachments/728333565548429318/802884045272383508/unknown.png

**Impact op de server**
Middelmatige impact, spelers kunnen hun refunds niet claimen die door staffleden zijn gegeven en dit kan frustrerend zijn.

**Comment by niekschoemaker** [comment]
Issue zou morgen gefixed moeten zijn, zo niet even issue heropenen.
