### ISSUE TITLE
Locks / sloten van de auto's zijn stuk

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#376]
**Omschrijf de bug**
De locks, esx_vehiclelocks doen het momenteel niet. Het zorgt voor ontzettend veel chaos in de stad met reports. Er staan nu dus ook bizar veel auto's of op slot of niet op slot.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak een auto en ga een beetje met je lock spelen, dus u spammen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De auto's zouden gewoon fluency moeten werken zonder enkele issues

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/73707925/105816124-31d92b00-5fb4-11eb-8931-ad84b9f6506b.png)
Geen gekke dingen opgevallen.

**Impact op de server**
Groot, de spelers kunnen op dit moment niet echt spelen.

**Comment by Willem-Dekker** [comment]
fixed
