### ISSUE TITLE
Facturen ambulance

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#377]
**Omschrijf de bug**
de ambulance kan geen facturen meer sturen met hun f6 menu

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
jezelf op ambu zetten en het uitproberen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
persoon dichtst bij jou zou een factuur moeten krijgen

**Screenshots en/of logbestanden**
https://clips.twitch.tv/BelovedFrozenSheepSSSsss

**Impact op de server**
ambu kan hun rp niet goed afronden

**Comment by Willem-Dekker** [comment]
is dit nog een issue? heb er namelijk niks meer over gehoord

**Comment by timfloors** [comment]
als het goed is was het al opgelost dus bij deze kun je hem sluiten
