### ISSUE TITLE
Toevoeging van /docu sjabloon

### ISSUE THREAD

**Issue by marvinh85** [Tedeapolis/development#378]
**Beschrijf zo duidelijk mogelijk de feature**
Na aanleiding van de nieuwe wetgeving omtrent schadevergoedingen is het handig om een sjabloon te hebben in /docu.
Zodoende hebben we vaste velden en teksten die we kunnen gebruiken. Zie het voorgestelde sjabloon in de bijlage

**Wat lost deze feature op?**
Snelheid voor het aanmaken van het schadevergoeding document en een uniforme manier van werken.
[Schadevergoeding.document.pdf](https://github.com/Tedeapolis/development/files/5879529/Schadevergoeding.document.pdf)

**Comment by dilyano** [comment]
zit nu in master. na een nieuwe deployment/herstart is hij beschikbaar
