### ISSUE TITLE
Door muur rijden

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#379]
**Omschrijf de bug**
Je kunt op deze locatie (sustancia road) door een muur heen rijden en je auto ongelimiteerd laten repareren na een citybug fall.
![image](https://user-images.githubusercontent.com/73707925/106000644-57972a80-60af-11eb-8398-0c47a69fbaff.png)

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak een auto en rij door de muur heen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Solid wall, dus vehicle failure

**Screenshots en/of logbestanden**
https://youtu.be/RVMqZMph1Ag

**Impact op de server**
Zeer redelijk, vrijwel niemand weet dit, maar er moet wel een solid object geplaatst worden.

**Comment by niekschoemaker** [comment]
Ik heb de deur in kwestie op slot gedaan en je kunt daar dus niet meer naar binnen, that should fix it denk ik
