### ISSUE TITLE
DNA Systeem

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#380]
**Omschrijf de bug**
Opslaan van DNA.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
DNA afnemen van een persoon en vervolgens het uploaden van de DNA op verdieping -2 in het politie bureau.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaliter zal het DNA worden opgeslagen.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/49393071/106181624-1f224a00-619e-11eb-96eb-1bc0080fb46b.png)

**Impact op de server**
Geen impact.

**Comment by Willem-Dekker** [comment]
is dit nog een issue?

**Comment by MartijnMeister** [comment]
> is dit nog een issue?

Naar mijn weten werkt het DNA systeem tot op heden nog niet

**Comment by niekschoemaker** [comment]
Is gefixed
