### ISSUE TITLE
Dingen vergeten in update vanacht

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#381]
**Omschrijf de bug**
Is geen bug, over het hoofd gekeken bij update

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
n.v.t

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
n.v.t.

**Screenshots en/of logbestanden**
n.v.t.

**Impact op de server**
Middel tot groot

-- 
 - Grote boot kan maar 1 liter benzine
 - Kleine boot an maar 6 liter benzine
 - Boten verwijderen in cirkel kan niet
 - Kustwacht Helikopter kan pas gepakt worden door BSB. Moet vanaf opperwachtmeester zijn
 - Kustwacht Helikopter moet toegevoegd worden aan de camera plugin

**Comment by niekschoemaker** [comment]
Wat is de spawnnaam van de kustwacht heli?

**Comment by walvisgedaan** [comment]
MH60T

**Comment by Willem-Dekker** [comment]
ga er van uit dat dit gefixed is zo niet graag heropenen
