### ISSUE TITLE
[EUP - interiors - retextures] visser verkoop verplaatsen of extra verkoop toevoegen

### ISSUE THREAD

**Issue by ZoiH** [Tedeapolis/development#382]
# Waar zit het in EUP, interiors of retextures ?
visser job
# Link naar issue of coördinaten naar de plek

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
te veel drukte
# Wat is de toegevoegde waarde?
minder drukte en chaos waardoor eht aantal reports omtrent dit kan worden verminderd

**Comment by Willem-Dekker** [comment]
dit is enhancement

**Comment by Willem-Dekker** [comment]
zit er in naar de restart
