### ISSUE TITLE
Nieuwe boten maar 1 tot 10 liter benzine, Avisa(de nieuwe onderzeeër bekijken)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#383]
**Omschrijf de bug**
De nieuwe boten die erin zijn gedaan volgensmij ook de kmar boot hebben allemaal maar 1 tot 10 liter benzine opslag het lijkt me dat dit niet helemaal goed is gegaan. De avisa onderzeeër kost 2.5miljoen maar gaat maar 30km/u en heeft 40kg opslag naar mijn mening is dit ook niet helemaal balanced misschien kan hier naar gekeken worden eerder iets van 50km/u en 300/400kg opslag

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een nieuwe boot pakken bijvoorbeeld de longfin en gaan rondvaren en hem dan vullen dan zie je dat er maar 10liter in kan

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
een normale hoeveelheid iets van 60/80liter

**Impact op de server**
de nieuwe boten worden niet gekocht of er komen veel klachten over ze. de avisa of andere onderzeeër zal nooit gekocht woorden door criminelen aangezien je er niks aan hebt als crimineel zijnde

**Comment by Willem-Dekker** [comment]
is dit nog een isseu?

**Comment by timfloors** [comment]
is fixed
