### ISSUE TITLE
verplaatsen aantal zwembad verschoon locaties

### ISSUE THREAD

**Issue by ZoiH** [Tedeapolis/development#385]
# Waar zit het in EUP, interiors of retextures ?
![image](https://user-images.githubusercontent.com/75584462/106499468-ec8b9080-64c0-11eb-9f0c-0b799ddd08cb.png)
![image](https://user-images.githubusercontent.com/75584462/106499485-f2817180-64c0-11eb-8c9f-03dd932c6fd2.png)
beide van deze locaties 
# Link naar issue of coördinaten naar de plek
x:-1775;Y:437;Z:125 en X:2390;Y:4840;Z:41
# Zitten er fouten in? zo ja graag beschrijven en een screenshots

# Wat is de toegevoegde waarde?
Zorgt voor veel conflictjes onderling

**Comment by niekschoemaker** [comment]
issue is opgelost.
