### ISSUE TITLE
Armed/Unarmed Humvee

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#387]
**Omschrijf de bug**
Armed/Unarmed Humvee zitten niet in DSI garage.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Zet jezelf op 'police 12' en kijk in de garage

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Armed/Unarmed Humvee zouden daar moeten staan.

**Screenshots en/of logbestanden**
n.v.t.

**Impact op de server**
Middel tot groot

**Comment by Willem-Dekker** [comment]
Wat is de spawn naam?
