### ISSUE TITLE
[EUP - interiors - retextures]

### ISSUE THREAD

**Issue by Daanwith** [Tedeapolis/development#388]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Link naar issue of coördinaten naar de plek
-
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
![dsdfsdf](https://user-images.githubusercontent.com/78437310/106637566-27ee9380-6583-11eb-904a-e11b0ffe5728.PNG)
![Knipsel](https://user-images.githubusercontent.com/78437310/106637578-2c1ab100-6583-11eb-9639-fadd520686e9.PNG)

# Wat is de toegevoegde waarde?
Ik zal graag het HRB pakje in eup willen hebben indien mogelijk. We gebruiken dit pakje nu al een aantal maanden maar zit er nog niet in. Om telkens naar een appartement te gaan is vervelend. En kunnen hierdoor niet snel in dienst.

**Comment by walvisgedaan** [comment]
Gedaan, zit er na de restart in + keuze uit normaal/been holster
