### ISSUE TITLE
EUP voor Recherche niet functionerend

### ISSUE THREAD

**Issue by Smikkelbakkie** [Tedeapolis/development#389]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Link naar issue of coördinaten naar de plek
n.v.t.
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Voor de personen met de rang **Recherche Leiding** is het niet mogelijk om bepaalde onderdelen van het EUP systeem te zien, zie hiervoor de bijgevoegde screenshots:
![image](https://user-images.githubusercontent.com/50171172/106665516-add00600-65a6-11eb-90ae-ee5a325dde67.png)
![image](https://user-images.githubusercontent.com/50171172/106665533-b294ba00-65a6-11eb-99a8-d97b581dde0f.png)

# Wat is de toegevoegde waarde?
Momenteel is het voor ons niet mogelijk om de _(nieuwe)_ t-shirts van de politie te gebruiken, en kunnen wij onder de kop **Recherche** niet de handschoenen en het masker gebruiken gezien deze er niet tussen staan.

**Comment by Smikkelbakkie** [comment]
Update: dit geldt voor **ALLE** recherche rangen, tevens is de recherchejas ook niet beschikbaar voor vrouwen.

**Comment by walvisgedaan** [comment]
Als het goed is zou dit al een tijd geleden gefixt moeten zijn?

**Comment by Smikkelbakkie** [comment]
Ik had graag willen zeggen dat het zo is, helaas is het tot op de dag van vandaag nog niet gefixt helaas.

**Comment by Willem-Dekker** [comment]
Ik heb net een aanpassing gedaan dit zou morgen moeten werken

**Comment by Smikkelbakkie** [comment]
> Ik heb net een aanpassing gedaan dit zou morgen moeten werken

Helaas niet, ook niet na het nogmaals in- en uitdienst gaan

**Comment by Willem-Dekker** [comment]
dan zie ik zo niet waar het mis gaat

**Comment by Willem-Dekker** [comment]
fixed

**Comment by Smikkelbakkie** [comment]
Ik weet niet of dit nog gelezen gaat worden @Willem-Dekker , het **recherche eup** gedeelte is gelukkig werkend. Thanks! Echter is de **politie eup** nog niet werkend, als in we kunnen de nieuwe t-shirts met de rangen helaas nog steeds niet gebruiken.

**Comment by Willem-Dekker** [comment]
dan graag een nieuw issue aan maken met duidelijke info een repro en alle andere verplichte velden
