### ISSUE TITLE
[EUP - interiors - retextures]

### ISSUE THREAD

**Issue by Tommetjeh** [Tedeapolis/development#390]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Link naar issue of coördinaten naar de plek
/
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
OvD-P vest groener maken zodat deze beter te onderscheiden is van Team Verkeer
# Wat is de toegevoegde waarde?
Beter en sneller overzicht wie OvD is bij een groot incident

**Comment by Willem-Dekker** [comment]
Graag format goed in vullen
