### ISSUE TITLE
vrouwelijk staff vestje (mocht van kennuth)

### ISSUE THREAD

**Issue by ZoiH** [Tedeapolis/development#391]
# Waar zit het in EUP, interiors of retextures ?
geen staff vestje
# Link naar issue of coördinaten naar de plek

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
hij is er niet dat is het probleem
# Wat is de toegevoegde waarde?
dat mensen me instant als staff zien en ik niet moet gaan schreeuwen om iets duidelijk te maken

**Comment by walvisgedaan** [comment]
Hoi Zoe,

Kun jij mij een screenshot (met nummer) sturen van de body voor het vestje?

Groetjes,
Whaledone

**Comment by walvisgedaan** [comment]
Geen reactie
