### ISSUE TITLE
Kmar heli en kmar boot

### ISSUE THREAD

**Issue by BillyMaes** [Tedeapolis/development#392]
**Omschrijf de bug**
momenteel kunnen enkel mensen die op de BSB rang staan de KMar heli nemen. we kunnen ook de helicopter niet terug in de opslag plaatsen in de rode cirkel
de boten kunnen we niet inleveren in de rode cirkel

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door het te veranderen? xD

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
we zouden heel graag hebben dat deze toegankelijk word vanaf de 3de rang dus wachtmeester
als je op de E spier drukt gaan de blauw lichten aan en wil hij hem niet terug opslaan in de opslag
**Screenshots en/of logbestanden**
/

**Impact op de server**
/

**Comment by niekschoemaker** [comment]
Oke ik snap hier dus echt niks van, het gaat er dus om dat helikopters niet toegankelijk zijn?
En opeens begin je ook over blauwe lichten ergens op?
Welke specifieke heli's moet ik nou aan welke rangen geven?
