### ISSUE TITLE
Buschauffeurs job werkt niet

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#393]
**Omschrijf de bug**
Bij het starten van de buschauffeursbaan werkt het prima om een bus te pakken, het vervolgens naar een
halte toe rijden en toeteren om de halte te activeren, werkt alleen niet. Ik heb geen idee of het een andere keybind 
ofzo is tegenwoordig maar het is onduidelijk en mensen gaan er vanuit dat het niet werkt. Daarnaast gaat
het vaak niet goed met het wegzetten van de bus, je krijgt geen optie om op E te drukken bij het wegzetten.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je merkt het eigenlijk gelijk wel wanneer je met een bus de eerste halte die je tegenkomt probeert te activeren.
Daarnaast werkt het meestal (soms wel)  niet om de bus weer weg te zetten. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je stapt in een bus, rijdt naar de eerste aangegeven halte op de kaart en drukt op de toeterknop (E)  terwijl je in de cirkel staat
om de halte als bereikt te markeren en geld te krijgen. 

**Screenshots en/of logbestanden**
Voertuig pakken 
![image](https://user-images.githubusercontent.com/56109953/107115191-2666e900-686b-11eb-84c4-ae4e09c9b17d.png)

Voertuig proberen weg te zetten
![image](https://user-images.githubusercontent.com/56109953/107115194-2a930680-686b-11eb-8e79-d91a33d3a679.png)

Proberen te activeren van een bushalte cirkel (ook naartoe gereden ondertussen dus kan ook daarvan zijn).

**Impact op de server**
![image](https://user-images.githubusercontent.com/56109953/107115197-31ba1480-686b-11eb-9098-bd689738220f.png)

**Comment by niekschoemaker** [comment]
Issue is opgelost
