### ISSUE TITLE
Jerrycan en andere toebehoren zaklamp etc verdwijnen [burgerraad]

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#394]
**Omschrijf de bug**
Jerrycan en andere toebehoren zaklamp etc verdwijnen na relog / knipperen, (mogelijk wel gefixt)

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een zaklamp of jerrycan pakken en dan reloggen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
hij zou in je inventory moeten blijven

**Screenshots en/of logbestanden**
-

**Impact op de server**
redelijkeimpact aangezien mensen dan heletijd alles opnieuw moeten kopen

**Comment by niekschoemaker** [comment]
Geen flauw idee of deze issue nog bestaat, kan hem zelf niet replicaten, heb een week terug wel een keer een delay toegevoegd voor de loadout check dus kan zijn dat het hiermee gefixed is.
