### ISSUE TITLE
Overheidsvoertuigen worden automatisch gerepaired [burgerraad]

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#395]
**Omschrijf de bug**
sommige overheidsvoertuigen krijgen geen schade, of als deze kapot is kun je van bestuurder wisselen en wordt de auto gerepareerd

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een overheidsvoertuig pakken zoals een ambu of anwb busje ergens tegenaan rijden en dan switchen van bestuurder

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
voertuig zou de damage moeten behouden

**Screenshots en/of logbestanden**
-

**Impact op de server**
redelijke impact aangezien dit soms gezien of vaak ongezien word gebruikt waar gewoon een ban op staat

**Comment by Willem-Dekker** [comment]
is als het goed is gemaakt zo niet heropenen
