### ISSUE TITLE
Verhogen van boetes voor verkeersovertredingen

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#396]
**Beschrijf zo duidelijk mogelijk de feature**
Tijdens het staffoverleg is besproken dat alle boetes die in de categorie 'verkeersovertredingen' staan verdriedubbeld moeten worden. Alle boetes moeten dus x 3. Hierbij zal bijvoorbeeld fout parkeren wel hetzelfde blijven.  

**Wat lost deze feature op?**
Roekeloos, idioot rijgedrag op en rond Blokkenpark.

**Comment by niekschoemaker** [comment]
Ik heb ze aangepast, zou na volgende herstart actief moeten zijn.

**Comment by Willem-Dekker** [comment]
is dit ook aangepast op de in de kosten pagina?
