### ISSUE TITLE
Bug met rij ontzegging

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#397]
**Omschrijf de bug**
Sinds het nieuwe systeem waar mensen 24 uur moeten wachten voordat ze opnieuw hun rijbewijs kunnen aanvragen zit een bug. Nadat een rijbewijs is ingevorderd is deze nog steeds in het bezit van desbetreffend persoon (zowel in-game op het rijbewijs als in meos). 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Neem de politierang en ontneem hiermee het rijbewijs van een willekeurig persoon. Laat de persoon zijn rijbewijs aan jou geven en check of hierop desbetreffend rijbewijs nog zichtbaar is. Hierna kan er op het meos profiel gekeken worden waar dit rijbewijs ook nog zichtbaar is.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Zodra een rijbewijs ingevorderd is zou persoon deze zowel in-game als in meos kwijt moeten zijn.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Middel - Voor agenten kan het nu voorkomen dat een persoon wel een rijbewijs in bezit heeft terwijl ze dit oorspronkelijk niet hebben. Dit kan miscommunicatie veroorzaken en tevens is dit tamelijk vervelend voor het korps in het algemeen.

**Comment by niekschoemaker** [comment]
Op beiden meosen is dit gefixed voor in game kan ik niks vinden wat dit kan veroorzaken, heb wel wat kleine aanpassingen gedaan dus kan zijn dat dit ook gefixed is.
Zou je even moeten na controleren.

**Comment by Willem-Dekker** [comment]
@timfloors is dit nu nog een issue?

**Comment by Willem-Dekker** [comment]
gezien geen reactie ga ik er van uit dat dit geen issue is meer
