### ISSUE TITLE
Vaarbewijs kun je niet kopen

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#398]
**Omschrijf de bug**
Je kunt het vaarbewijs niet kopen. Als je op enter klikt gebeurt er niets.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Ga naar de haven en koop hem.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Zou in bezit moeten komen en dat je boten kunt bekijken en kopen.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Middelmatig, mensen willen graag een vaarbewijs kopen (hot topic afgelopen dagen)

**Comment by niekschoemaker** [comment]
Issue is na volgende herstart opgelost
