### ISSUE TITLE
Tolpas kun je niet kopen

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#399]
**Omschrijf de bug**
Je kunt de tolpas niet kopen bij het gemeentehuis

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Ga naar het gemeentehuis en probeer hem te kopen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Zou je in bezit moeten krijgen.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Klein, er zijn weinig mensen die de tolpas willen kopen, maar toch heeft het invloed.

**Comment by niekschoemaker** [comment]
Issue is opgelost na volgende herstart
