### ISSUE TITLE
apart slot voor koferbak

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#4]
# Suggestienummer: 587
een knop (bijvoorbeeld Shift+U) waardoor alleen de kofferbak van een voertuig open gaat, maar de portieren gesloten. Zo kun je tenminste een beetje fatsoenlijk laden-lossen zonder dat een of andere clown er met je auto vandoor gaat. Zou ook handig zijn voor ambu en politie.

**Comment by niekschoemaker** [comment]
Deze key kan gebined worden onder INput instellingen en dan keybinds van FiveM
