### ISSUE TITLE
KMAR Bevoegdheden

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#40]
Aspirant-Wachtmeester: 
- [x] Touran
- [x] Amarok
- [ ] T5
- [x] Combat Pistol
- [x] Tazer
- [x] Nightstick
- [x] Flashlight

Surveillant-Wachtmeester:
- [x] Touran
- [x] Amarok
- [x] Audi A6
- [ ] Motoren
- [ ] T5
- [x] Combat Pistol
- [x] Tazer
- [x] Nightstick
- [x] Flashlight

Opperwachtmeester:
- [x] Touran
- [x] Amarok
- [ ] T5
- [ ] Audi A6
- [ ] Motoren
- [ ] VW Arteon
- [ ] Audi Q8 (Indien HRB gespecialiseerd)
- [x] COmbat Pistol
- [x] SMG (Indien HRB gespecialiseerd, Attachments: Flashlight)
- [x] Tazer
- [x] Nightstick
- [x] Flashlight

Kapitein+: 
- [ ] Toegang tot alles

**Comment by Willem-Dekker** [comment]
ik heb aangegeven wat nu aan staat

**Comment by Willem-Dekker** [comment]
T5 zal er niet in komen model is naar de kloten

**Comment by Willem-Dekker** [comment]
amarok staan u aan en kan gebruikt worden
