### ISSUE TITLE
Lightbars enhancement

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#400]
**Beschrijf zo duidelijk mogelijk de feature**
De lightbars van de DSI, BSB en recherche verbeteren op de volgende manier:

- [ ] De lightbars showen pas wanneer je op Q drukt, indien dit niet kan dan alleen met de pit (blue dome light), want je probeert unmarked te blijven wanneer je wil. De pit zet je in het echt op het dak en haal je er af, nu moet dit d.m.v. een command maar zal ontzettend fijn zijn als die pas showed wanneer je op Q drukt, dus de lightbars aanzet.
![image](https://user-images.githubusercontent.com/73707925/107226845-ef373a00-6a1a-11eb-8662-8c343556c156.png)
- [ ] De small stick light (rood en blauw 2-reeks) naar blauw blauw maken, zie onderstaande screenshot
![image](https://user-images.githubusercontent.com/73707925/107226828-ea728600-6a1a-11eb-964e-0408e6c80c20.png)

**Wat lost deze feature op?**
Redelijk veel, onder andere het blowen van een cover en eventuele vorm van powergaming voorkomen om de lightbars te zien door ruiten o.i.d.

**Comment by niekschoemaker** [comment]
How about handmatig je lightbars weghalen?

**Comment by ToniGain** [comment]
> How about handmatig je lightbars weghalen en weer terugzetten?

Dat zei ik al, dat is gewoon alsnog niet chill. Je wil gewoon zonder zo'n ding op het dak rijden en als je ergens heen moet ga je niet nog snel allemaal cmds typen en eventueel in clipboard houden, vandaar ook als 'enhancement' 🙂 het zal gewoon veel verbeteren naar mijn mening

**Comment by Willem-Dekker** [comment]
Na overleg met Nander is besloten dat deze feature niet gemaakt gaat worden.
