### ISSUE TITLE
Crash bij pakken van politie/kmar boot

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#401]
**Omschrijf de bug**
Als je bij de helipads als kmar een kmar boot probeert te pakken crashed je game instant

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
jezelf op een kmar rang zetten en dan een boot van de kmar proberen te pakken

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je zou een boot moeten krijgen

**Screenshots en/of logbestanden**
https://we.tl/t-v7cEfl7GMO

**Impact op de server**
groot aangezien de boten nu niet kunnen gebruikt worden

**Comment by niekschoemaker** [comment]
Deze issue is morgen gefixed.
