### ISSUE TITLE
HRB pakje ook toevoegen aan officier- en HRB rangen

### ISSUE THREAD

**Issue by Daanwith** [Tedeapolis/development#403]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Link naar issue of coördinaten naar de plek

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Hrb pakje is onlangs toegevoegd. Je kan dit pakje nu alleen pakken bij kader rangen en dit moet naar
**Luitenant 
Kapitein 
Majoor 
HRB
Kolonel
Generaal majoor
luitenant generaal**
# Wat is de toegevoegde waarde?
We kunnen het pakje als HRB nu niet gebruiken en willen dit wel graag gebruiken in onze diensten

**Comment by Willem-Dekker** [comment]
fixed voor morgen
