### ISSUE TITLE
Mensen kunnen nog steeds geen vaarbewijs kopen

### ISSUE THREAD

**Issue by YassirEy** [Tedeapolis/development#404]
Omschrijf de bug
Je kunt geen vaarbewijs kopen, er gebeurd niks als je in de cirkel staat en op kopen drukt.

Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)
Naar de haven gaan en een vaarbewijs proberen te kopen.

Normaal gedrag (Wat zou er normaal moeten gebeuren)
Je zou een vaarbewijs moeten kunnen kopen.

Screenshots en/of logbestanden
-

Impact op de server
Normaal, er zijn best wat mensen die een vaarbewijs willen kopen.

**Comment by Willem-Dekker** [comment]
fixed
