### ISSUE TITLE
Niet uit een dodo kunnen stappen op het water

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#405]
Omschrijf de bug
Al landt je momenteel met een dodo (watervliegtuig) op het water klappen de wieltjes automatisch in. Doordat de wieltjes op het water dus ingeklapt zijn denkt het vliegtuig / de server dat het vliegtuig nog in de lucht is waardoor je je gordel niet kan afdoen en vervolgens ook niet kan uitstappen.

Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)
Pak een dodo (watervliegtuig) en landt hiermee op het water. Probeer uit te stappen en je zult zien wat er wordt bedoelt.

Normaal gedrag (Wat zou er normaal moeten gebeuren)
Normaal gesproken zouden de wieltjes ingeklapt zijn zodra je op het water bent geland. Maar zou je hierna wel nog moeten kunnen uitstappen.

Screenshots en/of logbestanden

Impact op de server
Klein - Enkel vervelend voor mensen die graag met een dodo op het water landen.

**Comment by niekschoemaker** [comment]
Deze issue is nu gefixed
