### ISSUE TITLE
Ferrari Pista Spider livery 

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#406]
**Omschrijf de bug**
De Ferrari Pista Spider heeft een single color: white.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak de auto ga naar een modshop en probeer hem te kleuren.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Een andere kleur te geven.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/73707925/107623671-fa2bdd80-6c59-11eb-97eb-627994a71d23.png)

**Impact op de server**
Middel tot groot, veel mensen hebben deze auto en willen een kleur er op. Komen meerdere reports van binnen.

De default livery is opaque wit en moet doorzichtig gemaakt worden

**Comment by niekschoemaker** [comment]
Ooit dacht ik al dat ik dit alpha had gemaakt maar blijkbaar heb ik de default livery weer eens volledig wit gemaakt, ik zal even alpha toevoegen en de kleur zelf verwijderen, dan zou het morgen gefixed moeten zijn.

**Comment by niekschoemaker** [comment]
Deze issue is morgen gefixed.

Als dit niet het geval is gelieve even de eissue te reopenen.
