### ISSUE TITLE
Voertuig inleveren op het eiland teleporteerd je naar de airstrip

### ISSUE THREAD

**Issue by dilyano** [Tedeapolis/development#407]
**Omschrijf de bug**
Wanneer je op het eiland een voertuig terugzet in een cirkel, wordt je geteleporteerd naar de airstrip op het eiland.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak een voertuig en rij ermee naar de garage halverwege het eiland. Wanneer je hem daarin zet, zul je binnen 2 secone op de airstrip staan.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je komt te staan op de plek waar je je voertuig inlevert

**Screenshots en/of logbestanden**
n.v.t.

**Impact op de server**
los van frustratie bij mensen is er geen grote impact

**Comment by StoffigKontje** [comment]
Fixed! -dabt in lua-
