### ISSUE TITLE
Extra rang Recherche

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#408]
**Beschrijf zo duidelijk mogelijk de feature**
Er moet een copy worden gemaakt van de rang Recherche Junior en die moet dan Recherche genoemd worden. Het loon zal moeten staan op 1150.

**Wat lost deze feature op?**
Boze recherche leden :)

**Comment by StoffigKontje** [comment]
Na de restart zit het erin. Police rank 19
