### ISSUE TITLE
Lightbars koppelen aan jobcheck

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#409]
**Beschrijf zo duidelijk mogelijk de feature**
een jobcheck koppelen aan de voertuigen zodat je zonder lightbars geen boetes vangt als recherche zijnde.

**Wat lost deze feature op?**
Dat neventaken van de politie boetes vangen tijdens bijvoorbeeld een achtervolging of recherche werk

**Comment by TDA-SanderD** [comment]
Dit is inmiddels al gedaan,. Kun jij hem sluiten @DaanDeWit?
