### ISSUE TITLE
EUP fout DSI rangen

### ISSUE THREAD

**Issue by levisps** [Tedeapolis/development#411]
# Waar zit het in EUP, interiors of retextures ?
Het probleem zit onder het kopje: Dienst Speciale Interventies en Uniform

# Link naar issue of coördinaten naar de plek
Nvt

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
![CD9FD252-A5F9-4AA1-AE2E-775092C9C13A](https://user-images.githubusercontent.com/79063801/107891172-2fb41d80-6f1d-11eb-8e18-63b7e58ce852.png)
Zie fotos, dit is het beperkte zicht wat je hebt als je in dienst de stad in komt, je krijgt je volledige eup pas te zien als je uit en in dienst gaat, dan komt je insignia outfit ook tevoorschijn.

# Wat is de toegevoegde waarde?
Als het weer werkt hoef je niet als je inlogd uit en in dienst te gaan om je werkzaamheden te kunnen uitvoeren. Of als je een crash hebt kun je geen dsi outfit aandoen.
![B409755F-69A9-47B4-8FB1-23DFEA97A29D](https://user-images.githubusercontent.com/79063801/107891169-2e82f080-6f1d-11eb-9098-03772a36d05c.png)

**Comment by Willem-Dekker** [comment]
zie #419 voor meer info

**Comment by walvisgedaan** [comment]
Uit-dienst dus als je uitlogt. Niek had hier al naar gekeken en kan geen issue vinden
