### ISSUE TITLE
Mogelijkheid BSB om eup buiten dienst te gebruiken

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#412]
**Beschrijf zo duidelijk mogelijk de feature**
De mogelijkheid htoevoegen dat de rang bsb van de kmar ook toegang krijgt tot hun EUP buiten dienst.

**Wat lost deze feature op?**
De AOT(DSI kant politie) heeft buiten dienst toegang tot hun omdat ze dan kunnen reageren op meldingen zonder perse helemaal naar politie bureau te gaan, dit geld eigenlijk ook hetzelfde voor de BSB(DSI kant Kmar).

**Comment by walvisgedaan** [comment]
Is geen enhancement maar een eup ding

**Comment by Willem-Dekker** [comment]
dit zat er volgens mij al in

**Comment by timfloors** [comment]
naar mijn weten niet

**Comment by timfloors** [comment]
ik sluit deze aangezien alles daar in 1 lijstje staat :D
