### ISSUE TITLE
BSB kmar aanpassingen

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#413]
**Beschrijf zo duidelijk mogelijk de feature**

1. toevoeging dat de BSB rang kmar /comserv kan gebruiken
2. toevoeging dat de BSB rang kmar Overval meldingen ook krijgt te zien
3. toevoeging dat de BSB rang kmar hetzelfde indienst/uitdienst loon krijgt als de DSI rangen bij de politie

**Wat lost deze feature op?**
1. Dit zou toegevoegd moeten worden omdat ze als DSI vaak hun eigen zaken af moeten handelen en soms komt het wel voorbij dat ze taakstraffen uit moeten delen.
2. Op het moment dat er alleen maar kmar kant DSI is weten hun niet wanneer er overvallen gebeuren dit zou toegevoegd kunnen worden om hun werkwijze te versnellen en fouten te voorkomen
3. Op het moment verdienen ze ruim minder dan de politie rangen en uit dienst nog veel minder dit zou veranderd kunnen worden om het eerlijk te maken tegenover hun

**Comment by Willem-Dekker** [comment]
2. zou morgen moeten werken

**Comment by Willem-Dekker** [comment]
3. is gewoon de verantwoordelijkheid van de baas

**Comment by timfloors** [comment]
deze lonen kunnen niet aangepast worden door de baas bij de kmar

**Comment by timfloors** [comment]
het kan zijn dat kenneth ze al had aangepast maar dat is niet zeker, waar staan ze nu op

**Comment by Willem-Dekker** [comment]
punt 1 zit er nu ook in

**Comment by Willem-Dekker** [comment]
lonen staan gelijk dus ik sluit deze issue
