### ISSUE TITLE
UrenRegistratie beroepen

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#414]
**Omschrijf de bug**
de urenregisratie werkt mogelijk niet goed mensen hebben veel meer uren gemaakt dan normaal bijvoorbeeld 290uren en 300uren werktijden

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
even kijken in dat channel dan kun je zien hoeveel uren mensen hebben gewerkt

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
hij zou de uren daar tonen wat mensen intotaal hebben gewerkt maar er klopt mogelijk iets niet aan de uren

**Screenshots en/of logbestanden**
-

**Impact op de server**
als deze issue klopt middel aangezien er veel beroepen promoten vanuit de urenregistratie

**Comment by niekschoemaker** [comment]
Deze issue is voor zover ik weet ondertussen gefixed, anders horen we het over een week wel weer I guess.
