### ISSUE TITLE
Rs6 Topspeed bug

### ISSUE THREAD

**Issue by Jaqdueen** [Tedeapolis/development#416]
**Omschrijf de bug**
Als ik in mijn Rs6 2016 rijd en ik dan in het f8 menu kijk hoort hij 365 tegaan maar als ik dan ga rijden gaat ie maar 335

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een fully tuned Rs6 2016 pakken en er mee rijden (zonder pantser)

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Hij zou normaal 365 moetten rijden

**Screenshots en/of logbestanden**
![Desktop Screenshot 2021 02 16 - 11 37 39 98](https://user-images.githubusercontent.com/79140694/108054086-83725400-704e-11eb-8223-7d28e48b50af.png)
![Desktop Screenshot 2021 02 16 - 11 40 05 94](https://user-images.githubusercontent.com/79140694/108054095-853c1780-704e-11eb-9ccd-56c89fcbfcba.png)

**Impact op de server**
Zover ik me kan bedenken hebben alleen de mensen die dus een fully tuned rs6 hebben hier last van

**Comment by niekschoemaker** [comment]
Ligt er simpelweg aan hoe de auto is afgesteld en is dus niet zozeer een bug maar meer dat die snelheid gewoon op die manier staat
