### ISSUE TITLE
Insigna op langshirt

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#417]
# Waar zit het in EUP, interiors of retextures ?
Politie EUP > Uniform > Lange shirt (geen insigna)

# Link naar issue of coördinaten naar de plek
![image](https://user-images.githubusercontent.com/68959019/108088876-3c4d8880-7079-11eb-9ec2-7ceb7cf4cc6a.png)

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Geen fout, de aanvraag of er op lange mouwen shirt ook een insigna kan komen. Werd aangevraagd door een agent. Als dit mogelijk is zou dat enorm fijn zijn! 

# Wat is de toegevoegde waarde?
Het is 10 x mooier

**Comment by walvisgedaan** [comment]
Heuy Daan, om dit te kunnen doen moeten we wederom een model met veel texture varianten vervangen. Momenteel vind ik het dat niet waard en wil ik dit nu nog even laten wachten. Mocht dit over een maandje oid nogsteeds aan de orde zijn dan zal ik dit her-overwegen.
