### ISSUE TITLE
EUP fout BSB

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#419]
# Waar zit het in EUP, interiors of retextures ?
Het probleem bevindt zich in de EUP van de BSB. 

# Link naar issue of coördinaten naar de plek
-

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Het volgende probleem is aan de hand:

- Zodra een BSB lid net de stad in komt kan hij enkel de volgende outfits aandoen: 
https://media.discordapp.net/attachments/811710473212919858/811717901852737576/unknown.png
https://media.discordapp.net/attachments/811710473212919858/811717990852460594/unknown.png

-Zodra een BSB lid uit- en in dienst is gegaan na het joinen van de stad kan een BSB lid de volgende outfits aandoen:
https://media.discordapp.net/attachments/811710473212919858/811716985653821460/unknown.png

# Wat is de toegevoegde waarde?
Voor leden van de BSB scheelt het heel veel. Zodra ze de stad inkomen kunnen ze direct actie ondernemen tijdens oproepen zonder eerst uit- en in dienst te hoeven gaan.

**Comment by niekschoemaker** [comment]
Zou je iets specifieker kunnen zijn wat ik moet doen om dit te reproduceren?
Want mezelf als DSI zetten of KMAR (BSB KPL.3) werkt niet om de issue te reproduceren dus of er specifieke rangen oid zijn?

**Comment by MartijnMeister** [comment]
Wat mij is verteld is dat mensen die een dsi / bsb rang hebben enkel het volledige eup kunnen zien als ze, na het connecten, uit / indienst gaan. De volgende stappen zouden moeten werken:
- DSI / BSB rang nemen
- Uitloggen
- Connecten 
- /eup 

Op dit moment zou je enkel een klein aantal outfits kunnen zien.

- Uit en indienst gaan

Nu zou je pas alle outfits kunnen zien.
Mocht dit niet werken zal ik kijken of iemand het kan reproduceren en hier een video van kan maken.

**Comment by MartijnMeister** [comment]
^^ Zou bij elke rang zo moeten zijn

**Comment by MartijnMeister** [comment]
Ondertussen heb ik even de tijd genomen om de bug te reproduceren. Via volgende link is deze te bekijken:
https://youtu.be/h4pvvmqlE50

**Comment by niekschoemaker** [comment]
Oke zoals ik dus al noemde, ik kan deze issue niet replicaten, ik volg de stappen en bij mij werkt alles gewoon dus ik kan deze issue niet fixen.
