### ISSUE TITLE
Kraslootjes zijn niet balanced, desnoods inkoopprijs van lootjes verlagen?

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#42]
Ticket 4874, de lootjes voor Maria's Winkel lijken niet gebalanced. Er zijn meerdere tests uitgevoerd:

3x 100 lootjes

Kraslootjes inkoop:
100

Kraslootjes winst staat: (900)
90.000

Kraslootjes verkoop: (1300)
130.000 (Maria) - 90.000 (staat) = 40.000 winst Maria

Kraslootjes opbrengst koper:
(1) 56.000 per 100 lootjes
(2) 53.500  "   "     "
(3) 55.500  "   "     "

Kraslootjes koper winst/verlies:
(130.000 - Opbrengst)
(1) 74.000 Verlies
(2) 76.500    "
(3) 74.500    "

Reno:
2x 1000 lootjes

Op 2x 1000 lootjes (waar je 1.3M voor betaald) ...
Verlies je:
(1) 476.000
(2) 583.000

---------------------------------------------
Desnoods de inkoopprijs van de lootjes verlogen naar 600 euro.

**Comment by Willem-Dekker** [comment]
het systeem is ook niet gemaakt om met grote runs te werken, het is een gemaakt op enkele lot basis.  maar ik zal de prijs van inkoop verlagen naar 600 zodat de prijs per ticket 1000 kan zijn.
