### ISSUE TITLE
Treinen

### ISSUE THREAD

**Issue by Marius-002** [Tedeapolis/development#420]
**Beschrijf zo duidelijk mogelijk de feature**
Zorgen dat de treinen zoals in GTA 5 worden aangezet en effectief rondrijden op de treinsporen.

**Wat lost deze feature op?**
Dit zorgt voor extra roleplay die je eventueel met de treinen kan doen en ook wanneer mensen door de metrotunnels willen vluchten hier een gevaar aan verbonden is.

Het zorgt simpelweg gewoon voor meer realisme.

**Comment by Willem-Dekker** [comment]
Heb ik al enkele dagen aan besteed en niks mee verder gekomen

**Comment by Marius-002** [comment]
> Heb ik al enkele dagen aan besteed en niks mee verder gekomen

Oh, dacht dat het en easy fix was, als het te moeilijk is hoeft het idd niet! :P
