### ISSUE TITLE
Politie koppelriem (vrouw)

### ISSUE THREAD

**Issue by oliviazeta** [Tedeapolis/development#421]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Link naar issue of coördinaten naar de plek
EUP/Politie (Vrouw)
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
De huidige koppel is erg wijd en sluit daarom niet aan op het lichaam. Bij de nieuwe (die voorheen ook altijd is gebruikt) sluit deze wel goed aan.
Huidig: https://gyazo.com/8b12ea333b9d8c7fce2f3c46150628e8
Nieuw: https://gyazo.com/efec6b0a3d608e4229afc60c3171d0b1
# Wat is de toegevoegde waarde?
Realistischer dat de riem niet om het lichaam heen zweeft.

**Comment by Willem-Dekker** [comment]
welke nummers zijn het?

**Comment by oliviazeta** [comment]
T-Shirt 1 : <52> is de 'nieuw' versie van de koppel die ik bedoel

**Comment by Willem-Dekker** [comment]
Zit er vanaf morgen in
