### ISSUE TITLE
Witwas cirkels onzichtbaar

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#423]
**Omschrijf de bug**
Van Sommige witwas afleverpunten kan je de gele cirkel niet zien

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een rondje gaan witwassen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je zou een cirkel moeten zien waar je op moet gaan staan

**Screenshots en/of logbestanden**
https://media.discordapp.net/attachments/802947467368071178/813061720443846656/F2E94D467B0B3FB6447BE2A14DC9455D63FEA225.png?width=1202&height=676

https://media.discordapp.net/attachments/802947467368071178/813061782552969256/D5DB75D90C9B7D7A39DF720BAF1A4AE540CDD18C.png?width=1202&height=676
Coords moeten omhoog

**Impact op de server**
middel aangezien het nu onduidelijk is waar precies het punt is

**Comment by StoffigKontje** [comment]
![image](https://user-images.githubusercontent.com/53233719/108715185-ca62bc80-751a-11eb-8945-e1c91724f85f.png)
![image](https://user-images.githubusercontent.com/53233719/108715346-0bf36780-751b-11eb-92f0-064476b4435c.png)


me me fix
