### ISSUE TITLE
Sommige stukken grond zijn zand bij nieuwe anwb (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#424]
# Waar zit het in EUP, interiors of retextures ?
Nieuwe anwb

# Link naar issue of coördinaten naar de plek
[https://www.youtube.com/watch?v=PMg9jXyUI4o&feature=youtu.be&ab_channel=river ]

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Er zitten stukken zand waardoor sportwagens niet goed door kunnen rijden

# Wat is de toegevoegde waarde?
dan kunnen sportwagens beter rondrijden daar

**Comment by brothasx** [comment]
Hoever ik me kan herinneren had ik deze al gefixed.
