### ISSUE TITLE
/do Kleur (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#425]
**Beschrijf zo duidelijk mogelijk de feature**
de kleur veranderen van het /do command naar groen/geel

**Wat lost deze feature op?**
de kleur blauw is hetzelfde als twitter dus het is heel moeilijk om te zien wanneer je dood licht

**Comment by StoffigKontje** [comment]
Opgelost, de kleur van /do is naar groen gezet. 
![image](https://user-images.githubusercontent.com/53233719/108702549-b498cb80-7509-11eb-8c26-c5062eddc298.png)
