### ISSUE TITLE
Meerdere witwas locatie's (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#426]
**Beschrijf zo duidelijk mogelijk de feature**
Misschien in het noorden ook een witwas locatie, zorgt voor meer rp voor de kmar en politie. En voor meer rp in het noorden.

**Wat lost deze feature op?**
het lost mogelijk op dat mensen gaan campen op 1 locatie en meer variatie als witwasser

**Comment by StoffigKontje** [comment]
Er zijn 5 witwas locaties toegevoegd in het noorden, zodat er wat meer variatie is tijdens de witwas rondes en wat meer werk in het noorden.
