### ISSUE TITLE
Blokkade op pier (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#427]
**Beschrijf zo duidelijk mogelijk de feature**
een blokkade op het punt waar de pier smaller word iets van een bankje of muurtje/plantenbakken

**Wat lost deze feature op?**
 zodat voertuigen niet helemaal naar achter kunnen rijden en het daar helemaal vol staat met met autos

**Comment by MisterM02** [comment]
@niekschoemaker staffoverleg 06-12-2021. Garage toevoegen op de pier.

**Comment by timfloors** [comment]
Was de garage niet direct toegevoegd?

**Comment by MisterM02** [comment]
Enkel de flitspaL

**Comment by brothasx** [comment]
Deze update had ik uitgevoerd.
