### ISSUE TITLE
Ontboeien met lockpics 

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#428]
**Beschrijf zo duidelijk mogelijk de feature**

Zoals een deel vast weet, zijn politie handboeien nu permanent om ipv 15 minuten. Dit betekent dat je niet meer vrij kunt komen zonder dat een agent dit doet. Word je dus uitgebroken tijdens transport, zul je alsnog permanent in de boeien zitten en kan niemand je dragen, waardoor uitbreken niet eens mogelijk is zonder hulp van een agent.

Om dit mogelijk te maken is mijn suggestie om lockpics ook voor handboeien te laten werken. Hoe gaat dit in zijn werk?Iemand heeft een lockpick setje op zak en gaat achter de persoon staan die in de handboeien zit. Via zijn broekzakken (F2) gebruikt hij de lockpick. Hierbij wordt de emote uncuff gebruikt. Na 30 seconde zijn de boeien af en kan de persoon weer bewegen. Voor een moeilijkheidsgraad kan er nog iets worden toegevoegd waardoor er bijvoorbeeld een bepaalde slagingskans is. Mislukt de poging, zul je het met een nieuwe lockpick set opnieuw moeten proberen.

**Wat lost deze feature op?**
Zodat personen niet urenlang vast zitten als dit wordt vergeten door de politie en zodat er ook een ontsnappingsmogelijkheid is.

**Comment by Willem-Dekker** [comment]
#65 wordt dit ook in besproken

**Comment by niekschoemaker** [comment]
Dit werkt nu met het item van huis inbraken.
