### ISSUE TITLE
Paar toevoegingen bij ANWB

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#429]
- [x] /Repareer kunnen doen op ANWB HB als er 2 of minder anwb'ers in-dienst zijn.
- [x] Garage cirkel voor anwb'ers om hun voertuig erin te doen. Momenteel glitchen voertuigen op en door elkaar op de parkeerplaats.
- [x] Dat je hier voertuigen kan aanpassen (LAcustoms ding) voor mensen die komen met een WOK status. (zie foto)
Dus als het mogelijk is alleen op dat vierkantje. 
![dssdfsdfsdfsdfsdfs](https://user-images.githubusercontent.com/68514420/108702079-0b51d580-7509-11eb-83c6-8e50e51ccf5d.png)

**Comment by StoffigKontje** [comment]
Did it, mom
