### ISSUE TITLE
DSI Lightbars (AGAIN) 

### ISSUE THREAD

**Issue by SvenKeppel** [Tedeapolis/development#43]
De DSI lightbars lijken weer niet te werken . we kunnen ze wel op de auto zetten maar niet aan zetten. Ook is er een probleem dat de auto niet meer op slot kan of open als je de lightbars hebt geinstalled.  

To Do 

- [ ] Checken van de lightbars 
- [ ] Nagaan wat er fout gaat via logs 
- [ ] Slotenprobleem oplossen

**Comment by SvenKeppel** [comment]
[CitizenFX_log_2020-07-27T154341.log](https://github.com/Tedeapolis/development/files/4983162/CitizenFX_log_2020-07-27T154341.log)

**Comment by Willem-Dekker** [comment]
sloten is een bekend issue en gaat niet worden gefixed
