### ISSUE TITLE
Voertuig inbeslagname (Vliegtuigen & Helikopters)

### ISSUE THREAD

**Issue by levisps** [Tedeapolis/development#430]
**Omschrijf de bug**
Op dit moment staat er een inbeslagname in een hangar op LSIA Airfield, hier is alleen geen groene en rode cirkel aanwezig om de voertuigen en in dit geval vliegtuigen of helikopters in op te slaan of uit te halen. (Zie screenshot van de kaart) Ook heb je bij sandy shores bureau een fout dat je wel een groene cirkel ziet die half in de grond zit en ook geen rode cirkel. Als dit ook gefixt kan worden zou dat fijn zijn. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
U kunt naar het vliegveld gaan en naar de locatie van de grijze opslag. Hier ziet u dat er geen inbeslagname cirkels aanwezig zijn. (Mogelijk zijn ze te laag ingevoerd zodat ze niet zichtbaar zijn.) Voor Sandy werkt de zelfde reproductie, alleen zie je hier een halve groene cirkel en geen rode cirkel.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou hier een rode en groene cirkel zijn om de heli's en vliegtuigen op te slaan en uit te laten kopen of halen.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/79063801/108745863-ea56a800-753b-11eb-9913-e2595098deb5.png)

**Impact op de server**
Door deze bug kunnen vliegtuigen of helikopters nauwelijks goed en realistisch in beslag worden genomen. Nu is de enigste mogelijkheid om het in het HB te doen waar je enorm moet kloten met de garage, niet handig en realistisch.  Het zou fijn zijn als dit voor beide locaties aangepast kan worden. Dit voorkomt een hoop gezeur en zo krijg je wat meer realisme waar je helikopters in beslag neemt. 

Alvast enorm bedankt voor de genomen moeite!

Met vriendelijke groet,

Levi Noord

**Comment by Willem-Dekker** [comment]
er is dus geen gele cirkel daar?

**Comment by MartijnMeister** [comment]
![Uploading image.png…]()

**Comment by MartijnMeister** [comment]
https://cdn.discordapp.com/attachments/751254043925676132/809786551982358548/unknown.png

**Comment by Willem-Dekker** [comment]
Heb net een aanpassing gepushed naar main als @MartijnMeister mij na de restart kan laten weten of het nu goed staat zou top zijn

**Comment by MartijnMeister** [comment]
Fix is doorgekomen waardoor de cirkels nu zichtbaar + in werking zijn 👍

**Comment by Willem-Dekker** [comment]
top
