### ISSUE TITLE
ANWB pasje uitdienst

### ISSUE THREAD

**Issue by lexdeboer** [Tedeapolis/development#431]
**Beschrijf zo duidelijk mogelijk de feature**
Dat als ANWB uitdienst is dat wij dan ook een ANWB pasje hebben in onze portemonnee 

**Wat lost deze feature op?**
Dat ANWB korting kan krijgen als je een collega bent , met dit pasje kan daardoor geen fraude worden gepleegd met roepnummers en namen. Dan weet je zeker wie dat persoon is.

**Comment by Willem-Dekker** [comment]
zit er morgen in
