### ISSUE TITLE
Verkeerde spawnplek voertuigen

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#432]
**Omschrijf de bug**
Bij de garage achter blokkenpark appartementen en bij de mijnwerkerslocker spawnen bepaalde voertuigen foutief in. Doordat de garages geplaatst zijn in een gebouw spawnen (bepaalde) voertuigen in het gebouw, waarna deze vastzitten.

Het gaat om de volgende locaties:
Achter blokkenpark appartementen: X: 467.73 Y: -1111.91 Z: 35.32 H: 68.21
Bij mijnwerkerslocker: X: 804.08 Y: -2013.37 Z: 29.24 Z: 211.55

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)** 
Pak bij de garage het volgende voertuig:
Achter blokkenpark appartementen: Bestelbusje of Nissan Qashqai
Bij mijnwerkerslocker: Nissan Titan Warrior

Dit zijn de voertuigen waarmee ik het heb zien gebeuren.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden deze voertuigen netjes op de grond moeten inspawnen

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/72617118/108766242-306c3580-7555-11eb-8a2c-438ff14d8790.png)

**Impact op de server**
Voor spelers is het erg vervelend gezien ze hierdoor moeten wachten op een staflid gezien ze hier niet zelf weg kunnen komen.
Tevens zullen er na een eventuele fix minder reports binnenkomen.

**Comment by StoffigKontje** [comment]
Zou gefixed moeten zijn na de restart
