### ISSUE TITLE
Kleding icoon op paardenrenbaan

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#433]
**Omschrijf de bug**
Op de paardenrenbaan bij het originele GTA casino staat het icoontje van een kledingwinkel.
Hier is echter geen kledingwinkel aanwezig waardoor er verwarring ontstaat bij spelers.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Open de map en bekijk het kledingwinkel icoontje op de map.
Rij naar het icoontje en je zult zien dat er geen kledingwinkel is.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Er zou geen icoontje moeten staan

**Screenshots en/of logbestanden**
Coördinaten: X: 1103.70 Y: 196.70 Z: 80.99 H: 357.42

![image](https://user-images.githubusercontent.com/72617118/108837921-3dc80500-75d3-11eb-88a7-526cd97e1140.png)
![image](https://user-images.githubusercontent.com/72617118/108837969-49b3c700-75d3-11eb-8906-c7a166009892.png)

**Impact op de server**
Klein - Zorgt enkel voor verwarring bij spelers gezien ze de kledingwinkel die er zou moeten zijn niet kunnen vinden

**Comment by Willem-Dekker** [comment]
fixed
