### ISSUE TITLE
Bodycams glitchen i.c.m. nieuwe EUP

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#434]
# Waar zit het in EUP, interiors of retextures ?
EUP

# Link naar issue of coördinaten naar de plek
Bodycam optie in het EUP-menu voor alle rangen van de politie. 

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Ja, als je een bodycam aan wilt doen met het nieuwe steekvest dan ziet dit er vrij apart uit. 
![image](https://user-images.githubusercontent.com/71287080/109019784-9a9deb00-76b9-11eb-9a41-05217b64af47.png)

# Wat is de toegevoegde waarde?
Dit ziet er veel mooier en normaler uit.

**Comment by Willem-Dekker** [comment]
ik weet niet of dit gefixed wordt ik  zal @brothasx en @walvisgedaan taggen

**Comment by Willem-Dekker** [comment]
dit is niet makkelijk op te lossen en zal niet gedaan worden.
