### ISSUE TITLE
Niet werkende ATM

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#435]
**Omschrijf de bug**
Op postcode 650 staat naast de aanwezige garage een ATM. Deze werkt echter niet..

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Loop naar de ATM en druk op E. Er zal geen menu verschijnen via waar jij geld kan opnemen / storten.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je bij een ATM geld moeten kunnen storten / opnemen.

**Screenshots en/of logbestanden**
Coördinaten: X: -65.81 Y: 881.40 Z:235.83 H: 223.93

![image](https://user-images.githubusercontent.com/72617118/109197778-b5e22680-779d-11eb-9136-531129fca3bc.png)

![image](https://user-images.githubusercontent.com/72617118/109197796-bd093480-779d-11eb-9950-8d33f9b0fd36.png)

**Impact op de server**
Het is vervelend voor mensen die een auto uit de gele cirkel moeten pakken gezien ze hier geen geld op kunnen nemen.
Tevens wordt deze vaak gebruikt tijdens huiszoekingen en is het dus erg handig als deze ATM werkend wordt.

**Comment by Willem-Dekker** [comment]
fixed voor morgen
