### ISSUE TITLE
/reply een ander kleurtje

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#436]
**Beschrijf zo duidelijk mogelijk de feature**
/reply een ander kleurtje geven zodat je de reports en replies uit elkaar kan houden net zoals de /do een ander kleurtje heeft

**Wat lost deze feature op?**
Zodat je de reply's en reports uit elkaar kan houden

**Comment by Willem-Dekker** [comment]
@StoffigKontje kan dit mooi op pakken

**Comment by StoffigKontje** [comment]
Is gefixed na eerstvolgende restart!
