### ISSUE TITLE
Telefoon terug krijgen na gevangenisstraf

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#438]
**Beschrijf zo duidelijk mogelijk de feature**
Is het mogelijk om iets te maken waardoor je je telefoon terug kan krijgen als je gevangenisstraf erop zit? aangezien als je nu de gevangenis uit bent dan kan je niemand bellen om je op te halen waardoor je dus terug moet lopen naar de stad. of een telefooncel waar alleen de noodnummers op staan?

**Wat lost deze feature op?**
Dat je gewoon de taxi kan bellen terug naar de stad.

**Comment by Willem-Dekker** [comment]
Dit is iets wat is afgesproken met de politie dat zij die terug geven als ze hem veroordelen en voor zo ver ik weet kan je hem niet gebruiken als je vast zit

**Comment by TDA-SanderD** [comment]
Wij geven geen telefoons/portofoons terug op het moment dat een persoon naar de gevangenis wordt gestuurd. 

Wellicht zou het mogelijk zijn dat **alle** items van de persoon behalve voedsel worden afgenomen op het moment dat de persoon veroordeeld wordt (en in een soort virtuele "locker" worden bewaard). Als de persoon uit de gevangenis komt dan krijgt hij alles vanzelf weer terug.

**Comment by Willem-Dekker** [comment]
waarom worden deze niet terug gegeven? ze kunnen niet gebruikt worden. dus de politie is telefoons aan het farmen?

**Comment by DevvTDA** [comment]
Ik heb meerdere “criminele” gevraagd of zei al ooit eens hun telefoon terug hadden gekregen maar nog nooit hebben ze iets terug gekregen, ze hebben steeds nieuwe moeten kopen. Ook weet volgens mij zowat niemand dat je de telefoon ook terug mag vragen zodra je weer vrijuit bent.

**Comment by TDA-SanderD** [comment]
@Willem-Dekker Ik heb het zojuist getest. Telefoons zijn inderdaad uitgeschakeld in de gevangenis, maar portofoons werken gewoon. Hierdoor kan er wel communicatie plaatsvinden.

Er worden geen telefoons gefarmed. Ze komen in de opslag terecht en we gebruiken dit om terug te geven aan personen die hun telefoon op komen halen.
