### ISSUE TITLE
Urenlijsten overheidsdiensten kloppen niet

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#440]
**Omschrijf de bug**
Momenteel werken de urenlijsten voor overheidsdiensten niet meer correct. Er zijn medewerkers met meer dan 170 uur in dienst, dat is natuurlijk niet mogelijk. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Simpelweg het bestand downloaden dat naar de bazen van alle overheidsjobs wordt gestuurd en daar kun je zien dat de uren niet kloppen. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou er elke keer dat er in- en uitgeklokt wordt opgenomen moeten worden hoe lang de medewerker in dienst is, nu gebeurt dat onjuist waardoor het soms verdubbeld wordt lijkt me. 

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/71287080/109636760-4331cc00-7b4c-11eb-959d-ddd27b9c6631.png)

**Impact op de server**
Licht

**Comment by Willem-Dekker** [comment]
deze issue is die week ook al gefixed, deze week zijn de uren gewoon normaal
