### ISSUE TITLE
Ban scherm tijd naar juiste tijdzone zetten

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#441]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel wordt de tijd van unban in UTC weergegeven dit zou naar de huidige tijdzone van nederland moeten gaan

**Wat lost deze feature op?**
Verwarring onder spelers

**Comment by niekschoemaker** [comment]
¯\_(ツ)_/¯

**Comment by Willem-Dekker** [comment]
Dankje
