### ISSUE TITLE
DSI Kpl. 2 EUP Werkt bijna niet uitdienst.

### ISSUE THREAD

**Issue by Bladerdeeg** [Tedeapolis/development#442]
Als je bij DSI Kpl. 2 uitdienst bent kan je geen vesten / outfits aandoen,

Als je uitdienst gaat, en /EUP doen zie je dat je alleen maar een paar outfitjes kan pakken die niet relevant zijn voor de DSI

Wat hoort er te gebeuren? Dat je alles het wat je normaal indienst ook hebt, Zoals bij DSI Kpl. 1 

Impact op de server? :   Niet bepaald, Tis beetje als wij een melding krijgen dat we eerst helemaal naar Hb moeten om indienst / een outfit aan te doen.

**Comment by Willem-Dekker** [comment]
is iets wat we niet kunnen fixen gewoon in en uit dienst gaan is het makkelijkst
