### ISSUE TITLE
Vliegtuig dodo

### ISSUE THREAD

**Issue by DevinKoedam** [Tedeapolis/development#443]
**Beschrijf zo duidelijk mogelijk de feature**
Ik ben er zojuist achter gekomen dat er 400kg  in een dodo kan

**Wat lost deze feature op?**
het is niet echt realistisch vergeleken met het duurste vliegtuig (miljet) waar 300kg in kan en 10 keer zo duur is
heb het vergeleken met een hoop anderen vliegtuigen en deze kwam bovenaan,
mij lijkt 150kg beter.

**Comment by niekschoemaker** [comment]
De duurste vliegtuigen moeten nog een keer aangepast worden en gezien dit nogal dure voertuigen zijn ben ik er ook niet echt vanuit gegaan dat mensen deze voor drugs etc gaan gebruiken ivm inbeslagname enzo.

**Comment by DevinKoedam** [comment]
zie dat hij is aangepast bedankt!
