### ISSUE TITLE
Oude 2e hans

### ISSUE THREAD

**Issue by DevinKoedam** [Tedeapolis/development#444]
**Beschrijf zo duidelijk mogelijk de feature**
Het weghalen van de oude 2e hans (besproken met vorige staff overleg)

**Wat lost deze feature op?**
Tijdens het staff overleg had ik aangegeven of de oude 2e hans weg kon gehaald worden, dit aangezien er nu een grote 2e hans is gemaakt ( arena ) en daar staan alle voertuigen al. ook zal dit misschien wel voor iets minder lag zorgen.

*De locatie van de oude 2e hans is tegenover de cardealer*

**Comment by Willem-Dekker** [comment]
volgens mij was besproken dat deze gewoon bleef
