### ISSUE TITLE
Parkeergarage cirkels - berging

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#445]
**Beschrijf zo duidelijk mogelijk de feature**
Is het mogelijk dat er ergens vlakbij berging een rode, groene en eventueel ook een gele cirkel komen. Vaak gebeurd er doordat er teveel auto’s staan dat andere voertuigen verdwijnen en als wij deze dan weghalen dan heeft die geen vervoer meer vanuit berging, en de factuur van een taxi is dan ook vrij hoog

**Wat lost deze feature op?**
Verminderd het verdwijnen van voertuigen, wij hoeven dus ook minder vaak daarnaar om te kijken. En de kans op gedupliceerde autos is ook 10keer minder

**Comment by Willem-Dekker** [comment]
zit er in na restart
