### ISSUE TITLE
Vlieginstructeur voertuigen

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#446]
**Omschrijf de bug**
Sinds kort hebben alle vlieginstructeurs bij het pakken van een voertuig een kopje "vlieginstructeur". Hier kan een instructeur bijvoorbeeld een Frogger pakken om les mee te geven. Dit voertuig heeft echter geen officiële eigenaar waardoor de helikopter niet weggezet kan worden in de rode cirkel. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Jezelf vlieginstructeur permissies geven waardoor je een helikopter kan pakken onder het kopje "vlieginstructeur". Deze helikopter hierna pakken en proberen weg te zetten. Je zult dan zien dat de tekst "U bent niet de eigenaar van dit voertuig" links onderin komt te staan als je hem probeert weg te zetten.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je de helikoper zelfstandig weg kunnen zetten in de rode cirkel.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/72617118/110116887-72e50c00-7db8-11eb-96ac-fc607e6b459e.png)

**Impact op de server**
Middel - Vlieginstructeurs moeten steeds een report aanmaken wanneer ze hun helikopter weg willen zetten gezien ze dit zelf niet kunnen doen.

**Comment by Willem-Dekker** [comment]
zelfde issue als #463

**Comment by Willem-Dekker** [comment]
dit zou gefixed moeten zijn laat het anders ff weten of heropen de issue
