### ISSUE TITLE
Tattoo's overal in de map aan kunnen passen

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#447]
**Omschrijf de bug**
als je in een tattoage shop bent geweest en je gaat rondrijden blijft e links bovenin staan en kun je hem nogsteeds aanpassen

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een tattoo nemen en dan rond gaan rijden

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je kunt rustig wat anders gaan doen zonder dat dat links bovenin blijft staan

**Screenshots en/of logbestanden**
https://youtu.be/kxqqG7yzfRc

**Impact op de server**
middelmatig aangezien alleen spelers die net hun tattoo aanpassen het merken

**Comment by Willem-Dekker** [comment]
ja dan wordt er gewoon geen leaf event getriggerd

**Comment by timfloors** [comment]
is daar een oplossing voor of is dat iets wat soms kan gebeuren?

**Comment by Willem-Dekker** [comment]
dit zou gewoon moeten werken? welke shops zijn het

**Comment by timfloors** [comment]
dit was als je helemaal in het noorden naar de tattoshop gaat

**Comment by Willem-Dekker** [comment]
kan het nier reporduceren
