### ISSUE TITLE
Rangen Pavlov aanpassen

### ISSUE THREAD

**Issue by AaranDejager** [Tedeapolis/development#448]
**Beschrijf zo duidelijk mogelijk de feature**
De rang 'Bratan' of 'Mafia 2' kan momenteel geld opnemen van de samenleving terwijl dit niet de bedoeling is. Alleen de rang 'Ocec' of 'mafia 3' mag geld opnemen van de samenleving. 
De rang 'Stric' of 'mafia 50' moet toegang krijgen tot alle wapens inkopen + helikopter spawnen.

**Wat lost deze feature op?**
Dat mensen met de rang 'Bratan' geen geld meer kunnen opnemen van de samenleving + de rang 'Stric' die wapens kan inkopen + helikopters kunnen spawnen.

**Comment by Willem-Dekker** [comment]
heli kan alleen de baas dit is niet in te stellen per rank op dit moment

**Comment by Willem-Dekker** [comment]
De rest zit er voor morgen in
