### ISSUE TITLE
KMAR - Reanimeren + meldingen (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#450]
**Beschrijf zo duidelijk mogelijk de feature**
De vraag om toe te voegen vanaf de rang luitenant plus toevoeging dat medische meldingen als er geen ambu is ook doorgestuurd worden naar de KMAR

**Wat lost deze feature op?**
Komt dikwijls voor dat Ambu er niet is en dan krijgt politie alle medische assistentie aanvragen, zij kunnen dat niet bijbenen. Een idee om reanimeren in te voeren vanaf luitenant, zodat wij in het noordelijke halfdeel mensen kunnen voorzien van de nodige hulp

**Comment by Willem-Dekker** [comment]
zit er vanaf morgen in
