### ISSUE TITLE
KMAR - Comserv (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#451]
**Beschrijf zo duidelijk mogelijk de feature**
de vraag om toe te voegen dat de kmar /comserv en /endcomserv kunnen doen

**Wat lost deze feature op?**
De (h)OvJ's kunnen in hun zaken geen comserv gebruiken om de straf uit te delen als dit nodig is

**Comment by Willem-Dekker** [comment]
welke ranks zouden dit zijn dan?

**Comment by timfloors** [comment]
ik kreeg te horen dat die alleen op de volledige kmar rang kon, maar anders zou het vanaf luitenant moeten kunnen

**Comment by Willem-Dekker** [comment]
het is alles of niks ja, maar je geeft aan dat de Hovj's het moeten kunnen doen

**Comment by Willem-Dekker** [comment]
zit er vanaf morgen in
