### ISSUE TITLE
KMAR - HRB kleding (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#452]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
HRB kleding is alleen in het EUP voor bazen, misschien een github (als deze er nog niet was) om het op HRB rang te krijgen
# Wat is de toegevoegde waarde?
dat ze uberhaupt makkelijk hun kleding aan kunnen doen

**Comment by Willem-Dekker** [comment]
hier zijn al 2/3 andere issues voor..

**Comment by Willem-Dekker** [comment]
#403

**Comment by timfloors** [comment]
ik was retarded
