### ISSUE TITLE
AMBU - NCP/driving job (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#454]
**Beschrijf zo duidelijk mogelijk de feature**
de vraag om de oude npc job weer aan te zetten voor de ambu waarmee ze medicijnen rond konden brengen

**Wat lost deze feature op?**
Sommige dagen is het zo rustig, zeker in de nachten, dat je eigenlijk niks staat te doen.Toch wil je niet stil staan op het ziekenhuis. Voorkomt ook dat heel ambulancepersoneel in het ziekenhuis staat wanneer er geen meldingen zijn

**Comment by Willem-Dekker** [comment]
deze zou ergens moeten staan

**Comment by Willem-Dekker** [comment]
deze staat gewoon aan... je kan in de Pharmacy medicijnen kopen

**Comment by Willem-Dekker** [comment]
Met del kan je een job starten als je in de van rijd en of e-classe

**Comment by Willem-Dekker** [comment]
werkt weer vanaf morgen
