### ISSUE TITLE
Bug met upgraden van voertuigen (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#456]
**Omschrijf de bug**
Heel vaak als je een auto pakt en er iemand anders in laat rijden of gewoon direct naar de modshop geeft de de melding "de upgrades komen niet overheen met de server, haal je voertuig opnieuw uit de garage" hierdoor kun je dus niet upgraden

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een voertuig pakken
switchen van driver
modshop in gaan
e klikken
en dan krijg je 9 van de 10keer deze melding

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je zou het voertuig gewoon moeten kunnen aanpassen

**Screenshots en/of logbestanden**
ik kan screenshots maken als dit nodig is hierbij

**Impact op de server**
groot aangezien dit zwaar irritant is midden in je roleplay

**Comment by Willem-Dekker** [comment]
caching lijkt me

**Comment by timfloors** [comment]
dat zou kunnen merk wel dat het de laatste tijd niet meer voorkomt hoor het ook nergens meer, dus kan zijn dat het gefixt is

**Comment by timfloors** [comment]
naar mijn weten heeft dit issue zichzelf al opgelost dus bij deze zal ik hem ook sluiten :D
