### ISSUE TITLE
ANWB - Aanpassing max anwbers voor /repareer (burgerraad)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#457]
**Beschrijf zo duidelijk mogelijk de feature**
het verhogen van het limiet om /repareer te gebruiken naar 3

**Wat lost deze feature op?**
aangezien de stad zo snel groeit en zo druk is is het soms niet mogelijk om veel anwb in dienst te hebben hiervoor, dit zal die issue een klein beetje verhelpen

**Comment by Willem-Dekker** [comment]
fixed voor morgen
