### ISSUE TITLE
Extra platformen in gebruik nemen bij de eerste olie stop

### ISSUE THREAD

**Issue by musician1011** [Tedeapolis/development#458]
**Beschrijf zo duidelijk mogelijk de feature**
- Bij de eerste stop van olie verwerk, aan de ja-knikkers, heb je meerdere platformen maar wordt er maar een enkele gebruikt. Hierdoor gebeurt het soms dat als er teveel mensen bijeen staan, dat er uit het niets trucks beginnen ontploffen. 

**Wat lost deze feature op?**
Geen ontploffende trucks meer, minder mensen bijeen. Zo wordt het ook wat aangenamer voor mensen met een minder goeie pc.

![olieverwerk](https://user-images.githubusercontent.com/34730690/110500005-10ae4300-80f9-11eb-8a94-5ffb3f2c5223.jpg)

**Comment by Willem-Dekker** [comment]
zijn er nu 3 vanaf morgen
