### ISSUE TITLE
Nieuwe lijst specificaties boten

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#459]
In de onderstaande link staan de nieuwe voorgestelde specificaties van de boot
Zoals afgesproken in het afgelopen staffoverleg afgelopen zondag

Ook hebben wij een drietal nieuwe voertuigsuggesties toegevoegd voor meer variatie op het water.
- Marvin, Brockl
https://user-images.githubusercontent.com/71552704/110539172-30f3f700-8125-11eb-9dcc-4396abb30726.png

**Comment by Willem-Dekker** [comment]
laten we dit mee nemen in staff overleg zo als eerder besproken

**Comment by Willem-Dekker** [comment]
Is besproken in overleg en kan doorgevoerd worden

**Comment by Willem-Dekker** [comment]
is gedaan voor zover ik weet anders laat het ff weten

**Comment by TDAMarvinW** [comment]
Is nog niet doorgevoerd 😢 
Sorry voor het laat reageren, was deze helemaal uit t oog verloren
