### ISSUE TITLE
Taakstraf TP nog bij het oude bureau

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#461]
**Omschrijf de bug**
Wanneer iemand klaar is met zijn/haar taakstraffen, TPt deze terug naar het oude politiebureau, ipv het nieuwe. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een taakstraf eindigen van iemand en kijken waar deze naar TPt

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
TP naar het nieuwe bureau is handiger

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/53233719/110782030-e9758400-8266-11eb-9e0e-6db54fe469f0.png)
coords ongeveer van de huidige TP locatie ^

**Impact op de server**
niet veel, beetje irritant. Oude politiebureau is al een tijdje weg namelijk.

**Comment by Willem-Dekker** [comment]
zit er in na de restart
