### ISSUE TITLE
KMar helikopter

### ISSUE THREAD

**Issue by Billyaes** [Tedeapolis/development#462]
**Beschrijf zo duidelijk mogelijk de feature**
De Kmar helikopter zou moeten vanaf wachtmeester beschikbaar zijn. Dus vanaf wachtmeester tot luitenant generaal zouden de mensen deze helikopter moeten kunnen nemen.

**Wat lost deze feature op?**
Het aanpassen zodat vanaf wachtmeester tot luitenant generaal de helikopter kunnen pakken i guess? 

Thanks :)

**Comment by Willem-Dekker** [comment]
zit er vanaf de restart in
