### ISSUE TITLE
KMar boten

### ISSUE THREAD

**Issue by Billyaes** [Tedeapolis/development#463]
**Omschrijf de bug**
De Kmar boten kunnen niet ingeleverd worden in de rode cirkel. als je op E spier drukt dan gaan de lightbars aan maar despawned hij de boot niet. dit is zo bij alle 4 de KMar boten.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door jezelf op een KMar rang te zetten, de boot te nemen bij helipads bv. deze dan in de rode cirkel te varen en op E spier te klikken. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou de boot ingeleverd moeten worden.

**Screenshots en/of logbestanden**
/

**Impact op de server**
Geen idee.

**Comment by Willem-Dekker** [comment]
dit is als het goed is gefixed, als dit niet het geval is graag even laten weten of een nieuwe openen
