### ISSUE TITLE
Bugs taxi

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#465]
**Omschrijf de bug**
- Momenteel is rang 5 (taxi chef) weg bij de taxi.
- Taxi NPC's werken momenteel niet. Je kunt ze bij het ophalen niet vinden en dus niet wegbrengen. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
- Jezelf op taxi rang 5 zetten, dan zie je dat het niet werkt. 
- Een NPC job nemen als taxi

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
- Normaal zou rang 5 van de taxi "taxi chef" moeten zijn.
- NPC jobs zouden gewoon moeten werken.

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Licht/gemiddeld

**Comment by Willem-Dekker** [comment]
Rank werkt morgen weer

**Comment by Willem-Dekker** [comment]
Npc jobs zijn al langer een probleem

**Comment by Willem-Dekker** [comment]
zijn er verder nog logs?
