### ISSUE TITLE
Velum /tweak

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#466]
**Beschrijf zo duidelijk mogelijk de feature**
De velum, het propellervliegtuig gaat enorm traag. Het vliegtuig raakt amper de 200km/u aan en als je opstijgt kun je niet eens goed hoogte maken, omdat je stallt. Pas na ongeveer 3-5 minuten na het opstijgen zit je pas op de juiste hoogte.

Het zal fijn zijn om deze een tweak te geven, net zoals de Dodo en Cuban hebben gekregen.

**Wat lost deze feature op?**
Het vliegtuig zal fijner bestuurbaar zijn en de mensen die hem hebben gekocht kunnen er tevreden mee zijn.

**Comment by Willem-Dekker** [comment]
hier heb ik echt 0.0 last van als ik er mee vlieg heb er al een paar uur mee gevlogen

**Comment by ToniGain** [comment]
Hmm, ik wel en een paar andere ook. Kan die niet een kleine tweak anders alsnog gebruiken, gezien de dodo en cuban dit ook hebben gekregen?

**Comment by Willem-Dekker** [comment]
ik zal vragen of @niekschoemaker er naar kan kijken hij weet meer van de handeling af  namelijk

**Comment by niekschoemaker** [comment]
Dit is na volgende restart gefixed
