### ISSUE TITLE
Cirkels Peaky huis

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#467]
**Omschrijf de bug**
Momenteel staan de opslag cirkels van zowel de garage als helikopter fout geplaatst. Wanneer helikopters worden ingespawnt komen deze vast te zitten in het gebouwtje of kunnen ze niet opstijgen door de hitbox van bomen / palen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak uit zowel de garage als helikoptercirkel een helikopter en probeer hierna in een rechte lijn omhoog te gaan. Je zult zien dat je, of vast zit, of tegen een boom aan vliegt.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden de Peaky's normaal een helikopter uit de garage moeten kunnen pakken.
Om dit op te lossen zouden de volgende cirkels verplaatst moeten worden:

Cirkel op gangheli te pakken:
Oud: X: -43.02 Y: 946.80 Z: 232.17 H: 260.66
Nieuw: X: -111.26 Y: 977.61 Z: 235.76 H: 137.77

Spawnlocatie gangheli:
Oud: X: -49.24 Y: 942.88 Z: 236.33 H: 312.38
Nieuw: X: -119.06 Y: 972.53 Z: 240.07 H: 59.83

Cirkel om gangheli weg te zetten:
Oud: X: -49.24 Y: 942.88 Z: 236.33 H: 312.38
Nieuw: X: -119.06 Y: 972.53 Z: 240.07 H: 59.83

Cirkel om voertuigen uit garage te pakken:
Blijft hetzelfde

Spawnlocatie van voertuigen uit de garage:
Oud: X: -130.13 Y: 1003.88 Z: 235.73 H: 57.76
Nieuw: X: -125.51 Y: 997.35 Z: 239.92 H: 101.56

Cirkel om voertuigen weg te zetten in garage:
Oud: X: -130.13 Y: 1003.88 Z: 235.73 H: 57.76
Nieuw: X: -125.51 Y: 997.35 Z: 239.92 H: 101.56

**Screenshots en/of logbestanden**
Niet van toepassing

**Impact op de server**
Groot - Peaky's kunnen nu geen helikopters pakken en gebruiken

**Comment by Willem-Dekker** [comment]
je kan die heli gewoon weg vliegen heb dat allemaal getest en heb nergens problemen mee gehad

**Comment by Willem-Dekker** [comment]
impact op de server is tevens klein en niet groot

**Comment by Willem-Dekker** [comment]
Zit er morgen in
