### ISSUE TITLE
Niks verliezen nadat je dood gaat

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#468]
**Omschrijf de bug**
Wanneer je dood gaat verlies je momenteel enkel je telefoon. Voor de rest blijft alles in je inventory wat niet de bedoeling is.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Neem een inventory vol me spullen en laat jezelf dood gaan.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je alle spullen die je op zak had kwijt moeten zijn. Met uitzondering van je telefoon.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/72617118/111150349-47b7a500-858e-11eb-8033-dfc33bcb4f71.png)

In de foto zie je dat ik al mijn spullen nog heb, met uitzonder van mijn telefoon.

**Impact op de server**
Groot - Mensen behouden waardevolle spullen nadat ze dood zijn gegaan

**Comment by Willem-Dekker** [comment]
fixed, voor morgen met de restart
