### ISSUE TITLE
Recherche rangen hebben geen toegang tot nieuwe politie EUP (t-shirts)

### ISSUE THREAD

**Issue by Smikkelbakkie** [Tedeapolis/development#469]
# Waar zit het in EUP, interiors of retextures ?
EUP
# Link naar issue of coördinaten naar de plek
n.v.t.
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
![image](https://user-images.githubusercontent.com/50171172/111182777-8b6ed680-85af-11eb-92c6-35b7ea3428d0.png)
# Wat is de toegevoegde waarde?
Recentelijk is er een mooie EUP update geweest met betrekking tot nieuwe t-shirts met hier de rangen erop. Echter is het voor personen met een recherche rang niet mogelijk om deze te gebruiken _(zie screenshot)_. De recherche eup is gelukkig wel werkend, echter dit gedeelte nog niet.

**Comment by Willem-Dekker** [comment]
in en uit dienst gaan?

**Comment by Smikkelbakkie** [comment]
Werkt helaas ook niet

**Comment by walvisgedaan** [comment]
Ik zal even kijken, ik gok dat de isDsi check er op zit ipv de isDsiOrRecherche check.

**Comment by walvisgedaan** [comment]
![image](https://user-images.githubusercontent.com/69094685/112649997-423e4280-8e4b-11eb-96d4-5801bfc90bc4.png)
Hmmm.. apart, is dit niet al gefixt?

**Comment by Smikkelbakkie** [comment]
Zojuist voor je dubbel gecheckt, maar is niet werkend

**Comment by Smikkelbakkie** [comment]
Is er toevallig al meer bekend?

**Comment by walvisgedaan** [comment]
Als je inlogt, en vervolgens even in en uit dienst gaat, werkt het dan wel?

**Comment by Smikkelbakkie** [comment]
> Als je inlogt, en vervolgens even in en uit dienst gaat, werkt het dan wel?

Werkt  ook niet

**Comment by Willem-Dekker** [comment]
Zou nu moeten werken

**Comment by Smikkelbakkie** [comment]
Heb het zojuist laten testen lijkt inderdaad na behoren te werken op het moment, bedankt dat hier eindelijk na gekeken is en het werkend is. :)

**Comment by Smikkelbakkie** [comment]
Bedankje namen heel Recherche heren
