### ISSUE TITLE
xbox controller LT werkt niet 

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#47]
Je kan niet meer remmen met een controller . dit kon gister nog wel

**Comment by Willem-Dekker** [comment]
controllers worden ook niet officieel support maar dit is wel raar. ik kan zo ook ook niet zien waar het mis gaat

**Comment by takermart** [comment]
elke knop werkt nog , behalve de rem knop niet meer LT of L2 .

**Comment by takermart** [comment]
ik ben achter het probleem met de rem gekomen ... sinds de nieuwe update wat betreft het trekken van een wapen pakt  in een voertuig werkt de rem ook niet meer tijdens controller , dit omdat L2 of R2 ook je wapen pakken is .

**Comment by takermart** [comment]
dus ook al heb je geen wapen op zak gaat hij toch op het blokkeer systeem dat je niet kan sturen

**Comment by Willem-Dekker** [comment]
we hebben gevonden en gaan kijken of het gefixed kan worden

**Comment by takermart** [comment]
Oooh gelukkig 😁😁 Hopelijk kan dit gefixt worden

Op wo 29 jul. 2020 om 00:11 schreef Willem Dekker <notifications@github.com>

**Comment by Willem-Dekker** [comment]
het is gefixed op de dev server en het zal dus morgen na restart weer werken. 

houd er wel rekening mee dat er geen controller support is op deze server

**Comment by takermart** [comment]
Nee dat snap ik inderdaad , meeste knoppen doe ik ook via toetsenbord ,
alleen het rijden doe ik al jaren op de controller 🎮 gelukkig is het
opgelost 😁

Op wo 29 jul. 2020 om 00:15 schreef Willem Dekker <notifications@github.com>
