### ISSUE TITLE
Aanpassingen DSI/BSB rangen

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#470]
**Beschrijf zo duidelijk mogelijk de feature**
Sinds kort gebruikt het DSI team vanuit de KMAR (BSB) hun eigen rangen weer gezien de schietmeldingen hier nu aan gekoppeld zijn. Op de rangen missen echter nog een aantal features die hun werk kan belemmeren. Zo zijn er BSB leden die tevens als Klu. functioneren maar geen helikopters kunnen zien. Hieronder zal een lijst te zien zijn met aanpassingen die momenteel nog nodig zijn voor de BSB rangen.

- [x] In- en uitdienst in Sandy HB
- [ ] Kogelwerend vest 1 van de politie toevoegen aan de BSB eup (zie foto 1)
- [x] Bank-, winkel- en juwelier overval meldingen
- [x] Zelfde wapenkamer als de DSI rangen (zie foto 2 en 3)
- [x] Vliegtuigen/helikopters kunnen zien op de rader (groene cirkel)
- [x] EUP uit dienst
- [x] Kmar pas buiten dienst kunnen tonen
- [x] Op de kmar pas en bij het ondertekenen van documenten moet als rang "Luitenant" komen te staan. Net zoals er bij de DSI rangen "Hoofdagent" (zie foto 4 en 5)
- [ ] Alle essentiële documenten toevoegen aan /docu (zie foto 6)
- [ ] De EUP van de BSB zou veranderd moeten worden naar de volgende nummertjes (foto 7)
- [x] Toevoegen van "WEAPON_FLARE" aan de wapenkamer van de DSI en BSB 

Foto 1: 
![image](https://user-images.githubusercontent.com/72617118/111232957-65b3f280-85ec-11eb-80f7-cb70c385fa24.png)

Foto 2 (wapenkamer DSI): 
![image](https://user-images.githubusercontent.com/72617118/111233014-7bc1b300-85ec-11eb-8780-a42d3792e697.png)

Foto 3 (huidige wapenkamer BSB): 
![image](https://user-images.githubusercontent.com/72617118/111233039-84b28480-85ec-11eb-9286-01f2b474c4c8.png)

Foto 4: 
![image](https://user-images.githubusercontent.com/72617118/111233069-972cbe00-85ec-11eb-80ac-d8a520fa8246.png)

Foto 5: 
![image](https://user-images.githubusercontent.com/72617118/111233098-a449ad00-85ec-11eb-8a4a-d57d88159f23.png)

Foto 6: 
![image](https://user-images.githubusercontent.com/72617118/111232931-546ae600-85ec-11eb-8c28-3d06902d090d.png)

Foto 7:
![image](https://user-images.githubusercontent.com/72617118/111888924-3bde3f80-89e1-11eb-93ea-4f4259f80777.png)

**Wat lost deze feature op?**

Het aanpassen van deze features lost enkele mankementen op die de BSB heren momenteel hebben. Tevens hebben ze (grotendeels) hetzelfde werk als de heren van het AOT waardoor ze ook dezelfde spullen / materialen nodig hebben. 
Doordat er momenteel een aantal van deze features missen kunnen zij bijvoorbeeld hun werk als Klu. zijnde niet goed kunnen uitvoeren.
Tevens hebben ze geen dekmantel gezien hun rang zichtbaar is op de Kmar pas en bij het ondertekenen van documenten.

**Comment by Willem-Dekker** [comment]
zie #412

**Comment by Willem-Dekker** [comment]
is dit overlegt met billy?

**Comment by Willem-Dekker** [comment]
![image](https://user-images.githubusercontent.com/16556575/111274907-dc291280-8635-11eb-81fd-1a3918bda249.png)
![image](https://user-images.githubusercontent.com/16556575/111274975-ec40f200-8635-11eb-93b1-5077697e7b92.png)
![image](https://user-images.githubusercontent.com/16556575/111275210-36c26e80-8636-11eb-9622-60c3547dfc50.png)

**Comment by Willem-Dekker** [comment]
meer documenten kan niet is niet op rang dit zijn politie documenten

**Comment by Willem-Dekker** [comment]
Bank-, winkel- en juwelier overval meldingen: is alleen op oproep basis is het nu ook bij politie DSI krijgt deze niet standaart

**Comment by Willem-Dekker** [comment]
Kogelwerend vest 1 van de politie toevoegen aan de BSB eup (zie foto 1) welke optie in eup is dit?

**Comment by Willem-Dekker** [comment]
Vliegtuigen/helikopters kunnen zien op de rader: is ook al  gedaan en dsi ziet dit ook niet uit dienst

**Comment by timfloors** [comment]
> 
> 
> Bank-, winkel- en juwelier overval meldingen: is alleen op oproep basis is het nu ook bij politie DSI krijgt deze niet standaard

ze krijgen alsnog de melding wel alleen dit werk op dit moment nog niet bij de bsb rang, het is dan aan de ovdp om de dsi eropaf te sturen

**Comment by Willem-Dekker** [comment]
> > Bank-, winkel- en juwelier overval meldingen: is alleen op oproep basis is het nu ook bij politie DSI krijgt deze niet standaard
> 
> ze krijgen alsnog de melding wel alleen dit werk op dit moment nog niet bij de bsb rang, het is dan aan de ovdp om de dsi eropaf te sturen

ja en als ze een melding sturen naar  DSI krijgt bsb die ook

**Comment by MartijnMeister** [comment]
> is dit overlegt met billy?

Dit is gevraagd vanuit de BSB en ga er vanuit dat zij dit hebben overlegd met Billy

**Comment by MartijnMeister** [comment]
> EUP uit dienst moet al kunnen

Ga ik dan nogmaals even navragen, gezien het wel is aangevraagd omdat het ‘niet’ zou kunnen

**Comment by MartijnMeister** [comment]
> meer documenten kan niet is niet op rang dit zijn politie documenten

Het is nu alleen zo dat een hOvj die op de kmar rang staat niet de standaard doorzoekingsbevelen heeft

**Comment by Willem-Dekker** [comment]
> > is dit overlegt met billy?
> 
> Dit is gevraagd vanuit de BSB en ga er vanuit dat zij dit hebben overlegd met Billy

het werkt alleen niet voor een meter, gewoon in en uit dienst gaan

**Comment by MartijnMeister** [comment]
> Bank-, winkel- en juwelier overval meldingen: is alleen op oproep basis is het nu ook bij politie DSI krijgt deze niet standaart

DSI krijgt deze naar mijn weten wel altijd aangezien zij hun ook normale politiediensten draaien. Enkel krijgen ze deze niet buiten dienst wat logisch is.

**Comment by Willem-Dekker** [comment]
> > is dit overlegt met billy?
> 
> Dit is gevraagd vanuit de BSB en ga er vanuit dat zij dit hebben overlegd met Billy

ervaring uit het verleden zegt mij dat dit niet zo is

**Comment by MartijnMeister** [comment]
> Vliegtuigen/helikopters kunnen zien op de rader: is ook al gedaan en dsi ziet dit ook niet uit dienst

Dit moet ook enkel indienst. Werd ook aangevraagd aangezien ze het alsnog niet zouden kunnen zien. Ga ik ook nog eens navragen.

**Comment by MartijnMeister** [comment]
> Kogelwerend vest 1 van de politie toevoegen aan de BSB eup (zie foto 1) welke optie in eup is dit?

In de politie eup heb je “kogelwerend” en “zware vest”. Het gaat hier dan om “kogelwerend”.

**Comment by MartijnMeister** [comment]
> > > is dit overlegt met billy?
> > 
> > 
> > Dit is gevraagd vanuit de BSB en ga er vanuit dat zij dit hebben overlegd met Billy
> 
> het werkt alleen niet voor een meter, gewoon in en uit dienst gaan

Ik neem aan dat je hierbij uitdienst EUP bedoeld?

**Comment by Willem-Dekker** [comment]
> > > > is dit overlegt met billy?
> > > 
> > > 
> > > Dit is gevraagd vanuit de BSB en ga er vanuit dat zij dit hebben overlegd met Billy
> > 
> > 
> > het werkt alleen niet voor een meter, gewoon in en uit dienst gaan
> 
> Ik neem aan dat je hierbij uitdienst EUP bedoeld?

ja

**Comment by MartijnMeister** [comment]
> Kogelwerend vest 1 van de politie toevoegen aan de BSB eup (zie foto 1) welke optie in eup is dit?

![image](https://user-images.githubusercontent.com/72617118/111317303-51abd780-8664-11eb-9aa1-eb95b6a4ce5f.png)

**Comment by MartijnMeister** [comment]
> EUP uit dienst moet al kunnen

Deze foutmelding komt in beeld wanneer /eup wordt getypt buiten dienst

![image](https://user-images.githubusercontent.com/72617118/111317379-66886b00-8664-11eb-91f7-e606b82c3c95.png)

**Comment by MartijnMeister** [comment]
> > > is dit overlegt met billy?
> > 
> > 
> > Dit is gevraagd vanuit de BSB en ga er vanuit dat zij dit hebben overlegd met Billy
> 
> ervaring uit het verleden zegt mij dat dit niet zo is

Heb dit even nagevraagd waarna is aangegeven dat dit in overleg met Smith is gegaan (BSB leiding)

**Comment by MartijnMeister** [comment]
> > Vliegtuigen/helikopters kunnen zien op de rader: is ook al gedaan en dsi ziet dit ook niet uit dienst
> 
> Dit moet ook enkel indienst. Werd ook aangevraagd aangezien ze het alsnog niet zouden kunnen zien. Ga ik ook nog eens navragen.

Fox. (Dirk Schipper) heeft dit even voor me nagekeken en kwam tot de conclusie dat dit nog niet het geval is

**Comment by Willem-Dekker** [comment]
Vliegtuigen/helikopters kunnen zien op de rader (groene cirkel)

zou fixed moeten zijn, en als bonus kunnen ze nu ook een wapen uit de kofferbak halen uit dienst

**Comment by Willem-Dekker** [comment]
welke outfit van bsb wat is daar de naam van?

**Comment by Willem-Dekker** [comment]
wat is het nummer van dat vest in foto 1? en bij welke outfit

**Comment by MartijnMeister** [comment]
> wat is het nummer van dat vest in foto 1? en bij welke outfit

Het zou gaan om de volgende nummers:
Kogelvrij vest 1: 12
Kogelvrij vest 2: 3

Dit kogelvrije vest zou moeten toegevoegd worden onder het kopje "Accessoires/Vesten", dus niet in een outfit zelf.

**Comment by MartijnMeister** [comment]
> welke outfit van bsb wat is daar de naam van?

Het gaat om het outfit genaamd "BSB". Deze staat onder het kopje "Dienst Speciale Interventies"

**Comment by NoahR21-7** [comment]
Kan er nog iets geregeld worden ivm met /eup uitdienst?

**Comment by Willem-Dekker** [comment]
ja in en uitdienst gaan voor dat je het wil gebruiken

**Comment by NoahR21-7** [comment]
Als ik in en uitdienst gaat en ik doe /eup krijg ik ''You are not permitted to use this command''

**Comment by FoxOTF** [comment]
Tevens was er een github commit over de feature van de helikopters/ helikopters op de radar kunnen zien. Alleen is dit nog niet mogelijk voor ons op de BSB rang om te zien. Dit word dan heel lastig voor de BSB leden die tevens ook KLu zijn om hun taken te vervullen
