### ISSUE TITLE
Uitschakelen emotes politiebureau

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#471]
**Beschrijf zo duidelijk mogelijk de feature**
Helaas maken spelers nog steeds misbruik van emotes om uit hun cel te komen en zo bijvoorbeeld hun appartement leeg te halen voordat er een huiszoeking kan plaatsvinden. Daarom was er het idee om emotes uit te schakelen in het politiebureau voor niet-politie medewerkers. Hierdoor kan de politie dus nog wel steeds emotes gebruiken voor roleplay maar kunnen spelers het niet meer misbruiken om eruit te komen.

**Wat lost deze feature op?**
Ontsnappen uit gevangenis d.m.v. emote abuse omdat dit helaas moeilijk te bewijzen is zonder videdobewijs.

**Comment by Willem-Dekker** [comment]
Is volgens mij geen issue meer zo wel graag heropenen
