### ISSUE TITLE
De motor:  africat, achterwiel veranderd niet mee in pimpshop.

### ISSUE THREAD

**Issue by Bladerdeeg** [Tedeapolis/development#472]
Omschrijf de bug: Het achterwiel van de africat veranderd niet mee als je de wheels aanpast, Verder zijn alle wheels die je kan selecteren auto wielen inplaats van motor wielen waardoor ze geen spaken hebben

Hoe kunnen wij de bug reproduceren: Met de africat naar de pimpshop gaan en de wheels aanpassen naar een willekeurig wiel.

Normaal gedrag: Dat beide wielen veranderen naar een andere.

Screenshots en/of logbestanden: ( https://prnt.sc/10nl5ao )

Impact op de server: GEEN, is wel jammer van de motor.

**Comment by Willem-Dekker** [comment]
kan niet gefixt worden is gta
