### ISSUE TITLE
Missende muur

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#474]
# Waar zit het in EUP, interiors of retextures ?
Interiors / retextures

# Link naar issue of coördinaten naar de plek
X: -1386.15 Y: -585.79 Z: 30.020 H: 300.20

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
De muur op deze locatie staat er niet daadwerkelijk waardoor je er doorheen kan lopen. Dit zal resulteren in het feit dat je door de map heen valt.
![image](https://user-images.githubusercontent.com/72617118/111556801-a6963d80-878b-11eb-878f-69e55d82ee55.png)

# Wat is de toegevoegde waarde?
Voorkomt eventueel abuse van de locatie zodat mensen het niet als verstopplek gebruiken

**Comment by brothasx** [comment]
Fixed, deze word spoedig naar de main gezet
