### ISSUE TITLE
Muur achter de club op postcode 634 is onzichtbaar

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#476]
**Op postcode 634 achter de club is de muur niet goed, waardoor je door de map valt**

**Je kan met een auto achter de club tegen richting de muur aanrijden en dan kom je de onzichtbare muur tegen, zodra je hieroverheen springt val je door de map**

**Muur zou de hitbox moeten hebben op plaats van de texture**

**Heb geen screenshots of bestanden, Heb het zelf wel uitgetest**

**Minimale impact voor de server, maar haalt realisme weg.**

**Comment by brothasx** [comment]
Fixed, deze word spoedig naar de main gezet
