### ISSUE TITLE
Toevoegen kogelwerende vesten aan uitdienst eup van de DSI

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#479]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel is het als DSI uitdienst niet mogelijk om een kogelwerend / zwaar vest aan te trekken. Dit komt echter wel van pas als je uitdienst betrokken bent bij een schietincident o.i.d. 
Graag zouden we daarom willen zien dat de volgende vesten worden toegevoegd aan de uitdienst EUP van de DSI (indien mogelijk ook bij de BSB rang).

Kogelwerend vest 1: 12
Kogelwerend vest 2: 3

![image](https://user-images.githubusercontent.com/72617118/111889237-0555f400-89e4-11eb-8d5d-a996fbf54e70.png)

Van onderstaande vest kan ik de nummertjes niet vinden. Graag wel toevoegen indien mogelijk: 

![image](https://user-images.githubusercontent.com/72617118/111889806-67aef480-89e4-11eb-896d-a23a27b71a97.png)

**Wat lost deze feature op?**
DSI agenten kunnen zich uitdienst makkelijker identificeren als agent in een situatie waarbij ze hun vuurwapen moeten trekken. Dit voorkomt misverstanden en is tevens realistischer gezien een uitdienst DSI agent zich niet in één keer gaat omkleden naar AOT terwijl er mensen om hem heen staan.

**Comment by Willem-Dekker** [comment]
@walvisgedaan lukt dit

**Comment by walvisgedaan** [comment]
Dit is al gefixt
