### ISSUE TITLE
criminelen kunnen niet meer fouilleren

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#48]
via f6 menu kan je niet meer fouilleren

**Comment by Willem-Dekker** [comment]
kan je log bestanden hier van sturen?

**Comment by Willem-Dekker** [comment]
lijkt iets server side mis te gaan, ik kan zo niet zien wat er mis gaat misschien dat @niekschoemaker hier meer mee kan

**Comment by Willem-Dekker** [comment]
met dank aan @niekschoemaker werkt het nu weer
