### ISSUE TITLE
Helikopter opslag aanpassingen

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#480]
**Beschrijf zo duidelijk mogelijk de feature**
Dit was besproken 2 weken geleden in staffoverleg en dit is het aangepaste lijstje
![afbeelding](https://user-images.githubusercontent.com/56398140/111915595-62e75080-8a77-11eb-9cde-2802f5edda1f.png)

**Wat lost deze feature op?**
Het gezeik dat helikopters te weinig slag hebben voor de prijzen die ze kosten

**Comment by timfloors** [comment]
@niekschoemaker er was vorig staffoverleg gezegd dat jij naar de opslagen en snelheden ging kijken, hierbij nog even een kleine voorbeeld van de opslag :D

**Comment by Willem-Dekker** [comment]
Is dit al gedaan?

**Comment by timfloors** [comment]
nee hier is nog niks mee gebeurd

**Comment by Willem-Dekker** [comment]
zit er morgen in
