### ISSUE TITLE
kmar boten nog steeds hetzelfde

### ISSUE THREAD

**Issue by Billyaes** [Tedeapolis/development#481]
**Omschrijf de bug**
wanneer je de kmar boten wilt despawnen in de rode cirkel doet die dat nog steeds niet.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
je zelf op kmar functie zetten. eender welke kmar boot nemen en proberen te despawnen in de rode cirkel.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
de boten zouden moeten despawnen

**Screenshots en/of logbestanden**
/

**Impact op de server**
/

**Comment by Willem-Dekker** [comment]
er is dus geen impact op de server, en er is geen bewijs van?

**Comment by Billyaes** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/80492676/112507678-22e1df80-8d8f-11eb-8c0c-ff54ea9d7d5c.png)

impact op de server is dat al de boten nu rondom rond liggen bij de havens.  screenshot heb ik gestuurd van het f8 console weet niet of je daarmee genoeg hebt? als je nog iets nodig hebt hoor ik het wel. thanks!

**Comment by niekschoemaker** [comment]
Is ondertussen gefixed
