### ISSUE TITLE
Geen wapens kunnen plaatsen in werkvoertuigen van uitzendbanen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#482]
**Beschrijf zo duidelijk mogelijk de feature**

Op dit moment is het mogelijk om wapens te storen in de voertuigen van de uitzendjobs, zoals de bo-rent bus, mijnvrachtwagen en olietruck! de mogelijkheid om andere dingen dan alleen wat er in dat voertuig hoort moet uitgezet worden zodat er in ieder geval geen wapens meer in die voertuigen opgeslagen kan worden

**Wat lost deze feature op?**

Criminelen kunnen hier misbruik van maken aangezien de politie deze voertuigen niet ziet en dit valt onder powergaming en er word misbruik van gemaakt!

**Comment by Willem-Dekker** [comment]
https://wetboek.tedeapolis.nl/apv/#artikel-29-juist-gebruik-van-baan-voertuigen

**Comment by TDA-SanderD** [comment]
Dat klopt inderdaad Willem maar dit is haast niet te controleren. Dit valt enkel te controleren door mensen die database toegang hebben en dat wordt niet bij elke schietpartij/overval gedaan.

**Comment by Willem-Dekker** [comment]
Is dit nog een issue?
