### ISSUE TITLE
Noodknop politie

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#483]
**Beschrijf zo duidelijk mogelijk de feature**
Bij het korpsleidingoverleg hebben we besproken dat we graag zien dat de noodknop enkele aanpassingen krijgt. 
We zouden graag twee opties zien:
- De noodknop wordt twee keer achtereenvolgens ingedrukt. Hierbij maakt het niet uit hoe lang de noodknop ingedrukt wordt. Dan wordt de noodknop verstuurd.
- De noodknop wordt voor twee seconden ingedrukt. De noodknop wordt dan verstuurd. 
- Annuleren zodra de noodknop langer dan drie seconden wordt ingedrukt dient uitgeschakelt te worden. 
- Mogelijkheid om acties uit te voeren, wapens te pakken terwijl de noodknop ingedrukt wordt. De noodknop hoeft maar met 1 hand ingedrukt te worden. 

**Wat lost deze feature op?**
Een onrealistische, niet bruikbare noodknop. De noodknop is er namelijk tijdens noodsituaties. Momenteel werkt hij niet waarvoor hij bedoeld is. Er wordt ook geen rekening gehouden met de reactietijd die nodig is om de toetsencombinatie in te drukken.

**Comment by Willem-Dekker** [comment]
dit is gekomen ivm misbruik

**Comment by TDA-SanderD** [comment]
Misbruik in de zin van? Ik heb er namelijk nooit klachten over gehoord. Wellicht kun je dit ook navragen bij Nick. Hij heeft hier ook akkoord voor gegeven.

**Comment by TDA-SanderD** [comment]
Ik bedoel hiermee trouwens ook niet dat de animatie weg moet. Je ziet alsnog gewoon dat de noodknop in wordt gedrukt als crimineel bijvoorbeeld. Als de noodknop wordt gebruikt om locaties te verzenden dan zullen we hier ook een warning en een strike voor geven binnen het korps.
