### ISSUE TITLE
Baan Accepteren command

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#484]
**Beschrijf zo duidelijk mogelijk de feature**
De vraag of er een mogelijkheid is dat de functionaliteit word toegevoegd als jij door een baas van een job aan een job word toegevoegd dat je /acceptjob (voorbeeld) moet doen voordat je de job ook echt krijgt

**Wat lost deze feature op?**
Omdat je op dit moment gewoon aangenomen kunt worden door mensen, zowel expres als per ongeluk. hiermee voorkom je dus ook mogelijk meer het overtreden van de jobhopregel aangezien ze in beeld zien dat ze de rang echt krijgen

**Comment by Willem-Dekker** [comment]
Ik zie niet echt een mogelijkheid hier voor om dit makkelijk er in te zetten zonder grote aanpassingen aan de core en zie het nut er ook niet echt van om hier veel tijd in te steken. 

Naast het feit dat zowel werknemer als werkgever verantwoordelijkheid hebben in het job hob verhaal.

**Comment by timfloors** [comment]
als het teveel tijd kost dan is het gewoon niet haalbaar dan laten we dit liggen.

dit was er meer voor omdat elke baas van een job nu rechten heeft om elk random persoon in de stad de job te geven
