### ISSUE TITLE
Wielklemmen Politie

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#486]
**Beschrijf zo duidelijk mogelijk de feature**
De mogelijkheid of de politie toegang krijgt tot een soort van wielklemmen om dan voertuigen vast te zetten op plaats

**Wat lost deze feature op?**
Dit kunnen ze dan gebruiken op hotspots waar voertuigen vaak foutparkeren, kenneth wou hier een keer naar kijken is in overleg met hem hier toegevoegd :D

**Comment by ToyStoner** [comment]
Is het dan geen beter idee om die auto's in beslag te nemen? Want door er wielklemmen op te zetten blijft het voertuig staan. Wat dus ook nog een serverperformance impact kan hebben. Ook denk ik dat agenten niet snel naar een melding gaan voor een wielklem los te maken. Ook word een wielklem gebruikt om ervoor te zorgen dat de overtreder niet zijn voertuig pakt tussen het moment van de constatatie en het wegslepen van het voertuig. (als ik het goed gelezen heb 😉 ) 

--> Ik denk dus dat het mss beter is om de auto direct in beslag te nemen. En dan kunnen de overtreders hem voor 10%  ipv 20% van de inkoopprijs terugkopen. met een max van 50k boete. (dit is dus het bedrag voor het terug kopen van het voertuig) 

--> Wat jullie ook kunnen doen is dat iedere burger 2x een waarschuwing kan krijgen voor het fout parkeren.  Bij een 3x keer fout parkeren van voertuig, het voertuig in beslag nemen.

--> Een probleem is hier wel als u bent dood gegaan in een scenario en uw auto staat nog op de baan kunt u die niet meer verplaatsen en kan hij dus onterecht in beslag worden genomen.
