### ISSUE TITLE
Optie om kenteken van de Africat te kunnen verwijderen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#487]
**Beschrijf zo duidelijk mogelijk de feature**
BIj de modshop invoegen de optie om het kenteken te kunnen verwijderen op de Africat (offroad motor) 

**Wat lost deze feature op?**
Deze motor is de enige die offroad is opgewassen tegen de veel te snelle offroad politie motoren, daarbij kan dit een beetje de sanchez en manchez weghalen en als het op de zx10 wel kan zou dit voor deze motor ook geen probleem moeten zijn?

**Comment by TDA-SanderD** [comment]
Dan is het wel zeer waarschijnlijk dat dit een illegaal voertuig wordt en dat hij dan gelijk inbeslaggenomen wordt. Het voertuig is momenteel nog wel geschikt om op de openbare weg te rijden volgens de verkeersrichtlijnen, zonder kenteken helaas niet meer.

**Comment by Willem-Dekker** [comment]
als dit niet standaard kan kunnen wij dit denk ik ook zo niet maken.

**Comment by Willem-Dekker** [comment]
dan zou de modelmaker het moeten doen wij bij dev kunnen hier niet heel veel mee
