### ISSUE TITLE
Aanpassingen bij de ANWB

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#488]
- [x] Extra bevestiging bij confisceren ANWB menu.

- [ ] Delay bij meldingen maken in de ANWB-meldkamer. (als dit mogelijk is) 

- [ ] Als er 3 of minder ANWB'ers aanwezig zijn en mensen rijden ANWB HB binnen dat ze een meldingen krijgen met je kan /repareer doen.

**Comment by Willem-Dekker** [comment]
die laatste kan niet ik kan niet maken dat je dat zien en op het hb kan je ook geen /repareer doen

**Comment by Willem-Dekker** [comment]
zit al een rate limiter op meldingen

**Comment by Willem-Dekker** [comment]
de bevestiging zit er in na restart

**Comment by Willem-Dekker** [comment]
dacht dat het 1x per min of 5 min was moet ik kijken als ik thuis ben van werk

**Comment by DeStefanoKiller** [comment]
> dacht dat het 1x per min of 5 min was moet ik kijken als ik thuis ben van werk

Had je hier nog naar gekeken?

**Comment by DeStefanoKiller** [comment]
> dacht dat het 1x per min of 5 min was moet ik kijken als ik thuis ben van werk

Reminder :) @Willem-Dekker
