### ISSUE TITLE
Bodycam KMAR

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#489]
# Waar zit het in EUP, interiors of retextures ?
EUP

# Link naar issue of coördinaten naar de plek
-

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Momenteel zit er geen bodycam in de EUP van de KMAR. De bodycam van de politie moet ook worden toegevoegd bij de KMAR.

# Wat is de toegevoegde waarde?
Dat er minder gezeur is over het gebruiken van het bodycam beelden.

**Comment by Willem-Dekker** [comment]
Zit er in na de restart
