### ISSUE TITLE
benzine bug

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#49]
als mensen hun voertuig pakken uit de garage (blokkenpark) dan zegt het systeem dat er brandstof in zit maar ze kunnen hun motor niet starten . ik heb nu een jerrycan gekocht en mensen geholpen door hun tank een beetje te vullen , daarna kunnen ze hem weer starten . 

ik heb gekeken of er iets verschijnt in het f8 menu maar kan daar niks in terug vinden .

**Comment by Willem-Dekker** [comment]
zou gefixed moeten zijn
