### ISSUE TITLE
meer sloten op de isoleercellen

### ISSUE THREAD

**Issue by Taker1987** [Tedeapolis/development#490]
**Beschrijf zo duidelijk mogelijk de feature**
er zijn 6 of 8 isoleercellen maar er zijn maar 2 sloten . 
zo kunnen er meer man in de isoleercellen geplaatst worden 

de kmar wou er net 3 in plaatsen maar dit ging dus helaas niet . vandaar dit verzoek

**Comment by Willem-Dekker** [comment]
Zit er na restart in
