### ISSUE TITLE
Rijbewijs halen bug

### ISSUE THREAD

**Issue by DevinKoedam** [Tedeapolis/development#491]
**Omschrijf de bug**
Wanneer je rijbewijs net in beslag is genomen hoor je normal 24 uur te wachten, maar als je 2500 op zak hebt en je klikt op enter kan je hem alsnog halen terwijl er een timer staat

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je rijbewijs inbeslag laten nemen 2500 pinnen en je rijbewijs probeeren te halen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
er zal een message te horen staan van (je moet nog .... uur wachten voordat je je rijbewijs kan halen

**Screenshots en/of logbestanden**
n.v.t

**Impact op de server**
Mensen gaan hierdoor veel eerder kunnen rijden nadat ze hun rijbewijs in beslag hebben laten nemen

**Comment by niekschoemaker** [comment]
Is gefixed na volgende restart.
