### ISSUE TITLE
Lightbars niet te horen voor normale burgers

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#494]
**Omschrijf de bug**
Momenteel is het zo dat personen zonder de DSI, BSB, HRB, etc. rang geen lightbar sirenes kunnen horen. Kortgezegd is het geluid van de sirene enkel te horen voor mensen die toegang hebben tot dit command. 
DSI --> Zet lightbars + sirene aan
Burgers --> Zien de lightbars maar horen geen sirene

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Voor reproductie van deze bug heb je twee personen.
Persoon 1 moet staan op bijvoorbeeld de DSI rang en zet de lightbars + sirenes aan
Persoon 2 moet staan op een normale job en moest luisteren of deze de sirenes hoort

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zou iedereen de sirenes van de lightbars moeten kunnen horen.

**Screenshots en/of logbestanden**
https://youtu.be/KmjGbsnXU4s 
https://youtu.be/dKEZSrN-j-o

**Impact op de server**
Klein - De impact is niet dusdanig groot. Het is enkel vervelend dat er overbodige botsingen ontstaan doordat mensen je niet horen komen aanrijden als je Prio 1 naar een melding rijdt.

**Comment by niekschoemaker** [comment]
Horen mensen met lightbar toegang (dus dsi, kmar etc) de sirenes wel buiten het voertuig?

Dus is dit voertuig gerelateerd (personen die buiten het voertuig staan als sirene aangezet wordt) of is dit rang gerelateerd?

**Comment by MartijnMeister** [comment]
> Horen mensen met lightbar toegang (dus dsi, kmar etc) de sirenes wel buiten het voertuig?
> 
> Dus is dit voertuig gerelateerd (personen die buiten het voertuig staan als sirene aangezet wordt) of is dit rang gerelateerd?

Ik heb dit even getest en dit was ook niet te horen voor iemand die wel een DSI rang had op dat moment.
Zelf merk ik dat ik, als ben ik indienst, deze sirenes de ene keer wel hoor en de andere keer niet.
Kenneth gaf hierbij aan dat het zou gaan om one sync wat dit probleem veroorzaakt.
