### ISSUE TITLE
Extra mogelijkheden om een bank te overvallen

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#495]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel zijn er in totaal 8 banken in de stad waarvan er 5 te overvallen zijn. De overige 3 hebben wel het volledige interieur echter zijn hier de cirkels om de bank te overvallen niet aanwezig. De rode cirkels om te hacken zijn niet aanwezig en er ligt geen geld in de bank.
Nadat ik hier met Kenneth over heb gesproken gaf hij aan dat hiervoor een github issue aangemaakt kon worden.

De coördinaten van de 3 banken zijn:
- X: -351.06 Y: -49.34 Z: 49.04 H: 339.53
- X: -1213.58 Y: -329.99 Z: 37.78 H: 205.40
- X: 1175.52 Y: 2705.52 Z: 38.09 H: 97.79

![image](https://user-images.githubusercontent.com/72617118/113496148-f8aec100-94f6-11eb-8afe-202a27ca6c76.png)

**Wat lost deze feature op?**
Er ontstaan door deze toevoeging extra mogelijkheden voor criminelen om andere banken te overvallen waardoor dit iets meer gevarieerd wordt. Tevens zorgt het voor meer vluchtmogelijkheden en mogelijk andere roleplays.
De diversiteit zal hiermee dus verhoogd worden.

**Comment by niekschoemaker** [comment]
Is toegevoegd
