### ISSUE TITLE
K Menu werkt niet altijd

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#496]
**Omschrijf de bug**
Als je soms in de stad komt, en je wilt maskers of hoeden afdoen met K menu, gaat dit niet altijd waardoor je dus weer moet knipperen dan doet die het wel. Kort gezegd het K menu loopt vast

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Inloggen kijken of je met K menu een masker op of af kan doen zo niet dan nogmaals proberen
https://media.discordapp.net/attachments/828594948705222686/828595196061155388/unknown.png
Zodra je deze error in beeld krijgt en probeert te joinen dan zou het dus niet werken zelfde geld dus voor omkleden

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou gelijk je masker op en af moeten kunnen

**Screenshots en/of logbestanden**
[CitizenFX_log_2021-04-04T221145.log](https://github.com/Tedeapolis/development/files/6255612/CitizenFX_log_2021-04-04T221145.log)
(hoop dat deze de goede is want ik had het net nog gehad )

**Impact op de server**
Redelijk wat mensen moeten reloggen hiervoor, krijg er ook regelmatig reports over

**Comment by Willem-Dekker** [comment]
die curl error kunnen we niet heel veel aan doen

**Comment by Willem-Dekker** [comment]
K menu is meestal als de items niet in die outfit zitten dus dan is het niet raar dat je deze niet kan op en af doen

**Comment by DevvTDA** [comment]
Ah okee, ja nee maar bijvoorbeeld ik zelf hem masker en helm apart en afentoe als ik die error krijg dan kan ik het ook niet opzetten ook als ik hem al op heb kan die ook niet af

**Comment by niekschoemaker** [comment]
Dit met de maskers is idd een issue, dit is een bij issue van de hele queue issue, kwam door random playerDropped calls op random momenten van spelers die nog online waren, dit zou nu opgelost moeten zijn.
