### ISSUE TITLE
Justitie > Justitie 2.0

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#497]
Bij het Ministerie zijn wij van mening dat er een aantal zaken veranderd dienen te worden zodat het systeem nog beter gaat werken. We zijn inmiddels al weer enige tijd bezig in onze huidige vorm en merken dat bepaalde delen die Bram voor ogen had niet echt uitvoerbaar zijn zonder te weten wat zijn gedachte daarachter was. Momenteel hebben wij het idee dat we klaar zijn voor een Justitie 2.0 om zo verder door te kunnen groeien in de stad.
Uiteraard zijn de aankomende MEOS updates al een mooie vooruitgang, maar graag zouden wijzelf ook andere veranderingen zien. Ik zal hieronder eerst in steekwoorden aangeven wat het inhoudt en later per punt een uitgebreide uitleg geven. 

-	Taakverruiming 
-	Herindeling van de rangen met bijbehorende lonen 
-	Snelrechters
-	Mogelijk verbouwing

### Taakverruiming
In sommige opzichten voelt het op bepaalde momenten aan alsof wij alleen een advocatenbureau runnen i.p.v. een geheel ministerie, daarom zouden wij graag extra taken op ons krijgen. 
Hierbij hadden wij zelf het idee om een KVK-afdeling te krijgen waarbij wij vergunningen in de stad voor bepaalde zaken kunnen afgeven tegen betaling uiteraard. Zodoende genereert Justitie ook weer geld terug de pot in. Een voorbeeld hiervan is een vergunning voor een cardealer die dan elke maand voor een X bedrag vernieuwd dient te worden. Daartegenover staat dan dat wij een wet kunnen maken voor mensen die zonder vergunning op openbare plaatsen auto’s verhandelen zodat de politie hierop ook kan handhaven. Dat voorkomt dan ook weer een wildgroei van autohandelaren. 
Daarnaast zou een KVK afdeling ervoor zorgen dat spelers waar zij terecht kunnen voor vergunningen en zodoende scheelt dat ook weer tickets voor staff hierover. Uiteraard zal er niet meegewerkt worden aan vergunningen voor overvallen etc. 

Mochten er nog andere goede ideeën qua taken zijn dan horen wij dit ook graag uiteraard. 

### Herindeling rangen
Met onze huidige rangen zit er een geen logische volgorde in hoe mensen nou doorgroeien binnen Justitie. Daarnaast merken wij ook dat er een aantal salarissen nogal vreemd staan in de rangvolgorde. Vandaar dat wij de rangen graag in deze volgorde zouden zien, zodat er een logische doorgroei mogelijkheid is binnen Justitie. 

![organo](https://user-images.githubusercontent.com/77858957/113570137-0ad25180-9614-11eb-9411-c9d730951a9c.PNG)
De functies met de rode kleur hebben de dagelijkse leiding over Justitie.
 
**Taakbeschrijving per functie:** 

_Minister_: De minister is de eindverantwoordelijke van Justitie en Veiligheid. De minister is verder verantwoordelijk voor een bepaald beleidsterrein of zelfs een combinatie van beleidsterreinen. De minister is bijvoorbeeld verantwoordelijk voor het algemene beleid van de Justitie en Veiligheid. Denk hierbij aan het financieel beleid, aanbesteding beleid, wetgeving, personeelsbeleid etc.
Een Minister zal zelf geen advocaten zaken oppakken zie hiervoor het punt snelrechters.
_Salaris: 1500
Maximaal 2 personen_

_Staatssecretaris_: De staatssecretaris is de rechterhand van de minister. Een staatssecretaris ondersteunt de minister en kan bij afwezigheid volledig de taken krijgen at de minister normaal krijgt. Een staatssecretaris kan verder ook een specifiek beleidsterrein onder hun hoede krijgen.
Een Staatssecretaris zelf geen advocaten zaken oppakken zie hiervoor het punt snelrechters.
_Salaris: 1200
Maximaal 1 persoon_

_Deken van de orde_:  Neemt mensen aan en houdt toezicht op de advocaten. Gaat over promoties onder zijn rang. Kan advocaten op non-actief stellen. De Deken mag handhaven over advocaten. Bevordert de kwaliteit van advocaten. Neemt klachten over advocaten in behandeling. 
Promotie tot Deken gebeurt door rang(en) boven de Deken. De Deken mag pro-deo zaken opnemen als niemand aanwezig is.
_Salaris: 950
Maximaal 1 persoon_

_Afgevaardigde_:
 - Zelfde taken als een Senior advocaat
- Vertegenwoordigd verder de rangen onder de afgevaardigde in besloten vergaderingen
 - Houdt de moraal van de advocaten in de gaten
 - Functioneert als een soort van vertrouwenspersoon van de advocaten
 - Monitoren het imago van Justitie 
- Heeft inspraak in promoties van Senior Advocaten 
- Houdt kwaliteit van advocaten in de gaten 
Promotie tot afgevaardigde wordt gedaan door middel van stemmen door senior advocaten, advocaten en stagiaires. Dit komt omdat de afgevaardigde hun gaat vertegenwoordigen.
_Salaris: 750
Maximaal 3 personen_

_Juridisch Medewerker_: 
- Zelfde taken als een senior advocaat 
- Doet literatuuronderzoek m.b.t. wetgeving 
- Past het wetboek aan waar nodig 
- Kijkt actief naar gaten in het wetboek en handelt waar nodig. 
Promotie tot juridisch medewerker gebeurt door een interne sollicitatie of indien je voor de functie gevraagd wordt.
_Salaris: 750
Maximaal 4 personen_

_Senior Advocaat_: Een Senior Advocaat heeft dezelfde taken als bij een normale advocaat. Echter heeft de Senior advocaat een aanvullend taak, namelijk het begeleiden van advocaat stagiaires. Het moet gezien worden als een soort van trainer van de stagiair advocaten. Een Senior advocaat dient verder ook verslag te schrijven stagiaires en dan al niet aanbevelen tot promotie door middel van het resultaat van het examen van de stagiair onder zijn toezicht. 
Een promotie tot senior advocaat kan worden gedaan door een aanbeveling op basis van de Senior Advocaten, afgevaardigde en of de OvA. De promotie wordt uitgevoerd door de leiding van Justitie en Veiligheid.
_Salaris: 600
Geen maximaal aantal personen_

_Junior Advocaat_: Een Junior Advocaat is vrij om te doen wat hij wil. Hij kan zelf pro deo leiden en een eigen klantenkring bouwen. Het is een volwaardig lid van het ministerie van Justitie en Veiligheid. Het kan wel eens voorkomen dat een advocaat stagiair met hem moet meelopen. Hierin is hij verplicht om een kort verslag te doen over de stagiair. Dit komt echter nauwelijks voor.
Een promotie tot Junior Advocaat kan worden gedaan door een examen af te leggen. Dit kan zodra de Senior advocaat/Afgevaardigde denkt dat de stagiair klaar is om zelfstandig een zaak te doen wordt de stagiair gepromoveerd naar advocaat.
De stagiair dient als “examen” een eigen strafzaak met succes te weten te behalen. Het examen is een echte strafzaak op het HB onder toezicht van een afgevaardigde/ senior advocaat. De toetsing ligt bij de afgevaardigde en of senior advocaten.
_Salaris: 400
Geen maximaal aantal personen_

_Advocaat stagiair_: Een advocaat stagiaire(e) mag in het begin alleen maar meelopen bij een senior advocaat. Als een senior advocaat niet aanwezig is mag hij meelopen bij een normale advocaat. Het selectieproces zal streng doch rechtvaardig gebeuren. Indien een sollicitant wordt aangenomen, zal het eerst als stagiair moeten beginnen.
_Salaris: 200
Geen maximaal aantal personen_

### Snelrechters
Voor een realistischere trias politica lijkt het ons een goed idee om snelrechters een onderdeel te maken van Tedeapolis. De snel rechters vormen in principe een oordeel van de kleine zaken als het niet tussen de agent en de verdachte uitkomt op het hoofdbureau. De snel rechters zijn een dubbele functie aangezien er niet genoeg werk is om er een zelfstandige functie van te maken. De onpartijdigheid wordt gewaarborgd doordat de snel rechters de leiding van Justitie zijn en bijvoorbeeld individuen die bewezen onpartijdig zijn.
Door het toevoegen van deze functie wordt het voor een verdachte ook een minder grote stap om tegen een vonnis van een agent in bezwaar te gaan. Mocht iemand bezwaar hebben tegen de uitspraak van een snelrechter, dan kan er in echt uitzonderlijke gevallen hoger beroep worden aangetekend zodat er dan een hoge raadslid als rechter over de zaak kan oordelen. 
Naar ons idee bevorderd dit de mogelijkheden in de roleplay en wordt er ook meer gebruik gemaakt van de grote zaal in het gemeentehuis. In het kort kun zou dus De snel rechter oordeelt dus over de wat kleinere zaken. De snel rechter kan natuurlijk ook een straf opleggen.
Mocht er gekozen worden voor de stap naar de snelrechter dan zitten daar griffiekosten aan verbonden, waardoor de pot van Justitie ook weer inkomsten genereerd. Daarnaast kan er van de zaak een samenvatting getypt worden zodat we ook onze eigen echte jurisprudentie in de stad ontwikkelen. 

### Mogelijke verbouwing
Ik weet dat er in het verleden al eens gekeken is naar een verbouwing van het gemeentehuis. Mocht dit mogelijk zijn, dan zou dat uiteraard fantastisch zijn, zodat eventuele snelrecht zaken nog realistischer aanvoelen. Mocht dat niet mogelijk zijn, dan kunnen we met de huidige zaal op een creatieve manier hier ook vast wel gebruik van maken.

**Comment by Willem-Dekker** [comment]
wat moet er aan code aanpassingen gedaan worden?

**Comment by Hellie94** [comment]
Rollen die wegkunnen:

- Secretaris van de orde van advocaten
- Officier van Justitie
- Hoofdofficier van justitie

Nieuwe rolindeling:

- Advocaat stagiair           Salaris 200
- Junior advocaat             Salaris 400
- Senior advocaat            Salaris 600
- Juridisch medewerker   Salaris 750
- Afgevaardigde              Salaris 750
- Deken van de orde       Salaris 950
- Staatssecretaris             Salaris 1200
- Minister                        Salaris 1500

**Comment by Willem-Dekker** [comment]
|naam|salaris|
|---|---|
 |Advocaat stagiair|200|
 |Junior advocaat|400|
 |Senior advocaat| 600|
 |Juridisch medewerker|750|
 |Afgevaardigde|750|
 |Deken van de orde|950|
 |Staatssecretaris|1200|
 |Minister|1500|

**Comment by Willem-Dekker** [comment]
Rollen zitten er morgen in

**Comment by Hellie94** [comment]
Zo te zien is er met 1 naam iets niet goed gegaan. 

Staatssecretaris staat erin als Officier van Justitie. No big deal, maar zou deze nog aangepast kunnen worden? :P

**Comment by Willem-Dekker** [comment]
was dit klaar? geen idee

**Comment by Hellie94** [comment]
Is helemaal afgerond qua 2.0 nu naar 3.0 👍
