### ISSUE TITLE
Lightbar

### ISSUE THREAD

**Issue by DaanDeWit** [Tedeapolis/development#50]
Goedemiddag,

We hebben een tijdje geleden een overleg gehad met het korps en toen heb ik nog even met Nick privé gezeten omtrent een "feature" voor de recherche. Momenteel is het namelijk zo dat DSI-leden door middel van het command /lightbar blauw rode zwaailichten op hun privévoertuigen kunnen zetten. De recherche heeft dit daarentegen niet, terwijl het eigenlijk ook handig zou zijn voor de recherche. 

zou er gekeken kunnen worden naar deze optie, zodat deze ook beschikbaar is voor de recherche? Momenteel hebben rechercheleden standaard de rang "Inspecteur" in-game, maar dan zou het misschien handiger zijn om een aparte rechercherang te maken. Anders kunnen reguliere inspecteurs en hoger het commando namelijk ook gebruiken.
Daarnaast zou het handig zijn dat je vanaf rang Eerste Hoofdcommissaris (voor de korpsleiding die ook DSI zijn) om daar alle features van lightbar bij te gooien. Momenteel kan deze rang dat wel alleen kunnen de lampen niet aan wanneer ze geladen zijn.

**Comment by Willem-Dekker** [comment]
helaas is deze feature niet mogelijk aangezien light-bar veel van de server vraagt
