### ISSUE TITLE
Helicopter spawn kapot bij postcode 2010 (vliegveld)

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#502]
**Omschrijf de bug**
Bij de heli spawn op postcode 2010 (zie foto 1) 

Elke keer als je hier een helicopter uit  de opslag haalt spawned hij met een rood knipperend lampje 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je moet een helicopter uit deze opslag halen op postcode 2010 (zie foto 2)

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou de helicopter in zijn oude toestand (gemaakt) eruit komen en niet rood lampje

**Screenshots en/of logbestanden**
foto1:
![image](https://user-images.githubusercontent.com/82154593/114021157-acee7580-9870-11eb-9137-b7aa7ad37f11.png)

foto 2: 
![image](https://user-images.githubusercontent.com/82154593/114021132-a4963a80-9870-11eb-8d2d-6fac85777913.png)

**Impact op de server**
middelmatig de spelers raken geïrriteerd dat als ze moeten vluchten dit niet kan omdat de motor ineens rood is. Ook kost dit veel geld elke ANWB bellen

**Comment by niekschoemaker** [comment]
Zijn dit enkele specifieke helikopters? Want voor zover ik het test is er niks mis met deze specifieke spawn?

**Comment by JorisDeJoris** [comment]
Ik had het meet die seasparrow die je in de foto ziet meerdere reportjes van

**Comment by Willem-Dekker** [comment]
ja dan is het alleen bi die denk ik heb verder niks gemerkt of gezien ook vandaag niet toen ik zefde heli pakte. mocht de issue er nog zijn her open de issue
