### ISSUE TITLE
Pizza scooter niet inleverbaar

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#503]
**Omschrijf de bug**
De laatste tijd merk ik dat wij redelijk veel reports binnen krijgen over mensen die hun bezorgscooter niet kunnen inleven bij de pizzajob.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Ik durf niet te zeggen hoe dit precies gebeurt, maar het lijkt bij iedereen te gebeuren dit het doet.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je zou de scooter normaal moeten kunnen inleveren. 

**Screenshots en/of logbestanden**
-

**Impact op de server**
Minimaal, maar scheelt reports over bezorgscooters die niet ingeleverd kunnen worden

**Comment by Willem-Dekker** [comment]
Bug lijkt te zitten in het niet juist despawnen van de scooter

**Comment by musician1011** [comment]
Issue opgelost
