### ISSUE TITLE
Flitspaal neerzetten op kruispunt bij postcode 716/714

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#504]
**Beschrijf zo duidelijk mogelijk de feature**
Bij postcode 716 /714 een flitspaal op het kruispunt. mensen gaan daar met 300km/u door de wijken heen en dit hoort niet echt. KMAR zet hier soms mobiele posten op en het is zo tot onze attentie gekomen dat dit gebeurd. Ik denk dat doormiddel van een flitspaal mensen wat meer gaan afremmen op dat kruispunt

**Wat lost deze feature op?**
Deze feature zorgt ervoor dat mensen wat zachter door wijken en op wegen waar mensen lopen gaan rijden. Dit zorgt voor wat meer realisme (zie foto voor locatie)
https://cdn.discordapp.com/attachments/830034326615621672/830034671538667560/unknown.png

**Comment by Willem-Dekker** [comment]
zit er vanaf morgen in
