### ISSUE TITLE
Repairkitjes werken niet meer

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#505]
**Omschrijf de bug**
Als je een voertuig repareert blijft het lampje rood knipperend i.p.v. dat deze naar rood veranderd zoals vroeger. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door de repairkit uit te testen bij een kapot voertuig

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zou een voertuiglampje veranderen naar enkel een rood lampje waardoor er meer dan 50 meter weer mee gereden kan worden. 

**Screenshots en/of logbestanden**
-

**Impact op de server**
Op het mainland zijn de repairkits zo goed als waardeloos op het moment.

(Issue aangemaakt voor Ice)

**Comment by Willem-Dekker** [comment]
logs?

**Comment by Willem-Dekker** [comment]
Werkt zo als het hoort geeft 200 meer heath aan moter
geen bug.
