### ISSUE TITLE
Upgrades betalen voor niks

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#507]
Er is een ticket geopend. Persoon zat met een brabus 800 in een custom shop. Persoon ging naar upgrades en dan naar turbo. Persoon klikte perongekuk op no turbo en betaalde wel de prijs van een turbo. Dit kan problemen opleveren voor mensen die perongeluk op noturbo drukken en ineens geld kwijt is.

**Comment by niekschoemaker** [comment]
Deze issue is nu gefixed
