### ISSUE TITLE
Emote ontboeien toevoegen

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#51]
Het zou mooi zijn dat er ook in de RP kan worden geontboeid hiervoor zit al een Emote in de game /e uncuff . Dit kan een toevoeging worden voor de politie maar ook voor de criminelen.

**Comment by Willem-Dekker** [comment]
moet zeggen dat deze animatie niet heel erg mooi is hier voor

**Comment by Willem-Dekker** [comment]
ik heb dit toegevoegd en de animatie van boeien is oog update naar een nieuwe versie
