### ISSUE TITLE
ANWB omzetten naar ander autosysteem

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#511]
**Beschrijf zo duidelijk mogelijk de feature**
Gebruik laten maken van het zelfde systeem als de ambu en of politie

**Wat lost deze feature op?**
auto's die verdwijnen met x

**Comment by niekschoemaker** [comment]
Auto's die verdwijnen met X is een issue die door animaties werd veroorzaakt en is ondertussen al een poosje gefixed.

**Comment by DeStefanoKiller** [comment]
@Willem-Dekker Kan dit alsnog worden toegevoegd? Want dan kunnen ANWB'ers ook banden enzo in hun auto leggen.
