### ISSUE TITLE
Warmte beeld/ thermal scope toevoegen aan MH-60T (Kustwacht helikopter)

### ISSUE THREAD

**Issue by Daanwith** [Tedeapolis/development#512]
**Beschrijf zo duidelijk mogelijk de feature**
We zouden graag deze optie er bij op willen om zo boten/ drenkelingen op te kunnen sporen. Om dit model zit al een camera alleen kunnen deze nog niet gebruiken

**Wat lost deze feature op?**
Het is realistisch omdat hij er al op zit, en het helpt ons met het zoeken van drenkelingen/ boten. Bovendien beschikt de politie ook over een soort gelijke functie op de zulu.

**Comment by Willem-Dekker** [comment]
model naam of hash?

**Comment by Daanwith** [comment]
De heli zelf heet in de stad MH-60T zou niet weten wat de naam van het model is

**Comment by niekschoemaker** [comment]
Zou erin moeten zitten.
