### ISSUE TITLE
Bankautomaten Fixen bij de Oostpost

### ISSUE THREAD

**Issue by robinvdturk** [Tedeapolis/development#517]
**Omschrijf de bug**
De bank automaten bij de oostpost doen het niet.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
om eventuele nieuwe bank automaten toe te voegen zodat ze wel werken op de oostpost

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Dat je geld kan storten aangezien je soms nog wel een doodgeschoten wordt door iemand op de post, en dan ben je je contantengeld kwijt. Aangezien hier burgers ook wel eens komen met veel geld contant, en  de kmar ook.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/82364057/114593942-f4b83700-9c8c-11eb-8cb8-da1509a22daa.png)

**Impact op de server**
Nu kunnen mensen geen geld pinnen.

**Comment by Willem-Dekker** [comment]
denk dat deze niet kunnen ivm het is een andere prop dan de rest van de automaten.
