### ISSUE TITLE
Helicopter blips toevoegen aan KMar

### ISSUE THREAD

**Issue by Daanwith** [Tedeapolis/development#518]
**Beschrijf zo duidelijk mogelijk de feature**

Voor de mensen van klu en Kmar is dit handig zo kunnen ze makkenlijker luchtverkeer controleren
**Wat lost deze feature op?**
KMar kan makkelijker luchtverkeer controleren. Mensen van de klu die op kmar rang staan kunnen nu ook luchtverkeer controleren.

**Comment by Willem-Dekker** [comment]
fixed
