### ISSUE TITLE
Nieuwe banen.

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#519]
**Beschrijf zo duidelijk mogelijk de feature**

1. Boer.

Dit is het beginpunt voor de boeren,
https://gyazo.com/64b695e5a5de2ea37c86533001e57b42
Vanaf hier moeten de boeren een trekker pakken, dan kunnen ze een aanhanger meenemen en dan rijden ze naar 1 van de 2 plekken waar je het veld kan oogsten.
Plek 1/2: https://gyazo.com/f470a3784cd792132c3a8577ecca9072
Plek 2/2: https://gyazo.com/04ff02ca17fe9cf9600f0bb1616e355b (De velden, niet op de berg)

Vanaf daar moeten de boeren gaan oogsten totdat hun aanhangwagen vol zit. Dan moeten ze het hier afleveren, https://gyazo.com/51fe8195dff6252286ceebedf161ff27
Ze krijgen dan een geld bedrag per tarwe. (Bijvoorbeeld maximaal 200 tarwe in je aanhanger)

Vervolgens word het tarwe automatisch getransporteerd naar een brood fabriek.

2. Bakker

Een bakker heeft tarwe nodig om brood te bakken, wat hij/zij hier kan halen met een busje/vrachtwagen (https://gyazo.com/51fe8195dff6252286ceebedf161ff27).

Vanaf daar rijd de bakker met het tarwe naar de fabriek, de fabriek kan je vinden op deze locatie (https://gyazo.com/8c2663ca328bb9316ab8f2576aa520fd) (foto van locatie: https://gyazo.com/aabe073605e29f33b4d42bf0eec3c52d postcode 6005) Dit lijkt mij een best realistische plek omdat er ook meerdere soort silo's staan voor de tarwe en andere ingredienten.en omdat er 3 garage deuren zijn waar er eventueel voertuigen kunnen staan,
dan moet er nog wel gefixt worden dat deze deuren open kunnen.

Als ze er deeg van hebben gemaakt, moet het brood gebakken worden, dit kan eventueel in dezelfde fabriek. Als het brood gebakken is, moeten ze het brood met een busje vervoeren naar verschillende winkeltjes,
ze krijgen een x aantal bedrag per broodje per winkel, de winkel zou ook eventueel meerdere broden in kunnen kopen omdat het anders wel heel lang duurt om het brood te verkopen.

**Wat lost deze feature op?**
Meer werkgelegenheid / diversiteit

**Comment by musician1011** [comment]
Ik had anders nog een leuke model die misschien te gebruiken valt voor nog wat opties?
