### ISSUE TITLE
Dodo glitch

### ISSUE THREAD

**Issue by Marius-002** [Tedeapolis/development#521]
**Omschrijf de bug**
Het watervliegtuig genaamd 'Dodo' is onlangs vertraagd maar kan nu niet meer vanaf het water opstijgen aangezien de motor niet meer genoeg kracht geeft. Dit is wel noodzakelijk aangezien het een watervliegtuig is en nu veel mensen komen vast te zitten op het water.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
De motor weer wat extra kracht geven zodat het vliegtuig wel weer vanaf het water kan opstijgen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Het vliegtuig zou zonder al te veel moeite moeten kunnen opstijgen.

**Screenshots en/of logbestanden**
Niet noodzakelijk.

**Impact op de server**
Geen

**Comment by niekschoemaker** [comment]
Ik dacht dat ik onlangs de kracht iets verhoogd had, weet niet of het nu nog steeds een probleem is?

**Comment by Hellie94** [comment]
Het is inderdaad nog steeds een probleem vanaf het water. Ik heb wel een methode hoe je hem vanaf het water in de lucht kunt krijgen, alleen is deze omslachtig en niet hoe je normaal een vliegtuig bestuurd. Als er op het water 5 knopen qua snelheid bij kunnen komen, dan denk ik dat je er al bent.

**Comment by Willem-Dekker** [comment]
is het nu beter?

**Comment by niekschoemaker** [comment]
Zo opgelost moeten zijn
