### ISSUE TITLE
Snelheid Apache

### ISSUE THREAD

**Issue by FoxOTF** [Tedeapolis/development#522]
**Beschrijf zo duidelijk mogelijk de feature**

Op dit moment is de snelheid van de Apache (gevechtsvliegtuig van de KLu) te langzaam om ingezet te worden tegen de luchtvaartuigen die op dit moment in de stad zijn (zie foto 1).
). Om de taak van de KLu te vervullen moet je de normale luchtvaartuigen in de stad moeten kunnen bijhouden, dit is op het moment onmogelijk omdat een normale Maverick al snel op de 170KT zit (zie foto 2). 

Aanvraag: Snelheid apache naar de 160/170KT zodat de luchtvaartuigen bij gehouden kunnen worden

**Wat lost deze feature op?**
- KLu kan zijn taken vervullen door ATC checks te doen en een luchtvaartuig bij te houden.
- KLu kan dan een achtervolging in de lucht aangaan op gelijke snelheden 
Foto 1
![image](https://user-images.githubusercontent.com/80756288/115144247-f0549b00-a04b-11eb-843c-d670424f3c5c.png)
Foto 2
![image](https://user-images.githubusercontent.com/80756288/115144305-47f30680-a04c-11eb-995f-e8aab2fec050.png)

**Comment by ToyStoner** [comment]
Is het dan ook geen mogelijkheid om de Politie Zulu van de politie in snelheid te verlagen naar 190 knopen, ipv 230kt?

**Comment by Willem-Dekker** [comment]
Dit zou aangepast moeten zijn als dit niet zo is reopen hem nog een keer
