### ISSUE TITLE
Snelheidsradar op KMAR dirtbike

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#527]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel heeft de kmar dirtbike, in tegenstelling tot de politie dirtbike, geen werkende snelheidsradar. 
Dit zorgt er dus voor dat voertuigen niet geklokt kunnen worden op hun snelheid, en tevens kunnen kentekens niet gecontroleerd worden wanneer deze langs de radar heenrijden.
De vraag is dan ook om de snelheidsradar ook toe te voegen op dit voertuig.

https://prnt.sc/11v6o4i

**Wat lost deze feature op?**
Het zorgt ervoor dat de motor dezelfde mogelijkheden heeft als die van de politie. Hierdoor kan de kmar hun werk nog beter doen.

**Comment by Willem-Dekker** [comment]
zit er morgen in
