### ISSUE TITLE
Wiet pluk animatie

### ISSUE THREAD

**Issue by AFriendlyRacoon** [Tedeapolis/development#528]
**Omschrijf de bug**
De animatie van wiet pluk stopt niet meer automatisch je hoorde normaal e te drukken op een plantje en dan stond je na een paar seconde weer op maar nu moet je 2x (X) doen om op te kunnen staan

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een wiet plantje plukken

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Na een paar seconde opstaan om verder te gaan

**Screenshots en/of logbestanden**
https://youtu.be/BIO_lMmRX8w

**Impact op de server**
Niet goed meer kunnen plukken

**Comment by timfloors** [comment]
@AFriendlyRacoon Is dit eenmalig gebeurd of komt het elke keer voor?

**Comment by Willem-Dekker** [comment]
fixed
