### ISSUE TITLE
Toevoegen camera's aan de civiele buzzard

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#530]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel heb je tweede type buzzard, de civiele en armed. Het is echter zo dat enkel bij de armed buzzard camera's gebruikt kunnen worden om hiermee hittebronnen o.i.d. op te vatten. 
Toegevoegd zou dus moeten worden dat de camera's die tevens in de Zulu / Apache zitten ook op de civiele buzzard moeten komen. De spawnnaam hiervan is /car buzzard2.

**Wat lost deze feature op?**
Het maakt de helikoper realistischer gezien hij ook daadwerkelijk een camera in het model heeft zitten. En tevens zorgt het er ook voor dat de armed buzzard minder vaak gepakt hoeft te worden gezien er in de normale buzzard dan ook camera's zitten.

**Comment by Willem-Dekker** [comment]
wat is daar de hash van?

**Comment by Willem-Dekker** [comment]
zit er morgen in
