### ISSUE TITLE
NPC verkoop zakjes werkt niet

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#531]
**Omschrijf de bug**
Als je een hersenloze ziet en je wilt zakjes verkopen (tot nu toe alleen getest met wiet) kun je niet op E drukken of verkopen aan de hersenloze. Je krijgt er ook geen melding van als er iets gelukt is of niet. Na cache legen werkte het ook niet.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Zakjes wiet opzak hebben en een ander laten uitloggen dan op E drukken en kijken of er iets gebeurd. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal als je op E drukt zou je linksonder in een melding krijgen, dat kan zijn: Aftelling van als je verkoopt, deze persoon heeft je afgewezen of aan deze persoon is al drugs verkocht.

**Screenshots en/of logbestanden**
https://streamable.com/bhdzmh
https://www.youtube.com/watch?v=l7oDQmiJzDw
(tweede filmpje is van Willem.. ja dit is zijn normale gedrag :) )

**Impact op de server**
Drugs kunnen niet meer verkocht worden aan npc's

**Comment by niekschoemaker** [comment]
Is dit nog steeds een issue?

**Comment by DevvTDA** [comment]
Nee dit is niet meer relevant :) Bij deze sluit ikhem
