### ISSUE TITLE
Helikopter/vliegtuig opslag politie

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#532]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel word het voertuig niet geblokkeerd zodra hij in de politie opslag staat. Dus er moet een block op komen dat de persoon zijn helikopter/vliegtuig kan pakken zodra het in de politie opslag staat.

**Wat lost deze feature op?**
Verwarring bij spelers + het doorverkopen van een inbeslaggenomen helikopter/vliegtuig.

**Comment by Willem-Dekker** [comment]
fixed voor morgen
