### ISSUE TITLE
Kleur unmarked volvo v90 aanpassen

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#534]
**Omschrijf de bug**
Momenteel is de kleur van de volvo v90 van de politie niet aan te passen. Dit kost namelijk circa 260K. Om enigszins onopvallend te blijven, moet dit wel aangepast kunnen worden. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Naar de modshop rijden in een volvo v90 van de politie (/car politiev90) en deze proberen te resprayen. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou het mogelijk moeten zijn om de kleur van de unmarked voertuigen aan te passen (voor $1) bij de modshop. 

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/71287080/116252560-f9421c80-a76f-11eb-8b18-282f9b7fe967.png)

**Impact op de server**
Laag

**Comment by Bladerdeeg** [comment]
Heeft de unmarked BMW van de politie niet het zelfde probleem?

**Comment by musician1011** [comment]
Prijzen zijn aangepast.
