### ISSUE TITLE
Niks kunnen pakken uit gangopslag

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#535]
**Omschrijf de bug**
Momenteel kunnen gangs geen spullen pakken uit hun gangopslag.
Wanneer ze op het kopje "pak spullen uit opslag" drukken krijgen ze links onderin een foutmelding waarin staat: "Er ging iets mis, probeer het later opnieuw.).

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Zet jezelf op een juiste rang en loop naar de opslagcirkel van deze groepering. 
Probeer iets uit de opslag te pakken waarna een foutmelding zal verschijnen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je gewoon spullen uit de opslag moeten kunnen pakken zonder enige problemen.

**Screenshots en/of logbestanden**
Foutmelding:
![image](https://user-images.githubusercontent.com/72617118/116798674-677d3b00-aaf2-11eb-9eb7-b60db6d0a885.png)

Console error:
![image](https://user-images.githubusercontent.com/72617118/116798678-7532c080-aaf2-11eb-9094-e04720836e90.png)

**Impact op de server**
Middel: Groeperingen kunnen momenteel niks uit hun opslag pakken waardoor de circulatie van drugs stil komt te vallen.
Verder liggen er in de meeste opslagen grote hoeveelheden geld waardoor zit bijvoorbeeld ook niet gewassen kan worden.

**Comment by niekschoemaker** [comment]
Is gefixed
