### ISSUE TITLE
koerier job kapoet

### ISSUE THREAD

**Issue by ZoiH** [Tedeapolis/development#536]
**Omschrijf de bug**

werkt nie
**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
probeer de job

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je zou moeten kunnen werken

**Screenshots en/of logbestanden**

**Impact op de server**
mensen zeuren dat het niet werkt

**Comment by niekschoemaker** [comment]
Ik heb de job geprobeerd, en hij werkt.

Meer info nodig dus.

**Comment by niekschoemaker** [comment]
Deze is ondertussen al gefixed neem ik aan
