### ISSUE TITLE
Telefoon blijft hangen bij aanpassen contact

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#538]
**Omschrijf de bug**
Wanneer je in je telefoonlijst een contact wilt aanpassen blijft je scherm hierna hangen.
Op geen enkele mogelijkheid is je telefoonscherm weg te krijgen, hierdoor zal je dus moeten reloggen.

Zie video: https://youtu.be/LVgQuT3H-V8

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Open je telefoon en ga naar een willekeurig contact.
Pas dit contact aan en probeer je telefoonscherm hierna weer weg te drukken.
Het scherm zal vast blijven staan en je zal moeten reloggen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou het scherm netjes weg moeten gaan wanneer je meermaals backspace of esc drukt.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Klein - Enkel wanneer je een contact aanpast zal je moeten reloggen. Het is dus niet een enorm groot probleem.

**Comment by niekschoemaker** [comment]
Deze bug kan ik niet repliceren.

**Comment by MartijnMeister** [comment]
Zoals hierboven al staat beschreven komt dit probleem voor wanneer je op de main server de naam van een contact wilt aanpassen.

- Je opent je telefoon en gaat naar "contacten"
- Op een contact naar keuze druk je pijltje naar rechts waarna het menu naar voren komt waar je kan kiezen tussen "blokkeren en wijzig contact"
- Je drukt op wijzig contact
- In dit scherm pas je de naam van het contact aan waarna je op enter drukt
- Het contact zal nu aangepast in je telefoon staan
- Wanneer je momenteel op backspace of esc drukt gaat je telefoonscherm niet weg en blijft deze vastzitten in je scherm. Je moet reloggen om dit weg te krijgen.

Het wordt dus veroorzaakt door het aanpassen van de naam van een contact op de main server

**Comment by MartijnMeister** [comment]
Ik zelf durf dit niet te zeggen. Ik heb dit enkel zelf uitgeprobeerd nadat hierover een ticket was binnengekomen. Hierbij kwam ik erachter dat dit zowel met muiscontrole aan als uit gebeurd.

**Comment by MartijnMeister** [comment]
Probleem is inmiddels verholpen.
