### ISSUE TITLE
onzichtbare item 

### ISSUE THREAD

**Issue by DevinKoedam** [Tedeapolis/development#540]
**Omschrijf de bug**
Een onzichtbare item waaraan je werkvoertuig vaak kapot gaat, dit zit op de route van oliewerker en is bijna niet te vermijden 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Het item uit de game halen misschien 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden ze gewoon via de route kunnen rijden zonder dat hun auto kapot gaat door de 

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/79994975/117573016-05b26780-b0d6-11eb-9260-ddfc654a622b.png)
![image](https://user-images.githubusercontent.com/79994975/117573050-35616f80-b0d6-11eb-8190-53d2bc76747f.png)
![image](https://user-images.githubusercontent.com/79994975/117573061-3f836e00-b0d6-11eb-9822-31e27d19e0b8.png)

**Impact op de server**
er komen hier erg veel reports over binnen

**Comment by Willem-Dekker** [comment]
@brothasx zit hier een map ymap die dit kan doen of zo?

**Comment by Willem-Dekker** [comment]
Is de fivem build. we gaan kijken of we er pionen kunnen zetten
