### ISSUE TITLE
Geen toegang tot shop, maar wel de juiste brevetten!

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#541]
**Omschrijf de bug**

Sommige mensen hebben het brevet voor een vliegtuig of een Heli maar kunnen dan de shop niet in om een voertuig te kopen!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Normaal zou je de shop in moeten kunnen om een vliegtuig of Heli te kunnen kopen als je beide brevetten hebt

**Screenshots en/of logbestanden**

**Impact op de server**

**Comment by Willem-Dekker** [comment]
zijn er ook logs?

**Comment by FreddyKrueger2021** [comment]
Ik heb deze gemaakt vanuit een ticket van jou, daar stonden geen logs in!

**Comment by niekschoemaker** [comment]
Dit is als het goed is ondertussen al gefixed. Zo niet dan even heropenen
