### ISSUE TITLE
Gangopslag voertuigen

### ISSUE THREAD

**Issue by ZoiH** [Tedeapolis/development#542]
**Beschrijf zo duidelijk mogelijk de feature**

Er is momenteel een probleem dat je auto's kan duplicaten doormiddel van hem in een gang opslag te zetten. Zodra dit word geblokkeerd zal eht zorgen voor minder verwarring en het verwijderen van de optie tot powergame en failrp
**Wat lost deze feature op?**
Het voorkomen van failrp en powergamen

**Comment by niekschoemaker** [comment]
Zit erin na volgende herstart
