### ISSUE TITLE
Lightbar werkt niet naar behoren

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#543]
**Omschrijf de bug**
Kan geen nieuwe lightbars meer plaatsen op voertuigen.
Als je /lightbar doet en bijvoorbeeld een small blue stick aanklikt, kan je die niet bewegen, en hang je vast in je auto.
Kan niet meer uistappen, enkelt reloggen zorgt ervoor dat je weer verder kan spelen

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Probeer eens een nieuwe lightbar te zetten op een willekeurig voertuig.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gezien zou je nieuwe lightbars toe kunnen voegen. 
Echter werkt momenteel allene nog maar het /loadlightbar command, maar als mensen nieuwe willen zetten, lukt dit dus niet.

**Screenshots en/of logbestanden**
Niet in de gelegenheid deze momenteel bij te leveren, mocht dit echt benodigd zijn kan ik daar vannacht wel aan komen.

**Impact op de server**
DSI, BSB, en Recherche kunnen dus niet op voertuigen nieuwe lightbars zetten.

**Comment by niekschoemaker** [comment]
Oh nice one, typefoutje, is gefixed
