### ISSUE TITLE
Onzichtbaar object olieverwerk

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#544]
**Omschrijf de bug**
Er zweeft een onzichtbaar object bij olieverwerk waardoor er veel vrachtwagens kapot gaan omdat ze er tegen aan rijden

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je pakt een vrachtwagen en gaat naar de plek toe op het filmpje, rijd naar voren en dan zou je er tegen aan komen (zie video)

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je er zonder moeite kunnen rijden

**Screenshots en/of logbestanden**
https://streamable.com/nkzdos

**Impact op de server**
Veel vrachtwagens die onnodig kapot gaan waardoor de anwb ook steeds moet komen en mensen hun geld verliezen door een server fout

**Comment by Willem-Dekker** [comment]
zie #540
