### ISSUE TITLE
Mijnwerkers omkleedcirkel doet het niet

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#545]
**Omschrijf de bug**
Als je de mijnwerkers job wilt beginnen en in de omkleed cirkel staat, geeft hij niet aan dat je om kan kleden.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
De job ''mijnwerker'' nemen en richting de mijnwerkers lockers toe gaan. en in de cirkel staan om de mijnwerkers kleren aan te trekken als het goed is krijg je links boven niet ''druk op E om je om te kleden''

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je op ''E'' kunnen drukken en de mijnwerkers kleding aan kunnen doen zodat je de job kan starten

**Screenshots en/of logbestanden**
https://prnt.sc/12rt8c8

**Impact op de server**
Mijnwerkers job kan niet uitgevoerd worden

**Comment by Willem-Dekker** [comment]
werkt gewoon net getest
