### ISSUE TITLE
Schade aan vliegtuigen

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#546]
**Omschrijf de bug**
Zodra je land met vliegtuigen heb je 9 van de 10 keer meteen een lampje doordat het vliegtuig dit zo goed als altijd registreert dat het een soort van botsing is geweest. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door een vliegtuig te landen. Kreeg van de vlieginstructeurs mee, dat hier sowieso de jet en het stuntvliegtuig er last van hebben. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Geen lampje krijgen bij een normale landing.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Lichte impact op de mensen die vliegtuigen hebben. Het maakt het momenteel minder aantrekkelijk om te vliegen en daarnaast is het geven van lessen hierdoor ook gevaarlijk.

**Comment by niekschoemaker** [comment]
Dan moet je niet als een complete debiel landen lijkt me want ik vlieg persoonlijk best veel op de server en nog nooit last van gehad.

**Comment by Hellie94** [comment]
https://streamable.com/lj3g84

https://streamable.com/uwhoza

Gefilmd vanuit het perspectief van een vlieginstructeur

**Comment by niekschoemaker** [comment]
Deze issue is als het goed is ondertussen opgelost. Zo niet graag even reopenen.
Is al poosje terug gefixed maar ben vergeten de issue te sluiten toendertijd.
