### ISSUE TITLE
Aanpassing aan de portofoons

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#547]
**Beschrijf zo duidelijk mogelijk de feature**
Tijdens het staffoverleg is besproken dat Niek zou gaan kijken of het mogelijk is om porto's niet meer bruikbaar te maken in het water. Hierbij een github issue om hem hieraan te herinneren. 

**Wat lost deze feature op?**
Onrealistische roleplay en powergaming doordat de portofoons onder water of tijdens het zwemmen wordt gebruikt.

**Comment by Willem-Dekker** [comment]
done door  niek
