### ISSUE TITLE
Logging voor twitter

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#548]
**Beschrijf zo duidelijk mogelijk de feature**
Tijdens het staffoverleg is er besproken dat er gekeken dient te worden naar een logging kanaal voor twitter. Hierin kunnen staffleden zonder databasetoegang twitterberichten makkelijk teruglezen en dergelijke. 

- [ ] Toevoegen van een loggingkanaal voor twitter, soortgelijk aan #deepweb-logger

**Wat lost deze feature op?**
Dat er telkens gevraagd dient te worden om de database te bekijken om zaken omtrent twitterberichten op te lossen.

**Comment by niekschoemaker** [comment]
Wordt naar de Discord gelogged sinds een week ofzo, onder #chat-log
