### ISSUE TITLE
Rangen van de gangs aanpassen

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#549]
**Beschrijf zo duidelijk mogelijk de feature**
Aanpassen van de rangs van de gang qua toegang tot verschillende dingen (zie hieronder)

Brockl La icona

- [x] Godfather zo laten
- [x] Don -   Heli toegang, attachments kopen, Geld uit de pot, wapen inkopen
- [x] Consigliere , Heli toegang, attachments kopen, geld uit pot
- [x] capo attachments kopen

Pavlov Maxi

- [x] Stric - toegang tot gang heli

MC Ice

- [x] DTMC - V.President Geld uit de pot halen, Toegang tot gang heli
- [x] DTMC - Sergeant  Geld uit de pot halen, Toegang tot gang heli
- [x] DTMC - Secretary Geld uit de pot halen, Toegang tot gang heli

Bratva - Devin

- [x] Братва - Toegang tot helikopter
- [x]  Авторитет - Toegang tot helikopter

 
**Wat lost deze feature op?**
Gangs hebben op dit moment last dat alleen de baas heel veel dingen kunnen doen en de rest niet.

Vandaar dat ik even met de gangs was gaan praten en dit kwam naar voren bij de gangs.

**Comment by Maxva03** [comment]
Pavlof = Pavlov

**Comment by Willem-Dekker** [comment]
Братва is bratva ik heb maar ff gevraagd en het moest alleen Авторитет zijn

**Comment by Willem-Dekker** [comment]
> capo attachments kopen
kan niet aangezien dit op wapen perms gaat en niet los

**Comment by timfloors** [comment]
vraag vanuit tfft of rang 'Secretary' ook toegang kan krijgen tot de pot
