### ISSUE TITLE
Helicopter Seashark/Seasparrow kan gecustomized worden met homing missiles and miniguns

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#55]
https://cdn.discordapp.com/attachments/738897412042784788/738897479277477958/bug.mp4

Deze man legt alles uit in de video, ticket 6584, discordnaam Pinochento

Je kan dus wapens op deze helicopter zetten, daarnaast kan je de helicopter zo customizen dat deze half verdwijnt, en wanneer je uitstapt ontploft de helicopter random.

**Comment by Willem-Dekker** [comment]
je kan het kopen maar je hebt er niks aan
