### ISSUE TITLE
Geen drugs meer kunnen verkopen aan npc,s

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#550]
**Omschrijf de bug**
Sinds 14-5-2021 is het niet meer mogelijk om drugs te verkopen aan npc,s.
Normaal gezien zou je aan iedere npc drugs moeten kunnen verkopen maar sinds kort kan je dit bij geen een npc meer doen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je neemt als voorbeeld een zakje cocaine en loopt naar een npc toe (Dit kan een net uitgelogde player zijn of een standaard npc zoals bij de grote bank) Je drukt op E om te verkopen en er gebeurd niks normaal gezien zou er ook links boven in moeten staan druk op E om je drugs te verkopen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zou je naar een npc toe lopen en kan je op E drukken, dan begin je met een emote en dan start het verkopen dit duurt een aantal seconden en hierna krijg je er dan zwartgeld voor terug.

**Screenshots en/of logbestanden**
https://youtu.be/75buaYPXI50

**Impact op de server**
Criminele die nu niet kunnen verkopen aan npc,s waardoor er telkens reports binnen komen

**Comment by niekschoemaker** [comment]
Is dit nog steeds een issue?

**Comment by Willem-Dekker** [comment]
Gezien geen reactie, geen issue meer. Anders heropen de issue
