### ISSUE TITLE
Parachutes op het HB

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#552]
**Beschrijf zo duidelijk mogelijk de feature**
- Aanpassen van de wapeninkoop voor agenten op het HB: Elke agent (ALLE rangen van de politie) dient gratis een parachute te kunnen kopen op het HB. Dit hebben we besproken tijdens de KL-bespreking en is ook met Nick overlegd. 

**Wat lost deze feature op?**
Hierdoor wordt het mogelijk om verder te roleplayen bij een overval, aangezien vrijwel iedereen vlucht d.m.v. een parachute.

**Comment by Willem-Dekker** [comment]
Moeten alle rangen het of vanaf bepaalde?

**Comment by TDA-SanderD** [comment]
Alle rangen

**Comment by Willem-Dekker** [comment]
Zit er morgen in
