### ISSUE TITLE
Quiksell veiligheid functie autodealer

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#554]
**Omschrijf de bug**
Bij de autodealer zit een quiksell functie echter is de ja/nee optie ter veiligheid hiervan verdwenen. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door een auto te verkopen in de quiksell

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Een menu krijgen met of je zeker weet dat je de auto wil verkopen.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Lichte impact voor mensen die willen kijken voor hoeveel zij de auto willen quiksellen

**Comment by Willem-Dekker** [comment]
zit er in
