### ISSUE TITLE
City bug repareert je auto

### ISSUE THREAD

**Issue by zeletix** [Tedeapolis/development#555]
**Omschrijf de bug**
Als je last van city bug hebt dan val je vaak door de grond, dit verandert jouw enginehealth naar 1000 waardoor jouw auto weer helemaal heel is

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Iemand die last heeft van city bug met een kapote auto laten rijden op hoge snelheden, en als die dan door de grond valt zie je dat zijn auto is gerepareerd

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je enginehealth alleen terug zetten naar wat ie heeft verloren toen ie door de grond viel

**Screenshots en/of logbestanden**

**Impact op de server**
Kan groot zijn als meer mensen er achter komen en het gaan misbruiken

**Comment by Willem-Dekker** [comment]
Is geen bug is gewoon hoe het systeem is gemaakt. als je op ene potato wil spelen is dat niet mijn probleem
