### ISSUE TITLE
togglechat 

### ISSUE THREAD

**Issue by Marius-002** [Tedeapolis/development#556]
**Omschrijf de bug**
Wanneer je togglechat doet en er komt een report binnen wordt de chat automatisch weer aangezet

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Zorgen dat de chat gewoon uitblijft wanneer men togglechat doet, zoals vroeger dus :P

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Wanneer men dit normaal doet zou de chat moeten uitgaan en uitblijven.

**Screenshots en/of logbestanden**
Niet van toepassing

**Impact op de server**
Niets buiten dat dit vervelend is voor opnames / streams :P

**Comment by Willem-Dekker** [comment]
fixed
