### ISSUE TITLE
Confisceren gangs weer aanzetten [Staff overleg van 18/04/2021]

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#557]
Confisceren voor gangs weer aanzetten met de volgende regels en beperkingen [kijk discord] (Willem)
Besproken: Mee eens met wijziging aan de categorie 1 naar maximaal 7 dagen ban bij abuse.

^Puntje besproken tijdens staffoverleg van 18/04/2021, was er zelf niet bij maar is vergeten een github issue voor aan te maken.

**Comment by niekschoemaker** [comment]
@Willem-Dekker Hier was jij toch mee bezig?

**Comment by Willem-Dekker** [comment]
Zit er na de restart in
