### ISSUE TITLE
Random ontploffen DODO

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#558]
**Omschrijf de bug**

Mensen die een DODO hebben, ervaren nogal wat problemen zoals als ze gaan tanken met een jerrycan dat ie random ontploft, en dit gebeurd soms ook als mensen in en uit stappen!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

zie hierboven

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

lijkt me niet dat ie hoort te ontploffen, alleen als je crasht

**Screenshots en/of logbestanden**

https://cdn.discordapp.com/attachments/762003330041511976/842866359279812658/dodo2.mp4

https://cdn.discordapp.com/attachments/762003330041511976/842866376116797470/dodo1.mp4

**Impact op de server**

**Comment by Willem-Dekker** [comment]
kunnen we niks aan doen gta mechanics
