### ISSUE TITLE
Verschillende wapens voor het criminele circuit

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#559]
**Beschrijf zo duidelijk mogelijk de feature**
- Criminelen vinden dat de huidige wapens vrij gelimiteerd zijn en zouden hier graag wat variatie in zien
- Het zou handig zijn om verschillende type wapens toe te voegen, de limieten blijven ongeveer hetzelfde. 
**Wat lost deze feature op?**
- Dit zorgt voor meer variatie in wapens en dit zal leuker zijn voor de criminelen

Link naar de powerpoint: https://cdn.discordapp.com/attachments/605195142487343105/843522933509849088/Puntje_voor_staffoverleg.pptx

Dit is besproken en goedgekeurd tijdens het staffoverleg.

**Comment by Willem-Dekker** [comment]
zit er in
