### ISSUE TITLE
Tweedehands autodealer uitbreiden

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#56]
[] Of ervoor zorgen dat mensen hun tweedehands auto niet in een 'wachtrij' zetten, maar daadwerkelijk alleen kunnen plaatsen wanneer er plek is op de cardealer. Want nu komen er veel klachten binnen dat mensen hun auto plaatsen maar niet willen dat deze in de 'wachtrij' komen <-- kan een tijdelijke oplossing zijn totdat:
[] er een tweede dealer komt/grotere tweedehands dealer (in het noorden?). Willem wilde hiermee bezig maar is er nooit aan toegekomen want de hulp was er toen niet. Ik wil u best hiermee helpen, maar heb niet altijd tijd.

**Comment by Willem-Dekker** [comment]
Feature request: 
 
* Geen fietsen kunnen plaatsen op de dealer
