### ISSUE TITLE
Politie Buzzard schiet control dissablen

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#560]
**Omschrijf de bug**
Er wordt random geschoten met de buzzard tijdens het vliegen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door te vliegen ermee en spatiebalk in te drukken meen ik. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Zelf kunnen bepalen wanneer je vuurt.

**Screenshots en/of logbestanden**
-

**Impact op de server**
Er vliegen continu random kogels door de lucht waardoor er veel reports binnenkomen.

**Comment by FoxOTF** [comment]
Is in github #328 ook aangekaart

**Comment by niekschoemaker** [comment]
Duplicate van #328
