### ISSUE TITLE
Mavericks constant kapot uit de garage

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#562]
**Omschrijf de bug**
Als je een Maverick uit de opslag haalt dan is hij kapot. Dit is ook als hij gemaakt word en weer erin gezet word.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Maverick uit de opslag halen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou hij niet kapot moeten gaan

**Screenshots en/of logbestanden**
---

**Impact op de server**
Het is heel vervelend, nu worden er constant reports over gemaakt of moeten mensen de anwb er voor betalen terwijl het een fout is vanuit de server

**Comment by Willem-Dekker** [comment]
Van wie?

**Comment by DevvTDA** [comment]
Momenteel kreeg ik de reports van Ronny Fenn (Gillesss#0001 op discord) meerdere keren gehad vandaag

**Comment by DevvTDA** [comment]
Kenteken : LMF 701 (Seasparrow)
Kenteken: YUO 349 ( Maverick)

**Comment by niekschoemaker** [comment]
Ik heb wat kleine changes gemaakt, weet niet zeker of dit het fixed maar denk het wel.

Anders issue even reopenen aub.
