### ISSUE TITLE
Tattoo's verwijderen bevestigingsknop

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#563]
**Beschrijf zo duidelijk mogelijk de feature**
Een weet je dit zeker vraag nadat je op verwijderen klikt, waar je op ja of nee kan klikken. 

**Wat lost deze feature op?**
Dat mensen er niet per ongeluk op klikken en 50K kwijt raken per ongeluk.

**Comment by Willem-Dekker** [comment]
Das pech tattoo weg

**Comment by Willem-Dekker** [comment]
zit er op
