### ISSUE TITLE
Appartementen in het noorden

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#564]
**Beschrijf zo duidelijk mogelijk de feature**
De aanvraag om mogelijk meerdere appartementen te maken in het noorden

**Wat lost deze feature op?**
Dit lost op dat nu alles echt in de stad gebeurd onderin de map, als je appartementen kunt hebben in Sandy en het noordelijke puntje verdeel je de spelers mogelijk meer over de map en word niet alleen de RP op een vaste locatie gehouden.

**Disclaimer**
Hierover staat al een hele simpele github request open (#299), na aanleiding van de vele aanvragen hierover de laatste tijd toch even een duidelijker uitgetypt voorstel

**Voorbeeld locatie's**
![LocatiesNoorden](https://user-images.githubusercontent.com/56398140/118959898-06af8880-b963-11eb-9581-ad223c641f7c.png)

**Comment by Chang-nl** [comment]
Ik heb wat extra appartementen toegevoegd in het noorden en in die omgevingen! Zit als het goed is na de restart in de server
