### ISSUE TITLE
Porto's - Burgerraad

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#565]
**Beschrijf zo duidelijk mogelijk de feature**
Op het moment dat je in een porto frequentie zit komt er rechts bovenin het lijstje met blauwe namen te staan, de vraag of toegevoegd kan worden dat een naam geel word op het moment dat iemand praat :)

**Wat lost deze feature op?**
dan kan je zien wie er praat net als mumble rechts onder nu gaat de naam onder aan de lijst staan maar als die geel word kan je het nog makkelijker zien

**Comment by niekschoemaker** [comment]
Zit erin vanaf volgende herstart.
