### ISSUE TITLE
Porto op vest KMAR - Burgerraad

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#566]
# Waar zit het in EUP, interiors of retextures ?
Kmar eup

# Toevoeging:
Het kledingstuk porto beschikbaar maken in de KMAR eup aangezien hun geen porto op hun schouders hebben en dus nergens in praten

# Link naar issue of coördinaten naar de plek
-

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
-

# Wat is de toegevoegde waarde?
Het stukje realisme en netheid van de mogelijke RP hiervan word verbeterd

**Comment by walvisgedaan** [comment]
Dit is niet 123 gefixt zoals de meeste denken, ik zal moeten kijken naar een volledige nieuwe model

**Comment by timfloors** [comment]
het gaat hier niet om het model of het vest het gaat hier puur om de optie om het tshirt dat jou een porto op je schouder geeft toe te voegen aan de eup

**Comment by walvisgedaan** [comment]
Wat is het nummer daarvan dan? En hoe ziet de outfit er dan uit

**Comment by Willem-Dekker** [comment]
zit er morgen in na de restart
