### ISSUE TITLE
Telefoon Bellen - Burgerraad

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#567]
**Omschrijf de bug**
Op het moment dat jij aan het bellen met iemand en een andere persoon belt jou kan het zijn dat jullie opeens met zn 3en in gesprek zitten, of op het moment dat de persoon ophangt jou gesprek waar je in zat word opgehangen

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een persoon bellen en je dan door een andere persoon laten bellen, dit 2e belletje moet je dan neit opnemen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
persoon zou een melding moeten krijgen van "persoon is in gesprek"

**Screenshots en/of logbestanden**
-

**Impact op de server**
Gemiddeld aangezien veel non overheidjobs gebruik maken van de telefoon en het nogal irritant is als dit gebeurd

**Comment by niekschoemaker** [comment]
Telefoons zouden nu een "Deze persoon is in gepsrek melding" moeten geven.
