### ISSUE TITLE
Lancering sleepwagen

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#568]
**Omschrijf de bug**
Bij de nieuwe sleepwagen (slamtruck) als je een auto achterop doet en je wilt hem loskoppelen, lanceert de auto waardoor hij vervolgens op de kop of op de zij valt.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een auto achterop de slamtruck vastmaken en losmaken met ''E''. Mocht het na 1 keer niet lukken, dan vaker proberen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou hij gewoon moeten loskoppelen zonder moeite en dat je hem gelijk ervan af kan rijden.

**Screenshots en/of logbestanden**
https://medal.tv/clips/52413508/d1337b1AT8M1

**Impact op de server**
De wagens zijn €500.000 euro en het is een zonde om dat geld te investeren als je hem niet fatsoenlijk kan gebruiken.

**Comment by Willem-Dekker** [comment]
Ik ben best wel teleurgesteld dat dit niet gaat over een raket raketlancering

**Comment by Willem-Dekker** [comment]
Kunnen we niet heel veel aan doen aangezien hij gewoon je car terug zet boven de baan en bij die vid de baan schuin is en dus lager dan de wagen
