### ISSUE TITLE
Veranderingen Bikerjob

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#569]
**Beschrijf zo duidelijk mogelijk de feature**
- Clubkluis inhoud moeten toegang hebben voor Ice, Jack Mercer, Mulli Mercer en James Mercer(rangen: Vice-President, Sergeant at arms en Secretary)
- de Maverick Mogelijkheid om door Vice-president gepakt te worden
- elke rang kan in de gangkluis attachments kopen voor wapens (staat nu op president, VP en sergeant at arms)

**Wat lost deze feature op?**
Na een klein overlegje doorgekregen dat de baas er minder zal zijn daarom de vraag of dit aangepast kan worden zodat iedereen weer normaal te werk kan gaan :)

**Comment by Willem-Dekker** [comment]
zie #549
