### ISSUE TITLE
Opgeslagen Docu werkt niet.

### ISSUE THREAD

**Issue by RenoNiiChan** [Tedeapolis/development#57]
Meerdere mensen hebben hier ondertussen last van:

- /docu -> opent documenten script

- Opgeslagen documenten -> Opent normaal gezien een lijst met opgeslagen documenten. Dit werkt niet en er komt geen menu open & na dien kan /docu kan niet meer open tot restart.

[Error Log in het F8 menu](https://images-ext-2.discordapp.net/external/_UlO4FIZcjscTySPuRWKatmcI4zXZgkTMIflJ3AT6wQ/https/i.gyazo.com/thumb/1200/70173c1aac43e95ef3e4ca2611abebbe-png.jpg?width=1015&height=101)

- [x] Documenten script na kijken en het probleem lokaliseren

- [x] Probleem oplossen

- [ ] Indien het probleem niet kan gevonden worden kijken naar een andere mogelijkheid voor documenten

**Comment by niekschoemaker** [comment]
Is deze screenshot recent? Want als het goed is had ik hier al een workaround voor gemaakt.

Hij zou nu moeten werken maar nog wel een error moeten geven, als het een oude screenshot is zou je dan even een nieuwe kunnen posten als er een error in console is?

**Comment by RenoNiiChan** [comment]
Deze is recent op dit moment lukt het wel voor mij op dit terug open te doen.

Ik vraag even aan de gene die het ticket aan maakte om ook even na te kijken.
