### ISSUE TITLE
Auto,s die dubbel spawnen bij loods

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#570]
**Omschrijf de bug**

Auto,s die duplicaten bij de loodsen wanneer je /testrespawnvehicle doet  

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Men komt aan bij de loods parkeert zijn/haar auto daar en gaat vervolgens naar binnen. Wanneer men weer naar buiten komt is de auto gedespawned en dan vervolgens wanneer je /testrespawnvehicle doet komt hij terug maar wanneer je een stuk weg rijd van de loods en weer terug komt staat vervolgens de zelfde auto als die je ge testrespawned hebt weer en is die dus geduplicate

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Normaal gesproken zou de auto gewoon moeten blijven staan en zou je niet /testrespawnvehicle moeten doen om je voertuig weer terug te krijgen.

**Screenshots en/of logbestanden**

**Impact op de server**
Hier door komen er veel dubbele auto,s en krijgen we er steeds reports over binnen.

**Comment by Willem-Dekker** [comment]
moet je dat command niet doen

**Comment by niekschoemaker** [comment]
> 
> 
> moet je dat command niet doen

Voegt invalid label toe aan comment.


Maar anyways, wat ik zo hoorde was dit grotendeels gefixed door een change aan de deletion logica (server sided in plaats van client sided) dus ik gok zo dat dit ondertussen gefixed is. Zo niet graag even reopenen.
