### ISSUE TITLE
1 verandering bij ANWB

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#571]
- [x] /onduty mechanic kunnen doen vanaf rang 8 in-dienst (Technisch specialist in opleiding).

Momenteel kan alleen teamleiding /onduty mechanic doen en voor de ANWB OPCO die wij vanaf nu hebben is het handig als een rang 8 dit ook kan doen.

**Comment by Willem-Dekker** [comment]
zit er morgen in
