### ISSUE TITLE
Kogels worden niet overgegeven

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#572]
**Omschrijf de bug**
Wanneer iemand een wapen overdraagt aan een ander persoon worden de kogels niet meegegeven.
Het komt dus voor dat iemand een vol geladen wapen verkoopt aan iemand waarna de kopers het wapen zonder kogels krijgt.
Hierdoor moeten vele refunds uitgedeeld worden gezien er simpelweg kogels verloren gaan.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Om de bug te reproduceren zijn 2 mensen nodig.
Persoon 1 neemt een wapen die volledig geladen is met kogels. Deze persoon geeft het wapen over aan persoon 2. Wanneer persoon 2 het wapen trekt zal er gemerkt worden dat er geen kogels inzitten.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden alle kogels die origineel in het wapen zaten overgedragen moeten worden met het wapen.

**Screenshots en/of logbestanden**
- https://www.youtube.com/watch?v=lvxBgGR5SCM
- https://medal.tv/clips/53062314/d1337Zqfp1CT
- https://www.youtube.com/watch?v=EradbrHdq3c

**Impact op de server**
De laten tijd komen er veel tickets binnen over mensen die dit probleem hebben waardoor vele (onnodige) refunds uitgeschreven moeten worden. Tevens kan het ook hinderlijk zijn wanneer iemand namelijk snel een wapen moet overgeven i.v.m. een achtervolging o.i.d.

**Comment by niekschoemaker** [comment]
Gaan de kogels echt verloren of blijven ze achter in de originele speler?
Want kan dus zijn dat ze gewoon niet overgegeven worden, dus dat ze gewoon op de andere speler blijven staan.

**Comment by MartijnMeister** [comment]
De kogels gaan volledig verloren. Ik heb dit even getest met een jerrycan. Jerrycan met 2314 (kogels) erin overgegeven aan een ander waarna deze 0 (kogels) had. Daarna heb ik deze weer teruggekregen waarna er nogsteeds 0 (kogels) inzaten.

**Comment by niekschoemaker** [comment]
Ik heb nu even een ductapeje erop geplakt, als je even kunt laten weten of dit nu gefixed is.

**Comment by MartijnMeister** [comment]
Zojuist getest samen met Anthony. Kogels blijven in het wapen zitten nadat een wapen overgedragen wordt. Tevens lijkt het er ook op dat het overdragen van wapens veel gemakkelijker is gezien je niet steeds de foutmelding krijgt dat je het wapen niet in je handen hebt.
