### ISSUE TITLE
Wapens op de grond droppen zorgt voor despawn & kogels zijn uit het wapen als je hem overgeeft

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#573]
**Omschrijf de bug**

als een persoon een wapen op de grond dropt word deze gedespawnd, het overgeven van wapens van persoon op persoon kan niet meer ook niet als je het wapen in je hand hebt, en als het wapen is overgegeven op een andere manier dan zijn alle kogels eruit terwijl er op het moment dat hij uit het huis word gehaald of auto nog wel gewoon kogels inzitten!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

wapen uit je huis halen en in je huis op de grond droppen
wapen overgeven aan persoon ( je krijgt dan melding dat het niet kan en dat je het wapen in je hand moet nemen en als je dat dan doet kan je het nog steeds niet overgeven)
stop een wapen in je huis met kogels, haal het er weer uit en doe het in een auto, laat de ander persoon het pakken dan zijn de kogels weg, en dit gebeurd ook met overgeven als dit wel lukt!

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Wapens horen niet te despawnen, kogels horen niet uit de wapens te verdwijnen (lijkt mij) en het overgeven van persoon aan persoon moet denk ik ook normaal kunnen!

**Screenshots en/of logbestanden**

zijn meerdere tickets over binnen gekomen, is een issue die al paar dagen gaande is

**Impact op de server**

veel refunds, en tickets omtrent wapens!

**Comment by niekschoemaker** [comment]
Duplicate van #572
