### ISSUE TITLE
Cuban 800 gaat kapot als je bij de kofferbak zit.

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#574]
**Omschrijf de bug**
Als je in de kofferbak kijkt van de cuban 800 dan kan het wel zo eens zijn dat hij random kapot gaat.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Dicht bij de binnenkant van de vleugels de kofferbak ingaan (zie filmpje). Het kan een paar keer proberen zijn.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou hij niet kapot moeten gaan.

**Screenshots en/of logbestanden**
https://streamable.com/u7z7fn

**Impact op de server**
Hierdoor is onnodige reparatie nodig of meerdere reports.

**Comment by niekschoemaker** [comment]
Ik laat deze issue even open staan met label wontfix en need repro voor nu gezien dit een nogal tricky issue is omdat dit meer een onesync/GTA related issue is voor zover ik kan zien.
Dus tenzij er echt een hele specifieke manier is om he 100% te kunnen triggeren is dit niet echt de tijd en moeite waard om er zelf blindelings naar te zoeken.

**Comment by Willem-Dekker** [comment]
Ik sluit deze issue nu heropen als er een Repro is
