### ISSUE TITLE
La icona hangaround job

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#576]
**Beschrijf zo duidelijk mogelijk de feature**
alle gangs hebben op dit moment al een hang around rang.

Alleen deze ontbreekt nog bij la icona. Door deze feature kunnen de hangarounds van la icona: in het huis, spullen in de opslag leggen/opslaan en de rest van de features die de andere groepen ook krijgen

De naam van de rang moet Novato worden. 

**Wat lost deze feature op?**
Dit zorgt ervoor dat de mensen die hangaround bij la icona zijn wat beter bij de groep kunnen horen en ook de special features krijgt.

**Comment by niekschoemaker** [comment]
Zit erin vanaf morgen, als hij niet goed staat issue ff heropenen.
