### ISSUE TITLE
Hoog Risico Beveiliging, EUP fouten

### ISSUE THREAD

**Issue by FoxOTF** [Tedeapolis/development#578]
# Waar zit het in EUP, interiors of retextures ?
Het EUP van de Kmar rang genoemd: Koninklijke Marechaussee HRB

# Link naar issue of coördinaten naar de plek
Issue kan je bekijken doormiddel van jezelf op KMAR job 70 te zetten > KMar > Hoog Risico Beveiliging 

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Dit is het huidige uniform wat erin zit van de HRB (Zie foto 1). Bij het huidige uniform zitten een paar fouten: Verkeerde baret, verkeerde workerbroek, verkeerde kisten (schoenen) tevens als je op X drukt (handen omhoog) dan gaan je armen door je kleding heen

# Wat is de toegevoegde waarde?
Dat de HRB ook zijn normale uniform aan kan doen via het EUP en niet custom outfits hoeft te gebruiken doormiddel om steeds naar hun appartement te gaan om dit te veranderen . Hierbij heeft de HRB (met goedkeuring van de HRB leiding) een uniform gemaakt wat wel past bij de baan dat zij uitvoeren "Zie foto 2 + juiste uniform nummers". 

Foto 1. (huidige uniform in de EUP)
![unknown](https://user-images.githubusercontent.com/80756288/120015369-8e406b80-bfe3-11eb-926c-52dc63a5cff6.png)
Foto 2.
![unknown2](https://user-images.githubusercontent.com/80756288/120015676-e4151380-bfe3-11eb-920b-9481ef69252b.png)

![unknown 1](https://user-images.githubusercontent.com/80756288/120015571-c2b42780-bfe3-11eb-87a6-e47cfabcfc77.png)

**Comment by walvisgedaan** [comment]
Ik zal hier binnenkort naar kijken

**Comment by Willem-Dekker** [comment]
Fixed voor morgen
