### ISSUE TITLE
BSB, EUP buitendienst niet werkend

### ISSUE THREAD

**Issue by FoxOTF** [Tedeapolis/development#579]
# Waar zit het in EUP ?
De issue zit in het EUP op de KMar rang met betrekking tot de bsb rangen Kmar80 - 81 - 82

# Link naar issue of coördinaten naar de plek
Jezelf op een KMar BSB rang zetten en dan /eup doen buiten dienst

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Normaliter hoort buiten dienst de EUP te verschijnen, echter is nu als je op 1 van de KMar rangen /eup doet buiten dienst werkt dit niet. Je krijgt dan links boven je map te zien (You are not permitted to use this command). Zie foto 1.

# Wat is de toegevoegde waarde?
Dat de KMar (BSB) de eup buiten dienst kunnen gebruiken en niet worden neergeschoten door collega's ivm verwarring, echter is dit wel mogelijk op alle Politie (DSI) rangen.

![](https://cdn.discordapp.com/attachments/795660699749711922/847901409466122240/111317379-66886b00-8664-11eb-91f7-e606b82c3c95.png)

**Comment by Willem-Dekker** [comment]
dit zou gewoon moeten werken nu wat ik zo zie
