### ISSUE TITLE
Zijn deze veranderingen mogelijk?

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#580]
- [x] Dat meldingen op de telefoon groen worden als je een klant belt. 
**Wat lost dit op**: Dat er meer overzicht komt in de meldkamer in-game op de telefoon
- [ ] Dat anwb'ers als ze in-dienst zijn mensen anoniem kunnen bellen. Dat er bijvoorbeeld hier iets tussen komt staan? (kijk screenshot)
**Wat lost dit op**: Dat anwb'ers niet meer terug worden gebeld 1 dag later met de vraag of ze nu in-dienst zijn/ en of ze nu hun voertuig kunnen maken.
![Knipsel](https://user-images.githubusercontent.com/68514420/120119266-17e46a80-c197-11eb-9eda-45750a40e5a8.PNG)
![Knipsel1](https://user-images.githubusercontent.com/68514420/120119268-187d0100-c197-11eb-97e5-430403ca7552.PNG)

**Comment by niekschoemaker** [comment]
Eerste functionaliteit zit erin, 2e functionaliteit, geen flauw idee hoe ik dat zou moeten aanpakken.

**Comment by AdventurePandah** [comment]
Ik ga er vanuit dat jullie GCPhone gebruiken. 
![image](https://user-images.githubusercontent.com/47216413/121431168-589f6900-c979-11eb-8c1f-2cf1d1c0eaac.png)
In principe kun je de bovenstaande bel functie (waarschijnlijk `this.startCall({ numer: data.number })`) kopieëren en een nieuw item toevoegen met 'Anoniem bellen'. De functie daarachter is dan `this.startCall({ numer: '#' + data.number })`

**Comment by DeStefanoKiller** [comment]
@niekschoemaker heb je hier iets aan? ^ 

of mogelijk dit: https://github.com/niekschoemaker/gcphone/pull/4

**Comment by JordyHeemskerk** [comment]
@niekschoemaker bump 😇 

Is als het goed is inderdaad zo simpel als @AdventurePandah zegt, dat is ook wat ik gevonden had, zie ook mijn pull request die @DeStefanoKiller linkte, hoop dat de ANWB (en andere diensten) hier snel gebruik van kunnen maken 😄

**Comment by Willem-Dekker** [comment]
@JordyHeemskerk nergens voor nodig dit

**Comment by JordyHeemskerk** [comment]
Dit zou het werkt van de ANWB 1000x chiller maken, gezien je niet terug gebeld kunt worden. We kregen hierop het antwoord toen we dit aanvroegen dat het niet bekend was hoe dit aangepakt moest worden. Nou, nu zijn er twee mensen die hebben laten zien hoe dit zou kunnen, maar lijkt deze bedolven te zijn onder alle andere issues, gezien er meer dan een maand geen comment op geweest is. Ipc zou het zo simpel moeten (kunnen) zijn als de pull request accepten... Maar anyway, ik ga hier in ieder geval geen verdere tijd meer aan besteden, hoop dat het gaat komen voor mijn ex-collegas @ de ANWB.

Veel success nog, heb verder erg genoten van TDA, maar heb nu helaas geen tijd meer, ivm prive bezigheden.
