### ISSUE TITLE
Voertuig namen garage eiland | Burgerraad

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#581]
**Beschrijf zo duidelijk mogelijk de feature**
De aanvraag om het mogelijk te maken dat je een voertuig kunt renamen in de garage netzoals op het main land

**Wat lost deze feature op?**
Worden garage's overzichtelijker door en is het rechtgetrokken met het mainland

**Comment by niekschoemaker** [comment]
Support voor display van kentekens en het aanpassen en weergeven van namen zit erin voor de andere garage's (dus vliegtuig, helikopters, narcopolis, karts en boten)
