### ISSUE TITLE
Kledingcirkel ganghuizen | Burgerraad

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#582]
**Beschrijf zo duidelijk mogelijk de feature**
De aanvraag om cirkels in de ganghuizen te plaatsen netzoals in de basic fat waar je je outfit kunt veranderen

**Wat lost deze feature op?**
Is al een aantal keer aangepast, voegt ook het puntje easy to use toe kenneth zal hier naar kijken dus ik mention hem hierin

**Comment by Willem-Dekker** [comment]
Zit er morgen in
