### ISSUE TITLE
Safezone CBR | Staffoverleg 30-05-2021

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#584]
**Beschrijf zo duidelijk mogelijk de feature**
De aanvraag zoals besproken in staffoverleg om van het cbr een safezone te maken

**Wat lost deze feature op?**
dit om te voorkomen dat mensen daar overvallen worden, zomaar vermoord worden etc.. puur omdat hier meestal de nieuwe mensen zijn die het nog niet helemaal snappen

**Persoon staffoverleg**
Puntje in staffoverleg aankaart door Ronald D github namens hem gemaakt

**Comment by niekschoemaker** [comment]
Heb perongeluk ook 1 toegevoegd bij UWV, dus heb nu bij CBR en UWV een safe zone.
