### ISSUE TITLE
Onjuist eilandvoertuig bij aankoop

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#586]
**Omschrijf de bug**
Bij de voertuigshop op het eiland lijkt het erop dat de voertuigen soms niet goed inladen.
Het kan hierdoor voorkomen dat een verkeerd voertuig in je garage komt te staan wanneer je een ander voertuig aankoopt. Als voorbeeld onderstaande video:
Persoon wilt een Offroad Transporter kopen, echter nadat deze is aangekocht staat er een Safari Jeep in meneer zijn garage.
Voor wat ik zelf heb kunnen zien is dat er bij meneer 2 models waren ingeladen (zie foto). Van deze 2 models was de Offroad Transporter het voertuig wat meneer had geselecteerd om te kopen, maar meneer zat in de shop zelf op de Safari Jeep die door onbekende reden ook was ingeladen.
Doordat meneer op de Safari Jeep zat bij aankoop is deze in zijn garage terecht gekomen i.p.v. de Offroad Transporter.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Om de bug te reproduceren zou je naar de voertuigshop op Narcopolis moeten gaan.
Hierbij zal je door de lijst moeten gaan van voertuig en uiteindelijk stil moeten gaan staan op voertuig "x". Hierbij kan het voorkomen dat er 2 models inladen. Wanneer dit gebeurd zal je het voertuig moeten aankopen waarna je merkt dat het verkeerde voertuig in je garage terecht komt.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou het voertuig gekocht moeten worden dat je daadwerkelijk hebt geselecteerd.

**Screenshots en/of logbestanden**

Video: https://www.youtube.com/watch?v=3BC97HmOpW0&t=6s

Foto: 
![image](https://user-images.githubusercontent.com/72617118/120619182-0aabd200-c45c-11eb-948b-5087082619d2.png)

**Impact op de server**

Door deze bug ontstaan onnodige tickets gezien de voertuigen verwijderd moeten worden van mensen hun accounts / een refund uitgeschreven dient te worden.

**Comment by niekschoemaker** [comment]
Ik heb een extra check toegevoegd, deze zou dit hopelijk moeten fixen.
