### ISSUE TITLE
facturen overheidsbanen 

### ISSUE THREAD

**Issue by Taker1987** [Tedeapolis/development#587]
**Omschrijf de bug**
de overheidsdiensten kunnen geen facturen sturen , er komt geen melding dat de factuur gestuurd is , of je krijgt de melding : probeer het over een aantal seconden nog een keer . 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

je kan het testen via het f6 menu is of je zelf de baan geven van een overheidsbaan 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
de factuur hoort bij de speler binnen te komen 

**Screenshots en/of logbestanden**

**Impact op de server**

**Comment by Willem-Dekker** [comment]
Zou fixed moeten zijn
