### ISSUE TITLE
Smoke aanzetten voor stuntvliegtuigen

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#588]
**Beschrijf zo duidelijk mogelijk de feature**
Dat de smoke aankan voor stuntvliegtuigen zodat er bijvoorbeeld airshows mee gedaan kunnen worden. 

**Wat lost deze feature op?**
Dan worden de stuntvliegtuigen op meerdere manieren gebruikt. :)

**Comment by Chang-nl** [comment]
zit erin na de volgende restart!
voor de volgende voertuigen:
stunt
alphaz1
miljet
