### ISSUE TITLE
Pistol MKII Toevoegen aan /takehostage

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#589]
**Beschrijf zo duidelijk mogelijk de feature**
Zoals de title al luid het toevoegen van de pistol MKII/Beretta aan het /takehostage command aangezien dat op dit moment dus nog niet kan

**Wat lost deze feature op?**
Denk dat dit pistol vergeten is bij deze functionaliteit, daarnaast is het ook realistisch dat het kan met elk soort pistol en :)

**Comment by niekschoemaker** [comment]
Done.
