### ISSUE TITLE
Schietmeldingen Politie werken niet.

### ISSUE THREAD

**Issue by Jesse-Poolman** [Tedeapolis/development#59]
Agenten, DSI, Eerstehoofdcommensaris krijgen geen schietmeldingen binnen al ruim 1,5 week niet. Kan hier naar gekeken worden?

**Comment by Willem-Dekker** [comment]
er is een random kans, dat er een melding wordt gemaakt

**Comment by Willem-Dekker** [comment]
is dit nog steeds een issue?

**Comment by Jesse-Poolman** [comment]
Nee, is opgelost
