### ISSUE TITLE
ATC bug: Mensen praten in ATC zonder in ATC te praten

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#592]
**Omschrijf de bug**
Bij sommige mensen kan het gebeuren dat op het moment je normaal praat, je dit in de ATC hoort. Dit is enkel wanneer je in een vliegtuig of helikopter vliegt/zit. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In een vliegtuig zitten, ATC aanzetten op je radio en hier gebruik van maken. Als je geluk hebt dan wordt elke voice actie naar de ATC gestuurd.
Probleem is niet op te lossen door
- te reloggen
- radio aan/uit doen
- in en uitstappen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Wanneer je je radio knop (capslock) indrukt dat mensen je dan alleen horen in ATC. Wanneer je normaal praat in heli niet.

**Screenshots en/of logbestanden**
NVT

**Impact op de server**
Elk persoon in een heli of vliegtuig hoort je praten. Is erg hinderlijk en ATC raakt ontregeld.

**Comment by niekschoemaker** [comment]
Is er iets als een patroon wat dit triggered? Gezien ik moeilijk kan "hopen" dat ik de issue succesvol kan reproduceren.
