### ISSUE TITLE
ATC: Permissies voor vlieginstructeurs voor ATC

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#593]
**Beschrijf zo duidelijk mogelijk de feature**
Vlieginstructeurs mogen reageren op ATC commando's. Echter merk je vaak wel dat dit enkel gebeurd als er toevallig een vlieginstructeur in een vliegtuig/heli zit. Daarnaast is het momenteel niet mogelijk voor een vlieginstructeur om contact op te nemen met een helikopter vanaf de grond om bijvoorbeeld vlieggedrag op te merken. Vandaar deze feature request.
De 'feature' is eigenlijk heel simpel, op het moment iemand vlieginstructeur permissies heeft mag deze persoon de ATC altijd joinen waar en wanneer deze persoon ook is.

**Wat lost deze feature op?**
Hierdoor is het mogelijk voor vlieginstructeuren om mensen op vlieggedrag aan te spreken of om te reageren op de calls van vliegers.

**Comment by niekschoemaker** [comment]
Ah ja dit is iets wat ik ooit perongeluk eruit gehaald heb en dus al deze tijd niet door had, heb het gefixed voor volgende restart.

**Comment by AdventurePandah** [comment]
Destijds was dit opgelost. Echter doet het probleem zich opnieuw voor. Om de ATC te joinen is het verplicht om in een helikopter te zitten. Dit is erg lastig voor vlieginstructeurs die willen meeluisteren en erop willen reageren.
