### ISSUE TITLE
Omzeilen van opstijg timer vliegtuigen / helikopters

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#594]
**Omschrijf de bug**
Sinds een tijdje is er een cooldown gezet op het opstarten van motoren van zowel vliegtuigen als helikopters. Deze timer valt echter te omzeilen door het voertuig in en uit de garage te halen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Het volgende zal moeten gebeuren om de bug te reproduceren (de bug is enkel werkend op plekken waar voertuigen spawnen op de rode cirkel).

1. Pak een helikopter / vliegtuig uit de opslag
2. Start de enige
3. Zet de helikopter / het vliegtuig direct weer weg
4. Ren naar het punt waar je het voertuig kan pakken
5. Pak direct hetzelfde voertuig
6. Zet de engine aan
7. Je kan direct opstijgen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou het geblokkeerd moeten zijn dat je direct kan opstijgen wanneer je een luchtvoertuig uit de opslag haalt. Hierbij zou je simpelweg moeten wachten totdat de motoren full speed draaien.

- Eventueel zorgen dat helikopters en vliegtuigen niet spawnen op de rode cirkel? 

**Screenshots en/of logbestanden**
Indien nodig kan ik een video toevoegen.

**Impact op de server**
Mensen kunnen er misbruik van maken wanneer ze snel weg moeten komen. Verder is het een simpele omzeiling van de block die erop is gezet om te voorkomen dat mensen direct kunnen opstijgen.

**Comment by niekschoemaker** [comment]
Is als het goed is nu gefixed.
