### ISSUE TITLE
Bug met de tas op en af doen

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#595]
**Omschrijf de bug**
Elke keer als je jouw rugtas op en af doet gaat er 10 kilo van je gewicht af.
Nu heb je dan op een gegeven moment 10 kilo gewicht dat je kan dragen met rugtas om. Dit hoort niet te gebeuren

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je moet jou rugtas op en af doen een paar keer.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou de rugtas meer gewicht erbij moeten geven en dan weer terug naar het oude gewicht.

**Screenshots en/of logbestanden**
https://streamable.com/36krj9
Vaag filmpje waar je het ziet gebeuren
**Impact op de server**
Medium, mensen kunnen hierdoor geen criminelen dingen doen of iets anders bij zich hebben

**Comment by niekschoemaker** [comment]
Is gefixed na volgende herstart.

**Comment by JorisDeJoris** [comment]
Net weer gekeken @niekschoemaker maar de bug zit er nog steeds in https://streamable.com/wk5uki
