### ISSUE TITLE
aanpassen F6 menu Ambulance

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#596]
**Beschrijf zo duidelijk mogelijk de feature**
De politie en ANWB hebben eerst de optie om een ID te selecteren voordat ze iets 
kunnen uitvoeren met een persoon. Bij ambulance gebeurt dat op basis van wie in range staat.
Verzoek om ook voor Ambulance de mogelijkheid te geven om een ID te selecteren 
van een persoon waarvan ze bijvoorbeeld een hartslag willen checken.

**Wat lost deze feature op?**
Gebruiksgemak, nu moet er vaak gevraagd worden dat mensen afstand nemen, wat prima is
maar niet altijd lukt. Door een ID te selecteren weten ambulanciers zeker dat ze de juiste persoon hebben.

**Comment by Willem-Dekker** [comment]
Zit er na restart in als het goed is
