### ISSUE TITLE
Blokkeren contacten mobiele telefoon

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#597]
**Omschrijf de bug**
Wanneer je een nummer blokkeert in je telefoon "werkt" dit maar de persoon kan je vervolgens
nog steeds bellen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Iemand blokkeren en dan diegene je laten bellen, wat als het goed is nog steeds zou moeten werken
ondaks de blokkade.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Wanneer je iemand blokkert, moet diegene je niet meer kunnen bellen.

**Screenshots en/of logbestanden**
\

**Impact op de server**
Medium, erg storend voor spelers die lastiggevallen worden door iemand
en ze deze niet kunnen blokkeren.

**Comment by niekschoemaker** [comment]
Is gefixed (hopelijk)
Anders issue ff reopenen.
