### ISSUE TITLE
Bug sirenes / zwaailichten

### ISSUE THREAD

**Issue by VeerleDoorgeest** [Tedeapolis/development#60]
- De sirenes / zwaailichten zouden niet synced zijn. Als je ze uitzet, blijven ze voor andere mensen aanstaan en soms horen mensen de sirenes niet terwijl ze wel aanstaan.

**Comment by niekschoemaker** [comment]
Ik zal even kijken, dacht dat ik hier al een workaround voor had gemaakt maar dan werkt deze dus niet helemaal.

**Comment by niekschoemaker** [comment]
Denk dat ik de issue al heb, zal deze zo even naar main toe pushen

**Comment by Willem-Dekker** [comment]
gezien er na 3 dagen geen reactie is gaan we er van uit dat het is opgelost
