### ISSUE TITLE
Berging Job Kaput

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#601]
**Omschrijf de bug**

Mensen pakken een boot en zien geen gele cirkel waar ze heen moeten, op sommige locaties kan je geen wrak bergen waardoor je dus niets meer kan om verder te werken!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Berging job starten.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

normaal hoor je met f9 een gele stip te krijgen waar je heen hoort te gaan en daar dan een wrak te kunnen bergen door op E te drukken!

**Screenshots en/of logbestanden**

Meerdere tickets en videos over binnen gekomen staan bij Niek zijn cat.

**Impact op de server**

Mensen kunnen de berging job niet meer doen!

**Comment by niekschoemaker** [comment]
Als het goed is is deze issue ondertusesn opgelost
