### ISSUE TITLE
Aanhanger winkel 

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#602]
**Omschrijf de bug**

mensen kunnen geen aanhangers meer kopen bij de aanhangercirkel

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

probeer een aanhanger te kopen.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

in de groene cirkel moet je aanhangers kunnen kopen en dit gaat op dit moment niet

**Screenshots en/of logbestanden**

ticket aangemaakt staat bij Niek zijn cat.

**Impact op de server**

Mensen kunnen geen aanhangers meer kopen!

**Comment by niekschoemaker** [comment]
Is gefixed
