### ISSUE TITLE
Stickers veranderen random op voertuig in mod shop

### ISSUE THREAD

**Issue by StoffigKontje** [Tedeapolis/development#603]
**Omschrijf de bug**
Deze is aangegeven door discord user Letix#3462 [487228252272984065]. Wanneer hij zijn voertuig in de mod shop wil aanpassen en gewoon door het menu scrollt, krijgt hij andere stickers op zijn auto. Daarnaast zitten er ook andere stickers op zijn voertuig wanneer hij deze uit de garage haalt. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
https://streamable.com/5u3fvu

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De stickers zouden niet random moeten veranderen. 

**Screenshots en/of logbestanden**
https://streamable.com/5u3fvu

**Impact op de server**
tot nu toe alleen deze speler er over gehoord. Nog niet meer klachten binnengekregen.

**Comment by niekschoemaker** [comment]
Is niet te fixen, als je een livery koopt is het probleem opgelost.
