### ISSUE TITLE
Rijbewijs kunnen geven uit voertuigen

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#606]
**Omschrijf de bug**
Je kunt momenteel geen ID-kaarten en/of rijbewijzen geven terwijl je in een voertuig zit.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In een voertuig zitten en de bovenstaande items aan iemand anders proberen te geven

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Dit zou gewoon moeten kunnen

**Screenshots en/of logbestanden**
n.v.t.

**Impact op de server**
HEEEEL GROOOT xD

**Comment by Willem-Dekker** [comment]
zou moeten werken
