### ISSUE TITLE
Vito Politie kofferbak

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#609]
**Beschrijf zo duidelijk mogelijk de feature**
Grotere kofferbak voor de Vito van de politie.

**Wat lost deze feature op?**
Dat er 20 keer heen en weer moet worden gereden bij een huiszoeking met in beslag genomen drugs. Het is teven ook wel realistisch dat er meer dan 40KG in gaat.

**Comment by Willem-Dekker** [comment]
Hoe veel opslag stel je voor?

**Comment by SecretSupplier** [comment]
Het maakt het voor ons veel makkelijker als er 200KG in kan. Maakt de RP ook realistischer gezien je dan niet elke keer heen en weer rijdt.

**Comment by Willem-Dekker** [comment]
zit er morgen in
