### ISSUE TITLE
Ford Raptor Pantser niet werkend

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#610]
**Omschrijf de bug**

Het pantser op een Ford Raport werkt niet, een tik tegen een muur, paaltje of auto en hij is instant kapot zelfs met full pantser

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Pantser op een Ford Raptor zetten en dan rammen lijkt me :D

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Normaal zou er wel wat schade kunnen komen voordat hij instant rood lampje heeft in dit geval is dat dus helemaal niet werkend

**Screenshots en/of logbestanden**

geen logbestanden, wel meerdere tickets in afgelopen weken

**Impact op de server**

Mensen met een Ford Raptor hebben dus sneller de auto kapot terwijl ze wel betaald hebben voor de pantser tune

**Comment by niekschoemaker** [comment]
Ik kan zelf met zo'n 130 tegen een muur aan rijden en alleen oranje lampje krijgen dus lijkt me te werken zoals het hoort.
