### ISSUE TITLE
Taakstraf bug - Belangrijk!

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#613]
**Omschrijf de bug**
Als je klaar bent met taakstraf en teleporteerd naar HB kom je vast te zitten in het HB gebouw

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Jezelf op taakstraf sturen en zorgen dat je klaar bent daarna geteleporteerd worden naar HB en dan zal je als het goed is vast komen te zitten

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je goed in de lift komen en gewoon door kunnen lopen naar buiten

**Screenshots en/of logbestanden**
—

**Impact op de server**
Hierdoor worden er veel reports gemaakt en is het hinderlijk voor spelers

**Comment by Willem-Dekker** [comment]
fixed na restart van de server is nu voor het bureau
