### ISSUE TITLE
BUG taakstraf 

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#614]
**Omschrijf de bug**
Zodra je taakstraf voorbij is bug je in het politie bureau en moet je knipperen 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
je zelf taakstraf geven en eraf halen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je op locatie 1 moeten spawnen en kunnen weg lopen nu kan dit niet, dus misschien de spawn buiten HB zetten

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/82154593/123307312-a217b880-d522-11eb-91b7-43ef44cda7e3.png)

**Impact op de server**
Medium, heel veel mensen lopen vast

**Comment by Willem-Dekker** [comment]
Is al fixed
