### ISSUE TITLE
Banken bug  

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#615]
**Omschrijf de bug**
Als je een bank overvalt dan kan je hem hacken, nadat je hem hackt stopt het en krijgen de mensen geen geld of kunnen ze niet door de deuren heen om geld te krijgen

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je doet een bank overval

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je moet naar binnen kunnen lopen door de deuren (die je opblaast of open hackt) en dan het geld kunnen pakken

**Screenshots en/of logbestanden**
Niek weet ervan

**Impact op de server**
Groot

**Comment by niekschoemaker** [comment]
Als het goed is is dit morgen opgelost
