### ISSUE TITLE
mercxclass geen grip offroad

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#617]
**Omschrijf de bug**
`De mercxclass kan offroad maar heeft totaal geen grip

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Inspawnen en rijden maar?

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Het is een offroad en die zou redelijk goeie grip moeten hebben offroad

**Screenshots en/of logbestanden**

Geen van, alleen via ticket

**Impact op de server**

Niet veel lijkt me zo

**Comment by Willem-Dekker** [comment]
ik zie niks geks

**Comment by musician1011** [comment]
Zal verbeterd zijn bij de volgende restart.
