### ISSUE TITLE
Parachute niet weg uit weaponwheel

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#618]
**Omschrijf de bug**

De parachute kan niet meer in een auto worden gedaan, niet op de grond worden gedropt en na de sprong met een parachute gaat hij niet weg uit je inventory/weaponwheel

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Probeer er een te kopen aangezien hij als wapen word gezien kan je er niet zoveel mee

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
als je bent gesprongen met parachute dan hoort die uit je inventory te zijn, ook kan je hem niet meer overgeven, in een auto doen, of op de grond droppen

**Screenshots en/of logbestanden**
geen logs, wel tickets en ingame reports

**Impact op de server**
 niet veel alleen neemt ruimte in die mensen dan nodig kunnen hebben in inventory

**Comment by niekschoemaker** [comment]
Is gefixed (denk ik)
Ff checken, anders issue ff reopenen.
