### ISSUE TITLE
Togglechat toont nog reports

### ISSUE THREAD

**Issue by ToniGain** [Tedeapolis/development#621]
**Omschrijf de bug**
Op het moment dat je togglechat hebt, blijft de chat terug komen zodra er reports binnen komen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Log in, doe /togglechat en zie het vanzelf.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De chat moet hidden blijven.

**Screenshots en/of logbestanden**
n.v.t.

**Impact op de server**
Klein, maar voor content creator en staff zijnde redelijk vervelend

**Comment by niekschoemaker** [comment]
Dat gedrag hoort zo.

Ik heb nu toegevoegd dat je /report_settings ignore_toggle_chat kunt doen om dit gedrag uit te zetten.
Als je in dienst bent zul je wel ten allen tijden reports zien.
