### ISSUE TITLE
Kledingcirkel in HB toevoegen zodat vrouwen daar kunnen omkleden

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#622]
**Beschrijf zo duidelijk mogelijk de feature**
Kleding cirkel in het HB zodat vrouwelijke characters niet meer eerst naar hun appartement toe moeten om om te kleden. 

**Wat lost deze feature op?**
Aangezien er momenteel geen Eup is voor vrouwelijk Kmar leden hebben zij zelf outfits samen gesteld en kunnen zij deze enkel in een appartement aantrekken

**Comment by Willem-Dekker** [comment]
heb een temp oplossing gemaakt door zelfgemaakte outfits te maken in eup
