### ISSUE TITLE
ANWB Flatbed achterkant kan niet uitklappen

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#623]
**Omschrijf de bug**
Normaal als je naast het voertuig staat aan de achterkant, dan komt er "druk op E om de ramp te nemen / weg te nemen" maar dit komt er nu niet meer te staan. Daardoor kan er nu geen ramp worden uitgeschoven.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
/car flatbed spawnen en naar links/rechts achter lopen van het voertuig en dan kun je zien dat het niet werkt. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Als je links of rechts achter bij het Flatbed stond moest er "druk op E om de ramp te nemen / weg te nemen" komen te staan en als je dan op E drukte dan kwam er een ramp aan het achterkant van de Flatbed.

**Screenshots en/of logbestanden**
Hopelijk heb je iets aan de bijlage: 
![Flatbed](https://user-images.githubusercontent.com/68514420/124348899-e96e0b00-dbec-11eb-9fa4-4225349b9a8b.PNG)

**Impact op de server**
Wij kunnen nog steeds voertuigen takelen via het F6 menu, dus de impact is niet zo groot.

**Comment by Willem-Dekker** [comment]
zou fixed moeten zijn
