### ISSUE TITLE
EUP van de Recherche offduty

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#624]
**Beschrijf zo duidelijk mogelijk de feature**
Op dit moment kan de recherche geen EUP buiten dienst gebruiken. Dit zorgt ervoor dat ze niet kenbaar kunnen gemaakt worden als DSI. Hierdoor gebeurt er vaak friendly fire.

**Wat lost deze feature op?**
Dit lost op dat de recherche zichzelf kenbaar kan maken als Politie buiten dienst als ze moeten ingrijpen. En niet dood word geschoten door andere politie agenten.

**Comment by Willem-Dekker** [comment]
fixed
