### ISSUE TITLE
Voertuig off-road bugs

### ISSUE THREAD

**Issue by niekschoemaker** [Tedeapolis/development#625]
Laat hier comment achter met spawn naam van voertuigen die broken zijn, bedrankt.

**Comment by TDA-SanderD** [comment]
bf400 - Politie dirtbike: gaat langzamer dan normale off-road motoren

**Comment by TDA-SanderD** [comment]
pamarok - Politie amarok: gaat langzamer dan normale off-road voertuigen

**Comment by ToyStoner** [comment]
Ford Raptor 2019
Dodge Ram
Mercedes G65 6x6
Mercedes G65 AMG
Nissan Titanwarrior
Manchez
Clifhanger
.
.
.

**Comment by ToyStoner** [comment]
/car raptor2017
/car ram2500lifted
/car dubsta3
/car g65amg
/car nissantitan17
/car manchez
/car africat
/car kamacho

ly niek

**Comment by musician1011** [comment]
@ToyStoner wat scheelt er dan met die hele lijst?
