### ISSUE TITLE
Vliegtuigen Random ontploffen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#631]
**Omschrijf de bug**

Mensen die random in hun vliegtuig gaan hebben het risico dat het vliegtuig ontploft, ook gebeurt dit met tanken en soms ook geheel random als die stil staat, via fixvehicle is het voertuig dan ook niet te maken en blijft geheel uit elkaar vallen!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Vliegtuig pakken en voor zover ik weet is het vooral bij de DODO

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Lijkt me toch dat dit niet zou moeten gebeuren!

**Screenshots en/of logbestanden**

Logs niet, was wel meerdere voorbeelden via tickets en gezien ingame

**Impact op de server**

Vliegtuigen ontploffen random, is niet echt fijn voor de mensen die inladen en uitladen en moeten tanken en kunnen dan niet meer verder

**Comment by Willem-Dekker** [comment]
kunnen we niks mee
