### ISSUE TITLE
Safezone bij HB verwijderen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#632]
**Beschrijf zo duidelijk mogelijk de feature**

Om de mogelijkheid te bieden het uitbreken bij cellenblok realistischer te maken en te houden de safezone bij HB te verwijderen, hierbij wel bij Politie duidelijk te vermelden dat ze minimaal 2 brood en water aan de gevangene geven, Mocht de persoon hier misbruik van maken en zelfmoordplegen om eruit te komen instant accountwipe!

**Wat lost deze feature op?**

De roleplay voor uitbraken word hiermee realistisch gemaakt dat er ook geweld gebruikt mag worden en de politie net als de criminelen zich kunnen verweren/verdedigen! (besproken stafoverleg vorige week zondag!)

**Comment by Willem-Dekker** [comment]
done
