### ISSUE TITLE
Taakstraf gebied safe zone maken

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#633]
**Beschrijf zo duidelijk mogelijk de feature**

Een safezone zetten bij de taakstraf plek, waardoor mensen niet dood kunnen gaan door brood en water te kort, en dat vrienden van buitenaf niet daar komen om ze daar dood te kunnen maken/te kloten

**Wat lost deze feature op?**

Minder reports voor mensen die doodgaan op taakstraf plek, minder gekloot

**Comment by Willem-Dekker** [comment]
done
