### ISSUE TITLE
Sleepwagen auto kan niet achterop vast

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#636]
**Omschrijf de bug**
De nieuwe sleepwagen van 500.000 euro is kapot. Als je je voertuig achterop wil vastmaken door 'E' krijg je die optie niet en hij wilt hem dus ook niet vasthaken.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Sleepwagen pakken en proberen je auto vast te maken op de truck

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je linksboven in je scherm 'Druk op E op hem vast te maken' staan. en zou die dan automatisch vastklikken

**Screenshots en/of logbestanden**
https://streamable.com/vlegpj

**Impact op de server**
Hierdoor is een truck die zeer prijzig is niet te gebruiken waar hij voor bedoeld is

**Comment by Willem-Dekker** [comment]
zou fixed moeten zijn
