### ISSUE TITLE
Documenten geven via ID

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#637]
**Beschrijf zo duidelijk mogelijk de feature**

Bij het geven van een document via /docu enkel het id laten zien wat de persoon dichtbij. Momenteel wordt namelijk de steamnaam + id getoond.

**Wat lost deze feature op?**

Het voorkomt misbruik van mensen die /docu gebruiken om erachter te komen wie iemand is.

**Comment by Willem-Dekker** [comment]
zou er na de restart in moeten zitten.
