### ISSUE TITLE
Error bij aankoop attachments voor de AK-74u.

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#638]
**Omschrijf de bug**

Voor de AK-74u (weapon_compactrifle) zouden twee verschillende attachments beschikbaar moeten zijn:
- clip_extended --> € 32.500
- clip_drum -->€ 65.000

Momenteel is het echter zo dat het niet mogelijk is om deze erop te zetten.
Wanneer je naar het kopje "Koop wapen mods" gaat en hierin op AK-74u klikt krijg je een error te zien in F8 waarna je het menu verlaat.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Koop een AK-74u in vanuit een gangopslag.
Ga naar het kopje "Koop wapen mods" en druk op AK-74u.
Om het moment dat je hierop klikt komt er een error in F8 te staan.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Normaal zou je de attachments op dit wapen moeten kunnen zetten zonder deze error te krijgen.

**Screenshots en/of logbestanden**

![image](https://user-images.githubusercontent.com/72617118/124516706-92ca2200-dde2-11eb-9403-914f0b272557.png)

**Impact op de server**

Het is momenteel onmogelijk om aan attachments te komen voor de Compact Rifle. Wat vervelend is voor de mensen die hier gebruik van willen maken.

**Comment by niekschoemaker** [comment]
Lol ja dit wapen heeft helemaal geen drum mag...

K heb hem uit de menu's verwijderd nu
