### ISSUE TITLE
Nieuwe anwb kleding eup

### ISSUE THREAD

**Issue by lexdeboer** [Tedeapolis/development#639]
# Eventueel nieuwe ANWB kleding
# Waar zit het in EUP, interiors of retextures ?
retextures, Eup

# 1: Een ANWB leiding vest ( Dit ovd vest een ANWB leiding vest van maken )
![ANWB leiding vestje](https://user-images.githubusercontent.com/72770931/124673629-7d73f700-deb9-11eb-9ce0-3f7a066a46d6.PNG)

 # 2: teamleider pakje voor vrouwen ( Heb zo even geen voorbeeld )

 # 3: Nieuw ANWB baas pakje ( korte mouwen )
( dit is de huidige ) 
![nieuw bazen pakje](https://user-images.githubusercontent.com/72770931/124673678-9b415c00-deb9-11eb-89aa-55f0c5ccfc89.PNG)
 
 # Wat is de toegevoegde waarde?
 # 1: is handig voor onze opco's zodat je kan zien wie op moment de leiding heeft.

# 2: Voor als er eventuele vrouwlijke teamleiders bij de anwb komen, dan hebben hun ook een eigen pakkie.

# 3: Meer diversie tijd anderen kleding die je kan aandoen, niet altijd hetzelfde.

**Comment by lexdeboer** [comment]
@walvisgedaan kleine reminder

**Comment by walvisgedaan** [comment]
Wordt meegenomen in grote EUP update.
