### ISSUE TITLE
Loonen van de KMAR 

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#64]
In dienst lonen blijven en de uitdient lonen zijn aan gepast (zie mooie foto)
uitdienst:
Aspirant  : 150
Surveillant  : 175
Opperwachtmeester : 200
Kapitein : 250
Kolonel : 275
Generaal-Majoor : 300
Luitenant-Generaal : 350

https://user-images.githubusercontent.com/68496405/89126572-d1769e80-d4e6-11ea-894e-1947b354942b.png

**Comment by Willem-Dekker** [comment]
done
