### ISSUE TITLE
Cuban 800 meerdere problemen

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#640]
**Omschrijf de bug**
Als je de Cuban 800 op het water parkeert bij het strand ( wat hoort te kunnen) en uitstapt ontploft hij automatisch en ga je instant dood. Ook is de issue met de kofferbak ook nog steeds

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Cuban 800 parkeren op het water bij het strand en uitstappen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
normaal zou hij niet moeten ontploffen en jij doodgaan

**Screenshots en/of logbestanden**
https://streamable.com/tely2g

**Impact op de server**
Er komen hierdoor veel reports en ambu meldingen die voorkomen kunnen worden

**Comment by TDAMarvinW** [comment]
Hey Mila!

Hier is al een keer door Niek naar gekeken.
Helaas valt er weinig tot niks aan te doen.

Wat je kan doen om dit te verminderen / tegen te gaan is het volgende:
De wielen uitklappen en de dodo op het strand landen.

Maar als ie half op het water is en half op het land ontploft ie inderdaad 😢
