### ISSUE TITLE
Repairkit kunnen kopen op Narcopolis

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#643]
**Beschrijf zo duidelijk mogelijk de feature**
Het mogelijk maken om repair kits te kunnen kopen op Narcpolis.
Momenteel is de enige plek waar je ze kan verkrijgen op t mainland, en hij is vaak meer benodigd op het eiland.

**Wat lost deze feature op?**
Staan vaak mensen met een kapotte wagen op Narco.
Kunnen (als ze geen repairkit hebben) geen kant op, dus dumpen ze maar hun voertuig over het hele eiland. En die blijven daar dan ook tot de server restart.

**Extra toelichting**
Kwam van een suggestie van een speler.
Kreeg in een relatief korte tijd aardig wat upvotes, dus even pijlen wat jullie ervan vinden en wat de mogelijkheden hierin zijn. (waar je ze dan kan kopen etc.)

**Comment by brothasx** [comment]
Na de restart zit deze in de shop op Narcopolis
