### ISSUE TITLE
Kofferbak G800 gelijktrekken met G65

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#644]
**Beschrijf zo duidelijk mogelijk de feature**
De kofferbak van de Brabus G800 (huidig 70kg) gelijktrekken met die van de G65 AMG (huidig 100kg)

**Wat lost deze feature op?**
Is een tijd geleden besproken dat de kofferbakken beide 100kg zouden worden.
Zag er toevallig een suggestie van dus ging even naar de status zoeken, enkelt heb ik geen open github o.i.d zien staan. En ingame zijn de kofferbakken ook nog verschillende dus ik denk ik maak er maar één aan.

**Comment by niekschoemaker** [comment]
Done.
