### ISSUE TITLE
Handschoenen toevoegen aan EUP kleding ambulance

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#652]
# Waar zit het in EUP, interiors of retextures ?
Ambulance EUP

# Link naar issue of coördinaten naar de plek

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Er ontbreken handschoenen bij de EUP van ambulance.

# Wat is de toegevoegde waarde?
Handschoenen horen bij de ambulance dus maakt het realistischer.

**Comment by Willem-Dekker** [comment]
Zitten deze er al in zo ja welk nummer?

**Comment by RyanBoersma** [comment]
Armen 138 voor vrouwen

**Comment by walvisgedaan** [comment]
Wordt meegenomen in grote EUP update.
