### ISSUE TITLE
Bodycam voor Ambulance vrouwen

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#653]
# Waar zit het in EUP, interiors of retextures ?
EUP Ambulance, vrouwenkleding

# Link naar issue of coördinaten naar de plek

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Vrouwenkleding heeft geen bodycam.

# Wat is de toegevoegde waarde?
Bodycam mag officieel niet gebruikt worden als bewijs wanneer zij geen bodycam dragen.
Zij willen dit natuurlijk ook graag kunnen.

**Comment by walvisgedaan** [comment]
Wordt meegenomen in grote EUP update.
