### ISSUE TITLE
Garage voor KMAR en Politie op legerbasis

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#654]
**Beschrijf zo duidelijk mogelijk de feature**
Een garage toevoegen aan de legerbasis die alleen toegankelijk is voor KMAR en politie.

**Wat lost deze feature op?**
Zou er al moeten zijn, is er blijkbaar niet actief of iets dergelijks.
Maakt legerbasis makkelijker om te gebruiken voor trainingen en
het wegzetten van voertuigen tijdens bijvoorbeeld een schiettraining op de 
legerbasis wat weer ten goede komt van bijvoorbeeld lag reduceren.

**Comment by Willem-Dekker** [comment]
dus gewoon sloten om de hekken zetten lijkt me?

**Comment by RyanBoersma** [comment]
Ja, issue was meer dat die garage daar wel hoort te zijn maar blijkbaar dus niet actief is of daadwerkelijk gebruikt kan worden?
Verder alleen voor KMAR/Politie is meer zodat niet iedereen daar auto's gaat switchen, als dat makkelijker is met gewoon sloten is dat ook prima wat mij betreft.

**Comment by MisterM02** [comment]
Er is al een normale voertuiggarage op de legerbasis. Geen garage waar dienstvoertuigen gepakt kunnen worden. Gok dat het daar specifiek om gaat @RyanBoersma?

**Comment by Willem-Dekker** [comment]
zit er na restart in.
