### ISSUE TITLE
Fixen vrouwelijke ambulance kleding (laatste kans)

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#655]
# Waar zit het in EUP, interiors of retextures ?
EUP vrouwelijke ambu kleding.

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Ontbreken dingen ten opzichte van mannenkleding en 

# Wat is de toegevoegde waarde?
Gelijkheid

**Comment by walvisgedaan** [comment]
**Wordt meegenomen in grote EUP update.**
