### ISSUE TITLE
Schietbaan voor trainingen KMAR/Politie

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#656]
LAGE PRIORITEIT

**Beschrijf zo duidelijk mogelijk de feature**
Ergens op de map een schietbanan toevoegen voor trainingen.

**Wat lost deze feature op?**
Toepasselijke trainingslocatie voor schiettrainingen overheidsbanen.

**Comment by Willem-Dekker** [comment]
legerbasis?

**Comment by RyanBoersma** [comment]
Klopt voor, is meer een verzoek voor daadwerklijk een schietbaan.  Verder low priority dus meer de instelling "mocht er ooit een goede schietbaan gevonden worden die goed toegepast kan worden, dan graag" .
