### ISSUE TITLE
Gelijktrekken KMAR en Politie SIV qua snelheid en acceleratie

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#657]
**Label van voertuig**
KMAR SIV/Politie SIV

**Spawnnaam van voertuig**
Weet ik helaas niet

**Kenteken van voertuig (wanneer van toepassing)**
NVT

**Omschrijf de bug**
SIV van KMAR is veel trager dan Politie SIV.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Auto's pakken, tegen elkaar laten racen en zien wie wint.

**Normaal gedrag**
Ze zijn identiek qua functioneren behalve hoe ze eruit zijn.

**Impact op de server**
Medium

**Comment by Willem-Dekker** [comment]
zonder spawn naam kunnen we niet heel veel.

**Comment by RyanBoersma** [comment]
Even nagevraagd en spawnnaam voor KMAR is "kmaraudi" en voor politie is "police3".

**Comment by niekschoemaker** [comment]
Done
