### ISSUE TITLE
Verschillende rangen op schouder van kleding KMAR weergeven

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#658]
# Waar zit het in EUP, interiors of retextures ?
Volgens mij retextures anders EUP.

# Link naar issue of coördinaten naar de plek
NVT

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
KMAR heeft geen verschillende rangen op hun schouder net zoals de politie.

# Wat is de toegevoegde waarde?
Medium, Voegt extra uitstraling toe voor KMAR wat een leuke extra toevoeging is
en wel zo eerlijk aangezien de politie het ook heeft.

**Comment by walvisgedaan** [comment]
Wordt meegenomen in grote EUP update.
