### ISSUE TITLE
Voertuigen die nerf nodig zijn

### ISSUE THREAD

**Issue by niekschoemaker** [Tedeapolis/development#659]
Comment hier even met voertuig labels/spawn namen zodat ik deze ff kan checken/nerfen.

**Comment by Bladerdeeg** [comment]
Buckingham SuperVolito  Deze helicopter vliegt elke heli / vliegtuig eruit

**Comment by musician1011** [comment]
Issue was al opgelost maar nog niet gesloten, dus bij deze!
