### ISSUE TITLE
Reparatie van motoren bij de MC 

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#66]
de mogelijkheid om alleen motoren van andere spelers te repareren/tunen op de motorclub . 

wij maken de reclame op twitter dat mensen langs kunnen komen op de MC om daar hun motor te kunnen laten repareren tegen een goede prijs ,
dit locatie gebonden en niet dat wij langs de mensen gaan om hun voertuig ter plaatse te repareren .

**Comment by takermart** [comment]
waarom is deze gesloten ?

**Comment by Willem-Dekker** [comment]
Dit zal niet worden geïmplementeerd ivm het een oneerlijk voordeel geven aan een bepaalde groep door ze deze mogelijkheid te geven. Dit om vragen van andere groepen te vermijden
