### ISSUE TITLE
Aanpassen snelheid kustwacht helikopter

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#660]
**Label van voertuig**
Kustwacht helikopter?

**Spawnnaam van voertuig**
mh60t

**Kenteken van voertuig (wanneer van toepassing)**
NVT

**Omschrijf de bug**
Kunnen amper boten bijhouden, verzoek tot een iets grotere snelheid zodat ze in ieder geval
dichterbij kunnen komen om ze aan te houden of iets dergelijks.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
NVT

**Normaal gedrag**
Helikopter is snel genoeg om boten in te kunnen halen.

**Impact op de server**
Relatief groot omdat kustwacht taken niet goed uitgevoerd kunnen worden.
Vooral nu er ook een suggestie bij staat om boten voordelen te geven mbt transportcapaciteit
moeten deze wel aangepakt kunnen worden.

**Comment by niekschoemaker** [comment]
Is gefixed
