### ISSUE TITLE
F6 menu fixen voor Ambulance

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#663]
**Omschrijf de bug**
Het objecten plaatsen vereist nu ook eerst een ID selecteren.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Ambulance job nemen, items neer proberen te zetten.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Voor het plaatsen van objecten hoeft geen ID geselecteerd te worden.

**Screenshots en/of logbestanden**
/

**Impact op de server**
Medium

**Comment by Willem-Dekker** [comment]
is geen bug maar is al fixed
