### ISSUE TITLE
Mondkapje bij ziekenhuis kledij 

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#666]
# Waar zit het in EUP, interiors of retextures ?
In EUP

# Link naar issue of coördinaten naar de plek
GEEN ISSUE! Enkel een voorbeeld
https://forum.cfx.re/t/release-eup-face-mask-kuwu/2141520

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Nee

# Wat is de toegevoegde waarde?
De ambu vroeg af of het mogelijk was om in de kleren die we dragen in het ziekenhuis (verpleger/verpleegster) een mondmasker toe te voegen dit omdat IRL ze in operatie ruimtes ook mondmaskers dragen voor hygiene en is gewoon een leuke toevoeging anders eventueel ook toevoegen bij ambulance accesoires

**Comment by walvisgedaan** [comment]
Wordt meegenomen in grote EUP update.
