### ISSUE TITLE
Toevoeging Justitie/ Advocaten baan : Juridische documenten / Dwangbevelen rondbrengen.

### ISSUE THREAD

**Issue by Sjenkie-Sjembek** [Tedeapolis/development#667]
Hi!

We zien een hoop verloop bij Jusititie omdat er buiten de zaken om niet veel te doen is voor advocaten zelf. Als er een hoop advocaten zijn dan betekend dat dat er een x aantal zaken zijn waarop advocaten dan springen en een aantal buiten de boot valt.

Nou weet ik van het systeem van de Ambu dat ze medicijnen rond brengen. Is zo iets ook mogelijk voor Justitie? Dat je in dienst dan een soort busje krijgt om dan naar verschillende locaties te rijden om documenten of bevelen af te geven?

Ik had zelf al even gezocht maar ik kwam op iets als dit uit: https://forum.cfx.re/t/esx-gopostal-job/681872.

Wellicht dat we de VAN kunnen ombouwen tot iets met een Ministerie logo?

Ik weet niet of het mogelijk is want ik heb serieus geen verstand van fivem servers maar als ik iets kan betekenen in vertalen of zo?

Thnx voor jullie tijd!

**Comment by Hellie94** [comment]
Hoe staat het hiermee?

**Comment by Mikajac** [comment]
Kunnen wij een update hierover krijgen? De issue staat inmiddels al geruim een jaar open, is al 8 maanden geleden geaccepteerd maar sindsdien hebben wij helaas niks meer vernomen, noch de job.

**Comment by Chang-nl** [comment]
Generieke plugin is in de maak waar deze job aan toegevoegd word. Graag zou ik het volgende willen weten:
Waar moet de startlocatie/inkloklocatie komen?
Wat moet de outfit zijn voor de werknemers?

**Comment by Mikajac** [comment]
> Generieke plugin is in de maak waar deze job aan toegevoegd word. 
Graag zou ik het volgende willen weten: Waar moet de startlocatie/inkloklocatie komen? 
Wat moet de outfit zijn voor de werknemers?

Voor de startlocatie zouden wij het liefste een systeem zoals de ambulance heeft met medicijnen rondbrengen. Hierbij moeten zij uit de opslag medicijnen halen (voor ons dus "Juridisch document") om vervolgens hun ambulance te pakken (voor ons dus onze Volvo XC90 (overige voertuigen graag blacklisten)) en starten zij de ronde door op (ik geloof) DEL te drukken.
Onze opslag hadden wij graag op X: -554.27 Y: -182.83 Z: 38.22 H: 15.43 (deze coords komen uit de main server en zijn nog niet gecorrigeerd met ergens die 1 bij optellen of aftrekken). 



Kleding ga ik even verder overleggen met onze mensjes, hier kom ik zsm op terug (inclusief template).

**Comment by Chang-nl** [comment]
Ik was er nog een vergeten. Er was namelijk ooit een juridisch voertuig gemaakt dacht ik. Wat was de spawnnaam van dat voertuig?

**Comment by Mikajac** [comment]
> Ik was er nog een vergeten. Er was namelijk ooit een juridisch voertuig gemaakt dacht ik. Wat was de spawnnaam van dat voertuig?

mvolvo

**Comment by LM-666** [comment]
@Chang-nl hey. Ik vroeg me af of er toevallig al iets meer duidelijk was? Of was er nog extra informatie nodig voor de cirkels?

**Comment by Chang-nl** [comment]
Hey @LM-666, sorry voor het ongemak betreffende de plugin die aangevraagd is. Momenteel is het heel erg druk en doen wij heel erg ons best om Z.S.M. achterstallige projecten weg te werken. Ik kan geen helaas geen ETA geven, maar we zullen ons best doen.

**Comment by LM-666** [comment]
Thanks! Als er nog iets nodig help ik graag, daarvoor kun je me eventueel DM'en in Discord: Luci#3010.

**Comment by Chang-nl** [comment]
Hey @Luci-fer12, Ik zou graag willen weten welke outfit voor mannen en voor vrouwen jullie graag terug willen zien!

**Comment by Luci-fer12** [comment]
Is er een mogelijkheid dat het in eigen kledij word gedaan? De verplichte 'dresscode' binnen Justitie is momenteel al formeel, en ik kan niet 1,2,3 op kleren komen. 

Mocht het echt noodzakelijk zijn hoor ik het graag, dan ga ik het even opzoeken.

**Comment by Luci-fer12** [comment]
Kledingstukken
skin_male = {
tshirt_1 = 31,
tshirt_2 = 0,
torso_1 = 31,
torso_2 = 0,
sticker = 0,
sticker_2 = 0,
arms = 1,
arms_2 = 0,
pants_1 = 28,
pants_2 = 0,
shoes_1 = 20,
shoes_2 = 7,
ears_1 = -1,
sex = 0,
chain_1 = 0,
chain_2 = 0,
glasses_1 = 0,
glasses_2 = 0,
}

Dit is een prima outfitje, zwart 2 delig pak. Indien het eventueel toch nodig is.

**Comment by Chang-nl** [comment]
Hey @Luci-fer12, als je even contact met mij opzoekt via discord kan ik je tijdelijk toegang geven zodat je deze kan samenstellen! Chang#0001

**Comment by Chang-nl** [comment]
Hey @Sjenkie-Sjembek, na de herstart zal de baan erin zitten. De baan is voor nu even papieren ophalen dit zal nog worden aangepast maar momenteel is dat geen prioriteit. Basisfunctionaliteit werkt in ieder geval. Het startpunt zit op onderstaande coordinaten. Hier kun je je omkleden en dan kun je buiten naast de garage een voertuig pakken en beginnen in de paarse cirkel.

> Onze opslag hadden wij graag op X: -554.27 Y: -182.83 Z: 38.22 H: 15.43 (deze coords komen uit de main server en zijn nog niet gecorrigeerd met ergens die 1 bij optellen of aftrekken).

mochten er nog vragen zijn moet je deze zeker stellen!
