### ISSUE TITLE
[Server Supporter Suggestie] De cooldown van /testrespawnvehicle verlagen.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#669]
**Beschrijf zo duidelijk mogelijk de feature**
De cooldown van /testrespawnvehicle (mij is verteld dat deze 10 min. is) verlagen naar 300 seconde. Het komt steeds vaker voor dat mensen problemen hebben met hun auto (auto gaat niet open van het slot of iets) waardoor ze /testrespawnvehicle moeten gebruiken. Als dit binnen 10 minuten 2x voorkomt ben je in principe al "de lul" omdat je dan 20 minuten moet wachten. (1e x in 10 minuten en na die 10 minuten nog een keer).

De suggestie van Ian G. (26 upvotes)
De cooldown van /testrespawnvehicle verlagen naar 300 seconden, bij de meeste mensen doordat ze hun auto vol met zakjes steeken doen hun voertuig raar en moeten ze wel vaker /testrespawnvehicle doen en als je dan op die cooldown zit moet je 10 minuten wachten en dat vind ik best lang.

**Wat lost deze feature op?**
Minder reports betreft auto's die raar doen omdat mensen vaker /testrespawnvehicle kunnen doen in plaats van 10 minuten moeten wachten en dus maar een report aanmaken zodat een stafflid het kan doen voor ze.

**Comment by niekschoemaker** [comment]
Is gefixed
