### ISSUE TITLE
Voertuigen uit voertuig-menu bij ANWB verwijderen 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#670]
**Beschrijf zo duidelijk mogelijk de feature**
Ik wil dat de volgende voertuigen weggaan uit het menu bij de ANWB zodat niemand ze meer kan pakken.

**Het gaat om de volgende voertuigen:**
- ANWB test takel
- Leen fiets
- SlamVan

**Comment by niekschoemaker** [comment]
Snap niet helemaal waarom die er uberhaupt instonden maar ze zijn eruit gehaald nu.
