### ISSUE TITLE
/docu bereik is te ver en pakt iedereen in ruime omgeving

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#671]
**Omschrijf de bug**
 als je /docu doet en je klikt op toon krijg je iedereen in een range van minimaal 10 to 20 meter en dan alle steamnamen

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
probeer het maar op BP /docu en dan het bereik wat je hebt en de namen die je ziet

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
het zou handiger zijn als dit bereik een stuk kleiner zou zijn

**Screenshots en/of logbestanden**

**Impact op de server**
mensen kunnen op deze manier achter steamnamen komen van andere spelers in de buurt

**Comment by niekschoemaker** [comment]
Is gefixed
