### ISSUE TITLE
Sleepwagen KMAR

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#672]
**Beschrijf zo duidelijk mogelijk de feature**
Graag zouden wij de sleepwagen toegevoegd willen hebben bij de KMAR toegankelijk voor elke rang.
De spawn naam van het voertuig: flatbedp

**Wat lost deze feature op?**
Zodat de KMAR ook die taken op zich kan nemen.

**Comment by niekschoemaker** [comment]
Done
