### ISSUE TITLE
Schietmeldingen Luitenant-Generaal

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#673]
**Beschrijf zo duidelijk mogelijk de feature**
Schietmeldingen voor KMar rang Luitenant-Generaal aanzetten

**Wat lost deze feature op?**
Dat ik zowel DSI diensten kan draaien en mijn werk als KMar baas kan doen.

**Comment by niekschoemaker** [comment]
Is gefixed
