### ISSUE TITLE
Bug bij gebruik van /looc

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#674]
**Omschrijf de bug**
Op het moment dat je /looc gebruikt, komt er altijd "OC" te staan voor het bericht dat je typt. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Iets typen in /looc. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaliter zou enkel het bericht zonder "oc" ervoor moeten verschijnen. 

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/71287080/125858461-2d394f84-abb4-43fa-adf5-8dc05520fc9e.png)

**Impact op de server**
Zeer laag

**Comment by niekschoemaker** [comment]
Is gefixed
