### ISSUE TITLE
Dupe glitch drugs stack

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#675]
**Omschrijf de bug**
Tegenwoordig kan je maar een stack van 500 drugs hebben. 

Als er nu 480 drugs liggen en je hebt er 21 op zak. Leg je 21 op de stack en dan word de stack 500 maar houd je de 21 nog op zak. Hierdoor dupe je het

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een stack van 480 of hoger creëren en dan tot 501+ vullen 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je verliest de drugs uit je inventory

**Screenshots en/of logbestanden**
https://streamable.com/u9dzq0   (Clip van hoe het precies in elkaar zit)

**Impact op de server**
Enorm groot. je kan hierdoor niet normaal veel dupe

**Comment by niekschoemaker** [comment]
Is gefixed
