### ISSUE TITLE
2de hands laad niet in

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#677]
**Omschrijf de bug**
op de 2de hands zijn vaak als je wat langer in de stad bent dat auto's niet meer op hun plek komen te staan en er dus veel lege vakken zijn terwijl andere die auto's wel kunnen zien!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
tijdje in de stad zijn en dan eens langs de 2de hands gaan

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
normaal zouden alle auto's gewoon inspawnen

**Screenshots en/of logbestanden**

**Impact op de server**
mensen kunnen auto's niet zien waardoor ze ze dan ook niet kunnen kopen of de auto vinden die ze zoeken

**Comment by niekschoemaker** [comment]
Fixed <3
