### ISSUE TITLE
Packard 1948 kleuren worden niet opgeslagen!

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#678]
**Omschrijf de bug**
Als je in de modshop de Packard 1948 een nieuwe kleur geeft en hem dan weer in je garage zet, dan komt ie er weer uit met de basic kleur en moet je terug naar de modshop in het menu gaan om de kleur te krijgen die je erop hebt gezet!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
auto pakken kleuren en in je garage zetten

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
kleur zou opgeslagen moeten worden

**Screenshots en/of logbestanden**

**Impact op de server**
Niets bijzonders, maar is wel lichtelijk vervelend

**Comment by niekschoemaker** [comment]
Gaat om de pstan48

**Comment by musician1011** [comment]
Probleem gevonden! Is na de restart opgelost. :)
