### ISSUE TITLE
/swap_phonenummer recherche uitdienst

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#680]
**Beschrijf zo duidelijk mogelijk de feature**
Dat Recherche uitdienst ook /swap_phonenummer kunnen doen. Op dit moment kunnen ze dit alleen indienst.

**Wat lost deze feature op?**
Dit zorgt ervoor dat Recherche beter hun werk kan doen en zorgt ervoor dat ze niet onnodig indienst hoeven tegaan

**Comment by niekschoemaker** [comment]
Zit erin
