### ISSUE TITLE
range rover vogue texture bug 

### ISSUE THREAD

**Issue by Bladerdeeg** [Tedeapolis/development#682]
Label van voertuig: **range rover vogue**

Spawnnaam van voertuig: **VOGUE14**  

Omschrijf de bug: **Voorlampen geven geen licht, inplaats van dat worden er 2 witte boxen voor je auto vast geplakt kijk video: https://youtu.be/XxcCQbqUG_k**   

Hoe kunnen wij de bug reproduceren: **Voertuig inspawnen en overdag gaan rijden over evt in de nacht zodat je kan zien dat hij geen licht geeft.**

Normaal gedrag: **Dat er licht uit komt en dat de geen witte boxen zijn.** 

Screenshots en/of logbestanden: **https://prnt.sc/1f6turt**

Impact op de server: **Vrijwel geen.   Is wel zonde van de mooie auto**

**Comment by musician1011** [comment]
Probleem zal opgelost zijn bij de volgende restart!
