### ISSUE TITLE
carbon heli kofferbak.

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#684]
**SuperVolito Carbon**

**/car supervolito2**

**PROBLEEM : De kofferbak van de supervolito heeft een inhoud van 125 Kg terwijl zijn iets goedkopere variant, wat gewoon dezelfde is in het niet carbon ( /car supervolito) wel 160 Kg heeft
OPLOSSING : graag beide op 160Kg zetten aangezien ze hetzelfde zijn.**

125Kg van de supervolito2
https://cdn.discordapp.com/attachments/732701522634473545/868476069035003914/unknown.png

160Kg van de supervolito
https://cdn.discordapp.com/attachments/732701522634473545/868476152061231134/unknown.png

Impact op de server is gezeik in tickets.

**Comment by niekschoemaker** [comment]
Dit was al gefixed
