### ISSUE TITLE
extra modshop circle voor boten in het water. 

### ISSUE THREAD

**Issue by JeroenKla** [Tedeapolis/development#686]
**Beschrijf zo duidelijk mogelijk de feature**
een tune shop in het water voor de boten te kunnen tunen. Nu moet de anwb deze op de truck laden om hem dan te kunnen tunen in de modshop

**Wat lost deze feature op?**
dat de anwb onnodig meldingen moet rijden om een boot te gaan ophalen om deze te gaan tunen.

**Comment by niekschoemaker** [comment]
Done
