### ISSUE TITLE
Meer snel verkoop locaties

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#687]
**Beschrijf zo duidelijk mogelijk de feature**
Aan de hand van vorige staff overleg is het volgende besproken: 

Hoor van +- 34 man (#suggesties) dat die zakjes wel omhoog mogen bij snel verkoop, locaties zijn binnen 10 minuten al weer weg. ipv 500 zakjes het aantal verhogen naar 1500-2500? [Morgan]

Het antwoord hierop was: KNIP. Ook meer locaties. Morgan maakt hier issues voor aan. 

Dus bij deze: De github issue voor meer snelverkoop locaties.

**Wat lost deze feature op?**
Minder gekloot rond snelverkopen, minder geschiet en chaos omdat er meer verkoop locaties zijn.

**Comment by Willem-Dekker** [comment]
Gooi dit in stafoverleg denk ik maar kunnen we het daar overleggen.
