### ISSUE TITLE
Snel verkoop prijzen van drugs omhoog

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#688]
**Beschrijf zo duidelijk mogelijk de feature**
Aan de hand van vorig staff overleg was mijn agenda punt betreft het verhogen van snel verkoop prijzen (zakjes) met ~50 euro. Dit was goed en bij deze dus de github issue daarvoor.

Antwoord op het puntje vanuit de notule is: Prima! Github issue voor aanmaken. 

**Wat lost deze feature op?**
Iets meer compensatie vanwege de locaties die nu van plekken wisselen en aangezien deze binnen 10 minuten weg zijn een kleine extra.

**Comment by niekschoemaker** [comment]
Bij vorig staff overleg was het weer precies het omgekeerde. Door loodsen atm verdient het eigenlijk te veel, heb bankovervallen etc wel iets omhoog gezet nu.
