### ISSUE TITLE
discord chat/voice kanaal voor bendes

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#69]
de mc wil graag een eigen Discord Porto voor het geval de in game porto niet lekker werkt wegens drukte of storing .. 

daarnaast aangezien ik nu het aanspreek punt ben van de criminelen , zou ik graag een discord chat/voice kanaal willen in de discord tda waar alle bazen in zitten van elke criminele organisatie , dan kunnen alle vragen / gesprekken daar plaats vinden en kan de hoge raad dit ook in de gaten houden als ze te ver gaan .

**Comment by Willem-Dekker** [comment]
kanalen zijn aangemaakt
