### ISSUE TITLE
Cardealer cirkel in paleto bay 

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#690]
**Omschrijf de bug**
Er staat een cardealer cirkel en quicksell in paleto bay op 905 bij de garage

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
 naar postcode 905 gaan (garage in paleto bay)

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
denk niet dat die hier moet zijn

**Screenshots en/of logbestanden**
https://prnt.sc/1fdelzv
https://prnt.sc/1fdf6d1
**Impact op de server**
cirkel die er niet hoort te zijn

**Comment by niekschoemaker** [comment]
Ja klopt idd. Heb er nu ff wat werk voertuigen toegevoegd, die cirkel is specifiek voor vrachtwagens dus vandaar maar weet niet zo goed welke prijzen ik erop moet zetten dus vandaar dat hij ff leeg was.
