### ISSUE TITLE
Vuilnisman job

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#691]
**Omschrijf de bug**
Als je vuilnis opraapt en vervolgens weer je truck in wilt geeft hij aan dat het niet jou truck is, als je dan nogmaals in ene uit stapt doet die eht weer normaal

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
een vuilnis job doen en dan als je alle vuilniszakken opgepakt haalt en weer je truck in gaat dan zou er links boven in komen dat het neit jou voertuig is.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je instant een nieuw locatie krijgen

**Screenshots en/of logbestanden**
https://medal.tv/clips/59967895/d1337YJEbVe9

**Impact op de server**
Het is gewoon vervelend, dat je nu dubbel moet doen.

**Comment by niekschoemaker** [comment]
Is gefixed!
