### ISSUE TITLE
BPM in deathscreen

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#692]
**Omschrijf de bug**
De BPM in je deathscreen blijft staan op hetzelfde als toen je dood ging en dit veroorzaakt verwarring bij spelers of ze nog gerevived kunnen worden

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Doodgaan en BPM: {bpm} in de gaten houden.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De BPM zou naar beneden moeten gaan net zoals in de print van medSystem (bij ambu en politie)

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/61888104/127754565-50c9f270-bdd0-4c39-9337-aa6543419ef2.png)
De BPM is constant 23 gebleven (bloed functioneert wel)

**Impact op de server**
Spelers kunnen zo een verkeerd beeld krijgen in welke medische staat ze zijn.

**Comment by niekschoemaker** [comment]
Deze issue zou na volgende restart gefixed moeten zijn, zo niet even issue reopenen aub

**Comment by Cryonite** [comment]
De BPM tript hem, schommelt tussen de 100 en 130 bpm (zie video)
De controleer hartslag voor ambulanciers sis boven de 100 en gaat richting de 250 BPM, dit gebeurt niet als de persoon levend is.

# video
https://youtu.be/X_qcOn0J9xg

# screenshot
![image](https://user-images.githubusercontent.com/61888104/127913932-ce47432d-b434-42fe-b79a-e920d552bfc5.png)
![image](https://user-images.githubusercontent.com/61888104/127914076-f24cfe46-5c31-429d-aac4-d27476ab899c.png)

**Comment by Cryonite** [comment]
Ik kan zelf helaas de issue niet re-openen

**Comment by Cryonite** [comment]
Het zou nu goed moeten werken, bedankt voor het fixen!
