### ISSUE TITLE
Hersenloze laten syncen

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#693]
**Beschrijf zo duidelijk mogelijk de feature**

De verkoop aan hersenloze laten syncen dus een hersenloze voor iedereen waaraan dan verkocht kan worden voor de andere dan dikke pech

**Wat lost deze feature op?**

Dat iedereen een "eigen" hersenloze heeft waaraan hij/zij kan verkopen!

**Comment by niekschoemaker** [comment]
Deze feature is getest, maar zorgt voor crashes, hierom weer teruggedraaid.
