### ISSUE TITLE
Slot op een deur bij het ANWB lokaal.

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#694]
**Beschrijf zo duidelijk mogelijk de feature**
Bij de ANWB is een klaslokaal met een deur maar iedereen heeft daar nu toegang tot omdat er nog geen slot opzit dus random mensen lopen daar naar binnen toe als er een inwerking/cursus gaande is. De deur valt te vinden op de coords wat de screenshot aangeeft. Dus het zal fijn zijn als er een slot opkomt die alleen ANWB'ers kunnen openen. 

**Wat lost deze feature op?**
Dat mensen die niet ANWB zijn deze deur niet kunnen openen. 
![Knipsel](https://user-images.githubusercontent.com/68514420/128059445-ac0bee49-728f-4d2b-bac9-12181e9254c1.PNG)

**Comment by Willem-Dekker** [comment]
zit er na restart in
