### ISSUE TITLE
Instant tot stilstand komen met ALT+F4

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#695]
**Omschrijf de bug**
Via GTA is het zo dat wanneer je op ALT+F4 drukt je de vraag krijgt of je echt wilt afsluiten. Tot door een pop-up menu.
Nu is het zo dat je, wanneer je ALT+F4 indrukt, en dus dit scherm krijgt, je direct tot stilstand komt.
Zo is het dus dat je met een snelheid van 300 km/h binnen 1 seconde tot stilstand kan komen door simpelweg ALT+F4 in te drukken.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak een snelle auto en begin met rijden. Wanneer je op een redelijke snelheid zit druk je op ALT+F4. Je komt in het pop-up menu en geeft aan dat je niet wilt afsluiten. Je staat nu stil.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je niet tot stilstand moeten komen.

**Screenshots en/of logbestanden**
Mocht het nodig zijn kan ik een video uploaden.

**Impact op de server**
Mensen kunnen dit hevig abusen tijdens achtervolgingen o.i.d.

**Comment by niekschoemaker** [comment]
Is helaas niet te fixen zonder ergere problemen te veroorzaken
