### ISSUE TITLE
tweedehands dealer veranderingen

### ISSUE THREAD

**Issue by Taker1987** [Tedeapolis/development#696]
Tijdens staff overleg besproken 

Garage naar beneden kan wel, even github issue aanmaken, zelfde voor aanbied punt.
Eventueel een ymap met die politie/blokkenpark paaltjes er neer zetten zodat mensen moeten afremmen, of volledig afzetten en loop gebied van maken.

geen voertuigen meer die rijden op de tweedehands locatie .. voertuigen zet je weg in de cirkel beneden bij de tweedehands dealer .. bij de tweedehands dealer zelf komen paaltjes of iets dergelijks zodat daar geen voertuigen meer kunnen rijden .

**Comment by musician1011** [comment]
Is aangepast me dunkt. :)
