### ISSUE TITLE
Voertuig takelen script crash wanneer item in kofferbak

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#697]
**Omschrijf de bug**
Op het moment je een voertuig via E op een sleepwagen probeert te zetten met een item in de kofferbak, wordt de melding weergeven dat er iets in de kofferbak zit. Echter is het daarna niet meer mogelijk om de E spier te gebruiken voor de ramp en voor het takelen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Pak een sleepwagen en pak een voertuig. Stop nu bijvoorbeeld een jerrycan in de kofferbak en probeer het voertuig op de sleepwagen te rijden en vast te zetten. Het zal nu de melding weergeven dat er iets in de kofferbak zit. Je kunt vervolgens de ramp nu niet meer inschuiven en het voertuig niet meer op de sleepwagen vastzetten.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Nadat de melding weergeven is hoor je de ramp gewoon nog te kunnen bedienen en hoor je het voertuig ook normaal vast te kunnen zetten.

**Screenshots en/of logbestanden**
[CitizenFX_log_2021-08-10T172255.log](https://github.com/Tedeapolis/development/files/6963486/CitizenFX_log_2021-08-10T172255.log)

**Impact op de server**
Onbekend, voor nu lijkt dit op een client side issue

**Comment by niekschoemaker** [comment]
Is bij volgende restart gefixed
