### ISSUE TITLE
Meldkamer portofoon valt elke keer weg wanneer iemand praat

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#698]
**Omschrijf de bug**
Wanneer iemand aan het praten is, gebeurd het enorm vaak dat die persoon stil valt. Wat mij daarbij opvalt is dat dit 9/10 keer gebeurd als deze lijst: 

![image](https://user-images.githubusercontent.com/47216413/129089195-7c6a1b9d-01f2-4030-8ff0-704a9c5e0160.png)

updated van onderen. Dus wanneer iemand de porto inkomt / aandoet, valt de persoon die aan het praten is weg, tenzij een ander persoon gaat praten. Dan hoor je m weer.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Is lastig, ik denk zelf dat het goed is om te kijken tussen de code waar wordt bepaald dat de persoon die praat onderaan komt te staan. Het lijkt erop dat het sindsdien gebeurd.
Wat verder te valt te proberen is checken of het gebeurd wanneer iemand de porto inkomt, of wanneer je een andere voicebox inloopt.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Stemmen vallen niet weg en porto werkt volledig

**Screenshots en/of logbestanden**
nvt

**Impact op de server**
Communicatie tussen Kmar/Politie/DSI/KLU/HRB/BSB

**Comment by niekschoemaker** [comment]
Blijft de naam wel geel als je iemand niet meer hoort of valt dat ook weg?

**Comment by AdventurePandah** [comment]
> Blijft de naam wel geel als je iemand niet meer hoort of valt dat ook weg?

De naam blijft wel geel

**Comment by niekschoemaker** [comment]
> > Blijft de naam wel geel als je iemand niet meer hoort of valt dat ook weg?
> 
> De naam blijft wel geel

Yes, ik heb nu hee lwat dingen aangepast, want is al even poosje geleden,

Maar is dit nu nog steeds een probleem, want als het goed is is dit met m'n laatste update gefixed.

**Comment by niekschoemaker** [comment]
Is gefixed
