### ISSUE TITLE
/repareer verhogen naar 5

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#699]
**Beschrijf zo duidelijk mogelijk de feature**
Bij 0 tot 3 ANWB'ers kan iedereen nu nog in de stad /repareer doen maar wij komen telkens mensen tekort bij meldingen rijden. Dus het is voor nu even beter om /repareer naar 5 verhogen, zodat meldingen met meer mensen gereden kunnen worden met laag aantal ANWB'ers online.
**Wat lost deze feature op?**
Dat er meer meldingen gereden kunnen worden met laag aantal ANWB'ers in-dienst, en zo kunnen mensen bij een desbetreffende mechanic shop /repareer doen tot aan 5 ANWB'ers in-dienst. Dus bij de 6e in-dienst moeten ze wel naar ANWB HB.

**Comment by niekschoemaker** [comment]
Done
