### ISSUE TITLE
Kunnen deze dingen gemaakt worden bij de anwb?

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#70]
- [x] De cooldown van /repareer zou graag lager mogen. Bijvoorbeeld in plaats van 30 minuten naar 15 minuten. 
- [x]  Het uitzetten van NPC jobs omdat ze niet werken. Ze mogen niet gebruikt worden. !!
- [x] Een gele cirkel toevoegen bij de garage vlakbij de ANWB. 
- [x] Jerrycans doen het op dit moment niet. 
- [x] /Onduty mechanic werkt niet als je in dienst bent.
- [x] Rank 5 ANWB: Staat nog op experimente. Moet veranderd worden naar: Autotechnicus.
- [x] Mensen gaan dood als ze het andere pakje van een man/vrouw proberen aan te trekken /eup .

hopelijk heb ik de af vink vakjes goedgemaakt :D wist niet meer hoe het moest

**Comment by Willem-Dekker** [comment]
heb je vinkjes gefixed

**Comment by Willem-Dekker** [comment]
| Mensen gaan dood als ze het andere pakje van een man/vrouw proberen aan te trekken /eup .

ik zie geen probleemen

**Comment by Willem-Dekker** [comment]
| /Onduty mechanic werkt niet als je in dienst bent.
werkt volgens mij alleen voor baas

**Comment by DeStefanoKiller** [comment]
> | /Onduty mechanic werkt niet als je in dienst bent.
> werkt volgens mij alleen voor baas

Dit krijg ik tezien met /onduty mechanic  terwijl in-dienst 
![unknown](https://user-images.githubusercontent.com/68514420/89585020-68bc5880-d83d-11ea-9fc5-e05ab58565c6.png)
