### ISSUE TITLE
Toevoegen KMAR aan de voertuigopslag van de Politie

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#700]
**Beschrijf zo duidelijk mogelijk de feature**
Sinds kort is er een sleepwagen toegevoegd voor de kmar, echter is het zo dat deze niet in de voertuigopslag zelf kunnen.
In overleg met Sander daarom de aanvraag om kmar toegang te geven tot de voertuigopslag zodat deze gedeeld wordt met de Politie.

**Wat lost deze feature op?**
De kmar kan door deze feature daadwerkelijk zelf voertuigen in beslag nemen, en zijn daardoor niet afhankelijk van de politie.

**Comment by wolliebolly** [comment]
Is er een idee wanneer dit klaar is?

**Comment by musician1011** [comment]
Is toegevoegd, KMAR kan nu voertuigen in de politieopslag zetten maar mag deze er niet uit halen.
