### ISSUE TITLE
Nieuwe lijst boten specificaties

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#702]
**Beschrijf zo duidelijk mogelijk de feature**
Lijst met nieuwe boten specificaties.
Update een de kofferbakken en wellicht tospeed indien mogelijk

**Wat lost deze feature op?**
Momenteel staan alle kofferbakken gelijk en kan er dus evenveel kg in een Jetski als in een langere boot.

Dit is besproken tijdens het staffoverleg van eind Mei, ook een Github van aangemaakt, maar de update is dus niet helemaal lekker doorgekomen, gezien het nog niet in de server zit x)

In de onderstaande link staan de nieuwe voorgestelde specificaties van de boot

Ook hebben wij een drietal nieuwe voertuigsuggesties toegevoegd voor meer variatie op het water.
(we hadden tijd over, is dus niet prioriteit, maar indien mogelijk zien ze er wel leuk uit als toevoeging :P )

Kusjes,
Marvin, Brockl
https://user-images.githubusercontent.com/71552704/110539172-30f3f700-8125-11eb-9dcc-4396abb30726.png

**Comment by niekschoemaker** [comment]
Heb het doorgevoerd nu. Zit er na restart in.
