### ISSUE TITLE
Disable ELS keywanneer UI venster geopend is

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#703]
**Beschrijf zo duidelijk mogelijk de feature**
Disable de ELS hotkeys wanneer een UI text menu iets geopend is. Wanneer iemand bijvoorbeeld een SMS gaat typen, reageert de ELS erop waardoor dit soms helemaal bugged.

**Wat lost deze feature op?**
Dit zorgt ervoor dat bijv bij politie niet random opeens sirenes blijven vasthangen en dergelijke. Daarnaast ga je sws geen ELS bedienen vanuit je sms bericht.

**Comment by niekschoemaker** [comment]
Goeie, ik zal even kijken of de UpdateOnscreenKeyboard native hiervoor te gebruiken is.

**Comment by niekschoemaker** [comment]
Zit erin en werkt
