### ISSUE TITLE
Effect op dronken voeren

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#704]
**Beschrijf zo duidelijk mogelijk de feature**
Is het mogelijk om iets erin te zetten waardoor dronken voeren nog een effect heeft op de roleplay, dat als ze meer alcohol op hebben langer dronken blijven of dat er een gedeelte van je health weggaat of iets dergelijke? Merk dat criminele dit namelijk nog steeds veel gebruiken.

**Wat lost deze feature op?**
Een deel roleplay dat als ze niets meer mogen herinneren.

**Comment by Willem-Dekker** [comment]
is er al op bijna alle items met alcohol zit al een honger effect en verschillende tijden van dronken zijn

**Comment by DevvTDA** [comment]
> is er al op bijna alle items met alcohol zit al een honger effect en verschillende tijden van dronken zijn

Dan kan die van mij part gesloten worden dus dan is kans op redelijk goed doodgaan ernog tenzij ze eten hebben :)

**Comment by Willem-Dekker** [comment]
yep neem maar eens een paar shots vodka
