### ISSUE TITLE
Kofferbak limiet verhogen Kamacho

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#705]
**Beschrijf zo duidelijk mogelijk de feature**
Kofferbak limiet verhogen van de Kamacho

**Wat lost deze feature op?**
Momenteel heeft deze een kofferbak limiet van 75kg.
Auto's als de trophytruck hebben 100kg terwijl de kofferbak ruimte minimaal is.
![image](https://user-images.githubusercontent.com/71552704/129447385-c5c3880a-dc0f-4a94-9c87-8498b9239eef.png)
![image](https://user-images.githubusercontent.com/71552704/129447390-6a5d0419-f9dd-4e7f-8b79-ed82238a7f9c.png)
Bovenste is kamacho (huidig 75kg)
Onderste is trophytruck (huidig 100kg)

**SUGGESTIE UIT SUPPORTER SUGGESTIES**

**Comment by niekschoemaker** [comment]
Heb hem verhoogd naar 115kg
