### ISSUE TITLE
ATM emote tijdens het pinnen

### ISSUE THREAD

**Issue by TDAMarvinW** [Tedeapolis/development#706]
**Beschrijf zo duidelijk mogelijk de feature**
Wanneer je pint er een emote (/e atm) aan vastbinden

**Wat lost deze feature op?**
Is een stuk realistischer en niet binnen 2 seconde geld uit de muur te trekken als een kroket bij de FEBO

**SUGGESTIE SERVER SUPPORTER**
![image](https://user-images.githubusercontent.com/71552704/129450181-467c0d17-e1c3-4ba2-8262-194ed65e051e.png)

**Comment by Chang-nl** [comment]
Na restart zit dit in de stad!
