### ISSUE TITLE
Portofoon fixen op kleding Marechaussee

### ISSUE THREAD

**Issue by wolliebolly** [Tedeapolis/development#708]
# Waar zit het in EUP, interiors of retextures ?

EUP Marechaussee

# Link naar issue of coördinaten naar de plek

EUP menu

# Zitten er fouten in? zo ja graag beschrijven en een screenshots

Als je de kleding aan doet van o.a. de Marechaussee dan verschijnt er een portofoon, maar zodra je er een steekvest overheen doet dan verdwijnt deze portofoon. Dit zorgt er dus voor dat als je met de (nep-porto) animatie praat dat je in de lucht aan het praten bent.

# Wat is de toegevoegde waarde?

Realistischere kleding en animatie
![2021-08-15 07_59_27-FiveM - Tedeapolis (Test Server)](https://user-images.githubusercontent.com/88959015/129468772-c82a8536-645b-4eca-af2f-500e79fbaa96.png)
![2021-08-15 07_58_52-Window](https://user-images.githubusercontent.com/88959015/129468774-094e7498-22e7-4c86-b118-4a68c8c538dc.png)

**Comment by walvisgedaan** [comment]
Ik ga hier naar kijken

**Comment by walvisgedaan** [comment]
Ik heb even gekeken en de model die jij hierboven laat zien is gebugged, heb je eventueel een ander custom model (mag van internet af komen). Momenteel zit er namelijk in onze EUP geen geschikte model

**Comment by wolliebolly** [comment]
> Ik heb even gekeken en de model die jij hierboven laat zien is gebugged, heb je eventueel een ander custom model (mag van internet af komen). Momenteel zit er namelijk in onze EUP geen geschikte model

Ik ben niet zo goed in het zoeken van models en dergelijke. Dus geen idee waar ik moet beginnen. Portofoon die er nu in zit is volgens mij bugged met het schermpje (dat trilt soort van), maar voor de rest is die wel goed dacht ik. Het lijkt mij sowieso beter dan zonder portofoon, maar die beslissing laat ik aan jullie over.

**Comment by walvisgedaan** [comment]
De model die er nu in zit (met het bewegende schermpje) komt er niet in aangezien dit dusdanig irriterend is dat het het realisme verstoort

**Comment by wolliebolly** [comment]
https://www.lcpdfr.com/downloads/gta5mods/character/27944-eup-axon-body-cam-shoulder-mic-beta/

Heb je hier iets aan?

**Comment by walvisgedaan** [comment]
Ik ga even kijken

**Comment by walvisgedaan** [comment]
Vandaag of morgen zit het in de eup.
