### ISSUE TITLE
Vliegtuigen Spawn Sandy Shores

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#709]
**Omschrijf de bug**
Momenteel als je een Jet pakt op Sandy Shores komt deze vast te zitten onder de hangar 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door een jet te pakken bij de groene cirkel in Sandy Shores

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zou die een stukje meer naar voren moeten spawnen zodat je niet vast komt te zitten

**Screenshots en/of logbestanden**
https://gyazo.com/3e1f207d4cd8aa7927e5fd560133f745

**Impact op de server**
Telkens een kapotte Jet als je hem hier uit de hangar pakt waar door je weer anwb moet bellen en het weer geld kost

**Comment by niekschoemaker** [comment]
Gefixed
