### ISSUE TITLE
Melding bij offline geldoverboeking

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#710]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel bestaat de feature om via voor- en achternaam geld over te boeken naar een speler die offline is.
Het is echter onduidelijk dat je geld hebt ontvangen op het moment dat je online komt gezien er geen melding verschijnt.
Het idee is dus om een melding toe te voegen, net zoals je dit hebt bij de tweedehands, dat je geld hebt ontvangen wanneer je offline geld hebt ontvangen.

**Wat lost deze feature op?**
Het lost niet echt iets op, maar is meer een toevoeging waardoor duidelijk is dat je offline geld hebt ontvangen.

**Comment by niekschoemaker** [comment]
Heb ik toegevoegd
