### ISSUE TITLE
Aanpassing ANWB sollicitatie vragen.

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#711]
**Nieuwe sollicitatie vragen voor ANWB:** 

Ingame naam * (Blijft het zelfde)

Ingame 06 nummer * (Blijft het zelfde)

E-mail * E-mailadres bevestigen (Blijft het zelfde)

Discord Naam + (#0000) * (Blijft het zelfde)

Steam naam * (Blijft het zelfde)

Je echte leeftijd * (Blijft het zelfde)

Waarom solliciteer je specifiek voor de ANWB? * (Blijft het zelfde)

Noem 3 goede eigenschappen van jezelf * (Blijft het zelfde)

Noem 3 verbeterpunten voor jezelf *

Op welke manier hoop jij een waardevolle toevoeging te zijn voor de ANWB? *

Hoe presteer jij onder tijdsdruk? * (Blijft het zelfde)

Wat is jouw ervaring met RolePlay? (Blijft het zelfde)

Heb je al eerdere ervaringen met het ANWB beroep? * (Blijft het zelfde)

Wat wil jij bereiken bij de ANWB? 

Ben jij minstens 6 uur per week beschikbaar?
Ja / Nee

Op welk dagdeel ben je meestal online? * (Blijft het zelfde)

Heb je de afgelopen 7 dagen een andere overheidsbaan gehad (Blijft het zelfde)

Heb je de afgelopen 30 dagen bij een criminele organisatie gezeten * (Blijft het zelfde)

**Comment by Willem-Dekker** [comment]
done
