### ISSUE TITLE
Crash bij esx_lscustoms

### ISSUE THREAD

**Issue by niekschoemaker** [Tedeapolis/development#713]
**Omschrijf de bug**
Crash bij selecteren velgen in lscustoms

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
naar mod shop gaan en velgen selecteren

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

**Screenshots en/of logbestanden**
[CfxCrashDump_2021_08_19_15_30_59.zip](https://github.com/Tedeapolis/development/files/7016141/CfxCrashDump_2021_08_19_15_30_59.zip)
![image](https://user-images.githubusercontent.com/32094562/130107069-aaef419c-00cc-44a8-88cd-3e2d3f35edbc.png)

**Impact op de server**
Middelmatig - Groot

**Comment by brothasx** [comment]
#947  Word daar in behandeld.
