### ISSUE TITLE
Meldkamer DSI / Recherche

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#715]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel zijn er meldkamers voor elke overheidsdienst, graag zijn wij nog twee extra meldkamers voor de DSI en de Recherche. Beide diensten ontvangen al aparte meldingen.

**Wat lost deze feature op?**
Dat de meldingen overzichtelijk staan en er gezien kan worden als de meldkamer geabused word.

**Comment by Willem-Dekker** [comment]
zit er morgen in
