### ISSUE TITLE
/shuff werkt niet meer

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#718]
**Omschrijf de bug**
Momenteel als je /shuff doet dan schuif je niet door naar de andere stoel

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In een auto op de bijrijders stoel gaan zitten en dan /shuff doen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal als je /shuff doet zou je moeten verplaatsen naar de bestuurders stoel

**Screenshots en/of logbestanden**

**Impact op de server**
Redelijk veel

**Comment by niekschoemaker** [comment]
Is gefixed.
