### ISSUE TITLE
Grote EUP update (in progress)

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#719]
**DSI**
- [ ] Gillermo update
- [ ] DSI Platecarrier BOT variant maken

**Politie**
- [x] Rangonderscheiding
- [x] Jas
- [x] Lange / korto polo

**Recherche**
- [ ] Vrouwelijke politie pas
- [ ] Nieuwe recherche jas

**Ambulance**
- [x] Medische handschoenen toevoegen aan ambulance EUP-UI (mannen/vrouwen)
- [x] OVD-G outfit (vrouw) 
- [ ] MMT Piloot outfit (mannen/vrouwen)  (Komt binnenkort)
- [ ] Verpleegkundige outfit

**EUP-ui**
- [ ] DSI outfits permissions goed zetten, zijn nu voor iedereen beschikbaar
- [ ] Trainer outfit permissions goed zetten, moet voor iedereen
- [ ] Masker toevoegen aan vrouwelijk recherche ui

**Comment by MartijnMeister** [comment]
- [ ] Hondengeleider steekvest toevoegen aan UI
- [ ] Reflecterend hesje politie (ovd-k retexture) toevoegen aan UI
- [ ] Reflecterend hesje kmar (ovd-k retexture) toevoegen aan UI

**Comment by MisterM02** [comment]
- [ ] BOT Zware vest toevoegen aan de UI

**Comment by Devenco** [comment]
- [ ] Zwaar vest uit optie voor DSI vesten

**Comment by walvisgedaan** [comment]
> * [ ]  BOT Zware vest toevoegen aan de UI

Staat er in

**Comment by walvisgedaan** [comment]
> * [ ]  Kopje Recherche uit dienst beschikbaar maken voor boss job (recherche jobs hebben dit al)
> * [ ]  Kogelwerend (dus niet zware vest maar de andere) toevoegen aan recherche EUP
> * [ ]  Beenholster onder Recherche EUP werkend maken
> * [ ]  KMar kopje weghalen bij boss job en recherche jobs
> * [ ]  Masker 1/2 & Scarf toevoegen aan Recherche EUP
> * [ ]  Optie om medische handschoenen uit de doen (net als zwaar vest uitdoen)

Busy

**Comment by walvisgedaan** [comment]
> * [ ]  DSI outfits zijn voor iedereen bereikbaar (vermoedelijk =dsi check die fout staat)
> * [ ]  Trainer outfit alleen voor DSI+ bereikbaar (vermoedelijk =dsi check die fout staat)
> * [ ]  Vrouwelijk politiepasje + toevoegen aan recherche outfit (vrouw)
> * [ ]  Vrouwelijk masker toevoegen aan recherche UI

Busy
