### ISSUE TITLE
ANWB & AMBU rijbewijs check voordat je een bedrijfsauto kan pakken. 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#722]
**Beschrijf zo duidelijk mogelijk de feature**
Dat je zonder een autorijbewijs geen voertuig kan pakken uit de garage bij AMBU of ANWB. 

**Wat lost deze feature op?**
Dat de medewerkers van AMBU of ANWB verplicht zijn om in bezit te zijn van een geldig auto rijbewijs.

**Comment by niekschoemaker** [comment]
Done
