### ISSUE TITLE
Body Armor vest F11

### ISSUE THREAD

**Issue by RonaldDaquila** [Tedeapolis/development#725]
**Beschrijf zo duidelijk mogelijk de feature**
Met het F11 menu kan je jouw shirt, broek en schoenen uit trekken. Wanneer dit allemaal uit is blijft jouw body armor aan, wanneer je deze aan hebt bij jouw pakje. De suggestie is dus om dus om "body armor" aan en uit te trekken door middel van het f11 menu.

**Wat lost deze feature op?**
Nu moet je je shirt uit doen en soms houd je dan je body vest aan. Wanneer dit in de game zit, kan je ook jouw body armor uit trekken.

**Comment by niekschoemaker** [comment]
Done, heb het bij tshirt in gedaan.
