### ISSUE TITLE
/setjob en /setjob2 werkt niet voor supermod

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#727]
**Omschrijf de bug**
Momenteel als je als Super Mod /setjob of /setjob2 wilt doen geeft die acces denied aan 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Zet je zelf op de permissies van een Super Mod en probeer /setjob en /setjob2

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden wij hier toegang tot moeten hebben

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/84158163/131138305-4eefa3e4-af81-42df-bd00-73131ebde6de.png)

**Impact op de server**
Redelijk veel als mensen jobs nodig hebben etc...

**Comment by niekschoemaker** [comment]
Is dit ondertussen al gefixed? Voor zover ik kan zien/weet wel?

**Comment by AnatolyMoskvin** [comment]
Nee het werkt voor supermod nog steeds niet helaas alleen /setjobself werkt dus dan nog te fixen /setjob en /setjob 2

**Comment by AnatolyMoskvin** [comment]
Ondertussen werkt het weer voor Supermod!
