### ISSUE TITLE
Porto callsign,s verdwijnen naar reloggen 

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#729]
**Omschrijf de bug**
Momenteel als je bij taxi /setcallsign doet en gaat reloggen is deze na het reloggen weer weg. Zodra je dan dus weer in de porto gaat zie jij je eigen naam niet en andere ook niet.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een overheids job nemen daarna de porto van die job joinen dus bij taxi (140) dan doe je /setcallsign (je naam)
Daarna relog je en join je weer de porto, nu zal je zien dat je callsign weg is

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je callsign zou moeten blijven staan

**Screenshots en/of logbestanden**

**Impact op de server**
Redelijk groot mensen moeten steeds opnieuw /setcallsign doen

**Comment by niekschoemaker** [comment]
Is gefixed (als het goed is)
