### ISSUE TITLE
Voertuig opslag politie

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#73]
Graag zien wij de voertuig opslag in aphabetische volgorde. aangezien er veel voertuigen in staan maakt dit het onoverzichtelijk.

**Comment by Willem-Dekker** [comment]
op welk ding moet het staan?

Voornaam, achternaam, kenteken, inbeslagname datum?

**Comment by SecretSupplier** [comment]
Voornaam

**Comment by Willem-Dekker** [comment]
done
