### ISSUE TITLE
Buckingham Swift

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#730]
Buckingham Swift

 /car swift

- [ ]  De kofferbak van deze heli naar 375Kg brengen. 

Uitleg : Kofferbak Inhoud:  In de Buckingham Super Volito past 160 Kilo's. Met een berekening van 3.300.000 (prijs van volito) : 160 (kilo) = 20.625 (waarde van kilo's). Dus als je dan 8.000.000 : 20.625 = 388. Dan zou ik zeggen 
maak er 375 Kg van. Als je dit vergelijkt met andere heli's vind ik dit redelijk normaal. 

Ticket : 24808

**Comment by niekschoemaker** [comment]
Zelfde geld dan toch ook voor de volatus lijkt me

**Comment by niekschoemaker** [comment]
Nou ja heb even full rebalance gedaan om het wat logisch te krijgen
