### ISSUE TITLE
KMar rangen update

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#733]
**Beschrijf zo duidelijk mogelijk de feature**
Nieuwe rangen bij de KMar in-game. 
Lonen kunnen bij mij (Yassin de Vries) worden opgevraagd.

Nieuwe opzet van de normale, let op dit is exclusief de HRB en BSB die rangen zijn al helemaal goed nu en mogen blijven staan.

----- Kader -----
01.Luitenant-Generaal - ❙✯✯✯ \ 
02.Generaal-Majoor - ❙✯✯ \ 
03.Brigadegeneraal - ❙✯ \ 
----- Hoofdofficieren (OPS) -----
04.Kolonel - ❙❃❃❃ / Training: Unmarked \  +Unmarked Audi A6
05.Luitenant-Kolonel - ❙❃❃ / Training: SMG \ 
06.Majoor - ❙❃ / Training: OPS \ 
----- Officieren (OVD) -----
07.Kapitein - ❃❃❃ / Training: Motor 2/2 \
08.Eerste-Luitenant - ❃❃ / Training: KW heli \ +KW heli
09.Tweede-Luitenant - ❃ / Training: OVD e
----- Onderofficieren (OPCO) -----
10.Adjudant - ❙● / Training: Motor 1/2 \   +Motor on-/off-road
11.Opperwachtmeester - ❙❯❯❯❯ / Training: SIV - Gevorderde Rijtraining \ +SIV (audi a6)
12.Wachtmeester 1e klasse - ❙❯❯❯ / Training: OPCO - IBT+ \ 
13.Wachtmeester - ❙❯❯ / Training: Amarok - WKT \  +VW Amarok
----- Manschappen -----
14.Marechaussee 1e klasse - ❙❯ / Training: KW - COM-TOETS \  +Kustwacht booten
15.Marechaussee 2e klasse - ❯❯ / Training: IBT - RTGK VWP \ +Vuurwapen (HKP2000)
16.Marechaussee 3e klasse - ❯ / Training: BT+TOETS - RTGK NVWP \ Wapenstok, Taser, Zaklamp, Touran

**Wat lost deze feature op?**
Er zijn 13 bruikbare rangen (exclusief kader rangen) dan doe je er dus ongeveer driekwart jaar tot een jaar er over om aan de top te komen. Wat we ermee winnen: een extra manier om mensen te motiveren en meer training/leer momenten waardoor we een beter opgeleid team krijgen.

Kan ook relevant zijn voor Issue #719 waarbij WhaleDone de rangen gaat maken op de uniformen van de KMar

**Comment by Willem-Dekker** [comment]
zit er in na restart

**Comment by Streamcentralrulez** [comment]
Er zijn een aantal issues naar de herstart gekomen

100 Luitenant-Generaal -> 
Geen Maserati
Geen DSI meldingen

95 Generaal-Majoor -> 
Geen Maserati
Geen DSI meldingen
DSI/BSB EUP (Zowel indienst als uit dienst)
Geen BSB/DSI perms Porto 118, ook geen schietmeldingen.
Flitsboetes zowel indienst als uitdienst uitzetten.

90 Brigadegeneraal -> 
Geen Maserati
Mogelijk geen DSI meldingen
DSI/BSB EUP (Zowel indienst als uit dienst)
Geen BSB/DSI perms Porto 118, ook geen schietmeldingen.
Flitsboetes zowel indienst als uitdienst uitzetten.

**Comment by Ljosfari** [comment]
Is dit nog een issue ?

**Comment by Chrushers** [comment]
Ja er zijn nog wat issues met de rangen zie onderstaande.
Let op dit zou bij elke rang nog er bij moeten. De rest van wat de rangen reeds hebben mogen ze ook houden dit is een aanvulling op de rangen.

kmar 100 - Label: Marechaussee Luitenant-Generaal - + UNMARKED MASERATI
kmar 95 - Label: Marechaussee Generaal-Majoor - Overige: +Geen flitsboetes (Zoals huidige kmar 100 rang), +Schietmeldingen/overvallen. +(zelfde rechten/wapens en voertuigen als BSB dus kmar 80,81,82,83) + Unmarked Maserati +HRB Auto
kmar 90 - Label: Marechaussee Brigadegeneraal - Overige: +Geen flitsboetes (Zoals huidige kmar 100 rang), +Schietmeldingen/overvallen. +(zelfde rechten/wapens en voertuigen als BSB dus kmar 80,81,82,83) + Unmarked Maserati +HRB Auto
kmar 60 - Label: Marechaussee Kolonel - Voertuigen: +Unmarked Audi RS6
Kmar 70 - Label: HRB - Aspirant  - Wapenkluis: +fire extinguisher en parachute + Geen flitsboetes in dienst
Kmar 71 - Label: HRB - Operator  - Wapenkluis: +fire extinguisher en parachute + Geen flitsboetes in dienst
Kmar 72 - Label: HRB - Groepscommandant  - Wapenkluis: +fire extinguisher en parachute + Geen flitsboetes in dienst
Kmar 73 - Label: HRB - Sectiecommandant  - Wapenkluis: +fire extinguisher en parachute + Geen flitsboetes in dienst
Kmar 74 - Label: HRB - commandant  - Wapenkluis: +fire extinguisher en parachute + Geen flitsboetes in dienst
