### ISSUE TITLE
Attitude meter meer naar boven zetten.

### ISSUE THREAD

**Issue by RonaldDaquila** [Tedeapolis/development#734]
**Omschrijf de bug**
In de screenshot hieronder is te zien dat wanneer je twee banen hebt, het bijna niet mogelijk is om de attitude meter te zien wanneer je in airspace zit.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
De attitude op een andere plek zetten, zodat iedereen het kan zien.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Dat iedereen de attitude kan zien.

**Screenshots en/of logbestanden**
https://cdn.discordapp.com/attachments/608089499049787412/883630333940088862/unknown.png

**Impact op de server**
Zo kunnen ook spelers met twee jobs op een normale hoogte vliegen en dit beter in de gaten houden.

**Comment by Chang-nl** [comment]
Dit is geregeld na eerstvolgende restart!
