### ISSUE TITLE
Specaten werkt niet goed sinds vanochtend.

### ISSUE THREAD

**Issue by Sjenkie-Sjembek** [Tedeapolis/development#735]
**Omschrijf de bug**
Sinds vanochtend werkt /spectate niet meer goed. In veel gevallen blijf je ergens hangen en val je uiteindelijk terug op je oude positie met de melding 0 routing bucket. Ik heb het ook even gevraagd om te testen aan mede staff en Mart had het zelfde.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
/specate gebruiken

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
/spectate as usual.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/74136000/132119057-a7110ee1-a6d5-4093-bc73-9a28f76e9153.png)

**Impact op de server**
Helpers kunnen niet spectaten

**Comment by niekschoemaker** [comment]
Fixed
