### ISSUE TITLE
Repareerkit (burgerraad)

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#737]
**Beschrijf zo duidelijk mogelijk de feature**
Repareerkit meer stamina geven zodat het voertuig langer kan rijden.

**Wat lost deze feature op?**
Momenteel kun je maar 100meter afleggen na het gebruik van een repairkit.

**Comment by niekschoemaker** [comment]
Heb hem lichtelijk gebuffed en de melding ff aangepast zodat het duidelijk is dat je naar de ANWB moet gaan alsnog.
