### ISSUE TITLE
Bug Ramenwasser

### ISSUE THREAD

**Issue by RenoNiiChan** [Tedeapolis/development#74]
Na het voltooien van een ramenwasser job en het terug in de voertuig te stappen wordt men uit het voertuig gehaald.

Verwachte resultaten | Gekregen resultaten

1. Kleren aandoen & busje uithalen | **[OK]**

2. Ramen wassen & factuur verkrijgen | **[OK]**

3. Voertuig opnieuw in gaan en naar volgende locatie rijden | **[NOK]** Bestuurder & passagier worden eerste x na het uitvoeren van van punt 2, 1malig uit het voertuig gezet.

4. Verkrijgen nieuwe locatie | **[OK]**

5. Verkoop Facturen & busje retour | **[OK]**

Foto's & Videos hieronder te vinden.
 
Oplossingsplan:

- [x] Bug vaststellen en lokaliseren

- [x] Bug oplossen

[Video 1](https://youtu.be/Hs_vp7IZ3So)

[Video 2](https://youtu.be/I4tYMb35Erg)

[Video 3](https://youtu.be/RScL2g9uzIY)

[F8 Console tijdens de bug 1](https://user-images.githubusercontent.com/69079036/89403611-de7ad400-d718-11ea-8cba-b8349936dc21.jpg)
[F8 Console tijdens de bug 2](https://user-images.githubusercontent.com/69079036/89403614-df136a80-d718-11ea-89fd-d126de393963.jpg)
[F8 Console tijdens de bug 3](https://user-images.githubusercontent.com/69079036/89403617-df136a80-d718-11ea-943f-a21304bd02e1.jpg)
[F8 Console tijdens de bug 4](https://user-images.githubusercontent.com/69079036/89403618-dfac0100-d718-11ea-9ccb-4aa4488b4021.jpg)

**Comment by Willem-Dekker** [comment]
ik heb dit net getest en ik had geen issues
