### ISSUE TITLE
Uitdienst recherche permissies zelfde als DSI + fixes

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#742]
**Beschrijf zo duidelijk mogelijk de feature**
- Niet geflitst worden door flitspalen uit dienst (Dit is ook bij de DSI zo)
- uitdienst EUP (Fixen). Ze kunnen accessoires/vesten niet zien (dat kopje). (Dit is ook voor korpsleiding deze moet ook gefixed worden)
- Uitdienst overvallen van banken / winkels / juwelier melding van krijgen
- Ingame porto (radio 110 t/m 120)

**Wat lost deze feature op?**
Dit zorgt ervoor dat de Recherche beter hun werk kan verrichten

**Comment by dilyano** [comment]
Negatief. Recherche hoeft uit dienst NOOIt te hard te rijden. Worden ze opgeroepen, dienen ze in dienst te gaan en dan te gaan rijden is in RL ook zo

voor het korps gelden dezelfde regels. Iedere flitsboete moet jij in real life kunnen verantwoorden en moet door minimaal 3 cheffen goedgekeurd worden.

**Comment by JorisDeJoris** [comment]
> Negatief. Recherche hoeft uit dienst NOOIt te hard te rijden. Worden ze opgeroepen, dienen ze in dienst te gaan en dan te gaan rijden is in RL ook zo
> 
> voor het korps gelden dezelfde regels. Iedere flitsboete moet jij in real life kunnen verantwoorden en moet door minimaal 3 cheffen goedgekeurd worden.

Dus DSI mag wel uitdienst met 300 rijden zonder boetes?

**Comment by dilyano** [comment]
> > Negatief. Recherche hoeft uit dienst NOOIt te hard te rijden. Worden ze opgeroepen, dienen ze in dienst te gaan en dan te gaan rijden is in RL ook zo
> > voor het korps gelden dezelfde regels. Iedere flitsboete moet jij in real life kunnen verantwoorden en moet door minimaal 3 cheffen goedgekeurd worden.
> 
> Dus DSI mag wel uitdienst met 300 rijden zonder boetes?

Ja. Dsi is een speciaal getraind interventie team wat prive een hele snelle auto krijgt om zo heel snel van de ene kant van het land naar de andere kant te kunnen vanuit een prive situatie. 
een rechercheur is iemand die altijd NA het incident komt. Zonder prio 1. Zonder speciale interventie training.
