### ISSUE TITLE
Nieuwe flits palen

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#743]
**Beschrijf zo duidelijk mogelijk de feature**
Een flits paal op postcode 5032. 
![image](https://user-images.githubusercontent.com/82154593/132261973-c8f6834c-92e4-40d2-8fce-27fd51c0d328.png)
Hier rijden mensen met 300 langs en dit is niet realistisch 

Een flits paal op postcode 7027 (kruispunt basicfat) 
![image](https://user-images.githubusercontent.com/82154593/132262003-1f3310f2-5200-4bd1-88e7-c9fd2042d85b.png)

**Wat lost deze feature op?**
Dat mensen wat normaler hier gaan rijden. Mensen worden continu hier dood gereden omdat ze met 300 langs vliegen

**Comment by niekschoemaker** [comment]
Zit erin
