### ISSUE TITLE
Autos die niet showen in het MEOS

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#744]
**Omschrijf de bug**
voertuigen die niet in MEOS staan.
Zoals eiland autos
Veiling autos
en nieuwe boten (longfin)

OUD meos zie je niks
Nieuwe meos zie je alleen kenteken maar niet model naam van voertuig 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
MEOS openen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je ziet de autos erin staan. met kenteken en model van voertuig

**Screenshots en/of logbestanden**
zero

**Impact op de server**
De politie kan zijn werk hierdoor niet goed uitvoeren. En burgers gebruiken deze voertuigen als opslag aangezien de politie deze niet kunnen vinden.

**Comment by dilyano** [comment]
Voorstel zou zijn deze autos hier ook niet te showen aangezien het eiland voertuigen zijn.

**Comment by AnatolyMoskvin** [comment]
Eiland voertuigen is volgensmij juist express gedaan omdat het iets illegaals is

**Comment by Ljosfari** [comment]
duplicate van #814
