### ISSUE TITLE
ATC Glitch

### ISSUE THREAD

**Issue by TDA-Djao** [Tedeapolis/development#746]
**Omschrijf de bug**
Je hoort niet meer automatisch de ATC als je in een vliegtuig/helikopter stapt, enkel wanneer je ook in de porto gaat.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
1: Stap in een vliegtuig of helikopter
2: Ga niet in de atc
3: Laat iemand anders in de atc praten
**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal moet je de ATC altijd kunnen horen in een vliegtuig/helikopter.

**Screenshots en/of logbestanden**
Geen

**Impact op de server**
Klein

**Comment by niekschoemaker** [comment]
Is ondertussen gefixed
