### ISSUE TITLE
Heftruck vorken kunnen niet omhoog en omlaag

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#747]
**Omschrijf de bug**
Momenteel kan je de vorken niet met Numpad2 en Numpad8 omhoog doen

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door een Heftruck te pakken /car forklift en dan op Numpad2 en Numpad8 te drukken

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden deze omhoog en omlaag moeten gaan 

**Screenshots en/of logbestanden**

**Impact op de server**
Op de job in de haven best veel want deze kan je atm niet uitvoeren

**Comment by niekschoemaker** [comment]
Zou je dit even kunnen checken, als het goed is had ik dit gefixed

**Comment by Mikajac** [comment]
![image](https://user-images.githubusercontent.com/20951687/133165955-e21eac9d-b937-4a72-91c1-e66e648553c1.png)

Yes, het werkt weer!

**Comment by AnatolyMoskvin** [comment]
Toppers :D
