### ISSUE TITLE
ELS lampen werken niet tot 7/8 spier wordt ingedrukt

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#748]
**Omschrijf de bug**
Wanneer je ELS activeerd (Bijv blauwe lampen met Q) dan zie je in eerste instantie het blauwe licht om je heen. Wanneer je daarna op 7 klikt dan werken de lampen wel weer. 
Verder gebeurd het vaak dat als je stopteken wilt geven (K) dat je dan kleding menu krijgt. Gele lampen werken ook niet helemaal.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Stap in een ELS voertuig en druk op Q, K of L. Wanneer je daarna 7/8/9 probeert dan werkt het soms

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De lampen horen gewoon aan te gaan en te knipperen. Bij K hoort het kleding menu niet open te gaan.

**Screenshots en/of logbestanden**
[CitizenFX_log_2021-09-09T163610.txt](https://github.com/Tedeapolis/development/files/7138369/CitizenFX_log_2021-09-09T163610.txt)

**Impact op de server**
Onbekend.

**Comment by niekschoemaker** [comment]
ELS == pijn

maar k zal ff kijken doe ongeveer 1 rewrite per week voor die plugin

**Comment by niekschoemaker** [comment]
Ah ja het gedeelte met 7 en 8 spier miste ik, maar zie het idd, ambulances en anwb voertuig heeft er vooral last van.

Zal hier later even naar kijken.

**Comment by niekschoemaker** [comment]
Is gefixed.
