### ISSUE TITLE
Slagingskans op thermiet

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#750]
**Beschrijf zo duidelijk mogelijk de feature**
Besproken tijdens het staffoverleg op 12-09 is het toevoegen van een slagingskans op het gebruik van thermiet.
Dit houdt in dat er bijvoorbeeld een kans van 5 à 10% is dat het thermiet zijn werk niet goed doet, waardoor er dus een extra moet worden geplaatst.

**Wat lost deze feature op?**
Kans op falen, waardoor roleplay scenario's anders kunnen verlopen dan verwacht.
Tevens zit er daardoor ook een wat groter risico achter snelle uitbraken uit bijvoorbeeld de gevangenis.

- [ ] Random timer voor thermiet
- [ ] Random slagingskans voor thermiet
- [ ] Animatie iets korter laten duren zodat je wel kunt bewegen tijdens de thermiet

**Comment by niekschoemaker** [comment]
Zit erin na restart
