### ISSUE TITLE
Verkoop naaktemannen kamp

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#752]
**Omschrijf de bug**
Je kan de shop daar niet openen
https://cdn.discordapp.com/attachments/785223800504844318/887040095692152882/unknown.png

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Naar de shop toegaan en proberen te openen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De shop moet open gaan

**Screenshots en/of logbestanden**
https://cdn.discordapp.com/attachments/785223800504844318/887040095692152882/unknown.png

**Impact op de server**
Best groot mensen kunnen geen termiet kopen etc

**Comment by niekschoemaker** [comment]
Duplicate of #755 

(Eigenlijk is die andere een duplicate, maar die titel vind ik iets beter <3 )
