### ISSUE TITLE
Apache te zwak

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#754]
[//]: # (Dit type regels kun je gewoon weghalen, is puur uitleg)

**Label van voertuig**

[//]: # (Zoals weergegeven in voertuig winkel/garage)
Helicopter

**Spawnnaam van voertuig**
hunter

[//]: # (Wat je gebruikt /car om het in te spawnen)

**Kenteken van voertuig (wanneer van toepassing)**

n.v.t.

[//]: # (Als het om een specifiek voertuig gaat dit graag invullen)

**Omschrijf de bug**
In TDA gaat het toestel na een paar kogels van een AK of Pistol neer. In het echt kan het armour van dit toestel meerdere kogels van het 12x7mm kaliber moeten doorstaan (wat antimaterieel is). 

[//]: # (Duidelijke omschrijving van wat er precies gebeurd)

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Er op schieten terwijl hij vliegt

[//]: # (Welke hele specifieke stappen moeten we volgen om dit betrouwbaar te kunnen hercreeëren)

**Normaal gedrag**
Zou niet kapot moeten gaan, of in ieder geval niet zo snel

[//]: # (Wat is het verwachte gedrag, wat zou er normaal moeten gebeuren)

**Screenshots en/of logbestanden**
n.v.t.

[//]: # (Wanneer van toepassingen graag logbestanden en screenshots toevoegen)

**Impact op de server**
Momenteel vrij groot aangezien er optimaal misbruik van gemaakt wordt

**Comment by niekschoemaker** [comment]
Ik heb de weapondamage multiplier ff van 0.5 naar 0.1 gezet, weet niet of dit iets doet though

**Comment by walvisgedaan** [comment]
https://prnt.sc/1sh35xl

Heeft niets aangepast, valt nogsteeds uit de lucht zo lek als een mandje :P

**Comment by ARJ3N** [comment]
Eventueel naast de Apache ook de andere voertuigen van defensie meenemen? 🙂 

buzzard
buzzard2
annihilator3
chinook
hunter
lazer
hydra
