### ISSUE TITLE
Lester zwarte markt.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#755]
**Omschrijf de bug**
Cirkel zwarte markt werkt niet. Hij opent niet.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In cirkel staan en op E drukken.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Cirkel opent doormiddel van E drukken en je krijgt een menu.

**Screenshots en/of logbestanden**
![afbeelding](https://user-images.githubusercontent.com/69365961/133424377-ee391f90-5159-4559-af94-146e8f5fcab6.png)

**Impact op de server**
Medium.

**Comment by niekschoemaker** [comment]
Zou je dit even opnieuw kunnen checken, is als het goed is gefixed nu.

**Comment by niekschoemaker** [comment]
Is gefixed
