### ISSUE TITLE
ANWB aanpassingen #1

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#756]
- [x] ANWB zelfde garage menu geven zoals bijvoorbeeld Politie of Ambulance.
(zodat anwb'ers objecten kunnen opslaan in hun voertuig zoals banden en jerrycans.) 
- [ ] Dat anwb uitdienst-baas het bazen menu kan zien (Dan hoeven wij niet in-diens te gaan voor kleine dingetjes).
- [x] Dat ANWB'ers brood & water kunnen pakken op ANWB HB (tussen Stock opnemen".
- [x] ANWB Baas & Directeur rang toegang geven tot het command /setjob.  
- [x] De volgende rangen toegang geven om uit-dienst de ANWB porto's frequentie 130 en 131 te joinen: 
Uitdienst-Hoofddirecteur
Uitdienst-Directeur
Uitdienst-Teamleider
Uitdienst-Teamleider in opleiding

**Comment by niekschoemaker** [comment]
PUntje 1, als het goed is gebruiken anwb voertuigen sinds kort je werk kenteken, dus als het goed is is de kofferbak synced over alle anwb voertuigen van jou persoonlijk.

Puntje 2 ga ik afwijzen puur omdat dit heel wat changes zouden moeten zijn voor een hele kleine tijdswinst.

**Comment by niekschoemaker** [comment]
Porto wijziging zitten er na volgende restart in
