### ISSUE TITLE
WraithRS (Politie Radar) Patrol speed komt nog niet overeen met nieuwe snelheid

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#757]
**Omschrijf de bug**
Patrol speed vd WraithRS resource komt nog niet overeen met de snelheid die je rijd. Wanneer je 80 rijdt, staat daar dat je 64 rijdt. Hierdoor krijg je dus ook foutieve informatie met het klokken van voertuigen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Het klok systeem opstarten, speedlimit op 80 zetten en dan naar patrol speed kijken

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Patrol speed zou gelijk moeten zijn aan de snelheid die je daadwerkelijk rijdt

**Screenshots en/of logbestanden**
![Screenshot_145](https://user-images.githubusercontent.com/47216413/133680479-be8f6c0d-7be1-4a9e-bc60-fc7380f651e5.png)

**Impact op de server**
Mensen worden foutief geklokt en krijgen dus verkeerde boetes

**Comment by AdventurePandah** [comment]
Heb vernomen van Sander dat de snelheidmeter onderin niet klopt maar de patrol speed dus wel ^^

**Comment by niekschoemaker** [comment]
Fixed
