### ISSUE TITLE
Random dood gaan bij auto rijden

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#758]
**Omschrijf de bug**
Als burgers gewoon rijden of een klein stukje over gras gaan. Dan vliegen ze in een keer dood. Je remt nu ook super hard hier af als je op gras gaat wat niet logisch is.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Vaak genoeg over kleine stukjes gras rijden

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je vliegt niet meteen dood

**Screenshots en/of logbestanden**
https://streamable.com/7jn79b
https://www.youtube.com/watch?v=65SuPqQO2wg
**Impact op de server**
Super groot gaan veel mensen random dood en dit verpest veel RP

**Comment by niekschoemaker** [comment]
Als et goed is is dit ondertussen gefixed.
