### ISSUE TITLE
Bug spawn voertuigen job

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#759]
**Omschrijf de bug**
Bij sommige jobs (tot nu toe gemerkt bij olie verwerken en vuilniswagen) spawnen de voertuigen op zijn kop

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Voertuig pakken bij een van de job

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De voertuig spawnt op zijn wielen 

**Screenshots en/of logbestanden**
https://streamable.com/sw032v

**Impact op de server**
Vrij groot mensen kunnen nu niet hun job uitvoeren

**Comment by brothasx** [comment]
Alsook zijn er updates onderweg die loop deze 2 weken word uitgevoerd naar de main.
