### ISSUE TITLE
Sleepwagen van 500k wil geen auto's meer slepen.

### ISSUE THREAD

**Issue by BobDeHuisbaas20** [Tedeapolis/development#760]
**Omschrijf de bug**
Zoals je weet, moet je op E klikken om de sleepwagen vast te zetten. Dit werkt dus niet. Daarna crasht je fivem.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je rijdt de auto erop (met lege kofferbak) daarna klik je op E om het voertuig vast te zetten. Dit gebeurt nu dus niet, na een enkele seconden crash je.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Dat het voertuig vastgezet wordt.

**Screenshots en/of logbestanden**
https://youtu.be/TfNyXUalaR4

**Impact op de server**
Weet ik niet.

**Comment by MartijnMeister** [comment]
Dit probleem geldt ook voor de politie en anwb sleepwagen. Zal dus met het takelscript te maken hebben.
Zal vanavond even naar logbestanden zoeken

**Comment by MartijnMeister** [comment]
https://gyazo.com/342f39b81401ca4b94a139c7dfb4cf60

**Comment by niekschoemaker** [comment]
is dit nog steeds een issue? Kan hem namelijk niet replicaten (niet op canary en niet op release)

**Comment by MartijnMeister** [comment]
https://gyazo.com/9540363f0875d420aa88ecd19d94b09f

Nogsteeds deze crash ^^

**Comment by MartijnMeister** [comment]
Probleem is er nogsteeds

**Comment by MartijnMeister** [comment]
Probleem speelt nogsteeds

**Comment by niekschoemaker** [comment]
Is gefixed

**Comment by niekschoemaker** [comment]
Wat extra info,

Stack trace functie van C# lijkt broken te zijn, dus als er in LUA een error gebeurt maar er ergens in de stack een C# iets voorkomt crashed FiveM.

Heb het gefixed door een thread aan te maken in LUA voordat ik code uitvoer zodat er een nieuwe stack gemaakt wordt.
