### ISSUE TITLE
Bug - Zak van hoofd halen

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#763]
**Omschrijf de bug**
Wanneer iemand anders dan de "plaatser" de zak van het hoofd van een speler haalt, wordt deze zak uit de server verwijderd.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Speler A plaatst een zak over het hoofd van speler B. Deze zak haalt speler C van speler B.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Als speler A de zak van speler B verwijdert, krijgt hij deze terug in zijn inventaris. Als speler C deze verwijdert van speler B, krijgt niemand deze zak en wordt deze dus uit de server verwijderd.

**Screenshots en/of logbestanden**
/

**Impact op de server**
Klein, puur voor extra realisme. Ook onbekend of dit een bug is of zo hoort.

**Comment by niekschoemaker** [comment]
Fixed
