### ISSUE TITLE
Jute zakken zijn kapot

### ISSUE THREAD

**Issue by MartijnMeister** [Tedeapolis/development#764]
**Omschrijf de bug**
Als iemand een zak op het hoofd doet bij een persoon gaat deze automatisch weer af na enkele seconden. Dit zonder dat iemand hem van het hoofd afhaald.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een zak op iemand zijn hoofd doen en dan enkele seconden wachten

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou de zak er gewoon op moeten blijven zitten, en er enkel afgaan naar 15 minuten of wanneer hij eraf wordt gehaald.

**Screenshots en/of logbestanden**
Indien nodig kan ik een video uploaden

**Impact op de server**
Wanneer iemand geblinddoekt wordt is het vervelend dat hij toch achter een locatie kan komen terwijl dit niet de bedoeling is

**Comment by niekschoemaker** [comment]
fixed
