### ISSUE TITLE
Upgrade Porsche Panamera Techart

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#765]
**Label van voertuig**

Porsche Panamera Techart

**Spawnnaam van voertuig**

techart17

**Kenteken van voertuig (wanneer van toepassing)**

Alle voertuigen, geen specifiek kenteken

**Omschrijf de bug**

Upgrades op dit voertuig werken niet, er kan namelijk alleen turbo op.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Voertuig kopen/inspawnen en proberen te tunen

**Normaal gedrag**

Je kunt het voertuig met motor, transmissie, remmen en pantser upgraden/tunen.

**Screenshots en/of logbestanden**

/

**Impact op de server**
Klein, één specifiek voertuig wat niet fatsoenlijk geupgrade kan worden.

**Comment by walvisgedaan** [comment]
Ik weet zelf niet hoe ik dit moet oplossen @niekschoemaker weet jij iets?

**Comment by niekschoemaker** [comment]
> 
> 
> Ik weet zelf niet hoe ik dit moet oplossen @niekschoemaker weet jij iets?

Ja gewoon carcols test output checken en de ID's goed zetten, maar had dit al gedaan op de main server

**Comment by niekschoemaker** [comment]
Dus bij deze, is gefixed.
