### ISSUE TITLE
Bug - Nieuwe kleding zit niet goed

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#766]
**Omschrijf de bug**
Bepaalde kledingstukken (vermeld hieronder) sluiten niet goed aan of zorgen voor andere bugs.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
De volgende kledingstukken aan trekken.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal aansluiten/niet je hele outfit buggen.

**Screenshots en/of logbestanden**
Broeken 139 & 149 zijn te laag waardoor men geen middel heeft (ligt aan de broek, bij andere broeken sluit het wel mooi aan)
![image](https://user-images.githubusercontent.com/20951687/134791498-1cef290c-9685-4fd8-a3f8-69b31e94c6f6.png)

Pet 160 sluit niet mooi aan op je hoofd (pet 96 bijvoorbeeld wel)
![image](https://user-images.githubusercontent.com/20951687/134791522-e18a8521-9281-4aca-adb3-0916da16645d.png)

Kogelvrij vest 57 (is een tas) en tassen 104 & 105 zweven over de schouder (kan ook deels komen door "dun" shirt?).
![image](https://user-images.githubusercontent.com/20951687/134791542-27959413-e4df-459c-ac29-c5c0a1b0804c.png)

Ketting 57 laat je hele outfit glitchen.
https://medal.tv/clips/4t2Aib8zrVifS/i1d1hgrT54dX?invite=cr-MSw2dkQsMjE2NzQyMjcs

**Impact op de server**
Sommige klein (puur uiterlijk), maar ook een redelijke.

**Comment by niekschoemaker** [comment]
Hier kan niks aangedaan worden, is gewoon zo
