### ISSUE TITLE
Melding van warning

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#767]
**Beschrijf zo duidelijk mogelijk de feature**

Indien je een warning hebt gehad en de stad in komt, dat je te zien krijgt wat de reden van de warning is. Scheelt een hoop reports waarom ze ineens taakstraf hebben.
**Wat lost deze feature op?**
Dat mensen niet weten waarom ze bij de taakstrafplaats staan.

**Comment by niekschoemaker** [comment]
Done
