### ISSUE TITLE
DSI uitdienst - F6 menu

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#768]
**Beschrijf zo duidelijk mogelijk de feature**
De DSI mag zowel in- als uitdienst te werk gaan. Hierbij komt het vaak voor dat de eenheden uitdienst meerijden in achtervolgingen, overvallen o.i.d.
Het vervelende is echter dat ze buitendienst, terwijl ze wel al het benodigde gereedschap in hun voertuigen hebben liggen, geen gebruik kunnen maken van de fouilleer en boei optie uit het F6 menu.
In overleg met Whaledone daarom de aanvraag om de DSI ook uitdienst gebruik te laten maken van het F6 menu.

**Wat lost deze feature op?**
Het gaat mensen tegen die niet mee willen werken met request_search, wegrennen terwijl ze via /me worden vastgehouden etc.

**Comment by MartijnMeister** [comment]
Dit zou dan gaan om de DSI en BSB rangen ^^
