### ISSUE TITLE
Trailers houthakker verdwijnen.

### ISSUE THREAD

**Issue by BobDeHuisbaas20** [Tedeapolis/development#769]
**Omschrijf de bug**
De trailers van de vrachtwagens bij de houthakkers job verdwijnen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Gewoon de job te starten en te beginnen en vaak in het midden vd de job (denk aan een halfuurtje of 45 minuten verdwijnt ineens de trailer bij sommige mensen).

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De trailer zou moeten blijven staan.

**Screenshots en/of logbestanden**
Is er niet.

**Impact op de server**
Irritant.

**Comment by Mikajac** [comment]
Dit is mij recentelijk ook overkomen. Door in de truck te stappen en een stukje vooruit te rijden zou de trailer weer moeten inspawnen. Dat heeft het in ieder geval bij mij telkens opgelost.

**Comment by niekschoemaker** [comment]
Ik heb wat kleine dingen aangepast nu, fixed het hopelijk
