### ISSUE TITLE
Fixen van wapens trekken/delay

### ISSUE THREAD

**Issue by Gamespelman** [Tedeapolis/development#773]
**Omschrijf de bug**
Bij sommige wapens is de delay verkeerd ingesteld zoals de Carbine Rifle, hier moet even naar gekeken worden en eventueel nagetrokken worden. 

Voor Vladimir

**Comment by DaanVr2** [comment]
> Heb je een lijst met wapens waar naar gekeken moet worden?

WEAPON_CARBINERIFLE
WEAPON_CARBINERIFLE_MK2
WEAPON_SMG

ook is er bij elk pistool nog een 2 seconde delay met een holster om dan heb je het wapen al volledig getrokken maar kan je nog niet schieten dit klopt wel als je de animatie hebt zonder holster

**Comment by niekschoemaker** [comment]
Is gefixed
