### ISSUE TITLE
Advertenties duidelijk aangeven op twitter en de mogelijkheid om advertenties uit te zetten.

### ISSUE THREAD

**Issue by Gamespelman** [Tedeapolis/development#775]
**Beschrijf zo duidelijk mogelijk de feature**
Op twitter maken dat Advertenties om dingen te verkopen visueel gemarkeerd worden op de twitterfeed als Advertenties en dat je dit eventueel zou kunnen uitzetten met een command zoals /toggleadvertenties.

Voor Vladimir

**Comment by Ljosfari** [comment]
Hoe zie je dit precies voor je ? of hoe moet dit uitgewerkt worden ?
