### ISSUE TITLE
Spijkermatten toevoegen

### ISSUE THREAD

**Issue by Gamespelman** [Tedeapolis/development#779]
**Beschrijf zo duidelijk mogelijk de feature**
Spijkermatten toevoegen aan de shop bij de Politie en KMAR, en in het APV toevoegen dat dit alleen bij achtervolgingen mag gebruikt worden.

Voor Vladimir

**Comment by Willem-Dekker** [comment]
Randvoorwaarden: 

- Dit moet een item zijn
- Max aantal items kunnen hebben
- Je moet kunnen zien wie de mat geplaatst heeft (dit ivm eventueel straffen)
