### ISSUE TITLE
PRIO! FiveM Menu

### ISSUE THREAD

**Issue by RenoNiiChan** [Tedeapolis/development#78]
Op dit moment is een script error die ervoor zorgt dat volgende menus niet naar behoren werken:

-  Politie/Kmar Menu - F6 -> Burger Interactie gaat niet open.

- Kofferbak -> Niet mogelijk om dingen uit tehalen of weg testoppen

- Huizen -> Zijn mogelijk niet toegankelijk.

- Radio werkt niet

**Comment by RenoNiiChan** [comment]
![FiveM_GTAProcess_2020-08-06_09-12-15](https://user-images.githubusercontent.com/69079036/89503125-68cd4180-d7c6-11ea-9688-08a49a04717d.jpg)

**Comment by Willem-Dekker** [comment]
fixed
