### ISSUE TITLE
Taxi voertuigen borg

### ISSUE THREAD

**Issue by Gamespelman** [Tedeapolis/development#783]
**Beschrijf zo duidelijk mogelijk de feature**
Taxi voertuigen staan nu overal, Het is al heel lang zo dat de Taxi voertuigen overal (kapot) worden neergezet en niet worden ingeleverd bij Taxi HB, bijvoorbeeld bij politie zit er borg op  de auto’s zodat de auto’s niet worden achtergelaten. Dus een borg toevoegen op Taxi voertuigen voor medewerkers

Voor Vladimir

**Comment by niekschoemaker** [comment]
Is ondertussen geen probleem meer voor zover ik weet
