### ISSUE TITLE
F6 Menu toevoegingen voor Taxi

### ISSUE THREAD

**Issue by Gamespelman** [Tedeapolis/development#787]
optie 1 Extra 
factuur sturen naar ID

F6 menu
1-  Factuur naar dichtbij 100% (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
2- Factuur naar ID -> Factuur bedrag (100%) (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
                                   -> Helft van factuur (50%) (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
                                   -> Los bedrag tot max 2000 euro (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
3- start / stop taxi rit 
4- Conficeer taxi -> alleen voor recruiter, manager, chef rang

Voor Vladimir door Ali Osram

**Comment by TedeaTaxi** [comment]
F6 menu
1- Factuur naar dichtbij 100% (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
2- Factuur naar ID  -> Factuur bedrag (100%) (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
                               -> Helft van factuur (50%) (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
                               -> Los bedrag tot max 2000 euro (dit bedrag en naar de chauffeur en naar de taxi rekening net als NPC)
3-Taxi meter resetten
4-Taxi meter aan zetten(voor als je geen taxi auto hebt zoals ubers) moet nu via /taxi menu het kan beter in het F6 menu
5- start / stop taxi rit (NPC ritjes)
6- Conficeer taxi -> alleen voor recruiter, manager, chef rang

Uitleg:
4-Taxi meter aan zetten 
 Taxi meter aan zetten via F6 menu ipv /taxi makkelijker voor ubers mag toegevoegd worden aan elke rang

 Factuur naar ID  -> Helft van factuur (50%)
 zo dat je 2 personen ieder de rekening kan sturen nu als je toevallig 2 mensen van begraaf plaats moet brengen kan je er maar 1 een factuur sturen dit zou als oplossing kunnen zijn dat je 50/50 zou kunnen doen eerst 50% dan de rest
 
 -> Los bedrag tot max 2000 euro 
 tot max 2k om misbruik te voor komen.
 We hebben nu een log systeem en we zien dus wie hoevaak een factuur stuurt en kunnen ingrijpen bij misbruik
