### ISSUE TITLE
Geldkarretjes banken verdwijnen

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#792]
**Omschrijf de bug**
De afgelopen week is het meermaals voorgekomen dat geldkarretjes in de banken opeens despawnen terwijl het geld nog niet gepakt is. Dit gebeurd enkele seconden nadat de kluis is geopend. Samen met één van de personen heb ik al in de persoonlijke logbestanden van hem gekeken, maar hierin is niks geks terug te vinden. 
Bekend is dat dit is gebeurd in de grote bank op 07-10 15:13 en op 10-10 17:46

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Start met het overvallen van een bank en wacht totdat de kluis is geopend. Begin hierna met geld te pakken en je zult zien dat de karretjes despawnen. (Onbekend is of dit altijd gebeurd).

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden de karretjes enkele minuten moeten blijven staan zodat het ruim voldoende de tijd is om het geld te pakken.

**Screenshots en/of logbestanden**
https://www.youtube.com/watch?v=JRhH6Gla99c
https://gyazo.com/32efb7e5b9a286d1d5063a5d03b0653e

**Impact op de server**
Het is vervelend voor mensen die een overal doen gezien ze geen geld krijgen en hiervoor onnodig reports en tickets moeten aanmaken.

**Comment by niekschoemaker** [comment]
Als het goed is is dit ondertussen gefixed
