### ISSUE TITLE
Tankstation op vliegdekschip

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#795]
**Beschrijf zo duidelijk mogelijk de feature**
Graag zien we een pomp op het vliegdekschip zodat helikopter en vliegtuigen ook hier volgetankt kunnen worden. Momenteel kan dit enkel op LSIA en Helipads wat soms vervelend is voor de kustwacht / KLu.
Deze pomp zal moeten toegevoegd worden op de volgende locatie:
x: 3051.78 y: -4775.07 z: 15.26 h: 19.99

**Wat lost deze feature op?**
Het meer bruikbaar maken van het vliegdekschip.

**Comment by niekschoemaker** [comment]
Zit erin
