### ISSUE TITLE
Kledingcirkel toevoegen aan het 14k huis

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#797]
**Beschrijf zo duidelijk mogelijk de feature**
Graag zou 14k net als alle andere groepen een kledingcirkel willen net als de overige officials.
Deze moet geplaats worden op de volgende locatie:
x: -1887.23 y: 2070.41 z: 145.57 h: 340.38

**Wat lost deze feature op?**
Het feit dat zij dan ook een cirkel hebben om kleding aan te passen, net als de rest.

**Comment by Willem-Dekker** [comment]
zit er na de restart in

**Comment by MartijnMeister** [comment]
Gok dat er bij de X een - is vergeten.
De cirkel zit namelijk op coördinaten X 1887 Y 2070 Z 145
Maar moet op X -1887 Y 2070 Z 145 moeten zitten
