### ISSUE TITLE
K9

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#799]
**Beschrijf zo duidelijk mogelijk de feature**

Is het mogelijk om de k9 van de politie iemand te laten bijten met gevolgen dat de persoon niet meer kan lopen voor bepaade tijd? Dit omdat de persoon dan gewond is. 
**Wat lost deze feature op?**
Dit zorgd ervoor dat het meer realistish is als een hond je bijt. Nu wordt je 3/4 keer gebeten en kan je gewoon verder lopen, alsof er niks aan de hand is. Op dexe manier als iemand niet meer kan lopen zorgd er voor dat het al wat meer realisme is.

**Comment by Ljosfari** [comment]
nee is niet mogelijk
