### ISSUE TITLE
Geen upgrades op Ferrari F430S

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#8]
Geen tuning upgrades (motor turbo ...)

**Comment by niekschoemaker** [comment]
Deze issue heb ik als het goed is al gefixed een poosje terug, dus waarschijnlijk verouderde issue, zal de commit er even bij zoeken.

**Comment by niekschoemaker** [comment]
https://github.com/niekschoemaker/fivem_server/commit/3326758fe6d912e1b089d4b79b1b216a76ab413a
Jep 15 dagen geleden idd, dus is al poosje gefixed.
