### ISSUE TITLE
motoren

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#80]
meer motoren naar de stad brengen , ik zie steeds meer suggesties wat betreft motoren (harleys zou mooi zijn voor de MC en de wat moderne race monsters voor de echte motor fans

**Comment by Willem-Dekker** [comment]
graag modellen bijvoegen

**Comment by takermart** [comment]
https://nl.gta5-mods.com/vehicles/harley-davidson-flhxs-street-glide-special-2018-addon-replace-fivem

https://nl.gta5-mods.com/vehicles/harley-davidson-road-king
https://nl.gta5-mods.com/vehicles/harley-davidson-knucklehead
https://nl.gta5-mods.com/vehicles/harley-davidson-fat-boy-terminator-2-hq-add-on
https://nl.gta5-mods.com/vehicles/harley-davidson-fat-boy-lo-racing-bobber-lost-mc-custom-animated-replace
https://nl.gta5-mods.com/vehicles/harley-davidson-fat-boy-lo-vintage-release
https://nl.gta5-mods.com/vehicles/zbike-add-on-55-bikes-compilation-pack
