### ISSUE TITLE
Kleding gerelateerde features

### ISSUE THREAD

**Issue by niekschoemaker** [Tedeapolis/development#803]
* Meer outfit slots.
* Optie om opgeslagen outfits te verwijderen in een kledingwinkel. Voorkomt dat je eerst naar je appartement moet en dan weer terug om een outfit op te slaan als je het limiet bereikt hebt.
* Optie voor meerdere helmen/petten. Zo kan je dus bijvoorbeeld via 'K' zowel een helm als een pet aandoen i.p.v. dat je moet kiezen tussen welke je bij je wilt hebben.
* Optie om naam te veranderen van outfits in appartement en in kledingwinkel.

**Comment by Attomn** [comment]
gefixt
