### ISSUE TITLE
Bijhouden van hoeveel mensen er in dienst zijn op een bepaald moment

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#810]
**Beschrijf zo duidelijk mogelijk de feature**
Het bijhouden op een centrale plek hoe veel mensen er op dit moment bezig zijn met hun job dit is voor de banen als ramenwasser en poolcleaner. 

**Wat lost deze feature op?**
Een gebrek aan overzicht van welke baan er veel gedaan wordt in de stad en is een stepping stone voor een systeem om een maximaal aantal mensen in dienst te hebben.

**Comment by Willem-Dekker** [comment]
zit er in na restart

**Comment by Willem-Dekker** [comment]
moet nog aan nodered worden gekoppeld

**Comment by Willem-Dekker** [comment]
Zit een kleine fout in het bijhouden negatieve nummers...

**Comment by Ljosfari** [comment]
staat in #331
