### ISSUE TITLE
KMAR kustwachtvoertuigen

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#812]
Hallo,

Graag zouden we de snelheden van de Kustwacht boten en Kustwacht Heli willen aanpassen. Momenteel is het bijna onmogelijk de snellere boten bij te houden. Daarom deze aanvraag.

- [ ] KMAR RHIB van: 150KM/H naar: 200KM/H+
- [x] HILLBOATY van: 100KM/H naar: 150KM/H+
- [x] LARGEBOAT van: 50KM/H naar: 100KM/H+
- [x] KMAR HELI van 130 Knopen naar 200 Knopen (deze graag gelijk zetten aan de Wildcat van de KLU)

een LONGFIN gaat momenteel 300KM/H+

**Comment by Chrushers** [comment]
We hebben zonet even de boten getest maar we komen net de haven uit en dan is de brandstof op. Zou hier nog naar gekeken kunnen worden.

**Comment by Chrushers** [comment]
Wanneer zal hier naar gekeken worden. We zijn momenteel erg actief met de kustwacht alleen kunnen we nog steeds met de Heli de boten niet bijhouden. Tevens is bij de middelste boot de brandstof op zodra we bij helipads het open water op varen.

Alvast bedankt.

**Comment by Ljosfari** [comment]
De KMAR RHIB boot wel zo blijven van de task die nog openstaat in issue #812, alleen de helicopter moet wel aangepast worden

**Comment by Chrushers** [comment]
Alleen de Hilly Boat is de tank leeg wanneer je bij Heli Pads weg vaart en vervolgens aan het inde van de haven bent.

**Comment by Chrushers** [comment]
Misschien nog een kleine vraag. Zou het veel moeite zijn om nederlandse serines aan te brengen. Als we nu in achtervolging zitten horen ze ons vaak niet. 

Voor de rest hebben we de boten getest en ze werken allemaal perfect nu.

**Comment by Attomn** [comment]
Sirenes zijn nu gefixt op de boten en aangepast naar het Nederlands.
