### ISSUE TITLE
Eerste Hoofdcommissaris krijgt in de stad geen meldingen van Recherche op de telefoon

### ISSUE THREAD

**Issue by Smikkelbakkie** [Tedeapolis/development#818]
**Omschrijf de bug**
Als je in de stad op de rang Eerste Hoofdcommissaris staat, krijg je geenmeldingen binnen op je telefoon van berichten die gestuurd worden naar het recherche nummer.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Zet jezelf op de rang van Eerste Hoofdcommissaris en stuur een bericht naar het nummer van de recherche.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
_n.v.t._

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Dat je net zoals het nummer van de DSI alle meldingen/ berichten hoort binnen te krijgen die naar het nummer van de recherche worden gestuurd. 

**Screenshots en/of logbestanden**
_n.v.t._

**Impact op de server**
Worden veel meldingen misgelopen waar een leuke roleplay aan gehangen had kunnen worden ;P

**Comment by SecretSupplier** [comment]
Mag toegevoegd worden

**Comment by niekschoemaker** [comment]
Is gefixed
