### ISSUE TITLE
De sovereign zijn oude geluid weer teruggeven

### ISSUE THREAD

**Issue by MilonDB** [Tedeapolis/development#819]
**Beschrijf zo duidelijk mogelijk de feature**
De sovereign is een tijdje geleden in geluid verandert. Van een mooi brommend geluid naar een stofzuigergeluid (lijkt op zx10)
Ik zou graag dat dit terug verandert wordt.

**Wat lost deze feature op?**
Dit lost niet echt iets op maar maakt het rijden op deze motor een stuk leuker.

**Comment by musician1011** [comment]
Even geluisterd bij Theo, ligt aan z'n soundpack.
