### ISSUE TITLE
[BUG] /zeroto 

### ISSUE THREAD

**Issue by Mikajac** [Tedeapolis/development#820]
Betreft alle voertuigen!

**Omschrijf de bug**

Laatst zijn de topsnelheden van voertuigen met 20% gereduceerd. Echter is dit nog niet doorgevoerd in de /zeroto command. Zeroto 200 eindigt bijvoorbeeld pas zodra de teller op 250kmh staat, oftewel de reductie van 20% is nog niet doorgevoerd in dit systeem.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Een random voertuig pakken, /zeroto instellen en dan kijken op welke snelheid deze eindigt. Dit is nog op de originele snelheid, vóór de 20% reductie. 

**Normaal gedrag**

Dat /zeroto 200 op 200kmh eindigt ipv op 250kmh

**Screenshots en/of logbestanden**

https://youtu.be/HndNM7zUL6U

**Impact op de server**
Over het algemeen vrij weinig, alleen irritant voor mensen die bijvoorbeeld drag racen of de acceleratie als spec willen vermelden tijdens het verkopen.

**Comment by niekschoemaker** [comment]
Gefixed
