### ISSUE TITLE
Tunen van overgezette Audi rs6 2020

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#822]
**Omschrijf de bug**

We hebben een nieuwe rs6 2020 en diegene die de 2020 abt hadden hebben automatisch de nieuwe gekregen, probleem is dat hun die auto niet kunnen tunen want dan krijgen ze de melding dat de tunes niet overeenkomen met de server

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

De auto uit de cardealer nieuw doet het allemaal prima, de overgezette versies dus de oude rs6 2020 moet gewoon te tunen zijn

**Screenshots en/of logbestanden**

https://media.discordapp.net/attachments/723219042696953897/902014759510114325/Schermafbeelding_2021-10-25_040420.png?width=1226&height=676

**Impact op de server**

**Comment by niekschoemaker** [comment]
Heb je toevallig een kenteken van eentje die niet werkt?

**Comment by niekschoemaker** [comment]
Ik kan in de sentry logs niks meer vinden van dit voertuig dus het lijkt gefixed te zijn.
