### ISSUE TITLE
HRB G-Wagon   Ticket 3073

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#826]
Goedemiddag,

Ik maak deze Github aan omdat nu alles nog via een ticket loopt en dit makkelijker is om in te zien.

Er is een HRB G-Wagon en deze zouden we graag zien in de stad.
 
**Wat gaat die verbeteren?**
De realisme voor de HRB wordt hier zeer mee vergroot. Tevens zullen zei dan ook beschikken over een dienstvoertuig.
Momenteel is er ook te weinig geld om genoeg dienst auto's te kopen.

Nu weet ik dat er een HRB G-wagon klaar zou staan om in de stad gezet te gaan worden.

Zouden jullie hier eens naar kunnen kijken wat hier in mogelijk is. 
Men is al aan het wachten in Ticket 3073 sinds Maart.

Ik hoop jullie hiermee voldoende te hebben geïnformeerd.
Mochten er toch vragen zijn zie ik deze tegenmoet.

**Comment by walvisgedaan** [comment]
Zit er na de restart in
