### ISSUE TITLE
Voertuigen bugged

### ISSUE THREAD

**Issue by Gesja** [Tedeapolis/development#83]
voornamelijk is dit het geval bij de offroad voertuigen, als je offroad rijd dat hij gelimit op 80km/h of lager is en dat die opeens heel slecht offroad rijd. De Mercedes 6x6 AMG is hier een voorbeeld van, wat ik hoor is dat je moet reloggen om dit te fixen maar ik heb dat gedaan en hij werkte weer voor 10 minuten ongeveer en toen begon die weer met de rare handeling. Als ik hiermee kan helpen hoor ik het graag.

**Comment by niekschoemaker** [comment]
Heb je hier toevallig een log bestand of iets dergelijks van? Ik zie de issues hier en daar wel in Sentry maar ben even een specifiek voorbeeld nodig met log bestand.

**Comment by Gesja** [comment]
[CitizenFX_log_2020-08-10T000456.log](https://github.com/Tedeapolis/development/files/5048695/CitizenFX_log_2020-08-10T000456.log)
