### ISSUE TITLE
Ambulance F6 Verklaardood

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#831]
**Beschrijf zo duidelijk mogelijk de feature**
Een ja nee optie in de 'Verklaardood' label van de ambulance.

**Wat lost deze feature op?**
De keuze om nog terug te gaan als je per ongeluk mis klikt.

# Voorbeeld
**Weet je het zeker dat je {ID} wilt doodverklaren?**
* Ja
* Nee

**Comment by Ljosfari** [comment]
Is aangepast
