### ISSUE TITLE
Inchecken balie ambulance

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#832]
**Beschrijf zo duidelijk mogelijk de feature**
Een annuleer optie bij het inchecken.

**Wat lost deze feature op?**
Soms klik je per ongeluk (als ziekenhuisdienst, ambulance of burger) op G als je naast de balie staat en je kan het dan niet annuleren. Dit zorgt ervoor dat je een lange tijd moet wachten en dat is vervelend als het niet de bedoeling was om in te checken.

**Comment by Willem-Dekker** [comment]
zit er na restart in
