### ISSUE TITLE
Onduty command toevoeging

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#833]
**Beschrijf zo duidelijk mogelijk de feature**
Dat er bij de /onduty command naast ID en Steam naam ook Karakter namen worden weergeven.

Dit staat er atm.
![image](https://user-images.githubusercontent.com/61888104/139460115-b5bffca8-e401-4ae8-8ff2-593691ec2a01.png)

**Wat lost deze feature op?**
Het makkelijker aflezen voor teamleiders/bazen wie in dienst zijn.

**Comment by Chang-nl** [comment]
Dit is geregeld na eerstvolgende restart!
