### ISSUE TITLE
/setjob ook kunnen gebruiken om mensen uitdienst te zetten.

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#836]
**Beschrijf zo duidelijk mogelijk de feature**
Het gebeurd met enige regelmaat dat een werknemer geforceerd uit zijn werk wordt gehaald en daardoor lang niet aan het werk is. Momenteel kunnen we /setjob gebruiken alleen voor indienst rangen maar niet voor uitdienst.

**Wat lost deze feature op?**
Verminderd kan / zelfstandig oplossen in moneyfarm situaties (intern in een overheidsbedrijf).
Kan mensen uitdienst zetten als zei bijvoorbeeld aangehouden zijn tijdens hun dienst of niet reageren in de portofoon.

**Comment by Willem-Dekker** [comment]
limit alleen op baan baas

**Comment by TedeaTaxi** [comment]
Is geimplementeerd
