### ISSUE TITLE
F6 Zorgverzekering

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#837]
**Beschrijf zo duidelijk mogelijk de feature**
Dat het F6 menu niet word afgesloten als je uit de categorie 'Zorgverzekering' komt.
https://youtu.be/u8YPHwuw4Ms

**Wat lost deze feature op?**
Het makkelijker maken om van de categorie Zorgverzekering naar categorie Factuur te gaan.
(Bij de categorie Factuur is dit al het geval).

**Comment by niekschoemaker** [comment]
Zit erin, heb ook gelijk het combatlog automatisch uitvoeren toegevoegd.
