### ISSUE TITLE
Abseilen helikopter nogsteeds kapot

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#838]
**Omschrijf de bug**
Laatst zou het gefixed moeten zijn dat je kan abseilen uit een helikopter. Dit werkt helaas nog niet momenteel.
Wanneer je in een helikopter zit en op X drukt geeft hij aan dat je over 2 seconden gaat abseilen waarna het direct wordt geannuleerd. Zie foto.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Als bijrijder meegaan in een helikopter, op x drukken om te abseilen. Je zult de meldingen zien.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
![image](https://user-images.githubusercontent.com/72617118/139558465-eb1a6a44-3fd7-416e-b0a7-be171ec86860.png)

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je na 2 seconden moeten abseilen en zou het niet geannuleerd moeten worden.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/72617118/139558478-23b44719-0ef7-4c3d-b97d-d9fbd0075568.png)

**Impact op de server**
Zorgt ervoor dat mensen constant moeten landen om uit te stappen, terwijl rappelen voor leuke situaties kan zorgen

**Comment by Mikajac** [comment]
Ditzelfde gebeurt ook bij een Maverick. Ik had al geregeerd op mijn originele post, maar ik gok dat dat gemist is omdat deze al gesloten was.

**Comment by Mikajac** [comment]
![image](https://user-images.githubusercontent.com/20951687/139615241-de30c4dd-ee20-4a3a-951b-c823f8056b49.png)
Zojuist nog iemand even laten testen, zijn hele FiveM is er door gecrasht. Onbekend is of dit toeval is of daadwerkelijk door het abseilen komt.

**Comment by Willem-Dekker** [comment]
komt er iets in logs te staan?

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn na volgende restart

**Comment by MisterM02** [comment]
Nieuw probleem. Wanneer je op X drukt loopt de hele game vast waarna fivem afsuit. Ik krijg geen crash message en in de logs is ook niks geks te zien.

![image](https://user-images.githubusercontent.com/72617118/140000504-fb4154b7-aac7-4933-bfbb-e5b473e308b0.png)

**Comment by Willem-Dekker** [comment]
dit zou fixed moeten zijn
