### ISSUE TITLE
De tijd van de telefoon staat nog een uur naar voor

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#839]
**Omschrijf de bug**
de tijd van de telefoon staat nog een uur naar voor

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

-
**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

-
**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

-
**Screenshots en/of logbestanden**

![image](https://user-images.githubusercontent.com/89384945/139651182-5a7609c3-aa17-4fc7-90a1-ecb5955c3e48.png)

**Impact op de server**
Ander kom je te laat XD

**Comment by Willem-Dekker** [comment]
is geen issue meer
