### ISSUE TITLE
G-Wagon snelheid

### ISSUE THREAD

**Issue by Streamcentralrulez** [Tedeapolis/development#840]
[//]: # (Dit type regels kun je gewoon weghalen, is puur uitleg)

**Label van voertuig**
HRB GWAGON

[//]: # (Zoals weergegeven in voertuig winkel/garage)

**Spawnnaam van voertuig**
NULL in voertuigdealer <- wellicht ook aanpassen

[//]: # (Wat je gebruikt /car om het in te spawnen)

**Kenteken van voertuig (wanneer van toepassing)**

[//]: # (Als het om een specifiek voertuig gaat dit graag invullen)

**Omschrijf de bug**

[//]: # (Duidelijke omschrijving van wat er precies gebeurd)
Hij rijdt te traag.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

[//]: # (Welke hele specifieke stappen moeten we volgen om dit betrouwbaar te kunnen hercreeëren)
Rijden (Zowel offroad en zandpaden)

**Normaal gedrag**

[//]: # (Wat is het verwachte gedrag, wat zou er normaal moeten gebeuren)
Hij zou dus on-road 297 kmh en op de offroad 140kmh

**Screenshots en/of logbestanden**

[//]: # (Wanneer van toepassingen graag logbestanden en screenshots toevoegen)
Geen

**Impact op de server**
HRB rijdt nu veel trager dan andere mensen in de stad.

**Comment by Streamcentralrulez** [comment]
Aanvulling op basis van gesprek met WhaleDone.

Voertuig krijgt nog steeds snelheidsboetes graag gelijk trekken met andere politie voertuigen.
Voertuig heeft geen snelheidsmeter/kenteken scanner (CTRL+M) graag ook toevoegen.

**Comment by Ljosfari** [comment]
gclas9 = spawnnaam

**Comment by niekschoemaker** [comment]
Alle dingen die aangekaart zijn lijken gefixed te zijn
