### ISSUE TITLE
Ambulance in/uit dienst cirkel in sandy shores

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#841]
**Beschrijf zo duidelijk mogelijk de feature**
Een in/uit dienst cirkel voor de ambulance in sandy shores

Eventuele locatie:
COORDS: X: 1837.23 Y: 3695.02 Z: 33.27 H: 22.56
![image](https://user-images.githubusercontent.com/61888104/139705297-6e38922b-937b-4c4f-bac7-b013c73fe61b.png)
(Locatie conflict niet met politie cirkels)

**Wat lost deze feature op?**
Als mensen snel uitdienst moeten kunnen ze daar ook uit/in dienst gaan. Deze plek word namelijk veel gebruikt door collega's omdat er ook een ambulance opslag zit en een voertuigen opslag.

**Comment by krizz696** [comment]
niet overlegd met krikke , die niet akkoord gaat vanwege geen controle .
