### ISSUE TITLE
EUP vrouwen KMAR  Ticket 34333

### ISSUE THREAD

**Issue by Chrushers** [Tedeapolis/development#842]
# Waar zit het in EUP, interiors of retextures ?
Retextures

# Link naar issue of coördinaten naar de plek
Vrouwen EUP Kmar

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Er zitten geen fouten in. Als het goed is heeft Wahledone dit al met een collega besproken.

# Wat is de toegevoegde waarde?
Meer kleding voor vrouwen bij de KMAR. Momenteel niet veel andere kleding waardoor ze niet aansluiten met de rest.

![image](https://user-images.githubusercontent.com/90619128/139726945-f1e4034f-5caa-4ae4-9e4f-16eb285bdd08.png)

![image](https://user-images.githubusercontent.com/90619128/139727005-2f5c8475-f6fb-4267-8720-9d8f4a026d04.png)

**Comment by Chang-nl** [comment]
Er zijn ondertussen flink wat aanpassingen gedaan aan de eup, is dit niet onderhand al toegevoegd?

**Comment by Jaydpn** [comment]
> Er zijn ondertussen flink wat aanpassingen gedaan aan de eup, is dit niet onderhand al toegevoegd?

Nee de vrouwelijke KMar outfits zijn bijna niet aangepast naast taser holster. Naar mijn weten.

**Comment by Chang-nl** [comment]
@walvisgedaan staan er nog nieuwe vrouwelijke kledij voor de kmar op de planning?

**Comment by walvisgedaan** [comment]
Er zit nieuw vrouwen kleding in de EUP met rangonderscheiding.
