### ISSUE TITLE
/onduty uit dienst kunnen gebruiken

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#843]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel kun je alleen de /onduty command gebruiken als je zelf ook in dienst bent, maar soms kan het handig zijn om deze ook uit dienst te kunnen gebruiken wanneer je wilt checken wie er allemaal ingeklokt staan.

**Wat lost deze feature op?**
Dat je niet helemaal naar HB hoeft om in te klokken om te checken wie er in dienst staan.

**Comment by Willem-Dekker** [comment]
denk niet dat dit een wenselijke aanpassing is.

**Comment by ARJ3N** [comment]
@Willem-Dekker waarom niet? Is enkel dan voor de boss job zodat diegenen ook uit dienst kunnen checken wie er indienst geklokt staan. Wat is het bezwaar hiertegen? :)

**Comment by Willem-Dekker** [comment]
Dat dit een indienst bezigheid is en niet uit dienst

**Comment by ARJ3N** [comment]
Voorbeeldje: ik rij uitdienst rond, zie dat er een bankoverval gestart wordt maar ik zie maar twee mensen in dienst. Dan zou ik graag /onduty willen gebruiken om te kunnen checken wie er op dat moment ingeklokt staat maar niet in dienst is. Op dit moment zou ik dan dus naar HB moeten om in te klokken omdat dan pas de command werkt. Daarom zou het naar mijn mening fijn zijn als het ook uitdienst kan. Misschien dat ik iets mis maar voor zover ik weet kan dit niet misbruikt worden ofzoiets. @Willem-Dekker

**Comment by Chang-nl** [comment]
Na restart gefixt!
