### ISSUE TITLE
Schietmeldingen werken niet [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#845]
**Omschrijf de bug**
Er is vanmiddag/vanavond erg veel geschoten maar er is geen enkele schietmelding binnengekomen. Hierdoor vermoeden wij dus dat er iets niet klopt waardoor deze meldingen niet meer weergegeven worden.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In dienst gaan en iemand anders laten schieten. Dan zul je zien dat er geen melding binnenkomt.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
N.v.t.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken hoor je een schietmelding te ontvangen.

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Dit heeft een grote impact op de politie, aangezien er nu veel minder goed gehandhaafd kan worden op schietincidenten.

**Comment by MisterM02** [comment]
Voor de politie werkt het inmiddels, alleen voor de rangen van kmar nog niet

**Comment by niekschoemaker** [comment]
Opgelost
