### ISSUE TITLE
Klok rechtsboven je scherm klopt niet [Lage prio] [BUG]

### ISSUE THREAD

**Issue by AdventurePandah** [Tedeapolis/development#846]
**Omschrijf de bug**
Aangezien het wintertijd is, is de klok een uur terug gezet. Dit moet ook nog gebeuren met de datetime die rechtsboven je scherm staat.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Nvt

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Nvt

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Nvt

**Screenshots en/of logbestanden**
Nvt

**Impact op de server**
Weinig. Heeft lage prioriteit.

**Comment by Willem-Dekker** [comment]
fixed
