### ISSUE TITLE
Vissers boot niet kunnen opslaan ( Rode cirkel ) 

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#848]
**Omschrijf de bug**
Boot niet kunnen  opslaan in de rode cirkel.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Niet iedereen heeft dit probleem.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
-

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
-

**Screenshots en/of logbestanden**

![image](https://user-images.githubusercontent.com/89384945/140481588-62227802-fd4a-4ea4-a7fb-51c29e7907c7.png)
![image](https://user-images.githubusercontent.com/89384945/140481601-682cbbbe-be5f-467a-95fb-bde3a26eb7e0.png)
![image](https://user-images.githubusercontent.com/89384945/140481613-349da774-a8f0-47d0-93d3-d07ddfbba1f4.png)

**Impact op de server**
Niet kunnen grinden :P

**Comment by niekschoemaker** [comment]
Ik denk dat dit morgen gefixed is maar weet het niet zeker
