### ISSUE TITLE
[BUG] Rode cirkel krijgen in taakstraf gebied

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#849]
**Omschrijf de bug**
Rode cirkel krijgen in taakstraf gebied

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Dood gaan daar

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
-

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Geen rode cirkel krijgen

**Screenshots en/of logbestanden**
https://medal.tv/clips/70430475/d1337VAZraU8?invite=cr-MSxNTTUsMjAxMTcwMTcs
**Impact op de server**
Dat mensen onbeperkt veel taakstraf krijgen als zij daar dood gaan

**Comment by Willem-Dekker** [comment]
zou gefixed moeten zijn ander graag nieuwe openen
