### ISSUE TITLE
Witwaslocatie bij inloggen

### ISSUE THREAD

**Issue by RonaldDaquila** [Tedeapolis/development#850]
**Omschrijf de bug**
Wanneer je uitlogt met minimaal 40.000,- zwartgeld en vervolgens weer inlogt, krijg je gelijk een witwaslocatie. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
n.v.t.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
n.v.t.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zou je de locatie niet op de map moeten zien en pas wanneer je begint met een witwasronde.

**Screenshots en/of logbestanden**
https://youtu.be/NBJCSsF1lG0

**Impact op de server**
Vooral erg vervelend om die locatie telkens op je map te hebben en er niks tegen kunnen doen.

**Comment by MisterM02** [comment]
Dit probleem is nogsteeds.

**Comment by Willem-Dekker** [comment]
zou gefixed moeten zijn
