### ISSUE TITLE
Verkopen van gekochte huizen 20% van het aankoop bedrag vergoeden

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#852]
**Beschrijf zo duidelijk mogelijk de feature**

Als je nu een huis koopt in de stad, krijg je niets meer terug als je hem weer verkoopt... als het mogelijk is dit aan te passen dat iemand die een huis verkoopt 20% van het aankoop bedrag vergoed krijgt!

**Wat lost deze feature op?**

Er zijn nu veel klachten op gebied van dat ze niets terug krijgen, en dit lost dat op zodat ze toch het gevoel hebben dat ze iets ervan terug krijgen!

**Comment by Willem-Dekker** [comment]
duplicate van #835
