### ISSUE TITLE
In dienst flitsboetes [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#853]
**Omschrijf de bug**
Momenteel krijgen de politie/kmar nogsteeds flitboetes op een aantal van de flitspalen in de stad. Om een paar voorbeelden van deze flitspalen te noemen die nog werken op mensen die in dienst zijn: Blokkenpark (die is met opzet gedaan als het goed is), oude taxi, oude ANWB & Mazebank.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In dienst klokken op job Agent, rondrijden in een dienstvoertuig en dan langs bovengenoemde flitspalen rijden.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
N.v.t.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zouden deze flitspalen je niet moeten flitsen in dienst.

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Wij krijgen erg veel klachten van agenten die flitsboetes krijgen in dienst. Dit is erg vervelend in achtervolgingen waarbij je meerdere keren langs deze filtspalen kan rijden waardoor het uiteindelijk best veel geld kan kosten per achtervolging. Daarom zouden wij graag willen dat wij ook op deze locaties geen flitsboetes meer ontvangen.

**Comment by Willem-Dekker** [comment]
is geen bug, op die palen zit een margen waar je max boven mag zitten

**Comment by Willem-Dekker** [comment]
wel raar dat hier nu pas klachten over komen zit er al meer dan 1 jaar in

**Comment by PolitieTDA** [comment]
@Willem-Dekker vroeger waren dat hotspots, tegenwoordig niet meer omdat de ANWB/Taxi verplaatst zijn. Vandaar dat het mij persoonlijk ook niet nodig lijkt om deze genoemde flitspalen nog zo ingesteld te hebben voor de in dienst eenheden.

**Comment by Willem-Dekker** [comment]
omdat we niet willen dat ze daar als totale malloten op max speed over heen schieten
