### ISSUE TITLE
[BUG] Uit first-person kunnen gaan met vliegen

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#854]
**Omschrijf de bug**
je kan uit first-person als je aan het vliegen bent

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
vlien en op `c` drukken en op je heen kijken
uit de gang opslag pakken

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
je kijkt om je heen

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Niet uit first-person gaan

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/16556575/140748479-6d98b719-0886-45e0-b5ef-668e111372cb.png)

**Impact op de server**
Veel mensen die het misbruiken

**Comment by niekschoemaker** [comment]
Fixed, heb de C toets geblokkeerd en de issue met biker opslag kan ik niet reproducen.
