### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaanVr2** [Tedeapolis/development#855]
**Omschrijf de bug**

Mensen kunnen praten in het deepweb kanaal van de witwas typen dus mensen praten er nu constant in 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

In het deepweb kanaal "witwas" gaan en er iets typen

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Dat je hier niet kan praten omdat het voor een plugin is 

**Screenshots en/of logbestanden**

![image](https://user-images.githubusercontent.com/90869210/140764304-e3ab6496-0d1e-43ab-ae17-8d70c036db71.png)

**Impact op de server**

Hinder bij het witwassen / witwassers overvallen

**Comment by Willem-Dekker** [comment]
fixed
