### ISSUE TITLE
Autoverhuur script

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#858]
**Beschrijf zo duidelijk mogelijk de feature**
Graag zouden wij een script/command zien om onze privé auto's of op een andere (niet privé auto's) te verhuren. Als we onze privé auto's verhuren is dat met risico op boetes/in beslagname / mensen die auto's expres kapot rijden.

**Wat lost deze feature op?**
Meer professionaliteit in het verhuren van auto's, minder problemen met boetes, kapotte auto's en in beslaggenomen auto's.

**Comment by Hellie94** [comment]
Je bent een taxibedrijf, geen verhuurbedrijf?

**Comment by TedeaTaxi** [comment]
> Je bent een taxibedrijf, geen verhuurbedrijf?

Op onze voorgeven staat dat wij autos verhuren, en binnen hebben we een kleine showroom met een prijs. Kom een keertje langs ;p

**Comment by Hellie94** [comment]
Dat is mooi, maar dan moet je gewoon een contract opstellen of laten opstellen.
Dat tegen een borg of iets dergelijks, met ontbindende voorwaarden etc.
