### ISSUE TITLE
[BUG] zwart geld zichtbaar als er geen zwart geld is

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#859]
**Omschrijf de bug**
zwartgeld zichtbaar als je het niet 0 hebt 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
zwart geld staat soms op 0 als je het niet hebt maar kan het dan ook verborgen worden ?

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
geen zwart geld in beeld

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/93401910/141386932-5cf269fa-f0b3-40f8-a84f-4c9077661f18.png)

**Impact op de server**
stukje opschonen

**Comment by Willem-Dekker** [comment]
welk menu?

**Comment by Willem-Dekker** [comment]
fixed na restart
