### ISSUE TITLE
[BUG] [TEST SERVER] Crash bij het plaatsen van een boot op een aanhanger.

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#862]
Vanuit een Server Supporter Suggestie:
**Omschrijf de bug**
Als ik een auto en een boot trailer pak en een boot op de trailer plaats, dan heb ik continue een crash.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Hetzelfde dus ook een auto pakken, ik had een raptor en een trailer. Als je dan de trailer in het water rijden en dan de boot er opzet, crash je.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Zie foto bij screenshot. Crash is wat er gebeurde.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Geen crash als je gebruik maakt van deze functie maar gewoon mijn mooie boot op de aanhanger.

**Screenshots en/of logbestanden**
![afbeelding](https://user-images.githubusercontent.com/69365961/141624818-3f436a83-ed41-4f53-a2fc-84df1e49d11b.png)

**Impact op de server**
Geen, het is de test server en heeft geen haast.

**Comment by Willem-Dekker** [comment]
is dit alleen bij test? en niet op main?

**Comment by Attomn** [comment]
Als ik het zo, net hoor blijkbaar op beiden servers en dit zou ook bij sleepwagens van de politie en de normale sleepwagen die beschikbaar is voor spelers zijn. Dit zou al door de motorclub doorgegeven zijn, 2 maanden terug maar wat daarvan klopt geen idee.

**Comment by Willem-Dekker** [comment]
kan je log bestanden vragen?

**Comment by Attomn** [comment]
Ik heb ze zojuist aangevraagd, zodra ik reactie heb ontvang je ze meteen.

**Comment by Willem-Dekker** [comment]
ik ga er vanuit dat dit geen issue meer is
