### ISSUE TITLE
[BUG] Damage bij wapens aan de vage kant

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#863]
**Omschrijf de bug**
De laatste tijd valt het erg op dat er soms vage combatlogs ontstaan met betrekking tot het geraakt zijn door wapens e.d.
Denk hierbij aan headshots die maar 30 damage doen, schoten in het been waar je maximaal 10 damage door verliest en ga zo maar door. Enkele voorbeelden en vage combatlogs zijn te zien in de toegevoegde afbeeldingen. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Eens flink gaan schieten tegen andere personen en hierna kijken wat voor impact dit heeft op de damage die een persoon krijgt.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Mensen verliezen weinig damage bij kogelwonden die juist dodelijk zijn.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De damage zou realistischer moeten zijn.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/72617118/141695322-69a4f0a3-f6c9-4e38-8650-ed683acaab4d.png)
![image](https://user-images.githubusercontent.com/72617118/141695327-892d43df-6a2e-45cb-b5b8-0a65b9968892.png)
![image](https://user-images.githubusercontent.com/72617118/141695331-7cb73c08-e692-42b9-aa6f-83f69c0f71ae.png)
![image](https://user-images.githubusercontent.com/72617118/141695343-1d97d1cc-850c-461c-a468-3e4570109ee4.png)
![image](https://user-images.githubusercontent.com/72617118/141695351-379732f9-7b92-467e-92fc-6f10c81eca8e.png)
![image](https://user-images.githubusercontent.com/72617118/141695356-31aa0c6e-3c7f-4f9a-aa74-7eafb6dddbda.png)

Voorbeelden van criminele wapens volgen nog
**Impact op de server**
Het geeft rare beelden wanneer iemand een schot in het hoofd overleefd. Gezien persoon eigenlijk gewoon hartstikke dood moet zijn.

**Comment by niekschoemaker** [comment]
@MisterM02 Zou je hier aub zelf wat testing voor kunnen doen? "Vage damage" is voor ons lang niet genoeg informatie, er is iets wat dit veroorzaakt en waaarschijnlijk is dit simpelweg de afstand.

De damage in het hoofd heb ik al wel gefixed, dit komt omdat iemand een helm op heeft want GTA, dus ik kill iemand handmatig met een plugin als je hem in het hoofd raakt, maar carbinerifle stond niet in dit systeem.

**Comment by walvisgedaan** [comment]
**Ongeveer 20 meter**
AK doet (onder de zelfde omstandigheden) 47 damage
HK doet (onder de zelfde omstandigheden) 14 damage
Dat is echt een enorm verschil.
![image](https://user-images.githubusercontent.com/69094685/149676717-7e10e8c5-459f-47b9-a78a-f46fbd735a22.png)
Even als vergelijking, een combat pistol (9mm handvuurwapen) doet op dezelfde afstand 38 damage.
![image](https://user-images.githubusercontent.com/69094685/149676728-ab0bf373-8b20-46d8-bb6b-f87df98e31e8.png)
Dus die verhouding gaan niet op.

**Ongeveer 75 meter**
AK doet (onder de zelfde omstandigheden) 34damage
HK doet (onder de zelfde omstandigheden) 10 damage

Die AK doet dus gewoon 3x zoveel damage als een HK.
![image](https://user-images.githubusercontent.com/69094685/149676736-6467034a-37ab-41dd-a15e-d709f8c24f9e.png)
En dan opnieuw de vergelijking met een combat pistol. Op 75 meter doet die 12 damage, dat is dus meer dan de HK wat een veel groter kaliber is!
![image](https://user-images.githubusercontent.com/69094685/149676740-5e46c68d-c932-4712-8f7c-6304646fbd79.png)
Opnieuw doet de AK ruim 3x zoveel damage onder dezelfde omstandigheden.
![image](https://user-images.githubusercontent.com/69094685/149676754-8d449d2a-abd5-49bb-88c8-395eca779198.png)

**Comment by niekschoemaker** [comment]
Is gefixed, LimbDamageModifier stond verkeerd voor de HK416
