### ISSUE TITLE
Werkvoertuigkofferbakken

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#864]
**Beschrijf zo duidelijk mogelijk de feature**

Deze enkel toegankelijk maken voor de eigenaar van het voertuig. Daarnaast blokkeren dat er anderen voorwerpen dan werkartikelen in kunnen. 
**Wat lost deze feature op?**
Heel veel diefstal tickets van spelers die onwetend zijn.

**Comment by niekschoemaker** [comment]
Zit erin
