### ISSUE TITLE
Lopen met handboeien om

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#865]
**Via agenda punten is een stemming geweest over de handboeien, nu is er een meerderheid geweest om dit aan te passen naar het wel kunnen lopen met handboeien om. Maar dan wel dat het sprinten niet kan.**

**Dat er gekeken wordt naar het lopen met handboeien, niet sprinten maar alleen kunnen lopen**

**Comment by brothasx** [comment]
Is na restart gefixed. Heb  ik helemaal alleen gedaan
