### ISSUE TITLE
vrouwen kleding slager klopt niet.

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#866]
# Waar zit het in EUP, interiors of retextures ?
De vrouwn kleding van slager.

# Link naar issue of coördinaten naar de plek
https://prnt.sc/1znn9g6 Hier in kan je ook al gelijk zien dat er dingen niet kloppen.

# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Het bovenste gedeelte van de armen worden niet zichtbaar. waarscheinlijk is het gewoon een kopen Armen issue.

# Wat is de toegevoegde waarde?
het ziet er weer fatsoenlijk uit :D

**Comment by brothasx** [comment]
Deze is al gefixed
