### ISSUE TITLE
Amarok/Offroad handeling verbeteren voor ANWB, KMAR & Politie

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#868]
**Label van voertuig**
ANWB Offroad, Marachaussee Amarok en Politie Amarok

**Spawnnaam van voertuig**
/car pamarok
/car kamarok
Ik kan die spawnnaam van ANWB offroad niet echt vinden.

**Omschrijf de bug**
Handeling werkt niet zoals verwacht, volgens burgerraad is hij te langzaam en/of de grip is niet goed afgesteld.

**Screenshots en/of logbestanden**
https://medal.tv/games/gta-v/clips/71586059/d1337wk0Xzxb?invite=cr-MSxOQXIsMTUwODQwODQs
https://medal.tv/games/gta-v/clips/71586196/d133723972Le?invite=cr-MSxqelAsMTUwODQwODQs

**Impact op de server**
Best zwaar, het beperk ANWBers om moeilijke locaties te bereiken en de politie/kmar zullen er ook vast last van hebben
bij offroad achtervolgingen.

**Comment by walvisgedaan** [comment]
De amarok van de politie en de kmar hebben dezelfde handling. Ik zal kijken wat er met die ANWB offroad is

**Comment by Willem-Dekker** [comment]
heb de politie handling en kmar handeling gelijk getrokken / aan elkaar gelinkt

**Comment by rubenTomassen** [comment]
en die van de ANWB?
