### ISSUE TITLE
Aanpassing duratie zuurtstof van zuurstoffles kleding/rebreather (burgerraad)

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#869]
**Beschrijf zo duidelijk mogelijk de feature**
Op het moment kunnen mensen een half uur onder water blijven, dit wordt soms misbruikt
en er is bij burgerraad besproken dat dit beter aangepast kan worden naar 5 a 10 minuten.
(bij voorkeur 10 minuten).

Ook was er besproken dat er een mogelijkheid is om niet direct nadat je boven water komt weer
volledig zuurstof te hebben maar dat hij langzaam aanvult voor je nieuwe duik. Dit zou een
extra feature kunnen zijn. 

Dit zou ook weer handig zijn omdat anders mensen gewoon 1 seconde naar boven komen en gelijk weer duiken.
Dit zou het issue dan ook niet volledig oplossen wanneer dit zo zou zijn.

**Comment by Chang-nl** [comment]
in principe kunnen mensen nu 10 minuten onder water blijven met een zuurstoffles, voor het langzaam aanvullen van de zuurstof komt er later nog een oplossing.

**Comment by Chang-nl** [comment]
Na alle research gedaan te hebben is er op dit moment geen manier om hetgeen met de zuurstof langzaam te laten refillen.
