### ISSUE TITLE
Melding KMAR bij unjailen speler

### ISSUE THREAD

**Issue by RyanBoersma** [Tedeapolis/development#870]
Verzoek vanuit de burgerraad om een melding naar de politie/kmar (vooral KMAR) te maken met de naam van de persoon die unjailed door staff is.
Dit zodat zij een signalering op die naam kunnen gooien en/of zelf beter weter wie er nu ontsnapt is omdat dit nu vaak onduidelijk is met alleen gebruik van de lijst.

Voorbeeld hiervan (vanuit staffoverleg) was om een extra parameter toe te voegen aan het /unjail command (bijvoorbeeld yes/no) om wel of niet een melding te maken van de uitbraak inclusief naam.

**Comment by Chang-nl** [comment]
zit dit er niet ondertussen al in?
