### ISSUE TITLE
offroad taxi

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#871]
-Naam: Said B
Taxi Suggestienummer: 73
Waarom: off-road Taxi
Suggestie: dan kunnen we off-road rijden en daar ook klanten ophalen vaak gestrande bergings mensen en gecrashte auto's

Graag zien we een auto of toestemming om met taxi voertuigen offroad te mogen rijden om gestrande mensen op te halen waar de wegen niet zijn gebeurd vaak dat er dus mensen ver van de weg staan waar wij nu niet kunnen komen 

Hoe:
evt meer grip voor de taxi auto's zo dat offroad mogelijk is
of
een offroad auto die we kunnen gebruiken

**Comment by Ljosfari** [comment]
de 'off-road' waardes van de taxi voertuigen zijn wat aangepast
