### ISSUE TITLE
taxi bordje 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#872]
-Naam: Julian.N
Suggestienummer: 74
Waarom:  ziet er mooi uit en is duidelijker (net als politie alleen dan geen zwaailamp maar taxi bord)
Suggestie: taxi bord op de auto als uber (was ooit besproken dat dit zou komen niks meer van gehoord)

Taxi bordje op de auto plaatsen 
toen we over gingen naar het nieuwe kantoor pand waar we heel blij mee zijn
werd er gesproken over een taxi bordje op de auto we kregen te horen dat het wel kon maar geen prio had 
er was ook geen issue voor aangemaakt dus bij deze graag mogelijkheid om taxi bordje op een auto te kunnen zetten 

ik heb ook een plugin gevonden voor de politie evt kunne we dit omzetten naar taxi ?
https://www.youtube.com/watch?v=gw834BAuk7g&ab_channel=GtaVFivemandRageMpResources
https://forum.cfx.re/t/release-free-esx-kn-portable-light-bar-v2/4682631

ik zoek nog even verder

**Comment by brothasx** [comment]
Deze kan niet uitgevoerd worden,  te zwaar voor de server. Daarnaast zijn er allemaal voertuigen toegevoegd met taxi bordjer erop.
