### ISSUE TITLE
Aanpassing aan factuursysteem van Taxi

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#873]
## De reden
We willen bij Uberpolis medewerkers gemotiveerd houden en meer actie laten ondernemen met het oppakken van meldingen.

## De obstakels met de huidige situatie
1. Medewerkers pakken niet altijd snel genoeg meldingen op, omdat 'echte' ritjes geen geld verdienen en hersenlozen wel. Wij letten hier op en sturen mensen aan, maar dat werkt niet altijd goed genoeg.
2. Daarnaast is het taxi loon het laagste loon van de stad, waardoor mensen niet snel gemotiveerd blijven.

## De oorspronkelijke reden voor het uitzetten van betalingen
Er werd ooit misbruik gemaakt van het facturatiesysteem. Deze mensen hebben daar toentertijd een ban voor gekregen.

## De reden om weer iets soortgelijks te doen
Inmiddels hebben wij logging van facturen en uren, en hebben wij detectiesystemen op de taxi website gebouwd die misbruik makkelijker kunnen herkennen.

## De wijzigingen voor ogen
We hebben twee wijzigingen voor ogen:

Ten eerste, bij het sturen van facturen gaat 100% van het bedrag naar de chauffeur en 300% naar de taxi rekening, net als met hersenloze ritjes.

Ten tweede, we hebben een aantal aanpassing voor ogen in het F6 menu. De knoppen zouden dan als volgt zijn:

1. **Factuur naar dichtstbijzijnde persoon** -> Geen wijziging met het huidige gedrag.
2. **Factuur naar ID** -> Deze optie is voornamelijk voor als er meerdere mensen in de taxi zitten en heeft 3 subopties:
  - 100%
  - 50% -> Indien er twee mensen in de taxi zitten en ze de rekening willen splitsen.
  - Los bedrag tot max 2000 euro. -> Indien er meerdere mensen in de taxi zitten, of als er korting wordt gegeven op een ritje en dus niet het hele bedrag in rekening wordt gebracht. Ingrijpen bij misbruik is mogelijk ivm het logsysteem.
3. **Taxi meter resetten** -> Geen wijziging met het huidige gedrag.
4. **Taxi meter aanzetten** -> Voor als je geen taxi auto hebt, zoals ubers. Het moet nu via het `/taxi` menu, maar het kan beter in het F6 menu. Dit mag dan voor elke rang, omdat sommige medewerkers speciale toestemming krijgen om tijdens events etc met andere autos te rijden zoals limo's etc.
5. **start / stop taxi rit** -> Geen wijziging met het huidige gedrag.
6. **Conficeer taxi** -> Alleen voor recruiter, manager, chef rang.

**Comment by niekschoemaker** [comment]
Ik heb de taximeter in het F6 menu nu toegevoegd, alleen de rest is qua programmeer werk iets te veel.

Bijvoorbeeld splitten, ik heb persoonlijk zoiets van laat de mensen dat lekker onderling regelen als het zo'n probleem voor hun is.

**Comment by TedeaTaxi** [comment]
@niekschoemaker 

Los bedrag tot max 2000 euro. -> Indien er meerdere mensen in de taxi zitten, of als er korting wordt gegeven op een ritje en dus niet het hele bedrag in rekening wordt gebracht. Ingrijpen bij misbruik is mogelijk ivm het logsysteem.

Zou die dan nog wel kunnen zo dat we facturen kunnen met vaste bedragen of klanten korting geven
