### ISSUE TITLE
Rotatie/Nieuwe wapens voor criminelen

### ISSUE THREAD

**Issue by Ryvanoo** [Tedeapolis/development#874]
**Beschrijf zo duidelijk mogelijk de feature**
In de staff vergadering van14-11-2021 is er besproken een github aan te maken voor het volgende.

Nieuwe wapens toevoegen binnen de stad die om de wapen inkoop roteren. Voorbeeld: 
wapeninkoop 1: Cartel kan een mini ak kopen, icona een mini smg, tfft tommy gun, 14k machine pistol
Wapeninkoop 2: bij wapeninkoop 2 hetzelfde alleen wapens zijn verwisseld tussen de gangs.

Nieuwe wapens, Denk hierbij aan: Machine pistol, Tommy gun, revolver, assaultsmg.

**Wat lost deze feature op?**
Nieuwe wapens binnen TDA, Verwisseling van wapens. Mensen die bijvoorbeeld een mini ak willen, kunnen deze bijvoorbeeld alleen bij de ene groep kopen. aangezien niet iedereen dezelfde inkoop heeft gehad.

**Comment by niekschoemaker** [comment]
Voor zover ik weet is deze change niet geaccpeteerd, ik had alleen aangegeven dat ik de MK2 wapen ff kon toevoegen gezien deze klaar waren maar dat er geen rotatie zou komen.
