### ISSUE TITLE
[BUG] CBR vrachtwagen examen snelheids begrenzer werkt niet.

### ISSUE THREAD

**Issue by thoys** [Tedeapolis/development#875]
**Omschrijf de bug**
Snelheids begrenzer vrachtwagen les-vrachtauto werkt niet.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
1. Ga naar het CBR en doe het vrachtwagen rij-examen.
2. Versnel naar 80km/u en zet de begrenzer aan met Y.
3. Probeer nog harder te gaan rijden en zie dat je zelfs 90 kan rijden met de begrenzer aan op 80.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Bij het indrukken van de Y toets lijkt het of de begrenzer aan staat maar de vrachtwagen negeert deze.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De begrenzer zou gewoon moeten werken.

**Screenshots en/of logbestanden**
n.b.

**Impact op de server**
meer te hard rijdende les vrachtwagen's

**Comment by Willem-Dekker** [comment]
is dit bij alle vrachtwagens?

**Comment by thoys** [comment]
Dat durf ik niet zo te zeggen, de vrachtwagen voor electromonteur werkt goed.

**Comment by niekschoemaker** [comment]
Ik kon de achterliggende issue niet vinden, maar inderdaad de snelheidslimiet werkt niet bij de "mule3" specifiek.

Ik heb nu de snelheidslimiet wat aangepast zodat hij wel werkt en ook beter werkt dan eerst, dus nu houdt hij je gas tegen in plaats van de auto zelf zoals hij eerst werkte.

DUs is gefixed.
