### ISSUE TITLE
Alt + scroll zorgt ervoor dat zowel achterste stopbord als zoeklicht aangaat op SIV (A6) [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#876]
**Label van voertuig**
Audi A6

**Spawnnaam van voertuig**
/car police3

**Kenteken van voertuig (wanneer van toepassing)**
N.v.t.

**Omschrijf de bug**
Op dit moment zorgt de input van alt + scroll ervoor dat zowel het zoeklicht als het achterste stopbord van de SIV aangaan. Dit hoort normaal niet zo te zijn. Verzoek is daarom om de keybind van het stopbord te veranderen naar enkel scroll.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Stap in de SIV en doe alt + scroll.

**Normaal gedrag**
Normaal gesproken zou enkel het zoeklicht óf enkel het stopbord aan moeten gaan, maar niet beide tegelijk.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/93579695/142234623-176522ac-5b00-4a5b-b1d2-9d4c443e9bf2.png)
![image](https://user-images.githubusercontent.com/93579695/142234666-9e6bcc5f-d232-4740-8a14-8e958a55f0df.png)

**Impact op de server**
De impact valt natuurlijk mee, maar het is wel erg vervelend voor de mensen die op de SIV rijden.

**Comment by niekschoemaker** [comment]
Het gaat hier trouwens niet om het zoeklicht maar om de "scene lights" deze zijn dus om de scene te verlichten waar het voertuig staat.

Verder, hoe horen de controls te zijn? Ik neem aan scroll/. voor de stopborden en alt + scroll voor de scene light of zo?

**Comment by niekschoemaker** [comment]
Is gefixed.
