### ISSUE TITLE
[BUG] Taalfout deposeren -> deponeren

### ISSUE THREAD

**Issue by thoys** [Tedeapolis/development#878]
**Omschrijf de bug**
Taalfout in inventaris van voertuig

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Open voertuig inventaris met L

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Er staat `Deposeren` (gustavo is dat een Nederlands woord? Nee helaas, geen LINGO)

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Er zou iets als `Deponeren` moeten staan of `Spullen plaatsen`

**Screenshots en/of logbestanden**
/

**Impact op de server**
/

**Comment by niekschoemaker** [comment]
Heb het aangepast naar "Voorwerpen inladen" denk dat dat het meest correcte klinkt
