### ISSUE TITLE
Quicksell voor vliegtuigen, helikopters en boten - Staffoverleg 21-11-2021

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#879]
**Beschrijf zo duidelijk mogelijk de feature**
Besproken in het staffoverleg op 21-11-2021 is dat er een quicksell wordt toegevoegd voor vliegtuigen. helikopters en boten.
Denkende aan de quicksell voor vliegtuigen en helikopters op het vliegveld en voor boten in de haven.

Deze quicksell levert dan net als deze van de auto's enkel 50% van de nieuwwaarde op.

**Wat lost deze feature op?**
Mensen kunnen op een snelle wijze voertuigen verkopen voor een klein bedrag

**Comment by AnatolyMoskvin** [comment]
Locatie verkoop

X: -1659.30 Y: -3155.15 Z: 12.99

**Comment by Willem-Dekker** [comment]
zal als feature aan esx boat moeten worden toegevoegd

**Comment by AnatolyMoskvin** [comment]
> zal als feature aan esx boat moeten worden toegevoegd

Is dit mogelijk denk je ?
