### ISSUE TITLE
Aangepast ANWB sollicitatie formulier (kan dit worden aangepast?)

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#88]
Ingame naam:
Ingame 06 nummer:
E-mail-adres:
Discord naam (+ #0000):
Steam naam:
Je echte leeftijd:

Waarom solliciteer je specifiek voor de ANWB?

Wat zijn jouw drie sterkste eigenschappen?
Noem drie slechte eigenschappen van jezelf.
Hoe zou jouw beste vriend jou omschrijven?
Waarom zouden we juist jou aan moeten nemen bij de ANWB?

Hoe presteer jij onder tijdsdruk?
Met wat voor soort mensen werk jij het liefst samen?
Ben je een georganiseerd persoon? Waar zou dat wel of niet uit blijken?

Wat is jouw ervaring met RolePlay?
Heb je al eerdere ervaringen met het ANWB beroep?
Hoe zie jij jouw loopbaan binnen de ANWB?
Op welke manier hoop jij een waardevolle toevoeging te zijn voor de ANWB?

Hoeveel uur denk je per week aan de ANWB te willen besteden?

**Comment by Willem-Dekker** [comment]
staat nu live op de site
