### ISSUE TITLE
[BUG] Uitnodigen in appartementen werkt niet

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#880]
**Omschrijf de bug**
Als speler kun je mensen uitnodigen om in je huis te komen. Dit uitnodigen werkt echter niet naar toebehoren.
Wanneer je een persoon uitnodigt en deze persoon wilt jouw huis binnenkomen komt hij niet in het juiste huis terecht.
In plaats van in het huis van de "vriend" komt persoon namelijk in zijn eigen huis terecht.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Met twee personen naar een appartement gaan en elkaar uitnodigen naar binnen.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Je kwam in je eigen huis terecht

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je na uitnodiging in het huis van je "vriend" terecht moeten komen.

**Screenshots en/of logbestanden**
Volgens aangever is het rond 21:00 gebeurd
[CitizenFX_log_2021-11-21T195133.log](https://github.com/Tedeapolis/development/files/7584753/CitizenFX_log_2021-11-21T195133.log)

**Impact op de server**
Het is irritant gezien huiszoekingen niet goed lopen of je kan niet chillen in je huis etc.

**Comment by niekschoemaker** [comment]
Fixed
