### ISSUE TITLE
Nieuw steekwapen: Kapotte bierflesje in GTA

### ISSUE THREAD

**Issue by Attomn** [Tedeapolis/development#881]
**Beschrijf zo duidelijk mogelijk de feature**
Het toevoegen van een kapotte bierflesje in GTA, dit als steekwapen, als je deze hebt krijg je een dronken effect. Daarnaast moet het na 1x steken verdwijnen. Het doet minder damage als een mes.
Dit is besproken in staff overleg, ik moest een github issue aanmaken hiervoor.

![afbeelding](https://user-images.githubusercontent.com/69365961/143475451-68f55099-e0c8-4e70-820f-738e89fda702.png)

**Comment by niekschoemaker** [comment]
Minder damage als een mes is niet mogelijk, steekwapens zijn altijd insta kill.
