### ISSUE TITLE
Discord message links whitelisten op bot

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#882]
**Beschrijf zo duidelijk mogelijk de feature**
Discord message links toevoegen aan de whitelist van de Discord bot zodat deze niet verwijderd worden (bijvoorbeeld: https://discord.com/channels/).

**Wat lost deze feature op?**
Momenteel worden Discord message links door de bot verwijderd vanwege het ingebouwde filter. Nu zou het voor de politie/KMar handig zijn als wij wel message links zouden kunnen plaatsen i.v.m. makkelijk kunnen verwijzen naar bepaalde berichten in het bewijsmateriaal kanaal.
(Arjen)

**Comment by niekschoemaker** [comment]
Is gefixed
