### ISSUE TITLE
[BUG] Waypoint die blijft staan bij slager uitdienst

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#883]
**Omschrijf de bug**
Wanneer je bezig bent met de slagerjob en je jezelf omkleed terug in burgerkleding blijft de waypoint staan die je leidt naar het punt waar voertuigen gepakt kunnen worden. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Indienst gaan en even kort te baan uitvoeren om vervolgens weer uitdienst te gaan.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
De waypoint blijft staan en gaat pas weg als je relogt.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zouden alle waypoint weg moeten gaan als je uitdienst gaat

**Screenshots en/of logbestanden**
https://www.youtube.com/watch?v=pjhGf6moeug

**Impact op de server**
Is vervelend voor mensen die navigeren via waypoint en er nog eens extra zien

**Comment by niekschoemaker** [comment]
Ik kan hem zelf niet testen omdat het nogal specifiek is wat dit veroorzaakt (dus eerste keer een baan doen voor zover ik weet)

Maar als het goed is is dit na volgende restart gefixed.

**Comment by MisterM02** [comment]
![image](https://user-images.githubusercontent.com/72617118/144617563-c855dec5-162e-4cb1-8e1b-8aa09b41b154.png)
 
 Waypoint blijft nogsteeds staan na burgerkleding aan te hebben gedaan

**Comment by niekschoemaker** [comment]
Yes heb hem nu correct gefixed!-
