### ISSUE TITLE
Opslag kosten voor narcopolis

### ISSUE THREAD

**Issue by niekschoemaker** [Tedeapolis/development#885]
**Beschrijf zo duidelijk mogelijk de feature**
Opslag kosten net als main land voor voertuigopslag op narcopolis

**Wat lost deze feature op?**
Veel voertuigen met elke 10 drugs per stuk erin, dus meer drugs in 1 voertuig, meer risico

** To-do **

- [x] Quick sell op narcopolis
- [x] Mededeling hierover (om mensen er op voor te bereiden)

**Comment by Attomn** [comment]
Mededeling is gemaakt, mensen hebben tot 01-08 om hun voertuigen te fixen. Het gaat aan VANAF 01-08.

**Comment by Chang-nl** [comment]
Toegepast na herstart!
