### ISSUE TITLE
[BUG] Goudverkoop plaats in kantoor

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#889]
**Omschrijf de bug**
Verkoop plaats staat te hoog

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Mijnwerker doen

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
-

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
-

**Screenshots en/of logbestanden**
-

**Impact op de server**
Goud verkoop niet mogelijk

Moet verplaatst worden naar: 
![image](https://user-images.githubusercontent.com/77858957/143777634-69b5efe2-783f-44b1-be66-b8d647cec5ff.png)

**Comment by brothasx** [comment]
Is al fixed
