### ISSUE TITLE
[BUG] Flitspalen werken niet meer na restart (29-11-2021)

### ISSUE THREAD

**Issue by Ryvanoo** [Tedeapolis/development#891]
**Omschrijf de bug**
Alle flitspalen zijn verdwenen in de stad.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Door naar een flitspaal te rijden waar die oorspronkelijk stond.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Je krijgt geen boete, flitspaal zelf is ook weg.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou je een boete moeten krijgen, en zie je de flitspalen ook staan.

**Screenshots en/of logbestanden**
n.v.t

**Impact op de server**
Iedereen rijd 400+ op BP en andere plekken waar flitspalen staan.

**Comment by brothasx** [comment]
Flitspalen werken gewoon weer.
