### ISSUE TITLE
/speedlimit command werkt niet goed.

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#892]
**Omschrijf de bug**
Cruise control werkt niet goed, na activeren van een willekeurig getal pakt die automatisch de top speed van het voertuig.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

/speedlimit 80 in voeren als command
**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
-
**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
de snelheid die in je in command zet moet geactiveerd worden.
**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/89384945/143862639-6df7a3c6-f764-4c38-8136-ba6c6ca19461.png)
![image](https://user-images.githubusercontent.com/89384945/143862658-707ed12c-512b-4b18-ab3c-3c21945e7d0c.png)
![image](https://user-images.githubusercontent.com/89384945/143862674-3d1aea22-159b-47a3-a2c4-e2dcbfce8574.png)

**Impact op de server**
Zelf gas moeten geven XD

**Comment by niekschoemaker** [comment]
Is gefixed
