### ISSUE TITLE
[BUG] Ingame meldkamer politie kapot

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#893]
**Omschrijf de bug**
Momenteel is het zo dat sommige agenten wel meldingen / noodknoppen binnenkrijgen en andere niet. 
Dit is sinds de update van het ANPR systeem zo. 
Onbekend is wat het veroorzaakt.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Indienst gaan als politie en kijken of er meldingen binnenkomen. 

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Meldingen komen niet binnen. Geen gekke dingen te zien in F8

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal zou elke indienst agent meldingen / noodknoppen moeten binnenkrijgen

**Screenshots en/of logbestanden**
-

**Impact op de server**
Hoog, agenten moeten functioneren op basis van discord meldingen. Niet iedereen kan gebruik maken van een tweede scherm waardoor diensten draaien voor hen lastig is momenteel.

**Comment by MisterM02** [comment]
![image](https://user-images.githubusercontent.com/72617118/143906484-dcec28e3-07ee-4042-8ae4-a4e23d541338.png)

Het lijkt erop dat mensen die meldingen niet binnenkrijgen ingame ook een issue hebben in de meldkamer. Hun nummer wordt als "nil" neergezet.

**Comment by JohnnyFlodder** [comment]
In het algemeen is er een probleem met elke meldkamer, krijg meldingen in reports en tickets.

**Comment by MisterM02** [comment]
Is gefixed voor wat ik heb gemerkt / gehoord
