### ISSUE TITLE
Telefoon meldingen voor ambu/politie/taxi

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#894]
**Omschrijf de bug**

Telefoon meldingen komen niet binnen bij de overheden laatste meldingen vandaag 29-11-2021 kwamen er geen meldingen binnen bij de ambu!

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

normaal moeten overheden meldingen binnen krijgen om spelers te helpen

**Screenshots en/of logbestanden**

**Impact op de server**

overheden kunnen niets doen als de meldingen niet binnen komen

**Comment by DeStefanoKiller** [comment]
Dit probleem geldt ook voor ANWB. Bij de ANWB verschilt het per persoon dus de ene krijgt ze wel en de andere niet.
