### ISSUE TITLE
Onderzeeër op slot wanneer onderwater

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#895]
**Beschrijf zo duidelijk mogelijk de feature**
Onderzeeër op slot doen wanneer hij onder water is. Besproken in burgerraad:  Mensen die onderwater een onderzeeër ingaan en daardoor erin teleporteren. Op verzoek van Misstake even een githubje voor geopend.

**Wat lost deze feature op?**
Dat mensen niet deze GTA mechanic misbruiken door de onderzeeër onderwater te houden en onderwater er naartoe te zwemmen om zo erin te kunnen teleporteren en daardoor 100% safe en makkelijk weg te komen.

**Comment by Ljosfari** [comment]
Is aangepast

**Comment by ARJ3N** [comment]
Ik heb nu een aantal keren gezien dat personen alsnog onder water in kunnen stappen. Is het mogelijk dat hier nog eens een blik op geworpen kan worden? @Ljosfari

**Comment by Chang-nl** [comment]
Yes is gefixt na de herstart! Bedankt voor het melden.
