### ISSUE TITLE
Paleto Bay HB functioneel maken

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#896]
**Beschrijf zo duidelijk mogelijk de feature**
Het toevoegen van een cirkel om in te klokken, een plek voor de opslag waar je wapens/spullen uit kan pakken/kopen, een kledingcirkel, een pijl om van character te kunnen wisselen, een plek achter het HB bij de helipads waar je een politiehelikopter kan pakken (net zoals op het dak van HB), een plek waar je het dienstvoertuig kan pakken/wegzetten en een plek waar je inbeslaggenomen voertuigen in de politieopslag kan zetten zou erg fijn zijn.

**Coördinaten:**

- [x] Inklokcirkel: X: -448.94 Y: 6011.78 Z:31.72 H:129.17
- [x] Wapenopslag: X: -446.57 Y: 6009.10 Z: 31.72 H: 221.69
- [x] Kledingcirkel: X: -449.10 Y: 6016.94 Z: 31.72 H: 37.44
- [x] Pijl voor character switch: X: -447.89 Y:6018.29 Z: 31.72 H: 42.77
- [x] Politiehelikopter pakken: X: -465.55 Y: 5999.67 Z: 31.30 H: 135
- [x] Helikopter spawnplek: X: -475.19 Y: 5988.71 Z: 31.34 H: 315
- [x] Politievoertuig pakken/wegzetten: X: -448.18 Y: 6026.42 Z: 31.49 H: 137.82
- [x] Auto spawnplek 1: X: -452.84 Y: 6050.15 Z: 31.02 H: 220
- [x] Auto spawnplek 2: X: -449.13 Y: 6052.78 Z: 31.02 H: 212.72
- [x] Auto spawnplek 3: X: -444.81 Y: 6054.54 Z: 31.02 H: 208
- [x] Sleepwagen spawnplek: X: -451.39 Y: 6048.49 Z: 31.46 H: 220
- [x] Inbeslagnamecirkel: X: -416.30 Y: 6040.46 Z: 31.34 H: 137.20

**Wat lost deze feature op?**
Voegt extra mogelijkheden toe voor politie/KMar in het noorden, wat de roleplay in dat gebied erg zal bevorderen. Momenteel moet je namelijk naar Sandy HB om deze dingen te kunnen doen, en dat is nogal een stuk rijden heen en terug. Dit gaat de efficiëntie van de politie verbeteren en de ergernissen van sommige werkzaamheden in het noorden. Momenteel wordt er weinig tot niet gepatrouilleerd in de bovenkant van de map en denken dat dit de activiteit en inzetbaarheid in het noorden een boost zal geven. Tevens zit het interieur er al.
(Arjen)

**Comment by Willem-Dekker** [comment]
zit er in na restart

**Comment by ARJ3N** [comment]
@Willem-Dekker top man enorm bedankt! Enige wat me is opgevallen is dat de KMar de in en uitdienst klok cirkel niet ziet, maar de rest allemaal wel. Zou daar eventueel nog naar gekeken kunnen worden? :)
