### ISSUE TITLE
[BUG] registratie diensturen/facturen 

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#897]
**Omschrijf de bug**
De taxi hoort vaker van het personeel dat de gestuurde facturen en tijd niet kloppend zijn met wat aangeleverd word in de e-mail.
Wij baseren onze promoties op diensturen en gestuurde facturen dit is dus van groot belang.

Wij hebben zelf de uren gecontroleerd van mensen die zeggen dat het niet klopt, vaak kloppen de diensturen dan niet. Dit valt te controleren in de uren registratie in de overheids discord. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
-

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
-

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Sinds 1 maand ongeveer worden sommige data ontbreken of missend aangeleverd (vanuit de server), dus het normale gedrag is dat de bestanden die via de e-mail komen kloppend en volledig zijn.

**Screenshots en/of logbestanden**

**Impact op de server**
boze taxi medewerkers die stoppen door gebrek aan motivatie omdat het werk niet word/niet goed word beloond.

**Comment by Willem-Dekker** [comment]
voorbeelden? logs? kan hier niet veel mee

**Comment by TedeaTaxi** [comment]
Het enige wat ik er kan over vertellen en controleren is dat er soms in shiftlogger als je uitklokt geen message wordt geplaatst over je dienst, diensten van 30min en langer gaan meestal goed alleen daar onder niet.
