### ISSUE TITLE
Trailers

### ISSUE THREAD

**Issue by DaanVr2** [Tedeapolis/development#898]
**Beschrijf zo duidelijk mogelijk de feature**

*Meer trailers toevoegen en deze meer kilo's geven*

De volgende trailers toevoegen in de shop zodat deze kunnen worden gebruikt in rp op dit moment zit namelijk alleen de trekker in de game en het zou leuk zijn om ook trailers te kunnen gebruiken in rp 

Spawnnaam: /car docktrailer
Foto: ![image](https://user-images.githubusercontent.com/90869210/144109324-b3b15451-620a-4012-9812-eb03e194ee9e.png)

Spawnnaam: /car trailers (2 models)
Foto: Model 1 ![image](https://user-images.githubusercontent.com/90869210/144109511-ebaec324-41cc-4b48-8dbf-ca72418e07d9.png)
Model 2 ![image](https://user-images.githubusercontent.com/90869210/144109567-9ed45695-c023-45ee-90b8-0b1a3a3a9b45.png)

Spawnaam: /car trailers2 (meerdere skins)
Foto: ![image](https://user-images.githubusercontent.com/90869210/144110747-cd64c63b-07ec-4e34-badc-432cc1d0fe67.png)

Spawnaam: /car trailers3 
Foto: ![image](https://user-images.githubusercontent.com/90869210/144110889-648547cf-ac65-4bfc-afc7-c0b30ab41d8e.png)

Spawnnaam: /car trailers4
Foto: ![image](https://user-images.githubusercontent.com/90869210/144241150-794a72b0-bd86-4958-bc0b-793b3fb8b688.png)
 

Als deze 200-300 kilo zouden kunnen krijgen zou dat erg goed zijn voor de roleplay dan zouden deze echt kunnen worden gebruikt voor het vervoeren van drugs dit zijn dan veel kilos maar hij gaat ook niet harder dan 100km/u

**Wat lost deze feature op?**

Betere rp binnen de server omtrend het drugs vervoeren

En aangezien er op dit moment maar 2 aanhanger opslag plaatsen zijn mischien wat meer toevoegen

**Comment by AnatolyMoskvin** [comment]
**Koop Config**
  
Koop Cirkel |    X: 121.43 Y: 6413.35 Z: 30.34      
Display Cirkel | X: 135.83 Y: 6420.44 Z: 30.31

**Veranderen Spawn Config**

Spawn Cirkel | X: 122.67 Y: 6406.29 Z: 30.36
Spawn Location | X: 159.30 Y: 6445.13 Z: 31.32 H: 137.71
Inlever Cirkel | X: 152.97 Y: 6418.84 Z: 30.26


**Eventuele prijzen trailers**

Rond de 160K a 185K
