### ISSUE TITLE
[BUG} Als jij een bankoverval doet en jij haalt geld van de trolleys af dan zijn deze soms gebuged.

### ISSUE THREAD

**Issue by lexdeboer** [Tedeapolis/development#899]
**Omschrijf de bug**
Als jij een bank overval wilt doen en als jij dan eenmaal begonnen bent, en je moet het geld van de trolleys pakken dat zijn die soms gebuged. Want dan krijg je namelijk geen zwart geld.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Als jij dus naar een bank toe gaat en je gaat die eenmaal overvallen, als jij dan uiteindelijk de kluis open hebt en je het geld kan verzamelen van de trolleys. Dan kan het zijn dat je bij sommige trolleys geen zwart geld krijgt.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Je verzameld wel het geld alleen je krijgt er geen zwart geld voor terug wat normaal wel zo is, en je tas die je bij je hebt die blijft ook zweven in de lucht. ( Zie videos )

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal als jij geld van de trolleys pakt dan hoor jij gewoon zwart geld te krijgen, die jij van de trolleys verzameld.

**Screenshots en/of logbestanden**
https://youtu.be/1u91XRE8BQM
https://youtu.be/T6vIIOlUlvM

**Impact op de server**
Redelijk hoog denk ik omdat, er wel veel mensen zijn die bank overvallen doen. Maar niet iedereen heeft last van dit probleem.

**Comment by niekschoemaker** [comment]
Dit zou nu gefixed moeten zijn.
