### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaanVr2** [Tedeapolis/development#900]
**Omschrijf de bug**
Als je je voertuig in de garage wilt zetten terwijl je recent hebt geschoten kan dat niet voor een lange tijd 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Schieten en je auto in de garage proberen te zetten

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
melding van: je bent te recent in gevecht geweest

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
je kan hem erin zetten maar je zou hem niet kunnen wegzetten als er een wapen inzit die je recent hebt gebruikt

**Screenshots en/of logbestanden**
/

**Impact op de server**
Lange tijd wachten als je een andere auto wilt pakken nadat je in gevecht bent geweest

**Comment by timfloors** [comment]
Wat is precies het probleem, aangezien die "recent in gevecht" toegevoegd is om te voorkomen dat je voertuigen weg kunt stoppen nadat je gevochten hebt?

**Comment by DaanVr2** [comment]
> Wat is precies het probleem, aangezien die "recent in gevecht" toegevoegd is om te voorkomen dat je voertuigen weg kunt stoppen nadat je gevochten hebt?

het oorspronkelijke idee wat bij de burgerraad is voorgesteld was dat je wapen niet meer weg kon leggen nadat je recent had geschoten en niet dat je je auto helemaal niet meer weg kon zetten

**Comment by timfloors** [comment]
>>Wat is precies het probleem, aangezien die "recent in gevecht" toegevoegd is om te voorkomen dat je voertuigen weg kunt stoppen nadat je gevochten hebt?
> 
> het oorspronkelijke idee wat bij de burgerraad is voorgesteld was dat je wapen niet meer weg kon leggen nadat je recent had geschoten en niet dat je je auto helemaal niet meer weg kon zetten

Het uiteindelijke punt dat uitgekomen is hierdoor is een algehele combat block waarbij je niet meer in huizen kan of voertuigen weg kan zetten, dit is op die manier gemaakt om onder andere te voorkomen dat voertuigen direct na een schietincident weg gezet kunnen worden. Het werk na behoren namelijk
