### ISSUE TITLE
Groene en Rode Garage cirkel bij postnl

### ISSUE THREAD

**Issue by AnatolyMoskvin** [Tedeapolis/development#901]
**Beschrijf zo duidelijk mogelijk de feature**
Een garage plek bij Postnl zodat mensen hun auto hier in kunnen zetten

**Wat lost deze feature op?**

Enorme drukte van auto,s bij PostNL

![image](https://user-images.githubusercontent.com/84158163/144444825-84c36bce-f090-412e-8be9-a43e7cae8fd0.png)

**Comment by brothasx** [comment]
Na de restart zou deze gepushed moeten zijn.
