### ISSUE TITLE
Drugsmeldingen werken niet meer [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#902]
**Omschrijf de bug**
Als iemand afgewezen wordt door een NPC kregen wij voorheen een melding op de map, maar die krijgen we nu niet meer en zijn dus niet werkend.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Iemand aan een NPC laten verkopen totdat diegene afgewezen wordt en dan zul je zien dat de politie geen melding krijgt.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
N.v.t.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaliter zou bij een afgewezen drugsverkoop door een NPC een melding moeten binnen komen.

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Drugsmeldingen waren wel meldingen waar actief op gereden werd door zowel reguliere politie enheden als de recherche, maar dat is nu dus niet meer mogelijk.
(Arjen)

**Comment by Willem-Dekker** [comment]
is dit nog een issue?

**Comment by TDA-SanderD** [comment]
Ja, het is nog steeds een probleem.

**Comment by niekschoemaker** [comment]
> Ja, het is nog steeds een probleem.

Graag na volgende restart even controleren, zou nu gefixed moeten zijn

**Comment by PolitieTDA** [comment]
Is nu fixed!
