### ISSUE TITLE
Vliegradar werkt niet meer [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#903]
**Omschrijf de bug**
Voorheen kregen wij op de kaart een groene cirkel met waar ongeveer een toestel zich in de lucht bevond. Deze feature werkt nu niet meer en deze groene crikels komen niet meer voor.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een helikopter pakken en op de juiste hoogte gaan vliegen, dan zul je zien dat er geen groene crikel meer op de kaart komt te staan.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
N.v.t.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaliter zou je een grote groene crikel moeten kunnen zien op de kaart waar er ongeveer een toestel zich in de lucht bevind.

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Dit is erg vervelend voor met name de kustwacht & KLu aangezien zij hierdoor gehinderd zijn in hun werk m.b.t. controles e.d. uitvoeren.
(Arjen)

**Comment by niekschoemaker** [comment]
Graag sluiten als het gefixed is, heb de issue gevonden en als het goed is gefixed na volgende restart

**Comment by MisterM02** [comment]
Is gefixed.

**Comment by PolitieTDA** [comment]
Werkt weer naar behoren, bedankt! :)
