### ISSUE TITLE
[BUG] Noodknop KMar wordt weergegeven als "Politie"

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#904]
**Omschrijf de bug**
Wanneer de KMar een noodknop indrukt krijg je hiervan een melding.
In deze melding staat echter, "Noodsignaal van POLITIE".
In plaats van "POLITIE" zou hier "KMAR" moeten staan.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Als KMar zijnde de noodknop indrukken.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Er staat dat politie de noodknop heeft ingedrukt.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Er moet staan dat KMAR de noodknop heeft ingedrukt.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/72617118/144502442-a8e82aa4-e447-4e2d-bd59-d03ce60c919f.png)
![image](https://user-images.githubusercontent.com/72617118/144502521-e8d8e648-1e1a-40fc-b0a7-ad4eee48abcf.png)

**Impact op de server**
Is vervelend voor onderlinge communicatie tussen deze overheidsdiensten

**Comment by niekschoemaker** [comment]
Zou gefixed moeten zijn, graag even testen en closen als t gefixed is.

**Comment by MisterM02** [comment]
![image](https://user-images.githubusercontent.com/72617118/144616873-5b44979f-52a9-4d48-be36-ef69edc6549c.png)
Fixed
