### ISSUE TITLE
APV link toevoegen aan wachtscherm

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#905]
**Beschrijf zo duidelijk mogelijk de feature**
Onder hoelang iemand nog moet wachten toevoegen : 
Heeft u de server regels al doorgelezen? Met een linkje erbij naar de apv.
**Wat lost deze feature op?**
Dat spelers niks te doen hebben bij het wachten en zodoende nog eens op de server regels geattendeerd worden.

**Comment by brothasx** [comment]
Awel awel , waar is die link ?

**Comment by brothasx** [comment]
Uitgevoerd. Deze zal na de restart erbij staan.
