### ISSUE TITLE
[BUG]Als je in de modshop je velgen wil aanpassen crashed FIVEM

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#906]
Omschrijf de bug
FIVEM crashed als je bij de modshop dicht bij ziekenhuis je velgen wil aanpassen. 

Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)
Je velgen aanpassen (Dit kan ook liggen aan de drukte?)

Wat gebeurde er (meldingen, console, etc allemaal van belang)
Crash van de hele game

Normaal gedrag (Wat zou er normaal moeten gebeuren)
Dat je zonder crashes je auto kunt aanpassen

Screenshots en/of logbestanden
![image](https://user-images.githubusercontent.com/72617118/144642121-5350b1a6-d439-4d6b-a751-3d230a6a2d1d.png)

Als er beelden nodig zijn kunnen deze gestuurd worden

Impact op de server
Dat veel mensen crashen?

**Comment by brothasx** [comment]
Word verwerkt in #947
