### ISSUE TITLE
Rank naam

### ISSUE THREAD

**Issue by ExpensionX** [Tedeapolis/development#907]
**Beschrijf zo duidelijk mogelijk de feature**
Er is lang geleden een nieuwe rank aangemaakt genaamd Peaky Blinder. Onder de jobnaam expension. De groep is 2 maanden geleden veranderd naar Cangaço. Is het eventueel mogelijk om dit te veranderen? Dus van Peaky Blinder naar Cangaço.

**Wat lost deze feature op?**
Dit is voor de spelers geen meerwaarden. Het is meer voor als er streams/opnamens gedaan worden dat er een juiste rank staat. Ook voor ons eigen dat er een juiste groep naam staat. Dit is helemaal geen prio. Daarom vraag ik het aan via deze manier.

**Comment by niekschoemaker** [comment]
Heb het aangepast
