### ISSUE TITLE
/repareer verhogen naar 8 

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#908]
**Beschrijf zo duidelijk mogelijk de feature**
Momenteel staat het /repareer functie op 5 of minder ANWB'ers in-dienst dit wil ik graag verhogen naar 8 of minder ANWB'ers in-dienst.

**Wat lost deze feature op?**
Dat ANWB meer meldingen kunnen gaan rijden voordat er iemand op ANWB HB moet staan. Dit lost ook de drukte op ANWB HB een beetje op.

**Comment by Willem-Dekker** [comment]
fixed na restart
