### ISSUE TITLE
Holster cooldown

### ISSUE THREAD

**Issue by RonaldDaquila** [Tedeapolis/development#909]
**Beschrijf zo duidelijk mogelijk de feature**
Het is nu zo dat wanneer je een holster om doet, je gelijk een pistool kan trekken. Dit is onrealistisch en worden ook warnings voor gegeven. Mijn idee is dat je wanneer je een holster om wilt doen, je enkele seconde stil moet staan. Net zoals kleding aan en uit trekken.

**Wat lost deze feature op?**
Zo kunnen mensen niet meer misbruiken om snel je holster om te doen voordat je een pistool trekt.

**Comment by niekschoemaker** [comment]
Ik heb ene kleine delay van een seconde toegevoegd
