### ISSUE TITLE
Compact rifle

### ISSUE THREAD

**Issue by RenoNiiChan** [Tedeapolis/development#91]
[YT Video](https://www.youtube.com/watch?time_continue=4&v=GMDYe_tgTrc&feature=emb_logo)

In **ticket-7277** werd er een melding gemaakt dat bij het herladen van de compact rifle de clip verdwijnt maar het wapen niet herladen is.

Ik heb dit zelf niet kunnen nabootsen en in de video is het ook niet duidelijk wat er nu juist fout liep.

- [ ] Bug proberen nabootsen

- [ ] Bug oplossen

- [ ] Indien bug na geboots kan worden met veel succes refund klaar zetten

**Comment by Willem-Dekker** [comment]
probleem is niet na te bootsen en ik zie geen problemen
