### ISSUE TITLE
Vliegbrevet in de test server

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#910]
**Beschrijf zo duidelijk mogelijk de feature**
Onlangs is de update doorgevoerd waarbij je een vliegbrevet nodig hebt. Deze update is ook doorgevoerd in de test server, waardoor je geen vliegtuigen of heli's meer kunt besturen in de test server. Het verzoek is om deze update uit te schakelen in de test server of iedereen met test server/server supporter rang toegang te geven tot het command /giveflylicense.

**Wat lost deze feature op?**
Het feit dat het momenteel onmogelijk is om op te stijgen met een vliegtuig/heli in de test server.

**Comment by niekschoemaker** [comment]
De check staat uit op de test server
