### ISSUE TITLE
Crash tunestore [BUG]

### ISSUE THREAD

**Issue by JorisDeJoris** [Tedeapolis/development#911]
**Omschrijf de bug**
FIVEM crashed als je bij de modshop dicht bij ziekenhuis je velgen wil aanpassen. En ook bij de gene onder ANWB

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je velgen aanpassen (Dit kan ook liggen aan de drukte?)

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Crash van de hele game

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Dat je zonder crashes je auto kunt aanpassen

**Screenshots en/of logbestanden**
https://cdn.discordapp.com/attachments/852145929695658014/916716291954458674/Movies__TV_03_12_2021_17_46_14.png

**Impact op de server**
Medium

**Comment by brothasx** [comment]
Word aan gewerkt in #947
