### ISSUE TITLE
Vrouwelijke slagers outfit (BUG)

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#912]
# Waar zit het in EUP, interiors of retextures ?
Slagers outfit
# Link naar issue of coördinaten naar de plek
-
# Zitten er fouten in? zo ja graag beschrijven en een screenshots
Armen zijn gebugged
# Wat is de toegevoegde waarde?
-
![unknown](https://user-images.githubusercontent.com/69094685/144725699-3a34c661-3951-4024-845e-7fc992742eed.png)

**Comment by brothasx** [comment]
Deze is gefixed na de restart
