### ISSUE TITLE
[BUG]Basic Fat boksring dood na verslaan

### ISSUE THREAD

**Issue by OliviaVD** [Tedeapolis/development#913]
**Omschrijf de bug**
Als je in de boksring gaat en elkaar verslaat, ga je dood.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
In de boksring gaan en iemand verslaan bij het boksen

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
na het verslaan, gaan de twee deelnemers dood

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
de spelers staan, na de wedstrijd, normaal gewoon op de health waarmee hij aan de wedstrijd begon.

**Screenshots en/of logbestanden**
https://media.discordapp.net/attachments/916682531192061982/916683123645886494/unknown.png?width=1035&height=701

**Impact op de server**
Meer mensen gaan dood in de basic fat, extra belasting op de ambu, spelers kunnen niet meer gebruik maken van de boksring zonder dood te gaan.

**Comment by brothasx** [comment]
Deze heb ik paar keer getest  en zie hier zelf geen fout in. 
Hoogswaarschijnlijk zijn het kinderen die door blijven trappen.
