### ISSUE TITLE
[BUG]Datum rond middernacht komt niet overeen

### ISSUE THREAD

**Issue by OliviaVD** [Tedeapolis/development#914]
**Omschrijf de bug**
Datum links bovenaan verschilt 1 dag met de effectieve datum rond middernacht

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Om middernacht in de server gaan en kijken naar de weergegeven datum

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Links bovenaan is het 1 dag eerder dan dat het effectief is.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Links bovenaan zou dezelfde dag moeten staan.

**Screenshots en/of logbestanden**
https://youtu.be/BDBxdHiuNos

https://www.youtube.com/watch?v=BnIS4bq8Fkc
![2021-12-06](https://user-images.githubusercontent.com/95588337/144820798-9a3fedb9-130e-4aef-a511-6cd6a9ef2de1.png)
Gisteren is hierbij dus 05-12-2021

**Impact op de server**
Voor het maken van bewijzen en hierop terugvinden van de juiste logs is dit zeer verwarrend.

**Comment by niekschoemaker** [comment]
Check even of dit nu gefixed is, is als het goed is na volgende restart gefixed

**Comment by brothasx** [comment]
Is gefixed door Misstake

**Comment by OliviaVD** [comment]
Ik ben tot op heden niet meer in de stad geweest zo laat nog, heb er niet meer aan gedacht en/of heb er geen clips van genomen. Vandaag ook erg moe, dus kan ik niets beloven dat ik wakker blijf tot zo laat. Morgen moet ik niet werken, maar wel op tijd op voor de bambino, dusja...
