### ISSUE TITLE
Aanpassingen permissies DTMC / Motorclub

### ISSUE THREAD

**Issue by MisterM02** [Tedeapolis/development#915]
**Beschrijf zo duidelijk mogelijk de feature**
Graag de volgende permissies aanpassen op aanvraag van de motorclub.
/setjob {id} biker 600 | DTMC - Treasurer --> Toegang geven tot de wapeninkoop en het zetten van de attachments op wapens.
/setjob {id} biker 700 | DTMC - Secretary --> Toegang geven tot de pot waar al het geld ligt.

**Wat lost deze feature op?**
Simpele aanvraag van de motorclub. Helpt hun met de roleplay die verbonden is aan hun groep.

**Comment by GustavoTDA** [comment]
Is het ook mogelijk om een extra rol toe te voegen? Namelijk: Head Enforcer (kan afgekort worden met H. Enforcer indien te lang). Daarbij toegang tot attachments op wapens zetten. 

Dus: Head Enforcer --> (extra) toegang tot attachments op wapens.

**Comment by Willem-Dekker** [comment]
je kan niet los attachments dus aanpassing niet mogelijk originele aanpassingen zijn doorgevoerd
