### ISSUE TITLE
visser verkoop verplaatsen

### ISSUE THREAD

**Issue by kerrieeee** [Tedeapolis/development#917]
**Beschrijf zo duidelijk mogelijk de feature**

het verkopen van de visverkoop locatie

**Wat lost deze feature op?**
de enorme chaos van de huidige locatie zal verdwijnen omdat deze huidige locatie veel meer ruimte bied voor de hoeveelheid mensen die de job doen.

ik zat te denken aan locatie -807,80: -2671,79: 13,81: 244,05
![image](https://user-images.githubusercontent.com/95652537/144913071-3ef8308b-37f9-4879-a6ae-cb778785973f.png)

**Comment by brothasx** [comment]
Deze is al opgepakt met de update waar ik mee bezig ben :)
