### ISSUE TITLE
Rode en groene cirkel bij pakketbezorger

### ISSUE THREAD

**Issue by Hellie94** [Tedeapolis/development#918]
**Beschrijf zo duidelijk mogelijk de feature**
2 cirkels toevoegen, zodat mensen hun voertuigen weg kunnen zetten. 

Groene cirkel: X= 74/53 Y= 20.07 Z= 69.18 H= 160.02
Rode cirkel: X= 59.30 Y= 24.50 Z= 69.75 H= 146.07

**Wat lost deze feature op?**
Een hoop zwervende auto's die lag veroorzaken

![image](https://user-images.githubusercontent.com/77858957/144918342-c2c6d808-8204-4f3e-9094-9849e81cc09e.png)

**Comment by brothasx** [comment]
Deze zou na de restart uitgevoerd moeten zijn ;)
