### ISSUE TITLE
[BUG] ID's verdwijnen als je in kledingshop menu gaat

### ISSUE THREAD

**Issue by Rowdeeee** [Tedeapolis/development#919]
**Omschrijf de bug**
Als iemand in de cerkel van een kleding winkel gaat word die nu onzichtbaar, maar het probleem is dat je ook niet meer de ID's ziet, Dus als staff zijnde kan je ook niet meer iemand zien die in een cerkel staat en je die persoon nodig hebt (dit werkt ook niet met /alwaysshowname). 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Als 1 iemand buiten de cirkel blijft staan en de ander in de kleding winkel gaat om hij/haar gehele outfit aan te passen, dan zie je dus het ID niet meer.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Je ziet de ID's niet meer.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je zou gewoon de ID nummers moeten kunnen zien voor als je iemand moet aanspreken.

**Screenshots en/of logbestanden**
https://streamable.com/90dh8q
Let hier op Devv
ID verdwijnt en komt pas terug als ze uit het menu gaat.

**Impact op de server**
Als je als staff zijnde iemand aan wilt spreken kan je de persoon minder makkelijk vinden als ze dus in dit menu staan.

**Comment by niekschoemaker** [comment]
Dit is correct, dit komt door routing buckets, enige manier om bij deze persoon te komen is met /spectate.

Eventueel kan ik ook toevoegen dat /tp je automatisch in de routing bucket zet maar denk dat dit ook voor veel verwarring zal zorgen met staffleden die niet door hebben dat ze in een bucket zitten, waardoor je dus helemaal niemand meer ziet.
