### ISSUE TITLE
Offroad banden op alle overheids  voertuigen. 

### ISSUE THREAD

**Issue by Daanvl1** [Tedeapolis/development#920]
**Beschrijf zo duidelijk mogelijk de feature**
Onder al de politie, KMAR, Taxi, AMBU en ANWB voertuigen offroad banden plaatsen tot het einde van de sneeuw periode.

**Wat lost deze feature op?**
Momenteel zijn veel overheid voertuigen met de sneeuw niet bestuurbaar. De overheids voertuigen kunnen we helaas niet zelf tunen gezien dit 100.000+/- kost.

**Comment by brothasx** [comment]
Sneeuwperiode is al voorbij, dus deze is niet meer nodig x)
