### ISSUE TITLE
Lonen politie

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#922]
**Beschrijf zo duidelijk mogelijk de feature**
Wij zien graag de lonen van de politie veranderd.

**Wat lost deze feature op?**
Dat er meer agenten in dienst zullen komen in plaats van uitdienst.

"police"    "0"    "Aspirant"    "3300"                        
"police"    "1"    "Surveillant"    "4200"        
"police"    "2"    "Agent"    "5100"
"police"    "3"    "Hoofdagent"    "5700"
"police"    "4"    "Brigadier"    "6300"
"police"    "5"    "Inspecteur"    "6900"
"police"    "6"    "Hoofd inspecteur"    "7800"
"police"    "7"    "Commissaris"    "9600"
"police"    "8"    "Hoofd commissaris"    "10200"
"police"    "10"    "AIVD"    "8400"
"police"    "11"    "Officier van justitie"    "4350"
"police"    "12"    "Korporaals"    "7800"
"police"    "13"    "Onderofficieren"    "8400"
"police"    "14"    "Officieren"    "9000"
"police"    "15"    "Majoor"    "9600"
"police"    "16"    "Recherche Junior"    "7800"
"police"    "17"    "Recherche Senior"    "9000"
"police"    "18"    "Recherche Leiding"    "9600"
"police"    "19"    "Recherche"    "8400"
"police"    "1000"    "Eerste Hoofdcommissaris"    "11100"

"offpolice"    "0"    "Aspirant"    "1500"
"offpolice"    "1"    "Surveillant"    "1800"
"offpolice"    "2"    "Agent"    "1950"
"offpolice"    "3"    "Hoofdagent"    "2100"
"offpolice"    "4"    "Brigadier"    "2250"
"offpolice"    "5"    "Inspecteur"    "3000"
"offpolice"    "6"    "Hoofd inspecteur"    "3300"
"offpolice"    "7"    "Commissaris"    "3900"
"offpolice"    "8"    "Hoofd Commissaris"    "4050"
"offpolice"    "10"    "AIVD"    "7800"
"offpolice"    "11"    "Officier van justitie"    "3000"
"offpolice"    "12"    "Korporaals"    "5100"
"offpolice"    "13"    "Onderofficieren"    "5700"
"offpolice"    "14"    "Officieren"    "6300"
"offpolice"    "15"    "Majoor"    "9000"
"offpolice"    "16"    "Recherche Junior"    "5100"
"offpolice"    "17"    "Recherche Senior"    "6300"
"offpolice"    "18"    "Recherche Leiding"    "9000"
"offpolice"    "19"    "Recherche"    "5700"
"offpolice"    "1000"    "Eerste Hoofdcommissaris"    "10500"

**Comment by brothasx** [comment]
"police" "0" "Aspirant" "550"
"police" "1" "Surveillant" "700"
"police" "2" "Agent" "850"
"police" "3" "Hoofdagent" "950"
"police" "4" "Brigadier" "1050"
"police" "5" "Inspecteur" "1150"
"police" "6" "Hoofd inspecteur" "1300"
"police" "7" "Commissaris" "1600"
"police" "8" "Hoofd commissaris" "1700"
"police" "10" "AIVD" "1400"
"police" "11" "Officier van justitie" "725"
"police" "12" "Korporaals" "1300"
"police" "13" "Onderofficieren" "1400"
"police" "14" "Officieren" "1500"
"police" "15" "Majoor" "1600"
"police" "16" "Recherche Junior" "1300"
"police" "17" "Recherche Senior" "1500"
"police" "18" "Recherche Leiding" "1600"
"police" "19" "Recherche" "1400"
"police" "1000" "Eerste Hoofdcommissaris" "1850"

"offpolice" "0" "Aspirant" "250"
"offpolice" "1" "Surveillant" "300"
"offpolice" "2" "Agent" "325"
"offpolice" "3" "Hoofdagent" "350"
"offpolice" "4" "Brigadier" "375"
"offpolice" "5" "Inspecteur" "500"
"offpolice" "6" "Hoofd inspecteur" "550"
"offpolice" "7" "Commissaris" "650"
"offpolice" "8" "Hoofd Commissaris" "675"
"offpolice" "10" "AIVD" "1300"
"offpolice" "11" "Officier van justitie" "500"
"offpolice" "12" "Korporaals" "850"
"offpolice" "13" "Onderofficieren" "950"
"offpolice" "14" "Officieren" "1050"
"offpolice" "15" "Majoor" "1500"
"offpolice" "16" "Recherche Junior" "850"
"offpolice" "17" "Recherche Senior" "1050"
"offpolice" "18" "Recherche Leiding" "1500"
"offpolice" "19" "Recherche" "950"
"offpolice" "1000" "Eerste Hoofdcommissaris" "1850"

**Comment by brothasx** [comment]
Willem gaat deze uitvoeren.

**Comment by Willem-Dekker** [comment]
aangepast
