### ISSUE TITLE
ANWB aanpassing #2

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#923]
- [x] Speedzone op ANWB HB terrein (max 50 Kilometer per uur).

- [x] Het automatisch uit-dienst zetten na het ontvangen van promotie/demotie via het ANWB bazen menu. 

- [x] Extra kopje aanmaken in het facturen systeem van de ANWB met de naam "WOK Facturen" 
- [x] Onder het kopje "WOK Facturen" 2 facturen toevoegen met de volgende naam en prijzen: 
1: Motor 700
2: Auto 1400

- [x] Voor en Achternaam in ANWB-Meldkamer (Zowel Discord als in-game).

- [x] https://github.com/Tedeapolis/development/issues/722 Deze github issue heeft niet gewerkt voor de ANWB maar wel voor Ambulance. (komt waarschijnlijk omdat wij nog het oude garage systeem gebruiken maar ik had al een nieuwe garage systeem aangevraagd in de volgende github: https://github.com/Tedeapolis/development/issues/756

- [x] **(Job Documenten /docu)** APK Keuring formulier aanpassingen: 
1: Voornaam en Familienaam **(veranderen naar)** Voor en achternaam (1 veld)
2: Geboortedatum **(veranderen naar)** Telefoonnummer (1 veld) 
3: Geldig tot **(kan weg)**. 
4: Kilometerstand **(kan weg)**
5: Nummerplaat **(Blijft het zelfde)**
6: Automatische tekst bij Informatie: 

Dit voertuig document is bewijs van goedkeuring met kenteken (A-123-BC). 
Datum goedkeuring door ANWB Keurmeester (zie handtekening). Aanpassingen op en of aan het voertuig na keuringsdatum is op eigen verantwoording van bestuurder.

7: Tekst rechtsboven aanpassen: Dit document dient uitgeschreven te worden door een Technisch specialist in opleiding of hoger van de ANWB. 

8: Zie bijlage voor oude APK Keuring formulier.
![APK document](https://user-images.githubusercontent.com/68514420/145120343-a124d742-ce7f-4ad8-9323-25b4a1c30325.PNG)

**Comment by Willem-Dekker** [comment]
> Voor en Achternaam in ANWB-Meldkamer (Zowel Discord als in-game). 
won't fix
