### ISSUE TITLE
Nieuwe aanpassing aan ANWB-meldkamer is kapot[BUG]

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#924]
**Omschrijf de bug**
De ANWB Discord meldkamer werkt niet meer zoals aangegeven in deze github: github: https://github.com/Tedeapolis/development/issues/847 . Dit heeft trouwens wel even gewerkt en is sinds ongeveer 5 dagen geleden weer kapot gegaan.

**Comment by niekschoemaker** [comment]
Welk onderdeel is exact kapot dan?

Want als ik in meldkamer-overheidsdiensten kijk zie ik daar gewoon de meldingen van overheids diensten staan en in de andere de normale meldingen?

**Comment by DeStefanoKiller** [comment]
Momenteel komen Politie, Kmar, Ambu en ANWB meldingen ook in de normale meldkamer. Deze meldingen moeten juist alleen in Meldkamer-overheidsdiensten en dus niet in beide meldkamers.

**Comment by Willem-Dekker** [comment]
fixed voor na restart
