### ISSUE TITLE
Flitspalen zijn nog kapot

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#925]
**Omschrijf de bug**

de flitspalen of staan er helemaal niet, of ze staan er wel en doen het niet

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

in de mainserver de flitsers opzoeken, ene keer staan ze er wel andere keren staan ze er geheel niet

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

de palen zouden er gewoon moeten staan :)

**Screenshots en/of logbestanden**

**Impact op de server**

verkeersovertredingen en snelheden door het centrum loopt nu lekker op

**Comment by brothasx** [comment]
Paar keer getest, deze werken gewoon gedurende de tests.
