### ISSUE TITLE
6x6, Gwagon andere offroaders geen grip in sneeuw

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#926]
**Omschrijf de bug**

De offroaders zoals de 6x6 en de gwagon (oude versie) hebben met standaard en all terrain banden geen grip in de sneeuw en zijn bijna onbestuurbaar

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

probeer zelf maar met een van die voertuigen door de sneeuw te rijden

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

normaal zou een offroader toch ook redelijke wegligging in sneeuw moeten hebben?

**Screenshots en/of logbestanden**

**Impact op de server**

de offroaders hebben geen grip is de sneeuw waardoor er weinig aan auto's over blijft die wel goed in de sneeuw rijden

**Comment by brothasx** [comment]
Er is geen sneeuw meer, issue fixed ? x)
