### ISSUE TITLE
Rode cirkel op de map als je dood bent gegaan

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#927]
**Beschrijf zo duidelijk mogelijk de feature**

Zoals besproken afgelopen zondag hier dan de request, de cirkel die je krijgt als je dood gaat (dus die rode cirkel waar je taakstraf van krijgt en binnen een minuut uit moet zijn) de timer ervan verlagen naar max 15 sec. zodat mensen hier niet nog even snel hun voertuig uit kunnen halen

**Wat lost deze feature op?**

Vaak in roleplays waar mensen dood gaan en ze eigenlijk niets van de plek of locatie mogen weten gaan ze toch nog even snel terug om hun voertuig weg te halen waar ze zijn dood gegaan, of gaan gewoon terug om mensen uit te dagen die ze daar hebben vermoord.

**Comment by Willem-Dekker** [comment]
zit er in na restart
