### ISSUE TITLE
lonen ANWB aanpassing

### ISSUE THREAD

**Issue by DeStefanoKiller** [Tedeapolis/development#929]
Dit zijn de nieuwe lonen die wij binnen de ANWB willen hebben. (Dit is het loon per 10 minuten) 

Stagiair | 750
Uitzendkracht | 850
Monteur in opleiding | 950
Monteur | 1050
Eerste monteur | 1150
Hoofdmonteur | 1250
Autotechnicus in opleiding | 1350
Autotechnicus | 1400
Technisch specialist in   opleiding | 1450
Technisch specialist | 1500
Autotechnisch ingenieur | 1550
Leermeester | 1600
Teamleider in opleiding | 1700
Teamleider | 1750
Directeur | 1800
Hoofddirecteur | 1850

**Comment by brothasx** [comment]
Waarom zouden deze moeten aangepast worden ? 
Lonen zijn nu hetzelfde als Ambulance

**Comment by brothasx** [comment]
Jullie uitdienst lonen zijn pokke hoog zie ik net ook.

**Comment by Willem-Dekker** [comment]
aangepast
