### ISSUE TITLE
Piloten outfit DSI

### ISSUE THREAD

**Issue by walvisgedaan** [Tedeapolis/development#93]
Zou deze outfit toegevoegd kunnen worden aan de EUP van 'Leger' met als naam 'Vlieger'.

De outfit nummertjes ingame zijn:
T-Shirt 1 : <15>
T-Shirt 2 : <0>
Torso 1 : <48>
Torso 2 : <0>
Armen 1 : <18>
Armen 2 : <0>
Broek 1 : <30>
Broek 2 : <0>
Schoenen 1 : <25>
Schoenen 2 : <0>
Ketting 1 : <9>
Ketting 0 : <0>

**Comment by Willem-Dekker** [comment]
![image](https://user-images.githubusercontent.com/16556575/90180536-6a42cf00-ddaf-11ea-8c6b-3a6993868b67.png)
is dit het?
