### ISSUE TITLE
Loods verwerkingssnelheid verhogen 

### ISSUE THREAD

**Issue by GustavoTDA** [Tedeapolis/development#930]
Zoals besproken gaat dit simpelweg veel te langzaam.

Naar schatting is dit voor **Coke**: Verwerkt 1975 per dag en verwerkt 13825 per week.
**Meth**: Verwerkt 1235 per dag en verwerkt 8645 per week.

Dit is een voorbeeld van beide loodsen die op fully upgrades draaien.

**Comment by Ljosfari** [comment]
wordt al standaard in de gaten gehouden
