### ISSUE TITLE
Rate limiter van revive ambulance controleren

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#931]
**Omschrijf de bug**

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

**Screenshots en/of logbestanden**

**Impact op de server**

**Comment by Willem-Dekker** [comment]
er moet gekeken worden naar de revive reward.

**Comment by Willem-Dekker** [comment]
zou er iets meer info over komen

**Comment by FreddyKrueger2021** [comment]
Kort samen gevat, dit zit erin omdat mensen elkaar vaak dood slaan en abuse te voorkomen er dus niet telkens 150 euro per revive is voor een ambu, mij is opgevallen dat dit niet alleen is in die gevallen maar ook gewoon dan bij compleet andere meldingen en dat ze daar dan ook niet het revive geld voor krijgen

**Comment by niekschoemaker** [comment]
Yes heb het ff gechecked
