### ISSUE TITLE
Auto’s limiteren kapot (staffoverleg puntje)

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#932]
**Beschrijf zo duidelijk mogelijk de feature**

mensen gebruiken als excuus dat wanneer er banden geschoten zijn en de auto roodknipperend is. Kunnen ze nog 50+ rijden.

Persoonlijk een auto die total loss is die rijd niet meer

Mensen die onder schot gehouden worden vinden het nu een excuus van ja me auto rijd nog 50+ dus ik hoef niet mee te werken oftewel no value of life.

**_Mogelijk dat er iets op aangevoerd word zodat ze dit niet als excuus kunnen gebruiken want autos waar banden van kapot zijn en auto helemaal kapot is hoort niet te rijden_.**

**Wat lost deze feature op?**
excuses die gebruikt worden voor NVOL of niet realistisch een rp aangaan als het voertuig kapot is.

**Comment by niekschoemaker** [comment]
Is gefixed
