### ISSUE TITLE
Cooldown CommunicatieMiddelen(Staffoverleg 6-12-21)

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#933]
**Beschrijf zo duidelijk mogelijk de feature**
Er is besproken tijdens het overleg om na het vermoord worden door een steek/slag of vuurwapen een cooldown van 15min op je communicatiemiddelen te zetten, aka je kunt niet meer je telefoon openen, berichten sturen in sms zowel als deepwebs en een porto gebruiken

**Wat lost deze feature op?**
Een groot deel van de NewLifeRule overtredingen word hiermee aangepakt, het word lastiger om weer aan te sluiten bij oude situatie's

**Comment by Ljosfari** [comment]
telefoon weghalen als je respawned

**Comment by Ljosfari** [comment]
Top !

**Comment by niekschoemaker** [comment]
En porto word nu ook geblokkeerd
