### ISSUE TITLE
Discord bot addrole mogelijk maken meerdere rollen

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#934]
**Beschrijf zo duidelijk mogelijk de feature**

als je rang recruiter of teamleider hebt
dat je alle onderstaande rangen kan geven en weghalen van een taxi persoon
we hebben veel wisselende mensen bij deze rollen 

/role add gebruiker:@discord#1234 rol:@TAXI
/role add gebruiker:@discord#1234 rol:@TAXI MARKETING 
/role add gebruiker:@discord#1234 rol:@TAXI RECRUITERS
/role add gebruiker:@discord#1234 rol:@TAXI TEAMLEIDER

**Wat lost deze feature op?**
niet meer in role aanvraag hoeven te zetten als we binnen de taxi andere mensen andere dingen gaan laten doen
we hebben een grote door loop van personeel hier mee kunnen we sneller en efficiënter dingen veranderen waar nodig

**Comment by niekschoemaker** [comment]
Ik heb de rollen iets aangepast, de rol taxi baas kan nu de gegeven rollen beheren, en recruiters kunnen nu taxi en taxi marketing geven.

heb dit zo gedaan omdat het niet echt logisch is dat een bepaalde rol z'n eigen rol kan beheren, dus vandaar heb ik het even zo gedaan.
