### ISSUE TITLE
Mijnwerk trucks kunnen niet op zand rijden

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#935]
**Omschrijf de bug**
 De mijnwerk truck kan niet op het zand rijden, hij glipt alle kanten op en je moet naar de groeve en dus op zand grotendeel van de tijd

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

mijnwerktruck pakken en naar de groeve rijden

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

**Screenshots en/of logbestanden**

**Impact op de server**

**Comment by niekschoemaker** [comment]
Is gefixed
