### ISSUE TITLE
F6 Facturen menu TDA Ambulance.

### ISSUE THREAD

**Issue by VinnyMafklapper** [Tedeapolis/development#936]
**Beschrijf zo duidelijk mogelijk de feature**
F6 Facturen aanpassen/uitbreiden bij de Ambulance.

**Wat lost deze feature op?**
Zo kunnen we betere en gerichter de goede facturen geven waarvoor de patiënt behandeld of geopereerd is in en rondom het ziekenhuis.
Dit gaat dan voor leukere en gerichter RP zorgen.
Hier is door meerdere collega's bij de Ambulance om gevraagd.

Zie bijgevoegde document.

[Facturen_AMBU.xls](https://github.com/Tedeapolis/development/files/7721687/Facturen_AMBU.xls)

**Comment by Willem-Dekker** [comment]
No permission
