### ISSUE TITLE
[BUG] /shuff werkt wel de ene kant op maar niet de andere kant op.

### ISSUE THREAD

**Issue by JohnnyFlodder** [Tedeapolis/development#937]
**Omschrijf de bug**
/shuff werkt half alle voorbeelden staan in de clip van 2 min is alles te zien.

vna bijrijders stoel kan je niet meer /shuff naar bestuurder stoel daarin blijf je hangen.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Van bijrijders stoel shuff doen naar bestuurders stoel

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je zou van de ene kant naar de andere kant moet kunnen bewegen.

**Screenshots en/of logbestanden**
de clip bekijken van 2min tot einde
https://youtu.be/SN_GA7c8f20

![image](https://user-images.githubusercontent.com/89384945/146638113-5132ef92-1c65-4c2b-bdc3-0c9500166d4e.png)

**Impact op de server**
-

**Comment by brothasx** [comment]
Deze lijkt tijdens testen gewoon te werken.
