### ISSUE TITLE
ANPR systeem maakt melding voor elke inzittende van voertuig, hierdoor ontstaat veel spam. [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#938]
**Omschrijf de bug**
Momenteel krijg je voor elke inzittende van een voertuig die bijvoorbeeld met een WOK-status langs een flitspaal rijdt een melding in de politie meldkamer. Dus wanneer er een voertuig langsrijdt met vier inzittenden dan krijg je 4x een melding binnen. Dit veroorzaakt enorm veel spam van de meldkamer waardoor er meldingen gemist worden. Ook staan er op sommige plekken meerdere flitspalen vlak bij elkaar, eventueel dat er ook iets van een cooldown op de meldingen gezet kan worden. Maar als dit met meerdere inzittenden gefixt is scheelt het al 80% van de spam.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Met meerdere personen in een voertuig met WOK-status of die gestolen gemeld staat langs een flitspaal rijden.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
N.v.t.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zouden we eenmaal melding moeten krijgen.

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Dit heeft veel impact op de politie/KMar aangezien de meldkamer helemaal volgespammed wordt met meldingen. Hierdoor worden andere meldingen over het hoofd gezien en dit hinderd hun werk.

**Comment by Willem-Dekker** [comment]
is dit nog steeds een issue?
