### ISSUE TITLE
[BUG] walking style bug 

### ISSUE THREAD

**Issue by DaanVr2** [Tedeapolis/development#939]
**Omschrijf de bug**

Als je crouched gaat je walking style weg

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

1. selecteer een walking style
2. crouch
3. loop weer

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

de walking style zou moeten blijven 

**Screenshots en/of logbestanden**

https://youtu.be/eBWHGkFD-lE

**Impact op de server**

Bijna onmogelijk om blijvend met een walking style te moeten spelen zonder dat je elke keer opnieuw je walking style moet opzoeken

**Comment by brothasx** [comment]
Is best normaal, vermits crouchen een walkingstyle is

**Comment by brothasx** [comment]
Dus je override  de walkingstyle die je had.
