### ISSUE TITLE
"Schade is hier ontstaan" tekst/puntje weghalen uit hartslag controleren (Ambulance F6 menu)

### ISSUE THREAD

**Issue by Oesewoes** [Tedeapolis/development#94]
Betreft de witte https://cdn.discordapp.com/attachments/616029332049100841/717482651971223652/unknown.png tekst 

Is een beetje dubbel nu aangezien je het standaard ook ziet bij het hartslag controleren bij de rode teksten. 
BPM
Blood
**Hurt Area**
nog wat troep oid.

**Comment by Willem-Dekker** [comment]
Die punt geeft de exacte locatie aan waar de schade is ontstaan,  maar meestal is dit de root en dat is in je kruis
