### ISSUE TITLE
Boten uit inbeslagname spawnen op foute plek [BUG]

### ISSUE THREAD

**Issue by PolitieTDA** [Tedeapolis/development#941]
**Omschrijf de bug**
Momenteel staat de spawnplek voor de boten die uit de ingenomen boten opslag van de politie komen op de foute plek. Hierdoor krijg je dat boten op de stijger spawnen en dus verkeerd terecht komen (zie onderstaande clip). Ik heb hieronder ook coords gezet voor een juiste spawnplek in het water ernaast.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Een boot uit de inbeslaggenomen opslag van de politie pakken.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Check clip: https://youtu.be/7IYjWTvtWH8

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken zou die er naast moeten spawnen.
**Coords voor een juiste spawnplek:**
X: -717.27 Y: -1345.72 Z: 032 H: 138.34

**Screenshots en/of logbestanden**
N.v.t.

**Impact op de server**
Dit is vervelend voor de politie omdat er op deze manier geen boten uit de opslag gehaald kunnen worden.

**Comment by brothasx** [comment]
Deze zal met een restart gepushed worden.
