### ISSUE TITLE
Geen rode cirkel bij begraafplaats na doodgaan

### ISSUE THREAD

**Issue by OliviaVD** [Tedeapolis/development#943]
**Beschrijf zo duidelijk mogelijk de feature**
Dat een speler, die sterft bij de begraafplaats, geen rode cirkel krijgt hier, zodat die bij respawnen geen taakstraf krijgt.

**Wat lost deze feature op?**
Dat de spelers geen taakstraf krijgen als ze respawnen bij de begraafplaats

**Comment by Willem-Dekker** [comment]
is dit nog een issue?

**Comment by OliviaVD** [comment]
Ik heb al even geen reports meer gedaan, dus kan ik het je niet zeggen

**Comment by Ljosfari** [comment]
Is dit nog een issue ?

**Comment by Ljosfari** [comment]
is aangepast
