### ISSUE TITLE
Garage toevoege bij de botenplek van het vissen

### ISSUE THREAD

**Issue by OliviaVD** [Tedeapolis/development#944]
**Beschrijf zo duidelijk mogelijk de feature**
Een garage zetten voor wagens bij de botenplek van het vissen

![2021-12-20 (1)_LI](https://user-images.githubusercontent.com/95588337/146821749-5b214394-fa0b-48fe-9bfa-2024a553a2c9.jpg)
![2021-12-20](https://user-images.githubusercontent.com/95588337/146821761-60dba168-1ae2-4917-8ac5-08109ed2af07.png)

**Wat lost deze feature op?**
Dat er te veel wagens staan bij het vissen en dat wagens geparkeerd worden op de plek waar werkwagens moeten opgeslagen of uitgehaald worden.

**Comment by brothasx** [comment]
Word opgelost met de jobupdates. Dus deze word al behandeld :)
