### ISSUE TITLE
F5 tp naar vissersdepot (botenspawn)

### ISSUE THREAD

**Issue by ChrisCircka** [Tedeapolis/development#946]
Er is een groot probleem dat veel vissersboten zomaar despawnen. Deze mensen zitten dan zonder boot, midden op het water. Als helper zijnde kan je niet even snel noclippen of tpm naar de plek waar je de boot kan pakken. Dus moet je helemaal terug zwemmen om die persoon terug naar de bootspawn te tp'en.

Het zou ervoor zorgen dat helpers, vissers makkelijker kunnen helpen. Dit probleem was er eerst ook met berging en daar is nu een F5 tp voor gemaakt wat het makkelijker maakt om hun terug naar het depot te tp'en.

**Comment by Willem-Dekker** [comment]
zit er in na restart
