### ISSUE TITLE
auto banden wisselen zorgt voor een FiveM crash

### ISSUE THREAD

**Issue by MrPropZz** [Tedeapolis/development#947]
**Nissan Skyline**

**/car rmodskyline34** (model zou niet uit moeten maken, dus elk random voertuig)

**Omschrijf de bug**

als je de banden van je skyline wil veranderen krijg je een FiveM crash en word je er uit gegooid

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
als je met de Nissan Skyline de modshop in gaat en daar de banden gaat verwisselen krijg je een crash.

**hier is een clip van wat er gebeurt:** 
https://streamable.com/kwgn3o

Edit:
Details qua voertuig model

**Comment by niekschoemaker** [comment]
Extra repro stappen voor exacte repro:

1. Zet banden op de voertuig met een kleur (zie video, als t goed is de amazon)
2. Maak de velgen een kleur (zwart bijv.)
3. Ga naar categorie sport en selecteer hier "Chronos" en ga vervolgens door naar de "Chronos" welke een kleur ondersteund

**Comment by niekschoemaker** [comment]
Op het moment komt deze issue niet meer terug, ook niet met de exacte repro welke eerst wel werkte
