### ISSUE TITLE
Blazer heeft geen speedlimiter 

### ISSUE THREAD

**Issue by rubenTomassen** [Tedeapolis/development#948]
**Label van voertuig**

Blazer

**Spawnnaam van voertuig**

/car Blazer

**Omschrijf de bug**

voertuig heeft geen speedlimiter 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

w ingedrukt houden

**Normaal gedrag**

een topspeeds van 150 ofzo

**Screenshots en/of logbestanden**

https://medal.tv/games/gta-v/clips/5Pmr1PI0kPLF5/d1337qekBL2z?invite=cr-MSxqbjQsMTUwODQwODQs

**Impact op de server**

oneerlijk tegenover de andere voertuigen.

**Comment by brothasx** [comment]
Speedlimiter is toegevoegd
