### ISSUE TITLE
[BUG] Bloed op scherm

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#950]
**Omschrijf de bug**
Normaal na een bepaald aantal Damage te krijgen ontvang je zo kleine rode gloed over je scherm. Maar indien je een wapen gericht houd verwijderd deze gloed van het scherm. En dus zie je weer normaal. Doe je het wapen weer weg krijg je de rode gloed terug.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Krijg voldoende Damage om een rode gloed te krijgen. Dan neemt men een vuurwapen en gaat men hier mee richten. 

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Het realistische deel van de rode gloed,op je scherm verdwijnt bij het gericht houden van een vuurwapen. 

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De gloed hoort normaal te blijven  bij het richten van een vuurwapen

**Screenshots en/of logbestanden**
![afbeelding](https://user-images.githubusercontent.com/56398140/147515498-a5ebfbf6-1fdc-438e-84ca-012c2b807c1f.png)
![afbeelding](https://user-images.githubusercontent.com/56398140/147515505-63647c84-a2ef-406f-b964-b1ed67228033.png)

**Impact op de server**
Dat het makkelijker word om te schieten wanneer je geraakt bent, dus middelmatig

**Comment by Chang-nl** [comment]
is gefixt!
