### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#951]
**Omschrijf de bug**

Je kunt iemand uit een auto duwen zonder dat deze het wil en als de gordel zelfs om is

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Iemand aan de bestuurders kant laten zitten, een ander moet "F" ingedrukt houden aan de bijrijderskant dan gaat het automatisch (auto moet wel open zijn)

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**

Je word de auto uitgeduwd als bestuurder

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Het hoort niet je hoort niemand eruit te kunnen duwen

**Screenshots en/of logbestanden**

https://streamable.com/vu8njd

**Impact op de server**

Mensen gaan zwaar misbruik maken.

**Comment by niekschoemaker** [comment]
Is gefixed
