### ISSUE TITLE
[BUG] Lijkenzak steekt uit bij de amarok

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#952]
**Omschrijf de bug**
Lijkenzak in de ambulance amarok (ambuam) steekt aan de achterkant uit.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je pakt een lijkenzak en legt de lijkenzak achterin de wagen.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Niets.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Het zou niet moeten uitsteken.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/61888104/147795509-a1c82ab9-d9bd-4191-b31e-518b94d86a22.png)

**Impact op de server**
Onrealistisch dat er een er een stukje van de lijkenzak uitsteekt aan de achterkant.

**Comment by brothasx** [comment]
Fixed
