### ISSUE TITLE
[BUG] aantal spelers krijgt boot niet uit opslag

### ISSUE THREAD

**Issue by TDALionskull** [Tedeapolis/development#953]
**Omschrijf de bug**
Er zijn een aantal spelers die boten niet uit de opslag krijgen. Ze betalen er wel voor, maar krijgen uiteindelijk hun boot niet uit de opslag. Spelers blijven staan op dezelfde plaats in de circel maar spawnen niet in hun boot.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Bij een aantal andere spelers lukt het wel, en bij sommige ook weer niet.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Gaan in de groene circel staan en proberen hun boot uit de opslag te halen. Vervolgens gaat er geld van af, en krijgen ze hun boot niet. Er komt ook geen andere melding te staan.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gaat er €500,- van je contante geld af, en daarna spawn je in je boot.

**Screenshots en/of logbestanden**
NVT

**Impact op de server**
NVT

**Comment by niekschoemaker** [comment]
Heb je enkele kentekens van voertuigen waarbij dit gebeurt?

**Comment by TDALionskull** [comment]
Nee ik heb daar geen kentekens van.
Mocht er nog een melding zijn, dan zal ik het hier melden.

**Comment by niekschoemaker** [comment]
Zou gefixed moetten zijn
