### ISSUE TITLE
[BUG] apotheek cirkel actief

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#954]
**Omschrijf de bug**
Apotheek cirkel nog steeds actief in het ziekenhuis.

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Je gaat naar de tweede verdieping en loopt de apotheek binnen.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
-

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
De cirkel moet weg zijn

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/61888104/148567328-b25c6946-06cf-41d4-b7fc-fa3bd67168d4.png)

**Impact op de server**
Verwarring bij mensen.

**Comment by brothasx** [comment]
Dit is na de restart gefixed
