### ISSUE TITLE
[BUG] Persoon is gerespawned melding als persoon omhoog is geholpen

### ISSUE THREAD

**Issue by Cryonite** [Tedeapolis/development#955]
**Omschrijf de bug**
De melding: 'Persoon is gerespawned, hulp is niet meer nodig!' ook als je de persoon omhoog helpt (revived).

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Vind een dood persoon, revive hem en kijk in de meldkamer.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Als de persoon omhoog is geholpen zou er geen melding hoeven te komen.

**Screenshots en/of logbestanden**
![image](https://user-images.githubusercontent.com/61888104/148631027-812a760e-9757-4342-91a1-193e768db260.png)

**Impact op de server**
Maakt de meldkamer nog voller voor de ambulance (en evt politie?).

**Comment by niekschoemaker** [comment]
Yes klopt, dit is voor als een admin iemand omhoog helpt.

**Comment by Cryonite** [comment]
> 

het is dus ook als een ambulancier de persoon omhoog helpt, ik weet niet of dat ook de bedoeling is?

**Comment by niekschoemaker** [comment]
> > 
> 
> het is dus ook als een ambulancier de persoon omhoog helpt, ik weet niet of dat ook de bedoeling is?

Yes is geen onderscheid tussen atm en denk dat t wel handig is als extra confirmatie dat iemand omhoog geholpen is.
