### ISSUE TITLE
Issue kofferbak apart open/dicht

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#956]
**Omschrijf de bug**
Normaal kan je de kofferbak met een keybind in fivem instellingen apart open en dicht doen. Zodat in plaats van heel je auto open gaat, enkel de kofferbak open gaat. Nu werkt dit dus niet meer en 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
De auto opslot doen. Een keybind instellen op kofferbak open/dicht. En kijken of je hem met de keybind kunt openen/dicht doen.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Geeft aan dat je kofferbak open moet zijn maar zodra je er in gaat geeft hij aan dat de kofferbak opslot is.

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal hoort de kofferbak open en dicht te gaan zonder problemen.

**Screenshots en/of logbestanden**
N.V.T.

**Impact op de server**
Veel gebruiken deze feature aangezien je vaak meemaakt dat auto's gestolen worden etc.

**Comment by niekschoemaker** [comment]
Yes dit klopt, ik had de keybind omgedraaid zodat je specifiek je kofferbak op slot kunt doen.

Op die manier is het wat logischer en handig om te voorkomen dat mensen je kofferbak leegstelen als je je kofferbak van slot doet.
