### ISSUE TITLE
Beton blokken lombank appartement

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#957]
**Beschrijf zo duidelijk mogelijk de feature**
Het appartementen complex bij lombank wordt door velen gebruikt die in de criminaliteit zitten. Het is makkelijk over te laden met ook de ruimte om je auto neer te zetten. Echter als je het appartement in gaat en iedereen zet zijn auto voor het appartementencomplex neer ga je al gauw dood. Hierbij is aanvraag gedaan om hier iets te plaatsen zodat auto's niet meer recht voor het complex kunnen neerzetten. Ik heb vernomen dat brockl hier a eerder betonblokken geplaatst heeft om te zorgen dat niemand daar ging parkeren.

**Wat lost deze feature op?**
Het voorkomt onnodige dood van spelers en minder reports.

**Comment by brothasx** [comment]
Dit zou na de restart opgelost moeten zijn ;)
