### ISSUE TITLE
Hogere percentage witwas deep-web 

### ISSUE THREAD

**Issue by MrPropZz** [Tedeapolis/development#958]
**Beschrijf zo duidelijk mogelijk de feature**
de meldingen staan nu op 5% of 10%, na bespreking in het staff overleg graag de percentages met 5% te verhogen. Dit omdat er dan meer risico aan zit en meer kans is om mensen te overvallen / overvallen worden.

**Wat lost deze feature op?**
door dit te doen hopen we dat er meer actie komt tijdens het wassen.

**Comment by niekschoemaker** [comment]
Done
