### ISSUE TITLE
[BUG] Wekelijkse automatische uitdraai facturen Taxi - Facturen met bedrag 0

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#960]
**Omschrijf de bug**
In de wekelijkse automatische uitdraai van de facturen van de taxi die elke maandagochtend wordt verstuurd zitten er regelmatig facturen in die op 0 staan qua bedrag. Mogelijk een afronding van facturen die minder dan een euro zijn?

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Mogelijk wat facturen sturen van 0,50 eurocent oid. Maar ik weet het niet precies

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
nvt

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Geen 'lege' facturen.

**Screenshots en/of logbestanden**
Hierbij een screenshot van 2022 week 2 met alle facturen die 0 waren. Ivm privacy namen en steam id's geblurred.
![image](https://user-images.githubusercontent.com/93401910/148900521-368c4ff3-5c24-4a04-a827-b28a0e1c3e7d.png)

**Impact op de server**
Berekening van facturen, en daarmee promoties, mogelijk mis.

**Comment by Willem-Dekker** [comment]
fixed
