### ISSUE TITLE
[BUG] Wekelijkse automatische uitdraai facturen Taxi - Facturen op zondagen incorrect

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#961]
**Omschrijf de bug**
In de wekelijkse automatische uitdraai van de facturen van de taxi die elke maandagochtend wordt verstuurd zit een fout.

Elke week hebben we namelijk mensen die uren hebben gemaakt op zondag (en die zien we wel) en ook facturen hebben verstuurd op zondag (en die zien we niet). En het lijkt erop dat die er altijd bij de csv van de volgende week erin staan.

Het lijkt erop dat ipv dat de facturen vanaf maandag 08:00 van week 1 tot en met maandag 08:00 van week 2 worden berekend, zoals dat bij de uren gebeurt, de facturen vanaf zondag 08:00 van week 1 tot en met zondag 08:00 van week 2 worden berekend. Dit zien we elke week consistent terugkomen in de CSV die we binnenkrijgen. 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Bekijk eventueel de csv's die verstuurd zijn, en bekijk de code om te checken of er een verschil zit tussen uren en facturen, de ene berekent op maandag en de ander op zondag. En anders specifieker kijken naar waarom die zondagfacturen er niet in staan.

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
nvt

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
We willen de uren en facturen met elkaar uitlijnen, dat beide dus vanaf maandag 08:00 van week 1 tot en met maandag 08:00 van week 2 worden berekend.

**Screenshots en/of logbestanden**
Zie verstuurde emails met csv's, of log in op de taxi email om ze daar te downloaden. Ik plaats ze liever niet hier openbaar.

**Impact op de server**
Verkeerde berekening promoties en statistieken van taximedewerkers.

**Comment by Willem-Dekker** [comment]
fixed

**Comment by TedeaTaxi** [comment]
@Willem-Dekker dit is helaas nog niet gefixed. Facturen van twee zondagen geleden worden niet meer meegenomen, wat correct is, maar facturen van afgelopen zondag (gister) vallen nu weg. Waarschijnlijk weer na 8 uur 's ochtends, want we hebben van gister maar 20 facturen, waar dit er normaal zo'n 300 zijn.

**Comment by Willem-Dekker** [comment]
fixed nieuwe mail is er uit gestuurd
