### ISSUE TITLE
Wekelijkse automatische uitdraai facturen Taxi - Voeg ID toe naar wie verstuurd is

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#962]
**Beschrijf zo duidelijk mogelijk de feature**
Voeg in de wekelijkse automatische uitdraai van de facturen van de taxi die elke maandagochtend wordt verstuurd een identifier toe van de persoon naar wie die verstuurd is.

**Wat lost deze feature op?**
Factuurfraude. Als een persoon 20 facturen van onder de 50/100 euro naar zijn vriend stuurt om hoog in de statistieken te komen en meer kans te maken op een promotie. Wij kunnen op dit moment facturen onder een bepaald bedrag eruit filteren, maar het is beter te detecteren als we zien dat facturen veel naar de zelfde persoon zijn gegaan.

**Comment by Willem-Dekker** [comment]
uhm waarom zou ik deze info sturen? alleen daarvoor is geen reden genoeg tbh

**Comment by TedeaTaxi** [comment]
Met ID bedoel ik hier een puur een geanonimiseerd nummer die in deze reeks uniek is voor een gebruiker. Niet hun steam ID of iets dergelijks. Laat me weten als  het moeilijk te begrijpen is en je een voorbeeld wilt hebben, dan maak ik er een.

**Comment by TedeaTaxi** [comment]
Je zou bijvoorbeeld alle steamid's van de personen die facturen ontvangen hebben in een array kunnen knallen, alles duplicates eruithalen, of gewoon zonder duplicates, en dan de index ervan gebruiken als identifier. Dan is het anoniem, en kan je toch zien of werknemer A facturen naar B,C,D,E etc heeft gestuurd (andere indexes) of alleen naar F (allemaal de zelfde index).

**Comment by Willem-Dekker** [comment]
> Met ID bedoel ik hier puur een geanonimiseerd nummer die in deze reeks uniek is voor een gebruiker. Niet hun steam ID of iets dergelijks. Laat me weten als het moeilijk te begrijpen is en je een voorbeeld wilt hebben, dan maak ik er een.

dit is niet mogelijk om te doen is een te grote aanpassing

**Comment by Ljosfari** [comment]
is niet mogelijk
