### ISSUE TITLE
Op whisper praten in telefoon/porto hetzelfde volume geven als op normal [Staffoverleg]

### ISSUE THREAD

**Issue by ARJ3N** [Tedeapolis/development#969]
**Beschrijf zo duidelijk mogelijk de feature**
Wanneer je op whisper staat dat je dan alsnog net als op normal goed te verstaan bent in je porto of wanneer je aan het bellen bent.

**Wat lost deze feature op?**
N.a.v. staffoverleg besproken om problemen op te lossen dat je gedwongen op normal moet in voertuigen wanneer je contact wilt hebben en dat mensen je daardoor buiten het voertuig horen.

**Comment by niekschoemaker** [comment]
Oke en hoe voorkomen we bij dit de issue van het powergamen door te whisperen in porto's?

**Comment by TDA-SanderD** [comment]
Wat bedoel je met powergamen door te whisperen in porto's @niekschoemaker? Dat is juist de bedoeling en dat voorkomt juist dat mensen powergamen door van buiten een auto te horen wat je zegt terwijl je in de porto praat.

**Comment by AdventurePandah** [comment]
Wat hier bedoeld wordt is dat zodra je telefonisch contact met iemand opneemt, of je praat in de porto, dan ben je erg zacht te horen bij de ander als je op whisper staat.

Het doel van deze issue is dat mensen je normaal (qua geluidsniveau) horen via telefoon / porto op het moment je op whisper staat en dat de mensen die naast je staan je enkel kunnen horen als ze binnen de whisper afstand staan.

**Comment by niekschoemaker** [comment]
Ja maar het hele nut achter de porto's zachter laten gaan op whisper is dus om te voorkomen dat iederen standaard altijd in de porto whisperd, waardoor je nooit iemand in z'n porto hoort praten. Hierom is het volume dus zachter als je whispert.

**Comment by niekschoemaker** [comment]
Ik ga deze afwijzen omdat ik persoonlijk het nadeel van iedereen die standaard whispert in de porto's wat ik als een groter nadeel zie dan mensen die elkaar slecht horen als je in een auto praat.
