### ISSUE TITLE
[Maze bank garage]

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#970]
**Maze bank garage niet goed werkend. Voertuigen die al verkocht zijn en niet meer van de persoon is staat nog steeds tussen de catalogus.**

**Dat kan je zien in de Video in de Video doet persoon precies de stappen en kan je zien wat er foutief is. Ook is er een foto meegestuurd met een error via de f8**

**Ik heb persoon naar binnen laten gaan en een screenshot gemaakt van de f8 daar gaf die een error aan staat ook in de fotobijlage.**

**Alleen de auto's laten zien die je daadwerkelijk ook nog hebt. En niet die al verkocht zijn. **

**Screenshots/video word meegegeven in deze report ook staat er een Ticket voor open die kan je dan naderhand verwijderen.
Development Ticket nummer : 63224
Video: https://youtu.be/a6n0FqqB7Fc**
Anders even in de ticket kijken.
![github](https://user-images.githubusercontent.com/90053273/149840428-3be945ec-fbce-41f3-9747-fbdbd6a0a075.png)

**Het is een dat het als vervelend word ervaren dat wanneer ze een miljoen betalen voor deze garage het niet geheel werkt zoals het moet werken.**

**Comment by niekschoemaker** [comment]
Dit zou ondertussen gefixed moeten zijn.

Niet getest, dus graag even terugkoppelen of het daadwerkelijk gefixed is.

**Comment by Vayenn** [comment]
Is inderdaad opgelost, zover wij het nu hebben nagekeken met Lorenzo.

**Comment by Vayenn** [comment]
Alleen de fix heeft iets anders nu je kunt nu niet meer met een voertuig naar buiten. 
https://i.gyazo.com/18f691d62026d80352d88a8f48161d3e.mp4
![gittiehub](https://user-images.githubusercontent.com/90053273/150656024-af722bab-ba72-4052-aa72-9618acbd30fe.png)

**Comment by niekschoemaker** [comment]
Yes zie het idd, is gefixed!
Zou nu moeten werken

**Comment by Lorenzo3001** [comment]
Je kunt nog altijd niet met je voertuig naar buiten rijden en hij geeft deze script error
![unknown](https://user-images.githubusercontent.com/93911282/151196524-55ddab6c-6463-48c2-b60f-09b60c4dce31.png)

**Comment by niekschoemaker** [comment]
Yes heb deze error nu ook gefixed

**Comment by Lorenzo3001** [comment]
Ik krijg nu weer een andere error waardoor de voertuigen niet allemaal spawnen.
![image](https://user-images.githubusercontent.com/93911282/151667869-6795d44c-b3eb-4eb2-9477-f7f7b9f5b501.png)
