### ISSUE TITLE
[BUG] ESX-Shiflogger (Report namens Taxi)

### ISSUE THREAD

**Issue by batsbakbarry** [Tedeapolis/development#972]
**Omschrijf de bug**
In de ESX-Shiflogger van de taxi is met regelmaat te zien dat namen worden ingevuld met "nill nill"

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
Hier zijn geen stappen voor ondernomen, de shiftlog verschijnt in een apart kanaal na het uitklokken van een collega. De naam lijkt willekeurig omgezet te worden naar "nil nil"

**Wat gebeurde er (meldingen, console, etc allemaal van belang)**
Hier zijn geen meldingen van, ook niet in de console

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Normaal gesproken moet de ingame naam weergeven worden op de plaats van "nil nil". 

**Screenshots en/of logbestanden**
![nil nil](https://user-images.githubusercontent.com/97963374/149950452-bc48430e-435e-4e43-a2cf-2252c3fc046f.png)
![Correcte manier](https://user-images.githubusercontent.com/97963374/149950461-e116e568-eb46-4a1d-8783-58514a99d71c.png)

**Impact op de server**
Dit heeft geen impact op de server zelf, maar wel impact op de promotie momenten van speler

**Comment by TedeaTaxi** [comment]
We merken ook dat sommige uren niet worden getoond in the shift logger, als mensen bijvoorbeeld maar een half uur in dienst zijn.
Misschien heeft dit impact op de wekelijkse uren die we doorgestuurd krijgen, maar dat weten we niet zeker omdat het moeilijk te controleren is.

**Comment by TedeaTaxi** [comment]
![image](https://user-images.githubusercontent.com/93401910/150341533-9ef03a53-29e6-423f-bd65-7eb4dfc1ed46.png)
update sinds gister alleen achternaam mist nog @niekschoemaker
