### ISSUE TITLE
Status ambulance motor

### ISSUE THREAD

**Issue by Oesewoes** [Tedeapolis/development#98]
Mogelijkheid om te kijken of de ambulance motor van meneer Delano (https://github.com/DelanoChambon/ambulancemotor3) of een bepaalde andere ambulance motor die cadeau is gedaan functioneel genoeg is om te gebruiken. 

Zou top zijn als MMT/OVD-G meer dan 1 voertuig tot zijn/haar beschikking zou hebben.

**Comment by Willem-Dekker** [comment]
de motor waar je naar linkt heeft te veel poly's

**Comment by Willem-Dekker** [comment]
Deze motor gaat hem niet worden is te groot kwa polys en texture
