### ISSUE TITLE
Blauwe cirkel in loodsen vaak weg voor bezoekers die geinvite worden

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#981]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

De laatste tijd komen er veel reports binnen van mensen die vast zitten in een loods omdat er geen blauwe cirkel is als ze worden uitgenodigd door iemand anders in zijn/haar loods, er staat ook een ticket bij Niek in de cat. met foto's

### Wat hoorde er te gebueren?

Normaal is het net al met woningen dat je zelf de loods uit kan gaan met een blauwe cirkel voor de deur om eruit te gaan

### Wat veroorzaakt de bug?

Geen idee, heb geen logs wel foto voorbeelden in het ticket bij Niek

### Wat de impact van deze bug?

laag

### Relevante log bestanden

Er is een ticket van bij Niek zijn cat. verder geen logs helaas of zelf kunnen navinden

**Comment by Ljosfari** [comment]
is aangepast
