### ISSUE TITLE
Wapenwinkel vanuit sandy shores verplaatsen naar het eiland

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#982]
### Contact Details

[TDA] Freddy K#1026

### Beschrijf zo duidelijk mogelijk de feature

We hebben in stafvergadering besproken en besloten dat om de melee wapens in de stad was terug te dringen de winkel verplaatst zou worden naar het eiland en weg gaat uit sandy shores

### Wat lost deze feature op?

Hopelijk de grote hoeveelheden messen, hamers en boksbeugels terug dringen in main land

**Comment by Ljosfari** [comment]
duplicate van #890

**Comment by niekschoemaker** [comment]
Done
