### ISSUE TITLE
[FEATURE]: Urgent! Verkooplocaties drugs verplaatsen.

### ISSUE THREAD

**Issue by DevvTDA** [Tedeapolis/development#985]
### Contact Details

Devv#4532

### Beschrijf zo duidelijk mogelijk de feature

Mogelijk om de verkooplocaties van drugs te roulleren dat deze weer naar een andere plek gaan? Momenteel staan ze al ene jaar op dezelfde plek en wordt er behoorlijk gecampt. 

Misschien ook slim om dit om de zoveel tijd te doen? 2 maanden? Ik elke keer wel weer coordinaten kunnen veranderen.

### Wat lost deze feature op?

Het lost het campen op en zo houd je nog een beetje actie in de tent, ook gaat de politie hier dan niet meer van af weten als dit steeds veranderd.

**Comment by niekschoemaker** [comment]
Done
