### ISSUE TITLE
[Noodknop vanuit Gangs Onduty als Admin]: 

### ISSUE THREAD

**Issue by Vayenn** [Tedeapolis/development#990]
### Contact Details

Vayen#6904

### Wat gebeurde er?

Ik drukte onbewust de Noodknop in Onduty als Admin terwijl ik in een official gang zit, ik heb geen idee of dit ligt aan dat je zelf Admin bent dat je het daarom ook kunt. Of dat je dit alleen kunt als je in een official gang zit als admin on duty. 

### Wat hoorde er te gebueren?

Dat als je Onduty geen Noodknop stuurt naar de Politie meldkamer als je perongeluk onbewust de noodknop indrukt. 

### Wat veroorzaakt de bug?

Ik activeerde de Noodknop doormiddel van de keybind die erbij hoort als het goed is shift + f9 

### Wat de impact van deze bug?

laag

### Relevante log bestanden

![laicona](https://user-images.githubusercontent.com/90053273/150519701-1b489ba0-28b2-4149-a63e-8e399785a14a.png)

**Comment by Ljosfari** [comment]
is aangepast
