### ISSUE TITLE
[FEATURE]: Wapens categoriseren bij pak wapen gang opslag

### ISSUE THREAD

**Issue by Tom974** [Tedeapolis/development#991]
### Contact Details

Tom974#9209

### Beschrijf zo duidelijk mogelijk de feature

Met de nieuwe toegevoegde label feature bij wapens (een naam geven aan een specifiek wapen), kun je nu wapens in de gangopslag neerleggen en deze een naam geven. Echter zijn er tegenwoordig max 25 spelers in een gang en komt dit uiteindelijk op heel erg veel wapens neer die in de opslag gaan liggen, waardoor je helemaal het overzicht kwijt bent en soms wel een aantal minuten staat te zoeken naar je wapen. 

Mijn idee is als volgt, zodra je op pak wapen drukt opent er een nieuw menu, hier zie je alle wapentypes staan. Kies hier het type wapen waarvan je de voorraad wilt zien, en dan opent er weer een nieuw menu waar je de wapens ziet staan die van dat type in de opslag liggen. (Zie screenshot ter referentie / voorbeeld van AK-74)
Zie onderstaande screenshot ter referentie / voorbeeld.
![image](https://user-images.githubusercontent.com/55812394/150586385-46345279-bed8-498b-960a-e327e9ad4522.png)

### Wat lost deze feature op?

Meer duidelijkheid bij de wapenopslag, zorgt ervoor dat je niet 5 minuten lang aan het zoeken bent naar je wapen nu met de nieuwe label feature aangezien er (25 man per gang, gemiddeld 3-4 wapens p.p.) 25 x 4 = 100 wapens door aan het scrollen bent.

**Comment by niekschoemaker** [comment]
Zit erin na restart
