### ISSUE TITLE
Nieuw ingame report systeem

### ISSUE THREAD

**Issue by Willem-Dekker** [Tedeapolis/development#992]
# Nieuw ingame  report systeem

## Probleemstelling

Momenteel komen er veel reports binnen bij staff op de piekmomenten is dit niet bij te houden. Hierom zal er gekeken moeten worden naar een nieuw systeem.

## Voortbouwen op het huidige systeem

Het huidige systeem zal uitgebreid kunnen worden met een UI waar de reports in komen te staan. Hier kan een admin dan het report zien en als in behandeling markeren.
Als een report in behandeling is zien de andere admins dit ook. Zo kan er niet onnodig werk worden verricht. 

Een implementatie keuze zou zijn om ook knoppen als "TP naar indiener" en andere veel voorkomende handelingen toe te voegen.
Ook zou er een chat functie gemaakt kunnen worden waarmee snel info kan worden uitgewisseld.

Reports die langer dan een X aantal minuten niet zijn behandeld zullen een opvallende kleur moeten krijgen en voorrang moeten hebben op andere reports. Hierbij moet er wel een optie moeten zijn om een report als ongegrond te moeten markeren. deze zal dan uit het overzicht verdwijnen.

## Een nieuw systeem

Onderzoeken of er een beter systeem kant en klaar is of met kleine aanpassingen aan de wensen van Tedeapolis kan voldoen.

## Randvoorwaarden

* Het systeem moet duidelijk aangeven als een report langer dan X minuten open staat
* Er moet een optie zijn om reports te markeren als onnodig
* Elk report zal behandeld moeten worden (dit door middel van een kleur en aandacht)

### Optioneel

* een chat functie waar de betrokken partij en andere admins kunnen zien wat er gezegd wordt
* UI moet intuïtief zijn. Het moet duidelijk zijn wat je kan en moet doen.

### Technisch

* Reports moeten geloged worden zo ook als het uitgebreider is met metric mogelijkheden
* Zero trust front-end (alle input moet gevalideerd worden wat naar de db gaat)
* Moet voldoen aan de code standaarden van Tedeapolis

## Stappen voor implementatie

- [x] Onderzoek naar of er bestaande oplossingen zijn
- [x] Ontwerpen UI nieuw systeem indien nodig
- [x] Implementatie
- [x] #1056

**Comment by Vayenn** [comment]
Het zou handig kunnen zijn als je dit Menu als een key binding hebt dat je Bijvoorbeeld: 9 drukt dat je het menu krijgt ( Wat ook zo is ) maar als je dan nogmaals 9 drukt dat het dan ook weer verdwijnt.

**Comment by timfloors** [comment]
> Het zou handig kunnen zijn als je dit Menu als een key binding hebt dat je Bijvoorbeeld: 9 drukt dat je het menu krijgt ( Wat ook zo is ) maar als je dan nogmaals 9 drukt dat het dan ook weer verdwijnt.

kan je dat niet doen d.m.v. in f8 -> bind 9 reportslisted

**Comment by Chang-nl** [comment]
Ik kan hem wel toevoegen in de keybinds onder fivem en dan laat ik de knop leeg zodat je hem zelf kunt invullen.

**Comment by AdventurePandah** [comment]
Suggesties:

**Report website**
- Ipv ingame UI een website maken. Voor de mensen met 2 schermen is dit ideaal. Links een scherm met alle reports met daarbij de acties en rechts gewoon je game bijvoorbeeld.

Momenteel is het namelijk zo dat als je een report opent, deze alleen op in behandeling staat als je het UI open hebt. Als je de speler daadwerkelijk gaat helpen moet je de UI sluiten en dan staat de report weer open. Als je dan weer terug wilt gaan naar de report waar je mee bezig was moet je altijd even zoeken aangezien er veel reports binnenkomen

**Extra opties**
Meer opties toevoegen zoals
    - Teleporteer speler naar waypoint
    - Spectate speler
    - Actieve voertuigen van spelers (met daarbij een UI om een voertuig te despawnen)
    - .... ?

**Verlopen van oude reports**
Als iemand een probleem heeft en het probleem is nog niet opgelost, blijft deze persoon om de 5-10 minuten (of vaker) een report versturen. Daarom denk ik dat het handig is om oude verlopen reports automatisch te archiveren / te verwijderen. Bwv, als de speler voor 10 minuten lang geen report meer heeft gestuurd -> report archiveren.

**Comment by Chang-nl** [comment]
Deze close ik voor nu aangezien het script nu decent werkt. Werken er dingen niet fatsoenlijk of heb je issues/feedback betreffende het script maak dan een aparte issue aan.
