### ISSUE TITLE
[Bug]: Accessoires menu 

### ISSUE THREAD

**Issue by AaranDejager** [Tedeapolis/development#993]
### Wat gebeurde er?

Er is een nieuwe feature toegevoegd waardoor je alleen je accessoires (zoals masker, helm etc) aan kan doen als je voertuig stil staat. Echter als je dit momenteel rijdend doet sta je instant stil.

### Wat hoorde er te gebueren?

Het niet mogelijk maken om accessoires aan te doen als je aan het rijden bent in plaats van dat je instant stil staat.

### Wat veroorzaakt de bug?

Tijdens het rijden in een voertuig druk je op K en kies je 1 van je accessoires en drukt op enter. Op dat moment sta je binnen 0.5 seconde stil.

### Wat de impact van deze bug?

hoog

**Comment by niekschoemaker** [comment]
Is gefixed
