### ISSUE TITLE
[Bug]: screen kill effects

### ISSUE THREAD

**Issue by Ljosfari** [Tedeapolis/development#995]
### Wat gebeurde er?

instellingen > display > screen kill effects een instelling kan aanzetten en je hiermee een effect hebt zodra je iemand dood schiet. 
Je ziet hierdoor meteen of iemand dood is. soort van confirmatie.

**Comment by AdventurePandah** [comment]
Kan gedisabled worden door in de server.cfg het volgende toe te voegen: `setr profile_skfx 0`
0 = Uit
1 = Aan

Bron: https://forum.cfx.re/t/disable-kill-confirmation-and-screen-blink/1920827/3

**Comment by niekschoemaker** [comment]
> 

Hebben we er al in zitten idd. Maar blijkbaar kun je de setting dan nog wel aan passen.

**Comment by niekschoemaker** [comment]
Tenzij iemand anders hie rene oplossing voor heeft is dit op het moment niet te fixen voor zover ik weet.
