### ISSUE TITLE
Offroaders staan bijna instand stil als je met een wiel zand of gras raakt

### ISSUE THREAD

**Issue by FreddyKrueger2021** [Tedeapolis/development#996]
### Contact Details

[TDA] Freddy K#1026

### Wat gebeurde er?

Ik heb met mijn raptor het probleem als ik met een wiel zand of gras raak hij bijna instand stil staat, maar als iemand anders er dan in gaat rijden dan kan het wel normaal en als ik dan weer het stuur overneem doet ie hetzelfde probleem, ik weet niet welke offroaders er last van hebben

### Wat hoorde er te gebueren?

normaal moet de raptor gewoon offroad kunnen

### Wat veroorzaakt de bug?

Geen idee

### Wat de impact van deze bug?

laag

**Comment by Ljosfari** [comment]
Bug lijkt weer terug te zijn . Zijn meerdere tickets over geopend

**Comment by Ljosfari** [comment]
Lijkt alleen een issue te zijn bij de Kamacho ?

**Comment by Ljosfari** [comment]
Deze issue lijkt zich nu ook voor te doen met meerdere voertuigen. O.a admin car
