### ISSUE TITLE
[Bug]: Lightbars werken niet volledig correct

### ISSUE THREAD

**Issue by TDA-SanderD** [Tedeapolis/development#997]
### Contact Details

Lamine#4904

### Wat gebeurde er?

Als je in de stad komt en in dienst of uit dienst staat (natuurlijk met de juiste lightbar permissies), kun je in eerste instantie geen gebruik maken van enig command gerelateerd aan het lightbarscript. 

Om hiervan gebruik te maken, moet je eerst uitklokken en weer inklokken. Daarna werkt het weer. 

### Wat hoorde er te gebueren?

Het lightbarscript hoort gelijk te werken als je in-game komt, zowel als je in-dienst als uit-dienst bent.

### Wat veroorzaakt de bug?

1. Jezelf de DSI-rang geven
2. Jezelf in dienst zetten
3. Uitloggen en vervolgens weer connecten
4. Proberen om het lightbarscript te gebruiken door middel van /loadlightbars of /lightbars.

### Wat de impact van deze bug?

laag

### Relevante log bestanden

N.v.t.

**Comment by Ljosfari** [comment]
Is aangepast
