### ISSUE TITLE
[FEATURE]: Taximeter automatisch aanzetten in normale auto als medewerker in dienst is

### ISSUE THREAD

**Issue by TedeaTaxi** [Tedeapolis/development#998]
### Contact Details

Geertje123#2163

### Beschrijf zo duidelijk mogelijk de feature

Check of the persoon taxi indienst is, en zo ja, zet automatisch de taximeter aan als de persoon in de bestuurdersstoel stapt.

### Wat lost deze feature op?

Als je een standaard taxiauto uit de garage pakt bij het taxikantoor staat de meter automatisch aan.
Als je met de taxi in een privéauto rijdt (Uber, Managers, etc) dan moet je altijd eerst via /taxi de meter aanzetten.
De extra handelingen die je elke keer moet verrichten als je taxichauffeur bent zijn inefficiënt en vervelend. En dit is een logische feature, omdat als je indienst in een auto rijdt, je vrijwel altijd bezig bent met ritjes.

Default aan is dus logischer dan default uit.

**Comment by Ljosfari** [comment]
Is afgewezen
